{
  "abstract": [
    {
      "text": "A view controller that displays an interface for picking contacts.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Contacts-UI/documentation/ContactsUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CNContactPickerViewController",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CNContactPickerViewController"
      }
    ],
    "modules": [
      {
        "name": "Contacts UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CNContactPickerViewController"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CNContactPickerViewController"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNContactPickerViewController"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " allows the user to select one or more",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "contacts (or their properties) from the list of contacts displayed in the contact",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "view controller (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "). The picker supports both",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "single selection and multiselection of the contacts. The app using contact picker",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "view does not need access to the user’s contacts and the user will not be prompted",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "for “grant permission” access. The app has access only to the user’s final selection.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "There are predefined predicates in this class that let you control the user selection",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of the contact. Changing the predicates only take effect before the view is presented.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Contacts-UI/documentation/ContactsUI": {
      "abstract": [
        {
          "text": "Provide an interface that allows people to display information about their",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts UI",
      "type": "topic",
      "url": "/documentation/contactsui"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPicker": {
      "abstract": [
        {
          "text": "A popover-based interface for selecting a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactPicker"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPicker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactPicker"
        }
      ],
      "role": "symbol",
      "title": "CNContactPicker",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactpicker"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate": {
      "abstract": [
        {
          "text": "The methods that you implement to respond to contact-picker user events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactPickerDelegate"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactPickerDelegate"
        }
      ],
      "role": "symbol",
      "title": "CNContactPickerDelegate",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactpickerdelegate"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController": {
      "abstract": [
        {
          "text": "A view controller that displays an interface for picking contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactPickerViewController"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactPickerViewController"
        }
      ],
      "role": "symbol",
      "title": "CNContactPickerViewController",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactpickerviewcontroller"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/delegate": {
      "abstract": [
        {
          "text": "The delegate to be notified when the user selects a contact or a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CNContactPickerDelegate",
          "text": "CNContactPickerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactpickerviewcontroller/delegate"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/displayedPropertyKeys": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/Contacts/CNContact",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property keys",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "to display in the contact detail card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayedPropertyKeys"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/displayedPropertyKeys",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayedPropertyKeys"
        }
      ],
      "role": "symbol",
      "title": "displayedPropertyKeys",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactpickerviewcontroller/displayedpropertykeys"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/predicateForEnablingContact": {
      "abstract": [
        {
          "text": "A predicate to determine the contact selectability in the list of contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForEnablingContact"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/predicateForEnablingContact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForEnablingContact"
        }
      ],
      "role": "symbol",
      "title": "predicateForEnablingContact",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactpickerviewcontroller/predicateforenablingcontact"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/predicateForSelectionOfContact": {
      "abstract": [
        {
          "text": "A predicate to control the return of the selected contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForSelectionOfContact"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/predicateForSelectionOfContact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForSelectionOfContact"
        }
      ],
      "role": "symbol",
      "title": "predicateForSelectionOfContact",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactpickerviewcontroller/predicateforselectionofcontact"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/predicateForSelectionOfProperty": {
      "abstract": [
        {
          "text": "A predicate to control the properties of the selected contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForSelectionOfProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/predicateForSelectionOfProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForSelectionOfProperty"
        }
      ],
      "role": "symbol",
      "title": "predicateForSelectionOfProperty",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactpickerviewcontroller/predicateforselectionofproperty"
    },
    "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController": {
      "abstract": [
        {
          "text": "A view controller that displays a new, unknown, or existing contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContactViewController"
        }
      ],
      "identifier": "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNContactViewController"
        }
      ],
      "role": "symbol",
      "title": "CNContactViewController",
      "type": "topic",
      "url": "/documentation/contactsui/cncontactviewcontroller"
    },
    "doc://com.apple.documentation/documentation/Contacts/CNContact": {
      "abstract": [
        {
          "text": "An immutable object that stores information about a single contact, such as the contact’s first name, phone numbers, and addresses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNContact"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Contacts/CNContact",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNContact",
      "type": "topic",
      "url": "/documentation/Contacts/CNContact"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)UIViewController": {
      "abstract": [
        {
          "text": "An object that manages a view hierarchy for your UIKit app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIViewController",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIViewController",
      "type": "topic",
      "url": "/documentation/UIKit/UIViewController"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling": {
      "abstract": [
        {
          "text": "The interface an app extension uses to respond to a request from a host app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSExtensionRequestHandling"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtensionRequestHandling",
      "type": "topic",
      "url": "/documentation/foundation/nsextensionrequesthandling"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider": {
      "abstract": [
        {
          "text": "A protocol that an object adopts to create a bar object in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarProvider"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTouchBarProvider",
      "type": "topic",
      "url": "/documentation/AppKit/NSTouchBarProvider"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIActivityItemsConfigurationProviding": {
      "abstract": [
        {
          "text": "An interface that provides a source for shareable content to fulfill user requests to share current content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationProviding"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIActivityItemsConfigurationProviding",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIActivityItemsConfigurationProviding",
      "type": "topic",
      "url": "/documentation/UIKit/UIActivityItemsConfigurationProviding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIAppearanceContainer": {
      "abstract": [
        {
          "text": "A protocol that a class must adopt to allow appearance customization using the [`UIAppearance`](doc://com.apple.uikit/documentation/UIKit/UIAppearance) API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAppearanceContainer"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIAppearanceContainer",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAppearanceContainer",
      "type": "topic",
      "url": "/documentation/UIKit/UIAppearanceContainer"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIContentContainer": {
      "abstract": [
        {
          "text": "A set of methods for adapting the contents of your view controllers to size and trait changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentContainer"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIContentContainer",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentContainer",
      "type": "topic",
      "url": "/documentation/UIKit/UIContentContainer"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that define the focus behavior for a branch of the view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFocusEnvironment"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusEnvironment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIFocusEnvironment",
      "type": "topic",
      "url": "/documentation/UIKit/UIFocusEnvironment"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIPasteConfigurationSupporting": {
      "abstract": [
        {
          "text": "The interface that determines whether a responder object supports paste configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPasteConfigurationSupporting"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIPasteConfigurationSupporting",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPasteConfigurationSupporting",
      "type": "topic",
      "url": "/documentation/UIKit/UIPasteConfigurationSupporting"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIResponderStandardEditActions": {
      "abstract": [
        {
          "text": "A set of standard methods that apps can adopt to support editing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIResponderStandardEditActions"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIResponderStandardEditActions",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIResponderStandardEditActions",
      "type": "topic",
      "url": "/documentation/UIKit/UIResponderStandardEditActions"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIStateRestoring": {
      "abstract": [
        {
          "text": "Methods for adding objects to your state restoration archives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIStateRestoring"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIStateRestoring",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIStateRestoring",
      "type": "topic",
      "url": "/documentation/UIKit/UIStateRestoring"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UITraitEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that makes the iOS interface environment available to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UITraitEnvironment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitEnvironment",
      "type": "topic",
      "url": "/documentation/UIKit/UITraitEnvironment"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIUserActivityRestoring": {
      "abstract": [
        {
          "text": "The protocol you adopt to restore an object’s state from a user activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserActivityRestoring"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIUserActivityRestoring",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIUserActivityRestoring",
      "type": "topic",
      "url": "/documentation/UIKit/UIUserActivityRestoring"
    },
    "doc://com.externally.resolved.symbol/s:5UIKit23UITraitChangeObservableP": {
      "abstract": [
        {
          "text": "A type that calls your code in reaction to changes in the trait environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:5UIKit23UITraitChangeObservableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitChangeObservable",
      "type": "topic",
      "url": "/documentation/UIKit/UITraitChangeObservable-67e94"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)UIViewController"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIActivityItemsConfigurationProviding",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIAppearanceContainer",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIContentContainer",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusEnvironment",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIPasteConfigurationSupporting",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIResponderStandardEditActions",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIStateRestoring",
        "doc://com.externally.resolved.symbol/s:5UIKit23UITraitChangeObservableP",
        "doc://com.externally.resolved.symbol/c:objc(pl)UITraitEnvironment",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIUserActivityRestoring"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Contact-pickers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPicker"
      ],
      "title": "Contact pickers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Displaying-Contacts-Properties",
      "identifiers": [
        "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/displayedPropertyKeys"
      ],
      "title": "Displaying Contacts Properties"
    },
    {
      "anchor": "Responding-to-User-Interactions",
      "identifiers": [
        "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/delegate",
        "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate"
      ],
      "title": "Responding to User Interactions"
    },
    {
      "anchor": "Predicates-For-Selecting-Contacts",
      "identifiers": [
        "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/predicateForEnablingContact",
        "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/predicateForSelectionOfContact",
        "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/predicateForSelectionOfProperty"
      ],
      "title": "Predicates For Selecting Contacts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CNContactPickerViewController"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Contacts-UI/documentation/ContactsUI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Displaying-Contacts-Properties",
              "identifiers": [
                "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/displayedPropertyKeys"
              ],
              "title": "Displaying Contacts Properties"
            },
            {
              "anchor": "Responding-to-User-Interactions",
              "identifiers": [
                "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/delegate",
                "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerDelegate"
              ],
              "title": "Responding to User Interactions"
            },
            {
              "anchor": "Predicates-For-Selecting-Contacts",
              "identifiers": [
                "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/predicateForEnablingContact",
                "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/predicateForSelectionOfContact",
                "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPickerViewController/predicateForSelectionOfProperty"
              ],
              "title": "Predicates For Selecting Contacts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)UIViewController"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Contact-pickers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Contacts-UI/documentation/ContactsUI/CNContactPicker"
              ],
              "title": "Contact pickers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CNContactPickerViewController"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIViewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIViewController",
                    "text": "UIViewController"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPicker/title",
          "value": "CNContactPicker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPicker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPicker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController/title",
          "value": "CNContactViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIUserActivityRestoring/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIUserActivityRestoring"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate/title",
          "value": "CNContactPickerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPickerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPickerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIPasteConfigurationSupporting/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPasteConfigurationSupporting"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController~1predicateForSelectionOfProperty/title",
          "value": "predicateForSelectionOfProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController~1predicateForSelectionOfProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "predicateForSelectionOfProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIResponderStandardEditActions/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIResponderStandardEditActions"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIAppearanceContainer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIAppearanceContainer"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController/title",
          "value": "CNContactPickerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNContactPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)UIViewController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIViewController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIResponder",
              "text": "UIResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSTouchBarProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTouchBarProvider"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Contacts~1CNContact/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CNContact"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UITraitEnvironment/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController~1predicateForEnablingContact/title",
          "value": "predicateForEnablingContact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController~1predicateForEnablingContact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "predicateForEnablingContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController~1predicateForSelectionOfContact/title",
          "value": "predicateForSelectionOfContact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController~1predicateForSelectionOfContact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "predicateForSelectionOfContact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIActivityItemsConfigurationProviding/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationProviding"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController~1displayedPropertyKeys/title",
          "value": "displayedPropertyKeys"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Contacts-UI~1documentation~1ContactsUI~1CNContactPickerViewController~1displayedPropertyKeys/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayedPropertyKeys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIStateRestoring/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIStateRestoring"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIFocusEnvironment/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIFocusEnvironment"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIContentContainer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIContentContainer"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contactsui/cncontactpickerviewcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contactsui/cncontactpickerviewcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
