{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kLABiometryTypeOpticID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"modules":[{"name":"Local Authentication"}],"externalID":"c:@macro@kLABiometryTypeOpticID","navigatorTitle":[{"kind":"identifier","text":"kLABiometryTypeOpticID"}],"role":"symbol","title":"kLABiometryTypeOpticID","platforms":[{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"8.0","name":"iOS"},{"unavailable":false,"introducedAt":"8.0","deprecated":false,"name":"iPadOS","beta":false},{"unavailable":false,"introducedAt":"13.0","deprecated":false,"name":"Mac Catalyst","beta":false},{"unavailable":false,"introducedAt":"10.10","deprecated":false,"name":"macOS","beta":false},{"name":"visionOS","introducedAt":"1.0","beta":false,"deprecated":false,"unavailable":false},{"name":"watchOS","introducedAt":"9.0","beta":false,"deprecated":false,"unavailable":false}],"symbolKind":"var","roleHeading":"Global Variable"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.localauthentication/documentation/LocalAuthentication"]]},"kind":"symbol","sections":[],"seeAlsoSections":[{"generated":true,"anchor":"Constants","identifiers":["doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeFaceID","doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeNone","doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeTouchID"],"title":"Constants"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kLABiometryTypeOpticID","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"]}]}],"variants":[{"paths":["/documentation/localauthentication/klabiometrytypeopticid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/localauthentication/klabiometrytypeopticid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeOpticID","interfaceLanguage":"swift"},"references":{"doc://com.apple.localauthentication/documentation/LocalAuthentication":{"kind":"symbol","abstract":[{"type":"text","text":"Authenticate users biometrically or with a passphrase they already know."}],"url":"/documentation/localauthentication","role":"collection","title":"Local Authentication","identifier":"doc://com.apple.localauthentication/documentation/LocalAuthentication","type":"topic"},"doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeTouchID":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kLABiometryTypeTouchID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"url":"/documentation/localauthentication/klabiometrytypetouchid","abstract":[],"role":"symbol","title":"kLABiometryTypeTouchID","type":"topic","identifier":"doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeTouchID","navigatorTitle":[{"kind":"identifier","text":"kLABiometryTypeTouchID"}]},"doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeFaceID":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kLABiometryTypeFaceID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"role":"symbol","identifier":"doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeFaceID","url":"/documentation/localauthentication/klabiometrytypefaceid","navigatorTitle":[{"kind":"identifier","text":"kLABiometryTypeFaceID"}],"kind":"symbol","title":"kLABiometryTypeFaceID","abstract":[]},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","title":"Technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","role":"overview"},"doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeOpticID":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kLABiometryTypeOpticID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"role":"symbol","identifier":"doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeOpticID","url":"/documentation/localauthentication/klabiometrytypeopticid","navigatorTitle":[{"kind":"identifier","text":"kLABiometryTypeOpticID"}],"kind":"symbol","title":"kLABiometryTypeOpticID","abstract":[]},"doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeNone":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kLABiometryTypeNone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"kind":"identifier","text":"kLABiometryTypeNone"}],"kind":"symbol","title":"kLABiometryTypeNone","role":"symbol","abstract":[],"identifier":"doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeNone","type":"topic","url":"/documentation/localauthentication/klabiometrytypenone"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","abstract":[{"type":"text","text":"A 32-bit signed integer value type."}],"title":"Int32","url":"/documentation/Swift/Int32"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"name":"iOS","unavailable":false,"introducedAt":"8.0","deprecated":false,"beta":false},{"name":"iPadOS","unavailable":false,"introducedAt":"8.0","deprecated":false,"beta":false},{"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.0","deprecated":false,"beta":false},{"name":"macOS","unavailable":false,"introducedAt":"10.10","deprecated":false,"beta":false},{"name":"visionOS","unavailable":false,"introducedAt":"1.0","deprecated":false,"beta":false},{"name":"watchOS","introducedAt":"9.0","beta":false,"deprecated":false,"unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Macro","op":"replace"},{"path":"/metadata/title","value":"kLABiometryTypeOpticID","op":"replace"},{"path":"/metadata/symbolKind","value":"macro","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"kLABiometryTypeOpticID"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.localauthentication/documentation/LocalAuthentication"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Constants","generated":true,"anchor":"Constants","identifiers":["doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeFaceID","doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeNone","doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeTouchID"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kLABiometryTypeOpticID","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLABiometryTypeTouchID/title","value":"kLABiometryTypeTouchID"},{"op":"replace","path":"/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLABiometryTypeTouchID/fragments","value":[{"text":"kLABiometryTypeTouchID","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLABiometryTypeFaceID/title","value":"kLABiometryTypeFaceID"},{"op":"replace","path":"/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLABiometryTypeFaceID/fragments","value":[{"text":"kLABiometryTypeFaceID","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLABiometryTypeOpticID/title","value":"kLABiometryTypeOpticID"},{"op":"replace","path":"/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLABiometryTypeOpticID/fragments","value":[{"text":"kLABiometryTypeOpticID","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLABiometryTypeNone/title","value":"kLABiometryTypeNone"},{"op":"replace","path":"/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLABiometryTypeNone/fragments","value":[{"kind":"identifier","text":"kLABiometryTypeNone"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}