{
  "abstract": [
    {
      "text": "An attempt to authenticate with Apple Watch failed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorWatchNotAvailable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@kLAErrorWatchNotAvailable",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kLAErrorWatchNotAvailable"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "Local Authentication"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kLAErrorWatchNotAvailable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kLAErrorWatchNotAvailable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kLAErrorWatchNotAvailable"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You receive this error when the system fails to locate a nearby, paired Apple Watch running watchOS 6 or later while trying to authenticate using one of the watch authentication policies like ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithWatch",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication": {
      "abstract": [
        {
          "text": "Authenticate users biometrically or with a passphrase they already know.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication",
      "kind": "symbol",
      "role": "collection",
      "title": "Local Authentication",
      "type": "topic",
      "url": "/documentation/localauthentication"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithWatch": {
      "abstract": [
        {
          "text": "User authentication with Apple Watch.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceOwnerAuthenticationWithWatch"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithWatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAPolicyDeviceOwnerAuthenticationWithWatch"
        }
      ],
      "role": "symbol",
      "title": "LAPolicy.deviceOwnerAuthenticationWithWatch",
      "type": "topic",
      "url": "/documentation/localauthentication/lapolicy/deviceownerauthenticationwithwatch"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorAppCancel": {
      "abstract": [
        {
          "text": "The app canceled authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorAppCancel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorAppCancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorAppCancel"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorAppCancel",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorappcancel"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorAuthenticationFailed": {
      "abstract": [
        {
          "text": "The user failed to provide valid credentials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorAuthenticationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorAuthenticationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorAuthenticationFailed"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorAuthenticationFailed",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorauthenticationfailed"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryDisconnected": {
      "abstract": [
        {
          "text": "The device supports biometry only using a removable accessory, but the paired accessory isn’t connected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryDisconnected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryDisconnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryDisconnected"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorBiometryDisconnected",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorbiometrydisconnected"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryLockout": {
      "abstract": [
        {
          "text": "Biometry is locked because there were too many failed attempts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryLockout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryLockout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryLockout"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorBiometryLockout",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorbiometrylockout"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotAvailable": {
      "abstract": [
        {
          "text": "Biometry is not available on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorBiometryNotAvailable",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorbiometrynotavailable"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotEnrolled": {
      "abstract": [
        {
          "text": "The user has no enrolled biometric identities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryNotEnrolled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotEnrolled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryNotEnrolled"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorBiometryNotEnrolled",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorbiometrynotenrolled"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotPaired": {
      "abstract": [
        {
          "text": "The device supports biometry only using a removable accessory, but no accessory is paired.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryNotPaired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotPaired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryNotPaired"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorBiometryNotPaired",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorbiometrynotpaired"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorDomain": {
      "abstract": [
        {
          "text": "The error domain used by LocalAuthentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorDomain",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrordomain"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorInvalidContext": {
      "abstract": [
        {
          "text": "The context was previously invalidated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorInvalidContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorInvalidContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorInvalidContext"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorInvalidContext",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorinvalidcontext"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorInvalidDimensions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorInvalidDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorInvalidDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorInvalidDimensions"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorInvalidDimensions",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorinvaliddimensions"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorSystemCancel": {
      "abstract": [
        {
          "text": "The system canceled authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorSystemCancel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorSystemCancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorSystemCancel"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorSystemCancel",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorsystemcancel"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDLockout": {
      "abstract": [
        {
          "text": "Touch ID is locked because there were too many failed attempts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorTouchIDLockout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDLockout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorTouchIDLockout"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorTouchIDLockout",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrortouchidlockout"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDNotAvailable": {
      "abstract": [
        {
          "text": "Touch ID is not available on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorTouchIDNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorTouchIDNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorTouchIDNotAvailable",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrortouchidnotavailable"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDNotEnrolled": {
      "abstract": [
        {
          "text": "The user has no enrolled Touch ID fingers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorTouchIDNotEnrolled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDNotEnrolled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorTouchIDNotEnrolled"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorTouchIDNotEnrolled",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrortouchidnotenrolled"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorUserCancel": {
      "abstract": [
        {
          "text": "The user tapped the cancel button in the authentication dialog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorUserCancel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorUserCancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorUserCancel"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorUserCancel",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorusercancel"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorWatchNotAvailable": {
      "abstract": [
        {
          "text": "An attempt to authenticate with Apple Watch failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorWatchNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorWatchNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorWatchNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorWatchNotAvailable",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorwatchnotavailable"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Supporting-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorDomain",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorAppCancel",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorSystemCancel",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorUserCancel",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryDisconnected",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryLockout",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotAvailable",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotEnrolled",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotPaired",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDLockout",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDNotAvailable",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDNotEnrolled",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorAuthenticationFailed",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorInvalidContext",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorInvalidDimensions"
      ],
      "title": "Supporting Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kLAErrorWatchNotAvailable"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorWatchNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Supporting-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorDomain",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorAppCancel",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorSystemCancel",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorUserCancel",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryDisconnected",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryLockout",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotAvailable",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotEnrolled",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotPaired",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDLockout",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDNotAvailable",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDNotEnrolled",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorAuthenticationFailed",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorInvalidContext",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorInvalidDimensions"
              ],
              "title": "Supporting Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kLAErrorWatchNotAvailable"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorUserCancel/title",
          "value": "kLAErrorUserCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorUserCancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorUserCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorAuthenticationFailed/title",
          "value": "kLAErrorAuthenticationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorAuthenticationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorAuthenticationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorWatchNotAvailable/title",
          "value": "kLAErrorWatchNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorWatchNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorWatchNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorTouchIDNotAvailable/title",
          "value": "kLAErrorTouchIDNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorTouchIDNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorTouchIDNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryNotAvailable/title",
          "value": "kLAErrorBiometryNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorBiometryNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryNotPaired/title",
          "value": "kLAErrorBiometryNotPaired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryNotPaired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorBiometryNotPaired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryDisconnected/title",
          "value": "kLAErrorBiometryDisconnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryDisconnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorBiometryDisconnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorSystemCancel/title",
          "value": "kLAErrorSystemCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorSystemCancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorSystemCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorInvalidDimensions/title",
          "value": "kLAErrorInvalidDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorInvalidDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorInvalidDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorAppCancel/title",
          "value": "kLAErrorAppCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorAppCancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorAppCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryNotEnrolled/title",
          "value": "kLAErrorBiometryNotEnrolled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryNotEnrolled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorBiometryNotEnrolled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy~1deviceOwnerAuthenticationWithWatch/title",
          "value": "LAPolicyDeviceOwnerAuthenticationWithWatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy~1deviceOwnerAuthenticationWithWatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAPolicyDeviceOwnerAuthenticationWithWatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryLockout/title",
          "value": "kLAErrorBiometryLockout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryLockout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorBiometryLockout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorTouchIDNotEnrolled/title",
          "value": "kLAErrorTouchIDNotEnrolled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorTouchIDNotEnrolled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorTouchIDNotEnrolled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorDomain/title",
          "value": "kLAErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorTouchIDLockout/title",
          "value": "kLAErrorTouchIDLockout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorTouchIDLockout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorTouchIDLockout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorInvalidContext/title",
          "value": "kLAErrorInvalidContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorInvalidContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorInvalidContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/localauthentication/klaerrorwatchnotavailable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/localauthentication/klaerrorwatchnotavailable"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
