{
  "abstract": [
    {
      "text": "A mechanism for evaluating authentication policies and access controls.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)LAContext",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "LAContext"
      }
    ],
    "modules": [
      {
        "name": "Local Authentication"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LAContext"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "LAContext"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "LAContext"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You use an authentication context to evaluate the user’s identity, either with biometrics like Touch ID or Face ID, or by supplying the device passcode. The context handles user interaction, and also interfaces to the Secure Enclave, the underlying hardware element that manages biometric data. You create and configure the context, and ask it to carry out the authentication. You then receive an asynchronous callback, which provides an indication of authentication success or failure, and an error instance that explains the reason for a failure, if any.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Include the ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW75",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " key in your app’s ",
                  "type": "text"
                },
                {
                  "code": "Info.plist",
                  "type": "codeVoice"
                },
                {
                  "text": " file if your app allows biometric authentication. Otherwise, authorization requests may fail.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication": {
      "abstract": [
        {
          "text": "Authenticate users biometrically or with a passphrase they already know.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication",
      "kind": "symbol",
      "role": "collection",
      "title": "Local Authentication",
      "type": "topic",
      "url": "/documentation/localauthentication"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation": {
      "abstract": [
        {
          "text": "Operations to be evaluated for access control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LAAccessControlOperation"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAAccessControlOperation"
        }
      ],
      "role": "symbol",
      "title": "LAAccessControlOperation",
      "type": "topic",
      "url": "/documentation/localauthentication/laaccesscontroloperation"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType": {
      "abstract": [
        {
          "text": "The set of available biometric authentication types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LABiometryType"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LABiometryType"
        }
      ],
      "role": "symbol",
      "title": "LABiometryType",
      "type": "topic",
      "url": "/documentation/localauthentication/labiometrytype"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext": {
      "abstract": [
        {
          "text": "A mechanism for evaluating authentication policies and access controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LAContext"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAContext"
        }
      ],
      "role": "symbol",
      "title": "LAContext",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/biometryType": {
      "abstract": [
        {
          "text": "The type of biometric authentication supported by the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometryType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LABiometryType",
          "text": "LABiometryType"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/biometryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "biometryType"
        }
      ],
      "role": "symbol",
      "title": "biometryType",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/biometrytype"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/canEvaluatePolicy(_:error:)": {
      "abstract": [
        {
          "text": "Assesses whether authentication can proceed for a given policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canEvaluatePolicy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAPolicy",
          "text": "LAPolicy"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14NSErrorPointera",
          "text": "NSErrorPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/canEvaluatePolicy(_:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canEvaluatePolicy:error:"
        }
      ],
      "role": "symbol",
      "title": "canEvaluatePolicy(_:error:)",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/canevaluatepolicy(_:error:)"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/domainState": {
      "abstract": [
        {
          "text": "Contains authentication domain state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "domainState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)LADomainState",
          "text": "LADomainState"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/domainState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "domainState"
        }
      ],
      "role": "symbol",
      "title": "domainState",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/domainstate"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/evaluateAccessControl(_:operation:localizedReason:reply:)": {
      "abstract": [
        {
          "text": "Evaluates an access control for a given operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evaluateAccessControl"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SecAccessControlRef",
          "text": "SecAccessControl"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "operation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAAccessControlOperation",
          "text": "LAAccessControlOperation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "localizedReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reply"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/evaluateAccessControl(_:operation:localizedReason:reply:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "evaluateAccessControl:operation:localizedReason:reply:"
        }
      ],
      "role": "symbol",
      "title": "evaluateAccessControl(_:operation:localizedReason:reply:)",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/evaluateaccesscontrol(_:operation:localizedreason:reply:)"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/evaluatePolicy(_:localizedReason:reply:)": {
      "abstract": [
        {
          "text": "Evaluates the specified policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evaluatePolicy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAPolicy",
          "text": "LAPolicy"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "localizedReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reply"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/evaluatePolicy(_:localizedReason:reply:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "evaluatePolicy:localizedReason:reply:"
        }
      ],
      "role": "symbol",
      "title": "evaluatePolicy(_:localizedReason:reply:)",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/evaluatepolicy(_:localizedreason:reply:)"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/evaluatedPolicyDomainState": {
      "abstract": [
        {
          "text": "The current state of the evaluated policy domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evaluatedPolicyDomainState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/evaluatedPolicyDomainState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "evaluatedPolicyDomainState"
        }
      ],
      "role": "symbol",
      "title": "evaluatedPolicyDomainState",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/evaluatedpolicydomainstate"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/interactionNotAllowed": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether authentication can be interactive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interactionNotAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/interactionNotAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interactionNotAllowed"
        }
      ],
      "role": "symbol",
      "title": "interactionNotAllowed",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/interactionnotallowed"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/invalidate()": {
      "abstract": [
        {
          "text": "Invalidates the authentication context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidate"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/invalidate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidate"
        }
      ],
      "role": "symbol",
      "title": "invalidate()",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/invalidate()"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/isCredentialSet(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the specified credential type is set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isCredentialSet"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LACredentialType",
          "text": "LACredentialType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/isCredentialSet(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isCredentialSet:"
        }
      ],
      "role": "symbol",
      "title": "isCredentialSet(_:)",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/iscredentialset(_:)"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedCancelTitle": {
      "abstract": [
        {
          "text": "The localized title for the cancel button in the dialog presented to the user during authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedCancelTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedCancelTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedCancelTitle"
        }
      ],
      "role": "symbol",
      "title": "localizedCancelTitle",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/localizedcanceltitle"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedFallbackTitle": {
      "abstract": [
        {
          "text": "The localized title for the fallback button in the dialog presented to the user during authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedFallbackTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedFallbackTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedFallbackTitle"
        }
      ],
      "role": "symbol",
      "title": "localizedFallbackTitle",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/localizedfallbacktitle"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedReason": {
      "abstract": [
        {
          "text": "The localized explanation for authentication shown in the dialog presented to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedReason"
        }
      ],
      "role": "symbol",
      "title": "localizedReason",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/localizedreason"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/maxBiometryFailures": {
      "abstract": [
        {
          "text": "The number of biometric authentication failures after which the context falls back to another mechanism.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxBiometryFailures"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/maxBiometryFailures",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxBiometryFailures"
        }
      ],
      "role": "symbol",
      "title": "maxBiometryFailures",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/maxbiometryfailures"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/setCredential(_:type:)": {
      "abstract": [
        {
          "text": "Sets an application-provided credential to be used when evaluating authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setCredential"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LACredentialType",
          "text": "LACredentialType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/setCredential(_:type:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setCredential:type:"
        }
      ],
      "role": "symbol",
      "title": "setCredential(_:type:)",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/setcredential(_:type:)"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/touchIDAuthenticationAllowableReuseDuration": {
      "abstract": [
        {
          "text": "The duration for which Touch ID authentication reuse is allowable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchIDAuthenticationAllowableReuseDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/touchIDAuthenticationAllowableReuseDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "touchIDAuthenticationAllowableReuseDuration"
        }
      ],
      "role": "symbol",
      "title": "touchIDAuthenticationAllowableReuseDuration",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/touchidauthenticationallowablereuseduration"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LACredentialType": {
      "abstract": [
        {
          "text": "The types of credentials to be used for authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LACredentialType"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LACredentialType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LACredentialType"
        }
      ],
      "role": "symbol",
      "title": "LACredentialType",
      "type": "topic",
      "url": "/documentation/localauthentication/lacredentialtype"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy": {
      "abstract": [
        {
          "text": "The set of available local authentication policies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LAPolicy"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAPolicy"
        }
      ],
      "role": "symbol",
      "title": "LAPolicy",
      "type": "topic",
      "url": "/documentation/localauthentication/lapolicy"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight": {
      "abstract": [
        {
          "text": "A grouped set of requirements that gate access to a resource or operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LARight"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LARight"
        }
      ],
      "role": "symbol",
      "title": "LARight",
      "type": "topic",
      "url": "/documentation/localauthentication/laright"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum": {
      "abstract": [
        {
          "text": "The possible states for a right during authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "role": "symbol",
      "title": "LARight.State",
      "type": "topic",
      "url": "/documentation/localauthentication/laright/state-swift.enum"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LATouchIDAuthenticationMaximumAllowableReuseDuration": {
      "abstract": [
        {
          "text": "The maximum allowable reuse duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LATouchIDAuthenticationMaximumAllowableReuseDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LATouchIDAuthenticationMaximumAllowableReuseDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LATouchIDAuthenticationMaximumAllowableReuseDuration"
        }
      ],
      "role": "symbol",
      "title": "LATouchIDAuthenticationMaximumAllowableReuseDuration",
      "type": "topic",
      "url": "/documentation/localauthentication/latouchidauthenticationmaximumallowablereuseduration"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:11Observation10ObservableP": {
      "abstract": [
        {
          "text": "A type that emits notifications to observers when underlying data changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Observable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:11Observation10ObservableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Observable",
      "type": "topic",
      "url": "/documentation/Observation/Observable"
    },
    "doc://com.externally.resolved.symbol/s:7Combine16ObservableObjectP": {
      "abstract": [
        {
          "text": "A type of object with a publisher that emits before the object has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ObservableObject"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7Combine16ObservableObjectP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ObservableObject",
      "type": "topic",
      "url": "/documentation/Combine/ObservableObject"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW75": {
      "identifier": "https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW75",
      "title": "NSFaceIDUsageDescription",
      "titleInlineContent": [
        {
          "text": "NSFaceIDUsageDescription",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW75"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:11Observation10ObservableP",
        "doc://com.externally.resolved.symbol/s:7Combine16ObservableObjectP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Authentication-and-access",
      "generated": true,
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum"
      ],
      "title": "Authentication and access"
    }
  ],
  "topicSections": [
    {
      "anchor": "Checking-availability",
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/canEvaluatePolicy(_:error:)",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/biometryType",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType"
      ],
      "title": "Checking availability"
    },
    {
      "anchor": "Evaluating-authentication-policies",
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/evaluatePolicy(_:localizedReason:reply:)",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/evaluatedPolicyDomainState",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/maxBiometryFailures"
      ],
      "title": "Evaluating authentication policies"
    },
    {
      "anchor": "Evaluating-access-controls",
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/evaluateAccessControl(_:operation:localizedReason:reply:)",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/interactionNotAllowed"
      ],
      "title": "Evaluating access controls"
    },
    {
      "anchor": "Customizing-authentication-prompts",
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedReason",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedFallbackTitle",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedCancelTitle"
      ],
      "title": "Customizing authentication prompts"
    },
    {
      "anchor": "Reusing-device-unlock-state",
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/touchIDAuthenticationAllowableReuseDuration",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LATouchIDAuthenticationMaximumAllowableReuseDuration"
      ],
      "title": "Reusing device unlock state"
    },
    {
      "anchor": "Managing-credentials",
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/setCredential(_:type:)",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/isCredentialSet(_:)",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LACredentialType"
      ],
      "title": "Managing credentials"
    },
    {
      "anchor": "Invalidating-the-authentication-context",
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/invalidate()"
      ],
      "title": "Invalidating the authentication context"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/domainState"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LAContext"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Checking-availability",
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/canEvaluatePolicy(_:error:)",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/biometryType",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType"
              ],
              "title": "Checking availability"
            },
            {
              "anchor": "Evaluating-authentication-policies",
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/evaluatePolicy(_:localizedReason:reply:)",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/evaluatedPolicyDomainState",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/maxBiometryFailures"
              ],
              "title": "Evaluating authentication policies"
            },
            {
              "anchor": "Evaluating-access-controls",
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/evaluateAccessControl(_:operation:localizedReason:reply:)",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAAccessControlOperation",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/interactionNotAllowed"
              ],
              "title": "Evaluating access controls"
            },
            {
              "anchor": "Customizing-authentication-prompts",
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedReason",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedFallbackTitle",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/localizedCancelTitle"
              ],
              "title": "Customizing authentication prompts"
            },
            {
              "anchor": "Reusing-device-unlock-state",
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/touchIDAuthenticationAllowableReuseDuration",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LATouchIDAuthenticationMaximumAllowableReuseDuration"
              ],
              "title": "Reusing device unlock state"
            },
            {
              "anchor": "Managing-credentials",
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/setCredential(_:type:)",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/isCredentialSet(_:)",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LACredentialType"
              ],
              "title": "Managing credentials"
            },
            {
              "anchor": "Invalidating-the-authentication-context",
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/invalidate()"
              ],
              "title": "Invalidating the authentication context"
            },
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/domainState"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Authentication-and-access",
              "generated": true,
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LARight/State-swift.enum"
              ],
              "title": "Authentication and access"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "LAContext"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1domainState/title",
          "value": "domainState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1domainState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "domainState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext/title",
          "value": "LAContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LATouchIDAuthenticationMaximumAllowableReuseDuration/title",
          "value": "LATouchIDAuthenticationMaximumAllowableReuseDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LATouchIDAuthenticationMaximumAllowableReuseDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LATouchIDAuthenticationMaximumAllowableReuseDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1touchIDAuthenticationAllowableReuseDuration/title",
          "value": "touchIDAuthenticationAllowableReuseDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1touchIDAuthenticationAllowableReuseDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "touchIDAuthenticationAllowableReuseDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy/title",
          "value": "LAPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1invalidate()/title",
          "value": "invalidate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1invalidate()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "invalidate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1setCredential(_:type:)/title",
          "value": "setCredential:type:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1setCredential(_:type:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setCredential:type:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1biometryType/title",
          "value": "biometryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1biometryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "biometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight~1State-swift.enum/title",
          "value": "LARightState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight~1State-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LARightState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight~1State-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LARightState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1isCredentialSet(_:)/title",
          "value": "isCredentialSet:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1isCredentialSet(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "isCredentialSet:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LACredentialType/title",
          "value": "LACredentialType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LACredentialType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LACredentialType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LACredentialType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LACredentialType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1canEvaluatePolicy(_:error:)/title",
          "value": "canEvaluatePolicy:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1canEvaluatePolicy(_:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canEvaluatePolicy:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1evaluateAccessControl(_:operation:localizedReason:reply:)/title",
          "value": "evaluateAccessControl:operation:localizedReason:reply:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1evaluateAccessControl(_:operation:localizedReason:reply:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "evaluateAccessControl:operation:localizedReason:reply:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1localizedCancelTitle/title",
          "value": "localizedCancelTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1localizedCancelTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedCancelTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType/title",
          "value": "LABiometryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LABiometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LABiometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAAccessControlOperation/title",
          "value": "LAAccessControlOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAAccessControlOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAAccessControlOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAAccessControlOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAAccessControlOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1maxBiometryFailures/title",
          "value": "maxBiometryFailures"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1maxBiometryFailures/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxBiometryFailures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1evaluatedPolicyDomainState/title",
          "value": "evaluatedPolicyDomainState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1evaluatedPolicyDomainState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "evaluatedPolicyDomainState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1interactionNotAllowed/title",
          "value": "interactionNotAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1interactionNotAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interactionNotAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight/title",
          "value": "LARight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LARight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LARight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LARight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1evaluatePolicy(_:localizedReason:reply:)/title",
          "value": "evaluatePolicy:localizedReason:reply:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1evaluatePolicy(_:localizedReason:reply:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "evaluatePolicy:localizedReason:reply:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1localizedReason/title",
          "value": "localizedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1localizedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1localizedFallbackTitle/title",
          "value": "localizedFallbackTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1localizedFallbackTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedFallbackTitle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/localauthentication/lacontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/localauthentication/lacontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
