{
  "abstract": [
    {
      "text": "Errors issued by the LocalAuthentication framework.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC7LAErrorLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "LAError"
      }
    ],
    "modules": [
      {
        "name": "Local Authentication"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LAError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "LAError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "LAError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication": {
      "abstract": [
        {
          "text": "Authenticate users biometrically or with a passphrase they already know.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication",
      "kind": "symbol",
      "role": "collection",
      "title": "Local Authentication",
      "type": "topic",
      "url": "/documentation/localauthentication"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct": {
      "abstract": [
        {
          "text": "Errors issued by the LocalAuthentication framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LAError"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAError"
        }
      ],
      "role": "symbol",
      "title": "LAError",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Errors issued by the LocalAuthentication framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/appCancel": {
      "abstract": [
        {
          "text": "The app canceled authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appCancel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/appCancel",
      "kind": "symbol",
      "role": "symbol",
      "title": "appCancel",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/appcancel"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/authenticationFailed": {
      "abstract": [
        {
          "text": "The user failed to provide valid credentials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authenticationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/authenticationFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "authenticationFailed",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/authenticationfailed"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/biometryDisconnected": {
      "abstract": [
        {
          "text": "The device supports biometry only using a removable accessory, but the paired accessory isn’t connected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometryDisconnected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/biometryDisconnected",
      "kind": "symbol",
      "role": "symbol",
      "title": "biometryDisconnected",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/biometrydisconnected"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/biometryLockout": {
      "abstract": [
        {
          "text": "Biometry is locked because there were too many failed attempts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometryLockout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/biometryLockout",
      "kind": "symbol",
      "role": "symbol",
      "title": "biometryLockout",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/biometrylockout"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/biometryNotAvailable": {
      "abstract": [
        {
          "text": "Biometry is not available on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometryNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/biometryNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "biometryNotAvailable",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/biometrynotavailable"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/biometryNotEnrolled": {
      "abstract": [
        {
          "text": "The user has no enrolled biometric identities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometryNotEnrolled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/biometryNotEnrolled",
      "kind": "symbol",
      "role": "symbol",
      "title": "biometryNotEnrolled",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/biometrynotenrolled"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/biometryNotPaired": {
      "abstract": [
        {
          "text": "The device supports biometry only using a removable accessory, but no accessory is paired.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometryNotPaired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/biometryNotPaired",
      "kind": "symbol",
      "role": "symbol",
      "title": "biometryNotPaired",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/biometrynotpaired"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/companionNotAvailable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "companionNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/companionNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "companionNotAvailable",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/companionnotavailable"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/errordomain"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/invalidContext": {
      "abstract": [
        {
          "text": "The context was previously invalidated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/invalidContext",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidContext",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/invalidcontext"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/invalidDimensions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/invalidDimensions",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidDimensions",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/invaliddimensions"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/notInteractive": {
      "abstract": [
        {
          "text": "Displaying the required authentication user interface is forbidden.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notInteractive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/notInteractive",
      "kind": "symbol",
      "role": "symbol",
      "title": "notInteractive",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/notinteractive"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/passcodeNotSet": {
      "abstract": [
        {
          "text": "A passcode isn’t set on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passcodeNotSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/passcodeNotSet",
      "kind": "symbol",
      "role": "symbol",
      "title": "passcodeNotSet",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/passcodenotset"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/systemCancel": {
      "abstract": [
        {
          "text": "The system canceled authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemCancel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/systemCancel",
      "kind": "symbol",
      "role": "symbol",
      "title": "systemCancel",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/systemcancel"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/touchIDLockout": {
      "abstract": [
        {
          "text": "Touch ID is locked because there were too many failed attempts.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchIDLockout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/touchIDLockout",
      "kind": "symbol",
      "role": "symbol",
      "title": "touchIDLockout",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/touchidlockout"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/touchIDNotAvailable": {
      "abstract": [
        {
          "text": "Touch ID is not available on the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchIDNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/touchIDNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "touchIDNotAvailable",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/touchidnotavailable"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/touchIDNotEnrolled": {
      "abstract": [
        {
          "text": "The user has no enrolled Touch ID fingers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchIDNotEnrolled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/touchIDNotEnrolled",
      "kind": "symbol",
      "role": "symbol",
      "title": "touchIDNotEnrolled",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/touchidnotenrolled"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/userCancel": {
      "abstract": [
        {
          "text": "The user tapped the cancel button in the authentication dialog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userCancel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/userCancel",
      "kind": "symbol",
      "role": "symbol",
      "title": "userCancel",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/usercancel"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/userFallback": {
      "abstract": [
        {
          "text": "The user tapped the fallback button in the authentication dialog, but no fallback is available for the authentication policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userFallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/userFallback",
      "kind": "symbol",
      "role": "symbol",
      "title": "userFallback",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/userfallback"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/watchNotAvailable": {
      "abstract": [
        {
          "text": "An attempt to authenticate with Apple Watch failed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "watchNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/watchNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "watchNotAvailable",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/watchnotavailable"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAErrorDomain": {
      "abstract": [
        {
          "text": "The error domain that the framework uses when issuing errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LAErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "LAErrorDomain",
      "type": "topic",
      "url": "/documentation/localauthentication/laerrordomain"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Characteristics",
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAErrorDomain"
      ],
      "title": "Error Characteristics"
    },
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/appCancel",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/systemCancel",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/userCancel",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/biometryDisconnected",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/biometryLockout",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/biometryNotAvailable",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/biometryNotEnrolled",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/biometryNotPaired",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/touchIDLockout",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/touchIDNotAvailable",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/touchIDNotEnrolled",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/authenticationFailed",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/invalidContext",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/invalidDimensions",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/notInteractive",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/passcodeNotSet",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/userFallback",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/watchNotAvailable",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/companionNotAvailable",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code/title",
          "value": "LAError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAErrorDomain/title",
          "value": "LAErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/localauthentication/laerror-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
