{
  "abstract": [
    {
      "text": "The set of available local authentication policies.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@LAPolicy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "LAPolicy"
      }
    ],
    "modules": [
      {
        "name": "Local Authentication"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LAPolicy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "LAPolicy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "LAPolicy"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication": {
      "abstract": [
        {
          "text": "Authenticate users biometrically or with a passphrase they already know.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication",
      "kind": "symbol",
      "role": "collection",
      "title": "Local Authentication",
      "type": "topic",
      "url": "/documentation/localauthentication"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType": {
      "abstract": [
        {
          "text": "The set of available biometric authentication types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LABiometryType"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LABiometryType"
        }
      ],
      "role": "symbol",
      "title": "LABiometryType",
      "type": "topic",
      "url": "/documentation/localauthentication/labiometrytype"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/biometryType": {
      "abstract": [
        {
          "text": "The type of biometric authentication supported by the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometryType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LABiometryType",
          "text": "LABiometryType"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/biometryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "biometryType"
        }
      ],
      "role": "symbol",
      "title": "biometryType",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/biometrytype"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/canEvaluatePolicy(_:error:)": {
      "abstract": [
        {
          "text": "Assesses whether authentication can proceed for a given policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canEvaluatePolicy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAPolicy",
          "text": "LAPolicy"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14NSErrorPointera",
          "text": "NSErrorPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/canEvaluatePolicy(_:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canEvaluatePolicy:error:"
        }
      ],
      "role": "symbol",
      "title": "canEvaluatePolicy(_:error:)",
      "type": "topic",
      "url": "/documentation/localauthentication/lacontext/canevaluatepolicy(_:error:)"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy": {
      "abstract": [
        {
          "text": "The set of available local authentication policies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LAPolicy"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAPolicy"
        }
      ],
      "role": "symbol",
      "title": "LAPolicy",
      "type": "topic",
      "url": "/documentation/localauthentication/lapolicy"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthentication": {
      "abstract": [
        {
          "text": "User authentication with biometry, Apple Watch, or the device passcode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceOwnerAuthentication"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthentication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAPolicyDeviceOwnerAuthentication"
        }
      ],
      "role": "symbol",
      "title": "LAPolicy.deviceOwnerAuthentication",
      "type": "topic",
      "url": "/documentation/localauthentication/lapolicy/deviceownerauthentication"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithBiometrics": {
      "abstract": [
        {
          "text": "User authentication with biometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceOwnerAuthenticationWithBiometrics"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithBiometrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAPolicyDeviceOwnerAuthenticationWithBiometrics"
        }
      ],
      "role": "symbol",
      "title": "LAPolicy.deviceOwnerAuthenticationWithBiometrics",
      "type": "topic",
      "url": "/documentation/localauthentication/lapolicy/deviceownerauthenticationwithbiometrics"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithBiometricsOrCompanion": {
      "abstract": [
        {
          "text": "Device owner will be authenticated by biometry or a companion device e.g. Watch, Mac, etc.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceOwnerAuthenticationWithBiometricsOrCompanion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAPolicy",
          "text": "LAPolicy"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithBiometricsOrCompanion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAPolicyDeviceOwnerAuthenticationWithBiometricsOrCompanion"
        }
      ],
      "role": "symbol",
      "title": "deviceOwnerAuthenticationWithBiometricsOrCompanion",
      "type": "topic",
      "url": "/documentation/localauthentication/lapolicy/deviceownerauthenticationwithbiometricsorcompanion"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithBiometricsOrWatch": {
      "abstract": [
        {
          "text": "User authentication with either biometry or Apple Watch.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceOwnerAuthenticationWithBiometricsOrWatch"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithBiometricsOrWatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAPolicyDeviceOwnerAuthenticationWithBiometricsOrWatch"
        }
      ],
      "role": "symbol",
      "title": "LAPolicy.deviceOwnerAuthenticationWithBiometricsOrWatch",
      "type": "topic",
      "url": "/documentation/localauthentication/lapolicy/deviceownerauthenticationwithbiometricsorwatch"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithCompanion": {
      "abstract": [
        {
          "text": "Device owner will be authenticated by a companion device e.g. Watch, Mac, etc.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceOwnerAuthenticationWithCompanion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAPolicy",
          "text": "LAPolicy"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithCompanion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAPolicyDeviceOwnerAuthenticationWithCompanion"
        }
      ],
      "role": "symbol",
      "title": "deviceOwnerAuthenticationWithCompanion",
      "type": "topic",
      "url": "/documentation/localauthentication/lapolicy/deviceownerauthenticationwithcompanion"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithWatch": {
      "abstract": [
        {
          "text": "User authentication with Apple Watch.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceOwnerAuthenticationWithWatch"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithWatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAPolicyDeviceOwnerAuthenticationWithWatch"
        }
      ],
      "role": "symbol",
      "title": "LAPolicy.deviceOwnerAuthenticationWithWatch",
      "type": "topic",
      "url": "/documentation/localauthentication/lapolicy/deviceownerauthenticationwithwatch"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithWristDetection": {
      "abstract": [
        {
          "text": "User authentication with wrist detection on watchOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceOwnerAuthenticationWithWristDetection"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithWristDetection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAPolicyDeviceOwnerAuthenticationWithWristDetection"
        }
      ],
      "role": "symbol",
      "title": "LAPolicy.deviceOwnerAuthenticationWithWristDetection",
      "type": "topic",
      "url": "/documentation/localauthentication/lapolicy/deviceownerauthenticationwithwristdetection"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/localauthentication/lapolicy/init(rawvalue:)"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthentication": {
      "abstract": [
        {
          "text": "User authentication with either biometry or the device passcode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAPolicyDeviceOwnerAuthentication"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthentication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAPolicyDeviceOwnerAuthentication"
        }
      ],
      "role": "symbol",
      "title": "kLAPolicyDeviceOwnerAuthentication",
      "type": "topic",
      "url": "/documentation/localauthentication/klapolicydeviceownerauthentication"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthenticationWithBiometrics": {
      "abstract": [
        {
          "text": "User authentication with biometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAPolicyDeviceOwnerAuthenticationWithBiometrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthenticationWithBiometrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAPolicyDeviceOwnerAuthenticationWithBiometrics"
        }
      ],
      "role": "symbol",
      "title": "kLAPolicyDeviceOwnerAuthenticationWithBiometrics",
      "type": "topic",
      "url": "/documentation/localauthentication/klapolicydeviceownerauthenticationwithbiometrics"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthenticationWithBiometricsOrWatch": {
      "abstract": [
        {
          "text": "User authentication with either biometry or Apple Watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAPolicyDeviceOwnerAuthenticationWithBiometricsOrWatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthenticationWithBiometricsOrWatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAPolicyDeviceOwnerAuthenticationWithBiometricsOrWatch"
        }
      ],
      "role": "symbol",
      "title": "kLAPolicyDeviceOwnerAuthenticationWithBiometricsOrWatch",
      "type": "topic",
      "url": "/documentation/localauthentication/klapolicydeviceownerauthenticationwithbiometricsorwatch"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthenticationWithWatch": {
      "abstract": [
        {
          "text": "User authentication with Apple Watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAPolicyDeviceOwnerAuthenticationWithWatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthenticationWithWatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAPolicyDeviceOwnerAuthenticationWithWatch"
        }
      ],
      "role": "symbol",
      "title": "kLAPolicyDeviceOwnerAuthenticationWithWatch",
      "type": "topic",
      "url": "/documentation/localauthentication/klapolicydeviceownerauthenticationwithwatch"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthenticationWithWristDetection": {
      "abstract": [
        {
          "text": "User authentication with wrist detection on watchOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAPolicyDeviceOwnerAuthenticationWithWristDetection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthenticationWithWristDetection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAPolicyDeviceOwnerAuthenticationWithWristDetection"
        }
      ],
      "role": "symbol",
      "title": "kLAPolicyDeviceOwnerAuthenticationWithWristDetection",
      "type": "topic",
      "url": "/documentation/localauthentication/klapolicydeviceownerauthenticationwithwristdetection"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Checking-availability",
      "generated": true,
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/canEvaluatePolicy(_:error:)",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/biometryType",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType"
      ],
      "title": "Checking availability"
    }
  ],
  "topicSections": [
    {
      "anchor": "Policies",
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithBiometrics",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithWatch",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithBiometricsOrWatch",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthentication",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithWristDetection"
      ],
      "title": "Policies"
    },
    {
      "anchor": "Policy-Constants",
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthenticationWithBiometrics",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthenticationWithWatch",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthenticationWithBiometricsOrWatch",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthentication",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthenticationWithWristDetection"
      ],
      "title": "Policy Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithBiometricsOrCompanion",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithCompanion"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LAPolicy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Policies",
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithBiometrics",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithWatch",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithBiometricsOrWatch",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthentication",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithWristDetection"
              ],
              "title": "Policies"
            },
            {
              "anchor": "Policy-Constants",
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthenticationWithBiometrics",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthenticationWithWatch",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthenticationWithBiometricsOrWatch",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthentication",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAPolicyDeviceOwnerAuthenticationWithWristDetection"
              ],
              "title": "Policy Constants"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithBiometricsOrCompanion",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAPolicy/deviceOwnerAuthenticationWithCompanion"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Checking-availability",
              "generated": true,
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/canEvaluatePolicy(_:error:)",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAContext/biometryType",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType"
              ],
              "title": "Checking availability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "LAPolicy"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1canEvaluatePolicy(_:error:)/title",
          "value": "canEvaluatePolicy:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1canEvaluatePolicy(_:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canEvaluatePolicy:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAPolicyDeviceOwnerAuthenticationWithWatch/title",
          "value": "kLAPolicyDeviceOwnerAuthenticationWithWatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAPolicyDeviceOwnerAuthenticationWithWatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAPolicyDeviceOwnerAuthenticationWithWatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAPolicyDeviceOwnerAuthenticationWithWristDetection/title",
          "value": "kLAPolicyDeviceOwnerAuthenticationWithWristDetection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAPolicyDeviceOwnerAuthenticationWithWristDetection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAPolicyDeviceOwnerAuthenticationWithWristDetection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy~1deviceOwnerAuthenticationWithBiometricsOrCompanion/title",
          "value": "LAPolicyDeviceOwnerAuthenticationWithBiometricsOrCompanion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy~1deviceOwnerAuthenticationWithBiometricsOrCompanion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAPolicyDeviceOwnerAuthenticationWithBiometricsOrCompanion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy~1deviceOwnerAuthenticationWithWatch/title",
          "value": "LAPolicyDeviceOwnerAuthenticationWithWatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy~1deviceOwnerAuthenticationWithWatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAPolicyDeviceOwnerAuthenticationWithWatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy~1deviceOwnerAuthenticationWithCompanion/title",
          "value": "LAPolicyDeviceOwnerAuthenticationWithCompanion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy~1deviceOwnerAuthenticationWithCompanion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAPolicyDeviceOwnerAuthenticationWithCompanion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy~1deviceOwnerAuthenticationWithBiometricsOrWatch/title",
          "value": "LAPolicyDeviceOwnerAuthenticationWithBiometricsOrWatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy~1deviceOwnerAuthenticationWithBiometricsOrWatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAPolicyDeviceOwnerAuthenticationWithBiometricsOrWatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAPolicyDeviceOwnerAuthentication/title",
          "value": "kLAPolicyDeviceOwnerAuthentication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAPolicyDeviceOwnerAuthentication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAPolicyDeviceOwnerAuthentication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy~1deviceOwnerAuthenticationWithWristDetection/title",
          "value": "LAPolicyDeviceOwnerAuthenticationWithWristDetection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy~1deviceOwnerAuthenticationWithWristDetection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAPolicyDeviceOwnerAuthenticationWithWristDetection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType/title",
          "value": "LABiometryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LABiometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LABiometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy/title",
          "value": "LAPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy~1deviceOwnerAuthenticationWithBiometrics/title",
          "value": "LAPolicyDeviceOwnerAuthenticationWithBiometrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy~1deviceOwnerAuthenticationWithBiometrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAPolicyDeviceOwnerAuthenticationWithBiometrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1biometryType/title",
          "value": "biometryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAContext~1biometryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "biometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy~1deviceOwnerAuthentication/title",
          "value": "LAPolicyDeviceOwnerAuthentication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAPolicy~1deviceOwnerAuthentication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAPolicyDeviceOwnerAuthentication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAPolicyDeviceOwnerAuthenticationWithBiometrics/title",
          "value": "kLAPolicyDeviceOwnerAuthenticationWithBiometrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAPolicyDeviceOwnerAuthenticationWithBiometrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAPolicyDeviceOwnerAuthenticationWithBiometrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAPolicyDeviceOwnerAuthenticationWithBiometricsOrWatch/title",
          "value": "kLAPolicyDeviceOwnerAuthenticationWithBiometricsOrWatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAPolicyDeviceOwnerAuthenticationWithBiometricsOrWatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAPolicyDeviceOwnerAuthenticationWithBiometricsOrWatch"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/localauthentication/lapolicy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/localauthentication/lapolicy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
