{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.localauthentication/documentation/LocalAuthentication/localauthentication-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Local Authentication"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "LocalAuthentication Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication": {
      "abstract": [
        {
          "text": "Authenticate users biometrically or with a passphrase they already know.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication",
      "kind": "symbol",
      "role": "collection",
      "title": "Local Authentication",
      "type": "topic",
      "url": "/documentation/localauthentication"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeFaceID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLABiometryTypeFaceID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeFaceID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLABiometryTypeFaceID"
        }
      ],
      "role": "symbol",
      "title": "kLABiometryTypeFaceID",
      "type": "topic",
      "url": "/documentation/localauthentication/klabiometrytypefaceid"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLABiometryTypeNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLABiometryTypeNone"
        }
      ],
      "role": "symbol",
      "title": "kLABiometryTypeNone",
      "type": "topic",
      "url": "/documentation/localauthentication/klabiometrytypenone"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeOpticID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLABiometryTypeOpticID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeOpticID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLABiometryTypeOpticID"
        }
      ],
      "role": "symbol",
      "title": "kLABiometryTypeOpticID",
      "type": "topic",
      "url": "/documentation/localauthentication/klabiometrytypeopticid"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeTouchID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLABiometryTypeTouchID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeTouchID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLABiometryTypeTouchID"
        }
      ],
      "role": "symbol",
      "title": "kLABiometryTypeTouchID",
      "type": "topic",
      "url": "/documentation/localauthentication/klabiometrytypetouchid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeFaceID",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeNone",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeOpticID",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeTouchID"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeFaceID",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeNone",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeOpticID",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLABiometryTypeTouchID"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLABiometryTypeTouchID/title",
          "value": "kLABiometryTypeTouchID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLABiometryTypeTouchID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLABiometryTypeTouchID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLABiometryTypeOpticID/title",
          "value": "kLABiometryTypeOpticID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLABiometryTypeOpticID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLABiometryTypeOpticID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLABiometryTypeNone/title",
          "value": "kLABiometryTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLABiometryTypeNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLABiometryTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLABiometryTypeFaceID/title",
          "value": "kLABiometryTypeFaceID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLABiometryTypeFaceID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLABiometryTypeFaceID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/localauthentication/localauthentication-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/localauthentication/localauthentication-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
