{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setPasskey(_:for:usingSSP:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)IOBluetoothPasskeyDisplay(im)setPasskey:forDevice:usingSSP:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setPasskey"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)IOBluetoothDevice",
        "text": "IOBluetoothDevice"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "usingSSP"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setPasskey:forDevice:usingSSP:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setPasskey(_:for:usingSSP:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setPasskey"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inString"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "device"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)IOBluetoothDevice",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)IOBluetoothDevice",
              "text": "IOBluetoothDevice"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "usingSSP"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "isSSP"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI": {
      "abstract": [
        {
          "text": "Present an interface through which users can pair their devices with other Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth UI",
      "type": "topic",
      "url": "/documentation/iobluetoothui"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothPasskeyDisplay"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothPasskeyDisplay"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothPasskeyDisplay",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/advancePasskeyIndicator()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "advancePasskeyIndicator"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/advancePasskeyIndicator()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "advancePasskeyIndicator"
        }
      ],
      "role": "symbol",
      "title": "advancePasskeyIndicator()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/advancepasskeyindicator()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/resetAll": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "resetAll"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/resetAll",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resetAll"
        }
      ],
      "role": "symbol",
      "title": "resetAll",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/resetall"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/resetPasskeyIndicator()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resetPasskeyIndicator"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/resetPasskeyIndicator()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resetPasskeyIndicator"
        }
      ],
      "role": "symbol",
      "title": "resetPasskeyIndicator()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/resetpasskeyindicator()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/retreatPasskeyIndicator()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "retreatPasskeyIndicator"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/retreatPasskeyIndicator()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "retreatPasskeyIndicator"
        }
      ],
      "role": "symbol",
      "title": "retreatPasskeyIndicator()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/retreatpasskeyindicator()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setPasskey(_:for:usingSSP:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPasskey"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothDevice",
          "text": "IOBluetoothDevice"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "usingSSP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setPasskey(_:for:usingSSP:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPasskey:forDevice:usingSSP:"
        }
      ],
      "role": "symbol",
      "title": "setPasskey(_:for:usingSSP:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/setpasskey(_:for:usingssp:)"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setPasskeyIndicatorEnabled:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setPasskeyIndicatorEnabled:"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setPasskeyIndicatorEnabled:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPasskeyIndicatorEnabled:"
        }
      ],
      "role": "symbol",
      "title": "setPasskeyIndicatorEnabled:",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/setpasskeyindicatorenabled:"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setPasskeyString:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setPasskeyString:"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setPasskeyString:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPasskeyString:"
        }
      ],
      "role": "symbol",
      "title": "setPasskeyString:",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/setpasskeystring:"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setupUIForDevice:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setupUIForDevice:"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setupUIForDevice:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setupUIForDevice:"
        }
      ],
      "role": "symbol",
      "title": "setupUIForDevice:",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/setupuifordevice:"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setupUIForSSPDevice:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setupUIForSSPDevice:"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setupUIForSSPDevice:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setupUIForSSPDevice:"
        }
      ],
      "role": "symbol",
      "title": "setupUIForSSPDevice:",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/setupuiforsspdevice:"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)IOBluetoothDevice": {
      "abstract": [
        {
          "text": "An instance of IOBluetoothDevice represents a single remote Bluetooth device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDevice"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)IOBluetoothDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOBluetoothDevice",
      "type": "topic",
      "url": "/documentation/IOBluetooth/IOBluetoothDevice"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/advancePasskeyIndicator()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/resetPasskeyIndicator()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/retreatPasskeyIndicator()"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setPasskey:forDevice:usingSSP:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPasskey:forDevice:usingSSP:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/advancePasskeyIndicator()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/resetPasskeyIndicator()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/retreatPasskeyIndicator()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/resetAll",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setPasskeyIndicatorEnabled:",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setPasskeyString:",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setupUIForDevice:",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setupUIForSSPDevice:"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setPasskey:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inString"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "forDevice:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)IOBluetoothDevice",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)IOBluetoothDevice",
                    "text": "IOBluetoothDevice"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "device"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "usingSSP:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "isSSP"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay/title",
          "value": "IOBluetoothPasskeyDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPasskeyDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPasskeyDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1retreatPasskeyIndicator()/title",
          "value": "retreatPasskeyIndicator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1retreatPasskeyIndicator()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "retreatPasskeyIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)IOBluetoothDevice/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOBluetoothDevice"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)IOBluetoothObject",
              "text": "IOBluetoothObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1resetPasskeyIndicator()/title",
          "value": "resetPasskeyIndicator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1resetPasskeyIndicator()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resetPasskeyIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1advancePasskeyIndicator()/title",
          "value": "advancePasskeyIndicator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1advancePasskeyIndicator()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "advancePasskeyIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1setPasskey(_:for:usingSSP:)/title",
          "value": "setPasskey:forDevice:usingSSP:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1setPasskey(_:for:usingSSP:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPasskey:forDevice:usingSSP:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothpasskeydisplay/setpasskey(_:for:usingssp:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothpasskeydisplay/setpasskey(_:for:usingssp:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
