{
  "abstract": [
    {
      "text": "The name of an image to display during app launch.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIImageName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.UILaunchScreens.UILaunchScreenDefinitions.UIImageName",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIImageName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "UIImageName"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "UIImageName",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Provide a value for this key that’s the name of an image in your asset catalog. You use the same string for the value that you might use when calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIImage/init(named:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " initializer of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIImage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Because the image comes from your asset catalog, you can use slicing to provide a small image that works on many different platforms.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you don’t specify an image, the display shows the background color, as given by the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIColorName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key. The background color may also show through any transparency in your image.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens": {
      "abstract": [
        {
          "text": "The user interfaces to show while an app launches in response to different URL schemes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens",
      "kind": "symbol",
      "name": "UILaunchScreens",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchScreens"
        }
      ],
      "role": "symbol",
      "title": "UILaunchScreens",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions": {
      "abstract": [
        {
          "text": "A collection of launch screen configuration dictionaries.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions",
      "kind": "symbol",
      "name": "UILaunchScreenDefinitions",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchScreenDefinitions"
        }
      ],
      "role": "symbol",
      "title": "UILaunchScreenDefinitions",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIColorName": {
      "abstract": [
        {
          "text": "The name of a color to use as the background color on the launch screen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIColorName",
      "kind": "symbol",
      "name": "UIColorName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIColorName"
        }
      ],
      "role": "symbol",
      "title": "UIColorName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions/uicolorname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIImageName": {
      "abstract": [
        {
          "text": "The name of an image to display during app launch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIImageName",
      "kind": "symbol",
      "name": "UIImageName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageName"
        }
      ],
      "role": "symbol",
      "title": "UIImageName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions/uiimagename"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIImageRespectsSafeAreaInsets": {
      "abstract": [
        {
          "text": "A Boolean that specifies whether the launch image should respect the safe area insets.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIImageRespectsSafeAreaInsets",
      "kind": "symbol",
      "name": "UIImageRespectsSafeAreaInsets",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageRespectsSafeAreaInsets"
        }
      ],
      "role": "symbol",
      "title": "UIImageRespectsSafeAreaInsets",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions/uiimagerespectssafeareainsets"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIImage": {
      "abstract": [
        {
          "text": "An object that manages image data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIImage",
      "type": "topic",
      "url": "/documentation/UIKit/UIImage"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIImage/init(named:)": {
      "abstract": [
        {
          "text": "Creates an image object from the specified named asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "named"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIImage/init(named:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(named:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIImage/init(named:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Main-Interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIColorName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIImageRespectsSafeAreaInsets"
      ],
      "title": "Main Interface"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIImageName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Main-Interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIColorName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UIImageRespectsSafeAreaInsets"
              ],
              "title": "Main Interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens/title",
          "value": "UILaunchScreens"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreens"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UIImageRespectsSafeAreaInsets/title",
          "value": "UIImageRespectsSafeAreaInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UIImageRespectsSafeAreaInsets/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageRespectsSafeAreaInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UIImageName/title",
          "value": "UIImageName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UIImageName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIImage/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIImage"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions/title",
          "value": "UILaunchScreenDefinitions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreenDefinitions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UIColorName/title",
          "value": "UIColorName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UIColorName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIColorName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIImage~1init(named:)/title",
          "value": "imageNamed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIImage~1init(named:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIImage",
              "text": "UIImage"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "imageNamed:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "name"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions/uiimagename"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions/uiimagename"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
