{
  "abstract": [
    {
      "text": "A unique name for the launch screen configuration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UILaunchScreenIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.UILaunchScreens.UILaunchScreenDefinitions.UILaunchScreenIdentifier",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UILaunchScreenIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "UILaunchScreenIdentifier"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "UILaunchScreenIdentifier",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can choose any name you want for the identifier, as long as it’s unique among all your app’s configuration identifiers. Use this value to refer to the configuration when storing a URL to configuration mapping as the value for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UIURLToLaunchScreenAssociations",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key, or when specifying a default configuration with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UIDefaultLaunchScreen",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens": {
      "abstract": [
        {
          "text": "The user interfaces to show while an app launches in response to different URL schemes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens",
      "kind": "symbol",
      "name": "UILaunchScreens",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchScreens"
        }
      ],
      "role": "symbol",
      "title": "UILaunchScreens",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UIDefaultLaunchScreen": {
      "abstract": [
        {
          "text": "The default launch screen configuration.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UIDefaultLaunchScreen",
      "kind": "symbol",
      "name": "UIDefaultLaunchScreen",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDefaultLaunchScreen"
        }
      ],
      "role": "symbol",
      "title": "UIDefaultLaunchScreen",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uidefaultlaunchscreen"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions": {
      "abstract": [
        {
          "text": "A collection of launch screen configuration dictionaries.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions",
      "kind": "symbol",
      "name": "UILaunchScreenDefinitions",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchScreenDefinitions"
        }
      ],
      "role": "symbol",
      "title": "UILaunchScreenDefinitions",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UILaunchScreenIdentifier": {
      "abstract": [
        {
          "text": "A unique name for the launch screen configuration.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions/UILaunchScreenIdentifier",
      "kind": "symbol",
      "name": "UILaunchScreenIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchScreenIdentifier"
        }
      ],
      "role": "symbol",
      "title": "UILaunchScreenIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions/uilaunchscreenidentifier"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UIURLToLaunchScreenAssociations": {
      "abstract": [
        {
          "text": "The mapping of URL schemes to launch screen configurations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UIURLToLaunchScreenAssociations",
      "kind": "symbol",
      "name": "UIURLToLaunchScreenAssociations",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIURLToLaunchScreenAssociations"
        }
      ],
      "role": "symbol",
      "title": "UIURLToLaunchScreenAssociations",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchscreens/uiurltolaunchscreenassociations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UILaunchScreenIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreenIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchScreens/UILaunchScreenDefinitions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UIURLToLaunchScreenAssociations/title",
          "value": "UIURLToLaunchScreenAssociations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UIURLToLaunchScreenAssociations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIURLToLaunchScreenAssociations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions/title",
          "value": "UILaunchScreenDefinitions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreenDefinitions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UIDefaultLaunchScreen/title",
          "value": "UIDefaultLaunchScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UIDefaultLaunchScreen/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDefaultLaunchScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UILaunchScreenIdentifier/title",
          "value": "UILaunchScreenIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens~1UILaunchScreenDefinitions~1UILaunchScreenIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreenIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens/title",
          "value": "UILaunchScreens"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchScreens/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchScreens"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions/uilaunchscreenidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uilaunchscreens/uilaunchscreendefinitions/uilaunchscreenidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
