{
  "abstract": [
    {
      "text": "Informs the delegate of a change in value of a characteristic.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:service:didUpdateValueFor:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)HMAccessoryDelegate(im)accessory:service:didUpdateValueForCharacteristic:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "accessory"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)HMAccessory",
        "text": "HMAccessory"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "service"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)HMService",
        "text": "HMService"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didUpdateValueFor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)HMCharacteristic",
        "text": "HMCharacteristic"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "accessory:service:didUpdateValueForCharacteristic:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "accessory(_:service:didUpdateValueFor:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accessory"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "accessory"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessory",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HMAccessory",
              "text": "HMAccessory"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "service"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMService",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HMService",
              "text": "HMService"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didUpdateValueFor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "characteristic"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HMCharacteristic",
              "text": "HMCharacteristic"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The accessory.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "accessory"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The service with a changed characteristic value.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "service"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The characteristic whose value changed.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "characteristic"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.homekit/documentation/HomeKit/testing-your-app-with-the-homekit-accessory-simulator"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is called as a result of a change in value initiated by the accessory. Programmatic changes initiated by the app do not result in this method being called.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessory": {
      "abstract": [
        {
          "text": "A home automation accessory, like a garage door opener or a thermostat.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessory"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessory"
        }
      ],
      "role": "symbol",
      "title": "HMAccessory",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessory"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate": {
      "abstract": [
        {
          "text": "A set of methods that defines the communication method for state updates from accessories to their delegates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryDelegate"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryDelegate"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryDelegate",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorydelegate"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didAdd:)": {
      "abstract": [
        {
          "text": "Informs the delegate when a profile is added to an accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMAccessory",
          "text": "HMAccessory"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didAdd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMAccessoryProfile",
          "text": "HMAccessoryProfile"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didAdd:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessory:didAddProfile:"
        }
      ],
      "role": "symbol",
      "title": "accessory(_:didAdd:)",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorydelegate/accessory(_:didadd:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didRemove:)": {
      "abstract": [
        {
          "text": "Informs the delegate when a profile is removed from an accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMAccessory",
          "text": "HMAccessory"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRemove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMAccessoryProfile",
          "text": "HMAccessoryProfile"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didRemove:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessory:didRemoveProfile:"
        }
      ],
      "role": "symbol",
      "title": "accessory(_:didRemove:)",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorydelegate/accessory(_:didremove:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didUpdateAssociatedServiceTypeFor:)": {
      "abstract": [
        {
          "text": "Informs the delegate when the associated service type of a service is modified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMAccessory",
          "text": "HMAccessory"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdateAssociatedServiceTypeFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMService",
          "text": "HMService"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didUpdateAssociatedServiceTypeFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessory:didUpdateAssociatedServiceTypeForService:"
        }
      ],
      "role": "symbol",
      "title": "accessory(_:didUpdateAssociatedServiceTypeFor:)",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorydelegate/accessory(_:didupdateassociatedservicetypefor:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didUpdateFirmwareVersion:)": {
      "abstract": [
        {
          "text": "Informs the delegate when firmwareVersion has been changed for an accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMAccessory",
          "text": "HMAccessory"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdateFirmwareVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didUpdateFirmwareVersion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessory:didUpdateFirmwareVersion:"
        }
      ],
      "role": "symbol",
      "title": "accessory(_:didUpdateFirmwareVersion:)",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorydelegate/accessory(_:didupdatefirmwareversion:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didUpdateNameFor:)": {
      "abstract": [
        {
          "text": "Informs the delegate when the name of a service is updated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMAccessory",
          "text": "HMAccessory"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdateNameFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMService",
          "text": "HMService"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didUpdateNameFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessory:didUpdateNameForService:"
        }
      ],
      "role": "symbol",
      "title": "accessory(_:didUpdateNameFor:)",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorydelegate/accessory(_:didupdatenamefor:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:service:didUpdateValueFor:)": {
      "abstract": [
        {
          "text": "Informs the delegate of a change in value of a characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMAccessory",
          "text": "HMAccessory"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "service"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMService",
          "text": "HMService"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdateValueFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMCharacteristic",
          "text": "HMCharacteristic"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:service:didUpdateValueFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessory:service:didUpdateValueForCharacteristic:"
        }
      ],
      "role": "symbol",
      "title": "accessory(_:service:didUpdateValueFor:)",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorydelegate/accessory(_:service:didupdatevaluefor:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessoryDidUpdateName(_:)": {
      "abstract": [
        {
          "text": "Informs the delegate when the name of the accessory is updated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryDidUpdateName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMAccessory",
          "text": "HMAccessory"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessoryDidUpdateName(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessoryDidUpdateName:"
        }
      ],
      "role": "symbol",
      "title": "accessoryDidUpdateName(_:)",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorydelegate/accessorydidupdatename(_:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessoryDidUpdateReachability(_:)": {
      "abstract": [
        {
          "text": "Informs the delegate when the reachability of the accessory changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryDidUpdateReachability"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMAccessory",
          "text": "HMAccessory"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessoryDidUpdateReachability(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessoryDidUpdateReachability:"
        }
      ],
      "role": "symbol",
      "title": "accessoryDidUpdateReachability(_:)",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorydelegate/accessorydidupdatereachability(_:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessoryDidUpdateServices(_:)": {
      "abstract": [
        {
          "text": "Informs the delegate when the services on the accessory have been updated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryDidUpdateServices"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMAccessory",
          "text": "HMAccessory"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessoryDidUpdateServices(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessoryDidUpdateServices:"
        }
      ],
      "role": "symbol",
      "title": "accessoryDidUpdateServices(_:)",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorydelegate/accessorydidupdateservices(_:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic": {
      "abstract": [
        {
          "text": "A specific characteristic of a service, like the brightness of a dimmable light or its color temperature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristic"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristic",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristic"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMService": {
      "abstract": [
        {
          "text": "A controllable feature of an accessory, like a light attached to a garage door opener.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMService"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMService"
        }
      ],
      "role": "symbol",
      "title": "HMService",
      "type": "topic",
      "url": "/documentation/homekit/hmservice"
    },
    "doc://com.apple.homekit/documentation/HomeKit/testing-your-app-with-the-homekit-accessory-simulator": {
      "abstract": [
        {
          "text": "Install the HomeKit Accessory Simulator to help you debug your HomeKit-enabled app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/testing-your-app-with-the-homekit-accessory-simulator",
      "kind": "article",
      "role": "article",
      "title": "Testing your app with the HomeKit Accessory Simulator",
      "type": "topic",
      "url": "/documentation/homekit/testing-your-app-with-the-homekit-accessory-simulator"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Observing-accessories",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessoryDidUpdateName(_:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessoryDidUpdateReachability(_:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessoryDidUpdateServices(_:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didUpdateNameFor:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didUpdateAssociatedServiceTypeFor:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didAdd:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didRemove:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didUpdateFirmwareVersion:)"
      ],
      "title": "Observing accessories"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "accessory:service:didUpdateValueForCharacteristic:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessory:service:didUpdateValueForCharacteristic:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Observing-accessories",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessoryDidUpdateName(_:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessoryDidUpdateReachability(_:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessoryDidUpdateServices(_:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didUpdateNameFor:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didUpdateAssociatedServiceTypeFor:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didAdd:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didRemove:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryDelegate/accessory(_:didUpdateFirmwareVersion:)"
              ],
              "title": "Observing accessories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "accessory:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessory",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)HMAccessory",
                    "text": "HMAccessory"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "accessory"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "service:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMService",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)HMService",
                    "text": "HMService"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "service"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didUpdateValueForCharacteristic:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)HMCharacteristic",
                    "text": "HMCharacteristic"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "characteristic"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The accessory.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "accessory"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The service with a changed characteristic value.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "service"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The characteristic whose value changed.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "characteristic"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate~1accessory(_:didUpdateFirmwareVersion:)/title",
          "value": "accessory:didUpdateFirmwareVersion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate~1accessory(_:didUpdateFirmwareVersion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessory:didUpdateFirmwareVersion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate~1accessory(_:didUpdateNameFor:)/title",
          "value": "accessory:didUpdateNameForService:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate~1accessory(_:didUpdateNameFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessory:didUpdateNameForService:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate~1accessoryDidUpdateName(_:)/title",
          "value": "accessoryDidUpdateName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate~1accessoryDidUpdateName(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessoryDidUpdateName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate~1accessoryDidUpdateReachability(_:)/title",
          "value": "accessoryDidUpdateReachability:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate~1accessoryDidUpdateReachability(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessoryDidUpdateReachability:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMService/title",
          "value": "HMService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate~1accessory(_:didAdd:)/title",
          "value": "accessory:didAddProfile:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate~1accessory(_:didAdd:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessory:didAddProfile:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate~1accessory(_:didRemove:)/title",
          "value": "accessory:didRemoveProfile:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate~1accessory(_:didRemove:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessory:didRemoveProfile:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic/title",
          "value": "HMCharacteristic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate~1accessory(_:didUpdateAssociatedServiceTypeFor:)/title",
          "value": "accessory:didUpdateAssociatedServiceTypeForService:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate~1accessory(_:didUpdateAssociatedServiceTypeFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessory:didUpdateAssociatedServiceTypeForService:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate/title",
          "value": "HMAccessoryDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate~1accessoryDidUpdateServices(_:)/title",
          "value": "accessoryDidUpdateServices:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate~1accessoryDidUpdateServices(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessoryDidUpdateServices:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate~1accessory(_:service:didUpdateValueFor:)/title",
          "value": "accessory:service:didUpdateValueForCharacteristic:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryDelegate~1accessory(_:service:didUpdateValueFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessory:service:didUpdateValueForCharacteristic:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory/title",
          "value": "HMAccessory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessory"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmaccessorydelegate/accessory(_:service:didupdatevaluefor:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmaccessorydelegate/accessory(_:service:didupdatevaluefor:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
