{
  "abstract": [
    {
      "text": "The input source is the television’s tuner.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/tuner"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HMCharacteristicValueInputSourceType@HMCharacteristicValueInputSourceTypeTuner",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "tuner"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMCharacteristicValueInputSourceTypeTuner"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HMCharacteristicValueInputSourceType.tuner"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tuner"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType": {
      "abstract": [
        {
          "text": "Types of accessory input sources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputSourceType"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputSourceType"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputSourceType",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputsourcetype"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/airPlay": {
      "abstract": [
        {
          "text": "The input source is an AirPlay device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "airPlay"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/airPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputSourceTypeAirPlay"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputSourceType.airPlay",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputsourcetype/airplay"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/application": {
      "abstract": [
        {
          "text": "A virtual input source type for any preinstalled or downloaded applications on the television.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/application",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputSourceTypeApplication"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputSourceType.application",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputsourcetype/application"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/componentVideo": {
      "abstract": [
        {
          "text": "The input source is a Component Video input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "componentVideo"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/componentVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputSourceTypeComponentVideo"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputSourceType.componentVideo",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputsourcetype/componentvideo"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/compositeVideo": {
      "abstract": [
        {
          "text": "The input source is a Composite Video input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compositeVideo"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/compositeVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputSourceTypeCompositeVideo"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputSourceType.compositeVideo",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputsourcetype/compositevideo"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/dvi": {
      "abstract": [
        {
          "text": "The input source is a DVI input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dvi"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/dvi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputSourceTypeDVI"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputSourceType.dvi",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputsourcetype/dvi"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/hdmi": {
      "abstract": [
        {
          "text": "The input source is an HDMI input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hdmi"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/hdmi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputSourceTypeHDMI"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputSourceType.hdmi",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputsourcetype/hdmi"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/homeScreen": {
      "abstract": [
        {
          "text": "A virtual input source type that represents the television’s default home screen, if there is one.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "homeScreen"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/homeScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputSourceTypeHomeScreen"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputSourceType.homeScreen",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputsourcetype/homescreen"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/other": {
      "abstract": [
        {
          "text": "The input source is another input category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputSourceTypeOther"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputSourceType.other",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputsourcetype/other"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/sVideo": {
      "abstract": [
        {
          "text": "The input source is a S-Video input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sVideo"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/sVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputSourceTypeSVideo"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputSourceType.sVideo",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputsourcetype/svideo"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/tuner": {
      "abstract": [
        {
          "text": "The input source is the television’s tuner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tuner"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/tuner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputSourceTypeTuner"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputSourceType.tuner",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputsourcetype/tuner"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/usb": {
      "abstract": [
        {
          "text": "The input source is a USB device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usb"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/usb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueInputSourceTypeUSB"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueInputSourceType.usb",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueinputsourcetype/usb"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessory-source-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/airPlay",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/application",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/componentVideo",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/compositeVideo",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/dvi",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/hdmi",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/homeScreen",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/other",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/sVideo",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/usb"
      ],
      "title": "Accessory source types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMCharacteristicValueInputSourceTypeTuner"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputSourceTypeTuner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessory-source-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/airPlay",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/application",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/componentVideo",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/compositeVideo",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/dvi",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/hdmi",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/homeScreen",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/other",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/sVideo",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueInputSourceType/usb"
              ],
              "title": "Accessory source types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HMCharacteristicValueInputSourceTypeTuner"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1application/title",
          "value": "HMCharacteristicValueInputSourceTypeApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1application/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputSourceTypeApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1other/title",
          "value": "HMCharacteristicValueInputSourceTypeOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputSourceTypeOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1componentVideo/title",
          "value": "HMCharacteristicValueInputSourceTypeComponentVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1componentVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputSourceTypeComponentVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1hdmi/title",
          "value": "HMCharacteristicValueInputSourceTypeHDMI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1hdmi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputSourceTypeHDMI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType/title",
          "value": "HMCharacteristicValueInputSourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1compositeVideo/title",
          "value": "HMCharacteristicValueInputSourceTypeCompositeVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1compositeVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputSourceTypeCompositeVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1dvi/title",
          "value": "HMCharacteristicValueInputSourceTypeDVI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1dvi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputSourceTypeDVI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1airPlay/title",
          "value": "HMCharacteristicValueInputSourceTypeAirPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1airPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputSourceTypeAirPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1usb/title",
          "value": "HMCharacteristicValueInputSourceTypeUSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1usb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputSourceTypeUSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1sVideo/title",
          "value": "HMCharacteristicValueInputSourceTypeSVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1sVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputSourceTypeSVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1tuner/title",
          "value": "HMCharacteristicValueInputSourceTypeTuner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1tuner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputSourceTypeTuner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1homeScreen/title",
          "value": "HMCharacteristicValueInputSourceTypeHomeScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueInputSourceType~1homeScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueInputSourceTypeHomeScreen"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmcharacteristicvalueinputsourcetype/tuner"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmcharacteristicvalueinputsourcetype/tuner"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
