{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeftCorner"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKTileAdjacencyMask@SKTileAdjacencyLowerLeftCorner",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "adjacencyLowerLeftCorner"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
        "text": "SKTileAdjacencyMask"
      }
    ],
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKTileAdjacencyLowerLeftCorner"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "adjacencyLowerLeftCorner"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "adjacencyLowerLeftCorner"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
              "text": "SKTileAdjacencyMask"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask": {
      "abstract": [
        {
          "text": "An enumeration defining how neighboring tiles are automatically placed next to each other.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "role": "symbol",
      "title": "SKTileAdjacencyMask",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyAll": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyAll"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyAll",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyAll"
        }
      ],
      "role": "symbol",
      "title": "adjacencyAll",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyall"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyDown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyDown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyDown"
        }
      ],
      "role": "symbol",
      "title": "adjacencyDown",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencydown"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyDownEdge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyDownEdge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyDownEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyDownEdge"
        }
      ],
      "role": "symbol",
      "title": "adjacencyDownEdge",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencydownedge"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLeft": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyLeft"
        }
      ],
      "role": "symbol",
      "title": "adjacencyLeft",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyleft"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLeftEdge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyLeftEdge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLeftEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyLeftEdge"
        }
      ],
      "role": "symbol",
      "title": "adjacencyLeftEdge",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyleftedge"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeft": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyLowerLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyLowerLeft"
        }
      ],
      "role": "symbol",
      "title": "adjacencyLowerLeft",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencylowerleft"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeftCorner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyLowerLeftCorner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeftCorner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyLowerLeftCorner"
        }
      ],
      "role": "symbol",
      "title": "adjacencyLowerLeftCorner",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencylowerleftcorner"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeftEdge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyLowerLeftEdge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeftEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyLowerLeftEdge"
        }
      ],
      "role": "symbol",
      "title": "adjacencyLowerLeftEdge",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencylowerleftedge"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyLowerRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyLowerRight"
        }
      ],
      "role": "symbol",
      "title": "adjacencyLowerRight",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencylowerright"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRightCorner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyLowerRightCorner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRightCorner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyLowerRightCorner"
        }
      ],
      "role": "symbol",
      "title": "adjacencyLowerRightCorner",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencylowerrightcorner"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRightEdge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyLowerRightEdge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRightEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyLowerRightEdge"
        }
      ],
      "role": "symbol",
      "title": "adjacencyLowerRightEdge",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencylowerrightedge"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyRight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyRight"
        }
      ],
      "role": "symbol",
      "title": "adjacencyRight",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyright"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyRightEdge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyRightEdge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyRightEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyRightEdge"
        }
      ],
      "role": "symbol",
      "title": "adjacencyRightEdge",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyrightedge"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyUp"
        }
      ],
      "role": "symbol",
      "title": "adjacencyUp",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyup"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpEdge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyUpEdge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyUpEdge"
        }
      ],
      "role": "symbol",
      "title": "adjacencyUpEdge",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyupedge"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperLeft": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjacencyUpperLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKTileAdjacencyMask",
          "text": "SKTileAdjacencyMask"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTileAdjacencyUpperLeft"
        }
      ],
      "role": "symbol",
      "title": "adjacencyUpperLeft",
      "type": "topic",
      "url": "/documentation/spritekit/sktileadjacencymask/adjacencyupperleft"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Masks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyAll",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyDown",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyDownEdge",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLeft",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLeftEdge",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeft",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeftEdge",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRight",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRightCorner",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRightEdge",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyRight",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyRightEdge",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUp",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpEdge",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperLeft"
      ],
      "title": "Masks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKTileAdjacencyLowerLeftCorner"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyLowerLeftCorner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.spritekit/documentation/SpriteKit",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Masks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyAll",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyDown",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyDownEdge",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLeft",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLeftEdge",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeft",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerLeftEdge",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRight",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRightCorner",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyLowerRightEdge",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyRight",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyRightEdge",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUp",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpEdge",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKTileAdjacencyMask/adjacencyUpperLeft"
              ],
              "title": "Masks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SKTileAdjacencyLowerLeftCorner"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerRightEdge/title",
          "value": "SKTileAdjacencyLowerRightEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerRightEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyLowerRightEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUpperLeft/title",
          "value": "SKTileAdjacencyUpperLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUpperLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyUpperLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyDownEdge/title",
          "value": "SKTileAdjacencyDownEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyDownEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyDownEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerLeftEdge/title",
          "value": "SKTileAdjacencyLowerLeftEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerLeftEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyLowerLeftEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask/title",
          "value": "SKTileAdjacencyMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerLeft/title",
          "value": "SKTileAdjacencyLowerLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyLowerLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUp/title",
          "value": "SKTileAdjacencyUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyAll/title",
          "value": "SKTileAdjacencyAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyAll/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLeftEdge/title",
          "value": "SKTileAdjacencyLeftEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLeftEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyLeftEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerRightCorner/title",
          "value": "SKTileAdjacencyLowerRightCorner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerRightCorner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyLowerRightCorner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyDown/title",
          "value": "SKTileAdjacencyDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyRightEdge/title",
          "value": "SKTileAdjacencyRightEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyRightEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyRightEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerRight/title",
          "value": "SKTileAdjacencyLowerRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyLowerRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerLeftCorner/title",
          "value": "SKTileAdjacencyLowerLeftCorner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLowerLeftCorner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyLowerLeftCorner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyRight/title",
          "value": "SKTileAdjacencyRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUpEdge/title",
          "value": "SKTileAdjacencyUpEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyUpEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyUpEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLeft/title",
          "value": "SKTileAdjacencyLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKTileAdjacencyMask~1adjacencyLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTileAdjacencyLeft"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/sktileadjacencymask/adjacencylowerleftcorner"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/sktileadjacencymask/adjacencylowerleftcorner"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
