{"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataLayout","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensorNamedDataLayout","text":"MPSGraphTensorNamedDataLayout","kind":"typeIdentifier","preciseIdentifier":"c:@E@MPSGraphTensorNamedDataLayout"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"It defines the order of named dimensions (Batch, Channel, Height, Width). The convolution operation uses this to interpret data in the source tensor.","type":"text"},{"text":" ","type":"text"},{"text":"For example, if ","type":"text"},{"code":"dataLayout","type":"codeVoice"},{"text":" is ","type":"text"},{"code":"MPSGraphTensorNamedDataLayoutNCHW","type":"codeVoice"},{"text":", frameork interprets data in source tensor as ","type":"text"},{"code":"batch x channels x height x width","type":"codeVoice"},{"text":" ","type":"text"},{"text":"with ","type":"text"},{"code":"width","type":"codeVoice"},{"text":" as fastest moving dimension.","type":"text"}]}],"kind":"content"}],"identifier":{"url":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphConvolution2DOpDescriptor/dataLayout","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/metalperformanceshadersgraph/mpsgraphconvolution2dopdescriptor/datalayout"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/metalperformanceshadersgraph/mpsgraphconvolution2dopdescriptor/datalayout"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"dataLayout","symbolKind":"property","modules":[{"name":"Metal Performance Shaders Graph"}],"externalID":"c:objc(cs)MPSGraphConvolution2DOpDescriptor(py)dataLayout","navigatorTitle":[{"text":"dataLayout","kind":"identifier"}],"role":"symbol","platforms":[{"introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS"},{"introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"},{"introducedAt":"11.0","deprecated":false,"unavailable":false,"beta":false,"name":"macOS"},{"introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false,"name":"tvOS"},{"introducedAt":"1.0","deprecated":false,"unavailable":false,"beta":false,"name":"visionOS"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataLayout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPSGraphTensorNamedDataLayout","preciseIdentifier":"c:@E@MPSGraphTensorNamedDataLayout","kind":"typeIdentifier"}]},"sections":[],"abstract":[{"type":"text","text":"The named layout of data in the source tensor."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphConvolution2DOpDescriptor"]]},"references":{"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphConvolution2DOpDescriptor/dataLayout":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataLayout","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MPSGraphTensorNamedDataLayout","text":"MPSGraphTensorNamedDataLayout"}],"title":"dataLayout","role":"symbol","abstract":[{"type":"text","text":"The named layout of data in the source tensor."}],"navigatorTitle":[{"text":"dataLayout","kind":"identifier"}],"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphConvolution2DOpDescriptor/dataLayout","kind":"symbol","url":"/documentation/metalperformanceshadersgraph/mpsgraphconvolution2dopdescriptor/datalayout","type":"topic"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensorNamedDataLayout":{"abstract":[{"text":"The tensor layout.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPSGraphTensorNamedDataLayout","kind":"identifier"}],"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensorNamedDataLayout","type":"topic","title":"MPSGraphTensorNamedDataLayout","role":"symbol","url":"/documentation/metalperformanceshadersgraph/mpsgraphtensornameddatalayout","navigatorTitle":[{"text":"MPSGraphTensorNamedDataLayout","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph":{"role":"collection","kind":"symbol","url":"/documentation/metalperformanceshadersgraph","abstract":[{"type":"text","text":"Build, compile, and execute compute graphs utilizing all the different compute devices on the platform, including GPU, CPU, and Neural Engine."}],"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","title":"Metal Performance Shaders Graph","type":"topic"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphConvolution2DOpDescriptor":{"title":"MPSGraphConvolution2DOpDescriptor","kind":"symbol","type":"topic","url":"/documentation/metalperformanceshadersgraph/mpsgraphconvolution2dopdescriptor","navigatorTitle":[{"kind":"identifier","text":"MPSGraphConvolution2DOpDescriptor"}],"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphConvolution2DOpDescriptor","abstract":[{"text":"A class that describes the properties of a 2D-convolution operator.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPSGraphConvolution2DOpDescriptor","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"deprecated":false,"name":"iOS","introducedAt":"14.0","unavailable":false},{"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"14.0","unavailable":false},{"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false},{"beta":false,"deprecated":false,"name":"macOS","introducedAt":"11.0","unavailable":false},{"beta":false,"deprecated":false,"name":"tvOS","introducedAt":"14.0","unavailable":false},{"beta":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0","unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"dataLayout","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"dataLayout","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphConvolution2DOpDescriptor"]]},"op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MPSGraphTensorNamedDataLayout","text":"MPSGraphTensorNamedDataLayout","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensorNamedDataLayout"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataLayout"},{"kind":"text","text":";"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":"dataLayout","op":"replace","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphConvolution2DOpDescriptor~1dataLayout/title"},{"value":[{"kind":"identifier","text":"dataLayout"}],"op":"replace","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphConvolution2DOpDescriptor~1dataLayout/fragments"},{"value":"MPSGraphTensorNamedDataLayout","op":"replace","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensorNamedDataLayout/title"},{"value":[{"kind":"identifier","text":"MPSGraphTensorNamedDataLayout"}],"op":"replace","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensorNamedDataLayout/fragments"},{"value":[{"kind":"identifier","text":"MPSGraphTensorNamedDataLayout"}],"op":"replace","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensorNamedDataLayout/navigatorTitle"},{"value":"MPSGraphConvolution2DOpDescriptor","op":"replace","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphConvolution2DOpDescriptor/title"},{"value":[{"text":"MPSGraphConvolution2DOpDescriptor","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphConvolution2DOpDescriptor/fragments"},{"value":[{"text":"MPSGraphConvolution2DOpDescriptor","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphConvolution2DOpDescriptor/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}