{"seeAlsoSections":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/LocationAwarenessPG/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009497"]},{"title":"Creating a placemark object","generated":true,"anchor":"Creating-a-placemark-object","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKPlacemark/init(coordinate:)","doc://com.apple.mapkit/documentation/MapKit/MKPlacemark/init(coordinate:postalAddress:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/mapkit/mkplacemark/init(coordinate:addressdictionary:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/mapkit/mkplacemark/init(coordinate:addressdictionary:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"coordinate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","identifier":"doc://com.externally.resolved.symbol/c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addressDictionary"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","identifier":"doc://com.externally.resolved.symbol/s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The geographic coordinate to associate with the placemark.","type":"text"}],"type":"paragraph"}],"name":"coordinate"},{"content":[{"inlineContent":[{"type":"text","text":"A dictionary containing keys and values from an Address Book record. For a list of strings that you can use for the keys of this dictionary, see the “Address Property” constants in "},{"type":"codeVoice","code":"ABPerson"},{"type":"text","text":". All of the keys in should be at the top level of the dictionary."}],"type":"paragraph"}],"name":"addressDictionary"}],"kind":"parameters"},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"An initialized ","type":"text"},{"code":"MKPlacemark","type":"codeVoice"},{"text":" object.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"You can create placemark objects manually for entities for which you already have address information, such as contacts in the Address Book. Creating a placemark object explicitly avoids the need to query the reverse geocoder object for the same information.","type":"text"}]}],"kind":"content"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"modules":[{"name":"MapKit"}],"title":"init(coordinate:addressDictionary:)","platforms":[{"introducedAt":"3.0","deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"introducedAt":"3.0","deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"introducedAt":"13.1","deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false},{"introducedAt":"10.9","deprecated":false,"beta":false,"name":"macOS","unavailable":false},{"introducedAt":"9.2","deprecated":false,"beta":false,"name":"tvOS","unavailable":false},{"deprecated":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0","beta":false},{"deprecated":false,"name":"watchOS","unavailable":false,"introducedAt":"2.0","beta":false}],"symbolKind":"init","roleHeading":"Initializer","role":"symbol","externalID":"c:objc(cs)MKPlacemark(im)initWithCoordinate:addressDictionary:","navigatorTitle":[{"kind":"identifier","text":"initWithCoordinate:addressDictionary:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"coordinate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addressDictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}]},"abstract":[{"type":"text","text":"Creates and returns a placemark object using the specified coordinate and Address Book dictionary."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.mapkit/documentation/MapKit","doc://com.apple.mapkit/documentation/MapKit/MKPlacemark"]]},"identifier":{"url":"doc://com.apple.mapkit/documentation/MapKit/MKPlacemark/init(coordinate:addressDictionary:)","interfaceLanguage":"swift"},"references":{"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"kind":"technologies","role":"overview","url":"/documentation/technologies","type":"topic","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.mapkit/documentation/MapKit/MKPlacemark":{"abstract":[{"type":"text","text":"A user-friendly description of a location on the map."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MKPlacemark"}],"url":"/documentation/mapkit/mkplacemark","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKPlacemark"}],"title":"MKPlacemark","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKPlacemark","type":"topic","role":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/MKPlacemark/init(coordinate:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"coordinate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":")","kind":"text"}],"kind":"symbol","title":"init(coordinate:)","navigatorTitle":[{"kind":"identifier","text":"initWithCoordinate:"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKPlacemark/init(coordinate:)","abstract":[{"type":"text","text":"Creates and returns a placemark object using the specified coordinate."}],"url":"/documentation/mapkit/mkplacemark/init(coordinate:)","role":"symbol"},"doc://com.apple.mapkit/documentation/MapKit":{"identifier":"doc://com.apple.mapkit/documentation/MapKit","type":"topic","role":"collection","url":"/documentation/mapkit","title":"MapKit","kind":"symbol","abstract":[{"type":"text","text":"Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates."}]},"doc://com.apple.mapkit/documentation/MapKit/MKPlacemark/init(coordinate:postalAddress:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithCoordinate:postalAddress:"}],"role":"symbol","title":"init(coordinate:postalAddress:)","kind":"symbol","abstract":[{"type":"text","text":"Creates and returns a placemark object with the specified coordinate and postal address from the user’s Contacts database."}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKPlacemark/init(coordinate:postalAddress:)","type":"topic","url":"/documentation/mapkit/mkplacemark/init(coordinate:postaladdress:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"coordinate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"postalAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CNPostalAddress","text":"CNPostalAddress"},{"kind":"text","text":")"}]},"https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/LocationAwarenessPG/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009497":{"titleInlineContent":[{"type":"text","text":"Location and Maps Programming Guide"}],"url":"https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/LocationAwarenessPG/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009497","type":"link","title":"Location and Maps Programming Guide","identifier":"https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/LocationAwarenessPG/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009497"},"doc://com.externally.resolved.symbol/c:@S@CLLocationCoordinate2D":{"url":"/documentation/CoreLocation/CLLocationCoordinate2D","title":"CLLocationCoordinate2D","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@S@CLLocationCoordinate2D","type":"topic","abstract":[{"type":"text","text":"The latitude and longitude associated with a location, specified using the WGS 84 reference frame."}]},"doc://com.apple.mapkit/documentation/MapKit/MKPlacemark/init(coordinate:addressDictionary:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"coordinate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"addressDictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"kind":"symbol","title":"init(coordinate:addressDictionary:)","navigatorTitle":[{"kind":"identifier","text":"initWithCoordinate:addressDictionary:"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKPlacemark/init(coordinate:addressDictionary:)","abstract":[{"type":"text","text":"Creates and returns a placemark object using the specified coordinate and Address Book dictionary."}],"url":"/documentation/mapkit/mkplacemark/init(coordinate:addressdictionary:)","role":"symbol"},"doc://com.externally.resolved.symbol/s:SS":{"role":"symbol","title":"String","url":"/documentation/Swift/String","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"type":"topic","identifier":"doc://com.externally.resolved.symbol/s:SS","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"introducedAt":"3.0","deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"introducedAt":"3.0","deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"introducedAt":"13.1","deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false},{"introducedAt":"10.9","deprecated":false,"beta":false,"name":"macOS","unavailable":false},{"introducedAt":"9.2","deprecated":false,"beta":false,"name":"tvOS","unavailable":false},{"introducedAt":"1.0","deprecated":false,"beta":false,"name":"visionOS","unavailable":false},{"deprecated":false,"name":"watchOS","unavailable":false,"introducedAt":"2.0","beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"initWithCoordinate:addressDictionary:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCoordinate:addressDictionary:","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.mapkit/documentation/MapKit","doc://com.apple.mapkit/documentation/MapKit/MKPlacemark"]]},"path":"/hierarchy","op":"replace"},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/LocationAwarenessPG/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009497"],"title":"Related Documentation","anchor":"Related-Documentation"},{"identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKPlacemark/init(coordinate:)","doc://com.apple.mapkit/documentation/MapKit/MKPlacemark/init(coordinate:postalAddress:)"],"title":"Creating a placemark object","generated":true,"anchor":"Creating-a-placemark-object"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithCoordinate:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","identifier":"doc://com.externally.resolved.symbol/c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"coordinate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"addressDictionary:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"addressDictionary","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The geographic coordinate to associate with the placemark.","type":"text"}],"type":"paragraph"}],"name":"coordinate"},{"content":[{"inlineContent":[{"type":"text","text":"A dictionary containing keys and values from an Address Book record. For a list of strings that you can use for the keys of this dictionary, see the “Address Property” constants in "},{"type":"codeVoice","code":"ABPerson"},{"type":"text","text":". All of the keys in should be at the top level of the dictionary."}],"type":"paragraph"}],"name":"addressDictionary"}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"/primaryContentSections/2","value":{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An initialized "},{"type":"codeVoice","code":"MKPlacemark"},{"type":"text","text":" object."}]}],"kind":"content"}},{"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPlacemark/title","value":"MKPlacemark","op":"replace"},{"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPlacemark/fragments","value":[{"text":"MKPlacemark","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPlacemark/navigatorTitle","value":[{"kind":"identifier","text":"MKPlacemark"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPlacemark~1init(coordinate:)/title","value":"initWithCoordinate:","op":"replace"},{"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPlacemark~1init(coordinate:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCoordinate:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPlacemark~1init(coordinate:postalAddress:)/title","value":"initWithCoordinate:postalAddress:","op":"replace"},{"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPlacemark~1init(coordinate:postalAddress:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoordinate:postalAddress:"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@S@CLLocationCoordinate2D/fragments","value":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CLLocationCoordinate2D"},{"kind":"text","text":";"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPlacemark~1init(coordinate:addressDictionary:)/title","value":"initWithCoordinate:addressDictionary:","op":"replace"},{"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPlacemark~1init(coordinate:addressDictionary:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoordinate:addressDictionary:"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}