{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/watchkit/wkaudiofileplayer/replacecurrentitem(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/watchkit/wkaudiofileplayer/replacecurrentitem(with:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer/replaceCurrentItem(with:)"},"abstract":[{"type":"text","text":"Replaces the current player item with a different one."}],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer/init(playerItem:)"],"anchor":"Creating-a-Player","title":"Creating a Player"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replaceCurrentItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"item","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerItem","text":"WKAudioFilePlayerItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKAudioFilePlayerItem"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["watchOS"]}],"kind":"declarations"},{"parameters":[{"name":"item","content":[{"type":"paragraph","inlineContent":[{"text":"The player item whose contents you want to play.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"text":"Discussion","anchor":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"The default implementation of this method does nothing. Subclasses can override it to implement support for swapping out the current player item for a new one.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"modules":[{"name":"WatchKit"}],"externalID":"c:objc(cs)WKAudioFilePlayer(im)replaceCurrentItemWithPlayerItem:","role":"symbol","symbolKind":"method","platforms":[{"introducedAt":"2.0","unavailable":false,"beta":false,"name":"watchOS","deprecatedAt":"6.0","deprecated":false}],"roleHeading":"Instance Method","title":"replaceCurrentItem(with:)","navigatorTitle":[{"kind":"identifier","text":"replaceCurrentItemWithPlayerItem:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"replaceCurrentItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)WKAudioFilePlayerItem","kind":"typeIdentifier","text":"WKAudioFilePlayerItem"},{"kind":"text","text":"?)"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.watchkit/documentation/WatchKit","doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer"]]},"kind":"symbol","references":{"doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerItem":{"abstract":[{"type":"text","text":"An object that manages the presentation state of an audio file while it is playing."}],"type":"topic","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerItem","title":"WKAudioFilePlayerItem","role":"symbol","url":"/documentation/watchkit/wkaudiofileplayeritem","kind":"symbol","deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WKAudioFilePlayerItem","kind":"identifier"}],"navigatorTitle":[{"text":"WKAudioFilePlayerItem","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","abstract":[{"type":"text","text":""}],"role":"overview","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies"},"doc://com.apple.watchkit/documentation/WatchKit":{"kind":"symbol","abstract":[{"type":"text","text":"Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions."}],"role":"collection","type":"topic","identifier":"doc://com.apple.watchkit/documentation/WatchKit","title":"WatchKit","url":"/documentation/watchkit"},"doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer/replaceCurrentItem(with:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"replaceCurrentItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKAudioFilePlayerItem","text":"WKAudioFilePlayerItem"},{"kind":"text","text":"?)"}],"identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer/replaceCurrentItem(with:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"replaceCurrentItemWithPlayerItem:"}],"url":"/documentation/watchkit/wkaudiofileplayer/replacecurrentitem(with:)","title":"replaceCurrentItem(with:)","abstract":[{"type":"text","text":"Replaces the current player item with a different one."}],"role":"symbol","deprecated":true},"doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer/init(playerItem:)":{"kind":"symbol","fragments":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"playerItem","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WKAudioFilePlayerItem","preciseIdentifier":"c:objc(cs)WKAudioFilePlayerItem","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer/init(playerItem:)","type":"topic","navigatorTitle":[{"text":"playerWithPlayerItem:","kind":"identifier"}],"url":"/documentation/watchkit/wkaudiofileplayer/init(playeritem:)","title":"init(playerItem:)","abstract":[{"type":"text","text":"Creates and returns a player initialized with the specified player item."}],"role":"symbol","deprecated":true},"doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer":{"identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer","role":"symbol","abstract":[{"text":"An object that controls playback of a single audio item.","type":"text"}],"title":"WKAudioFilePlayer","type":"topic","kind":"symbol","navigatorTitle":[{"text":"WKAudioFilePlayer","kind":"identifier"}],"deprecated":true,"url":"/documentation/watchkit/wkaudiofileplayer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WKAudioFilePlayer","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"introducedAt":"2.0","name":"watchOS","beta":false,"deprecatedAt":"6.0","unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"replaceCurrentItemWithPlayerItem:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"replaceCurrentItemWithPlayerItem:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.watchkit/documentation/WatchKit","doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer"]]}},{"path":"/topicSections","op":"add","value":null},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Creating a Player","anchor":"Creating-a-Player","identifiers":["doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer/init(playerItem:)"],"generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["watchOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"replaceCurrentItemWithPlayerItem:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerItem","text":"WKAudioFilePlayerItem","preciseIdentifier":"c:objc(cs)WKAudioFilePlayerItem","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"item","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The player item whose contents you want to play."}]}],"name":"item"}],"kind":"parameters"},"path":"/primaryContentSections/1","op":"replace"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayerItem/title","op":"replace","value":"WKAudioFilePlayerItem"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayerItem/fragments","op":"replace","value":[{"text":"WKAudioFilePlayerItem","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayerItem/navigatorTitle","op":"replace","value":[{"text":"WKAudioFilePlayerItem","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayer~1replaceCurrentItem(with:)/title","op":"replace","value":"replaceCurrentItemWithPlayerItem:"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayer~1replaceCurrentItem(with:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"replaceCurrentItemWithPlayerItem:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayer~1init(playerItem:)/title","op":"replace","value":"playerWithPlayerItem:"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayer~1init(playerItem:)/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"playerWithPlayerItem:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayer/title","op":"replace","value":"WKAudioFilePlayer"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayer/fragments","op":"replace","value":[{"text":"WKAudioFilePlayer","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayer/navigatorTitle","op":"replace","value":[{"text":"WKAudioFilePlayer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}