{
  "abstract": [
    {
      "text": "Tells the delegate that part of the incrementally loaded image data is available.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:didLoadPartOfRepresentation:withValidRows:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSImageDelegate(im)image:didLoadPartOfRepresentation:withValidRows:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "image:didLoadPartOfRepresentation:withValidRows:"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "image:didLoadPartOfRepresentation:withValidRows:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.4",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "image:didLoadPartOfRepresentation:withValidRows:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "image:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSImage",
              "text": "NSImage"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "image"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "didLoadPartOfRepresentation:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageRep",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSImageRep",
              "text": "NSImageRep"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "rep"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "withValidRows:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "rows"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The image object whose contents are being loaded.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "image"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The image representation object that is receiving and processing the image data.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "rep"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of rows of data that have been decompressed.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "rows"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is optional; incremental loading will continue if the delegate does not implement it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage": {
      "abstract": [
        {
          "text": "A high-level interface for manipulating image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "role": "symbol",
      "title": "NSImage",
      "type": "topic",
      "url": "/documentation/appkit/nsimage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/LoadStatus": {
      "abstract": [
        {
          "text": "Status values for incremental image loading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LoadStatus"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/LoadStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LoadStatus"
        }
      ],
      "role": "symbol",
      "title": "NSImage.LoadStatus",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/loadstatus"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods that you can use to respond to drawing failures and manage incremental loads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImageDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSImageDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsimagedelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:didLoadPartOfRepresentation:withValidRows:": {
      "abstract": [
        {
          "text": "Tells the delegate that part of the incrementally loaded image data is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "image:didLoadPartOfRepresentation:withValidRows:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:didLoadPartOfRepresentation:withValidRows:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "image:didLoadPartOfRepresentation:withValidRows:"
        }
      ],
      "role": "symbol",
      "title": "image:didLoadPartOfRepresentation:withValidRows:",
      "type": "topic",
      "url": "/documentation/appkit/nsimagedelegate/image:didloadpartofrepresentation:withvalidrows:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:didLoadRepresentation:withStatus:": {
      "abstract": [
        {
          "text": "Tells the delegate that an incrementally loaded image has been loaded and decompressed as completely as is possible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "image:didLoadRepresentation:withStatus:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:didLoadRepresentation:withStatus:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "image:didLoadRepresentation:withStatus:"
        }
      ],
      "role": "symbol",
      "title": "image:didLoadRepresentation:withStatus:",
      "type": "topic",
      "url": "/documentation/appkit/nsimagedelegate/image:didloadrepresentation:withstatus:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:didLoadRepresentationHeader:": {
      "abstract": [
        {
          "text": "Tells the delegate that enough data has been read to determine the size of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "image:didLoadRepresentationHeader:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:didLoadRepresentationHeader:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "image:didLoadRepresentationHeader:"
        }
      ],
      "role": "symbol",
      "title": "image:didLoadRepresentationHeader:",
      "type": "topic",
      "url": "/documentation/appkit/nsimagedelegate/image:didloadrepresentationheader:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:willLoadRepresentation:": {
      "abstract": [
        {
          "text": "Tells the delegate that the image object is about to access its underlying bitmap data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "image:willLoadRepresentation:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:willLoadRepresentation:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "image:willLoadRepresentation:"
        }
      ],
      "role": "symbol",
      "title": "image:willLoadRepresentation:",
      "type": "topic",
      "url": "/documentation/appkit/nsimagedelegate/image:willloadrepresentation:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageRep": {
      "abstract": [
        {
          "text": "A semiabstract superclass that provides subclasses that you use to draw an image from a particular type of source data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImageRep"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageRep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageRep"
        }
      ],
      "role": "symbol",
      "title": "NSImageRep",
      "type": "topic",
      "url": "/documentation/appkit/nsimagerep"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Incremental-Loads",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:didLoadRepresentation:withStatus:",
        "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:didLoadRepresentationHeader:",
        "doc://com.apple.appkit/documentation/AppKit/NSImageDelegate/image:willLoadRepresentation:",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/LoadStatus"
      ],
      "title": "Managing Incremental Loads"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageDelegate/title",
          "value": "NSImageDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/title",
          "value": "NSImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep/title",
          "value": "NSImageRep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1LoadStatus/title",
          "value": "NSImageLoadStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1LoadStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageLoadStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1LoadStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageLoadStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsimagedelegate/image:didloadpartofrepresentation:withvalidrows:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
