{
  "abstract": [
    {
      "text": "Returns the rectangle within which glyphs should be laid out for a text table block.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTextTable"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextTable/rect(for:layoutAt:in:textContainer:characterRange:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSTextTable(im)rectForBlock:layoutAtPoint:inRect:textContainer:characterRange:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rect"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSTextTableBlock",
        "text": "NSTextTableBlock"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "layoutAt"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSPoint",
        "text": "NSPoint"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "in"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSRect",
        "text": "NSRect"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "textContainer"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSTextContainer",
        "text": "NSTextContainer"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "characterRange"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "text": "NSRange"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSRect",
        "text": "NSRect"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "rectForBlock:layoutAtPoint:inRect:textContainer:characterRange:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "rect(for:layoutAt:in:textContainer:characterRange:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rect"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "block"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextTableBlock",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSTextTableBlock",
              "text": "NSTextTableBlock"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "layoutAt"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "startingPoint"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSPoint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSPoint",
              "text": "NSPoint"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "in"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "rect"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRect",
              "text": "NSRect"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "textContainer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContainer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSTextContainer",
              "text": "NSTextContainer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "characterRange"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "charRange"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "NSRange"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRect",
              "text": "NSRect"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The text table block that wants to determine where to layout its glyphs.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "block"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The location, in container coordinates, where layout begins.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "startingPoint"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The rectangle in which the block is constrained to lie. For top-level blocks, this is the container rectangle of ",
                  "type": "text"
                },
                {
                  "code": "textContainer",
                  "type": "codeVoice"
                },
                {
                  "text": "; for nested blocks, this is the layout rectangle of the enclosing block.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "rect"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The text container being used for the layout.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "textContainer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The range of the characters whose glyphs are to be drawn.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "charRange"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The rectangle within which glyphs should be laid out.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is called by the text table block ",
              "type": "text"
            },
            {
              "code": "block",
              "type": "codeVoice"
            },
            {
              "text": " to determine the rectangle within which glyphs should be laid out for the text table block.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContainer": {
      "abstract": [
        {
          "text": "A region where text layout occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextContainer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContainer"
        }
      ],
      "role": "symbol",
      "title": "NSTextContainer",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontainer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextTable": {
      "abstract": [
        {
          "text": "An object that represents a text table as a whole.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextTable"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextTable"
        }
      ],
      "role": "symbol",
      "title": "NSTextTable",
      "type": "topic",
      "url": "/documentation/appkit/nstexttable"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextTable/boundsRect(for:contentRect:in:textContainer:characterRange:)": {
      "abstract": [
        {
          "text": "Returns the rectangle the text table block actually occupies, including padding, borders, and margins.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boundsRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextTableBlock",
          "text": "NSTextTableBlock"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contentRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "textContainer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextContainer",
          "text": "NSTextContainer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "characterRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextTable/boundsRect(for:contentRect:in:textContainer:characterRange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "boundsRectForBlock:contentRect:inRect:textContainer:characterRange:"
        }
      ],
      "role": "symbol",
      "title": "boundsRect(for:contentRect:in:textContainer:characterRange:)",
      "type": "topic",
      "url": "/documentation/appkit/nstexttable/boundsrect(for:contentrect:in:textcontainer:characterrange:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextTable/rect(for:layoutAt:in:textContainer:characterRange:)": {
      "abstract": [
        {
          "text": "Returns the rectangle within which glyphs should be laid out for a text table block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextTableBlock",
          "text": "NSTextTableBlock"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "layoutAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "textContainer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextContainer",
          "text": "NSTextContainer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "characterRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextTable/rect(for:layoutAt:in:textContainer:characterRange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectForBlock:layoutAtPoint:inRect:textContainer:characterRange:"
        }
      ],
      "role": "symbol",
      "title": "rect(for:layoutAt:in:textContainer:characterRange:)",
      "type": "topic",
      "url": "/documentation/appkit/nstexttable/rect(for:layoutat:in:textcontainer:characterrange:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextTableBlock": {
      "abstract": [
        {
          "text": "A text block that appears as a cell in a text table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextTableBlock"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextTableBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextTableBlock"
        }
      ],
      "role": "symbol",
      "title": "NSTextTableBlock",
      "type": "topic",
      "url": "/documentation/appkit/nstexttableblock"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@_NSRange": {
      "abstract": [
        {
          "text": "A Swift-only concrete structure that backs the range type alias.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "_NSRange"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@_NSRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "_NSRange",
      "type": "topic",
      "url": "/documentation/foundation/nsrange-jio"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSPoint": {
      "abstract": [
        {
          "text": "A point in a Cartesian coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSPoint",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPoint",
      "type": "topic",
      "url": "/documentation/foundation/nspoint"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSRect": {
      "abstract": [
        {
          "text": "A rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRect",
      "type": "topic",
      "url": "/documentation/foundation/nsrect"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Determining-layout-rectangles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextTable/boundsRect(for:contentRect:in:textContainer:characterRange:)"
      ],
      "title": "Determining layout rectangles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "rectForBlock:layoutAtPoint:inRect:textContainer:characterRange:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rectForBlock:layoutAtPoint:inRect:textContainer:characterRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTextTable"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Determining-layout-rectangles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextTable/boundsRect(for:contentRect:in:textContainer:characterRange:)"
              ],
              "title": "Determining layout rectangles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSRect",
                    "text": "NSRect"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "rectForBlock:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextTableBlock",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSTextTableBlock",
                    "text": "NSTextTableBlock"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "block"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "layoutAtPoint:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSPoint",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSPoint",
                    "text": "NSPoint"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "startingPoint"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "inRect:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSRect",
                    "text": "NSRect"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "rect"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "textContainer:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContainer",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSTextContainer",
                    "text": "NSTextContainer"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "textContainer"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "characterRange:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@_NSRange",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@_NSRange",
                    "text": "NSRange"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "charRange"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The text table block that wants to determine where to layout its glyphs.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "block"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The location, in container coordinates, where layout begins.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "startingPoint"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The rectangle in which the block is constrained to lie. For top-level blocks, this is the container rectangle of ",
                        "type": "text"
                      },
                      {
                        "code": "textContainer",
                        "type": "codeVoice"
                      },
                      {
                        "text": "; for nested blocks, this is the layout rectangle of the enclosing block.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "rect"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The text container being used for the layout.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "textContainer"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The range of the characters whose glyphs are to be drawn.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "charRange"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The rectangle within which glyphs should be laid out.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTable/title",
          "value": "NSTextTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTableBlock/title",
          "value": "NSTextTableBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTableBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTableBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTableBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTableBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTable~1boundsRect(for:contentRect:in:textContainer:characterRange:)/title",
          "value": "boundsRectForBlock:contentRect:inRect:textContainer:characterRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTable~1boundsRect(for:contentRect:in:textContainer:characterRange:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "boundsRectForBlock:contentRect:inRect:textContainer:characterRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContainer/title",
          "value": "NSTextContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTable~1rect(for:layoutAt:in:textContainer:characterRange:)/title",
          "value": "rectForBlock:layoutAtPoint:inRect:textContainer:characterRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTable~1rect(for:layoutAt:in:textContainer:characterRange:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rectForBlock:layoutAtPoint:inRect:textContainer:characterRange:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstexttable/rect(for:layoutat:in:textcontainer:characterrange:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstexttable/rect(for:layoutat:in:textcontainer:characterrange:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
