{
  "abstract": [
    {
      "text": "The word contains the search string as a prefix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/startsWith"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UITextSearchMatchMethod@UITextSearchMatchMethodStartsWith",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "startsWith"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITextSearchMatchMethodStartsWith"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UITextSearchOptions.WordMatchMethod.startsWith"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "startsWith"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions": {
      "abstract": [
        {
          "text": "An object containing the configurable options for a text search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSearchOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchOptions"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchOptions",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the method to use when searching text for words that match a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WordMatchMethod"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WordMatchMethod"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchOptions.WordMatchMethod",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/contains": {
      "abstract": [
        {
          "text": "The word contains the search string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contains"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/contains",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchMatchMethodContains"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchOptions.WordMatchMethod.contains",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.enum/contains"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/fullWord": {
      "abstract": [
        {
          "text": "The word matches the search string exactly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullWord"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/fullWord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchMatchMethodFullWord"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchOptions.WordMatchMethod.fullWord",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.enum/fullword"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/startsWith": {
      "abstract": [
        {
          "text": "The word contains the search string as a prefix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startsWith"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/startsWith",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchMatchMethodStartsWith"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchOptions.WordMatchMethod.startsWith",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.enum/startswith"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/contains",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/fullWord"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITextSearchMatchMethodStartsWith"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethodStartsWith"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/contains",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum/fullWord"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UITextSearchMatchMethodStartsWith"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum~1contains/title",
          "value": "UITextSearchMatchMethodContains"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum~1contains/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethodContains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum~1startsWith/title",
          "value": "UITextSearchMatchMethodStartsWith"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum~1startsWith/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethodStartsWith"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum/title",
          "value": "UITextSearchMatchMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum~1fullWord/title",
          "value": "UITextSearchMatchMethodFullWord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum~1fullWord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethodFullWord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions/title",
          "value": "UITextSearchOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.enum/startswith"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.enum/startswith"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
