{
  "abstract": [
    {
      "text": "A range of time within which the user arrives at a location of interest.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit/arrivalDateInterval"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SRVisit(py)arrivalDateInterval",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "arrivalDateInterval"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation12DateIntervalV",
        "text": "DateInterval"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "arrivalDateInterval"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "arrivalDateInterval"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "arrivalDateInterval"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation12DateIntervalV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation12DateIntervalV",
              "text": "DateInterval"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit": {
      "abstract": [
        {
          "text": "The user’s progress in their daily travel routine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRVisit"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRVisit"
        }
      ],
      "role": "symbol",
      "title": "SRVisit",
      "type": "topic",
      "url": "/documentation/sensorkit/srvisit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit/LocationCategory-swift.enum": {
      "abstract": [
        {
          "text": "Types of locations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LocationCategory"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit/LocationCategory-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LocationCategory"
        }
      ],
      "role": "symbol",
      "title": "SRVisit.LocationCategory",
      "type": "topic",
      "url": "/documentation/sensorkit/srvisit/locationcategory-swift.enum"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit/arrivalDateInterval": {
      "abstract": [
        {
          "text": "A range of time within which the user arrives at a location of interest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrivalDateInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12DateIntervalV",
          "text": "DateInterval"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit/arrivalDateInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "arrivalDateInterval"
        }
      ],
      "role": "symbol",
      "title": "arrivalDateInterval",
      "type": "topic",
      "url": "/documentation/sensorkit/srvisit/arrivaldateinterval"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit/departureDateInterval": {
      "abstract": [
        {
          "text": "A range of time within which the user departs from a location of interest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "departureDateInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12DateIntervalV",
          "text": "DateInterval"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit/departureDateInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "departureDateInterval"
        }
      ],
      "role": "symbol",
      "title": "departureDateInterval",
      "type": "topic",
      "url": "/documentation/sensorkit/srvisit/departuredateinterval"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit/distanceFromHome": {
      "abstract": [
        {
          "text": "The location’s distance from the home-category location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distanceFromHome"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDistance",
          "text": "CLLocationDistance"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit/distanceFromHome",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "distanceFromHome"
        }
      ],
      "role": "symbol",
      "title": "distanceFromHome",
      "type": "topic",
      "url": "/documentation/sensorkit/srvisit/distancefromhome"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit/locationCategory-swift.property": {
      "abstract": [
        {
          "text": "The location’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRVisit",
          "text": "SRVisit"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SRLocationCategory",
          "text": "LocationCategory"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit/locationCategory-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locationCategory"
        }
      ],
      "role": "symbol",
      "title": "locationCategory",
      "type": "topic",
      "url": "/documentation/sensorkit/srvisit/locationcategory-swift.property"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation12DateIntervalV": {
      "abstract": [
        {
          "text": "The span of time between a specific start date and end date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "DateInterval"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation12DateIntervalV",
      "kind": "symbol",
      "role": "symbol",
      "title": "DateInterval",
      "type": "topic",
      "url": "/documentation/foundation/dateinterval"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Visit-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit/departureDateInterval",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit/distanceFromHome",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit/locationCategory-swift.property",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit/LocationCategory-swift.enum"
      ],
      "title": "Accessing Visit Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "arrivalDateInterval"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "arrivalDateInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Visit-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit/departureDateInterval",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit/distanceFromHome",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit/locationCategory-swift.property",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRVisit/LocationCategory-swift.enum"
              ],
              "title": "Accessing Visit Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSDateInterval",
                    "text": "NSDateInterval"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "arrivalDateInterval"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit/title",
          "value": "SRVisit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRVisit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRVisit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit~1distanceFromHome/title",
          "value": "distanceFromHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit~1distanceFromHome/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "distanceFromHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit~1locationCategory-swift.property/title",
          "value": "locationCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit~1locationCategory-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "locationCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit~1arrivalDateInterval/title",
          "value": "arrivalDateInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit~1arrivalDateInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "arrivalDateInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit~1departureDateInterval/title",
          "value": "departureDateInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit~1departureDateInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "departureDateInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit~1LocationCategory-swift.enum/title",
          "value": "SRLocationCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit~1LocationCategory-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRLocationCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit~1LocationCategory-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRLocationCategory"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srvisit/arrivaldateinterval"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srvisit/arrivaldateinterval"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
