{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ASWebAuthenticationSessionErrorCode instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safariservices/documentation/SafariServices",
        "doc://com.apple.safariservices/documentation/SafariServices/SFAuthenticationError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safariservices/documentation/SafariServices/SFAuthenticationError-swift.struct/canceledLogin"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC21SFAuthenticationErrorLeV13canceledLoginSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "canceledLogin"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC21SFAuthenticationErrorLeV",
        "text": "SFAuthenticationError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SFAuthenticationError",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Safari Services"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "11.0",
        "message": "Use ASWebAuthenticationSessionErrorCode instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "11.0",
        "message": "Use ASWebAuthenticationSessionErrorCode instead",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "canceledLogin"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "canceledLogin"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFAuthenticationError-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC21SFAuthenticationErrorLeV",
              "text": "SFAuthenticationError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFAuthenticationError-swift.struct/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SFAuthenticationError",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safariservices/documentation/SafariServices": {
      "abstract": [
        {
          "text": "Enable web views and services in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Safari Services",
      "type": "topic",
      "url": "/documentation/safariservices"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFAuthenticationError-swift.struct": {
      "abstract": [
        {
          "text": "An authentication error.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFAuthenticationError"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFAuthenticationError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFAuthenticationError"
        }
      ],
      "role": "symbol",
      "title": "SFAuthenticationError",
      "type": "topic",
      "url": "/documentation/safariservices/sfauthenticationerror-swift.struct"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFAuthenticationError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Messages that describe an authentication error.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFAuthenticationError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SFAuthenticationError.Code",
      "type": "topic",
      "url": "/documentation/safariservices/sfauthenticationerror-swift.struct/code"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFAuthenticationError-swift.struct/canceledLogin": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canceledLogin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21SFAuthenticationErrorLeV",
          "text": "SFAuthenticationError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SFAuthenticationError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFAuthenticationError-swift.struct/canceledLogin",
      "kind": "symbol",
      "role": "symbol",
      "title": "canceledLogin",
      "type": "topic",
      "url": "/documentation/safariservices/sfauthenticationerror-swift.struct/canceledlogin"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFAuthenticationError-swift.struct~1Code/title",
          "value": "SFAuthenticationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFAuthenticationError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthenticationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFAuthenticationError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthenticationError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safariservices/sfauthenticationerror-swift.struct/canceledlogin"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
