{
  "abstract": [
    {
      "text": "The color of the fog effect to be rendered with the scene. Animatable.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNScene"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNScene/fogColor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SCNScene(py)fogColor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "fogColor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "keyword",
        "text": "Any"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "fogColor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "fogColor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "fogColor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property’s value can be an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSColor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object (in macOS), a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIColor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object (in iOS), or a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgcolor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. The default fog color is white.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can animate changes to this property’s value. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppKit/NSColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity (alpha value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSColor",
      "type": "topic",
      "url": "/documentation/AppKit/NSColor"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIColor",
      "type": "topic",
      "url": "/documentation/UIKit/UIColor"
    },
    "doc://com.apple.documentation/documentation/coregraphics/cgcolor": {
      "abstract": [
        {
          "text": "A set of components that define a color, with a color space specifying how to interpret them.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CGColor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgcolor",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGColor",
      "type": "topic",
      "url": "/documentation/coregraphics/cgcolor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNScene": {
      "abstract": [
        {
          "text": "A container for the node hierarchy and global properties that together form a displayable 3D scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNScene"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNScene"
        }
      ],
      "role": "symbol",
      "title": "SCNScene",
      "type": "topic",
      "url": "/documentation/scenekit/scnscene"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNScene/fogColor": {
      "abstract": [
        {
          "text": "The color of the fog effect to be rendered with the scene. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fogColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNScene/fogColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fogColor"
        }
      ],
      "role": "symbol",
      "title": "fogColor",
      "type": "topic",
      "url": "/documentation/scenekit/scnscene/fogcolor"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNScene/fogDensityExponent": {
      "abstract": [
        {
          "text": "The transition curve for the fog’s intensity between its start and end distances. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fogDensityExponent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNScene/fogDensityExponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fogDensityExponent"
        }
      ],
      "role": "symbol",
      "title": "fogDensityExponent",
      "type": "topic",
      "url": "/documentation/scenekit/scnscene/fogdensityexponent"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNScene/fogEndDistance": {
      "abstract": [
        {
          "text": "The distance from a point of view at which the scene’s contents are completely obscured by fog. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fogEndDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNScene/fogEndDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fogEndDistance"
        }
      ],
      "role": "symbol",
      "title": "fogEndDistance",
      "type": "topic",
      "url": "/documentation/scenekit/scnscene/fogenddistance"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNScene/fogStartDistance": {
      "abstract": [
        {
          "text": "The distance from a point of view at which the scene’s contents begin to be obscured by fog. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fogStartDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNScene/fogStartDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fogStartDistance"
        }
      ],
      "role": "symbol",
      "title": "fogStartDistance",
      "type": "topic",
      "url": "/documentation/scenekit/scnscene/fogstartdistance"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content": {
      "abstract": [
        {
          "text": "Learn about implicit animations, explicit animations, and actions, and when to choose each in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content",
      "kind": "article",
      "role": "article",
      "title": "Animating SceneKit Content",
      "type": "topic",
      "url": "/documentation/scenekit/animating-scenekit-content"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Adding-Fog-to-a-Scene",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNScene/fogStartDistance",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNScene/fogEndDistance",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNScene/fogDensityExponent"
      ],
      "title": "Adding Fog to a Scene"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "fogColor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fogColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNScene"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Adding-Fog-to-a-Scene",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNScene/fogStartDistance",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNScene/fogEndDistance",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNScene/fogDensityExponent"
              ],
              "title": "Adding Fog to a Scene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "retain"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "fogColor"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNScene~1fogStartDistance/title",
          "value": "fogStartDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNScene~1fogStartDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fogStartDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNScene/title",
          "value": "SCNScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNScene~1fogDensityExponent/title",
          "value": "fogDensityExponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNScene~1fogDensityExponent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fogDensityExponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNScene~1fogColor/title",
          "value": "fogColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNScene~1fogColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fogColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSColor/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSColor"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIColor/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIColor"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgcolor/title",
          "value": "CGColorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNScene~1fogEndDistance/title",
          "value": "fogEndDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNScene~1fogEndDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fogEndDistance"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnscene/fogcolor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnscene/fogcolor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
