{
  "abstract": [
    {
      "text": "You are performing the search but do not yet have the results.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/inProgress"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INSearchForMessagesIntentResponseCode@INSearchForMessagesIntentResponseCodeInProgress",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "inProgress"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INSearchForMessagesIntentResponseCodeInProgress"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INSearchForMessagesIntentResponseCode.inProgress"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "inProgress"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When handling the intent, return this code if your search may take longer than a few seconds to complete.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode": {
      "abstract": [
        {
          "text": "Constants that indicate the response state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchForMessagesIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMessagesIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMessagesIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/insearchformessagesintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/failure": {
      "abstract": [
        {
          "text": "You are unable to perform the search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMessagesIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMessagesIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/insearchformessagesintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/failureMessageServiceNotAvailable": {
      "abstract": [
        {
          "text": "You were unable to perform the search because your message service is currently unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureMessageServiceNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/failureMessageServiceNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMessagesIntentResponseCodeFailureMessageServiceNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMessagesIntentResponseCode.failureMessageServiceNotAvailable",
      "type": "topic",
      "url": "/documentation/intents/insearchformessagesintentresponsecode/failuremessageservicenotavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/failureMessageTooManyResults": {
      "abstract": [
        {
          "text": "Too many messages matched the specified search criteria.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureMessageTooManyResults"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/failureMessageTooManyResults",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMessagesIntentResponseCodeFailureMessageTooManyResults"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMessagesIntentResponseCode.failureMessageTooManyResults",
      "type": "topic",
      "url": "/documentation/intents/insearchformessagesintentresponsecode/failuremessagetoomanyresults"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [
        {
          "text": "The user must launch your app to search their messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMessagesIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMessagesIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/insearchformessagesintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/inProgress": {
      "abstract": [
        {
          "text": "You are performing the search but do not yet have the results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inProgress"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/inProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMessagesIntentResponseCodeInProgress"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMessagesIntentResponseCode.inProgress",
      "type": "topic",
      "url": "/documentation/intents/insearchformessagesintentresponsecode/inprogress"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/ready": {
      "abstract": [
        {
          "text": "A response code indicating app readiness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMessagesIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMessagesIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/insearchformessagesintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/success": {
      "abstract": [
        {
          "text": "You successfully handled the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMessagesIntentResponseCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMessagesIntentResponseCode.success",
      "type": "topic",
      "url": "/documentation/intents/insearchformessagesintentresponsecode/success"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/unspecified": {
      "abstract": [
        {
          "text": "The response code is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMessagesIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMessagesIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/insearchformessagesintentresponsecode/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Response-State",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/unspecified",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/ready",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/success",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/failure",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/failureRequiringAppLaunch",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/failureMessageServiceNotAvailable",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/failureMessageTooManyResults"
      ],
      "title": "Response State"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INSearchForMessagesIntentResponseCodeInProgress"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMessagesIntentResponseCodeInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Response-State",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/unspecified",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/ready",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/success",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/failure",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/failureRequiringAppLaunch",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/failureMessageServiceNotAvailable",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentResponseCode/failureMessageTooManyResults"
              ],
              "title": "Response State"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INSearchForMessagesIntentResponseCodeInProgress"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentResponseCode~1unspecified/title",
          "value": "INSearchForMessagesIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMessagesIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentResponseCode~1failureMessageServiceNotAvailable/title",
          "value": "INSearchForMessagesIntentResponseCodeFailureMessageServiceNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentResponseCode~1failureMessageServiceNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMessagesIntentResponseCodeFailureMessageServiceNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentResponseCode~1ready/title",
          "value": "INSearchForMessagesIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMessagesIntentResponseCodeReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentResponseCode~1failureMessageTooManyResults/title",
          "value": "INSearchForMessagesIntentResponseCodeFailureMessageTooManyResults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentResponseCode~1failureMessageTooManyResults/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMessagesIntentResponseCodeFailureMessageTooManyResults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentResponseCode~1success/title",
          "value": "INSearchForMessagesIntentResponseCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentResponseCode~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMessagesIntentResponseCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentResponseCode~1failure/title",
          "value": "INSearchForMessagesIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMessagesIntentResponseCodeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentResponseCode~1inProgress/title",
          "value": "INSearchForMessagesIntentResponseCodeInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentResponseCode~1inProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMessagesIntentResponseCodeInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INSearchForMessagesIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMessagesIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentResponseCode/title",
          "value": "INSearchForMessagesIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMessagesIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMessagesIntentResponseCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insearchformessagesintentresponsecode/inprogress"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insearchformessagesintentresponsecode/inprogress"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
