{
  "abstract": [
    {
      "text": "An identifier indicating a balance that represents points.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance",
        "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/BalanceType-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/BalanceType-swift.struct/loyaltyPoints"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "PassKit",
    "externalID": "c:@PKStoredValuePassBalanceTypeLoyaltyPoints",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "loyaltyPoints"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)PKStoredValuePassBalance",
        "text": "PKStoredValuePassBalance"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@PKStoredValuePassBalanceType",
        "text": "BalanceType"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKStoredValuePassBalanceTypeLoyaltyPoints"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "loyaltyPoints"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "loyaltyPoints"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PKStoredValuePassBalance",
              "text": "PKStoredValuePassBalance"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/BalanceType-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@PKStoredValuePassBalanceType",
              "text": "BalanceType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance": {
      "abstract": [
        {
          "text": "An object that represents a balance that’s available for transactions, such as points or money.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKStoredValuePassBalance"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStoredValuePassBalance"
        }
      ],
      "role": "symbol",
      "title": "PKStoredValuePassBalance",
      "type": "topic",
      "url": "/documentation/passkit/pkstoredvaluepassbalance"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/BalanceType-swift.struct": {
      "abstract": [
        {
          "text": "The type of value that the balance represents, such as money or points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BalanceType"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/BalanceType-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BalanceType"
        }
      ],
      "role": "symbol",
      "title": "PKStoredValuePassBalance.BalanceType",
      "type": "topic",
      "url": "/documentation/passkit/pkstoredvaluepassbalance/balancetype-swift.struct"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/BalanceType-swift.struct/cash": {
      "abstract": [
        {
          "text": "An identifier indicating a balance that represents money.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKStoredValuePassBalance",
          "text": "PKStoredValuePassBalance"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKStoredValuePassBalanceType",
          "text": "BalanceType"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/BalanceType-swift.struct/cash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStoredValuePassBalanceTypeCash"
        }
      ],
      "role": "symbol",
      "title": "cash",
      "type": "topic",
      "url": "/documentation/passkit/pkstoredvaluepassbalance/balancetype-swift.struct/cash"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/BalanceType-swift.struct/loyaltyPoints": {
      "abstract": [
        {
          "text": "An identifier indicating a balance that represents points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loyaltyPoints"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKStoredValuePassBalance",
          "text": "PKStoredValuePassBalance"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKStoredValuePassBalanceType",
          "text": "BalanceType"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/BalanceType-swift.struct/loyaltyPoints",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKStoredValuePassBalanceTypeLoyaltyPoints"
        }
      ],
      "role": "symbol",
      "title": "loyaltyPoints",
      "type": "topic",
      "url": "/documentation/passkit/pkstoredvaluepassbalance/balancetype-swift.struct/loyaltypoints"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reading-the-balance-type",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/BalanceType-swift.struct/cash"
      ],
      "title": "Reading the balance type"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKStoredValuePassBalanceTypeLoyaltyPoints"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassBalanceTypeLoyaltyPoints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reading-the-balance-type",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/BalanceType-swift.struct/cash"
              ],
              "title": "Reading the balance type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.passkit/documentation/PassKit/PKStoredValuePassBalance/BalanceType-swift.struct",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@PKStoredValuePassBalanceType",
                    "text": "PKStoredValuePassBalanceType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKStoredValuePassBalanceTypeLoyaltyPoints"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance~1BalanceType-swift.struct~1cash/title",
          "value": "PKStoredValuePassBalanceTypeCash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance~1BalanceType-swift.struct~1cash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassBalanceTypeCash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance/title",
          "value": "PKStoredValuePassBalance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassBalance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassBalance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance~1BalanceType-swift.struct~1loyaltyPoints/title",
          "value": "PKStoredValuePassBalanceTypeLoyaltyPoints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance~1BalanceType-swift.struct~1loyaltyPoints/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassBalanceTypeLoyaltyPoints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance~1BalanceType-swift.struct/title",
          "value": "PKStoredValuePassBalanceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance~1BalanceType-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassBalanceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKStoredValuePassBalance~1BalanceType-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKStoredValuePassBalanceType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkstoredvaluepassbalance/balancetype-swift.struct/loyaltypoints"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkstoredvaluepassbalance/balancetype-swift.struct/loyaltypoints"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
