{
  "abstract": [
    {
      "text": "The window can enter full-screen mode.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenPrimary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSWindowCollectionBehavior@NSWindowCollectionBehaviorFullScreenPrimary",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "fullScreenPrimary"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSWindow",
        "text": "NSWindow"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
        "text": "CollectionBehavior"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSWindowCollectionBehaviorFullScreenPrimary"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "fullScreenPrimary"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "fullScreenPrimary"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSWindow",
              "text": "NSWindow"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
              "text": "CollectionBehavior"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow": {
      "abstract": [
        {
          "text": "A window that an app displays on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "role": "symbol",
      "title": "NSWindow",
      "type": "topic",
      "url": "/documentation/appkit/nswindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct": {
      "abstract": [
        {
          "text": "Window collection behaviors related to Mission Control, Spaces, and Stage Manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CollectionBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.CollectionBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenAllowsTiling": {
      "abstract": [
        {
          "text": "The window can be a secondary full screen tile even if it can’t be a full screen window itself.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullScreenAllowsTiling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenAllowsTiling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorFullScreenAllowsTiling"
        }
      ],
      "role": "symbol",
      "title": "fullScreenAllowsTiling",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/fullscreenallowstiling"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenAuxiliary": {
      "abstract": [
        {
          "text": "The window displays on the same space as the full screen window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullScreenAuxiliary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenAuxiliary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorFullScreenAuxiliary"
        }
      ],
      "role": "symbol",
      "title": "fullScreenAuxiliary",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/fullscreenauxiliary"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenDisallowsTiling": {
      "abstract": [
        {
          "text": "The window doesn’t support being a full-screen tile window, but may support being a full-screen window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullScreenDisallowsTiling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenDisallowsTiling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorFullScreenDisallowsTiling"
        }
      ],
      "role": "symbol",
      "title": "fullScreenDisallowsTiling",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/fullscreendisallowstiling"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenNone": {
      "abstract": [
        {
          "text": "The window doesn’t support full-screen mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullScreenNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorFullScreenNone"
        }
      ],
      "role": "symbol",
      "title": "fullScreenNone",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/fullscreennone"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenPrimary": {
      "abstract": [
        {
          "text": "The window can enter full-screen mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullScreenPrimary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenPrimary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorFullScreenPrimary"
        }
      ],
      "role": "symbol",
      "title": "fullScreenPrimary",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/fullscreenprimary"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Full-screen",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenAuxiliary",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenNone",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenAllowsTiling",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenDisallowsTiling"
      ],
      "title": "Full screen"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSWindowCollectionBehaviorFullScreenPrimary"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorFullScreenPrimary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Full-screen",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenAuxiliary",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenNone",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenAllowsTiling",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenDisallowsTiling"
              ],
              "title": "Full screen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSWindowCollectionBehaviorFullScreenPrimary"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct/title",
          "value": "NSWindowCollectionBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenPrimary/title",
          "value": "NSWindowCollectionBehaviorFullScreenPrimary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenPrimary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorFullScreenPrimary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenDisallowsTiling/title",
          "value": "NSWindowCollectionBehaviorFullScreenDisallowsTiling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenDisallowsTiling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorFullScreenDisallowsTiling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title",
          "value": "NSWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenNone/title",
          "value": "NSWindowCollectionBehaviorFullScreenNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorFullScreenNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenAllowsTiling/title",
          "value": "NSWindowCollectionBehaviorFullScreenAllowsTiling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenAllowsTiling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorFullScreenAllowsTiling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenAuxiliary/title",
          "value": "NSWindowCollectionBehaviorFullScreenAuxiliary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenAuxiliary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorFullScreenAuxiliary"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nswindow/collectionbehavior-swift.struct/fullscreenprimary"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nswindow/collectionbehavior-swift.struct/fullscreenprimary"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
