{
  "abstract": [
    {
      "text": "Initializes a TLV record with the specified tag and value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSimpleTLVRecord"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSimpleTLVRecord/init(tag:value:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)TKSimpleTLVRecord(im)initWithTag:value:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "tag"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5UInt8V",
        "text": "UInt8"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "value"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation4DataV",
        "text": "Data"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "CryptoTokenKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithTag:value:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(tag:value:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "tag"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5UInt8V",
              "text": "UInt8"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "value"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DataV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4DataV",
              "text": "Data"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The tag field of the record.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tag"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The value field of the record.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "value"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new TLV record containing the specified tag and value fields.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit": {
      "abstract": [
        {
          "text": "Access security tokens and the cryptographic assets they store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CryptoTokenKit",
      "type": "topic",
      "url": "/documentation/cryptotokenkit"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSimpleTLVRecord": {
      "abstract": [
        {
          "text": "An object that implements encoding using Simple-TLV encoding according to ISO 7816-4.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TKSimpleTLVRecord"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSimpleTLVRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKSimpleTLVRecord"
        }
      ],
      "role": "symbol",
      "title": "TKSimpleTLVRecord",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tksimpletlvrecord"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSimpleTLVRecord/init(tag:value:)": {
      "abstract": [
        {
          "text": "Initializes a TLV record with the specified tag and value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "tag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSimpleTLVRecord/init(tag:value:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTag:value:"
        }
      ],
      "role": "symbol",
      "title": "init(tag:value:)",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tksimpletlvrecord/init(tag:value:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@UInt8": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@UInt8",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt8",
      "type": "topic",
      "url": "/documentation/driverkit/uint8"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSData": {
      "abstract": [
        {
          "text": "A static byte buffer that bridges to ; use  when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSData"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSData",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSData",
      "type": "topic",
      "url": "/documentation/foundation/nsdata"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation4DataV": {
      "abstract": [
        {
          "text": "A byte buffer in memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DataV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Data",
      "type": "topic",
      "url": "/documentation/foundation/data"
    },
    "doc://com.externally.resolved.symbol/s:s5UInt8V": {
      "abstract": [
        {
          "text": "An 8-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt8",
      "type": "topic",
      "url": "/documentation/Swift/UInt8"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithTag:value:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTag:value:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKSimpleTLVRecord"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithTag:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@UInt8",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UInt8",
                    "text": "UInt8"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "tag"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "value:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSData",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSData",
                    "text": "NSData"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "value"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The tag field of the record.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "tag"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The value field of the record.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "value"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new TLV record containing the specified tag and value fields.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSimpleTLVRecord~1init(tag:value:)/title",
          "value": "initWithTag:value:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSimpleTLVRecord~1init(tag:value:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTag:value:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSimpleTLVRecord/title",
          "value": "TKSimpleTLVRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSimpleTLVRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKSimpleTLVRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKSimpleTLVRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TKSimpleTLVRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSData/abstract",
          "value": [
            {
              "text": "A static byte buffer in memory.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cryptotokenkit/tksimpletlvrecord/init(tag:value:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cryptotokenkit/tksimpletlvrecord/init(tag:value:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
