{
  "abstract": [
    {
      "text": "A list of options that represent the kinds of data a message can contain.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext",
        "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UIMessageConversationEntryDataKind",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DataKind"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DataKind"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIMessageConversationContext.MessageEntry.DataKind"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DataKind"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext": {
      "abstract": [
        {
          "text": "A class that represents a message conversation.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMessageConversationContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMessageConversationContext"
        }
      ],
      "role": "symbol",
      "title": "UIMessageConversationContext",
      "type": "topic",
      "url": "/documentation/uikit/uimessageconversationcontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry": {
      "abstract": [
        {
          "text": "A class that represents a message in a message conversation.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MessageEntry"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MessageEntry"
        }
      ],
      "role": "symbol",
      "title": "UIMessageConversationContext.MessageEntry",
      "type": "topic",
      "url": "/documentation/uikit/uimessageconversationcontext/messageentry"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum": {
      "abstract": [
        {
          "text": "A list of options that represent the kinds of data a message can contain.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DataKind"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DataKind"
        }
      ],
      "role": "symbol",
      "title": "UIMessageConversationContext.MessageEntry.DataKind",
      "type": "topic",
      "url": "/documentation/uikit/uimessageconversationcontext/messageentry/datakind-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/attachment": {
      "abstract": [
        {
          "text": "The message contains an attachment, such as an image or file.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attachment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/attachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMessageConversationEntryDataKindAttachment"
        }
      ],
      "role": "symbol",
      "title": "UIMessageConversationContext.MessageEntry.DataKind.attachment",
      "type": "topic",
      "url": "/documentation/uikit/uimessageconversationcontext/messageentry/datakind-swift.enum/attachment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/init(rawValue:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uimessageconversationcontext/messageentry/datakind-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/other": {
      "abstract": [
        {
          "text": "The message contains other data, such as data that represents a sticker or a payment.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMessageConversationEntryDataKindOther"
        }
      ],
      "role": "symbol",
      "title": "UIMessageConversationContext.MessageEntry.DataKind.other",
      "type": "topic",
      "url": "/documentation/uikit/uimessageconversationcontext/messageentry/datakind-swift.enum/other"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/text": {
      "abstract": [
        {
          "text": "The message contains text.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/text",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMessageConversationEntryDataKindText"
        }
      ],
      "role": "symbol",
      "title": "UIMessageConversationContext.MessageEntry.DataKind.text",
      "type": "topic",
      "url": "/documentation/uikit/uimessageconversationcontext/messageentry/datakind-swift.enum/text"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/dataKind-swift.property": {
      "abstract": [
        {
          "text": "An item that represents the kind of data the message contains.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataKind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIMessageConversationContext",
          "text": "UIMessageConversationContext"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIMessageConversationEntry",
          "text": "MessageEntry"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIMessageConversationEntryDataKind",
          "text": "DataKind"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/dataKind-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataKind"
        }
      ],
      "role": "symbol",
      "title": "dataKind",
      "type": "topic",
      "url": "/documentation/uikit/uimessageconversationcontext/messageentry/datakind-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/wasSentBySelf": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the current user sent the message.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wasSentBySelf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/wasSentBySelf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wasSentBySelf"
        }
      ],
      "role": "symbol",
      "title": "wasSentBySelf",
      "type": "topic",
      "url": "/documentation/uikit/uimessageconversationcontext/messageentry/wassentbyself"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Categorizing-the-entry",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/dataKind-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/wasSentBySelf"
      ],
      "title": "Categorizing the entry"
    }
  ],
  "topicSections": [
    {
      "anchor": "Kinds-of-data-in-a-message",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/attachment",
        "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/other",
        "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/text"
      ],
      "title": "Kinds of data in a message"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIMessageConversationEntryDataKind"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationEntryDataKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationEntryDataKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Kinds-of-data-in-a-message",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/attachment",
                "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/other",
                "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/text"
              ],
              "title": "Kinds of data in a message"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Categorizing-the-entry",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/dataKind-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/wasSentBySelf"
              ],
              "title": "Categorizing the entry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIMessageConversationEntryDataKind"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1DataKind-swift.enum~1attachment/title",
          "value": "UIMessageConversationEntryDataKindAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1DataKind-swift.enum~1attachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationEntryDataKindAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1DataKind-swift.enum~1other/title",
          "value": "UIMessageConversationEntryDataKindOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1DataKind-swift.enum~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationEntryDataKindOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1DataKind-swift.enum/title",
          "value": "UIMessageConversationEntryDataKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1DataKind-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationEntryDataKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1DataKind-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationEntryDataKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry/title",
          "value": "UIMessageConversationEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext/title",
          "value": "UIMessageConversationContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1dataKind-swift.property/title",
          "value": "dataKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1dataKind-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dataKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1wasSentBySelf/title",
          "value": "wasSentBySelf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1wasSentBySelf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wasSentBySelf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1DataKind-swift.enum~1text/title",
          "value": "UIMessageConversationEntryDataKindText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1DataKind-swift.enum~1text/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationEntryDataKindText"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uimessageconversationcontext/messageentry/datakind-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uimessageconversationcontext/messageentry/datakind-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
