{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/SFNTLookupSingleHeader"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/SFNTLookupSingleHeader/init(binSearch:entries:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So22SFNTLookupSingleHeaderV9binSearch7entriesABSo0a6BinaryeC0V_So0aB0Vtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "binSearch"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@SFNTLookupBinarySearchHeader",
        "text": "SFNTLookupBinarySearchHeader"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "entries"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@SFNTLookupSingle",
        "text": "SFNTLookupSingle"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(binSearch:entries:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "binSearch"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/SFNTLookupBinarySearchHeader",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@SFNTLookupBinarySearchHeader",
              "text": "SFNTLookupBinarySearchHeader"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "entries"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/SFNTLookupSingle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@SFNTLookupSingle",
              "text": "SFNTLookupSingle"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/SFNTLookupBinarySearchHeader": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFNTLookupBinarySearchHeader"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/SFNTLookupBinarySearchHeader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFNTLookupBinarySearchHeader"
        }
      ],
      "role": "symbol",
      "title": "SFNTLookupBinarySearchHeader",
      "type": "topic",
      "url": "/documentation/coretext/sfntlookupbinarysearchheader"
    },
    "doc://com.apple.coretext/documentation/CoreText/SFNTLookupSingle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFNTLookupSingle"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/SFNTLookupSingle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFNTLookupSingle"
        }
      ],
      "role": "symbol",
      "title": "SFNTLookupSingle",
      "type": "topic",
      "url": "/documentation/coretext/sfntlookupsingle"
    },
    "doc://com.apple.coretext/documentation/CoreText/SFNTLookupSingleHeader": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFNTLookupSingleHeader"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/SFNTLookupSingleHeader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFNTLookupSingleHeader"
        }
      ],
      "role": "symbol",
      "title": "SFNTLookupSingleHeader",
      "type": "topic",
      "url": "/documentation/coretext/sfntlookupsingleheader"
    },
    "doc://com.apple.coretext/documentation/CoreText/SFNTLookupSingleHeader/init(binSearch:entries:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "binSearch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SFNTLookupBinarySearchHeader",
          "text": "SFNTLookupBinarySearchHeader"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "entries"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SFNTLookupSingle",
          "text": "SFNTLookupSingle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/SFNTLookupSingleHeader/init(binSearch:entries:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(binSearch:entries:)",
      "type": "topic",
      "url": "/documentation/coretext/sfntlookupsingleheader/init(binsearch:entries:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1SFNTLookupSingle/title",
          "value": "SFNTLookupSingle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1SFNTLookupSingle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFNTLookupSingle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1SFNTLookupSingle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFNTLookupSingle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1SFNTLookupSingleHeader/title",
          "value": "SFNTLookupSingleHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1SFNTLookupSingleHeader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFNTLookupSingleHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1SFNTLookupSingleHeader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFNTLookupSingleHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1SFNTLookupBinarySearchHeader/title",
          "value": "SFNTLookupBinarySearchHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1SFNTLookupBinarySearchHeader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFNTLookupBinarySearchHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1SFNTLookupBinarySearchHeader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFNTLookupBinarySearchHeader"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/sfntlookupsingleheader/init(binsearch:entries:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
