{
  "abstract": [
    {
      "text": "The post-tessellation vertex function fetches data based on the patch index of the patch.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction/perPatch"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLVertexStepFunction@MTLVertexStepFunctionPerPatch",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "perPatch"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLVertexStepFunctionPerPatch"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLVertexStepFunction.perPatch"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "perPatch"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction": {
      "abstract": [
        {
          "text": "The frequency with which the vertex function or post-tessellation vertex function fetches attribute data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLVertexStepFunction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexStepFunction"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexStepFunction",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexstepfunction"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction/constant": {
      "abstract": [
        {
          "text": "The vertex function fetches attribute data once and uses that data for every vertex.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constant"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction/constant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexStepFunctionConstant"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexStepFunction.constant",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexstepfunction/constant"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction/perInstance": {
      "abstract": [
        {
          "text": "The vertex function regularly fetches new attribute data for a number of instances that is determined by ",
          "type": "text"
        },
        {
          "code": "stepRate",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perInstance"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction/perInstance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexStepFunctionPerInstance"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexStepFunction.perInstance",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexstepfunction/perinstance"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction/perPatch": {
      "abstract": [
        {
          "text": "The post-tessellation vertex function fetches data based on the patch index of the patch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perPatch"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction/perPatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexStepFunctionPerPatch"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexStepFunction.perPatch",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexstepfunction/perpatch"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction/perPatchControlPoint": {
      "abstract": [
        {
          "text": "The post-tessellation vertex function fetches data based on the control-point indices associated with the patch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perPatchControlPoint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction/perPatchControlPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexStepFunctionPerPatchControlPoint"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexStepFunction.perPatchControlPoint",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexstepfunction/perpatchcontrolpoint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction/perVertex": {
      "abstract": [
        {
          "text": "The vertex function fetches and uses new attribute data for every vertex.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perVertex"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction/perVertex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexStepFunctionPerVertex"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexStepFunction.perVertex",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexstepfunction/pervertex"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction/constant",
        "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction/perVertex",
        "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction/perInstance",
        "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction/perPatchControlPoint"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLVertexStepFunctionPerPatch"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexStepFunctionPerPatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction/constant",
                "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction/perVertex",
                "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction/perInstance",
                "doc://com.apple.metal/documentation/Metal/MTLVertexStepFunction/perPatchControlPoint"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLVertexStepFunctionPerPatch"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexStepFunction~1perPatch/title",
          "value": "MTLVertexStepFunctionPerPatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexStepFunction~1perPatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexStepFunctionPerPatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexStepFunction~1perInstance/title",
          "value": "MTLVertexStepFunctionPerInstance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexStepFunction~1perInstance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexStepFunctionPerInstance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexStepFunction~1constant/title",
          "value": "MTLVertexStepFunctionConstant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexStepFunction~1constant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexStepFunctionConstant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexStepFunction/title",
          "value": "MTLVertexStepFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexStepFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexStepFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexStepFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexStepFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexStepFunction~1perVertex/title",
          "value": "MTLVertexStepFunctionPerVertex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexStepFunction~1perVertex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexStepFunctionPerVertex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexStepFunction~1perPatchControlPoint/title",
          "value": "MTLVertexStepFunctionPerPatchControlPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexStepFunction~1perPatchControlPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexStepFunctionPerPatchControlPoint"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlvertexstepfunction/perpatch"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlvertexstepfunction/perpatch"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
