{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/CE_Data"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/CE_Data/crlNumber"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@UA@CE_Data@FI@crlNumber",
    "fragments": [
      {
        "kind": "identifier",
        "text": "crlNumber"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "crlNumber"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "crlNumber"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.apple.security/documentation/Security/CE_CrlNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CE_CrlNumber",
              "text": "CE_CrlNumber"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "crlNumber"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CE_CrlNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CE_CrlNumber"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CE_CrlNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CE_CrlNumber"
        }
      ],
      "role": "symbol",
      "title": "CE_CrlNumber",
      "type": "topic",
      "url": "/documentation/security/ce_crlnumber"
    },
    "doc://com.apple.security/documentation/Security/CE_Data": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CE_Data"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CE_Data",
      "kind": "symbol",
      "role": "symbol",
      "title": "CE_Data",
      "type": "topic",
      "url": "/documentation/security/ce_data"
    },
    "doc://com.apple.security/documentation/Security/CE_Data/crlNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "crlNumber"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CE_Data/crlNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "crlNumber",
      "type": "topic",
      "url": "/documentation/security/ce_data/crlnumber"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CE_CrlNumber/title",
          "value": "CE_CrlNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CE_CrlNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CE_CrlNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CE_CrlNumber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CE_CrlNumber"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/ce_data/crlnumber"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
