{
  "abstract": [
    {
      "text": "Runs the receiver as an application-modal dialog.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.collaboration/documentation/Collaboration",
        "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityPicker"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityPicker/runModal()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CBIdentityPicker(im)runModal",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "runModal"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Collaboration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "runModal"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "runModal()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "runModal"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "code": "NSOKButton",
              "type": "codeVoice"
            },
            {
              "text": " if the user selected OK; otherwise,  ",
              "type": "text"
            },
            {
              "code": "NSCancelButton",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The receiver may create identities for selected records if necessary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.collaboration/documentation/Collaboration": {
      "abstract": [
        {
          "text": "Find and access identities, that is, users and groups. Display the Identity Picker, which lets users create and select identities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration",
      "kind": "symbol",
      "role": "collection",
      "title": "Collaboration",
      "type": "topic",
      "url": "/documentation/collaboration"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityPicker": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "CBIdentityPicker",
          "type": "codeVoice"
        },
        {
          "text": " object allows a user to select identities—for example, user or group objects—that it wants one or more services or shared resources to have access to. An identity picker can be displayed either as an application-modal dialog or as a sheet attached to a document window. An identity picker returns the selected records to be added to access control lists using Collaboration. If a selected record is not a user or group identity, then an identity picker prompts the user for additional information—such as a password—to promote that record to a sharing account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBIdentityPicker"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityPicker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBIdentityPicker"
        }
      ],
      "role": "symbol",
      "title": "CBIdentityPicker",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentitypicker"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityPicker/runModal()": {
      "abstract": [
        {
          "text": "Runs the receiver as an application-modal dialog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModal"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityPicker/runModal()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModal"
        }
      ],
      "role": "symbol",
      "title": "runModal()",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentitypicker/runmodal()"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityPicker/runModal(for:completionHandler:)": {
      "abstract": [
        {
          "text": "Runs the identity picker modally as a sheet attached to a specified window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSModalResponse",
          "text": "ModalResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityPicker/runModal(for:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModalForWindow:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "runModal(for:completionHandler:)",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentitypicker/runmodal(for:completionhandler:)"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityPicker/runModal(for:modalDelegate:didEnd:contextInfo:)": {
      "abstract": [
        {
          "text": "Runs the receiver modally as a sheet attached to a specified window.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "modalDelegate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "didEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "contextInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityPicker/runModal(for:modalDelegate:didEnd:contextInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModalForWindow:modalDelegate:didEndSelector:contextInfo:"
        }
      ],
      "role": "symbol",
      "title": "runModal(for:modalDelegate:didEnd:contextInfo:)",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentitypicker/runmodal(for:modaldelegate:didend:contextinfo:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Running-an-Identity-Picker",
      "generated": true,
      "identifiers": [
        "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityPicker/runModal(for:modalDelegate:didEnd:contextInfo:)",
        "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityPicker/runModal(for:completionHandler:)"
      ],
      "title": "Running an Identity Picker"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "runModal"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.collaboration/documentation/Collaboration",
                "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityPicker"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Running-an-Identity-Picker",
              "generated": true,
              "identifiers": [
                "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityPicker/runModal(for:modalDelegate:didEnd:contextInfo:)",
                "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityPicker/runModal(for:completionHandler:)"
              ],
              "title": "Running an Identity Picker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "runModal"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "code": "NSOKButton",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if the user selected OK; otherwise,  ",
                    "type": "text"
                  },
                  {
                    "code": "NSCancelButton",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityPicker~1runModal(for:completionHandler:)/title",
          "value": "runModalForWindow:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityPicker~1runModal(for:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModalForWindow:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityPicker~1runModal(for:modalDelegate:didEnd:contextInfo:)/title",
          "value": "runModalForWindow:modalDelegate:didEndSelector:contextInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityPicker~1runModal(for:modalDelegate:didEnd:contextInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModalForWindow:modalDelegate:didEndSelector:contextInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityPicker/title",
          "value": "CBIdentityPicker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityPicker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentityPicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityPicker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentityPicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityPicker~1runModal()/title",
          "value": "runModal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityPicker~1runModal()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModal"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/collaboration/cbidentitypicker/runmodal()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/collaboration/cbidentitypicker/runmodal()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
