{
  "abstract": [
    {
      "text": "An array of dictionaries mapping launch storyboard identifiers to storyboards.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UILaunchStoryboardDefinitions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.UILaunchStoryboards.UILaunchStoryboardDefinitions",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UILaunchStoryboardDefinitions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "UILaunchStoryboardDefinitions"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "UILaunchStoryboardDefinitions",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "dictionary "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each dictionary has ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UILaunchStoryboardDefinitions/UILaunchStoryboardFile",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UILaunchStoryboardDefinitions/UILaunchStoryboardIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " keys, associating a storyboard file or xib with an identifier.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards": {
      "abstract": [
        {
          "text": "The launch storyboard to use to generate a launch image when your app opens from a supported scheme.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards",
      "kind": "symbol",
      "name": "UILaunchStoryboards",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchStoryboards"
        }
      ],
      "role": "symbol",
      "title": "UILaunchStoryboards",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchstoryboards"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UIDefaultLaunchStoryboard": {
      "abstract": [
        {
          "text": "The identifier of the default launch storyboard to use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UIDefaultLaunchStoryboard",
      "kind": "symbol",
      "name": "UIDefaultLaunchStoryboard",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDefaultLaunchStoryboard"
        }
      ],
      "role": "symbol",
      "title": "UIDefaultLaunchStoryboard",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchstoryboards/uidefaultlaunchstoryboard"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UILaunchStoryboardDefinitions": {
      "abstract": [
        {
          "text": "An array of dictionaries mapping launch storyboard identifiers to storyboards.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UILaunchStoryboardDefinitions",
      "kind": "symbol",
      "name": "UILaunchStoryboardDefinitions",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchStoryboardDefinitions"
        }
      ],
      "role": "symbol",
      "title": "UILaunchStoryboardDefinitions",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchstoryboards/uilaunchstoryboarddefinitions"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UILaunchStoryboardDefinitions/UILaunchStoryboardFile": {
      "abstract": [
        {
          "text": "A launch storyboard file or xib.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UILaunchStoryboardDefinitions/UILaunchStoryboardFile",
      "kind": "symbol",
      "name": "UILaunchStoryboardFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchStoryboardFile"
        }
      ],
      "role": "symbol",
      "title": "UILaunchStoryboardFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchstoryboards/uilaunchstoryboarddefinitions/uilaunchstoryboardfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UILaunchStoryboardDefinitions/UILaunchStoryboardIdentifier": {
      "abstract": [
        {
          "text": "A user-specified identifier for a launch storyboard.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UILaunchStoryboardDefinitions/UILaunchStoryboardIdentifier",
      "kind": "symbol",
      "name": "UILaunchStoryboardIdentifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchStoryboardIdentifier"
        }
      ],
      "role": "symbol",
      "title": "UILaunchStoryboardIdentifier",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchstoryboards/uilaunchstoryboarddefinitions/uilaunchstoryboardidentifier"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Launch-Storyboards",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UIDefaultLaunchStoryboard"
      ],
      "title": "Specifying Launch Storyboards"
    }
  ],
  "topicSections": [
    {
      "anchor": "Specifying-Storyboard-Identifiers",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UILaunchStoryboardDefinitions/UILaunchStoryboardIdentifier",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UILaunchStoryboardDefinitions/UILaunchStoryboardFile"
      ],
      "title": "Specifying Storyboard Identifiers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UILaunchStoryboardDefinitions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchStoryboardDefinitions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Specifying-Storyboard-Identifiers",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UILaunchStoryboardDefinitions/UILaunchStoryboardIdentifier",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UILaunchStoryboardDefinitions/UILaunchStoryboardFile"
              ],
              "title": "Specifying Storyboard Identifiers"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-Launch-Storyboards",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchStoryboards/UIDefaultLaunchStoryboard"
              ],
              "title": "Specifying Launch Storyboards"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards~1UILaunchStoryboardDefinitions/title",
          "value": "UILaunchStoryboardDefinitions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards~1UILaunchStoryboardDefinitions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchStoryboardDefinitions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards~1UILaunchStoryboardDefinitions~1UILaunchStoryboardIdentifier/title",
          "value": "UILaunchStoryboardIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards~1UILaunchStoryboardDefinitions~1UILaunchStoryboardIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchStoryboardIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards~1UILaunchStoryboardDefinitions~1UILaunchStoryboardFile/title",
          "value": "UILaunchStoryboardFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards~1UILaunchStoryboardDefinitions~1UILaunchStoryboardFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchStoryboardFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards~1UIDefaultLaunchStoryboard/title",
          "value": "UIDefaultLaunchStoryboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards~1UIDefaultLaunchStoryboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDefaultLaunchStoryboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards/title",
          "value": "UILaunchStoryboards"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchStoryboards/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchStoryboards"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uilaunchstoryboards/uilaunchstoryboarddefinitions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uilaunchstoryboards/uilaunchstoryboarddefinitions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
