{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIControl","doc://com.apple.uikit/documentation/UIKit/UIControl/Event"]]},"abstract":[{"text":"All touch events.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allTouchEvents"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl"},{"kind":"text","text":"."},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlEvents","text":"Event"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"seeAlsoSections":[{"title":"Constants","anchor":"Constants","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDown","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDownRepeat","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragInside","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragOutside","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragEnter","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragExit","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpInside","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpOutside","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchCancel","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/valueChanged","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/menuActionTriggered","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/primaryActionTriggered","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidBegin","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingChanged","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEnd"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uicontrol/event/alltouchevents"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uicontrol/event/alltouchevents"]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/allTouchEvents","interfaceLanguage":"swift"},"metadata":{"platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"visionOS"}],"roleHeading":"Type Property","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"UIControlEventAllTouchEvents"}],"externalID":"c:@E@UIControlEvents@UIControlEventAllTouchEvents","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allTouchEvents"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier","text":"UIControl"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier","text":"Event"}],"modules":[{"name":"UIKit"}],"title":"allTouchEvents"},"kind":"symbol","references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragOutside":{"type":"topic","title":"touchDragOutside","kind":"symbol","navigatorTitle":[{"text":"UIControlEventTouchDragOutside","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragOutside","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"touchDragOutside","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl"},{"text":".","kind":"text"},{"text":"Event","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlEvents"}],"abstract":[{"type":"text","text":"An event where a finger is dragged just outside the bounds of the control."}],"url":"/documentation/uikit/uicontrol/event/touchdragoutside"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragEnter":{"type":"topic","title":"touchDragEnter","kind":"symbol","navigatorTitle":[{"text":"UIControlEventTouchDragEnter","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragEnter","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"touchDragEnter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"abstract":[{"text":"An event where a finger is dragged into the bounds of the control.","type":"text"}],"url":"/documentation/uikit/uicontrol/event/touchdragenter"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDown":{"url":"/documentation/uikit/uicontrol/event/touchdown","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"touchDown","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIControlEventTouchDown","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDown","kind":"symbol","abstract":[{"type":"text","text":"A touch-down event in the control."}],"role":"symbol","type":"topic","title":"touchDown"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEnd":{"url":"/documentation/uikit/uicontrol/event/editingdidend","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"editingDidEnd","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIControlEventEditingDidEnd","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEnd","kind":"symbol","abstract":[{"text":"A touch ending an editing session in a text field by leaving its bounds.","type":"text"}],"role":"symbol","type":"topic","title":"editingDidEnd"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/allTouchEvents":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/allTouchEvents","role":"symbol","kind":"symbol","url":"/documentation/uikit/uicontrol/event/alltouchevents","title":"allTouchEvents","type":"topic","abstract":[{"type":"text","text":"All touch events."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allTouchEvents","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIControlEvents","text":"Event","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIControlEventAllTouchEvents","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/valueChanged":{"kind":"symbol","title":"valueChanged","navigatorTitle":[{"text":"UIControlEventValueChanged","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"valueChanged","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIControlEvents","text":"Event","kind":"typeIdentifier"}],"abstract":[{"text":"A touch dragging or otherwise manipulating a control, causing it to emit a series of different values.","type":"text"}],"url":"/documentation/uikit/uicontrol/event/valuechanged","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/valueChanged"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpOutside":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpOutside","title":"touchUpOutside","type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"touchUpOutside","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"url":"/documentation/uikit/uicontrol/event/touchupoutside","abstract":[{"text":"A touch-up event in the control where the finger is outside the bounds of the control.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"UIControlEventTouchUpOutside","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragExit":{"url":"/documentation/uikit/uicontrol/event/touchdragexit","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"touchDragExit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIControlEventTouchDragExit","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragExit","kind":"symbol","abstract":[{"type":"text","text":"An event where a finger is dragged from within a control to outside its bounds."}],"role":"symbol","type":"topic","title":"touchDragExit"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event":{"url":"/documentation/uikit/uicontrol/event","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Event","kind":"identifier"}],"navigatorTitle":[{"text":"Event","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event","kind":"symbol","abstract":[{"type":"text","text":"Constants describing the types of events possible for controls."}],"role":"symbol","type":"topic","title":"UIControl.Event"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragInside":{"role":"symbol","title":"touchDragInside","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragInside","type":"topic","url":"/documentation/uikit/uicontrol/event/touchdraginside","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"touchDragInside","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl"},{"text":".","kind":"text"},{"text":"Event","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlEvents"}],"kind":"symbol","abstract":[{"text":"An event where a finger is dragged inside the bounds of the control.","type":"text"}],"navigatorTitle":[{"text":"UIControlEventTouchDragInside","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchCancel":{"role":"symbol","title":"touchCancel","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchCancel","type":"topic","url":"/documentation/uikit/uicontrol/event/touchcancel","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"touchCancel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"A system event canceling the current touches for the control.","type":"text"}],"navigatorTitle":[{"text":"UIControlEventTouchCancel","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpInside":{"role":"symbol","title":"touchUpInside","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpInside","type":"topic","url":"/documentation/uikit/uicontrol/event/touchupinside","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"touchUpInside","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"A touch-up event in the control where the finger is inside the bounds of the control.","type":"text"}],"navigatorTitle":[{"text":"UIControlEventTouchUpInside","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDownRepeat":{"url":"/documentation/uikit/uicontrol/event/touchdownrepeat","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"touchDownRepeat","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIControlEventTouchDownRepeat","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDownRepeat","kind":"symbol","abstract":[{"text":"A repeated touch-down event in the control; for this event the value of the UITouch ","type":"text"},{"type":"codeVoice","code":"tapCount"},{"text":" method is greater than one.","type":"text"}],"role":"symbol","type":"topic","title":"touchDownRepeat"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingChanged":{"url":"/documentation/uikit/uicontrol/event/editingchanged","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"editingChanged","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIControlEvents","text":"Event","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIControlEventEditingChanged","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingChanged","kind":"symbol","abstract":[{"type":"text","text":"A touch making an editing change in a text field."}],"role":"symbol","type":"topic","title":"editingChanged"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidBegin":{"url":"/documentation/uikit/uicontrol/event/editingdidbegin","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"editingDidBegin","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIControlEventEditingDidBegin","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidBegin","kind":"symbol","abstract":[{"type":"text","text":"A touch initiating an editing session in a text field by entering its bounds."}],"role":"symbol","type":"topic","title":"editingDidBegin"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/menuActionTriggered":{"url":"/documentation/uikit/uicontrol/event/menuactiontriggered","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"menuActionTriggered","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Event","preciseIdentifier":"c:@E@UIControlEvents","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIControlEventMenuActionTriggered","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/menuActionTriggered","kind":"symbol","abstract":[{"text":"A menu action has triggered prior to the menu being presented.","type":"text"}],"role":"symbol","type":"topic","title":"menuActionTriggered"},"doc://com.apple.uikit/documentation/UIKit/UIControl":{"navigatorTitle":[{"text":"UIControl","kind":"identifier"}],"title":"UIControl","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIControl","kind":"identifier"}],"abstract":[{"type":"text","text":"The base class for controls, which are visual elements that convey a specific action or intention in response to user interactions."}],"url":"/documentation/uikit/uicontrol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/primaryActionTriggered":{"url":"/documentation/uikit/uicontrol/event/primaryactiontriggered","abstract":[{"type":"text","text":"A semantic action triggered by buttons."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/Event/primaryActionTriggered","navigatorTitle":[{"text":"UIControlEventPrimaryActionTriggered","kind":"identifier"}],"title":"primaryActionTriggered","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryActionTriggered"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Event","preciseIdentifier":"c:@E@UIControlEvents"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false},{"deprecated":false,"beta":false,"name":"tvOS","unavailable":false},{"unavailable":false,"deprecated":false,"name":"visionOS","beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"/metadata/title","value":"UIControlEventAllTouchEvents"},{"op":"replace","path":"/metadata/symbolKind","value":"case"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"UIControlEventAllTouchEvents","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIControl/Event"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Constants","generated":true,"anchor":"Constants","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDown","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDownRepeat","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragInside","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragOutside","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragEnter","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragExit","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpInside","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpOutside","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchCancel","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/valueChanged","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/menuActionTriggered","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/primaryActionTriggered","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidBegin","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingChanged","doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEnd"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"UIControlEventAllTouchEvents","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragOutside/title","value":"UIControlEventTouchDragOutside","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragOutside/fragments","value":[{"text":"UIControlEventTouchDragOutside","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragEnter/title","value":"UIControlEventTouchDragEnter","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragEnter/fragments","value":[{"text":"UIControlEventTouchDragEnter","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDown/title","value":"UIControlEventTouchDown","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDown/fragments","value":[{"text":"UIControlEventTouchDown","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingDidEnd/title","value":"UIControlEventEditingDidEnd","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingDidEnd/fragments","value":[{"text":"UIControlEventEditingDidEnd","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1allTouchEvents/title","op":"replace","value":"UIControlEventAllTouchEvents"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1allTouchEvents/fragments","op":"replace","value":[{"text":"UIControlEventAllTouchEvents","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1valueChanged/title","op":"replace","value":"UIControlEventValueChanged"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1valueChanged/fragments","op":"replace","value":[{"text":"UIControlEventValueChanged","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchUpOutside/title","op":"replace","value":"UIControlEventTouchUpOutside"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchUpOutside/fragments","op":"replace","value":[{"kind":"identifier","text":"UIControlEventTouchUpOutside"}]},{"value":"UIControlEventTouchDragExit","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragExit/title"},{"value":[{"kind":"identifier","text":"UIControlEventTouchDragExit"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragExit/fragments"},{"value":"UIControlEvents","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event/title"},{"value":[{"kind":"identifier","text":"UIControlEvents"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event/fragments"},{"value":[{"text":"UIControlEvents","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event/navigatorTitle"},{"value":"UIControlEventTouchDragInside","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragInside/title"},{"value":[{"kind":"identifier","text":"UIControlEventTouchDragInside"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragInside/fragments"},{"value":"UIControlEventTouchCancel","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchCancel/title"},{"value":[{"kind":"identifier","text":"UIControlEventTouchCancel"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchCancel/fragments"},{"value":"UIControlEventTouchUpInside","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchUpInside/title"},{"value":[{"text":"UIControlEventTouchUpInside","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchUpInside/fragments"},{"value":"UIControlEventTouchDownRepeat","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDownRepeat/title"},{"value":[{"text":"UIControlEventTouchDownRepeat","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDownRepeat/fragments"},{"value":"UIControlEventEditingChanged","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingChanged/title"},{"value":[{"text":"UIControlEventEditingChanged","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingChanged/fragments"},{"value":"UIControlEventEditingDidBegin","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingDidBegin/title"},{"value":[{"kind":"identifier","text":"UIControlEventEditingDidBegin"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingDidBegin/fragments"},{"value":"UIControlEventMenuActionTriggered","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1menuActionTriggered/title"},{"value":[{"kind":"identifier","text":"UIControlEventMenuActionTriggered"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1menuActionTriggered/fragments"},{"value":"UIControl","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/title"},{"value":[{"kind":"identifier","text":"UIControl"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/fragments"},{"value":[{"text":"UIControl","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/navigatorTitle"},{"value":"UIControlEventPrimaryActionTriggered","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1primaryActionTriggered/title"},{"value":[{"kind":"identifier","text":"UIControlEventPrimaryActionTriggered"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1primaryActionTriggered/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}