{
  "abstract": [
    {
      "text": "A touch-up event in the control where the finger is outside the bounds of the control.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIControl",
        "doc://com.apple.uikit/documentation/UIKit/UIControl/Event"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpOutside"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIControlEvents@UIControlEventTouchUpOutside",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "touchUpOutside"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIControl",
        "text": "UIControl"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UIControlEvents",
        "text": "Event"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIControlEventTouchUpOutside"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "touchUpOutside"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "touchUpOutside"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIControl",
              "text": "UIControl"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/Event",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIControlEvents",
              "text": "Event"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl": {
      "abstract": [
        {
          "text": "The base class for controls, which are visual elements that convey a specific action or intention in response to user interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIControl"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControl"
        }
      ],
      "role": "symbol",
      "title": "UIControl",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/Event": {
      "abstract": [
        {
          "text": "Constants describing the types of events possible for controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/Event",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Event"
        }
      ],
      "role": "symbol",
      "title": "UIControl.Event",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/event"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingChanged": {
      "abstract": [
        {
          "text": "A touch making an editing change in a text field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "editingChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlEvents",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControlEventEditingChanged"
        }
      ],
      "role": "symbol",
      "title": "editingChanged",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/event/editingchanged"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidBegin": {
      "abstract": [
        {
          "text": "A touch initiating an editing session in a text field by entering its bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "editingDidBegin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlEvents",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidBegin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControlEventEditingDidBegin"
        }
      ],
      "role": "symbol",
      "title": "editingDidBegin",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/event/editingdidbegin"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEnd": {
      "abstract": [
        {
          "text": "A touch ending an editing session in a text field by leaving its bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "editingDidEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlEvents",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControlEventEditingDidEnd"
        }
      ],
      "role": "symbol",
      "title": "editingDidEnd",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/event/editingdidend"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEndOnExit": {
      "abstract": [
        {
          "text": "A touch ending an editing session in a text field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "editingDidEndOnExit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlEvents",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEndOnExit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControlEventEditingDidEndOnExit"
        }
      ],
      "role": "symbol",
      "title": "editingDidEndOnExit",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/event/editingdidendonexit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/menuActionTriggered": {
      "abstract": [
        {
          "text": "A menu action has triggered prior to the menu being presented.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menuActionTriggered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlEvents",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/menuActionTriggered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControlEventMenuActionTriggered"
        }
      ],
      "role": "symbol",
      "title": "menuActionTriggered",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/event/menuactiontriggered"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/primaryActionTriggered": {
      "abstract": [
        {
          "text": "A semantic action triggered by buttons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryActionTriggered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlEvents",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/primaryActionTriggered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControlEventPrimaryActionTriggered"
        }
      ],
      "role": "symbol",
      "title": "primaryActionTriggered",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/event/primaryactiontriggered"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchCancel": {
      "abstract": [
        {
          "text": "A system event canceling the current touches for the control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchCancel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlEvents",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchCancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControlEventTouchCancel"
        }
      ],
      "role": "symbol",
      "title": "touchCancel",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/event/touchcancel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDown": {
      "abstract": [
        {
          "text": "A touch-down event in the control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchDown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlEvents",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControlEventTouchDown"
        }
      ],
      "role": "symbol",
      "title": "touchDown",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/event/touchdown"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDownRepeat": {
      "abstract": [
        {
          "text": "A repeated touch-down event in the control; for this event the value of the UITouch ",
          "type": "text"
        },
        {
          "code": "tapCount",
          "type": "codeVoice"
        },
        {
          "text": " method is greater than one.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchDownRepeat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlEvents",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDownRepeat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControlEventTouchDownRepeat"
        }
      ],
      "role": "symbol",
      "title": "touchDownRepeat",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/event/touchdownrepeat"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragEnter": {
      "abstract": [
        {
          "text": "An event where a finger is dragged into the bounds of the control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchDragEnter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlEvents",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragEnter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControlEventTouchDragEnter"
        }
      ],
      "role": "symbol",
      "title": "touchDragEnter",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/event/touchdragenter"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragExit": {
      "abstract": [
        {
          "text": "An event where a finger is dragged from within a control to outside its bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchDragExit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlEvents",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragExit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControlEventTouchDragExit"
        }
      ],
      "role": "symbol",
      "title": "touchDragExit",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/event/touchdragexit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragInside": {
      "abstract": [
        {
          "text": "An event where a finger is dragged inside the bounds of the control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchDragInside"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlEvents",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragInside",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControlEventTouchDragInside"
        }
      ],
      "role": "symbol",
      "title": "touchDragInside",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/event/touchdraginside"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragOutside": {
      "abstract": [
        {
          "text": "An event where a finger is dragged just outside the bounds of the control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchDragOutside"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlEvents",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragOutside",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControlEventTouchDragOutside"
        }
      ],
      "role": "symbol",
      "title": "touchDragOutside",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/event/touchdragoutside"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpInside": {
      "abstract": [
        {
          "text": "A touch-up event in the control where the finger is inside the bounds of the control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchUpInside"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlEvents",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpInside",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControlEventTouchUpInside"
        }
      ],
      "role": "symbol",
      "title": "touchUpInside",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/event/touchupinside"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpOutside": {
      "abstract": [
        {
          "text": "A touch-up event in the control where the finger is outside the bounds of the control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchUpOutside"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlEvents",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpOutside",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControlEventTouchUpOutside"
        }
      ],
      "role": "symbol",
      "title": "touchUpOutside",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/event/touchupoutside"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/valueChanged": {
      "abstract": [
        {
          "text": "A touch dragging or otherwise manipulating a control, causing it to emit a series of different values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "valueChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlEvents",
          "text": "Event"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/valueChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControlEventValueChanged"
        }
      ],
      "role": "symbol",
      "title": "valueChanged",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/event/valuechanged"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDown",
        "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDownRepeat",
        "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragInside",
        "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragOutside",
        "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragEnter",
        "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragExit",
        "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpInside",
        "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchCancel",
        "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/valueChanged",
        "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/menuActionTriggered",
        "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/primaryActionTriggered",
        "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidBegin",
        "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingChanged",
        "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEnd",
        "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEndOnExit"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIControlEventTouchUpOutside"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlEventTouchUpOutside"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIControl/Event"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDown",
                "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDownRepeat",
                "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragInside",
                "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragOutside",
                "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragEnter",
                "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchDragExit",
                "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchUpInside",
                "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/touchCancel",
                "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/valueChanged",
                "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/menuActionTriggered",
                "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/primaryActionTriggered",
                "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidBegin",
                "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingChanged",
                "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEnd",
                "doc://com.apple.uikit/documentation/UIKit/UIControl/Event/editingDidEndOnExit"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIControlEventTouchUpOutside"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchUpOutside/title",
          "value": "UIControlEventTouchUpOutside"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchUpOutside/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlEventTouchUpOutside"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event/title",
          "value": "UIControlEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragInside/title",
          "value": "UIControlEventTouchDragInside"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragInside/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlEventTouchDragInside"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingDidEndOnExit/title",
          "value": "UIControlEventEditingDidEndOnExit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingDidEndOnExit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlEventEditingDidEndOnExit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1primaryActionTriggered/title",
          "value": "UIControlEventPrimaryActionTriggered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1primaryActionTriggered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlEventPrimaryActionTriggered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingDidEnd/title",
          "value": "UIControlEventEditingDidEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingDidEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlEventEditingDidEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragEnter/title",
          "value": "UIControlEventTouchDragEnter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragEnter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlEventTouchDragEnter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingChanged/title",
          "value": "UIControlEventEditingChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlEventEditingChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDownRepeat/title",
          "value": "UIControlEventTouchDownRepeat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDownRepeat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlEventTouchDownRepeat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragOutside/title",
          "value": "UIControlEventTouchDragOutside"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragOutside/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlEventTouchDragOutside"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDown/title",
          "value": "UIControlEventTouchDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlEventTouchDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingDidBegin/title",
          "value": "UIControlEventEditingDidBegin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1editingDidBegin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlEventEditingDidBegin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchUpInside/title",
          "value": "UIControlEventTouchUpInside"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchUpInside/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlEventTouchUpInside"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/title",
          "value": "UIControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragExit/title",
          "value": "UIControlEventTouchDragExit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchDragExit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlEventTouchDragExit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1menuActionTriggered/title",
          "value": "UIControlEventMenuActionTriggered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1menuActionTriggered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlEventMenuActionTriggered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1valueChanged/title",
          "value": "UIControlEventValueChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1valueChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlEventValueChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchCancel/title",
          "value": "UIControlEventTouchCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1Event~1touchCancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControlEventTouchCancel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicontrol/event/touchupoutside"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uicontrol/event/touchupoutside"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
