{
  "abstract": [
    {
      "text": "Error codes from CryptoTokenKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@TKErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "CryptoTokenKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "TKError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit": {
      "abstract": [
        {
          "text": "Access security tokens and the cryptographic assets they store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CryptoTokenKit",
      "type": "topic",
      "url": "/documentation/cryptotokenkit"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError": {
      "abstract": [
        {
          "text": "An error specific to the CryptoTokenKit framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TKError"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKError"
        }
      ],
      "role": "symbol",
      "title": "TKError",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tkerror"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code": {
      "abstract": [
        {
          "text": "Error codes from CryptoTokenKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "TKError.Code",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tkerror/code"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/TKErrorAuthenticationFailed": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TKErrorAuthenticationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11TKErrorCodeLeV",
          "text": "TKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/TKErrorAuthenticationFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "TKErrorAuthenticationFailed",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tkerror/code/tkerrorauthenticationfailed"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/TKErrorObjectNotFound": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TKErrorObjectNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11TKErrorCodeLeV",
          "text": "TKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/TKErrorObjectNotFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "TKErrorObjectNotFound",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tkerror/code/tkerrorobjectnotfound"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/TKErrorTokenNotFound": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TKErrorTokenNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11TKErrorCodeLeV",
          "text": "TKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/TKErrorTokenNotFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "TKErrorTokenNotFound",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tkerror/code/tkerrortokennotfound"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/authenticationFailed": {
      "abstract": [
        {
          "text": "Authentication failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authenticationFailed"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/authenticationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKErrorCodeAuthenticationFailed"
        }
      ],
      "role": "symbol",
      "title": "TKError.Code.authenticationFailed",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tkerror/code/authenticationfailed"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/authenticationNeeded": {
      "abstract": [
        {
          "text": "Authentication is needed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authenticationNeeded"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/authenticationNeeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKErrorCodeAuthenticationNeeded"
        }
      ],
      "role": "symbol",
      "title": "TKError.Code.authenticationNeeded",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tkerror/code/authenticationneeded"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/badParameter": {
      "abstract": [
        {
          "text": "An invalid parameter was provided.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badParameter"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/badParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKErrorCodeBadParameter"
        }
      ],
      "role": "symbol",
      "title": "TKError.Code.badParameter",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tkerror/code/badparameter"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/canceledByUser": {
      "abstract": [
        {
          "text": "The operation was canceled by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canceledByUser"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/canceledByUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKErrorCodeCanceledByUser"
        }
      ],
      "role": "symbol",
      "title": "TKError.Code.canceledByUser",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tkerror/code/canceledbyuser"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/communicationError": {
      "abstract": [
        {
          "text": "A communication error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "communicationError"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/communicationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKErrorCodeCommunicationError"
        }
      ],
      "role": "symbol",
      "title": "TKError.Code.communicationError",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tkerror/code/communicationerror"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/corruptedData": {
      "abstract": [
        {
          "text": "The data was corrupted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "corruptedData"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/corruptedData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKErrorCodeCorruptedData"
        }
      ],
      "role": "symbol",
      "title": "TKError.Code.corruptedData",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tkerror/code/corrupteddata"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tkerror/code/init(rawvalue:)"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/notImplemented": {
      "abstract": [
        {
          "text": "The functionality is not implemented.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notImplemented"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/notImplemented",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKErrorCodeNotImplemented"
        }
      ],
      "role": "symbol",
      "title": "TKError.Code.notImplemented",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tkerror/code/notimplemented"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/objectNotFound": {
      "abstract": [
        {
          "text": "The object was not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectNotFound"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/objectNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKErrorCodeObjectNotFound"
        }
      ],
      "role": "symbol",
      "title": "TKError.Code.objectNotFound",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tkerror/code/objectnotfound"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/tokenNotFound": {
      "abstract": [
        {
          "text": "The token was not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tokenNotFound"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/tokenNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKErrorCodeTokenNotFound"
        }
      ],
      "role": "symbol",
      "title": "TKError.Code.tokenNotFound",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tkerror/code/tokennotfound"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKErrorCode/TKErrorAuthenticationFailed": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "TKErrorAuthenticationFailed"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKErrorCode/TKErrorAuthenticationFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "TKErrorAuthenticationFailed",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tkerrorcode/tkerrorauthenticationfailed"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKErrorCode/TKErrorObjectNotFound": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "TKErrorObjectNotFound"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKErrorCode/TKErrorObjectNotFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "TKErrorObjectNotFound",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tkerrorcode/tkerrorobjectnotfound"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKErrorCode/TKErrorTokenNotFound": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "TKErrorTokenNotFound"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKErrorCode/TKErrorTokenNotFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "TKErrorTokenNotFound",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tkerrorcode/tkerrortokennotfound"
    },
    "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKErrorDomain": {
      "abstract": [
        {
          "text": "The domain for all CryptoTokenKit framework errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TKErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TKErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "TKErrorDomain",
      "type": "topic",
      "url": "/documentation/cryptotokenkit/tkerrordomain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/notImplemented",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/communicationError",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/corruptedData",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/canceledByUser",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/authenticationFailed",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/objectNotFound",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/tokenNotFound",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/badParameter",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/authenticationNeeded",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/TKErrorAuthenticationFailed",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/TKErrorObjectNotFound",
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/TKErrorTokenNotFound"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TKErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "identifiers": [
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/notImplemented",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/communicationError",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/corruptedData",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/canceledByUser",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/authenticationFailed",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/objectNotFound",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/tokenNotFound",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/badParameter",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKError/Code/authenticationNeeded"
              ],
              "title": "Error Codes"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKErrorCode/TKErrorAuthenticationFailed",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKErrorCode/TKErrorObjectNotFound",
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKErrorCode/TKErrorTokenNotFound"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cryptotokenkit/documentation/CryptoTokenKit/TKErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "TKErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code~1objectNotFound/title",
          "value": "TKErrorCodeObjectNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code~1objectNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKErrorCodeObjectNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code~1authenticationNeeded/title",
          "value": "TKErrorCodeAuthenticationNeeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code~1authenticationNeeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKErrorCodeAuthenticationNeeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code~1authenticationFailed/title",
          "value": "TKErrorCodeAuthenticationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code~1authenticationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKErrorCodeAuthenticationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKErrorDomain/title",
          "value": "TKErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code~1communicationError/title",
          "value": "TKErrorCodeCommunicationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code~1communicationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKErrorCodeCommunicationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code~1badParameter/title",
          "value": "TKErrorCodeBadParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code~1badParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKErrorCodeBadParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code~1notImplemented/title",
          "value": "TKErrorCodeNotImplemented"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code~1notImplemented/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKErrorCodeNotImplemented"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code~1corruptedData/title",
          "value": "TKErrorCodeCorruptedData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code~1corruptedData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKErrorCodeCorruptedData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code~1canceledByUser/title",
          "value": "TKErrorCodeCanceledByUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code~1canceledByUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKErrorCodeCanceledByUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code~1tokenNotFound/title",
          "value": "TKErrorCodeTokenNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code~1tokenNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKErrorCodeTokenNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code/title",
          "value": "TKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cryptotokenkit~1documentation~1CryptoTokenKit~1TKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TKErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cryptotokenkit/tkerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cryptotokenkit/tkerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
