{
  "abstract": [
    {
      "text": "Adds a text range to the set of matches.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-swift.struct/foundRange(_:searchString:document:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:5UIKit22UITextSearchAggregatorV10foundRange_12searchString8documentySo0bF0C_SSxtF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "foundRange"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UITextRange",
        "text": "UITextRange"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "searchString"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "document"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "text": "DocumentIdentifier"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "foundRange(_:searchString:document:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "foundRange"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "range"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UITextRange",
              "text": "UITextRange"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "searchString"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "document"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "DocumentIdentifier"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The text range to add to the set of matches.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "range"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The query string the search used to locate this range of text.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "searchString"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A string that uniquely identifies the document containing the text range. ",
                  "type": "text"
                },
                {
                  "code": "Nil",
                  "type": "codeVoice"
                },
                {
                  "text": " when searching a single document.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "document"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Call this method to add a text range found in your document to the set of matches.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextRange": {
      "abstract": [
        {
          "text": "A range of characters in a text container with a starting index and an ending index in string backing a text-entry object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextRange"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextRange"
        }
      ],
      "role": "symbol",
      "title": "UITextRange",
      "type": "topic",
      "url": "/documentation/uikit/uitextrange"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-swift.struct": {
      "abstract": [
        {
          "text": "The methods you use on a find session’s aggregator to collect matching text ranges for a search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSearchAggregator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchAggregator"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchAggregator",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchaggregator-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-swift.struct/allFoundRanges": {
      "abstract": [
        {
          "text": "An ordered set of all the text ranges that match the search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allFoundRanges"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextRange",
          "text": "UITextRange"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-swift.struct/allFoundRanges",
      "kind": "symbol",
      "role": "symbol",
      "title": "allFoundRanges",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchaggregator-swift.struct/allfoundranges"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-swift.struct/finishedSearching()": {
      "abstract": [
        {
          "text": "Finishes the search for text ranges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishedSearching"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-swift.struct/finishedSearching()",
      "kind": "symbol",
      "role": "symbol",
      "title": "finishedSearching()",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchaggregator-swift.struct/finishedsearching()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-swift.struct/foundRange(_:searchString:document:)": {
      "abstract": [
        {
          "text": "Adds a text range to the set of matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foundRange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextRange",
          "text": "UITextRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "searchString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "document"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "DocumentIdentifier"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-swift.struct/foundRange(_:searchString:document:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "foundRange(_:searchString:document:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchaggregator-swift.struct/foundrange(_:searchstring:document:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-swift.struct/invalidate()": {
      "abstract": [
        {
          "text": "Invalidates all currently shown ranges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidate"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-swift.struct/invalidate()",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidate()",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchaggregator-swift.struct/invalidate()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-swift.struct/invalidateFoundRange(_:document:)": {
      "abstract": [
        {
          "text": "Removes a text range from the set of matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidateFoundRange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextRange",
          "text": "UITextRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "document"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "DocumentIdentifier"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-swift.struct/invalidateFoundRange(_:document:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidateFoundRange(_:document:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchaggregator-swift.struct/invalidatefoundrange(_:document:)"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Tracking-search-results",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-swift.struct/invalidateFoundRange(_:document:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-swift.struct/invalidate()",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-swift.struct/finishedSearching()",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-swift.struct/allFoundRanges"
      ],
      "title": "Tracking search results"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextRange/title",
          "value": "UITextRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextRange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextsearchaggregator-swift.struct/foundrange(_:searchstring:document:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
