{
  "abstract": [
    {
      "text": "No data detection.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/WKDataDetectorTypeNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKDataDetectorTypes@WKDataDetectorTypeNone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "WKDataDetectorTypeNone"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKDataDetectorTypeNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "WKDataDetectorTypeNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypeNone"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes": {
      "abstract": [
        {
          "text": "The data detector types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypes"
        }
      ],
      "role": "symbol",
      "title": "WKDataDetectorTypes",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/WKDataDetectorTypeNone": {
      "abstract": [
        {
          "text": "No data detection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypeNone"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/WKDataDetectorTypeNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "WKDataDetectorTypeNone",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/wkdatadetectortypenone"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/address": {
      "abstract": [
        {
          "text": "Detect addresses in text and turn them into links to display the location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "address"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKDataDetectorTypes",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/address",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypeAddress"
        }
      ],
      "role": "symbol",
      "title": "address",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/address"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/all": {
      "abstract": [
        {
          "text": "Detect all data types and turn them into links.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKDataDetectorTypes",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/all",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypeAll"
        }
      ],
      "role": "symbol",
      "title": "all",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/all"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/calendarEvent": {
      "abstract": [
        {
          "text": "Turn future dates and times into links to create calendar events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKDataDetectorTypes",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/calendarEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypeCalendarEvent"
        }
      ],
      "role": "symbol",
      "title": "calendarEvent",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/calendarevent"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/flightNumber": {
      "abstract": [
        {
          "text": "Detect flight numbers in text and turn them into links.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flightNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKDataDetectorTypes",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/flightNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypeFlightNumber"
        }
      ],
      "role": "symbol",
      "title": "flightNumber",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/flightnumber"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/link": {
      "abstract": [
        {
          "text": "Detect URLs in text and turn them into links.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "link"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKDataDetectorTypes",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/link",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypeLink"
        }
      ],
      "role": "symbol",
      "title": "link",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/link"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/lookupSuggestion": {
      "abstract": [
        {
          "text": "Detect Spotlight suggestions and turn them into links.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lookupSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKDataDetectorTypes",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/lookupSuggestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypeLookupSuggestion"
        }
      ],
      "role": "symbol",
      "title": "lookupSuggestion",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/lookupsuggestion"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/phoneNumber": {
      "abstract": [
        {
          "text": "Detect phone numbers in text and create a link to call the specified number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phoneNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKDataDetectorTypes",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/phoneNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypePhoneNumber"
        }
      ],
      "role": "symbol",
      "title": "phoneNumber",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/phonenumber"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/trackingNumber": {
      "abstract": [
        {
          "text": "Detect tracking numbers in text and turn them into links.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackingNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@WKDataDetectorTypes",
          "text": "WKDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/trackingNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDataDetectorTypeTrackingNumber"
        }
      ],
      "role": "symbol",
      "title": "trackingNumber",
      "type": "topic",
      "url": "/documentation/webkit/wkdatadetectortypes/trackingnumber"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Detector-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/phoneNumber",
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/link",
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/address",
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/calendarEvent",
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/trackingNumber",
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/flightNumber",
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/lookupSuggestion",
        "doc://com.apple.webkit/documentation/WebKit/WKDataDetectorTypes/all"
      ],
      "title": "Data Detector Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1all/title",
          "value": "WKDataDetectorTypeAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1all/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypeAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1flightNumber/title",
          "value": "WKDataDetectorTypeFlightNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1flightNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypeFlightNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1trackingNumber/title",
          "value": "WKDataDetectorTypeTrackingNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1trackingNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypeTrackingNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1lookupSuggestion/title",
          "value": "WKDataDetectorTypeLookupSuggestion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1lookupSuggestion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypeLookupSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1calendarEvent/title",
          "value": "WKDataDetectorTypeCalendarEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1calendarEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypeCalendarEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1phoneNumber/title",
          "value": "WKDataDetectorTypePhoneNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1phoneNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypePhoneNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1link/title",
          "value": "WKDataDetectorTypeLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1link/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypeLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1address/title",
          "value": "WKDataDetectorTypeAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes~1address/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypeAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes/title",
          "value": "WKDataDetectorTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDataDetectorTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDataDetectorTypes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkdatadetectortypes/wkdatadetectortypenone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
