{
  "abstract": [
    {
      "text": "The range of allowed random values for a particle’s initial speed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/particleSpeedRange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SKEmitterNode(py)particleSpeedRange",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "particleSpeedRange"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
        "text": "CGFloat"
      }
    ],
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "particleSpeedRange"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "particleSpeedRange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "particleSpeedRange"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "particleSpeedRange"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default value is ",
              "type": "text"
            },
            {
              "code": "0.0",
              "type": "codeVoice"
            },
            {
              "text": ". If non-zero, the speed of each particle is randomly determined and may vary by plus or minus half of the range value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode": {
      "abstract": [
        {
          "text": "A source of various particle effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKEmitterNode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKEmitterNode"
        }
      ],
      "role": "symbol",
      "title": "SKEmitterNode",
      "type": "topic",
      "url": "/documentation/spritekit/skemitternode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/emissionAngle": {
      "abstract": [
        {
          "text": "The average initial direction of a particle, expressed as an angle in radians.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emissionAngle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/emissionAngle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "emissionAngle"
        }
      ],
      "role": "symbol",
      "title": "emissionAngle",
      "type": "topic",
      "url": "/documentation/spritekit/skemitternode/emissionangle"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/emissionAngleRange": {
      "abstract": [
        {
          "text": "The range of allowed random values for a particle’s initial direction, expressed as an angle in radians.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emissionAngleRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/emissionAngleRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "emissionAngleRange"
        }
      ],
      "role": "symbol",
      "title": "emissionAngleRange",
      "type": "topic",
      "url": "/documentation/spritekit/skemitternode/emissionanglerange"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/particleSpeed": {
      "abstract": [
        {
          "text": "The average initial speed of a new particle, in points per second.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "particleSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/particleSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "particleSpeed"
        }
      ],
      "role": "symbol",
      "title": "particleSpeed",
      "type": "topic",
      "url": "/documentation/spritekit/skemitternode/particlespeed"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/particleSpeedRange": {
      "abstract": [
        {
          "text": "The range of allowed random values for a particle’s initial speed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "particleSpeedRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/particleSpeedRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "particleSpeedRange"
        }
      ],
      "role": "symbol",
      "title": "particleSpeedRange",
      "type": "topic",
      "url": "/documentation/spritekit/skemitternode/particlespeedrange"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/particleZPositionSpeed": {
      "abstract": [
        {
          "text": "The speed at which the particle’s depth changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "particleZPositionSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/particleZPositionSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "particleZPositionSpeed"
        }
      ],
      "role": "symbol",
      "title": "particleZPositionSpeed",
      "type": "topic",
      "url": "/documentation/spritekit/skemitternode/particlezpositionspeed"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/xAcceleration": {
      "abstract": [
        {
          "text": "The acceleration to apply to a particle’s horizontal velocity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xAcceleration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/xAcceleration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xAcceleration"
        }
      ],
      "role": "symbol",
      "title": "xAcceleration",
      "type": "topic",
      "url": "/documentation/spritekit/skemitternode/xacceleration"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/yAcceleration": {
      "abstract": [
        {
          "text": "The acceleration to apply to a particle’s vertical velocity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yAcceleration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/yAcceleration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "yAcceleration"
        }
      ],
      "role": "symbol",
      "title": "yAcceleration",
      "type": "topic",
      "url": "/documentation/spritekit/skemitternode/yacceleration"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGFloat": {
      "abstract": [
        {
          "text": "The basic type for all floating-point values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV": {
      "abstract": [
        {
          "text": "The basic type for floating-point scalar values in Core Graphics and related frameworks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Controlling-Particle-Velocity-and-Acceleration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/particleSpeed",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/emissionAngle",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/emissionAngleRange",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/xAcceleration",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/yAcceleration",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/particleZPositionSpeed"
      ],
      "title": "Controlling Particle Velocity and Acceleration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "particleSpeedRange"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "particleSpeedRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.spritekit/documentation/SpriteKit",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Controlling-Particle-Velocity-and-Acceleration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/particleSpeed",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/emissionAngle",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/emissionAngleRange",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/xAcceleration",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/yAcceleration",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKEmitterNode/particleZPositionSpeed"
              ],
              "title": "Controlling Particle Velocity and Acceleration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGFloat",
                    "text": "CGFloat"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "particleSpeedRange"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode~1particleSpeedRange/title",
          "value": "particleSpeedRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode~1particleSpeedRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "particleSpeedRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode~1xAcceleration/title",
          "value": "xAcceleration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode~1xAcceleration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xAcceleration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode~1emissionAngleRange/title",
          "value": "emissionAngleRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode~1emissionAngleRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "emissionAngleRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode~1emissionAngle/title",
          "value": "emissionAngle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode~1emissionAngle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "emissionAngle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode/title",
          "value": "SKEmitterNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKEmitterNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKEmitterNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode~1particleZPositionSpeed/title",
          "value": "particleZPositionSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode~1particleZPositionSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "particleZPositionSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode~1yAcceleration/title",
          "value": "yAcceleration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode~1yAcceleration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "yAcceleration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode~1particleSpeed/title",
          "value": "particleSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKEmitterNode~1particleSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "particleSpeed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/skemitternode/particlespeedrange"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/skemitternode/particlespeedrange"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
