{
  "abstract": [
    {
      "text": "The date and time the user last played the media item, or ",
      "type": "text"
    },
    {
      "code": "nil",
      "type": "codeVoice"
    },
    {
      "text": " if the user hasn’t played it.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/lastPlayedDate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ITLibMediaItem(py)lastPlayedDate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "lastPlayedDate"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation4DateV",
        "text": "Date"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "iTunes Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "lastPlayedDate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "lastPlayedDate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "lastPlayedDate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DateV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4DateV",
              "text": "Date"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary": {
      "abstract": [
        {
          "text": "Retrieve the properties of the media in the user’s iTunes library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "iTunes Library",
      "type": "topic",
      "url": "/documentation/ituneslibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem": {
      "abstract": [
        {
          "text": "This class describes a media item (a track) in the iTunes library, such as a song, a video, or a podcast.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItem"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItem"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItem",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/album": {
      "abstract": [
        {
          "text": "The album of the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "album"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ITLibAlbum",
          "text": "ITLibAlbum"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/album",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "album"
        }
      ],
      "role": "symbol",
      "title": "album",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/album"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/artist": {
      "abstract": [
        {
          "text": "Information about the artist that iTunes associates with the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "artist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ITLibArtist",
          "text": "ITLibArtist"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/artist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "artist"
        }
      ],
      "role": "symbol",
      "title": "artist",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/artist"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/composer": {
      "abstract": [
        {
          "text": "The name of the composer that iTunes associates with the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "composer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/composer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "composer"
        }
      ],
      "role": "symbol",
      "title": "composer",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/composer"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/genre": {
      "abstract": [
        {
          "text": "The genre of the media item, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genre"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/genre",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "genre"
        }
      ],
      "role": "symbol",
      "title": "genre",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/genre"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/isRatingComputed": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether iTunes computes the media item’s rating from its album rating.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRatingComputed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/isRatingComputed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ratingComputed"
        }
      ],
      "role": "symbol",
      "title": "isRatingComputed",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/isratingcomputed"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/kind": {
      "abstract": [
        {
          "text": "The kind of media item file, such as an MPEG audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/kind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kind"
        }
      ],
      "role": "symbol",
      "title": "kind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/kind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/lastPlayedDate": {
      "abstract": [
        {
          "text": "The date and time the user last played the media item, or ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": " if the user hasn’t played it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastPlayedDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/lastPlayedDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lastPlayedDate"
        }
      ],
      "role": "symbol",
      "title": "lastPlayedDate",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/lastplayeddate"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/mediaKind": {
      "abstract": [
        {
          "text": "The kind of media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaKind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ITLibMediaItemMediaKind",
          "text": "ITLibMediaItemMediaKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/mediaKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaKind"
        }
      ],
      "role": "symbol",
      "title": "mediaKind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/mediakind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/rating": {
      "abstract": [
        {
          "text": "The rating of the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/rating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rating"
        }
      ],
      "role": "symbol",
      "title": "rating",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/rating"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/sortComposer": {
      "abstract": [
        {
          "text": "The name to use when sorting by composer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sortComposer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/sortComposer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sortComposer"
        }
      ],
      "role": "symbol",
      "title": "sortComposer",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/sortcomposer"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/sortTitle": {
      "abstract": [
        {
          "text": "The title of the media item to use when sorting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sortTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/sortTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sortTitle"
        }
      ],
      "role": "symbol",
      "title": "sortTitle",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/sorttitle"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/startTime": {
      "abstract": [
        {
          "text": "If nonzero, the actual time playback of the media item starts instead of 0:00 (in milliseconds).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/startTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startTime"
        }
      ],
      "role": "symbol",
      "title": "startTime",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/starttime"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/stopTime": {
      "abstract": [
        {
          "text": "If nonzero, the actual time playback of the media item stops versus the total time (in milliseconds).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/stopTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopTime"
        }
      ],
      "role": "symbol",
      "title": "stopTime",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/stoptime"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/title": {
      "abstract": [
        {
          "text": "The title of the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/title"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/totalTime": {
      "abstract": [
        {
          "text": "The length of the media item in milliseconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/totalTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalTime"
        }
      ],
      "role": "symbol",
      "title": "totalTime",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/totaltime"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/trackNumber": {
      "abstract": [
        {
          "text": "The position of the media item within its album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/trackNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trackNumber"
        }
      ],
      "role": "symbol",
      "title": "trackNumber",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitem/tracknumber"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation4DateV": {
      "abstract": [
        {
          "text": "A specific point in time, independent of any calendar or time zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DateV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Date",
      "type": "topic",
      "url": "/documentation/foundation/date"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Media-Item-Info",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/title",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/sortTitle",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/artist",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/composer",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/sortComposer",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/rating",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/isRatingComputed",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/startTime",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/stopTime",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/album",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/genre",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/kind",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/mediaKind",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/totalTime",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/trackNumber"
      ],
      "title": "Getting Media Item Info"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "lastPlayedDate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lastPlayedDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Media-Item-Info",
              "generated": true,
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/title",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/sortTitle",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/artist",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/composer",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/sortComposer",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/rating",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/isRatingComputed",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/startTime",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/stopTime",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/album",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/genre",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/kind",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/mediaKind",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/totalTime",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItem/trackNumber"
              ],
              "title": "Getting Media Item Info"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "retain"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSDate",
                    "text": "NSDate"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "lastPlayedDate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1sortComposer/title",
          "value": "sortComposer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1sortComposer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sortComposer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1isRatingComputed/title",
          "value": "ratingComputed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1isRatingComputed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ratingComputed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1trackNumber/title",
          "value": "trackNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1trackNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trackNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1composer/title",
          "value": "composer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1composer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "composer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1mediaKind/title",
          "value": "mediaKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1mediaKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1startTime/title",
          "value": "startTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1startTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1totalTime/title",
          "value": "totalTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1totalTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1lastPlayedDate/title",
          "value": "lastPlayedDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1lastPlayedDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lastPlayedDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1artist/title",
          "value": "artist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1artist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "artist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1album/title",
          "value": "album"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1album/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "album"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1stopTime/title",
          "value": "stopTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1stopTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stopTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1rating/title",
          "value": "rating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1rating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1sortTitle/title",
          "value": "sortTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1sortTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sortTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem/title",
          "value": "ITLibMediaItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1kind/title",
          "value": "kind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1kind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1genre/title",
          "value": "genre"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItem~1genre/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "genre"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/ituneslibrary/itlibmediaitem/lastplayeddate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/ituneslibrary/itlibmediaitem/lastplayeddate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
