{
  "abstract": [
    {
      "text": "The IDs of the record zones that contain the records to fetch.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/recordZoneIDs"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CKFetchRecordZoneChangesOperation(py)recordZoneIDs",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "recordZoneIDs"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKRecordZone",
        "text": "CKRecordZone"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKRecordZoneID",
        "text": "ID"
      },
      {
        "kind": "text",
        "text": "]?"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "recordZoneIDs"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "recordZoneIDs"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "recordZoneIDs"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordZone",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKRecordZone",
              "text": "CKRecordZone"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordZone/ID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKRecordZoneID",
              "text": "ID"
            },
            {
              "kind": "text",
              "text": "]? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Typically, you set the value of this property when you create the operation. If you intend to change the record zone IDs, update the value before you execute the operation or submit it to a queue.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation": {
      "abstract": [
        {
          "text": "An operation that fetches record zone changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKFetchRecordZoneChangesOperation"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKFetchRecordZoneChangesOperation"
        }
      ],
      "role": "symbol",
      "title": "CKFetchRecordZoneChangesOperation",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchrecordzonechangesoperation"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/ZoneConfiguration": {
      "abstract": [
        {
          "text": "A configuration object that describes the information to fetch from a record zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ZoneConfiguration"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/ZoneConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ZoneConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CKFetchRecordZoneChangesOperation.ZoneConfiguration",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchrecordzonechangesoperation/zoneconfiguration"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/configurationsByRecordZoneID": {
      "abstract": [
        {
          "text": "A dictionary of configurations for fetching change operations by zone identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationsByRecordZoneID"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordZone",
          "text": "CKRecordZone"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordZoneID",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKFetchRecordZoneChangesOperation",
          "text": "CKFetchRecordZoneChangesOperation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKFetchRecordZoneChangesConfiguration",
          "text": "ZoneConfiguration"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/configurationsByRecordZoneID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configurationsByRecordZoneID"
        }
      ],
      "role": "symbol",
      "title": "configurationsByRecordZoneID",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchrecordzonechangesoperation/configurationsbyrecordzoneid"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/fetchAllChanges": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to send repeated requests to the server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchAllChanges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/fetchAllChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchAllChanges"
        }
      ],
      "role": "symbol",
      "title": "fetchAllChanges",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchrecordzonechangesoperation/fetchallchanges"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/recordZoneIDs": {
      "abstract": [
        {
          "text": "The IDs of the record zones that contain the records to fetch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordZoneIDs"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordZone",
          "text": "CKRecordZone"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKRecordZoneID",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/recordZoneIDs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordZoneIDs"
        }
      ],
      "role": "symbol",
      "title": "recordZoneIDs",
      "type": "topic",
      "url": "/documentation/cloudkit/ckfetchrecordzonechangesoperation/recordzoneids"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordZone": {
      "abstract": [
        {
          "text": "A database partition that contains related records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKRecordZone"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordZone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecordZone"
        }
      ],
      "role": "symbol",
      "title": "CKRecordZone",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordzone"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordZone/ID": {
      "abstract": [
        {
          "text": "An object that uniquely identifies a record zone in a database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ID"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordZone/ID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ID"
        }
      ],
      "role": "symbol",
      "title": "CKRecordZone.ID",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordzone/id"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-Zone-Change-Operation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/configurationsByRecordZoneID",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/ZoneConfiguration",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/fetchAllChanges"
      ],
      "title": "Configuring the Zone Change Operation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "recordZoneIDs"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recordZoneIDs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-Zone-Change-Operation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/configurationsByRecordZoneID",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/ZoneConfiguration",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKFetchRecordZoneChangesOperation/fetchAllChanges"
              ],
              "title": "Configuring the Zone Change Operation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<CKRecordZoneID *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "recordZoneIDs"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordZone~1ID/title",
          "value": "CKRecordZoneID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordZone~1ID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordZoneID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordZone~1ID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordZoneID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation/title",
          "value": "CKFetchRecordZoneChangesOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKFetchRecordZoneChangesOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKFetchRecordZoneChangesOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordZone/title",
          "value": "CKRecordZone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordZone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordZone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordZone/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordZone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation~1ZoneConfiguration/title",
          "value": "CKFetchRecordZoneChangesConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation~1ZoneConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKFetchRecordZoneChangesConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation~1ZoneConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKFetchRecordZoneChangesConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation~1recordZoneIDs/title",
          "value": "recordZoneIDs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation~1recordZoneIDs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recordZoneIDs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation~1configurationsByRecordZoneID/title",
          "value": "configurationsByRecordZoneID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation~1configurationsByRecordZoneID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "configurationsByRecordZoneID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation~1fetchAllChanges/title",
          "value": "fetchAllChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKFetchRecordZoneChangesOperation~1fetchAllChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fetchAllChanges"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckfetchrecordzonechangesoperation/recordzoneids"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/ckfetchrecordzonechangesoperation/recordzoneids"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
