{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIEvent/touches(for:)-9neb4","doc://com.apple.uikit/documentation/UIKit/UIEvent/touches(for:)-767rm","doc://com.apple.uikit/documentation/UIKit/UIEvent/coalescedTouches(for:)","doc://com.apple.uikit/documentation/UIKit/UIEvent/predictedTouches(for:)"],"anchor":"Getting-the-touches-for-an-event","title":"Getting the touches for an event"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIEvent/allTouches"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIEvent"]]},"abstract":[{"type":"text","text":"All touches associated with the event."}],"metadata":{"platforms":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"2.0"},{"unavailable":false,"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"2.0"},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"13.1"},{"unavailable":false,"name":"tvOS","beta":false,"deprecated":false},{"unavailable":false,"name":"visionOS","beta":false,"deprecated":false,"introducedAt":"1.0"}],"externalID":"c:objc(cs)UIEvent(py)allTouches","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allTouches"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":">?"}],"navigatorTitle":[{"kind":"identifier","text":"allTouches"}],"symbolKind":"property","title":"allTouches","roleHeading":"Instance Property","modules":[{"name":"UIKit"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allTouches"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Sh","preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"kind":"text","text":"<"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch","preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier","text":"UITouch"},{"kind":"text","text":">? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]},{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"A set of "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch"},{"type":"text","text":" objects representing all touches associated with the event."}],"type":"paragraph"}],"kind":"content"},{"content":[{"anchor":"Discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"text":"If the touches of the event originate in different views and windows, the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch"},{"text":" objects obtained from this method will be associated with different responder objects.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["/documentation/uikit/uievent/alltouches"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uievent/alltouches"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIEvent":{"abstract":[{"type":"text","text":"An object that describes a single user interaction with your app."}],"title":"UIEvent","url":"/documentation/uikit/uievent","navigatorTitle":[{"text":"UIEvent","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEvent","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIEvent","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIEvent/coalescedTouches(for:)":{"title":"coalescedTouches(for:)","role":"symbol","url":"/documentation/uikit/uievent/coalescedtouches(for:)","abstract":[{"type":"text","text":"Returns all of the touches associated with the specified main touch."}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"coalescedTouches","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch"},{"kind":"text","text":"]?"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"coalescedTouchesForTouch:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEvent/coalescedTouches(for:)"},"doc://com.apple.uikit/documentation/UIKit/UIEvent/touches(for:)-9neb4":{"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEvent/touches(for:)-9neb4","url":"/documentation/uikit/uievent/touches(for:)-9neb4","type":"topic","title":"touches(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"touches"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier"},{"text":">?","kind":"text"}],"navigatorTitle":[{"text":"touchesForView:","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns the touch objects from the event that belong to the specified given view."}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIEvent/allTouches":{"abstract":[{"type":"text","text":"All touches associated with the event."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allTouches"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier","text":"UITouch"},{"text":">?","kind":"text"}],"title":"allTouches","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEvent/allTouches","navigatorTitle":[{"text":"allTouches","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/uievent/alltouches","role":"symbol"},"doc://com.externally.resolved.symbol/s:Sh":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sh","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"text":" ","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Set"},{"text":"<","kind":"text"},{"text":"Element","kind":"genericParameter"},{"kind":"text","text":"> "},{"text":"where","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Element"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SH","text":"Hashable","kind":"typeIdentifier"}],"url":"/documentation/Swift/Set","abstract":[{"type":"text","text":"An unordered collection of unique elements."}],"title":"Set","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITouch":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITouch"}],"type":"topic","title":"UITouch","url":"/documentation/uikit/uitouch","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch","navigatorTitle":[{"kind":"identifier","text":"UITouch"}],"abstract":[{"text":"An object representing the location, size, movement, and force of a touch occurring on the screen.","type":"text"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIEvent/predictedTouches(for:)":{"navigatorTitle":[{"kind":"identifier","text":"predictedTouchesForTouch:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predictedTouches"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier","text":"UITouch"},{"kind":"text","text":") -> ["},{"preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier","text":"UITouch"},{"kind":"text","text":"]?"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEvent/predictedTouches(for:)","type":"topic","title":"predictedTouches(for:)","url":"/documentation/uikit/uievent/predictedtouches(for:)","abstract":[{"text":"Returns an array of touches that are predicted to occur for the specified touch.","type":"text"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIEvent/touches(for:)-767rm":{"abstract":[{"type":"text","text":"Returns the touch objects from the event that belong to the specified window."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"touches"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIWindow","kind":"typeIdentifier","text":"UIWindow"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch"},{"text":">?","kind":"text"}],"title":"touches(for:)","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEvent/touches(for:)-767rm","navigatorTitle":[{"text":"touchesForWindow:","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/uievent/touches(for:)-767rm","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"2.0"},{"name":"iPadOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"2.0"},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"13.1"},{"name":"tvOS","beta":false,"unavailable":false,"deprecated":false},{"name":"visionOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"1.0"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"allTouches","path":"/metadata/title"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"allTouches"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIEvent"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIEvent/touches(for:)-9neb4","doc://com.apple.uikit/documentation/UIKit/UIEvent/touches(for:)-767rm","doc://com.apple.uikit/documentation/UIKit/UIEvent/coalescedTouches(for:)","doc://com.apple.uikit/documentation/UIKit/UIEvent/predictedTouches(for:)"],"anchor":"Getting-the-touches-for-an-event","title":"Getting the touches for an event"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSSet","kind":"typeIdentifier","text":"NSSet<UITouch *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"allTouches"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent/title","value":"UIEvent"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent/fragments","value":[{"text":"UIEvent","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent/navigatorTitle","value":[{"text":"UIEvent","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1coalescedTouches(for:)/title","value":"coalescedTouchesForTouch:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1coalescedTouches(for:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"coalescedTouchesForTouch:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1touches(for:)-9neb4/title","value":"touchesForView:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1touches(for:)-9neb4/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"touchesForView:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1allTouches/title","value":"allTouches"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1allTouches/fragments","value":[{"text":"allTouches","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch/title","value":"UITouch"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch/fragments","value":[{"kind":"identifier","text":"UITouch"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch/navigatorTitle","value":[{"text":"UITouch","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1predictedTouches(for:)/title","value":"predictedTouchesForTouch:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1predictedTouches(for:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"predictedTouchesForTouch:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1touches(for:)-767rm/title","value":"touchesForWindow:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1touches(for:)-767rm/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"touchesForWindow:"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}