{
  "abstract": [
    {
      "text": "Constants that specify the subtype of the event in relation to its general type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UIEventSubtype",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "EventSubtype"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EventSubtype"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIEvent.EventSubtype"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "EventSubtype"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can obtain the subtype of an event from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/subtype",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent": {
      "abstract": [
        {
          "text": "An object that describes a single user interaction with your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIEvent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEvent"
        }
      ],
      "role": "symbol",
      "title": "UIEvent",
      "type": "topic",
      "url": "/documentation/uikit/uievent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype": {
      "abstract": [
        {
          "text": "Constants that specify the subtype of the event in relation to its general type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EventSubtype"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EventSubtype"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/motionShake": {
      "abstract": [
        {
          "text": "The event is related to a person shaking the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionShake"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/motionShake",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeMotionShake"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.motionShake",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/motionshake"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/none": {
      "abstract": [
        {
          "text": "The event has no subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeNone"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.none",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/none"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlBeginSeekingBackward": {
      "abstract": [
        {
          "text": "A remote-control event to start seeking backward through the audio or video medium.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlBeginSeekingBackward"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlBeginSeekingBackward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlBeginSeekingBackward"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlBeginSeekingBackward",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontrolbeginseekingbackward"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlBeginSeekingForward": {
      "abstract": [
        {
          "text": "A remote-control event to start seeking forward through the audio or video medium.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlBeginSeekingForward"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlBeginSeekingForward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlBeginSeekingForward"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlBeginSeekingForward",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontrolbeginseekingforward"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlEndSeekingBackward": {
      "abstract": [
        {
          "text": "A remote-control event to end seeking backward through the audio or video medium.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlEndSeekingBackward"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlEndSeekingBackward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlEndSeekingBackward"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlEndSeekingBackward",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontrolendseekingbackward"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlEndSeekingForward": {
      "abstract": [
        {
          "text": "A remote-control event to end seeking forward through the audio or video medium.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlEndSeekingForward"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlEndSeekingForward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlEndSeekingForward"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlEndSeekingForward",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontrolendseekingforward"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlNextTrack": {
      "abstract": [
        {
          "text": "A remote-control event for skipping to the next audio or video track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlNextTrack"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlNextTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlNextTrack"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlNextTrack",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontrolnexttrack"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPause": {
      "abstract": [
        {
          "text": "A remote-control event for pausing audio or video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlPause"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlPause"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlPause",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontrolpause"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPlay": {
      "abstract": [
        {
          "text": "A remote-control event for playing audio or video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlPlay"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlPlay"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlPlay",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontrolplay"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPreviousTrack": {
      "abstract": [
        {
          "text": "A remote-control event for skipping to the previous audio or video track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlPreviousTrack"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPreviousTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlPreviousTrack"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlPreviousTrack",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontrolprevioustrack"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlStop": {
      "abstract": [
        {
          "text": "A remote-control event for stopping audio or video from playing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlStop"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlStop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlStop"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlStop",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontrolstop"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlTogglePlayPause": {
      "abstract": [
        {
          "text": "A remote-control event for toggling audio or video between play and pause.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteControlTogglePlayPause"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlTogglePlayPause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEventSubtypeRemoteControlTogglePlayPause"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventSubtype.remoteControlTogglePlayPause",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventsubtype/remotecontroltoggleplaypause"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventType": {
      "abstract": [
        {
          "text": "Constants that specify the general type of an event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EventType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EventType"
        }
      ],
      "role": "symbol",
      "title": "UIEvent.EventType",
      "type": "topic",
      "url": "/documentation/uikit/uievent/eventtype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/subtype": {
      "abstract": [
        {
          "text": "Returns the subtype of the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIEvent",
          "text": "UIEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIEventSubtype",
          "text": "EventSubtype"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/subtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subtype"
        }
      ],
      "role": "symbol",
      "title": "subtype",
      "type": "topic",
      "url": "/documentation/uikit/uievent/subtype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent/type": {
      "abstract": [
        {
          "text": "Returns the type of the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIEvent",
          "text": "UIEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIEventType",
          "text": "EventType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/uikit/uievent/type"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-event-type",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/type",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventType",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/subtype"
      ],
      "title": "Getting the event type"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/none",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/motionShake",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPlay",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPause",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlStop",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlTogglePlayPause",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlNextTrack",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPreviousTrack",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlBeginSeekingBackward",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlEndSeekingBackward",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlBeginSeekingForward",
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlEndSeekingForward"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIEventSubtype"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/none",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/motionShake",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPlay",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPause",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlStop",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlTogglePlayPause",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlNextTrack",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlPreviousTrack",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlBeginSeekingBackward",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlEndSeekingBackward",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlBeginSeekingForward",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype/remoteControlEndSeekingForward"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-event-type",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/type",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/EventType",
                "doc://com.apple.uikit/documentation/UIKit/UIEvent/subtype"
              ],
              "title": "Getting the event type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIEventSubtype"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype/title",
          "value": "UIEventSubtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlBeginSeekingForward/title",
          "value": "UIEventSubtypeRemoteControlBeginSeekingForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlBeginSeekingForward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlBeginSeekingForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1motionShake/title",
          "value": "UIEventSubtypeMotionShake"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1motionShake/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeMotionShake"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlStop/title",
          "value": "UIEventSubtypeRemoteControlStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlStop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlPlay/title",
          "value": "UIEventSubtypeRemoteControlPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlTogglePlayPause/title",
          "value": "UIEventSubtypeRemoteControlTogglePlayPause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlTogglePlayPause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlTogglePlayPause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent/title",
          "value": "UIEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1subtype/title",
          "value": "subtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1subtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlPreviousTrack/title",
          "value": "UIEventSubtypeRemoteControlPreviousTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlPreviousTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlPreviousTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlPause/title",
          "value": "UIEventSubtypeRemoteControlPause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlPause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlPause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlEndSeekingBackward/title",
          "value": "UIEventSubtypeRemoteControlEndSeekingBackward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlEndSeekingBackward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlEndSeekingBackward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlEndSeekingForward/title",
          "value": "UIEventSubtypeRemoteControlEndSeekingForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlEndSeekingForward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlEndSeekingForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventType/title",
          "value": "UIEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1none/title",
          "value": "UIEventSubtypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlBeginSeekingBackward/title",
          "value": "UIEventSubtypeRemoteControlBeginSeekingBackward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlBeginSeekingBackward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlBeginSeekingBackward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlNextTrack/title",
          "value": "UIEventSubtypeRemoteControlNextTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype~1remoteControlNextTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEventSubtypeRemoteControlNextTrack"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uievent/eventsubtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uievent/eventsubtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
