{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEvent","preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEvent/EventType","preciseIdentifier":"c:@E@UIEventType","text":"EventType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}]},{"content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEvent/EventType"},{"type":"text","text":" constant returned by this property indicates the general type of this event — for example, whether it’s a touch or motion event."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIEvent"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uievent/type"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uievent/type"]}],"kind":"symbol","seeAlsoSections":[{"anchor":"Getting-the-event-type","generated":true,"title":"Getting the event type","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIEvent/EventType","doc://com.apple.uikit/documentation/UIKit/UIEvent/subtype","doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype"]}],"metadata":{"roleHeading":"Instance Property","platforms":[{"name":"iOS","beta":false,"deprecated":false,"introducedAt":"3.0","unavailable":false},{"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"3.0","unavailable":false},{"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"13.1","unavailable":false},{"name":"tvOS","beta":false,"deprecated":false,"unavailable":false},{"name":"visionOS","beta":false,"deprecated":false,"introducedAt":"1.0","unavailable":false}],"modules":[{"name":"UIKit"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"type"}],"externalID":"c:objc(cs)UIEvent(py)type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"EventType","preciseIdentifier":"c:@E@UIEventType"}],"title":"type"},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIEvent/type","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns the type of the event."}],"sections":[],"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIEvent/EventType":{"url":"/documentation/uikit/uievent/eventtype","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEvent/EventType","navigatorTitle":[{"text":"EventType","kind":"identifier"}],"abstract":[{"text":"Constants that specify the general type of an event.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EventType","kind":"identifier"}],"title":"UIEvent.EventType"},"doc://com.apple.uikit/documentation/UIKit/UIEvent/type":{"navigatorTitle":[{"kind":"identifier","text":"type"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"EventType","preciseIdentifier":"c:@E@UIEventType"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEvent/type","url":"/documentation/uikit/uievent/type","title":"type","abstract":[{"type":"text","text":"Returns the type of the event."}],"role":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIEvent/subtype":{"navigatorTitle":[{"kind":"identifier","text":"subtype"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtype"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIEventSubtype","text":"EventSubtype"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEvent/subtype","url":"/documentation/uikit/uievent/subtype","title":"subtype","abstract":[{"type":"text","text":"Returns the subtype of the event."}],"role":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIEvent":{"abstract":[{"type":"text","text":"An object that describes a single user interaction with your app."}],"title":"UIEvent","url":"/documentation/uikit/uievent","navigatorTitle":[{"text":"UIEvent","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEvent","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIEvent","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventSubtype"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Constants that specify the subtype of the event in relation to its general type."}],"url":"/documentation/uikit/uievent/eventsubtype","navigatorTitle":[{"kind":"identifier","text":"EventSubtype"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype","title":"UIEvent.EventSubtype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"name":"iOS","unavailable":false,"introducedAt":"3.0","beta":false,"deprecated":false},{"name":"iPadOS","unavailable":false,"introducedAt":"3.0","beta":false,"deprecated":false},{"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1","beta":false,"deprecated":false},{"name":"tvOS","unavailable":false,"beta":false,"deprecated":false},{"name":"visionOS","unavailable":false,"introducedAt":"1.0","beta":false,"deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"type","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"type"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIEvent"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Getting the event type","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIEvent/EventType","doc://com.apple.uikit/documentation/UIKit/UIEvent/subtype","doc://com.apple.uikit/documentation/UIKit/UIEvent/EventSubtype"],"anchor":"Getting-the-event-type"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@E@UIEventType","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEvent/EventType","kind":"typeIdentifier","text":"UIEventType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"UIEventType","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventType/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIEventType"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventType/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIEventType"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventType/navigatorTitle"},{"op":"replace","value":"type","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1type/title"},{"op":"replace","value":[{"kind":"identifier","text":"type"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1type/fragments"},{"op":"replace","value":"subtype","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1subtype/title"},{"op":"replace","value":[{"kind":"identifier","text":"subtype"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1subtype/fragments"},{"op":"replace","value":"UIEvent","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent/title"},{"op":"replace","value":[{"text":"UIEvent","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIEvent"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent/navigatorTitle"},{"op":"replace","value":"UIEventSubtype","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIEventSubtype"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIEventSubtype"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent~1EventSubtype/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}