{"kind":"symbol","variants":[{"paths":["/documentation/virtualization/vzgenericmachineidentifier/init(datarepresentation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/virtualization/vzgenericmachineidentifier/init(datarepresentation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Creates a new unique identifier for a VM with the provided data.","type":"text"}],"seeAlsoSections":[{"anchor":"Creating-a-Machine-Identifier","generated":true,"title":"Creating a Machine Identifier","identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/init()"]}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"dataRepresentation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer","platforms":[{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.0","name":"macOS"}],"modules":[{"name":"Virtualization"}],"symbolKind":"init","title":"init(dataRepresentation:)","externalID":"c:objc(cs)VZGenericMachineIdentifier(im)initWithDataRepresentation:","navigatorTitle":[{"text":"initWithDataRepresentation:","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization","doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"dataRepresentation"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DataV","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":")"}],"platforms":["macOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A data object that describes the machine identifier."}],"type":"paragraph"}],"name":"dataRepresentation"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/init(dataRepresentation:)"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.virtualization/documentation/Virtualization":{"type":"topic","abstract":[{"text":"Create virtual machines and run macOS and Linux-based operating systems.","type":"text"}],"role":"collection","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization","title":"Virtualization","url":"/documentation/virtualization"},"doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VZGenericMachineIdentifier","kind":"identifier"}],"navigatorTitle":[{"text":"VZGenericMachineIdentifier","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier","abstract":[{"type":"text","text":"An object that represents a unique identifier for a virtual machine."}],"url":"/documentation/virtualization/vzgenericmachineidentifier","kind":"symbol","title":"VZGenericMachineIdentifier"},"doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/init(dataRepresentation:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithDataRepresentation:"}],"type":"topic","abstract":[{"type":"text","text":"Creates a new unique identifier for a VM with the provided data."}],"role":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/init(dataRepresentation:)","url":"/documentation/virtualization/vzgenericmachineidentifier/init(datarepresentation:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"dataRepresentation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"title":"init(dataRepresentation:)"},"doc://com.externally.resolved.symbol/s:10Foundation4DataV":{"fragments":[{"text":"struct ","kind":"text"},{"kind":"identifier","text":"Data"}],"role":"symbol","type":"topic","url":"/documentation/foundation/data","kind":"symbol","title":"Data","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DataV","abstract":[{"text":"A byte buffer in memory.","type":"text"}]},"doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/init()":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","abstract":[{"type":"text","text":"Creates a new unique identifier for a VM."}],"role":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/init()","url":"/documentation/virtualization/vzgenericmachineidentifier/init()","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","role":"overview","kind":"technologies","abstract":[{"text":"","type":"text"}],"type":"topic","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"name":"macOS","unavailable":false,"introducedAt":"13.0","beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"initWithDataRepresentation:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDataRepresentation:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization","doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZGenericMachineIdentifier/init()"],"generated":true,"title":"Creating a Machine Identifier","anchor":"Creating-a-Machine-Identifier"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDataRepresentation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dataRepresentation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"}},{"path":"/primaryContentSections/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"dataRepresentation","content":[{"inlineContent":[{"text":"A data object that describes the machine identifier.","type":"text"}],"type":"paragraph"}]}]}},{"value":"VZGenericMachineIdentifier","op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericMachineIdentifier/title"},{"value":[{"text":"VZGenericMachineIdentifier","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericMachineIdentifier/fragments"},{"value":[{"kind":"identifier","text":"VZGenericMachineIdentifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericMachineIdentifier/navigatorTitle"},{"value":"initWithDataRepresentation:","op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericMachineIdentifier~1init(dataRepresentation:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDataRepresentation:"}],"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericMachineIdentifier~1init(dataRepresentation:)/fragments"},{"value":"init","op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericMachineIdentifier~1init()/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZGenericMachineIdentifier~1init()/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}