{
  "abstract": [
    {
      "text": "Identifies an ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " object containing a Boolean that indicates whether the image is dithered.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/ditherTransparency"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSImageDitherTransparency",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ditherTransparency"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
        "text": "NSBitmapImageRep"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSBitmapImageRepPropertyKey",
        "text": "PropertyKey"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSImageDitherTransparency"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "ditherTransparency"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ditherTransparency"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
              "text": "NSBitmapImageRep"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSBitmapImageRepPropertyKey",
              "text": "PropertyKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Used only when writing GIF files.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep": {
      "abstract": [
        {
          "text": "An object that renders an image from bitmap data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBitmapImageRep"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBitmapImageRep"
        }
      ],
      "role": "symbol",
      "title": "NSBitmapImageRep",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey": {
      "abstract": [
        {
          "text": "Constants that identify bitmap image representation properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PropertyKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PropertyKey"
        }
      ],
      "role": "symbol",
      "title": "NSBitmapImageRep.PropertyKey",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/propertykey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/colorSyncProfileData": {
      "abstract": [
        {
          "text": "Identifies an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsdata",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object containing the ColorSync profile data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorSyncProfileData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBitmapImageRepPropertyKey",
          "text": "PropertyKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/colorSyncProfileData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageColorSyncProfileData"
        }
      ],
      "role": "symbol",
      "title": "colorSyncProfileData",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/propertykey/colorsyncprofiledata"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/compressionFactor": {
      "abstract": [
        {
          "text": "Identifies an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object containing the compression factor of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compressionFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBitmapImageRepPropertyKey",
          "text": "PropertyKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/compressionFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageCompressionFactor"
        }
      ],
      "role": "symbol",
      "title": "compressionFactor",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/propertykey/compressionfactor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/compressionMethod": {
      "abstract": [
        {
          "text": "Identifies an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object identifying the compression method of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compressionMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBitmapImageRepPropertyKey",
          "text": "PropertyKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/compressionMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageCompressionMethod"
        }
      ],
      "role": "symbol",
      "title": "compressionMethod",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/propertykey/compressionmethod"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/currentFrame": {
      "abstract": [
        {
          "text": "Identifies an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object containing the current frame for an animated GIF file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBitmapImageRepPropertyKey",
          "text": "PropertyKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/currentFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageCurrentFrame"
        }
      ],
      "role": "symbol",
      "title": "currentFrame",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/propertykey/currentframe"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/currentFrameDuration": {
      "abstract": [
        {
          "text": "Identifies an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object containing the duration (in seconds) of the current frame for an animated GIF image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentFrameDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBitmapImageRepPropertyKey",
          "text": "PropertyKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/currentFrameDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageCurrentFrameDuration"
        }
      ],
      "role": "symbol",
      "title": "currentFrameDuration",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/propertykey/currentframeduration"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/ditherTransparency": {
      "abstract": [
        {
          "text": "Identifies an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object containing a Boolean that indicates whether the image is dithered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ditherTransparency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBitmapImageRepPropertyKey",
          "text": "PropertyKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/ditherTransparency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageDitherTransparency"
        }
      ],
      "role": "symbol",
      "title": "ditherTransparency",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/propertykey/dithertransparency"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/exifData": {
      "abstract": [
        {
          "text": "Identifies an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsdictionary",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object containing the EXIF data for the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exifData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBitmapImageRepPropertyKey",
          "text": "PropertyKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/exifData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageEXIFData"
        }
      ],
      "role": "symbol",
      "title": "exifData",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/propertykey/exifdata"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/fallbackBackgroundColor": {
      "abstract": [
        {
          "text": "Specifies the background color to use when writing to an image format (such as JPEG) that doesn’t support alpha. The color’s alpha value is ignored. The default background color, when this property is not specified, is white. The value of the property should be an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object. This constant corresponds to the kCGImageDestinationBackgroundColor constant in Quartz.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fallbackBackgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBitmapImageRepPropertyKey",
          "text": "PropertyKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/fallbackBackgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageFallbackBackgroundColor"
        }
      ],
      "role": "symbol",
      "title": "fallbackBackgroundColor",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/propertykey/fallbackbackgroundcolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/frameCount": {
      "abstract": [
        {
          "text": "Identifies an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object containing the number of frames in an animated GIF file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBitmapImageRepPropertyKey",
          "text": "PropertyKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/frameCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageFrameCount"
        }
      ],
      "role": "symbol",
      "title": "frameCount",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/propertykey/framecount"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/gamma": {
      "abstract": [
        {
          "text": "Identifies an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object containing the gamma value for the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gamma"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBitmapImageRepPropertyKey",
          "text": "PropertyKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/gamma",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageGamma"
        }
      ],
      "role": "symbol",
      "title": "gamma",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/propertykey/gamma"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/interlaced": {
      "abstract": [
        {
          "text": "Identifies an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object containing a Boolean value that indicates whether the image is interlaced.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interlaced"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBitmapImageRepPropertyKey",
          "text": "PropertyKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/interlaced",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageInterlaced"
        }
      ],
      "role": "symbol",
      "title": "interlaced",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/propertykey/interlaced"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/loopCount": {
      "abstract": [
        {
          "text": "Identifies an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object containing the number of loops to make when animating a GIF image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loopCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBitmapImageRepPropertyKey",
          "text": "PropertyKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/loopCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageLoopCount"
        }
      ],
      "role": "symbol",
      "title": "loopCount",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/propertykey/loopcount"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/progressive": {
      "abstract": [
        {
          "text": "Identifies an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object containing a Boolean that indicates whether the image uses progressive encoding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "progressive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBitmapImageRepPropertyKey",
          "text": "PropertyKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/progressive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageProgressive"
        }
      ],
      "role": "symbol",
      "title": "progressive",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/propertykey/progressive"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/rgbColorTable": {
      "abstract": [
        {
          "text": "Identifies an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsdata",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object containing the RGB color table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgbColorTable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSBitmapImageRepPropertyKey",
          "text": "PropertyKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/rgbColorTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageRGBColorTable"
        }
      ],
      "role": "symbol",
      "title": "rgbColorTable",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/propertykey/rgbcolortable"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity (alpha value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "role": "symbol",
      "title": "NSColor",
      "type": "topic",
      "url": "/documentation/appkit/nscolor"
    },
    "doc://com.apple.documentation/documentation/foundation/nsdata": {
      "abstract": [
        {
          "text": "A static byte buffer that bridges to ; use  when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSData"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsdata",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSData",
      "type": "topic",
      "url": "/documentation/foundation/nsdata"
    },
    "doc://com.apple.documentation/documentation/foundation/nsdictionary": {
      "abstract": [
        {
          "text": "An object representing a static collection of key-value pairs, for use instead of a  constant in cases that require reference semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSDictionary"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsdictionary",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDictionary",
      "type": "topic",
      "url": "/documentation/foundation/nsdictionary"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Bitmap-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/colorSyncProfileData",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/compressionFactor",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/compressionMethod",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/currentFrame",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/currentFrameDuration",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/exifData",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/fallbackBackgroundColor",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/frameCount",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/gamma",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/interlaced",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/loopCount",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/progressive",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/rgbColorTable"
      ],
      "title": "Bitmap Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSImageDitherTransparency"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDitherTransparency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Bitmap-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/colorSyncProfileData",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/compressionFactor",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/compressionMethod",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/currentFrame",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/currentFrameDuration",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/exifData",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/fallbackBackgroundColor",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/frameCount",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/gamma",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/interlaced",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/loopCount",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/progressive",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey/rgbColorTable"
              ],
              "title": "Bitmap Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/PropertyKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSBitmapImageRepPropertyKey",
                    "text": "NSBitmapImageRepPropertyKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSImageDitherTransparency"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1colorSyncProfileData/title",
          "value": "NSImageColorSyncProfileData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1colorSyncProfileData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageColorSyncProfileData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1gamma/title",
          "value": "NSImageGamma"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1gamma/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageGamma"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1rgbColorTable/title",
          "value": "NSImageRGBColorTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1rgbColorTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageRGBColorTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1exifData/title",
          "value": "NSImageEXIFData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1exifData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageEXIFData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsdictionary/abstract",
          "value": [
            {
              "text": "A static collection of objects associated with unique keys.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1currentFrameDuration/title",
          "value": "NSImageCurrentFrameDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1currentFrameDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageCurrentFrameDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1compressionFactor/title",
          "value": "NSImageCompressionFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1compressionFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageCompressionFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep/title",
          "value": "NSBitmapImageRep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1ditherTransparency/title",
          "value": "NSImageDitherTransparency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1ditherTransparency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDitherTransparency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1frameCount/title",
          "value": "NSImageFrameCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1frameCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageFrameCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1currentFrame/title",
          "value": "NSImageCurrentFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1currentFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageCurrentFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1progressive/title",
          "value": "NSImageProgressive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1progressive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageProgressive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1loopCount/title",
          "value": "NSImageLoopCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1loopCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageLoopCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey/title",
          "value": "NSBitmapImageRepPropertyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapImageRepPropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapImageRepPropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1compressionMethod/title",
          "value": "NSImageCompressionMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1compressionMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageCompressionMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsdata/abstract",
          "value": [
            {
              "text": "A static byte buffer in memory.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/title",
          "value": "NSColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1interlaced/title",
          "value": "NSImageInterlaced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1interlaced/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageInterlaced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1fallbackBackgroundColor/title",
          "value": "NSImageFallbackBackgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1PropertyKey~1fallbackBackgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageFallbackBackgroundColor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsbitmapimagerep/propertykey/dithertransparency"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsbitmapimagerep/propertykey/dithertransparency"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
