{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination"]]},"seeAlsoSections":[{"anchor":"Managing-a-Dragging-Session-Before-an-Image-Is-Released","title":"Managing a Dragging Session Before an Image Is Released","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingEntered(_:)","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/wantsPeriodicDraggingUpdates()","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingUpdated(_:)","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingEnded(_:)"]}],"variants":[{"paths":["/documentation/appkit/nsdraggingdestination/draggingexited(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsdraggingdestination/draggingexited(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Invoked when the dragged image exits the destination’s bounds rectangle (in the case of a view object) or its frame rectangle (in the case of a window object).","type":"text"}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingExited(_:)","interfaceLanguage":"swift"},"metadata":{"platforms":[{"beta":false,"name":"macOS","deprecated":false,"unavailable":false}],"symbolKind":"method","navigatorTitle":[{"text":"draggingExited:","kind":"identifier"}],"title":"draggingExited(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"draggingExited","kind":"identifier"},{"text":"((any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSDraggingInfo","text":"NSDraggingInfo","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"AppKit"}],"externalID":"c:objc(pl)NSDraggingDestination(im)draggingExited:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"draggingExited","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":": (any ","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo","text":"NSDraggingInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSDraggingInfo"},{"text":")?)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"sender","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The object sending the message; use it to get details about the dragging operation."}]}]}]}],"kind":"symbol","sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/wantsPeriodicDraggingUpdates()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"wantsPeriodicDraggingUpdates","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/wantsPeriodicDraggingUpdates()","url":"/documentation/appkit/nsdraggingdestination/wantsperiodicdraggingupdates()","type":"topic","navigatorTitle":[{"text":"wantsPeriodicDraggingUpdates","kind":"identifier"}],"title":"wantsPeriodicDraggingUpdates()","abstract":[{"text":"Asks the destination object whether it wants to receive periodic ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingUpdated(_:)"},{"text":" messages.","type":"text"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingUpdated(_:)":{"navigatorTitle":[{"text":"draggingUpdated:","kind":"identifier"}],"title":"draggingUpdated(_:)","url":"/documentation/appkit/nsdraggingdestination/draggingupdated(_:)","abstract":[{"type":"text","text":"Invoked periodically as the image is held within the destination area, allowing modification of the dragging operation or mouse-pointer position."}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingUpdated(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"draggingUpdated","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSDraggingInfo","text":"NSDraggingInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@NSDragOperation","text":"NSDragOperation","kind":"typeIdentifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingExited(_:)":{"kind":"symbol","title":"draggingExited(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"draggingExited","kind":"identifier"},{"text":"((any ","kind":"text"},{"text":"NSDraggingInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSDraggingInfo"},{"text":")?)","kind":"text"}],"type":"topic","url":"/documentation/appkit/nsdraggingdestination/draggingexited(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingExited(_:)","navigatorTitle":[{"text":"draggingExited:","kind":"identifier"}],"abstract":[{"text":"Invoked when the dragged image exits the destination’s bounds rectangle (in the case of a view object) or its frame rectangle (in the case of a window object).","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingEnded(_:)":{"title":"draggingEnded(_:)","kind":"symbol","role":"symbol","url":"/documentation/appkit/nsdraggingdestination/draggingended(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingEnded(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"draggingEnded","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"NSDraggingInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSDraggingInfo"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"draggingEnded:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Called when a drag operation ends."}]},"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingEntered(_:)":{"role":"symbol","title":"draggingEntered(_:)","type":"topic","url":"/documentation/appkit/nsdraggingdestination/draggingentered(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"draggingEntered","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSDraggingInfo","text":"NSDraggingInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@NSDragOperation","text":"NSDragOperation","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"draggingEntered:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingEntered(_:)","abstract":[{"text":"Invoked when the dragged image enters destination bounds or frame; delegate returns dragging operation to perform.","type":"text"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination":{"abstract":[{"type":"text","text":"A set of methods that the destination object (or recipient) of a dragged image must implement."}],"url":"/documentation/appkit/nsdraggingdestination","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSDraggingDestination"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination","title":"NSDraggingDestination","navigatorTitle":[{"kind":"identifier","text":"NSDraggingDestination"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"NSDraggingInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"A set of methods that supply information about a dragging session."}],"url":"/documentation/appkit/nsdragginginfo","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDraggingInfo","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo","title":"NSDraggingInfo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"name":"macOS","deprecated":false,"unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"draggingExited:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"draggingExited:","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination"]]}},{"path":"/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingEntered(_:)","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/wantsPeriodicDraggingUpdates()","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingUpdated(_:)","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingEnded(_:)"],"title":"Managing a Dragging Session Before an Image Is Released","generated":true,"anchor":"Managing-a-Dragging-Session-Before-an-Image-Is-Released"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"draggingExited:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<NSDraggingInfo>","preciseIdentifier":"c:Qoobjc(pl)NSDraggingInfo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":{"parameters":[{"name":"sender","content":[{"type":"paragraph","inlineContent":[{"text":"The object sending the message; use it to get details about the dragging operation.","type":"text"}]}]}],"kind":"parameters"},"op":"replace","path":"/primaryContentSections/1"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1wantsPeriodicDraggingUpdates()/title","value":"wantsPeriodicDraggingUpdates","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1wantsPeriodicDraggingUpdates()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"wantsPeriodicDraggingUpdates"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingUpdated(_:)/title","value":"draggingUpdated:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingUpdated(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"draggingUpdated:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingExited(_:)/title","value":"draggingExited:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingExited(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"draggingExited:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingEnded(_:)/title","value":"draggingEnded:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingEnded(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"draggingEnded:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingEntered(_:)/title","value":"draggingEntered:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingEntered(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"draggingEntered:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/title","op":"replace","value":"NSDraggingDestination"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/fragments","op":"replace","value":[{"kind":"identifier","text":"NSDraggingDestination"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/navigatorTitle","op":"replace","value":[{"text":"NSDraggingDestination","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo/title","op":"replace","value":"NSDraggingInfo"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo/fragments","op":"replace","value":[{"text":"NSDraggingInfo","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo/navigatorTitle","op":"replace","value":[{"text":"NSDraggingInfo","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}