{"kind":"symbol","seeAlsoSections":[{"anchor":"Managing-a-Dragging-Session-After-an-Image-Is-Released","generated":true,"title":"Managing a Dragging Session After an Image Is Released","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/performDragOperation(_:)","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/concludeDragOperation(_:)"]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/prepareForDragOperation(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsdraggingdestination/preparefordragoperation(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsdraggingdestination/preparefordragoperation(_:)"]}],"abstract":[{"text":"Invoked when the image is released, allowing the receiver to agree to or refuse drag operation.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prepareForDragOperation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo","text":"NSDraggingInfo","preciseIdentifier":"c:objc(pl)NSDraggingInfo"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"},{"parameters":[{"name":"sender","content":[{"type":"paragraph","inlineContent":[{"text":"The object sending the message; use it to get details about the dragging operation.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true"},{"type":"text","text":" if the receiver agrees to perform the drag operation and "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false"},{"type":"text","text":" if not."}]}],"kind":"content"},{"content":[{"anchor":"Discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"text":"This method is invoked only if the most recent ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingEntered(_:)"},{"text":" or ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingUpdated(_:)"},{"text":" message returned an acceptable drag-operation value.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"If you want the drag items to animate from their current location on screen to their final location in your view, set the sender object’s ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/animatesToDestination","isActive":true,"type":"reference"},{"text":" property to ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true,"type":"reference"},{"text":" in your implementation of this method.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForDragOperation"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"NSDraggingInfo","preciseIdentifier":"c:objc(pl)NSDraggingInfo"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"prepareForDragOperation:"}],"title":"prepareForDragOperation(_:)","modules":[{"name":"AppKit"}],"platforms":[{"beta":false,"name":"macOS","unavailable":false,"deprecated":false}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(pl)NSDraggingDestination(im)prepareForDragOperation:"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination"]]},"sections":[],"references":{"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/prepareForDragOperation(_:)":{"navigatorTitle":[{"text":"prepareForDragOperation:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForDragOperation"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)NSDraggingInfo","text":"NSDraggingInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"prepareForDragOperation(_:)","role":"symbol","kind":"symbol","abstract":[{"text":"Invoked when the image is released, allowing the receiver to agree to or refuse drag operation.","type":"text"}],"url":"/documentation/appkit/nsdraggingdestination/preparefordragoperation(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/prepareForDragOperation(_:)","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/concludeDragOperation(_:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"concludeDragOperation","kind":"identifier"},{"text":"((any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSDraggingInfo","text":"NSDraggingInfo","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/concludeDragOperation(_:)","abstract":[{"text":"Invoked when the dragging operation is complete, signaling the receiver to perform any necessary clean-up.","type":"text"}],"title":"concludeDragOperation(_:)","navigatorTitle":[{"text":"concludeDragOperation:","kind":"identifier"}],"url":"/documentation/appkit/nsdraggingdestination/concludedragoperation(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination":{"abstract":[{"type":"text","text":"A set of methods that the destination object (or recipient) of a dragged image must implement."}],"url":"/documentation/appkit/nsdraggingdestination","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSDraggingDestination"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination","title":"NSDraggingDestination","navigatorTitle":[{"kind":"identifier","text":"NSDraggingDestination"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/swift/false":{"title":"false","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/false","role":"symbol","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","url":"/documentation/swift/false"},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"NSDraggingInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"A set of methods that supply information about a dragging session."}],"url":"/documentation/appkit/nsdragginginfo","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDraggingInfo","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo","title":"NSDraggingInfo"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingUpdated(_:)":{"navigatorTitle":[{"text":"draggingUpdated:","kind":"identifier"}],"title":"draggingUpdated(_:)","url":"/documentation/appkit/nsdraggingdestination/draggingupdated(_:)","abstract":[{"type":"text","text":"Invoked periodically as the image is held within the destination area, allowing modification of the dragging operation or mouse-pointer position."}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingUpdated(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"draggingUpdated","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSDraggingInfo","text":"NSDraggingInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@NSDragOperation","text":"NSDragOperation","kind":"typeIdentifier"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingEntered(_:)":{"role":"symbol","title":"draggingEntered(_:)","type":"topic","url":"/documentation/appkit/nsdraggingdestination/draggingentered(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"draggingEntered","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSDraggingInfo","text":"NSDraggingInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@NSDragOperation","text":"NSDragOperation","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"draggingEntered:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingEntered(_:)","abstract":[{"text":"Invoked when the dragged image enters destination bounds or frame; delegate returns dragging operation to perform.","type":"text"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/performDragOperation(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/performDragOperation(_:)","navigatorTitle":[{"text":"performDragOperation:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"performDragOperation"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"NSDraggingInfo","preciseIdentifier":"c:objc(pl)NSDraggingInfo"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"text":"Invoked after the released image has been removed from the screen, signaling the receiver to import the pasteboard data.","type":"text"}],"url":"/documentation/appkit/nsdraggingdestination/performdragoperation(_:)","type":"topic","title":"performDragOperation(_:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/animatesToDestination":{"type":"topic","title":"animatesToDestination","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A Boolean value that indicates whether the dragging formation animates while the drag is over the destination."}],"url":"/documentation/appkit/nsdragginginfo/animatestodestination","navigatorTitle":[{"kind":"identifier","text":"animatesToDestination"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animatesToDestination","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingInfo/animatesToDestination"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"name":"macOS","unavailable":false,"deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"prepareForDragOperation:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareForDragOperation:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Managing a Dragging Session After an Image Is Released","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/performDragOperation(_:)","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/concludeDragOperation(_:)"],"anchor":"Managing-a-Dragging-Session-After-an-Image-Is-Released"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"prepareForDragOperation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)NSDraggingInfo","text":"id<NSDraggingInfo>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"sender","content":[{"inlineContent":[{"type":"text","text":"The object sending the message; use it to get details about the dragging operation."}],"type":"paragraph"}]}]},"op":"replace","path":"/primaryContentSections/1"},{"path":"/primaryContentSections/2","op":"replace","value":{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference"},{"text":" if the receiver agrees to perform the drag operation and ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference"},{"text":" if not.","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"value":"prepareForDragOperation:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1prepareForDragOperation(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"prepareForDragOperation:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1prepareForDragOperation(_:)/fragments"},{"value":"concludeDragOperation:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1concludeDragOperation(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"concludeDragOperation:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1concludeDragOperation(_:)/fragments"},{"value":"NSDraggingDestination","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/title"},{"value":[{"kind":"identifier","text":"NSDraggingDestination"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/fragments"},{"op":"replace","value":[{"text":"NSDraggingDestination","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/navigatorTitle"},{"op":"replace","value":"NSDraggingInfo","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo/title"},{"op":"replace","value":[{"text":"NSDraggingInfo","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo/fragments"},{"op":"replace","value":[{"text":"NSDraggingInfo","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo/navigatorTitle"},{"op":"replace","value":"draggingUpdated:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingUpdated(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"draggingUpdated:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingUpdated(_:)/fragments"},{"op":"replace","value":"draggingEntered:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingEntered(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"draggingEntered:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingEntered(_:)/fragments"},{"op":"replace","value":"performDragOperation:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1performDragOperation(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"performDragOperation:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1performDragOperation(_:)/fragments"},{"op":"replace","value":"animatesToDestination","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1animatesToDestination/title"},{"op":"replace","value":[{"text":"animatesToDestination","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingInfo~1animatesToDestination/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}