{"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingEntered(_:)","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingUpdated(_:)","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingExited(_:)","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingEnded(_:)"],"anchor":"Managing-a-Dragging-Session-Before-an-Image-Is-Released","generated":true,"title":"Managing a Dragging Session Before an Image Is Released"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wantsPeriodicDraggingUpdates","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb"}]}]},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true"},{"text":" if the destination wants to receive periodic ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingUpdated(_:)"},{"text":" messages, ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false"},{"text":" otherwise.","type":"text"}]}],"kind":"content"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"Discussion"},{"inlineContent":[{"type":"text","text":"If the destination returns "},{"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference","isActive":true},{"type":"text","text":", these messages are sent only when the mouse moves or a modifier flag changes. Otherwise the destination gets the default behavior, where it receives periodic dragging-updated messages even if nothing changes."}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/wantsPeriodicDraggingUpdates()"},"metadata":{"title":"wantsPeriodicDraggingUpdates()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"wantsPeriodicDraggingUpdates"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":[{"beta":false,"unavailable":false,"deprecated":false,"name":"macOS"}],"externalID":"c:objc(pl)NSDraggingDestination(im)wantsPeriodicDraggingUpdates","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"wantsPeriodicDraggingUpdates"}],"modules":[{"name":"AppKit"}],"symbolKind":"method","role":"symbol"},"abstract":[{"type":"text","text":"Asks the destination object whether it wants to receive periodic "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingUpdated(_:)","isActive":true},{"type":"text","text":" messages."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination"]]},"sections":[],"variants":[{"paths":["/documentation/appkit/nsdraggingdestination/wantsperiodicdraggingupdates()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsdraggingdestination/wantsperiodicdraggingupdates()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingExited(_:)":{"kind":"symbol","title":"draggingExited(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"draggingExited","kind":"identifier"},{"text":"((any ","kind":"text"},{"text":"NSDraggingInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSDraggingInfo"},{"text":")?)","kind":"text"}],"type":"topic","url":"/documentation/appkit/nsdraggingdestination/draggingexited(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingExited(_:)","navigatorTitle":[{"text":"draggingExited:","kind":"identifier"}],"abstract":[{"text":"Invoked when the dragged image exits the destination’s bounds rectangle (in the case of a view object) or its frame rectangle (in the case of a window object).","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingEnded(_:)":{"title":"draggingEnded(_:)","kind":"symbol","role":"symbol","url":"/documentation/appkit/nsdraggingdestination/draggingended(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingEnded(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"draggingEnded","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"NSDraggingInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSDraggingInfo"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"draggingEnded:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Called when a drag operation ends."}]},"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination":{"abstract":[{"type":"text","text":"A set of methods that the destination object (or recipient) of a dragged image must implement."}],"url":"/documentation/appkit/nsdraggingdestination","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSDraggingDestination"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination","title":"NSDraggingDestination","navigatorTitle":[{"kind":"identifier","text":"NSDraggingDestination"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingEntered(_:)":{"role":"symbol","title":"draggingEntered(_:)","type":"topic","url":"/documentation/appkit/nsdraggingdestination/draggingentered(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"draggingEntered","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSDraggingInfo","text":"NSDraggingInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@NSDragOperation","text":"NSDragOperation","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"draggingEntered:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingEntered(_:)","abstract":[{"text":"Invoked when the dragged image enters destination bounds or frame; delegate returns dragging operation to perform.","type":"text"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingUpdated(_:)":{"navigatorTitle":[{"text":"draggingUpdated:","kind":"identifier"}],"title":"draggingUpdated(_:)","url":"/documentation/appkit/nsdraggingdestination/draggingupdated(_:)","abstract":[{"type":"text","text":"Invoked periodically as the image is held within the destination area, allowing modification of the dragging operation or mouse-pointer position."}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingUpdated(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"draggingUpdated","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSDraggingInfo","text":"NSDraggingInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@NSDragOperation","text":"NSDragOperation","kind":"typeIdentifier"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.apple.documentation/documentation/swift/false":{"title":"false","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/false","role":"symbol","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","url":"/documentation/swift/false"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/wantsPeriodicDraggingUpdates()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"wantsPeriodicDraggingUpdates","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/wantsPeriodicDraggingUpdates()","url":"/documentation/appkit/nsdraggingdestination/wantsperiodicdraggingupdates()","type":"topic","navigatorTitle":[{"text":"wantsPeriodicDraggingUpdates","kind":"identifier"}],"title":"wantsPeriodicDraggingUpdates()","abstract":[{"text":"Asks the destination object whether it wants to receive periodic ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingUpdated(_:)"},{"text":" messages.","type":"text"}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"name":"macOS","deprecated":false,"unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"wantsPeriodicDraggingUpdates","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"wantsPeriodicDraggingUpdates","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Managing a Dragging Session Before an Image Is Released","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingEntered(_:)","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingUpdated(_:)","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingExited(_:)","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingEnded(_:)"],"anchor":"Managing-a-Dragging-Session-Before-an-Image-Is-Released","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"wantsPeriodicDraggingUpdates"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":""},{"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference","isActive":true},{"type":"text","text":" if the destination wants to receive periodic "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination/draggingUpdated(_:)","type":"reference","isActive":true},{"type":"text","text":" messages, "},{"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference","isActive":true},{"type":"text","text":" otherwise."}],"type":"paragraph"}],"kind":"content"},"path":"/primaryContentSections/1"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingExited(_:)/title","value":"draggingExited:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingExited(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"draggingExited:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingEnded(_:)/title","value":"draggingEnded:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingEnded(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"draggingEnded:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/title","value":"NSDraggingDestination"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/fragments","value":[{"text":"NSDraggingDestination","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/navigatorTitle","value":[{"text":"NSDraggingDestination","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingEntered(_:)/title","value":"draggingEntered:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingEntered(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"draggingEntered:","kind":"identifier"}]},{"op":"replace","value":"draggingUpdated:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingUpdated(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"draggingUpdated:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1draggingUpdated(_:)/fragments"},{"op":"replace","value":"wantsPeriodicDraggingUpdates","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1wantsPeriodicDraggingUpdates()/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"wantsPeriodicDraggingUpdates"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination~1wantsPeriodicDraggingUpdates()/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}