{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSOpenPanel"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsopenpanel/allowsmultipleselection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsopenpanel/allowsmultipleselection"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/canChooseFiles","doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/canChooseDirectories","doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/resolvesAliases","doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/isAccessoryViewDisclosed"],"generated":true,"anchor":"Configuring-the-Open-Panel","title":"Configuring the Open Panel"}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/allowsMultipleSelection","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsMultipleSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["macOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"anchor":"Discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"text":"When the value of this property is ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference","isActive":true},{"text":", the user may select multiple items from the browser. When the selection contains multiple items, use the ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/urls","type":"reference","isActive":true},{"text":" property to retrieve those items instead of the inherited ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/url"},{"type":"text","text":" property."}],"type":"paragraph"}]}],"sections":[],"abstract":[{"type":"text","text":"A Boolean that indicates whether the user may select multiple files and directories."}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsMultipleSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"modules":[{"name":"AppKit"}],"platforms":[{"deprecated":false,"name":"macOS","unavailable":false,"beta":false}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"allowsMultipleSelection"}],"title":"allowsMultipleSelection","externalID":"c:objc(cs)NSOpenPanel(py)allowsMultipleSelection"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/urls":{"url":"/documentation/appkit/nsopenpanel/urls","identifier":"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/urls","title":"urls","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urls","kind":"identifier"},{"text":": [","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"abstract":[{"text":"An array of URLs, each of which contains the fully specified location of a selected file or directory.","type":"text"}],"navigatorTitle":[{"text":"URLs","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel":{"url":"/documentation/appkit/nsopenpanel","title":"NSOpenPanel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSOpenPanel"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSOpenPanel"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel","abstract":[{"text":"A panel that prompts the user to select a file to open.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/isAccessoryViewDisclosed":{"title":"isAccessoryViewDisclosed","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAccessoryViewDisclosed","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"text":"A Boolean value that indicates whether the panel’s accessory view is visible.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/isAccessoryViewDisclosed","type":"topic","role":"symbol","url":"/documentation/appkit/nsopenpanel/isaccessoryviewdisclosed","navigatorTitle":[{"text":"accessoryViewDisclosed","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/url":{"title":"url","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"abstract":[{"text":"A URL that contains the fully specified location of the targeted file.","type":"text"}],"navigatorTitle":[{"text":"URL","kind":"identifier"}],"role":"symbol","url":"/documentation/appkit/nssavepanel/url","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSavePanel/url","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/canChooseFiles":{"url":"/documentation/appkit/nsopenpanel/canchoosefiles","identifier":"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/canChooseFiles","title":"canChooseFiles","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canChooseFiles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A Boolean that indicates whether the user can choose files in the panel."}],"navigatorTitle":[{"text":"canChooseFiles","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/resolvesAliases":{"url":"/documentation/appkit/nsopenpanel/resolvesaliases","identifier":"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/resolvesAliases","title":"resolvesAliases","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resolvesAliases","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"A Boolean that indicates whether the panel resolves aliases.","type":"text"}],"navigatorTitle":[{"text":"resolvesAliases","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/canChooseDirectories":{"title":"canChooseDirectories","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canChooseDirectories","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"text":"A Boolean that indicates whether the user can choose directories in the panel.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/canChooseDirectories","type":"topic","role":"symbol","url":"/documentation/appkit/nsopenpanel/canchoosedirectories","navigatorTitle":[{"text":"canChooseDirectories","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/allowsMultipleSelection":{"abstract":[{"type":"text","text":"A Boolean that indicates whether the user may select multiple files and directories."}],"title":"allowsMultipleSelection","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/allowsMultipleSelection","type":"topic","navigatorTitle":[{"text":"allowsMultipleSelection","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsMultipleSelection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"/documentation/appkit/nsopenpanel/allowsmultipleselection","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"name":"macOS","unavailable":false,"beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"allowsMultipleSelection","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"allowsMultipleSelection","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSOpenPanel"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Configuring the Open Panel","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/canChooseFiles","doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/canChooseDirectories","doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/resolvesAliases","doc://com.apple.appkit/documentation/AppKit/NSOpenPanel/isAccessoryViewDisclosed"],"anchor":"Configuring-the-Open-Panel"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsMultipleSelection"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"]}]},"path":"/primaryContentSections/0"},{"value":"URLs","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel~1urls/title","op":"replace"},{"value":[{"kind":"identifier","text":"URLs"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel~1urls/fragments","op":"replace"},{"value":"NSOpenPanel","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel/title","op":"replace"},{"value":[{"text":"NSOpenPanel","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel/fragments","op":"replace"},{"value":[{"text":"NSOpenPanel","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel/navigatorTitle","op":"replace"},{"value":"accessoryViewDisclosed","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel~1isAccessoryViewDisclosed/title","op":"replace"},{"value":[{"kind":"identifier","text":"accessoryViewDisclosed"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel~1isAccessoryViewDisclosed/fragments","op":"replace"},{"value":"URL","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1url/title","op":"replace"},{"value":[{"text":"URL","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSavePanel~1url/fragments","op":"replace"},{"value":"canChooseFiles","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel~1canChooseFiles/title","op":"replace"},{"value":[{"kind":"identifier","text":"canChooseFiles"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel~1canChooseFiles/fragments","op":"replace"},{"value":"resolvesAliases","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel~1resolvesAliases/title","op":"replace"},{"value":[{"text":"resolvesAliases","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel~1resolvesAliases/fragments","op":"replace"},{"value":"canChooseDirectories","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel~1canChooseDirectories/title","op":"replace"},{"value":[{"text":"canChooseDirectories","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel~1canChooseDirectories/fragments","op":"replace"},{"value":"allowsMultipleSelection","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel~1allowsMultipleSelection/title","op":"replace"},{"value":[{"text":"allowsMultipleSelection","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel~1allowsMultipleSelection/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}