{
  "abstract": [
    {
      "text": "Set criteria for assigning players to teams in your game using matchmaking rules.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit",
        "doc://com.apple.gamekit/documentation/GameKit/matchmaking-rules"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/assigning-players-to-teams-using-rules"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Assigning players to teams using rules"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If your game has teams, add team rules to balance the assignment of players to teams that makes gameplay more fair and enjoyable for the players. Team rules create constraints on adding players to teams.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Game Center applies the team rules to match requests in the queue after applying other compatible, distance, and match rules. Game Center applies the team rules to candidate teams from combinations of compatible match requests.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Before you begin adding team rules:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a rule set to contain the team rules using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingRuleSets",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " endpoint.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add compatibility and distance rules that filter the match requests using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingRules",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " endpoint.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add match rules, such as skill-level rules, that apply to compatible requests.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For more information on creating the other types of rules, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/letting-players-join-matches-using-party-codes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/finding-players-with-similar-skill-levels",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-teams-to-the-rule-set",
          "level": 3,
          "text": "Add teams to the rule set",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Create two or more teams to compete in your game using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingTeams",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " endpoint.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In the attributes property, pass the minimum and maximum players, and a name of the team. In the relationships property, pass the rule set ",
              "type": "text"
            },
            {
              "code": "id",
              "type": "codeVoice"
            },
            {
              "text": " that the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingRuleSets",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " endpoint returns in the response.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "POST /v1/gameCenterMatchmakingTeams",
            "{",
            "    \"data\": {",
            "        \"type\": \"gameCenterMatchmakingTeams\",",
            "        \"attributes\": {",
            "            \"minPlayers\": 2,",
            "            \"maxPlayers\": 4,",
            "            \"referenceName\": \"blue\"",
            "        },",
            "        \"relationships\": {",
            "            \"ruleSet\": {",
            "                \"data\": {",
            "                    \"type\": \"gameCenterMatchmakingRuleSets\",",
            "                    \"id\": \"6195839b-4ef7-4798-b91d-d59802111607\"",
            "                }",
            "            }",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "json",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Create one or more other teams to compete with the first team using a different name and add them to the same rule set:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "POST /v1/gameCenterMatchmakingTeams",
            "{",
            "    \"data\": {",
            "        \"type\": \"gameCenterMatchmakingTeams\",",
            "        \"attributes\": {",
            "            \"minPlayers\": 2,",
            "            \"maxPlayers\": 4,",
            "            \"referenceName\": \"red\"",
            "        },",
            "        \"relationships\": {",
            "            \"ruleSet\": {",
            "                \"data\": {",
            "                    \"type\": \"gameCenterMatchmakingRuleSets\",",
            "                    \"id\": \"6195839b-4ef7-4798-b91d-d59802111607\"",
            "                }",
            "            }",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "json",
          "type": "codeListing"
        },
        {
          "anchor": "Add-team-rules-to-the-rule-set",
          "level": 3,
          "text": "Add team rules to the rule set",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can add one or more team rules to your rule set depending on how many constraints you want to add to the team assignments. For example, if your matches have a variable number of team members, you can create a team rule that keeps the sizes of the teams balanced. You can also balance the teams by skill level and ensure that invited players are on the same team.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To create a team rule, set the rule’s type field to ",
              "type": "text"
            },
            {
              "code": "TEAM",
              "type": "codeVoice"
            },
            {
              "text": " and the ",
              "type": "text"
            },
            {
              "code": "teams",
              "type": "codeVoice"
            },
            {
              "text": " array becomes available to use in expressions. The ",
              "type": "text"
            },
            {
              "code": "teams",
              "type": "codeVoice"
            },
            {
              "text": " array contains ",
              "type": "text"
            },
            {
              "code": "Team",
              "type": "codeVoice"
            },
            {
              "text": " objects that represent the teams in the rule set. A team has a ",
              "type": "text"
            },
            {
              "code": "players",
              "type": "codeVoice"
            },
            {
              "text": " property that contains ",
              "type": "text"
            },
            {
              "code": "Player",
              "type": "codeVoice"
            },
            {
              "text": " objects that represent the players assigned to the team.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Write an expression that returns ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when the size of the teams are the same using expression functions, the ",
              "type": "text"
            },
            {
              "code": "teams",
              "type": "codeVoice"
            },
            {
              "text": " array, and the ",
              "type": "text"
            },
            {
              "code": "players",
              "type": "codeVoice"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "length(teams[?name == 'red'].players[]) == length(teams[?name == 'blue'].players[])"
          ],
          "syntax": "json",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Pass the rule type, the expression, and the rule set, along with other settings, to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingRules",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " endpoint.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "POST /v1/gameCenterMatchmakingRules",
            "{",
            "    \"data\": {",
            "        \"type\": \"gameCenterMatchmakingRules\",",
            "        \"attributes\": {",
            "            \"type\": \"TEAM\",",
            "            \"description\": \"Teams must have same number of players\",",
            "            \"referenceName\": \"SameSizeTeams\",",
            "            \"expression\": \"length(teams[?name == 'red'].players[]) == length(teams[?name == 'blue'].players[])\"",
            "        },",
            "        \"relationships\": {",
            "            \"ruleSet\": {",
            "                \"data\": {",
            "                    \"type\": \"gameCenterMatchmakingRuleSets\",",
            "                    \"id\": \"6195839b-4ef7-4798-b91d-d59802111607\"",
            "                }",
            "            }",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "json",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In team rule expressions, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/player",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object has a ",
              "type": "text"
            },
            {
              "code": "requestName",
              "type": "codeVoice"
            },
            {
              "text": " field that is an identifier for the associated match request. For more information on the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/team",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/player",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects you use in team rules, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/expressions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in App Store Connect API.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-match-requests-that-assign-players-to-teams",
          "level": 3,
          "text": "Create match requests that assign players to teams",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In your code, create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that initiates a team game. Set the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/queueName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to the reference name of the queue that contains your team rules.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Create a match request.",
            "let request = GKMatchRequest()",
            "",
            "// Set the matchmaking rules queue name.",
            "request.queueName = \"com.example.mygame.TeamBasedQueue\""
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If you add a rule to balance the teams by skill level, add the local player’s skill to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/properties",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Set properties to the game-specific keys you use in the rules.",
            "let skill = localPlayerData.skill",
            "request.properties = [ \"skill\": skill]"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Game Center finds all compatible players and assigns them to teams.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Get-team-assignments-when-players-accept-invitations",
          "level": 3,
          "text": "Get team assignments when players accept invitations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When all the players accept their invitations, GameKit invokes the ",
              "type": "text"
            },
            {
              "code": "GKMatchmakerViewControllerDelegate",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchmakerViewControllerDelegate/matchmakerViewController(_:didFind:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method in the app instances for all players in the game, including the player who sent the invitations.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func matchmakerViewController(_ viewController: GKMatchmakerViewController,",
            "                                  didFind match: GKMatch) {",
            "    // Dismiss the view controller.",
            "    viewController.dismiss(animated: true, completion: nil)",
            "",
            "    // Set the match delegate.",
            "    match.delegate = myGame",
            "          ",
            "    // Start the game with the players in the match.",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Before your implementation of this delegate method starts the game, you can get all the team assignments from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatch",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatch/players",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to get the players that accepted the invitation, including the player that initiated the match. Then use the ",
              "type": "text"
            },
            {
              "code": "GKMatch.``playersProperties",
              "type": "codeVoice"
            },
            {
              "text": " to get the game-specific properties for each player, such as the ",
              "type": "text"
            },
            {
              "code": "skill",
              "type": "codeVoice"
            },
            {
              "text": " property, including the team assignment. If you add team rules to your rule set, use the ",
              "type": "text"
            },
            {
              "code": "gc",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "team",
              "type": "codeVoice"
            },
            {
              "text": " keys to get the name of the player’s team that you previously configured using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingTeams",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " endpoint.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Get the local player's team assignment.",
            "properties = match.properties",
            "team = properties[\"gc\"][\"team\"]"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingRuleSets": {
      "abstract": [
        {
          "text": "Create a rule set to contain matchmaking rules and teams.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingRuleSets",
      "kind": "symbol",
      "role": "symbol",
      "title": "Create a rule set",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingRuleSets"
    },
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingRules": {
      "abstract": [
        {
          "text": "Add a matchmaking rule to a rule set.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingRules",
      "kind": "symbol",
      "role": "symbol",
      "title": "Create a rule",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingRules"
    },
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingTeams": {
      "abstract": [
        {
          "text": "Add a game-specific team to a rule set.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingTeams",
      "kind": "symbol",
      "role": "symbol",
      "title": "Create a team",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingTeams"
    },
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI/expressions": {
      "abstract": [
        {
          "text": "Write expressions that query the match requests in a queue to find the best players for a match.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/expressions",
      "kind": "article",
      "role": "article",
      "title": "Expressions",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI/expressions"
    },
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI/player": {
      "abstract": [
        {
          "text": "An object that represents a player associated with a match request.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/player",
      "kind": "article",
      "role": "article",
      "title": "Player",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI/player"
    },
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI/team": {
      "abstract": [
        {
          "text": "A team that you add to a rule set.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/team",
      "kind": "article",
      "role": "article",
      "title": "Team",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI/team"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatch": {
      "abstract": [
        {
          "text": "A peer-to-peer network between a group of players that sign into Game Center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKMatch"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKMatch"
        }
      ],
      "role": "symbol",
      "title": "GKMatch",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatch"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatch/players": {
      "abstract": [
        {
          "text": "The players that join the match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "players"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatch/players",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "players"
        }
      ],
      "role": "symbol",
      "title": "players",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatch/players"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest": {
      "abstract": [
        {
          "text": "An object that encapsulates the parameters to create a real-time or turn-based match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKMatchRequest"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKMatchRequest"
        }
      ],
      "role": "symbol",
      "title": "GKMatchRequest",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/properties": {
      "abstract": [
        {
          "text": "The criteria for the local player that Game Center uses to find other players when using matchmaking rules.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "properties"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/properties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "properties"
        }
      ],
      "role": "symbol",
      "title": "properties",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/properties"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/queueName": {
      "abstract": [
        {
          "text": "The name of the queue that Game Center places the match request in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "queueName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/queueName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "queueName"
        }
      ],
      "role": "symbol",
      "title": "queueName",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/queuename"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchmakerViewControllerDelegate/matchmakerViewController(_:didFind:)": {
      "abstract": [
        {
          "text": "Handles when the view controller finds players for a peer-to-peer match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchmakerViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKMatchmakerViewController",
          "text": "GKMatchmakerViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKMatch",
          "text": "GKMatch"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchmakerViewControllerDelegate/matchmakerViewController(_:didFind:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchmakerViewController:didFindMatch:"
        }
      ],
      "role": "symbol",
      "title": "matchmakerViewController(_:didFind:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchmakerviewcontrollerdelegate/matchmakerviewcontroller(_:didfind:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/creating-matchmaking-rules-for-backward-compatibility": {
      "abstract": [
        {
          "text": "Add matchmaking rules that support previous classic matchmaking versions of your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/creating-matchmaking-rules-for-backward-compatibility",
      "kind": "article",
      "role": "article",
      "title": "Creating matchmaking rules for backward compatibility",
      "type": "topic",
      "url": "/documentation/gamekit/creating-matchmaking-rules-for-backward-compatibility"
    },
    "doc://com.apple.gamekit/documentation/GameKit/finding-players-with-similar-skill-levels": {
      "abstract": [
        {
          "text": "Add a rule to find players in a range of skill levels to balance competitive gameplay.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/finding-players-with-similar-skill-levels",
      "kind": "article",
      "role": "article",
      "title": "Finding players with similar skill levels",
      "type": "topic",
      "url": "/documentation/gamekit/finding-players-with-similar-skill-levels"
    },
    "doc://com.apple.gamekit/documentation/GameKit/letting-players-join-matches-using-party-codes": {
      "abstract": [
        {
          "text": "Add a rule that lets players invite players and join matches using a shared party code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/letting-players-join-matches-using-party-codes",
      "kind": "article",
      "role": "article",
      "title": "Letting players join matches using party codes",
      "type": "topic",
      "url": "/documentation/gamekit/letting-players-join-matches-using-party-codes"
    },
    "doc://com.apple.gamekit/documentation/GameKit/matchmaking-rules": {
      "abstract": [
        {
          "text": "Game Center applies different type of rules you create in a particular order to find the best matches.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/matchmaking-rules",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Matchmaking rules",
      "type": "topic",
      "url": "/documentation/gamekit/matchmaking-rules"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Rules",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/letting-players-join-matches-using-party-codes",
        "doc://com.apple.gamekit/documentation/GameKit/finding-players-with-similar-skill-levels",
        "doc://com.apple.gamekit/documentation/GameKit/creating-matchmaking-rules-for-backward-compatibility"
      ],
      "title": "Rules"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Rules",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/letting-players-join-matches-using-party-codes",
                "doc://com.apple.gamekit/documentation/GameKit/finding-players-with-similar-skill-levels",
                "doc://com.apple.gamekit/documentation/GameKit/creating-matchmaking-rules-for-backward-compatibility"
              ],
              "title": "Rules"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1queueName/title",
          "value": "queueName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1queueName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "queueName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest/title",
          "value": "GKMatchRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatch~1players/title",
          "value": "players"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatch~1players/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "players"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmakerViewControllerDelegate~1matchmakerViewController(_:didFind:)/title",
          "value": "matchmakerViewController:didFindMatch:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmakerViewControllerDelegate~1matchmakerViewController(_:didFind:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "matchmakerViewController:didFindMatch:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatch/title",
          "value": "GKMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1properties/title",
          "value": "properties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1properties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "properties"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/assigning-players-to-teams-using-rules"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/assigning-players-to-teams-using-rules"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
