{
  "abstract": [
    {
      "text": "Create a leaderboard for your game that ranks player scores based on a schedule.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/creating-recurring-leaderboards"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Creating recurring leaderboards"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "recurring leaderboard",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " to organize regular competitions or encourage players",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to score higher in your game. Unlike a classic leaderboard that never resets, a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "recurring leaderboard represents score rankings during a period of time. Each leaderboard",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in the sequence is called an ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "occurrence",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For design guidance, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/design/human-interface-guidelines/game-center#Leaderboards",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-a-recurring-leaderboard",
          "level": 3,
          "text": "Configure a recurring leaderboard",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Begin configuring a recurring leaderboard by creating a GameKit configuration file.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "In Xcode, choose File > New > File from Template. Select GameKit File, and click",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Next. In the sheet that appears, enter a name for the configuration and click Create.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Click Add (+) at the bottom of the left column, then choose Leaderboard.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "You configure a recurring leaderboard like a classic leaderboard,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "except that you enable Recurring and configure time-related properties.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Under Recurring, set a start date for the first occurrence. Then enter the duration",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "for each occurrence, to establish the period in which players can earn scores. To",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "specify the frequency of the occurrences, enter a restart interval. Occurrences are",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "sequential and don’t overlap, so the restart interval must be equal to or greater",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "than the duration. To create a time delay between occurrences, set the restart",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "interval to a number that is greater than the duration.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, if the restart interval and duration are both 24 hours, the recurring",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "leaderboard runs daily with no gaps between occurrences. To create a 1-hour contest every",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Sunday at noon, set the start date to Sunday at noon, then set the restart interval",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to 7 days and the duration to 60 minutes. To create a 15-minute competition every hour,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "set the restart interval to 60 minutes and the duration to 15 minutes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If you’ve already pushed your configuration changes to App Store Connect,",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "removing a leaderboard or leaderboard set from the local configuration file",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "doesn’t remove the leaderboard or leaderboard set from App Store Connect.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "To learn more about the information you enter in App Store Connect, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/help/app-store-connect/reference/leaderboards#leaderboard-properties",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Test-recurring-leaderboards-by-using-the-Progress-Manager",
          "level": 3,
          "text": "Test recurring leaderboards by using the Progress Manager",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Before you begin testing your GameKit configuration, you need to enable Debug Mode.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "In Xcode, choose Product > Scheme > Edit Scheme. From the Run configuration,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "select Options and toggle Enable Debug Mode.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To begin testing your leaderboard configuration, open the game Progress Manager.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "In Xcode, choose Debug > GameKit > Manage Game Progress. From the top left of the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "window that appears, select the physical device you use for testing, and the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "project you want to debug. The test data stays local to your machine and doesn’t",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "rely on App Store Connect to test.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you test recurring leaderboards in the Progress Manager, you click Reset",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Leaderboards to simulate what happens in your game when the leaderboard occurrence",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "ends. You can’t access previous occurrences of a recurring leaderboard in",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Debug Mode.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Submit-a-score-to-the-current-occurrence",
          "level": 3,
          "text": "Submit a score to the current occurrence",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the leaderboard ID you entered in Xcode to specify the current",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "occurrence when submitting a score. Don’t submit scores to past occurances leaderboards.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To submit a score to one or more leaderboards, including recurring leaderboards,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/submitScore(_:context:player:leaderboardIDs:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "class method in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Pass one or more leaderboard IDs, the score, context,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and player. The ",
              "type": "text"
            },
            {
              "code": "context",
              "type": "codeVoice"
            },
            {
              "text": " parameter is an optional value for game-specific data that",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you can store, and fetch later with the score. If there’s an occurrence at the time",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you submit the score, the occurrence retains either the best score or the most recent",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "score.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Submit a score to one or more leaderboards",
            "try await GKLeaderboard.submitScore(points, ",
            "                                    context: 0, ",
            "                                    player: GKLocalPlayer.local,",
            "                                    leaderboardIDs: [\"my.recurring.leaderboard.id\"]) "
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Alternatively, submit the score to the recurring leaderboard by loading the leaderboard",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadLeaderboards(IDs:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method in",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Then use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/submitScore(_:context:player:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "instance method to submit the score to the recurring leaderboard.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Submit a score to the current occurrence of a recurring leaderboard",
            "let leaderboards = try await GKLeaderboard.loadLeaderboards(IDs: [\"my.recurring.leaderboard.id\"])",
            "guard let leaderboard = leaderboards.first,",
            "          let endDate = leaderboard.startDate?.addingTimeInterval(leaderboard.duration), endDate > Date() else { return }",
            "",
            "try await GKLeaderboard.submitScore(points, ",
            "                                    context: 0, ",
            "                                    player: GKLocalPlayer.local, ",
            "                                    leaderboardIDs: [\"my.recurring.leaderboard.id\"])"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You can only use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/submitScore(_:context:player:completionHandler:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "instance method for recurring leaderboards.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "However, submitting a score with this method fails if the leaderboard isn’t active,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "so check the start date and duration properties of the leaderboard before calling",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/submitScore(_:context:player:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. To",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "get the start date of the next occurrence, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/nextStartDate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Access-the-previous-occurrence",
          "level": 3,
          "text": "Access the previous occurrence",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you want the scores and rankings from the previous occurrence, you can get the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "occurrence using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadPreviousOccurrence(completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "method in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". First, load the current occurrence using the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadLeaderboards(IDs:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class method, then",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadPreviousOccurrence(completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to load the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "previous occurrence.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Load current occurrence of a recurring leaderboard",
            "let leaderboards = try await GKLeaderboard.loadLeaderboards(IDs: [\"my.recurring.leaderboard.id\"])",
            "",
            "if let current = leaderboards.first {",
            "    // Load previous occurrence using the current occurrence.",
            "    try await current.loadPreviousOccurrence()",
            "    ",
            "    // Do something with the previous occurrence.",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Game Center keeps expired occurrences for up to 30 days. However, a player can view",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "scores only on the current occurrence and one previous occurrence. The previous occurrence",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "is the most recent expired occurrence in which the player submitted a score.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard": {
      "abstract": [
        {
          "text": "A leaderboard for a game that Game Center stores.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKLeaderboard"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKLeaderboard"
        }
      ],
      "role": "symbol",
      "title": "GKLeaderboard",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadLeaderboards(IDs:completionHandler:)": {
      "abstract": [
        {
          "text": "Loads leaderboards for the specified leaderboard IDs that Game Center uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadLeaderboards"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "IDs"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboard",
          "text": "GKLeaderboard"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadLeaderboards(IDs:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadLeaderboardsWithIDs:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "loadLeaderboards(IDs:completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/loadleaderboards(ids:completionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadPreviousOccurrence(completionHandler:)": {
      "abstract": [
        {
          "text": "Loads the previous recurring leaderboard occurrence that the player submits a score to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadPreviousOccurrence"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboard",
          "text": "GKLeaderboard"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadPreviousOccurrence(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadPreviousOccurrenceWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "loadPreviousOccurrence(completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/loadpreviousoccurrence(completionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/nextStartDate": {
      "abstract": [
        {
          "text": "The date and time the next recurring leaderboard occurrence starts accepting scores.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextStartDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/nextStartDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nextStartDate"
        }
      ],
      "role": "symbol",
      "title": "nextStartDate",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/nextstartdate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/submitScore(_:context:player:completionHandler:)": {
      "abstract": [
        {
          "text": "Submits a score to the leaderboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "submitScore"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "player"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/submitScore(_:context:player:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "submitScore:context:player:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "submitScore(_:context:player:completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/submitscore(_:context:player:completionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/submitScore(_:context:player:leaderboardIDs:completionHandler:)": {
      "abstract": [
        {
          "text": "Submits a score to multiple leaderboards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "submitScore"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "player"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "leaderboardIDs"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/submitScore(_:context:player:leaderboardIDs:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "submitScore:context:player:leaderboardIDs:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "submitScore(_:context:player:leaderboardIDs:completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/submitscore(_:context:player:leaderboardids:completionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardScore": {
      "abstract": [
        {
          "text": "Information about a player’s score on a leaderboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKLeaderboardScore"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardScore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKLeaderboardScore"
        }
      ],
      "role": "symbol",
      "title": "GKLeaderboardScore",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboardscore"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardSet": {
      "abstract": [
        {
          "text": "Organizes leaderboards into logical and coherent groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKLeaderboardSet"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKLeaderboardSet"
        }
      ],
      "role": "symbol",
      "title": "GKLeaderboardSet",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboardset"
    },
    "doc://com.apple.gamekit/documentation/GameKit/adding-recurring-leaderboards-to-your-game": {
      "abstract": [
        {
          "text": "Encourage competition in your games by adding leaderboards that have a duration and repeat.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/adding-recurring-leaderboards-to-your-game",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adding Recurring Leaderboards to Your Game",
      "type": "topic",
      "url": "/documentation/gamekit/adding-recurring-leaderboards-to-your-game"
    },
    "doc://com.apple.gamekit/documentation/GameKit/encourage-progress-and-competition-with-leaderboards": {
      "abstract": [
        {
          "text": "Let players measure their own progress and compare their skills with friends and others.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/encourage-progress-and-competition-with-leaderboards",
      "kind": "article",
      "role": "article",
      "title": "Encourage progress and competition with leaderboards",
      "type": "topic",
      "url": "/documentation/gamekit/encourage-progress-and-competition-with-leaderboards"
    },
    "https://developer.apple.com/design/human-interface-guidelines/game-center#Leaderboards": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/game-center#Leaderboards",
      "title": "Human Interface Guidelines > Technologies > Game Center > Leaderboards",
      "titleInlineContent": [
        {
          "text": "Human Interface Guidelines > Technologies > Game Center > Leaderboards",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/game-center#Leaderboards"
    },
    "https://developer.apple.com/help/app-store-connect/reference/leaderboards#leaderboard-properties": {
      "identifier": "https://developer.apple.com/help/app-store-connect/reference/leaderboards#leaderboard-properties",
      "title": "Leaderboard properties",
      "titleInlineContent": [
        {
          "text": "Leaderboard properties",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/help/app-store-connect/reference/leaderboards#leaderboard-properties"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Leaderboards",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/encourage-progress-and-competition-with-leaderboards",
        "doc://com.apple.gamekit/documentation/GameKit/adding-recurring-leaderboards-to-your-game",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardSet",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardScore"
      ],
      "title": "Leaderboards"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Leaderboards",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/encourage-progress-and-competition-with-leaderboards",
                "doc://com.apple.gamekit/documentation/GameKit/adding-recurring-leaderboards-to-your-game",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardSet",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardScore"
              ],
              "title": "Leaderboards"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1nextStartDate/title",
          "value": "nextStartDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1nextStartDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nextStartDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1loadLeaderboards(IDs:completionHandler:)/title",
          "value": "loadLeaderboardsWithIDs:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1loadLeaderboards(IDs:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "loadLeaderboardsWithIDs:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboardSet/title",
          "value": "GKLeaderboardSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboardSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboardSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboardSet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboardSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1loadPreviousOccurrence(completionHandler:)/title",
          "value": "loadPreviousOccurrenceWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1loadPreviousOccurrence(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadPreviousOccurrenceWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1submitScore(_:context:player:leaderboardIDs:completionHandler:)/title",
          "value": "submitScore:context:player:leaderboardIDs:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1submitScore(_:context:player:leaderboardIDs:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "submitScore:context:player:leaderboardIDs:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1submitScore(_:context:player:completionHandler:)/title",
          "value": "submitScore:context:player:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1submitScore(_:context:player:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "submitScore:context:player:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard/title",
          "value": "GKLeaderboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboardScore/title",
          "value": "GKLeaderboardScore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboardScore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboardScore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboardScore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboardScore"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/creating-recurring-leaderboards"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/creating-recurring-leaderboards"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
