{
  "abstract": [
    {
      "text": "Review unsupported symbols and their replacements.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated symbols"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAchievementViewController": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "GKAchievementViewController",
          "type": "codeVoice"
        },
        {
          "text": " object provides a standard user interface to display achievement progress for the local player. If the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class is available, you should use it instead.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKAchievementViewController"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAchievementViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKAchievementViewController"
        }
      ],
      "role": "symbol",
      "title": "GKAchievementViewController",
      "type": "topic",
      "url": "/documentation/gamekit/gkachievementviewcontroller"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAchievementViewControllerDelegate": {
      "abstract": [
        {
          "text": "An object implementing the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAchievementViewControllerDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol is called when the user dismisses the achievements view controller. Typically, this protocol is implemented by the object in your game that originally displayed the achievements user interface.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKAchievementViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAchievementViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKAchievementViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "GKAchievementViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/gamekit/gkachievementviewcontrollerdelegate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKChallengeEventHandler": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "GKChallengeEventHandler",
          "type": "codeVoice"
        },
        {
          "text": " class is used to respond to events related to challenges sent or received by the local player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKChallengeEventHandler"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKChallengeEventHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKChallengeEventHandler"
        }
      ],
      "role": "symbol",
      "title": "GKChallengeEventHandler",
      "type": "topic",
      "url": "/documentation/gamekit/gkchallengeeventhandler"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKChallengeEventHandlerDelegate": {
      "abstract": [
        {
          "text": "You implement the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKChallengeEventHandlerDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " delegate to control how challenges are displayed in your game.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKChallengeEventHandlerDelegate"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKChallengeEventHandlerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKChallengeEventHandlerDelegate"
        }
      ],
      "role": "symbol",
      "title": "GKChallengeEventHandlerDelegate",
      "type": "topic",
      "url": "/documentation/gamekit/gkchallengeeventhandlerdelegate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKChallengesViewController": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKChallengesViewController"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKChallengesViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKChallengesViewController"
        }
      ],
      "role": "symbol",
      "title": "GKChallengesViewController",
      "type": "topic",
      "url": "/documentation/gamekit/gkchallengesviewcontroller"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKChallengesViewControllerDelegate": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKChallengesViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKChallengesViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKChallengesViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "GKChallengesViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/gamekit/gkchallengesviewcontrollerdelegate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKCloudPlayer": {
      "abstract": [
        {
          "text": "The object representing the currently signed-in iCloud user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKCloudPlayer"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKCloudPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKCloudPlayer"
        }
      ],
      "role": "symbol",
      "title": "GKCloudPlayer",
      "type": "topic",
      "url": "/documentation/gamekit/gkcloudplayer"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKFriendRequestComposeViewController": {
      "abstract": [
        {
          "text": "Your game uses the ",
          "type": "text"
        },
        {
          "code": "GKFriendRequestComposeViewController",
          "type": "codeVoice"
        },
        {
          "text": " class to present a screen that allows the local player to send friend requests to other players.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKFriendRequestComposeViewController"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKFriendRequestComposeViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKFriendRequestComposeViewController"
        }
      ],
      "role": "symbol",
      "title": "GKFriendRequestComposeViewController",
      "type": "topic",
      "url": "/documentation/gamekit/gkfriendrequestcomposeviewcontroller"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKFriendRequestComposeViewControllerDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKFriendRequestComposeViewControllerDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol is implemented by delegates of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKFriendRequestComposeViewController",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class. The delegate is called when the player dismisses the friend request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKFriendRequestComposeViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKFriendRequestComposeViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKFriendRequestComposeViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "GKFriendRequestComposeViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/gamekit/gkfriendrequestcomposeviewcontrollerdelegate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController": {
      "abstract": [
        {
          "text": "The dashboard that allows players to access their Game Center data in your game.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGameCenterViewController"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterViewController"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterViewController",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontroller"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSession": {
      "abstract": [
        {
          "text": "A game session you can use to save game data, invite other players, and create turn-based and real-time game apps.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGameSession"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameSession"
        }
      ],
      "role": "symbol",
      "title": "GKGameSession",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesession"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError": {
      "abstract": [
        {
          "text": "Error codes for the game session domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGameSessionError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameSessionError"
        }
      ],
      "role": "symbol",
      "title": "GKGameSessionError",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/Code": {
      "abstract": [
        {
          "text": "Error codes for the game session domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "GKGameSessionError.Code",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/code"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for game sessions.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGameSessionErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameSessionErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "GKGameSessionErrorDomain",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerrordomain"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionEventListener": {
      "abstract": [
        {
          "text": "An event listener that handles game session events.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGameSessionEventListener"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionEventListener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameSessionEventListener"
        }
      ],
      "role": "symbol",
      "title": "GKGameSessionEventListener",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessioneventlistener"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionSharingViewController": {
      "abstract": [
        {
          "text": "A user interface you can use to invite other users into a tvOS game session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGameSessionSharingViewController"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionSharingViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameSessionSharingViewController"
        }
      ],
      "role": "symbol",
      "title": "GKGameSessionSharingViewController",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionsharingviewcontroller"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardViewController": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "GKLeaderboardViewController",
          "type": "codeVoice"
        },
        {
          "text": " class provides a standard user interface that displays leaderboard scores to the player. If the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class is available, you should use it instead.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKLeaderboardViewController"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKLeaderboardViewController"
        }
      ],
      "role": "symbol",
      "title": "GKLeaderboardViewController",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboardviewcontroller"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardViewControllerDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardViewControllerDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol is implemented by delegates of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardViewController",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class. The delegate is called when the player dismisses the leaderboard.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKLeaderboardViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKLeaderboardViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "GKLeaderboardViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboardviewcontrollerdelegate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKPeerConnectionState": {
      "abstract": [
        {
          "text": "The state of a peer known to the session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKPeerConnectionState"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKPeerConnectionState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKPeerConnectionState"
        }
      ],
      "role": "symbol",
      "title": "GKPeerConnectionState",
      "type": "topic",
      "url": "/documentation/gamekit/gkpeerconnectionstate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerConnectionType": {
      "abstract": [
        {
          "text": "Network connections available to the peer picker dialog.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKPeerPickerConnectionType"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerConnectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKPeerPickerConnectionType"
        }
      ],
      "role": "symbol",
      "title": "GKPeerPickerConnectionType",
      "type": "topic",
      "url": "/documentation/gamekit/gkpeerpickerconnectiontype"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerController": {
      "abstract": [
        {
          "text": "Provides a standard user interface to allow one iOS device to discover and connect to another.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKPeerPickerController"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKPeerPickerController"
        }
      ],
      "role": "symbol",
      "title": "GKPeerPickerController",
      "type": "topic",
      "url": "/documentation/gamekit/gkpeerpickercontroller"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerControllerDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerControllerDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol is implemented on an object to customize the behavior of a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerController",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object. The delegate is called by the peer picker to create a session object and to respond as the session is configured by the controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKPeerPickerControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKPeerPickerControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "GKPeerPickerControllerDelegate",
      "type": "topic",
      "url": "/documentation/gamekit/gkpeerpickercontrollerdelegate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKScore": {
      "abstract": [
        {
          "text": "An object containing information for a score that was earned by the player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKScore"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKScore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKScore"
        }
      ],
      "role": "symbol",
      "title": "GKScore",
      "type": "topic",
      "url": "/documentation/gamekit/gkscore"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSendDataMode": {
      "abstract": [
        {
          "text": "The mechanism used to transmit data to other peers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKSendDataMode"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSendDataMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSendDataMode"
        }
      ],
      "role": "symbol",
      "title": "GKSendDataMode",
      "type": "topic",
      "url": "/documentation/gamekit/gksenddatamode"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSession": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSession",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object provides the ability to discover and connect to nearby iOS devices using Bluetooth or Wi-fi.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKSession"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSession"
        }
      ],
      "role": "symbol",
      "title": "GKSession",
      "type": "topic",
      "url": "/documentation/gamekit/gksession"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate": {
      "abstract": [
        {
          "text": "An object implements the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol to control the behavior of a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSession",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object. The delegate is called when other visible peers change their state relative to the session. It is also called to determine whether another peer is allowed to connect to the session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKSessionDelegate"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionDelegate"
        }
      ],
      "role": "symbol",
      "title": "GKSessionDelegate",
      "type": "topic",
      "url": "/documentation/gamekit/gksessiondelegate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKSessionError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for the session error domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError.Code",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct/code"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionErrorDomain": {
      "abstract": [
        {
          "text": "An error occurred in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSession",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKSessionErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "GKSessionErrorDomain",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerrordomain"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionMode": {
      "abstract": [
        {
          "text": "Modes that determine how a session interacts with other peers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKSessionMode"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionMode"
        }
      ],
      "role": "symbol",
      "title": "GKSessionMode",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionmode"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandler": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandler",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class is used to respond to important messages related to turn-based matches. To use it, call the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandler/shared()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class method to get the singleton instance and assign an object that implements the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandlerDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol to its ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandler/delegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property. All methods are called on the main thread.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKTurnBasedEventHandler"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedEventHandler"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedEventHandler",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedeventhandler"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandler/delegate": {
      "abstract": [
        {
          "text": "The delegate for the event handler.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GKTurnBasedEventHandlerDelegate",
          "text": "GKTurnBasedEventHandlerDelegate"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandler/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedeventhandler/delegate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandler/shared()": {
      "abstract": [
        {
          "text": "Returns the shared instance of the event handler.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shared"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKTurnBasedEventHandler",
          "text": "GKTurnBasedEventHandler"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandler/shared()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedTurnBasedEventHandler"
        }
      ],
      "role": "symbol",
      "title": "shared()",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedeventhandler/shared()"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandlerDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandlerDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol is implemented by an object to receive notifications events for turn-based matches. All methods are called on the main thread.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKTurnBasedEventHandlerDelegate"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandlerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedEventHandlerDelegate"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedEventHandlerDelegate",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedeventhandlerdelegate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChat": {
      "abstract": [
        {
          "text": "A voice channel that allows players to speak with each other in a multiplayer game.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKVoiceChat"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChat"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChat",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechat"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatClient": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatClient",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol is implemented to control the behavior of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatService",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object. The voice chat client has a number of responsibilities:",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKVoiceChatClient"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatClient"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatClient",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatclient"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatService": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatService",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class allows your application to connect two iOS devices into a voice chat.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKVoiceChatService"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatService"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatService",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatservice"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for the voice chat service error domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError.Code",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct/code"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceErrorDomain": {
      "abstract": [
        {
          "text": "An error occurred in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatService",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceErrorDomain",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerrordomain"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Deprecated-classes",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKAchievementViewController",
        "doc://com.apple.gamekit/documentation/GameKit/GKChallengeEventHandler",
        "doc://com.apple.gamekit/documentation/GameKit/GKChallengesViewController",
        "doc://com.apple.gamekit/documentation/GameKit/GKCloudPlayer",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSession",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionSharingViewController",
        "doc://com.apple.gamekit/documentation/GameKit/GKFriendRequestComposeViewController",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardViewController",
        "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerController",
        "doc://com.apple.gamekit/documentation/GameKit/GKScore",
        "doc://com.apple.gamekit/documentation/GameKit/GKSession",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandler",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChat",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatService"
      ],
      "title": "Deprecated classes"
    },
    {
      "anchor": "Deprecated-protocols",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKAchievementViewControllerDelegate",
        "doc://com.apple.gamekit/documentation/GameKit/GKChallengeEventHandlerDelegate",
        "doc://com.apple.gamekit/documentation/GameKit/GKChallengesViewControllerDelegate",
        "doc://com.apple.gamekit/documentation/GameKit/GKFriendRequestComposeViewControllerDelegate",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionEventListener",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardViewControllerDelegate",
        "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerControllerDelegate",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandlerDelegate",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatClient"
      ],
      "title": "Deprecated protocols"
    },
    {
      "anchor": "Deprecated-structures",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError"
      ],
      "title": "Deprecated structures"
    },
    {
      "anchor": "Deprecated-constants",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionErrorDomain",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionErrorDomain",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceErrorDomain"
      ],
      "title": "Deprecated constants"
    },
    {
      "anchor": "Deprecated-enumerations",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/Code",
        "doc://com.apple.gamekit/documentation/GameKit/GKPeerConnectionState",
        "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerConnectionType",
        "doc://com.apple.gamekit/documentation/GameKit/GKSendDataMode",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionMode",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct"
      ],
      "title": "Deprecated enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Deprecated-classes",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKAchievementViewController",
                "doc://com.apple.gamekit/documentation/GameKit/GKChallengeEventHandler",
                "doc://com.apple.gamekit/documentation/GameKit/GKChallengesViewController",
                "doc://com.apple.gamekit/documentation/GameKit/GKCloudPlayer",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameSession",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionSharingViewController",
                "doc://com.apple.gamekit/documentation/GameKit/GKFriendRequestComposeViewController",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardViewController",
                "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerController",
                "doc://com.apple.gamekit/documentation/GameKit/GKScore",
                "doc://com.apple.gamekit/documentation/GameKit/GKSession",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandler",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChat",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatService"
              ],
              "title": "Deprecated classes"
            },
            {
              "anchor": "Deprecated-protocols",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKAchievementViewControllerDelegate",
                "doc://com.apple.gamekit/documentation/GameKit/GKChallengeEventHandlerDelegate",
                "doc://com.apple.gamekit/documentation/GameKit/GKChallengesViewControllerDelegate",
                "doc://com.apple.gamekit/documentation/GameKit/GKFriendRequestComposeViewControllerDelegate",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionEventListener",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardViewControllerDelegate",
                "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerControllerDelegate",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandlerDelegate",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatClient"
              ],
              "title": "Deprecated protocols"
            },
            {
              "anchor": "Deprecated-constants",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionErrorDomain",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionErrorDomain",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceErrorDomain"
              ],
              "title": "Deprecated constants"
            },
            {
              "anchor": "Deprecated-enumerations",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/Code",
                "doc://com.apple.gamekit/documentation/GameKit/GKPeerConnectionState",
                "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerConnectionType",
                "doc://com.apple.gamekit/documentation/GameKit/GKSendDataMode",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct/Code",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionMode",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct/Code"
              ],
              "title": "Deprecated enumerations"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKChallengeEventHandler/title",
          "value": "GKChallengeEventHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKChallengeEventHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKChallengeEventHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKChallengeEventHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKChallengeEventHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerConnectionState/title",
          "value": "GKPeerConnectionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerConnectionState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPeerConnectionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerConnectionState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPeerConnectionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKChallengesViewController/title",
          "value": "GKChallengesViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKChallengesViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKChallengesViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKChallengesViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKChallengesViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerPickerControllerDelegate/title",
          "value": "GKPeerPickerControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerPickerControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPeerPickerControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerPickerControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPeerPickerControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKScore/title",
          "value": "GKScore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKScore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKScore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKScore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKScore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAchievementViewController/title",
          "value": "GKAchievementViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAchievementViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAchievementViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAchievementViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAchievementViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionError~1Code/title",
          "value": "GKGameSessionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameSessionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameSessionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionMode/title",
          "value": "GKSessionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionErrorDomain/title",
          "value": "GKGameSessionErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameSessionErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatClient/title",
          "value": "GKVoiceChatClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatClient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendRequestComposeViewController/title",
          "value": "GKFriendRequestComposeViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendRequestComposeViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKFriendRequestComposeViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendRequestComposeViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKFriendRequestComposeViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboardViewController/title",
          "value": "GKLeaderboardViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboardViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboardViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboardViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboardViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChat/title",
          "value": "GKVoiceChat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSession/title",
          "value": "GKGameSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionSharingViewController/title",
          "value": "GKGameSessionSharingViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionSharingViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameSessionSharingViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionSharingViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameSessionSharingViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKCloudPlayer/title",
          "value": "GKCloudPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKCloudPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKCloudPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKCloudPlayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKCloudPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code/title",
          "value": "GKVoiceChatServiceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventHandler/title",
          "value": "GKTurnBasedEventHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedEventHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedEventHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code/title",
          "value": "GKSessionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatService/title",
          "value": "GKVoiceChatService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSession/title",
          "value": "GKSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewController/title",
          "value": "GKGameCenterViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSendDataMode/title",
          "value": "GKSendDataMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSendDataMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSendDataMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSendDataMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSendDataMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventHandler~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventHandler~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventHandlerDelegate/title",
          "value": "GKTurnBasedEventHandlerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventHandlerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedEventHandlerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventHandlerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedEventHandlerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerPickerController/title",
          "value": "GKPeerPickerController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerPickerController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPeerPickerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerPickerController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPeerPickerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventHandler~1shared()/title",
          "value": "sharedTurnBasedEventHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventHandler~1shared()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "sharedTurnBasedEventHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionErrorDomain/title",
          "value": "GKSessionErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceErrorDomain/title",
          "value": "GKVoiceChatServiceErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatServiceErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatServiceErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKChallengeEventHandlerDelegate/title",
          "value": "GKChallengeEventHandlerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKChallengeEventHandlerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKChallengeEventHandlerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKChallengeEventHandlerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKChallengeEventHandlerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionEventListener/title",
          "value": "GKGameSessionEventListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionEventListener/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameSessionEventListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionEventListener/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameSessionEventListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionDelegate/title",
          "value": "GKSessionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAchievementViewControllerDelegate/title",
          "value": "GKAchievementViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAchievementViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAchievementViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAchievementViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAchievementViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKChallengesViewControllerDelegate/title",
          "value": "GKChallengesViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKChallengesViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKChallengesViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKChallengesViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKChallengesViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboardViewControllerDelegate/title",
          "value": "GKLeaderboardViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboardViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboardViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboardViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboardViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerPickerConnectionType/title",
          "value": "GKPeerPickerConnectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerPickerConnectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPeerPickerConnectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerPickerConnectionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPeerPickerConnectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendRequestComposeViewControllerDelegate/title",
          "value": "GKFriendRequestComposeViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendRequestComposeViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKFriendRequestComposeViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendRequestComposeViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKFriendRequestComposeViewControllerDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
