{
  "abstract": [
    {
      "text": "Enable Game Center in your Xcode project and configure features in App Store Connect.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/enabling-and-configuring-game-center"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Enabling and configuring Game Center"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Before you can use the GameKit framework and access Game Center data, you need to enable Game Center. When you enable Game Center in your project, Xcode adds the Game Center entitlement to your App ID and adds the GameKit framework to your project. Then you can configure features that you use in your game, such as leaderboards and achievements, in App Store Connect.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about the Game Center service, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/help/app-store-connect/configure-game-center/overview-of-game-center",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Enable-Game-Center",
          "level": 3,
          "text": "Enable Game Center",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In Xcode, select the project in the main window, and in the project editor that appears on the right, select the target. Then click the Signing & Capabilities tab in the project editor and click the Library button (+) in the toolbar to open the Capabilities library. To enable Game Center, double-click the Game Center capability in the library or drag the capability from the library to the Signing & Capabilities pane.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3678702",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For Mac targets, ensure that you enable both Incoming Connections and Outgoing Connections in the App Sandbox capability under Network.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-Game-Center-features",
          "level": 3,
          "text": "Configure Game Center features",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you don’t have an app record in App Store Connect, first create one so you can configure Game Center features while you develop your game. To create an app record in App Store Connect that matches your App ID in your developer account, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/help/app-store-connect/create-an-app-record/add-a-new-app/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in App Store Connect Help. To enable Game Center for versions of your app, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/help/app-store-connect/configure-game-center/enable-an-app-version-for-game-center/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Then follow the steps in App Store Connect Help to configure leaderboards, achievements, and multiplayer games.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.game-center": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether users of the app may see and compare achievements on a leaderboard, invite friends, and start multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.game-center",
      "kind": "symbol",
      "role": "symbol",
      "title": "Game Center Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.game-center"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/authenticating-a-player": {
      "abstract": [
        {
          "text": "Confirm player credentials and device capabilities and check for account restrictions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/authenticating-a-player",
      "kind": "article",
      "role": "article",
      "title": "Authenticating a player",
      "type": "topic",
      "url": "/documentation/gamekit/authenticating-a-player"
    },
    "doc://com.apple.gamekit/documentation/GameKit/improving-the-player-experience-for-games-with-large-downloads": {
      "abstract": [
        {
          "text": "Provide ample content in your base installation and then use on-demand resources and the Background Assets API to handle additional content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/improving-the-player-experience-for-games-with-large-downloads",
      "kind": "article",
      "role": "article",
      "title": "Improving the player experience for games with large downloads",
      "type": "topic",
      "url": "/documentation/gamekit/improving-the-player-experience-for-games-with-large-downloads"
    },
    "https://developer.apple.com/help/app-store-connect/configure-game-center/enable-an-app-version-for-game-center/": {
      "identifier": "https://developer.apple.com/help/app-store-connect/configure-game-center/enable-an-app-version-for-game-center/",
      "title": "Enable your app version for Game Center",
      "titleInlineContent": [
        {
          "text": "Enable your app version for Game Center",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/help/app-store-connect/configure-game-center/enable-an-app-version-for-game-center/"
    },
    "https://developer.apple.com/help/app-store-connect/configure-game-center/overview-of-game-center": {
      "identifier": "https://developer.apple.com/help/app-store-connect/configure-game-center/overview-of-game-center",
      "title": "Overview of Game Center",
      "titleInlineContent": [
        {
          "text": "Overview of Game Center",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/help/app-store-connect/configure-game-center/overview-of-game-center"
    },
    "https://developer.apple.com/help/app-store-connect/create-an-app-record/add-a-new-app/": {
      "identifier": "https://developer.apple.com/help/app-store-connect/create-an-app-record/add-a-new-app/",
      "title": "Add a new app",
      "titleInlineContent": [
        {
          "text": "Add a new app",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/help/app-store-connect/create-an-app-record/add-a-new-app/"
    },
    "media-3678702": {
      "alt": "Screenshot showing the Xcode project called MyGame with the Game Center capability selected in the Library.",
      "identifier": "media-3678702",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5819ba38a000770a7a82de4f13473f04/media-3678702@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/authenticating-a-player",
        "doc://com.apple.gamekit/documentation/GameKit/improving-the-player-experience-for-games-with-large-downloads",
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.game-center"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/authenticating-a-player",
                "doc://com.apple.gamekit/documentation/GameKit/improving-the-player-experience-for-games-with-large-downloads",
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.game-center"
              ],
              "title": "Essentials"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/enabling-and-configuring-game-center"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/enabling-and-configuring-game-center"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
