{
  "abstract": [
    {
      "text": "Add the ability for players to exchange game data and send messages while waiting for their turns.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/exchanging-data-between-players-in-turn-based-games"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Exchanging data between players in turn-based games"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can increase engagement in turn-based games by letting participants communicate and exchange data while they wait for the current participant to take their turn.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To implement this feature, provide an interface in your game where participants can communicate — for example, exchange items in the game. Then initiate an exchange request from the user of your game instance, called the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "local player",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", to one or more recipients. GameKit handles the requests between participants and the status of the exchange object as participants reply. You implement protocol methods to accept exchanges, display results, and save completed exchanges. When you save completed exchanges, GameKit notifies all other participants.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To receive the protocol messages, register as a listener of the local player, and conform to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventListener",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/starting-turn-based-matches-and-passing-turns-between-players",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "GKLocalPlayer.local.register(self)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The code examples in this article use GameKit asynchronous methods that you invoke from an ",
                  "type": "text"
                },
                {
                  "code": "async",
                  "type": "codeVoice"
                },
                {
                  "text": " method or within a ",
                  "type": "text"
                },
                {
                  "code": "Task",
                  "type": "codeVoice"
                },
                {
                  "text": " structure. For details about asynchronous flows, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://docs.swift.org/swift-book/LanguageGuide/Concurrency.html",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Send-exchange-requests",
          "level": 3,
          "text": "Send exchange requests",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Any participant, including the current participant who is taking their turn, can send an exchange request to one or more other participants. When sending an exchange request, you pass the recipients, the game-specific exchange data, and a localized message to the ",
              "type": "text"
            },
            {
              "code": "GKTurnBasedMatch",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/sendExchange(to:data:localizableMessageKey:arguments:timeout:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "try await match.sendExchange(to: participants, data: data!, localizableMessageKey: ",
            "   \"This is my exchange request.\", arguments: [], timeout: GKTurnTimeoutDefault)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In the exchange data, provide enough game-specific information for recipients to decide whether to accept or decline the request.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To localize the message, add the key you pass and a placeholder translation to a ",
              "type": "text"
            },
            {
              "code": ".strings",
              "type": "codeVoice"
            },
            {
              "text": " file in your project (for example, the default ",
              "type": "text"
            },
            {
              "code": "Localizable.strings",
              "type": "codeVoice"
            },
            {
              "text": " file). For more information about adapting your game for different languages and regions, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode/localization",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Respond-to-exchange-requests",
          "level": 3,
          "text": "Respond to exchange requests",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When a recipient receives an exchange request, GameKit invokes the ",
              "type": "text"
            },
            {
              "code": "GKTurnBasedEventListener",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventListener/player(_:receivedExchangeRequest:for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol method, passing the exchange object. If your game isn’t running or is in the background, GameKit displays a notification containing the localized message first. When the recipient taps the notification, GameKit launches your game or brings your game back to the foreground, and then invokes the method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To accept or decline the exchange request on behalf of the participant, implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventListener/player(_:receivedExchangeRequest:for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method using the following steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Unarchive the exchange data in the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchange",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object that GameKit passes to this method.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If the status property is ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchangeStatus/active",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", present an interface containing the exchange data that lets the recipient accept or decline the request.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To display more details to the recipient, use the other ",
                      "type": "text"
                    },
                    {
                      "code": "GKTurnBasedExchange",
                      "type": "codeVoice"
                    },
                    {
                      "text": " properties, such as the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchange/sender",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchange/message",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " properties.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If the recipient accepts the exchange request, invoke the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchange/reply(withLocalizableMessageKey:arguments:data:completionHandler:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method. Optionally, pass additional exchange information back to the sender using the ",
                      "type": "text"
                    },
                    {
                      "code": "data",
                      "type": "codeVoice"
                    },
                    {
                      "text": " parameter.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Save-completed-exchanges",
          "level": 3,
          "text": "Save completed exchanges",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When all recipients reply to an exchange request or requests time out, GameKit invokes the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventListener/player(_:receivedExchangeReplies:forCompletedExchange:for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method in the current participant’s game instance and the original sender’s game instance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "GameKit passes the exchange object with the status property of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchangeStatus/complete",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and the recipient details (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchangeReply",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects) in the ",
              "type": "text"
            },
            {
              "code": "replies",
              "type": "codeVoice"
            },
            {
              "text": " parameter. Optionally, present the replies along with their messages and exchange data to the original sender.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the local player is the current participant, implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventListener/player(_:receivedExchangeReplies:forCompletedExchange:for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to resolve and save the exchange data. Also, save completed exchanges before the current participant ends their turn, forfeits the match, or ends the match.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add your game-specific exchange data to the match data that you save in Game Center and send to participants. For example, add code that transfers items between participants or saves their conversations.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Invoke the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/saveMergedMatch(_:withResolvedExchanges:completionHandler:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method, passing the current match data, including any exchange data, and the completed exchange objects. This method removes the exchanges from the match’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/completedExchanges",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/exchanges",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " properties.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Only the current participant can invoke the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/saveMergedMatch(_:withResolvedExchanges:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, even if the current participant isn’t involved in the exchanges.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Display-exchange-results",
          "level": 3,
          "text": "Display exchange results",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the current participant saves completed exchanges with match data, GameKit invokes the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventListener/player(_:receivedTurnEventFor:didBecomeActive:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method in each participant game instance. Implement this method to present the new match data, including the exchange data. For example, show the items that transfer between participants and recipient reply messages.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Cancel-exchange-requests",
          "level": 3,
          "text": "Cancel exchange requests",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can cancel an exchange request anytime before the current participant saves it and the status property becomes ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchangeStatus/resolved",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". To cancel an exchange request, use the ",
              "type": "text"
            },
            {
              "code": "GKTurnBasedExchange",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchange/cancel(withLocalizableMessageKey:arguments:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. Pass a localizable message that GameKit displays in a notification if the recipient isn’t running your game or it’s in the background.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "try await exchange.cancel(withLocalizableMessageKey: \"I'm canceling the exchange request.\", arguments: [])"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To update the gameplay interface and display the message when a participant cancels an exchange request, implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventListener/player(_:receivedExchangeCancellation:for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/GKGameCenterBadgingDisabled": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether GameKit can add badges to a turn-based game icon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/GKGameCenterBadgingDisabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "GKGameCenterBadgingDisabled",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/GKGameCenterBadgingDisabled"
    },
    "doc://com.apple.documentation/documentation/Xcode/localization": {
      "abstract": [
        {
          "text": "Expand the market for your app by supporting multiple languages and regions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/localization",
      "kind": "article",
      "role": "article",
      "title": "Localization",
      "type": "topic",
      "url": "/documentation/Xcode/localization"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventListener": {
      "abstract": [
        {
          "text": "The protocol that handles turn-based and data-exchange events between participants in a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKTurnBasedEventListener"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventListener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedEventListener"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedEventListener",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedeventlistener"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventListener/player(_:receivedExchangeCancellation:for:)": {
      "abstract": [
        {
          "text": "Handles when the sender cancels an exchange request they intiated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "player"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "receivedExchangeCancellation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKTurnBasedExchange",
          "text": "GKTurnBasedExchange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKTurnBasedMatch",
          "text": "GKTurnBasedMatch"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventListener/player(_:receivedExchangeCancellation:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "player:receivedExchangeCancellation:forMatch:"
        }
      ],
      "role": "symbol",
      "title": "player(_:receivedExchangeCancellation:for:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedeventlistener/player(_:receivedexchangecancellation:for:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventListener/player(_:receivedExchangeReplies:forCompletedExchange:for:)": {
      "abstract": [
        {
          "text": "Handles when all recipients of an exchange request respond.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "player"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "receivedExchangeReplies"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKTurnBasedExchangeReply",
          "text": "GKTurnBasedExchangeReply"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "forCompletedExchange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKTurnBasedExchange",
          "text": "GKTurnBasedExchange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKTurnBasedMatch",
          "text": "GKTurnBasedMatch"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventListener/player(_:receivedExchangeReplies:forCompletedExchange:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "player:receivedExchangeReplies:forCompletedExchange:forMatch:"
        }
      ],
      "role": "symbol",
      "title": "player(_:receivedExchangeReplies:forCompletedExchange:for:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedeventlistener/player(_:receivedexchangereplies:forcompletedexchange:for:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventListener/player(_:receivedExchangeRequest:for:)": {
      "abstract": [
        {
          "text": "Handles when the local player receives an exchange request from another participant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "player"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "receivedExchangeRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKTurnBasedExchange",
          "text": "GKTurnBasedExchange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKTurnBasedMatch",
          "text": "GKTurnBasedMatch"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventListener/player(_:receivedExchangeRequest:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "player:receivedExchangeRequest:forMatch:"
        }
      ],
      "role": "symbol",
      "title": "player(_:receivedExchangeRequest:for:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedeventlistener/player(_:receivedexchangerequest:for:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventListener/player(_:receivedTurnEventFor:didBecomeActive:)": {
      "abstract": [
        {
          "text": "Handles turn-based match events, such as accepting invitations, passing turns, and saving match data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "player"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "receivedTurnEventFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKTurnBasedMatch",
          "text": "GKTurnBasedMatch"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didBecomeActive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventListener/player(_:receivedTurnEventFor:didBecomeActive:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "player:receivedTurnEventForMatch:didBecomeActive:"
        }
      ],
      "role": "symbol",
      "title": "player(_:receivedTurnEventFor:didBecomeActive:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedeventlistener/player(_:receivedturneventfor:didbecomeactive:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchange": {
      "abstract": [
        {
          "text": "Exchange request information that participants send in a turn-based match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKTurnBasedExchange"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedExchange"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedExchange",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedexchange"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchange/cancel(withLocalizableMessageKey:arguments:completionHandler:)": {
      "abstract": [
        {
          "text": "Cancels an exchange request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withLocalizableMessageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "arguments"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchange/cancel(withLocalizableMessageKey:arguments:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelWithLocalizableMessageKey:arguments:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "cancel(withLocalizableMessageKey:arguments:completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedexchange/cancel(withlocalizablemessagekey:arguments:completionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchange/message": {
      "abstract": [
        {
          "text": "A localized message from the sender to the recipients of an exchange request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "message"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchange/message",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "message"
        }
      ],
      "role": "symbol",
      "title": "message",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedexchange/message"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchange/reply(withLocalizableMessageKey:arguments:data:completionHandler:)": {
      "abstract": [
        {
          "text": "Replies to an exchange request on behalf of a recipient.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withLocalizableMessageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "arguments"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchange/reply(withLocalizableMessageKey:arguments:data:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replyWithLocalizableMessageKey:arguments:data:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "reply(withLocalizableMessageKey:arguments:data:completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedexchange/reply(withlocalizablemessagekey:arguments:data:completionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchange/sender": {
      "abstract": [
        {
          "text": "The participant who sends the exchange request to recipients.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKTurnBasedParticipant",
          "text": "GKTurnBasedParticipant"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchange/sender",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sender"
        }
      ],
      "role": "symbol",
      "title": "sender",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedexchange/sender"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchangeReply": {
      "abstract": [
        {
          "text": "Details about a recipient’s response to an exchange request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKTurnBasedExchangeReply"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchangeReply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedExchangeReply"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedExchangeReply",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedexchangereply"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchangeStatus/active": {
      "abstract": [
        {
          "text": "GameKit sent the exchange request to recipients but not all recipients replied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "active"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchangeStatus/active",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedExchangeStatusActive"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedExchangeStatus.active",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedexchangestatus/active"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchangeStatus/complete": {
      "abstract": [
        {
          "text": "All recipients of the exchange request replied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "complete"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchangeStatus/complete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedExchangeStatusComplete"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedExchangeStatus.complete",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedexchangestatus/complete"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchangeStatus/resolved": {
      "abstract": [
        {
          "text": "The current participant saved the exchange request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolved"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchangeStatus/resolved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedExchangeStatusResolved"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedExchangeStatus.resolved",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedexchangestatus/resolved"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch": {
      "abstract": [
        {
          "text": "An object that encapsulates the match data for games where players take turns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatch"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatch"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedMatch",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/completedExchanges": {
      "abstract": [
        {
          "text": "The exchange requests that all recipients replied to and the current participant needs to save.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completedExchanges"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKTurnBasedExchange",
          "text": "GKTurnBasedExchange"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/completedExchanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completedExchanges"
        }
      ],
      "role": "symbol",
      "title": "completedExchanges",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/completedexchanges"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/exchanges": {
      "abstract": [
        {
          "text": "The exchange requests that are active or complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exchanges"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKTurnBasedExchange",
          "text": "GKTurnBasedExchange"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/exchanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exchanges"
        }
      ],
      "role": "symbol",
      "title": "exchanges",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/exchanges"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/saveMergedMatch(_:withResolvedExchanges:completionHandler:)": {
      "abstract": [
        {
          "text": "Saves match data for completed exchanges without ending the turn.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saveMergedMatch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withResolvedExchanges"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKTurnBasedExchange",
          "text": "GKTurnBasedExchange"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/saveMergedMatch(_:withResolvedExchanges:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveMergedMatchData:withResolvedExchanges:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "saveMergedMatch(_:withResolvedExchanges:completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/savemergedmatch(_:withresolvedexchanges:completionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/sendExchange(to:data:localizableMessageKey:arguments:timeout:completionHandler:)": {
      "abstract": [
        {
          "text": "Sends an exchange request that contains your game data to one or more participants.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendExchange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKTurnBasedParticipant",
          "text": "GKTurnBasedParticipant"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "localizableMessageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "arguments"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "timeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKTurnBasedExchange",
          "text": "GKTurnBasedExchange"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/sendExchange(to:data:localizableMessageKey:arguments:timeout:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendExchangeToParticipants:data:localizableMessageKey:arguments:timeout:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "sendExchange(to:data:localizableMessageKey:arguments:timeout:completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/sendexchange(to:data:localizablemessagekey:arguments:timeout:completionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatchmakerViewController": {
      "abstract": [
        {
          "text": "An interface that allows a player to invite other players to a turn-based match and automatch to fill any empty slots.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatchmakerViewController"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatchmakerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatchmakerViewController"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedMatchmakerViewController",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatchmakerviewcontroller"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedParticipant": {
      "abstract": [
        {
          "text": "A participant in a turn-based match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKTurnBasedParticipant"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedParticipant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedParticipant"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedParticipant",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedparticipant"
    },
    "doc://com.apple.gamekit/documentation/GameKit/creating-turn-based-games": {
      "abstract": [
        {
          "text": "Develop games where multiple players take turns and can exchange data while waiting for their turn.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/creating-turn-based-games",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating turn-based games",
      "type": "topic",
      "url": "/documentation/gamekit/creating-turn-based-games"
    },
    "doc://com.apple.gamekit/documentation/GameKit/sending-messages-to-players-in-turn-based-games": {
      "abstract": [
        {
          "text": "Notify players of match events by sending messages and game data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/sending-messages-to-players-in-turn-based-games",
      "kind": "article",
      "role": "article",
      "title": "Sending messages to players in turn-based games",
      "type": "topic",
      "url": "/documentation/gamekit/sending-messages-to-players-in-turn-based-games"
    },
    "doc://com.apple.gamekit/documentation/GameKit/starting-turn-based-matches-and-passing-turns-between-players": {
      "abstract": [
        {
          "text": "Let Game Center store and forward match data between players in a turn-based game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/starting-turn-based-matches-and-passing-turns-between-players",
      "kind": "article",
      "role": "article",
      "title": "Starting turn-based matches and passing turns between players",
      "type": "topic",
      "url": "/documentation/gamekit/starting-turn-based-matches-and-passing-turns-between-players"
    },
    "https://docs.swift.org/swift-book/LanguageGuide/Concurrency.html": {
      "identifier": "https://docs.swift.org/swift-book/LanguageGuide/Concurrency.html",
      "title": "Concurrency",
      "titleInlineContent": [
        {
          "text": "Concurrency",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://docs.swift.org/swift-book/LanguageGuide/Concurrency.html"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Turn-based-games",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/creating-turn-based-games",
        "doc://com.apple.gamekit/documentation/GameKit/starting-turn-based-matches-and-passing-turns-between-players",
        "doc://com.apple.gamekit/documentation/GameKit/sending-messages-to-players-in-turn-based-games",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatchmakerViewController",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedParticipant",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventListener",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchange",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchangeReply",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/GKGameCenterBadgingDisabled"
      ],
      "title": "Turn-based games"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Turn-based-games",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/creating-turn-based-games",
                "doc://com.apple.gamekit/documentation/GameKit/starting-turn-based-matches-and-passing-turns-between-players",
                "doc://com.apple.gamekit/documentation/GameKit/sending-messages-to-players-in-turn-based-games",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatchmakerViewController",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedParticipant",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventListener",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchange",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedExchangeReply",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/GKGameCenterBadgingDisabled"
              ],
              "title": "Turn-based games"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedParticipant/title",
          "value": "GKTurnBasedParticipant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedParticipant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedParticipant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedParticipant/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedParticipant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventListener~1player(_:receivedExchangeRequest:for:)/title",
          "value": "player:receivedExchangeRequest:forMatch:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventListener~1player(_:receivedExchangeRequest:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "player:receivedExchangeRequest:forMatch:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchange~1sender/title",
          "value": "sender"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchange~1sender/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sender"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1saveMergedMatch(_:withResolvedExchanges:completionHandler:)/title",
          "value": "saveMergedMatchData:withResolvedExchanges:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1saveMergedMatch(_:withResolvedExchanges:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveMergedMatchData:withResolvedExchanges:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventListener~1player(_:receivedExchangeCancellation:for:)/title",
          "value": "player:receivedExchangeCancellation:forMatch:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventListener~1player(_:receivedExchangeCancellation:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "player:receivedExchangeCancellation:forMatch:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatchmakerViewController/title",
          "value": "GKTurnBasedMatchmakerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatchmakerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatchmakerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatchmakerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatchmakerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventListener~1player(_:receivedExchangeReplies:forCompletedExchange:for:)/title",
          "value": "player:receivedExchangeReplies:forCompletedExchange:forMatch:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventListener~1player(_:receivedExchangeReplies:forCompletedExchange:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "player:receivedExchangeReplies:forCompletedExchange:forMatch:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchangeStatus~1active/title",
          "value": "GKTurnBasedExchangeStatusActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchangeStatus~1active/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedExchangeStatusActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch/title",
          "value": "GKTurnBasedMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventListener~1player(_:receivedTurnEventFor:didBecomeActive:)/title",
          "value": "player:receivedTurnEventForMatch:didBecomeActive:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventListener~1player(_:receivedTurnEventFor:didBecomeActive:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "player:receivedTurnEventForMatch:didBecomeActive:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchangeStatus~1complete/title",
          "value": "GKTurnBasedExchangeStatusComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchangeStatus~1complete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedExchangeStatusComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1completedExchanges/title",
          "value": "completedExchanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1completedExchanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "completedExchanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1exchanges/title",
          "value": "exchanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1exchanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exchanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchange~1cancel(withLocalizableMessageKey:arguments:completionHandler:)/title",
          "value": "cancelWithLocalizableMessageKey:arguments:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchange~1cancel(withLocalizableMessageKey:arguments:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancelWithLocalizableMessageKey:arguments:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchangeStatus~1resolved/title",
          "value": "GKTurnBasedExchangeStatusResolved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchangeStatus~1resolved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedExchangeStatusResolved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchangeReply/title",
          "value": "GKTurnBasedExchangeReply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchangeReply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedExchangeReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchangeReply/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedExchangeReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchange~1message/title",
          "value": "message"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchange~1message/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "message"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1sendExchange(to:data:localizableMessageKey:arguments:timeout:completionHandler:)/title",
          "value": "sendExchangeToParticipants:data:localizableMessageKey:arguments:timeout:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1sendExchange(to:data:localizableMessageKey:arguments:timeout:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sendExchangeToParticipants:data:localizableMessageKey:arguments:timeout:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchange/title",
          "value": "GKTurnBasedExchange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedExchange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedExchange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventListener/title",
          "value": "GKTurnBasedEventListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventListener/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedEventListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventListener/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedEventListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchange~1reply(withLocalizableMessageKey:arguments:data:completionHandler:)/title",
          "value": "replyWithLocalizableMessageKey:arguments:data:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedExchange~1reply(withLocalizableMessageKey:arguments:data:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replyWithLocalizableMessageKey:arguments:data:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/exchanging-data-between-players-in-turn-based-games"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/exchanging-data-between-players-in-turn-based-games"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
