{
  "abstract": [
    {
      "text": "An object that allows players to view and manage their Game Center information from within your game.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GKAccessPoint",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GKAccessPoint"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKAccessPoint"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "GKAccessPoint"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKAccessPoint"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.gamekit/documentation/GameKit/adding-an-access-point-to-your-game"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The access point displays a control in a corner of your game that opens a Game Center dashboard when the player taps or clicks it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/shared",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to get the shared access point object. GameKit attaches the access point to the window you specify in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/parentWindow",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, in the corner you specify using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/location-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. If you don’t specify a parent window, GameKit infers an appropriate location. For the location of the access point on visionOS, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/adding-an-access-point-to-your-game#Configure-the-access-point-on-visionOS",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To display highlights, set the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/showHighlights",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Then set ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/isActive",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to display the access point control.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint": {
      "abstract": [
        {
          "text": "An object that allows players to view and manage their Game Center information from within your game.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKAccessPoint"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKAccessPoint"
        }
      ],
      "role": "symbol",
      "title": "GKAccessPoint",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum": {
      "abstract": [
        {
          "text": "Specifies the corner of the screen to display the access point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Location"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Location"
        }
      ],
      "role": "symbol",
      "title": "GKAccessPoint.Location",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/location-swift.enum"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/frameInScreenCoordinates": {
      "abstract": [
        {
          "text": "The frame of the access point in screen coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameInScreenCoordinates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/frameInScreenCoordinates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frameInScreenCoordinates"
        }
      ],
      "role": "symbol",
      "title": "frameInScreenCoordinates",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/frameinscreencoordinates"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/isActive": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether to display the access point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isActive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/isActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "active"
        }
      ],
      "role": "symbol",
      "title": "isActive",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/isactive"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/isFocused": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the access point is in focus on tvOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFocused"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/isFocused",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "focused"
        }
      ],
      "role": "symbol",
      "title": "isFocused",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/isfocused"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/isPresentingGameCenter": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the game is presenting the Game Center dashboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPresentingGameCenter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/isPresentingGameCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isPresentingGameCenter"
        }
      ],
      "role": "symbol",
      "title": "isPresentingGameCenter",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/ispresentinggamecenter"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/isVisible": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the access point is visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isVisible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/isVisible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visible"
        }
      ],
      "role": "symbol",
      "title": "isVisible",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/isvisible"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/location-swift.property": {
      "abstract": [
        {
          "text": "The corner of the screen to display the access point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKAccessPoint",
          "text": "GKAccessPoint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKAccessPointLocation",
          "text": "Location"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/location-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "location"
        }
      ],
      "role": "symbol",
      "title": "location",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/location-swift.property"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/parentWindow": {
      "abstract": [
        {
          "text": "The window that contains the access point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parentWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindow",
          "text": "UIWindow"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/parentWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parentWindow"
        }
      ],
      "role": "symbol",
      "title": "parentWindow",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/parentwindow"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/shared": {
      "abstract": [
        {
          "text": "The shared access point object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shared"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKAccessPoint",
          "text": "GKAccessPoint"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/shared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shared"
        }
      ],
      "role": "symbol",
      "title": "shared",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/shared"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/showHighlights": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to display highlights for achievements and current ranks for leaderboards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showHighlights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/showHighlights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showHighlights"
        }
      ],
      "role": "symbol",
      "title": "showHighlights",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/showhighlights"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(achievementID:handler:)": {
      "abstract": [
        {
          "text": "Displays the Game Center dashboard in a state that shows a specific achievement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trigger"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "achievementID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(achievementID:handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "triggerAccessPointWithAchievementID:handler:"
        }
      ],
      "role": "symbol",
      "title": "trigger(achievementID:handler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/trigger(achievementid:handler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(handler:)": {
      "abstract": [
        {
          "text": "Displays the Game Center dashboard as if the player taps or presses the access point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trigger"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "triggerAccessPointWithHandler:"
        }
      ],
      "role": "symbol",
      "title": "trigger(handler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/trigger(handler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(leaderboardID:playerScope:timeScope:handler:)": {
      "abstract": [
        {
          "text": "Displays the Game Center dashboard in a state that shows a specific leaderboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trigger"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "leaderboardID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "playerScope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboard",
          "text": "GKLeaderboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKLeaderboardPlayerScope",
          "text": "PlayerScope"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeScope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboard",
          "text": "GKLeaderboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKLeaderboardTimeScope",
          "text": "TimeScope"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(leaderboardID:playerScope:timeScope:handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "triggerAccessPointWithLeaderboardID:playerScope:timeScope:handler:"
        }
      ],
      "role": "symbol",
      "title": "trigger(leaderboardID:playerScope:timeScope:handler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/trigger(leaderboardid:playerscope:timescope:handler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(leaderboardSetID:handler:)": {
      "abstract": [
        {
          "text": "Displays the Game Center dashboard in a state that shows a specific leaderboard set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trigger"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "leaderboardSetID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(leaderboardSetID:handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "triggerAccessPointWithLeaderboardSetID:handler:"
        }
      ],
      "role": "symbol",
      "title": "trigger(leaderboardSetID:handler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/trigger(leaderboardsetid:handler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(player:handler:)": {
      "abstract": [
        {
          "text": "Displays the Game Center dashboard in a state that shows a player profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trigger"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "player"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(player:handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "triggerAccessPointWithPlayer:handler:"
        }
      ],
      "role": "symbol",
      "title": "trigger(player:handler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/trigger(player:handler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(state:handler:)": {
      "abstract": [
        {
          "text": "Displays the Game Center dashboard in the specified state as if the player taps or presses the access point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trigger"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKGameCenterViewControllerState",
          "text": "GKGameCenterViewControllerState"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(state:handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "triggerAccessPointWithState:handler:"
        }
      ],
      "role": "symbol",
      "title": "trigger(state:handler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkaccesspoint/trigger(state:handler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKDialogController": {
      "abstract": [
        {
          "text": "An object that provides the ability to present the dashboard in macOS games.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKDialogController"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKDialogController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKDialogController"
        }
      ],
      "role": "symbol",
      "title": "GKDialogController",
      "type": "topic",
      "url": "/documentation/gamekit/gkdialogcontroller"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController": {
      "abstract": [
        {
          "text": "The dashboard that allows players to access their Game Center data in your game.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGameCenterViewController"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterViewController"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterViewController",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontroller"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKNotificationBanner": {
      "abstract": [
        {
          "text": "A Game Center-style banner that displays a message to the local player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKNotificationBanner"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKNotificationBanner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKNotificationBanner"
        }
      ],
      "role": "symbol",
      "title": "GKNotificationBanner",
      "type": "topic",
      "url": "/documentation/gamekit/gknotificationbanner"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKViewController": {
      "abstract": [
        {
          "text": "The abstract base protocol adopted by GameKit view controller classes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKViewController"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKViewController"
        }
      ],
      "role": "symbol",
      "title": "GKViewController",
      "type": "topic",
      "url": "/documentation/gamekit/gkviewcontroller"
    },
    "doc://com.apple.gamekit/documentation/GameKit/adding-an-access-point-to-your-game": {
      "abstract": [
        {
          "text": "Provide your users a convenient connection to the Game Center dashboard.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/adding-an-access-point-to-your-game",
      "kind": "article",
      "role": "article",
      "title": "Adding an access point to your game",
      "type": "topic",
      "url": "/documentation/gamekit/adding-an-access-point-to-your-game"
    },
    "doc://com.apple.gamekit/documentation/GameKit/adding-an-access-point-to-your-game#Configure-the-access-point-on-visionOS": {
      "abstract": [],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/adding-an-access-point-to-your-game#Configure-the-access-point-on-visionOS",
      "kind": "section",
      "title": "Configure the access point on visionOS",
      "type": "topic",
      "url": "/documentation/gamekit/adding-an-access-point-to-your-game#Configure-the-access-point-on-visionOS"
    },
    "doc://com.apple.gamekit/documentation/GameKit/displaying-the-game-center-dashboard": {
      "abstract": [
        {
          "text": "Provide an interface for players to navigate to their Game Center data from your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/displaying-the-game-center-dashboard",
      "kind": "article",
      "role": "article",
      "title": "Displaying the Game Center dashboard",
      "type": "topic",
      "url": "/documentation/gamekit/displaying-the-game-center-dashboard"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Game-Center-interfaces",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/adding-an-access-point-to-your-game",
        "doc://com.apple.gamekit/documentation/GameKit/displaying-the-game-center-dashboard",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController",
        "doc://com.apple.gamekit/documentation/GameKit/GKDialogController",
        "doc://com.apple.gamekit/documentation/GameKit/GKViewController",
        "doc://com.apple.gamekit/documentation/GameKit/GKNotificationBanner"
      ],
      "title": "Game Center interfaces"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-shared-access-point",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/shared"
      ],
      "title": "Getting the shared access point"
    },
    {
      "anchor": "Managing-the-location",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/location-swift.property",
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum",
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/frameInScreenCoordinates",
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/parentWindow"
      ],
      "title": "Managing the location"
    },
    {
      "anchor": "Displaying-the-access-point",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/isActive",
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/isPresentingGameCenter",
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/isVisible",
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/showHighlights"
      ],
      "title": "Displaying the access point"
    },
    {
      "anchor": "Managing-the-access-point",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/isFocused",
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(handler:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(state:handler:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(player:handler:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(achievementID:handler:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(leaderboardID:playerScope:timeScope:handler:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(leaderboardSetID:handler:)"
      ],
      "title": "Managing the access point"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKAccessPoint"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAccessPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAccessPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-shared-access-point",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/shared"
              ],
              "title": "Getting the shared access point"
            },
            {
              "anchor": "Managing-the-location",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/location-swift.property",
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/Location-swift.enum",
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/frameInScreenCoordinates",
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/parentWindow"
              ],
              "title": "Managing the location"
            },
            {
              "anchor": "Displaying-the-access-point",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/isActive",
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/isPresentingGameCenter",
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/isVisible",
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/showHighlights"
              ],
              "title": "Displaying the access point"
            },
            {
              "anchor": "Managing-the-access-point",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/isFocused",
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(handler:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(state:handler:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(player:handler:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(achievementID:handler:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(leaderboardID:playerScope:timeScope:handler:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKAccessPoint/trigger(leaderboardSetID:handler:)"
              ],
              "title": "Managing the access point"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Game-Center-interfaces",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/adding-an-access-point-to-your-game",
                "doc://com.apple.gamekit/documentation/GameKit/displaying-the-game-center-dashboard",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController",
                "doc://com.apple.gamekit/documentation/GameKit/GKDialogController",
                "doc://com.apple.gamekit/documentation/GameKit/GKViewController",
                "doc://com.apple.gamekit/documentation/GameKit/GKNotificationBanner"
              ],
              "title": "Game Center interfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GKAccessPoint"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKViewController/title",
          "value": "GKViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1Location-swift.enum/title",
          "value": "GKAccessPointLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1Location-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAccessPointLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1Location-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAccessPointLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1trigger(state:handler:)/title",
          "value": "triggerAccessPointWithState:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1trigger(state:handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "triggerAccessPointWithState:handler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1showHighlights/title",
          "value": "showHighlights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1showHighlights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showHighlights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1isVisible/title",
          "value": "visible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1isVisible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "visible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1trigger(leaderboardID:playerScope:timeScope:handler:)/title",
          "value": "triggerAccessPointWithLeaderboardID:playerScope:timeScope:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1trigger(leaderboardID:playerScope:timeScope:handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "triggerAccessPointWithLeaderboardID:playerScope:timeScope:handler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKNotificationBanner/title",
          "value": "GKNotificationBanner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKNotificationBanner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKNotificationBanner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKNotificationBanner/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKNotificationBanner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1trigger(player:handler:)/title",
          "value": "triggerAccessPointWithPlayer:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1trigger(player:handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "triggerAccessPointWithPlayer:handler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1isPresentingGameCenter/title",
          "value": "isPresentingGameCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1isPresentingGameCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isPresentingGameCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1trigger(achievementID:handler:)/title",
          "value": "triggerAccessPointWithAchievementID:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1trigger(achievementID:handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "triggerAccessPointWithAchievementID:handler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1trigger(handler:)/title",
          "value": "triggerAccessPointWithHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1trigger(handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "triggerAccessPointWithHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1isFocused/title",
          "value": "focused"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1isFocused/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focused"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1trigger(leaderboardSetID:handler:)/title",
          "value": "triggerAccessPointWithLeaderboardSetID:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1trigger(leaderboardSetID:handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "triggerAccessPointWithLeaderboardSetID:handler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1parentWindow/title",
          "value": "parentWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1parentWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "parentWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKDialogController/title",
          "value": "GKDialogController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKDialogController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKDialogController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKDialogController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKDialogController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint/title",
          "value": "GKAccessPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAccessPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAccessPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewController/title",
          "value": "GKGameCenterViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1shared/title",
          "value": "shared"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1shared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shared"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1location-swift.property/title",
          "value": "location"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1location-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "location"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1isActive/title",
          "value": "active"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1isActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "active"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1frameInScreenCoordinates/title",
          "value": "frameInScreenCoordinates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAccessPoint~1frameInScreenCoordinates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frameInScreenCoordinates"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkaccesspoint"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gkaccesspoint"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
