{
  "abstract": [
    {
      "text": "The error structure used by this framework.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11GKErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GKError"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "GKError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKError"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.gamekit/documentation/GameKit/finding-multiple-players-for-a-game"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError": {
      "abstract": [
        {
          "text": "The error structure used by this framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKError"
        }
      ],
      "role": "symbol",
      "title": "GKError",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code": {
      "abstract": [
        {
          "text": "Error codes for the GameKit error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/apiNotAvailable": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the API isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apiNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/apiNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "apiNotAvailable",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/apinotavailable"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/apiObsolete": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because Apple deprecated the API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apiObsolete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/apiObsolete",
      "kind": "symbol",
      "role": "symbol",
      "title": "apiObsolete",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/apiobsolete"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/appUnlisted": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the game isn’t available on the App Store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appUnlisted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/appUnlisted",
      "kind": "symbol",
      "role": "symbol",
      "title": "appUnlisted",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/appunlisted"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/authenticationInProgress": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the local player is already authenticating.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authenticationInProgress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/authenticationInProgress",
      "kind": "symbol",
      "role": "symbol",
      "title": "authenticationInProgress",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/authenticationinprogress"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/cancelled": {
      "abstract": [
        {
          "text": "The system canceled the requested operation or the user disabled it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/cancelled",
      "kind": "symbol",
      "role": "symbol",
      "title": "cancelled",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/cancelled"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/challengeInvalid": {
      "abstract": [
        {
          "text": "The challenge request failed due to invalid challenge data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "challengeInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/challengeInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "challengeInvalid",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/challengeinvalid"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/communicationsFailure": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation due to an error communicating with the server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "communicationsFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/communicationsFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "communicationsFailure",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/communicationsfailure"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/connectionTimeout": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the connection timed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/connectionTimeout",
      "kind": "symbol",
      "role": "symbol",
      "title": "connectionTimeout",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/connectiontimeout"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/debugMode": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debugMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/debugMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "debugMode",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/debugmode"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/errordomain"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/friendListDenied": {
      "abstract": [
        {
          "text": "The local player denies access to their friends list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "friendListDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/friendListDenied",
      "kind": "symbol",
      "role": "symbol",
      "title": "friendListDenied",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/friendlistdenied"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/friendListDescriptionMissing": {
      "abstract": [
        {
          "text": "The system denies access to the local player’s friends list because the game didn’t provide a reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "friendListDescriptionMissing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/friendListDescriptionMissing",
      "kind": "symbol",
      "role": "symbol",
      "title": "friendListDescriptionMissing",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/friendlistdescriptionmissing"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/friendListRestricted": {
      "abstract": [
        {
          "text": "The system restricts access to the local player’s friends list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "friendListRestricted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/friendListRestricted",
      "kind": "symbol",
      "role": "symbol",
      "title": "friendListRestricted",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/friendlistrestricted"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/friendRequestNotAvailable": {
      "abstract": [
        {
          "text": "The player can’t send a friend request at this time from this device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "friendRequestNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/friendRequestNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "friendRequestNotAvailable",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/friendrequestnotavailable"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/gameSessionRequestInvalid": {
      "abstract": [
        {
          "text": "The properties of the game session request are impossible to fulfill.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gameSessionRequestInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/gameSessionRequestInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "gameSessionRequestInvalid",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/gamesessionrequestinvalid"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/gameUnrecognized": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because Game Center doesn’t recognize the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gameUnrecognized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/gameUnrecognized",
      "kind": "symbol",
      "role": "symbol",
      "title": "gameUnrecognized",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/gameunrecognized"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/iCloudUnavailable": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because it can’t access the player’s iCloud account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iCloudUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/iCloudUnavailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "iCloudUnavailable",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/icloudunavailable"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/invalidCredentials": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the user name or password are incorrect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidCredentials"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/invalidCredentials",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidCredentials",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/invalidcredentials"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/invalidParameter": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because one or more parameters are invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/invalidParameter",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidParameter",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/invalidparameter"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/invalidPlayer": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the player is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPlayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/invalidPlayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidPlayer",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/invalidplayer"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/invitationsDisabled": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the receiving player has disabled invitations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invitationsDisabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/invitationsDisabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "invitationsDisabled",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/invitationsdisabled"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/lockdownMode": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the player enabled Lockdown Mode on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lockdownMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/lockdownMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "lockdownMode",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/lockdownmode"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/matchNotConnected": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the match isn’t connected to other players.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchNotConnected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/matchNotConnected",
      "kind": "symbol",
      "role": "symbol",
      "title": "matchNotConnected",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/matchnotconnected"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/matchRequestInvalid": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the match request is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchRequestInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/matchRequestInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "matchRequestInvalid",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/matchrequestinvalid"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/notAuthenticated": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the system hasn’t authenticated the local player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthenticated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/notAuthenticated",
      "kind": "symbol",
      "role": "symbol",
      "title": "notAuthenticated",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/notauthenticated"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/notAuthorized": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the system hasn’t authorized the player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthorized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/notAuthorized",
      "kind": "symbol",
      "role": "symbol",
      "title": "notAuthorized",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/notauthorized"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/notSupported": {
      "abstract": [
        {
          "text": "The app doesn’t have Game Center enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/notSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "notSupported",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/notsupported"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/parentalControlsBlocked": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the user disabled this feature in Restrictions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parentalControlsBlocked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/parentalControlsBlocked",
      "kind": "symbol",
      "role": "symbol",
      "title": "parentalControlsBlocked",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/parentalcontrolsblocked"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/playerPhotoFailure": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation to retrieve a player’s photo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerPhotoFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/playerPhotoFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "playerPhotoFailure",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/playerphotofailure"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/playerStatusExceedsMaximumLength": {
      "abstract": [
        {
          "text": "The player’s status exceeds the maximum length.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerStatusExceedsMaximumLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/playerStatusExceedsMaximumLength",
      "kind": "symbol",
      "role": "symbol",
      "title": "playerStatusExceedsMaximumLength",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/playerstatusexceedsmaximumlength"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/playerStatusInvalid": {
      "abstract": [
        {
          "text": "The player’s status is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerStatusInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/playerStatusInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "playerStatusInvalid",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/playerstatusinvalid"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/restrictedToAutomatch": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the player is using automatch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restrictedToAutomatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/restrictedToAutomatch",
      "kind": "symbol",
      "role": "symbol",
      "title": "restrictedToAutomatch",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/restrictedtoautomatch"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/scoreNotSet": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the system hasn’t set the score.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scoreNotSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/scoreNotSet",
      "kind": "symbol",
      "role": "symbol",
      "title": "scoreNotSet",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/scorenotset"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/turnBasedInvalidParticipant": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the specified participant is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "turnBasedInvalidParticipant"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/turnBasedInvalidParticipant",
      "kind": "symbol",
      "role": "symbol",
      "title": "turnBasedInvalidParticipant",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/turnbasedinvalidparticipant"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/turnBasedInvalidState": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the session is in an invalid state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "turnBasedInvalidState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/turnBasedInvalidState",
      "kind": "symbol",
      "role": "symbol",
      "title": "turnBasedInvalidState",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/turnbasedinvalidstate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/turnBasedInvalidTurn": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the participant doesn’t have the required turn state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "turnBasedInvalidTurn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/turnBasedInvalidTurn",
      "kind": "symbol",
      "role": "symbol",
      "title": "turnBasedInvalidTurn",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/turnbasedinvalidturn"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/turnBasedMatchDataTooLarge": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the match data is too large.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "turnBasedMatchDataTooLarge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/turnBasedMatchDataTooLarge",
      "kind": "symbol",
      "role": "symbol",
      "title": "turnBasedMatchDataTooLarge",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/turnbasedmatchdatatoolarge"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/turnBasedTooManySessions": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because it exceeds the maximum number of sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "turnBasedTooManySessions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/turnBasedTooManySessions",
      "kind": "symbol",
      "role": "symbol",
      "title": "turnBasedTooManySessions",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/turnbasedtoomanysessions"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/ubiquityContainerUnavailable": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the user hasn’t signed in to iCloud or hasn’t enabled iCloud Drive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ubiquityContainerUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/ubiquityContainerUnavailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "ubiquityContainerUnavailable",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/ubiquitycontainerunavailable"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/underage": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because this feature isn’t available to underage players.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "underage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/underage",
      "kind": "symbol",
      "role": "symbol",
      "title": "underage",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/underage"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/unexpectedConnection": {
      "abstract": [
        {
          "text": "An unexpected player has connected to a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unexpectedConnection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/unexpectedConnection",
      "kind": "symbol",
      "role": "symbol",
      "title": "unexpectedConnection",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/unexpectedconnection"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/unknown": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation due to an unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/unknown"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/userDenied": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the user denied it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11GKErrorCodeLeV",
          "text": "GKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/userDenied",
      "kind": "symbol",
      "role": "symbol",
      "title": "userDenied",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/userdenied"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for general game errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "GKErrorDomain",
      "type": "topic",
      "url": "/documentation/gamekit/gkerrordomain"
    },
    "doc://com.apple.gamekit/documentation/GameKit/finding-multiple-players-for-a-game": {
      "abstract": [
        {
          "text": "Discover and invite other players to participate in a real-time game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/finding-multiple-players-for-a-game",
      "kind": "article",
      "role": "article",
      "title": "Finding multiple players for a game",
      "type": "topic",
      "url": "/documentation/gamekit/finding-multiple-players-for-a-game"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code",
        "doc://com.apple.gamekit/documentation/GameKit/GKErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/authenticationInProgress",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/cancelled",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/challengeInvalid",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/communicationsFailure",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/gameSessionRequestInvalid",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/gameUnrecognized",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/invalidCredentials",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/invalidParameter",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/invalidPlayer",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/invitationsDisabled",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/matchNotConnected",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/matchRequestInvalid",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/notAuthenticated",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/notSupported",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/parentalControlsBlocked",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/playerPhotoFailure",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/playerStatusExceedsMaximumLength",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/playerStatusInvalid",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/scoreNotSet",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/turnBasedInvalidParticipant",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/turnBasedInvalidState",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/turnBasedInvalidTurn",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/turnBasedMatchDataTooLarge",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/turnBasedTooManySessions",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/ubiquityContainerUnavailable",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/underage",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/unexpectedConnection",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/unknown",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/userDenied",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/restrictedToAutomatch",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/apiNotAvailable",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/notAuthorized",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/connectionTimeout",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/apiObsolete",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/iCloudUnavailable",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/lockdownMode",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/appUnlisted",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/friendListDescriptionMissing",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/friendListRestricted",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/friendListDenied",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/friendRequestNotAvailable"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKError/debugMode",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKErrorDomain/title",
          "value": "GKErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code/title",
          "value": "GKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
