{
  "abstract": [
    {
      "text": "Constants that indicate if the local player grants access to their friends list.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@GKFriendsAuthorizationStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GKFriendsAuthorizationStatus"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKFriendsAuthorizationStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.3",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "GKFriendsAuthorizationStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKFriendsAuthorizationStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSGKFriendListUsageDescription": {
      "abstract": [
        {
          "text": "A message that tells the user why the app needs access to their Game Center friends list.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSGKFriendListUsageDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGKFriendListUsageDescription",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSGKFriendListUsageDescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus": {
      "abstract": [
        {
          "text": "Constants that indicate if the local player grants access to their friends list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKFriendsAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKFriendsAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "GKFriendsAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/gamekit/gkfriendsauthorizationstatus"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus/authorized": {
      "abstract": [
        {
          "text": "The player authorized your game to access their list of friends.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorized"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus/authorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKFriendsAuthorizationStatusAuthorized"
        }
      ],
      "role": "symbol",
      "title": "GKFriendsAuthorizationStatus.authorized",
      "type": "topic",
      "url": "/documentation/gamekit/gkfriendsauthorizationstatus/authorized"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus/denied": {
      "abstract": [
        {
          "text": "Access to the player’s friends’ data denied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "denied"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus/denied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKFriendsAuthorizationStatusDenied"
        }
      ],
      "role": "symbol",
      "title": "GKFriendsAuthorizationStatus.denied",
      "type": "topic",
      "url": "/documentation/gamekit/gkfriendsauthorizationstatus/denied"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkfriendsauthorizationstatus/init(rawvalue:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus/notDetermined": {
      "abstract": [
        {
          "text": "The player hasn’t choosen whether your game may access their friends list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notDetermined"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus/notDetermined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKFriendsAuthorizationStatusNotDetermined"
        }
      ],
      "role": "symbol",
      "title": "GKFriendsAuthorizationStatus.notDetermined",
      "type": "topic",
      "url": "/documentation/gamekit/gkfriendsauthorizationstatus/notdetermined"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus/restricted": {
      "abstract": [
        {
          "text": "Access to the player’s list of friends restricted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restricted"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus/restricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKFriendsAuthorizationStatusRestricted"
        }
      ],
      "role": "symbol",
      "title": "GKFriendsAuthorizationStatus.restricted",
      "type": "topic",
      "url": "/documentation/gamekit/gkfriendsauthorizationstatus/restricted"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadChallengableFriends(completionHandler:)": {
      "abstract": [
        {
          "text": "Loads players to whom the local player can issue a challenge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadChallengableFriends"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadChallengableFriends(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadChallengableFriendsWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "loadChallengableFriends(completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gklocalplayer/loadchallengablefriends(completionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadFriends(_:)": {
      "abstract": [
        {
          "text": "Loads the local player’s friends list if the local player and their friends grant access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadFriends"
        },
        {
          "kind": "text",
          "text": "((["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadFriends(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadFriends:"
        }
      ],
      "role": "symbol",
      "title": "loadFriends(_:)",
      "type": "topic",
      "url": "/documentation/gamekit/gklocalplayer/loadfriends(_:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadFriends(identifiedBy:completionHandler:)": {
      "abstract": [
        {
          "text": "Loads the player’s friends list, scoped by the identifiers, if the player and their friends grant access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadFriends"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "identifiedBy"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadFriends(identifiedBy:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadFriendsWithIdentifiers:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "loadFriends(identifiedBy:completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gklocalplayer/loadfriends(identifiedby:completionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadFriendsAuthorizationStatus(_:)": {
      "abstract": [
        {
          "text": "Returns whether the player authorizes your game to access their friends list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadFriendsAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKFriendsAuthorizationStatus",
          "text": "GKFriendsAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadFriendsAuthorizationStatus(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadFriendsAuthorizationStatus:"
        }
      ],
      "role": "symbol",
      "title": "loadFriendsAuthorizationStatus(_:)",
      "type": "topic",
      "url": "/documentation/gamekit/gklocalplayer/loadfriendsauthorizationstatus(_:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadRecentPlayers(completionHandler:)": {
      "abstract": [
        {
          "text": "Loads players from the friends list or players that recently participated in a game with the local player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadRecentPlayers"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadRecentPlayers(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadRecentPlayersWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "loadRecentPlayers(completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gklocalplayer/loadrecentplayers(completionhandler:)"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Friends-and-Recents",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadFriendsAuthorizationStatus(_:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadFriends(_:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadFriends(identifiedBy:completionHandler:)",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSGKFriendListUsageDescription",
        "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadChallengableFriends(completionHandler:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadRecentPlayers(completionHandler:)"
      ],
      "title": "Accessing Friends and Recents"
    }
  ],
  "topicSections": [
    {
      "anchor": "Authorization-Statuses",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus/authorized",
        "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus/denied",
        "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus/notDetermined",
        "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus/restricted"
      ],
      "title": "Authorization Statuses"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.3",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKFriendsAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKFriendsAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKFriendsAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Authorization-Statuses",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus/authorized",
                "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus/denied",
                "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus/notDetermined",
                "doc://com.apple.gamekit/documentation/GameKit/GKFriendsAuthorizationStatus/restricted"
              ],
              "title": "Authorization Statuses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Friends-and-Recents",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadFriendsAuthorizationStatus(_:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadFriends(_:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadFriends(identifiedBy:completionHandler:)",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSGKFriendListUsageDescription",
                "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadChallengableFriends(completionHandler:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKLocalPlayer/loadRecentPlayers(completionHandler:)"
              ],
              "title": "Accessing Friends and Recents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GKFriendsAuthorizationStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLocalPlayer~1loadFriends(identifiedBy:completionHandler:)/title",
          "value": "loadFriendsWithIdentifiers:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLocalPlayer~1loadFriends(identifiedBy:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadFriendsWithIdentifiers:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLocalPlayer~1loadFriendsAuthorizationStatus(_:)/title",
          "value": "loadFriendsAuthorizationStatus:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLocalPlayer~1loadFriendsAuthorizationStatus(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadFriendsAuthorizationStatus:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendsAuthorizationStatus~1notDetermined/title",
          "value": "GKFriendsAuthorizationStatusNotDetermined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendsAuthorizationStatus~1notDetermined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKFriendsAuthorizationStatusNotDetermined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLocalPlayer~1loadFriends(_:)/title",
          "value": "loadFriends:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLocalPlayer~1loadFriends(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadFriends:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendsAuthorizationStatus~1authorized/title",
          "value": "GKFriendsAuthorizationStatusAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendsAuthorizationStatus~1authorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKFriendsAuthorizationStatusAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendsAuthorizationStatus~1restricted/title",
          "value": "GKFriendsAuthorizationStatusRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendsAuthorizationStatus~1restricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKFriendsAuthorizationStatusRestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendsAuthorizationStatus~1denied/title",
          "value": "GKFriendsAuthorizationStatusDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendsAuthorizationStatus~1denied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKFriendsAuthorizationStatusDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendsAuthorizationStatus/title",
          "value": "GKFriendsAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendsAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKFriendsAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendsAuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKFriendsAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLocalPlayer~1loadRecentPlayers(completionHandler:)/title",
          "value": "loadRecentPlayersWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLocalPlayer~1loadRecentPlayers(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadRecentPlayersWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLocalPlayer~1loadChallengableFriends(completionHandler:)/title",
          "value": "loadChallengableFriendsWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLocalPlayer~1loadChallengableFriends(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadChallengableFriendsWithCompletionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkfriendsauthorizationstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gkfriendsauthorizationstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
