{
  "abstract": [
    {
      "text": "Error codes for the game session domain.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "GKGameSession is deprecated, use real-time and turn-based matchmaking APIs instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC22GKGameSessionErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GKGameSessionError"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKGameSessionError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.0",
        "message": "GKGameSession is deprecated, use real-time and turn-based matchmaking APIs instead.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.0",
        "message": "GKGameSession is deprecated, use real-time and turn-based matchmaking APIs instead.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "GKGameSession is deprecated, use real-time and turn-based matchmaking APIs instead.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.12",
        "message": "GKGameSession is deprecated, use real-time and turn-based matchmaking APIs instead.",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.0",
        "message": "GKGameSession is deprecated, use real-time and turn-based matchmaking APIs instead.",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "GKGameSession is deprecated, use real-time and turn-based matchmaking APIs instead.",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "GKGameSessionError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKGameSessionError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError": {
      "abstract": [
        {
          "text": "Error codes for the game session domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGameSessionError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameSessionError"
        }
      ],
      "role": "symbol",
      "title": "GKGameSessionError",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/Code": {
      "abstract": [
        {
          "text": "Error codes for the game session domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "GKGameSessionError.Code",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/code"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/badContainer": {
      "abstract": [
        {
          "text": "The requested operation could not be completed because the iCloud container is invalid.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badContainer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22GKGameSessionErrorCodeLeV",
          "text": "GKGameSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKGameSessionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/badContainer",
      "kind": "symbol",
      "role": "symbol",
      "title": "badContainer",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/badcontainer"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/cloudDriveDisabled": {
      "abstract": [
        {
          "text": "The requested operation could not be completed because iCloud Drive has been disabled for the application.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudDriveDisabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22GKGameSessionErrorCodeLeV",
          "text": "GKGameSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKGameSessionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/cloudDriveDisabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "cloudDriveDisabled",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/clouddrivedisabled"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/cloudQuotaExceeded": {
      "abstract": [
        {
          "text": "The requested operation could not be completed because the user’s iCloud quota would be exceeded.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudQuotaExceeded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22GKGameSessionErrorCodeLeV",
          "text": "GKGameSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKGameSessionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/cloudQuotaExceeded",
      "kind": "symbol",
      "role": "symbol",
      "title": "cloudQuotaExceeded",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/cloudquotaexceeded"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/connectionCancelledByUser": {
      "abstract": [
        {
          "text": "The requested operation could not be completed because the connection to the session was cancelled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionCancelledByUser"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22GKGameSessionErrorCodeLeV",
          "text": "GKGameSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKGameSessionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/connectionCancelledByUser",
      "kind": "symbol",
      "role": "symbol",
      "title": "connectionCancelledByUser",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/connectioncancelledbyuser"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/connectionFailed": {
      "abstract": [
        {
          "text": "The requested operation could not be completed because the session could not find other players to connect to.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22GKGameSessionErrorCodeLeV",
          "text": "GKGameSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKGameSessionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/connectionFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "connectionFailed",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/connectionfailed"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/errorDomain": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/errordomain"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/invalidSession": {
      "abstract": [
        {
          "text": "The requested operation could not be completed because the Game Session does not exist or the player is not part of the game session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22GKGameSessionErrorCodeLeV",
          "text": "GKGameSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKGameSessionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/invalidSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidSession",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/invalidsession"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/networkFailure": {
      "abstract": [
        {
          "text": "The requested operation could not be completed due to an error communicating with the server.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22GKGameSessionErrorCodeLeV",
          "text": "GKGameSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKGameSessionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/networkFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "networkFailure",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/networkfailure"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/notAuthenticated": {
      "abstract": [
        {
          "text": "The requested operation could not be completed because you are not signed in to iCloud.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthenticated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22GKGameSessionErrorCodeLeV",
          "text": "GKGameSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKGameSessionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/notAuthenticated",
      "kind": "symbol",
      "role": "symbol",
      "title": "notAuthenticated",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/notauthenticated"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sendDataNoRecipients": {
      "abstract": [
        {
          "text": "The requested operation could not be completed because there are no recipients connected to session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendDataNoRecipients"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22GKGameSessionErrorCodeLeV",
          "text": "GKGameSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKGameSessionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sendDataNoRecipients",
      "kind": "symbol",
      "role": "symbol",
      "title": "sendDataNoRecipients",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/senddatanorecipients"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sendDataNotConnected": {
      "abstract": [
        {
          "text": "The requested operation could not be completed because you are not connected to the session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendDataNotConnected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22GKGameSessionErrorCodeLeV",
          "text": "GKGameSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKGameSessionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sendDataNotConnected",
      "kind": "symbol",
      "role": "symbol",
      "title": "sendDataNotConnected",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/senddatanotconnected"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sendDataNotReachable": {
      "abstract": [
        {
          "text": "The requested operation could not be completed because one or more players is not reachable.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendDataNotReachable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22GKGameSessionErrorCodeLeV",
          "text": "GKGameSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKGameSessionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sendDataNotReachable",
      "kind": "symbol",
      "role": "symbol",
      "title": "sendDataNotReachable",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/senddatanotreachable"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sendRateLimitReached": {
      "abstract": [
        {
          "text": "The requested operation could not be completed because you have reached the limits for save data request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendRateLimitReached"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22GKGameSessionErrorCodeLeV",
          "text": "GKGameSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKGameSessionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sendRateLimitReached",
      "kind": "symbol",
      "role": "symbol",
      "title": "sendRateLimitReached",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/sendratelimitreached"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sessionConflict": {
      "abstract": [
        {
          "text": "The requested operation could not be completed because the session has been updated on the server, causing a conflict.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionConflict"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22GKGameSessionErrorCodeLeV",
          "text": "GKGameSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKGameSessionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sessionConflict",
      "kind": "symbol",
      "role": "symbol",
      "title": "sessionConflict",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/sessionconflict"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sessionHasMaxConnectedPlayers": {
      "abstract": [
        {
          "text": "The requested operation could not be completed because the session has reached the maximum number of connected players.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionHasMaxConnectedPlayers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22GKGameSessionErrorCodeLeV",
          "text": "GKGameSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKGameSessionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sessionHasMaxConnectedPlayers",
      "kind": "symbol",
      "role": "symbol",
      "title": "sessionHasMaxConnectedPlayers",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/sessionhasmaxconnectedplayers"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sessionNotShared": {
      "abstract": [
        {
          "text": "The requested operation could not be completed because this session has not been shared with other players.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionNotShared"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22GKGameSessionErrorCodeLeV",
          "text": "GKGameSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKGameSessionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sessionNotShared",
      "kind": "symbol",
      "role": "symbol",
      "title": "sessionNotShared",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/sessionnotshared"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/unknown": {
      "abstract": [
        {
          "text": "The requested operation could not be completed due to an unknown error.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC22GKGameSessionErrorCodeLeV",
          "text": "GKGameSessionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKGameSessionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerror/unknown"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for game sessions.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGameSessionErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameSessionErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "GKGameSessionErrorDomain",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessionerrordomain"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKSessionError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionError"
        }
      ],
      "role": "symbol",
      "title": "GKSessionError",
      "type": "topic",
      "url": "/documentation/gamekit/gksessionerror-swift.struct"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatServiceError"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatServiceError",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatserviceerror-swift.struct"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatServiceError-swift.struct",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionError-swift.struct"
      ],
      "title": "Deprecated structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/badContainer",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/cloudDriveDisabled",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/cloudQuotaExceeded",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/connectionCancelledByUser",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/connectionFailed",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/invalidSession",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/networkFailure",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/notAuthenticated",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sendDataNoRecipients",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sendDataNotConnected",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sendDataNotReachable",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sendRateLimitReached",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sessionConflict",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sessionHasMaxConnectedPlayers",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/sessionNotShared",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/unknown",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/Code"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Error-Domain",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionErrorDomain"
      ],
      "title": "Error Domain"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionError/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionError~1Code/title",
          "value": "GKGameSessionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameSessionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameSessionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionErrorDomain/title",
          "value": "GKGameSessionErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameSessionErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkgamesessionerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
