{
  "abstract": [
    {
      "text": "The type of content for the view controller to present.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@GKGameCenterViewControllerState",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GKGameCenterViewControllerState"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKGameCenterViewControllerState"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "GKGameCenterViewControllerState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerState"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(achievementID:)": {
      "abstract": [
        {
          "text": "Creates a view controller that presents an achievement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "achievementID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(achievementID:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithAchievementID:"
        }
      ],
      "role": "symbol",
      "title": "init(achievementID:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontroller/init(achievementid:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(leaderboard:playerScope:)": {
      "abstract": [
        {
          "text": "Creates a view controller that presents a leaderboard with data for the specified players.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "leaderboard"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboard",
          "text": "GKLeaderboard"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "playerScope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboard",
          "text": "GKLeaderboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKLeaderboardPlayerScope",
          "text": "PlayerScope"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(leaderboard:playerScope:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLeaderboard:playerScope:"
        }
      ],
      "role": "symbol",
      "title": "init(leaderboard:playerScope:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontroller/init(leaderboard:playerscope:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(leaderboardID:playerScope:timeScope:)": {
      "abstract": [
        {
          "text": "Creates a view controller that presents a leaderboard with data from the specified players and time period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "leaderboardID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "playerScope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboard",
          "text": "GKLeaderboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKLeaderboardPlayerScope",
          "text": "PlayerScope"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeScope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboard",
          "text": "GKLeaderboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKLeaderboardTimeScope",
          "text": "TimeScope"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(leaderboardID:playerScope:timeScope:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLeaderboardID:playerScope:timeScope:"
        }
      ],
      "role": "symbol",
      "title": "init(leaderboardID:playerScope:timeScope:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontroller/init(leaderboardid:playerscope:timescope:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(leaderboardSetID:)": {
      "abstract": [
        {
          "text": "Creates a view controller that presents a leaderboard set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "leaderboardSetID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(leaderboardSetID:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLeaderboardSetID:"
        }
      ],
      "role": "symbol",
      "title": "init(leaderboardSetID:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontroller/init(leaderboardsetid:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(player:)": {
      "abstract": [
        {
          "text": "Creates a view controller that presents a player’s Game Center profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "player"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(player:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPlayer:"
        }
      ],
      "role": "symbol",
      "title": "init(player:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontroller/init(player:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(state:)": {
      "abstract": [
        {
          "text": "Creates a view controller that presents the specified Game Center content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKGameCenterViewControllerState",
          "text": "GKGameCenterViewControllerState"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(state:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithState:"
        }
      ],
      "role": "symbol",
      "title": "init(state:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontroller/init(state:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState": {
      "abstract": [
        {
          "text": "The type of content for the view controller to present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGameCenterViewControllerState"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterViewControllerState"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterViewControllerState",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontrollerstate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/achievements": {
      "abstract": [
        {
          "text": "The view controller should present a list of achievements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "achievements"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/achievements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterViewControllerStateAchievements"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterViewControllerState.achievements",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontrollerstate/achievements"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/challenges": {
      "abstract": [
        {
          "text": "The view controller should present a list of challenges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "challenges"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/challenges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterViewControllerStateChallenges"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterViewControllerState.challenges",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontrollerstate/challenges"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/dashboard": {
      "abstract": [
        {
          "text": "The view controller should present the dashboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dashboard"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/dashboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterViewControllerStateDashboard"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterViewControllerState.dashboard",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontrollerstate/dashboard"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/default": {
      "abstract": [
        {
          "text": "The view controller should present the default screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterViewControllerStateDefault"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterViewControllerState.default",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontrollerstate/default"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontrollerstate/init(rawvalue:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/leaderboards": {
      "abstract": [
        {
          "text": "The view controller should present leaderboard sets or leaderboards if there are no sets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leaderboards"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/leaderboards",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterViewControllerStateLeaderboards"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterViewControllerState.leaderboards",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontrollerstate/leaderboards"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/localPlayerFriendsList": {
      "abstract": [
        {
          "text": "The view controller should present the friends list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localPlayerFriendsList"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/localPlayerFriendsList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterViewControllerStateLocalPlayerFriendsList"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterViewControllerState.localPlayerFriendsList",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontrollerstate/localplayerfriendslist"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/localPlayerProfile": {
      "abstract": [
        {
          "text": "The view controller should present the local player’s profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localPlayerProfile"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/localPlayerProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameCenterViewControllerStateLocalPlayerProfile"
        }
      ],
      "role": "symbol",
      "title": "GKGameCenterViewControllerState.localPlayerProfile",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamecenterviewcontrollerstate/localplayerprofile"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Game-Center-content",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(state:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(leaderboard:playerScope:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(leaderboardID:playerScope:timeScope:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(leaderboardSetID:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(achievementID:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(player:)"
      ],
      "title": "Configuring Game Center content"
    }
  ],
  "topicSections": [
    {
      "anchor": "States",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/default",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/leaderboards",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/achievements",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/challenges",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/localPlayerProfile",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/dashboard",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/localPlayerFriendsList"
      ],
      "title": "States"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKGameCenterViewControllerState"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "States",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/default",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/leaderboards",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/achievements",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/challenges",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/localPlayerProfile",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/dashboard",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewControllerState/localPlayerFriendsList"
              ],
              "title": "States"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Game-Center-content",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(state:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(leaderboard:playerScope:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(leaderboardID:playerScope:timeScope:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(leaderboardSetID:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(achievementID:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController/init(player:)"
              ],
              "title": "Configuring Game Center content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GKGameCenterViewControllerState"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1leaderboards/title",
          "value": "GKGameCenterViewControllerStateLeaderboards"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1leaderboards/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerStateLeaderboards"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewController~1init(leaderboard:playerScope:)/title",
          "value": "initWithLeaderboard:playerScope:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewController~1init(leaderboard:playerScope:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLeaderboard:playerScope:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewController~1init(leaderboardSetID:)/title",
          "value": "initWithLeaderboardSetID:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewController~1init(leaderboardSetID:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLeaderboardSetID:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1dashboard/title",
          "value": "GKGameCenterViewControllerStateDashboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1dashboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerStateDashboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1achievements/title",
          "value": "GKGameCenterViewControllerStateAchievements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1achievements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerStateAchievements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1challenges/title",
          "value": "GKGameCenterViewControllerStateChallenges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1challenges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerStateChallenges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewController~1init(achievementID:)/title",
          "value": "initWithAchievementID:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewController~1init(achievementID:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAchievementID:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewController~1init(state:)/title",
          "value": "initWithState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewController~1init(state:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1default/title",
          "value": "GKGameCenterViewControllerStateDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerStateDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewController~1init(player:)/title",
          "value": "initWithPlayer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewController~1init(player:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPlayer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1localPlayerProfile/title",
          "value": "GKGameCenterViewControllerStateLocalPlayerProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1localPlayerProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerStateLocalPlayerProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState/title",
          "value": "GKGameCenterViewControllerState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewController~1init(leaderboardID:playerScope:timeScope:)/title",
          "value": "initWithLeaderboardID:playerScope:timeScope:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewController~1init(leaderboardID:playerScope:timeScope:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLeaderboardID:playerScope:timeScope:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1localPlayerFriendsList/title",
          "value": "GKGameCenterViewControllerStateLocalPlayerFriendsList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameCenterViewControllerState~1localPlayerFriendsList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameCenterViewControllerStateLocalPlayerFriendsList"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkgamecenterviewcontrollerstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gkgamecenterviewcontrollerstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
