{
  "abstract": [
    {
      "text": "A player’s response to an invitation to join a match.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@GKInviteRecipientResponse",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GKInviteRecipientResponse"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKInviteRecipientResponse"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "GKInviteRecipientResponse"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponse"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse": {
      "abstract": [
        {
          "text": "A player’s response to an invitation to join a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "role": "symbol",
      "title": "GKInviteRecipientResponse",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/accepted": {
      "abstract": [
        {
          "text": "A response when the player accepts the invitation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accepted"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/accepted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponseAccepted"
        }
      ],
      "role": "symbol",
      "title": "GKInviteRecipientResponse.accepted",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/accepted"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/declined": {
      "abstract": [
        {
          "text": "A response when the player rejects the invitation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "declined"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/declined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponseDeclined"
        }
      ],
      "role": "symbol",
      "title": "GKInviteRecipientResponse.declined",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/declined"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/failed": {
      "abstract": [
        {
          "text": "A response when the system fails to deliver the invitation to the player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failed"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/failed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponseFailed"
        }
      ],
      "role": "symbol",
      "title": "GKInviteRecipientResponse.failed",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/failed"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/incompatible": {
      "abstract": [
        {
          "text": "A response when the player isn’t running a compatible version of the game.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incompatible"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/incompatible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponseIncompatible"
        }
      ],
      "role": "symbol",
      "title": "GKInviteRecipientResponse.incompatible",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/incompatible"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/init(rawvalue:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseAccepted": {
      "abstract": [
        {
          "text": "The player accepted the invitation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inviteeResponseAccepted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKInviteRecipientResponse",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseAccepted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteeResponseAccepted"
        }
      ],
      "role": "symbol",
      "title": "inviteeResponseAccepted",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/inviteeresponseaccepted"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseDeclined": {
      "abstract": [
        {
          "text": "The player rejected the invitation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inviteeResponseDeclined"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKInviteRecipientResponse",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseDeclined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteeResponseDeclined"
        }
      ],
      "role": "symbol",
      "title": "inviteeResponseDeclined",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/inviteeresponsedeclined"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseFailed": {
      "abstract": [
        {
          "text": "The invitation was unable to be delivered.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inviteeResponseFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKInviteRecipientResponse",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteeResponseFailed"
        }
      ],
      "role": "symbol",
      "title": "inviteeResponseFailed",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/inviteeresponsefailed"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseIncompatible": {
      "abstract": [
        {
          "text": "The invitee isn’t running a compatible version of your game.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inviteeResponseIncompatible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKInviteRecipientResponse",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseIncompatible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteeResponseIncompatible"
        }
      ],
      "role": "symbol",
      "title": "inviteeResponseIncompatible",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/inviteeresponseincompatible"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseNoAnswer": {
      "abstract": [
        {
          "text": "The invitation timed out without an answer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inviteeResponseNoAnswer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKInviteRecipientResponse",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseNoAnswer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteeResponseNoAnswer"
        }
      ],
      "role": "symbol",
      "title": "inviteeResponseNoAnswer",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/inviteeresponsenoanswer"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseUnableToConnect": {
      "abstract": [
        {
          "text": "The invitee couldn’t be contacted.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inviteeResponseUnableToConnect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKInviteRecipientResponse",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseUnableToConnect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteeResponseUnableToConnect"
        }
      ],
      "role": "symbol",
      "title": "inviteeResponseUnableToConnect",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/inviteeresponseunabletoconnect"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/noAnswer": {
      "abstract": [
        {
          "text": "A response when the invitation times out because the player doesn’t answer it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noAnswer"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/noAnswer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponseNoAnswer"
        }
      ],
      "role": "symbol",
      "title": "GKInviteRecipientResponse.noAnswer",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/noanswer"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/unableToConnect": {
      "abstract": [
        {
          "text": "A response when the system can’t contact the player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unableToConnect"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/unableToConnect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponseUnableToConnect"
        }
      ],
      "role": "symbol",
      "title": "GKInviteRecipientResponse.unableToConnect",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/unabletoconnect"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/inviteMessage": {
      "abstract": [
        {
          "text": "The message sent to other players when the local player invites them to join a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inviteMessage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/inviteMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inviteMessage"
        }
      ],
      "role": "symbol",
      "title": "inviteMessage",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/invitemessage"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipientResponseHandler": {
      "abstract": [
        {
          "text": "A method that handles when a player responds to an invitation to join a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recipientResponseHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKInviteRecipientResponse",
          "text": "GKInviteRecipientResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipientResponseHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recipientResponseHandler"
        }
      ],
      "role": "symbol",
      "title": "recipientResponseHandler",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/recipientresponsehandler"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipients": {
      "abstract": [
        {
          "text": "The players to invite to the match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recipients"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipients",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recipients"
        }
      ],
      "role": "symbol",
      "title": "recipients",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/recipients"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inviting-players",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/inviteMessage",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipients",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipientResponseHandler"
      ],
      "title": "Inviting players"
    }
  ],
  "topicSections": [
    {
      "anchor": "Responses",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/accepted",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/declined",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/failed",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/incompatible",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/unableToConnect",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/noAnswer"
      ],
      "title": "Responses"
    },
    {
      "anchor": "Deprecated-Properties",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseAccepted",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseDeclined",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseFailed",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseIncompatible",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseNoAnswer",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseUnableToConnect"
      ],
      "title": "Deprecated Properties"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKInviteRecipientResponse"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Responses",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/accepted",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/declined",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/failed",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/incompatible",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/unableToConnect",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/noAnswer"
              ],
              "title": "Responses"
            },
            {
              "anchor": "Deprecated-Properties",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseAccepted",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseDeclined",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseFailed",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseIncompatible",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseNoAnswer",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseUnableToConnect"
              ],
              "title": "Deprecated Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inviting-players",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/inviteMessage",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipients",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipientResponseHandler"
              ],
              "title": "Inviting players"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GKInviteRecipientResponse"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1recipients/title",
          "value": "recipients"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1recipients/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recipients"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1inviteMessage/title",
          "value": "inviteMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1inviteMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inviteMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1recipientResponseHandler/title",
          "value": "recipientResponseHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1recipientResponseHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recipientResponseHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseFailed/title",
          "value": "GKInviteeResponseFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteeResponseFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseAccepted/title",
          "value": "GKInviteeResponseAccepted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseAccepted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteeResponseAccepted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1incompatible/title",
          "value": "GKInviteRecipientResponseIncompatible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1incompatible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponseIncompatible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1noAnswer/title",
          "value": "GKInviteRecipientResponseNoAnswer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1noAnswer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponseNoAnswer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse/title",
          "value": "GKInviteRecipientResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1unableToConnect/title",
          "value": "GKInviteRecipientResponseUnableToConnect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1unableToConnect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponseUnableToConnect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseUnableToConnect/title",
          "value": "GKInviteeResponseUnableToConnect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseUnableToConnect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteeResponseUnableToConnect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseIncompatible/title",
          "value": "GKInviteeResponseIncompatible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseIncompatible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteeResponseIncompatible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1failed/title",
          "value": "GKInviteRecipientResponseFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1failed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponseFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseNoAnswer/title",
          "value": "GKInviteeResponseNoAnswer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseNoAnswer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteeResponseNoAnswer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseDeclined/title",
          "value": "GKInviteeResponseDeclined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseDeclined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteeResponseDeclined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1declined/title",
          "value": "GKInviteRecipientResponseDeclined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1declined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponseDeclined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1accepted/title",
          "value": "GKInviteRecipientResponseAccepted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1accepted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponseAccepted"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkinviterecipientresponse"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gkinviterecipientresponse"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
