{
  "abstract": [
    {
      "text": "Possible responses from an invitation to a remote player.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKInviteeResponse"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@GKInviteeResponse",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GKInviteeResponse"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKInviteeResponse"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "GKInviteeResponse"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKInviteeResponse"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@GKInviteRecipientResponse",
              "text": "GKInviteRecipientResponse"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse": {
      "abstract": [
        {
          "text": "A player’s response to an invitation to join a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "role": "symbol",
      "title": "GKInviteRecipientResponse",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseAccepted": {
      "abstract": [
        {
          "text": "The player accepted the invitation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inviteeResponseAccepted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKInviteRecipientResponse",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseAccepted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteeResponseAccepted"
        }
      ],
      "role": "symbol",
      "title": "inviteeResponseAccepted",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/inviteeresponseaccepted"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseDeclined": {
      "abstract": [
        {
          "text": "The player rejected the invitation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inviteeResponseDeclined"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKInviteRecipientResponse",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseDeclined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteeResponseDeclined"
        }
      ],
      "role": "symbol",
      "title": "inviteeResponseDeclined",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/inviteeresponsedeclined"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseFailed": {
      "abstract": [
        {
          "text": "The invitation was unable to be delivered.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inviteeResponseFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKInviteRecipientResponse",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteeResponseFailed"
        }
      ],
      "role": "symbol",
      "title": "inviteeResponseFailed",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/inviteeresponsefailed"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseIncompatible": {
      "abstract": [
        {
          "text": "The invitee isn’t running a compatible version of your game.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inviteeResponseIncompatible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKInviteRecipientResponse",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseIncompatible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteeResponseIncompatible"
        }
      ],
      "role": "symbol",
      "title": "inviteeResponseIncompatible",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/inviteeresponseincompatible"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseNoAnswer": {
      "abstract": [
        {
          "text": "The invitation timed out without an answer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inviteeResponseNoAnswer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKInviteRecipientResponse",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseNoAnswer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteeResponseNoAnswer"
        }
      ],
      "role": "symbol",
      "title": "inviteeResponseNoAnswer",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/inviteeresponsenoanswer"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseUnableToConnect": {
      "abstract": [
        {
          "text": "The invitee couldn’t be contacted.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inviteeResponseUnableToConnect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKInviteRecipientResponse",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseUnableToConnect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteeResponseUnableToConnect"
        }
      ],
      "role": "symbol",
      "title": "inviteeResponseUnableToConnect",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/inviteeresponseunabletoconnect"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteeResponse": {
      "abstract": [
        {
          "text": "Possible responses from an invitation to a remote player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKInviteeResponse"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteeResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteeResponse"
        }
      ],
      "role": "symbol",
      "title": "GKInviteeResponse",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviteeresponse"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/inviteeResponseHandler": {
      "abstract": [
        {
          "text": "Handles when a player responds to an invitation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inviteeResponseHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GKInviteeResponse",
          "text": "GKInviteeResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/inviteeResponseHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inviteeResponseHandler"
        }
      ],
      "role": "symbol",
      "title": "inviteeResponseHandler",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/inviteeresponsehandler"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playersToInvite": {
      "abstract": [
        {
          "text": "A list of player identifiers for players to invite to the match.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playersToInvite"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playersToInvite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playersToInvite"
        }
      ],
      "role": "symbol",
      "title": "playersToInvite",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/playerstoinvite"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/restrictToAutomatch": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether a game uses automatch to find players or the local player invites players.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restrictToAutomatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/restrictToAutomatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "restrictToAutomatch"
        }
      ],
      "role": "symbol",
      "title": "restrictToAutomatch",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/restricttoautomatch"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-methods-and-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/inviteeResponseHandler",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playersToInvite",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/restrictToAutomatch"
      ],
      "title": "Deprecated methods and properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Responses",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseAccepted",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseDeclined",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseFailed",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseIncompatible",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseUnableToConnect",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseNoAnswer"
      ],
      "title": "Responses"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKInviteeResponse"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteeResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteeResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Responses",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseAccepted",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseDeclined",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseFailed",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseIncompatible",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseUnableToConnect",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/inviteeResponseNoAnswer"
              ],
              "title": "Responses"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-methods-and-properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/inviteeResponseHandler",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playersToInvite",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/restrictToAutomatch"
              ],
              "title": "Deprecated methods and properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@GKInviteRecipientResponse",
                    "text": "GKInviteRecipientResponse"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GKInviteeResponse"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseDeclined/title",
          "value": "GKInviteeResponseDeclined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseDeclined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteeResponseDeclined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteeResponse/title",
          "value": "GKInviteeResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteeResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteeResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteeResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteeResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseIncompatible/title",
          "value": "GKInviteeResponseIncompatible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseIncompatible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteeResponseIncompatible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseNoAnswer/title",
          "value": "GKInviteeResponseNoAnswer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseNoAnswer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteeResponseNoAnswer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1inviteeResponseHandler/title",
          "value": "inviteeResponseHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1inviteeResponseHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inviteeResponseHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseFailed/title",
          "value": "GKInviteeResponseFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteeResponseFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseUnableToConnect/title",
          "value": "GKInviteeResponseUnableToConnect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseUnableToConnect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteeResponseUnableToConnect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1playersToInvite/title",
          "value": "playersToInvite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1playersToInvite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playersToInvite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseAccepted/title",
          "value": "GKInviteeResponseAccepted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1inviteeResponseAccepted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteeResponseAccepted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse/title",
          "value": "GKInviteRecipientResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1restrictToAutomatch/title",
          "value": "restrictToAutomatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1restrictToAutomatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "restrictToAutomatch"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkinviteeresponse"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gkinviteeresponse"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
