{
  "abstract": [
    {
      "text": "Review unsupported symbols and their replacements.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/gkleaderboard-deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated symbols"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard": {
      "abstract": [
        {
          "text": "A leaderboard for a game that Game Center stores.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKLeaderboard"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKLeaderboard"
        }
      ],
      "role": "symbol",
      "title": "GKLeaderboard",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/category": {
      "abstract": [
        {
          "text": "The named leaderboard to retrieve information from.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "category"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/category",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "category"
        }
      ],
      "role": "symbol",
      "title": "category",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/category"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/identifier": {
      "abstract": [
        {
          "text": "The named leaderboard to retrieve information from.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/identifier"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/init": {
      "abstract": [
        {
          "text": "Initializes a default leaderboard request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/init",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/init"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/init(playerIDs:)": {
      "abstract": [
        {
          "text": "Initializes a leaderboard request to retrieve the scores of a specific group of players.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "playerIDs"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/init(playerIDs:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPlayerIDs:"
        }
      ],
      "role": "symbol",
      "title": "init(playerIDs:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/init(playerids:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/init(players:)": {
      "abstract": [
        {
          "text": "Initializes a leaderboard request to retrieve the scores of a specific group of players.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "players"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/init(players:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPlayers:"
        }
      ],
      "role": "symbol",
      "title": "init(players:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/init(players:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/isLoading": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the leaderboard object is retrieving scores.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isLoading"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/isLoading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loading"
        }
      ],
      "role": "symbol",
      "title": "isLoading",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/isloading"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadCategories(completionHandler:)": {
      "abstract": [
        {
          "text": "Loads the list of leaderboard categories along with their corresponding localized titles.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadCategories"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?, ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadCategories(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadCategoriesWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "loadCategories(completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/loadcategories(completionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadLeaderboards(completionHandler:)": {
      "abstract": [
        {
          "text": "Loads a list of leaderboards from Game Center.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadLeaderboards"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboard",
          "text": "GKLeaderboard"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadLeaderboards(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadLeaderboardsWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "loadLeaderboards(completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/loadleaderboards(completionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadScores(completionHandler:)": {
      "abstract": [
        {
          "text": "Retrieves a set of scores from Game Center.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadScores"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKScore",
          "text": "GKScore"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadScores(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadScoresWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "loadScores(completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/loadscores(completionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/localPlayerScore": {
      "abstract": [
        {
          "text": "The score that the local player earns.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localPlayerScore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKScore",
          "text": "GKScore"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/localPlayerScore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localPlayerScore"
        }
      ],
      "role": "symbol",
      "title": "localPlayerScore",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/localplayerscore"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/maxRange": {
      "abstract": [
        {
          "text": "The size of the leaderboard.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/maxRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxRange"
        }
      ],
      "role": "symbol",
      "title": "maxRange",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/maxrange"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/playerScope-swift.property": {
      "abstract": [
        {
          "text": "A filter that restricts the search to a subset of the players in Game Center.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerScope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboard",
          "text": "GKLeaderboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKLeaderboardPlayerScope",
          "text": "PlayerScope"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/playerScope-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playerScope"
        }
      ],
      "role": "symbol",
      "title": "playerScope",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/playerscope-swift.property"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/range": {
      "abstract": [
        {
          "text": "The numerical score rankings to return from the search.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/range",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "range"
        }
      ],
      "role": "symbol",
      "title": "range",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/range"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/scores": {
      "abstract": [
        {
          "text": "An array of scores that contains the scores that the search returns.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scores"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKScore",
          "text": "GKScore"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/scores",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scores"
        }
      ],
      "role": "symbol",
      "title": "scores",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/scores"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/setDefault(_:withCompletionHandler:)": {
      "abstract": [
        {
          "text": "Sets the default leaderboard for the local player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDefault"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "withCompletionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/setDefault(_:withCompletionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDefaultLeaderboard:withCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "setDefault(_:withCompletionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/setdefault(_:withcompletionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/timeScope-swift.property": {
      "abstract": [
        {
          "text": "A filter that restricts the search to scores within a specific period of time.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeScope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKLeaderboard",
          "text": "GKLeaderboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKLeaderboardTimeScope",
          "text": "TimeScope"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/timeScope-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeScope"
        }
      ],
      "role": "symbol",
      "title": "timeScope",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboard/timescope-swift.property"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Deprecated-initializers",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/init(playerIDs:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/init(players:)"
      ],
      "title": "Deprecated initializers"
    },
    {
      "anchor": "Deprecated-properties",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/category",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/identifier",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/isLoading",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/localPlayerScore",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/maxRange",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/playerScope-swift.property",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/range",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/scores",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/timeScope-swift.property"
      ],
      "title": "Deprecated properties"
    },
    {
      "anchor": "Deprecated-methods",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/setDefault(_:withCompletionHandler:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadCategories(completionHandler:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadLeaderboards(completionHandler:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadScores(completionHandler:)"
      ],
      "title": "Deprecated methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Deprecated-initializers",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/init",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/init(playerIDs:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/init(players:)"
              ],
              "title": "Deprecated initializers"
            },
            {
              "anchor": "Deprecated-properties",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/category",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/identifier",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/isLoading",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/localPlayerScore",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/maxRange",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/playerScope-swift.property",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/range",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/scores",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/timeScope-swift.property"
              ],
              "title": "Deprecated properties"
            },
            {
              "anchor": "Deprecated-methods",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/setDefault(_:withCompletionHandler:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadCategories(completionHandler:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadLeaderboards(completionHandler:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboard/loadScores(completionHandler:)"
              ],
              "title": "Deprecated methods"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1range/title",
          "value": "range"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1range/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "range"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1playerScope-swift.property/title",
          "value": "playerScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1playerScope-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playerScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1timeScope-swift.property/title",
          "value": "timeScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1timeScope-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1init(players:)/title",
          "value": "initWithPlayers:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1init(players:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPlayers:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1category/title",
          "value": "category"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1category/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "category"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1localPlayerScore/title",
          "value": "localPlayerScore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1localPlayerScore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localPlayerScore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1init(playerIDs:)/title",
          "value": "initWithPlayerIDs:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1init(playerIDs:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPlayerIDs:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1loadScores(completionHandler:)/title",
          "value": "loadScoresWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1loadScores(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadScoresWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1isLoading/title",
          "value": "loading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1isLoading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "loading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1scores/title",
          "value": "scores"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1scores/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scores"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard/title",
          "value": "GKLeaderboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1maxRange/title",
          "value": "maxRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1maxRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1loadCategories(completionHandler:)/title",
          "value": "loadCategoriesWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1loadCategories(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "loadCategoriesWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1setDefault(_:withCompletionHandler:)/title",
          "value": "setDefaultLeaderboard:withCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1setDefault(_:withCompletionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "setDefaultLeaderboard:withCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1loadLeaderboards(completionHandler:)/title",
          "value": "loadLeaderboardsWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboard~1loadLeaderboards(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "loadLeaderboardsWithCompletionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkleaderboard-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gkleaderboard-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
