{
  "abstract": [
    {
      "text": "An object that encapsulates the parameters to create a real-time or turn-based match.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GKMatchRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GKMatchRequest"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKMatchRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "GKMatchRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKMatchRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.gamekit/documentation/GameKit/finding-players-using-matchmaking-rules",
        "doc://com.apple.gamekit/documentation/GameKit/finding-multiple-players-for-a-game",
        "doc://com.apple.gamekit/documentation/GameKit/starting-turn-based-matches-and-passing-turns-between-players",
        "doc://com.apple.gamekit/documentation/GameKit/finding-players-with-similar-skill-levels",
        "doc://com.apple.gamekit/documentation/GameKit/troubleshooting-matchmaking-rules-using-metrics",
        "doc://com.apple.gamekit/documentation/GameKit/assigning-players-to-teams-using-rules"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To request a match, set the properties of the match request, such as the number of players, the invitation message, and whether to use automatch to fill the player slots. You’re required to set the minimum and maximum number of players allowed in the match. Then, pass the match request to the appropriate class, depending on the type of game and whether you implement your own user interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To use the matchmaking user interface that GameKit provides, pass the match request to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchmakerViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class for real-time games, or the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatchmakerViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class for turn-based games. GameKit sends messages to the delegates of these classes when players receive and accept invitations to the match.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you implement your own interface for finding players, pass the match request to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class for real-time games, or the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class for turn-based games. If the player selects the other players to invite in your interface, set the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipients",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/inviteMessage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipientResponseHandler",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties before creating the match.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Matchmaking-using-rules",
          "level": 3,
          "text": "Matchmaking using rules",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can refine the match results and reduce player wait times by configuring matchmaking before you present an interface. You can either find players using matchmaking rules you set up on the server, or find players from a subset of players you specify in the game.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To use matchmaking rules, set the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/queueName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to the queue name that you configure in App Store Connect. Optionally, set ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/properties",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipientProperties",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to game-specific criteria. Players in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipientProperties",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property need to also be in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipients",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property — that is, be a recipient of an invitation. When using matchmaking rules, Game Center ignores the subset that you specify using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playerGroup",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playerAttributes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you set the request’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/minPlayers",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/maxPlayers",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties, use values that are in the rule set’s player range. Otherwise, the default values for these properties are the rule set’s ",
              "type": "text"
            },
            {
              "code": "minPlayers",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "maxPlayers",
              "type": "codeVoice"
            },
            {
              "text": " fields (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingRuleSets",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you don’t use matchmaking rules, you can restrict finding players to a subset of players. Set the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/queueName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", and set the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playerGroup",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playerAttributes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties to specify the subset. Then matchmaking ignores the rules-based ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/properties",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipientProperties",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/GameKit/finding-players-using-matchmaking-rules",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Matchmaking rules are only available for peer-to-peer (",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchType/turnBased",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ") and hosted (",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchType/hosted",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ") match requests.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingRuleSets": {
      "abstract": [
        {
          "text": "Create a rule set to contain matchmaking rules and teams.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingRuleSets",
      "kind": "symbol",
      "role": "symbol",
      "title": "Create a rule set",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingRuleSets"
    },
    "doc://com.apple.documentation/documentation/GameKit/finding-players-using-matchmaking-rules": {
      "abstract": [
        {
          "text": "Create a more customized and optimized gaming experience by using matchmaking rules to find players in a real-time game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GameKit/finding-players-using-matchmaking-rules",
      "kind": "article",
      "role": "article",
      "title": "Finding players using matchmaking rules",
      "type": "topic",
      "url": "/documentation/GameKit/finding-players-using-matchmaking-rules"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInvite": {
      "abstract": [
        {
          "text": "An invitation to join a match sent to the local player from another player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKInvite"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInvite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInvite"
        }
      ],
      "role": "symbol",
      "title": "GKInvite",
      "type": "topic",
      "url": "/documentation/gamekit/gkinvite"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteEventListener": {
      "abstract": [
        {
          "text": "A protocol that handles invite events from Game Center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKInviteEventListener"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteEventListener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteEventListener"
        }
      ],
      "role": "symbol",
      "title": "GKInviteEventListener",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviteeventlistener"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse": {
      "abstract": [
        {
          "text": "A player’s response to an invitation to join a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "role": "symbol",
      "title": "GKInviteRecipientResponse",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteeResponse": {
      "abstract": [
        {
          "text": "Possible responses from an invitation to a remote player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKInviteeResponse"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteeResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteeResponse"
        }
      ],
      "role": "symbol",
      "title": "GKInviteeResponse",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviteeresponse"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatch": {
      "abstract": [
        {
          "text": "A peer-to-peer network between a group of players that sign into Game Center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKMatch"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKMatch"
        }
      ],
      "role": "symbol",
      "title": "GKMatch",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatch"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchProperties": {
      "abstract": [
        {
          "text": "A type for game-specific properties that Game Center uses to find players when using matchmaking rules.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GKMatchProperties"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "GKMatchProperties",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchproperties"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest": {
      "abstract": [
        {
          "text": "An object that encapsulates the parameters to create a real-time or turn-based match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKMatchRequest"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKMatchRequest"
        }
      ],
      "role": "symbol",
      "title": "GKMatchRequest",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/defaultNumberOfPlayers": {
      "abstract": [
        {
          "text": "The default number of players for the match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultNumberOfPlayers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/defaultNumberOfPlayers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultNumberOfPlayers"
        }
      ],
      "role": "symbol",
      "title": "defaultNumberOfPlayers",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/defaultnumberofplayers"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/inviteMessage": {
      "abstract": [
        {
          "text": "The message sent to other players when the local player invites them to join a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inviteMessage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/inviteMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inviteMessage"
        }
      ],
      "role": "symbol",
      "title": "inviteMessage",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/invitemessage"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/inviteeResponseHandler": {
      "abstract": [
        {
          "text": "Handles when a player responds to an invitation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inviteeResponseHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GKInviteeResponse",
          "text": "GKInviteeResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/inviteeResponseHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inviteeResponseHandler"
        }
      ],
      "role": "symbol",
      "title": "inviteeResponseHandler",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/inviteeresponsehandler"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/maxPlayers": {
      "abstract": [
        {
          "text": "The maximum number of players that can join the match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxPlayers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/maxPlayers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxPlayers"
        }
      ],
      "role": "symbol",
      "title": "maxPlayers",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/maxplayers"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/maxPlayersAllowedForMatch(of:)": {
      "abstract": [
        {
          "text": "Returns the maximum number of players allowed in the match request for a given match type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxPlayersAllowedForMatch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKMatchType",
          "text": "GKMatchType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/maxPlayersAllowedForMatch(of:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxPlayersAllowedForMatchOfType:"
        }
      ],
      "role": "symbol",
      "title": "maxPlayersAllowedForMatch(of:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/maxplayersallowedformatch(of:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/minPlayers": {
      "abstract": [
        {
          "text": "The minimum number of players that can join the match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minPlayers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/minPlayers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minPlayers"
        }
      ],
      "role": "symbol",
      "title": "minPlayers",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/minplayers"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playerAttributes": {
      "abstract": [
        {
          "text": "A mask that specifies the role that the local player would like to play in the game.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerAttributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playerAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playerAttributes"
        }
      ],
      "role": "symbol",
      "title": "playerAttributes",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/playerattributes"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playerGroup": {
      "abstract": [
        {
          "text": "A number identifying a subset of players invited to join a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerGroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playerGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playerGroup"
        }
      ],
      "role": "symbol",
      "title": "playerGroup",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/playergroup"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playersToInvite": {
      "abstract": [
        {
          "text": "A list of player identifiers for players to invite to the match.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playersToInvite"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playersToInvite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playersToInvite"
        }
      ],
      "role": "symbol",
      "title": "playersToInvite",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/playerstoinvite"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/properties": {
      "abstract": [
        {
          "text": "The criteria for the local player that Game Center uses to find other players when using matchmaking rules.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "properties"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/properties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "properties"
        }
      ],
      "role": "symbol",
      "title": "properties",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/properties"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/queueName": {
      "abstract": [
        {
          "text": "The name of the queue that Game Center places the match request in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "queueName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/queueName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "queueName"
        }
      ],
      "role": "symbol",
      "title": "queueName",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/queuename"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipientProperties": {
      "abstract": [
        {
          "text": "The criteria for recipients of the match request that Game Center uses to find other players when using matchmaking rules.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recipientProperties"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": " : ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]]?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipientProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recipientProperties"
        }
      ],
      "role": "symbol",
      "title": "recipientProperties",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/recipientproperties"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipientResponseHandler": {
      "abstract": [
        {
          "text": "A method that handles when a player responds to an invitation to join a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recipientResponseHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKInviteRecipientResponse",
          "text": "GKInviteRecipientResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipientResponseHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recipientResponseHandler"
        }
      ],
      "role": "symbol",
      "title": "recipientResponseHandler",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/recipientresponsehandler"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipients": {
      "abstract": [
        {
          "text": "The players to invite to the match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recipients"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipients",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recipients"
        }
      ],
      "role": "symbol",
      "title": "recipients",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/recipients"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/restrictToAutomatch": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether a game uses automatch to find players or the local player invites players.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restrictToAutomatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/restrictToAutomatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "restrictToAutomatch"
        }
      ],
      "role": "symbol",
      "title": "restrictToAutomatch",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/restricttoautomatch"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchType": {
      "abstract": [
        {
          "text": "The kind of match managed by Game Center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKMatchType"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKMatchType"
        }
      ],
      "role": "symbol",
      "title": "GKMatchType",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchtype"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchType/hosted": {
      "abstract": [
        {
          "text": "A match hosted on your private server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hosted"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchType/hosted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKMatchTypeHosted"
        }
      ],
      "role": "symbol",
      "title": "GKMatchType.hosted",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchtype/hosted"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchType/turnBased": {
      "abstract": [
        {
          "text": "A turn-based match hosted by Game Center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "turnBased"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchType/turnBased",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKMatchTypeTurnBased"
        }
      ],
      "role": "symbol",
      "title": "GKMatchType.turnBased",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchtype/turnbased"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker": {
      "abstract": [
        {
          "text": "An object that creates matches with other players without presenting an interface to the players.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKMatchmaker"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKMatchmaker"
        }
      ],
      "role": "symbol",
      "title": "GKMatchmaker",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchmaker"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchmakerViewController": {
      "abstract": [
        {
          "text": "An interface that allows a player to invite other players to a real-time game and automatch to fill any empty slots.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKMatchmakerViewController"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchmakerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKMatchmakerViewController"
        }
      ],
      "role": "symbol",
      "title": "GKMatchmakerViewController",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchmakerviewcontroller"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch": {
      "abstract": [
        {
          "text": "An object that encapsulates the match data for games where players take turns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatch"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatch"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedMatch",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatchmakerViewController": {
      "abstract": [
        {
          "text": "An interface that allows a player to invite other players to a turn-based match and automatch to fill any empty slots.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatchmakerViewController"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatchmakerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatchmakerViewController"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedMatchmakerViewController",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatchmakerviewcontroller"
    },
    "doc://com.apple.gamekit/documentation/GameKit/adding-voice-chat-to-multiplayer-games": {
      "abstract": [
        {
          "text": "Enable players to voice chat with all, or groups of, players in a multiplayer game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/adding-voice-chat-to-multiplayer-games",
      "kind": "article",
      "role": "article",
      "title": "Adding voice chat to multiplayer games",
      "type": "topic",
      "url": "/documentation/gamekit/adding-voice-chat-to-multiplayer-games"
    },
    "doc://com.apple.gamekit/documentation/GameKit/assigning-players-to-teams-using-rules": {
      "abstract": [
        {
          "text": "Set criteria for assigning players to teams in your game using matchmaking rules.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/assigning-players-to-teams-using-rules",
      "kind": "article",
      "role": "article",
      "title": "Assigning players to teams using rules",
      "type": "topic",
      "url": "/documentation/gamekit/assigning-players-to-teams-using-rules"
    },
    "doc://com.apple.gamekit/documentation/GameKit/creating-real-time-games": {
      "abstract": [
        {
          "text": "Develop games where multiple players interact in real time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/creating-real-time-games",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating real-time games",
      "type": "topic",
      "url": "/documentation/gamekit/creating-real-time-games"
    },
    "doc://com.apple.gamekit/documentation/GameKit/exchanging-data-between-players-in-real-time-games": {
      "abstract": [
        {
          "text": "Send data between players in a real-time multiplayer game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/exchanging-data-between-players-in-real-time-games",
      "kind": "article",
      "role": "article",
      "title": "Exchanging data between players in real-time games",
      "type": "topic",
      "url": "/documentation/gamekit/exchanging-data-between-players-in-real-time-games"
    },
    "doc://com.apple.gamekit/documentation/GameKit/finding-multiple-players-for-a-game": {
      "abstract": [
        {
          "text": "Discover and invite other players to participate in a real-time game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/finding-multiple-players-for-a-game",
      "kind": "article",
      "role": "article",
      "title": "Finding multiple players for a game",
      "type": "topic",
      "url": "/documentation/gamekit/finding-multiple-players-for-a-game"
    },
    "doc://com.apple.gamekit/documentation/GameKit/finding-players-using-matchmaking-rules": {
      "abstract": [
        {
          "text": "Create a more customized and optimized gaming experience by using matchmaking rules to find players in a real-time game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/finding-players-using-matchmaking-rules",
      "kind": "article",
      "role": "article",
      "title": "Finding players using matchmaking rules",
      "type": "topic",
      "url": "/documentation/gamekit/finding-players-using-matchmaking-rules"
    },
    "doc://com.apple.gamekit/documentation/GameKit/finding-players-with-similar-skill-levels": {
      "abstract": [
        {
          "text": "Add a rule to find players in a range of skill levels to balance competitive gameplay.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/finding-players-with-similar-skill-levels",
      "kind": "article",
      "role": "article",
      "title": "Finding players with similar skill levels",
      "type": "topic",
      "url": "/documentation/gamekit/finding-players-with-similar-skill-levels"
    },
    "doc://com.apple.gamekit/documentation/GameKit/matchmaking-rules": {
      "abstract": [
        {
          "text": "Game Center applies different type of rules you create in a particular order to find the best matches.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/matchmaking-rules",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Matchmaking rules",
      "type": "topic",
      "url": "/documentation/gamekit/matchmaking-rules"
    },
    "doc://com.apple.gamekit/documentation/GameKit/starting-turn-based-matches-and-passing-turns-between-players": {
      "abstract": [
        {
          "text": "Let Game Center store and forward match data between players in a turn-based game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/starting-turn-based-matches-and-passing-turns-between-players",
      "kind": "article",
      "role": "article",
      "title": "Starting turn-based matches and passing turns between players",
      "type": "topic",
      "url": "/documentation/gamekit/starting-turn-based-matches-and-passing-turns-between-players"
    },
    "doc://com.apple.gamekit/documentation/GameKit/troubleshooting-matchmaking-rules-using-metrics": {
      "abstract": [
        {
          "text": "Investigate issues with Game Center by evaluating your matchmaking rules using metrics endpoints.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/troubleshooting-matchmaking-rules-using-metrics",
      "kind": "article",
      "role": "article",
      "title": "Troubleshooting matchmaking rules using metrics",
      "type": "topic",
      "url": "/documentation/gamekit/troubleshooting-matchmaking-rules-using-metrics"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Real-time-games",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/creating-real-time-games",
        "doc://com.apple.gamekit/documentation/GameKit/finding-multiple-players-for-a-game",
        "doc://com.apple.gamekit/documentation/GameKit/exchanging-data-between-players-in-real-time-games",
        "doc://com.apple.gamekit/documentation/GameKit/adding-voice-chat-to-multiplayer-games",
        "doc://com.apple.gamekit/documentation/GameKit/matchmaking-rules",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchmakerViewController",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteEventListener",
        "doc://com.apple.gamekit/documentation/GameKit/GKInvite",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatch"
      ],
      "title": "Real-time games"
    }
  ],
  "topicSections": [
    {
      "anchor": "Restricting-the-number-of-players",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/maxPlayersAllowedForMatch(of:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchType",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/minPlayers",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/maxPlayers",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/defaultNumberOfPlayers"
      ],
      "title": "Restricting the number of players"
    },
    {
      "anchor": "Inviting-players",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/inviteMessage",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipients",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipientResponseHandler",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse"
      ],
      "title": "Inviting players"
    },
    {
      "anchor": "Matching-players-using-rules",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/queueName",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/properties",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipientProperties"
      ],
      "title": "Matching players using rules"
    },
    {
      "anchor": "Matching-specific-players",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playerGroup",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playerAttributes"
      ],
      "title": "Matching specific players"
    },
    {
      "anchor": "Deprecated-methods-and-properties",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/inviteeResponseHandler",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteeResponse",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playersToInvite",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/restrictToAutomatch"
      ],
      "title": "Deprecated methods and properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKMatchRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Restricting-the-number-of-players",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/maxPlayersAllowedForMatch(of:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchType",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/minPlayers",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/maxPlayers",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/defaultNumberOfPlayers"
              ],
              "title": "Restricting the number of players"
            },
            {
              "anchor": "Inviting-players",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/inviteMessage",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipients",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipientResponseHandler",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse"
              ],
              "title": "Inviting players"
            },
            {
              "anchor": "Matching-players-using-rules",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/queueName",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/properties",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipientProperties",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchProperties"
              ],
              "title": "Matching players using rules"
            },
            {
              "anchor": "Matching-specific-players",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playerGroup",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playerAttributes"
              ],
              "title": "Matching specific players"
            },
            {
              "anchor": "Deprecated-methods-and-properties",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/inviteeResponseHandler",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteeResponse",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/playersToInvite",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/restrictToAutomatch"
              ],
              "title": "Deprecated methods and properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Real-time-games",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/creating-real-time-games",
                "doc://com.apple.gamekit/documentation/GameKit/finding-multiple-players-for-a-game",
                "doc://com.apple.gamekit/documentation/GameKit/exchanging-data-between-players-in-real-time-games",
                "doc://com.apple.gamekit/documentation/GameKit/adding-voice-chat-to-multiplayer-games",
                "doc://com.apple.gamekit/documentation/GameKit/matchmaking-rules",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchmakerViewController",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteEventListener",
                "doc://com.apple.gamekit/documentation/GameKit/GKInvite",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatch"
              ],
              "title": "Real-time games"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GKMatchRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1properties/title",
          "value": "properties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1properties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1queueName/title",
          "value": "queueName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1queueName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "queueName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1maxPlayers/title",
          "value": "maxPlayers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1maxPlayers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxPlayers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1playerGroup/title",
          "value": "playerGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1playerGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playerGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchType~1turnBased/title",
          "value": "GKMatchTypeTurnBased"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchType~1turnBased/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchTypeTurnBased"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchType~1hosted/title",
          "value": "GKMatchTypeHosted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchType~1hosted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchTypeHosted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1restrictToAutomatch/title",
          "value": "restrictToAutomatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1restrictToAutomatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "restrictToAutomatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest/title",
          "value": "GKMatchRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchType/title",
          "value": "GKMatchType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1playersToInvite/title",
          "value": "playersToInvite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1playersToInvite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playersToInvite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1recipientProperties/title",
          "value": "recipientProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1recipientProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recipientProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1inviteeResponseHandler/title",
          "value": "inviteeResponseHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1inviteeResponseHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inviteeResponseHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1playerAttributes/title",
          "value": "playerAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1playerAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playerAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInvite/title",
          "value": "GKInvite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInvite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInvite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInvite/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInvite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse/title",
          "value": "GKInviteRecipientResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1defaultNumberOfPlayers/title",
          "value": "defaultNumberOfPlayers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1defaultNumberOfPlayers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultNumberOfPlayers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatchmakerViewController/title",
          "value": "GKTurnBasedMatchmakerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatchmakerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatchmakerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatchmakerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatchmakerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatch/title",
          "value": "GKMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1inviteMessage/title",
          "value": "inviteMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1inviteMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inviteMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch/title",
          "value": "GKTurnBasedMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteeResponse/title",
          "value": "GKInviteeResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteeResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteeResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteeResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteeResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmakerViewController/title",
          "value": "GKMatchmakerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmakerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchmakerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmakerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchmakerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker/title",
          "value": "GKMatchmaker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchmaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchmaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1minPlayers/title",
          "value": "minPlayers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1minPlayers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minPlayers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteEventListener/title",
          "value": "GKInviteEventListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteEventListener/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteEventListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteEventListener/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteEventListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1maxPlayersAllowedForMatch(of:)/title",
          "value": "maxPlayersAllowedForMatchOfType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1maxPlayersAllowedForMatch(of:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "maxPlayersAllowedForMatchOfType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1recipients/title",
          "value": "recipients"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1recipients/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recipients"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1recipientResponseHandler/title",
          "value": "recipientResponseHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1recipientResponseHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recipientResponseHandler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkmatchrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gkmatchrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
