{
  "abstract": [
    {
      "text": "An object implements the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " protocol to control the behavior of a ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSession",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " object. The delegate is called when other visible peers change their state relative to the session. It is also called to determine whether another peer is allowed to connect to the session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)GKSessionDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GKSessionDelegate"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKSessionDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.10",
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "GKSessionDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKSessionDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKAchievementViewControllerDelegate": {
      "abstract": [
        {
          "text": "An object implementing the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAchievementViewControllerDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol is called when the user dismisses the achievements view controller. Typically, this protocol is implemented by the object in your game that originally displayed the achievements user interface.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKAchievementViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKAchievementViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKAchievementViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "GKAchievementViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/gamekit/gkachievementviewcontrollerdelegate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKChallengeEventHandlerDelegate": {
      "abstract": [
        {
          "text": "You implement the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKChallengeEventHandlerDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " delegate to control how challenges are displayed in your game.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKChallengeEventHandlerDelegate"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKChallengeEventHandlerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKChallengeEventHandlerDelegate"
        }
      ],
      "role": "symbol",
      "title": "GKChallengeEventHandlerDelegate",
      "type": "topic",
      "url": "/documentation/gamekit/gkchallengeeventhandlerdelegate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKChallengesViewControllerDelegate": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKChallengesViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKChallengesViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKChallengesViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "GKChallengesViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/gamekit/gkchallengesviewcontrollerdelegate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKFriendRequestComposeViewController": {
      "abstract": [
        {
          "text": "Your game uses the ",
          "type": "text"
        },
        {
          "code": "GKFriendRequestComposeViewController",
          "type": "codeVoice"
        },
        {
          "text": " class to present a screen that allows the local player to send friend requests to other players.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKFriendRequestComposeViewController"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKFriendRequestComposeViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKFriendRequestComposeViewController"
        }
      ],
      "role": "symbol",
      "title": "GKFriendRequestComposeViewController",
      "type": "topic",
      "url": "/documentation/gamekit/gkfriendrequestcomposeviewcontroller"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKFriendRequestComposeViewControllerDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKFriendRequestComposeViewControllerDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol is implemented by delegates of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKFriendRequestComposeViewController",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class. The delegate is called when the player dismisses the friend request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKFriendRequestComposeViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKFriendRequestComposeViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKFriendRequestComposeViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "GKFriendRequestComposeViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/gamekit/gkfriendrequestcomposeviewcontrollerdelegate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionEventListener": {
      "abstract": [
        {
          "text": "An event listener that handles game session events.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGameSessionEventListener"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionEventListener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKGameSessionEventListener"
        }
      ],
      "role": "symbol",
      "title": "GKGameSessionEventListener",
      "type": "topic",
      "url": "/documentation/gamekit/gkgamesessioneventlistener"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardViewController": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "GKLeaderboardViewController",
          "type": "codeVoice"
        },
        {
          "text": " class provides a standard user interface that displays leaderboard scores to the player. If the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKGameCenterViewController",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class is available, you should use it instead.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKLeaderboardViewController"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKLeaderboardViewController"
        }
      ],
      "role": "symbol",
      "title": "GKLeaderboardViewController",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboardviewcontroller"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardViewControllerDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardViewControllerDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol is implemented by delegates of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardViewController",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class. The delegate is called when the player dismisses the leaderboard.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKLeaderboardViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKLeaderboardViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "GKLeaderboardViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/gamekit/gkleaderboardviewcontrollerdelegate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerController": {
      "abstract": [
        {
          "text": "Provides a standard user interface to allow one iOS device to discover and connect to another.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKPeerPickerController"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKPeerPickerController"
        }
      ],
      "role": "symbol",
      "title": "GKPeerPickerController",
      "type": "topic",
      "url": "/documentation/gamekit/gkpeerpickercontroller"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerControllerDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerControllerDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol is implemented on an object to customize the behavior of a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerController",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object. The delegate is called by the peer picker to create a session object and to respond as the session is configured by the controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKPeerPickerControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKPeerPickerControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "GKPeerPickerControllerDelegate",
      "type": "topic",
      "url": "/documentation/gamekit/gkpeerpickercontrollerdelegate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSession": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSession",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object provides the ability to discover and connect to nearby iOS devices using Bluetooth or Wi-fi.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKSession"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSession"
        }
      ],
      "role": "symbol",
      "title": "GKSession",
      "type": "topic",
      "url": "/documentation/gamekit/gksession"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate": {
      "abstract": [
        {
          "text": "An object implements the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol to control the behavior of a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSession",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object. The delegate is called when other visible peers change their state relative to the session. It is also called to determine whether another peer is allowed to connect to the session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKSessionDelegate"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKSessionDelegate"
        }
      ],
      "role": "symbol",
      "title": "GKSessionDelegate",
      "type": "topic",
      "url": "/documentation/gamekit/gksessiondelegate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate/session(_:connectionWithPeerFailed:withError:)": {
      "abstract": [
        {
          "text": "Received by the delegate when an attempt to connect to another peer failed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKSession",
          "text": "GKSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "connectionWithPeerFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate/session(_:connectionWithPeerFailed:withError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "session:connectionWithPeerFailed:withError:"
        }
      ],
      "role": "symbol",
      "title": "session(_:connectionWithPeerFailed:withError:)",
      "type": "topic",
      "url": "/documentation/gamekit/gksessiondelegate/session(_:connectionwithpeerfailed:witherror:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate/session(_:didFailWithError:)": {
      "abstract": [
        {
          "text": "Sent to the delegate when a serious error has occurred in the session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKSession",
          "text": "GKSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFailWithError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate/session(_:didFailWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "session:didFailWithError:"
        }
      ],
      "role": "symbol",
      "title": "session(_:didFailWithError:)",
      "type": "topic",
      "url": "/documentation/gamekit/gksessiondelegate/session(_:didfailwitherror:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate/session(_:didReceiveConnectionRequestFromPeer:)": {
      "abstract": [
        {
          "text": "Received by the delegate when a remote peer wants to create a connection to the session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKSession",
          "text": "GKSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didReceiveConnectionRequestFromPeer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate/session(_:didReceiveConnectionRequestFromPeer:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "session:didReceiveConnectionRequestFromPeer:"
        }
      ],
      "role": "symbol",
      "title": "session(_:didReceiveConnectionRequestFromPeer:)",
      "type": "topic",
      "url": "/documentation/gamekit/gksessiondelegate/session(_:didreceiveconnectionrequestfrompeer:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate/session(_:peer:didChange:)": {
      "abstract": [
        {
          "text": "Received by the delegate when a peer changes state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKSession",
          "text": "GKSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "peer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@GKPeerConnectionState",
          "text": "GKPeerConnectionState"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate/session(_:peer:didChange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "session:peer:didChangeState:"
        }
      ],
      "role": "symbol",
      "title": "session(_:peer:didChange:)",
      "type": "topic",
      "url": "/documentation/gamekit/gksessiondelegate/session(_:peer:didchange:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandlerDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandlerDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol is implemented by an object to receive notifications events for turn-based matches. All methods are called on the main thread.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKTurnBasedEventHandlerDelegate"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandlerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedEventHandlerDelegate"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedEventHandlerDelegate",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedeventhandlerdelegate"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatClient": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatClient",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol is implemented to control the behavior of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatService",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object. The voice chat client has a number of responsibilities:",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKVoiceChatClient"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatClient"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatClient",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatclient"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatService": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatService",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class allows your application to connect two iOS devices into a voice chat.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKVoiceChatService"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKVoiceChatService"
        }
      ],
      "role": "symbol",
      "title": "GKVoiceChatService",
      "type": "topic",
      "url": "/documentation/gamekit/gkvoicechatservice"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKAchievementViewControllerDelegate",
        "doc://com.apple.gamekit/documentation/GameKit/GKChallengeEventHandlerDelegate",
        "doc://com.apple.gamekit/documentation/GameKit/GKChallengesViewControllerDelegate",
        "doc://com.apple.gamekit/documentation/GameKit/GKFriendRequestComposeViewControllerDelegate",
        "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionEventListener",
        "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardViewControllerDelegate",
        "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerControllerDelegate",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandlerDelegate",
        "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatClient"
      ],
      "title": "Deprecated protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Observing-Changes-to-Peers",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate/session(_:peer:didChange:)"
      ],
      "title": "Observing Changes to Peers"
    },
    {
      "anchor": "Connection-Requests-from-Other-Peers",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate/session(_:didReceiveConnectionRequestFromPeer:)"
      ],
      "title": "Connection Requests from Other Peers"
    },
    {
      "anchor": "Connection-Errors",
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate/session(_:connectionWithPeerFailed:withError:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate/session(_:didFailWithError:)"
      ],
      "title": "Connection Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "7.0",
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "7.0",
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.10",
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKSessionDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Observing-Changes-to-Peers",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate/session(_:peer:didChange:)"
              ],
              "title": "Observing Changes to Peers"
            },
            {
              "anchor": "Connection-Requests-from-Other-Peers",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate/session(_:didReceiveConnectionRequestFromPeer:)"
              ],
              "title": "Connection Requests from Other Peers"
            },
            {
              "anchor": "Connection-Errors",
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate/session(_:connectionWithPeerFailed:withError:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKSessionDelegate/session(_:didFailWithError:)"
              ],
              "title": "Connection Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKAchievementViewControllerDelegate",
                "doc://com.apple.gamekit/documentation/GameKit/GKChallengeEventHandlerDelegate",
                "doc://com.apple.gamekit/documentation/GameKit/GKChallengesViewControllerDelegate",
                "doc://com.apple.gamekit/documentation/GameKit/GKFriendRequestComposeViewControllerDelegate",
                "doc://com.apple.gamekit/documentation/GameKit/GKGameSessionEventListener",
                "doc://com.apple.gamekit/documentation/GameKit/GKLeaderboardViewControllerDelegate",
                "doc://com.apple.gamekit/documentation/GameKit/GKPeerPickerControllerDelegate",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedEventHandlerDelegate",
                "doc://com.apple.gamekit/documentation/GameKit/GKVoiceChatClient"
              ],
              "title": "Deprecated protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GKSessionDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKChallengesViewControllerDelegate/title",
          "value": "GKChallengesViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKChallengesViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKChallengesViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKChallengesViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKChallengesViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSession/title",
          "value": "GKSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionDelegate~1session(_:didFailWithError:)/title",
          "value": "session:didFailWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionDelegate~1session(_:didFailWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "session:didFailWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatService/title",
          "value": "GKVoiceChatService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerPickerController/title",
          "value": "GKPeerPickerController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerPickerController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPeerPickerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerPickerController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPeerPickerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionEventListener/title",
          "value": "GKGameSessionEventListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionEventListener/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameSessionEventListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKGameSessionEventListener/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKGameSessionEventListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatClient/title",
          "value": "GKVoiceChatClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKVoiceChatClient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKVoiceChatClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboardViewControllerDelegate/title",
          "value": "GKLeaderboardViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboardViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboardViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboardViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboardViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAchievementViewControllerDelegate/title",
          "value": "GKAchievementViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAchievementViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAchievementViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKAchievementViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKAchievementViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionDelegate/title",
          "value": "GKSessionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKSessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionDelegate~1session(_:didReceiveConnectionRequestFromPeer:)/title",
          "value": "session:didReceiveConnectionRequestFromPeer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionDelegate~1session(_:didReceiveConnectionRequestFromPeer:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "session:didReceiveConnectionRequestFromPeer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionDelegate~1session(_:peer:didChange:)/title",
          "value": "session:peer:didChangeState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionDelegate~1session(_:peer:didChange:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "session:peer:didChangeState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventHandlerDelegate/title",
          "value": "GKTurnBasedEventHandlerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventHandlerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedEventHandlerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedEventHandlerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedEventHandlerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboardViewController/title",
          "value": "GKLeaderboardViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboardViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboardViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKLeaderboardViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKLeaderboardViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerPickerControllerDelegate/title",
          "value": "GKPeerPickerControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerPickerControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPeerPickerControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKPeerPickerControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPeerPickerControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendRequestComposeViewControllerDelegate/title",
          "value": "GKFriendRequestComposeViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendRequestComposeViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKFriendRequestComposeViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendRequestComposeViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKFriendRequestComposeViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKChallengeEventHandlerDelegate/title",
          "value": "GKChallengeEventHandlerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKChallengeEventHandlerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKChallengeEventHandlerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKChallengeEventHandlerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKChallengeEventHandlerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionDelegate~1session(_:connectionWithPeerFailed:withError:)/title",
          "value": "session:connectionWithPeerFailed:withError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKSessionDelegate~1session(_:connectionWithPeerFailed:withError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "session:connectionWithPeerFailed:withError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendRequestComposeViewController/title",
          "value": "GKFriendRequestComposeViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendRequestComposeViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKFriendRequestComposeViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKFriendRequestComposeViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKFriendRequestComposeViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gksessiondelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gksessiondelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
