{
  "abstract": [
    {
      "text": "Investigate issues with Game Center by evaluating your matchmaking rules using metrics endpoints.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit",
        "doc://com.apple.gamekit/documentation/GameKit/matchmaking-rules"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/troubleshooting-matchmaking-rules-using-metrics"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Troubleshooting matchmaking rules using metrics"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can diagnose problems with your matchmaking rules using the metrics endpoints. You can get matchmaking data at different granularities, such as every 15 minutes for 8 hours, hourly over 24 hours, or daily for 30 days. If Game Center takes too long to find matches or fails to find matches, use the metrics APIs to help troubleshoot your rules.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "View-match-requests-on-the-queue",
          "level": 3,
          "text": "View match requests on the queue",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "First, confirm that your game submits requests to the correct queue using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingQueues-_id_-metrics-matchmakingRequests",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " endpoint. In the query parameters, pass the Game Center details ",
              "type": "text"
            },
            {
              "code": "id",
              "type": "codeVoice"
            },
            {
              "text": " and pass a value for the ",
              "type": "text"
            },
            {
              "code": "granularity",
              "type": "codeVoice"
            },
            {
              "text": " parameter that returns the level of information you want. To get the Game Center detail ",
              "type": "text"
            },
            {
              "code": "id",
              "type": "codeVoice"
            },
            {
              "text": ", use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterDetails",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GET-v1-apps",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " endpoint.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "GET /v1/gameCenterMatchmakingQueues/8fb73d41-1ca1-1cbf-2538-9df424beb10b/metrics/matchmakingRequests?granularity=PT15M"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Parse the match request data in the response. If the ",
              "type": "text"
            },
            {
              "code": "count",
              "type": "codeVoice"
            },
            {
              "text": " field in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GameCenterMatchmakingAppRequestsV1MetricResponse/Data-data.dictionary/DataPoints-data.dictionary/Values-data.dictionary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object isn’t the value you expect, verify that the game submits a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object with the correct value for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/queueName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. Also, check device logs for any errors that may occur when submitting match requests.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "{    ",
            "      “data”: [    ",
            "        {  ",
            "          \"type\": \"gameCenterMatchmakingQueueRequests\",  ",
            "          “dataPoints”: [   ",
            "            {  ",
            "              “start”: “2023-10-05T04:00:00Z”, ",
            "              “end”: “2023-10-05T04:15:00Z”, ",
            "              “values”: {    ",
            "                “averageSecondsInQueue”: 2.9630714285714284, ",
            "                “p95SecondsInQueue”: 3.838, ",
            "                “count”: 14,   ",
            "                “p50SecondsInQueue”: 3.36   ",
            "              }    ",
            "            },",
            "..."
          ],
          "syntax": "json",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To organize the match requests by type (",
              "type": "text"
            },
            {
              "code": "MATCHED",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "CANCELED",
              "type": "codeVoice"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "code": "EXPIRED",
              "type": "codeVoice"
            },
            {
              "text": "), set the ",
              "type": "text"
            },
            {
              "code": "groupBy",
              "type": "codeVoice"
            },
            {
              "text": " query parameter to ",
              "type": "text"
            },
            {
              "code": "result",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "GET /v1/gameCenterMatchmakingQueues/8fb73d41-1ca1-1cbf-2538-9df424beb10b/metrics/matchmakingRequests?granularity=PT15M&groupBy=result"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "It’s common for players to cancel a match request by quitting a game or other compatible match requests to arrive too late to fill empty slots. However, if the amount of canceled and expired match requests exceeds the amount of matched requests, investigate whether there’s a problem with your rules.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "View-match-request-errors",
          "level": 3,
          "text": "View match request errors",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Runtime errors can occur when your game submits a match request. If an error occurs while Game Center evaluates a match request, it may reject it and log an error. To view these types of errors, pass the matchmaking rule ",
              "type": "text"
            },
            {
              "code": "id",
              "type": "codeVoice"
            },
            {
              "text": " and pass a ",
              "type": "text"
            },
            {
              "code": "granularity",
              "type": "codeVoice"
            },
            {
              "text": " query parameter to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingRules-_id_-metrics-matchmakingRuleErrors",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " endpoint.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "GET /v1/gameCenterMatchmakingRules/2b4835c6-d06b-479d-8b0f-dab9d7eb3d11/metrics/matchmakingRuleErrors?granularity=PT15M"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If errors occur, use the testing",
              "type": "text"
            },
            {
              "code": " ",
              "type": "codeVoice"
            },
            {
              "text": "APIs to reproduce the error. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/testing-matchmaking-rules",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, you can verify that the game passes the correct key for game-specific data that your matchmaking rules use in the ",
              "type": "text"
            },
            {
              "code": "GKMatchRequest",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/properties",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipientProperties",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To get the matchmaking rule ",
              "type": "text"
            },
            {
              "code": "id",
              "type": "codeVoice"
            },
            {
              "text": ", use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingRules",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " endpoint.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Check-if-your-rules-are-too-restrictive",
          "level": 3,
          "text": "Check if your rules are too restrictive",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Your matchmaking rules should strike a balance between finding the best players and reducing wait times. Check whether your rules are too restrictive by getting the frequency that your rules reject candidate matches using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingRules-_id_-metrics-matchmakingBooleanRuleResults",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingRules-_id_-metrics-matchmakingNumberRuleResults",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " endpoints. Pass the matchmaking rule ",
              "type": "text"
            },
            {
              "code": "id,",
              "type": "codeVoice"
            },
            {
              "text": " pass a ",
              "type": "text"
            },
            {
              "code": "granularity",
              "type": "codeVoice"
            },
            {
              "text": " query parameter, and to organize the results by type, set the ",
              "type": "text"
            },
            {
              "code": "groupBy",
              "type": "codeVoice"
            },
            {
              "text": " query parameter to ",
              "type": "text"
            },
            {
              "code": "result",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "GET /v1/gameCenterMatchmakingRules/0f0fcbf9-43b6-429d-8c08-fcaf66a52872/metrics/matchmakingBooleanRuleResults?granularity=PT15M&groupBy=result"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If your rules are too restrictive, consider relaxing the criteria over time using a match rule with an age function. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/finding-players-with-similar-skill-levels",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/expressions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in App Store Connect API.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Keep-the-queues-short-and-responsive",
          "level": 3,
          "text": "Keep the queues short and responsive",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you submit too many match requests to one queue, the matchmaking algorithm may struggle to keep up with the requests and fail to find candidate matches, even when they exist in the queue. To avoid this problem, monitor the size of your queue using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingQueues-_id_-metrics-matchmakingQueueSizes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " endpoint. Pass the queue ",
              "type": "text"
            },
            {
              "code": "id",
              "type": "codeVoice"
            },
            {
              "text": " and pass a ",
              "type": "text"
            },
            {
              "code": "granularity",
              "type": "codeVoice"
            },
            {
              "text": " query parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "GET /v1/gameCenterMatchmakingQueues/532ad9c0-1a28-4536-ad57-33213bcc0a29/metrics/matchmakingQueueSizes?granularity=PT15M"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If the algorithm fails to find players as the queue size increases, try adding one or more queues and splitting match requests between them. For best results, keep the number of requests in each queue under 100. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/matchmaking-rules#The-matchmaking-rules-algorithm",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To get the queue ",
              "type": "text"
            },
            {
              "code": "id",
              "type": "codeVoice"
            },
            {
              "text": ", use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingQueues",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " endpoint.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GET-v1-apps": {
      "abstract": [
        {
          "text": "Find and list apps in App Store Connect.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GET-v1-apps",
      "kind": "symbol",
      "role": "symbol",
      "title": "List Apps",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI/GET-v1-apps"
    },
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingQueues-_id_-metrics-matchmakingQueueSizes": {
      "abstract": [
        {
          "text": "Get the time that match requests are in a specific queue.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingQueues-_id_-metrics-matchmakingQueueSizes",
      "kind": "symbol",
      "role": "symbol",
      "title": "Get queue size",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingQueues-_id_-metrics-matchmakingQueueSizes"
    },
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingQueues-_id_-metrics-matchmakingRequests": {
      "abstract": [
        {
          "text": "Get the match requests that a specific queue processes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingQueues-_id_-metrics-matchmakingRequests",
      "kind": "symbol",
      "role": "symbol",
      "title": "Get match request time in queue",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingQueues-_id_-metrics-matchmakingRequests"
    },
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingRules-_id_-metrics-matchmakingBooleanRuleResults": {
      "abstract": [
        {
          "text": "Get the results of a specific matchmaking rule that returns Boolean values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingRules-_id_-metrics-matchmakingBooleanRuleResults",
      "kind": "symbol",
      "role": "symbol",
      "title": "Get Boolean rule results",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingRules-_id_-metrics-matchmakingBooleanRuleResults"
    },
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingRules-_id_-metrics-matchmakingNumberRuleResults": {
      "abstract": [
        {
          "text": "Get the results of a specific matchmaking rule that returns numeric values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingRules-_id_-metrics-matchmakingNumberRuleResults",
      "kind": "symbol",
      "role": "symbol",
      "title": "Get numeric rule results",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingRules-_id_-metrics-matchmakingNumberRuleResults"
    },
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingRules-_id_-metrics-matchmakingRuleErrors": {
      "abstract": [
        {
          "text": "Get errors that occur for a specific matchmaking rule.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingRules-_id_-metrics-matchmakingRuleErrors",
      "kind": "symbol",
      "role": "symbol",
      "title": "Get matchmaking rule errors",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI/GET-v1-gameCenterMatchmakingRules-_id_-metrics-matchmakingRuleErrors"
    },
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GameCenterMatchmakingAppRequestsV1MetricResponse/Data-data.dictionary/DataPoints-data.dictionary/Values-data.dictionary": {
      "abstract": [
        {
          "text": "The values of the data points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "GameCenterMatchmakingAppRequestsV1MetricResponse.Data.DataPoints.Values"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/GameCenterMatchmakingAppRequestsV1MetricResponse/Data-data.dictionary/DataPoints-data.dictionary/Values-data.dictionary",
      "kind": "symbol",
      "role": "symbol",
      "title": "GameCenterMatchmakingAppRequestsV1MetricResponse.Data.DataPoints.Values",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI/GameCenterMatchmakingAppRequestsV1MetricResponse/Data-data.dictionary/DataPoints-data.dictionary/Values-data.dictionary"
    },
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterDetails": {
      "abstract": [
        {
          "text": "Create a Game Center detail for an app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterDetails",
      "kind": "symbol",
      "role": "symbol",
      "title": "Enable Game Center for an app",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI/POST-v1-gameCenterDetails"
    },
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingQueues": {
      "abstract": [
        {
          "text": "Create a queue and add it to a rule set.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingQueues",
      "kind": "symbol",
      "role": "symbol",
      "title": "Create a queue",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingQueues"
    },
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingRules": {
      "abstract": [
        {
          "text": "Add a matchmaking rule to a rule set.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingRules",
      "kind": "symbol",
      "role": "symbol",
      "title": "Create a rule",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI/POST-v1-gameCenterMatchmakingRules"
    },
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI/expressions": {
      "abstract": [
        {
          "text": "Write expressions that query the match requests in a queue to find the best players for a match.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI/expressions",
      "kind": "article",
      "role": "article",
      "title": "Expressions",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI/expressions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest": {
      "abstract": [
        {
          "text": "An object that encapsulates the parameters to create a real-time or turn-based match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKMatchRequest"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKMatchRequest"
        }
      ],
      "role": "symbol",
      "title": "GKMatchRequest",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/properties": {
      "abstract": [
        {
          "text": "The criteria for the local player that Game Center uses to find other players when using matchmaking rules.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "properties"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/properties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "properties"
        }
      ],
      "role": "symbol",
      "title": "properties",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/properties"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/queueName": {
      "abstract": [
        {
          "text": "The name of the queue that Game Center places the match request in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "queueName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/queueName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "queueName"
        }
      ],
      "role": "symbol",
      "title": "queueName",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/queuename"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipientProperties": {
      "abstract": [
        {
          "text": "The criteria for recipients of the match request that Game Center uses to find other players when using matchmaking rules.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recipientProperties"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": " : ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]]?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/recipientProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recipientProperties"
        }
      ],
      "role": "symbol",
      "title": "recipientProperties",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/recipientproperties"
    },
    "doc://com.apple.gamekit/documentation/GameKit/finding-players-with-similar-skill-levels": {
      "abstract": [
        {
          "text": "Add a rule to find players in a range of skill levels to balance competitive gameplay.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/finding-players-with-similar-skill-levels",
      "kind": "article",
      "role": "article",
      "title": "Finding players with similar skill levels",
      "type": "topic",
      "url": "/documentation/gamekit/finding-players-with-similar-skill-levels"
    },
    "doc://com.apple.gamekit/documentation/GameKit/matchmaking-rules": {
      "abstract": [
        {
          "text": "Game Center applies different type of rules you create in a particular order to find the best matches.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/matchmaking-rules",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Matchmaking rules",
      "type": "topic",
      "url": "/documentation/gamekit/matchmaking-rules"
    },
    "doc://com.apple.gamekit/documentation/GameKit/matchmaking-rules#The-matchmaking-rules-algorithm": {
      "abstract": [],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/matchmaking-rules#The-matchmaking-rules-algorithm",
      "kind": "section",
      "title": "The matchmaking rules algorithm",
      "type": "topic",
      "url": "/documentation/gamekit/matchmaking-rules#The-matchmaking-rules-algorithm"
    },
    "doc://com.apple.gamekit/documentation/GameKit/testing-matchmaking-rules": {
      "abstract": [
        {
          "text": "Test your matchmaking rules before you use them in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/testing-matchmaking-rules",
      "kind": "article",
      "role": "article",
      "title": "Testing matchmaking rules",
      "type": "topic",
      "url": "/documentation/gamekit/testing-matchmaking-rules"
    },
    "doc://com.apple.gamekit/documentation/GameKit/testing-rule-sets-with-player-traffic-using-metrics": {
      "abstract": [
        {
          "text": "Get metrics on a new rule set with real match requests before releasing it.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/testing-rule-sets-with-player-traffic-using-metrics",
      "kind": "article",
      "role": "article",
      "title": "Testing rule sets with player traffic using metrics",
      "type": "topic",
      "url": "/documentation/gamekit/testing-rule-sets-with-player-traffic-using-metrics"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Testing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/testing-matchmaking-rules",
        "doc://com.apple.gamekit/documentation/GameKit/testing-rule-sets-with-player-traffic-using-metrics"
      ],
      "title": "Testing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Testing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/testing-matchmaking-rules",
                "doc://com.apple.gamekit/documentation/GameKit/testing-rule-sets-with-player-traffic-using-metrics"
              ],
              "title": "Testing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest/title",
          "value": "GKMatchRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1recipientProperties/title",
          "value": "recipientProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1recipientProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recipientProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1queueName/title",
          "value": "queueName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1queueName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "queueName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1properties/title",
          "value": "properties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1properties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "properties"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/troubleshooting-matchmaking-rules-using-metrics"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/troubleshooting-matchmaking-rules-using-metrics"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
