{
  "abstract": [
    {
      "text": "The battery charge level.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDevice"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDevice/batteryLevel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ICCameraDevice(py)batteryLevel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "batteryLevel"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "batteryLevel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "batteryLevel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "batteryLevel"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value of this property ranges from 0 to 100.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDevice": {
      "abstract": [
        {
          "text": "An object that represents a camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICCameraDevice"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICCameraDevice"
        }
      ],
      "role": "symbol",
      "title": "ICCameraDevice",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevice"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDevice/batteryLevel": {
      "abstract": [
        {
          "text": "The battery charge level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "batteryLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDevice/batteryLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "batteryLevel"
        }
      ],
      "role": "symbol",
      "title": "batteryLevel",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevice/batterylevel"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDevice/batteryLevelAvailable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the battery charge level is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "batteryLevelAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDevice/batteryLevelAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "batteryLevelAvailable"
        }
      ],
      "role": "symbol",
      "title": "batteryLevelAvailable",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameradevice/batterylevelavailable"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-the-Battery-Charge-Level",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDevice/batteryLevelAvailable"
      ],
      "title": "Inspecting the Battery Charge Level"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "batteryLevel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "batteryLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDevice"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-the-Battery-Charge-Level",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraDevice/batteryLevelAvailable"
              ],
              "title": "Inspecting the Battery Charge Level"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "batteryLevel"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDevice~1batteryLevel/title",
          "value": "batteryLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDevice~1batteryLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "batteryLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDevice~1batteryLevelAvailable/title",
          "value": "batteryLevelAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDevice~1batteryLevelAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "batteryLevelAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDevice/title",
          "value": "ICCameraDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraDevice"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/iccameradevice/batterylevel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/iccameradevice/batterylevel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
