{
  "abstract": [
    {
      "text": "The participant’s role is unknown.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkit/documentation/EventKit",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole/unknown"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@EKParticipantRole@EKParticipantRoleUnknown",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unknown"
      }
    ],
    "modules": [
      {
        "name": "EventKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EKParticipantRoleUnknown"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "EKParticipantRole.unknown"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unknown"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkit/documentation/EventKit": {
      "abstract": [
        {
          "text": "Create, view, and edit calendar and reminder events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit",
      "type": "topic",
      "url": "/documentation/eventkit"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole": {
      "abstract": [
        {
          "text": "The participant’s role for an event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKParticipantRole"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantRole"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantRole",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantrole"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole/chair": {
      "abstract": [
        {
          "text": "The participant is the chair of the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chair"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole/chair",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantRoleChair"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantRole.chair",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantrole/chair"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole/nonParticipant": {
      "abstract": [
        {
          "text": "The participant does not have an active role in the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonParticipant"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole/nonParticipant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantRoleNonParticipant"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantRole.nonParticipant",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantrole/nonparticipant"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole/optional": {
      "abstract": [
        {
          "text": "The participant’s attendance is optional.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optional"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole/optional",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantRoleOptional"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantRole.optional",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantrole/optional"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole/required": {
      "abstract": [
        {
          "text": "The participant’s attendance is required.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "required"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole/required",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantRoleRequired"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantRole.required",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantrole/required"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole/unknown": {
      "abstract": [
        {
          "text": "The participant’s role is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantRoleUnknown"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantRole.unknown",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantrole/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole/required",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole/optional",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole/chair",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole/nonParticipant"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "EKParticipantRoleUnknown"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantRoleUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.eventkit/documentation/EventKit",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole/required",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole/optional",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole/chair",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole/nonParticipant"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "EKParticipantRoleUnknown"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantRole~1unknown/title",
          "value": "EKParticipantRoleUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantRole~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantRoleUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantRole~1chair/title",
          "value": "EKParticipantRoleChair"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantRole~1chair/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantRoleChair"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantRole/title",
          "value": "EKParticipantRole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantRole/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantRole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantRole/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantRole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantRole~1nonParticipant/title",
          "value": "EKParticipantRoleNonParticipant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantRole~1nonParticipant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantRoleNonParticipant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantRole~1optional/title",
          "value": "EKParticipantRoleOptional"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantRole~1optional/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantRoleOptional"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantRole~1required/title",
          "value": "EKParticipantRoleRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantRole~1required/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantRoleRequired"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkit/ekparticipantrole/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkit/ekparticipantrole/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
