{
  "abstract": [
    {
      "text": "Returns a value indicating whether the app is authorized to record sensor data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMSensorRecorder"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/CMSensorRecorder/authorizationStatus()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CMSensorRecorder(cm)authorizationStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "authorizationStatus"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CMAuthorizationStatus",
        "text": "CMAuthorizationStatus"
      }
    ],
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "authorizationStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "authorizationStatus()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "authorizationStatus"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMAuthorizationStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CMAuthorizationStatus",
              "text": "CMAuthorizationStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMAuthorizationStatus": {
      "abstract": [
        {
          "text": "The authorization status for motion-related features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "CMAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/coremotion/cmauthorizationstatus"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMSensorRecorder": {
      "abstract": [
        {
          "text": "An object that gathers and retrieves accelerometer data from a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSensorRecorder"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMSensorRecorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSensorRecorder"
        }
      ],
      "role": "symbol",
      "title": "CMSensorRecorder",
      "type": "topic",
      "url": "/documentation/coremotion/cmsensorrecorder"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMSensorRecorder/authorizationStatus()": {
      "abstract": [
        {
          "text": "Returns a value indicating whether the app is authorized to record sensor data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMAuthorizationStatus",
          "text": "CMAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMSensorRecorder/authorizationStatus()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "authorizationStatus()",
      "type": "topic",
      "url": "/documentation/coremotion/cmsensorrecorder/authorizationstatus()"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMSensorRecorder/isAccelerometerRecordingAvailable()": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether accelerometer recording is supported on the current device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAccelerometerRecordingAvailable"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMSensorRecorder/isAccelerometerRecordingAvailable()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isAccelerometerRecordingAvailable"
        }
      ],
      "role": "symbol",
      "title": "isAccelerometerRecordingAvailable()",
      "type": "topic",
      "url": "/documentation/coremotion/cmsensorrecorder/isaccelerometerrecordingavailable()"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMSensorRecorder/isAuthorizedForRecording()": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the app is authorized to record sensor data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAuthorizedForRecording"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMSensorRecorder/isAuthorizedForRecording()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isAuthorizedForRecording"
        }
      ],
      "role": "symbol",
      "title": "isAuthorizedForRecording()",
      "type": "topic",
      "url": "/documentation/coremotion/cmsensorrecorder/isauthorizedforrecording()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Checking-the-Availability-of-Sensor-Recording",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMSensorRecorder/isAccelerometerRecordingAvailable()",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMAuthorizationStatus",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMSensorRecorder/isAuthorizedForRecording()"
      ],
      "title": "Checking the Availability of Sensor Recording"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "authorizationStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "authorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremotion/documentation/CoreMotion",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMSensorRecorder"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Checking-the-Availability-of-Sensor-Recording",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMSensorRecorder/isAccelerometerRecordingAvailable()",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMAuthorizationStatus",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMSensorRecorder/isAuthorizedForRecording()"
              ],
              "title": "Checking the Availability of Sensor Recording"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMAuthorizationStatus",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@CMAuthorizationStatus",
                    "text": "CMAuthorizationStatus"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "authorizationStatus"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMAuthorizationStatus/title",
          "value": "CMAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMAuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMSensorRecorder/title",
          "value": "CMSensorRecorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMSensorRecorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSensorRecorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMSensorRecorder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSensorRecorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMSensorRecorder~1isAccelerometerRecordingAvailable()/title",
          "value": "isAccelerometerRecordingAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMSensorRecorder~1isAccelerometerRecordingAvailable()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "isAccelerometerRecordingAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMSensorRecorder~1isAuthorizedForRecording()/title",
          "value": "isAuthorizedForRecording"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMSensorRecorder~1isAuthorizedForRecording()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "isAuthorizedForRecording"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMSensorRecorder~1authorizationStatus()/title",
          "value": "authorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMSensorRecorder~1authorizationStatus()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "authorizationStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/cmsensorrecorder/authorizationstatus()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremotion/cmsensorrecorder/authorizationstatus()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
