{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iosurface/documentation/IOSurface"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@IOSurfacePropertyKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOSurfacePropertyKey"
      }
    ],
    "modules": [
      {
        "name": "IOSurface"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOSurfacePropertyKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "IOSurfacePropertyKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iosurface/documentation/IOSurface": {
      "abstract": [
        {
          "text": "Share hardware-accelerated buffer data (framebuffers and textures) across multiple processes. Manage image memory more efficiently.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface",
      "kind": "symbol",
      "role": "collection",
      "title": "IOSurface",
      "type": "topic",
      "url": "/documentation/iosurface"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceLockOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceLockOptions"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceLockOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceLockOptions"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceLockOptions",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacelockoptions"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "role": "symbol",
      "title": "IOSurfacePropertyKey",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/allocSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allocSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/allocSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyAllocSize"
        }
      ],
      "role": "symbol",
      "title": "allocSize",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/allocsize"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/allocSizeKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allocSizeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/allocSizeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyAllocSizeKey"
        }
      ],
      "role": "symbol",
      "title": "allocSizeKey",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/allocsizekey"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/bytesPerElement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bytesPerElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/bytesPerElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyBytesPerElement"
        }
      ],
      "role": "symbol",
      "title": "bytesPerElement",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/bytesperelement"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/bytesPerRow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bytesPerRow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/bytesPerRow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyBytesPerRow"
        }
      ],
      "role": "symbol",
      "title": "bytesPerRow",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/bytesperrow"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/cacheMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cacheMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/cacheMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyCacheMode"
        }
      ],
      "role": "symbol",
      "title": "cacheMode",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/cachemode"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/elementHeight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elementHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/elementHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyElementHeight"
        }
      ],
      "role": "symbol",
      "title": "elementHeight",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/elementheight"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/elementWidth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elementWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/elementWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyElementWidth"
        }
      ],
      "role": "symbol",
      "title": "elementWidth",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/elementwidth"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/height": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/height",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyHeight"
        }
      ],
      "role": "symbol",
      "title": "height",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/height"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/init(rawvalue:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/name": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyName"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/name"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/offset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/offset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyOffset"
        }
      ],
      "role": "symbol",
      "title": "offset",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/offset"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/pixelFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/pixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyPixelFormat"
        }
      ],
      "role": "symbol",
      "title": "pixelFormat",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/pixelformat"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/pixelSizeCastingAllowed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelSizeCastingAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/pixelSizeCastingAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyPixelSizeCastingAllowed"
        }
      ],
      "role": "symbol",
      "title": "pixelSizeCastingAllowed",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/pixelsizecastingallowed"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeBase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "planeBase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeBase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyPlaneBase"
        }
      ],
      "role": "symbol",
      "title": "planeBase",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/planebase"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeBytesPerElement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "planeBytesPerElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeBytesPerElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyPlaneBytesPerElement"
        }
      ],
      "role": "symbol",
      "title": "planeBytesPerElement",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/planebytesperelement"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeBytesPerRow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "planeBytesPerRow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeBytesPerRow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyPlaneBytesPerRow"
        }
      ],
      "role": "symbol",
      "title": "planeBytesPerRow",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/planebytesperrow"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeElementHeight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "planeElementHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeElementHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyPlaneElementHeight"
        }
      ],
      "role": "symbol",
      "title": "planeElementHeight",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/planeelementheight"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeElementWidth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "planeElementWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeElementWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyPlaneElementWidth"
        }
      ],
      "role": "symbol",
      "title": "planeElementWidth",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/planeelementwidth"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeHeight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "planeHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyPlaneHeight"
        }
      ],
      "role": "symbol",
      "title": "planeHeight",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/planeheight"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "planeInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyPlaneInfo"
        }
      ],
      "role": "symbol",
      "title": "planeInfo",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/planeinfo"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "planeOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyPlaneOffset"
        }
      ],
      "role": "symbol",
      "title": "planeOffset",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/planeoffset"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "planeSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyPlaneSize"
        }
      ],
      "role": "symbol",
      "title": "planeSize",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/planesize"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeWidth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "planeWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyPlaneWidth"
        }
      ],
      "role": "symbol",
      "title": "planeWidth",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/planewidth"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/width": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfacePropertyKey",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/width",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKeyWidth"
        }
      ],
      "role": "symbol",
      "title": "width",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey/width"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfacePurgeabilityState"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePurgeabilityState"
        }
      ],
      "role": "symbol",
      "title": "IOSurfacePurgeabilityState",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepurgeabilitystate"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceLockOptions",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/allocSizeKey",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/bytesPerElement",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/bytesPerRow",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/cacheMode",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/elementHeight",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/elementWidth",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/height",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/offset",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/pixelFormat",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/pixelSizeCastingAllowed",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeBase",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeBytesPerElement",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeBytesPerRow",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeElementHeight",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeElementWidth",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeHeight",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeInfo",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeOffset",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeSize",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeWidth",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/width",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/allocSize",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/name"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOSurfacePropertyKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iosurface/documentation/IOSurface"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/allocSizeKey",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/bytesPerElement",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/bytesPerRow",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/cacheMode",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/elementHeight",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/elementWidth",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/height",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/offset",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/pixelFormat",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/pixelSizeCastingAllowed",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeBase",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeBytesPerElement",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeBytesPerRow",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeElementHeight",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeElementWidth",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeHeight",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeInfo",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeOffset",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeSize",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/planeWidth",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/width",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/allocSize",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey/name"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceLockOptions",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOSurfacePropertyKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1bytesPerElement/title",
          "value": "IOSurfacePropertyKeyBytesPerElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1bytesPerElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyBytesPerElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeElementWidth/title",
          "value": "IOSurfacePropertyKeyPlaneElementWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeElementWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyPlaneElementWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceLockOptions/title",
          "value": "IOSurfaceLockOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceLockOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceLockOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceLockOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceLockOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1width/title",
          "value": "IOSurfacePropertyKeyWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1width/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1elementHeight/title",
          "value": "IOSurfacePropertyKeyElementHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1elementHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyElementHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeHeight/title",
          "value": "IOSurfacePropertyKeyPlaneHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyPlaneHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1offset/title",
          "value": "IOSurfacePropertyKeyOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1offset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1bytesPerRow/title",
          "value": "IOSurfacePropertyKeyBytesPerRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1bytesPerRow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyBytesPerRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeBase/title",
          "value": "IOSurfacePropertyKeyPlaneBase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeBase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyPlaneBase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeElementHeight/title",
          "value": "IOSurfacePropertyKeyPlaneElementHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeElementHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyPlaneElementHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1pixelFormat/title",
          "value": "IOSurfacePropertyKeyPixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1pixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyPixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1elementWidth/title",
          "value": "IOSurfacePropertyKeyElementWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1elementWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyElementWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1allocSize/title",
          "value": "IOSurfacePropertyKeyAllocSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1allocSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyAllocSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePurgeabilityState/title",
          "value": "IOSurfacePurgeabilityState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePurgeabilityState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePurgeabilityState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePurgeabilityState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePurgeabilityState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeBytesPerElement/title",
          "value": "IOSurfacePropertyKeyPlaneBytesPerElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeBytesPerElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyPlaneBytesPerElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1name/title",
          "value": "IOSurfacePropertyKeyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1cacheMode/title",
          "value": "IOSurfacePropertyKeyCacheMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1cacheMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyCacheMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeBytesPerRow/title",
          "value": "IOSurfacePropertyKeyPlaneBytesPerRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeBytesPerRow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyPlaneBytesPerRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey/title",
          "value": "IOSurfacePropertyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeOffset/title",
          "value": "IOSurfacePropertyKeyPlaneOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyPlaneOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1height/title",
          "value": "IOSurfacePropertyKeyHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1height/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1pixelSizeCastingAllowed/title",
          "value": "IOSurfacePropertyKeyPixelSizeCastingAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1pixelSizeCastingAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyPixelSizeCastingAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1allocSizeKey/title",
          "value": "IOSurfacePropertyAllocSizeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1allocSizeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyAllocSizeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeInfo/title",
          "value": "IOSurfacePropertyKeyPlaneInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyPlaneInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeWidth/title",
          "value": "IOSurfacePropertyKeyPlaneWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyPlaneWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeSize/title",
          "value": "IOSurfacePropertyKeyPlaneSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey~1planeSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKeyPlaneSize"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iosurface/iosurfacepropertykey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iosurface/iosurfacepropertykey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
