{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iosurface/documentation/IOSurface"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-structures"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOSurface"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "IOSurface Structures"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iosurface/documentation/IOSurface": {
      "abstract": [
        {
          "text": "Share hardware-accelerated buffer data (framebuffers and textures) across multiple processes. Manage image memory more efficiently.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface",
      "kind": "symbol",
      "role": "collection",
      "title": "IOSurface",
      "type": "topic",
      "url": "/documentation/iosurface"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceMemoryLedgerFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceMemoryLedgerFlags"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceMemoryLedgerFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceMemoryLedgerFlags"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceMemoryLedgerFlags",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacememoryledgerflags"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceRef": {
      "abstract": [
        {
          "text": "Data type representing an IOSurface opaque object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceRef"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceRef"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceRef",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfaceref"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Constants",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-constants"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Data Types",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-data-types"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Enumerations",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-enumerations"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Functions",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-functions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/iosurface-constants",
        "doc://com.apple.iosurface/documentation/IOSurface/iosurface-functions"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceMemoryLedgerFlags",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceRef"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Structures",
              "identifiers": [
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceMemoryLedgerFlags",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceRef"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iosurface/documentation/IOSurface/iosurface-enumerations",
                "doc://com.apple.iosurface/documentation/IOSurface/iosurface-constants",
                "doc://com.apple.iosurface/documentation/IOSurface/iosurface-functions",
                "doc://com.apple.iosurface/documentation/IOSurface/iosurface-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceMemoryLedgerFlags/title",
          "value": "IOSurfaceMemoryLedgerFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceMemoryLedgerFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceMemoryLedgerFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceMemoryLedgerFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceMemoryLedgerFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceRef/title",
          "value": "IOSurfaceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iosurface/iosurface-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iosurface/iosurface-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
