{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iosurface/documentation/IOSurface"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOSurface"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "IOSurface Data Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iosurface/documentation/IOSurface": {
      "abstract": [
        {
          "text": "Share hardware-accelerated buffer data (framebuffers and textures) across multiple processes. Manage image memory more efficiently.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface",
      "kind": "symbol",
      "role": "collection",
      "title": "IOSurface",
      "type": "topic",
      "url": "/documentation/iosurface"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceID": {
      "abstract": [
        {
          "text": "An IOSurface identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceID"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceID"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceID",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfaceid"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePropertyKey"
        }
      ],
      "role": "symbol",
      "title": "IOSurfacePropertyKey",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepropertykey"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Constants",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-constants"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Enumerations",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-enumerations"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Functions",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-functions"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Structures",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-structures"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/iosurface-structures",
        "doc://com.apple.iosurface/documentation/IOSurface/iosurface-enumerations",
        "doc://com.apple.iosurface/documentation/IOSurface/iosurface-constants",
        "doc://com.apple.iosurface/documentation/IOSurface/iosurface-functions"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceID"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Type-aliases",
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePropertyKey"
      ],
      "title": "Type aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey/title",
          "value": "IOSurfacePropertyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePropertyKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceID/title",
          "value": "IOSurfaceID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iosurface/iosurface-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
