{
  "abstract": [
    {
      "text": "“Unlock” an ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " for reading or writing.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iosurface/documentation/IOSurface"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceUnlock(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@IOSurfaceUnlock",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOSurfaceUnlock"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@IOSurfaceRef",
        "text": "IOSurfaceRef"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@IOSurfaceLockOptions",
        "text": "IOSurfaceLockOptions"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      },
      {
        "kind": "text",
        "text": ">?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@kern_return_t",
        "text": "kern_return_t"
      }
    ],
    "modules": [
      {
        "name": "IOSurface"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOSurfaceUnlock"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "IOSurfaceUnlock(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOSurfaceUnlock"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "buffer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@IOSurfaceRef",
              "text": "IOSurfaceRef"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceLockOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@IOSurfaceLockOptions",
              "text": "IOSurfaceLockOptions"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "seed"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ">?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@kern_return_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@kern_return_t",
              "text": "kern_return_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The term “lock” is used loosely in this context, and is used along with the “unlock” information to put a bound on CPU access to the raw ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the seed parameter is non-NULL, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceLock(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " will store the buffer’s internal modification seed value at the time you made the lock call. You can compare this value to a value returned previously to determine of the contents of the buffer has been changed since the last lock.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In the case of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceUnlock(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the seed value returned will be the internal seed value at the time of the unlock. If you locked the buffer for writing, this value will be incremented as the unlock is performed and the new value will be returned.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "See the kIOSurfaceLock enums for more information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Locking and unlocking an ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " is not a particularly cheap operation, so care should be taken to avoid the calls whenever possible. The seed values are particularly useful for keeping a cache of the buffer contents.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iosurface/documentation/IOSurface": {
      "abstract": [
        {
          "text": "Share hardware-accelerated buffer data (framebuffers and textures) across multiple processes. Manage image memory more efficiently.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface",
      "kind": "symbol",
      "role": "collection",
      "title": "IOSurface",
      "type": "topic",
      "url": "/documentation/iosurface"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface": {
      "abstract": [
        {
          "text": "Data type representing an IOSurface opaque object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurface"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurface"
        }
      ],
      "role": "symbol",
      "title": "IOSurface",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceAlignProperty(_:_:)": {
      "abstract": [
        {
          "text": "Returns the smallest aligned value greater than or equal to the specified value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceAlignProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceAlignProperty(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceAlignProperty"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceAlignProperty(_:_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacealignproperty(_:_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceAllowsPixelSizeCasting(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceAllowsPixelSizeCasting"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceAllowsPixelSizeCasting(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceAllowsPixelSizeCasting"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceAllowsPixelSizeCasting(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfaceallowspixelsizecasting(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCopyAllValues(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceCopyAllValues"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCopyAllValues(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceCopyAllValues"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceCopyAllValues(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecopyallvalues(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCopyValue(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves a value from the dictionary associated with the buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceCopyValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCopyValue(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceCopyValue"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceCopyValue(_:_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecopyvalue(_:_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreate(_:)": {
      "abstract": [
        {
          "text": "Creates a brand new IOSurface object",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceCreate"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceCreate(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecreate(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreateMachPort(_:)": {
      "abstract": [
        {
          "text": "Returns a mach_port_t that holds a reference to the IOSurface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceCreateMachPort"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@mach_port_t",
          "text": "mach_port_t"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreateMachPort(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceCreateMachPort"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceCreateMachPort(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecreatemachport(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreateXPCObject(_:)": {
      "abstract": [
        {
          "text": "Returns an xpc_object_t that holds a reference to the IOSurface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceCreateXPCObject"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreateXPCObject(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceCreateXPCObject"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceCreateXPCObject(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecreatexpcobject(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceDecrementUseCount(_:)": {
      "abstract": [
        {
          "text": "Decrements the per-process usage count for an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceDecrementUseCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceDecrementUseCount(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceDecrementUseCount"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceDecrementUseCount(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacedecrementusecount(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetAllocSize(_:)": {
      "abstract": [
        {
          "text": "Returns the total allocation size of the buffer including all planes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceGetAllocSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetAllocSize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceGetAllocSize"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceGetAllocSize(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacegetallocsize(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBaseAddress(_:)": {
      "abstract": [
        {
          "text": "Returns the address of the first byte of data in a particular buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBaseAddress"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBaseAddress(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBaseAddress"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceGetBaseAddress(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacegetbaseaddress(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBaseAddressOfPlane(_:_:)": {
      "abstract": [
        {
          "text": "Returns the address of the first byte of data in the specified plane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBaseAddressOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBaseAddressOfPlane(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBaseAddressOfPlane"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceGetBaseAddressOfPlane(_:_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacegetbaseaddressofplane(_:_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBitDepthOfComponentOfPlane(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBitDepthOfComponentOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBitDepthOfComponentOfPlane(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBitDepthOfComponentOfPlane"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceGetBitDepthOfComponentOfPlane(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacegetbitdepthofcomponentofplane(_:_:_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBitOffsetOfComponentOfPlane(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBitOffsetOfComponentOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBitOffsetOfComponentOfPlane(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBitOffsetOfComponentOfPlane"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceGetBitOffsetOfComponentOfPlane(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacegetbitoffsetofcomponentofplane(_:_:_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerElement(_:)": {
      "abstract": [
        {
          "text": "Returns the length (in bytes) of each element in a particular buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBytesPerElement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerElement(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBytesPerElement"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceGetBytesPerElement(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacegetbytesperelement(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerElementOfPlane(_:_:)": {
      "abstract": [
        {
          "text": "Returns the size of each element (in bytes) in the specified plane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBytesPerElementOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerElementOfPlane(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBytesPerElementOfPlane"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceGetBytesPerElementOfPlane(_:_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacegetbytesperelementofplane(_:_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceLock(_:_:_:)": {
      "abstract": [
        {
          "text": "“Lock” an IOSurface for reading or writing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceLock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IOSurfaceLockOptions",
          "text": "IOSurfaceLockOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@kern_return_t",
          "text": "kern_return_t"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceLock(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceLock"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceLock(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacelock(_:_:_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceLockOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceLockOptions"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceLockOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceLockOptions"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceLockOptions",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacelockoptions"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceRef": {
      "abstract": [
        {
          "text": "Data type representing an IOSurface opaque object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceRef"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceRef"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceRef",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfaceref"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceUnlock(_:_:_:)": {
      "abstract": [
        {
          "text": "“Unlock” an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for reading or writing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceUnlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IOSurfaceLockOptions",
          "text": "IOSurfaceLockOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@kern_return_t",
          "text": "kern_return_t"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceUnlock(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceUnlock"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceUnlock(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfaceunlock(_:_:_:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@kern_return_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@kern_return_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "kern_return_t",
      "type": "topic",
      "url": "/documentation/kernel/kern_return_t"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceAlignProperty(_:_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceAllowsPixelSizeCasting(_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCopyAllValues(_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCopyValue(_:_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreate(_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreateMachPort(_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreateXPCObject(_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceDecrementUseCount(_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetAllocSize(_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBaseAddress(_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBaseAddressOfPlane(_:_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBitDepthOfComponentOfPlane(_:_:_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBitOffsetOfComponentOfPlane(_:_:_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerElement(_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerElementOfPlane(_:_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOSurfaceUnlock"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceUnlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iosurface/documentation/IOSurface"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceAlignProperty(_:_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceAllowsPixelSizeCasting(_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCopyAllValues(_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCopyValue(_:_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreate(_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreateMachPort(_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreateXPCObject(_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceDecrementUseCount(_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetAllocSize(_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBaseAddress(_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBaseAddressOfPlane(_:_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBitDepthOfComponentOfPlane(_:_:_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBitOffsetOfComponentOfPlane(_:_:_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerElement(_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerElementOfPlane(_:_:)"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@kern_return_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@kern_return_t",
                    "text": "kern_return_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOSurfaceUnlock"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@IOSurfaceRef",
                    "text": "IOSurfaceRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "buffer"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceLockOptions",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@IOSurfaceLockOptions",
                    "text": "IOSurfaceLockOptions"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "options"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "seed"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetAllocSize(_:)/title",
          "value": "IOSurfaceGetAllocSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetAllocSize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceGetAllocSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceRef/title",
          "value": "IOSurfaceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBaseAddress(_:)/title",
          "value": "IOSurfaceGetBaseAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBaseAddress(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceGetBaseAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface/title",
          "value": "IOSurface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCreateXPCObject(_:)/title",
          "value": "IOSurfaceCreateXPCObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCreateXPCObject(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceCreateXPCObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceLock(_:_:_:)/title",
          "value": "IOSurfaceLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceLock(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBytesPerElementOfPlane(_:_:)/title",
          "value": "IOSurfaceGetBytesPerElementOfPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBytesPerElementOfPlane(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceGetBytesPerElementOfPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCopyAllValues(_:)/title",
          "value": "IOSurfaceCopyAllValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCopyAllValues(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceCopyAllValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceDecrementUseCount(_:)/title",
          "value": "IOSurfaceDecrementUseCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceDecrementUseCount(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceDecrementUseCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceLockOptions/title",
          "value": "IOSurfaceLockOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceLockOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceLockOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceLockOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceLockOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCopyValue(_:_:)/title",
          "value": "IOSurfaceCopyValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCopyValue(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceCopyValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceUnlock(_:_:_:)/title",
          "value": "IOSurfaceUnlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceUnlock(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceUnlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBitOffsetOfComponentOfPlane(_:_:_:)/title",
          "value": "IOSurfaceGetBitOffsetOfComponentOfPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBitOffsetOfComponentOfPlane(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceGetBitOffsetOfComponentOfPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBitDepthOfComponentOfPlane(_:_:_:)/title",
          "value": "IOSurfaceGetBitDepthOfComponentOfPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBitDepthOfComponentOfPlane(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceGetBitDepthOfComponentOfPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBytesPerElement(_:)/title",
          "value": "IOSurfaceGetBytesPerElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBytesPerElement(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceGetBytesPerElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceAllowsPixelSizeCasting(_:)/title",
          "value": "IOSurfaceAllowsPixelSizeCasting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceAllowsPixelSizeCasting(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceAllowsPixelSizeCasting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCreateMachPort(_:)/title",
          "value": "IOSurfaceCreateMachPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCreateMachPort(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceCreateMachPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCreate(_:)/title",
          "value": "IOSurfaceCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCreate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBaseAddressOfPlane(_:_:)/title",
          "value": "IOSurfaceGetBaseAddressOfPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBaseAddressOfPlane(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceGetBaseAddressOfPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceAlignProperty(_:_:)/title",
          "value": "IOSurfaceAlignProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceAlignProperty(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceAlignProperty"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iosurface/iosurfaceunlock(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iosurface/iosurfaceunlock(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
