{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iosurface/documentation/IOSurface"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOSurface"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "IOSurface Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd",
      "kind": "article",
      "role": "article",
      "title": "CFNumber",
      "type": "topic",
      "url": "/documentation/corefoundation/cfnumber-rjd"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iosurface/documentation/IOSurface": {
      "abstract": [
        {
          "text": "Share hardware-accelerated buffer data (framebuffers and textures) across multiple processes. Manage image memory more efficiently.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface",
      "kind": "symbol",
      "role": "collection",
      "title": "IOSurface",
      "type": "topic",
      "url": "/documentation/iosurface"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSFC_DEPRECATED_MSG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOSFC_DEPRECATED_MSG"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSFC_DEPRECATED_MSG",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOSFC_DEPRECATED_MSG",
      "type": "topic",
      "url": "/documentation/iosurface/iosfc_deprecated_msg"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSFC_IOS_DEPRECATED_MSG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOSFC_IOS_DEPRECATED_MSG"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSFC_IOS_DEPRECATED_MSG",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOSFC_IOS_DEPRECATED_MSG",
      "type": "topic",
      "url": "/documentation/iosurface/iosfc_ios_deprecated_msg"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSFC_SWIFT_NAME": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOSFC_SWIFT_NAME"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSFC_SWIFT_NAME",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOSFC_SWIFT_NAME",
      "type": "topic",
      "url": "/documentation/iosurface/iosfc_swift_name"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Data Types",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-data-types"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Enumerations",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-enumerations"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Functions",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-functions"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Structures",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-structures"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceAllocSize": {
      "abstract": [
        {
          "text": "CFNumber of the total allocation size of the buffer including all planes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceAllocSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceAllocSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceAllocSize"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceAllocSize",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceallocsize"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerElement": {
      "abstract": [
        {
          "text": "CFNumber for the total number of bytes in an element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceBytesPerElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceBytesPerElement"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceBytesPerElement",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacebytesperelement"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerRow": {
      "abstract": [
        {
          "text": "CFNumber for the bytes per row of the buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceBytesPerRow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerRow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceBytesPerRow"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceBytesPerRow",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacebytesperrow"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCacheMode": {
      "abstract": [
        {
          "text": "CFNumber for the CPU cache mode to be used for the allocation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceCacheMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCacheMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceCacheMode"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceCacheMode",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacecachemode"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceColorSpace": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceColorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceColorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceColorSpace"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceColorSpace",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacecolorspace"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementHeight": {
      "abstract": [
        {
          "text": "CFNumber for how many pixels high each element is.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceElementHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceElementHeight"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceElementHeight",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceelementheight"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementWidth": {
      "abstract": [
        {
          "text": "CFNumber for how many pixels wide each element is.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceElementWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceElementWidth"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceElementWidth",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceelementwidth"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceHeight": {
      "abstract": [
        {
          "text": "CFNumber for the height of the IOSurface buffer in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceHeight"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceHeight",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceheight"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceICCProfile": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceICCProfile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceICCProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceICCProfile"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceICCProfile",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceiccprofile"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceIsGlobal": {
      "abstract": [
        {
          "text": "CFBoolean If true, the IOSurface may be looked up by any task in the system by its ID.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceIsGlobal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceIsGlobal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceIsGlobal"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceIsGlobal",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceisglobal"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceName"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceName",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacename"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceOffset": {
      "abstract": [
        {
          "text": "CFNumber for the starting offset into the buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceOffset"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceOffset",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceoffset"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelFormat": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " that stores the traditional macOS buffer format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePixelFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePixelFormat"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePixelFormat",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacepixelformat"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelSizeCastingAllowed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePixelSizeCastingAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelSizeCastingAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePixelSizeCastingAllowed"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePixelSizeCastingAllowed",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacepixelsizecastingallowed"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBase": {
      "abstract": [
        {
          "text": "CFNumber for the base offset into the buffer for this plane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneBase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneBase"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePlaneBase",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceplanebase"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBitsPerElement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneBitsPerElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBitsPerElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneBitsPerElement"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePlaneBitsPerElement",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceplanebitsperelement"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBytesPerElement": {
      "abstract": [
        {
          "text": "CFNumber for the bytes per element of this plane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneBytesPerElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBytesPerElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneBytesPerElement"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePlaneBytesPerElement",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceplanebytesperelement"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBytesPerRow": {
      "abstract": [
        {
          "text": "CFNumber for the bytes per row of this plane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneBytesPerRow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBytesPerRow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneBytesPerRow"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePlaneBytesPerRow",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceplanebytesperrow"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentBitDepths": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneComponentBitDepths"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentBitDepths",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneComponentBitDepths"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePlaneComponentBitDepths",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceplanecomponentbitdepths"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentBitOffsets": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneComponentBitOffsets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentBitOffsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneComponentBitOffsets"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePlaneComponentBitOffsets",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceplanecomponentbitoffsets"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentNames": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneComponentNames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneComponentNames"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePlaneComponentNames",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceplanecomponentnames"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentRanges": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneComponentRanges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentRanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneComponentRanges"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePlaneComponentRanges",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceplanecomponentranges"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentTypes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneComponentTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneComponentTypes"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePlaneComponentTypes",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceplanecomponenttypes"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneElementHeight": {
      "abstract": [
        {
          "text": "CFNumber for the element height of this plane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneElementHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneElementHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneElementHeight"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePlaneElementHeight",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceplaneelementheight"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneElementWidth": {
      "abstract": [
        {
          "text": "CFNumber for the element width of this plane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneElementWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneElementWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneElementWidth"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePlaneElementWidth",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceplaneelementwidth"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneHeight": {
      "abstract": [
        {
          "text": "CFNumber for the height of this plane in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneHeight"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePlaneHeight",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceplaneheight"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneInfo": {
      "abstract": [
        {
          "text": "CFArray describing each image plane in the buffer as a CFDictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneInfo"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePlaneInfo",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceplaneinfo"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneOffset": {
      "abstract": [
        {
          "text": "CFNumber for the offset into the buffer for this plane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneOffset"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePlaneOffset",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceplaneoffset"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneSize": {
      "abstract": [
        {
          "text": "CFNumber for the total data size of this plane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneSize"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePlaneSize",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceplanesize"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneWidth": {
      "abstract": [
        {
          "text": "CFNumber for the width of this plane in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneWidth"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePlaneWidth",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceplanewidth"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceSubsampling": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceSubsampling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceSubsampling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceSubsampling"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceSubsampling",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacesubsampling"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceSuccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceSuccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceSuccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceSuccess"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceSuccess",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacesuccess"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceWidth": {
      "abstract": [
        {
          "text": "CFNumber for the width of the IOSurface buffer in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceWidth"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceWidth",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacewidth"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/iosurface-structures",
        "doc://com.apple.iosurface/documentation/IOSurface/iosurface-functions"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceAllocSize",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerElement",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerRow",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCacheMode",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceColorSpace",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementHeight",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementWidth",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceHeight",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceICCProfile",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceIsGlobal",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceName",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceOffset",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelFormat",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelSizeCastingAllowed",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBase",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBitsPerElement",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBytesPerElement",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBytesPerRow",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentBitDepths",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentBitOffsets",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentNames",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentRanges",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentTypes",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneElementHeight",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneElementWidth",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneHeight",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneInfo",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneOffset",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneSize",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneWidth",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceSubsampling",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceSuccess",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceWidth"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceAllocSize",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerElement",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerRow",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCacheMode",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceColorSpace",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementHeight",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementWidth",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceHeight",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceICCProfile",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceIsGlobal",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceName",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceOffset",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelFormat",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelSizeCastingAllowed",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBase",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBitsPerElement",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBytesPerElement",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBytesPerRow",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentBitDepths",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentBitOffsets",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentNames",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentRanges",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneComponentTypes",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneElementHeight",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneElementWidth",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneHeight",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneInfo",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneOffset",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneSize",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneWidth",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceSubsampling",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceSuccess",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceWidth"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.iosurface/documentation/IOSurface/IOSFC_DEPRECATED_MSG",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSFC_IOS_DEPRECATED_MSG",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSFC_SWIFT_NAME"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iosurface/documentation/IOSurface/iosurface-structures",
                "doc://com.apple.iosurface/documentation/IOSurface/iosurface-enumerations",
                "doc://com.apple.iosurface/documentation/IOSurface/iosurface-functions",
                "doc://com.apple.iosurface/documentation/IOSurface/iosurface-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBitsPerElement/title",
          "value": "kIOSurfacePlaneBitsPerElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBitsPerElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePlaneBitsPerElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceSubsampling/title",
          "value": "kIOSurfaceSubsampling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceSubsampling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceSubsampling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceElementHeight/title",
          "value": "kIOSurfaceElementHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceElementHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceElementHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceName/title",
          "value": "kIOSurfaceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneComponentBitDepths/title",
          "value": "kIOSurfacePlaneComponentBitDepths"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneComponentBitDepths/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePlaneComponentBitDepths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceBytesPerElement/title",
          "value": "kIOSurfaceBytesPerElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceBytesPerElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceBytesPerElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceIsGlobal/title",
          "value": "kIOSurfaceIsGlobal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceIsGlobal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceIsGlobal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceHeight/title",
          "value": "kIOSurfaceHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneComponentRanges/title",
          "value": "kIOSurfacePlaneComponentRanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneComponentRanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePlaneComponentRanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceBytesPerRow/title",
          "value": "kIOSurfaceBytesPerRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceBytesPerRow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceBytesPerRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceCacheMode/title",
          "value": "kIOSurfaceCacheMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceCacheMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceCacheMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePixelFormat/title",
          "value": "kIOSurfacePixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneInfo/title",
          "value": "kIOSurfacePlaneInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePlaneInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceColorSpace/title",
          "value": "kIOSurfaceColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceColorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneHeight/title",
          "value": "kIOSurfacePlaneHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePlaneHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBase/title",
          "value": "kIOSurfacePlaneBase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePlaneBase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneOffset/title",
          "value": "kIOSurfacePlaneOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePlaneOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePixelSizeCastingAllowed/title",
          "value": "kIOSurfacePixelSizeCastingAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePixelSizeCastingAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePixelSizeCastingAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneComponentTypes/title",
          "value": "kIOSurfacePlaneComponentTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneComponentTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePlaneComponentTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBytesPerElement/title",
          "value": "kIOSurfacePlaneBytesPerElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBytesPerElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePlaneBytesPerElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneSize/title",
          "value": "kIOSurfacePlaneSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePlaneSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneElementHeight/title",
          "value": "kIOSurfacePlaneElementHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneElementHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePlaneElementHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneWidth/title",
          "value": "kIOSurfacePlaneWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePlaneWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneComponentNames/title",
          "value": "kIOSurfacePlaneComponentNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneComponentNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePlaneComponentNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceElementWidth/title",
          "value": "kIOSurfaceElementWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceElementWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceElementWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceICCProfile/title",
          "value": "kIOSurfaceICCProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceICCProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceICCProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceOffset/title",
          "value": "kIOSurfaceOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceAllocSize/title",
          "value": "kIOSurfaceAllocSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceAllocSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceAllocSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneComponentBitOffsets/title",
          "value": "kIOSurfacePlaneComponentBitOffsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneComponentBitOffsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePlaneComponentBitOffsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneElementWidth/title",
          "value": "kIOSurfacePlaneElementWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneElementWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePlaneElementWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceSuccess/title",
          "value": "kIOSurfaceSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceSuccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBytesPerRow/title",
          "value": "kIOSurfacePlaneBytesPerRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBytesPerRow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePlaneBytesPerRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceWidth/title",
          "value": "kIOSurfaceWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceWidth"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iosurface/iosurface-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iosurface/iosurface-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
