{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iosurface/documentation/IOSurface"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOSurface"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "IOSurface Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iosurface/documentation/IOSurface": {
      "abstract": [
        {
          "text": "Share hardware-accelerated buffer data (framebuffers and textures) across multiple processes. Manage image memory more efficiently.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface",
      "kind": "symbol",
      "role": "collection",
      "title": "IOSurface",
      "type": "topic",
      "url": "/documentation/iosurface"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceComponentName"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceComponentName"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceComponentName",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecomponentname"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceComponentRange"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceComponentRange"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceComponentRange",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecomponentrange"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceComponentType"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceComponentType"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceComponentType",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecomponenttype"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceMemoryLedgerFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceMemoryLedgerFlags"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceMemoryLedgerFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceMemoryLedgerFlags"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceMemoryLedgerFlags",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacememoryledgerflags"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceMemoryLedgerTags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceMemoryLedgerTags"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceMemoryLedgerTags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceMemoryLedgerTags"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceMemoryLedgerTags",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacememoryledgertags"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceSubsampling"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceSubsampling"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceSubsampling",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacesubsampling"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Constants",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-constants"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Data Types",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-data-types"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Functions",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-functions"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/iosurface-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/iosurface-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOSurface Structures",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface-structures"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/iosurface-structures",
        "doc://com.apple.iosurface/documentation/IOSurface/iosurface-constants",
        "doc://com.apple.iosurface/documentation/IOSurface/iosurface-functions",
        "doc://com.apple.iosurface/documentation/IOSurface/iosurface-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentRange",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentType",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceMemoryLedgerFlags",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceMemoryLedgerTags",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceSubsampling"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceSubsampling/title",
          "value": "IOSurfaceSubsampling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceSubsampling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceSubsampling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceSubsampling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceSubsampling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceMemoryLedgerTags/title",
          "value": "IOSurfaceMemoryLedgerTags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceMemoryLedgerTags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceMemoryLedgerTags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceMemoryLedgerTags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceMemoryLedgerTags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceMemoryLedgerFlags/title",
          "value": "IOSurfaceMemoryLedgerFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceMemoryLedgerFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceMemoryLedgerFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceMemoryLedgerFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceMemoryLedgerFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentType/title",
          "value": "IOSurfaceComponentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceComponentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceComponentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentRange/title",
          "value": "IOSurfaceComponentRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceComponentRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceComponentRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName/title",
          "value": "IOSurfaceComponentName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceComponentName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceComponentName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iosurface/iosurface-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
