{
  "abstract": [
    {
      "text": "Returns the total allocation size of the buffer including all planes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iosurface/documentation/IOSurface"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetAllocSize(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@IOSurfaceGetAllocSize",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOSurfaceGetAllocSize"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@IOSurfaceRef",
        "text": "IOSurfaceRef"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOSurface"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOSurfaceGetAllocSize"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "IOSurfaceGetAllocSize(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOSurfaceGetAllocSize"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "buffer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@IOSurfaceRef",
              "text": "IOSurfaceRef"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns 0 if buffer is invalid.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iosurface/documentation/IOSurface": {
      "abstract": [
        {
          "text": "Share hardware-accelerated buffer data (framebuffers and textures) across multiple processes. Manage image memory more efficiently.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface",
      "kind": "symbol",
      "role": "collection",
      "title": "IOSurface",
      "type": "topic",
      "url": "/documentation/iosurface"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurface": {
      "abstract": [
        {
          "text": "Data type representing an IOSurface opaque object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurface"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurface"
        }
      ],
      "role": "symbol",
      "title": "IOSurface",
      "type": "topic",
      "url": "/documentation/iosurface/iosurface"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceAlignProperty(_:_:)": {
      "abstract": [
        {
          "text": "Returns the smallest aligned value greater than or equal to the specified value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceAlignProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceAlignProperty(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceAlignProperty"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceAlignProperty(_:_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacealignproperty(_:_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceAllowsPixelSizeCasting(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceAllowsPixelSizeCasting"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceAllowsPixelSizeCasting(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceAllowsPixelSizeCasting"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceAllowsPixelSizeCasting(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfaceallowspixelsizecasting(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCopyAllValues(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceCopyAllValues"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCopyAllValues(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceCopyAllValues"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceCopyAllValues(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecopyallvalues(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCopyValue(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves a value from the dictionary associated with the buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceCopyValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCopyValue(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceCopyValue"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceCopyValue(_:_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecopyvalue(_:_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreate(_:)": {
      "abstract": [
        {
          "text": "Creates a brand new IOSurface object",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceCreate"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceCreate(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecreate(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreateMachPort(_:)": {
      "abstract": [
        {
          "text": "Returns a mach_port_t that holds a reference to the IOSurface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceCreateMachPort"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@mach_port_t",
          "text": "mach_port_t"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreateMachPort(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceCreateMachPort"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceCreateMachPort(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecreatemachport(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreateXPCObject(_:)": {
      "abstract": [
        {
          "text": "Returns an xpc_object_t that holds a reference to the IOSurface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceCreateXPCObject"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreateXPCObject(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceCreateXPCObject"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceCreateXPCObject(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecreatexpcobject(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceDecrementUseCount(_:)": {
      "abstract": [
        {
          "text": "Decrements the per-process usage count for an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurface",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceDecrementUseCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceDecrementUseCount(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceDecrementUseCount"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceDecrementUseCount(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacedecrementusecount(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetAllocSize(_:)": {
      "abstract": [
        {
          "text": "Returns the total allocation size of the buffer including all planes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceGetAllocSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetAllocSize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceGetAllocSize"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceGetAllocSize(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacegetallocsize(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBaseAddress(_:)": {
      "abstract": [
        {
          "text": "Returns the address of the first byte of data in a particular buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBaseAddress"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBaseAddress(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBaseAddress"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceGetBaseAddress(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacegetbaseaddress(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBaseAddressOfPlane(_:_:)": {
      "abstract": [
        {
          "text": "Returns the address of the first byte of data in the specified plane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBaseAddressOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBaseAddressOfPlane(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBaseAddressOfPlane"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceGetBaseAddressOfPlane(_:_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacegetbaseaddressofplane(_:_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBitDepthOfComponentOfPlane(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBitDepthOfComponentOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBitDepthOfComponentOfPlane(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBitDepthOfComponentOfPlane"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceGetBitDepthOfComponentOfPlane(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacegetbitdepthofcomponentofplane(_:_:_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBitOffsetOfComponentOfPlane(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBitOffsetOfComponentOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBitOffsetOfComponentOfPlane(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBitOffsetOfComponentOfPlane"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceGetBitOffsetOfComponentOfPlane(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacegetbitoffsetofcomponentofplane(_:_:_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerElement(_:)": {
      "abstract": [
        {
          "text": "Returns the length (in bytes) of each element in a particular buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBytesPerElement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerElement(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBytesPerElement"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceGetBytesPerElement(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacegetbytesperelement(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerElementOfPlane(_:_:)": {
      "abstract": [
        {
          "text": "Returns the size of each element (in bytes) in the specified plane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBytesPerElementOfPlane"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerElementOfPlane(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBytesPerElementOfPlane"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceGetBytesPerElementOfPlane(_:_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacegetbytesperelementofplane(_:_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerRow(_:)": {
      "abstract": [
        {
          "text": "Returns the length (in bytes) of each row in a particular buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBytesPerRow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOSurfaceRef",
          "text": "IOSurfaceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerRow(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceGetBytesPerRow"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceGetBytesPerRow(_:)",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacegetbytesperrow(_:)"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceRef": {
      "abstract": [
        {
          "text": "Data type representing an IOSurface opaque object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceRef"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceRef"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceRef",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfaceref"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceAlignProperty(_:_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceAllowsPixelSizeCasting(_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCopyAllValues(_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCopyValue(_:_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreate(_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreateMachPort(_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreateXPCObject(_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceDecrementUseCount(_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBaseAddress(_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBaseAddressOfPlane(_:_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBitDepthOfComponentOfPlane(_:_:_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBitOffsetOfComponentOfPlane(_:_:_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerElement(_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerElementOfPlane(_:_:)",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerRow(_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOSurfaceGetAllocSize"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceGetAllocSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iosurface/documentation/IOSurface"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceAlignProperty(_:_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceAllowsPixelSizeCasting(_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCopyAllValues(_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCopyValue(_:_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreate(_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreateMachPort(_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceCreateXPCObject(_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceDecrementUseCount(_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBaseAddress(_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBaseAddressOfPlane(_:_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBitDepthOfComponentOfPlane(_:_:_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBitOffsetOfComponentOfPlane(_:_:_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerElement(_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerElementOfPlane(_:_:)",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceGetBytesPerRow(_:)"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@size_t",
                    "text": "size_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOSurfaceGetAllocSize"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@IOSurfaceRef",
                    "text": "IOSurfaceRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "buffer"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "Returns 0 if buffer is invalid.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceAlignProperty(_:_:)/title",
          "value": "IOSurfaceAlignProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceAlignProperty(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceAlignProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceAllowsPixelSizeCasting(_:)/title",
          "value": "IOSurfaceAllowsPixelSizeCasting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceAllowsPixelSizeCasting(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceAllowsPixelSizeCasting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBytesPerElementOfPlane(_:_:)/title",
          "value": "IOSurfaceGetBytesPerElementOfPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBytesPerElementOfPlane(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceGetBytesPerElementOfPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface/title",
          "value": "IOSurface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurface/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCreateXPCObject(_:)/title",
          "value": "IOSurfaceCreateXPCObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCreateXPCObject(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceCreateXPCObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBaseAddressOfPlane(_:_:)/title",
          "value": "IOSurfaceGetBaseAddressOfPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBaseAddressOfPlane(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceGetBaseAddressOfPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBitOffsetOfComponentOfPlane(_:_:_:)/title",
          "value": "IOSurfaceGetBitOffsetOfComponentOfPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBitOffsetOfComponentOfPlane(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceGetBitOffsetOfComponentOfPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetAllocSize(_:)/title",
          "value": "IOSurfaceGetAllocSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetAllocSize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceGetAllocSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCreate(_:)/title",
          "value": "IOSurfaceCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCreate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBytesPerRow(_:)/title",
          "value": "IOSurfaceGetBytesPerRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBytesPerRow(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceGetBytesPerRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceDecrementUseCount(_:)/title",
          "value": "IOSurfaceDecrementUseCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceDecrementUseCount(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceDecrementUseCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCopyAllValues(_:)/title",
          "value": "IOSurfaceCopyAllValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCopyAllValues(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceCopyAllValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBytesPerElement(_:)/title",
          "value": "IOSurfaceGetBytesPerElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBytesPerElement(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceGetBytesPerElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCreateMachPort(_:)/title",
          "value": "IOSurfaceCreateMachPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCreateMachPort(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceCreateMachPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCopyValue(_:_:)/title",
          "value": "IOSurfaceCopyValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceCopyValue(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceCopyValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceRef/title",
          "value": "IOSurfaceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBaseAddress(_:)/title",
          "value": "IOSurfaceGetBaseAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBaseAddress(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceGetBaseAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBitDepthOfComponentOfPlane(_:_:_:)/title",
          "value": "IOSurfaceGetBitDepthOfComponentOfPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceGetBitDepthOfComponentOfPlane(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceGetBitDepthOfComponentOfPlane"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iosurface/iosurfacegetallocsize(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iosurface/iosurfacegetallocsize(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
