{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iosurface/documentation/IOSurface"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kIOSurfaceName",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kIOSurfaceName"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "IOSurface"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kIOSurfaceName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kIOSurfaceName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kIOSurfaceName"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd",
      "kind": "article",
      "role": "article",
      "title": "CFNumber",
      "type": "topic",
      "url": "/documentation/corefoundation/cfnumber-rjd"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iosurface/documentation/IOSurface": {
      "abstract": [
        {
          "text": "Share hardware-accelerated buffer data (framebuffers and textures) across multiple processes. Manage image memory more efficiently.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface",
      "kind": "symbol",
      "role": "collection",
      "title": "IOSurface",
      "type": "topic",
      "url": "/documentation/iosurface"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceAllocSize": {
      "abstract": [
        {
          "text": "CFNumber of the total allocation size of the buffer including all planes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceAllocSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceAllocSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceAllocSize"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceAllocSize",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceallocsize"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerElement": {
      "abstract": [
        {
          "text": "CFNumber for the total number of bytes in an element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceBytesPerElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceBytesPerElement"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceBytesPerElement",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacebytesperelement"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerRow": {
      "abstract": [
        {
          "text": "CFNumber for the bytes per row of the buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceBytesPerRow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerRow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceBytesPerRow"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceBytesPerRow",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacebytesperrow"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCacheMode": {
      "abstract": [
        {
          "text": "CFNumber for the CPU cache mode to be used for the allocation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceCacheMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCacheMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceCacheMode"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceCacheMode",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacecachemode"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceColorSpace": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceColorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceColorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceColorSpace"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceColorSpace",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacecolorspace"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementHeight": {
      "abstract": [
        {
          "text": "CFNumber for how many pixels high each element is.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceElementHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceElementHeight"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceElementHeight",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceelementheight"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementWidth": {
      "abstract": [
        {
          "text": "CFNumber for how many pixels wide each element is.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceElementWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceElementWidth"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceElementWidth",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceelementwidth"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceHeight": {
      "abstract": [
        {
          "text": "CFNumber for the height of the IOSurface buffer in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceHeight"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceHeight",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceheight"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceICCProfile": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceICCProfile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceICCProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceICCProfile"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceICCProfile",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceiccprofile"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceIsGlobal": {
      "abstract": [
        {
          "text": "CFBoolean If true, the IOSurface may be looked up by any task in the system by its ID.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceIsGlobal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceIsGlobal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceIsGlobal"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceIsGlobal",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceisglobal"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceName"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceName",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacename"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceOffset": {
      "abstract": [
        {
          "text": "CFNumber for the starting offset into the buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfaceOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceOffset"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfaceOffset",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceoffset"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelFormat": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " that stores the traditional macOS buffer format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePixelFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePixelFormat"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePixelFormat",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacepixelformat"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelSizeCastingAllowed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePixelSizeCastingAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelSizeCastingAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePixelSizeCastingAllowed"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePixelSizeCastingAllowed",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfacepixelsizecastingallowed"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBase": {
      "abstract": [
        {
          "text": "CFNumber for the base offset into the buffer for this plane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneBase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneBase"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePlaneBase",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceplanebase"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBitsPerElement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneBitsPerElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBitsPerElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePlaneBitsPerElement"
        }
      ],
      "role": "symbol",
      "title": "kIOSurfacePlaneBitsPerElement",
      "type": "topic",
      "url": "/documentation/iosurface/kiosurfaceplanebitsperelement"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceAllocSize",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerElement",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerRow",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCacheMode",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceColorSpace",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementHeight",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementWidth",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceHeight",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceICCProfile",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceIsGlobal",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceOffset",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelFormat",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelSizeCastingAllowed",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBase",
        "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBitsPerElement"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kIOSurfaceName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iosurface/documentation/IOSurface"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceAllocSize",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerElement",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerRow",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCacheMode",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceColorSpace",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementHeight",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementWidth",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceHeight",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceICCProfile",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceIsGlobal",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceOffset",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelFormat",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelSizeCastingAllowed",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBase",
                "doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBitsPerElement"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kIOSurfaceName"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePixelSizeCastingAllowed/title",
          "value": "kIOSurfacePixelSizeCastingAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePixelSizeCastingAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePixelSizeCastingAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceElementWidth/title",
          "value": "kIOSurfaceElementWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceElementWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceElementWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceCacheMode/title",
          "value": "kIOSurfaceCacheMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceCacheMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceCacheMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceIsGlobal/title",
          "value": "kIOSurfaceIsGlobal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceIsGlobal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceIsGlobal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBase/title",
          "value": "kIOSurfacePlaneBase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePlaneBase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceOffset/title",
          "value": "kIOSurfaceOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePixelFormat/title",
          "value": "kIOSurfacePixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceAllocSize/title",
          "value": "kIOSurfaceAllocSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceAllocSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceAllocSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceHeight/title",
          "value": "kIOSurfaceHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBitsPerElement/title",
          "value": "kIOSurfacePlaneBitsPerElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBitsPerElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePlaneBitsPerElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceName/title",
          "value": "kIOSurfaceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceBytesPerRow/title",
          "value": "kIOSurfaceBytesPerRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceBytesPerRow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceBytesPerRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceElementHeight/title",
          "value": "kIOSurfaceElementHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceElementHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceElementHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceICCProfile/title",
          "value": "kIOSurfaceICCProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceICCProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceICCProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceColorSpace/title",
          "value": "kIOSurfaceColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceColorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceBytesPerElement/title",
          "value": "kIOSurfaceBytesPerElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceBytesPerElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceBytesPerElement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iosurface/kiosurfacename"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iosurface/kiosurfacename"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
