{"metadata":{"platforms":[{"introducedAt":"11.0","beta":false,"name":"iOS","deprecated":false,"unavailable":false},{"introducedAt":"11.0","beta":false,"name":"iPadOS","deprecated":false,"unavailable":false},{"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false},{"introducedAt":"10.6","beta":false,"name":"macOS","deprecated":false,"unavailable":false},{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"11.0","name":"tvOS"},{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"1.0","name":"visionOS"}],"symbolKind":"var","title":"kIOSurfacePlaneBytesPerElement","role":"symbol","navigatorTitle":[{"text":"kIOSurfacePlaneBytesPerElement","kind":"identifier"}],"modules":[{"name":"IOSurface"}],"roleHeading":"Global Variable","externalID":"c:@kIOSurfacePlaneBytesPerElement","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kIOSurfacePlaneBytesPerElement","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CFString","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef"}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBytesPerElement"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iosurface/documentation/IOSurface"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kIOSurfacePlaneBytesPerElement","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/c:@T@CFStringRef","kind":"typeIdentifier","text":"CFString","preciseIdentifier":"c:@T@CFStringRef"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"},{"content":[{"anchor":"Discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional, default is 1."}]}],"kind":"content"}],"variants":[{"paths":["/documentation/iosurface/kiosurfaceplanebytesperelement"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/iosurface/kiosurfaceplanebytesperelement"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"title":"Constants","identifiers":["doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceAllocSize","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerElement","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerRow","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCacheMode","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceColorSpace","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementHeight","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementWidth","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceHeight","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceICCProfile","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceIsGlobal","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceName","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceOffset","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelFormat","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelSizeCastingAllowed","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBase"],"generated":true,"anchor":"Constants"}],"abstract":[{"text":"CFNumber for the bytes per element of this plane.","type":"text"}],"references":{"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceName":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kIOSurfaceName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CFString","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef"}],"navigatorTitle":[{"text":"kIOSurfaceName","kind":"identifier"}],"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceName","url":"/documentation/iosurface/kiosurfacename","kind":"symbol","title":"kIOSurfaceName","type":"topic","abstract":[],"role":"symbol"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceICCProfile":{"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceICCProfile","title":"kIOSurfaceICCProfile","kind":"symbol","url":"/documentation/iosurface/kiosurfaceiccprofile","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kIOSurfaceICCProfile"},{"text":": ","kind":"text"},{"text":"CFString","preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"kIOSurfaceICCProfile","kind":"identifier"}],"type":"topic"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelFormat":{"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelFormat","title":"kIOSurfacePixelFormat","kind":"symbol","url":"/documentation/iosurface/kiosurfacepixelformat","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kIOSurfacePixelFormat","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CFString","preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A 32-bit unsigned integer "},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd","type":"reference"},{"type":"text","text":" that stores the traditional macOS buffer format."}],"role":"symbol","navigatorTitle":[{"text":"kIOSurfacePixelFormat","kind":"identifier"}],"type":"topic"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceAllocSize":{"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceAllocSize","title":"kIOSurfaceAllocSize","kind":"symbol","url":"/documentation/iosurface/kiosurfaceallocsize","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kIOSurfaceAllocSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier","text":"CFString"}],"abstract":[{"type":"text","text":"CFNumber of the total allocation size of the buffer including all planes."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kIOSurfaceAllocSize"}],"type":"topic"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceColorSpace":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"kIOSurfaceColorSpace","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CFString","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef"}],"navigatorTitle":[{"text":"kIOSurfaceColorSpace","kind":"identifier"}],"type":"topic","kind":"symbol","title":"kIOSurfaceColorSpace","role":"symbol","url":"/documentation/iosurface/kiosurfacecolorspace","identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceColorSpace","abstract":[]},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","title":"Technologies","type":"topic","abstract":[{"text":"","type":"text"}],"role":"overview","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd":{"type":"topic","role":"article","abstract":[{"type":"text","text":""}],"title":"CFNumber","url":"/documentation/corefoundation/cfnumber-rjd","identifier":"doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd","kind":"article"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceIsGlobal":{"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceIsGlobal","title":"kIOSurfaceIsGlobal","kind":"symbol","url":"/documentation/iosurface/kiosurfaceisglobal","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kIOSurfaceIsGlobal"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier","text":"CFString"}],"abstract":[{"type":"text","text":"CFBoolean If true, the IOSurface may be looked up by any task in the system by its ID."}],"role":"symbol","navigatorTitle":[{"text":"kIOSurfaceIsGlobal","kind":"identifier"}],"deprecated":true,"type":"topic"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementWidth":{"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementWidth","title":"kIOSurfaceElementWidth","kind":"symbol","url":"/documentation/iosurface/kiosurfaceelementwidth","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kIOSurfaceElementWidth"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CFStringRef","text":"CFString","kind":"typeIdentifier"}],"abstract":[{"text":"CFNumber for how many pixels wide each element is.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"kIOSurfaceElementWidth","kind":"identifier"}],"type":"topic"},"doc://com.externally.resolved.symbol/c:@T@CFStringRef":{"identifier":"doc://com.externally.resolved.symbol/c:@T@CFStringRef","title":"CFString","kind":"symbol","url":"/documentation/corefoundation/cfstring","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"CFString"}],"abstract":[{"type":"text","text":"A reference to a CFString object."}],"role":"symbol","type":"topic"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceHeight":{"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceHeight","title":"kIOSurfaceHeight","kind":"symbol","url":"/documentation/iosurface/kiosurfaceheight","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kIOSurfaceHeight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CFStringRef","text":"CFString","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"CFNumber for the height of the IOSurface buffer in pixels."}],"role":"symbol","navigatorTitle":[{"text":"kIOSurfaceHeight","kind":"identifier"}],"type":"topic"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBase":{"abstract":[{"text":"CFNumber for the base offset into the buffer for this plane.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"kIOSurfacePlaneBase","kind":"identifier"}],"url":"/documentation/iosurface/kiosurfaceplanebase","identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBase","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kIOSurfacePlaneBase"},{"text":": ","kind":"text"},{"text":"CFString","preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier"}],"role":"symbol","type":"topic","title":"kIOSurfacePlaneBase"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBytesPerElement":{"title":"kIOSurfacePlaneBytesPerElement","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kIOSurfacePlaneBytesPerElement","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef","text":"CFString"}],"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBytesPerElement","type":"topic","abstract":[{"type":"text","text":"CFNumber for the bytes per element of this plane."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"kIOSurfacePlaneBytesPerElement"}],"url":"/documentation/iosurface/kiosurfaceplanebytesperelement"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCacheMode":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kIOSurfaceCacheMode"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kIOSurfaceCacheMode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef","text":"CFString"}],"abstract":[{"type":"text","text":"CFNumber for the CPU cache mode to be used for the allocation."}],"title":"kIOSurfaceCacheMode","url":"/documentation/iosurface/kiosurfacecachemode","identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCacheMode","kind":"symbol"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceOffset":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kIOSurfaceOffset"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kIOSurfaceOffset","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef","text":"CFString"}],"abstract":[{"type":"text","text":"CFNumber for the starting offset into the buffer."}],"title":"kIOSurfaceOffset","url":"/documentation/iosurface/kiosurfaceoffset","identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceOffset","kind":"symbol"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerElement":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kIOSurfaceBytesPerElement"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kIOSurfaceBytesPerElement","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef","text":"CFString"}],"abstract":[{"type":"text","text":"CFNumber for the total number of bytes in an element."}],"title":"kIOSurfaceBytesPerElement","url":"/documentation/iosurface/kiosurfacebytesperelement","identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerElement","kind":"symbol"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerRow":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kIOSurfaceBytesPerRow"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kIOSurfaceBytesPerRow"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier","text":"CFString"}],"abstract":[{"type":"text","text":"CFNumber for the bytes per row of the buffer."}],"title":"kIOSurfaceBytesPerRow","url":"/documentation/iosurface/kiosurfacebytesperrow","identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerRow","kind":"symbol"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementHeight":{"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementHeight","title":"kIOSurfaceElementHeight","kind":"symbol","url":"/documentation/iosurface/kiosurfaceelementheight","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kIOSurfaceElementHeight"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier","text":"CFString"}],"abstract":[{"type":"text","text":"CFNumber for how many pixels high each element is."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kIOSurfaceElementHeight"}],"type":"topic"},"doc://com.apple.iosurface/documentation/IOSurface":{"url":"/documentation/iosurface","title":"IOSurface","type":"topic","abstract":[{"type":"text","text":"Share hardware-accelerated buffer data (framebuffers and textures) across multiple processes. Manage image memory more efficiently."}],"role":"collection","kind":"symbol","identifier":"doc://com.apple.iosurface/documentation/IOSurface"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelSizeCastingAllowed":{"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelSizeCastingAllowed","title":"kIOSurfacePixelSizeCastingAllowed","kind":"symbol","url":"/documentation/iosurface/kiosurfacepixelsizecastingallowed","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kIOSurfacePixelSizeCastingAllowed"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier","text":"CFString"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kIOSurfacePixelSizeCastingAllowed"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"11.0","beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"11.0","beta":false},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1","beta":false},{"deprecated":false,"name":"macOS","unavailable":false,"introducedAt":"10.6","beta":false},{"deprecated":false,"name":"tvOS","beta":false,"introducedAt":"11.0","unavailable":false},{"deprecated":false,"name":"visionOS","beta":false,"introducedAt":"1.0","unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Global Variable"},{"op":"replace","value":"kIOSurfacePlaneBytesPerElement","path":"/metadata/title"},{"op":"replace","value":"var","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"kIOSurfacePlaneBytesPerElement"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iosurface/documentation/IOSurface"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceAllocSize","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerElement","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerRow","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCacheMode","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceColorSpace","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementHeight","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementWidth","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceHeight","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceICCProfile","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceIsGlobal","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceName","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceOffset","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelFormat","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelSizeCastingAllowed","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBase"],"title":"Constants","anchor":"Constants","generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@CFStringRef","text":"CFStringRef","preciseIdentifier":"c:@T@CFStringRef"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kIOSurfacePlaneBytesPerElement","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","value":"kIOSurfaceName","path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceName/title"},{"op":"replace","value":[{"kind":"identifier","text":"kIOSurfaceName"}],"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceName/fragments"},{"op":"replace","value":"kIOSurfaceICCProfile","path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceICCProfile/title"},{"op":"replace","value":[{"text":"kIOSurfaceICCProfile","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceICCProfile/fragments"},{"op":"replace","value":"kIOSurfacePixelFormat","path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePixelFormat/title"},{"op":"replace","value":[{"text":"kIOSurfacePixelFormat","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePixelFormat/fragments"},{"op":"replace","value":"kIOSurfaceAllocSize","path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceAllocSize/title"},{"op":"replace","value":[{"text":"kIOSurfaceAllocSize","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceAllocSize/fragments"},{"op":"replace","value":"kIOSurfaceColorSpace","path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceColorSpace/title"},{"op":"replace","value":[{"kind":"identifier","text":"kIOSurfaceColorSpace"}],"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceColorSpace/fragments"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceIsGlobal/title","op":"replace","value":"kIOSurfaceIsGlobal"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceIsGlobal/fragments","op":"replace","value":[{"kind":"identifier","text":"kIOSurfaceIsGlobal"}]},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceElementWidth/title","op":"replace","value":"kIOSurfaceElementWidth"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceElementWidth/fragments","op":"replace","value":[{"text":"kIOSurfaceElementWidth","kind":"identifier"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title","op":"replace","value":"CFStringRef"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceHeight/title","op":"replace","value":"kIOSurfaceHeight"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceHeight/fragments","op":"replace","value":[{"kind":"identifier","text":"kIOSurfaceHeight"}]},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBase/title","op":"replace","value":"kIOSurfacePlaneBase"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBase/fragments","op":"replace","value":[{"text":"kIOSurfacePlaneBase","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBytesPerElement/title","op":"replace","value":"kIOSurfacePlaneBytesPerElement"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBytesPerElement/fragments","op":"replace","value":[{"kind":"identifier","text":"kIOSurfacePlaneBytesPerElement"}]},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceCacheMode/title","op":"replace","value":"kIOSurfaceCacheMode"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceCacheMode/fragments","op":"replace","value":[{"text":"kIOSurfaceCacheMode","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceOffset/title","op":"replace","value":"kIOSurfaceOffset"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceOffset/fragments","op":"replace","value":[{"kind":"identifier","text":"kIOSurfaceOffset"}]},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceBytesPerElement/title","op":"replace","value":"kIOSurfaceBytesPerElement"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceBytesPerElement/fragments","op":"replace","value":[{"kind":"identifier","text":"kIOSurfaceBytesPerElement"}]},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceBytesPerRow/title","op":"replace","value":"kIOSurfaceBytesPerRow"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceBytesPerRow/fragments","op":"replace","value":[{"text":"kIOSurfaceBytesPerRow","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceElementHeight/title","op":"replace","value":"kIOSurfaceElementHeight"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceElementHeight/fragments","op":"replace","value":[{"text":"kIOSurfaceElementHeight","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePixelSizeCastingAllowed/title","op":"replace","value":"kIOSurfacePixelSizeCastingAllowed"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePixelSizeCastingAllowed/fragments","op":"replace","value":[{"text":"kIOSurfacePixelSizeCastingAllowed","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}