{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/iosurface/kiosurfacebytesperrow"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/iosurface/kiosurfacebytesperrow"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"CFNumber for the bytes per row of the buffer."}],"seeAlsoSections":[{"identifiers":["doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceAllocSize","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerElement","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCacheMode","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceColorSpace","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementHeight","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementWidth","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceHeight","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceICCProfile","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceIsGlobal","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceName","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceOffset","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelFormat","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelSizeCastingAllowed","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBase","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBitsPerElement"],"anchor":"Constants","title":"Constants","generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iosurface/documentation/IOSurface"]]},"metadata":{"navigatorTitle":[{"text":"kIOSurfaceBytesPerRow","kind":"identifier"}],"title":"kIOSurfaceBytesPerRow","modules":[{"name":"IOSurface"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kIOSurfaceBytesPerRow"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier","text":"CFString"}],"role":"symbol","symbolKind":"var","platforms":[{"name":"iOS","deprecated":false,"beta":false,"introducedAt":"11.0","unavailable":false},{"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"11.0","unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"13.1","unavailable":false},{"name":"macOS","deprecated":false,"beta":false,"introducedAt":"10.6","unavailable":false},{"name":"tvOS","deprecated":false,"beta":false,"introducedAt":"11.0","unavailable":false},{"beta":false,"deprecated":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0"}],"roleHeading":"Global Variable","externalID":"c:@kIOSurfaceBytesPerRow"},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kIOSurfaceBytesPerRow"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/c:@T@CFStringRef","preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier","text":"CFString"}]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","anchor":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"If not specified, IOSurface will first calculate the number full elements required on each row (by rounding up), multiplied by the bytes per element for this buffer. That value will then be appropriately aligned."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerRow","interfaceLanguage":"swift"},"references":{"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelFormat":{"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelFormat","title":"kIOSurfacePixelFormat","kind":"symbol","url":"/documentation/iosurface/kiosurfacepixelformat","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kIOSurfacePixelFormat","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CFString","preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A 32-bit unsigned integer "},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd","type":"reference"},{"type":"text","text":" that stores the traditional macOS buffer format."}],"role":"symbol","navigatorTitle":[{"text":"kIOSurfacePixelFormat","kind":"identifier"}],"type":"topic"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCacheMode":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kIOSurfaceCacheMode"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kIOSurfaceCacheMode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef","text":"CFString"}],"abstract":[{"type":"text","text":"CFNumber for the CPU cache mode to be used for the allocation."}],"title":"kIOSurfaceCacheMode","url":"/documentation/iosurface/kiosurfacecachemode","identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCacheMode","kind":"symbol"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceColorSpace":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"kIOSurfaceColorSpace","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CFString","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef"}],"navigatorTitle":[{"text":"kIOSurfaceColorSpace","kind":"identifier"}],"type":"topic","kind":"symbol","title":"kIOSurfaceColorSpace","role":"symbol","url":"/documentation/iosurface/kiosurfacecolorspace","identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceColorSpace","abstract":[]},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","title":"Technologies","type":"topic","abstract":[{"text":"","type":"text"}],"role":"overview","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementWidth":{"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementWidth","title":"kIOSurfaceElementWidth","kind":"symbol","url":"/documentation/iosurface/kiosurfaceelementwidth","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kIOSurfaceElementWidth"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CFStringRef","text":"CFString","kind":"typeIdentifier"}],"abstract":[{"text":"CFNumber for how many pixels wide each element is.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"kIOSurfaceElementWidth","kind":"identifier"}],"type":"topic"},"doc://com.apple.iosurface/documentation/IOSurface":{"url":"/documentation/iosurface","title":"IOSurface","type":"topic","abstract":[{"type":"text","text":"Share hardware-accelerated buffer data (framebuffers and textures) across multiple processes. Manage image memory more efficiently."}],"role":"collection","kind":"symbol","identifier":"doc://com.apple.iosurface/documentation/IOSurface"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceName":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kIOSurfaceName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CFString","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef"}],"navigatorTitle":[{"text":"kIOSurfaceName","kind":"identifier"}],"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceName","url":"/documentation/iosurface/kiosurfacename","kind":"symbol","title":"kIOSurfaceName","type":"topic","abstract":[],"role":"symbol"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBitsPerElement":{"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBitsPerElement","title":"kIOSurfacePlaneBitsPerElement","kind":"symbol","url":"/documentation/iosurface/kiosurfaceplanebitsperelement","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kIOSurfacePlaneBitsPerElement"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CFStringRef","text":"CFString","kind":"typeIdentifier"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"kIOSurfacePlaneBitsPerElement","kind":"identifier"}],"type":"topic"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerElement":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kIOSurfaceBytesPerElement"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kIOSurfaceBytesPerElement","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef","text":"CFString"}],"abstract":[{"type":"text","text":"CFNumber for the total number of bytes in an element."}],"title":"kIOSurfaceBytesPerElement","url":"/documentation/iosurface/kiosurfacebytesperelement","identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerElement","kind":"symbol"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceICCProfile":{"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceICCProfile","title":"kIOSurfaceICCProfile","kind":"symbol","url":"/documentation/iosurface/kiosurfaceiccprofile","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kIOSurfaceICCProfile"},{"text":": ","kind":"text"},{"text":"CFString","preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"kIOSurfaceICCProfile","kind":"identifier"}],"type":"topic"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelSizeCastingAllowed":{"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelSizeCastingAllowed","title":"kIOSurfacePixelSizeCastingAllowed","kind":"symbol","url":"/documentation/iosurface/kiosurfacepixelsizecastingallowed","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kIOSurfacePixelSizeCastingAllowed"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier","text":"CFString"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kIOSurfacePixelSizeCastingAllowed"}],"type":"topic"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBase":{"abstract":[{"text":"CFNumber for the base offset into the buffer for this plane.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"kIOSurfacePlaneBase","kind":"identifier"}],"url":"/documentation/iosurface/kiosurfaceplanebase","identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBase","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kIOSurfacePlaneBase"},{"text":": ","kind":"text"},{"text":"CFString","preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier"}],"role":"symbol","type":"topic","title":"kIOSurfacePlaneBase"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceAllocSize":{"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceAllocSize","title":"kIOSurfaceAllocSize","kind":"symbol","url":"/documentation/iosurface/kiosurfaceallocsize","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kIOSurfaceAllocSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier","text":"CFString"}],"abstract":[{"type":"text","text":"CFNumber of the total allocation size of the buffer including all planes."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kIOSurfaceAllocSize"}],"type":"topic"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceIsGlobal":{"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceIsGlobal","title":"kIOSurfaceIsGlobal","kind":"symbol","url":"/documentation/iosurface/kiosurfaceisglobal","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kIOSurfaceIsGlobal"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier","text":"CFString"}],"abstract":[{"type":"text","text":"CFBoolean If true, the IOSurface may be looked up by any task in the system by its ID."}],"role":"symbol","navigatorTitle":[{"text":"kIOSurfaceIsGlobal","kind":"identifier"}],"deprecated":true,"type":"topic"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementHeight":{"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementHeight","title":"kIOSurfaceElementHeight","kind":"symbol","url":"/documentation/iosurface/kiosurfaceelementheight","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kIOSurfaceElementHeight"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier","text":"CFString"}],"abstract":[{"type":"text","text":"CFNumber for how many pixels high each element is."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kIOSurfaceElementHeight"}],"type":"topic"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceOffset":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kIOSurfaceOffset"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kIOSurfaceOffset","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef","text":"CFString"}],"abstract":[{"type":"text","text":"CFNumber for the starting offset into the buffer."}],"title":"kIOSurfaceOffset","url":"/documentation/iosurface/kiosurfaceoffset","identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceOffset","kind":"symbol"},"doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd":{"type":"topic","role":"article","abstract":[{"type":"text","text":""}],"title":"CFNumber","url":"/documentation/corefoundation/cfnumber-rjd","identifier":"doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd","kind":"article"},"doc://com.externally.resolved.symbol/c:@T@CFStringRef":{"identifier":"doc://com.externally.resolved.symbol/c:@T@CFStringRef","title":"CFString","kind":"symbol","url":"/documentation/corefoundation/cfstring","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"CFString"}],"abstract":[{"type":"text","text":"A reference to a CFString object."}],"role":"symbol","type":"topic"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerRow":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kIOSurfaceBytesPerRow"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kIOSurfaceBytesPerRow"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier","text":"CFString"}],"abstract":[{"type":"text","text":"CFNumber for the bytes per row of the buffer."}],"title":"kIOSurfaceBytesPerRow","url":"/documentation/iosurface/kiosurfacebytesperrow","identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerRow","kind":"symbol"},"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceHeight":{"identifier":"doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceHeight","title":"kIOSurfaceHeight","kind":"symbol","url":"/documentation/iosurface/kiosurfaceheight","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kIOSurfaceHeight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CFStringRef","text":"CFString","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"CFNumber for the height of the IOSurface buffer in pixels."}],"role":"symbol","navigatorTitle":[{"text":"kIOSurfaceHeight","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"11.0"},{"beta":false,"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"11.0"},{"beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"13.1"},{"beta":false,"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"10.6"},{"beta":false,"deprecated":false,"unavailable":false,"name":"tvOS","introducedAt":"11.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0"}],"path":"/metadata/platforms"},{"op":"replace","value":"Global Variable","path":"/metadata/roleHeading"},{"op":"replace","value":"kIOSurfaceBytesPerRow","path":"/metadata/title"},{"op":"replace","value":"var","path":"/metadata/symbolKind"},{"value":[{"text":"kIOSurfaceBytesPerRow","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iosurface/documentation/IOSurface"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Constants","identifiers":["doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceAllocSize","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceBytesPerElement","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceCacheMode","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceColorSpace","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementHeight","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceElementWidth","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceHeight","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceICCProfile","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceIsGlobal","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceName","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfaceOffset","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelFormat","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePixelSizeCastingAllowed","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBase","doc://com.apple.iosurface/documentation/IOSurface/kIOSurfacePlaneBitsPerElement"],"anchor":"Constants","generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CFStringRef","preciseIdentifier":"c:@T@CFStringRef","identifier":"doc://com.externally.resolved.symbol/c:@T@CFStringRef","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kIOSurfaceBytesPerRow","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePixelFormat/title","value":"kIOSurfacePixelFormat","op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePixelFormat/fragments","value":[{"kind":"identifier","text":"kIOSurfacePixelFormat"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceCacheMode/title","value":"kIOSurfaceCacheMode","op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceCacheMode/fragments","value":[{"text":"kIOSurfaceCacheMode","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceColorSpace/title","value":"kIOSurfaceColorSpace","op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceColorSpace/fragments","value":[{"text":"kIOSurfaceColorSpace","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceElementWidth/title","value":"kIOSurfaceElementWidth","op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceElementWidth/fragments","value":[{"text":"kIOSurfaceElementWidth","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceName/title","value":"kIOSurfaceName","op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceName/fragments","value":[{"text":"kIOSurfaceName","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBitsPerElement/title","value":"kIOSurfacePlaneBitsPerElement","op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBitsPerElement/fragments","value":[{"kind":"identifier","text":"kIOSurfacePlaneBitsPerElement"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceBytesPerElement/title","value":"kIOSurfaceBytesPerElement","op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceBytesPerElement/fragments","value":[{"kind":"identifier","text":"kIOSurfaceBytesPerElement"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceICCProfile/title","value":"kIOSurfaceICCProfile","op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceICCProfile/fragments","value":[{"text":"kIOSurfaceICCProfile","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePixelSizeCastingAllowed/title","value":"kIOSurfacePixelSizeCastingAllowed","op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePixelSizeCastingAllowed/fragments","value":[{"text":"kIOSurfacePixelSizeCastingAllowed","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBase/title","value":"kIOSurfacePlaneBase","op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfacePlaneBase/fragments","value":[{"kind":"identifier","text":"kIOSurfacePlaneBase"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceAllocSize/title","value":"kIOSurfaceAllocSize","op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceAllocSize/fragments","value":[{"text":"kIOSurfaceAllocSize","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceIsGlobal/title","value":"kIOSurfaceIsGlobal","op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceIsGlobal/fragments","value":[{"kind":"identifier","text":"kIOSurfaceIsGlobal"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceElementHeight/title","value":"kIOSurfaceElementHeight","op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceElementHeight/fragments","value":[{"text":"kIOSurfaceElementHeight","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceOffset/title","value":"kIOSurfaceOffset","op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceOffset/fragments","value":[{"text":"kIOSurfaceOffset","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title","value":"CFStringRef","op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceBytesPerRow/title","value":"kIOSurfaceBytesPerRow","op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceBytesPerRow/fragments","value":[{"text":"kIOSurfaceBytesPerRow","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceHeight/title","value":"kIOSurfaceHeight","op":"replace"},{"path":"/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1kIOSurfaceHeight/fragments","value":[{"kind":"identifier","text":"kIOSurfaceHeight"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}