{
  "abstract": [
    {
      "text": "You are in the process of handling the intent.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "INGetRideStatusIntentResponseCodeInProgress is deprecated.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/inProgress"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INGetRideStatusIntentResponseCode@INGetRideStatusIntentResponseCodeInProgress",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "inProgress"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INGetRideStatusIntentResponseCodeInProgress"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.0",
        "message": "INGetRideStatusIntentResponseCodeInProgress is deprecated.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.0",
        "message": "INGetRideStatusIntentResponseCodeInProgress is deprecated.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "INGetRideStatusIntentResponseCodeInProgress is deprecated.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INGetRideStatusIntentResponseCodeInProgress is deprecated.",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "4.0",
        "introducedAt": "3.2",
        "message": "INGetRideStatusIntentResponseCodeInProgress is deprecated.",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INGetRideStatusIntentResponseCode.inProgress"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "inProgress"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Avoid using this response code when possible unless you are actively retrieving the ride status information but are unable to return that information in a timely manner.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode": {
      "abstract": [
        {
          "text": "Constants indicating the state of the response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INGetRideStatusIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/ingetridestatusintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/failure": {
      "abstract": [
        {
          "text": "You were unable to retrieve information about the current ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INGetRideStatusIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/ingetridestatusintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [
        {
          "text": "The user must launch your app to get information about the current ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INGetRideStatusIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/ingetridestatusintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/failureRequiringAppLaunchMustVerifyCredentials": {
      "abstract": [
        {
          "text": "The user must launch your app and verify their credentials to continue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunchMustVerifyCredentials"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/failureRequiringAppLaunchMustVerifyCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntentResponseCodeFailureRequiringAppLaunchMustVerifyCredentials"
        }
      ],
      "role": "symbol",
      "title": "INGetRideStatusIntentResponseCode.failureRequiringAppLaunchMustVerifyCredentials",
      "type": "topic",
      "url": "/documentation/intents/ingetridestatusintentresponsecode/failurerequiringapplaunchmustverifycredentials"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/failureRequiringAppLaunchServiceTemporarilyUnavailable": {
      "abstract": [
        {
          "text": "Your service is temporarily unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunchServiceTemporarilyUnavailable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/failureRequiringAppLaunchServiceTemporarilyUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntentResponseCodeFailureRequiringAppLaunchServiceTemporarilyUnavailable"
        }
      ],
      "role": "symbol",
      "title": "INGetRideStatusIntentResponseCode.failureRequiringAppLaunchServiceTemporarilyUnavailable",
      "type": "topic",
      "url": "/documentation/intents/ingetridestatusintentresponsecode/failurerequiringapplaunchservicetemporarilyunavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/inProgress": {
      "abstract": [
        {
          "text": "You are in the process of handling the intent.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inProgress"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/inProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntentResponseCodeInProgress"
        }
      ],
      "role": "symbol",
      "title": "INGetRideStatusIntentResponseCode.inProgress",
      "type": "topic",
      "url": "/documentation/intents/ingetridestatusintentresponsecode/inprogress"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/ready": {
      "abstract": [
        {
          "text": "You are ready to handle the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INGetRideStatusIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/ingetridestatusintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/success": {
      "abstract": [
        {
          "text": "You successfully handled the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntentResponseCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "INGetRideStatusIntentResponseCode.success",
      "type": "topic",
      "url": "/documentation/intents/ingetridestatusintentresponsecode/success"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/unspecified": {
      "abstract": [
        {
          "text": "There is no specified response code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INGetRideStatusIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/ingetridestatusintentresponsecode/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/unspecified",
        "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/ready",
        "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/success",
        "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/failure",
        "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/failureRequiringAppLaunch",
        "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/failureRequiringAppLaunchMustVerifyCredentials",
        "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/failureRequiringAppLaunchServiceTemporarilyUnavailable"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "4.0",
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INGetRideStatusIntentResponseCodeInProgress"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntentResponseCodeInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/unspecified",
                "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/ready",
                "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/success",
                "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/failure",
                "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/failureRequiringAppLaunch",
                "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/failureRequiringAppLaunchMustVerifyCredentials",
                "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseCode/failureRequiringAppLaunchServiceTemporarilyUnavailable"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INGetRideStatusIntentResponseCodeInProgress"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "INGetRideStatusIntentResponseCodeInProgress is deprecated.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INGetRideStatusIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseCode/title",
          "value": "INGetRideStatusIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseCode~1inProgress/title",
          "value": "INGetRideStatusIntentResponseCodeInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseCode~1inProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntentResponseCodeInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseCode~1failureRequiringAppLaunchMustVerifyCredentials/title",
          "value": "INGetRideStatusIntentResponseCodeFailureRequiringAppLaunchMustVerifyCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseCode~1failureRequiringAppLaunchMustVerifyCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntentResponseCodeFailureRequiringAppLaunchMustVerifyCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseCode~1success/title",
          "value": "INGetRideStatusIntentResponseCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseCode~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntentResponseCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseCode~1failure/title",
          "value": "INGetRideStatusIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntentResponseCodeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseCode~1failureRequiringAppLaunchServiceTemporarilyUnavailable/title",
          "value": "INGetRideStatusIntentResponseCodeFailureRequiringAppLaunchServiceTemporarilyUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseCode~1failureRequiringAppLaunchServiceTemporarilyUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntentResponseCodeFailureRequiringAppLaunchServiceTemporarilyUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseCode~1ready/title",
          "value": "INGetRideStatusIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntentResponseCodeReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseCode~1unspecified/title",
          "value": "INGetRideStatusIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntentResponseCodeUnspecified"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/ingetridestatusintentresponsecode/inprogress"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/ingetridestatusintentresponsecode/inprogress"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
