{
  "abstract": [
    {
      "text": "The encoded image data is rotated 90° clockwise from the image’s intended display orientation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO",
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/right"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CGImagePropertyOrientation@kCGImagePropertyOrientationRight",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "right"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImagePropertyOrientationRight"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CGImagePropertyOrientation.right"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "right"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The (x,y) pixel coordinates of the origin point (0,0) represent the top row and rightmost column, respectively. Pixel (x,y) positions increase top-to-bottom, right-to-left.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If an image is encoded with this orientation, then displayed by software unaware of orientation metadata, the image appears to be rotated 90° counter-clockwise. (That is, to present the image in its intended orientation, you must rotate it 90° clockwise.)",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2948299",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation": {
      "abstract": [
        {
          "text": "A value describing the intended display orientation for an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImagePropertyOrientation"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImagePropertyOrientation"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/down": {
      "abstract": [
        {
          "text": "The encoded image data is rotated 180° from the image’s intended display orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "down"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/down",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientationDown"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation.down",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation/down"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/downMirrored": {
      "abstract": [
        {
          "text": "The encoded image data is vertically flipped from the image’s intended display orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downMirrored"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/downMirrored",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientationDownMirrored"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation.downMirrored",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation/downmirrored"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/left": {
      "abstract": [
        {
          "text": "The encoded image data is rotated 90° clockwise from the image’s intended display orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientationLeft"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation.left",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation/left"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/leftMirrored": {
      "abstract": [
        {
          "text": "The encoded image data is horizontally flipped and rotated 90° counter-clockwise from the image’s intended display orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftMirrored"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/leftMirrored",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientationLeftMirrored"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation.leftMirrored",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation/leftmirrored"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/right": {
      "abstract": [
        {
          "text": "The encoded image data is rotated 90° clockwise from the image’s intended display orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientationRight"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation.right",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation/right"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/rightMirrored": {
      "abstract": [
        {
          "text": "The encoded image data is horizontally flipped and rotated 90° clockwise from the image’s intended display orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightMirrored"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/rightMirrored",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientationRightMirrored"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation.rightMirrored",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation/rightmirrored"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/up": {
      "abstract": [
        {
          "text": "The encoded image data matches the image’s intended display orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "up"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/up",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientationUp"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation.up",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation/up"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/upMirrored": {
      "abstract": [
        {
          "text": "The encoded image data is horizontally flipped from the image’s intended display orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "upMirrored"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/upMirrored",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientationUpMirrored"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation.upMirrored",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation/upmirrored"
    },
    "media-2948299": {
      "alt": "To correct an image with right orientation for display, rotate it 90° clockwise.",
      "identifier": "media-2948299",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5f85393673d69bff25539fb1abf634d9/media-2948299.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a4de8a358cbf9a76800cc595fceb8892/media-2948299@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Image-Orientations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/up",
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/upMirrored",
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/down",
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/downMirrored",
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/leftMirrored",
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/rightMirrored",
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/left"
      ],
      "title": "Image Orientations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImagePropertyOrientationRight"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientationRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO",
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Image-Orientations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/up",
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/upMirrored",
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/down",
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/downMirrored",
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/leftMirrored",
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/rightMirrored",
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/left"
              ],
              "title": "Image Orientations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCGImagePropertyOrientationRight"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1left/title",
          "value": "kCGImagePropertyOrientationLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientationLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1upMirrored/title",
          "value": "kCGImagePropertyOrientationUpMirrored"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1upMirrored/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientationUpMirrored"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1leftMirrored/title",
          "value": "kCGImagePropertyOrientationLeftMirrored"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1leftMirrored/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientationLeftMirrored"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1up/title",
          "value": "kCGImagePropertyOrientationUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1up/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientationUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1right/title",
          "value": "kCGImagePropertyOrientationRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientationRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation/title",
          "value": "CGImagePropertyOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImagePropertyOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImagePropertyOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1rightMirrored/title",
          "value": "kCGImagePropertyOrientationRightMirrored"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1rightMirrored/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientationRightMirrored"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1downMirrored/title",
          "value": "kCGImagePropertyOrientationDownMirrored"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1downMirrored/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientationDownMirrored"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1down/title",
          "value": "kCGImagePropertyOrientationDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1down/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientationDown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/cgimagepropertyorientation/right"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/cgimagepropertyorientation/right"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
