{
  "abstract": [
    {
      "text": "The user denied your app’s request to perform speech recognition.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.speech/documentation/Speech",
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus/denied"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SFSpeechRecognizerAuthorizationStatus@SFSpeechRecognizerAuthorizationStatusDenied",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "denied"
      }
    ],
    "modules": [
      {
        "name": "Speech"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SFSpeechRecognizerAuthorizationStatusDenied"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SFSpeechRecognizerAuthorizationStatus.denied"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "denied"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.speech/documentation/Speech": {
      "abstract": [
        {
          "text": "Perform speech recognition on live or prerecorded audio, and receive transcriptions, alternative interpretations, and confidence levels of the results.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech",
      "kind": "symbol",
      "role": "collection",
      "title": "Speech",
      "type": "topic",
      "url": "/documentation/speech"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus": {
      "abstract": [
        {
          "text": "The app’s authorization to perform speech recognition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechRecognizerAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognizerAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognizerAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognizerauthorizationstatus"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus/authorized": {
      "abstract": [
        {
          "text": "The user granted your app’s request to perform speech recognition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorized"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus/authorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognizerAuthorizationStatusAuthorized"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognizerAuthorizationStatus.authorized",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognizerauthorizationstatus/authorized"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus/denied": {
      "abstract": [
        {
          "text": "The user denied your app’s request to perform speech recognition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "denied"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus/denied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognizerAuthorizationStatusDenied"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognizerAuthorizationStatus.denied",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognizerauthorizationstatus/denied"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus/notDetermined": {
      "abstract": [
        {
          "text": "The app’s authorization status has not yet been determined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notDetermined"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus/notDetermined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognizerAuthorizationStatusNotDetermined"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognizerAuthorizationStatus.notDetermined",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognizerauthorizationstatus/notdetermined"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus/restricted": {
      "abstract": [
        {
          "text": "The device prevents your app from performing speech recognition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restricted"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus/restricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognizerAuthorizationStatusRestricted"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognizerAuthorizationStatus.restricted",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognizerauthorizationstatus/restricted"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Authorization-Statuses",
      "generated": true,
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus/notDetermined",
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus/restricted",
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus/authorized"
      ],
      "title": "Authorization Statuses"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SFSpeechRecognizerAuthorizationStatusDenied"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognizerAuthorizationStatusDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.speech/documentation/Speech",
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Authorization-Statuses",
              "generated": true,
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus/notDetermined",
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus/restricted",
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognizerAuthorizationStatus/authorized"
              ],
              "title": "Authorization Statuses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SFSpeechRecognizerAuthorizationStatusDenied"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizerAuthorizationStatus~1denied/title",
          "value": "SFSpeechRecognizerAuthorizationStatusDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizerAuthorizationStatus~1denied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognizerAuthorizationStatusDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizerAuthorizationStatus~1restricted/title",
          "value": "SFSpeechRecognizerAuthorizationStatusRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizerAuthorizationStatus~1restricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognizerAuthorizationStatusRestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizerAuthorizationStatus~1notDetermined/title",
          "value": "SFSpeechRecognizerAuthorizationStatusNotDetermined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizerAuthorizationStatus~1notDetermined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognizerAuthorizationStatusNotDetermined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizerAuthorizationStatus~1authorized/title",
          "value": "SFSpeechRecognizerAuthorizationStatusAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizerAuthorizationStatus~1authorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognizerAuthorizationStatusAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizerAuthorizationStatus/title",
          "value": "SFSpeechRecognizerAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizerAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognizerAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognizerAuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognizerAuthorizationStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/speech/sfspeechrecognizerauthorizationstatus/denied"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/speech/sfspeechrecognizerauthorizationstatus/denied"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
