{
  "abstract": [
    {
      "text": "Texture coordinates wrap to the other side of the texture, effectively keeping only the fractional part of the texture coordinate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/repeat"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLSamplerAddressMode@MTLSamplerAddressModeRepeat",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "`repeat`"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLSamplerAddressModeRepeat"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLSamplerAddressMode.repeat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "`repeat`"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode": {
      "abstract": [
        {
          "text": "Modes that determine the texture coordinate at each pixel when a fetch falls outside the bounds of a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLSamplerAddressMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerAddressMode"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerAddressMode",
      "type": "topic",
      "url": "/documentation/metal/mtlsampleraddressmode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToBorderColor": {
      "abstract": [
        {
          "text": "Out-of-range texture coordinates return the value specified by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/borderColor",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clampToBorderColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToBorderColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerAddressModeClampToBorderColor"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerAddressMode.clampToBorderColor",
      "type": "topic",
      "url": "/documentation/metal/mtlsampleraddressmode/clamptobordercolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToEdge": {
      "abstract": [
        {
          "text": "Texture coordinates are clamped between ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ", inclusive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clampToEdge"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerAddressModeClampToEdge"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerAddressMode.clampToEdge",
      "type": "topic",
      "url": "/documentation/metal/mtlsampleraddressmode/clamptoedge"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToZero": {
      "abstract": [
        {
          "text": "Out-of-range texture coordinates return transparent zero ",
          "type": "text"
        },
        {
          "code": "(0,0,0,0)",
          "type": "codeVoice"
        },
        {
          "text": " for images with an alpha channel and return opaque zero ",
          "type": "text"
        },
        {
          "code": "(0,0,0,1)",
          "type": "codeVoice"
        },
        {
          "text": " for images without an alpha channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clampToZero"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToZero",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerAddressModeClampToZero"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerAddressMode.clampToZero",
      "type": "topic",
      "url": "/documentation/metal/mtlsampleraddressmode/clamptozero"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/mirrorClampToEdge": {
      "abstract": [
        {
          "text": "Between ",
          "type": "text"
        },
        {
          "code": "-1.0",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ", the texture coordinates are mirrored across the axis; outside ",
          "type": "text"
        },
        {
          "code": "-1.0",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ", texture coordinates are clamped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mirrorClampToEdge"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/mirrorClampToEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerAddressModeMirrorClampToEdge"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerAddressMode.mirrorClampToEdge",
      "type": "topic",
      "url": "/documentation/metal/mtlsampleraddressmode/mirrorclamptoedge"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/mirrorRepeat": {
      "abstract": [
        {
          "text": "Between ",
          "type": "text"
        },
        {
          "code": "-1.0",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ", the texture coordinates are mirrored across the axis; outside ",
          "type": "text"
        },
        {
          "code": "-1.0",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ", the image is repeated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mirrorRepeat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/mirrorRepeat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerAddressModeMirrorRepeat"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerAddressMode.mirrorRepeat",
      "type": "topic",
      "url": "/documentation/metal/mtlsampleraddressmode/mirrorrepeat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/repeat": {
      "abstract": [
        {
          "text": "Texture coordinates wrap to the other side of the texture, effectively keeping only the fractional part of the texture coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`repeat`"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/repeat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerAddressModeRepeat"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerAddressMode.repeat",
      "type": "topic",
      "url": "/documentation/metal/mtlsampleraddressmode/repeat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/borderColor": {
      "abstract": [
        {
          "text": "The border color for clamped texture values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLSamplerBorderColor",
          "text": "MTLSamplerBorderColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/borderColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "borderColor"
        }
      ],
      "role": "symbol",
      "title": "borderColor",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/bordercolor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Address-Mode-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToEdge",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/mirrorClampToEdge",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/mirrorRepeat",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToZero",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToBorderColor"
      ],
      "title": "Address Mode Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLSamplerAddressModeRepeat"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerAddressModeRepeat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Address-Mode-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToEdge",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/mirrorClampToEdge",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/mirrorRepeat",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToZero",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToBorderColor"
              ],
              "title": "Address Mode Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLSamplerAddressModeRepeat"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode~1repeat/title",
          "value": "MTLSamplerAddressModeRepeat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode~1repeat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerAddressModeRepeat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode/title",
          "value": "MTLSamplerAddressMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerAddressMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerAddressMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1borderColor/title",
          "value": "borderColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1borderColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "borderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode~1clampToBorderColor/title",
          "value": "MTLSamplerAddressModeClampToBorderColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode~1clampToBorderColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerAddressModeClampToBorderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode~1clampToEdge/title",
          "value": "MTLSamplerAddressModeClampToEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode~1clampToEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerAddressModeClampToEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode~1clampToZero/title",
          "value": "MTLSamplerAddressModeClampToZero"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode~1clampToZero/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerAddressModeClampToZero"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode~1mirrorRepeat/title",
          "value": "MTLSamplerAddressModeMirrorRepeat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode~1mirrorRepeat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerAddressModeMirrorRepeat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode~1mirrorClampToEdge/title",
          "value": "MTLSamplerAddressModeMirrorClampToEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode~1mirrorClampToEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerAddressModeMirrorClampToEdge"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlsampleraddressmode/repeat"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlsampleraddressmode/repeat"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
