{
  "abstract": [
    {
      "text": "Returns an array of identities available on tokens.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/AuthorizationCallbacks"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/AuthorizationCallbacks/GetTokenIdentities"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AuthorizationCallbacks@FI@GetTokenIdentities",
    "fragments": [
      {
        "kind": "identifier",
        "text": "GetTokenIdentities"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GetTokenIdentities"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "10.13",
        "name": "macOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "GetTokenIdentities"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:*FI(#*$@S@__OpaqueAuthorizationEngine#*1v#**1$@S@__CFArray)",
              "text": "int (*)(struct __OpaqueAuthorizationEngine *, const void *, const struct __CFArray **)"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GetTokenIdentities"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An opaque handle that’s passed to your plug-in when the authorization engine calls your ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismCreate",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inEngine"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A local authentication context returned by the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/AuthorizationCallbacks/GetLAContext",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " call.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "context"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer the function uses to return an array of identities, each of which consists of two array elements: a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/SecIdentity",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instance and a text description of the identity.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outValue"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The caller owns the returned array and is responsible for releasing it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This function is only available when the callback ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/AuthorizationCallbacks/version",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " is 2 or higher.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationCallbacks": {
      "abstract": [
        {
          "text": "The interface implemented by the Security Server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AuthorizationCallbacks"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationCallbacks",
      "kind": "symbol",
      "role": "symbol",
      "title": "AuthorizationCallbacks",
      "type": "topic",
      "url": "/documentation/security/authorizationcallbacks"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationCallbacks/GetLAContext": {
      "abstract": [
        {
          "text": "Constructs a local authentication context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GetLAContext"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationCallbacks/GetLAContext",
      "kind": "symbol",
      "role": "symbol",
      "title": "GetLAContext",
      "type": "topic",
      "url": "/documentation/security/authorizationcallbacks/getlacontext"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationCallbacks/GetTokenIdentities": {
      "abstract": [
        {
          "text": "Returns an array of identities available on tokens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GetTokenIdentities"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationCallbacks/GetTokenIdentities",
      "kind": "symbol",
      "role": "symbol",
      "title": "GetTokenIdentities",
      "type": "topic",
      "url": "/documentation/security/authorizationcallbacks/gettokenidentities"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationCallbacks/version": {
      "abstract": [
        {
          "text": "The engine callback version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationCallbacks/version",
      "kind": "symbol",
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/security/authorizationcallbacks/version"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismCreate": {
      "abstract": [
        {
          "text": "Creates an authorization mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MechanismCreate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "MechanismCreate",
      "type": "topic",
      "url": "/documentation/security/authorizationplugininterface/mechanismcreate"
    },
    "doc://com.apple.security/documentation/Security/SecIdentity": {
      "abstract": [
        {
          "text": "An abstract Core Foundation-type object representing an identity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SecIdentity"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/SecIdentity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SecIdentity"
        }
      ],
      "role": "symbol",
      "title": "SecIdentity",
      "type": "topic",
      "url": "/documentation/security/secidentity"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecIdentity/title",
          "value": "SecIdentityRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecIdentity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SecIdentityRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1SecIdentity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SecIdentityRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/authorizationcallbacks/gettokenidentities"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
