{
  "abstract": [
    {
      "text": "A four-component vector with 8-bit, signed integer values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLDataType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLDataType/char4"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLDataType@MTLDataTypeChar4",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "char4"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLDataTypeChar4"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLDataType.char4"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "char4"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType": {
      "abstract": [
        {
          "text": "The types of GPU functions, including shaders and compute kernels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDataType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataType"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/char": {
      "abstract": [
        {
          "text": "An 8-bit, signed integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "char"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/char",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeChar"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.char",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/char"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/char2": {
      "abstract": [
        {
          "text": "A two-component vector with 8-bit, signed integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "char2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/char2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeChar2"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.char2",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/char2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/char3": {
      "abstract": [
        {
          "text": "A three-component vector with 8-bit, signed integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "char3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/char3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeChar3"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.char3",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/char3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/char4": {
      "abstract": [
        {
          "text": "A four-component vector with 8-bit, signed integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "char4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/char4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeChar4"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.char4",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/char4"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/uchar": {
      "abstract": [
        {
          "text": "An 8-bit, unsigned integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uchar"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/uchar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeUChar"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.uchar",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/uchar"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/uchar2": {
      "abstract": [
        {
          "text": "A two-component vector with 8-bit, unsigned integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uchar2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/uchar2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeUChar2"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.uchar2",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/uchar2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/uchar3": {
      "abstract": [
        {
          "text": "A three-component vector with 8-bit, unsigned integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uchar3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/uchar3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeUChar3"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.uchar3",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/uchar3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/uchar4": {
      "abstract": [
        {
          "text": "A four-component vector with 8-bit, unsigned integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uchar4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/uchar4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeUChar4"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.uchar4",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/uchar4"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "8-bit-Integer-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDataType/char",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/char2",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/char3",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/uchar",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/uchar2",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/uchar3",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/uchar4"
      ],
      "title": "8-bit Integer Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLDataTypeChar4"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeChar4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLDataType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "8-bit-Integer-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDataType/char",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/char2",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/char3",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/uchar",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/uchar2",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/uchar3",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/uchar4"
              ],
              "title": "8-bit Integer Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLDataTypeChar4"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1uchar3/title",
          "value": "MTLDataTypeUChar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1uchar3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeUChar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1uchar2/title",
          "value": "MTLDataTypeUChar2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1uchar2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeUChar2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1char2/title",
          "value": "MTLDataTypeChar2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1char2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeChar2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1uchar4/title",
          "value": "MTLDataTypeUChar4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1uchar4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeUChar4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1char3/title",
          "value": "MTLDataTypeChar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1char3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeChar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1uchar/title",
          "value": "MTLDataTypeUChar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1uchar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeUChar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType/title",
          "value": "MTLDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1char4/title",
          "value": "MTLDataTypeChar4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1char4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeChar4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1char/title",
          "value": "MTLDataTypeChar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1char/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeChar"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtldatatype/char4"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtldatatype/char4"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
