{
  "abstract": [
    {
      "text": "A four-component vector with 32-bit, signed integer values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLDataType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLDataType/int4"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLDataType@MTLDataTypeInt4",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "int4"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLDataTypeInt4"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLDataType.int4"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "int4"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType": {
      "abstract": [
        {
          "text": "The types of GPU functions, including shaders and compute kernels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDataType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataType"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/int": {
      "abstract": [
        {
          "text": "A 32-bit, signed integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/int",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeInt"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.int",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/int"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/int2": {
      "abstract": [
        {
          "text": "A two-component vector with 32-bit, signed integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "int2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/int2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeInt2"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.int2",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/int2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/int3": {
      "abstract": [
        {
          "text": "A three-component vector with 32-bit, signed integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "int3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/int3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeInt3"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.int3",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/int3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/int4": {
      "abstract": [
        {
          "text": "A four-component vector with 32-bit, signed integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "int4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/int4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeInt4"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.int4",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/int4"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/uint": {
      "abstract": [
        {
          "text": "A 32-bit, unsigned integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/uint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeUInt"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.uint",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/uint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/uint2": {
      "abstract": [
        {
          "text": "A two-component vector with 32-bit, unsigned integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uint2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/uint2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeUInt2"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.uint2",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/uint2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/uint3": {
      "abstract": [
        {
          "text": "A three-component vector with 32-bit, unsigned integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uint3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/uint3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeUInt3"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.uint3",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/uint3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/uint4": {
      "abstract": [
        {
          "text": "A four-component vector with 32-bit, unsigned integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uint4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/uint4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeUInt4"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.uint4",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/uint4"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "32-bit-Integer-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDataType/int",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/int2",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/int3",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/uint",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/uint2",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/uint3",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/uint4"
      ],
      "title": "32-bit Integer Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLDataTypeInt4"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeInt4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLDataType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "32-bit-Integer-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDataType/int",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/int2",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/int3",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/uint",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/uint2",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/uint3",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/uint4"
              ],
              "title": "32-bit Integer Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLDataTypeInt4"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1uint2/title",
          "value": "MTLDataTypeUInt2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1uint2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeUInt2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1int3/title",
          "value": "MTLDataTypeInt3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1int3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeInt3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1uint/title",
          "value": "MTLDataTypeUInt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1uint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeUInt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1uint4/title",
          "value": "MTLDataTypeUInt4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1uint4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeUInt4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1int4/title",
          "value": "MTLDataTypeInt4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1int4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeInt4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1int2/title",
          "value": "MTLDataTypeInt2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1int2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeInt2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1uint3/title",
          "value": "MTLDataTypeUInt3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1uint3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeUInt3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1int/title",
          "value": "MTLDataTypeInt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1int/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeInt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType/title",
          "value": "MTLDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtldatatype/int4"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtldatatype/int4"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
