{
  "abstract": [
    {
      "text": "An ordinary pixel with two components, each of which is a 16-bit, normalized, signed integer value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLDataType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLDataType/rg16Snorm"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLDataType@MTLDataTypeRG16Snorm",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rg16Snorm"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLDataTypeRG16Snorm"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLDataType.rg16Snorm"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rg16Snorm"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The color components are in RG order, which stands for red and green.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType": {
      "abstract": [
        {
          "text": "The types of GPU functions, including shaders and compute kernels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDataType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataType"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/rg11b10Float": {
      "abstract": [
        {
          "text": "A packed 32-bit format with three floating-point color components, two of which are 11-bit values, and one is a 10-bit value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rg11b10Float"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/rg11b10Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeRG11B10Float"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.rg11b10Float",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/rg11b10float"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/rg16Snorm": {
      "abstract": [
        {
          "text": "An ordinary pixel with two components, each of which is a 16-bit, normalized, signed integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rg16Snorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/rg16Snorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeRG16Snorm"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.rg16Snorm",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/rg16snorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/rg16Unorm": {
      "abstract": [
        {
          "text": "An ordinary pixel with two components, each of which is a 16-bit, normalized, unsigned integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rg16Unorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/rg16Unorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeRG16Unorm"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.rg16Unorm",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/rg16unorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/rgb10a2Unorm": {
      "abstract": [
        {
          "text": "A packed 32-bit format with three color components, each of which is a 10-bit, normalized, unsigned integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgb10a2Unorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/rgb10a2Unorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeRGB10A2Unorm"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.rgb10a2Unorm",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/rgb10a2unorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/rgb9e5Float": {
      "abstract": [
        {
          "text": "A packed 32-bit format with three color components, each of which is a 9-bit floating-point value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgb9e5Float"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/rgb9e5Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeRGB9E5Float"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.rgb9e5Float",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/rgb9e5float"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/rgba8Snorm": {
      "abstract": [
        {
          "text": "An ordinary pixel with four components, each of which is an 8-bit, normalized, signed integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba8Snorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/rgba8Snorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeRGBA8Snorm"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.rgba8Snorm",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/rgba8snorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/rgba8Unorm": {
      "abstract": [
        {
          "text": "An ordinary pixel with four components, each of which is an 8-bit, normalized, unsigned integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba8Unorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/rgba8Unorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeRGBA8Unorm"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.rgba8Unorm",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/rgba8unorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/rgba8Unorm_srgb": {
      "abstract": [
        {
          "text": "An ordinary pixel with four components, each of which is an 8-bit, normalized, unsigned integer value in the sRGB color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba8Unorm_srgb"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/rgba8Unorm_srgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeRGBA8Unorm_sRGB"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.rgba8Unorm_srgb",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/rgba8unorm_srgb"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "32-bit-Pixel-Format-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDataType/rgba8Snorm",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/rgba8Unorm",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/rgba8Unorm_srgb",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/rg16Unorm",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/rgb10a2Unorm",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/rgb9e5Float",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/rg11b10Float"
      ],
      "title": "32-bit Pixel Format Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLDataTypeRG16Snorm"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeRG16Snorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLDataType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "32-bit-Pixel-Format-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDataType/rgba8Snorm",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/rgba8Unorm",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/rgba8Unorm_srgb",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/rg16Unorm",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/rgb10a2Unorm",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/rgb9e5Float",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/rg11b10Float"
              ],
              "title": "32-bit Pixel Format Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLDataTypeRG16Snorm"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1rgba8Unorm/title",
          "value": "MTLDataTypeRGBA8Unorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1rgba8Unorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeRGBA8Unorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1rgb9e5Float/title",
          "value": "MTLDataTypeRGB9E5Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1rgb9e5Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeRGB9E5Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1rgba8Unorm_srgb/title",
          "value": "MTLDataTypeRGBA8Unorm_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1rgba8Unorm_srgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeRGBA8Unorm_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1rgba8Snorm/title",
          "value": "MTLDataTypeRGBA8Snorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1rgba8Snorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeRGBA8Snorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType/title",
          "value": "MTLDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1rg16Snorm/title",
          "value": "MTLDataTypeRG16Snorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1rg16Snorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeRG16Snorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1rgb10a2Unorm/title",
          "value": "MTLDataTypeRGB10A2Unorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1rgb10a2Unorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeRGB10A2Unorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1rg16Unorm/title",
          "value": "MTLDataTypeRG16Unorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1rg16Unorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeRG16Unorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1rg11b10Float/title",
          "value": "MTLDataTypeRG11B10Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1rg11b10Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeRG11B10Float"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtldatatype/rg16snorm"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtldatatype/rg16snorm"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
