{
  "abstract": [
    {
      "text": "A four-component vector with 16-bit, signed integer values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLDataType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLDataType/short4"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLDataType@MTLDataTypeShort4",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "short4"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLDataTypeShort4"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLDataType.short4"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "short4"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType": {
      "abstract": [
        {
          "text": "The types of GPU functions, including shaders and compute kernels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDataType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataType"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/short": {
      "abstract": [
        {
          "text": "A 16-bit, signed integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "short"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/short",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeShort"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.short",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/short"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/short2": {
      "abstract": [
        {
          "text": "A two-component vector with 16-bit, signed integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "short2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/short2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeShort2"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.short2",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/short2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/short3": {
      "abstract": [
        {
          "text": "A three-component vector with 16-bit, signed integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "short3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/short3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeShort3"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.short3",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/short3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/short4": {
      "abstract": [
        {
          "text": "A four-component vector with 16-bit, signed integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "short4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/short4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeShort4"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.short4",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/short4"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/ushort": {
      "abstract": [
        {
          "text": "A 16-bit, unsigned integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ushort"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/ushort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeUShort"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.ushort",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/ushort"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/ushort2": {
      "abstract": [
        {
          "text": "A two-component vector with 16-bit, unsigned integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ushort2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/ushort2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeUShort2"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.ushort2",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/ushort2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/ushort3": {
      "abstract": [
        {
          "text": "A three-component vector with 16-bit, unsigned integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ushort3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/ushort3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeUShort3"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.ushort3",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/ushort3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDataType/ushort4": {
      "abstract": [
        {
          "text": "A four-component vector with 16-bit, unsigned integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ushort4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDataType/ushort4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDataTypeUShort4"
        }
      ],
      "role": "symbol",
      "title": "MTLDataType.ushort4",
      "type": "topic",
      "url": "/documentation/metal/mtldatatype/ushort4"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "16-bit-Integer-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDataType/short",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/short2",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/short3",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/ushort",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/ushort2",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/ushort3",
        "doc://com.apple.metal/documentation/Metal/MTLDataType/ushort4"
      ],
      "title": "16-bit Integer Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLDataTypeShort4"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeShort4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLDataType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "16-bit-Integer-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDataType/short",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/short2",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/short3",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/ushort",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/ushort2",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/ushort3",
                "doc://com.apple.metal/documentation/Metal/MTLDataType/ushort4"
              ],
              "title": "16-bit Integer Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLDataTypeShort4"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1ushort/title",
          "value": "MTLDataTypeUShort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1ushort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeUShort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1short/title",
          "value": "MTLDataTypeShort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1short/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeShort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1ushort3/title",
          "value": "MTLDataTypeUShort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1ushort3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeUShort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1short4/title",
          "value": "MTLDataTypeShort4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1short4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeShort4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1short3/title",
          "value": "MTLDataTypeShort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1short3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeShort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1ushort2/title",
          "value": "MTLDataTypeUShort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1ushort2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeUShort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1short2/title",
          "value": "MTLDataTypeShort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1short2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeShort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1ushort4/title",
          "value": "MTLDataTypeUShort4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType~1ushort4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataTypeUShort4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType/title",
          "value": "MTLDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDataType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtldatatype/short4"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtldatatype/short4"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
