{
  "abstract": [
    {
      "text": "Asynchronously finds all instances of the specified array of strings in the document.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/beginFindStrings(_:withOptions:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PDFDocument(im)beginFindStrings:withOptions:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "beginFindStrings"
      },
      {
        "kind": "text",
        "text": "(["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "withOptions"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSString",
        "text": "NSString"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSStringCompareOptions",
        "text": "CompareOptions"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "beginFindStrings:withOptions:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "beginFindStrings(_:withOptions:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "beginFindStrings"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "strings"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "withOptions"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@NSStringCompareOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSStringCompareOptions",
              "text": "CompareOptions"
            },
            {
              "kind": "text",
              "text": " = [])"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method returns immediately. It causes notifications to be issued when searching begins and ends, on each search hit, and when the search proceeds to a new page. For options, refer to ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Strings/Articles/SearchingStrings.html#//apple_ref/doc/uid/20000149",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument": {
      "abstract": [
        {
          "text": "An object that represents PDF data or a PDF file and defines methods for writing, searching, and selecting PDF data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFDocument"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDocument"
        }
      ],
      "role": "symbol",
      "title": "PDFDocument",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/beginFindString(_:withOptions:)": {
      "abstract": [
        {
          "text": "Asynchronously finds all instances of the specified string in the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginFindString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSString",
          "text": "NSString"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSStringCompareOptions",
          "text": "CompareOptions"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/beginFindString(_:withOptions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginFindString:withOptions:"
        }
      ],
      "role": "symbol",
      "title": "beginFindString(_:withOptions:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/beginfindstring(_:withoptions:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/beginFindStrings(_:withOptions:)": {
      "abstract": [
        {
          "text": "Asynchronously finds all instances of the specified array of strings in the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginFindStrings"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "withOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSString",
          "text": "NSString"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSStringCompareOptions",
          "text": "CompareOptions"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/beginFindStrings(_:withOptions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginFindStrings:withOptions:"
        }
      ],
      "role": "symbol",
      "title": "beginFindStrings(_:withOptions:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/beginfindstrings(_:withoptions:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/cancelFindString()": {
      "abstract": [
        {
          "text": "Cancels a search initiated with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/beginFindString(_:withOptions:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelFindString"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/cancelFindString()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelFindString"
        }
      ],
      "role": "symbol",
      "title": "cancelFindString()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/cancelfindstring()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/findString(_:fromSelection:withOptions:)": {
      "abstract": [
        {
          "text": "Synchronously finds the next occurance of a string after the specified selection (or before the selection if you specified ",
          "type": "text"
        },
        {
          "code": "NSBackwardsSearch",
          "type": "codeVoice"
        },
        {
          "text": " as a search option.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "findString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fromSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFSelection",
          "text": "PDFSelection"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "withOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSString",
          "text": "NSString"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSStringCompareOptions",
          "text": "CompareOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFSelection",
          "text": "PDFSelection"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/findString(_:fromSelection:withOptions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "findString:fromSelection:withOptions:"
        }
      ],
      "role": "symbol",
      "title": "findString(_:fromSelection:withOptions:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/findstring(_:fromselection:withoptions:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/findString(_:withOptions:)": {
      "abstract": [
        {
          "text": "Synchronously finds all instances of the specified string in the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "findString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSString",
          "text": "NSString"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSStringCompareOptions",
          "text": "CompareOptions"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFSelection",
          "text": "PDFSelection"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/findString(_:withOptions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "findString:withOptions:"
        }
      ],
      "role": "symbol",
      "title": "findString(_:withOptions:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/findstring(_:withoptions:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isFinding": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether an asynchronous find operation is in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFinding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isFinding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isFinding"
        }
      ],
      "role": "symbol",
      "title": "isFinding",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/isfinding"
    },
    "doc://com.externally.resolved.symbol/c:@E@NSStringCompareOptions": {
      "abstract": [
        {
          "text": "These values represent the options available to many of the string classes’ search and comparison methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSString.CompareOptions"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@NSStringCompareOptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString.CompareOptions",
      "type": "topic",
      "url": "/documentation/foundation/nsstring/compareoptions"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Strings/Articles/SearchingStrings.html#//apple_ref/doc/uid/20000149": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Strings/Articles/SearchingStrings.html#//apple_ref/doc/uid/20000149",
      "title": "Searching, Comparing, and Sorting Strings",
      "titleInlineContent": [
        {
          "text": "Searching, Comparing, and Sorting Strings",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Strings/Articles/SearchingStrings.html#//apple_ref/doc/uid/20000149"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Searching-Documents",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/findString(_:withOptions:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/beginFindString(_:withOptions:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/findString(_:fromSelection:withOptions:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isFinding",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/cancelFindString()"
      ],
      "title": "Searching Documents"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "beginFindStrings:withOptions:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginFindStrings:withOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Searching-Documents",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/findString(_:withOptions:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/beginFindString(_:withOptions:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/findString(_:fromSelection:withOptions:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/isFinding",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/cancelFindString()"
              ],
              "title": "Searching Documents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "beginFindStrings:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSString *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "strings"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "withOptions:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@E@NSStringCompareOptions",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSStringCompareOptions",
                    "text": "NSStringCompareOptions"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "options"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1findString(_:fromSelection:withOptions:)/title",
          "value": "findString:fromSelection:withOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1findString(_:fromSelection:withOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "findString:fromSelection:withOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1findString(_:withOptions:)/title",
          "value": "findString:withOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1findString(_:withOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "findString:withOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1cancelFindString()/title",
          "value": "cancelFindString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1cancelFindString()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancelFindString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1beginFindString(_:withOptions:)/title",
          "value": "beginFindString:withOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1beginFindString(_:withOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginFindString:withOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument/title",
          "value": "PDFDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1isFinding/title",
          "value": "isFinding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1isFinding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isFinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1beginFindStrings(_:withOptions:)/title",
          "value": "beginFindStrings:withOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1beginFindStrings(_:withOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginFindStrings:withOptions:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfdocument/beginfindstrings(_:withoptions:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfdocument/beginfindstrings(_:withoptions:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
