{
  "abstract": [
    {
      "text": "Returns a print operation suitable for printing the PDF document.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/printOperation(for:scalingMode:autoRotate:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PDFDocument(im)printOperationForPrintInfo:scalingMode:autoRotate:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "printOperation"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSPrintInfo",
        "text": "NSPrintInfo"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "scalingMode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@PDFPrintScalingMode",
        "text": "PDFPrintScalingMode"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "autoRotate"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSPrintOperation",
        "text": "NSPrintOperation"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "printOperationForPrintInfo:scalingMode:autoRotate:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "printOperation(for:scalingMode:autoRotate:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "printOperation"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "printInfo"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPrintInfo",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSPrintInfo",
              "text": "NSPrintInfo"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "scalingMode"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "scaleMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFPrintScalingMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PDFPrintScalingMode",
              "text": "PDFPrintScalingMode"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "autoRotate"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "doRotate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPrintOperation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSPrintOperation",
              "text": "NSPrintOperation"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument": {
      "abstract": [
        {
          "text": "An object that represents PDF data or a PDF file and defines methods for writing, searching, and selecting PDF data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFDocument"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDocument"
        }
      ],
      "role": "symbol",
      "title": "PDFDocument",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/printOperation(for:scalingMode:autoRotate:)": {
      "abstract": [
        {
          "text": "Returns a print operation suitable for printing the PDF document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printOperation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "scalingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFPrintScalingMode",
          "text": "PDFPrintScalingMode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "autoRotate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintOperation",
          "text": "NSPrintOperation"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/printOperation(for:scalingMode:autoRotate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printOperationForPrintInfo:scalingMode:autoRotate:"
        }
      ],
      "role": "symbol",
      "title": "printOperation(for:scalingMode:autoRotate:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdocument/printoperation(for:scalingmode:autorotate:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFPrintScalingMode": {
      "abstract": [
        {
          "text": "The type of scaling to be used when printing a page (see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFPrintScalingMode"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFPrintScalingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFPrintScalingMode"
        }
      ],
      "role": "symbol",
      "title": "PDFPrintScalingMode",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfprintscalingmode"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSPrintInfo": {
      "abstract": [
        {
          "text": "An object that stores information that’s used to generate printed output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintInfo"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPrintInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPrintInfo",
      "type": "topic",
      "url": "/documentation/AppKit/NSPrintInfo"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSPrintOperation": {
      "abstract": [
        {
          "text": "An object that controls operations that generate Encapsulated PostScript (EPS) code, Portable Document Format (PDF) code, or print jobs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintOperation"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPrintOperation",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPrintOperation",
      "type": "topic",
      "url": "/documentation/AppKit/NSPrintOperation"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Printing-Documents-for-macOS",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFPrintScalingMode"
      ],
      "title": "Printing Documents for macOS"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "printOperationForPrintInfo:scalingMode:autoRotate:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printOperationForPrintInfo:scalingMode:autoRotate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Printing-Documents-for-macOS",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFPrintScalingMode"
              ],
              "title": "Printing Documents for macOS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPrintOperation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSPrintOperation",
                    "text": "NSPrintOperation"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "printOperationForPrintInfo:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPrintInfo",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSPrintInfo",
                    "text": "NSPrintInfo"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "printInfo"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "scalingMode:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFPrintScalingMode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@PDFPrintScalingMode",
                    "text": "PDFPrintScalingMode"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "scaleMode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "autoRotate:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "doRotate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSPrintOperation/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSPrintOperation"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSPrintInfo/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSPrintInfo"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPrintScalingMode/title",
          "value": "PDFPrintScalingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPrintScalingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFPrintScalingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPrintScalingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFPrintScalingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1printOperation(for:scalingMode:autoRotate:)/title",
          "value": "printOperationForPrintInfo:scalingMode:autoRotate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1printOperation(for:scalingMode:autoRotate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printOperationForPrintInfo:scalingMode:autoRotate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument/title",
          "value": "PDFDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDocument"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfdocument/printoperation(for:scalingmode:autorotate:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfdocument/printoperation(for:scalingmode:autorotate:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
