{"kind":"symbol","metadata":{"roleHeading":"Instance Method","role":"symbol","platforms":[{"beta":false,"introducedAt":"11.0","unavailable":false,"deprecated":false,"name":"iOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS","introducedAt":"11.0"},{"deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"deprecated":false,"beta":false,"unavailable":false,"name":"macOS","introducedAt":"10.4"},{"deprecated":false,"beta":false,"unavailable":false,"name":"tvOS","introducedAt":"11.0"},{"deprecated":false,"beta":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0"}],"navigatorTitle":[{"kind":"identifier","text":"writeToURL:withOptions:"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"write","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withOptions","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"PDFDocumentWriteOption","preciseIdentifier":"c:@T@PDFDocumentWriteOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"modules":[{"name":"PDFKit"}],"title":"write(to:withOptions:)","externalID":"c:objc(cs)PDFDocument(im)writeToURL:withOptions:"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument"]]},"abstract":[{"type":"text","text":"Writes the document to the specified URL with the specified options."}],"seeAlsoSections":[{"anchor":"Related-Documentation","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/dataRepresentation()"],"title":"Related Documentation"},{"generated":true,"anchor":"Writing-Out-the-PDF-Data","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(toFile:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(toFile:withOptions:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(to:)","doc://com.apple.pdfkit/documentation/PDFKit/data-representations"],"title":"Writing Out the PDF Data"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"write","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"url","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:10Foundation3URLV","preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withOptions","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":": [","kind":"text"},{"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentWriteOption","preciseIdentifier":"c:@T@PDFDocumentWriteOption","text":"PDFDocumentWriteOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]? = nil) -> ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"]}]}],"variants":[{"paths":["/documentation/pdfkit/pdfdocument/write(to:withoptions:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/pdfkit/pdfdocument/write(to:withoptions:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(to:withOptions:)"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool","role":"symbol","type":"topic","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}]},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentWriteOption":{"navigatorTitle":[{"text":"PDFDocumentWriteOption","kind":"identifier"}],"role":"symbol","url":"/documentation/pdfkit/pdfdocumentwriteoption","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFDocumentWriteOption","kind":"identifier"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocumentWriteOption","abstract":[{"text":"A structure that specifies file writing options for a document.","type":"text"}],"type":"topic","title":"PDFDocumentWriteOption","kind":"symbol"},"doc://com.apple.pdfkit/documentation/PDFKit":{"role":"collection","identifier":"doc://com.apple.pdfkit/documentation/PDFKit","type":"topic","abstract":[{"type":"text","text":"Display and manipulate PDF documents in your apps."}],"kind":"symbol","title":"PDFKit","url":"/documentation/pdfkit"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(to:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"writeToURL:"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(to:)","type":"topic","abstract":[{"text":"Writes the document to a location specified by the passed-in URL.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"write"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","title":"write(to:)","url":"/documentation/pdfkit/pdfdocument/write(to:)"},"doc://com.externally.resolved.symbol/s:10Foundation3URLV":{"kind":"symbol","url":"/documentation/foundation/url","fragments":[{"text":"struct ","kind":"text"},{"text":"URL","kind":"identifier"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:10Foundation3URLV","abstract":[{"text":"A value that identifies the location of a resource, such as an item on a remote server or the path to a local file.","type":"text"}],"title":"URL","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"title":"Technologies","type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(toFile:withOptions:)":{"title":"write(toFile:withOptions:)","navigatorTitle":[{"text":"writeToFile:withOptions:","kind":"identifier"}],"url":"/documentation/pdfkit/pdfdocument/write(tofile:withoptions:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"write","kind":"identifier"},{"text":"(","kind":"text"},{"text":"toFile","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withOptions","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@T@PDFDocumentWriteOption","text":"PDFDocumentWriteOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"Writes the document to a file at the specified path with the specified options."}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(toFile:withOptions:)"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(to:withOptions:)":{"abstract":[{"text":"Writes the document to the specified URL with the specified options.","type":"text"}],"title":"write(to:withOptions:)","navigatorTitle":[{"text":"writeToURL:withOptions:","kind":"identifier"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(to:withOptions:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"write","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"withOptions","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"PDFDocumentWriteOption","kind":"typeIdentifier","preciseIdentifier":"c:@T@PDFDocumentWriteOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"/documentation/pdfkit/pdfdocument/write(to:withoptions:)","role":"symbol","kind":"symbol","type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument":{"kind":"symbol","url":"/documentation/pdfkit/pdfdocument","navigatorTitle":[{"kind":"identifier","text":"PDFDocument"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PDFDocument"}],"role":"symbol","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument","abstract":[{"type":"text","text":"An object that represents PDF data or a PDF file and defines methods for writing, searching, and selecting PDF data."}],"title":"PDFDocument","type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(toFile:)":{"abstract":[{"text":"Writes the document to a file at the specified path.","type":"text"}],"title":"write(toFile:)","navigatorTitle":[{"text":"writeToFile:","kind":"identifier"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(toFile:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"write","kind":"identifier"},{"text":"(","kind":"text"},{"text":"toFile","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"/documentation/pdfkit/pdfdocument/write(tofile:)","role":"symbol","kind":"symbol","type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/dataRepresentation()":{"title":"dataRepresentation()","navigatorTitle":[{"text":"dataRepresentation","kind":"identifier"}],"url":"/documentation/pdfkit/pdfdocument/datarepresentation()","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataRepresentation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[{"text":"Returns a representation of the document as an ","type":"text"},{"code":"NSData","type":"codeVoice"},{"text":" object.","type":"text"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/dataRepresentation()"},"doc://com.apple.pdfkit/documentation/PDFKit/data-representations":{"title":"Data Representations","role":"collectionGroup","abstract":[{"text":"Operations to represent PDF documents as data objects.","type":"text"}],"type":"topic","url":"/documentation/pdfkit/data-representations","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/data-representations","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"iOS","beta":false,"deprecated":false,"introducedAt":"11.0","unavailable":false},{"deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS","introducedAt":"11.0"},{"deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"deprecated":false,"beta":false,"unavailable":false,"name":"macOS","introducedAt":"10.4"},{"deprecated":false,"beta":false,"unavailable":false,"name":"tvOS","introducedAt":"11.0"},{"deprecated":false,"beta":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"writeToURL:withOptions:","path":"/metadata/title","op":"replace"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"writeToURL:withOptions:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/dataRepresentation()"]},{"generated":true,"title":"Writing Out the PDF Data","anchor":"Writing-Out-the-PDF-Data","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(toFile:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(toFile:withOptions:)","doc://com.apple.pdfkit/documentation/PDFKit/PDFDocument/write(to:)","doc://com.apple.pdfkit/documentation/PDFKit/data-representations"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"writeToURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"url"},{"kind":"text","text":" "},{"kind":"identifier","text":"withOptions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"options"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentWriteOption/title","value":"PDFDocumentWriteOption","op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentWriteOption/fragments","value":[{"kind":"identifier","text":"PDFDocumentWriteOption"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocumentWriteOption/navigatorTitle","value":[{"kind":"identifier","text":"PDFDocumentWriteOption"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1write(to:)/title","value":"writeToURL:","op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1write(to:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"writeToURL:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1write(toFile:withOptions:)/title","value":"writeToFile:withOptions:","op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1write(toFile:withOptions:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"writeToFile:withOptions:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1write(to:withOptions:)/title","value":"writeToURL:withOptions:","op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1write(to:withOptions:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"writeToURL:withOptions:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument/title","value":"PDFDocument","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument/fragments","value":[{"kind":"identifier","text":"PDFDocument"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument/navigatorTitle","value":[{"kind":"identifier","text":"PDFDocument"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1write(toFile:)/title","value":"writeToFile:"},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1write(toFile:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"writeToFile:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1dataRepresentation()/title","value":"dataRepresentation"},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDocument~1dataRepresentation()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dataRepresentation"}]}]}],"diffAvailability":{"major":{"change":"modified","platform":"Xcode","versions":["16.0","16.3 beta 2"]}},"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}