{
  "abstract": [
    {
      "text": "A new value passes the comparison test if it is less than or equal to the existing value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLCompareFunction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/lessEqual"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLCompareFunction@MTLCompareFunctionLessEqual",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "lessEqual"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLCompareFunctionLessEqual"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLCompareFunction.lessEqual"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "lessEqual"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompareFunction": {
      "abstract": [
        {
          "text": "Options used to specify how a sample compare operation should be performed on a depth texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCompareFunction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompareFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCompareFunction"
        }
      ],
      "role": "symbol",
      "title": "MTLCompareFunction",
      "type": "topic",
      "url": "/documentation/metal/mtlcomparefunction"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/always": {
      "abstract": [
        {
          "text": "A new value always passes the comparison test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "always"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/always",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCompareFunctionAlways"
        }
      ],
      "role": "symbol",
      "title": "MTLCompareFunction.always",
      "type": "topic",
      "url": "/documentation/metal/mtlcomparefunction/always"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/equal": {
      "abstract": [
        {
          "text": "A new value passes the comparison test if it is equal to the existing value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "equal"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/equal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCompareFunctionEqual"
        }
      ],
      "role": "symbol",
      "title": "MTLCompareFunction.equal",
      "type": "topic",
      "url": "/documentation/metal/mtlcomparefunction/equal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/greater": {
      "abstract": [
        {
          "text": "A new value passes the comparison test if it is greater than the existing value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "greater"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/greater",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCompareFunctionGreater"
        }
      ],
      "role": "symbol",
      "title": "MTLCompareFunction.greater",
      "type": "topic",
      "url": "/documentation/metal/mtlcomparefunction/greater"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/greaterEqual": {
      "abstract": [
        {
          "text": "A new value passes the comparison test if it is greater than or equal to the existing value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "greaterEqual"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/greaterEqual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCompareFunctionGreaterEqual"
        }
      ],
      "role": "symbol",
      "title": "MTLCompareFunction.greaterEqual",
      "type": "topic",
      "url": "/documentation/metal/mtlcomparefunction/greaterequal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/less": {
      "abstract": [
        {
          "text": "A new value passes the comparison test if it is less than the existing value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "less"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/less",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCompareFunctionLess"
        }
      ],
      "role": "symbol",
      "title": "MTLCompareFunction.less",
      "type": "topic",
      "url": "/documentation/metal/mtlcomparefunction/less"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/lessEqual": {
      "abstract": [
        {
          "text": "A new value passes the comparison test if it is less than or equal to the existing value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lessEqual"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/lessEqual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCompareFunctionLessEqual"
        }
      ],
      "role": "symbol",
      "title": "MTLCompareFunction.lessEqual",
      "type": "topic",
      "url": "/documentation/metal/mtlcomparefunction/lessequal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/never": {
      "abstract": [
        {
          "text": "A new value never passes the comparison test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "never"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/never",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCompareFunctionNever"
        }
      ],
      "role": "symbol",
      "title": "MTLCompareFunction.never",
      "type": "topic",
      "url": "/documentation/metal/mtlcomparefunction/never"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/notEqual": {
      "abstract": [
        {
          "text": "A new value passes the comparison test if it is not equal to the existing value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notEqual"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/notEqual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCompareFunctionNotEqual"
        }
      ],
      "role": "symbol",
      "title": "MTLCompareFunction.notEqual",
      "type": "topic",
      "url": "/documentation/metal/mtlcomparefunction/notequal"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Compare-function-options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/never",
        "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/less",
        "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/equal",
        "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/greater",
        "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/notEqual",
        "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/greaterEqual",
        "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/always"
      ],
      "title": "Compare function options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLCompareFunctionLessEqual"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCompareFunctionLessEqual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLCompareFunction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Compare-function-options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/never",
                "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/less",
                "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/equal",
                "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/greater",
                "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/notEqual",
                "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/greaterEqual",
                "doc://com.apple.metal/documentation/Metal/MTLCompareFunction/always"
              ],
              "title": "Compare function options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLCompareFunctionLessEqual"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction~1equal/title",
          "value": "MTLCompareFunctionEqual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction~1equal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCompareFunctionEqual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction/title",
          "value": "MTLCompareFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCompareFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCompareFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction~1less/title",
          "value": "MTLCompareFunctionLess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction~1less/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCompareFunctionLess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction~1lessEqual/title",
          "value": "MTLCompareFunctionLessEqual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction~1lessEqual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCompareFunctionLessEqual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction~1always/title",
          "value": "MTLCompareFunctionAlways"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction~1always/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCompareFunctionAlways"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction~1greater/title",
          "value": "MTLCompareFunctionGreater"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction~1greater/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCompareFunctionGreater"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction~1notEqual/title",
          "value": "MTLCompareFunctionNotEqual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction~1notEqual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCompareFunctionNotEqual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction~1never/title",
          "value": "MTLCompareFunctionNever"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction~1never/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCompareFunctionNever"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction~1greaterEqual/title",
          "value": "MTLCompareFunctionGreaterEqual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction~1greaterEqual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCompareFunctionGreaterEqual"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlcomparefunction/lessequal"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlcomparefunction/lessequal"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
