{
  "abstract": [
    {
      "text": "Indicates that the uniform variable holds a ",
      "type": "text"
    },
    {
      "code": "2 x 2",
      "type": "codeVoice"
    },
    {
      "text": " matrix of four 32-bit floating-point values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatMatrix2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKUniformType@SKUniformTypeFloatMatrix2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "floatMatrix2"
      }
    ],
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKUniformTypeFloatMatrix2"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SKUniformType.floatMatrix2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "floatMatrix2"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType": {
      "abstract": [
        {
          "text": "An enumerated type to identify the type of a uniform object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKUniformType"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKUniformType"
        }
      ],
      "role": "symbol",
      "title": "SKUniformType",
      "type": "topic",
      "url": "/documentation/spritekit/skuniformtype"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/float": {
      "abstract": [
        {
          "text": "Indicates that the uniform variable holds a 32-bit floating-point value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "float"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKUniformTypeFloat"
        }
      ],
      "role": "symbol",
      "title": "SKUniformType.float",
      "type": "topic",
      "url": "/documentation/spritekit/skuniformtype/float"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatMatrix2": {
      "abstract": [
        {
          "text": "Indicates that the uniform variable holds a ",
          "type": "text"
        },
        {
          "code": "2 x 2",
          "type": "codeVoice"
        },
        {
          "text": " matrix of four 32-bit floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "floatMatrix2"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatMatrix2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKUniformTypeFloatMatrix2"
        }
      ],
      "role": "symbol",
      "title": "SKUniformType.floatMatrix2",
      "type": "topic",
      "url": "/documentation/spritekit/skuniformtype/floatmatrix2"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatMatrix3": {
      "abstract": [
        {
          "text": "Indicates that the uniform variable holds a ",
          "type": "text"
        },
        {
          "code": "3 x 3",
          "type": "codeVoice"
        },
        {
          "text": " matrix of four 32-bit floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "floatMatrix3"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatMatrix3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKUniformTypeFloatMatrix3"
        }
      ],
      "role": "symbol",
      "title": "SKUniformType.floatMatrix3",
      "type": "topic",
      "url": "/documentation/spritekit/skuniformtype/floatmatrix3"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatMatrix4": {
      "abstract": [
        {
          "text": "Indicates that the uniform variable holds a ",
          "type": "text"
        },
        {
          "code": "3 x 3",
          "type": "codeVoice"
        },
        {
          "text": " matrix of four 32-bit floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "floatMatrix4"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatMatrix4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKUniformTypeFloatMatrix4"
        }
      ],
      "role": "symbol",
      "title": "SKUniformType.floatMatrix4",
      "type": "topic",
      "url": "/documentation/spritekit/skuniformtype/floatmatrix4"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatVector2": {
      "abstract": [
        {
          "text": "Indicates that the uniform variable holds a vector of two 32-bit floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "floatVector2"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatVector2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKUniformTypeFloatVector2"
        }
      ],
      "role": "symbol",
      "title": "SKUniformType.floatVector2",
      "type": "topic",
      "url": "/documentation/spritekit/skuniformtype/floatvector2"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatVector3": {
      "abstract": [
        {
          "text": "Indicates that the uniform variable holds a vector of three 32-bit floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "floatVector3"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatVector3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKUniformTypeFloatVector3"
        }
      ],
      "role": "symbol",
      "title": "SKUniformType.floatVector3",
      "type": "topic",
      "url": "/documentation/spritekit/skuniformtype/floatvector3"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatVector4": {
      "abstract": [
        {
          "text": "Indicates that the uniform variable holds a vector of four 32-bit floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "floatVector4"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatVector4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKUniformTypeFloatVector4"
        }
      ],
      "role": "symbol",
      "title": "SKUniformType.floatVector4",
      "type": "topic",
      "url": "/documentation/spritekit/skuniformtype/floatvector4"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/none": {
      "abstract": [
        {
          "text": "Indicates that the uniform variable does not currently hold any data. A uniform object has this type until the first time its value is set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKUniformTypeNone"
        }
      ],
      "role": "symbol",
      "title": "SKUniformType.none",
      "type": "topic",
      "url": "/documentation/spritekit/skuniformtype/none"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/texture": {
      "abstract": [
        {
          "text": "Indicates that the uniform variable holds a reference to a SpriteKit texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "texture"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/texture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKUniformTypeTexture"
        }
      ],
      "role": "symbol",
      "title": "SKUniformType.texture",
      "type": "topic",
      "url": "/documentation/spritekit/skuniformtype/texture"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/none",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/float",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatVector2",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatVector3",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatVector4",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatMatrix3",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatMatrix4",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/texture"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKUniformTypeFloatMatrix2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKUniformTypeFloatMatrix2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.spritekit/documentation/SpriteKit",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/none",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/float",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatVector2",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatVector3",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatVector4",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatMatrix3",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/floatMatrix4",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKUniformType/texture"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SKUniformTypeFloatMatrix2"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType~1floatVector2/title",
          "value": "SKUniformTypeFloatVector2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType~1floatVector2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKUniformTypeFloatVector2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType~1floatMatrix4/title",
          "value": "SKUniformTypeFloatMatrix4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType~1floatMatrix4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKUniformTypeFloatMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType~1floatMatrix2/title",
          "value": "SKUniformTypeFloatMatrix2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType~1floatMatrix2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKUniformTypeFloatMatrix2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType~1floatVector3/title",
          "value": "SKUniformTypeFloatVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType~1floatVector3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKUniformTypeFloatVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType~1floatVector4/title",
          "value": "SKUniformTypeFloatVector4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType~1floatVector4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKUniformTypeFloatVector4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType~1floatMatrix3/title",
          "value": "SKUniformTypeFloatMatrix3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType~1floatMatrix3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKUniformTypeFloatMatrix3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType~1float/title",
          "value": "SKUniformTypeFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType~1float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKUniformTypeFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType~1texture/title",
          "value": "SKUniformTypeTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType~1texture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKUniformTypeTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType~1none/title",
          "value": "SKUniformTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKUniformTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType/title",
          "value": "SKUniformType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKUniformType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKUniformType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKUniformType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/skuniformtype/floatmatrix2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/skuniformtype/floatmatrix2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
