{
  "abstract": [
    {
      "text": "Retrieves a descriptor from the cache or the device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/descriptorWithType:length:index:languageID:requestType:requestRecipient:error:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)IOUSBHostObject(im)descriptorWithType:length:index:languageID:requestType:requestRecipient:error:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "descriptorWithType:length:index:languageID:requestType:requestRecipient:error:"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "descriptorWithType:length:index:languageID:requestType:requestRecipient:error:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "descriptorWithType:length:index:languageID:requestType:requestRecipient:error:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@IOUSBDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@IOUSBDescriptor",
              "text": "IOUSBDescriptor"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "descriptorWithType:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@tIOUSBDescriptorType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@tIOUSBDescriptorType",
              "text": "tIOUSBDescriptorType"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "type"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "length:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "length"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "index:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "index"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "languageID:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "languageID"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "requestType:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@tIOUSBDeviceRequestTypeValue",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@tIOUSBDeviceRequestTypeValue",
              "text": "tIOUSBDeviceRequestTypeValue"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "requestType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "requestRecipient:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@tIOUSBDeviceRequestRecipientValue",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@tIOUSBDeviceRequestRecipientValue",
              "text": "tIOUSBDeviceRequestRecipientValue"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "requestRecipient"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "error:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSError",
              "text": "NSError"
            },
            {
              "kind": "text",
              "text": " * *) "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The type of the descriptor to find.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "type"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A reference to an ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/objectivec/nsuinteger",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " that updates with the length of the descriptor. You can use ",
                  "type": "text"
                },
                {
                  "code": "wLength",
                  "type": "codeVoice"
                },
                {
                  "text": " when searching for variable-length configuration or BOS descriptors, or when searching for nonstandard descriptor types.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "length"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A descriptor index value that is the low byte of ",
                  "type": "text"
                },
                {
                  "code": "wValue",
                  "type": "codeVoice"
                },
                {
                  "text": " of the ",
                  "type": "text"
                },
                {
                  "code": "SET_DESCRIPTOR",
                  "type": "codeVoice"
                },
                {
                  "text": " control request (See USB 3.2, 9.4.8.). The default is value is ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "index"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A descriptor language ID that’s the ",
                  "type": "text"
                },
                {
                  "code": "wIndex",
                  "type": "codeVoice"
                },
                {
                  "text": " of the ",
                  "type": "text"
                },
                {
                  "code": "SET_DESCRIPTOR",
                  "type": "codeVoice"
                },
                {
                  "text": " control request (See USB 3.2, 9.4.8.). The default value is ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "languageID"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The request type for a ",
                  "type": "text"
                },
                {
                  "code": "GET_DESCRIPTOR",
                  "type": "codeVoice"
                },
                {
                  "text": " control request. The default value is ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/iokit/tiousbdevicerequesttypevalue/kiousbdevicerequesttypevaluestandard",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "requestType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The request recipient for a ",
                  "type": "text"
                },
                {
                  "code": "GET_DESCRIPTOR",
                  "type": "codeVoice"
                },
                {
                  "text": " control request. The default value is ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/iokit/tiousbdevicerequestrecipientvalue/kiousbdevicerequestrecipientvaluedevice",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "requestRecipient"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " that contains an ",
                  "type": "text"
                },
                {
                  "text": "doc://com.apple.documentation/documentation/kernel/ioreturn",
                  "type": "text"
                },
                {
                  "text": " value on failure.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "error"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A pointer to the cached descriptor, or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if no matching descriptor returns.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method searches the descriptor cache for the descriptor that matches the input arguments. If the descriptor isn’t in the cache, the method issues a ",
              "type": "text"
            },
            {
              "code": "GET_DESCRIPTOR",
              "type": "codeVoice"
            },
            {
              "text": " control request (See USB 3.2, 9.4.3.) to retrieve the descriptor from the device. If the device request is successful, the method adds the retrieved descriptor to the cache.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nserror": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.apple.documentation/documentation/iokit/tiousbdevicerequestrecipientvalue/kiousbdevicerequestrecipientvaluedevice": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/iokit/tiousbdevicerequestrecipientvalue/kiousbdevicerequestrecipientvaluedevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "kIOUSBDeviceRequestRecipientValueDevice",
      "type": "topic",
      "url": "/documentation/iokit/tiousbdevicerequestrecipientvalue/kiousbdevicerequestrecipientvaluedevice"
    },
    "doc://com.apple.documentation/documentation/iokit/tiousbdevicerequesttypevalue/kiousbdevicerequesttypevaluestandard": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/iokit/tiousbdevicerequesttypevalue/kiousbdevicerequesttypevaluestandard",
      "kind": "symbol",
      "role": "symbol",
      "title": "kIOUSBDeviceRequestTypeValueStandard",
      "type": "topic",
      "url": "/documentation/iokit/tiousbdevicerequesttypevalue/kiousbdevicerequesttypevaluestandard"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsuinteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsuinteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject": {
      "abstract": [
        {
          "text": "This class provides basic functionality for sending device requests and retrieving descriptors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostObject"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostObject"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostObject",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostobject"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/descriptorWithType:length:error:": {
      "abstract": [
        {
          "text": "Retrieves a descriptor with default arguments from the cache or the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "descriptorWithType:length:error:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/descriptorWithType:length:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorWithType:length:error:"
        }
      ],
      "role": "symbol",
      "title": "descriptorWithType:length:error:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostobject/descriptorwithtype:length:error:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/descriptorWithType:length:index:languageID:error:": {
      "abstract": [
        {
          "text": "Retrieves a string descriptor from the cache or the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "descriptorWithType:length:index:languageID:error:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/descriptorWithType:length:index:languageID:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorWithType:length:index:languageID:error:"
        }
      ],
      "role": "symbol",
      "title": "descriptorWithType:length:index:languageID:error:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostobject/descriptorwithtype:length:index:languageid:error:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/descriptorWithType:length:index:languageID:requestType:requestRecipient:error:": {
      "abstract": [
        {
          "text": "Retrieves a descriptor from the cache or the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "descriptorWithType:length:index:languageID:requestType:requestRecipient:error:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/descriptorWithType:length:index:languageID:requestType:requestRecipient:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorWithType:length:index:languageID:requestType:requestRecipient:error:"
        }
      ],
      "role": "symbol",
      "title": "descriptorWithType:length:index:languageID:requestType:requestRecipient:error:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostobject/descriptorwithtype:length:index:languageid:requesttype:requestrecipient:error:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/stringWithIndex:error:": {
      "abstract": [
        {
          "text": "Retrieves an English-language string from a string descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "stringWithIndex:error:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/stringWithIndex:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringWithIndex:error:"
        }
      ],
      "role": "symbol",
      "title": "stringWithIndex:error:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostobject/stringwithindex:error:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/stringWithIndex:languageID:error:": {
      "abstract": [
        {
          "text": "Retrieves a string from a string descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "stringWithIndex:languageID:error:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/stringWithIndex:languageID:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringWithIndex:languageID:error:"
        }
      ],
      "role": "symbol",
      "title": "stringWithIndex:languageID:error:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostobject/stringwithindex:languageid:error:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/parsing-usb-descriptors": {
      "abstract": [
        {
          "text": "Extract information from various USB descriptors using helper methods.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/parsing-usb-descriptors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Parsing USB Descriptors",
      "type": "topic",
      "url": "/documentation/iousbhost/parsing-usb-descriptors"
    },
    "doc://com.externally.resolved.symbol/c:@E@tIOUSBDescriptorType": {
      "abstract": [
        {
          "text": "Constants describing the types of descriptors available for a USB device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tIOUSBDescriptorType"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:i",
          "text": "unsigned int"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@tIOUSBDescriptorType",
      "kind": "symbol",
      "role": "symbol",
      "title": "tIOUSBDescriptorType",
      "type": "topic",
      "url": "/documentation/USBDriverKit/tIOUSBDescriptorType"
    },
    "doc://com.externally.resolved.symbol/c:@E@tIOUSBDeviceRequestRecipientValue": {
      "abstract": [
        {
          "text": "Constants indicating the type of object that receives the results of a request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tIOUSBDeviceRequestRecipientValue"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:i",
          "text": "unsigned int"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@tIOUSBDeviceRequestRecipientValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "tIOUSBDeviceRequestRecipientValue",
      "type": "topic",
      "url": "/documentation/USBDriverKit/tIOUSBDeviceRequestRecipientValue"
    },
    "doc://com.externally.resolved.symbol/c:@E@tIOUSBDeviceRequestTypeValue": {
      "abstract": [
        {
          "text": "Constants indicating the type of request to make from a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tIOUSBDeviceRequestTypeValue"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:i",
          "text": "unsigned int"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@tIOUSBDeviceRequestTypeValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "tIOUSBDeviceRequestTypeValue",
      "type": "topic",
      "url": "/documentation/USBDriverKit/tIOUSBDeviceRequestTypeValue"
    },
    "doc://com.externally.resolved.symbol/c:@T@IOUSBDescriptor": {
      "abstract": [
        {
          "text": "The base descriptor type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typedef"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBDescriptorHeader",
          "text": "IOUSBDescriptorHeader"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBDescriptor"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@IOUSBDescriptor",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOUSBDescriptor",
      "type": "topic",
      "url": "/documentation/USBDriverKit/IOUSBDescriptor"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Retrieving-Base-Class-Descriptors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/parsing-usb-descriptors",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/descriptorWithType:length:error:",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/descriptorWithType:length:index:languageID:error:",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/stringWithIndex:languageID:error:",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObject/stringWithIndex:error:"
      ],
      "title": "Retrieving Base Class Descriptors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostObject/title",
          "value": "IOUSBHostObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhostobject/descriptorwithtype:length:index:languageid:requesttype:requestrecipient:error:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
