{
  "abstract": [
    {
      "text": "The notification has no user-facing content, but should.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.usernotifications/documentation/UserNotifications",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/notificationInvalidNoContent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11UNErrorCodeLeV28notificationInvalidNoContentSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "notificationInvalidNoContent"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC11UNErrorCodeLeV",
        "text": "UNError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UNErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "User Notifications"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "notificationInvalidNoContent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "notificationInvalidNoContent"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC11UNErrorCodeLeV",
              "text": "UNError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UNErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "UserNotifications-PageImage-card.png": {
      "alt": "[A notification interface displayed on the lock screen of an iOS device.]",
      "identifier": "UserNotifications-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/074de9a9213bf2905d67fae5eb46e4f8/UserNotifications-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5733742e1c084fc202b3c92df9083686/UserNotifications-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications": {
      "abstract": [
        {
          "text": "Push user-facing notifications to the user’s device from a server, or generate them locally from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications",
      "images": [
        {
          "identifier": "UserNotifications-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "User Notifications",
      "type": "topic",
      "url": "/documentation/usernotifications"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError": {
      "abstract": [
        {
          "text": "An object that represents a notification error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNError"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNError"
        }
      ],
      "role": "symbol",
      "title": "UNError",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code": {
      "abstract": [
        {
          "text": "Constants that identify notification errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "UNError.Code",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/code"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/attachmentCorrupt": {
      "abstract": [
        {
          "text": "The file for an attachment is corrupt.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attachmentCorrupt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11UNErrorCodeLeV",
          "text": "UNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/attachmentCorrupt",
      "kind": "symbol",
      "role": "symbol",
      "title": "attachmentCorrupt",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/attachmentcorrupt"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/attachmentInvalidFileSize": {
      "abstract": [
        {
          "text": "An attachment is too large.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attachmentInvalidFileSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11UNErrorCodeLeV",
          "text": "UNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/attachmentInvalidFileSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "attachmentInvalidFileSize",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/attachmentinvalidfilesize"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/attachmentInvalidURL": {
      "abstract": [
        {
          "text": "The URL for an attachment was invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attachmentInvalidURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11UNErrorCodeLeV",
          "text": "UNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/attachmentInvalidURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "attachmentInvalidURL",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/attachmentinvalidurl"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/attachmentMoveIntoDataStoreFailed": {
      "abstract": [
        {
          "text": "An error occurred when trying to move an attachment to the system data store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attachmentMoveIntoDataStoreFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11UNErrorCodeLeV",
          "text": "UNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/attachmentMoveIntoDataStoreFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "attachmentMoveIntoDataStoreFailed",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/attachmentmoveintodatastorefailed"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/attachmentNotInDataStore": {
      "abstract": [
        {
          "text": "The specified attachment is not in the system data store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attachmentNotInDataStore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11UNErrorCodeLeV",
          "text": "UNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/attachmentNotInDataStore",
      "kind": "symbol",
      "role": "symbol",
      "title": "attachmentNotInDataStore",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/attachmentnotindatastore"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/attachmentUnrecognizedType": {
      "abstract": [
        {
          "text": "The file type of an attachment is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attachmentUnrecognizedType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11UNErrorCodeLeV",
          "text": "UNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/attachmentUnrecognizedType",
      "kind": "symbol",
      "role": "symbol",
      "title": "attachmentUnrecognizedType",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/attachmentunrecognizedtype"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/badgeInputInvalid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badgeInputInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11UNErrorCodeLeV",
          "text": "UNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/badgeInputInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "badgeInputInvalid",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/badgeinputinvalid"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/contentProvidingInvalid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentProvidingInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11UNErrorCodeLeV",
          "text": "UNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/contentProvidingInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentProvidingInvalid",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/contentprovidinginvalid"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/contentProvidingObjectNotAllowed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentProvidingObjectNotAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11UNErrorCodeLeV",
          "text": "UNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/contentProvidingObjectNotAllowed",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentProvidingObjectNotAllowed",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/contentprovidingobjectnotallowed"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/notificationInvalidNoContent": {
      "abstract": [
        {
          "text": "The notification has no user-facing content, but should.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationInvalidNoContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11UNErrorCodeLeV",
          "text": "UNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/notificationInvalidNoContent",
      "kind": "symbol",
      "role": "symbol",
      "title": "notificationInvalidNoContent",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/notificationinvalidnocontent"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/notificationInvalidNoDate": {
      "abstract": [
        {
          "text": "The notification does not have an associated date, but should.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationInvalidNoDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11UNErrorCodeLeV",
          "text": "UNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/notificationInvalidNoDate",
      "kind": "symbol",
      "role": "symbol",
      "title": "notificationInvalidNoDate",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/notificationinvalidnodate"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/notificationsNotAllowed": {
      "abstract": [
        {
          "text": "Notifications are not allowed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationsNotAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11UNErrorCodeLeV",
          "text": "UNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/notificationsNotAllowed",
      "kind": "symbol",
      "role": "symbol",
      "title": "notificationsNotAllowed",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/notificationsnotallowed"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/notificationsNotAllowed",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/attachmentInvalidURL",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/attachmentUnrecognizedType",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/attachmentInvalidFileSize",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/attachmentNotInDataStore",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/attachmentMoveIntoDataStoreFailed",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/attachmentCorrupt",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/notificationInvalidNoDate",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/contentProvidingInvalid",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/contentProvidingObjectNotAllowed",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/badgeInputInvalid"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code/title",
          "value": "UNErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/usernotifications/unerror/notificationinvalidnocontent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
