{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:)"},"metadata":{"externalID":"c:objc(cs)HKQuery(cm)predicateForWorkoutsWithWorkoutActivityType:","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForWorkouts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"HKWorkoutActivityType","preciseIdentifier":"c:@E@HKWorkoutActivityType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate"}],"platforms":[{"unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"deprecated":false,"unavailable":false,"name":"iPadOS","beta":false},{"beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false},{"deprecated":false,"name":"macOS","unavailable":false,"beta":false},{"beta":false,"unavailable":false,"deprecated":false,"name":"visionOS"},{"unavailable":false,"beta":false,"name":"watchOS","deprecated":false}],"symbolKind":"method","navigatorTitle":[{"text":"predicateForWorkoutsWithWorkoutActivityType:","kind":"identifier"}],"role":"symbol","title":"predicateForWorkouts(with:)","roleHeading":"Type Method","extendedModule":"HealthKit","modules":[{"name":"HealthKit"}]},"kind":"symbol","abstract":[{"type":"text","text":"Returns a predicate for matching workouts based on the type of activity."}],"seeAlsoSections":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKWorkout/workoutActivityType","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutType"],"title":"Related Documentation","anchor":"Related-Documentation"},{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-5irg9","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(activityPredicate:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:duration:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:averageQuantity:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:maximumQuantity:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:minimumQuantity:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:sumQuantity:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalDistance:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalEnergyBurned:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalFlightsClimbed:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalSwimmingStrokeCount:)"],"generated":true,"title":"Creating workout predicates","anchor":"Creating-workout-predicates"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKQuery"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForWorkouts","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"workoutActivityType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@HKWorkoutActivityType","kind":"typeIdentifier","text":"HKWorkoutActivityType","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate","text":"NSPredicate","preciseIdentifier":"c:objc(cs)NSPredicate"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"workoutActivityType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of activity. For a list of valid workout activities, see "},{"type":"reference","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType","isActive":true},{"text":".","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"A predicate for matching workouts based on the type of activity."}],"type":"paragraph"}]},{"kind":"content","content":[{"anchor":"Discussion","text":"Discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this convenience method to create a predicate that matches workouts based on their activity. The following sample uses both the convenience method and a predicate format string to create equivalent predicates."}]},{"tabs":[{"title":"Swift","content":[{"code":["let workout = HKQuery.predicateForWorkoutsWithWorkoutActivityType(.Curling)"," "," ","let explicitWorkout = NSPredicate(format: \"%K == %d\",","                                  HKPredicateKeyPathWorkoutType,","                                  HKWorkoutActivityType.Curling.rawValue)"],"type":"codeListing","syntax":"swift"}]},{"title":"Objective-C","content":[{"syntax":"objc","code":["NSPredicate *workout =","    [HKQuery predicateForWorkoutsWithWorkoutActivityType:","     HKWorkoutActivityTypeCurling];"," ","NSPredicate *explicitWorkout =","[NSPredicate predicateWithFormat:@\"%K == %d\","," HKPredicateKeyPathWorkoutType,"," HKWorkoutActivityTypeCurling];"],"type":"codeListing"}]}],"type":"tabNavigator"}]}],"variants":[{"paths":["/documentation/healthkit/hkquery/predicateforworkouts(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/healthkit/hkquery/predicateforworkouts(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:averageQuantity:)":{"url":"/documentation/healthkit/hkquery/predicateforworkouts(operatortype:quantitytype:averagequantity:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"predicateForWorkoutsWithOperatorType:quantityType:averageQuantity:","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:averageQuantity:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"predicateForWorkouts","kind":"identifier"},{"kind":"text","text":"("},{"text":"operatorType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSComparisonPredicate","kind":"typeIdentifier","text":"NSComparisonPredicate"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSPredicateOperatorType","text":"Operator"},{"text":", ","kind":"text"},{"text":"quantityType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKQuantityType","kind":"typeIdentifier","text":"HKQuantityType"},{"kind":"text","text":", "},{"text":"averageQuantity","kind":"externalParam"},{"kind":"text","text":": "},{"text":"HKQuantity","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantity"},{"text":") -> ","kind":"text"},{"text":"NSPredicate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate"}],"title":"predicateForWorkouts(operatorType:quantityType:averageQuantity:)","abstract":[{"type":"text","text":"Returns a predicate for matching workouts based the average value of an associated quantity type."}]},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery":{"title":"HKQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKQuery"}],"url":"/documentation/healthkit/hkquery","abstract":[{"type":"text","text":"An abstract class for all the query classes in HealthKit."}],"kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKQuery"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(activityPredicate:)":{"type":"topic","url":"/documentation/healthkit/hkquery/predicateforworkouts(activitypredicate:)","title":"predicateForWorkouts(activityPredicate:)","role":"symbol","kind":"symbol","abstract":[{"text":"Returns a predicate for matching workouts based on the associated workout activities.","type":"text"}],"navigatorTitle":[{"text":"predicateForWorkoutsWithActivityPredicate:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForWorkouts","kind":"identifier"},{"text":"(","kind":"text"},{"text":"activityPredicate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPredicate","preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSPredicate","preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(activityPredicate:)"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType":{"url":"/documentation/healthkit/hkworkoutactivitytype","type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType","title":"HKWorkoutActivityType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKWorkoutActivityType","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"HKWorkoutActivityType","kind":"identifier"}],"abstract":[{"text":"The type of activity performed during a workout.","type":"text"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:duration:)":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:duration:)","url":"/documentation/healthkit/hkquery/predicateforworkouts(with:duration:)","title":"predicateForWorkouts(with:duration:)","abstract":[{"type":"text","text":"Returns a predicate for matching workouts based on their duration."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForWorkouts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSComparisonPredicate","kind":"typeIdentifier","text":"NSComparisonPredicate"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSPredicateOperatorType","kind":"typeIdentifier","text":"Operator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier","text":"NSPredicate"}],"navigatorTitle":[{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:duration:"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:maximumQuantity:)":{"type":"topic","title":"predicateForWorkouts(operatorType:quantityType:maximumQuantity:)","abstract":[{"type":"text","text":"Returns a predicate for matching workout activities based the maximum value of an associated quantity type."}],"role":"symbol","url":"/documentation/healthkit/hkquery/predicateforworkouts(operatortype:quantitytype:maximumquantity:)","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForWorkouts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"operatorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSComparisonPredicate","text":"NSComparisonPredicate"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSPredicateOperatorType","text":"Operator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"quantityType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantityType","text":"HKQuantityType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maximumQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantity","text":"HKQuantity"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:maximumQuantity:)","navigatorTitle":[{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:quantityType:maximumQuantity:"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:sumQuantity:)":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForWorkouts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"operatorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSComparisonPredicate","text":"NSComparisonPredicate"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSPredicateOperatorType","text":"Operator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"quantityType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantityType","text":"HKQuantityType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sumQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantity","text":"HKQuantity"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate"}],"title":"predicateForWorkouts(operatorType:quantityType:sumQuantity:)","navigatorTitle":[{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:quantityType:sumQuantity:"}],"kind":"symbol","abstract":[{"type":"text","text":"Returns a predicate for matching workout activities based the sum of an associated quantity type."}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:sumQuantity:)","role":"symbol","url":"/documentation/healthkit/hkquery/predicateforworkouts(operatortype:quantitytype:sumquantity:)"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:)":{"url":"/documentation/healthkit/hkquery/predicateforworkouts(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"predicateForWorkoutsWithWorkoutActivityType:","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForWorkouts","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKWorkoutActivityType","preciseIdentifier":"c:@E@HKWorkoutActivityType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSPredicate","preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier"}],"title":"predicateForWorkouts(with:)","abstract":[{"type":"text","text":"Returns a predicate for matching workouts based on the type of activity."}]},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalFlightsClimbed:)":{"url":"/documentation/healthkit/hkquery/predicateforworkouts(with:totalflightsclimbed:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForWorkouts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSComparisonPredicate","kind":"typeIdentifier","text":"NSComparisonPredicate"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSPredicateOperatorType","kind":"typeIdentifier","text":"Operator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalFlightsClimbed"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)HKQuantity","kind":"typeIdentifier","text":"HKQuantity"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier","text":"NSPredicate"}],"title":"predicateForWorkouts(with:totalFlightsClimbed:)","type":"topic","abstract":[{"type":"text","text":"Returns a predicate that matches workout samples based on the number of flights climbed."}],"kind":"symbol","deprecated":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:totalFlightsClimbed:"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalFlightsClimbed:)"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalSwimmingStrokeCount:)":{"navigatorTitle":[{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:totalSwimmingStrokeCount:"}],"title":"predicateForWorkouts(with:totalSwimmingStrokeCount:)","deprecated":true,"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalSwimmingStrokeCount:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForWorkouts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSComparisonPredicate","kind":"typeIdentifier","text":"NSComparisonPredicate"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSPredicateOperatorType","kind":"typeIdentifier","text":"Operator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalSwimmingStrokeCount"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)HKQuantity","kind":"typeIdentifier","text":"HKQuantity"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier","text":"NSPredicate"}],"role":"symbol","type":"topic","url":"/documentation/healthkit/hkquery/predicateforworkouts(with:totalswimmingstrokecount:)","kind":"symbol","abstract":[{"type":"text","text":"Returns a predicate that matches workout samples based on the number of strokes while swimming."}]},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalEnergyBurned:)":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForWorkouts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSComparisonPredicate","kind":"typeIdentifier","text":"NSComparisonPredicate"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSPredicateOperatorType","kind":"typeIdentifier","text":"Operator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalEnergyBurned"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)HKQuantity","kind":"typeIdentifier","text":"HKQuantity"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier","text":"NSPredicate"}],"title":"predicateForWorkouts(with:totalEnergyBurned:)","navigatorTitle":[{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:totalEnergyBurned:"}],"kind":"symbol","deprecated":true,"abstract":[{"type":"text","text":"Returns a predicate for matching workouts based on the total energy burned."}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalEnergyBurned:)","role":"symbol","url":"/documentation/healthkit/hkquery/predicateforworkouts(with:totalenergyburned:)"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-5irg9":{"abstract":[{"text":"Returns a predicate that matches any objects that have been associated with the provided workout.","type":"text"}],"title":"predicateForObjects(from:)","navigatorTitle":[{"text":"predicateForObjectsFromWorkout:","kind":"identifier"}],"url":"/documentation/healthkit/hkquery/predicateforobjects(from:)-5irg9","kind":"symbol","type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-5irg9","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKWorkout","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKWorkout"},{"text":") -> ","kind":"text"},{"text":"NSPredicate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:minimumQuantity:)":{"abstract":[{"text":"Returns a predicate for matching workout activities based the minimum value of an associated quantity type.","type":"text"}],"title":"predicateForWorkouts(operatorType:quantityType:minimumQuantity:)","navigatorTitle":[{"text":"predicateForWorkoutsWithOperatorType:quantityType:minimumQuantity:","kind":"identifier"}],"url":"/documentation/healthkit/hkquery/predicateforworkouts(operatortype:quantitytype:minimumquantity:)","kind":"symbol","type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:minimumQuantity:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForWorkouts","kind":"identifier"},{"text":"(","kind":"text"},{"text":"operatorType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSComparisonPredicate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSComparisonPredicate"},{"text":".","kind":"text"},{"text":"Operator","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSPredicateOperatorType"},{"text":", ","kind":"text"},{"text":"quantityType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKQuantityType","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantityType"},{"text":", ","kind":"text"},{"text":"minimumQuantity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKQuantity","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantity"},{"text":") -> ","kind":"text"},{"text":"NSPredicate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalDistance:)":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalDistance:)","title":"predicateForWorkouts(with:totalDistance:)","abstract":[{"text":"Returns a predicate for matching workouts based on the total distance traveled.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForWorkouts","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSComparisonPredicate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSComparisonPredicate"},{"text":".","kind":"text"},{"text":"Operator","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSPredicateOperatorType"},{"text":", ","kind":"text"},{"text":"totalDistance","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKQuantity","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantity"},{"text":") -> ","kind":"text"},{"text":"NSPredicate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate"}],"navigatorTitle":[{"text":"predicateForWorkoutsWithOperatorType:totalDistance:","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"/documentation/healthkit/hkquery/predicateforworkouts(with:totaldistance:)","deprecated":true},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutType":{"abstract":[{"text":"The key path for accessing the workout’s type.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathWorkoutType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutType"}],"role":"symbol","url":"/documentation/healthkit/hkpredicatekeypathworkouttype","title":"HKPredicateKeyPathWorkoutType"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkout/workoutActivityType":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkout/workoutActivityType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"workoutActivityType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@HKWorkoutActivityType","text":"HKWorkoutActivityType"}],"navigatorTitle":[{"kind":"identifier","text":"workoutActivityType"}],"kind":"symbol","title":"workoutActivityType","abstract":[{"type":"text","text":"The type of activity performed during the workout."}],"type":"topic","role":"symbol","url":"/documentation/healthkit/hkworkout/workoutactivitytype"},"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate":{"url":"/documentation/foundation/nspredicate","title":"NSPredicate","abstract":[{"text":"A definition of logical conditions for constraining a search for a fetch or for in-memory filtering.","type":"text"}],"fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSPredicate"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false},{"deprecated":false,"unavailable":false,"name":"macOS","beta":false},{"unavailable":false,"deprecated":false,"beta":false,"name":"visionOS"},{"deprecated":false,"name":"watchOS","unavailable":false,"beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Type Method","path":"/metadata/roleHeading"},{"op":"replace","value":"predicateForWorkoutsWithWorkoutActivityType:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"predicateForWorkoutsWithWorkoutActivityType:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKQuery"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKWorkout/workoutActivityType","doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutType"],"anchor":"Related-Documentation","title":"Related Documentation"},{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-5irg9","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(activityPredicate:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:duration:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:averageQuantity:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:maximumQuantity:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:minimumQuantity:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:sumQuantity:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalDistance:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalEnergyBurned:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalFlightsClimbed:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalSwimmingStrokeCount:)"],"title":"Creating workout predicates","anchor":"Creating-workout-predicates","generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate","text":"NSPredicate"},{"text":" *) ","kind":"text"},{"text":"predicateForWorkoutsWithWorkoutActivityType:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@HKWorkoutActivityType","text":"HKWorkoutActivityType","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"workoutActivityType"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The type of activity. For a list of valid workout activities, see "},{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivityType","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"workoutActivityType"}],"kind":"parameters"},"path":"/primaryContentSections/1"},{"op":"replace","value":{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"A predicate for matching workouts based on the type of activity."}],"type":"paragraph"}],"kind":"content"},"path":"/primaryContentSections/2"},{"op":"replace","value":"predicateForWorkoutsWithOperatorType:quantityType:averageQuantity:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(operatorType:quantityType:averageQuantity:)/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"predicateForWorkoutsWithOperatorType:quantityType:averageQuantity:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(operatorType:quantityType:averageQuantity:)/fragments"},{"op":"replace","value":"HKQuery","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/title"},{"op":"replace","value":[{"text":"HKQuery","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/fragments"},{"op":"replace","value":[{"text":"HKQuery","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/navigatorTitle"},{"op":"replace","value":"predicateForWorkoutsWithActivityPredicate:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(activityPredicate:)/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"predicateForWorkoutsWithActivityPredicate:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(activityPredicate:)/fragments"},{"op":"replace","value":"HKWorkoutActivityType","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/title"},{"value":[{"kind":"identifier","text":"HKWorkoutActivityType"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/fragments"},{"value":[{"kind":"identifier","text":"HKWorkoutActivityType"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivityType/navigatorTitle","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:duration:)/title","value":"predicateForWorkoutsWithOperatorType:duration:"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:duration:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"predicateForWorkoutsWithOperatorType:duration:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(operatorType:quantityType:maximumQuantity:)/title","value":"predicateForWorkoutsWithOperatorType:quantityType:maximumQuantity:","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(operatorType:quantityType:maximumQuantity:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:quantityType:maximumQuantity:"}]},{"op":"replace","value":"predicateForWorkoutsWithOperatorType:quantityType:sumQuantity:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(operatorType:quantityType:sumQuantity:)/title"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(operatorType:quantityType:sumQuantity:)/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:quantityType:sumQuantity:"}],"op":"replace"},{"value":"predicateForWorkoutsWithWorkoutActivityType:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:)/title","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:)/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"predicateForWorkoutsWithWorkoutActivityType:","kind":"identifier"}]},{"value":"predicateForWorkoutsWithOperatorType:totalFlightsClimbed:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:totalFlightsClimbed:)/title","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:totalFlightsClimbed:)/fragments","value":[{"kind":"text","text":"+ "},{"text":"predicateForWorkoutsWithOperatorType:totalFlightsClimbed:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:totalSwimmingStrokeCount:)/title","value":"predicateForWorkoutsWithOperatorType:totalSwimmingStrokeCount:"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:totalSwimmingStrokeCount:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:totalSwimmingStrokeCount:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:totalEnergyBurned:)/title","value":"predicateForWorkoutsWithOperatorType:totalEnergyBurned:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:totalEnergyBurned:"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:totalEnergyBurned:)/fragments"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-5irg9/title","value":"predicateForObjectsFromWorkout:"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-5irg9/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForObjectsFromWorkout:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(operatorType:quantityType:minimumQuantity:)/title","value":"predicateForWorkoutsWithOperatorType:quantityType:minimumQuantity:","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(operatorType:quantityType:minimumQuantity:)/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:quantityType:minimumQuantity:"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:totalDistance:)/title","value":"predicateForWorkoutsWithOperatorType:totalDistance:","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:totalDistance:)/fragments","value":[{"kind":"text","text":"+ "},{"text":"predicateForWorkoutsWithOperatorType:totalDistance:","kind":"identifier"}],"op":"replace"},{"value":"HKPredicateKeyPathWorkoutType","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutType/title"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutType/fragments","op":"replace","value":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutType"}]},{"op":"replace","value":"workoutActivityType","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout~1workoutActivityType/title"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout~1workoutActivityType/fragments","op":"replace","value":[{"text":"workoutActivityType","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}