{"sections":[],"abstract":[{"text":"Returns a predicate that finds verifiable health records with a relevant date within the specified range.","type":"text"}],"metadata":{"extendedModule":"HealthKit","externalID":"c:objc(cs)HKQuery(cm)predicateForVerifiableClinicalRecordsWithRelevantDateWithinDateInterval:","role":"symbol","modules":[{"name":"HealthKit"}],"platforms":[{"name":"iOS","unavailable":false,"introducedAt":"15.0","beta":false,"deprecated":false},{"name":"iPadOS","unavailable":false,"introducedAt":"15.0","beta":false,"deprecated":false},{"name":"Mac Catalyst","unavailable":false,"introducedAt":"15.0","beta":false,"deprecated":false},{"name":"macOS","unavailable":false,"introducedAt":"13.0","beta":false,"deprecated":false},{"name":"visionOS","unavailable":false,"introducedAt":"1.0","beta":false,"deprecated":false},{"name":"watchOS","unavailable":false,"introducedAt":"8.0","beta":false,"deprecated":false}],"roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForVerifiableClinicalRecords"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withRelevantDateWithin"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation12DateIntervalV","kind":"typeIdentifier","text":"DateInterval"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier","text":"NSPredicate"}],"title":"predicateForVerifiableClinicalRecords(withRelevantDateWithin:)","navigatorTitle":[{"kind":"identifier","text":"predicateForVerifiableClinicalRecordsWithRelevantDateWithinDateInterval:"}],"symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForVerifiableClinicalRecords(withRelevantDateWithin:)"},"seeAlsoSections":[{"title":"Creating clinical record predicates","generated":true,"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForClinicalRecords(from:fhirResourceType:identifier:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForClinicalRecords(withFHIRResourceType:)"],"anchor":"Creating-clinical-record-predicates"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForVerifiableClinicalRecords","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withRelevantDateWithin","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"dateInterval","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"DateInterval","identifier":"doc://com.externally.resolved.symbol/s:10Foundation12DateIntervalV","preciseIdentifier":"s:10Foundation12DateIntervalV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSPredicate","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate","preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The start and end date for the predicate."}],"type":"paragraph"}],"name":"dateInterval"}]},{"kind":"content","content":[{"anchor":"Discussion","type":"heading","text":"Discussion","level":2},{"inlineContent":[{"text":"The resulting predicate matches ","type":"text"},{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord","type":"reference","isActive":true},{"text":" instances that have a ","type":"text"},{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/relevantDate","type":"reference","isActive":true},{"text":" property within the specified date interval.","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","variants":[{"paths":["/documentation/healthkit/hkquery/predicateforverifiableclinicalrecords(withrelevantdatewithin:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/healthkit/hkquery/predicateforverifiableclinicalrecords(withrelevantdatewithin:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKQuery"]]},"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForVerifiableClinicalRecords(withRelevantDateWithin:)":{"url":"/documentation/healthkit/hkquery/predicateforverifiableclinicalrecords(withrelevantdatewithin:)","abstract":[{"text":"Returns a predicate that finds verifiable health records with a relevant date within the specified range.","type":"text"}],"title":"predicateForVerifiableClinicalRecords(withRelevantDateWithin:)","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForVerifiableClinicalRecords(withRelevantDateWithin:)","role":"symbol","navigatorTitle":[{"text":"predicateForVerifiableClinicalRecordsWithRelevantDateWithinDateInterval:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForVerifiableClinicalRecords","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withRelevantDateWithin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DateInterval","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12DateIntervalV"},{"text":") -> ","kind":"text"},{"text":"NSPredicate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate"}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/relevantDate":{"role":"symbol","title":"relevantDate","url":"/documentation/healthkit/hkverifiableclinicalrecord/relevantdate","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/relevantDate","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"relevantDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"navigatorTitle":[{"text":"relevantDate","kind":"identifier"}],"abstract":[{"text":"A date relevant to this record, such as when the issuer administered a vaccine or performed a test.","type":"text"}],"type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForClinicalRecords(withFHIRResourceType:)":{"url":"/documentation/healthkit/hkquery/predicateforclinicalrecords(withfhirresourcetype:)","abstract":[{"text":"Returns a predicate for a specific FHIR type.","type":"text"}],"title":"predicateForClinicalRecords(withFHIRResourceType:)","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForClinicalRecords(withFHIRResourceType:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"predicateForClinicalRecordsWithFHIRResourceType:"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"predicateForClinicalRecords"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withFHIRResourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@HKFHIRResourceType","text":"HKFHIRResourceType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate"}],"type":"topic"},"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate":{"url":"/documentation/foundation/nspredicate","title":"NSPredicate","abstract":[{"text":"A definition of logical conditions for constraining a search for a fetch or for in-memory filtering.","type":"text"}],"fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSPredicate"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate","type":"topic","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery":{"title":"HKQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKQuery"}],"url":"/documentation/healthkit/hkquery","abstract":[{"type":"text","text":"An abstract class for all the query classes in HealthKit."}],"kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKQuery"}]},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForClinicalRecords(from:fhirResourceType:identifier:)":{"url":"/documentation/healthkit/hkquery/predicateforclinicalrecords(from:fhirresourcetype:identifier:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"predicateForClinicalRecordsFromSource:FHIRResourceType:identifier:"}],"role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForClinicalRecords(from:fhirResourceType:identifier:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"predicateForClinicalRecords"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKSource","text":"HKSource"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fhirResourceType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@HKFHIRResourceType","kind":"typeIdentifier","text":"HKFHIRResourceType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier","text":"NSPredicate"}],"title":"predicateForClinicalRecords(from:fhirResourceType:identifier:)","abstract":[{"text":"Returns a predicate for a specific FHIR resource.","type":"text"}]},"doc://com.externally.resolved.symbol/s:10Foundation12DateIntervalV":{"abstract":[{"text":"The span of time between a specific start date and end date.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:10Foundation12DateIntervalV","fragments":[{"text":"struct ","kind":"text"},{"text":"DateInterval","kind":"identifier"}],"role":"symbol","type":"topic","url":"/documentation/foundation/dateinterval","kind":"symbol","title":"DateInterval"},"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKVerifiableClinicalRecord","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord","abstract":[{"text":"A sample that represents the contents of a SMART Health Card or EU Digital COVID Certificate.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"HKVerifiableClinicalRecord","kind":"identifier"}],"type":"topic","title":"HKVerifiableClinicalRecord","url":"/documentation/healthkit/hkverifiableclinicalrecord"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"name":"iOS","unavailable":false,"introducedAt":"15.0","beta":false,"deprecated":false},{"name":"iPadOS","unavailable":false,"introducedAt":"15.0","beta":false,"deprecated":false},{"deprecated":false,"introducedAt":"15.0","name":"Mac Catalyst","beta":false,"unavailable":false},{"deprecated":false,"introducedAt":"13.0","name":"macOS","beta":false,"unavailable":false},{"deprecated":false,"introducedAt":"1.0","name":"visionOS","beta":false,"unavailable":false},{"deprecated":false,"introducedAt":"8.0","name":"watchOS","beta":false,"unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Type Method","op":"replace"},{"path":"/metadata/title","value":"predicateForVerifiableClinicalRecordsWithRelevantDateWithinDateInterval:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"+ ","kind":"text"},{"text":"predicateForVerifiableClinicalRecordsWithRelevantDateWithinDateInterval:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKQuery"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"anchor":"Creating-clinical-record-predicates","title":"Creating clinical record predicates","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForClinicalRecords(from:fhirResourceType:identifier:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForClinicalRecords(withFHIRResourceType:)"],"generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate","preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"predicateForVerifiableClinicalRecordsWithRelevantDateWithinDateInterval:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDateInterval","text":"NSDateInterval"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dateInterval"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":{"parameters":[{"name":"dateInterval","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The start and end date for the predicate."}]}]}],"kind":"parameters"},"path":"/primaryContentSections/1","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForVerifiableClinicalRecords(withRelevantDateWithin:)/title","value":"predicateForVerifiableClinicalRecordsWithRelevantDateWithinDateInterval:","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForVerifiableClinicalRecords(withRelevantDateWithin:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForVerifiableClinicalRecordsWithRelevantDateWithinDateInterval:"}],"op":"replace"},{"op":"replace","value":"relevantDate","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord~1relevantDate/title"},{"op":"replace","value":[{"kind":"identifier","text":"relevantDate"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord~1relevantDate/fragments"},{"op":"replace","value":"predicateForClinicalRecordsWithFHIRResourceType:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForClinicalRecords(withFHIRResourceType:)/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForClinicalRecordsWithFHIRResourceType:"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForClinicalRecords(withFHIRResourceType:)/fragments"},{"op":"replace","value":"HKQuery","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/title"},{"op":"replace","value":[{"text":"HKQuery","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HKQuery"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/navigatorTitle"},{"op":"replace","value":"predicateForClinicalRecordsFromSource:FHIRResourceType:identifier:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForClinicalRecords(from:fhirResourceType:identifier:)/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"predicateForClinicalRecordsFromSource:FHIRResourceType:identifier:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForClinicalRecords(from:fhirResourceType:identifier:)/fragments"},{"op":"replace","value":"HKVerifiableClinicalRecord","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord/title"},{"op":"replace","value":[{"text":"HKVerifiableClinicalRecord","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord/fragments"},{"op":"replace","value":[{"text":"HKVerifiableClinicalRecord","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}