{
  "abstract": [
    {
      "text": "Returns a predicate that checks a category sample’s value.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePredicateProviding/predicateForSamples(_:value:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuery"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForCategorySamples(with:value:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "HealthKit",
    "externalID": "c:objc(cs)HKQuery(cm)predicateForCategorySamplesWithOperatorType:value:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "predicateForCategorySamples"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "with"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSComparisonPredicate",
        "text": "NSComparisonPredicate"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSPredicateOperatorType",
        "text": "Operator"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "value"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSPredicate",
        "text": "NSPredicate"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "predicateForCategorySamplesWithOperatorType:value:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.4",
        "introducedAt": "8.0",
        "message": "Use HKCategoryValuePredicateProviding.predicateForSamples(_:value:)",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.4",
        "introducedAt": "8.0",
        "message": "Use HKCategoryValuePredicateProviding.predicateForSamples(_:value:)",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "message": "Use HKCategoryValuePredicateProviding.predicateForSamples(_:value:)",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.4",
        "introducedAt": "1.0",
        "message": "Use HKCategoryValuePredicateProviding.predicateForSamples(_:value:)",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.4",
        "introducedAt": "2.0",
        "message": "Use HKCategoryValuePredicateProviding.predicateForSamples(_:value:)",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "predicateForCategorySamples(with:value:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "predicateForCategorySamples"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "with"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "operatorType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSComparisonPredicate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSComparisonPredicate",
              "text": "NSComparisonPredicate"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@NSPredicateOperatorType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSPredicateOperatorType",
              "text": "Operator"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "value"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSPredicate",
              "text": "NSPredicate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The type of operation to perform when matching the category sample’s value against the target value. For a list of possible operators, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/nscomparisonpredicate/operator/contains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "operatorType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The category sample’s target value. Use an enumeration value appropriate for the type of category samples you are working with. For example, a predicate for sleep analysis samples use values from the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " enumeration.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "value"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A predicate that matches category samples based on the provided expression. This predicate works only with category samples.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this convenience method to create a predicate that checks a category sample’s value. The following listing uses both the convenience method and a predicate format string to create equivalent predicates.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let asleep = HKQuery.predicateForCategorySamplesWithOperatorType(",
                    "    .EqualToPredicateOperatorType,",
                    "    value: HKCategoryValueSleepAnalysis.Asleep.rawValue)",
                    " ",
                    "let explicitAsleep =",
                    "    NSPredicate(format: \"%K == %d\",",
                    "                HKPredicateKeyPathCategoryValue,",
                    "                HKCategoryValueSleepAnalysis.Asleep.rawValue)"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "NSPredicate *asleep =",
                    "    [HKQuery",
                    "     predicateForCategorySamplesWithOperatorType:NSEqualToPredicateOperatorType",
                    "     value:HKCategoryValueSleepAnalysisAsleep];",
                    " ",
                    "NSPredicate *explicitAsleep =",
                    "    [NSPredicate predicateWithFormat:@\"%K == %d\",",
                    "     HKPredicateKeyPathCategoryValue,",
                    "     HKCategoryValueSleepAnalysisAsleep];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nscomparisonpredicate/operator/contains": {
      "abstract": [
        {
          "text": "A predicate to determine if the left hand side contains the right hand side.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "case "
        },
        {
          "kind": "identifier",
          "text": "contains"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nscomparisonpredicate/operator/contains",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSComparisonPredicate.Operator.contains",
      "type": "topic",
      "url": "/documentation/foundation/nscomparisonpredicate/operator/contains"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategorySample/value": {
      "abstract": [
        {
          "text": "The category value for this sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategorySample/value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "value"
        }
      ],
      "role": "symbol",
      "title": "value",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorysample/value"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePredicateProviding": {
      "abstract": [
        {
          "text": "A protocol for objects that produce predicates that match category value samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValuePredicateProviding"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePredicateProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValuePredicateProviding"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValuePredicateProviding",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluepredicateproviding"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePredicateProviding/predicateForSamples(_:value:)": {
      "abstract": [
        {
          "text": "Returns a predicate that checks a category sample’s value.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "RawValue",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "Int",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForSamples"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSComparisonPredicate",
          "text": "NSComparisonPredicate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPredicateOperatorType",
          "text": "Operator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePredicateProviding/predicateForSamples(_:value:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "predicateForSamples(_:value:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluepredicateproviding/predicateforsamples(_:value:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis": {
      "abstract": [
        {
          "text": "Categories that represent the result of a sleep analysis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueSleepAnalysis"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueSleepAnalysis"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueSleepAnalysis",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvaluesleepanalysis"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCategoryValue": {
      "abstract": [
        {
          "text": "The key path for accessing the category sample’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathCategoryValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCategoryValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKPredicateKeyPathCategoryValue"
        }
      ],
      "role": "symbol",
      "title": "HKPredicateKeyPathCategoryValue",
      "type": "topic",
      "url": "/documentation/healthkit/hkpredicatekeypathcategoryvalue"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuery": {
      "abstract": [
        {
          "text": "An abstract class for all the query classes in HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuery"
        }
      ],
      "role": "symbol",
      "title": "HKQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkquery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForCategorySamples(with:value:)": {
      "abstract": [
        {
          "text": "Returns a predicate that checks a category sample’s value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForCategorySamples"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSComparisonPredicate",
          "text": "NSComparisonPredicate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPredicateOperatorType",
          "text": "Operator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForCategorySamples(with:value:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForCategorySamplesWithOperatorType:value:"
        }
      ],
      "role": "symbol",
      "title": "predicateForCategorySamples(with:value:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkquery/predicateforcategorysamples(with:value:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForCategorySamplesEqualToValues:": {
      "abstract": [
        {
          "text": "A predicate that returns category samples with a matching value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "predicateForCategorySamplesEqualToValues:"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForCategorySamplesEqualToValues:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForCategorySamplesEqualToValues:"
        }
      ],
      "role": "symbol",
      "title": "predicateForCategorySamplesEqualToValues:",
      "type": "topic",
      "url": "/documentation/healthkit/hkquery/predicateforcategorysamplesequaltovalues:"
    },
    "doc://com.externally.resolved.symbol/c:@E@NSPredicateOperatorType": {
      "abstract": [
        {
          "text": "Defines the type of comparison for a comparison predicate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "enum "
        },
        {
          "kind": "identifier",
          "text": "NSComparisonPredicate.Operator"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@NSPredicateOperatorType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSComparisonPredicate.Operator",
      "type": "topic",
      "url": "/documentation/foundation/nscomparisonpredicate/operator"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSComparisonPredicate": {
      "abstract": [
        {
          "text": "A specialized predicate for comparing expressions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSComparisonPredicate"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSComparisonPredicate",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSComparisonPredicate",
      "type": "topic",
      "url": "/documentation/foundation/nscomparisonpredicate"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate": {
      "abstract": [
        {
          "text": "A definition of logical conditions for constraining a search for a fetch or for in-memory filtering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPredicate",
      "type": "topic",
      "url": "/documentation/foundation/nspredicate"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategorySample/value",
        "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCategoryValue"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Creating-category-sample-predicates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValuePredicateProviding"
      ],
      "title": "Creating category sample predicates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "predicateForCategorySamplesWithOperatorType:value:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForCategorySamplesWithOperatorType:value:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuery"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategorySample/value",
                "doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathCategoryValue"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Creating-category-sample-predicates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForCategorySamplesEqualToValues:"
              ],
              "title": "Creating category sample predicates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSPredicate",
                    "text": "NSPredicate"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "predicateForCategorySamplesWithOperatorType:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@E@NSPredicateOperatorType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSPredicateOperatorType",
                    "text": "NSPredicateOperatorType"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "operatorType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "value:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "value"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The type of operation to perform when matching the category sample’s value against the target value. For a list of possible operators, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/foundation/nscomparisonpredicate/operator/contains",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "operatorType"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The category sample’s target value. Use an enumeration value appropriate for the type of category samples you are working with. For example, a predicate for sleep analysis samples use values from the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueSleepAnalysis",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " enumeration.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "value"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A predicate that matches category samples based on the provided expression. This predicate works only with category samples.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/title",
          "value": "HKQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nscomparisonpredicate~1operator~1contains/title",
          "value": "NSContainsPredicateOperatorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategorySample~1value/title",
          "value": "value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategorySample~1value/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathCategoryValue/title",
          "value": "HKPredicateKeyPathCategoryValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathCategoryValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKPredicateKeyPathCategoryValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForCategorySamples(with:value:)/title",
          "value": "predicateForCategorySamplesWithOperatorType:value:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForCategorySamples(with:value:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForCategorySamplesWithOperatorType:value:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSleepAnalysis/title",
          "value": "HKCategoryValueSleepAnalysis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSleepAnalysis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueSleepAnalysis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueSleepAnalysis/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueSleepAnalysis"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkquery/predicateforcategorysamples(with:value:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkquery/predicateforcategorysamples(with:value:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
