{"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKQuery"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathUUID","doc://com.apple.healthkit/documentation/HealthKit/HKObject/uuid"],"anchor":"Related-Documentation","title":"Related Documentation"},{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObject(with:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-7j3p2","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-89b4t","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-9h87f","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withDeviceProperty:allowedValues:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-1ar4g","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:allowedValues:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:operatorType:value:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjectsWithNoCorrelation()"],"anchor":"Creating-object-predicates","generated":true,"title":"Creating object predicates"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"UUIDs","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sh","preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:10Foundation4UUIDV","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate","preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"]}]},{"kind":"parameters","parameters":[{"name":"UUIDs","content":[{"inlineContent":[{"text":"The set of UUIDs to be matched.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A predicate that matches the specified objects based on their UUIDs."}]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"HealthKit assigns a UUID to each object when it is saved to the HealthKit store. HealthKit uses these IDs to uniquely identify objects from the store. Use this convenience method to create a predicate that checks an object’s UUID against the provided set of UUIDs. The following sample uses both the convenience method and a predicate format string to create equivalent predicates."}]},{"type":"tabNavigator","tabs":[{"content":[{"type":"codeListing","syntax":"swift","code":["let uuids = HKQuery.predicateForObjectsWithUUIDs(myUUIDs)"," ","let explicitUUIDs =","    NSPredicate(format: \"%K IN %@\", HKPredicateKeyPathUUID, myUUIDs)"]}],"title":"Swift"},{"content":[{"code":["NSPredicate *uuids = [HKQuery predicateForObjectsWithUUIDs:myUUIDs];"," ","NSPredicate *explicitUUIDs = [NSPredicate predicateWithFormat:@\"%K IN %@\",","                              HKPredicateKeyPathUUID,","                              myUUIDs];"],"syntax":"objc","type":"codeListing"}],"title":"Objective-C"}]}]}],"abstract":[{"text":"Returns a predicate that matches the objects with the specified  universally unique identifiers (UUIDs).","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/healthkit/hkquery/predicateforobjects(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/healthkit/hkquery/predicateforobjects(with:)"]}],"identifier":{"url":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(with:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"HealthKit"}],"symbolKind":"method","title":"predicateForObjects(with:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":">) -> ","kind":"text"},{"text":"NSPredicate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate"}],"role":"symbol","platforms":[{"unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"name":"iPadOS","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"name":"macOS","deprecated":false,"beta":false,"unavailable":false},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false},{"name":"watchOS","deprecated":false,"beta":false,"unavailable":false}],"externalID":"c:objc(cs)HKQuery(cm)predicateForObjectsWithUUIDs:","roleHeading":"Type Method","navigatorTitle":[{"text":"predicateForObjectsWithUUIDs:","kind":"identifier"}],"extendedModule":"HealthKit"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-89b4t":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"predicateForObjectsFromSources:","kind":"identifier"}],"title":"predicateForObjects(from:)","abstract":[{"text":"Returns a predicate that matches all the objects that were created by any of the provided sources.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKSource","text":"HKSource","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate","kind":"typeIdentifier"}],"url":"/documentation/healthkit/hkquery/predicateforobjects(from:)-89b4t","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-89b4t","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKObject/uuid":{"url":"/documentation/healthkit/hkobject/uuid","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"uuid"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier","text":"UUID"}],"title":"uuid","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKObject/uuid","navigatorTitle":[{"kind":"identifier","text":"UUID"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The universally unique identifier (UUID) for this HealthKit object."}],"kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-9h87f":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-9h87f","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKDevice","text":"HKDevice","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate","kind":"typeIdentifier"}],"url":"/documentation/healthkit/hkquery/predicateforobjects(from:)-9h87f","abstract":[{"type":"text","text":"Returns a predicate that matches all the objects that were created by any of the provided devices."}],"kind":"symbol","title":"predicateForObjects(from:)","type":"topic","navigatorTitle":[{"text":"predicateForObjectsFromDevices:","kind":"identifier"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:Sh":{"abstract":[{"text":"An unordered collection of unique elements.","type":"text"}],"role":"symbol","title":"Set","identifier":"doc://com.externally.resolved.symbol/s:Sh","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Set","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Element","kind":"genericParameter"},{"text":"> ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Element","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SH","text":"Hashable"}],"type":"topic","url":"/documentation/Swift/Set","kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathUUID":{"type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathUUID","url":"/documentation/healthkit/hkpredicatekeypathuuid","title":"HKPredicateKeyPathUUID","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKPredicateKeyPathUUID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKPredicateKeyPathUUID"}],"abstract":[{"type":"text","text":"The key path for accessing the object’s UUID inside a predicate format string."}]},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:operatorType:value:)":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:operatorType:value:)","navigatorTitle":[{"text":"predicateForObjectsWithMetadataKey:operatorType:value:","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns a predicate that matches objects based on the provided metadata key, value, and operator."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withMetadataKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"operatorType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSComparisonPredicate","kind":"typeIdentifier","text":"NSComparisonPredicate"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSPredicateOperatorType","kind":"typeIdentifier","text":"Operator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate"}],"kind":"symbol","title":"predicateForObjects(withMetadataKey:operatorType:value:)","url":"/documentation/healthkit/hkquery/predicateforobjects(withmetadatakey:operatortype:value:)","role":"symbol","type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjectsWithNoCorrelation()":{"role":"symbol","abstract":[{"type":"text","text":"Returns a predicate that matches all objects that are not associated with a HealthKit correlation."}],"navigatorTitle":[{"kind":"identifier","text":"predicateForObjectsWithNoCorrelation"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjectsWithNoCorrelation()","url":"/documentation/healthkit/hkquery/predicateforobjectswithnocorrelation()","kind":"symbol","title":"predicateForObjectsWithNoCorrelation()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForObjectsWithNoCorrelation"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier","text":"NSPredicate"}],"type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:allowedValues:)":{"role":"symbol","abstract":[{"type":"text","text":"Returns a predicate that matches objects based on the provided metadata key and an array of target values."}],"navigatorTitle":[{"text":"predicateForObjectsWithMetadataKey:allowedValues:","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:allowedValues:)","url":"/documentation/healthkit/hkquery/predicateforobjects(withmetadatakey:allowedvalues:)","kind":"symbol","title":"predicateForObjects(withMetadataKey:allowedValues:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForObjects"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withMetadataKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"allowedValues","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate","kind":"typeIdentifier"}],"type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:)":{"abstract":[{"type":"text","text":"Returns a predicate that matches any object whose metadata contains the provided key."}],"navigatorTitle":[{"text":"predicateForObjectsWithMetadataKey:","kind":"identifier"}],"url":"/documentation/healthkit/hkquery/predicateforobjects(withmetadatakey:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withMetadataKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate","kind":"typeIdentifier"}],"title":"predicateForObjects(withMetadataKey:)","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:)"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-1ar4g":{"role":"symbol","navigatorTitle":[{"text":"predicateForObjectsFromSourceRevisions:","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-1ar4g","abstract":[{"text":"Returns a predicate that matches all the objects that were created by any of the provided source revisions.","type":"text"}],"type":"topic","title":"predicateForObjects(from:)","url":"/documentation/healthkit/hkquery/predicateforobjects(from:)-1ar4g","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKSourceRevision","text":"HKSourceRevision","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate","kind":"typeIdentifier"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-7j3p2":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-7j3p2","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKSource","text":"HKSource","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate","kind":"typeIdentifier"}],"url":"/documentation/healthkit/hkquery/predicateforobjects(from:)-7j3p2","abstract":[{"type":"text","text":"Returns a predicate that matches all the objects that were created by the provided source."}],"kind":"symbol","title":"predicateForObjects(from:)","type":"topic","navigatorTitle":[{"text":"predicateForObjectsFromSource:","kind":"identifier"}],"role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery":{"title":"HKQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKQuery"}],"url":"/documentation/healthkit/hkquery","abstract":[{"type":"text","text":"An abstract class for all the query classes in HealthKit."}],"kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKQuery"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withDeviceProperty:allowedValues:)":{"abstract":[{"text":"Returns a predicate that matches all objects created by devices with the specified properties.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withDeviceProperty:allowedValues:)","kind":"symbol","title":"predicateForObjects(withDeviceProperty:allowedValues:)","role":"symbol","url":"/documentation/healthkit/hkquery/predicateforobjects(withdeviceproperty:allowedvalues:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withDeviceProperty","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"allowedValues","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"predicateForObjectsWithDeviceProperty:allowedValues:","kind":"identifier"}],"type":"topic"},"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate":{"url":"/documentation/foundation/nspredicate","title":"NSPredicate","abstract":[{"text":"A definition of logical conditions for constraining a search for a fetch or for in-memory filtering.","type":"text"}],"fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSPredicate"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate","type":"topic","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(with:)":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(with:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate","kind":"typeIdentifier"}],"url":"/documentation/healthkit/hkquery/predicateforobjects(with:)","abstract":[{"type":"text","text":"Returns a predicate that matches the objects with the specified  universally unique identifiers (UUIDs)."}],"kind":"symbol","title":"predicateForObjects(with:)","type":"topic","navigatorTitle":[{"text":"predicateForObjectsWithUUIDs:","kind":"identifier"}],"role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObject(with:)":{"role":"symbol","navigatorTitle":[{"text":"predicateForObjectWithUUID:","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObject(with:)","abstract":[{"text":"Returns a predicate that matches an object with the specified universally unique identifier (UUID).","type":"text"}],"type":"topic","title":"predicateForObject(with:)","url":"/documentation/healthkit/hkquery/predicateforobject(with:)","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate","kind":"typeIdentifier"}]},"doc://com.externally.resolved.symbol/s:10Foundation4UUIDV":{"type":"topic","title":"UUID","kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"UUID"}],"abstract":[{"type":"text","text":"A universally unique value to identify types, interfaces, and other items."}],"url":"/documentation/foundation/uuid","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4UUIDV"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"unavailable":false,"name":"iOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst"},{"name":"macOS","deprecated":false,"beta":false,"unavailable":false},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false},{"name":"watchOS","deprecated":false,"beta":false,"unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Type Method"},{"op":"replace","path":"/metadata/title","value":"predicateForObjectsWithUUIDs:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"path":"/metadata/fragments","value":[{"text":"+ ","kind":"text"},{"text":"predicateForObjectsWithUUIDs:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKQuery"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"value":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathUUID","doc://com.apple.healthkit/documentation/HealthKit/HKObject/uuid"]},{"title":"Creating object predicates","anchor":"Creating-object-predicates","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObject(with:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-7j3p2","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-89b4t","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-9h87f","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withDeviceProperty:allowedValues:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-1ar4g","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:allowedValues:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:operatorType:value:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjectsWithNoCorrelation()"],"generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier","text":"NSPredicate","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"predicateForObjectsWithUUIDs:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSSet","kind":"typeIdentifier","text":"NSSet<NSUUID *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"UUIDs"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The set of UUIDs to be matched.","type":"text"}],"type":"paragraph"}],"name":"UUIDs"}]}},{"value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A predicate that matches the specified objects based on their UUIDs.","type":"text"}]}]},"path":"/primaryContentSections/2","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-89b4t/title","value":"predicateForObjectsFromSources:"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-89b4t/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForObjectsFromSources:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObject~1uuid/title","value":"UUID"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObject~1uuid/fragments","value":[{"text":"UUID","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-9h87f/title","value":"predicateForObjectsFromDevices:"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-9h87f/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForObjectsFromDevices:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathUUID/title","value":"HKPredicateKeyPathUUID"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathUUID/fragments","value":[{"kind":"identifier","text":"HKPredicateKeyPathUUID"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(withMetadataKey:operatorType:value:)/title","value":"predicateForObjectsWithMetadataKey:operatorType:value:"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(withMetadataKey:operatorType:value:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"predicateForObjectsWithMetadataKey:operatorType:value:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjectsWithNoCorrelation()/title","value":"predicateForObjectsWithNoCorrelation"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjectsWithNoCorrelation()/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForObjectsWithNoCorrelation"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(withMetadataKey:allowedValues:)/title","value":"predicateForObjectsWithMetadataKey:allowedValues:"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(withMetadataKey:allowedValues:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"predicateForObjectsWithMetadataKey:allowedValues:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(withMetadataKey:)/title","value":"predicateForObjectsWithMetadataKey:"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(withMetadataKey:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForObjectsWithMetadataKey:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-1ar4g/title","value":"predicateForObjectsFromSourceRevisions:"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-1ar4g/fragments","value":[{"text":"+ ","kind":"text"},{"text":"predicateForObjectsFromSourceRevisions:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-7j3p2/title","value":"predicateForObjectsFromSource:"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-7j3p2/fragments","value":[{"text":"+ ","kind":"text"},{"text":"predicateForObjectsFromSource:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/title","value":"HKQuery"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/fragments","value":[{"text":"HKQuery","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/navigatorTitle","value":[{"text":"HKQuery","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(withDeviceProperty:allowedValues:)/title","value":"predicateForObjectsWithDeviceProperty:allowedValues:"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(withDeviceProperty:allowedValues:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"predicateForObjectsWithDeviceProperty:allowedValues:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(with:)/title","value":"predicateForObjectsWithUUIDs:"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(with:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForObjectsWithUUIDs:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObject(with:)/title","value":"predicateForObjectWithUUID:"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObject(with:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"predicateForObjectWithUUID:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}