{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/healthkit/hkquery/predicateforobjects(from:)-89b4t"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/healthkit/hkquery/predicateforobjects(from:)-89b4t"]}],"abstract":[{"text":"Returns a predicate that matches all the objects that were created by any of the provided sources.","type":"text"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKObject/source","doc://com.apple.healthkit/documentation/HealthKit/HKSourceQuery"]},{"anchor":"Creating-object-predicates","title":"Creating object predicates","generated":true,"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObject(with:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(with:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-7j3p2","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-9h87f","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withDeviceProperty:allowedValues:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-1ar4g","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:allowedValues:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:operatorType:value:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjectsWithNoCorrelation()"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKQuery"]]},"identifier":{"url":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-89b4t","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sources","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sh","text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKSource","text":"HKSource","preciseIdentifier":"c:objc(cs)HKSource","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate","text":"NSPredicate","preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A set of sources that have saved data to the HealthKit store.","type":"text"}]}],"name":"sources"}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A predicate that matches all the objects created by any of the provided sources."}]}]},{"kind":"content","content":[{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"text":"Use this convenience method to create a predicate that finds all the objects from a specified set of apps or devices. The following sample uses both the convenience method and a predicate format string to create equivalent predicates.","type":"text"}],"type":"paragraph"},{"tabs":[{"content":[{"syntax":"swift","code":["let fromSources = HKQuery.predicateForObjectsFromSources(sources)"," ","let explicitFromSources =","    NSPredicate(format: \"%K IN %@\", HKPredicateKeyPathSource, sources)"],"type":"codeListing"}],"title":"Swift"},{"content":[{"code":["NSPredicate *fromSources = [HKQuery predicateForObjectsFromSources:sources];"," ","NSPredicate *explicitFromSources = [NSPredicate predicateWithFormat:@\"%K IN %@\",","                                   HKPredicateKeyPathSource,","                                   sources];"],"syntax":"objc","type":"codeListing"}],"title":"Objective-C"}],"type":"tabNavigator"}]}],"metadata":{"platforms":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false},{"name":"macOS","unavailable":false,"beta":false,"deprecated":false},{"name":"visionOS","unavailable":false,"beta":false,"deprecated":false},{"name":"watchOS","unavailable":false,"beta":false,"deprecated":false}],"symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"HKSource","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKSource"},{"text":">) -> ","kind":"text"},{"text":"NSPredicate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate"}],"title":"predicateForObjects(from:)","roleHeading":"Type Method","role":"symbol","externalID":"c:objc(cs)HKQuery(cm)predicateForObjectsFromSources:","navigatorTitle":[{"text":"predicateForObjectsFromSources:","kind":"identifier"}],"modules":[{"name":"HealthKit"}],"extendedModule":"HealthKit"},"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKSourceQuery":{"title":"HKSourceQuery","navigatorTitle":[{"kind":"identifier","text":"HKSourceQuery"}],"kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKSourceQuery","role":"symbol","abstract":[{"type":"text","text":"A query that returns a list of sources, such as apps and devices, that have saved matching queries to the HealthKit store."}],"type":"topic","url":"/documentation/healthkit/hksourcequery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKSourceQuery"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:)":{"abstract":[{"type":"text","text":"Returns a predicate that matches any object whose metadata contains the provided key."}],"navigatorTitle":[{"text":"predicateForObjectsWithMetadataKey:","kind":"identifier"}],"url":"/documentation/healthkit/hkquery/predicateforobjects(withmetadatakey:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withMetadataKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate","kind":"typeIdentifier"}],"title":"predicateForObjects(withMetadataKey:)","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:)"},"doc://com.apple.healthkit/documentation/HealthKit/HKSource":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKSource","kind":"symbol","title":"HKSource","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKSource"}],"abstract":[{"text":"An object indicating the app or device that created a HealthKit sample","type":"text"}],"url":"/documentation/healthkit/hksource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKSource"}],"type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(with:)":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(with:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate","kind":"typeIdentifier"}],"url":"/documentation/healthkit/hkquery/predicateforobjects(with:)","abstract":[{"type":"text","text":"Returns a predicate that matches the objects with the specified  universally unique identifiers (UUIDs)."}],"kind":"symbol","title":"predicateForObjects(with:)","type":"topic","navigatorTitle":[{"text":"predicateForObjectsWithUUIDs:","kind":"identifier"}],"role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObject(with:)":{"role":"symbol","navigatorTitle":[{"text":"predicateForObjectWithUUID:","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObject(with:)","abstract":[{"text":"Returns a predicate that matches an object with the specified universally unique identifier (UUID).","type":"text"}],"type":"topic","title":"predicateForObject(with:)","url":"/documentation/healthkit/hkquery/predicateforobject(with:)","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate","kind":"typeIdentifier"}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate":{"url":"/documentation/foundation/nspredicate","title":"NSPredicate","abstract":[{"text":"A definition of logical conditions for constraining a search for a fetch or for in-memory filtering.","type":"text"}],"fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSPredicate"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate","type":"topic","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:operatorType:value:)":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:operatorType:value:)","navigatorTitle":[{"text":"predicateForObjectsWithMetadataKey:operatorType:value:","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns a predicate that matches objects based on the provided metadata key, value, and operator."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withMetadataKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"operatorType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSComparisonPredicate","kind":"typeIdentifier","text":"NSComparisonPredicate"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSPredicateOperatorType","kind":"typeIdentifier","text":"Operator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate"}],"kind":"symbol","title":"predicateForObjects(withMetadataKey:operatorType:value:)","url":"/documentation/healthkit/hkquery/predicateforobjects(withmetadatakey:operatortype:value:)","role":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjectsWithNoCorrelation()":{"role":"symbol","abstract":[{"type":"text","text":"Returns a predicate that matches all objects that are not associated with a HealthKit correlation."}],"navigatorTitle":[{"kind":"identifier","text":"predicateForObjectsWithNoCorrelation"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjectsWithNoCorrelation()","url":"/documentation/healthkit/hkquery/predicateforobjectswithnocorrelation()","kind":"symbol","title":"predicateForObjectsWithNoCorrelation()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForObjectsWithNoCorrelation"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier","text":"NSPredicate"}],"type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:allowedValues:)":{"role":"symbol","abstract":[{"type":"text","text":"Returns a predicate that matches objects based on the provided metadata key and an array of target values."}],"navigatorTitle":[{"text":"predicateForObjectsWithMetadataKey:allowedValues:","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:allowedValues:)","url":"/documentation/healthkit/hkquery/predicateforobjects(withmetadatakey:allowedvalues:)","kind":"symbol","title":"predicateForObjects(withMetadataKey:allowedValues:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForObjects"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withMetadataKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"allowedValues","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate","kind":"typeIdentifier"}],"type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-89b4t":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"predicateForObjectsFromSources:","kind":"identifier"}],"title":"predicateForObjects(from:)","abstract":[{"text":"Returns a predicate that matches all the objects that were created by any of the provided sources.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKSource","text":"HKSource","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate","kind":"typeIdentifier"}],"url":"/documentation/healthkit/hkquery/predicateforobjects(from:)-89b4t","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-89b4t","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKObject/source":{"url":"/documentation/healthkit/hkobject/source","deprecated":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)HKSource","kind":"typeIdentifier","text":"HKSource"}],"title":"source","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKObject/source","navigatorTitle":[{"kind":"identifier","text":"source"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A HealthKit source, representing the app or device that created this object."}],"kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-7j3p2":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-7j3p2","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKSource","text":"HKSource","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate","kind":"typeIdentifier"}],"url":"/documentation/healthkit/hkquery/predicateforobjects(from:)-7j3p2","abstract":[{"type":"text","text":"Returns a predicate that matches all the objects that were created by the provided source."}],"kind":"symbol","title":"predicateForObjects(from:)","type":"topic","navigatorTitle":[{"text":"predicateForObjectsFromSource:","kind":"identifier"}],"role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery":{"title":"HKQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKQuery"}],"url":"/documentation/healthkit/hkquery","abstract":[{"type":"text","text":"An abstract class for all the query classes in HealthKit."}],"kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKQuery"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-9h87f":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-9h87f","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKDevice","text":"HKDevice","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate","kind":"typeIdentifier"}],"url":"/documentation/healthkit/hkquery/predicateforobjects(from:)-9h87f","abstract":[{"type":"text","text":"Returns a predicate that matches all the objects that were created by any of the provided devices."}],"kind":"symbol","title":"predicateForObjects(from:)","type":"topic","navigatorTitle":[{"text":"predicateForObjectsFromDevices:","kind":"identifier"}],"role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-1ar4g":{"role":"symbol","navigatorTitle":[{"text":"predicateForObjectsFromSourceRevisions:","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-1ar4g","abstract":[{"text":"Returns a predicate that matches all the objects that were created by any of the provided source revisions.","type":"text"}],"type":"topic","title":"predicateForObjects(from:)","url":"/documentation/healthkit/hkquery/predicateforobjects(from:)-1ar4g","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKSourceRevision","text":"HKSourceRevision","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate","kind":"typeIdentifier"}]},"doc://com.externally.resolved.symbol/s:Sh":{"abstract":[{"text":"An unordered collection of unique elements.","type":"text"}],"role":"symbol","title":"Set","identifier":"doc://com.externally.resolved.symbol/s:Sh","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Set","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Element","kind":"genericParameter"},{"text":"> ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Element","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SH","text":"Hashable"}],"type":"topic","url":"/documentation/Swift/Set","kind":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withDeviceProperty:allowedValues:)":{"abstract":[{"text":"Returns a predicate that matches all objects created by devices with the specified properties.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withDeviceProperty:allowedValues:)","kind":"symbol","title":"predicateForObjects(withDeviceProperty:allowedValues:)","role":"symbol","url":"/documentation/healthkit/hkquery/predicateforobjects(withdeviceproperty:allowedvalues:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withDeviceProperty","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"allowedValues","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"predicateForObjectsWithDeviceProperty:allowedValues:","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"visionOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"watchOS"}],"path":"/metadata/platforms","op":"replace"},{"value":"Type Method","path":"/metadata/roleHeading","op":"replace"},{"value":"predicateForObjectsFromSources:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"predicateForObjectsFromSources:","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKQuery"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKObject/source","doc://com.apple.healthkit/documentation/HealthKit/HKSourceQuery"],"anchor":"Related-Documentation","title":"Related Documentation"},{"generated":true,"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObject(with:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(with:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-7j3p2","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-9h87f","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withDeviceProperty:allowedValues:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-1ar4g","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:allowedValues:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(withMetadataKey:operatorType:value:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjectsWithNoCorrelation()"],"anchor":"Creating-object-predicates","title":"Creating object predicates"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"NSPredicate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate"},{"text":" *) ","kind":"text"},{"text":"predicateForObjectsFromSources:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSSet<HKSource *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"text":" *) ","kind":"text"},{"text":"sources","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"path":"/primaryContentSections/1","value":{"parameters":[{"name":"sources","content":[{"inlineContent":[{"text":"A set of sources that have saved data to the HealthKit store.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"value":{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"A predicate that matches all the objects created by any of the provided sources."}],"type":"paragraph"}],"kind":"content"},"path":"/primaryContentSections/2","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSourceQuery/title","value":"HKSourceQuery","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSourceQuery/fragments","value":[{"kind":"identifier","text":"HKSourceQuery"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSourceQuery/navigatorTitle","value":[{"text":"HKSourceQuery","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(withMetadataKey:)/title","value":"predicateForObjectsWithMetadataKey:","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(withMetadataKey:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForObjectsWithMetadataKey:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSource/title","value":"HKSource","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSource/fragments","value":[{"text":"HKSource","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSource/navigatorTitle","value":[{"text":"HKSource","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(with:)/title","value":"predicateForObjectsWithUUIDs:","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(with:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForObjectsWithUUIDs:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObject(with:)/title","value":"predicateForObjectWithUUID:","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObject(with:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForObjectWithUUID:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(withMetadataKey:operatorType:value:)/title","value":"predicateForObjectsWithMetadataKey:operatorType:value:","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(withMetadataKey:operatorType:value:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"predicateForObjectsWithMetadataKey:operatorType:value:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjectsWithNoCorrelation()/title","value":"predicateForObjectsWithNoCorrelation","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjectsWithNoCorrelation()/fragments","value":[{"text":"+ ","kind":"text"},{"text":"predicateForObjectsWithNoCorrelation","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(withMetadataKey:allowedValues:)/title","value":"predicateForObjectsWithMetadataKey:allowedValues:","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(withMetadataKey:allowedValues:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForObjectsWithMetadataKey:allowedValues:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-89b4t/title","value":"predicateForObjectsFromSources:","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-89b4t/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForObjectsFromSources:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObject~1source/title","value":"source","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKObject~1source/fragments","value":[{"kind":"identifier","text":"source"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-7j3p2/title","value":"predicateForObjectsFromSource:","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-7j3p2/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForObjectsFromSource:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/title","value":"HKQuery","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/fragments","value":[{"text":"HKQuery","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/navigatorTitle","value":[{"kind":"identifier","text":"HKQuery"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-9h87f/title","value":"predicateForObjectsFromDevices:","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-9h87f/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForObjectsFromDevices:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-1ar4g/title","value":"predicateForObjectsFromSourceRevisions:","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-1ar4g/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForObjectsFromSourceRevisions:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(withDeviceProperty:allowedValues:)/title","value":"predicateForObjectsWithDeviceProperty:allowedValues:","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(withDeviceProperty:allowedValues:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForObjectsWithDeviceProperty:allowedValues:"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}