{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkoutEffortSamplesRelated(workout:activity:)"},"sections":[],"metadata":{"title":"predicateForWorkoutEffortSamplesRelated(workout:activity:)","symbolKind":"method","role":"symbol","extendedModule":"HealthKit","roleHeading":"Type Method","platforms":[{"introducedAt":"18.0","unavailable":false,"name":"iOS","beta":false,"deprecated":false},{"introducedAt":"18.0","unavailable":false,"name":"iPadOS","beta":false,"deprecated":false},{"introducedAt":"18.0","unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false},{"introducedAt":"15.0","unavailable":false,"name":"macOS","beta":false,"deprecated":false},{"introducedAt":"2.0","unavailable":false,"name":"visionOS","beta":false,"deprecated":false},{"introducedAt":"11.0","unavailable":false,"name":"watchOS","beta":false,"deprecated":false}],"externalID":"c:objc(cs)HKQuery(cm)predicateForWorkoutEffortSamplesRelatedToWorkout:activity:","navigatorTitle":[{"text":"predicateForWorkoutEffortSamplesRelatedToWorkout:activity:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForWorkoutEffortSamplesRelated"},{"kind":"text","text":"("},{"kind":"externalParam","text":"workout"},{"kind":"text","text":": "},{"text":"HKWorkout","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKWorkout"},{"text":", ","kind":"text"},{"text":"activity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKWorkoutActivity","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKWorkoutActivity"},{"text":"?) -> ","kind":"text"},{"text":"NSPredicate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate"}],"modules":[{"name":"HealthKit"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/healthkit/hkquery/predicateforworkouteffortsamplesrelated(workout:activity:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/healthkit/hkquery/predicateforworkouteffortsamplesrelated(workout:activity:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKQuery"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForWorkoutEffortSamplesRelated","kind":"identifier"},{"text":"(","kind":"text"},{"text":"workout","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKWorkout","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkout","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKWorkout"},{"text":", ","kind":"text"},{"text":"activity","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity","preciseIdentifier":"c:objc(cs)HKWorkoutActivity","text":"HKWorkoutActivity"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate","preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery":{"title":"HKQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKQuery"}],"url":"/documentation/healthkit/hkquery","abstract":[{"type":"text","text":"An abstract class for all the query classes in HealthKit."}],"kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKQuery"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkout":{"title":"HKWorkout","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKWorkout"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKWorkout"}],"type":"topic","url":"/documentation/healthkit/hkworkout","abstract":[{"type":"text","text":"A workout sample that stores information about a single physical activity."}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkout"},"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity":{"abstract":[{"text":"An object that describes an activity within a longer workout.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HKWorkoutActivity"}],"title":"HKWorkoutActivity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKWorkoutActivity"}],"role":"symbol","url":"/documentation/healthkit/hkworkoutactivity","kind":"symbol","type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity"},"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate":{"url":"/documentation/foundation/nspredicate","title":"NSPredicate","abstract":[{"text":"A definition of logical conditions for constraining a search for a fetch or for in-memory filtering.","type":"text"}],"fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSPredicate"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate","type":"topic","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkoutEffortSamplesRelated(workout:activity:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForWorkoutEffortSamplesRelated","kind":"identifier"},{"text":"(","kind":"text"},{"text":"workout","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKWorkout","preciseIdentifier":"c:objc(cs)HKWorkout","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"activity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKWorkoutActivity","preciseIdentifier":"c:objc(cs)HKWorkoutActivity","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"NSPredicate","preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkoutEffortSamplesRelated(workout:activity:)","type":"topic","url":"/documentation/healthkit/hkquery/predicateforworkouteffortsamplesrelated(workout:activity:)","abstract":[],"role":"symbol","navigatorTitle":[{"text":"predicateForWorkoutEffortSamplesRelatedToWorkout:activity:","kind":"identifier"}],"title":"predicateForWorkoutEffortSamplesRelated(workout:activity:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"path":"/metadata/platforms","op":"replace","value":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"18.0"},{"beta":false,"deprecated":false,"introducedAt":"18.0","unavailable":false,"name":"iPadOS"},{"beta":false,"deprecated":false,"introducedAt":"18.0","unavailable":false,"name":"Mac Catalyst"},{"beta":false,"deprecated":false,"introducedAt":"15.0","unavailable":false,"name":"macOS"},{"beta":false,"deprecated":false,"introducedAt":"2.0","unavailable":false,"name":"visionOS"},{"beta":false,"deprecated":false,"introducedAt":"11.0","unavailable":false,"name":"watchOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Type Method"},{"path":"/metadata/title","op":"replace","value":"predicateForWorkoutEffortSamplesRelatedToWorkout:activity:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForWorkoutEffortSamplesRelatedToWorkout:activity:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKQuery"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"add","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate","text":"NSPredicate","preciseIdentifier":"c:objc(cs)NSPredicate"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"predicateForWorkoutEffortSamplesRelatedToWorkout:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkout","text":"HKWorkout","preciseIdentifier":"c:objc(cs)HKWorkout"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"workout"},{"kind":"text","text":" "},{"kind":"identifier","text":"activity:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutActivity","text":"HKWorkoutActivity","preciseIdentifier":"c:objc(cs)HKWorkoutActivity"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"activity"},{"kind":"text","text":";"}]}]}},{"value":"HKQuery","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/title"},{"value":[{"kind":"identifier","text":"HKQuery"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/fragments"},{"value":[{"kind":"identifier","text":"HKQuery"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/navigatorTitle"},{"value":"HKWorkout","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/title"},{"value":[{"kind":"identifier","text":"HKWorkout"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/fragments"},{"value":[{"text":"HKWorkout","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkout/navigatorTitle"},{"value":"HKWorkoutActivity","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/title"},{"value":[{"kind":"identifier","text":"HKWorkoutActivity"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/fragments"},{"value":[{"text":"HKWorkoutActivity","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutActivity/navigatorTitle"},{"value":"predicateForWorkoutEffortSamplesRelatedToWorkout:activity:","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkoutEffortSamplesRelated(workout:activity:)/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"predicateForWorkoutEffortSamplesRelatedToWorkout:activity:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkoutEffortSamplesRelated(workout:activity:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}