{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/healthkit/hkquery/predicateforworkouts(with:totalflightsclimbed:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/healthkit/hkquery/predicateforworkouts(with:totalflightsclimbed:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"predicateForWorkouts","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"operatorType","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSComparisonPredicate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSComparisonPredicate","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSComparisonPredicate"},{"text":".","kind":"text"},{"text":"Operator","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSPredicateOperatorType","identifier":"doc://com.externally.resolved.symbol/c:@E@NSPredicateOperatorType"},{"text":", ","kind":"text"},{"text":"totalFlightsClimbed","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKQuantity","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantity","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuantity"},{"text":") -> ","kind":"text"},{"text":"NSPredicate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"]}],"kind":"declarations"},{"parameters":[{"name":"operatorType","content":[{"inlineContent":[{"type":"text","text":"The operator to use when comparing the sample to the target number of flights climbed."}],"type":"paragraph"}]},{"name":"totalFlightsClimbed","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A quantity representing the target number of flights climbed."}]}]}],"kind":"parameters"},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"A predicate that matches workouts based on the number of flights climbed."}],"type":"paragraph"}],"kind":"content"},{"content":[{"anchor":"Discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This convenience method creates a predicate that compares the total flights climbed during a workout with a target number of flights climbed. The following sample uses the convenience method and a predicate format string to create equivalent predicates."}]},{"code":["let flightsClimbed = HKQuantity(unit: HKUnit.count(), doubleValue: 10.0)","let tenFlightsClimbed = HKQuery.predicateForWorkouts(with: .greaterThanOrEqualTo, totalFlightsClimbed: flightsClimbed)","","// Creating a predicate using a predicate format string.","let explicitTenFlightsClimbed = NSPredicate(format: \"%K >= %@\",","                                            HKPredicateKeyPathWorkoutTotalFlightsClimbed,","                                            flightsClimbed)"],"type":"codeListing","syntax":"swift"}],"kind":"content"}],"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalFlightsClimbed"]},{"generated":true,"anchor":"Creating-workout-predicates","title":"Creating workout predicates","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-5irg9","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(activityPredicate:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:duration:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:averageQuantity:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:maximumQuantity:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:minimumQuantity:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:sumQuantity:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalDistance:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalEnergyBurned:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalSwimmingStrokeCount:)"]}],"abstract":[{"type":"text","text":"Returns a predicate that matches workout samples based on the number of flights climbed."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","deprecationSummary":[{"inlineContent":[{"text":"Use predicateForWorkoutsWithOperatorType:quantityType:sumQuantity: passing the HKQuantityType for HKQuantityTypeIdentifierFlightsClimbed","type":"text"}],"type":"paragraph"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalFlightsClimbed:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKQuery"]]},"metadata":{"externalID":"c:objc(cs)HKQuery(cm)predicateForWorkoutsWithOperatorType:totalFlightsClimbed:","symbolKind":"method","extendedModule":"HealthKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForWorkouts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSComparisonPredicate","text":"NSComparisonPredicate"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSPredicateOperatorType","text":"Operator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalFlightsClimbed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantity","text":"HKQuantity"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate"}],"roleHeading":"Type Method","title":"predicateForWorkouts(with:totalFlightsClimbed:)","navigatorTitle":[{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:totalFlightsClimbed:"}],"platforms":[{"name":"iOS","introducedAt":"11.0","message":"Use predicateForWorkoutsWithOperatorType:quantityType:sumQuantity: passing the HKQuantityType for HKQuantityTypeIdentifierFlightsClimbed","deprecated":false,"beta":false,"unavailable":false,"deprecatedAt":"18.0"},{"name":"iPadOS","introducedAt":"11.0","message":"Use predicateForWorkoutsWithOperatorType:quantityType:sumQuantity: passing the HKQuantityType for HKQuantityTypeIdentifierFlightsClimbed","deprecated":false,"beta":false,"unavailable":false,"deprecatedAt":"18.0"},{"name":"Mac Catalyst","introducedAt":"13.0","message":"Use predicateForWorkoutsWithOperatorType:quantityType:sumQuantity: passing the HKQuantityType for HKQuantityTypeIdentifierFlightsClimbed","deprecated":false,"beta":false,"unavailable":false,"deprecatedAt":"18.0"},{"name":"macOS","introducedAt":"13.0","message":"Use predicateForWorkoutsWithOperatorType:quantityType:sumQuantity: passing the HKQuantityType for HKQuantityTypeIdentifierFlightsClimbed","deprecated":false,"beta":false,"unavailable":false,"deprecatedAt":"15.0"},{"name":"visionOS","introducedAt":"1.0","message":"Use predicateForWorkoutsWithOperatorType:quantityType:sumQuantity: passing the HKQuantityType for HKQuantityTypeIdentifierFlightsClimbed","deprecated":false,"beta":false,"unavailable":false,"deprecatedAt":"2.0"},{"name":"watchOS","introducedAt":"4.0","message":"Use predicateForWorkoutsWithOperatorType:quantityType:sumQuantity: passing the HKQuantityType for HKQuantityTypeIdentifierFlightsClimbed","deprecated":false,"beta":false,"unavailable":false,"deprecatedAt":"11.0"}],"modules":[{"name":"HealthKit"}],"role":"symbol"},"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKQuery":{"title":"HKQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKQuery"}],"url":"/documentation/healthkit/hkquery","abstract":[{"type":"text","text":"An abstract class for all the query classes in HealthKit."}],"kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKQuery"}]},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.externally.resolved.symbol/c:objc(cs)NSComparisonPredicate":{"url":"/documentation/foundation/nscomparisonpredicate","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSComparisonPredicate","role":"symbol","abstract":[{"text":"A specialized predicate for comparing expressions.","type":"text"}],"fragments":[{"text":"class ","kind":"text"},{"text":"NSComparisonPredicate","kind":"identifier"}],"kind":"symbol","title":"NSComparisonPredicate","type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-5irg9":{"abstract":[{"text":"Returns a predicate that matches any objects that have been associated with the provided workout.","type":"text"}],"title":"predicateForObjects(from:)","navigatorTitle":[{"text":"predicateForObjectsFromWorkout:","kind":"identifier"}],"url":"/documentation/healthkit/hkquery/predicateforobjects(from:)-5irg9","kind":"symbol","type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-5irg9","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForObjects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKWorkout","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKWorkout"},{"text":") -> ","kind":"text"},{"text":"NSPredicate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate"}]},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalFlightsClimbed:)":{"url":"/documentation/healthkit/hkquery/predicateforworkouts(with:totalflightsclimbed:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForWorkouts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSComparisonPredicate","kind":"typeIdentifier","text":"NSComparisonPredicate"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSPredicateOperatorType","kind":"typeIdentifier","text":"Operator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalFlightsClimbed"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)HKQuantity","kind":"typeIdentifier","text":"HKQuantity"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier","text":"NSPredicate"}],"title":"predicateForWorkouts(with:totalFlightsClimbed:)","type":"topic","abstract":[{"type":"text","text":"Returns a predicate that matches workout samples based on the number of flights climbed."}],"kind":"symbol","deprecated":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:totalFlightsClimbed:"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalFlightsClimbed:)"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalDistance:)":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalDistance:)","title":"predicateForWorkouts(with:totalDistance:)","abstract":[{"text":"Returns a predicate for matching workouts based on the total distance traveled.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForWorkouts","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSComparisonPredicate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSComparisonPredicate"},{"text":".","kind":"text"},{"text":"Operator","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSPredicateOperatorType"},{"text":", ","kind":"text"},{"text":"totalDistance","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKQuantity","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantity"},{"text":") -> ","kind":"text"},{"text":"NSPredicate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate"}],"navigatorTitle":[{"text":"predicateForWorkoutsWithOperatorType:totalDistance:","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"/documentation/healthkit/hkquery/predicateforworkouts(with:totaldistance:)","deprecated":true},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:duration:)":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:duration:)","url":"/documentation/healthkit/hkquery/predicateforworkouts(with:duration:)","title":"predicateForWorkouts(with:duration:)","abstract":[{"type":"text","text":"Returns a predicate for matching workouts based on their duration."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForWorkouts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSComparisonPredicate","kind":"typeIdentifier","text":"NSComparisonPredicate"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSPredicateOperatorType","kind":"typeIdentifier","text":"Operator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier","text":"NSPredicate"}],"navigatorTitle":[{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:duration:"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalFlightsClimbed":{"role":"symbol","abstract":[{"type":"text","text":"The key path for accessing the total number of flights of stairs climbed during the workout."}],"navigatorTitle":[{"text":"HKPredicateKeyPathWorkoutTotalFlightsClimbed","kind":"identifier"}],"deprecated":true,"title":"HKPredicateKeyPathWorkoutTotalFlightsClimbed","kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalFlightsClimbed","type":"topic","url":"/documentation/healthkit/hkpredicatekeypathworkouttotalflightsclimbed","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKPredicateKeyPathWorkoutTotalFlightsClimbed","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalSwimmingStrokeCount:)":{"navigatorTitle":[{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:totalSwimmingStrokeCount:"}],"title":"predicateForWorkouts(with:totalSwimmingStrokeCount:)","deprecated":true,"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalSwimmingStrokeCount:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForWorkouts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSComparisonPredicate","kind":"typeIdentifier","text":"NSComparisonPredicate"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSPredicateOperatorType","kind":"typeIdentifier","text":"Operator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalSwimmingStrokeCount"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)HKQuantity","kind":"typeIdentifier","text":"HKQuantity"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier","text":"NSPredicate"}],"role":"symbol","type":"topic","url":"/documentation/healthkit/hkquery/predicateforworkouts(with:totalswimmingstrokecount:)","kind":"symbol","abstract":[{"type":"text","text":"Returns a predicate that matches workout samples based on the number of strokes while swimming."}]},"doc://com.apple.healthkit/documentation/HealthKit/HKQuantity":{"title":"HKQuantity","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKQuantity","kind":"identifier"}],"url":"/documentation/healthkit/hkquantity","abstract":[{"text":"An object that stores a value for a given unit.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuantity","type":"topic","role":"symbol","navigatorTitle":[{"text":"HKQuantity","kind":"identifier"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalEnergyBurned:)":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForWorkouts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSComparisonPredicate","kind":"typeIdentifier","text":"NSComparisonPredicate"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSPredicateOperatorType","kind":"typeIdentifier","text":"Operator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalEnergyBurned"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)HKQuantity","kind":"typeIdentifier","text":"HKQuantity"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier","text":"NSPredicate"}],"title":"predicateForWorkouts(with:totalEnergyBurned:)","navigatorTitle":[{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:totalEnergyBurned:"}],"kind":"symbol","deprecated":true,"abstract":[{"type":"text","text":"Returns a predicate for matching workouts based on the total energy burned."}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalEnergyBurned:)","role":"symbol","url":"/documentation/healthkit/hkquery/predicateforworkouts(with:totalenergyburned:)"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:minimumQuantity:)":{"abstract":[{"text":"Returns a predicate for matching workout activities based the minimum value of an associated quantity type.","type":"text"}],"title":"predicateForWorkouts(operatorType:quantityType:minimumQuantity:)","navigatorTitle":[{"text":"predicateForWorkoutsWithOperatorType:quantityType:minimumQuantity:","kind":"identifier"}],"url":"/documentation/healthkit/hkquery/predicateforworkouts(operatortype:quantitytype:minimumquantity:)","kind":"symbol","type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:minimumQuantity:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForWorkouts","kind":"identifier"},{"text":"(","kind":"text"},{"text":"operatorType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSComparisonPredicate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSComparisonPredicate"},{"text":".","kind":"text"},{"text":"Operator","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSPredicateOperatorType"},{"text":", ","kind":"text"},{"text":"quantityType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKQuantityType","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantityType"},{"text":", ","kind":"text"},{"text":"minimumQuantity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKQuantity","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantity"},{"text":") -> ","kind":"text"},{"text":"NSPredicate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(activityPredicate:)":{"type":"topic","url":"/documentation/healthkit/hkquery/predicateforworkouts(activitypredicate:)","title":"predicateForWorkouts(activityPredicate:)","role":"symbol","kind":"symbol","abstract":[{"text":"Returns a predicate for matching workouts based on the associated workout activities.","type":"text"}],"navigatorTitle":[{"text":"predicateForWorkoutsWithActivityPredicate:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForWorkouts","kind":"identifier"},{"text":"(","kind":"text"},{"text":"activityPredicate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPredicate","preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSPredicate","preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(activityPredicate:)"},"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate":{"url":"/documentation/foundation/nspredicate","title":"NSPredicate","abstract":[{"text":"A definition of logical conditions for constraining a search for a fetch or for in-memory filtering.","type":"text"}],"fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSPredicate"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate","type":"topic","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:)":{"url":"/documentation/healthkit/hkquery/predicateforworkouts(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"predicateForWorkoutsWithWorkoutActivityType:","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicateForWorkouts","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HKWorkoutActivityType","preciseIdentifier":"c:@E@HKWorkoutActivityType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSPredicate","preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier"}],"title":"predicateForWorkouts(with:)","abstract":[{"type":"text","text":"Returns a predicate for matching workouts based on the type of activity."}]},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:maximumQuantity:)":{"type":"topic","title":"predicateForWorkouts(operatorType:quantityType:maximumQuantity:)","abstract":[{"type":"text","text":"Returns a predicate for matching workout activities based the maximum value of an associated quantity type."}],"role":"symbol","url":"/documentation/healthkit/hkquery/predicateforworkouts(operatortype:quantitytype:maximumquantity:)","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForWorkouts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"operatorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSComparisonPredicate","text":"NSComparisonPredicate"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSPredicateOperatorType","text":"Operator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"quantityType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantityType","text":"HKQuantityType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maximumQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantity","text":"HKQuantity"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:maximumQuantity:)","navigatorTitle":[{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:quantityType:maximumQuantity:"}]},"doc://com.externally.resolved.symbol/c:@E@NSPredicateOperatorType":{"identifier":"doc://com.externally.resolved.symbol/c:@E@NSPredicateOperatorType","url":"/documentation/foundation/nscomparisonpredicate/operator","title":"NSComparisonPredicate.Operator","abstract":[{"text":"Defines the type of comparison for a comparison predicate.","type":"text"}],"fragments":[{"text":"enum ","kind":"text"},{"text":"NSComparisonPredicate.Operator","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:sumQuantity:)":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"predicateForWorkouts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"operatorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSComparisonPredicate","text":"NSComparisonPredicate"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSPredicateOperatorType","text":"Operator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"quantityType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantityType","text":"HKQuantityType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sumQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantity","text":"HKQuantity"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate","text":"NSPredicate"}],"title":"predicateForWorkouts(operatorType:quantityType:sumQuantity:)","navigatorTitle":[{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:quantityType:sumQuantity:"}],"kind":"symbol","abstract":[{"type":"text","text":"Returns a predicate for matching workout activities based the sum of an associated quantity type."}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:sumQuantity:)","role":"symbol","url":"/documentation/healthkit/hkquery/predicateforworkouts(operatortype:quantitytype:sumquantity:)"},"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:averageQuantity:)":{"url":"/documentation/healthkit/hkquery/predicateforworkouts(operatortype:quantitytype:averagequantity:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"predicateForWorkoutsWithOperatorType:quantityType:averageQuantity:","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:averageQuantity:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"predicateForWorkouts","kind":"identifier"},{"kind":"text","text":"("},{"text":"operatorType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSComparisonPredicate","kind":"typeIdentifier","text":"NSComparisonPredicate"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSPredicateOperatorType","text":"Operator"},{"text":", ","kind":"text"},{"text":"quantityType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)HKQuantityType","kind":"typeIdentifier","text":"HKQuantityType"},{"kind":"text","text":", "},{"text":"averageQuantity","kind":"externalParam"},{"kind":"text","text":": "},{"text":"HKQuantity","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)HKQuantity"},{"text":") -> ","kind":"text"},{"text":"NSPredicate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPredicate"}],"title":"predicateForWorkouts(operatorType:quantityType:averageQuantity:)","abstract":[{"type":"text","text":"Returns a predicate for matching workouts based the average value of an associated quantity type."}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"iOS","beta":false,"introducedAt":"11.0","unavailable":false,"deprecatedAt":"18.0","deprecated":false},{"name":"iPadOS","beta":false,"introducedAt":"11.0","unavailable":false,"deprecatedAt":"18.0","deprecated":false},{"name":"Mac Catalyst","beta":false,"introducedAt":"13.0","unavailable":false,"deprecatedAt":"18.0","deprecated":false},{"name":"macOS","beta":false,"introducedAt":"13.0","unavailable":false,"deprecatedAt":"15.0","deprecated":false},{"name":"visionOS","beta":false,"introducedAt":"1.0","unavailable":false,"deprecatedAt":"2.0","deprecated":false},{"name":"watchOS","beta":false,"introducedAt":"4.0","unavailable":false,"deprecatedAt":"11.0","deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Type Method"},{"path":"/metadata/title","op":"replace","value":"predicateForWorkoutsWithOperatorType:totalFlightsClimbed:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:totalFlightsClimbed:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKQuery"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKPredicateKeyPathWorkoutTotalFlightsClimbed"],"title":"Related Documentation","anchor":"Related-Documentation"},{"generated":true,"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForObjects(from:)-5irg9","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(activityPredicate:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:duration:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:averageQuantity:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:maximumQuantity:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:minimumQuantity:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(operatorType:quantityType:sumQuantity:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalDistance:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalEnergyBurned:)","doc://com.apple.healthkit/documentation/HealthKit/HKQuery/predicateForWorkouts(with:totalSwimmingStrokeCount:)"],"title":"Creating workout predicates","anchor":"Creating-workout-predicates"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate","kind":"typeIdentifier","text":"NSPredicate","preciseIdentifier":"c:objc(cs)NSPredicate"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:"},{"kind":"text","text":"("},{"identifier":"doc://com.externally.resolved.symbol/c:@E@NSPredicateOperatorType","kind":"typeIdentifier","text":"NSPredicateOperatorType","preciseIdentifier":"c:@E@NSPredicateOperatorType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"operatorType"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalFlightsClimbed:"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKQuantity","kind":"typeIdentifier","text":"HKQuantity","preciseIdentifier":"c:objc(cs)HKQuantity"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"totalFlightsClimbed"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The operator to use when comparing the sample to the target number of flights climbed.","type":"text"}],"type":"paragraph"}],"name":"operatorType"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A quantity representing the target number of flights climbed.","type":"text"}]}],"name":"totalFlightsClimbed"}]},"path":"/primaryContentSections/1"},{"path":"/primaryContentSections/2","op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"A predicate that matches workouts based on the number of flights climbed."}],"type":"paragraph"}]}},{"op":"replace","value":[{"inlineContent":[{"text":"Use predicateForWorkoutsWithOperatorType:quantityType:sumQuantity: passing the HKQuantityType for HKQuantityTypeIdentifierFlightsClimbed","type":"text"}],"type":"paragraph"}],"path":"/deprecationSummary"},{"op":"replace","value":"HKQuery","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/title"},{"op":"replace","value":[{"text":"HKQuery","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/fragments"},{"op":"replace","value":[{"text":"HKQuery","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery/navigatorTitle"},{"op":"replace","value":"predicateForObjectsFromWorkout:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-5irg9/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForObjectsFromWorkout:"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForObjects(from:)-5irg9/fragments"},{"op":"replace","value":"predicateForWorkoutsWithOperatorType:totalFlightsClimbed:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:totalFlightsClimbed:)/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:totalFlightsClimbed:"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:totalFlightsClimbed:)/fragments"},{"op":"replace","value":"predicateForWorkoutsWithOperatorType:totalDistance:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:totalDistance:)/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:totalDistance:"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:totalDistance:)/fragments"},{"op":"replace","value":"predicateForWorkoutsWithOperatorType:duration:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:duration:)/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:duration:"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:duration:)/fragments"},{"op":"replace","value":"HKPredicateKeyPathWorkoutTotalFlightsClimbed","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutTotalFlightsClimbed/title"},{"op":"replace","value":[{"kind":"identifier","text":"HKPredicateKeyPathWorkoutTotalFlightsClimbed"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKPredicateKeyPathWorkoutTotalFlightsClimbed/fragments"},{"op":"replace","value":"predicateForWorkoutsWithOperatorType:totalSwimmingStrokeCount:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:totalSwimmingStrokeCount:)/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:totalSwimmingStrokeCount:"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:totalSwimmingStrokeCount:)/fragments"},{"op":"replace","value":"HKQuantity","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/title"},{"op":"replace","value":[{"kind":"identifier","text":"HKQuantity"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/fragments"},{"op":"replace","value":[{"text":"HKQuantity","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuantity/navigatorTitle"},{"op":"replace","value":"predicateForWorkoutsWithOperatorType:totalEnergyBurned:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:totalEnergyBurned:)/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:totalEnergyBurned:"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:totalEnergyBurned:)/fragments"},{"op":"replace","value":"predicateForWorkoutsWithOperatorType:quantityType:minimumQuantity:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(operatorType:quantityType:minimumQuantity:)/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:quantityType:minimumQuantity:"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(operatorType:quantityType:minimumQuantity:)/fragments"},{"op":"replace","value":"predicateForWorkoutsWithActivityPredicate:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(activityPredicate:)/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForWorkoutsWithActivityPredicate:"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(activityPredicate:)/fragments"},{"op":"replace","value":"predicateForWorkoutsWithWorkoutActivityType:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:)/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"predicateForWorkoutsWithWorkoutActivityType:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(with:)/fragments"},{"op":"replace","value":"predicateForWorkoutsWithOperatorType:quantityType:maximumQuantity:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(operatorType:quantityType:maximumQuantity:)/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"predicateForWorkoutsWithOperatorType:quantityType:maximumQuantity:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(operatorType:quantityType:maximumQuantity:)/fragments"},{"op":"replace","value":"predicateForWorkoutsWithOperatorType:quantityType:sumQuantity:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(operatorType:quantityType:sumQuantity:)/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"predicateForWorkoutsWithOperatorType:quantityType:sumQuantity:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(operatorType:quantityType:sumQuantity:)/fragments"},{"op":"replace","value":"predicateForWorkoutsWithOperatorType:quantityType:averageQuantity:","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(operatorType:quantityType:averageQuantity:)/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"predicateForWorkoutsWithOperatorType:quantityType:averageQuantity:"}],"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKQuery~1predicateForWorkouts(operatorType:quantityType:averageQuantity:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}