{
  "abstract": [
    {
      "text": "An error message that indicates a stream is already running or doesn’t exist when trying to start a stream.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToStartStreamState"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SCStreamErrorCode@SCStreamErrorAttemptToStartStreamState",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "attemptToStartStreamState"
      }
    ],
    "modules": [
      {
        "name": "ScreenCaptureKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCStreamErrorAttemptToStartStreamState"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SCStreamError.Code.attemptToStartStreamState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "attemptToStartStreamState"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit": {
      "abstract": [
        {
          "text": "Filter and select screen content and stream it to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ScreenCaptureKit",
      "type": "topic",
      "url": "/documentation/screencapturekit"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError": {
      "abstract": [
        {
          "text": "An instance representing a ScreenCaptureKit framework error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCStreamError"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamError"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code": {
      "abstract": [
        {
          "text": "Codes for user cancellation events and errors that can occur in ScreenCaptureKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToConfigState": {
      "abstract": [
        {
          "text": "An error message that indicates a stream couldn’t update its configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attemptToConfigState"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToConfigState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorAttemptToConfigState"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.attemptToConfigState",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/attempttoconfigstate"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToStartStreamState": {
      "abstract": [
        {
          "text": "An error message that indicates a stream is already running or doesn’t exist when trying to start a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attemptToStartStreamState"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToStartStreamState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorAttemptToStartStreamState"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.attemptToStartStreamState",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/attempttostartstreamstate"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToStopStreamState": {
      "abstract": [
        {
          "text": "An error message that indicates a stream is already stopped or doesn’t exist when trying to stop a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attemptToStopStreamState"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToStopStreamState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorAttemptToStopStreamState"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.attemptToStopStreamState",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/attempttostopstreamstate"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToUpdateFilterState": {
      "abstract": [
        {
          "text": "An error message that indicates a stream couldn’t update its content filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attemptToUpdateFilterState"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToUpdateFilterState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorAttemptToUpdateFilterState"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.attemptToUpdateFilterState",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/attempttoupdatefilterstate"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStart": {
      "abstract": [
        {
          "text": "An error message that indicates a stream failed to start.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToStart"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorFailedToStart"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.failedToStart",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/failedtostart"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStartAudioCapture": {
      "abstract": [
        {
          "text": "An error message that indicates an audio stream failed to start.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToStartAudioCapture"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStartAudioCapture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorFailedToStartAudioCapture"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.failedToStartAudioCapture",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/failedtostartaudiocapture"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStartMicrophoneCapture": {
      "abstract": [
        {
          "text": "An error message that indicates microphone capture failed to start.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToStartMicrophoneCapture"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStartMicrophoneCapture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorFailedToStartMicrophoneCapture"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.failedToStartMicrophoneCapture",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/failedtostartmicrophonecapture"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStopAudioCapture": {
      "abstract": [
        {
          "text": "An error message that indicates an audio stream failed to stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToStopAudioCapture"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStopAudioCapture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorFailedToStopAudioCapture"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.failedToStopAudioCapture",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/failedtostopaudiocapture"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/internalError": {
      "abstract": [
        {
          "text": "An error message that indicates a stream can’t start due to a failure in ScreenCaptureKit’s internals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/internalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorInternalError"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.internalError",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/internalerror"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/removingStream": {
      "abstract": [
        {
          "text": "An error message that indicates a stream wasn’t removed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removingStream"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/removingStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorRemovingStream"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.removingStream",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/removingstream"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/systemStoppedStream": {
      "abstract": [
        {
          "text": "An error message that indicates the system stopped the stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemStoppedStream"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/systemStoppedStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorSystemStoppedStream"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.systemStoppedStream",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/systemstoppedstream"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Stream-management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToStopStreamState",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToUpdateFilterState",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToConfigState",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStart",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/removingStream",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStartAudioCapture",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStopAudioCapture",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStartMicrophoneCapture",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/systemStoppedStream",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/internalError"
      ],
      "title": "Stream management"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCStreamErrorAttemptToStartStreamState"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorAttemptToStartStreamState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Stream-management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToStopStreamState",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToUpdateFilterState",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/attemptToConfigState",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStart",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/removingStream",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStartAudioCapture",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStopAudioCapture",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedToStartMicrophoneCapture",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/systemStoppedStream",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/internalError"
              ],
              "title": "Stream management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SCStreamErrorAttemptToStartStreamState"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedToStartAudioCapture/title",
          "value": "SCStreamErrorFailedToStartAudioCapture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedToStartAudioCapture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorFailedToStartAudioCapture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedToStopAudioCapture/title",
          "value": "SCStreamErrorFailedToStopAudioCapture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedToStopAudioCapture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorFailedToStopAudioCapture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1removingStream/title",
          "value": "SCStreamErrorRemovingStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1removingStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorRemovingStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1attemptToConfigState/title",
          "value": "SCStreamErrorAttemptToConfigState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1attemptToConfigState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorAttemptToConfigState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code/title",
          "value": "SCStreamErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedToStart/title",
          "value": "SCStreamErrorFailedToStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedToStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorFailedToStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1attemptToUpdateFilterState/title",
          "value": "SCStreamErrorAttemptToUpdateFilterState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1attemptToUpdateFilterState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorAttemptToUpdateFilterState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedToStartMicrophoneCapture/title",
          "value": "SCStreamErrorFailedToStartMicrophoneCapture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedToStartMicrophoneCapture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorFailedToStartMicrophoneCapture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1systemStoppedStream/title",
          "value": "SCStreamErrorSystemStoppedStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1systemStoppedStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorSystemStoppedStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1attemptToStartStreamState/title",
          "value": "SCStreamErrorAttemptToStartStreamState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1attemptToStartStreamState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorAttemptToStartStreamState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1attemptToStopStreamState/title",
          "value": "SCStreamErrorAttemptToStopStreamState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1attemptToStopStreamState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorAttemptToStopStreamState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1internalError/title",
          "value": "SCStreamErrorInternalError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1internalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorInternalError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/screencapturekit/scstreamerror/code/attempttostartstreamstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/screencapturekit/scstreamerror/code/attempttostartstreamstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
