{
  "abstract": [
    {
      "text": "An error message that indicates the stream lost its connection to an app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedApplicationConnectionInvalid"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SCStreamErrorCode@SCStreamErrorFailedApplicationConnectionInvalid",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "failedApplicationConnectionInvalid"
      }
    ],
    "modules": [
      {
        "name": "ScreenCaptureKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCStreamErrorFailedApplicationConnectionInvalid"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SCStreamError.Code.failedApplicationConnectionInvalid"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "failedApplicationConnectionInvalid"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit": {
      "abstract": [
        {
          "text": "Filter and select screen content and stream it to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ScreenCaptureKit",
      "type": "topic",
      "url": "/documentation/screencapturekit"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError": {
      "abstract": [
        {
          "text": "An instance representing a ScreenCaptureKit framework error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCStreamError"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamError"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code": {
      "abstract": [
        {
          "text": "Codes for user cancellation events and errors that can occur in ScreenCaptureKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedApplicationConnectionInterrupted": {
      "abstract": [
        {
          "text": "An error message that indicates there was an interruption in a connection to an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedApplicationConnectionInterrupted"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedApplicationConnectionInterrupted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorFailedApplicationConnectionInterrupted"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.failedApplicationConnectionInterrupted",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/failedapplicationconnectioninterrupted"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedApplicationConnectionInvalid": {
      "abstract": [
        {
          "text": "An error message that indicates the stream lost its connection to an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedApplicationConnectionInvalid"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedApplicationConnectionInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorFailedApplicationConnectionInvalid"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.failedApplicationConnectionInvalid",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/failedapplicationconnectioninvalid"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedNoMatchingApplicationContext": {
      "abstract": [
        {
          "text": "An error message that indicates there isn’t a matching app context for streaming.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedNoMatchingApplicationContext"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedNoMatchingApplicationContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorFailedNoMatchingApplicationContext"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.failedNoMatchingApplicationContext",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/failednomatchingapplicationcontext"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noCaptureSource": {
      "abstract": [
        {
          "text": "An error message that indicates a stream doesn’t have a source to capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noCaptureSource"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noCaptureSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorNoCaptureSource"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.noCaptureSource",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/nocapturesource"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noDisplayList": {
      "abstract": [
        {
          "text": "An error message that indicates a stream doesn’t have displays available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noDisplayList"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noDisplayList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorNoDisplayList"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.noDisplayList",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/nodisplaylist"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noWindowList": {
      "abstract": [
        {
          "text": "An error message that indicates a stream doesn’t have windows available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noWindowList"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noWindowList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCStreamErrorNoWindowList"
        }
      ],
      "role": "symbol",
      "title": "SCStreamError.Code.noWindowList",
      "type": "topic",
      "url": "/documentation/screencapturekit/scstreamerror/code/nowindowlist"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Shareable-content",
      "generated": true,
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noCaptureSource",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noDisplayList",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noWindowList",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedApplicationConnectionInterrupted",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedNoMatchingApplicationContext"
      ],
      "title": "Shareable content"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCStreamErrorFailedApplicationConnectionInvalid"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorFailedApplicationConnectionInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Shareable-content",
              "generated": true,
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noCaptureSource",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noDisplayList",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/noWindowList",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedApplicationConnectionInterrupted",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCStreamError/Code/failedNoMatchingApplicationContext"
              ],
              "title": "Shareable content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SCStreamErrorFailedApplicationConnectionInvalid"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedApplicationConnectionInterrupted/title",
          "value": "SCStreamErrorFailedApplicationConnectionInterrupted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedApplicationConnectionInterrupted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorFailedApplicationConnectionInterrupted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1noCaptureSource/title",
          "value": "SCStreamErrorNoCaptureSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1noCaptureSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorNoCaptureSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedApplicationConnectionInvalid/title",
          "value": "SCStreamErrorFailedApplicationConnectionInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedApplicationConnectionInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorFailedApplicationConnectionInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code/title",
          "value": "SCStreamErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedNoMatchingApplicationContext/title",
          "value": "SCStreamErrorFailedNoMatchingApplicationContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1failedNoMatchingApplicationContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorFailedNoMatchingApplicationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1noDisplayList/title",
          "value": "SCStreamErrorNoDisplayList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1noDisplayList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorNoDisplayList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1noWindowList/title",
          "value": "SCStreamErrorNoWindowList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCStreamError~1Code~1noWindowList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCStreamErrorNoWindowList"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/screencapturekit/scstreamerror/code/failedapplicationconnectioninvalid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/screencapturekit/scstreamerror/code/failedapplicationconnectioninvalid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
