{
  "abstract": [
    {
      "text": "Creates a skinner object with the specified visible geometry and skeleton information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner/init(baseGeometry:bones:boneInverseBindTransforms:boneWeights:boneIndices:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SCNSkinner(cm)skinnerWithBaseGeometry:bones:boneInverseBindTransforms:boneWeights:boneIndices:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "baseGeometry"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SCNGeometry",
        "text": "SCNGeometry"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "bones"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SCNNode",
        "text": "SCNNode"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "boneInverseBindTransforms"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSValue",
        "text": "NSValue"
      },
      {
        "kind": "text",
        "text": "]?, "
      },
      {
        "kind": "externalParam",
        "text": "boneWeights"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SCNGeometrySource",
        "text": "SCNGeometrySource"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "boneIndices"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SCNGeometrySource",
        "text": "SCNGeometrySource"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "skinnerWithBaseGeometry:bones:boneInverseBindTransforms:boneWeights:boneIndices:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(baseGeometry:bones:boneInverseBindTransforms:boneWeights:boneIndices:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "baseGeometry"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SCNGeometry",
              "text": "SCNGeometry"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "bones"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SCNNode",
              "text": "SCNNode"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "boneInverseBindTransforms"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSValue",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSValue",
              "text": "NSValue"
            },
            {
              "kind": "text",
              "text": "]?, "
            },
            {
              "kind": "externalParam",
              "text": "boneWeights"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SCNGeometrySource",
              "text": "SCNGeometrySource"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "boneIndices"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SCNGeometrySource",
              "text": "SCNGeometrySource"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The geometry whose surface the skinner’s animation skeleton deforms.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "baseGeometry"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " objects, each representing a bone or control point for the animation skeleton.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "bones"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/nsvalue",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " objects containing ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " transforms, each of which corresponds to a node in the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner/bones",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " array. Each value is the inverse of the bone node’s transform from bind space (that is, of the concatenation of all transforms from the skeleton root down to that bone) in the skeleton’s default pose.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "boneInverseBindTransforms"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The geometry source defining the influence of each bone on the positions of vertices in the geometry. For details, see the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner/boneWeights",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "boneWeights"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The geometry source defining the mapping from bone indices in skeleton data to the skinner’s bones array. For details, see the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner/boneIndices",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "boneIndices"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new skinner object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To use the skinner object in a scene, assign it to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode/skinner",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of a node. That node’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode/geometry",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property should reference the same ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object as the skinner’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner/baseGeometry",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsvalue": {
      "abstract": [
        {
          "text": "A simple container for a single C or Objective-C data item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSValue"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsvalue",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSValue",
      "type": "topic",
      "url": "/documentation/foundation/nsvalue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry": {
      "abstract": [
        {
          "text": "A three-dimensional shape (also called a model or mesh) that can be displayed in a scene, with attached materials that define its appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNGeometry"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNGeometry"
        }
      ],
      "role": "symbol",
      "title": "SCNGeometry",
      "type": "topic",
      "url": "/documentation/scenekit/scngeometry"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource": {
      "abstract": [
        {
          "text": "A container for vertex data forming part of the definition for a three-dimensional object, or geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNGeometrySource"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNGeometrySource"
        }
      ],
      "role": "symbol",
      "title": "SCNGeometrySource",
      "type": "topic",
      "url": "/documentation/scenekit/scngeometrysource"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct": {
      "abstract": [
        {
          "text": "A representation of a 4 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMatrix4"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMatrix4"
        }
      ],
      "role": "symbol",
      "title": "SCNMatrix4",
      "type": "topic",
      "url": "/documentation/scenekit/scnmatrix4-swift.struct"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNNode": {
      "abstract": [
        {
          "text": "A structural element of a scene graph, representing a position and transform in a 3D coordinate space, to which you can attach geometry, lights, cameras, or other displayable content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNNode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNNode"
        }
      ],
      "role": "symbol",
      "title": "SCNNode",
      "type": "topic",
      "url": "/documentation/scenekit/scnnode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNNode/geometry": {
      "abstract": [
        {
          "text": "The geometry attached to the node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "geometry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNGeometry",
          "text": "SCNGeometry"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode/geometry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "geometry"
        }
      ],
      "role": "symbol",
      "title": "geometry",
      "type": "topic",
      "url": "/documentation/scenekit/scnnode/geometry"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNNode/skinner": {
      "abstract": [
        {
          "text": "The skinner object responsible for skeletal animations of node’s contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "skinner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSkinner",
          "text": "SCNSkinner"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode/skinner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "skinner"
        }
      ],
      "role": "symbol",
      "title": "skinner",
      "type": "topic",
      "url": "/documentation/scenekit/scnnode/skinner"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner": {
      "abstract": [
        {
          "text": "An object that manages the relationship between skeletal animations and the nodes and geometries they animate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSkinner"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSkinner"
        }
      ],
      "role": "symbol",
      "title": "SCNSkinner",
      "type": "topic",
      "url": "/documentation/scenekit/scnskinner"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner/baseGeometry": {
      "abstract": [
        {
          "text": "The geometry whose surface the skinner’s animation skeleton deforms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "baseGeometry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNGeometry",
          "text": "SCNGeometry"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner/baseGeometry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "baseGeometry"
        }
      ],
      "role": "symbol",
      "title": "baseGeometry",
      "type": "topic",
      "url": "/documentation/scenekit/scnskinner/basegeometry"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner/boneIndices": {
      "abstract": [
        {
          "text": "The geometry source defining the mapping from bone indices in skeleton data to the skinner’s bones array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boneIndices"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNGeometrySource",
          "text": "SCNGeometrySource"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner/boneIndices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "boneIndices"
        }
      ],
      "role": "symbol",
      "title": "boneIndices",
      "type": "topic",
      "url": "/documentation/scenekit/scnskinner/boneindices"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner/boneWeights": {
      "abstract": [
        {
          "text": "The geometry source that defines the influence of each bone on the positions the geometry’s vertices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boneWeights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNGeometrySource",
          "text": "SCNGeometrySource"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner/boneWeights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "boneWeights"
        }
      ],
      "role": "symbol",
      "title": "boneWeights",
      "type": "topic",
      "url": "/documentation/scenekit/scnskinner/boneweights"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner/bones": {
      "abstract": [
        {
          "text": "The control nodes of the animation skeleton.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bones"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNNode",
          "text": "SCNNode"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner/bones",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bones"
        }
      ],
      "role": "symbol",
      "title": "bones",
      "type": "topic",
      "url": "/documentation/scenekit/scnskinner/bones"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner/init(baseGeometry:bones:boneInverseBindTransforms:boneWeights:boneIndices:)": {
      "abstract": [
        {
          "text": "Creates a skinner object with the specified visible geometry and skeleton information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "baseGeometry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNGeometry",
          "text": "SCNGeometry"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "bones"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNNode",
          "text": "SCNNode"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "boneInverseBindTransforms"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSValue",
          "text": "NSValue"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "boneWeights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNGeometrySource",
          "text": "SCNGeometrySource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "boneIndices"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNGeometrySource",
          "text": "SCNGeometrySource"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner/init(baseGeometry:bones:boneInverseBindTransforms:boneWeights:boneIndices:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "skinnerWithBaseGeometry:bones:boneInverseBindTransforms:boneWeights:boneIndices:"
        }
      ],
      "role": "symbol",
      "title": "init(baseGeometry:bones:boneInverseBindTransforms:boneWeights:boneIndices:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnskinner/init(basegeometry:bones:boneinversebindtransforms:boneweights:boneindices:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSValue": {
      "abstract": [
        {
          "text": "A simple container for a single C or Objective-C data item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSValue"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSValue",
      "type": "topic",
      "url": "/documentation/foundation/nsvalue"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "skinnerWithBaseGeometry:bones:boneInverseBindTransforms:boneWeights:boneIndices:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "skinnerWithBaseGeometry:bones:boneInverseBindTransforms:boneWeights:boneIndices:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "skinnerWithBaseGeometry:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometry",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SCNGeometry",
                    "text": "SCNGeometry"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "baseGeometry"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "bones:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<SCNNode *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "bones"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "boneInverseBindTransforms:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSValue *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "boneInverseBindTransforms"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "boneWeights:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SCNGeometrySource",
                    "text": "SCNGeometrySource"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "boneWeights"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "boneIndices:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNGeometrySource",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SCNGeometrySource",
                    "text": "SCNGeometrySource"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "boneIndices"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The geometry whose surface the skinner’s animation skeleton deforms.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "baseGeometry"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " objects, each representing a bone or control point for the animation skeleton.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "bones"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/foundation/nsvalue",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " objects containing ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMatrix4-swift.struct",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " transforms, each of which corresponds to a node in the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner/bones",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " array. Each value is the inverse of the bone node’s transform from bind space (that is, of the concatenation of all transforms from the skeleton root down to that bone) in the skeleton’s default pose.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "boneInverseBindTransforms"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The geometry source defining the influence of each bone on the positions of vertices in the geometry. For details, see the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner/boneWeights",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " property.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "boneWeights"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The geometry source defining the mapping from bone indices in skeleton data to the skinner’s bones array. For details, see the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSkinner/boneIndices",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " property.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "boneIndices"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new skinner object.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/title",
          "value": "SCNGeometry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner~1boneWeights/title",
          "value": "boneWeights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner~1boneWeights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "boneWeights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner/title",
          "value": "SCNSkinner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSkinner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSkinner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner~1baseGeometry/title",
          "value": "baseGeometry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner~1baseGeometry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "baseGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometrySource/title",
          "value": "SCNGeometrySource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometrySource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometrySource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNGeometrySource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNGeometrySource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/title",
          "value": "SCNNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct/title",
          "value": "SCNMatrix4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMatrix4-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMatrix4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner~1init(baseGeometry:bones:boneInverseBindTransforms:boneWeights:boneIndices:)/title",
          "value": "skinnerWithBaseGeometry:bones:boneInverseBindTransforms:boneWeights:boneIndices:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner~1init(baseGeometry:bones:boneInverseBindTransforms:boneWeights:boneIndices:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "skinnerWithBaseGeometry:bones:boneInverseBindTransforms:boneWeights:boneIndices:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner~1boneIndices/title",
          "value": "boneIndices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner~1boneIndices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "boneIndices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1skinner/title",
          "value": "skinner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1skinner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "skinner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1geometry/title",
          "value": "geometry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1geometry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "geometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner~1bones/title",
          "value": "bones"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSkinner~1bones/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bones"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnskinner/init(basegeometry:bones:boneinversebindtransforms:boneweights:boneindices:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnskinner/init(basegeometry:bones:boneinversebindtransforms:boneweights:boneindices:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
