{
  "abstract": [
    {
      "text": "Only one segment in the control can be selected at a time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl",
        "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/selectOne"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSSegmentSwitchTracking@NSSegmentSwitchTrackingSelectOne",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "selectOne"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSSegmentSwitchTrackingSelectOne"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSSegmentedControl.SwitchTracking.selectOne"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "selectOne"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This mode functions as a radio button and is illustrated by the view selection control in Finder, which allows you to toggle between icon view, list view, column view, and Cover Flow.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSControl/isContinuous": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the receiver’s cell sends its action message continuously to its target during mouse tracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isContinuous"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/isContinuous",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "continuous"
        }
      ],
      "role": "symbol",
      "title": "isContinuous",
      "type": "topic",
      "url": "/documentation/appkit/nscontrol/iscontinuous"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl": {
      "abstract": [
        {
          "text": "Display one or more buttons in a single horizontal group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSegmentedControl"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSegmentedControl"
        }
      ],
      "role": "symbol",
      "title": "NSSegmentedControl",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking": {
      "abstract": [
        {
          "text": "The following constants specify the type of tracking behavior a segmented control exhibits. They are used by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/trackingMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SwitchTracking"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SwitchTracking"
        }
      ],
      "role": "symbol",
      "title": "NSSegmentedControl.SwitchTracking",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol/switchtracking"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/momentary": {
      "abstract": [
        {
          "text": "A segment is selected only when the user is pressing the mouse down within the bounds of the segment. When the mouse is no longer down within the segment, the segment is automatically deselected. A momentary segmented control sends an action when the user clicks a segment, and another action when the user releases the segment. If configured as continuous (see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/isContinuous",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": "), the control also sends actions at repeating intervals until the user releases the segment, at which point the control sends its final action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "momentary"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/momentary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSegmentSwitchTrackingMomentary"
        }
      ],
      "role": "symbol",
      "title": "NSSegmentedControl.SwitchTracking.momentary",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol/switchtracking/momentary"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/momentaryAccelerator": {
      "abstract": [
        {
          "text": "On pressure-sensitive systems, when the user force clicks a segment, a momentary accelerator segmented control sends repeating actions as pressure changes occur. The control stops sending actions when the user releases pressure. A document-based app, for example, might implement a momentary accelerator segmented control in order to allow a user to adjust the speed of paging by using variable pressure. In this example, actions are sent to the app to indicate when pressure on the control has changed. The app then determines the amount of pressure currently applied, and adjusts navigation speed accordingly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "momentaryAccelerator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/momentaryAccelerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSegmentSwitchTrackingMomentaryAccelerator"
        }
      ],
      "role": "symbol",
      "title": "NSSegmentedControl.SwitchTracking.momentaryAccelerator",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol/switchtracking/momentaryaccelerator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/selectAny": {
      "abstract": [
        {
          "text": "One or more segment cells in the control can be selected at a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectAny"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/selectAny",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSegmentSwitchTrackingSelectAny"
        }
      ],
      "role": "symbol",
      "title": "NSSegmentedControl.SwitchTracking.selectAny",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol/switchtracking/selectany"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/selectOne": {
      "abstract": [
        {
          "text": "Only one segment in the control can be selected at a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectOne"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/selectOne",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSegmentSwitchTrackingSelectOne"
        }
      ],
      "role": "symbol",
      "title": "NSSegmentedControl.SwitchTracking.selectOne",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol/switchtracking/selectone"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/trackingMode": {
      "abstract": [
        {
          "text": "The type of tracking behavior the control exhibits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSegmentedControl",
          "text": "NSSegmentedControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSegmentSwitchTracking",
          "text": "SwitchTracking"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/trackingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trackingMode"
        }
      ],
      "role": "symbol",
      "title": "trackingMode",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol/trackingmode"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/selectAny",
        "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/momentary",
        "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/momentaryAccelerator"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSSegmentSwitchTrackingSelectOne"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentSwitchTrackingSelectOne"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/selectAny",
                "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/momentary",
                "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/momentaryAccelerator"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSSegmentSwitchTrackingSelectOne"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1SwitchTracking~1selectOne/title",
          "value": "NSSegmentSwitchTrackingSelectOne"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1SwitchTracking~1selectOne/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentSwitchTrackingSelectOne"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1SwitchTracking~1selectAny/title",
          "value": "NSSegmentSwitchTrackingSelectAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1SwitchTracking~1selectAny/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentSwitchTrackingSelectAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1trackingMode/title",
          "value": "trackingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1trackingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trackingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1SwitchTracking/title",
          "value": "NSSegmentSwitchTracking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1SwitchTracking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentSwitchTracking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1SwitchTracking/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentSwitchTracking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1isContinuous/title",
          "value": "continuous"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1isContinuous/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "continuous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/title",
          "value": "NSSegmentedControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentedControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentedControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1SwitchTracking~1momentary/title",
          "value": "NSSegmentSwitchTrackingMomentary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1SwitchTracking~1momentary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentSwitchTrackingMomentary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1SwitchTracking~1momentaryAccelerator/title",
          "value": "NSSegmentSwitchTrackingMomentaryAccelerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1SwitchTracking~1momentaryAccelerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentSwitchTrackingMomentaryAccelerator"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nssegmentedcontrol/switchtracking/selectone"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nssegmentedcontrol/switchtracking/selectone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
