{
  "abstract": [
    {
      "text": "Constants that indicate the type of activity associated with location updates.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CLActivityType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CLActivityType"
      }
    ],
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLActivityType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CLActivityType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLActivityType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType": {
      "abstract": [
        {
          "text": "Constants that indicate the type of activity associated with location updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLActivityType"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLActivityType"
        }
      ],
      "role": "symbol",
      "title": "CLActivityType",
      "type": "topic",
      "url": "/documentation/corelocation/clactivitytype"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/airborne": {
      "abstract": [
        {
          "text": "The value that indicates activities in the air.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "airborne"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/airborne",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLActivityTypeAirborne"
        }
      ],
      "role": "symbol",
      "title": "CLActivityType.airborne",
      "type": "topic",
      "url": "/documentation/corelocation/clactivitytype/airborne"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/automotiveNavigation": {
      "abstract": [
        {
          "text": "The value that indicates positioning in an automobile following a road network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automotiveNavigation"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/automotiveNavigation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLActivityTypeAutomotiveNavigation"
        }
      ],
      "role": "symbol",
      "title": "CLActivityType.automotiveNavigation",
      "type": "topic",
      "url": "/documentation/corelocation/clactivitytype/automotivenavigation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/fitness": {
      "abstract": [
        {
          "text": "The value that indicates positioning during dedicated fitness sessions, such as walking workouts, running workouts, cycling workouts, and so on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fitness"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/fitness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLActivityTypeFitness"
        }
      ],
      "role": "symbol",
      "title": "CLActivityType.fitness",
      "type": "topic",
      "url": "/documentation/corelocation/clactivitytype/fitness"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/corelocation/clactivitytype/init(rawvalue:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/other": {
      "abstract": [
        {
          "text": "The value that indicates the app is using location manager for an unspecified activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLActivityTypeOther"
        }
      ],
      "role": "symbol",
      "title": "CLActivityType.other",
      "type": "topic",
      "url": "/documentation/corelocation/clactivitytype/other"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/otherNavigation": {
      "abstract": [
        {
          "text": "The value that indicates positioning for activities that don’t or may not adhere to roads such as cycling, scooters, trains, boats and off-road vehicles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "otherNavigation"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/otherNavigation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLActivityTypeOtherNavigation"
        }
      ],
      "role": "symbol",
      "title": "CLActivityType.otherNavigation",
      "type": "topic",
      "url": "/documentation/corelocation/clactivitytype/othernavigation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/activityType": {
      "abstract": [
        {
          "text": "The type of activity the app expects the user to typically perform while in the app’s location session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLActivityType",
          "text": "CLActivityType"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/activityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activityType"
        }
      ],
      "role": "symbol",
      "title": "activityType",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/activitytype"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/allowsBackgroundLocationUpdates": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app receives location updates when running in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsBackgroundLocationUpdates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/allowsBackgroundLocationUpdates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsBackgroundLocationUpdates"
        }
      ],
      "role": "symbol",
      "title": "allowsBackgroundLocationUpdates",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/allowsbackgroundlocationupdates"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/pausesLocationUpdatesAutomatically": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the location-manager object may pause location updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pausesLocationUpdatesAutomatically"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/pausesLocationUpdatesAutomatically",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pausesLocationUpdatesAutomatically"
        }
      ],
      "role": "symbol",
      "title": "pausesLocationUpdatesAutomatically",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/pauseslocationupdatesautomatically"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/requestLocation()": {
      "abstract": [
        {
          "text": "Requests the one-time delivery of the user’s current location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestLocation"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/requestLocation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestLocation"
        }
      ],
      "role": "symbol",
      "title": "requestLocation()",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/requestlocation()"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/showsBackgroundLocationIndicator": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the status bar changes its appearance when an app uses location services in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsBackgroundLocationIndicator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/showsBackgroundLocationIndicator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showsBackgroundLocationIndicator"
        }
      ],
      "role": "symbol",
      "title": "showsBackgroundLocationIndicator",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/showsbackgroundlocationindicator"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startUpdatingLocation()": {
      "abstract": [
        {
          "text": "Starts the generation of updates that report the user’s current location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startUpdatingLocation"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startUpdatingLocation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startUpdatingLocation"
        }
      ],
      "role": "symbol",
      "title": "startUpdatingLocation()",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/startupdatinglocation()"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/stopUpdatingLocation()": {
      "abstract": [
        {
          "text": "Stops the generation of location updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopUpdatingLocation"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/stopUpdatingLocation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopUpdatingLocation"
        }
      ],
      "role": "symbol",
      "title": "stopUpdatingLocation()",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/stopupdatinglocation()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Running-the-standard-location-service",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startUpdatingLocation()",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/stopUpdatingLocation()",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/requestLocation()",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/pausesLocationUpdatesAutomatically",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/allowsBackgroundLocationUpdates",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/showsBackgroundLocationIndicator",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/activityType"
      ],
      "title": "Running the standard location service"
    }
  ],
  "topicSections": [
    {
      "anchor": "Activity-types",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/other",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/automotiveNavigation",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/fitness",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/otherNavigation",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/airborne"
      ],
      "title": "Activity types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLActivityType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corelocation/documentation/CoreLocation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Activity-types",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/other",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/automotiveNavigation",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/fitness",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/otherNavigation",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/airborne"
              ],
              "title": "Activity types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Running-the-standard-location-service",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startUpdatingLocation()",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/stopUpdatingLocation()",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/requestLocation()",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/pausesLocationUpdatesAutomatically",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/allowsBackgroundLocationUpdates",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/showsBackgroundLocationIndicator",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/activityType"
              ],
              "title": "Running the standard location service"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLActivityType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1allowsBackgroundLocationUpdates/title",
          "value": "allowsBackgroundLocationUpdates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1allowsBackgroundLocationUpdates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsBackgroundLocationUpdates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1startUpdatingLocation()/title",
          "value": "startUpdatingLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1startUpdatingLocation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startUpdatingLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1otherNavigation/title",
          "value": "CLActivityTypeOtherNavigation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1otherNavigation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLActivityTypeOtherNavigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1automotiveNavigation/title",
          "value": "CLActivityTypeAutomotiveNavigation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1automotiveNavigation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLActivityTypeAutomotiveNavigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1requestLocation()/title",
          "value": "requestLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1requestLocation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1showsBackgroundLocationIndicator/title",
          "value": "showsBackgroundLocationIndicator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1showsBackgroundLocationIndicator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showsBackgroundLocationIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1pausesLocationUpdatesAutomatically/title",
          "value": "pausesLocationUpdatesAutomatically"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1pausesLocationUpdatesAutomatically/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pausesLocationUpdatesAutomatically"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType/title",
          "value": "CLActivityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLActivityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1activityType/title",
          "value": "activityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1activityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1fitness/title",
          "value": "CLActivityTypeFitness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1fitness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLActivityTypeFitness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1airborne/title",
          "value": "CLActivityTypeAirborne"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1airborne/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLActivityTypeAirborne"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1other/title",
          "value": "CLActivityTypeOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLActivityTypeOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1stopUpdatingLocation()/title",
          "value": "stopUpdatingLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1stopUpdatingLocation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopUpdatingLocation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/clactivitytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corelocation/clactivitytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
