{
  "abstract": [
    {
      "text": "A circular geographic condition that a center point and radius define.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/CLCircularGeographicCondition"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CLCircularGeographicCondition",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CLCircularGeographicCondition"
      }
    ],
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLCircularGeographicCondition"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CLCircularGeographicCondition"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLCircularGeographicCondition"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLCondition-c.class",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CLCondition",
              "text": "CLCondition"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.corelocation/documentation/CoreLocation/monitoring-the-user-s-proximity-to-geographic-regions"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "code": "CLCircularGeographicCondition",
              "type": "codeVoice"
            },
            {
              "text": " to monitor events that occur in a circular geographic condition that you describe.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLBeacon": {
      "abstract": [
        {
          "text": "Information about an observed iBeacon device and its relative distance to a person’s device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLBeacon"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeacon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLBeacon"
        }
      ],
      "role": "symbol",
      "title": "CLBeacon",
      "type": "topic",
      "url": "/documentation/corelocation/clbeacon"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityCondition": {
      "abstract": [
        {
          "text": "A condition that describes the identity characteristics of a beacon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CLBeaconIdentityCondition"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityCondition",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLBeaconIdentityCondition",
      "type": "topic",
      "url": "/documentation/corelocation/clbeaconidentitycondition"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLCircularGeographicCondition": {
      "abstract": [
        {
          "text": "A circular geographic condition that a center point and radius define.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CLCircularGeographicCondition"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLCircularGeographicCondition",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLCircularGeographicCondition",
      "type": "topic",
      "url": "/documentation/corelocation/clcirculargeographiccondition"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLCircularGeographicCondition/center": {
      "abstract": [
        {
          "text": "The center of the circular geographic condition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "center"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLCircularGeographicCondition/center",
      "kind": "symbol",
      "role": "symbol",
      "title": "center",
      "type": "topic",
      "url": "/documentation/corelocation/clcirculargeographiccondition/center"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLCircularGeographicCondition/initWithCenter:radius:": {
      "abstract": [
        {
          "text": "Creates a new circular geographic condition with the center point and radius you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithCenter:radius:"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLCircularGeographicCondition/initWithCenter:radius:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCenter:radius:"
        }
      ],
      "role": "symbol",
      "title": "initWithCenter:radius:",
      "type": "topic",
      "url": "/documentation/corelocation/clcirculargeographiccondition/initwithcenter:radius:"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLCircularGeographicCondition/radius": {
      "abstract": [
        {
          "text": "The radius of the circular geographic condition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "radius"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLCircularGeographicCondition/radius",
      "kind": "symbol",
      "role": "symbol",
      "title": "radius",
      "type": "topic",
      "url": "/documentation/corelocation/clcirculargeographiccondition/radius"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLCondition-c.class": {
      "abstract": [
        {
          "text": "The abstract base class that all other conditions derive from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CLCondition"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLCondition-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLCondition",
      "type": "topic",
      "url": "/documentation/corelocation/clcondition-c.class"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/determining-the-proximity-to-an-ibeacon-device": {
      "abstract": [
        {
          "text": "Detect beacons and determine the relative distance to them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/determining-the-proximity-to-an-ibeacon-device",
      "kind": "article",
      "role": "article",
      "title": "Determining the proximity to an iBeacon device",
      "type": "topic",
      "url": "/documentation/corelocation/determining-the-proximity-to-an-ibeacon-device"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/monitoring-the-user-s-proximity-to-geographic-regions": {
      "abstract": [
        {
          "text": "Use condition monitoring to determine when the user enters or leaves a geographic region.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/monitoring-the-user-s-proximity-to-geographic-regions",
      "kind": "article",
      "role": "article",
      "title": "Monitoring the user’s proximity to geographic regions",
      "type": "topic",
      "url": "/documentation/corelocation/monitoring-the-user-s-proximity-to-geographic-regions"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/ranging-for-beacons": {
      "abstract": [
        {
          "text": "Configure a device to act as a beacon and to detect surrounding beacons.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/ranging-for-beacons",
      "kind": "article",
      "role": "sampleCode",
      "title": "Ranging for Beacons",
      "type": "topic",
      "url": "/documentation/corelocation/ranging-for-beacons"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/turning-an-ios-device-into-an-ibeacon-device": {
      "abstract": [
        {
          "text": "Broadcast iBeacon signals from an iOS device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/turning-an-ios-device-into-an-ibeacon-device",
      "kind": "article",
      "role": "article",
      "title": "Turning an iOS device into an iBeacon device",
      "type": "topic",
      "url": "/documentation/corelocation/turning-an-ios-device-into-an-ibeacon-device"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLCondition-c.class"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "iBeacon",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/ranging-for-beacons",
        "doc://com.apple.corelocation/documentation/CoreLocation/determining-the-proximity-to-an-ibeacon-device",
        "doc://com.apple.corelocation/documentation/CoreLocation/turning-an-ios-device-into-an-ibeacon-device",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLBeacon",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLCondition-c.class",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityCondition"
      ],
      "title": "iBeacon"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-circular-geographic-condition",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLCircularGeographicCondition/initWithCenter:radius:"
      ],
      "title": "Creating a circular geographic condition"
    },
    {
      "anchor": "Instance-properties",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLCircularGeographicCondition/center",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLCircularGeographicCondition/radius"
      ],
      "title": "Instance properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLBeacon/title",
          "value": "CLBeacon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLBeacon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLBeacon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLBeacon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLBeacon"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/clcirculargeographiccondition"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
