{
  "abstract": [
    {
      "text": "Constants indicating the physical orientation of the device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CLDeviceOrientation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CLDeviceOrientation"
      }
    ],
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLDeviceOrientation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CLDeviceOrientation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLDeviceOrientation"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation": {
      "abstract": [
        {
          "text": "Constants indicating the physical orientation of the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLDeviceOrientation"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLDeviceOrientation"
        }
      ],
      "role": "symbol",
      "title": "CLDeviceOrientation",
      "type": "topic",
      "url": "/documentation/corelocation/cldeviceorientation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/faceDown": {
      "abstract": [
        {
          "text": "The device is held parallel to the ground with the screen facing downwards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faceDown"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/faceDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLDeviceOrientationFaceDown"
        }
      ],
      "role": "symbol",
      "title": "CLDeviceOrientation.faceDown",
      "type": "topic",
      "url": "/documentation/corelocation/cldeviceorientation/facedown"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/faceUp": {
      "abstract": [
        {
          "text": "The device is held parallel to the ground with the screen facing upwards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faceUp"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/faceUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLDeviceOrientationFaceUp"
        }
      ],
      "role": "symbol",
      "title": "CLDeviceOrientation.faceUp",
      "type": "topic",
      "url": "/documentation/corelocation/cldeviceorientation/faceup"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/corelocation/cldeviceorientation/init(rawvalue:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/landscapeLeft": {
      "abstract": [
        {
          "text": "The device is in landscape mode, with the device held upright and the home button on the right side.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "landscapeLeft"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/landscapeLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLDeviceOrientationLandscapeLeft"
        }
      ],
      "role": "symbol",
      "title": "CLDeviceOrientation.landscapeLeft",
      "type": "topic",
      "url": "/documentation/corelocation/cldeviceorientation/landscapeleft"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/landscapeRight": {
      "abstract": [
        {
          "text": "The device is in landscape mode, with the device held upright and the home button on the left side.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "landscapeRight"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/landscapeRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLDeviceOrientationLandscapeRight"
        }
      ],
      "role": "symbol",
      "title": "CLDeviceOrientation.landscapeRight",
      "type": "topic",
      "url": "/documentation/corelocation/cldeviceorientation/landscaperight"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/portrait": {
      "abstract": [
        {
          "text": "The device is in portrait mode, with the device held upright and the home button at the bottom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portrait"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/portrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLDeviceOrientationPortrait"
        }
      ],
      "role": "symbol",
      "title": "CLDeviceOrientation.portrait",
      "type": "topic",
      "url": "/documentation/corelocation/cldeviceorientation/portrait"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/portraitUpsideDown": {
      "abstract": [
        {
          "text": "The device is in portrait mode but upside down, with the device held upright and the home button at the top.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portraitUpsideDown"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/portraitUpsideDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLDeviceOrientationPortraitUpsideDown"
        }
      ],
      "role": "symbol",
      "title": "CLDeviceOrientation.portraitUpsideDown",
      "type": "topic",
      "url": "/documentation/corelocation/cldeviceorientation/portraitupsidedown"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/unknown": {
      "abstract": [
        {
          "text": "The orientation is currently not known.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLDeviceOrientationUnknown"
        }
      ],
      "role": "symbol",
      "title": "CLDeviceOrientation.unknown",
      "type": "topic",
      "url": "/documentation/corelocation/cldeviceorientation/unknown"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationDegrees": {
      "abstract": [
        {
          "text": "A latitude or longitude value specified in degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationDegrees"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationDegrees",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationDegrees"
        }
      ],
      "role": "symbol",
      "title": "CLLocationDegrees",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationdegrees"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/dismissHeadingCalibrationDisplay()": {
      "abstract": [
        {
          "text": "Dismisses the heading calibration view from the screen immediately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dismissHeadingCalibrationDisplay"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/dismissHeadingCalibrationDisplay()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dismissHeadingCalibrationDisplay"
        }
      ],
      "role": "symbol",
      "title": "dismissHeadingCalibrationDisplay()",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/dismissheadingcalibrationdisplay()"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/headingFilter": {
      "abstract": [
        {
          "text": "The minimum angular change in degrees required to generate new heading events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headingFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDegrees",
          "text": "CLLocationDegrees"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/headingFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "headingFilter"
        }
      ],
      "role": "symbol",
      "title": "headingFilter",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/headingfilter"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/headingOrientation": {
      "abstract": [
        {
          "text": "The device orientation to use when computing heading values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headingOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLDeviceOrientation",
          "text": "CLDeviceOrientation"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/headingOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "headingOrientation"
        }
      ],
      "role": "symbol",
      "title": "headingOrientation",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/headingorientation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startUpdatingHeading()": {
      "abstract": [
        {
          "text": "Starts the generation of updates that report the user’s current heading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startUpdatingHeading"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startUpdatingHeading()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startUpdatingHeading"
        }
      ],
      "role": "symbol",
      "title": "startUpdatingHeading()",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/startupdatingheading()"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/stopUpdatingHeading()": {
      "abstract": [
        {
          "text": "Stops the generation of heading updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopUpdatingHeading"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/stopUpdatingHeading()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopUpdatingHeading"
        }
      ],
      "role": "symbol",
      "title": "stopUpdatingHeading()",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/stopupdatingheading()"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/kCLHeadingFilterNone": {
      "abstract": [
        {
          "text": "A constant indicating that all header values should be reported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCLHeadingFilterNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDegrees",
          "text": "CLLocationDegrees"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/kCLHeadingFilterNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLHeadingFilterNone"
        }
      ],
      "role": "symbol",
      "title": "kCLHeadingFilterNone",
      "type": "topic",
      "url": "/documentation/corelocation/kclheadingfilternone"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Running-the-heading-service",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startUpdatingHeading()",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/stopUpdatingHeading()",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/dismissHeadingCalibrationDisplay()",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/headingFilter",
        "doc://com.apple.corelocation/documentation/CoreLocation/kCLHeadingFilterNone",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationDegrees",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/headingOrientation"
      ],
      "title": "Running the heading service"
    }
  ],
  "topicSections": [
    {
      "anchor": "Device-Orientations",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/unknown",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/portrait",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/portraitUpsideDown",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/landscapeLeft",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/landscapeRight",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/faceUp",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/faceDown"
      ],
      "title": "Device Orientations"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLDeviceOrientation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corelocation/documentation/CoreLocation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Device-Orientations",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/unknown",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/portrait",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/portraitUpsideDown",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/landscapeLeft",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/landscapeRight",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/faceUp",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/faceDown"
              ],
              "title": "Device Orientations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Running-the-heading-service",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startUpdatingHeading()",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/stopUpdatingHeading()",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/dismissHeadingCalibrationDisplay()",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/headingFilter",
                "doc://com.apple.corelocation/documentation/CoreLocation/kCLHeadingFilterNone",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationDegrees",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/headingOrientation"
              ],
              "title": "Running the heading service"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLDeviceOrientation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:I",
                    "text": "int"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation/title",
          "value": "CLDeviceOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1faceDown/title",
          "value": "CLDeviceOrientationFaceDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1faceDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientationFaceDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1headingOrientation/title",
          "value": "headingOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1headingOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "headingOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationDegrees/title",
          "value": "CLLocationDegrees"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationDegrees/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationDegrees"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationDegrees/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationDegrees"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1unknown/title",
          "value": "CLDeviceOrientationUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientationUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1landscapeLeft/title",
          "value": "CLDeviceOrientationLandscapeLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1landscapeLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientationLandscapeLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLHeadingFilterNone/title",
          "value": "kCLHeadingFilterNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLHeadingFilterNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLHeadingFilterNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1stopUpdatingHeading()/title",
          "value": "stopUpdatingHeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1stopUpdatingHeading()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopUpdatingHeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1dismissHeadingCalibrationDisplay()/title",
          "value": "dismissHeadingCalibrationDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1dismissHeadingCalibrationDisplay()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dismissHeadingCalibrationDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1portrait/title",
          "value": "CLDeviceOrientationPortrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1portrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientationPortrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1landscapeRight/title",
          "value": "CLDeviceOrientationLandscapeRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1landscapeRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientationLandscapeRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1headingFilter/title",
          "value": "headingFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1headingFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "headingFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1startUpdatingHeading()/title",
          "value": "startUpdatingHeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1startUpdatingHeading()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startUpdatingHeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1portraitUpsideDown/title",
          "value": "CLDeviceOrientationPortraitUpsideDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1portraitUpsideDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientationPortraitUpsideDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1faceUp/title",
          "value": "CLDeviceOrientationFaceUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1faceUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientationFaceUp"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/cldeviceorientation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corelocation/cldeviceorientation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
