{
  "abstract": [
    {
      "text": "A Core Location error.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC7CLErrorLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CLError"
      }
    ],
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CLError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLError"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Instances of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object delivered to the delegate use these error codes for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nserror/1409165-code",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of the error object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct": {
      "abstract": [
        {
          "text": "A Core Location error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLError"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLError"
        }
      ],
      "role": "symbol",
      "title": "CLError",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes returned by the location manager object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CLError.Code",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/code"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/alternateRegion": {
      "abstract": [
        {
          "text": "A region that location services can monitor more effectively.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alternateRegion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLRegion",
          "text": "CLRegion"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/alternateRegion",
      "kind": "symbol",
      "role": "symbol",
      "title": "alternateRegion",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/alternateregion"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/deferredAccuracyTooLow": {
      "abstract": [
        {
          "text": "A constant that indicates deferred mode isn’t supported for the requested accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deferredAccuracyTooLow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/deferredAccuracyTooLow",
      "kind": "symbol",
      "role": "symbol",
      "title": "deferredAccuracyTooLow",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/deferredaccuracytoolow"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/deferredCanceled": {
      "abstract": [
        {
          "text": "A constant that indicates your app or the location manager canceled the request for deferred updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deferredCanceled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/deferredCanceled",
      "kind": "symbol",
      "role": "symbol",
      "title": "deferredCanceled",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/deferredcanceled"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/deferredDistanceFiltered": {
      "abstract": [
        {
          "text": "A constant that indicates deferred mode doesn’t support distance filters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deferredDistanceFiltered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/deferredDistanceFiltered",
      "kind": "symbol",
      "role": "symbol",
      "title": "deferredDistanceFiltered",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/deferreddistancefiltered"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/deferredFailed": {
      "abstract": [
        {
          "text": "A constant that indicates the location manager didn’t enter deferred mode for an unknown reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deferredFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/deferredFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "deferredFailed",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/deferredfailed"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/deferredNotUpdatingLocation": {
      "abstract": [
        {
          "text": "A constant that indicates the location manager didn’t enter deferred mode because location updates were already disabled or paused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deferredNotUpdatingLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/deferredNotUpdatingLocation",
      "kind": "symbol",
      "role": "symbol",
      "title": "deferredNotUpdatingLocation",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/deferrednotupdatinglocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/denied": {
      "abstract": [
        {
          "text": "A constant that indicates the user denied access to the location service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "denied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/denied",
      "kind": "symbol",
      "role": "symbol",
      "title": "denied",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/denied"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/errordomain"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/geocodeCanceled": {
      "abstract": [
        {
          "text": "A constant that indicates the geocode request was canceled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "geocodeCanceled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/geocodeCanceled",
      "kind": "symbol",
      "role": "symbol",
      "title": "geocodeCanceled",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/geocodecanceled"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/geocodeFoundNoResult": {
      "abstract": [
        {
          "text": "A constant that indicates the geocode request yielded no result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "geocodeFoundNoResult"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/geocodeFoundNoResult",
      "kind": "symbol",
      "role": "symbol",
      "title": "geocodeFoundNoResult",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/geocodefoundnoresult"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/geocodeFoundPartialResult": {
      "abstract": [
        {
          "text": "A constant that indicates the geocode request yielded a partial result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "geocodeFoundPartialResult"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/geocodeFoundPartialResult",
      "kind": "symbol",
      "role": "symbol",
      "title": "geocodeFoundPartialResult",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/geocodefoundpartialresult"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/headingFailure": {
      "abstract": [
        {
          "text": "A constant that indicates the location manager can’t determine the heading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headingFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/headingFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "headingFailure",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/headingfailure"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/historicalLocationError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "historicalLocationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/historicalLocationError",
      "kind": "symbol",
      "role": "symbol",
      "title": "historicalLocationError",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/historicallocationerror"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/locationUnknown": {
      "abstract": [
        {
          "text": "A constant that indicates the location manager was unable to obtain a location value right now.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/locationUnknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "locationUnknown",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/locationunknown"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/network": {
      "abstract": [
        {
          "text": "A constant that indicates the network was unavailable or a network error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "network"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/network",
      "kind": "symbol",
      "role": "symbol",
      "title": "network",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/network"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/promptDeclined": {
      "abstract": [
        {
          "text": "A constant that indicates the user didn’t grant the requested temporary authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "promptDeclined"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/promptDeclined",
      "kind": "symbol",
      "role": "symbol",
      "title": "promptDeclined",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/promptdeclined"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/rangingFailure": {
      "abstract": [
        {
          "text": "A constant that indicates a general ranging error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rangingFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/rangingFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "rangingFailure",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/rangingfailure"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/rangingUnavailable": {
      "abstract": [
        {
          "text": "A constant that indicates ranging is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rangingUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/rangingUnavailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "rangingUnavailable",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/rangingunavailable"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/regionMonitoringDenied": {
      "abstract": [
        {
          "text": "A constant that indicates the user denied access to the region monitoring service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionMonitoringDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/regionMonitoringDenied",
      "kind": "symbol",
      "role": "symbol",
      "title": "regionMonitoringDenied",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/regionmonitoringdenied"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/regionMonitoringFailure": {
      "abstract": [
        {
          "text": "A constant that indicates the location manager failed to monitor a registered region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionMonitoringFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/regionMonitoringFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "regionMonitoringFailure",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/regionmonitoringfailure"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/regionMonitoringResponseDelayed": {
      "abstract": [
        {
          "text": "A constant that indicates Core Location will deliver events but they may be delayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionMonitoringResponseDelayed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/regionMonitoringResponseDelayed",
      "kind": "symbol",
      "role": "symbol",
      "title": "regionMonitoringResponseDelayed",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/regionmonitoringresponsedelayed"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/regionMonitoringSetupDelayed": {
      "abstract": [
        {
          "text": "A constant that indicates Core Location couldn’t initialize the region monitoring feature immediately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionMonitoringSetupDelayed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CLErrorLeV",
          "text": "CLError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/regionMonitoringSetupDelayed",
      "kind": "symbol",
      "role": "symbol",
      "title": "regionMonitoringSetupDelayed",
      "type": "topic",
      "url": "/documentation/corelocation/clerror-swift.struct/regionmonitoringsetupdelayed"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/kCLErrorDomain": {
      "abstract": [
        {
          "text": "The domain for Core Location errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCLErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/kCLErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "kCLErrorDomain",
      "type": "topic",
      "url": "/documentation/corelocation/kclerrordomain"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/kCLErrorUserInfoAlternateRegionKey": {
      "abstract": [
        {
          "text": "A key in the user information dictionary of an error relating to a delayed region-monitoring response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCLErrorUserInfoAlternateRegionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/kCLErrorUserInfoAlternateRegionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLErrorUserInfoAlternateRegionKey"
        }
      ],
      "role": "symbol",
      "title": "kCLErrorUserInfoAlternateRegionKey",
      "type": "topic",
      "url": "/documentation/corelocation/kclerroruserinfoalternateregionkey"
    },
    "doc://com.apple.documentation/documentation/foundation/nserror": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.apple.documentation/documentation/foundation/nserror/1409165-code": {
      "abstract": [
        {
          "text": "The error code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": Int"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror/1409165-code",
      "kind": "symbol",
      "role": "symbol",
      "title": "code",
      "type": "topic",
      "url": "/documentation/foundation/nserror/1409165-code"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/kCLErrorDomain",
        "doc://com.apple.corelocation/documentation/CoreLocation/kCLErrorUserInfoAlternateRegionKey"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-general-errors",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/locationUnknown",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/denied",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/promptDeclined",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/network",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/headingFailure",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/rangingUnavailable",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/rangingFailure",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/Code"
      ],
      "title": "Getting general errors"
    },
    {
      "anchor": "Getting-region-monitoring-errors",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/regionMonitoringDenied",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/regionMonitoringFailure",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/regionMonitoringSetupDelayed",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/regionMonitoringResponseDelayed"
      ],
      "title": "Getting region monitoring errors"
    },
    {
      "anchor": "Getting-geocoding-errors",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/geocodeCanceled",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/geocodeFoundNoResult",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/geocodeFoundPartialResult"
      ],
      "title": "Getting geocoding errors"
    },
    {
      "anchor": "Getting-deferred-location-update-errors",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/deferredFailed",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/deferredCanceled",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/deferredAccuracyTooLow",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/deferredDistanceFiltered",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/deferredNotUpdatingLocation"
      ],
      "title": "Getting deferred location update errors"
    },
    {
      "anchor": "Getting-the-error-details",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/alternateRegion"
      ],
      "title": "Getting the error details"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/historicalLocationError",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLError-swift.struct/errorDomain"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLErrorDomain/title",
          "value": "kCLErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code/title",
          "value": "CLError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLErrorUserInfoAlternateRegionKey/title",
          "value": "kCLErrorUserInfoAlternateRegionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLErrorUserInfoAlternateRegionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLErrorUserInfoAlternateRegionKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/clerror-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
