{
  "abstract": [
    {
      "text": "An object that provides device location updates.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CLLocationUpdater",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CLLocationUpdater"
      }
    ],
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLLocationUpdater"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CLLocationUpdater"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLLocationUpdater"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLBackgroundActivitySessionDiagnostic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CLBackgroundActivitySessionDiagnostic"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBackgroundActivitySessionDiagnostic",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLBackgroundActivitySessionDiagnostic",
      "type": "topic",
      "url": "/documentation/corelocation/clbackgroundactivitysessiondiagnostic"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLFloor": {
      "abstract": [
        {
          "text": "The floor of a building on which the user’s device is located.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLFloor"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLFloor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLFloor"
        }
      ],
      "role": "symbol",
      "title": "CLFloor",
      "type": "topic",
      "url": "/documentation/corelocation/clfloor"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLiveUpdateConfiguration": {
      "abstract": [
        {
          "text": "Specifies the types of locations that a location updater generates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CLLiveUpdateConfiguration"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLiveUpdateConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLLiveUpdateConfiguration",
      "type": "topic",
      "url": "/documentation/corelocation/clliveupdateconfiguration"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation": {
      "abstract": [
        {
          "text": "The latitude, longitude, and course information reported by the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocation"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocation"
        }
      ],
      "role": "symbol",
      "title": "CLLocation",
      "type": "topic",
      "url": "/documentation/corelocation/cllocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D": {
      "abstract": [
        {
          "text": "The latitude and longitude associated with a location, specified using the WGS 84 reference frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationCoordinate2D"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationCoordinate2D"
        }
      ],
      "role": "symbol",
      "title": "CLLocationCoordinate2D",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationcoordinate2d"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationSourceInformation": {
      "abstract": [
        {
          "text": "Information about the source that provides a location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationSourceInformation"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationSourceInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationSourceInformation"
        }
      ],
      "role": "symbol",
      "title": "CLLocationSourceInformation",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationsourceinformation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater": {
      "abstract": [
        {
          "text": "An object that provides device location updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CLLocationUpdater"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLLocationUpdater",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationupdater"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater/invalidate": {
      "abstract": [
        {
          "text": "Invalidates the updater.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "invalidate"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater/invalidate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidate"
        }
      ],
      "role": "symbol",
      "title": "invalidate",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationupdater/invalidate"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater/liveUpdaterWithConfiguration:queue:handler:": {
      "abstract": [
        {
          "text": "Creates a location updater with the configuration and queue that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "liveUpdaterWithConfiguration:queue:handler:"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater/liveUpdaterWithConfiguration:queue:handler:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "liveUpdaterWithConfiguration:queue:handler:"
        }
      ],
      "role": "symbol",
      "title": "liveUpdaterWithConfiguration:queue:handler:",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationupdater/liveupdaterwithconfiguration:queue:handler:"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater/liveUpdaterWithQueue:handler:": {
      "abstract": [
        {
          "text": "Creates a location updater on the queue you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "liveUpdaterWithQueue:handler:"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater/liveUpdaterWithQueue:handler:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "liveUpdaterWithQueue:handler:"
        }
      ],
      "role": "symbol",
      "title": "liveUpdaterWithQueue:handler:",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationupdater/liveupdaterwithqueue:handler:"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater/pause": {
      "abstract": [
        {
          "text": "Pauses the updater.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "pause"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater/pause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pause"
        }
      ],
      "role": "symbol",
      "title": "pause",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationupdater/pause"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater/resume": {
      "abstract": [
        {
          "text": "Resumes the updater.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "resume"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater/resume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resume"
        }
      ],
      "role": "symbol",
      "title": "resume",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationupdater/resume"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSession-2ddhd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CLServiceSession"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSession-2ddhd",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLServiceSession",
      "type": "topic",
      "url": "/documentation/corelocation/clservicesession-2ddhd"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSessionDiagnostic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CLServiceSessionDiagnostic"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSessionDiagnostic",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLServiceSessionDiagnostic",
      "type": "topic",
      "url": "/documentation/corelocation/clservicesessiondiagnostic"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLVisit": {
      "abstract": [
        {
          "text": "Information about the user’s location during a specific period of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLVisit"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLVisit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLVisit"
        }
      ],
      "role": "symbol",
      "title": "CLVisit",
      "type": "topic",
      "url": "/documentation/corelocation/clvisit"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/creating-a-location-push-service-extension": {
      "abstract": [
        {
          "text": "Add and configure an extension to enable your location-sharing app to access a user’s location in response to a request from another user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/creating-a-location-push-service-extension",
      "kind": "article",
      "role": "article",
      "title": "Creating a location push service extension",
      "type": "topic",
      "url": "/documentation/corelocation/creating-a-location-push-service-extension"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/getting-the-current-location-of-a-device": {
      "abstract": [
        {
          "text": "Start location services and provide information the system needs to optimize power usage for those services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/getting-the-current-location-of-a-device",
      "kind": "article",
      "role": "article",
      "title": "Getting the current location of a device",
      "type": "topic",
      "url": "/documentation/corelocation/getting-the-current-location-of-a-device"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/handling-location-updates-in-the-background": {
      "abstract": [
        {
          "text": "Configure your app to receive location updates when it isn’t running in the foreground.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/handling-location-updates-in-the-background",
      "kind": "article",
      "role": "article",
      "title": "Handling location updates in the background",
      "type": "topic",
      "url": "/documentation/corelocation/handling-location-updates-in-the-background"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Location-updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/getting-the-current-location-of-a-device",
        "doc://com.apple.corelocation/documentation/CoreLocation/handling-location-updates-in-the-background",
        "doc://com.apple.corelocation/documentation/CoreLocation/creating-a-location-push-service-extension",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLFloor",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLVisit",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationSourceInformation",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSession-2ddhd",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSessionDiagnostic",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLBackgroundActivitySessionDiagnostic"
      ],
      "title": "Location updates"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-location-updater",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater/liveUpdaterWithConfiguration:queue:handler:",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater/liveUpdaterWithQueue:handler:",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLiveUpdateConfiguration"
      ],
      "title": "Creating a location updater"
    },
    {
      "anchor": "Controlling-the-updater",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater/invalidate",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater/pause",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater/resume"
      ],
      "title": "Controlling the updater"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2D/title",
          "value": "CLLocationCoordinate2D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationCoordinate2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationCoordinate2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLVisit/title",
          "value": "CLVisit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLVisit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLVisit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLVisit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLVisit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLFloor/title",
          "value": "CLFloor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLFloor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLFloor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLFloor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLFloor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocation/title",
          "value": "CLLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationSourceInformation/title",
          "value": "CLLocationSourceInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationSourceInformation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationSourceInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationSourceInformation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationSourceInformation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/cllocationupdater"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
