{
  "abstract": [
    {
      "text": "The accuracy of a geographical coordinate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationAccuracy"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CLLocationAccuracy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CLLocationAccuracy"
      }
    ],
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLLocationAccuracy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "CLLocationAccuracy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLLocationAccuracy"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sd",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sd",
              "text": "Double"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When reported in a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, accuracy values are the number of meters from the original geographic coordinate that could yield the user’s actual location. When specifying values for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/desiredAccuracy",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, use one of the appropriate constants.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation": {
      "abstract": [
        {
          "text": "The latitude, longitude, and course information reported by the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocation"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocation"
        }
      ],
      "role": "symbol",
      "title": "CLLocation",
      "type": "topic",
      "url": "/documentation/corelocation/cllocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation/horizontalAccuracy": {
      "abstract": [
        {
          "text": "The radius of uncertainty for the location, measured in meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontalAccuracy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationAccuracy",
          "text": "CLLocationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation/horizontalAccuracy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "horizontalAccuracy"
        }
      ],
      "role": "symbol",
      "title": "horizontalAccuracy",
      "type": "topic",
      "url": "/documentation/corelocation/cllocation/horizontalaccuracy"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation/verticalAccuracy": {
      "abstract": [
        {
          "text": "The validity of the altitude values, and their estimated uncertainty, measured in meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verticalAccuracy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationAccuracy",
          "text": "CLLocationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation/verticalAccuracy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "verticalAccuracy"
        }
      ],
      "role": "symbol",
      "title": "verticalAccuracy",
      "type": "topic",
      "url": "/documentation/corelocation/cllocation/verticalaccuracy"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationAccuracy": {
      "abstract": [
        {
          "text": "The accuracy of a geographical coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationAccuracy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationAccuracy"
        }
      ],
      "role": "symbol",
      "title": "CLLocationAccuracy",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationaccuracy"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager": {
      "abstract": [
        {
          "text": "The object you use to start and stop the delivery of location-related events to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationManager"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationManager"
        }
      ],
      "role": "symbol",
      "title": "CLLocationManager",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/desiredAccuracy": {
      "abstract": [
        {
          "text": "The accuracy of the location data that your app wants to receive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "desiredAccuracy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationAccuracy",
          "text": "CLLocationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/desiredAccuracy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "desiredAccuracy"
        }
      ],
      "role": "symbol",
      "title": "desiredAccuracy",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/desiredaccuracy"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyBest": {
      "abstract": [
        {
          "text": "The best level of accuracy available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCLLocationAccuracyBest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationAccuracy",
          "text": "CLLocationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyBest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLLocationAccuracyBest"
        }
      ],
      "role": "symbol",
      "title": "kCLLocationAccuracyBest",
      "type": "topic",
      "url": "/documentation/corelocation/kcllocationaccuracybest"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyBestForNavigation": {
      "abstract": [
        {
          "text": "The highest possible accuracy that uses additional sensor data to facilitate navigation apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCLLocationAccuracyBestForNavigation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationAccuracy",
          "text": "CLLocationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyBestForNavigation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLLocationAccuracyBestForNavigation"
        }
      ],
      "role": "symbol",
      "title": "kCLLocationAccuracyBestForNavigation",
      "type": "topic",
      "url": "/documentation/corelocation/kcllocationaccuracybestfornavigation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyHundredMeters": {
      "abstract": [
        {
          "text": "Accurate to within one hundred meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCLLocationAccuracyHundredMeters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationAccuracy",
          "text": "CLLocationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyHundredMeters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLLocationAccuracyHundredMeters"
        }
      ],
      "role": "symbol",
      "title": "kCLLocationAccuracyHundredMeters",
      "type": "topic",
      "url": "/documentation/corelocation/kcllocationaccuracyhundredmeters"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyKilometer": {
      "abstract": [
        {
          "text": "Accurate to the nearest kilometer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCLLocationAccuracyKilometer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationAccuracy",
          "text": "CLLocationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyKilometer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLLocationAccuracyKilometer"
        }
      ],
      "role": "symbol",
      "title": "kCLLocationAccuracyKilometer",
      "type": "topic",
      "url": "/documentation/corelocation/kcllocationaccuracykilometer"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyNearestTenMeters": {
      "abstract": [
        {
          "text": "Accurate to within ten meters of the desired target.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCLLocationAccuracyNearestTenMeters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationAccuracy",
          "text": "CLLocationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyNearestTenMeters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLLocationAccuracyNearestTenMeters"
        }
      ],
      "role": "symbol",
      "title": "kCLLocationAccuracyNearestTenMeters",
      "type": "topic",
      "url": "/documentation/corelocation/kcllocationaccuracynearesttenmeters"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyReduced": {
      "abstract": [
        {
          "text": "The level of accuracy used when an app isn’t authorized for full accuracy location data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCLLocationAccuracyReduced"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationAccuracy",
          "text": "CLLocationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyReduced",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLLocationAccuracyReduced"
        }
      ],
      "role": "symbol",
      "title": "kCLLocationAccuracyReduced",
      "type": "topic",
      "url": "/documentation/corelocation/kcllocationaccuracyreduced"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyThreeKilometers": {
      "abstract": [
        {
          "text": "Accurate to the nearest three kilometers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCLLocationAccuracyThreeKilometers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationAccuracy",
          "text": "CLLocationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyThreeKilometers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLLocationAccuracyThreeKilometers"
        }
      ],
      "role": "symbol",
      "title": "kCLLocationAccuracyThreeKilometers",
      "type": "topic",
      "url": "/documentation/corelocation/kcllocationaccuracythreekilometers"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sd": {
      "abstract": [
        {
          "text": "A double-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sd",
      "kind": "symbol",
      "role": "symbol",
      "title": "Double",
      "type": "topic",
      "url": "/documentation/Swift/Double"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-location-accuracy",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation/horizontalAccuracy",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation/verticalAccuracy"
      ],
      "title": "Getting the location accuracy"
    }
  ],
  "topicSections": [
    {
      "anchor": "Desired-Accuracy-Constants",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyBestForNavigation",
        "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyBest",
        "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyNearestTenMeters",
        "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyHundredMeters",
        "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyKilometer",
        "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyThreeKilometers",
        "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyReduced"
      ],
      "title": "Desired Accuracy Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLLocationAccuracy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corelocation/documentation/CoreLocation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Desired-Accuracy-Constants",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyBestForNavigation",
                "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyBest",
                "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyNearestTenMeters",
                "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyHundredMeters",
                "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyKilometer",
                "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyThreeKilometers",
                "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationAccuracyReduced"
              ],
              "title": "Desired Accuracy Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-location-accuracy",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation/horizontalAccuracy",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation/verticalAccuracy"
              ],
              "title": "Getting the location accuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:d",
                    "text": "double"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLLocationAccuracy"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocation~1verticalAccuracy/title",
          "value": "verticalAccuracy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocation~1verticalAccuracy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "verticalAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLLocationAccuracyThreeKilometers/title",
          "value": "kCLLocationAccuracyThreeKilometers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLLocationAccuracyThreeKilometers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLLocationAccuracyThreeKilometers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLLocationAccuracyReduced/title",
          "value": "kCLLocationAccuracyReduced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLLocationAccuracyReduced/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLLocationAccuracyReduced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocation~1horizontalAccuracy/title",
          "value": "horizontalAccuracy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocation~1horizontalAccuracy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "horizontalAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocation/title",
          "value": "CLLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager/title",
          "value": "CLLocationManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationAccuracy/title",
          "value": "CLLocationAccuracy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationAccuracy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationAccuracy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLLocationAccuracyBest/title",
          "value": "kCLLocationAccuracyBest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLLocationAccuracyBest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLLocationAccuracyBest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1desiredAccuracy/title",
          "value": "desiredAccuracy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1desiredAccuracy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "desiredAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLLocationAccuracyHundredMeters/title",
          "value": "kCLLocationAccuracyHundredMeters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLLocationAccuracyHundredMeters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLLocationAccuracyHundredMeters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLLocationAccuracyNearestTenMeters/title",
          "value": "kCLLocationAccuracyNearestTenMeters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLLocationAccuracyNearestTenMeters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLLocationAccuracyNearestTenMeters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLLocationAccuracyKilometer/title",
          "value": "kCLLocationAccuracyKilometer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLLocationAccuracyKilometer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLLocationAccuracyKilometer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLLocationAccuracyBestForNavigation/title",
          "value": "kCLLocationAccuracyBestForNavigation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLLocationAccuracyBestForNavigation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLLocationAccuracyBestForNavigation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/cllocationaccuracy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corelocation/cllocationaccuracy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
