{
  "abstract": [
    {
      "text": "The latitude and longitude associated with a location, specified using the WGS 84 reference frame.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@CLLocationCoordinate2D",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CLLocationCoordinate2D"
      }
    ],
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLLocationCoordinate2D"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CLLocationCoordinate2D"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLLocationCoordinate2D"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLBackgroundActivitySessionDiagnostic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CLBackgroundActivitySessionDiagnostic"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBackgroundActivitySessionDiagnostic",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLBackgroundActivitySessionDiagnostic",
      "type": "topic",
      "url": "/documentation/corelocation/clbackgroundactivitysessiondiagnostic"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLFloor": {
      "abstract": [
        {
          "text": "The floor of a building on which the user’s device is located.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLFloor"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLFloor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLFloor"
        }
      ],
      "role": "symbol",
      "title": "CLFloor",
      "type": "topic",
      "url": "/documentation/corelocation/clfloor"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation": {
      "abstract": [
        {
          "text": "The latitude, longitude, and course information reported by the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocation"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocation"
        }
      ],
      "role": "symbol",
      "title": "CLLocation",
      "type": "topic",
      "url": "/documentation/corelocation/cllocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D": {
      "abstract": [
        {
          "text": "The latitude and longitude associated with a location, specified using the WGS 84 reference frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationCoordinate2D"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationCoordinate2D"
        }
      ],
      "role": "symbol",
      "title": "CLLocationCoordinate2D",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationcoordinate2d"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/init()": {
      "abstract": [
        {
          "text": "Creates a location coordinate object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationcoordinate2d/init()"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/init(latitude:longitude:)": {
      "abstract": [
        {
          "text": "Creates a location coordination object with the specified latitude and longitude values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "latitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDegrees",
          "text": "CLLocationDegrees"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "longitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDegrees",
          "text": "CLLocationDegrees"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/init(latitude:longitude:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(latitude:longitude:)",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationcoordinate2d/init(latitude:longitude:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/latitude": {
      "abstract": [
        {
          "text": "The latitude in degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "latitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDegrees",
          "text": "CLLocationDegrees"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/latitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "latitude"
        }
      ],
      "role": "symbol",
      "title": "latitude",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationcoordinate2d/latitude"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/longitude": {
      "abstract": [
        {
          "text": "The longitude in degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "longitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDegrees",
          "text": "CLLocationDegrees"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/longitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "longitude"
        }
      ],
      "role": "symbol",
      "title": "longitude",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationcoordinate2d/longitude"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2DIsValid(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the specified coordinate is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationCoordinate2DIsValid"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CLLocationCoordinate2D",
          "text": "CLLocationCoordinate2D"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2DIsValid(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationCoordinate2DIsValid"
        }
      ],
      "role": "symbol",
      "title": "CLLocationCoordinate2DIsValid(_:)",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationcoordinate2disvalid(_:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2DMake(_:_:)": {
      "abstract": [
        {
          "text": "Formats a latitude and longitude value into a coordinate data structure format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationCoordinate2DMake"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDegrees",
          "text": "CLLocationDegrees"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDegrees",
          "text": "CLLocationDegrees"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CLLocationCoordinate2D",
          "text": "CLLocationCoordinate2D"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2DMake(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationCoordinate2DMake"
        }
      ],
      "role": "symbol",
      "title": "CLLocationCoordinate2DMake(_:_:)",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationcoordinate2dmake(_:_:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationSourceInformation": {
      "abstract": [
        {
          "text": "Information about the source that provides a location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationSourceInformation"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationSourceInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationSourceInformation"
        }
      ],
      "role": "symbol",
      "title": "CLLocationSourceInformation",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationsourceinformation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater": {
      "abstract": [
        {
          "text": "An object that provides device location updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CLLocationUpdater"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLLocationUpdater",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationupdater"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSession-2ddhd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CLServiceSession"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSession-2ddhd",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLServiceSession",
      "type": "topic",
      "url": "/documentation/corelocation/clservicesession-2ddhd"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSession-pt7n": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLServiceSession"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSession-pt7n",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLServiceSession"
        }
      ],
      "role": "symbol",
      "title": "CLServiceSession",
      "type": "topic",
      "url": "/documentation/corelocation/clservicesession-pt7n"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSessionDiagnostic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CLServiceSessionDiagnostic"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSessionDiagnostic",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLServiceSessionDiagnostic",
      "type": "topic",
      "url": "/documentation/corelocation/clservicesessiondiagnostic"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLVisit": {
      "abstract": [
        {
          "text": "Information about the user’s location during a specific period of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLVisit"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLVisit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLVisit"
        }
      ],
      "role": "symbol",
      "title": "CLVisit",
      "type": "topic",
      "url": "/documentation/corelocation/clvisit"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/creating-a-location-push-service-extension": {
      "abstract": [
        {
          "text": "Add and configure an extension to enable your location-sharing app to access a user’s location in response to a request from another user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/creating-a-location-push-service-extension",
      "kind": "article",
      "role": "article",
      "title": "Creating a location push service extension",
      "type": "topic",
      "url": "/documentation/corelocation/creating-a-location-push-service-extension"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/getting-the-current-location-of-a-device": {
      "abstract": [
        {
          "text": "Start location services and provide information the system needs to optimize power usage for those services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/getting-the-current-location-of-a-device",
      "kind": "article",
      "role": "article",
      "title": "Getting the current location of a device",
      "type": "topic",
      "url": "/documentation/corelocation/getting-the-current-location-of-a-device"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/handling-location-updates-in-the-background": {
      "abstract": [
        {
          "text": "Configure your app to receive location updates when it isn’t running in the foreground.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/handling-location-updates-in-the-background",
      "kind": "article",
      "role": "article",
      "title": "Handling location updates in the background",
      "type": "topic",
      "url": "/documentation/corelocation/handling-location-updates-in-the-background"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationCoordinate2DInvalid": {
      "abstract": [
        {
          "text": "An invalid coordinate value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCLLocationCoordinate2DInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CLLocationCoordinate2D",
          "text": "CLLocationCoordinate2D"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationCoordinate2DInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCLLocationCoordinate2DInvalid"
        }
      ],
      "role": "symbol",
      "title": "kCLLocationCoordinate2DInvalid",
      "type": "topic",
      "url": "/documentation/corelocation/kcllocationcoordinate2dinvalid"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/monitoring-location-changes-with-core-location": {
      "abstract": [
        {
          "text": "Define boundaries and act on user location updates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/monitoring-location-changes-with-core-location",
      "kind": "article",
      "role": "sampleCode",
      "title": "Monitoring location changes with Core Location",
      "type": "topic",
      "url": "/documentation/corelocation/monitoring-location-changes-with-core-location"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:7SwiftUI10AnimatableP": {
      "abstract": [
        {
          "text": "A type that describes how to animate a property of a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Animatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI10AnimatableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Animatable",
      "type": "topic",
      "url": "/documentation/SwiftUI/Animatable"
    },
    "doc://com.externally.resolved.symbol/s:SE": {
      "abstract": [
        {
          "text": "A type that can encode itself to an external representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Encodable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SE",
      "kind": "symbol",
      "role": "symbol",
      "title": "Encodable",
      "type": "topic",
      "url": "/documentation/Swift/Encodable"
    },
    "doc://com.externally.resolved.symbol/s:Se": {
      "abstract": [
        {
          "text": "A type that can decode itself from an external representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Decodable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Se",
      "kind": "symbol",
      "role": "symbol",
      "title": "Decodable",
      "type": "topic",
      "url": "/documentation/Swift/Decodable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:7SwiftUI10AnimatableP",
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:Se",
        "doc://com.externally.resolved.symbol/s:SE",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Location-updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/getting-the-current-location-of-a-device",
        "doc://com.apple.corelocation/documentation/CoreLocation/handling-location-updates-in-the-background",
        "doc://com.apple.corelocation/documentation/CoreLocation/creating-a-location-push-service-extension",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLFloor",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLVisit",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationSourceInformation",
        "doc://com.apple.corelocation/documentation/CoreLocation/monitoring-location-changes-with-core-location",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSession-pt7n"
      ],
      "title": "Location updates"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-location-coordinate",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/init()",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/init(latitude:longitude:)",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2DMake(_:_:)"
      ],
      "title": "Creating a location coordinate"
    },
    {
      "anchor": "Getting-the-geographic-coordinates",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/latitude",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/longitude"
      ],
      "title": "Getting the geographic coordinates"
    },
    {
      "anchor": "Validating-a-coordinate",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2DIsValid(_:)",
        "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationCoordinate2DInvalid"
      ],
      "title": "Validating a coordinate"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLLocationCoordinate2D"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationCoordinate2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationCoordinate2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corelocation/documentation/CoreLocation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-location-coordinate",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2DMake(_:_:)"
              ],
              "title": "Creating a location coordinate"
            },
            {
              "anchor": "Getting-the-geographic-coordinates",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/latitude",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D/longitude"
              ],
              "title": "Getting the geographic coordinates"
            },
            {
              "anchor": "Validating-a-coordinate",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2DIsValid(_:)",
                "doc://com.apple.corelocation/documentation/CoreLocation/kCLLocationCoordinate2DInvalid"
              ],
              "title": "Validating a coordinate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/s:7SwiftUI10AnimatableP",
                "doc://com.externally.resolved.symbol/s:s8CopyableP"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Location-updates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/getting-the-current-location-of-a-device",
                "doc://com.apple.corelocation/documentation/CoreLocation/handling-location-updates-in-the-background",
                "doc://com.apple.corelocation/documentation/CoreLocation/creating-a-location-push-service-extension",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLFloor",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLVisit",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationSourceInformation",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSession-2ddhd",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSessionDiagnostic",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLBackgroundActivitySessionDiagnostic",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater"
              ],
              "title": "Location updates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLLocationCoordinate2D"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocation/title",
          "value": "CLLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2D~1latitude/title",
          "value": "latitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2D~1latitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "latitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2D~1longitude/title",
          "value": "longitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2D~1longitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "longitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLFloor/title",
          "value": "CLFloor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLFloor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLFloor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLFloor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLFloor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLLocationCoordinate2DInvalid/title",
          "value": "kCLLocationCoordinate2DInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1kCLLocationCoordinate2DInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCLLocationCoordinate2DInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLVisit/title",
          "value": "CLVisit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLVisit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLVisit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLVisit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLVisit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationSourceInformation/title",
          "value": "CLLocationSourceInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationSourceInformation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationSourceInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationSourceInformation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationSourceInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2DMake(_:_:)/title",
          "value": "CLLocationCoordinate2DMake"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2DMake(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationCoordinate2DMake"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2D/title",
          "value": "CLLocationCoordinate2D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationCoordinate2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationCoordinate2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2DIsValid(_:)/title",
          "value": "CLLocationCoordinate2DIsValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2DIsValid(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationCoordinate2DIsValid"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/cllocationcoordinate2d"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corelocation/cllocationcoordinate2d"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
