{
  "abstract": [
    {
      "text": "A user-friendly description of a geographic coordinate, often containing the name of the place, its address, and other relevant information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CLPlacemark",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CLPlacemark"
      }
    ],
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLPlacemark"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CLPlacemark"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLPlacemark"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.corelocation/documentation/CoreLocation/converting-between-coordinates-and-user-friendly-place-names",
        "doc://com.apple.corelocation/documentation/CoreLocation/converting-a-user-s-location-to-a-descriptive-placemark"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "code": "CLPlacemark",
              "type": "codeVoice"
            },
            {
              "text": " object stores placemark data for a given latitude and longitude. Placemark data includes information such as the country or region, state, city, and street address associated with the specified coordinate. It can also include points of interest and geographically related data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you reverse geocode a geographic coordinate using a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLGeocoder",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, you receive a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object containing the descriptive information for that location. You can also create ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object and fill it with address information yourself, which you might do when you want to determine the geographic coordinate associated with the location.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLGeocoder": {
      "abstract": [
        {
          "text": "An interface for converting between geographic coordinates and place names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLGeocoder"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLGeocoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLGeocoder"
        }
      ],
      "role": "symbol",
      "title": "CLGeocoder",
      "type": "topic",
      "url": "/documentation/corelocation/clgeocoder"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark": {
      "abstract": [
        {
          "text": "A user-friendly description of a geographic coordinate, often containing the name of the place, its address, and other relevant information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLPlacemark"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLPlacemark"
        }
      ],
      "role": "symbol",
      "title": "CLPlacemark",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/InstanceDisplayRepresentable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/InstanceDisplayRepresentable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "InstanceDisplayRepresentable Implementations",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/instancedisplayrepresentable-implementations"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/Specification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Specification"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/Specification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Specification"
        }
      ],
      "role": "symbol",
      "title": "CLPlacemark.Specification",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/specification"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/TypeDisplayRepresentable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/TypeDisplayRepresentable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TypeDisplayRepresentable Implementations",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/typedisplayrepresentable-implementations"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/UnwrappedType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnwrappedType"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/UnwrappedType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UnwrappedType"
        }
      ],
      "role": "symbol",
      "title": "CLPlacemark.UnwrappedType",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/unwrappedtype"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/ValueType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ValueType"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/ValueType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ValueType"
        }
      ],
      "role": "symbol",
      "title": "CLPlacemark.ValueType",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/valuetype"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/addressDictionary": {
      "abstract": [
        {
          "text": "A dictionary containing the Address Book keys and values for the placemark.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addressDictionary"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/addressDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addressDictionary"
        }
      ],
      "role": "symbol",
      "title": "addressDictionary",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/addressdictionary"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/administrativeArea": {
      "abstract": [
        {
          "text": "The state or province associated with the placemark.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "administrativeArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/administrativeArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "administrativeArea"
        }
      ],
      "role": "symbol",
      "title": "administrativeArea",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/administrativearea"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/areasOfInterest": {
      "abstract": [
        {
          "text": "The relevant areas of interest associated with the placemark.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "areasOfInterest"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/areasOfInterest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "areasOfInterest"
        }
      ],
      "role": "symbol",
      "title": "areasOfInterest",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/areasofinterest"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/country": {
      "abstract": [
        {
          "text": "The name of the country or region associated with the placemark.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "country"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/country",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "country"
        }
      ],
      "role": "symbol",
      "title": "country",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/country"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/defaultResolverSpecification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultResolverSpecification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10AppIntents26EmptyResolverSpecificationV",
          "text": "EmptyResolverSpecification"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLPlacemark",
          "text": "CLPlacemark"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/defaultResolverSpecification",
      "kind": "symbol",
      "role": "symbol",
      "title": "defaultResolverSpecification",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/defaultresolverspecification"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/displayRepresentation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayRepresentation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10AppIntents21DisplayRepresentationV",
          "text": "DisplayRepresentation"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/displayRepresentation",
      "kind": "symbol",
      "role": "symbol",
      "title": "displayRepresentation",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/displayrepresentation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/init": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/init",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/init"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/init(location:name:postalAddress:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLLocation",
          "text": "CLLocation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "postalAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNPostalAddress",
          "text": "CNPostalAddress"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/init(location:name:postalAddress:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "placemarkWithLocation:name:postalAddress:"
        }
      ],
      "role": "symbol",
      "title": "init(location:name:postalAddress:)",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/init(location:name:postaladdress:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/init(placemark:)": {
      "abstract": [
        {
          "text": "Initializes and returns a placemark object from another placemark object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "placemark"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLPlacemark",
          "text": "CLPlacemark"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/init(placemark:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPlacemark:"
        }
      ],
      "role": "symbol",
      "title": "init(placemark:)",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/init(placemark:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/inlandWater": {
      "abstract": [
        {
          "text": "The name of the inland water body associated with the placemark.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inlandWater"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/inlandWater",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inlandWater"
        }
      ],
      "role": "symbol",
      "title": "inlandWater",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/inlandwater"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/isoCountryCode": {
      "abstract": [
        {
          "text": "The abbreviated country or region name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isoCountryCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/isoCountryCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ISOcountryCode"
        }
      ],
      "role": "symbol",
      "title": "isoCountryCode",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/isocountrycode"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/locality": {
      "abstract": [
        {
          "text": "The city associated with the placemark.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/locality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locality"
        }
      ],
      "role": "symbol",
      "title": "locality",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/locality"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/location": {
      "abstract": [
        {
          "text": "The location object containing latitude and longitude information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLLocation",
          "text": "CLLocation"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/location",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "location"
        }
      ],
      "role": "symbol",
      "title": "location",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/location"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/name": {
      "abstract": [
        {
          "text": "The name of the placemark.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/name"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/new": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "new"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/new",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "new"
        }
      ],
      "role": "symbol",
      "title": "new",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/new"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/ocean": {
      "abstract": [
        {
          "text": "The name of the ocean associated with the placemark.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ocean"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/ocean",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ocean"
        }
      ],
      "role": "symbol",
      "title": "ocean",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/ocean"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/postalAddress": {
      "abstract": [
        {
          "text": "The postal address associated with the location, formatted for use with the Contacts framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postalAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CNPostalAddress",
          "text": "CNPostalAddress"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/postalAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "postalAddress"
        }
      ],
      "role": "symbol",
      "title": "postalAddress",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/postaladdress"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/postalCode": {
      "abstract": [
        {
          "text": "The postal code associated with the placemark.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postalCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/postalCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "postalCode"
        }
      ],
      "role": "symbol",
      "title": "postalCode",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/postalcode"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/region": {
      "abstract": [
        {
          "text": "The geographic region associated with the placemark.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "region"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLRegion",
          "text": "CLRegion"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/region",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "region"
        }
      ],
      "role": "symbol",
      "title": "region",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/region"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/subAdministrativeArea": {
      "abstract": [
        {
          "text": "Additional administrative area information for the placemark.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subAdministrativeArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/subAdministrativeArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subAdministrativeArea"
        }
      ],
      "role": "symbol",
      "title": "subAdministrativeArea",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/subadministrativearea"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/subLocality": {
      "abstract": [
        {
          "text": "Additional city-level information for the placemark.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subLocality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/subLocality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subLocality"
        }
      ],
      "role": "symbol",
      "title": "subLocality",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/sublocality"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/subThoroughfare": {
      "abstract": [
        {
          "text": "Additional street-level information for the placemark.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subThoroughfare"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/subThoroughfare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subThoroughfare"
        }
      ],
      "role": "symbol",
      "title": "subThoroughfare",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/subthoroughfare"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/thoroughfare": {
      "abstract": [
        {
          "text": "The street address associated with the placemark.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thoroughfare"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/thoroughfare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "thoroughfare"
        }
      ],
      "role": "symbol",
      "title": "thoroughfare",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/thoroughfare"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/timeZone": {
      "abstract": [
        {
          "text": "The time zone associated with the placemark.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeZone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8TimeZoneV",
          "text": "TimeZone"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/timeZone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeZone"
        }
      ],
      "role": "symbol",
      "title": "timeZone",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/timezone"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/typeDisplayRepresentation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeDisplayRepresentation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10AppIntents25TypeDisplayRepresentationV",
          "text": "TypeDisplayRepresentation"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/typeDisplayRepresentation",
      "kind": "symbol",
      "role": "symbol",
      "title": "typeDisplayRepresentation",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/typedisplayrepresentation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/converting-a-user-s-location-to-a-descriptive-placemark": {
      "abstract": [
        {
          "text": "Transform the user’s location that displays on a map into an informative textual description by reverse geocoding.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/converting-a-user-s-location-to-a-descriptive-placemark",
      "kind": "article",
      "role": "article",
      "title": "Converting a user’s location to a descriptive placemark",
      "type": "topic",
      "url": "/documentation/corelocation/converting-a-user-s-location-to-a-descriptive-placemark"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/converting-between-coordinates-and-user-friendly-place-names": {
      "abstract": [
        {
          "text": "Convert between a latitude and longitude pair and a more user-friendly description of that location.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/converting-between-coordinates-and-user-friendly-place-names",
      "kind": "article",
      "role": "article",
      "title": "Converting between coordinates and user-friendly place names",
      "type": "topic",
      "url": "/documentation/corelocation/converting-between-coordinates-and-user-friendly-place-names"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:10AppIntents20DisplayRepresentableP": {
      "abstract": [
        {
          "text": "An interface for providing a dynamic visual representation of a specific type and instances of that type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisplayRepresentable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10AppIntents28InstanceDisplayRepresentableP",
          "text": "InstanceDisplayRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10AppIntents24TypeDisplayRepresentableP",
          "text": "TypeDisplayRepresentable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10AppIntents20DisplayRepresentableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "DisplayRepresentable",
      "type": "topic",
      "url": "/documentation/AppIntents/DisplayRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:10AppIntents24TypeDisplayRepresentableP": {
      "abstract": [
        {
          "text": "An interface for providing the visual representation of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TypeDisplayRepresentable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10AppIntents24TypeDisplayRepresentableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "TypeDisplayRepresentable",
      "type": "topic",
      "url": "/documentation/AppIntents/TypeDisplayRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:10AppIntents28InstanceDisplayRepresentableP": {
      "abstract": [
        {
          "text": "An interface for providing the visual representation for an instance of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InstanceDisplayRepresentable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation40CustomLocalizedStringResourceConvertibleP",
          "text": "CustomLocalizedStringResourceConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10AppIntents28InstanceDisplayRepresentableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "InstanceDisplayRepresentable",
      "type": "topic",
      "url": "/documentation/AppIntents/InstanceDisplayRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation40CustomLocalizedStringResourceConvertibleP": {
      "abstract": [
        {
          "text": "A type that provides an out-of-process localizable description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomLocalizedStringResourceConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation40CustomLocalizedStringResourceConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomLocalizedStringResourceConvertible",
      "type": "topic",
      "url": "/documentation/foundation/customlocalizedstringresourceconvertible"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:10Foundation40CustomLocalizedStringResourceConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:10AppIntents20DisplayRepresentableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:10AppIntents28InstanceDisplayRepresentableP",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:10AppIntents24TypeDisplayRepresentableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Geocoding",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/converting-between-coordinates-and-user-friendly-place-names",
        "doc://com.apple.corelocation/documentation/CoreLocation/converting-a-user-s-location-to-a-descriptive-placemark",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLGeocoder"
      ],
      "title": "Geocoding"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-placemark-object",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/init(placemark:)"
      ],
      "title": "Creating a placemark object"
    },
    {
      "anchor": "Getting-the-placemarks-location",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/location",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/region"
      ],
      "title": "Getting the placemark’s location"
    },
    {
      "anchor": "Getting-the-placemark-name",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/name"
      ],
      "title": "Getting the placemark name"
    },
    {
      "anchor": "Getting-the-placemark-details",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/thoroughfare",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/subThoroughfare",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/locality",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/subLocality",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/administrativeArea",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/subAdministrativeArea",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/postalCode"
      ],
      "title": "Getting the placemark details"
    },
    {
      "anchor": "Getting-the-placemarks-country",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/isoCountryCode",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/country"
      ],
      "title": "Getting the placemark’s country"
    },
    {
      "anchor": "Getting-the-associated-contact-details",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/postalAddress",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/addressDictionary"
      ],
      "title": "Getting the associated contact details"
    },
    {
      "anchor": "Getting-landscape-information",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/inlandWater",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/ocean"
      ],
      "title": "Getting landscape information"
    },
    {
      "anchor": "Getting-points-of-interest",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/areasOfInterest"
      ],
      "title": "Getting points of interest"
    },
    {
      "anchor": "Getting-the-placemarks-time-zone",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/timeZone"
      ],
      "title": "Getting the placemark’s time zone"
    },
    {
      "anchor": "Type-Aliases",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/Specification",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/UnwrappedType",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/ValueType"
      ],
      "title": "Type Aliases"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/displayRepresentation"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/defaultResolverSpecification",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/typeDisplayRepresentation"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/init(location:name:postalAddress:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/InstanceDisplayRepresentable-Implementations",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/TypeDisplayRepresentable-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLPlacemark"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLPlacemark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLPlacemark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corelocation/documentation/CoreLocation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-placemark-object",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/init(placemark:)"
              ],
              "title": "Creating a placemark object"
            },
            {
              "anchor": "Getting-the-placemarks-location",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/location",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/region"
              ],
              "title": "Getting the placemark’s location"
            },
            {
              "anchor": "Getting-the-placemark-name",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/name"
              ],
              "title": "Getting the placemark name"
            },
            {
              "anchor": "Getting-the-placemark-details",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/thoroughfare",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/subThoroughfare",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/locality",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/subLocality",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/administrativeArea",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/subAdministrativeArea",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/postalCode"
              ],
              "title": "Getting the placemark details"
            },
            {
              "anchor": "Getting-the-placemarks-country",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/isoCountryCode",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/country"
              ],
              "title": "Getting the placemark’s country"
            },
            {
              "anchor": "Getting-the-associated-contact-details",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/postalAddress",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/addressDictionary"
              ],
              "title": "Getting the associated contact details"
            },
            {
              "anchor": "Getting-landscape-information",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/inlandWater",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/ocean"
              ],
              "title": "Getting landscape information"
            },
            {
              "anchor": "Getting-points-of-interest",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/areasOfInterest"
              ],
              "title": "Getting points of interest"
            },
            {
              "anchor": "Getting-the-placemarks-time-zone",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/timeZone"
              ],
              "title": "Getting the placemark’s time zone"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/init"
              ],
              "title": "Instance Methods"
            },
            {
              "anchor": "Type-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/init(location:name:postalAddress:)",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/new"
              ],
              "title": "Type Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/s:s8CopyableP",
                "doc://com.externally.resolved.symbol/s:10Foundation40CustomLocalizedStringResourceConvertibleP",
                "doc://com.externally.resolved.symbol/s:10AppIntents20DisplayRepresentableP",
                "doc://com.externally.resolved.symbol/s:10AppIntents28InstanceDisplayRepresentableP",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
                "doc://com.externally.resolved.symbol/s:10AppIntents24TypeDisplayRepresentableP"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Geocoding",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/converting-between-coordinates-and-user-friendly-place-names",
                "doc://com.apple.corelocation/documentation/CoreLocation/converting-a-user-s-location-to-a-descriptive-placemark",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLGeocoder"
              ],
              "title": "Geocoding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLPlacemark"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1locality/title",
          "value": "locality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1locality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "locality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1isoCountryCode/title",
          "value": "ISOcountryCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1isoCountryCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ISOcountryCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1thoroughfare/title",
          "value": "thoroughfare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1thoroughfare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "thoroughfare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1subLocality/title",
          "value": "subLocality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1subLocality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subLocality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1postalAddress/title",
          "value": "postalAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1postalAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "postalAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1inlandWater/title",
          "value": "inlandWater"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1inlandWater/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inlandWater"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1subThoroughfare/title",
          "value": "subThoroughfare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1subThoroughfare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subThoroughfare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1postalCode/title",
          "value": "postalCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1postalCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "postalCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1areasOfInterest/title",
          "value": "areasOfInterest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1areasOfInterest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "areasOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1administrativeArea/title",
          "value": "administrativeArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1administrativeArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "administrativeArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark/title",
          "value": "CLPlacemark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLPlacemark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLPlacemark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1addressDictionary/title",
          "value": "addressDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1addressDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "addressDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLGeocoder/title",
          "value": "CLGeocoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLGeocoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLGeocoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLGeocoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLGeocoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1init(placemark:)/title",
          "value": "initWithPlacemark:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1init(placemark:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPlacemark:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1ocean/title",
          "value": "ocean"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1ocean/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ocean"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1timeZone/title",
          "value": "timeZone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1timeZone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeZone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1country/title",
          "value": "country"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1country/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "country"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1init(location:name:postalAddress:)/title",
          "value": "placemarkWithLocation:name:postalAddress:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1init(location:name:postalAddress:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "placemarkWithLocation:name:postalAddress:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1region/title",
          "value": "region"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1region/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "region"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1subAdministrativeArea/title",
          "value": "subAdministrativeArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1subAdministrativeArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subAdministrativeArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1location/title",
          "value": "location"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1location/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "location"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/clplacemark"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corelocation/clplacemark"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
