{
  "abstract": [
    {
      "text": "Transform the user’s location that displays on a map into an informative textual description by reverse geocoding.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/converting-a-user-s-location-to-a-descriptive-placemark"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Converting a user’s location to a descriptive placemark"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can show a user’s location on a map in order to orient them to elements of your app that use map content. For instance, a user’s current location can be a point of reference for retrieving search results or calculating directions. Additionally, you can display location information outside of the map, such as a search field pre-filled with the user’s current city or street address. To provide this information in your app, configure your map view to display the user’s location, and then translate the location to informative, user-friendly data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Display-the-user-location-annotation",
          "level": 3,
          "text": "Display the user location annotation",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To provide user-friendly place information, configure your map view to display the user’s current location by enabling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MapKit/MKMapView/showsUserLocation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". After enabling this property, the map delegate begins receiving updates to the user’s location, represented with a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MapKit/MKUserLocation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, through ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MapKit/MKMapViewDelegate/mapView(_:didUpdate:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Geocode-the-user-location-annotation",
          "level": 3,
          "text": "Geocode the user location annotation",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects represent user place names, and include properties for street name, city name, country or region name, and many other location identifiers. When ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MapKit/MKMapViewDelegate/mapView(_:didUpdate:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " receives updates on the user’s location, convert the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MapKit/MKUserLocation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " by reverse geocoding the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MapKit/MKUserLocation/location",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property with a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLGeocoder",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Readable descriptions of the user’s location are available as properties on the placemark, such as the city information stored in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/locality",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Geocoding requests are rate-limited for each app. Issue new geocoding requests only when the user has moved a significant distance and after a reasonable amount of time has passed.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "code": [
            "func mapView(_ mapView: MKMapView, didUpdate userLocation: MKUserLocation) {",
            "        guard let newLocation = userLocation.location else { return }",
            "        ",
            "        let currentTime = Date()",
            "        let lastLocation = self.currentLocation",
            "        self.currentLocation = newLocation",
            "        ",
            "        // Only get new placemark information if you don't have a previous location,",
            "        // if the user has moved a meaningful distance from the previous location, such as 1000 meters,",
            "        // and if it's been 60 seconds since the last geocode request.",
            "        if let lastLocation = lastLocation,",
            "            newLocation.distance(from: lastLocation) <= 1000,",
            "            let lastTime = lastGeocodeTime,",
            "            currentTime.timeIntervalSince(lastTime) < 60 {",
            "            return",
            "        }",
            "        ",
            "        // Convert the user's location to a user-friendly place name by reverse geocoding the location.",
            "        lastGeocodeTime = currentTime",
            "        geocoder.reverseGeocodeLocation(newLocation) { (placemarks, error) in",
            "            guard error == nil else {",
            "                self.handleError(error)",
            "                return",
            "            }",
            "            ",
            "            // Most geocoding requests contain only one result.",
            "            if let firstPlacemark = placemarks?.first {",
            "                self.mostRecentPlacemark = firstPlacemark",
            "                self.currentCity = firstPlacemark.locality",
            "            }",
            "        }",
            "    }"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "See-also",
          "level": 2,
          "text": "See also",
          "type": "heading"
        },
        {
          "anchor": "Related-Documentation",
          "level": 3,
          "text": "Related Documentation",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/converting-between-coordinates-and-user-friendly-place-names",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLGeocoder": {
      "abstract": [
        {
          "text": "An interface for converting between geographic coordinates and place names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLGeocoder"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLGeocoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLGeocoder"
        }
      ],
      "role": "symbol",
      "title": "CLGeocoder",
      "type": "topic",
      "url": "/documentation/corelocation/clgeocoder"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark": {
      "abstract": [
        {
          "text": "A user-friendly description of a geographic coordinate, often containing the name of the place, its address, and other relevant information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLPlacemark"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLPlacemark"
        }
      ],
      "role": "symbol",
      "title": "CLPlacemark",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/locality": {
      "abstract": [
        {
          "text": "The city associated with the placemark.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark/locality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locality"
        }
      ],
      "role": "symbol",
      "title": "locality",
      "type": "topic",
      "url": "/documentation/corelocation/clplacemark/locality"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/converting-between-coordinates-and-user-friendly-place-names": {
      "abstract": [
        {
          "text": "Convert between a latitude and longitude pair and a more user-friendly description of that location.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/converting-between-coordinates-and-user-friendly-place-names",
      "kind": "article",
      "role": "article",
      "title": "Converting between coordinates and user-friendly place names",
      "type": "topic",
      "url": "/documentation/corelocation/converting-between-coordinates-and-user-friendly-place-names"
    },
    "doc://com.apple.documentation/documentation/MapKit/MKMapView/showsUserLocation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the map tries to display the user’s location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsUserLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MapKit/MKMapView/showsUserLocation",
      "kind": "symbol",
      "role": "symbol",
      "title": "showsUserLocation",
      "type": "topic",
      "url": "/documentation/MapKit/MKMapView/showsUserLocation"
    },
    "doc://com.apple.documentation/documentation/MapKit/MKMapViewDelegate/mapView(_:didUpdate:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the map view updates the user’s location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "mapView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapView",
          "text": "MKMapView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdate"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "userLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKUserLocation",
          "text": "MKUserLocation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MapKit/MKMapViewDelegate/mapView(_:didUpdate:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "mapView(_:didUpdate:)",
      "type": "topic",
      "url": "/documentation/MapKit/MKMapViewDelegate/mapView(_:didUpdate:)"
    },
    "doc://com.apple.documentation/documentation/MapKit/MKUserLocation": {
      "abstract": [
        {
          "text": "An annotation that reflects the user’s location on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKUserLocation"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MapKit/MKUserLocation",
      "kind": "symbol",
      "role": "symbol",
      "title": "MKUserLocation",
      "type": "topic",
      "url": "/documentation/MapKit/MKUserLocation"
    },
    "doc://com.apple.documentation/documentation/MapKit/MKUserLocation/location": {
      "abstract": [
        {
          "text": "The location of the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLLocation",
          "text": "CLLocation"
        },
        {
          "kind": "text",
          "text": "? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MapKit/MKUserLocation/location",
      "kind": "symbol",
      "role": "symbol",
      "title": "location",
      "type": "topic",
      "url": "/documentation/MapKit/MKUserLocation/location"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Geocoding",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/converting-between-coordinates-and-user-friendly-place-names",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLGeocoder",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark"
      ],
      "title": "Geocoding"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Geocoding",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/converting-between-coordinates-and-user-friendly-place-names",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLGeocoder",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLPlacemark"
              ],
              "title": "Geocoding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark/title",
          "value": "CLPlacemark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLPlacemark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLPlacemark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKMapViewDelegate~1mapView(_:didUpdate:)/title",
          "value": "mapView:didUpdateUserLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKMapViewDelegate~1mapView(_:didUpdate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "mapView:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MKMapView",
              "text": "MKMapView"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "mapView"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "didUpdateUserLocation:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MKUserLocation",
              "text": "MKUserLocation"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "userLocation"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLGeocoder/title",
          "value": "CLGeocoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLGeocoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLGeocoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLGeocoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLGeocoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1locality/title",
          "value": "locality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLPlacemark~1locality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "locality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKUserLocation/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MKUserLocation"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKMapView~1showsUserLocation/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "showsUserLocation"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKUserLocation~1location/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CLLocation",
              "text": "CLLocation"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "location"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/converting-a-user-s-location-to-a-descriptive-placemark"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corelocation/converting-a-user-s-location-to-a-descriptive-placemark"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
