{
  "abstract": [
    {
      "text": "Review unsupported symbols and their replacements.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated symbols"
  },
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager": {
      "abstract": [
        {
          "text": "The object you use to start and stop the delivery of location-related events to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationManager"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationManager"
        }
      ],
      "role": "symbol",
      "title": "CLLocationManager",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/allowDeferredLocationUpdates(untilTraveled:timeout:)": {
      "abstract": [
        {
          "text": "Asks the location manager to defer the delivery of location updates until the specified criteria are met.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowDeferredLocationUpdates"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "untilTraveled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDistance",
          "text": "CLLocationDistance"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/allowDeferredLocationUpdates(untilTraveled:timeout:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowDeferredLocationUpdatesUntilTraveled:timeout:"
        }
      ],
      "role": "symbol",
      "title": "allowDeferredLocationUpdates(untilTraveled:timeout:)",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/allowdeferredlocationupdates(untiltraveled:timeout:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/authorizationStatus()": {
      "abstract": [
        {
          "text": "Returns the app’s authorization status for using location services.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLAuthorizationStatus",
          "text": "CLAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/authorizationStatus()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "authorizationStatus()",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/authorizationstatus()"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/deferredLocationUpdatesAvailable()": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the device supports deferred location updates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deferredLocationUpdatesAvailable"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/deferredLocationUpdatesAvailable()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deferredLocationUpdatesAvailable"
        }
      ],
      "role": "symbol",
      "title": "deferredLocationUpdatesAvailable()",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/deferredlocationupdatesavailable()"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/disallowDeferredLocationUpdates()": {
      "abstract": [
        {
          "text": "Cancels the deferral of location updates for this app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disallowDeferredLocationUpdates"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/disallowDeferredLocationUpdates()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disallowDeferredLocationUpdates"
        }
      ],
      "role": "symbol",
      "title": "disallowDeferredLocationUpdates()",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/disallowdeferredlocationupdates()"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/headingAvailable-swift.property": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the location manager is able to generate heading-related events.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headingAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/headingAvailable-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "headingAvailable"
        }
      ],
      "role": "symbol",
      "title": "headingAvailable",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/headingavailable-swift.property"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/locationServicesEnabled-swift.property": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether location services are enabled on the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationServicesEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/locationServicesEnabled-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locationServicesEnabled"
        }
      ],
      "role": "symbol",
      "title": "locationServicesEnabled",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/locationservicesenabled-swift.property"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/purpose": {
      "abstract": [
        {
          "text": "An app-provided string that describes the reason for using location services.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "purpose"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/purpose",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "purpose"
        }
      ],
      "role": "symbol",
      "title": "purpose",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/purpose"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/rangedRegions": {
      "abstract": [
        {
          "text": "The set of regions currently being tracked using ranging.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rangedRegions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLRegion",
          "text": "CLRegion"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/rangedRegions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rangedRegions"
        }
      ],
      "role": "symbol",
      "title": "rangedRegions",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/rangedregions"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/regionMonitoringAvailable()": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether region monitoring is supported on the current device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionMonitoringAvailable"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/regionMonitoringAvailable()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "regionMonitoringAvailable"
        }
      ],
      "role": "symbol",
      "title": "regionMonitoringAvailable()",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/regionmonitoringavailable()"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/regionMonitoringEnabled()": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether region monitoring is currently enabled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionMonitoringEnabled"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/regionMonitoringEnabled()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "regionMonitoringEnabled"
        }
      ],
      "role": "symbol",
      "title": "regionMonitoringEnabled()",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/regionmonitoringenabled()"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/requestState(for:)": {
      "abstract": [
        {
          "text": "Retrieves the state of a region asynchronously.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLRegion",
          "text": "CLRegion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/requestState(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestStateForRegion:"
        }
      ],
      "role": "symbol",
      "title": "requestState(for:)",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/requeststate(for:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startMonitoring(for:)": {
      "abstract": [
        {
          "text": "Starts monitoring the specified region.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startMonitoring"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLRegion",
          "text": "CLRegion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startMonitoring(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startMonitoringForRegion:"
        }
      ],
      "role": "symbol",
      "title": "startMonitoring(for:)",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/startmonitoring(for:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startMonitoring(for:desiredAccuracy:)": {
      "abstract": [
        {
          "text": "Starts monitoring the specified region for boundary crossings.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startMonitoring"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLRegion",
          "text": "CLRegion"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "desiredAccuracy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationAccuracy",
          "text": "CLLocationAccuracy"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startMonitoring(for:desiredAccuracy:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startMonitoringForRegion:desiredAccuracy:"
        }
      ],
      "role": "symbol",
      "title": "startMonitoring(for:desiredAccuracy:)",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/startmonitoring(for:desiredaccuracy:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startRangingBeacons(in:)": {
      "abstract": [
        {
          "text": "Starts the delivery of notifications for the specified beacon region.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startRangingBeacons"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLBeaconRegion",
          "text": "CLBeaconRegion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startRangingBeacons(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startRangingBeaconsInRegion:"
        }
      ],
      "role": "symbol",
      "title": "startRangingBeacons(in:)",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/startrangingbeacons(in:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/stopMonitoring(for:)": {
      "abstract": [
        {
          "text": "Stops monitoring the specified region.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopMonitoring"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLRegion",
          "text": "CLRegion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/stopMonitoring(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopMonitoringForRegion:"
        }
      ],
      "role": "symbol",
      "title": "stopMonitoring(for:)",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/stopmonitoring(for:)"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/stopRangingBeacons(in:)": {
      "abstract": [
        {
          "text": "Stops the delivery of notifications for the specified beacon region.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopRangingBeacons"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLBeaconRegion",
          "text": "CLBeaconRegion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/stopRangingBeacons(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopRangingBeaconsInRegion:"
        }
      ],
      "role": "symbol",
      "title": "stopRangingBeacons(in:)",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/stoprangingbeacons(in:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Properties",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/headingAvailable-swift.property",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/locationServicesEnabled-swift.property",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/purpose",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/rangedRegions"
      ],
      "title": "Properties"
    },
    {
      "anchor": "Methods",
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startMonitoring(for:)",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/stopMonitoring(for:)",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/regionMonitoringAvailable()",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/regionMonitoringEnabled()",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/authorizationStatus()",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startMonitoring(for:desiredAccuracy:)",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/requestState(for:)",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startRangingBeacons(in:)",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/stopRangingBeacons(in:)",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/deferredLocationUpdatesAvailable()",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/allowDeferredLocationUpdates(untilTraveled:timeout:)",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/disallowDeferredLocationUpdates()"
      ],
      "title": "Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Properties",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/headingAvailable-swift.property",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/locationServicesEnabled-swift.property",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/purpose",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/rangedRegions"
              ],
              "title": "Properties"
            },
            {
              "anchor": "Methods",
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startMonitoring(for:)",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/stopMonitoring(for:)",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/regionMonitoringAvailable()",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/regionMonitoringEnabled()",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/authorizationStatus()",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startMonitoring(for:desiredAccuracy:)",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/requestState(for:)",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startRangingBeacons(in:)",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/stopRangingBeacons(in:)",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/deferredLocationUpdatesAvailable()",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/allowDeferredLocationUpdates(untilTraveled:timeout:)",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/disallowDeferredLocationUpdates()"
              ],
              "title": "Methods"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1startMonitoring(for:)/title",
          "value": "startMonitoringForRegion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1startMonitoring(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startMonitoringForRegion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1locationServicesEnabled-swift.property/title",
          "value": "locationServicesEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1locationServicesEnabled-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "locationServicesEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1regionMonitoringEnabled()/title",
          "value": "regionMonitoringEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1regionMonitoringEnabled()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "regionMonitoringEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1purpose/title",
          "value": "purpose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1purpose/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "purpose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1rangedRegions/title",
          "value": "rangedRegions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1rangedRegions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rangedRegions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1disallowDeferredLocationUpdates()/title",
          "value": "disallowDeferredLocationUpdates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1disallowDeferredLocationUpdates()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "disallowDeferredLocationUpdates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1authorizationStatus()/title",
          "value": "authorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1authorizationStatus()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "authorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1allowDeferredLocationUpdates(untilTraveled:timeout:)/title",
          "value": "allowDeferredLocationUpdatesUntilTraveled:timeout:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1allowDeferredLocationUpdates(untilTraveled:timeout:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "allowDeferredLocationUpdatesUntilTraveled:timeout:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1startRangingBeacons(in:)/title",
          "value": "startRangingBeaconsInRegion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1startRangingBeacons(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startRangingBeaconsInRegion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1headingAvailable-swift.property/title",
          "value": "headingAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1headingAvailable-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "headingAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1regionMonitoringAvailable()/title",
          "value": "regionMonitoringAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1regionMonitoringAvailable()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "regionMonitoringAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1startMonitoring(for:desiredAccuracy:)/title",
          "value": "startMonitoringForRegion:desiredAccuracy:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1startMonitoring(for:desiredAccuracy:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startMonitoringForRegion:desiredAccuracy:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1requestState(for:)/title",
          "value": "requestStateForRegion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1requestState(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestStateForRegion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1stopMonitoring(for:)/title",
          "value": "stopMonitoringForRegion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1stopMonitoring(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopMonitoringForRegion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1deferredLocationUpdatesAvailable()/title",
          "value": "deferredLocationUpdatesAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1deferredLocationUpdatesAvailable()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "deferredLocationUpdatesAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager/title",
          "value": "CLLocationManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1stopRangingBeacons(in:)/title",
          "value": "stopRangingBeaconsInRegion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1stopRangingBeacons(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopRangingBeaconsInRegion:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corelocation/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
