{
  "abstract": [
    {
      "text": "Start location services and provide information the system needs to optimize power usage for those services.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/getting-the-current-location-of-a-device"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Getting the current location of a device"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Core Location offers many different services for getting location-related data, but the most common services return the device’s current location. You might use this information to:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Facilitate navigation, either by foot, car, or other modes of transportation.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Identify nearby points of interest.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Filter search results based on proximity to the person.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Display the person’s location on a map.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Share the person’s location with a friend.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Tag the location of a photo.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Check in with social media.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Track the path someone takes during a workout or hike.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Core Location can determine the current location using many different types of hardware, including Wi-Fi, cellular, and GPS radios. Core Location doesn’t need every one of these radios to determine the location. Instead, it selectively enables radios to get the required location data in the most power-efficient way possible. The configuration of your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object affects which radios the system uses and your app’s power consumption.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Start-the-service-that-delivers-the-location-data-you-need",
          "level": 3,
          "text": "Start the service that delivers the location data you need",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Always choose the most power-efficient location service that meets the needs of your app. Core Location provides the following services for getting location data:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "Visits",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " location service provides the most power-efficient way to get location data. The system monitors the places someone visits and the time they spend there, and delivers that data at a later time. Call ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startMonitoringVisits()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to start the service.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "Significant-change",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " location service offers a low-power way to get location updates. This service uses the cellular and Wi-Fi radios (not GPS) to report only location changes that exceed a significantly large distance. Call ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startMonitoringSignificantLocationChanges()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to start the service.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "Standard",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " location service provides the most precise and regular location data, but uses more power than the other services. Use it primarily if your app provides turn-by-turn navigation or needs a greater precision or frequency of events. This location service is the only one available to apps running in visionOS. Call ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startUpdatingLocation()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to start the service, or call ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/requestLocation()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to get a single location event.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Few apps need to start location services right away, and fewer still need to keep those services running for extended periods of time. Delay the start of location services until someone interacts with your app in a way that requires that information. Then, as soon as you have the location data you need, stop services to preserve battery life. For example, stop services if you only need the current location to filter search results once.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When adding support for a location service, make sure to implement all of the service’s relevant methods in your delegate object. The Standard and Significant-change location services use the same set of delegate methods, but the Visits service has a separate method to receive visit-specific data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For information about the behavior of individual services and how to start and stop them, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Enable-power-saving-features",
          "level": 3,
          "text": "Enable power-saving features",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Core Location optimizes power usage as much as possible, but you can still help. The best optimization is to turn off location services when your app doesn’t need new location data. Other optimizations require you to adjust the configuration of your location manager object:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/distanceFilter",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to the largest possible value that gives you the information you need. Higher values let the system turn off radio hardware more frequently.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/desiredAccuracy",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to the lowest possible value that gives you the information you need. Lower accuracy values let the system use more power-efficient hardware. Lower values also let the system turn off hardware sooner.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configure the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/activityType",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to an appropriate value, and set the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/pausesLocationUpdatesAutomatically",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/swift/true",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". Core Location uses your activity type to turn off hardware automatically when conditions allow it. For example, if the activity type is ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/automotiveNavigation",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and someone’s location isn’t changing, the system might turn off radio hardware until it detects new movement.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/allowsBackgroundLocationUpdates",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/swift/false",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " when you don’t actually need background location updates.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Another way to improve power usage is to add the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSLocationDefaultAccuracyReduced",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key with the value true to your app’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file. Include this key if lower-accuracy location data is sufficient for your needs. For example, an app that returns a list of restaurants within driving distance doesn’t need someone’s precise location. As needed, you can always use your location manager to request more accurate data later. However, the system displays a prompt to the device owner to grant each request you make.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/automotiveNavigation": {
      "abstract": [
        {
          "text": "The value that indicates positioning in an automobile following a road network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automotiveNavigation"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLActivityType/automotiveNavigation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLActivityTypeAutomotiveNavigation"
        }
      ],
      "role": "symbol",
      "title": "CLActivityType.automotiveNavigation",
      "type": "topic",
      "url": "/documentation/corelocation/clactivitytype/automotivenavigation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLBackgroundActivitySessionDiagnostic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CLBackgroundActivitySessionDiagnostic"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBackgroundActivitySessionDiagnostic",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLBackgroundActivitySessionDiagnostic",
      "type": "topic",
      "url": "/documentation/corelocation/clbackgroundactivitysessiondiagnostic"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLFloor": {
      "abstract": [
        {
          "text": "The floor of a building on which the user’s device is located.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLFloor"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLFloor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLFloor"
        }
      ],
      "role": "symbol",
      "title": "CLFloor",
      "type": "topic",
      "url": "/documentation/corelocation/clfloor"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation": {
      "abstract": [
        {
          "text": "The latitude, longitude, and course information reported by the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocation"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocation"
        }
      ],
      "role": "symbol",
      "title": "CLLocation",
      "type": "topic",
      "url": "/documentation/corelocation/cllocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D": {
      "abstract": [
        {
          "text": "The latitude and longitude associated with a location, specified using the WGS 84 reference frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationCoordinate2D"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationCoordinate2D"
        }
      ],
      "role": "symbol",
      "title": "CLLocationCoordinate2D",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationcoordinate2d"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager": {
      "abstract": [
        {
          "text": "The object you use to start and stop the delivery of location-related events to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationManager"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationManager"
        }
      ],
      "role": "symbol",
      "title": "CLLocationManager",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/activityType": {
      "abstract": [
        {
          "text": "The type of activity the app expects the user to typically perform while in the app’s location session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLActivityType",
          "text": "CLActivityType"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/activityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activityType"
        }
      ],
      "role": "symbol",
      "title": "activityType",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/activitytype"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/allowsBackgroundLocationUpdates": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app receives location updates when running in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsBackgroundLocationUpdates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/allowsBackgroundLocationUpdates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsBackgroundLocationUpdates"
        }
      ],
      "role": "symbol",
      "title": "allowsBackgroundLocationUpdates",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/allowsbackgroundlocationupdates"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/desiredAccuracy": {
      "abstract": [
        {
          "text": "The accuracy of the location data that your app wants to receive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "desiredAccuracy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationAccuracy",
          "text": "CLLocationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/desiredAccuracy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "desiredAccuracy"
        }
      ],
      "role": "symbol",
      "title": "desiredAccuracy",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/desiredaccuracy"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/distanceFilter": {
      "abstract": [
        {
          "text": "The minimum distance in meters the device must move horizontally before an update event is generated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distanceFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDistance",
          "text": "CLLocationDistance"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/distanceFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "distanceFilter"
        }
      ],
      "role": "symbol",
      "title": "distanceFilter",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/distancefilter"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/pausesLocationUpdatesAutomatically": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the location-manager object may pause location updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pausesLocationUpdatesAutomatically"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/pausesLocationUpdatesAutomatically",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pausesLocationUpdatesAutomatically"
        }
      ],
      "role": "symbol",
      "title": "pausesLocationUpdatesAutomatically",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/pauseslocationupdatesautomatically"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/requestLocation()": {
      "abstract": [
        {
          "text": "Requests the one-time delivery of the user’s current location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestLocation"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/requestLocation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestLocation"
        }
      ],
      "role": "symbol",
      "title": "requestLocation()",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/requestlocation()"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startMonitoringSignificantLocationChanges()": {
      "abstract": [
        {
          "text": "Starts the generation of updates based on significant location changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startMonitoringSignificantLocationChanges"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startMonitoringSignificantLocationChanges()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startMonitoringSignificantLocationChanges"
        }
      ],
      "role": "symbol",
      "title": "startMonitoringSignificantLocationChanges()",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/startmonitoringsignificantlocationchanges()"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startMonitoringVisits()": {
      "abstract": [
        {
          "text": "Starts the delivery of visit-related events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startMonitoringVisits"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startMonitoringVisits()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startMonitoringVisits"
        }
      ],
      "role": "symbol",
      "title": "startMonitoringVisits()",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/startmonitoringvisits()"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startUpdatingLocation()": {
      "abstract": [
        {
          "text": "Starts the generation of updates that report the user’s current location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startUpdatingLocation"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationManager/startUpdatingLocation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startUpdatingLocation"
        }
      ],
      "role": "symbol",
      "title": "startUpdatingLocation()",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationmanager/startupdatinglocation()"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationSourceInformation": {
      "abstract": [
        {
          "text": "Information about the source that provides a location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationSourceInformation"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationSourceInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationSourceInformation"
        }
      ],
      "role": "symbol",
      "title": "CLLocationSourceInformation",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationsourceinformation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater": {
      "abstract": [
        {
          "text": "An object that provides device location updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CLLocationUpdater"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLLocationUpdater",
      "type": "topic",
      "url": "/documentation/corelocation/cllocationupdater"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSession-2ddhd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CLServiceSession"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSession-2ddhd",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLServiceSession",
      "type": "topic",
      "url": "/documentation/corelocation/clservicesession-2ddhd"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSession-pt7n": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLServiceSession"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSession-pt7n",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLServiceSession"
        }
      ],
      "role": "symbol",
      "title": "CLServiceSession",
      "type": "topic",
      "url": "/documentation/corelocation/clservicesession-pt7n"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSessionDiagnostic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CLServiceSessionDiagnostic"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSessionDiagnostic",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLServiceSessionDiagnostic",
      "type": "topic",
      "url": "/documentation/corelocation/clservicesessiondiagnostic"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLVisit": {
      "abstract": [
        {
          "text": "Information about the user’s location during a specific period of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLVisit"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLVisit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLVisit"
        }
      ],
      "role": "symbol",
      "title": "CLVisit",
      "type": "topic",
      "url": "/documentation/corelocation/clvisit"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/creating-a-location-push-service-extension": {
      "abstract": [
        {
          "text": "Add and configure an extension to enable your location-sharing app to access a user’s location in response to a request from another user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/creating-a-location-push-service-extension",
      "kind": "article",
      "role": "article",
      "title": "Creating a location push service extension",
      "type": "topic",
      "url": "/documentation/corelocation/creating-a-location-push-service-extension"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/handling-location-updates-in-the-background": {
      "abstract": [
        {
          "text": "Configure your app to receive location updates when it isn’t running in the foreground.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/handling-location-updates-in-the-background",
      "kind": "article",
      "role": "article",
      "title": "Handling location updates in the background",
      "type": "topic",
      "url": "/documentation/corelocation/handling-location-updates-in-the-background"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/monitoring-location-changes-with-core-location": {
      "abstract": [
        {
          "text": "Define boundaries and act on user location updates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/monitoring-location-changes-with-core-location",
      "kind": "article",
      "role": "sampleCode",
      "title": "Monitoring location changes with Core Location",
      "type": "topic",
      "url": "/documentation/corelocation/monitoring-location-changes-with-core-location"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSLocationDefaultAccuracyReduced": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app requests reduced location accuracy by default.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/NSLocationDefaultAccuracyReduced",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLocationDefaultAccuracyReduced",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/NSLocationDefaultAccuracyReduced"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Location-updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/handling-location-updates-in-the-background",
        "doc://com.apple.corelocation/documentation/CoreLocation/creating-a-location-push-service-extension",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLFloor",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLVisit",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationSourceInformation",
        "doc://com.apple.corelocation/documentation/CoreLocation/monitoring-location-changes-with-core-location",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSession-pt7n"
      ],
      "title": "Location updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Location-updates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/handling-location-updates-in-the-background",
                "doc://com.apple.corelocation/documentation/CoreLocation/creating-a-location-push-service-extension",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocation",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationCoordinate2D",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLFloor",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLVisit",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationSourceInformation",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSession-2ddhd",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLServiceSessionDiagnostic",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLBackgroundActivitySessionDiagnostic",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLLocationUpdater"
              ],
              "title": "Location updates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLVisit/title",
          "value": "CLVisit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLVisit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLVisit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLVisit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLVisit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1pausesLocationUpdatesAutomatically/title",
          "value": "pausesLocationUpdatesAutomatically"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1pausesLocationUpdatesAutomatically/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pausesLocationUpdatesAutomatically"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1automotiveNavigation/title",
          "value": "CLActivityTypeAutomotiveNavigation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLActivityType~1automotiveNavigation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLActivityTypeAutomotiveNavigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1startUpdatingLocation()/title",
          "value": "startUpdatingLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1startUpdatingLocation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startUpdatingLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1startMonitoringVisits()/title",
          "value": "startMonitoringVisits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1startMonitoringVisits()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startMonitoringVisits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationSourceInformation/title",
          "value": "CLLocationSourceInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationSourceInformation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationSourceInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationSourceInformation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationSourceInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager/title",
          "value": "CLLocationManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1desiredAccuracy/title",
          "value": "desiredAccuracy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1desiredAccuracy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "desiredAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocation/title",
          "value": "CLLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLFloor/title",
          "value": "CLFloor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLFloor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLFloor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLFloor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLFloor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1requestLocation()/title",
          "value": "requestLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1requestLocation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2D/title",
          "value": "CLLocationCoordinate2D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationCoordinate2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationCoordinate2D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationCoordinate2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1activityType/title",
          "value": "activityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1activityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1startMonitoringSignificantLocationChanges()/title",
          "value": "startMonitoringSignificantLocationChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1startMonitoringSignificantLocationChanges()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startMonitoringSignificantLocationChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1allowsBackgroundLocationUpdates/title",
          "value": "allowsBackgroundLocationUpdates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1allowsBackgroundLocationUpdates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsBackgroundLocationUpdates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1distanceFilter/title",
          "value": "distanceFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLLocationManager~1distanceFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "distanceFilter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/getting-the-current-location-of-a-device"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corelocation/getting-the-current-location-of-a-device"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
