{
  "abstract": [
    {
      "text": "The Smart Invert accessibility feature.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature/invertColors"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIGuidedAccessAccessibilityFeature@UIGuidedAccessAccessibilityFeatureInvertColors",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invertColors"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UIGuidedAccessAccessibilityFeature",
        "text": "UIGuidedAccessAccessibilityFeature"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIGuidedAccessAccessibilityFeatureInvertColors"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "invertColors"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invertColors"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIGuidedAccessAccessibilityFeature",
              "text": "UIGuidedAccessAccessibilityFeature"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature": {
      "abstract": [
        {
          "text": "Constants that describe accessibility features for Guided Access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGuidedAccessAccessibilityFeature"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGuidedAccessAccessibilityFeature"
        }
      ],
      "role": "symbol",
      "title": "UIGuidedAccessAccessibilityFeature",
      "type": "topic",
      "url": "/documentation/uikit/uiguidedaccessaccessibilityfeature"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature/assistiveTouch": {
      "abstract": [
        {
          "text": "The AssistiveTouch accessibility feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assistiveTouch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIGuidedAccessAccessibilityFeature",
          "text": "UIGuidedAccessAccessibilityFeature"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature/assistiveTouch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGuidedAccessAccessibilityFeatureAssistiveTouch"
        }
      ],
      "role": "symbol",
      "title": "assistiveTouch",
      "type": "topic",
      "url": "/documentation/uikit/uiguidedaccessaccessibilityfeature/assistivetouch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature/grayscaleDisplay": {
      "abstract": [
        {
          "text": "The Grayscale accessibility feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "grayscaleDisplay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIGuidedAccessAccessibilityFeature",
          "text": "UIGuidedAccessAccessibilityFeature"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature/grayscaleDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGuidedAccessAccessibilityFeatureGrayscaleDisplay"
        }
      ],
      "role": "symbol",
      "title": "grayscaleDisplay",
      "type": "topic",
      "url": "/documentation/uikit/uiguidedaccessaccessibilityfeature/grayscaledisplay"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature/invertColors": {
      "abstract": [
        {
          "text": "The Smart Invert accessibility feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invertColors"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIGuidedAccessAccessibilityFeature",
          "text": "UIGuidedAccessAccessibilityFeature"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature/invertColors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGuidedAccessAccessibilityFeatureInvertColors"
        }
      ],
      "role": "symbol",
      "title": "invertColors",
      "type": "topic",
      "url": "/documentation/uikit/uiguidedaccessaccessibilityfeature/invertcolors"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature/voiceOver": {
      "abstract": [
        {
          "text": "The VoiceOver assistive app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voiceOver"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIGuidedAccessAccessibilityFeature",
          "text": "UIGuidedAccessAccessibilityFeature"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature/voiceOver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGuidedAccessAccessibilityFeatureVoiceOver"
        }
      ],
      "role": "symbol",
      "title": "voiceOver",
      "type": "topic",
      "url": "/documentation/uikit/uiguidedaccessaccessibilityfeature/voiceover"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature/zoom": {
      "abstract": [
        {
          "text": "The Zoom accessibility feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zoom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIGuidedAccessAccessibilityFeature",
          "text": "UIGuidedAccessAccessibilityFeature"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature/zoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGuidedAccessAccessibilityFeatureZoom"
        }
      ],
      "role": "symbol",
      "title": "zoom",
      "type": "topic",
      "url": "/documentation/uikit/uiguidedaccessaccessibilityfeature/zoom"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature/assistiveTouch",
        "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature/grayscaleDisplay",
        "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature/voiceOver",
        "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature/zoom"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIGuidedAccessAccessibilityFeatureInvertColors"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGuidedAccessAccessibilityFeatureInvertColors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature/assistiveTouch",
                "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature/grayscaleDisplay",
                "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature/voiceOver",
                "doc://com.apple.uikit/documentation/UIKit/UIGuidedAccessAccessibilityFeature/zoom"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIGuidedAccessAccessibilityFeatureInvertColors"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGuidedAccessAccessibilityFeature~1assistiveTouch/title",
          "value": "UIGuidedAccessAccessibilityFeatureAssistiveTouch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGuidedAccessAccessibilityFeature~1assistiveTouch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGuidedAccessAccessibilityFeatureAssistiveTouch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGuidedAccessAccessibilityFeature~1invertColors/title",
          "value": "UIGuidedAccessAccessibilityFeatureInvertColors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGuidedAccessAccessibilityFeature~1invertColors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGuidedAccessAccessibilityFeatureInvertColors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGuidedAccessAccessibilityFeature~1grayscaleDisplay/title",
          "value": "UIGuidedAccessAccessibilityFeatureGrayscaleDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGuidedAccessAccessibilityFeature~1grayscaleDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGuidedAccessAccessibilityFeatureGrayscaleDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGuidedAccessAccessibilityFeature~1voiceOver/title",
          "value": "UIGuidedAccessAccessibilityFeatureVoiceOver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGuidedAccessAccessibilityFeature~1voiceOver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGuidedAccessAccessibilityFeatureVoiceOver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGuidedAccessAccessibilityFeature/title",
          "value": "UIGuidedAccessAccessibilityFeature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGuidedAccessAccessibilityFeature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGuidedAccessAccessibilityFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGuidedAccessAccessibilityFeature/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGuidedAccessAccessibilityFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGuidedAccessAccessibilityFeature~1zoom/title",
          "value": "UIGuidedAccessAccessibilityFeatureZoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGuidedAccessAccessibilityFeature~1zoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGuidedAccessAccessibilityFeatureZoom"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiguidedaccessaccessibilityfeature/invertcolors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiguidedaccessaccessibilityfeature/invertcolors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
