{"metadata":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"label","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:objc(pl)MTLBinaryArchive(py)label","roleHeading":"Instance Property","title":"label","modules":[{"name":"Metal"}],"platforms":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"14.0"},{"name":"iPadOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"14.0"},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"14.0"},{"name":"macOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"11.0"},{"name":"tvOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"14.0"},{"name":"visionOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"1.0"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"label","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc://com.apple.metal/documentation/Metal/MTLBinaryArchive/label","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"label","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:SS","preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Object and command labels are useful identifiers at runtime or when profiling and debugging your app using any Metal tool. See "},{"type":"codeVoice","code":"Enhancing Frame Capture by Using Labels"},{"type":"text","text":"."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metal/documentation/Metal","doc://com.apple.metal/documentation/Metal/MTLBinaryArchive"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/metal/mtlbinaryarchive/label"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/metal/mtlbinaryarchive/label"]}],"abstract":[{"text":"A string that identifies the library.","type":"text"}],"seeAlsoSections":[{"title":"Identifying the Archive","identifiers":["doc://com.apple.metal/documentation/Metal/MTLBinaryArchive/device"],"anchor":"Identifying-the-Archive","generated":true}],"references":{"doc://com.apple.metal/documentation/Metal":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc://com.apple.metal/documentation/Metal","title":"Metal","abstract":[{"text":"Render advanced 3D graphics and compute data in parallel with graphics processors.","type":"text"}],"url":"/documentation/metal"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"role":"symbol","abstract":[{"type":"text","text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. "}],"fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSString"}],"kind":"symbol","title":"NSString","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","url":"/documentation/foundation/nsstring"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","kind":"technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"text":"","type":"text"}],"url":"/documentation/technologies"},"doc://com.apple.metal/documentation/Metal/MTLBinaryArchive":{"url":"/documentation/metal/mtlbinaryarchive","navigatorTitle":[{"text":"MTLBinaryArchive","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.metal/documentation/Metal/MTLBinaryArchive","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MTLBinaryArchive","kind":"identifier"}],"title":"MTLBinaryArchive","abstract":[{"text":"A container for pipeline state descriptors and their associated compiled shader code.","type":"text"}]},"doc://com.apple.metal/documentation/Metal/MTLBinaryArchive/device":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"device","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"MTLDevice","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MTLDevice"}],"kind":"symbol","identifier":"doc://com.apple.metal/documentation/Metal/MTLBinaryArchive/device","title":"device","type":"topic","abstract":[{"type":"text","text":"The Metal device object that created the binary archive."}],"navigatorTitle":[{"text":"device","kind":"identifier"}],"required":true,"url":"/documentation/metal/mtlbinaryarchive/device"},"doc://com.apple.metal/documentation/Metal/MTLBinaryArchive/label":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"label","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc://com.apple.metal/documentation/Metal/MTLBinaryArchive/label","title":"label","type":"topic","abstract":[{"type":"text","text":"A string that identifies the library."}],"navigatorTitle":[{"text":"label","kind":"identifier"}],"required":true,"url":"/documentation/metal/mtlbinaryarchive/label"},"doc://com.externally.resolved.symbol/s:SS":{"abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"kind":"symbol","url":"/documentation/Swift/String","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SS","title":"String","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"introducedAt":"14.0","beta":false,"name":"iOS","deprecated":false},{"unavailable":false,"introducedAt":"14.0","beta":false,"name":"iPadOS","deprecated":false},{"unavailable":false,"introducedAt":"14.0","beta":false,"name":"Mac Catalyst","deprecated":false},{"name":"macOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"11.0"},{"name":"tvOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"name":"visionOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"1.0"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"label","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"label","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metal/documentation/Metal","doc://com.apple.metal/documentation/Metal/MTLBinaryArchive"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"anchor":"Identifying-the-Archive","identifiers":["doc://com.apple.metal/documentation/Metal/MTLBinaryArchive/device"],"title":"Identifying the Archive"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"atomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"label","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]}},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","value":[{"text":"A static, plain-text Unicode string object.","type":"text"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinaryArchive/title","value":"MTLBinaryArchive"},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinaryArchive/fragments","value":[{"text":"MTLBinaryArchive","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinaryArchive/navigatorTitle","value":[{"kind":"identifier","text":"MTLBinaryArchive"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinaryArchive~1device/title","value":"device"},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinaryArchive~1device/fragments","value":[{"text":"device","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinaryArchive~1label/title","value":"label"},{"op":"replace","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinaryArchive~1label/fragments","value":[{"text":"label","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}