{
  "abstract": [
    {
      "text": "A sigmoid curve.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE",
        "doc://com.apple.phase/documentation/PHASE/PHASECurveType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/PHASECurveType/sigmoid"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHASECurveType@PHASECurveTypeSigmoid",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sigmoid"
      }
    ],
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHASECurveTypeSigmoid"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PHASECurveType.sigmoid"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sigmoid"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Also known as an ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "s-curve",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", the sigmoid curve’s path movement is slow at either end and quick in the middle.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECurveType": {
      "abstract": [
        {
          "text": "Options that apply a mathematical function to an input value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASECurveType"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECurveType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECurveType"
        }
      ],
      "role": "symbol",
      "title": "PHASECurveType",
      "type": "topic",
      "url": "/documentation/phase/phasecurvetype"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECurveType/cubed": {
      "abstract": [
        {
          "text": "A curve that increases at a rate that cubes its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cubed"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECurveType/cubed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECurveTypeCubed"
        }
      ],
      "role": "symbol",
      "title": "PHASECurveType.cubed",
      "type": "topic",
      "url": "/documentation/phase/phasecurvetype/cubed"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECurveType/holdStartValue": {
      "abstract": [
        {
          "text": "A curve that equals its start value for the entire duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "holdStartValue"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECurveType/holdStartValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECurveTypeHoldStartValue"
        }
      ],
      "role": "symbol",
      "title": "PHASECurveType.holdStartValue",
      "type": "topic",
      "url": "/documentation/phase/phasecurvetype/holdstartvalue"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECurveType/inverseCubed": {
      "abstract": [
        {
          "text": "A curve that increases at a rate of one divided by the input’s cube.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inverseCubed"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECurveType/inverseCubed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECurveTypeInverseCubed"
        }
      ],
      "role": "symbol",
      "title": "PHASECurveType.inverseCubed",
      "type": "topic",
      "url": "/documentation/phase/phasecurvetype/inversecubed"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECurveType/inverseSigmoid": {
      "abstract": [
        {
          "text": "An inverse sigmoid curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inverseSigmoid"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECurveType/inverseSigmoid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECurveTypeInverseSigmoid"
        }
      ],
      "role": "symbol",
      "title": "PHASECurveType.inverseSigmoid",
      "type": "topic",
      "url": "/documentation/phase/phasecurvetype/inversesigmoid"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECurveType/inverseSine": {
      "abstract": [
        {
          "text": "An inverse sine curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inverseSine"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECurveType/inverseSine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECurveTypeInverseSine"
        }
      ],
      "role": "symbol",
      "title": "PHASECurveType.inverseSine",
      "type": "topic",
      "url": "/documentation/phase/phasecurvetype/inversesine"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECurveType/inverseSquared": {
      "abstract": [
        {
          "text": "A curve that increases at a rate of one divided by the input’s square.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inverseSquared"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECurveType/inverseSquared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECurveTypeInverseSquared"
        }
      ],
      "role": "symbol",
      "title": "PHASECurveType.inverseSquared",
      "type": "topic",
      "url": "/documentation/phase/phasecurvetype/inversesquared"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECurveType/jumpToEndValue": {
      "abstract": [
        {
          "text": "A curve that equals its end value for the entire duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jumpToEndValue"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECurveType/jumpToEndValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECurveTypeJumpToEndValue"
        }
      ],
      "role": "symbol",
      "title": "PHASECurveType.jumpToEndValue",
      "type": "topic",
      "url": "/documentation/phase/phasecurvetype/jumptoendvalue"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECurveType/linear": {
      "abstract": [
        {
          "text": "A curve that increases uniformly with its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linear"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECurveType/linear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECurveTypeLinear"
        }
      ],
      "role": "symbol",
      "title": "PHASECurveType.linear",
      "type": "topic",
      "url": "/documentation/phase/phasecurvetype/linear"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECurveType/sigmoid": {
      "abstract": [
        {
          "text": "A sigmoid curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sigmoid"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECurveType/sigmoid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECurveTypeSigmoid"
        }
      ],
      "role": "symbol",
      "title": "PHASECurveType.sigmoid",
      "type": "topic",
      "url": "/documentation/phase/phasecurvetype/sigmoid"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECurveType/sine": {
      "abstract": [
        {
          "text": "A sine curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sine"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECurveType/sine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECurveTypeSine"
        }
      ],
      "role": "symbol",
      "title": "PHASECurveType.sine",
      "type": "topic",
      "url": "/documentation/phase/phasecurvetype/sine"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASECurveType/squared": {
      "abstract": [
        {
          "text": "A curve that increases at a rate that squares its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "squared"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASECurveType/squared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASECurveTypeSquared"
        }
      ],
      "role": "symbol",
      "title": "PHASECurveType.squared",
      "type": "topic",
      "url": "/documentation/phase/phasecurvetype/squared"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASECurveType/linear",
        "doc://com.apple.phase/documentation/PHASE/PHASECurveType/squared",
        "doc://com.apple.phase/documentation/PHASE/PHASECurveType/inverseSquared",
        "doc://com.apple.phase/documentation/PHASE/PHASECurveType/cubed",
        "doc://com.apple.phase/documentation/PHASE/PHASECurveType/inverseCubed",
        "doc://com.apple.phase/documentation/PHASE/PHASECurveType/sine",
        "doc://com.apple.phase/documentation/PHASE/PHASECurveType/inverseSine",
        "doc://com.apple.phase/documentation/PHASE/PHASECurveType/inverseSigmoid",
        "doc://com.apple.phase/documentation/PHASE/PHASECurveType/holdStartValue",
        "doc://com.apple.phase/documentation/PHASE/PHASECurveType/jumpToEndValue"
      ],
      "title": "Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHASECurveTypeSigmoid"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECurveTypeSigmoid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.phase/documentation/PHASE",
                "doc://com.apple.phase/documentation/PHASE/PHASECurveType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASECurveType/linear",
                "doc://com.apple.phase/documentation/PHASE/PHASECurveType/squared",
                "doc://com.apple.phase/documentation/PHASE/PHASECurveType/inverseSquared",
                "doc://com.apple.phase/documentation/PHASE/PHASECurveType/cubed",
                "doc://com.apple.phase/documentation/PHASE/PHASECurveType/inverseCubed",
                "doc://com.apple.phase/documentation/PHASE/PHASECurveType/sine",
                "doc://com.apple.phase/documentation/PHASE/PHASECurveType/inverseSine",
                "doc://com.apple.phase/documentation/PHASE/PHASECurveType/inverseSigmoid",
                "doc://com.apple.phase/documentation/PHASE/PHASECurveType/holdStartValue",
                "doc://com.apple.phase/documentation/PHASE/PHASECurveType/jumpToEndValue"
              ],
              "title": "Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PHASECurveTypeSigmoid"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType/title",
          "value": "PHASECurveType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECurveType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECurveType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1inverseSigmoid/title",
          "value": "PHASECurveTypeInverseSigmoid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1inverseSigmoid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECurveTypeInverseSigmoid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1inverseCubed/title",
          "value": "PHASECurveTypeInverseCubed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1inverseCubed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECurveTypeInverseCubed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1holdStartValue/title",
          "value": "PHASECurveTypeHoldStartValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1holdStartValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECurveTypeHoldStartValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1inverseSquared/title",
          "value": "PHASECurveTypeInverseSquared"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1inverseSquared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECurveTypeInverseSquared"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1jumpToEndValue/title",
          "value": "PHASECurveTypeJumpToEndValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1jumpToEndValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECurveTypeJumpToEndValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1linear/title",
          "value": "PHASECurveTypeLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1linear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECurveTypeLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1sine/title",
          "value": "PHASECurveTypeSine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1sine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECurveTypeSine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1inverseSine/title",
          "value": "PHASECurveTypeInverseSine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1inverseSine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECurveTypeInverseSine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1squared/title",
          "value": "PHASECurveTypeSquared"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1squared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECurveTypeSquared"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1sigmoid/title",
          "value": "PHASECurveTypeSigmoid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1sigmoid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECurveTypeSigmoid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1cubed/title",
          "value": "PHASECurveTypeCubed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASECurveType~1cubed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASECurveTypeCubed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/phasecurvetype/sigmoid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/phase/phasecurvetype/sigmoid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
