{"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIButtonRole","identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/Role-swift.enum","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIButtonRole"},{"text":" ","kind":"text"},{"text":"role","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["/documentation/uikit/uicontentunavailablebuttonproperties/role"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","fragments":[{"text":"role","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","title":"role","platforms":[{"deprecated":false,"introducedAt":"17.0","beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"introducedAt":"17.0","beta":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"introducedAt":"17.0","beta":false,"name":"Mac Catalyst","unavailable":false},{"deprecated":false,"introducedAt":"17.0","beta":false,"name":"tvOS","unavailable":false},{"deprecated":false,"introducedAt":"1.0","beta":false,"name":"visionOS","unavailable":false}],"navigatorTitle":[{"text":"role","kind":"identifier"}],"modules":[{"name":"UIKit"}],"externalID":"c:objc(cs)UIContentUnavailableButtonProperties(py)role"},"sections":[],"abstract":[{"type":"text","text":"The role of the button."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableButtonProperties/role","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableButtonProperties"]]},"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIButton/Role-swift.enum":{"role":"symbol","navigatorTitle":[{"text":"Role","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Role","kind":"identifier"}],"kind":"symbol","title":"UIButton.Role","url":"/documentation/uikit/uibutton/role-swift.enum","abstract":[{"text":"Constants that describe the role of the button.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIButton/Role-swift.enum"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableButtonProperties/role":{"role":"symbol","title":"role","abstract":[{"type":"text","text":"The role of the button."}],"fragments":[{"text":"role","kind":"identifier"}],"url":"/documentation/uikit/uicontentunavailablebuttonproperties/role","kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableButtonProperties/role"},"doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableButtonProperties":{"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableButtonProperties","title":"UIContentUnavailableButtonProperties","url":"/documentation/uikit/uicontentunavailablebuttonproperties","role":"symbol","abstract":[{"text":"Properties configuring the appearance and behavior of a button in a content-unavailable view.","type":"text"}],"type":"topic","fragments":[{"text":"UIContentUnavailableButtonProperties","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1Role-swift.enum/title","value":"UIButtonRole"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1Role-swift.enum/fragments","value":[{"text":"UIButtonRole","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1Role-swift.enum/navigatorTitle","value":[{"kind":"identifier","text":"UIButtonRole"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}