{
  "abstract": [
    {
      "text": "Creates a menu with the specified title and child menu elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIMenu"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIMenu/menuWithTitle:children:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIMenu(cm)menuWithTitle:children:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "menuWithTitle:children:"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "menuWithTitle:children:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "menuWithTitle:children:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenu",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIMenu",
              "text": "UIMenu"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "menuWithTitle:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "title"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "children:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<UIMenuElement *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "children"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The title of the menu.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "title"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The menu elements in the menu. Specify leaf menu elements using ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenuElement",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " subclasses like ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAction",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UICommand",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", and specify submenus using ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenu",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " objects. You may specify an empty array if the menu has no child menu elements.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "children"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new menu object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method creates a unique identifier for the menu and exposes that value from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenu/identifier-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAction": {
      "abstract": [
        {
          "text": "A menu element that performs its action in a closure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAction"
        }
      ],
      "role": "symbol",
      "title": "UIAction",
      "type": "topic",
      "url": "/documentation/uikit/uiaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICommand": {
      "abstract": [
        {
          "text": "A menu element that performs its action in a selector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICommand"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICommand"
        }
      ],
      "role": "symbol",
      "title": "UICommand",
      "type": "topic",
      "url": "/documentation/uikit/uicommand"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand": {
      "abstract": [
        {
          "text": "An object that specifies a key press perform on a hardware keyboard and the resulting action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIKeyCommand"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyCommand"
        }
      ],
      "role": "symbol",
      "title": "UIKeyCommand",
      "type": "topic",
      "url": "/documentation/uikit/uikeycommand"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMenu": {
      "abstract": [
        {
          "text": "A container for grouping related menu elements in an app menu or contextual menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMenu"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMenu"
        }
      ],
      "role": "symbol",
      "title": "UIMenu",
      "type": "topic",
      "url": "/documentation/uikit/uimenu"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMenu/Identifier-swift.struct": {
      "abstract": [
        {
          "text": "Constants you use to identify an app’s standard menus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Identifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenu/Identifier-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Identifier"
        }
      ],
      "role": "symbol",
      "title": "UIMenu.Identifier",
      "type": "topic",
      "url": "/documentation/uikit/uimenu/identifier-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMenu/Options-swift.struct": {
      "abstract": [
        {
          "text": "Options you use to configure a menu’s appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenu/Options-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "role": "symbol",
      "title": "UIMenu.Options",
      "type": "topic",
      "url": "/documentation/uikit/uimenu/options-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMenu/identifier-swift.property": {
      "abstract": [
        {
          "text": "The unique identifier for the current menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIMenu",
          "text": "UIMenu"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIMenuIdentifier",
          "text": "Identifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenu/identifier-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/uikit/uimenu/identifier-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMenu/init(coder:)": {
      "abstract": [
        {
          "text": "Creates a menu from data in an unarchiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenu/init(coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/uikit/uimenu/init(coder:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMenu/menuWithChildren:": {
      "abstract": [
        {
          "text": "Creates a new menu with the specified child elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "menuWithChildren:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenu/menuWithChildren:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "menuWithChildren:"
        }
      ],
      "role": "symbol",
      "title": "menuWithChildren:",
      "type": "topic",
      "url": "/documentation/uikit/uimenu/menuwithchildren:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMenu/menuWithTitle:children:": {
      "abstract": [
        {
          "text": "Creates a menu with the specified title and child menu elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "menuWithTitle:children:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenu/menuWithTitle:children:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "menuWithTitle:children:"
        }
      ],
      "role": "symbol",
      "title": "menuWithTitle:children:",
      "type": "topic",
      "url": "/documentation/uikit/uimenu/menuwithtitle:children:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMenu/menuWithTitle:image:identifier:options:children:": {
      "abstract": [
        {
          "text": "Creates a new menu with the specified values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "menuWithTitle:image:identifier:options:children:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenu/menuWithTitle:image:identifier:options:children:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "menuWithTitle:image:identifier:options:children:"
        }
      ],
      "role": "symbol",
      "title": "menuWithTitle:image:identifier:options:children:",
      "type": "topic",
      "url": "/documentation/uikit/uimenu/menuwithtitle:image:identifier:options:children:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMenuElement": {
      "abstract": [
        {
          "text": "An object representing a menu, action, or command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMenuElement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenuElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMenuElement"
        }
      ],
      "role": "symbol",
      "title": "UIMenuElement",
      "type": "topic",
      "url": "/documentation/uikit/uimenuelement"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-menu-object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIMenu/menuWithChildren:",
        "doc://com.apple.uikit/documentation/UIKit/UIMenu/menuWithTitle:image:identifier:options:children:",
        "doc://com.apple.uikit/documentation/UIKit/UIMenu/Identifier-swift.struct",
        "doc://com.apple.uikit/documentation/UIKit/UIMenu/Options-swift.struct",
        "doc://com.apple.uikit/documentation/UIKit/UIMenu/init(coder:)"
      ],
      "title": "Creating a menu object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuElement/title",
          "value": "UIMenuElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMenuElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMenuElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICommand/title",
          "value": "UICommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenu~1identifier-swift.property/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenu~1identifier-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenu/title",
          "value": "UIMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenu/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenu~1Identifier-swift.struct/title",
          "value": "UIMenuIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenu~1Identifier-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMenuIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenu~1Identifier-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMenuIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenu~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenu~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand/title",
          "value": "UIKeyCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenu~1Options-swift.struct/title",
          "value": "UIMenuOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenu~1Options-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMenuOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenu~1Options-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMenuOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAction/title",
          "value": "UIAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uimenu/menuwithtitle:children:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
