{
  "abstract": [
    {
      "text": "The starting time of the reporting period.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metrickit/documentation/MetricKit",
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/timeStampBegin"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MXDiagnosticPayload(py)timeStampBegin",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "timeStampBegin"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation4DateV",
        "text": "Date"
      }
    ],
    "modules": [
      {
        "name": "MetricKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "timeStampBegin"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "timeStampBegin"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "timeStampBegin"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DateV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4DateV",
              "text": "Date"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metrickit/documentation/MetricKit": {
      "abstract": [
        {
          "text": "Aggregate and analyze per-device reports on exception and crash diagnostics and on power and performance metrics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetricKit",
      "type": "topic",
      "url": "/documentation/metrickit"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload": {
      "abstract": [
        {
          "text": "An object that encapsulates a diagnostic report.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXDiagnosticPayload"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXDiagnosticPayload"
        }
      ],
      "role": "symbol",
      "title": "MXDiagnosticPayload",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiagnosticpayload"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/timeStampBegin": {
      "abstract": [
        {
          "text": "The starting time of the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeStampBegin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/timeStampBegin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeStampBegin"
        }
      ],
      "role": "symbol",
      "title": "timeStampBegin",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiagnosticpayload/timestampbegin"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/timeStampEnd": {
      "abstract": [
        {
          "text": "The ending time of the reporting period.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeStampEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/timeStampEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeStampEnd"
        }
      ],
      "role": "symbol",
      "title": "timeStampEnd",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiagnosticpayload/timestampend"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation4DateV": {
      "abstract": [
        {
          "text": "A specific point in time, independent of any calendar or time zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DateV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Date",
      "type": "topic",
      "url": "/documentation/foundation/date"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reading-information-about-the-payload",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/timeStampEnd"
      ],
      "title": "Reading information about the payload"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "timeStampBegin"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeStampBegin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metrickit/documentation/MetricKit",
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reading-information-about-the-payload",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnosticPayload/timeStampEnd"
              ],
              "title": "Reading information about the payload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSDate",
                    "text": "NSDate"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "timeStampBegin"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1timeStampBegin/title",
          "value": "timeStampBegin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1timeStampBegin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeStampBegin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1timeStampEnd/title",
          "value": "timeStampEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload~1timeStampEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeStampEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload/title",
          "value": "MXDiagnosticPayload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiagnosticPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnosticPayload/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiagnosticPayload"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metrickit/mxdiagnosticpayload/timestampbegin"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metrickit/mxdiagnosticpayload/timestampbegin"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
