{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialAssertion"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialAssertion/prf-8o9sr"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AuthenticationServices",
    "externalID": "s:So51ASAuthorizationPlatformPublicKeyCredentialAssertionC22AuthenticationServicesE3prfAC0acdE18PRFAssertionOutputVSgvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "prf"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:22AuthenticationServices52ASAuthorizationPublicKeyCredentialPRFAssertionOutputV",
        "text": "ASAuthorizationPublicKeyCredentialPRFAssertionOutput"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Authentication Services"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "prf"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "prf"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialPRFAssertionOutput-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:22AuthenticationServices52ASAuthorizationPublicKeyCredentialPRFAssertionOutputV",
              "text": "ASAuthorizationPublicKeyCredentialPRFAssertionOutput"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices": {
      "abstract": [
        {
          "text": "Make it easy for users to log into apps and services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Authentication Services",
      "type": "topic",
      "url": "/documentation/authenticationservices"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialAssertion": {
      "abstract": [
        {
          "text": "A class that represents the platform credential assertion type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAuthorizationPlatformPublicKeyCredentialAssertion"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialAssertion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationPlatformPublicKeyCredentialAssertion"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationPlatformPublicKeyCredentialAssertion",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationplatformpublickeycredentialassertion"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialAssertion/prf-8o9sr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22AuthenticationServices52ASAuthorizationPublicKeyCredentialPRFAssertionOutputV",
          "text": "ASAuthorizationPublicKeyCredentialPRFAssertionOutput"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPlatformPublicKeyCredentialAssertion/prf-8o9sr",
      "kind": "symbol",
      "role": "symbol",
      "title": "prf",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationplatformpublickeycredentialassertion/prf-8o9sr"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialPRFAssertionOutput-swift.struct": {
      "abstract": [
        {
          "text": "The outputs of the WebAuthentication PRF extension, when requested during an assertion. This object represents one or two SymmetricKeys which are available anywhere the passkey can be used.",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "These are general purpose keys which can be used for application-specific needs, such as encryption of user data.",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "These keys should not be stored or exported. They should only ever be derived as the result of an assertion operation, and then discarded when finished.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAuthorizationPublicKeyCredentialPRFAssertionOutput"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationPublicKeyCredentialPRFAssertionOutput-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationPublicKeyCredentialPRFAssertionOutput"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationPublicKeyCredentialPRFAssertionOutput",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationpublickeycredentialprfassertionoutput-swift.struct"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialAssertion/title",
          "value": "ASAuthorizationPlatformPublicKeyCredentialAssertion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialAssertion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationPlatformPublicKeyCredentialAssertion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationPlatformPublicKeyCredentialAssertion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationPlatformPublicKeyCredentialAssertion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/authenticationservices/asauthorizationplatformpublickeycredentialassertion/prf-8o9sr"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
