{
  "abstract": [
    {
      "text": "An external device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/externalDevice"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MIDIObjectType@kMIDIObjectType_ExternalDevice",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "externalDevice"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMIDIObjectType_ExternalDevice"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MIDIObjectType.externalDevice"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "externalDevice"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType": {
      "abstract": [
        {
          "text": "The MIDI object types that the system supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIObjectType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIObjectType"
        }
      ],
      "role": "symbol",
      "title": "MIDIObjectType",
      "type": "topic",
      "url": "/documentation/coremidi/midiobjecttype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/destination": {
      "abstract": [
        {
          "text": "A MIDI destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destination"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/destination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIObjectType_Destination"
        }
      ],
      "role": "symbol",
      "title": "MIDIObjectType.destination",
      "type": "topic",
      "url": "/documentation/coremidi/midiobjecttype/destination"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/device": {
      "abstract": [
        {
          "text": "A MIDI device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "device"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/device",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIObjectType_Device"
        }
      ],
      "role": "symbol",
      "title": "MIDIObjectType.device",
      "type": "topic",
      "url": "/documentation/coremidi/midiobjecttype/device"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/entity": {
      "abstract": [
        {
          "text": "A MIDI entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "entity"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/entity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIObjectType_Entity"
        }
      ],
      "role": "symbol",
      "title": "MIDIObjectType.entity",
      "type": "topic",
      "url": "/documentation/coremidi/midiobjecttype/entity"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/externalDestination": {
      "abstract": [
        {
          "text": "An external destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "externalDestination"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/externalDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIObjectType_ExternalDestination"
        }
      ],
      "role": "symbol",
      "title": "MIDIObjectType.externalDestination",
      "type": "topic",
      "url": "/documentation/coremidi/midiobjecttype/externaldestination"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/externalDevice": {
      "abstract": [
        {
          "text": "An external device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "externalDevice"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/externalDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIObjectType_ExternalDevice"
        }
      ],
      "role": "symbol",
      "title": "MIDIObjectType.externalDevice",
      "type": "topic",
      "url": "/documentation/coremidi/midiobjecttype/externaldevice"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/externalEntity": {
      "abstract": [
        {
          "text": "An external entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "externalEntity"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/externalEntity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIObjectType_ExternalEntity"
        }
      ],
      "role": "symbol",
      "title": "MIDIObjectType.externalEntity",
      "type": "topic",
      "url": "/documentation/coremidi/midiobjecttype/externalentity"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/externalSource": {
      "abstract": [
        {
          "text": "An external source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "externalSource"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/externalSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIObjectType_ExternalSource"
        }
      ],
      "role": "symbol",
      "title": "MIDIObjectType.externalSource",
      "type": "topic",
      "url": "/documentation/coremidi/midiobjecttype/externalsource"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/other": {
      "abstract": [
        {
          "text": "A MIDI object with an undefined type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIObjectType_Other"
        }
      ],
      "role": "symbol",
      "title": "MIDIObjectType.other",
      "type": "topic",
      "url": "/documentation/coremidi/midiobjecttype/other"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/source": {
      "abstract": [
        {
          "text": "A MIDI source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "source"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/source",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIObjectType_Source"
        }
      ],
      "role": "symbol",
      "title": "MIDIObjectType.source",
      "type": "topic",
      "url": "/documentation/coremidi/midiobjecttype/source"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIObjectType_ExternalMask": {
      "abstract": [
        {
          "text": "A bit mask indicating that a device is external.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIObjectType_ExternalMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MIDIObjectType",
          "text": "MIDIObjectType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIObjectType_ExternalMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIObjectType_ExternalMask"
        }
      ],
      "role": "symbol",
      "title": "kMIDIObjectType_ExternalMask",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiobjecttype_externalmask"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Object-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/other",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/device",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/entity",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/source",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/destination",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/externalEntity",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/externalSource",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/externalDestination",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIObjectType_ExternalMask"
      ],
      "title": "Object Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMIDIObjectType_ExternalDevice"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIObjectType_ExternalDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Object-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/other",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/device",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/entity",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/source",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/destination",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/externalEntity",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/externalSource",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType/externalDestination",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIObjectType_ExternalMask"
              ],
              "title": "Object Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kMIDIObjectType_ExternalDevice"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType~1device/title",
          "value": "kMIDIObjectType_Device"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType~1device/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIObjectType_Device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType~1externalDevice/title",
          "value": "kMIDIObjectType_ExternalDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType~1externalDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIObjectType_ExternalDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType~1source/title",
          "value": "kMIDIObjectType_Source"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType~1source/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIObjectType_Source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType~1destination/title",
          "value": "kMIDIObjectType_Destination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType~1destination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIObjectType_Destination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType~1other/title",
          "value": "kMIDIObjectType_Other"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIObjectType_Other"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType~1externalDestination/title",
          "value": "kMIDIObjectType_ExternalDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType~1externalDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIObjectType_ExternalDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType/title",
          "value": "MIDIObjectType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIObjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIObjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType~1entity/title",
          "value": "kMIDIObjectType_Entity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType~1entity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIObjectType_Entity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIObjectType_ExternalMask/title",
          "value": "kMIDIObjectType_ExternalMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIObjectType_ExternalMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIObjectType_ExternalMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType~1externalEntity/title",
          "value": "kMIDIObjectType_ExternalEntity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType~1externalEntity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIObjectType_ExternalEntity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType~1externalSource/title",
          "value": "kMIDIObjectType_ExternalSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType~1externalSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIObjectType_ExternalSource"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midiobjecttype/externaldevice"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midiobjecttype/externaldevice"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
