{
  "abstract": [
    {
      "text": "The system can’t complete the requested operation because the connection timed out.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit",
        "doc://com.apple.gamekit/documentation/GameKit/GKError",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/connectionTimeout"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@GKErrorCode@GKErrorConnectionTimeout",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "connectionTimeout"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKErrorConnectionTimeout"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "GKError.Code.connectionTimeout"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "connectionTimeout"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError": {
      "abstract": [
        {
          "text": "The error structure used by this framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKError"
        }
      ],
      "role": "symbol",
      "title": "GKError",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code": {
      "abstract": [
        {
          "text": "Error codes for the GameKit error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/apiNotAvailable": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the API isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apiNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/apiNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorAPINotAvailable"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.apiNotAvailable",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/apinotavailable"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/apiObsolete": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because Apple deprecated the API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apiObsolete"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/apiObsolete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorAPIObsolete"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.apiObsolete",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/apiobsolete"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/cancelled": {
      "abstract": [
        {
          "text": "The system canceled the requested operation or the user disabled it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorCancelled"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.cancelled",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/cancelled"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/communicationsFailure": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation due to an error communicating with the server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "communicationsFailure"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/communicationsFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorCommunicationsFailure"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.communicationsFailure",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/communicationsfailure"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/connectionTimeout": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the connection timed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionTimeout"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/connectionTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorConnectionTimeout"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.connectionTimeout",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/connectiontimeout"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/gameSessionRequestInvalid": {
      "abstract": [
        {
          "text": "The properties of the game session request are impossible to fulfill.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gameSessionRequestInvalid"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/gameSessionRequestInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorGameSessionRequestInvalid"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.gameSessionRequestInvalid",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/gamesessionrequestinvalid"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidParameter": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because one or more parameters are invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameter"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorInvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.invalidParameter",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/invalidparameter"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidPlayer": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the player is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPlayer"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorInvalidPlayer"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.invalidPlayer",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/invalidplayer"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/unknown": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation due to an unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.unknown",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Communication-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/unknown",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/cancelled",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/communicationsFailure",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidPlayer",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidParameter",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/gameSessionRequestInvalid",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/apiNotAvailable",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/apiObsolete"
      ],
      "title": "Communication Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKErrorConnectionTimeout"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorConnectionTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Communication-Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/unknown",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/cancelled",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/communicationsFailure",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidPlayer",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidParameter",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/gameSessionRequestInvalid",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/apiNotAvailable",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/apiObsolete"
              ],
              "title": "Communication Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "GKErrorConnectionTimeout"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1apiObsolete/title",
          "value": "GKErrorAPIObsolete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1apiObsolete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorAPIObsolete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1gameSessionRequestInvalid/title",
          "value": "GKErrorGameSessionRequestInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1gameSessionRequestInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorGameSessionRequestInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1communicationsFailure/title",
          "value": "GKErrorCommunicationsFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1communicationsFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorCommunicationsFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1cancelled/title",
          "value": "GKErrorCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1unknown/title",
          "value": "GKErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1invalidPlayer/title",
          "value": "GKErrorInvalidPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1invalidPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorInvalidPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1connectionTimeout/title",
          "value": "GKErrorConnectionTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1connectionTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorConnectionTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code/title",
          "value": "GKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1apiNotAvailable/title",
          "value": "GKErrorAPINotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1apiNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorAPINotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1invalidParameter/title",
          "value": "GKErrorInvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1invalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorInvalidParameter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkerror/code/connectiontimeout"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gkerror/code/connectiontimeout"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
