{
  "abstract": [
    {
      "text": "The system can’t complete the requested operation because the player enabled Lockdown Mode on the device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit",
        "doc://com.apple.gamekit/documentation/GameKit/GKError",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/lockdownMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@GKErrorCode@GKErrorLockdownMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "lockdownMode"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKErrorLockdownMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.1",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "GKError.Code.lockdownMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "lockdownMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about Lockdown Mode, see ",
              "type": "text"
            },
            {
              "identifier": "https://support.apple.com/en-us/HT212650",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError": {
      "abstract": [
        {
          "text": "The error structure used by this framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKError"
        }
      ],
      "role": "symbol",
      "title": "GKError",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code": {
      "abstract": [
        {
          "text": "Error codes for the GameKit error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/authenticationInProgress": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the local player is already authenticating.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authenticationInProgress"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/authenticationInProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorAuthenticationInProgress"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.authenticationInProgress",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/authenticationinprogress"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/iCloudUnavailable": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because it can’t access the player’s iCloud account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iCloudUnavailable"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/iCloudUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorICloudUnavailable"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.iCloudUnavailable",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/icloudunavailable"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidCredentials": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the user name or password are incorrect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidCredentials"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorInvalidCredentials"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.invalidCredentials",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/invalidcredentials"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/lockdownMode": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the player enabled Lockdown Mode on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lockdownMode"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/lockdownMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorLockdownMode"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.lockdownMode",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/lockdownmode"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notAuthenticated": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the system hasn’t authorized the player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthenticated"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notAuthenticated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorNotAuthenticated"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.notAuthenticated",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/notauthenticated"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notAuthorized": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the system hasn’t authorized the player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthorized"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notAuthorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorNotAuthorized"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.notAuthorized",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/notauthorized"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/parentalControlsBlocked": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the user disabled this feature in Restrictions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parentalControlsBlocked"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/parentalControlsBlocked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorParentalControlsBlocked"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.parentalControlsBlocked",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/parentalcontrolsblocked"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerPhotoFailure": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation to retrieve a player’s photo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerPhotoFailure"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerPhotoFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorPlayerPhotoFailure"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.playerPhotoFailure",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/playerphotofailure"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerStatusExceedsMaximumLength": {
      "abstract": [
        {
          "text": "The player’s status exceeds the maximum length.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerStatusExceedsMaximumLength"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerStatusExceedsMaximumLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorPlayerStatusExceedsMaximumLength"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.playerStatusExceedsMaximumLength",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/playerstatusexceedsmaximumlength"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerStatusInvalid": {
      "abstract": [
        {
          "text": "The player’s status is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerStatusInvalid"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerStatusInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorPlayerStatusInvalid"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.playerStatusInvalid",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/playerstatusinvalid"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/ubiquityContainerUnavailable": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the user hasn’t signed in to iCloud or hasn’t enabled iCloud Drive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ubiquityContainerUnavailable"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/ubiquityContainerUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorUbiquityContainerUnavailable"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.ubiquityContainerUnavailable",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/ubiquitycontainerunavailable"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/underage": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because this feature isn’t available to underage players.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "underage"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/underage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorUnderage"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.underage",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/underage"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/userDenied": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the user denied it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userDenied"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/userDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorUserDenied"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.userDenied",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/userdenied"
    },
    "https://support.apple.com/en-us/HT212650": {
      "identifier": "https://support.apple.com/en-us/HT212650",
      "title": "About Lockdown Mode",
      "titleInlineContent": [
        {
          "text": "About Lockdown Mode",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/en-us/HT212650"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Player-Related-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/userDenied",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidCredentials",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notAuthenticated",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/authenticationInProgress",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/parentalControlsBlocked",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerStatusExceedsMaximumLength",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerStatusInvalid",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/underage",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerPhotoFailure",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/ubiquityContainerUnavailable",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notAuthorized",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/iCloudUnavailable"
      ],
      "title": "Player-Related Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.2",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.1",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKErrorLockdownMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorLockdownMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Player-Related-Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/userDenied",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invalidCredentials",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notAuthenticated",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/authenticationInProgress",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/parentalControlsBlocked",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerStatusExceedsMaximumLength",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerStatusInvalid",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/underage",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/playerPhotoFailure",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/ubiquityContainerUnavailable",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/notAuthorized",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/iCloudUnavailable"
              ],
              "title": "Player-Related Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "GKErrorLockdownMode"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1ubiquityContainerUnavailable/title",
          "value": "GKErrorUbiquityContainerUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1ubiquityContainerUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorUbiquityContainerUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1lockdownMode/title",
          "value": "GKErrorLockdownMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1lockdownMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorLockdownMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1parentalControlsBlocked/title",
          "value": "GKErrorParentalControlsBlocked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1parentalControlsBlocked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorParentalControlsBlocked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code/title",
          "value": "GKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1authenticationInProgress/title",
          "value": "GKErrorAuthenticationInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1authenticationInProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorAuthenticationInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1underage/title",
          "value": "GKErrorUnderage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1underage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorUnderage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1invalidCredentials/title",
          "value": "GKErrorInvalidCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1invalidCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorInvalidCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1notAuthenticated/title",
          "value": "GKErrorNotAuthenticated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1notAuthenticated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorNotAuthenticated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1playerPhotoFailure/title",
          "value": "GKErrorPlayerPhotoFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1playerPhotoFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorPlayerPhotoFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1notAuthorized/title",
          "value": "GKErrorNotAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1notAuthorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorNotAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1playerStatusInvalid/title",
          "value": "GKErrorPlayerStatusInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1playerStatusInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorPlayerStatusInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1playerStatusExceedsMaximumLength/title",
          "value": "GKErrorPlayerStatusExceedsMaximumLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1playerStatusExceedsMaximumLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorPlayerStatusExceedsMaximumLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1userDenied/title",
          "value": "GKErrorUserDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1userDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorUserDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1iCloudUnavailable/title",
          "value": "GKErrorICloudUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1iCloudUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorICloudUnavailable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkerror/code/lockdownmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gkerror/code/lockdownmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
