{
  "abstract": [
    {
      "text": "The system can’t complete the requested operation because the match request is invalid.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit",
        "doc://com.apple.gamekit/documentation/GameKit/GKError",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/matchRequestInvalid"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@GKErrorCode@GKErrorMatchRequestInvalid",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "matchRequestInvalid"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKErrorMatchRequestInvalid"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "GKError.Code.matchRequestInvalid"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "matchRequestInvalid"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError": {
      "abstract": [
        {
          "text": "The error structure used by this framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKError"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKError"
        }
      ],
      "role": "symbol",
      "title": "GKError",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code": {
      "abstract": [
        {
          "text": "Error codes for the GameKit error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invitationsDisabled": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the receiving player has disabled invitations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invitationsDisabled"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invitationsDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorInvitationsDisabled"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.invitationsDisabled",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/invitationsdisabled"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/matchNotConnected": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the match isn’t connected to other players.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchNotConnected"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/matchNotConnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorMatchNotConnected"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.matchNotConnected",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/matchnotconnected"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/matchRequestInvalid": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the match request is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchRequestInvalid"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/matchRequestInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorMatchRequestInvalid"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.matchRequestInvalid",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/matchrequestinvalid"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/restrictedToAutomatch": {
      "abstract": [
        {
          "text": "The system can’t complete the requested operation because the player is using automatch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restrictedToAutomatch"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/restrictedToAutomatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorRestrictedToAutomatch"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.restrictedToAutomatch",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/restrictedtoautomatch"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/unexpectedConnection": {
      "abstract": [
        {
          "text": "An unexpected player has connected to a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unexpectedConnection"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/unexpectedConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKErrorUnexpectedConnection"
        }
      ],
      "role": "symbol",
      "title": "GKError.Code.unexpectedConnection",
      "type": "topic",
      "url": "/documentation/gamekit/gkerror/code/unexpectedconnection"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Matchmaking-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/unexpectedConnection",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invitationsDisabled",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/matchNotConnected",
        "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/restrictedToAutomatch"
      ],
      "title": "Matchmaking Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKErrorMatchRequestInvalid"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorMatchRequestInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Matchmaking-Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/unexpectedConnection",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/invitationsDisabled",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/matchNotConnected",
                "doc://com.apple.gamekit/documentation/GameKit/GKError/Code/restrictedToAutomatch"
              ],
              "title": "Matchmaking Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "GKErrorMatchRequestInvalid"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1unexpectedConnection/title",
          "value": "GKErrorUnexpectedConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1unexpectedConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorUnexpectedConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1matchNotConnected/title",
          "value": "GKErrorMatchNotConnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1matchNotConnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorMatchNotConnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1matchRequestInvalid/title",
          "value": "GKErrorMatchRequestInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1matchRequestInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorMatchRequestInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code/title",
          "value": "GKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1restrictedToAutomatch/title",
          "value": "GKErrorRestrictedToAutomatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1restrictedToAutomatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorRestrictedToAutomatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1invitationsDisabled/title",
          "value": "GKErrorInvitationsDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKError~1Code~1invitationsDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKErrorInvitationsDisabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkerror/code/matchrequestinvalid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gkerror/code/matchrequestinvalid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
