{
  "abstract": [
    {
      "text": "A value that indicates whether the toolbar displays items using a name, icon, or combination of elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSToolbar"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSToolbar/displayMode-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSToolbar(py)displayMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "displayMode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSToolbar",
        "text": "NSToolbar"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSToolbarDisplayMode",
        "text": "DisplayMode"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "displayMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "displayMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "displayMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbar",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSToolbar",
              "text": "NSToolbar"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbar/DisplayMode-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSToolbarDisplayMode",
              "text": "DisplayMode"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default value of this property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbar/DisplayMode-swift.enum/default",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For a list of possible values, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbar/DisplayMode-swift.enum",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbar": {
      "abstract": [
        {
          "text": "An object that manages the space above your app’s custom content and either below or integrated with the window’s title bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSToolbar"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSToolbar"
        }
      ],
      "role": "symbol",
      "title": "NSToolbar",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbar/DisplayMode-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate whether the toolbar displays items using a name, icon, or combination of elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisplayMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbar/DisplayMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisplayMode"
        }
      ],
      "role": "symbol",
      "title": "NSToolbar.DisplayMode",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbar/displaymode-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbar/DisplayMode-swift.enum/default": {
      "abstract": [
        {
          "text": "The default display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbar/DisplayMode-swift.enum/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSToolbarDisplayModeDefault"
        }
      ],
      "role": "symbol",
      "title": "NSToolbar.DisplayMode.default",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbar/displaymode-swift.enum/default"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbar/allowsExtensionItems": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the toolbar can add items for Action extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsExtensionItems"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbar/allowsExtensionItems",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsExtensionItems"
        }
      ],
      "role": "symbol",
      "title": "allowsExtensionItems",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbar/allowsextensionitems"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbar/allowsUserCustomization": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether users can modify the contents of the toolbar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsUserCustomization"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbar/allowsUserCustomization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsUserCustomization"
        }
      ],
      "role": "symbol",
      "title": "allowsUserCustomization",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbar/allowsusercustomization"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbar/displayMode-swift.property": {
      "abstract": [
        {
          "text": "A value that indicates whether the toolbar displays items using a name, icon, or combination of elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSToolbar",
          "text": "NSToolbar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSToolbarDisplayMode",
          "text": "DisplayMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbar/displayMode-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayMode"
        }
      ],
      "role": "symbol",
      "title": "displayMode",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbar/displaymode-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbar/isVisible": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the toolbar is visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isVisible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbar/isVisible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visible"
        }
      ],
      "role": "symbol",
      "title": "isVisible",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbar/isvisible"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbar/showsBaselineSeparator": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the toolbar shows the separator between the toolbar and the main window contents.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsBaselineSeparator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbar/showsBaselineSeparator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showsBaselineSeparator"
        }
      ],
      "role": "symbol",
      "title": "showsBaselineSeparator",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbar/showsbaselineseparator"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-toolbars-behavior",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSToolbar/isVisible",
        "doc://com.apple.appkit/documentation/AppKit/NSToolbar/DisplayMode-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSToolbar/showsBaselineSeparator",
        "doc://com.apple.appkit/documentation/AppKit/NSToolbar/allowsUserCustomization",
        "doc://com.apple.appkit/documentation/AppKit/NSToolbar/allowsExtensionItems"
      ],
      "title": "Configuring the toolbar’s behavior"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "displayMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSToolbar"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-toolbars-behavior",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSToolbar/isVisible",
                "doc://com.apple.appkit/documentation/AppKit/NSToolbar/DisplayMode-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSToolbar/showsBaselineSeparator",
                "doc://com.apple.appkit/documentation/AppKit/NSToolbar/allowsUserCustomization",
                "doc://com.apple.appkit/documentation/AppKit/NSToolbar/allowsExtensionItems"
              ],
              "title": "Configuring the toolbar’s behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbar/DisplayMode-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSToolbarDisplayMode",
                    "text": "NSToolbarDisplayMode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "displayMode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar~1allowsUserCustomization/title",
          "value": "allowsUserCustomization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar~1allowsUserCustomization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsUserCustomization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar~1isVisible/title",
          "value": "visible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar~1isVisible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "visible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar~1showsBaselineSeparator/title",
          "value": "showsBaselineSeparator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar~1showsBaselineSeparator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showsBaselineSeparator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar/title",
          "value": "NSToolbar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar~1displayMode-swift.property/title",
          "value": "displayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar~1displayMode-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar~1allowsExtensionItems/title",
          "value": "allowsExtensionItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar~1allowsExtensionItems/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsExtensionItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar~1DisplayMode-swift.enum~1default/title",
          "value": "NSToolbarDisplayModeDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar~1DisplayMode-swift.enum~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbarDisplayModeDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar~1DisplayMode-swift.enum/title",
          "value": "NSToolbarDisplayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar~1DisplayMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbarDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar~1DisplayMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbarDisplayMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstoolbar/displaymode-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstoolbar/displaymode-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
