{
  "abstract": [
    {
      "text": "An object that defines the default settings to use for universal links pattern matching.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/applinks"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Defaults-swift.dictionary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "ul:applinks.Defaults",
    "fragments": [
      {
        "kind": "text",
        "text": "object "
      },
      {
        "kind": "identifier",
        "text": "applinks.Defaults"
      }
    ],
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "applinks.Defaults"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Object",
    "symbolKind": "dictionary",
    "title": "applinks.Defaults"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Defaults"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "items": [
        {
          "attributes": [],
          "content": [],
          "introducedVersion": "14.0.0",
          "name": "caseSensitive",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "boolean"
            }
          ]
        },
        {
          "attributes": [],
          "content": [],
          "introducedVersion": "14.0.0",
          "name": "percentEncoded",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "boolean"
            }
          ]
        }
      ],
      "kind": "properties",
      "title": "Properties"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This object is a subclass of ",
              "type": "text"
            },
            {
              "code": "components",
              "type": "codeVoice"
            },
            {
              "text": " and can contain any of its properties.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for a list of available properties.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can specify pattern-matching values at three levels: domain, app, and URL.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "You use the ",
              "type": "text"
            },
            {
              "code": "defaults",
              "type": "codeVoice"
            },
            {
              "text": " object to define domain- and app-level default values.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "When you define default values at the domain level, they apply to all pattern matches for the domain, while default values at the app level apply to all pattern matches for the associated apps.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The more specific definition overrides the less specific.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "So the default values you set at the app level override the default values you set at the domain level.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "If you set values at the URL level in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, those values override the default values at the app and domain levels.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/applinks": {
      "abstract": [
        {
          "text": "The root object for a universal links service definition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applinks"
        }
      ],
      "role": "symbol",
      "title": "applinks",
      "type": "topic",
      "url": "/documentation/bundleresources/applinks"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Defaults-swift.dictionary": {
      "abstract": [
        {
          "text": "An object that defines the default settings to use for universal links pattern matching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks.Defaults"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Defaults-swift.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applinks.Defaults"
        }
      ],
      "role": "symbol",
      "title": "applinks.Defaults",
      "type": "topic",
      "url": "/documentation/bundleresources/applinks/defaults-swift.dictionary"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary": {
      "abstract": [
        {
          "text": "Patterns that define the universal links an app can open.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks.Details.Components"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applinks.Details.Components"
        }
      ],
      "role": "symbol",
      "title": "applinks.Details.Components",
      "type": "topic",
      "url": "/documentation/bundleresources/applinks/details-swift.dictionary/components-swift.dictionary"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Object"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "applinks.Defaults"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Defaults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks.Defaults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/applinks"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "object "
                  },
                  {
                    "kind": "identifier",
                    "text": "applinks.Defaults"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "items": [
              {
                "attributes": [],
                "content": [],
                "introducedVersion": "14.0.0",
                "name": "caseSensitive",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "boolean"
                  }
                ]
              },
              {
                "attributes": [],
                "content": [],
                "introducedVersion": "14.0.0",
                "name": "percentEncoded",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "boolean"
                  }
                ]
              }
            ],
            "kind": "properties",
            "title": "Properties"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks/title",
          "value": "applinks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary~1Components-swift.dictionary/title",
          "value": "applinks.Details.Components"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary~1Components-swift.dictionary/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Details.Components"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary~1Components-swift.dictionary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks.Details.Components"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Defaults-swift.dictionary/title",
          "value": "applinks.Defaults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Defaults-swift.dictionary/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Defaults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Defaults-swift.dictionary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks.Defaults"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/applinks/defaults-swift.dictionary"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/applinks/defaults-swift.dictionary"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
