{
  "abstract": [
    {
      "text": "A list of apps and the universal links they handle for a domain.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/applinks"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "ul:applinks.Details",
    "fragments": [
      {
        "kind": "text",
        "text": "object "
      },
      {
        "kind": "identifier",
        "text": "applinks.Details"
      }
    ],
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "applinks.Details"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Object",
    "symbolKind": "dictionary",
    "title": "applinks.Details"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Details"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "items": [
        {
          "attributes": [],
          "content": [],
          "introducedVersion": "9.0.0",
          "name": "appID",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [],
          "introducedVersion": "9.0.0",
          "name": "appIDs",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "[string]"
            }
          ]
        },
        {
          "attributes": [],
          "content": [],
          "introducedVersion": "9.0.0",
          "name": "components",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "["
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary",
              "kind": "typeIdentifier",
              "preciseIdentifier": "ul:applinks.Details.Components",
              "text": "applinks.Details.Components"
            },
            {
              "kind": "text",
              "text": "]"
            }
          ]
        },
        {
          "attributes": [],
          "content": [],
          "introducedVersion": "9.0.0",
          "name": "defaults",
          "required": false,
          "type": [
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Defaults-swift.dictionary",
              "kind": "typeIdentifier",
              "preciseIdentifier": "ul:applinks.Defaults",
              "text": "applinks.Defaults"
            }
          ]
        }
      ],
      "kind": "properties",
      "title": "Properties"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The object optionally contains any of these keys:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An application identifier that specifies the app that can handle the universal links in the ",
                        "type": "text"
                      },
                      {
                        "code": "components",
                        "type": "codeVoice"
                      },
                      {
                        "text": " array.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "appID",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of application identifiers that specify the apps that can handle the universal links in the ",
                        "type": "text"
                      },
                      {
                        "code": "components",
                        "type": "codeVoice"
                      },
                      {
                        "text": " array.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "appIDs",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of components that define the universal link URLs an app can handle.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "components",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A dictionary for defining the default settings to use for all universal links pattern matching in the components array.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "defaults",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "code": "appID",
              "type": "codeVoice"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "code": "appIDs",
              "type": "codeVoice"
            },
            {
              "text": " to specify the applications that can access the specific URLs you define in the associated ",
              "type": "text"
            },
            {
              "code": "components",
              "type": "codeVoice"
            },
            {
              "text": " array.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "You specify each application identifier in the following format:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<Application Identifier Prefix>.<Bundle Identifier>"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "This example code shows a universal links details object in an association file:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "{",
            "  \"appIDs\": [ \"ABCDE12345.com.example.app\", \"ABCDE12345.com.example.app2\" ],",
            "  \"components\": [",
            "    {",
            "      \"/\": \"/buy/*\",",
            "      \"#\": \"my_great_product_123\",",
            "      \"comment\": \"Matches any URL whose path starts with /buy/ and fragment equals my_great_product_123, ignoring case\"",
            "    }",
            "  ],",
            "  \"defaults\": { \"caseSensitive\": false }",
            "}"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/applinks": {
      "abstract": [
        {
          "text": "The root object for a universal links service definition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applinks"
        }
      ],
      "role": "symbol",
      "title": "applinks",
      "type": "topic",
      "url": "/documentation/bundleresources/applinks"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Defaults-swift.dictionary": {
      "abstract": [
        {
          "text": "An object that defines the default settings to use for universal links pattern matching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks.Defaults"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Defaults-swift.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applinks.Defaults"
        }
      ],
      "role": "symbol",
      "title": "applinks.Defaults",
      "type": "topic",
      "url": "/documentation/bundleresources/applinks/defaults-swift.dictionary"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary": {
      "abstract": [
        {
          "text": "A list of apps and the universal links they handle for a domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks.Details"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applinks.Details"
        }
      ],
      "role": "symbol",
      "title": "applinks.Details",
      "type": "topic",
      "url": "/documentation/bundleresources/applinks/details-swift.dictionary"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary": {
      "abstract": [
        {
          "text": "Patterns that define the universal links an app can open.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks.Details.Components"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applinks.Details.Components"
        }
      ],
      "role": "symbol",
      "title": "applinks.Details.Components",
      "type": "topic",
      "url": "/documentation/bundleresources/applinks/details-swift.dictionary/components-swift.dictionary"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "URL-components",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary"
      ],
      "title": "URL components"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Object"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "applinks.Details"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks.Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/applinks"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "URL-components",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary"
              ],
              "title": "URL components"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "object "
                  },
                  {
                    "kind": "identifier",
                    "text": "applinks.Details"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "items": [
              {
                "attributes": [],
                "content": [],
                "introducedVersion": "9.0.0",
                "name": "appID",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "string"
                  }
                ]
              },
              {
                "attributes": [],
                "content": [],
                "introducedVersion": "9.0.0",
                "name": "appIDs",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "[string]"
                  }
                ]
              },
              {
                "attributes": [],
                "content": [],
                "introducedVersion": "9.0.0",
                "name": "components",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "["
                  },
                  {
                    "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "ul:applinks.Details.Components",
                    "text": "applinks.Details.Components"
                  },
                  {
                    "kind": "text",
                    "text": "]"
                  }
                ]
              },
              {
                "attributes": [],
                "content": [],
                "introducedVersion": "9.0.0",
                "name": "defaults",
                "required": false,
                "type": [
                  {
                    "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Defaults-swift.dictionary",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "ul:applinks.Defaults",
                    "text": "applinks.Defaults"
                  }
                ]
              }
            ],
            "kind": "properties",
            "title": "Properties"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks/title",
          "value": "applinks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary~1Components-swift.dictionary/title",
          "value": "applinks.Details.Components"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary~1Components-swift.dictionary/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Details.Components"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary~1Components-swift.dictionary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks.Details.Components"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Defaults-swift.dictionary/title",
          "value": "applinks.Defaults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Defaults-swift.dictionary/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Defaults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Defaults-swift.dictionary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks.Defaults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary/title",
          "value": "applinks.Details"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks.Details"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/applinks/details-swift.dictionary"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/applinks/details-swift.dictionary"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
