{
  "abstract": [
    {
      "text": "The number of triangles described by the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/triangleIndices-1azi3",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/triangleCount"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ARPlaneGeometry(py)triangleCount",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "triangleCount"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "triangleCount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "triangleCount"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "triangleCount"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each set of three indices forms a triangle, so the number of indices in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/triangleIndices-1azi3",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " buffer is three times the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/triangleCount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry": {
      "abstract": [
        {
          "text": "A 3D mesh describing the shape of a detected plane in world-tracking AR sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARPlaneGeometry"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARPlaneGeometry"
        }
      ],
      "role": "symbol",
      "title": "ARPlaneGeometry",
      "type": "topic",
      "url": "/documentation/arkit/arplanegeometry"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/textureCoordinateCount": {
      "abstract": [
        {
          "text": "The number of elements in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/textureCoordinates-91pbc",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "textureCoordinateCount"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/textureCoordinateCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "textureCoordinateCount",
      "type": "topic",
      "url": "/documentation/arkit/arplanegeometry/texturecoordinatecount"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/textureCoordinates-91pbc": {
      "abstract": [
        {
          "text": "A buffer of texture coordinate values for each point in the plane mesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "textureCoordinates"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/textureCoordinates-91pbc",
      "kind": "symbol",
      "role": "symbol",
      "title": "textureCoordinates",
      "type": "topic",
      "url": "/documentation/arkit/arplanegeometry/texturecoordinates-91pbc"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/textureCoordinates-p801": {
      "abstract": [
        {
          "text": "An array of texture coordinate values for each point in the plane mesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textureCoordinates"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_float2",
          "text": "vector_float2"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/textureCoordinates-p801",
      "kind": "symbol",
      "role": "symbol",
      "title": "textureCoordinates",
      "type": "topic",
      "url": "/documentation/arkit/arplanegeometry/texturecoordinates-p801"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/triangleCount": {
      "abstract": [
        {
          "text": "The number of triangles described by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/triangleIndices-1azi3",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "triangleCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/triangleCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "triangleCount"
        }
      ],
      "role": "symbol",
      "title": "triangleCount",
      "type": "topic",
      "url": "/documentation/arkit/arplanegeometry/trianglecount"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/triangleIndices-1azi3": {
      "abstract": [
        {
          "text": "A buffer of indices describing the triangle mesh formed by the plane geometry’s vertex data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "triangleIndices"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/triangleIndices-1azi3",
      "kind": "symbol",
      "role": "symbol",
      "title": "triangleIndices",
      "type": "topic",
      "url": "/documentation/arkit/arplanegeometry/triangleindices-1azi3"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/triangleIndices-64epx": {
      "abstract": [
        {
          "text": "An array of indices describing the triangle mesh formed by the plane geometry’s vertex data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "triangleIndices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/triangleIndices-64epx",
      "kind": "symbol",
      "role": "symbol",
      "title": "triangleIndices",
      "type": "topic",
      "url": "/documentation/arkit/arplanegeometry/triangleindices-64epx"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/vertexCount": {
      "abstract": [
        {
          "text": "The number of elements in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/vertices-3kgkm",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vertexCount"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/vertexCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "vertexCount",
      "type": "topic",
      "url": "/documentation/arkit/arplanegeometry/vertexcount"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/vertices-3kgkm": {
      "abstract": [
        {
          "text": "A buffer of vertex positions for each point in the plane mesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vertices"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/vertices-3kgkm",
      "kind": "symbol",
      "role": "symbol",
      "title": "vertices",
      "type": "topic",
      "url": "/documentation/arkit/arplanegeometry/vertices-3kgkm"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/vertices-43kle": {
      "abstract": [
        {
          "text": "An array of vertex positions for each point in the plane mesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float3",
          "text": "simd_float3"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/vertices-43kle",
      "kind": "symbol",
      "role": "symbol",
      "title": "vertices",
      "type": "topic",
      "url": "/documentation/arkit/arplanegeometry/vertices-43kle"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Mesh-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/vertices-43kle",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/textureCoordinates-p801",
        "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/triangleIndices-64epx"
      ],
      "title": "Accessing Mesh Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "triangleCount"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "triangleCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit",
                "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Mesh-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/vertices-3kgkm",
                "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/vertexCount",
                "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/textureCoordinates-91pbc",
                "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/textureCoordinateCount",
                "doc://com.apple.arkit/documentation/ARKit/ARPlaneGeometry/triangleIndices-1azi3"
              ],
              "title": "Accessing Mesh Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "triangleCount"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPlaneGeometry/title",
          "value": "ARPlaneGeometry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPlaneGeometry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARPlaneGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPlaneGeometry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARPlaneGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPlaneGeometry~1triangleCount/title",
          "value": "triangleCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPlaneGeometry~1triangleCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "triangleCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arplanegeometry/trianglecount"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/arplanegeometry/trianglecount"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
