{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenDurationBecomesGreaterThanOrEqualTo(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So16CMBufferQueueRefa9CoreMediaE16TriggerConditionO39whenDurationBecomesGreaterThanOrEqualToyAESo6CMTimeacAEmF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "whenDurationBecomesGreaterThanOrEqualTo"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@CMTime",
        "text": "CMTime"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CMBufferQueue.TriggerCondition.whenDurationBecomesGreaterThanOrEqualTo(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "whenDurationBecomesGreaterThanOrEqualTo"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTime",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CMTime",
              "text": "CMTime"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue": {
      "abstract": [
        {
          "text": "A reference to a buffer queue instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueue"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueue",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition": {
      "abstract": [
        {
          "text": "An enumeration of trigger conditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TriggerCondition"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TriggerCondition"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueue.TriggerCondition",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/triggercondition"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenBufferCountBecomesGreaterThan(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "whenBufferCountBecomesGreaterThan"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMItemCount",
          "text": "CMItemCount"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenBufferCountBecomesGreaterThan(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMBufferQueue.TriggerCondition.whenBufferCountBecomesGreaterThan(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/triggercondition/whenbuffercountbecomesgreaterthan(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenBufferCountBecomesLessThan(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "whenBufferCountBecomesLessThan"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMItemCount",
          "text": "CMItemCount"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenBufferCountBecomesLessThan(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMBufferQueue.TriggerCondition.whenBufferCountBecomesLessThan(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/triggercondition/whenbuffercountbecomeslessthan(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenDataBecomesReady": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "whenDataBecomesReady"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenDataBecomesReady",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMBufferQueue.TriggerCondition.whenDataBecomesReady",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/triggercondition/whendatabecomesready"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenDurationBecomesGreaterThan(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "whenDurationBecomesGreaterThan"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenDurationBecomesGreaterThan(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMBufferQueue.TriggerCondition.whenDurationBecomesGreaterThan(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/triggercondition/whendurationbecomesgreaterthan(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenDurationBecomesGreaterThanOrEqualTo(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "whenDurationBecomesGreaterThanOrEqualTo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenDurationBecomesGreaterThanOrEqualTo(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMBufferQueue.TriggerCondition.whenDurationBecomesGreaterThanOrEqualTo(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/triggercondition/whendurationbecomesgreaterthanorequalto(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenDurationBecomesLessThan(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "whenDurationBecomesLessThan"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenDurationBecomesLessThan(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMBufferQueue.TriggerCondition.whenDurationBecomesLessThan(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/triggercondition/whendurationbecomeslessthan(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenDurationBecomesLessThanOrEqualTo(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "whenDurationBecomesLessThanOrEqualTo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenDurationBecomesLessThanOrEqualTo(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMBufferQueue.TriggerCondition.whenDurationBecomesLessThanOrEqualTo(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/triggercondition/whendurationbecomeslessthanorequalto(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenEndOfDataReached": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "whenEndOfDataReached"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenEndOfDataReached",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMBufferQueue.TriggerCondition.whenEndOfDataReached",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/triggercondition/whenendofdatareached"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenMaxPresentationTimeStampChanges": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "whenMaxPresentationTimeStampChanges"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenMaxPresentationTimeStampChanges",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMBufferQueue.TriggerCondition.whenMaxPresentationTimeStampChanges",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/triggercondition/whenmaxpresentationtimestampchanges"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenMinPresentationTimeStampChanges": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "whenMinPresentationTimeStampChanges"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenMinPresentationTimeStampChanges",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMBufferQueue.TriggerCondition.whenMinPresentationTimeStampChanges",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/triggercondition/whenminpresentationtimestampchanges"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenReset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "whenReset"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenReset",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMBufferQueue.TriggerCondition.whenReset",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueue/triggercondition/whenreset"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTime": {
      "abstract": [
        {
          "text": "A structure that represents time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTime"
        }
      ],
      "role": "symbol",
      "title": "CMTime",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Conditions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenBufferCountBecomesGreaterThan(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenBufferCountBecomesLessThan(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenDataBecomesReady",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenDurationBecomesGreaterThan(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenDurationBecomesLessThan(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenDurationBecomesLessThanOrEqualTo(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenEndOfDataReached",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenMaxPresentationTimeStampChanges",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenMinPresentationTimeStampChanges",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueue/TriggerCondition/whenReset"
      ],
      "title": "Conditions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueue/title",
          "value": "CMBufferQueueRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime/title",
          "value": "CMTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTime"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmbufferqueue/triggercondition/whendurationbecomesgreaterthanorequalto(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
