{
  "abstract": [
    {
      "text": "The setting that permits incoming audio.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMCameraAudioStreamSetting"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMCameraAudioStreamSetting/incomingAudioAllowed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HMCameraAudioStreamSetting@HMCameraAudioStreamSettingIncomingAudioAllowed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "incomingAudioAllowed"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMCameraAudioStreamSettingIncomingAudioAllowed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HMCameraAudioStreamSetting.incomingAudioAllowed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "incomingAudioAllowed"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCameraAudioStreamSetting": {
      "abstract": [
        {
          "text": "The options associated with a camera’s audio stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCameraAudioStreamSetting"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraAudioStreamSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCameraAudioStreamSetting"
        }
      ],
      "role": "symbol",
      "title": "HMCameraAudioStreamSetting",
      "type": "topic",
      "url": "/documentation/homekit/hmcameraaudiostreamsetting"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCameraAudioStreamSetting/bidirectionalAudioAllowed": {
      "abstract": [
        {
          "text": "The setting that permits both incoming and outgoing audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bidirectionalAudioAllowed"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraAudioStreamSetting/bidirectionalAudioAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCameraAudioStreamSettingBidirectionalAudioAllowed"
        }
      ],
      "role": "symbol",
      "title": "HMCameraAudioStreamSetting.bidirectionalAudioAllowed",
      "type": "topic",
      "url": "/documentation/homekit/hmcameraaudiostreamsetting/bidirectionalaudioallowed"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCameraAudioStreamSetting/incomingAudioAllowed": {
      "abstract": [
        {
          "text": "The setting that permits incoming audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incomingAudioAllowed"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraAudioStreamSetting/incomingAudioAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCameraAudioStreamSettingIncomingAudioAllowed"
        }
      ],
      "role": "symbol",
      "title": "HMCameraAudioStreamSetting.incomingAudioAllowed",
      "type": "topic",
      "url": "/documentation/homekit/hmcameraaudiostreamsetting/incomingaudioallowed"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCameraAudioStreamSetting/muted": {
      "abstract": [
        {
          "text": "The setting that mutes both incoming and outgoing audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "muted"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraAudioStreamSetting/muted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCameraAudioStreamSettingMuted"
        }
      ],
      "role": "symbol",
      "title": "HMCameraAudioStreamSetting.muted",
      "type": "topic",
      "url": "/documentation/homekit/hmcameraaudiostreamsetting/muted"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-Audio-Stream",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCameraAudioStreamSetting/muted",
        "doc://com.apple.homekit/documentation/HomeKit/HMCameraAudioStreamSetting/bidirectionalAudioAllowed"
      ],
      "title": "Configuring the Audio Stream"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMCameraAudioStreamSettingIncomingAudioAllowed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraAudioStreamSettingIncomingAudioAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit",
                "doc://com.apple.homekit/documentation/HomeKit/HMCameraAudioStreamSetting"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-Audio-Stream",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCameraAudioStreamSetting/muted",
                "doc://com.apple.homekit/documentation/HomeKit/HMCameraAudioStreamSetting/bidirectionalAudioAllowed"
              ],
              "title": "Configuring the Audio Stream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HMCameraAudioStreamSettingIncomingAudioAllowed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraAudioStreamSetting~1incomingAudioAllowed/title",
          "value": "HMCameraAudioStreamSettingIncomingAudioAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraAudioStreamSetting~1incomingAudioAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraAudioStreamSettingIncomingAudioAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraAudioStreamSetting/title",
          "value": "HMCameraAudioStreamSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraAudioStreamSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraAudioStreamSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraAudioStreamSetting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraAudioStreamSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraAudioStreamSetting~1muted/title",
          "value": "HMCameraAudioStreamSettingMuted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraAudioStreamSetting~1muted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraAudioStreamSettingMuted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraAudioStreamSetting~1bidirectionalAudioAllowed/title",
          "value": "HMCameraAudioStreamSettingBidirectionalAudioAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraAudioStreamSetting~1bidirectionalAudioAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraAudioStreamSettingBidirectionalAudioAllowed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmcameraaudiostreamsetting/incomingaudioallowed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmcameraaudiostreamsetting/incomingaudioallowed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
