{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/cssm_db_schema_index_info-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.security/documentation/Security/cssm_db_schema_index_info-swift.struct/init(AttributeId:IndexId:IndexType:IndexedDataLocation:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So25cssm_db_schema_index_infoV11AttributeId05IndexG00H4Type19IndexedDataLocationABs6UInt32V_A3Htcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "AttributeId"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@uint32",
        "text": "uint32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "IndexId"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@uint32",
        "text": "uint32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "IndexType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CSSM_DB_INDEX_TYPE",
        "text": "CSSM_DB_INDEX_TYPE"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "IndexedDataLocation"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CSSM_DB_INDEXED_DATA_LOCATION",
        "text": "CSSM_DB_INDEXED_DATA_LOCATION"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(AttributeId:IndexId:IndexType:IndexedDataLocation:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "AttributeId"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32",
              "text": "uint32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "IndexId"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32",
              "text": "uint32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "IndexType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_DB_INDEX_TYPE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_DB_INDEX_TYPE",
              "text": "CSSM_DB_INDEX_TYPE"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "IndexedDataLocation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_DB_INDEXED_DATA_LOCATION",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_DB_INDEXED_DATA_LOCATION",
              "text": "CSSM_DB_INDEXED_DATA_LOCATION"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_DB_INDEXED_DATA_LOCATION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_DB_INDEXED_DATA_LOCATION"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_DB_INDEXED_DATA_LOCATION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_DB_INDEXED_DATA_LOCATION"
        }
      ],
      "role": "symbol",
      "title": "CSSM_DB_INDEXED_DATA_LOCATION",
      "type": "topic",
      "url": "/documentation/security/cssm_db_indexed_data_location"
    },
    "doc://com.apple.security/documentation/Security/CSSM_DB_INDEX_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_DB_INDEX_TYPE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_DB_INDEX_TYPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_DB_INDEX_TYPE"
        }
      ],
      "role": "symbol",
      "title": "CSSM_DB_INDEX_TYPE",
      "type": "topic",
      "url": "/documentation/security/cssm_db_index_type"
    },
    "doc://com.apple.security/documentation/Security/cssm_db_schema_index_info-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cssm_db_schema_index_info"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_db_schema_index_info-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cssm_db_schema_index_info"
        }
      ],
      "role": "symbol",
      "title": "cssm_db_schema_index_info",
      "type": "topic",
      "url": "/documentation/security/cssm_db_schema_index_info-swift.struct"
    },
    "doc://com.apple.security/documentation/Security/cssm_db_schema_index_info-swift.struct/init(AttributeId:IndexId:IndexType:IndexedDataLocation:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "AttributeId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "IndexId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uint32",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "IndexType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_DB_INDEX_TYPE",
          "text": "CSSM_DB_INDEX_TYPE"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "IndexedDataLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CSSM_DB_INDEXED_DATA_LOCATION",
          "text": "CSSM_DB_INDEXED_DATA_LOCATION"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_db_schema_index_info-swift.struct/init(AttributeId:IndexId:IndexType:IndexedDataLocation:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(AttributeId:IndexId:IndexType:IndexedDataLocation:)",
      "type": "topic",
      "url": "/documentation/security/cssm_db_schema_index_info-swift.struct/init(attributeid:indexid:indextype:indexeddatalocation:)"
    },
    "doc://com.apple.security/documentation/Security/uint32": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uint32"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/uint32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uint32"
        }
      ],
      "role": "symbol",
      "title": "uint32",
      "type": "topic",
      "url": "/documentation/security/uint32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_DB_INDEXED_DATA_LOCATION/title",
          "value": "CSSM_DB_INDEXED_DATA_LOCATION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_DB_INDEXED_DATA_LOCATION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_DB_INDEXED_DATA_LOCATION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_DB_INDEXED_DATA_LOCATION/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_DB_INDEXED_DATA_LOCATION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_db_schema_index_info-swift.struct/title",
          "value": "cssm_db_schema_index_info"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_db_schema_index_info-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_db_schema_index_info"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1cssm_db_schema_index_info-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cssm_db_schema_index_info"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_DB_INDEX_TYPE/title",
          "value": "CSSM_DB_INDEX_TYPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_DB_INDEX_TYPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_DB_INDEX_TYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_DB_INDEX_TYPE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_DB_INDEX_TYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1uint32/title",
          "value": "uint32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1uint32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uint32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1uint32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "uint32"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cssm_db_schema_index_info-swift.struct/init(attributeid:indexid:indextype:indexeddatalocation:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
