{
  "abstract": [
    {
      "text": "The attributes for a rule set that you create.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "App Store Connect API",
      "versions": [
        "3.0",
        "3.6"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appstoreconnectapi/documentation/AppStoreConnectAPI",
        "doc://com.apple.appstoreconnectapi/documentation/AppStoreConnectAPI/GameCenterMatchmakingRuleSetCreateRequest",
        "doc://com.apple.appstoreconnectapi/documentation/AppStoreConnectAPI/GameCenterMatchmakingRuleSetCreateRequest/Data-data.dictionary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "data",
    "url": "doc://com.apple.appstoreconnectapi/documentation/AppStoreConnectAPI/GameCenterMatchmakingRuleSetCreateRequest/Data-data.dictionary/Attributes-data.dictionary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "data:app_store_connect_api:GameCenterMatchmakingRuleSetCreateRequest.Data.Attributes",
    "fragments": [
      {
        "kind": "text",
        "text": "object "
      },
      {
        "kind": "identifier",
        "text": "GameCenterMatchmakingRuleSetCreateRequest.Data.Attributes"
      }
    ],
    "modules": [
      {
        "name": "App Store Connect API"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GameCenterMatchmakingRuleSetCreateRequest.Data.Attributes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "3.1",
        "name": "App Store Connect API"
      }
    ],
    "role": "symbol",
    "roleHeading": "Object",
    "symbolKind": "dictionary",
    "title": "GameCenterMatchmakingRuleSetCreateRequest.Data.Attributes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "data"
          ],
          "platforms": [
            "Unsupported OS: App Store Connect"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "GameCenterMatchmakingRuleSetCreateRequest.Data.Attributes"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "items": [
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The maximum number of players who can join the matches that Game Center finds using these rules.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "maxPlayers",
          "required": true,
          "type": [
            {
              "kind": "text",
              "text": "integer"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The minimum number of players who can join the matches that Game Center finds using these rules.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "minPlayers",
          "required": true,
          "type": [
            {
              "kind": "text",
              "text": "integer"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A name for the rule set that’s unique within the scope of your development team.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "referenceName",
          "required": true,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The version of the expression language that all the rules in this rule set use. The only possible value is ",
                  "type": "text"
                },
                {
                  "code": "1",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "ruleLanguageVersion",
          "required": true,
          "type": [
            {
              "kind": "text",
              "text": "integer"
            }
          ]
        }
      ],
      "kind": "properties",
      "title": "Properties"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "minPlayers",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "maxPlayers",
              "type": "codeVoice"
            },
            {
              "text": " attributes constrain the range of players in the match requests. If you don’t set the ",
              "type": "text"
            },
            {
              "code": "GKMatchRequest.",
              "type": "codeVoice"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/GameKit/GKMatchRequest/minPlayers",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "GKMatchRequest.",
              "type": "codeVoice"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/GameKit/GKMatchRequest/maxPlayers",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties in your code, the properties default to the rule set ",
              "type": "text"
            },
            {
              "code": "minPlayers",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "maxPlayers",
              "type": "codeVoice"
            },
            {
              "text": " attributes. If you set the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/GameKit/GKMatchRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties, use values that are in the rule set range.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, if the match request range is ",
              "type": "text"
            },
            {
              "code": "[2, 4]",
              "type": "codeVoice"
            },
            {
              "text": " and the rule set range is ",
              "type": "text"
            },
            {
              "code": "[2,8]",
              "type": "codeVoice"
            },
            {
              "text": ", Game Center finds players within the ",
              "type": "text"
            },
            {
              "code": "[2, 4]",
              "type": "codeVoice"
            },
            {
              "text": " match request range. However, if the match request range is ",
              "type": "text"
            },
            {
              "code": "[2, 8]",
              "type": "codeVoice"
            },
            {
              "text": " and the rule set range is ",
              "type": "text"
            },
            {
              "code": "[3, 4]",
              "type": "codeVoice"
            },
            {
              "text": ", Game Center ignores the match request properties and finds players within the ",
              "type": "text"
            },
            {
              "code": "[3, 4]",
              "type": "codeVoice"
            },
            {
              "text": " rule set range. If the match request range is ",
              "type": "text"
            },
            {
              "code": "[8, 8]",
              "type": "codeVoice"
            },
            {
              "text": " and the rule set range is ",
              "type": "text"
            },
            {
              "code": "[2, 4]",
              "type": "codeVoice"
            },
            {
              "text": " (outside of the rule set range), Game Center never finds players for that request.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appstoreconnectapi/documentation/AppStoreConnectAPI": {
      "abstract": [
        {
          "text": "Automate the tasks you perform on the Apple Developer website and in App Store Connect.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appstoreconnectapi/documentation/AppStoreConnectAPI",
      "kind": "symbol",
      "role": "collection",
      "title": "App Store Connect API",
      "type": "topic",
      "url": "/documentation/appstoreconnectapi"
    },
    "doc://com.apple.appstoreconnectapi/documentation/AppStoreConnectAPI/GameCenterMatchmakingRuleSetCreateRequest": {
      "abstract": [
        {
          "text": "The request body you use to create a rule set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "GameCenterMatchmakingRuleSetCreateRequest"
        }
      ],
      "identifier": "doc://com.apple.appstoreconnectapi/documentation/AppStoreConnectAPI/GameCenterMatchmakingRuleSetCreateRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GameCenterMatchmakingRuleSetCreateRequest"
        }
      ],
      "role": "symbol",
      "title": "GameCenterMatchmakingRuleSetCreateRequest",
      "type": "topic",
      "url": "/documentation/appstoreconnectapi/gamecentermatchmakingrulesetcreaterequest"
    },
    "doc://com.apple.appstoreconnectapi/documentation/AppStoreConnectAPI/GameCenterMatchmakingRuleSetCreateRequest/Data-data.dictionary": {
      "abstract": [
        {
          "text": "The data structure of the request body you use to create a rule set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "GameCenterMatchmakingRuleSetCreateRequest.Data"
        }
      ],
      "identifier": "doc://com.apple.appstoreconnectapi/documentation/AppStoreConnectAPI/GameCenterMatchmakingRuleSetCreateRequest/Data-data.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GameCenterMatchmakingRuleSetCreateRequest.Data"
        }
      ],
      "role": "symbol",
      "title": "GameCenterMatchmakingRuleSetCreateRequest.Data",
      "type": "topic",
      "url": "/documentation/appstoreconnectapi/gamecentermatchmakingrulesetcreaterequest/data-data.dictionary"
    },
    "doc://com.apple.appstoreconnectapi/documentation/AppStoreConnectAPI/GameCenterMatchmakingRuleSetCreateRequest/Data-data.dictionary/Attributes-data.dictionary": {
      "abstract": [
        {
          "text": "The attributes for a rule set that you create.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "GameCenterMatchmakingRuleSetCreateRequest.Data.Attributes"
        }
      ],
      "identifier": "doc://com.apple.appstoreconnectapi/documentation/AppStoreConnectAPI/GameCenterMatchmakingRuleSetCreateRequest/Data-data.dictionary/Attributes-data.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GameCenterMatchmakingRuleSetCreateRequest.Data.Attributes"
        }
      ],
      "role": "symbol",
      "title": "GameCenterMatchmakingRuleSetCreateRequest.Data.Attributes",
      "type": "topic",
      "url": "/documentation/appstoreconnectapi/gamecentermatchmakingrulesetcreaterequest/data-data.dictionary/attributes-data.dictionary"
    },
    "doc://com.apple.documentation/documentation/GameKit/GKMatchRequest": {
      "abstract": [
        {
          "text": "An object that encapsulates the parameters to create a real-time or turn-based match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKMatchRequest"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GameKit/GKMatchRequest",
      "kind": "symbol",
      "role": "symbol",
      "title": "GKMatchRequest",
      "type": "topic",
      "url": "/documentation/GameKit/GKMatchRequest"
    },
    "doc://com.apple.documentation/documentation/GameKit/GKMatchRequest/maxPlayers": {
      "abstract": [
        {
          "text": "The maximum number of players that can join the match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxPlayers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GameKit/GKMatchRequest/maxPlayers",
      "kind": "symbol",
      "role": "symbol",
      "title": "maxPlayers",
      "type": "topic",
      "url": "/documentation/GameKit/GKMatchRequest/maxPlayers"
    },
    "doc://com.apple.documentation/documentation/GameKit/GKMatchRequest/minPlayers": {
      "abstract": [
        {
          "text": "The minimum number of players that can join the match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minPlayers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GameKit/GKMatchRequest/minPlayers",
      "kind": "symbol",
      "role": "symbol",
      "title": "minPlayers",
      "type": "topic",
      "url": "/documentation/GameKit/GKMatchRequest/minPlayers"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1GameKit~1GKMatchRequest~1maxPlayers/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "maxPlayers"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1GameKit~1GKMatchRequest~1minPlayers/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "minPlayers"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1GameKit~1GKMatchRequest/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKMatchRequest"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appstoreconnectapi/gamecentermatchmakingrulesetcreaterequest/data-data.dictionary/attributes-data.dictionary"
      ],
      "traits": [
        {
          "interfaceLanguage": "data"
        }
      ]
    }
  ]
}
