{
  "abstract": [
    {
      "text": "The message contains text.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext",
        "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry",
        "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/text"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIMessageConversationEntryDataKind@UIMessageConversationEntryDataKindText",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "text"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIMessageConversationEntryDataKindText"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIMessageConversationContext.MessageEntry.DataKind.text"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "text"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext": {
      "abstract": [
        {
          "text": "A class that represents a message conversation.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMessageConversationContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMessageConversationContext"
        }
      ],
      "role": "symbol",
      "title": "UIMessageConversationContext",
      "type": "topic",
      "url": "/documentation/uikit/uimessageconversationcontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry": {
      "abstract": [
        {
          "text": "A class that represents a message in a message conversation.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MessageEntry"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MessageEntry"
        }
      ],
      "role": "symbol",
      "title": "UIMessageConversationContext.MessageEntry",
      "type": "topic",
      "url": "/documentation/uikit/uimessageconversationcontext/messageentry"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum": {
      "abstract": [
        {
          "text": "A list of options that represent the kinds of data a message can contain.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DataKind"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DataKind"
        }
      ],
      "role": "symbol",
      "title": "UIMessageConversationContext.MessageEntry.DataKind",
      "type": "topic",
      "url": "/documentation/uikit/uimessageconversationcontext/messageentry/datakind-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/attachment": {
      "abstract": [
        {
          "text": "The message contains an attachment, such as an image or file.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attachment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/attachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMessageConversationEntryDataKindAttachment"
        }
      ],
      "role": "symbol",
      "title": "UIMessageConversationContext.MessageEntry.DataKind.attachment",
      "type": "topic",
      "url": "/documentation/uikit/uimessageconversationcontext/messageentry/datakind-swift.enum/attachment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/other": {
      "abstract": [
        {
          "text": "The message contains other data, such as data that represents a sticker or a payment.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMessageConversationEntryDataKindOther"
        }
      ],
      "role": "symbol",
      "title": "UIMessageConversationContext.MessageEntry.DataKind.other",
      "type": "topic",
      "url": "/documentation/uikit/uimessageconversationcontext/messageentry/datakind-swift.enum/other"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/text": {
      "abstract": [
        {
          "text": "The message contains text.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/text",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMessageConversationEntryDataKindText"
        }
      ],
      "role": "symbol",
      "title": "UIMessageConversationContext.MessageEntry.DataKind.text",
      "type": "topic",
      "url": "/documentation/uikit/uimessageconversationcontext/messageentry/datakind-swift.enum/text"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Kinds-of-data-in-a-message",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/attachment",
        "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/other"
      ],
      "title": "Kinds of data in a message"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIMessageConversationEntryDataKindText"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationEntryDataKindText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Kinds-of-data-in-a-message",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/attachment",
                "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry/DataKind-swift.enum/other"
              ],
              "title": "Kinds of data in a message"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIMessageConversationEntryDataKindText"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext/title",
          "value": "UIMessageConversationContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1DataKind-swift.enum~1text/title",
          "value": "UIMessageConversationEntryDataKindText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1DataKind-swift.enum~1text/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationEntryDataKindText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry/title",
          "value": "UIMessageConversationEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1DataKind-swift.enum/title",
          "value": "UIMessageConversationEntryDataKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1DataKind-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationEntryDataKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1DataKind-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationEntryDataKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1DataKind-swift.enum~1attachment/title",
          "value": "UIMessageConversationEntryDataKindAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1DataKind-swift.enum~1attachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationEntryDataKindAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1DataKind-swift.enum~1other/title",
          "value": "UIMessageConversationEntryDataKindOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry~1DataKind-swift.enum~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationEntryDataKindOther"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uimessageconversationcontext/messageentry/datakind-swift.enum/text"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uimessageconversationcontext/messageentry/datakind-swift.enum/text"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
