{
  "abstract": [
    {
      "text": "Rotated 90° CCW and flipped vertically",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation5"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ICEXIFOrientationType@ICEXIFOrientation5",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "orientation5"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICEXIFOrientation5"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ICEXIFOrientationType.orientation5"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "orientation5"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType": {
      "abstract": [
        {
          "text": "The file’s orientation type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICEXIFOrientationType"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICEXIFOrientationType"
        }
      ],
      "role": "symbol",
      "title": "ICEXIFOrientationType",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation1": {
      "abstract": [
        {
          "text": "Normal",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation1"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICEXIFOrientation1"
        }
      ],
      "role": "symbol",
      "title": "ICEXIFOrientationType.orientation1",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype/orientation1"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation2": {
      "abstract": [
        {
          "text": "Flipped horizontally",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation2"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICEXIFOrientation2"
        }
      ],
      "role": "symbol",
      "title": "ICEXIFOrientationType.orientation2",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype/orientation2"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation3": {
      "abstract": [
        {
          "text": "Rotated 180°",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation3"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICEXIFOrientation3"
        }
      ],
      "role": "symbol",
      "title": "ICEXIFOrientationType.orientation3",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype/orientation3"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation4": {
      "abstract": [
        {
          "text": "Flipped vertically",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation4"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICEXIFOrientation4"
        }
      ],
      "role": "symbol",
      "title": "ICEXIFOrientationType.orientation4",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype/orientation4"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation5": {
      "abstract": [
        {
          "text": "Rotated 90° CCW and flipped vertically",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation5"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICEXIFOrientation5"
        }
      ],
      "role": "symbol",
      "title": "ICEXIFOrientationType.orientation5",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype/orientation5"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation6": {
      "abstract": [
        {
          "text": "Rotated 90° CCW",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation6"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICEXIFOrientation6"
        }
      ],
      "role": "symbol",
      "title": "ICEXIFOrientationType.orientation6",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype/orientation6"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation7": {
      "abstract": [
        {
          "text": "Rotated 90° CW and flipped vertically",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation7"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICEXIFOrientation7"
        }
      ],
      "role": "symbol",
      "title": "ICEXIFOrientationType.orientation7",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype/orientation7"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation8": {
      "abstract": [
        {
          "text": "Rotated 90° CW",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation8"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICEXIFOrientation8"
        }
      ],
      "role": "symbol",
      "title": "ICEXIFOrientationType.orientation8",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype/orientation8"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation1",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation2",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation3",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation4",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation6",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation7",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation8"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICEXIFOrientation5"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientation5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation1",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation2",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation3",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation4",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation6",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation7",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType/orientation8"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ICEXIFOrientation5"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation6/title",
          "value": "ICEXIFOrientation6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientation6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation4/title",
          "value": "ICEXIFOrientation4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientation4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation2/title",
          "value": "ICEXIFOrientation2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientation2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation1/title",
          "value": "ICEXIFOrientation1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientation1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation8/title",
          "value": "ICEXIFOrientation8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientation8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation7/title",
          "value": "ICEXIFOrientation7"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientation7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation5/title",
          "value": "ICEXIFOrientation5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientation5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation3/title",
          "value": "ICEXIFOrientation3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType~1orientation3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientation3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType/title",
          "value": "ICEXIFOrientationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientationType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icexiforientationtype/orientation5"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icexiforientationtype/orientation5"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
