{
  "abstract": [
    {
      "text": "The option to redisplay the view when the bounds change by invoking the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/setNeedsDisplay()",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " method.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIView",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/redraw"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIViewContentMode@UIViewContentModeRedraw",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "redraw"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIViewContentModeRedraw"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIView.ContentMode.redraw"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "redraw"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/uikit/uiview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum": {
      "abstract": [
        {
          "text": "Options to specify how a view adjusts its content when its size changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ContentMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ContentMode"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottom": {
      "abstract": [
        {
          "text": "The option to center the content aligned at the bottom in the view’s bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeBottom"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.bottom",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/bottom"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottomLeft": {
      "abstract": [
        {
          "text": "The option to align the content in the bottom-left corner of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomLeft"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottomLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeBottomLeft"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.bottomLeft",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/bottomleft"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottomRight": {
      "abstract": [
        {
          "text": "The option to align the content in the bottom-right corner of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomRight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottomRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeBottomRight"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.bottomRight",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/bottomright"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/center": {
      "abstract": [
        {
          "text": "The option to center the content in the view’s bounds, keeping the proportions the same.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeCenter"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.center",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/center"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/left": {
      "abstract": [
        {
          "text": "The option to align the content on the left of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeLeft"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.left",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/left"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/redraw": {
      "abstract": [
        {
          "text": "The option to redisplay the view when the bounds change by invoking the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/setNeedsDisplay()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "redraw"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/redraw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeRedraw"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.redraw",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/redraw"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/right": {
      "abstract": [
        {
          "text": "The option to align the content on the right of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeRight"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.right",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/right"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleAspectFill": {
      "abstract": [
        {
          "text": "The option to scale the content to fill the size of the view. Some portion of the content may be clipped to fill the view’s bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleAspectFill"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleAspectFill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeScaleAspectFill"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.scaleAspectFill",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/scaleaspectfill"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleAspectFit": {
      "abstract": [
        {
          "text": "The option to scale the content to fit the size of the view by maintaining the aspect ratio. Any remaining area of the view’s bounds is transparent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleAspectFit"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleAspectFit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeScaleAspectFit"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.scaleAspectFit",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/scaleaspectfit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleToFill": {
      "abstract": [
        {
          "text": "The option to scale the content to fit the size of itself by changing the aspect ratio of the content if necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleToFill"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleToFill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeScaleToFill"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.scaleToFill",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/scaletofill"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/top": {
      "abstract": [
        {
          "text": "The option to center the content aligned at the top in the view’s bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeTop"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.top",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/top"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/topLeft": {
      "abstract": [
        {
          "text": "The option to align the content in the top-left corner of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLeft"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/topLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeTopLeft"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.topLeft",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/topleft"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/topRight": {
      "abstract": [
        {
          "text": "The option to align the content in the top-right corner of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topRight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/topRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeTopRight"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.topRight",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/topright"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/setNeedsDisplay()": {
      "abstract": [
        {
          "text": "Marks the receiver’s entire bounds rectangle as needing to be redrawn.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setNeedsDisplay"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/setNeedsDisplay()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setNeedsDisplay"
        }
      ],
      "role": "symbol",
      "title": "setNeedsDisplay()",
      "type": "topic",
      "url": "/documentation/uikit/uiview/setneedsdisplay()"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleToFill",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleAspectFit",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleAspectFill",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/center",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/top",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottom",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/left",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/right",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/topLeft",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/topRight",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottomLeft",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottomRight"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIViewContentModeRedraw"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeRedraw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleToFill",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleAspectFit",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleAspectFill",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/center",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/top",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottom",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/left",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/right",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/topLeft",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/topRight",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottomLeft",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottomRight"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIViewContentModeRedraw"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setNeedsDisplay()/title",
          "value": "setNeedsDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setNeedsDisplay()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setNeedsDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title",
          "value": "UIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1top/title",
          "value": "UIViewContentModeTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1scaleAspectFit/title",
          "value": "UIViewContentModeScaleAspectFit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1scaleAspectFit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeScaleAspectFit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1bottom/title",
          "value": "UIViewContentModeBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1right/title",
          "value": "UIViewContentModeRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1redraw/title",
          "value": "UIViewContentModeRedraw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1redraw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeRedraw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1bottomRight/title",
          "value": "UIViewContentModeBottomRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1bottomRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeBottomRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1bottomLeft/title",
          "value": "UIViewContentModeBottomLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1bottomLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeBottomLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1topRight/title",
          "value": "UIViewContentModeTopRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1topRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeTopRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1center/title",
          "value": "UIViewContentModeCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1scaleToFill/title",
          "value": "UIViewContentModeScaleToFill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1scaleToFill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeScaleToFill"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1topLeft/title",
          "value": "UIViewContentModeTopLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1topLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeTopLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum/title",
          "value": "UIViewContentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1scaleAspectFill/title",
          "value": "UIViewContentModeScaleAspectFill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1scaleAspectFill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeScaleAspectFill"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1left/title",
          "value": "UIViewContentModeLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeLeft"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiview/contentmode-swift.enum/redraw"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiview/contentmode-swift.enum/redraw"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
