{
  "abstract": [
    {
      "text": "Implement this method to customize the Open panel shown by a pop-up–style path.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSPathControlDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPathControlDelegate/pathControl(_:willDisplay:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSPathControlDelegate(im)pathControl:willDisplayOpenPanel:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "pathControl"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSPathControl",
        "text": "NSPathControl"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "willDisplay"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSOpenPanel",
        "text": "NSOpenPanel"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "pathControl:willDisplayOpenPanel:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "pathControl(_:willDisplay:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "pathControl"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "pathControl"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathControl",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSPathControl",
              "text": "NSPathControl"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "willDisplay"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "openPanel"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenPanel",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSOpenPanel",
              "text": "NSOpenPanel"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The path control displaying the Open panel.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "pathControl"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The Open panel to be displayed.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "openPanel"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is called before the Open panel is shown but after its allowed file types are set to the cell’s allowed types. At this time, you can further customize the Open panel as required. This method is called only when the style is set to ",
              "type": "text"
            },
            {
              "code": "NSPathStylePopUp",
              "type": "codeVoice"
            },
            {
              "text": ". Implementation of this method is optional.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenPanel": {
      "abstract": [
        {
          "text": "A panel that prompts the user to select a file to open.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenPanel"
        }
      ],
      "role": "symbol",
      "title": "NSOpenPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsopenpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPathControl": {
      "abstract": [
        {
          "text": "A display of a file system path or virtual path information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPathControl"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPathControl"
        }
      ],
      "role": "symbol",
      "title": "NSPathControl",
      "type": "topic",
      "url": "/documentation/appkit/nspathcontrol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPathControlDelegate": {
      "abstract": [
        {
          "text": "A set of methods that can be implemented by the delegate of a path control object to support dragging to and from the control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPathControlDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathControlDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPathControlDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSPathControlDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nspathcontroldelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPathControlDelegate/pathControl(_:willDisplay:)": {
      "abstract": [
        {
          "text": "Implement this method to customize the Open panel shown by a pop-up–style path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pathControl"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPathControl",
          "text": "NSPathControl"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willDisplay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOpenPanel",
          "text": "NSOpenPanel"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathControlDelegate/pathControl(_:willDisplay:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pathControl:willDisplayOpenPanel:"
        }
      ],
      "role": "symbol",
      "title": "pathControl(_:willDisplay:)",
      "type": "topic",
      "url": "/documentation/appkit/nspathcontroldelegate/pathcontrol(_:willdisplay:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPathControlDelegate/pathControl(_:willPopUp:)": {
      "abstract": [
        {
          "text": "Implement this method to customize the menu of a pop-up–style path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pathControl"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPathControl",
          "text": "NSPathControl"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willPopUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenu",
          "text": "NSMenu"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathControlDelegate/pathControl(_:willPopUp:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pathControl:willPopUpMenu:"
        }
      ],
      "role": "symbol",
      "title": "pathControl(_:willPopUp:)",
      "type": "topic",
      "url": "/documentation/appkit/nspathcontroldelegate/pathcontrol(_:willpopup:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-a-Pop-Up-Style-Path",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPathControlDelegate/pathControl(_:willPopUp:)"
      ],
      "title": "Customizing a Pop-Up–Style Path"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "pathControl:willDisplayOpenPanel:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pathControl:willDisplayOpenPanel:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSPathControlDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Customizing-a-Pop-Up-Style-Path",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPathControlDelegate/pathControl(_:willPopUp:)"
              ],
              "title": "Customizing a Pop-Up–Style Path"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "pathControl:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathControl",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSPathControl",
                    "text": "NSPathControl"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "pathControl"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "willDisplayOpenPanel:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenPanel",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSOpenPanel",
                    "text": "NSOpenPanel"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "openPanel"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The path control displaying the Open panel.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "pathControl"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The Open panel to be displayed.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "openPanel"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControlDelegate/title",
          "value": "NSPathControlDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControlDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathControlDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControlDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathControlDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControlDelegate~1pathControl(_:willDisplay:)/title",
          "value": "pathControl:willDisplayOpenPanel:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControlDelegate~1pathControl(_:willDisplay:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pathControl:willDisplayOpenPanel:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel/title",
          "value": "NSOpenPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControlDelegate~1pathControl(_:willPopUp:)/title",
          "value": "pathControl:willPopUpMenu:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControlDelegate~1pathControl(_:willPopUp:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pathControl:willPopUpMenu:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControl/title",
          "value": "NSPathControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathControl"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nspathcontroldelegate/pathcontrol(_:willdisplay:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nspathcontroldelegate/pathcontrol(_:willdisplay:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
