{
  "abstract": [
    {
      "text": "The user denied location access, or the source of the App Clip invocation wasn’t an NFC tag or visual code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appclip/documentation/AppClip",
        "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/disallowed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC28APActivationPayloadErrorCodeLeV10disallowedSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "disallowed"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC28APActivationPayloadErrorCodeLeV",
        "text": "APActivationPayloadError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@APActivationPayloadErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "App Clips"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "disallowed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "disallowed"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC28APActivationPayloadErrorCodeLeV",
              "text": "APActivationPayloadError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@APActivationPayloadErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appclip/documentation/AppClip": {
      "abstract": [
        {
          "text": "Provide people a shortcut to selected content and features of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip",
      "kind": "symbol",
      "role": "collection",
      "title": "App Clips",
      "type": "topic",
      "url": "/documentation/appclip"
    },
    "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError": {
      "abstract": [
        {
          "text": "An error that an App Clip activation payload returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "APActivationPayloadError"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "APActivationPayloadError"
        }
      ],
      "role": "symbol",
      "title": "APActivationPayloadError",
      "type": "topic",
      "url": "/documentation/appclip/apactivationpayloaderror"
    },
    "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/Code": {
      "abstract": [
        {
          "text": "Error codes that an App Clip activation payload returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "APActivationPayloadError.Code",
      "type": "topic",
      "url": "/documentation/appclip/apactivationpayloaderror/code"
    },
    "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/disallowed": {
      "abstract": [
        {
          "text": "The user denied location access, or the source of the App Clip invocation wasn’t an NFC tag or visual code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disallowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC28APActivationPayloadErrorCodeLeV",
          "text": "APActivationPayloadError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@APActivationPayloadErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/disallowed",
      "kind": "symbol",
      "role": "symbol",
      "title": "disallowed",
      "type": "topic",
      "url": "/documentation/appclip/apactivationpayloaderror/disallowed"
    },
    "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/doesNotMatch": {
      "abstract": [
        {
          "text": "The provided URL doesn’t match the invocation URL you registered for the App Clip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doesNotMatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC28APActivationPayloadErrorCodeLeV",
          "text": "APActivationPayloadError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@APActivationPayloadErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/doesNotMatch",
      "kind": "symbol",
      "role": "symbol",
      "title": "doesNotMatch",
      "type": "topic",
      "url": "/documentation/appclip/apactivationpayloaderror/doesnotmatch"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/doesNotMatch",
        "doc://com.apple.appclip/documentation/AppClip/APActivationPayloadError/Code"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appclip~1documentation~1AppClip~1APActivationPayloadError~1Code/title",
          "value": "APActivationPayloadErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appclip~1documentation~1AppClip~1APActivationPayloadError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "APActivationPayloadErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appclip~1documentation~1AppClip~1APActivationPayloadError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "APActivationPayloadErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appclip/apactivationpayloaderror/disallowed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
