{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"output"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MDLMaterialProperty","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty","text":"MDLMaterialProperty"},{"kind":"text","text":", "},{"kind":"externalParam","text":"input"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MDLMaterialProperty","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty","text":"MDLMaterialProperty"},{"kind":"text","text":")"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyConnection/init(output:input:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyConnection"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/modelio/mdlmaterialpropertyconnection/init(output:input:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/modelio/mdlmaterialpropertyconnection/init(output:input:)"]}],"metadata":{"symbolKind":"init","title":"init(output:input:)","navigatorTitle":[{"text":"initWithOutput:input:","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)MDLMaterialPropertyConnection(im)initWithOutput:input:","platforms":[{"introducedAt":"10.0","name":"iOS","deprecated":false,"beta":false,"unavailable":false},{"introducedAt":"10.0","name":"iPadOS","deprecated":false,"beta":false,"unavailable":false},{"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"introducedAt":"10.12","name":"macOS","deprecated":false,"beta":false,"unavailable":false},{"beta":false,"unavailable":false,"deprecated":false,"name":"tvOS","introducedAt":"10.0"},{"beta":false,"unavailable":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"output","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MDLMaterialProperty","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MDLMaterialProperty"},{"text":", ","kind":"text"},{"text":"input","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MDLMaterialProperty","text":"MDLMaterialProperty","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"Model I/O"}],"roleHeading":"Initializer"},"references":{"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty":{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty","kind":"symbol","title":"MDLMaterialProperty","url":"/documentation/modelio/mdlmaterialproperty","abstract":[{"type":"text","text":"A definition for one specific aspect of the rendering parameters for a material."}],"role":"symbol","navigatorTitle":[{"text":"MDLMaterialProperty","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLMaterialProperty","kind":"identifier"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO":{"identifier":"doc://com.apple.modelio/documentation/ModelIO","title":"Model I/O","role":"collection","kind":"symbol","abstract":[{"text":"Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.","type":"text"}],"type":"topic","url":"/documentation/modelio"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyConnection":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MDLMaterialPropertyConnection"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MDLMaterialPropertyConnection"}],"kind":"symbol","role":"symbol","title":"MDLMaterialPropertyConnection","url":"/documentation/modelio/mdlmaterialpropertyconnection","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyConnection","type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyConnection/init(output:input:)":{"url":"/documentation/modelio/mdlmaterialpropertyconnection/init(output:input:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"output","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MDLMaterialProperty","preciseIdentifier":"c:objc(cs)MDLMaterialProperty"},{"kind":"text","text":", "},{"kind":"externalParam","text":"input"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MDLMaterialProperty","preciseIdentifier":"c:objc(cs)MDLMaterialProperty"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithOutput:input:"}],"kind":"symbol","title":"init(output:input:)","abstract":[],"role":"symbol","type":"topic","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyConnection/init(output:input:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"10.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"10.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.1"},{"name":"macOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"10.12"},{"beta":false,"unavailable":false,"deprecated":false,"name":"tvOS","introducedAt":"10.0"},{"beta":false,"unavailable":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"initWithOutput:input:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOutput:input:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLMaterialPropertyConnection"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"add","path":"/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithOutput:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MDLMaterialProperty","kind":"typeIdentifier","text":"MDLMaterialProperty","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"output"},{"kind":"text","text":" "},{"kind":"identifier","text":"input:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MDLMaterialProperty","kind":"typeIdentifier","text":"MDLMaterialProperty","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"input"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty/title","value":"MDLMaterialProperty"},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty/fragments","value":[{"text":"MDLMaterialProperty","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty/navigatorTitle","value":[{"text":"MDLMaterialProperty","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyConnection/title","value":"MDLMaterialPropertyConnection"},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyConnection/fragments","value":[{"kind":"identifier","text":"MDLMaterialPropertyConnection"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyConnection/navigatorTitle","value":[{"text":"MDLMaterialPropertyConnection","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyConnection~1init(output:input:)/title","value":"initWithOutput:input:"},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialPropertyConnection~1init(output:input:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithOutput:input:","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}