{
  "abstract": [
    {
      "text": "An array of email addresses that the data detection system identifies.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/emailAddresses"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So12UIPasteboardC5UIKitE14DetectedValuesV14emailAddressesSaySo19DDMatchEmailAddressCGvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "emailAddresses"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)DDMatchEmailAddress",
        "text": "DDMatchEmailAddress"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "emailAddresses"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "emailAddresses"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)DDMatchEmailAddress",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)DDMatchEmailAddress",
              "text": "DDMatchEmailAddress"
            },
            {
              "kind": "text",
              "text": "] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard": {
      "abstract": [
        {
          "text": "An object that helps a user share data from one place to another within your app, and from your app to other apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPasteboard"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteboard"
        }
      ],
      "role": "symbol",
      "title": "UIPasteboard",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues": {
      "abstract": [
        {
          "text": "An object that contains common types of data that the data detection system matches for a pasteboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DetectedValues"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DetectedValues"
        }
      ],
      "role": "symbol",
      "title": "UIPasteboard.DetectedValues",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/calendarEvents": {
      "abstract": [
        {
          "text": "An array of calendar events that the data detection system identifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarEvents"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchCalendarEvent",
          "text": "DDMatchCalendarEvent"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/calendarEvents",
      "kind": "symbol",
      "role": "symbol",
      "title": "calendarEvents",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/calendarevents"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/emailAddresses": {
      "abstract": [
        {
          "text": "An array of email addresses that the data detection system identifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emailAddresses"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchEmailAddress",
          "text": "DDMatchEmailAddress"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/emailAddresses",
      "kind": "symbol",
      "role": "symbol",
      "title": "emailAddresses",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/emailaddresses"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/flightNumbers": {
      "abstract": [
        {
          "text": "An array of flight numbers that the system data detection system identifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flightNumbers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchFlightNumber",
          "text": "DDMatchFlightNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/flightNumbers",
      "kind": "symbol",
      "role": "symbol",
      "title": "flightNumbers",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/flightnumbers"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/links": {
      "abstract": [
        {
          "text": "An array of web links that the data detection system identifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "links"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchLink",
          "text": "DDMatchLink"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/links",
      "kind": "symbol",
      "role": "symbol",
      "title": "links",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/links"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/moneyAmounts": {
      "abstract": [
        {
          "text": "An array of money amounts and currencies that the data detection system identifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moneyAmounts"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchMoneyAmount",
          "text": "DDMatchMoneyAmount"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/moneyAmounts",
      "kind": "symbol",
      "role": "symbol",
      "title": "moneyAmounts",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/moneyamounts"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/number": {
      "abstract": [
        {
          "text": "A number that the data detection system identifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "number"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/number",
      "kind": "symbol",
      "role": "symbol",
      "title": "number",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/number"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/phoneNumbers": {
      "abstract": [
        {
          "text": "An array of phone numbers that the data detection system identifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phoneNumbers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchPhoneNumber",
          "text": "DDMatchPhoneNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/phoneNumbers",
      "kind": "symbol",
      "role": "symbol",
      "title": "phoneNumbers",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/phonenumbers"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/postalAddresses": {
      "abstract": [
        {
          "text": "An array of postal addresses that the data detection system identifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postalAddresses"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchPostalAddress",
          "text": "DDMatchPostalAddress"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/postalAddresses",
      "kind": "symbol",
      "role": "symbol",
      "title": "postalAddresses",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/postaladdresses"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/shipmentTrackingNumbers": {
      "abstract": [
        {
          "text": "An array of parcel tracking numbers that the data detection system identifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shipmentTrackingNumbers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchShipmentTrackingNumber",
          "text": "DDMatchShipmentTrackingNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/shipmentTrackingNumbers",
      "kind": "symbol",
      "role": "symbol",
      "title": "shipmentTrackingNumbers",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectedvalues/shipmenttrackingnumbers"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)DDMatchEmailAddress": {
      "abstract": [
        {
          "text": "An object that contains an email address that the data detection system matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DDMatchEmailAddress"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)DDMatchEmailAddress",
      "kind": "symbol",
      "role": "symbol",
      "title": "DDMatchEmailAddress",
      "type": "topic",
      "url": "/documentation/DataDetection/DDMatchEmailAddress"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Detected-values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/calendarEvents",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/flightNumbers",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/links",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/moneyAmounts",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/number",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/phoneNumbers",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/postalAddresses",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectedValues/shipmentTrackingNumbers"
      ],
      "title": "Detected values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard/title",
          "value": "UIPasteboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)DDMatchEmailAddress/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DDMatchEmailAddress"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)DDMatch",
              "text": "DDMatch"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uipasteboard/detectedvalues/emailaddresses"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
