{
  "abstract": [
    {
      "text": "An optional setting that tells the algorithm how to scale an input image before generating the feature print.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNGenerateImageFeaturePrintRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNGenerateImageFeaturePrintRequest/imageCropAndScaleOption"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VNGenerateImageFeaturePrintRequest(py)imageCropAndScaleOption",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "imageCropAndScaleOption"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@VNImageCropAndScaleOption",
        "text": "VNImageCropAndScaleOption"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "imageCropAndScaleOption"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "imageCropAndScaleOption"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "imageCropAndScaleOption"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@VNImageCropAndScaleOption",
              "text": "VNImageCropAndScaleOption"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Scaling is applied before generating the feature print. The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFill",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Scaling an image ensures that the entire image fits into the algorithm’s input image dimensions, which may require a change in aspect ratio. Each crop and scale option transforms the input image in a different way:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3261301",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateImageFeaturePrintRequest": {
      "abstract": [
        {
          "text": "An image-based request to generate feature prints from an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNGenerateImageFeaturePrintRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateImageFeaturePrintRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGenerateImageFeaturePrintRequest"
        }
      ],
      "role": "symbol",
      "title": "VNGenerateImageFeaturePrintRequest",
      "type": "topic",
      "url": "/documentation/vision/vngenerateimagefeatureprintrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateImageFeaturePrintRequest/imageCropAndScaleOption": {
      "abstract": [
        {
          "text": "An optional setting that tells the algorithm how to scale an input image before generating the feature print.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageCropAndScaleOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VNImageCropAndScaleOption",
          "text": "VNImageCropAndScaleOption"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateImageFeaturePrintRequest/imageCropAndScaleOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageCropAndScaleOption"
        }
      ],
      "role": "symbol",
      "title": "imageCropAndScaleOption",
      "type": "topic",
      "url": "/documentation/vision/vngenerateimagefeatureprintrequest/imagecropandscaleoption"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption": {
      "abstract": [
        {
          "text": "Options that define how Vision crops and scales an input-image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNImageCropAndScaleOption"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageCropAndScaleOption"
        }
      ],
      "role": "symbol",
      "title": "VNImageCropAndScaleOption",
      "type": "topic",
      "url": "/documentation/vision/vnimagecropandscaleoption"
    },
    "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFill": {
      "abstract": [
        {
          "text": "An option that scales the image to fill the input dimensions, resizing it if necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleFill"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption/scaleFill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNImageCropAndScaleOptionScaleFill"
        }
      ],
      "role": "symbol",
      "title": "VNImageCropAndScaleOption.scaleFill",
      "type": "topic",
      "url": "/documentation/vision/vnimagecropandscaleoption/scalefill"
    },
    "media-3261301": {
      "alt": "A photo of a flower cropped and scaled according to Vision image options",
      "identifier": "media-3261301",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/476a6197148640b76f4b73d478241743/media-3261301@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Scaling-and-Cropping-Images",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption"
      ],
      "title": "Scaling and Cropping Images"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "imageCropAndScaleOption"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageCropAndScaleOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision",
                "doc://com.apple.vision/documentation/Vision/VNGenerateImageFeaturePrintRequest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Scaling-and-Cropping-Images",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption"
              ],
              "title": "Scaling and Cropping Images"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readwrite"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNImageCropAndScaleOption",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@VNImageCropAndScaleOption",
                    "text": "VNImageCropAndScaleOption"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "imageCropAndScaleOption"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption/title",
          "value": "VNImageCropAndScaleOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateImageFeaturePrintRequest/title",
          "value": "VNGenerateImageFeaturePrintRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateImageFeaturePrintRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateImageFeaturePrintRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateImageFeaturePrintRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateImageFeaturePrintRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateImageFeaturePrintRequest~1imageCropAndScaleOption/title",
          "value": "imageCropAndScaleOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateImageFeaturePrintRequest~1imageCropAndScaleOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageCropAndScaleOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1scaleFill/title",
          "value": "VNImageCropAndScaleOptionScaleFill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNImageCropAndScaleOption~1scaleFill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNImageCropAndScaleOptionScaleFill"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vngenerateimagefeatureprintrequest/imagecropandscaleoption"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vngenerateimagefeatureprintrequest/imagecropandscaleoption"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
