{
  "abstract": [
    {
      "text": "Moves the child collections at the specified indexes in the collection list to a new index.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/moveChildCollections(at:to:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHCollectionListChangeRequest(im)moveChildCollectionsAtIndexes:toIndex:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "moveChildCollections"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "at"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation8IndexSetV",
        "text": "IndexSet"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "to"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "moveChildCollectionsAtIndexes:toIndex:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "moveChildCollections(at:to:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "moveChildCollections"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "at"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "indexes"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation8IndexSetV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation8IndexSetV",
              "text": "IndexSet"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "to"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "toIndex"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The indexes of the child collections to be moved in the collection list.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "indexes"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The index at which to place the moved child collections, relative to the collection list’s ordering after removing the items at ",
                  "type": "text"
                },
                {
                  "code": "indexes",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "toIndex"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you call this method, Photos first removes the items in the ",
              "type": "text"
            },
            {
              "code": "indexes",
              "type": "codeVoice"
            },
            {
              "text": " parameter from the collection, and then inserts them at the location specified by the ",
              "type": "text"
            },
            {
              "code": "toIndex",
              "type": "codeVoice"
            },
            {
              "text": " parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To ensure that the index set you specify is valid even if the collection list has changed since you fetched it, create a change request with a snapshot of the collection list’s contents using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/init(for:childCollections:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method before rearranging child collections.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest": {
      "abstract": [
        {
          "text": "A request to create, delete, or modify a Photos collection list, for use in a photo library change block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHCollectionListChangeRequest"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionListChangeRequest"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionListChangeRequest",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlistchangerequest"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/addChildCollections(_:)": {
      "abstract": [
        {
          "text": "Adds the specified collections as children of the collection list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addChildCollections"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSFastEnumeration",
          "text": "NSFastEnumeration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/addChildCollections(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addChildCollections:"
        }
      ],
      "role": "symbol",
      "title": "addChildCollections(_:)",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlistchangerequest/addchildcollections(_:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/init(for:childCollections:)": {
      "abstract": [
        {
          "text": "Creates a request for modifying the specified collection list, with a fetch result for tracking changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHCollectionList",
          "text": "PHCollectionList"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "childCollections"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchResult",
          "text": "PHFetchResult"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHCollection",
          "text": "PHCollection"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/init(for:childCollections:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changeRequestForCollectionList:childCollections:"
        }
      ],
      "role": "symbol",
      "title": "init(for:childCollections:)",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlistchangerequest/init(for:childcollections:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/insertChildCollections(_:at:)": {
      "abstract": [
        {
          "text": "Inserts the specified collections into the collection list at the specified indexes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertChildCollections"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSFastEnumeration",
          "text": "NSFastEnumeration"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/insertChildCollections(_:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "insertChildCollections:atIndexes:"
        }
      ],
      "role": "symbol",
      "title": "insertChildCollections(_:at:)",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlistchangerequest/insertchildcollections(_:at:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/moveChildCollections(at:to:)": {
      "abstract": [
        {
          "text": "Moves the child collections at the specified indexes in the collection list to a new index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moveChildCollections"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/moveChildCollections(at:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "moveChildCollectionsAtIndexes:toIndex:"
        }
      ],
      "role": "symbol",
      "title": "moveChildCollections(at:to:)",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlistchangerequest/movechildcollections(at:to:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/removeChildCollections(_:)": {
      "abstract": [
        {
          "text": "Removes the specified child collections from the collection list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeChildCollections"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSFastEnumeration",
          "text": "NSFastEnumeration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/removeChildCollections(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeChildCollections:"
        }
      ],
      "role": "symbol",
      "title": "removeChildCollections(_:)",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlistchangerequest/removechildcollections(_:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/removeChildCollections(at:)": {
      "abstract": [
        {
          "text": "Removes the child collections at the specified indexes from the collection list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeChildCollections"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/removeChildCollections(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeChildCollectionsAtIndexes:"
        }
      ],
      "role": "symbol",
      "title": "removeChildCollections(at:)",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlistchangerequest/removechildcollections(at:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/replaceChildCollections(at:withChildCollections:)": {
      "abstract": [
        {
          "text": "Replaces the child collections at the specified indexes in the collection list with the specified collections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replaceChildCollections"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withChildCollections"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSFastEnumeration",
          "text": "NSFastEnumeration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/replaceChildCollections(at:withChildCollections:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replaceChildCollectionsAtIndexes:withChildCollections:"
        }
      ],
      "role": "symbol",
      "title": "replaceChildCollections(at:withChildCollections:)",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlistchangerequest/replacechildcollections(at:withchildcollections:)"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation8IndexSetV": {
      "abstract": [
        {
          "text": "A collection of unique integer values that represent the indexes of elements in another collection. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "IndexSet"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation8IndexSetV",
      "kind": "symbol",
      "role": "symbol",
      "title": "IndexSet",
      "type": "topic",
      "url": "/documentation/foundation/indexset"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Collections",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/addChildCollections(_:)",
        "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/insertChildCollections(_:at:)",
        "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/replaceChildCollections(at:withChildCollections:)",
        "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/removeChildCollections(_:)",
        "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/removeChildCollections(at:)"
      ],
      "title": "Managing Collections"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "moveChildCollectionsAtIndexes:toIndex:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "moveChildCollectionsAtIndexes:toIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos",
                "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Collections",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/addChildCollections(_:)",
                "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/insertChildCollections(_:at:)",
                "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/replaceChildCollections(at:withChildCollections:)",
                "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/removeChildCollections(_:)",
                "doc://com.apple.photokit/documentation/Photos/PHCollectionListChangeRequest/removeChildCollections(at:)"
              ],
              "title": "Managing Collections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "moveChildCollectionsAtIndexes:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSIndexSet",
                    "text": "NSIndexSet"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "indexes"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "toIndex:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "toIndex"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The indexes of the child collections to be moved in the collection list.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "indexes"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The index at which to place the moved child collections, relative to the collection list’s ordering after removing the items at ",
                        "type": "text"
                      },
                      {
                        "code": "indexes",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "toIndex"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest~1removeChildCollections(at:)/title",
          "value": "removeChildCollectionsAtIndexes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest~1removeChildCollections(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeChildCollectionsAtIndexes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest~1init(for:childCollections:)/title",
          "value": "changeRequestForCollectionList:childCollections:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest~1init(for:childCollections:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "changeRequestForCollectionList:childCollections:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest~1replaceChildCollections(at:withChildCollections:)/title",
          "value": "replaceChildCollectionsAtIndexes:withChildCollections:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest~1replaceChildCollections(at:withChildCollections:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replaceChildCollectionsAtIndexes:withChildCollections:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest~1removeChildCollections(_:)/title",
          "value": "removeChildCollections:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest~1removeChildCollections(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeChildCollections:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest~1addChildCollections(_:)/title",
          "value": "addChildCollections:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest~1addChildCollections(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addChildCollections:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest~1insertChildCollections(_:at:)/title",
          "value": "insertChildCollections:atIndexes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest~1insertChildCollections(_:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "insertChildCollections:atIndexes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest/title",
          "value": "PHCollectionListChangeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionListChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionListChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest~1moveChildCollections(at:to:)/title",
          "value": "moveChildCollectionsAtIndexes:toIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionListChangeRequest~1moveChildCollections(at:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "moveChildCollectionsAtIndexes:toIndex:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phcollectionlistchangerequest/movechildcollections(at:to:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phcollectionlistchangerequest/movechildcollections(at:to:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
