{"sections":[],"kind":"symbol","seeAlsoSections":[{"title":"Managing Input from the Digital Crown","identifiers":["doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/resignFocus()"],"generated":true,"anchor":"Managing-Input-from-the-Digital-Crown"}],"abstract":[{"text":"Configures the picker to receive input from the Digital Crown.","type":"text"}],"metadata":{"platforms":[{"unavailable":false,"beta":false,"name":"watchOS","introducedAt":"2.0","deprecated":false}],"roleHeading":"Instance Method","title":"focus()","navigatorTitle":[{"kind":"identifier","text":"focus"}],"externalID":"c:objc(cs)WKInterfacePicker(im)focus","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"focus"},{"kind":"text","text":"()"}],"modules":[{"name":"WatchKit"}]},"variants":[{"paths":["/documentation/watchkit/wkinterfacepicker/focus()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/watchkit/wkinterfacepicker/focus()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/focus()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.watchkit/documentation/WatchKit","doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker"]]},"primaryContentSections":[{"declarations":[{"platforms":["watchOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"focus"},{"kind":"text","text":"()"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"The picker adds custom highlighting when it is configured as the target of crown input. For an interface that contains multiple pickers, you might use this method to switch the focus at an appropriate time. Because scrolling in an interface controller causes the picker to lose focus, you can also use this method to select the picker again later.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"WKInterfacePicker","kind":"identifier"}],"navigatorTitle":[{"text":"WKInterfacePicker","kind":"identifier"}],"abstract":[{"type":"text","text":"An interface element that presents a scrolling list of items for the user to choose from."}],"role":"symbol","type":"topic","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker","title":"WKInterfacePicker","url":"/documentation/watchkit/wkinterfacepicker"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/resignFocus()":{"title":"resignFocus()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resignFocus","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"Removes focus from the picker, causing it to stop receiving input from the Digital Crown.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"resignFocus","kind":"identifier"}],"identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/resignFocus()","url":"/documentation/watchkit/wkinterfacepicker/resignfocus()","kind":"symbol"},"doc://com.apple.watchkit/documentation/WatchKit":{"kind":"symbol","abstract":[{"type":"text","text":"Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions."}],"role":"collection","type":"topic","identifier":"doc://com.apple.watchkit/documentation/WatchKit","title":"WatchKit","url":"/documentation/watchkit"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","abstract":[{"type":"text","text":""}],"role":"overview","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/focus()":{"navigatorTitle":[{"kind":"identifier","text":"focus"}],"title":"focus()","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/focus()","abstract":[{"text":"Configures the picker to receive input from the Digital Crown.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"focus"},{"kind":"text","text":"()"}],"url":"/documentation/watchkit/wkinterfacepicker/focus()"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"introducedAt":"2.0","beta":false,"deprecated":false,"unavailable":false,"name":"watchOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"focus","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"focus","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.watchkit/documentation/WatchKit","doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker"]]},"op":"replace"},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Managing Input from the Digital Crown","anchor":"Managing-Input-from-the-Digital-Crown","identifiers":["doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/resignFocus()"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["watchOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"focus"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker/title","op":"replace","value":"WKInterfacePicker"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker/fragments","op":"replace","value":[{"text":"WKInterfacePicker","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"WKInterfacePicker"}]},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker~1resignFocus()/title","op":"replace","value":"resignFocus"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker~1resignFocus()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"resignFocus","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker~1focus()/title","op":"replace","value":"focus"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker~1focus()/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"focus"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}