{"sections":[],"metadata":{"roleHeading":"Instance Method","platforms":[{"deprecated":false,"name":"watchOS","unavailable":false,"introducedAt":"2.0","beta":false}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"resignFocus"},{"kind":"text","text":"()"}],"modules":[{"name":"WatchKit"}],"title":"resignFocus()","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)WKInterfacePicker(im)resignFocus","navigatorTitle":[{"kind":"identifier","text":"resignFocus"}]},"abstract":[{"text":"Removes focus from the picker, causing it to stop receiving input from the Digital Crown.","type":"text"}],"kind":"symbol","variants":[{"paths":["/documentation/watchkit/wkinterfacepicker/resignfocus()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/watchkit/wkinterfacepicker/resignfocus()"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/focus()"],"generated":true,"anchor":"Managing-Input-from-the-Digital-Crown","title":"Managing Input from the Digital Crown"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/resignFocus()"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resignFocus"},{"kind":"text","text":"()"}],"platforms":["watchOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"Discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"When no picker has focus, input from the Digital Crown is once again used to scroll the contents of the screen."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.watchkit/documentation/WatchKit","doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker"]]},"references":{"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/resignFocus()":{"title":"resignFocus()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resignFocus","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"Removes focus from the picker, causing it to stop receiving input from the Digital Crown.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"resignFocus","kind":"identifier"}],"identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/resignFocus()","url":"/documentation/watchkit/wkinterfacepicker/resignfocus()","kind":"symbol"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/focus()":{"navigatorTitle":[{"kind":"identifier","text":"focus"}],"title":"focus()","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/focus()","abstract":[{"text":"Configures the picker to receive input from the Digital Crown.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"focus"},{"kind":"text","text":"()"}],"url":"/documentation/watchkit/wkinterfacepicker/focus()"},"doc://com.apple.watchkit/documentation/WatchKit":{"kind":"symbol","abstract":[{"type":"text","text":"Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions."}],"role":"collection","type":"topic","identifier":"doc://com.apple.watchkit/documentation/WatchKit","title":"WatchKit","url":"/documentation/watchkit"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","abstract":[{"type":"text","text":""}],"role":"overview","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"WKInterfacePicker","kind":"identifier"}],"navigatorTitle":[{"text":"WKInterfacePicker","kind":"identifier"}],"abstract":[{"type":"text","text":"An interface element that presents a scrolling list of items for the user to choose from."}],"role":"symbol","type":"topic","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker","title":"WKInterfacePicker","url":"/documentation/watchkit/wkinterfacepicker"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"watchOS","deprecated":false,"introducedAt":"2.0","beta":false,"unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"resignFocus","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resignFocus"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.watchkit/documentation/WatchKit","doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"anchor":"Managing-Input-from-the-Digital-Crown","title":"Managing Input from the Digital Crown","identifiers":["doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/focus()"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"platforms":["watchOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"resignFocus"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker~1resignFocus()/title","op":"replace","value":"resignFocus"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker~1resignFocus()/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resignFocus"}]},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker~1focus()/title","op":"replace","value":"focus"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker~1focus()/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"focus"}]},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker/title","op":"replace","value":"WKInterfacePicker"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker/fragments","op":"replace","value":[{"text":"WKInterfacePicker","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker/navigatorTitle","op":"replace","value":[{"text":"WKInterfacePicker","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}