{"abstract":[{"type":"text","text":"Selects the specified item in the list."}],"seeAlsoSections":[{"title":"Managing the Picker Contents","identifiers":["doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/setItems(_:)","doc://com.apple.watchkit/documentation/WatchKit/WKPickerItem","doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/setCoordinatedAnimations(_:)"],"generated":true,"anchor":"Managing-the-Picker-Contents"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/setSelectedItemIndex(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["watchOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setSelectedItemIndex","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"itemIndex","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"itemIndex","content":[{"inlineContent":[{"text":"The index of the item to select. This index represents the index into the array of items you set using the ","type":"text"},{"type":"reference","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/setItems(_:)","isActive":true},{"text":" method.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If the value in "},{"type":"codeVoice","code":"itemIndex"},{"type":"text","text":" exceeds the number of items in the array, the picker selects the last item. If "},{"type":"codeVoice","code":"itemIndex"},{"type":"text","text":" is negative, the picker selects the first item in the array."}]}],"kind":"content"}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.watchkit/documentation/WatchKit","doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/watchkit/wkinterfacepicker/setselecteditemindex(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/watchkit/wkinterfacepicker/setselecteditemindex(_:)"]}],"metadata":{"modules":[{"name":"WatchKit"}],"symbolKind":"method","navigatorTitle":[{"text":"setSelectedItemIndex:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)WKInterfacePicker(im)setSelectedItemIndex:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSelectedItemIndex"},{"kind":"text","text":"("},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"setSelectedItemIndex(_:)","platforms":[{"name":"watchOS","introducedAt":"2.0","unavailable":false,"deprecated":false,"beta":false}],"role":"symbol"},"references":{"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","abstract":[{"type":"text","text":""}],"role":"overview","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/setItems(_:)":{"identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/setItems(_:)","title":"setItems(_:)","type":"topic","url":"/documentation/watchkit/wkinterfacepicker/setitems(_:)","abstract":[{"text":"Sets the list of items displayed by the picker.","type":"text"}],"navigatorTitle":[{"text":"setItems:","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setItems"},{"kind":"text","text":"(["},{"text":"WKPickerItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKPickerItem"},{"text":"]?)","kind":"text"}]},"doc://com.apple.watchkit/documentation/WatchKit":{"kind":"symbol","abstract":[{"type":"text","text":"Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions."}],"role":"collection","type":"topic","identifier":"doc://com.apple.watchkit/documentation/WatchKit","title":"WatchKit","url":"/documentation/watchkit"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/setSelectedItemIndex(_:)":{"abstract":[{"type":"text","text":"Selects the specified item in the list."}],"role":"symbol","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/setSelectedItemIndex(_:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSelectedItemIndex"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"title":"setSelectedItemIndex(_:)","navigatorTitle":[{"kind":"identifier","text":"setSelectedItemIndex:"}],"url":"/documentation/watchkit/wkinterfacepicker/setselecteditemindex(_:)"},"doc://com.apple.watchkit/documentation/WatchKit/WKPickerItem":{"kind":"symbol","type":"topic","title":"WKPickerItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WKPickerItem"}],"navigatorTitle":[{"kind":"identifier","text":"WKPickerItem"}],"url":"/documentation/watchkit/wkpickeritem","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKPickerItem","role":"symbol","abstract":[{"type":"text","text":"A single item in a picker interface."}]},"doc://com.externally.resolved.symbol/s:Si":{"role":"symbol","url":"/documentation/Swift/Int","type":"topic","kind":"symbol","title":"Int","abstract":[{"text":"A signed integer value type.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:Si","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Int","kind":"identifier"}]},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"WKInterfacePicker","kind":"identifier"}],"navigatorTitle":[{"text":"WKInterfacePicker","kind":"identifier"}],"abstract":[{"type":"text","text":"An interface element that presents a scrolling list of items for the user to choose from."}],"role":"symbol","type":"topic","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker","title":"WKInterfacePicker","url":"/documentation/watchkit/wkinterfacepicker"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/setCoordinatedAnimations(_:)":{"url":"/documentation/watchkit/wkinterfacepicker/setcoordinatedanimations(_:)","type":"topic","abstract":[{"type":"text","text":"Sets the interface objects that should coordinate their own animations with the picker."}],"title":"setCoordinatedAnimations(_:)","role":"symbol","kind":"symbol","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/setCoordinatedAnimations(_:)","navigatorTitle":[{"text":"setCoordinatedAnimations:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCoordinatedAnimations","kind":"identifier"},{"text":"([any ","kind":"text"},{"text":"WKInterfaceObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKInterfaceObject"},{"text":" & ","kind":"text"},{"text":"WKImageAnimatable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)WKImageAnimatable"},{"text":"]?)","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"2.0","name":"watchOS","deprecated":false,"unavailable":false,"beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"setSelectedItemIndex:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSelectedItemIndex:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.watchkit/documentation/WatchKit","doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker"]]}},{"op":"add","path":"/topicSections","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Managing the Picker Contents","anchor":"Managing-the-Picker-Contents","generated":true,"identifiers":["doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/setItems(_:)","doc://com.apple.watchkit/documentation/WatchKit/WKPickerItem","doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/setCoordinatedAnimations(_:)"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setSelectedItemIndex:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"itemIndex","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["watchOS"]}]}},{"value":{"kind":"parameters","parameters":[{"name":"itemIndex","content":[{"inlineContent":[{"text":"The index of the item to select. This index represents the index into the array of items you set using the ","type":"text"},{"identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfacePicker/setItems(_:)","type":"reference","isActive":true},{"text":" method.","type":"text"}],"type":"paragraph"}]}]},"op":"replace","path":"/primaryContentSections/1"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker~1setItems(_:)/title","op":"replace","value":"setItems:"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker~1setItems(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setItems:"}]},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker~1setSelectedItemIndex(_:)/title","op":"replace","value":"setSelectedItemIndex:"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker~1setSelectedItemIndex(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setSelectedItemIndex:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKPickerItem/title","op":"replace","value":"WKPickerItem"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKPickerItem/fragments","op":"replace","value":[{"text":"WKPickerItem","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKPickerItem/navigatorTitle","op":"replace","value":[{"text":"WKPickerItem","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker/title","op":"replace","value":"WKInterfacePicker"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker/fragments","op":"replace","value":[{"text":"WKInterfacePicker","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker/navigatorTitle","value":[{"text":"WKInterfacePicker","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker~1setCoordinatedAnimations(_:)/title","value":"setCoordinatedAnimations:"},{"op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfacePicker~1setCoordinatedAnimations(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCoordinatedAnimations:"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}