{
  "abstract": [
    {
      "text": "An audio stream sink that defines how the host handles audio data produced by the guest.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceOutputStreamConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceOutputStreamConfiguration/sink"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VZVirtioSoundDeviceOutputStreamConfiguration(py)sink",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sink"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)VZAudioOutputStreamSink",
        "text": "VZAudioOutputStreamSink"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sink"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "sink"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sink"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZAudioOutputStreamSink",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)VZAudioOutputStreamSink",
              "text": "VZAudioOutputStreamSink"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Not specifying a sink results in a default handler that suppresses the audio. The default is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZAudioOutputStreamSink": {
      "abstract": [
        {
          "text": "The base class for an audio output stream sink.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZAudioOutputStreamSink"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZAudioOutputStreamSink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZAudioOutputStreamSink"
        }
      ],
      "role": "symbol",
      "title": "VZAudioOutputStreamSink",
      "type": "topic",
      "url": "/documentation/virtualization/vzaudiooutputstreamsink"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZHostAudioOutputStreamSink": {
      "abstract": [
        {
          "text": "Host audio output stream sink plays audio to the host system’s default output device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZHostAudioOutputStreamSink"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZHostAudioOutputStreamSink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZHostAudioOutputStreamSink"
        }
      ],
      "role": "symbol",
      "title": "VZHostAudioOutputStreamSink",
      "type": "topic",
      "url": "/documentation/virtualization/vzhostaudiooutputstreamsink"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceOutputStreamConfiguration": {
      "abstract": [
        {
          "text": "An object that defines a Virtio sound device output stream configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioSoundDeviceOutputStreamConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceOutputStreamConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioSoundDeviceOutputStreamConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioSoundDeviceOutputStreamConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtiosounddeviceoutputstreamconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceOutputStreamConfiguration/sink": {
      "abstract": [
        {
          "text": "An audio stream sink that defines how the host handles audio data produced by the guest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZAudioOutputStreamSink",
          "text": "VZAudioOutputStreamSink"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceOutputStreamConfiguration/sink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sink"
        }
      ],
      "role": "symbol",
      "title": "sink",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtiosounddeviceoutputstreamconfiguration/sink"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZAudioOutputStreamSink",
        "doc://com.apple.virtualization/documentation/Virtualization/VZHostAudioOutputStreamSink"
      ],
      "title": "Related Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "sink"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.virtualization/documentation/Virtualization",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioSoundDeviceOutputStreamConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZAudioOutputStreamSink",
                "doc://com.apple.virtualization/documentation/Virtualization/VZHostAudioOutputStreamSink"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZAudioOutputStreamSink",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VZAudioOutputStreamSink",
                    "text": "VZAudioOutputStreamSink"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "sink"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceOutputStreamConfiguration/title",
          "value": "VZVirtioSoundDeviceOutputStreamConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceOutputStreamConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSoundDeviceOutputStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceOutputStreamConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioSoundDeviceOutputStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZHostAudioOutputStreamSink/title",
          "value": "VZHostAudioOutputStreamSink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZHostAudioOutputStreamSink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZHostAudioOutputStreamSink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZHostAudioOutputStreamSink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZHostAudioOutputStreamSink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZAudioOutputStreamSink/title",
          "value": "VZAudioOutputStreamSink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZAudioOutputStreamSink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZAudioOutputStreamSink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZAudioOutputStreamSink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZAudioOutputStreamSink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceOutputStreamConfiguration~1sink/title",
          "value": "sink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioSoundDeviceOutputStreamConfiguration~1sink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sink"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzvirtiosounddeviceoutputstreamconfiguration/sink"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/vzvirtiosounddeviceoutputstreamconfiguration/sink"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
