{
  "abstract": [
    {
      "text": "No biometry type is supported.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/none"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@LABiometryType@LABiometryTypeNone",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "none"
      }
    ],
    "modules": [
      {
        "name": "Local Authentication"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LABiometryTypeNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "LABiometryType.none"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "none"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication": {
      "abstract": [
        {
          "text": "Authenticate users biometrically or with a passphrase they already know.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication",
      "kind": "symbol",
      "role": "collection",
      "title": "Local Authentication",
      "type": "topic",
      "url": "/documentation/localauthentication"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType": {
      "abstract": [
        {
          "text": "The set of available biometric authentication types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LABiometryType"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LABiometryType"
        }
      ],
      "role": "symbol",
      "title": "LABiometryType",
      "type": "topic",
      "url": "/documentation/localauthentication/labiometrytype"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/faceID": {
      "abstract": [
        {
          "text": "The device supports Face ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faceID"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/faceID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LABiometryTypeFaceID"
        }
      ],
      "role": "symbol",
      "title": "LABiometryType.faceID",
      "type": "topic",
      "url": "/documentation/localauthentication/labiometrytype/faceid"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/none": {
      "abstract": [
        {
          "text": "No biometry type is supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LABiometryTypeNone"
        }
      ],
      "role": "symbol",
      "title": "LABiometryType.none",
      "type": "topic",
      "url": "/documentation/localauthentication/labiometrytype/none"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/opticID": {
      "abstract": [
        {
          "text": "The device supports Optic ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opticID"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/opticID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LABiometryTypeOpticID"
        }
      ],
      "role": "symbol",
      "title": "LABiometryType.opticID",
      "type": "topic",
      "url": "/documentation/localauthentication/labiometrytype/opticid"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/touchID": {
      "abstract": [
        {
          "text": "The device supports Touch ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchID"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/touchID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LABiometryTypeTouchID"
        }
      ],
      "role": "symbol",
      "title": "LABiometryType.touchID",
      "type": "topic",
      "url": "/documentation/localauthentication/labiometrytype/touchid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/faceID",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/touchID",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/opticID"
      ],
      "title": "Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LABiometryTypeNone"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LABiometryTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/faceID",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/touchID",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LABiometryType/opticID"
              ],
              "title": "Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "LABiometryTypeNone"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType~1touchID/title",
          "value": "LABiometryTypeTouchID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType~1touchID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LABiometryTypeTouchID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType~1faceID/title",
          "value": "LABiometryTypeFaceID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType~1faceID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LABiometryTypeFaceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType~1none/title",
          "value": "LABiometryTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LABiometryTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType~1opticID/title",
          "value": "LABiometryTypeOpticID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType~1opticID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LABiometryTypeOpticID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType/title",
          "value": "LABiometryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LABiometryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LABiometryType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LABiometryType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/localauthentication/labiometrytype/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/localauthentication/labiometrytype/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
