{
  "abstract": [
    {
      "text": "Layout direction is left to right.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutDirection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutDirection/leftToRight"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSUserInterfaceLayoutDirection@NSUserInterfaceLayoutDirectionLeftToRight",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "leftToRight"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSUserInterfaceLayoutDirectionLeftToRight"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSUserInterfaceLayoutDirection.leftToRight"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "leftToRight"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutDirection": {
      "abstract": [
        {
          "text": "Specifies the directional flow of the user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceLayoutDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserInterfaceLayoutDirection"
        }
      ],
      "role": "symbol",
      "title": "NSUserInterfaceLayoutDirection",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfacelayoutdirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutDirection/leftToRight": {
      "abstract": [
        {
          "text": "Layout direction is left to right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftToRight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutDirection/leftToRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserInterfaceLayoutDirectionLeftToRight"
        }
      ],
      "role": "symbol",
      "title": "NSUserInterfaceLayoutDirection.leftToRight",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfacelayoutdirection/lefttoright"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutDirection/rightToLeft": {
      "abstract": [
        {
          "text": "Layout direction is right to left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightToLeft"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutDirection/rightToLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserInterfaceLayoutDirectionRightToLeft"
        }
      ],
      "role": "symbol",
      "title": "NSUserInterfaceLayoutDirection.rightToLeft",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfacelayoutdirection/righttoleft"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutDirection/rightToLeft"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSUserInterfaceLayoutDirectionLeftToRight"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceLayoutDirectionLeftToRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutDirection"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutDirection/rightToLeft"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSUserInterfaceLayoutDirectionLeftToRight"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutDirection/title",
          "value": "NSUserInterfaceLayoutDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceLayoutDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceLayoutDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutDirection~1leftToRight/title",
          "value": "NSUserInterfaceLayoutDirectionLeftToRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutDirection~1leftToRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceLayoutDirectionLeftToRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutDirection~1rightToLeft/title",
          "value": "NSUserInterfaceLayoutDirectionRightToLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutDirection~1rightToLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceLayoutDirectionRightToLeft"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsuserinterfacelayoutdirection/lefttoright"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsuserinterfacelayoutdirection/lefttoright"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
