{
  "abstract": [
    {
      "text": "Creates a text view that displays styled attributed content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.SwiftUI/documentation/SwiftUI",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/Text"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-1a4oh"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SwiftUI",
    "externalID": "s:7SwiftUI4TextVyAC10Foundation16AttributedStringVcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation16AttributedStringV",
        "text": "AttributedString"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "SwiftUI"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "otherDeclarations": {
            "declarations": [
              {
                "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-4k7ab",
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "init"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "internalParam",
                    "text": "dates"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.externally.resolved.symbol/s:SN",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:SN",
                    "text": "ClosedRange"
                  },
                  {
                    "highlight": "changed",
                    "kind": "text",
                    "text": "<"
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DateV",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:10Foundation4DateV",
                    "text": "Date"
                  },
                  {
                    "highlight": "changed",
                    "kind": "text",
                    "text": ">"
                  },
                  {
                    "kind": "text",
                    "text": ")"
                  }
                ]
              },
              {
                "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-60ax7",
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "init"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "internalParam",
                    "text": "image"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Image",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:7SwiftUI5ImageV",
                    "text": "Image"
                  },
                  {
                    "kind": "text",
                    "text": ")"
                  }
                ]
              },
              {
                "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-56n81",
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "init"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "internalParam",
                    "text": "interval"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.externally.resolved.symbol/s:10Foundation12DateIntervalV",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:10Foundation12DateIntervalV",
                    "text": "DateInterval"
                  },
                  {
                    "kind": "text",
                    "text": ")"
                  }
                ]
              },
              {
                "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-1s6o1",
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "init"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "internalParam",
                    "text": "resource"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.externally.resolved.symbol/s:10Foundation23LocalizedStringResourceV",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:10Foundation23LocalizedStringResourceV",
                    "text": "LocalizedStringResource"
                  },
                  {
                    "kind": "text",
                    "text": ")"
                  }
                ]
              },
              {
                "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-9d1g4",
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "init"
                  },
                  {
                    "highlight": "changed",
                    "kind": "text",
                    "text": "<"
                  },
                  {
                    "highlight": "changed",
                    "kind": "genericParameter",
                    "text": "S"
                  },
                  {
                    "highlight": "changed",
                    "kind": "text",
                    "text": ">"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "internalParam",
                    "text": "content"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "highlight": "changed",
                    "kind": "typeIdentifier",
                    "text": "S"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "highlight": "changed",
                    "kind": "keyword",
                    "text": "where"
                  },
                  {
                    "highlight": "changed",
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "highlight": "changed",
                    "kind": "typeIdentifier",
                    "text": "S"
                  },
                  {
                    "highlight": "changed",
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.externally.resolved.symbol/s:Sy",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:Sy",
                    "text": "StringProtocol"
                  }
                ]
              }
            ],
            "displayIndex": 0
          },
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "highlight": "changed",
              "kind": "internalParam",
              "text": "attributedContent"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "highlight": "changed",
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation16AttributedStringV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation16AttributedStringV",
              "text": "AttributedString"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An attributed string to style and display,",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "in accordance with its attributes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "attributedContent"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this initializer to style text according to attributes found in the specified",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/attributedstring",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Attributes in the attributed string take precedence over styles added by",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "view modifiers. For example, the attributed text in the following",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "example appears in blue, despite the use of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/foregroundColor(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "modifier to use red throughout the enclosing ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/VStack",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var content: AttributedString {",
            "    var attributedString = AttributedString(\"Blue text\")",
            "    attributedString.foregroundColor = .blue",
            "    return attributedString",
            "}",
            "",
            "var body: some View {",
            "    VStack {",
            "        Text(content)",
            "        Text(\"Red text\")",
            "    }",
            "    .foregroundColor(.red)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "identifier": "SwiftUI-Text-init-attributed.png",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "SwiftUI combines text attributes with SwiftUI modifiers whenever",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "possible. For example, the following listing creates text that is",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "both bold and red:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var content: AttributedString {",
            "    var content = AttributedString(\"Some text\")",
            "    content.inlinePresentationIntent = .stronglyEmphasized",
            "    return content",
            "}",
            "",
            "var body: some View {",
            "    Text(content).foregroundColor(Color.red)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "A SwiftUI ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " view renders most of the styles defined by the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Foundation attribute",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes/3796123-inlinepresentationintent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", like the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3746899-stronglyemphasized",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "value, which SwiftUI presents as bold text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " uses only a subset of the attributes defined in",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "code": "Text",
                  "type": "codeVoice"
                },
                {
                  "text": " renders all",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/inlinepresentationintent",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "attributes except for",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3787563-linebreak",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3787564-softbreak",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "It also renders the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes/3764633-link",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "attribute as a clickable link. ",
                  "type": "text"
                },
                {
                  "code": "Text",
                  "type": "codeVoice"
                },
                {
                  "text": " ignores any other",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Foundation-defined attributes in an attributed string.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "SwiftUI also defines additional attributes in the attribute scope",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/attributescopes/swiftuiattributes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "which you can access from an attributed string’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/attributescopes/3788543-swiftui",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "property. SwiftUI attributes take precedence over equivalent attributes",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "from other frameworks, such as",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/attributescopes/uikitattributes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/attributescopes/appkitattributes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can create an ",
              "type": "text"
            },
            {
              "code": "AttributedString",
              "type": "codeVoice"
            },
            {
              "text": " with Markdown syntax, which allows",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you to style distinct runs within a ",
              "type": "text"
            },
            {
              "code": "Text",
              "type": "codeVoice"
            },
            {
              "text": " view:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let content = try! AttributedString(",
            "    markdown: \"**Thank You!** Please visit our [website](http://example.com).\")",
            "",
            "var body: some View {",
            "    Text(content)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "**",
              "type": "codeVoice"
            },
            {
              "text": " syntax around “Thank You!” applies an",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes/3796123-inlinepresentationintent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "attribute with the value",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3746899-stronglyemphasized",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "SwiftUI renders this as",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "bold text, as described earlier. The link syntax around “website”",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "creates a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes/3764633-link",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "attribute, which ",
              "type": "text"
            },
            {
              "code": "Text",
              "type": "codeVoice"
            },
            {
              "text": " styles to indicate it’s a link; by default,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "clicking or tapping the link opens the linked URL in the user’s default",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "browser. Alternatively, you can perform custom link handling by putting",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/OpenURLAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in the text view’s environment.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "SwiftUI-Text-init-markdown.png",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can also use Markdown syntax in localized string keys, which means",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you can write the above example without needing to explicitly create",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "an ",
              "type": "text"
            },
            {
              "code": "AttributedString",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var body: some View {",
            "    Text(\"**Thank You!** Please visit our [website](https://example.com).\")",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In your app’s strings files, use Markdown syntax to apply styling",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to the app’s localized strings. You also use this approach when you want",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to perform automatic grammar agreement on localized strings, with",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the ",
              "type": "text"
            },
            {
              "code": "^[text](inflect:true)",
              "type": "codeVoice"
            },
            {
              "text": " syntax.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For details about Markdown syntax support in SwiftUI, see",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:tableName:bundle:comment:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "SwiftUI-PageImage-card.png": {
      "alt": "A black Swift logo on a swirly blue and purple background.",
      "identifier": "SwiftUI-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b1de0de086f81a5d0eac3839a0af6e6f/SwiftUI-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1450d0b30a6b024e10c148e3f31dafe9/SwiftUI-PageImage-card~dark@2x.png"
        }
      ]
    },
    "SwiftUI-Text-init-attributed.png": {
      "alt": "A vertical stack of two text views, the top labeled Blue Text with a",
      "identifier": "SwiftUI-Text-init-attributed.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/0e75f9a9c2cd81bdb1086e94efdc2417/SwiftUI-Text-init-attributed@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6dbd29384e0436ded2cc4c1020a34e5f/SwiftUI-Text-init-attributed~dark@2x.png"
        }
      ]
    },
    "SwiftUI-Text-init-markdown.png": {
      "alt": "A text view that says Thank you. Please visit our website. The text",
      "identifier": "SwiftUI-Text-init-markdown.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e5680bbca5ad5a5f2779dea53103d8ca/SwiftUI-Text-init-markdown@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/f346510a8513a20208edc3ec8096a012/SwiftUI-Text-init-markdown~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI": {
      "abstract": [
        {
          "text": "Declare the user interface and behavior for your app on every platform.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI",
      "images": [
        {
          "identifier": "SwiftUI-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "SwiftUI",
      "type": "topic",
      "url": "/documentation/swiftui"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/Image": {
      "abstract": [
        {
          "text": "A view that displays an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Image"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Image",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Image"
        }
      ],
      "role": "symbol",
      "title": "Image",
      "type": "topic",
      "url": "/documentation/swiftui/image"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/OpenURLAction": {
      "abstract": [
        {
          "text": "An action that opens a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OpenURLAction"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/OpenURLAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OpenURLAction"
        }
      ],
      "role": "symbol",
      "title": "OpenURLAction",
      "type": "topic",
      "url": "/documentation/swiftui/openurlaction"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/Text": {
      "abstract": [
        {
          "text": "A view that displays one or more lines of read-only text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Text"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Text"
        }
      ],
      "role": "symbol",
      "title": "Text",
      "type": "topic",
      "url": "/documentation/swiftui/text"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-1a4oh": {
      "abstract": [
        {
          "text": "Creates a text view that displays styled attributed content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation16AttributedStringV",
          "text": "AttributedString"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-1a4oh",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/text/init(_:)-1a4oh"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-1s6o1": {
      "abstract": [
        {
          "text": "Creates a text view that displays a localized string resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation23LocalizedStringResourceV",
          "text": "LocalizedStringResource"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-1s6o1",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/text/init(_:)-1s6o1"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-4k7ab": {
      "abstract": [
        {
          "text": "Creates an instance that displays a localized range between two dates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SN",
          "text": "ClosedRange"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-4k7ab",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/text/init(_:)-4k7ab"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-56n81": {
      "abstract": [
        {
          "text": "Creates an instance that displays a localized time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12DateIntervalV",
          "text": "DateInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-56n81",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/text/init(_:)-56n81"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-60ax7": {
      "abstract": [
        {
          "text": "Creates an instance that wraps an ",
          "type": "text"
        },
        {
          "code": "Image",
          "type": "codeVoice"
        },
        {
          "text": ", suitable for concatenating",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "with other ",
          "type": "text"
        },
        {
          "code": "Text",
          "type": "codeVoice"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI5ImageV",
          "text": "Image"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-60ax7",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/text/init(_:)-60ax7"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-9d1g4": {
      "abstract": [
        {
          "text": "Creates a text view that displays a stored string without localization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "S"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "S"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-9d1g4",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/text/init(_:)-9d1g4"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:tableName:bundle:comment:)": {
      "abstract": [
        {
          "text": "Creates a text view that displays localized content identified by a key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI18LocalizedStringKeyV",
          "text": "LocalizedStringKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "tableName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "bundle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBundle",
          "text": "Bundle"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "comment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s12StaticStringV",
          "text": "StaticString"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:tableName:bundle:comment:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:tableName:bundle:comment:)",
      "type": "topic",
      "url": "/documentation/swiftui/text/init(_:tablename:bundle:comment:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/VStack": {
      "abstract": [
        {
          "text": "A view that arranges its subviews in a vertical line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VStack"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/VStack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VStack"
        }
      ],
      "role": "symbol",
      "title": "VStack",
      "type": "topic",
      "url": "/documentation/swiftui/vstack"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/foregroundColor(_:)": {
      "abstract": [
        {
          "text": "Sets the color of the foreground elements displayed by this view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foregroundColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI5ColorV",
          "text": "Color"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/foregroundColor(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "foregroundColor(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/foregroundcolor(_:)"
    },
    "doc://com.apple.documentation/documentation/foundation/attributedstring": {
      "abstract": [
        {
          "text": "A value type for a string with associated attributes for portions of its text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "AttributedString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/attributedstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "AttributedString",
      "type": "topic",
      "url": "/documentation/foundation/attributedstring"
    },
    "doc://com.apple.documentation/documentation/foundation/attributescopes/3788543-swiftui": {
      "abstract": [
        {
          "text": "A property for accessing the attribute scopes that SwiftUI defines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "swiftUI"
        },
        {
          "kind": "text",
          "text": ": AttributeScopes.SwiftUIAttributes.Type"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/attributescopes/3788543-swiftui",
      "kind": "symbol",
      "role": "symbol",
      "title": "swiftUI",
      "type": "topic",
      "url": "/documentation/foundation/attributescopes/3788543-swiftui"
    },
    "doc://com.apple.documentation/documentation/foundation/attributescopes/appkitattributes": {
      "abstract": [
        {
          "text": "Attribute scopes that AppKit defines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "AttributeScopes.AppKitAttributes"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/attributescopes/appkitattributes",
      "kind": "symbol",
      "role": "symbol",
      "title": "AttributeScopes.AppKitAttributes",
      "type": "topic",
      "url": "/documentation/foundation/attributescopes/appkitattributes"
    },
    "doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes": {
      "abstract": [
        {
          "text": "Attribute scopes that Foundation defines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "AttributeScopes.FoundationAttributes"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes",
      "kind": "symbol",
      "role": "symbol",
      "title": "AttributeScopes.FoundationAttributes",
      "type": "topic",
      "url": "/documentation/foundation/attributescopes/foundationattributes"
    },
    "doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes/3764633-link": {
      "abstract": [
        {
          "text": "A property for accessing the link attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "link"
        },
        {
          "kind": "text",
          "text": ": AttributeScopes.FoundationAttributes.LinkAttribute"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes/3764633-link",
      "kind": "symbol",
      "role": "symbol",
      "title": "link",
      "type": "topic",
      "url": "/documentation/foundation/attributescopes/foundationattributes/3764633-link"
    },
    "doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes/3796123-inlinepresentationintent": {
      "abstract": [
        {
          "text": "A property for accessing an inline presentation intent attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "inlinePresentationIntent"
        },
        {
          "kind": "text",
          "text": ": AttributeScopes.FoundationAttributes.InlinePresentationIntentAttribute"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes/3796123-inlinepresentationintent",
      "kind": "symbol",
      "role": "symbol",
      "title": "inlinePresentationIntent",
      "type": "topic",
      "url": "/documentation/foundation/attributescopes/foundationattributes/3796123-inlinepresentationintent"
    },
    "doc://com.apple.documentation/documentation/foundation/attributescopes/swiftuiattributes": {
      "abstract": [
        {
          "text": "Attribute scopes that SwiftUI defines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "AttributeScopes.SwiftUIAttributes"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/attributescopes/swiftuiattributes",
      "kind": "symbol",
      "role": "symbol",
      "title": "AttributeScopes.SwiftUIAttributes",
      "type": "topic",
      "url": "/documentation/foundation/attributescopes/swiftuiattributes"
    },
    "doc://com.apple.documentation/documentation/foundation/attributescopes/uikitattributes": {
      "abstract": [
        {
          "text": "Attribute scopes that UIKit defines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "AttributeScopes.UIKitAttributes"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/attributescopes/uikitattributes",
      "kind": "symbol",
      "role": "symbol",
      "title": "AttributeScopes.UIKitAttributes",
      "type": "topic",
      "url": "/documentation/foundation/attributescopes/uikitattributes"
    },
    "doc://com.apple.documentation/documentation/foundation/inlinepresentationintent": {
      "abstract": [
        {
          "text": "A type that defines presentation intent for runs of characters for traits like emphasis, strikethrough, and code voice.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "InlinePresentationIntent"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/inlinepresentationintent",
      "kind": "symbol",
      "role": "symbol",
      "title": "InlinePresentationIntent",
      "type": "topic",
      "url": "/documentation/foundation/inlinepresentationintent"
    },
    "doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3746899-stronglyemphasized": {
      "abstract": [
        {
          "text": "An intent that represents a strongly emphasized presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static var "
        },
        {
          "kind": "identifier",
          "text": "stronglyEmphasized"
        },
        {
          "kind": "text",
          "text": ": InlinePresentationIntent"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3746899-stronglyemphasized",
      "kind": "symbol",
      "role": "symbol",
      "title": "stronglyEmphasized",
      "type": "topic",
      "url": "/documentation/foundation/inlinepresentationintent/3746899-stronglyemphasized"
    },
    "doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3787563-linebreak": {
      "abstract": [
        {
          "text": "An intent that represents a line break.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static var "
        },
        {
          "kind": "identifier",
          "text": "lineBreak"
        },
        {
          "kind": "text",
          "text": ": InlinePresentationIntent"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3787563-linebreak",
      "kind": "symbol",
      "role": "symbol",
      "title": "lineBreak",
      "type": "topic",
      "url": "/documentation/foundation/inlinepresentationintent/3787563-linebreak"
    },
    "doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3787564-softbreak": {
      "abstract": [
        {
          "text": "An intent that represents a soft line break.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static var "
        },
        {
          "kind": "identifier",
          "text": "softBreak"
        },
        {
          "kind": "text",
          "text": ": InlinePresentationIntent"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3787564-softbreak",
      "kind": "symbol",
      "role": "symbol",
      "title": "softBreak",
      "type": "topic",
      "url": "/documentation/foundation/inlinepresentationintent/3787564-softbreak"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation12DateIntervalV": {
      "abstract": [
        {
          "text": "The span of time between a specific start date and end date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "DateInterval"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation12DateIntervalV",
      "kind": "symbol",
      "role": "symbol",
      "title": "DateInterval",
      "type": "topic",
      "url": "/documentation/foundation/dateinterval"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation16AttributedStringV": {
      "abstract": [
        {
          "text": "A value type for a string with associated attributes for portions of its text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "AttributedString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation16AttributedStringV",
      "kind": "symbol",
      "role": "symbol",
      "title": "AttributedString",
      "type": "topic",
      "url": "/documentation/foundation/attributedstring"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation23LocalizedStringResourceV": {
      "abstract": [
        {
          "text": "A reference to a localizable string, accessible from another process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "LocalizedStringResource"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation23LocalizedStringResourceV",
      "kind": "symbol",
      "role": "symbol",
      "title": "LocalizedStringResource",
      "type": "topic",
      "url": "/documentation/foundation/localizedstringresource"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation4DateV": {
      "abstract": [
        {
          "text": "A specific point in time, independent of any calendar or time zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DateV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Date",
      "type": "topic",
      "url": "/documentation/foundation/date"
    },
    "doc://com.externally.resolved.symbol/s:SN": {
      "abstract": [
        {
          "text": "An interval from a lower bound up to, and including, an upper bound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ClosedRange"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Bound"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Bound"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SL",
          "text": "Comparable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SN",
      "kind": "symbol",
      "role": "symbol",
      "title": "ClosedRange",
      "type": "topic",
      "url": "/documentation/Swift/ClosedRange"
    },
    "doc://com.externally.resolved.symbol/s:Sy": {
      "abstract": [
        {
          "text": "A type that can represent a string as a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StringProtocol"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SK",
          "text": "BidirectionalCollection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SL",
          "text": "Comparable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s32ExpressibleByStringInterpolationP",
          "text": "ExpressibleByStringInterpolation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25LosslessStringConvertibleP",
          "text": "LosslessStringConvertible"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s16TextOutputStreamP",
          "text": "TextOutputStream"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s20TextOutputStreamableP",
          "text": "TextOutputStreamable"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ST7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": " == "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SJ",
          "text": "Character"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl5IndexQa",
          "text": "Index"
        },
        {
          "kind": "text",
          "text": " == "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS5IndexV",
          "text": "Index"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s32ExpressibleByStringInterpolationP0cD0Qa",
          "text": "StringInterpolation"
        },
        {
          "kind": "text",
          "text": " == "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s26DefaultStringInterpolationV",
          "text": "DefaultStringInterpolation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl11SubSequenceQa",
          "text": "SubSequence"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sy",
          "text": "StringProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sy",
      "kind": "symbol",
      "role": "symbol",
      "title": "StringProtocol",
      "type": "topic",
      "url": "/documentation/Swift/StringProtocol"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1inlinepresentationintent/title",
          "value": "NSInlinePresentationIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1inlinepresentationintent~13746899-stronglyemphasized/title",
          "value": "NSInlinePresentationIntentStronglyEmphasized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1inlinepresentationintent~13787564-softbreak/title",
          "value": "NSInlinePresentationIntentSoftBreak"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1inlinepresentationintent~13787563-linebreak/title",
          "value": "NSInlinePresentationIntentLineBreak"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/swiftui/text/init(_:)-1a4oh"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
