{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":":)","kind":"text"}],"externalID":"s:7SwiftUI4TextVyAC10Foundation16AttributedStringVcfc::OverloadGroup","extendedModule":"SwiftUI","navigatorTitle":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":":)","kind":"text"}],"title":"init(_:)","platforms":[{"name":"iOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"15.0"},{"name":"iPadOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"15.0"},{"name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"15.0"},{"name":"macOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"12.0"},{"name":"tvOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"15.0"},{"name":"visionOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"1.0"},{"name":"watchOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"8.0"}],"modules":[{"name":"SwiftUI"}],"roleHeading":"Initializer","symbolKind":"init","role":"symbol"},"variants":[{"paths":["/documentation/swiftui/text/init(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.SwiftUI/documentation/SwiftUI","doc://com.apple.SwiftUI/documentation/SwiftUI/Text"]]},"abstract":[{"type":"text","text":"Creates a text view that displays styled attributed content."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"highlight":"changed","kind":"internalParam","text":"attributedContent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation16AttributedStringV","highlight":"changed","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:10Foundation16AttributedStringV","text":"AttributedString"},{"kind":"text","text":")"}],"languages":["swift"],"otherDeclarations":{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","highlight":"changed","text":"dates"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SN","kind":"typeIdentifier","highlight":"changed","text":"ClosedRange","identifier":"doc://com.externally.resolved.symbol/s:SN"},{"kind":"text","highlight":"changed","text":"<"},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","highlight":"changed","text":"Date","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DateV"},{"kind":"text","highlight":"changed","text":">"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-4k7ab"},{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"highlight":"changed","text":"image","kind":"internalParam"},{"text":": ","kind":"text"},{"highlight":"changed","text":"Image","identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Image","preciseIdentifier":"s:7SwiftUI5ImageV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-60ax7"},{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","highlight":"changed","text":"interval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","highlight":"changed","identifier":"doc://com.externally.resolved.symbol/s:10Foundation12DateIntervalV","preciseIdentifier":"s:10Foundation12DateIntervalV","text":"DateInterval"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-56n81"},{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"resource","kind":"internalParam","highlight":"changed"},{"text":": ","kind":"text"},{"text":"LocalizedStringResource","identifier":"doc://com.externally.resolved.symbol/s:10Foundation23LocalizedStringResourceV","preciseIdentifier":"s:10Foundation23LocalizedStringResourceV","kind":"typeIdentifier","highlight":"changed"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-1s6o1"},{"tokens":[{"kind":"keyword","text":"init"},{"highlight":"changed","kind":"text","text":"<"},{"highlight":"changed","kind":"genericParameter","text":"S"},{"highlight":"changed","kind":"text","text":">"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"highlight":"changed","kind":"internalParam","text":"content"},{"kind":"text","text":": "},{"highlight":"changed","kind":"typeIdentifier","text":"S"},{"kind":"text","text":") "},{"highlight":"changed","kind":"keyword","text":"where"},{"highlight":"changed","kind":"text","text":" "},{"highlight":"changed","kind":"typeIdentifier","text":"S"},{"highlight":"changed","kind":"text","text":" : "},{"highlight":"changed","identifier":"doc://com.externally.resolved.symbol/s:Sy","kind":"typeIdentifier","preciseIdentifier":"s:Sy","text":"StringProtocol"}],"identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-9d1g4"}],"displayIndex":0},"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"attributedContent","content":[{"type":"paragraph","inlineContent":[{"text":"An attributed string to style and display,","type":"text"},{"text":" ","type":"text"},{"text":"in accordance with its attributes.","type":"text"}]}]}]},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this initializer to style text according to attributes found in the specified"},{"type":"text","text":" "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/attributedstring","isActive":true},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Attributes in the attributed string take precedence over styles added by"},{"type":"text","text":" "},{"type":"text","text":"view modifiers. For example, the attributed text in the following"},{"type":"text","text":" "},{"type":"text","text":"example appears in blue, despite the use of the "},{"type":"reference","identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/View/foregroundColor(_:)","isActive":true},{"type":"text","text":" "},{"type":"text","text":"modifier to use red throughout the enclosing "},{"type":"reference","identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/VStack","isActive":true},{"type":"text","text":":"}]},{"type":"codeListing","code":["var content: AttributedString {","    var attributedString = AttributedString(\"Blue text\")","    attributedString.foregroundColor = .blue","    return attributedString","}","","var body: some View {","    VStack {","        Text(content)","        Text(\"Red text\")","    }","    .foregroundColor(.red)","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"SwiftUI-Text-init-attributed.png"}]},{"type":"paragraph","inlineContent":[{"text":"SwiftUI combines text attributes with SwiftUI modifiers whenever","type":"text"},{"text":" ","type":"text"},{"text":"possible. For example, the following listing creates text that is","type":"text"},{"text":" ","type":"text"},{"text":"both bold and red:","type":"text"}]},{"type":"codeListing","code":["var content: AttributedString {","    var content = AttributedString(\"Some text\")","    content.inlinePresentationIntent = .stronglyEmphasized","    return content","}","","var body: some View {","    Text(content).foregroundColor(Color.red)","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"A SwiftUI ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text","type":"reference"},{"text":" view renders most of the styles defined by the","type":"text"},{"text":" ","type":"text"},{"text":"Foundation attribute","type":"text"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes/3796123-inlinepresentationintent","type":"reference"},{"text":", like the","type":"text"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3746899-stronglyemphasized","type":"reference"},{"text":" ","type":"text"},{"text":"value, which SwiftUI presents as bold text.","type":"text"}]},{"type":"aside","name":"Important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text"},{"type":"text","text":" uses only a subset of the attributes defined in"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes"},{"type":"text","text":"."},{"type":"text","text":" "},{"code":"Text","type":"codeVoice"},{"type":"text","text":" renders all"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/inlinepresentationintent"},{"type":"text","text":" "},{"type":"text","text":"attributes except for"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3787563-linebreak"},{"type":"text","text":" and"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3787564-softbreak"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"It also renders the"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes/3764633-link"},{"type":"text","text":" "},{"type":"text","text":"attribute as a clickable link. "},{"code":"Text","type":"codeVoice"},{"type":"text","text":" ignores any other"},{"type":"text","text":" "},{"type":"text","text":"Foundation-defined attributes in an attributed string."}]}],"style":"important"},{"type":"paragraph","inlineContent":[{"type":"text","text":"SwiftUI also defines additional attributes in the attribute scope"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/foundation/attributescopes/swiftuiattributes"},{"type":"text","text":" "},{"type":"text","text":"which you can access from an attributed string’s"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/foundation/attributescopes/3788543-swiftui"},{"type":"text","text":" "},{"type":"text","text":"property. SwiftUI attributes take precedence over equivalent attributes"},{"type":"text","text":" "},{"type":"text","text":"from other frameworks, such as"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/foundation/attributescopes/uikitattributes"},{"type":"text","text":" and"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/foundation/attributescopes/appkitattributes"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can create an "},{"type":"codeVoice","code":"AttributedString"},{"type":"text","text":" with Markdown syntax, which allows"},{"type":"text","text":" "},{"type":"text","text":"you to style distinct runs within a "},{"type":"codeVoice","code":"Text"},{"type":"text","text":" view:"}]},{"type":"codeListing","code":["let content = try! AttributedString(","    markdown: \"**Thank You!** Please visit our [website](http://example.com).\")","","var body: some View {","    Text(content)","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"**","type":"codeVoice"},{"type":"text","text":" syntax around “Thank You!” applies an"},{"type":"text","text":" "},{"identifier":"doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes/3796123-inlinepresentationintent","type":"reference","isActive":true},{"type":"text","text":" "},{"type":"text","text":"attribute with the value"},{"type":"text","text":" "},{"identifier":"doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3746899-stronglyemphasized","type":"reference","isActive":true},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"SwiftUI renders this as"},{"type":"text","text":" "},{"type":"text","text":"bold text, as described earlier. The link syntax around “website”"},{"type":"text","text":" "},{"type":"text","text":"creates a"},{"type":"text","text":" "},{"identifier":"doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes/3764633-link","type":"reference","isActive":true},{"type":"text","text":" "},{"type":"text","text":"attribute, which "},{"code":"Text","type":"codeVoice"},{"type":"text","text":" styles to indicate it’s a link; by default,"},{"type":"text","text":" "},{"type":"text","text":"clicking or tapping the link opens the linked URL in the user’s default"},{"type":"text","text":" "},{"type":"text","text":"browser. Alternatively, you can perform custom link handling by putting"},{"type":"text","text":" "},{"type":"text","text":"an "},{"identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/OpenURLAction","type":"reference","isActive":true},{"type":"text","text":" in the text view’s environment."}]},{"type":"paragraph","inlineContent":[{"identifier":"SwiftUI-Text-init-markdown.png","type":"image"}]},{"type":"paragraph","inlineContent":[{"text":"You can also use Markdown syntax in localized string keys, which means","type":"text"},{"text":" ","type":"text"},{"text":"you can write the above example without needing to explicitly create","type":"text"},{"text":" ","type":"text"},{"text":"an ","type":"text"},{"type":"codeVoice","code":"AttributedString"},{"text":":","type":"text"}]},{"type":"codeListing","code":["var body: some View {","    Text(\"**Thank You!** Please visit our [website](https://example.com).\")","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In your app’s strings files, use Markdown syntax to apply styling"},{"type":"text","text":" "},{"type":"text","text":"to the app’s localized strings. You also use this approach when you want"},{"type":"text","text":" "},{"type":"text","text":"to perform automatic grammar agreement on localized strings, with"},{"type":"text","text":" "},{"type":"text","text":"the "},{"code":"^[text](inflect:true)","type":"codeVoice"},{"type":"text","text":" syntax."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For details about Markdown syntax support in SwiftUI, see"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:tableName:bundle:comment:)"},{"type":"text","text":"."}]}],"kind":"content"}],"sections":[],"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:tableName:bundle:comment:)","doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(verbatim:)","doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:style:)","doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:format:)","doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:formatter:)","doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(timerInterval:pauseTime:countsDown:showsHours:)"],"anchor":"Creating-a-text-view","title":"Creating a text view","generated":true}],"references":{"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:style:)":{"abstract":[{"text":"Creates an instance that displays localized dates and times using a specific style.","type":"text"}],"title":"init(_:style:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Text","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4TextV"},{"text":".","kind":"text"},{"text":"DateStyle","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4TextV9DateStyleV"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:style:)","url":"/documentation/swiftui/text/init(_:style:)","role":"symbol","kind":"symbol"},"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-1s6o1":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"LocalizedStringResource","preciseIdentifier":"s:10Foundation23LocalizedStringResourceV"},{"kind":"text","text":")"}],"title":"init(_:)","url":"/documentation/swiftui/text/init(_:)-1s6o1","abstract":[{"text":"Creates a text view that displays a localized string resource.","type":"text"}],"identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-1s6o1"},"doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3787563-linebreak":{"type":"topic","role":"symbol","url":"/documentation/foundation/inlinepresentationintent/3787563-linebreak","identifier":"doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3787563-linebreak","title":"lineBreak","abstract":[{"type":"text","text":"An intent that represents a line break."}],"kind":"symbol","fragments":[{"kind":"text","text":"static var "},{"kind":"identifier","text":"lineBreak"},{"kind":"text","text":": InlinePresentationIntent"}]},"doc://com.externally.resolved.symbol/s:10Foundation16AttributedStringV":{"abstract":[{"type":"text","text":"A value type for a string with associated attributes for portions of its text."}],"title":"AttributedString","type":"topic","fragments":[{"text":"struct ","kind":"text"},{"text":"AttributedString","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:10Foundation16AttributedStringV","url":"/documentation/foundation/attributedstring","role":"symbol","kind":"symbol"},"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-9d1g4":{"role":"symbol","abstract":[{"text":"Creates a text view that displays a stored string without localization.","type":"text"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"S"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"S"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-9d1g4","title":"init(_:)","type":"topic","url":"/documentation/swiftui/text/init(_:)-9d1g4"},"doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3746899-stronglyemphasized":{"type":"topic","role":"symbol","url":"/documentation/foundation/inlinepresentationintent/3746899-stronglyemphasized","identifier":"doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3746899-stronglyemphasized","title":"stronglyEmphasized","abstract":[{"type":"text","text":"An intent that represents a strongly emphasized presentation."}],"kind":"symbol","fragments":[{"kind":"text","text":"static var "},{"kind":"identifier","text":"stronglyEmphasized"},{"kind":"text","text":": InlinePresentationIntent"}]},"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-56n81":{"url":"/documentation/swiftui/text/init(_:)-56n81","role":"symbol","abstract":[{"text":"Creates an instance that displays a localized time interval.","type":"text"}],"identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-56n81","title":"init(_:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DateInterval","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12DateIntervalV"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/s:10Foundation12DateIntervalV":{"abstract":[{"text":"The span of time between a specific start date and end date.","type":"text"}],"title":"DateInterval","type":"topic","fragments":[{"text":"struct ","kind":"text"},{"text":"DateInterval","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:10Foundation12DateIntervalV","url":"/documentation/foundation/dateinterval","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes":{"type":"topic","role":"symbol","url":"/documentation/foundation/attributescopes/foundationattributes","identifier":"doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes","title":"AttributeScopes.FoundationAttributes","abstract":[{"type":"text","text":"Attribute scopes that Foundation defines."}],"kind":"symbol","fragments":[{"kind":"text","text":"struct "},{"text":"AttributeScopes.FoundationAttributes","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:10Foundation4DateV":{"abstract":[{"text":"A specific point in time, independent of any calendar or time zone.","type":"text"}],"title":"Date","type":"topic","fragments":[{"text":"struct ","kind":"text"},{"text":"Date","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DateV","url":"/documentation/foundation/date","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/foundation/attributescopes/uikitattributes":{"type":"topic","role":"symbol","url":"/documentation/foundation/attributescopes/uikitattributes","identifier":"doc://com.apple.documentation/documentation/foundation/attributescopes/uikitattributes","title":"AttributeScopes.UIKitAttributes","abstract":[{"type":"text","text":"Attribute scopes that UIKit defines."}],"kind":"symbol","fragments":[{"kind":"text","text":"struct "},{"text":"AttributeScopes.UIKitAttributes","kind":"identifier"}]},"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-60ax7":{"title":"init(_:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"preciseIdentifier":"s:7SwiftUI5ImageV","text":"Image","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Creates an instance that wraps an "},{"code":"Image","type":"codeVoice"},{"text":", suitable for concatenating","type":"text"},{"type":"text","text":" "},{"text":"with other ","type":"text"},{"code":"Text","type":"codeVoice"}],"url":"/documentation/swiftui/text/init(_:)-60ax7","role":"symbol","identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-60ax7","type":"topic"},"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:tableName:bundle:comment:)":{"title":"init(_:tableName:bundle:comment:)","abstract":[{"text":"Creates a text view that displays localized content identified by a key.","type":"text"}],"url":"/documentation/swiftui/text/init(_:tablename:bundle:comment:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"LocalizedStringKey","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI18LocalizedStringKeyV"},{"text":", ","kind":"text"},{"text":"tableName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"bundle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"},{"text":"?, ","kind":"text"},{"text":"comment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":"?)","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:tableName:bundle:comment:)"},"doc://com.apple.SwiftUI/documentation/SwiftUI/View/foregroundColor(_:)":{"type":"topic","role":"symbol","deprecated":true,"url":"/documentation/swiftui/view/foregroundcolor(_:)","identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/View/foregroundColor(_:)","title":"foregroundColor(_:)","abstract":[{"type":"text","text":"Sets the color of the foreground elements displayed by this view."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"foregroundColor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Color","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI5ColorV"},{"text":"?) -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}]},"doc://com.apple.SwiftUI/documentation/SwiftUI":{"title":"SwiftUI","role":"collection","abstract":[{"text":"Declare the user interface and behavior for your app on every platform.","type":"text"}],"kind":"symbol","type":"topic","url":"/documentation/swiftui","images":[{"identifier":"SwiftUI-PageImage-card.png","type":"card"}],"identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI"},"doc://com.externally.resolved.symbol/s:SN":{"abstract":[{"text":"An interval from a lower bound up to, and including, an upper bound.","type":"text"}],"title":"ClosedRange","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClosedRange","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Bound","kind":"genericParameter"},{"text":"> ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bound","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Comparable","preciseIdentifier":"s:SL","kind":"typeIdentifier"}],"identifier":"doc://com.externally.resolved.symbol/s:SN","url":"/documentation/Swift/ClosedRange","role":"symbol","kind":"symbol"},"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(verbatim:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"verbatim","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"url":"/documentation/swiftui/text/init(verbatim:)","role":"symbol","identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(verbatim:)","kind":"symbol","abstract":[{"text":"Creates a text view that displays a string literal without localization.","type":"text"}],"title":"init(verbatim:)","type":"topic"},"doc://com.apple.SwiftUI/documentation/SwiftUI/Image":{"navigatorTitle":[{"text":"Image","kind":"identifier"}],"title":"Image","role":"symbol","abstract":[{"text":"A view that displays an image.","type":"text"}],"kind":"symbol","type":"topic","url":"/documentation/swiftui/image","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Image"},"SwiftUI-PageImage-card.png":{"type":"image","identifier":"SwiftUI-PageImage-card.png","alt":"A black Swift logo on a swirly blue and purple background.","variants":[{"url":"https://docs-assets.developer.apple.com/published/b1de0de086f81a5d0eac3839a0af6e6f/SwiftUI-PageImage-card@2x.png","traits":["2x","light"]},{"url":"https://docs-assets.developer.apple.com/published/1450d0b30a6b024e10c148e3f31dafe9/SwiftUI-PageImage-card~dark@2x.png","traits":["2x","dark"]}]},"doc://com.apple.SwiftUI/documentation/SwiftUI/VStack":{"navigatorTitle":[{"text":"VStack","kind":"identifier"}],"identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/VStack","url":"/documentation/swiftui/vstack","abstract":[{"type":"text","text":"A view that arranges its subviews in a vertical line."}],"role":"symbol","kind":"symbol","type":"topic","title":"VStack","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"VStack","kind":"identifier"}]},"doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3787564-softbreak":{"url":"/documentation/foundation/inlinepresentationintent/3787564-softbreak","type":"topic","abstract":[{"type":"text","text":"An intent that represents a soft line break."}],"identifier":"doc://com.apple.documentation/documentation/foundation/inlinepresentationintent/3787564-softbreak","kind":"symbol","title":"softBreak","fragments":[{"text":"static var ","kind":"text"},{"text":"softBreak","kind":"identifier"},{"text":": InlinePresentationIntent","kind":"text"}],"role":"symbol"},"doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes/3764633-link":{"url":"/documentation/foundation/attributescopes/foundationattributes/3764633-link","type":"topic","abstract":[{"type":"text","text":"A property for accessing the link attribute."}],"identifier":"doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes/3764633-link","kind":"symbol","title":"link","fragments":[{"text":"let ","kind":"text"},{"text":"link","kind":"identifier"},{"text":": AttributeScopes.FoundationAttributes.LinkAttribute","kind":"text"}],"role":"symbol"},"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:formatter:)":{"identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:formatter:)","url":"/documentation/swiftui/text/init(_:formatter:)","abstract":[{"type":"text","text":"Creates a text view that displays the formatted representation"},{"type":"text","text":" "},{"type":"text","text":"of a Foundation object."}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":":"},{"kind":"externalParam","text":"formatter"},{"kind":"text","text":":)"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":":"},{"kind":"externalParam","text":"formatter"},{"kind":"text","text":":)"}],"role":"symbol","title":"init(_:formatter:)"},"doc://com.apple.documentation/documentation/foundation/attributescopes/3788543-swiftui":{"url":"/documentation/foundation/attributescopes/3788543-swiftui","type":"topic","abstract":[{"type":"text","text":"A property for accessing the attribute scopes that SwiftUI defines."}],"identifier":"doc://com.apple.documentation/documentation/foundation/attributescopes/3788543-swiftui","kind":"symbol","title":"swiftUI","fragments":[{"text":"var ","kind":"text"},{"text":"swiftUI","kind":"identifier"},{"text":": AttributeScopes.SwiftUIAttributes.Type","kind":"text"}],"role":"symbol"},"doc://com.apple.SwiftUI/documentation/SwiftUI/OpenURLAction":{"abstract":[{"type":"text","text":"An action that opens a URL."}],"role":"symbol","title":"OpenURLAction","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenURLAction"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OpenURLAction"}],"identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/OpenURLAction","url":"/documentation/swiftui/openurlaction","type":"topic"},"doc://com.apple.documentation/documentation/foundation/inlinepresentationintent":{"abstract":[{"type":"text","text":"A type that defines presentation intent for runs of characters for traits like emphasis, strikethrough, and code voice."}],"fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"InlinePresentationIntent"}],"url":"/documentation/foundation/inlinepresentationintent","type":"topic","title":"InlinePresentationIntent","identifier":"doc://com.apple.documentation/documentation/foundation/inlinepresentationintent","role":"symbol","kind":"symbol"},"SwiftUI-Text-init-attributed.png":{"variants":[{"url":"https://docs-assets.developer.apple.com/published/0e75f9a9c2cd81bdb1086e94efdc2417/SwiftUI-Text-init-attributed@2x.png","traits":["2x","light"]},{"url":"https://docs-assets.developer.apple.com/published/6dbd29384e0436ded2cc4c1020a34e5f/SwiftUI-Text-init-attributed~dark@2x.png","traits":["2x","dark"]}],"alt":"A vertical stack of two text views, the top labeled Blue Text with a","type":"image","identifier":"SwiftUI-Text-init-attributed.png"},"doc://com.externally.resolved.symbol/s:Sy":{"abstract":[{"type":"text","text":"A type that can represent a string as a collection of characters."}],"title":"StringProtocol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StringProtocol"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SK","kind":"typeIdentifier","text":"BidirectionalCollection"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SL","kind":"typeIdentifier","text":"Comparable"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s32ExpressibleByStringInterpolationP","kind":"typeIdentifier","text":"ExpressibleByStringInterpolation"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SH","kind":"typeIdentifier","text":"Hashable"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s25LosslessStringConvertibleP","kind":"typeIdentifier","text":"LosslessStringConvertible"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s16TextOutputStreamP","kind":"typeIdentifier","text":"TextOutputStream"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s20TextOutputStreamableP","text":"TextOutputStreamable"},{"kind":"text","text":" "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:ST7ElementQa","text":"Element"},{"kind":"text","text":" == "},{"kind":"typeIdentifier","preciseIdentifier":"s:SJ","text":"Character"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sl5IndexQa","text":"Index"},{"text":" == ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:SS5IndexV","text":"Index","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:s32ExpressibleByStringInterpolationP0cD0Qa","text":"StringInterpolation","kind":"typeIdentifier"},{"text":" == ","kind":"text"},{"preciseIdentifier":"s:s26DefaultStringInterpolationV","text":"DefaultStringInterpolation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sl11SubSequenceQa","text":"SubSequence","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:Sy","text":"StringProtocol","kind":"typeIdentifier"}],"identifier":"doc://com.externally.resolved.symbol/s:Sy","url":"/documentation/Swift/StringProtocol","role":"symbol","kind":"symbol"},"doc://com.apple.SwiftUI/documentation/SwiftUI/Text":{"navigatorTitle":[{"kind":"identifier","text":"Text"}],"title":"Text","role":"symbol","abstract":[{"text":"A view that displays one or more lines of read-only text.","type":"text"}],"kind":"symbol","type":"topic","url":"/documentation/swiftui/text","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Text","kind":"identifier"}],"identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text"},"doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes/3796123-inlinepresentationintent":{"abstract":[{"type":"text","text":"A property for accessing an inline presentation intent attribute."}],"fragments":[{"text":"let ","kind":"text"},{"text":"inlinePresentationIntent","kind":"identifier"},{"text":": AttributeScopes.FoundationAttributes.InlinePresentationIntentAttribute","kind":"text"}],"url":"/documentation/foundation/attributescopes/foundationattributes/3796123-inlinepresentationintent","type":"topic","title":"inlinePresentationIntent","identifier":"doc://com.apple.documentation/documentation/foundation/attributescopes/foundationattributes/3796123-inlinepresentationintent","role":"symbol","kind":"symbol"},"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-4k7ab":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SN","text":"ClosedRange","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":">)","kind":"text"}],"kind":"symbol","abstract":[{"text":"Creates an instance that displays a localized range between two dates.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)-4k7ab","url":"/documentation/swiftui/text/init(_:)-4k7ab","title":"init(_:)"},"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:format:)":{"abstract":[{"text":"Creates a text view that displays the formatted representation","type":"text"},{"text":" ","type":"text"},{"text":"of a nonstring type supported by a corresponding format style.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":":","kind":"text"},{"text":"format","kind":"externalParam"},{"text":":)","kind":"text"}],"title":"init(_:format:)","identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:format:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":":","kind":"text"},{"text":"format","kind":"externalParam"},{"text":":)","kind":"text"}],"role":"symbol","url":"/documentation/swiftui/text/init(_:format:)"},"SwiftUI-Text-init-markdown.png":{"variants":[{"url":"https://docs-assets.developer.apple.com/published/e5680bbca5ad5a5f2779dea53103d8ca/SwiftUI-Text-init-markdown@2x.png","traits":["2x","light"]},{"url":"https://docs-assets.developer.apple.com/published/f346510a8513a20208edc3ec8096a012/SwiftUI-Text-init-markdown~dark@2x.png","traits":["2x","dark"]}],"alt":"A text view that says Thank you. Please visit our website. The text","type":"image","identifier":"SwiftUI-Text-init-markdown.png"},"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)":{"identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(_:)","kind":"symbol","abstract":[{"text":"Creates a text view that displays styled attributed content.","type":"text"}],"title":"init(_:)","type":"topic","url":"/documentation/swiftui/text/init(_:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":":)","kind":"text"}],"navigatorTitle":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":":)","kind":"text"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:10Foundation23LocalizedStringResourceV":{"abstract":[{"type":"text","text":"A reference to a localizable string, accessible from another process."}],"title":"LocalizedStringResource","type":"topic","fragments":[{"text":"struct ","kind":"text"},{"text":"LocalizedStringResource","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:10Foundation23LocalizedStringResourceV","url":"/documentation/foundation/localizedstringresource","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/foundation/attributedstring":{"abstract":[{"text":"A value type for a string with associated attributes for portions of its text.","type":"text"}],"title":"AttributedString","type":"topic","fragments":[{"text":"struct ","kind":"text"},{"text":"AttributedString","kind":"identifier"}],"identifier":"doc://com.apple.documentation/documentation/foundation/attributedstring","url":"/documentation/foundation/attributedstring","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/foundation/attributescopes/swiftuiattributes":{"abstract":[{"type":"text","text":"Attribute scopes that SwiftUI defines."}],"fragments":[{"text":"struct ","kind":"text"},{"text":"AttributeScopes.SwiftUIAttributes","kind":"identifier"}],"url":"/documentation/foundation/attributescopes/swiftuiattributes","type":"topic","title":"AttributeScopes.SwiftUIAttributes","identifier":"doc://com.apple.documentation/documentation/foundation/attributescopes/swiftuiattributes","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/foundation/attributescopes/appkitattributes":{"abstract":[{"type":"text","text":"Attribute scopes that AppKit defines."}],"fragments":[{"text":"struct ","kind":"text"},{"text":"AttributeScopes.AppKitAttributes","kind":"identifier"}],"url":"/documentation/foundation/attributescopes/appkitattributes","type":"topic","title":"AttributeScopes.AppKitAttributes","identifier":"doc://com.apple.documentation/documentation/foundation/attributescopes/appkitattributes","role":"symbol","kind":"symbol"},"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(timerInterval:pauseTime:countsDown:showsHours:)":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"timerInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SN","kind":"typeIdentifier","text":"ClosedRange"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"pauseTime"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"countsDown"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showsHours"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"title":"init(timerInterval:pauseTime:countsDown:showsHours:)","url":"/documentation/swiftui/text/init(timerinterval:pausetime:countsdown:showshours:)","abstract":[{"type":"text","text":"Creates an instance that displays a timer counting within the provided"},{"type":"text","text":" "},{"type":"text","text":"interval."}],"identifier":"doc://com.apple.SwiftUI/documentation/SwiftUI/Text/init(timerInterval:pauseTime:countsDown:showsHours:)"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","role":"overview","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies"}},"variantOverrides":[{"patch":[{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1inlinepresentationintent~13787563-linebreak/title","value":"NSInlinePresentationIntentLineBreak","op":"replace"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1inlinepresentationintent~13746899-stronglyemphasized/title","value":"NSInlinePresentationIntentStronglyEmphasized","op":"replace"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1inlinepresentationintent~13787564-softbreak/title","value":"NSInlinePresentationIntentSoftBreak","op":"replace"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1inlinepresentationintent/title","value":"NSInlinePresentationIntent","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}