{
  "abstract": [
    {
      "text": "Sampling at any texture coordinate outside the ",
      "type": "text"
    },
    {
      "code": "0.0",
      "type": "codeVoice"
    },
    {
      "text": " to ",
      "type": "text"
    },
    {
      "code": "1.0",
      "type": "codeVoice"
    },
    {
      "text": " range returns the texel color from the nearest edge.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode/clamp"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MDLMaterialTextureWrapMode@MDLMaterialTextureWrapModeClamp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "clamp"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MDLMaterialTextureWrapModeClamp"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MDLMaterialTextureWrapMode.clamp"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "clamp"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode": {
      "abstract": [
        {
          "text": "Modes for sampling textures at coordinates outside the texture bounds, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/sWrapMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/tWrapMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/rWrapMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialTextureWrapMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialTextureWrapMode"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialTextureWrapMode",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialtexturewrapmode"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode/clamp": {
      "abstract": [
        {
          "text": "Sampling at any texture coordinate outside the ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": " to ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": " range returns the texel color from the nearest edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clamp"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode/clamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialTextureWrapModeClamp"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialTextureWrapMode.clamp",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialtexturewrapmode/clamp"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode/mirror": {
      "abstract": [
        {
          "text": "Sampling at texture coordinates outside the ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": " to ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": " range results in a mirrored tiling effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mirror"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode/mirror",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialTextureWrapModeMirror"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialTextureWrapMode.mirror",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialtexturewrapmode/mirror"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode/repeat": {
      "abstract": [
        {
          "text": "Sampling at texture coordinates outside the ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": " to ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": " range results in a repeated tiling effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`repeat`"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode/repeat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialTextureWrapModeRepeat"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialTextureWrapMode.repeat",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialtexturewrapmode/repeat"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/rWrapMode": {
      "abstract": [
        {
          "text": "The coordinate wrapping mode for texture r-coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rWrapMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialTextureWrapMode",
          "text": "MDLMaterialTextureWrapMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/rWrapMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rWrapMode"
        }
      ],
      "role": "symbol",
      "title": "rWrapMode",
      "type": "topic",
      "url": "/documentation/modelio/mdltexturefilter/rwrapmode"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/sWrapMode": {
      "abstract": [
        {
          "text": "The coordinate wrapping mode for texture t-coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sWrapMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialTextureWrapMode",
          "text": "MDLMaterialTextureWrapMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/sWrapMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sWrapMode"
        }
      ],
      "role": "symbol",
      "title": "sWrapMode",
      "type": "topic",
      "url": "/documentation/modelio/mdltexturefilter/swrapmode"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/tWrapMode": {
      "abstract": [
        {
          "text": "The coordinate wrapping mode for texture t-coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tWrapMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialTextureWrapMode",
          "text": "MDLMaterialTextureWrapMode"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLTextureFilter/tWrapMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tWrapMode"
        }
      ],
      "role": "symbol",
      "title": "tWrapMode",
      "type": "topic",
      "url": "/documentation/modelio/mdltexturefilter/twrapmode"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode/repeat",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode/mirror"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MDLMaterialTextureWrapModeClamp"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialTextureWrapModeClamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode/repeat",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialTextureWrapMode/mirror"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MDLMaterialTextureWrapModeClamp"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureWrapMode/title",
          "value": "MDLMaterialTextureWrapMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureWrapMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialTextureWrapMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureWrapMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialTextureWrapMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureWrapMode~1mirror/title",
          "value": "MDLMaterialTextureWrapModeMirror"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureWrapMode~1mirror/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialTextureWrapModeMirror"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1sWrapMode/title",
          "value": "sWrapMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1sWrapMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sWrapMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureWrapMode~1clamp/title",
          "value": "MDLMaterialTextureWrapModeClamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureWrapMode~1clamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialTextureWrapModeClamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1rWrapMode/title",
          "value": "rWrapMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1rWrapMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rWrapMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureWrapMode~1repeat/title",
          "value": "MDLMaterialTextureWrapModeRepeat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialTextureWrapMode~1repeat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialTextureWrapModeRepeat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1tWrapMode/title",
          "value": "tWrapMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLTextureFilter~1tWrapMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tWrapMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlmaterialtexturewrapmode/clamp"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlmaterialtexturewrapmode/clamp"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
