{
  "abstract": [
    {
      "text": "The music player is stopped.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/stopped"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MPMusicPlaybackState@MPMusicPlaybackStateStopped",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "stopped"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MPMusicPlaybackStateStopped"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MPMusicPlaybackState.stopped"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "stopped"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState": {
      "abstract": [
        {
          "text": "The music player playback state modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMusicPlaybackState"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMusicPlaybackState"
        }
      ],
      "role": "symbol",
      "title": "MPMusicPlaybackState",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplaybackstate"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/interrupted": {
      "abstract": [
        {
          "text": "The music player has been interrupted, such as by an incoming phone call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interrupted"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/interrupted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMusicPlaybackStateInterrupted"
        }
      ],
      "role": "symbol",
      "title": "MPMusicPlaybackState.interrupted",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplaybackstate/interrupted"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/paused": {
      "abstract": [
        {
          "text": "The music player is paused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paused"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/paused",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMusicPlaybackStatePaused"
        }
      ],
      "role": "symbol",
      "title": "MPMusicPlaybackState.paused",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplaybackstate/paused"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/playing": {
      "abstract": [
        {
          "text": "The music player is playing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playing"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/playing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMusicPlaybackStatePlaying"
        }
      ],
      "role": "symbol",
      "title": "MPMusicPlaybackState.playing",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplaybackstate/playing"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/seekingBackward": {
      "abstract": [
        {
          "text": "The music player is seeking backward.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "seekingBackward"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/seekingBackward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMusicPlaybackStateSeekingBackward"
        }
      ],
      "role": "symbol",
      "title": "MPMusicPlaybackState.seekingBackward",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplaybackstate/seekingbackward"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/seekingForward": {
      "abstract": [
        {
          "text": "The music player is seeking forward.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "seekingForward"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/seekingForward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMusicPlaybackStateSeekingForward"
        }
      ],
      "role": "symbol",
      "title": "MPMusicPlaybackState.seekingForward",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplaybackstate/seekingforward"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/stopped": {
      "abstract": [
        {
          "text": "The music player is stopped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopped"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/stopped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMusicPlaybackStateStopped"
        }
      ],
      "role": "symbol",
      "title": "MPMusicPlaybackState.stopped",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmusicplaybackstate/stopped"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/playing",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/paused",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/interrupted",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/seekingForward",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/seekingBackward"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MPMusicPlaybackStateStopped"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMusicPlaybackStateStopped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/playing",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/paused",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/interrupted",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/seekingForward",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMusicPlaybackState/seekingBackward"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MPMusicPlaybackStateStopped"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlaybackState~1interrupted/title",
          "value": "MPMusicPlaybackStateInterrupted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlaybackState~1interrupted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMusicPlaybackStateInterrupted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlaybackState~1seekingBackward/title",
          "value": "MPMusicPlaybackStateSeekingBackward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlaybackState~1seekingBackward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMusicPlaybackStateSeekingBackward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlaybackState~1playing/title",
          "value": "MPMusicPlaybackStatePlaying"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlaybackState~1playing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMusicPlaybackStatePlaying"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlaybackState~1seekingForward/title",
          "value": "MPMusicPlaybackStateSeekingForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlaybackState~1seekingForward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMusicPlaybackStateSeekingForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlaybackState/title",
          "value": "MPMusicPlaybackState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlaybackState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMusicPlaybackState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlaybackState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMusicPlaybackState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlaybackState~1stopped/title",
          "value": "MPMusicPlaybackStateStopped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlaybackState~1stopped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMusicPlaybackStateStopped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlaybackState~1paused/title",
          "value": "MPMusicPlaybackStatePaused"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMusicPlaybackState~1paused/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMusicPlaybackStatePaused"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpmusicplaybackstate/stopped"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpmusicplaybackstate/stopped"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
