{
  "abstract": [
    {
      "text": "The inset or outset values specifying your content’s size increase when in focus.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvuikit/documentation/TVUIKit",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView/focusSizeIncrease"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)TVLockupView(py)focusSizeIncrease",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "focusSizeIncrease"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@NSDirectionalEdgeInsets",
        "text": "NSDirectionalEdgeInsets"
      }
    ],
    "modules": [
      {
        "name": "TVUIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "focusSizeIncrease"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "focusSizeIncrease"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "focusSizeIncrease"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@NSDirectionalEdgeInsets",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@NSDirectionalEdgeInsets",
              "text": "NSDirectionalEdgeInsets"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use negative values for a size increase. The values contribute to the lockup view’s intrinsic content size and guide layout update when focus state changes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit": {
      "abstract": [
        {
          "text": "Show common user interface elements from Apple TV in your native app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVUIKit",
      "type": "topic",
      "url": "/documentation/tvuikit"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView": {
      "abstract": [
        {
          "text": "A focusable view that presents main content, like a movie poster, and an optional header and footer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVLockupView"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVLockupView"
        }
      ],
      "role": "symbol",
      "title": "TVLockupView",
      "type": "topic",
      "url": "/documentation/tvuikit/tvlockupview"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView/contentSize": {
      "abstract": [
        {
          "text": "The size of the content view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView/contentSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentSize"
        }
      ],
      "role": "symbol",
      "title": "contentSize",
      "type": "topic",
      "url": "/documentation/tvuikit/tvlockupview/contentsize"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView/contentViewInsets": {
      "abstract": [
        {
          "text": "The spacing between the content view and its peer and containing views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentViewInsets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSDirectionalEdgeInsets",
          "text": "NSDirectionalEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView/contentViewInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentViewInsets"
        }
      ],
      "role": "symbol",
      "title": "contentViewInsets",
      "type": "topic",
      "url": "/documentation/tvuikit/tvlockupview/contentviewinsets"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView/focusSizeIncrease": {
      "abstract": [
        {
          "text": "The inset or outset values specifying your content’s size increase when in focus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusSizeIncrease"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSDirectionalEdgeInsets",
          "text": "NSDirectionalEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView/focusSizeIncrease",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "focusSizeIncrease"
        }
      ],
      "role": "symbol",
      "title": "focusSizeIncrease",
      "type": "topic",
      "url": "/documentation/tvuikit/tvlockupview/focussizeincrease"
    },
    "doc://com.externally.resolved.symbol/c:@S@NSDirectionalEdgeInsets": {
      "abstract": [
        {
          "text": "The inset distances for views, taking the user interface layout direction into account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDirectionalEdgeInsets"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@NSDirectionalEdgeInsets",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDirectionalEdgeInsets",
      "type": "topic",
      "url": "/documentation/AppKit/NSDirectionalEdgeInsets"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-view-size",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView/contentSize",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView/contentViewInsets"
      ],
      "title": "Setting view size"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "focusSizeIncrease"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focusSizeIncrease"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvuikit/documentation/TVUIKit",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-view-size",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView/contentSize",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView/contentViewInsets"
              ],
              "title": "Setting view size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@NSDirectionalEdgeInsets",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@NSDirectionalEdgeInsets",
                    "text": "NSDirectionalEdgeInsets"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "focusSizeIncrease"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupView/title",
          "value": "TVLockupView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVLockupView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVLockupView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupView~1focusSizeIncrease/title",
          "value": "focusSizeIncrease"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupView~1focusSizeIncrease/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focusSizeIncrease"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@S@NSDirectionalEdgeInsets/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSDirectionalEdgeInsets"
            },
            {
              "kind": "text",
              "text": " { ... } "
            },
            {
              "kind": "identifier",
              "text": "NSDirectionalEdgeInsets"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupView~1contentViewInsets/title",
          "value": "contentViewInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupView~1contentViewInsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentViewInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupView~1contentSize/title",
          "value": "contentSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupView~1contentSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentSize"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvuikit/tvlockupview/focussizeincrease"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvuikit/tvlockupview/focussizeincrease"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
