{
  "abstract": [
    {
      "text": "An object that provides forward and inverse discrete Fourier transforms on single- or double-precision collections of interleaved or split-complex data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Accelerate",
    "externalID": "s:10Accelerate4vDSPO24DiscreteFourierTransformC",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DiscreteFourierTransform"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DiscreteFourierTransform"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "vDSP.DiscreteFourierTransform"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DiscreteFourierTransform"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "genericParameter",
              "text": "T"
            },
            {
              "kind": "text",
              "text": "> "
            },
            {
              "kind": "keyword",
              "text": "where"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "text": "T"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DiscreteFourierTransformable",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate33vDSP_DiscreteFourierTransformableP",
              "text": "vDSP_DiscreteFourierTransformable"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to perform discrete Fourier transforms (DFTs) on split-complex or interleaved data. To learn more about working with split-complex and interleaved data, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Accelerate/performing-fourier-transforms-on-interleaved-complex-data",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance to work with interleaved data, pass either ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPComplex",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleComplex",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/init(previous:count:direction:transformType:ofType:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The following code shows how to perform a forward complex-to-complex DFT on the interleaved single-precision values in the ",
              "type": "text"
            },
            {
              "code": "interleavedInput",
              "type": "codeVoice"
            },
            {
              "text": " array:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// The `interleavedInput` array contains `complexValuesCount` `DSPComplex` elements.",
            "let interleavedInput: [DSPComplex] = [ ... ]",
            "",
            "let interleavedDFT = try? vDSP.DiscreteFourierTransform(previous: nil,",
            "                                                        count: complexValuesCount,",
            "                                                        direction: .forward,",
            "                                                        transformType: .complexComplex,",
            "                                                        ofType: DSPComplex.self)",
            "",
            "// On return, the `interleavedOutput` array contains an array of `DSPComplex`",
            "// structures.",
            "let interleavedOutput = interleavedDFT?.transform(input: interleavedInput)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance to work with split-complex data, pass either ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Swift/Float",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Swift/Double",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/init(previous:count:direction:transformType:ofType:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Split-complex data stores the real and imaginary parts of each complex value in separate arrays. The following code shows how to perform forward complex-to-complex DFT on the split-complex single-precision values in the ",
              "type": "text"
            },
            {
              "code": "splitComplexRealInput",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "splitComplexImaginaryInput",
              "type": "codeVoice"
            },
            {
              "text": " arrays:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var splitComplexRealInput: [Float] = [ ... ]",
            "var splitComplexImaginaryInput: [Float] = [ ... ]",
            "",
            "let splitComplexDFT = try? vDSP.DiscreteFourierTransform(previous: nil,",
            "                                                         count: complexValuesCount,",
            "                                                         direction: .forward,",
            "                                                         transformType: .complexComplex,",
            "                                                         ofType: Float.self)",
            "",
            "// The `splitComplexOutput` tuple contains two arrays that represent the",
            "// real and imaginary parts of the output.",
            "let splitComplexOutput = splitComplexDFT?.transform(real: splitComplexRealInput,",
            "                                                    imaginary: splitComplexImaginaryInput)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If the underlying data in both the ",
              "type": "text"
            },
            {
              "code": "interleavedInput",
              "type": "codeVoice"
            },
            {
              "text": " array and the split-complex input arrays is the same, for each ",
              "type": "text"
            },
            {
              "code": "i",
              "type": "codeVoice"
            },
            {
              "text": " in ",
              "type": "text"
            },
            {
              "code": "0 ..< complexValuesCount",
              "type": "codeVoice"
            },
            {
              "text": ", the following is true",
              "type": "text"
            },
            {
              "code": ":",
              "type": "codeVoice"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "interleavedOutput[i].real ≈ splitComplexOutput.real[i]",
            "interleavedOutput[i].imag ≈ splitComplexOutput.imaginary[i]"
          ],
          "syntax": "c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "``",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DSPComplex": {
      "abstract": [
        {
          "text": "A structure that represents a single-precision complex value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DSPComplex"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPComplex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DSPComplex"
        }
      ],
      "role": "symbol",
      "title": "DSPComplex",
      "type": "topic",
      "url": "/documentation/accelerate/dspcomplex"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleComplex": {
      "abstract": [
        {
          "text": "A structure that represents a double-precision complex value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DSPDoubleComplex"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleComplex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DSPDoubleComplex"
        }
      ],
      "role": "symbol",
      "title": "DSPDoubleComplex",
      "type": "topic",
      "url": "/documentation/accelerate/dspdoublecomplex"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP": {
      "abstract": [
        {
          "text": "An enumeration that acts as a namespace for Swift overlays to vDSP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP"
        }
      ],
      "role": "symbol",
      "title": "vDSP",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DFT": {
      "abstract": [
        {
          "text": "A single- and double-precision discrete Fourier transform.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DFT"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DFT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DFT"
        }
      ],
      "role": "symbol",
      "title": "vDSP.DFT",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/dft"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DFTTransformType": {
      "abstract": [
        {
          "text": "Discrete Fourier transform types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DFTTransformType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DFTTransformType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DFTTransformType"
        }
      ],
      "role": "symbol",
      "title": "vDSP.DFTTransformType",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/dfttransformtype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform": {
      "abstract": [
        {
          "text": "An object that provides forward and inverse discrete Fourier transforms on single- or double-precision collections of interleaved or split-complex data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DiscreteFourierTransform"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DiscreteFourierTransform"
        }
      ],
      "role": "symbol",
      "title": "vDSP.DiscreteFourierTransform",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/discretefouriertransform"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/init(previous:count:direction:transformType:ofType:)": {
      "abstract": [
        {
          "text": "Returns a new discrete Fourier transform instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "previous"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4vDSPO",
          "text": "vDSP"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4vDSPO24DiscreteFourierTransformC",
          "text": "DiscreteFourierTransform"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "direction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4vDSPO",
          "text": "vDSP"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4vDSPO25FourierTransformDirectionO",
          "text": "FourierTransformDirection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "transformType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4vDSPO",
          "text": "vDSP"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4vDSPO16DFTTransformTypeO",
          "text": "DFTTransformType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ".Type) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/init(previous:count:direction:transformType:ofType:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(previous:count:direction:transformType:ofType:)",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/discretefouriertransform/init(previous:count:direction:transformtype:oftype:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(input:)-5si4h": {
      "abstract": [
        {
          "text": "Returns the result of a double-precision discrete Fourier transform.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "T",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "DSPDoubleComplex",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transform"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "input"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@DSPDoubleComplex",
          "text": "DSPDoubleComplex"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(input:)-5si4h",
      "kind": "symbol",
      "role": "symbol",
      "title": "transform(input:)",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/discretefouriertransform/transform(input:)-5si4h"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(input:)-92b3l": {
      "abstract": [
        {
          "text": "Returns the result of a single-precision discrete Fourier transform.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "T",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "DSPComplex",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transform"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "input"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@DSPComplex",
          "text": "DSPComplex"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(input:)-92b3l",
      "kind": "symbol",
      "role": "symbol",
      "title": "transform(input:)",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/discretefouriertransform/transform(input:)-92b3l"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(input:output:)-1k3hd": {
      "abstract": [
        {
          "text": "Computes a single-precision discrete Fourier transform.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "T",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "DSPComplex",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transform"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "input"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "output"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(input:output:)-1k3hd",
      "kind": "symbol",
      "role": "symbol",
      "title": "transform(input:output:)",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/discretefouriertransform/transform(input:output:)-1k3hd"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(input:output:)-1tsod": {
      "abstract": [
        {
          "text": "Computes a double-precision discrete Fourier transform.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "T",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "DSPDoubleComplex",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transform"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "input"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "output"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(input:output:)-1tsod",
      "kind": "symbol",
      "role": "symbol",
      "title": "transform(input:output:)",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/discretefouriertransform/transform(input:output:)-1tsod"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(inputReal:inputImaginary:outputReal:outputImaginary:)-7115x": {
      "abstract": [
        {
          "text": "Computes a double-precision discrete Fourier transform.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "T",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "Double",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transform"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "inputReal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inputImaginary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "outputReal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "outputImaginary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(inputReal:inputImaginary:outputReal:outputImaginary:)-7115x",
      "kind": "symbol",
      "role": "symbol",
      "title": "transform(inputReal:inputImaginary:outputReal:outputImaginary:)",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/discretefouriertransform/transform(inputreal:inputimaginary:outputreal:outputimaginary:)-7115x"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(inputReal:inputImaginary:outputReal:outputImaginary:)-sihh": {
      "abstract": [
        {
          "text": "Computes a single-precision discrete Fourier transform.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "T",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "Float",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transform"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "inputReal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inputImaginary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "outputReal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "outputImaginary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(inputReal:inputImaginary:outputReal:outputImaginary:)-sihh",
      "kind": "symbol",
      "role": "symbol",
      "title": "transform(inputReal:inputImaginary:outputReal:outputImaginary:)",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/discretefouriertransform/transform(inputreal:inputimaginary:outputreal:outputimaginary:)-sihh"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(real:imaginary:)-4nwy9": {
      "abstract": [
        {
          "text": "Returns the result of a single-precision discrete Fourier transform.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "T",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "Float",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transform"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "real"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "imaginary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ") -> (real"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": "], imaginary"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(real:imaginary:)-4nwy9",
      "kind": "symbol",
      "role": "symbol",
      "title": "transform(real:imaginary:)",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/discretefouriertransform/transform(real:imaginary:)-4nwy9"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(real:imaginary:)-82jag": {
      "abstract": [
        {
          "text": "Returns the result of a double-precision discrete Fourier transform.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "T",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "Double",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transform"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "real"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "imaginary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "U"
        },
        {
          "kind": "text",
          "text": ") -> (real"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "], imaginary"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(real:imaginary:)-82jag",
      "kind": "symbol",
      "role": "symbol",
      "title": "transform(real:imaginary:)",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/discretefouriertransform/transform(real:imaginary:)-82jag"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DiscreteFourierTransformable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_DiscreteFourierTransformable"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DiscreteFourierTransformable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_DiscreteFourierTransformable"
        }
      ],
      "role": "symbol",
      "title": "vDSP_DiscreteFourierTransformable",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_discretefouriertransformable"
    },
    "doc://com.apple.documentation/documentation/Accelerate/performing-fourier-transforms-on-interleaved-complex-data": {
      "abstract": [
        {
          "text": "Optimize discrete Fourier transform (DFT) performance with the vDSP interleaved DFT routines.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Accelerate/performing-fourier-transforms-on-interleaved-complex-data",
      "kind": "article",
      "role": "article",
      "title": "Performing Fourier transforms on interleaved-complex data",
      "type": "topic",
      "url": "/documentation/Accelerate/performing-fourier-transforms-on-interleaved-complex-data"
    },
    "doc://com.apple.documentation/documentation/Swift/Double": {
      "abstract": [
        {
          "text": "A double-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/Double",
      "kind": "symbol",
      "role": "symbol",
      "title": "Double",
      "type": "topic",
      "url": "/documentation/Swift/Double"
    },
    "doc://com.apple.documentation/documentation/Swift/Float": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/Float",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Objects-that-simplify-discrete-Fourier-transforms",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DFTTransformType",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DFT"
      ],
      "title": "Objects that simplify discrete Fourier transforms"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Discrete-Fourier-Transform-Instance",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/init(previous:count:direction:transformType:ofType:)"
      ],
      "title": "Creating a Discrete Fourier Transform Instance"
    },
    {
      "anchor": "Performing-Split-Complex-Discrete-Fourier-Transforms",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(real:imaginary:)-4nwy9",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(real:imaginary:)-82jag",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(inputReal:inputImaginary:outputReal:outputImaginary:)-sihh",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(inputReal:inputImaginary:outputReal:outputImaginary:)-7115x"
      ],
      "title": "Performing Split-Complex Discrete Fourier Transforms"
    },
    {
      "anchor": "Performing-Interleaved-Discrete-Fourier-Transforms",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(input:)-92b3l",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(input:)-5si4h",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(input:output:)-1k3hd",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/DiscreteFourierTransform/transform(input:output:)-1tsod"
      ],
      "title": "Performing Interleaved Discrete Fourier Transforms"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPComplex/title",
          "value": "DSPComplex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPComplex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPComplex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPDoubleComplex/title",
          "value": "DSPDoubleComplex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPDoubleComplex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPDoubleComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPDoubleComplex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPDoubleComplex"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vdsp/discretefouriertransform"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
