{
  "abstract": [
    {
      "text": "A 1D single- and double-precision fast Fourier transform.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FFT"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Accelerate",
    "externalID": "s:10Accelerate4vDSPO3FFTC",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FFT"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FFT"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "vDSP.FFT"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FFT"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "genericParameter",
              "text": "T"
            },
            {
              "kind": "text",
              "text": "> "
            },
            {
              "kind": "keyword",
              "text": "where"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "text": "T"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_FourierTransformable",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Accelerate25vDSP_FourierTransformableP",
              "text": "vDSP_FourierTransformable"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/FFT_FORWARD": {
      "abstract": [
        {
          "text": "Forward FFT.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFT_FORWARD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/FFT_FORWARD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFT_FORWARD"
        }
      ],
      "role": "symbol",
      "title": "FFT_FORWARD",
      "type": "topic",
      "url": "/documentation/accelerate/fft_forward"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/FFT_INVERSE": {
      "abstract": [
        {
          "text": "Inverse FFT.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFT_INVERSE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/FFT_INVERSE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFT_INVERSE"
        }
      ],
      "role": "symbol",
      "title": "FFT_INVERSE",
      "type": "topic",
      "url": "/documentation/accelerate/fft_inverse"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/FFT_RADIX2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFT_RADIX2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/FFT_RADIX2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFT_RADIX2"
        }
      ],
      "role": "symbol",
      "title": "FFT_RADIX2",
      "type": "topic",
      "url": "/documentation/accelerate/fft_radix2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/FFT_RADIX3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFT_RADIX3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/FFT_RADIX3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFT_RADIX3"
        }
      ],
      "role": "symbol",
      "title": "FFT_RADIX3",
      "type": "topic",
      "url": "/documentation/accelerate/fft_radix3"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/FFT_RADIX5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFT_RADIX5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/FFT_RADIX5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFT_RADIX5"
        }
      ],
      "role": "symbol",
      "title": "FFT_RADIX5",
      "type": "topic",
      "url": "/documentation/accelerate/fft_radix5"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kFFTDirection_Forward": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFFTDirection_Forward"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kFFTDirection_Forward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFFTDirection_Forward"
        }
      ],
      "role": "symbol",
      "title": "kFFTDirection_Forward",
      "type": "topic",
      "url": "/documentation/accelerate/kfftdirection_forward"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kFFTDirection_Inverse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFFTDirection_Inverse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kFFTDirection_Inverse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFFTDirection_Inverse"
        }
      ],
      "role": "symbol",
      "title": "kFFTDirection_Inverse",
      "type": "topic",
      "url": "/documentation/accelerate/kfftdirection_inverse"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kFFTRadix2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFFTRadix2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kFFTRadix2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFFTRadix2"
        }
      ],
      "role": "symbol",
      "title": "kFFTRadix2",
      "type": "topic",
      "url": "/documentation/accelerate/kfftradix2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kFFTRadix3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFFTRadix3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kFFTRadix3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFFTRadix3"
        }
      ],
      "role": "symbol",
      "title": "kFFTRadix3",
      "type": "topic",
      "url": "/documentation/accelerate/kfftradix3"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kFFTRadix5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFFTRadix5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kFFTRadix5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFFTRadix5"
        }
      ],
      "role": "symbol",
      "title": "kFFTRadix5",
      "type": "topic",
      "url": "/documentation/accelerate/kfftradix5"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP": {
      "abstract": [
        {
          "text": "An enumeration that acts as a namespace for Swift overlays to vDSP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP"
        }
      ],
      "role": "symbol",
      "title": "vDSP",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FFT": {
      "abstract": [
        {
          "text": "A 1D single- and double-precision fast Fourier transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFT"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FFT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFT"
        }
      ],
      "role": "symbol",
      "title": "vDSP.FFT",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/fft"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FFT/forward(input:output:)": {
      "abstract": [
        {
          "text": "Computes an out-of-place forward fast Fourier transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forward"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "input"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@DSPSplitComplex",
          "text": "DSPSplitComplex"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "output"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@DSPSplitComplex",
          "text": "DSPSplitComplex"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FFT/forward(input:output:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "forward(input:output:)",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/fft/forward(input:output:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FFT/init(log2n:radix:ofType:)": {
      "abstract": [
        {
          "text": "Initializes a new fast Fourier transform instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "log2n"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vDSP_Length",
          "text": "vDSP_Length"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "radix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4vDSPO",
          "text": "vDSP"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4vDSPO5RadixO",
          "text": "Radix"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ".Type)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FFT/init(log2n:radix:ofType:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(log2n:radix:ofType:)",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/fft/init(log2n:radix:oftype:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FFT/inverse(input:output:)": {
      "abstract": [
        {
          "text": "Computes an out-of-place inverse fast Fourier transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inverse"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "input"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@DSPSplitComplex",
          "text": "DSPSplitComplex"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "output"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@DSPSplitComplex",
          "text": "DSPSplitComplex"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FFT/inverse(input:output:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "inverse(input:output:)",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/fft/inverse(input:output:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FFT/transform(input:output:direction:)": {
      "abstract": [
        {
          "text": "Computes an out-of-place fast Fourier transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transform"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "input"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "output"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "direction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4vDSPO",
          "text": "vDSP"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4vDSPO25FourierTransformDirectionO",
          "text": "FourierTransformDirection"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FFT/transform(input:output:direction:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "transform(input:output:direction:)",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/fft/transform(input:output:direction:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FFT2D": {
      "abstract": [
        {
          "text": "A 2D single- and double-precision fast Fourier transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFT2D"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FFT2D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFT2D"
        }
      ],
      "role": "symbol",
      "title": "vDSP.FFT2D",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/fft2d"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FourierTransformDirection": {
      "abstract": [
        {
          "text": "Fast Fourier transform directions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FourierTransformDirection"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FourierTransformDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FourierTransformDirection"
        }
      ],
      "role": "symbol",
      "title": "vDSP.FourierTransformDirection",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/fouriertransformdirection"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/Radix": {
      "abstract": [
        {
          "text": "Fast Fourier transform radices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Radix"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/Radix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Radix"
        }
      ],
      "role": "symbol",
      "title": "vDSP.Radix",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/radix"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_FourierTransformable": {
      "abstract": [
        {
          "text": "Types that support fast Fourier transform operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_FourierTransformable"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_FourierTransformable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_FourierTransformable"
        }
      ],
      "role": "symbol",
      "title": "vDSP_FourierTransformable",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_fouriertransformable"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FFT2D"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Objects-that-Simplify-FFTs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FFT2D",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FourierTransformDirection",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/Radix"
      ],
      "title": "Objects that Simplify FFTs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FFT/init(log2n:radix:ofType:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FFT/forward(input:output:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FFT/inverse(input:output:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/FFT/transform(input:output:direction:)"
      ],
      "title": "Instance Methods"
    },
    {
      "anchor": "Variables",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/FFT_FORWARD",
        "doc://com.apple.accelerate/documentation/Accelerate/FFT_INVERSE",
        "doc://com.apple.accelerate/documentation/Accelerate/FFT_RADIX2",
        "doc://com.apple.accelerate/documentation/Accelerate/FFT_RADIX3",
        "doc://com.apple.accelerate/documentation/Accelerate/FFT_RADIX5",
        "doc://com.apple.accelerate/documentation/Accelerate/kFFTDirection_Forward",
        "doc://com.apple.accelerate/documentation/Accelerate/kFFTDirection_Inverse",
        "doc://com.apple.accelerate/documentation/Accelerate/kFFTRadix2",
        "doc://com.apple.accelerate/documentation/Accelerate/kFFTRadix3",
        "doc://com.apple.accelerate/documentation/Accelerate/kFFTRadix5"
      ],
      "title": "Variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFT_FORWARD/title",
          "value": "FFT_FORWARD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFT_FORWARD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFT_FORWARD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kFFTRadix3/title",
          "value": "kFFTRadix3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kFFTRadix3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFFTRadix3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFT_INVERSE/title",
          "value": "FFT_INVERSE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFT_INVERSE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFT_INVERSE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFT_RADIX3/title",
          "value": "FFT_RADIX3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFT_RADIX3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFT_RADIX3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFT_RADIX5/title",
          "value": "FFT_RADIX5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFT_RADIX5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFT_RADIX5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kFFTRadix2/title",
          "value": "kFFTRadix2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kFFTRadix2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFFTRadix2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kFFTDirection_Inverse/title",
          "value": "kFFTDirection_Inverse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kFFTDirection_Inverse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFFTDirection_Inverse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFT_RADIX2/title",
          "value": "FFT_RADIX2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFT_RADIX2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFT_RADIX2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kFFTRadix5/title",
          "value": "kFFTRadix5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kFFTRadix5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFFTRadix5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kFFTDirection_Forward/title",
          "value": "kFFTDirection_Forward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kFFTDirection_Forward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFFTDirection_Forward"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vdsp/fft"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
