{"schemaVersion":{"major":0,"minor":3,"patch":0},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/all"},{"text":" instead.","type":"text"}]}],"abstract":[{"type":"text","text":"All edges."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/all"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uidirectionalrectedge/all"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uidirectionalrectedge/all"]}],"metadata":{"title":"all","symbolKind":"property","platforms":[{"deprecatedAt":"13.0","introducedAt":"13.0","deprecated":false,"unavailable":false,"name":"iOS","renamed":"NSDirectionalRectEdge","beta":false},{"deprecatedAt":"13.0","introducedAt":"13.0","deprecated":false,"unavailable":false,"name":"iPadOS","renamed":"NSDirectionalRectEdge","beta":false},{"deprecatedAt":"13.1","introducedAt":"13.1","deprecated":false,"unavailable":false,"name":"Mac Catalyst","renamed":"NSDirectionalRectEdge","beta":false},{"deprecatedAt":"13.0","introducedAt":"13.0","deprecated":false,"unavailable":false,"name":"tvOS","renamed":"NSDirectionalRectEdge","beta":false},{"deprecatedAt":"6.0","introducedAt":"6.0","deprecated":false,"unavailable":false,"name":"watchOS","renamed":"NSDirectionalRectEdge","beta":false}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"all","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIDirectionalRectEdge","preciseIdentifier":"c:@E@UIDirectionalRectEdge","kind":"typeIdentifier"}],"modules":[{"name":"UIKit"}],"roleHeading":"Type Property","navigatorTitle":[{"text":"UIDirectionalRectEdgeAll","kind":"identifier"}],"externalID":"c:@E@UIDirectionalRectEdge@UIDirectionalRectEdgeAll"},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIDirectionalRectEdge","text":"UIDirectionalRectEdge"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","watchOS"]}],"kind":"declarations"}],"sections":[],"seeAlsoSections":[{"anchor":"Constants","title":"Constants","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/top","doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/leading","doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/bottom","doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/trailing"]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/all":{"title":"all","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/all","abstract":[{"text":"All edges.","type":"text"}],"deprecated":true,"type":"topic","navigatorTitle":[{"text":"UIDirectionalRectEdgeAll","kind":"identifier"}],"url":"/documentation/uikit/uidirectionalrectedge/all","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"all","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIDirectionalRectEdge","text":"UIDirectionalRectEdge","kind":"typeIdentifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/UIDirectionalRectEdgeNone":{"deprecated":true,"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/UIDirectionalRectEdgeNone","role":"symbol","fragments":[{"text":"UIDirectionalRectEdgeNone","kind":"identifier"}],"url":"/documentation/uikit/uidirectionalrectedge/uidirectionalrectedgenone","abstract":[{"text":"No specified edge.","type":"text"}],"title":"UIDirectionalRectEdgeNone","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/leading":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leading","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIDirectionalRectEdge","text":"UIDirectionalRectEdge","kind":"typeIdentifier"}],"title":"leading","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/leading","role":"symbol","type":"topic","url":"/documentation/uikit/uidirectionalrectedge/leading","abstract":[{"type":"text","text":"The leading edge."}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"text":"UIDirectionalRectEdgeLeading","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/bottom":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIDirectionalRectEdge","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIDirectionalRectEdge"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The bottom edge."}],"deprecated":true,"url":"/documentation/uikit/uidirectionalrectedge/bottom","navigatorTitle":[{"text":"UIDirectionalRectEdgeBottom","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/bottom","title":"bottom"},"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/top":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"top","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIDirectionalRectEdge","preciseIdentifier":"c:@E@UIDirectionalRectEdge","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIDirectionalRectEdgeTop","kind":"identifier"}],"title":"top","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/top","deprecated":true,"type":"topic","url":"/documentation/uikit/uidirectionalrectedge/top","kind":"symbol","abstract":[{"text":"The top edge.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/trailing":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trailing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIDirectionalRectEdge","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIDirectionalRectEdge"}],"navigatorTitle":[{"text":"UIDirectionalRectEdgeTrailing","kind":"identifier"}],"title":"trailing","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/trailing","deprecated":true,"type":"topic","url":"/documentation/uikit/uidirectionalrectedge/trailing","kind":"symbol","abstract":[{"text":"The trailing edge.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge":{"navigatorTitle":[{"text":"UIDirectionalRectEdge","kind":"identifier"}],"deprecated":true,"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDirectionalRectEdge","kind":"identifier"}],"url":"/documentation/uikit/uidirectionalrectedge","abstract":[{"text":"Constants that specify an edge or a set of edges, taking the user interface layout direction into account.","type":"text"}],"title":"UIDirectionalRectEdge","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/all":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"all","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSDirectionalRectEdge","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSDirectionalRectEdge"}],"role":"symbol","title":"all","url":"/documentation/uikit/nsdirectionalrectedge/all","identifier":"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/all","navigatorTitle":[{"text":"NSDirectionalRectEdgeAll","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"All edges.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecatedAt":"13.0","name":"iOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"13.0"},{"deprecatedAt":"13.0","name":"iPadOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"13.0"},{"deprecatedAt":"13.1","name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"13.1"},{"deprecatedAt":"13.0","name":"tvOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"13.0"},{"deprecatedAt":"6.0","name":"watchOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"6.0"}],"path":"/metadata/platforms","op":"replace"},{"value":"Enumeration Case","path":"/metadata/roleHeading","op":"replace"},{"value":"UIDirectionalRectEdgeAll","path":"/metadata/title","op":"replace"},{"value":"case","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"UIDirectionalRectEdgeAll"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge"]]},"path":"/hierarchy","op":"replace"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Constants","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/UIDirectionalRectEdgeNone","doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/top","doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/leading","doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/bottom","doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/trailing"],"title":"Constants","generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"UIDirectionalRectEdgeAll","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","path":"/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/all","type":"reference","isActive":true},{"type":"text","text":" instead."}]}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1all/title","value":"UIDirectionalRectEdgeAll"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1all/fragments","value":[{"kind":"identifier","text":"UIDirectionalRectEdgeAll"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1leading/title","value":"UIDirectionalRectEdgeLeading"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1leading/fragments","value":[{"text":"UIDirectionalRectEdgeLeading","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1bottom/title","value":"UIDirectionalRectEdgeBottom"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1bottom/fragments","value":[{"text":"UIDirectionalRectEdgeBottom","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1top/title","value":"UIDirectionalRectEdgeTop"},{"value":[{"text":"UIDirectionalRectEdgeTop","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1top/fragments","op":"replace"},{"value":"UIDirectionalRectEdgeTrailing","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1trailing/title","op":"replace"},{"value":[{"text":"UIDirectionalRectEdgeTrailing","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1trailing/fragments","op":"replace"},{"value":"UIDirectionalRectEdge","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge/title","op":"replace"},{"value":[{"text":"UIDirectionalRectEdge","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UIDirectionalRectEdge"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge/navigatorTitle","op":"replace"},{"value":"NSDirectionalRectEdgeAll","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge~1all/title","op":"replace"},{"value":[{"text":"NSDirectionalRectEdgeAll","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge~1all/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}