{"deprecationSummary":[{"inlineContent":[{"text":"Use ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/NSDirectionalRectEdgeNone","type":"reference"},{"text":" instead.","type":"text"}],"type":"paragraph"}],"sections":[],"seeAlsoSections":[{"generated":true,"title":"Constants","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/top","doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/leading","doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/bottom","doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/trailing","doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/all"],"anchor":"Constants"}],"variants":[{"paths":["/documentation/uikit/uidirectionalrectedge/uidirectionalrectedgenone"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/UIDirectionalRectEdgeNone"},"abstract":[{"text":"No specified edge.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"UIDirectionalRectEdgeNone"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"]}]}],"kind":"symbol","metadata":{"symbolKind":"case","platforms":[{"beta":false,"introducedAt":"13.0","deprecatedAt":"13.0","name":"iOS","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"13.0","deprecatedAt":"13.0","name":"iPadOS","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"13.1","deprecatedAt":"13.1","name":"Mac Catalyst","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"13.0","deprecatedAt":"13.0","name":"tvOS","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"6.0","deprecatedAt":"6.0","name":"watchOS","deprecated":false,"unavailable":false}],"fragments":[{"text":"UIDirectionalRectEdgeNone","kind":"identifier"}],"role":"symbol","externalID":"c:@E@UIDirectionalRectEdge@UIDirectionalRectEdgeNone","modules":[{"name":"UIKit"}],"title":"UIDirectionalRectEdgeNone","navigatorTitle":[{"text":"UIDirectionalRectEdgeNone","kind":"identifier"}],"roleHeading":"Enumeration Case"},"references":{"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/all":{"title":"all","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/all","abstract":[{"text":"All edges.","type":"text"}],"deprecated":true,"type":"topic","navigatorTitle":[{"text":"UIDirectionalRectEdgeAll","kind":"identifier"}],"url":"/documentation/uikit/uidirectionalrectedge/all","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"all","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIDirectionalRectEdge","text":"UIDirectionalRectEdge","kind":"typeIdentifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/trailing":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trailing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIDirectionalRectEdge","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIDirectionalRectEdge"}],"navigatorTitle":[{"text":"UIDirectionalRectEdgeTrailing","kind":"identifier"}],"title":"trailing","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/trailing","deprecated":true,"type":"topic","url":"/documentation/uikit/uidirectionalrectedge/trailing","kind":"symbol","abstract":[{"text":"The trailing edge.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/bottom":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIDirectionalRectEdge","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIDirectionalRectEdge"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The bottom edge."}],"deprecated":true,"url":"/documentation/uikit/uidirectionalrectedge/bottom","navigatorTitle":[{"text":"UIDirectionalRectEdgeBottom","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/bottom","title":"bottom"},"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/UIDirectionalRectEdgeNone":{"deprecated":true,"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/UIDirectionalRectEdgeNone","role":"symbol","fragments":[{"text":"UIDirectionalRectEdgeNone","kind":"identifier"}],"url":"/documentation/uikit/uidirectionalrectedge/uidirectionalrectedgenone","abstract":[{"text":"No specified edge.","type":"text"}],"title":"UIDirectionalRectEdgeNone","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/NSDirectionalRectEdgeNone":{"role":"symbol","fragments":[{"text":"NSDirectionalRectEdgeNone","kind":"identifier"}],"title":"NSDirectionalRectEdgeNone","identifier":"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/NSDirectionalRectEdgeNone","type":"topic","url":"/documentation/uikit/nsdirectionalrectedge/nsdirectionalrectedgenone","kind":"symbol","abstract":[{"text":"No specified edge.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/top":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"top","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIDirectionalRectEdge","preciseIdentifier":"c:@E@UIDirectionalRectEdge","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIDirectionalRectEdgeTop","kind":"identifier"}],"title":"top","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/top","deprecated":true,"type":"topic","url":"/documentation/uikit/uidirectionalrectedge/top","kind":"symbol","abstract":[{"text":"The top edge.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge":{"navigatorTitle":[{"text":"UIDirectionalRectEdge","kind":"identifier"}],"deprecated":true,"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDirectionalRectEdge","kind":"identifier"}],"url":"/documentation/uikit/uidirectionalrectedge","abstract":[{"text":"Constants that specify an edge or a set of edges, taking the user interface layout direction into account.","type":"text"}],"title":"UIDirectionalRectEdge","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/leading":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leading","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIDirectionalRectEdge","text":"UIDirectionalRectEdge","kind":"typeIdentifier"}],"title":"leading","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge/leading","role":"symbol","type":"topic","url":"/documentation/uikit/uidirectionalrectedge/leading","abstract":[{"type":"text","text":"The leading edge."}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"text":"UIDirectionalRectEdgeLeading","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"UIDirectionalRectEdgeAll","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1all/title"},{"value":[{"text":"UIDirectionalRectEdgeAll","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1all/fragments"},{"value":"UIDirectionalRectEdgeTrailing","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1trailing/title"},{"value":[{"text":"UIDirectionalRectEdgeTrailing","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1trailing/fragments"},{"value":"UIDirectionalRectEdgeBottom","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1bottom/title"},{"value":[{"text":"UIDirectionalRectEdgeBottom","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1bottom/fragments"},{"value":"UIDirectionalRectEdgeTop","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1top/title"},{"value":[{"kind":"identifier","text":"UIDirectionalRectEdgeTop"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1top/fragments"},{"value":"UIDirectionalRectEdge","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge/title"},{"value":[{"kind":"identifier","text":"UIDirectionalRectEdge"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge/fragments"},{"value":[{"text":"UIDirectionalRectEdge","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge/navigatorTitle"},{"value":"UIDirectionalRectEdgeLeading","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1leading/title"},{"value":[{"text":"UIDirectionalRectEdgeLeading","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge~1leading/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}