{
  "abstract": [
    {
      "text": "Returns a Boolean value that indicates whether it is safe to autosave document changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDocument/checkAutosavingSafety()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSDocument(im)checkAutosavingSafetyAndReturnError:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "checkAutosavingSafety"
      },
      {
        "kind": "text",
        "text": "() "
      },
      {
        "kind": "keyword",
        "text": "throws"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "checkAutosavingSafetyAndReturnError:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "checkAutosavingSafety()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "checkAutosavingSafety"
            },
            {
              "kind": "text",
              "text": "() "
            },
            {
              "kind": "keyword",
              "text": "throws"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default implementation of this method checks for documents that have not been changed in a while (“a while” is subject to change) or are saved in folders where the user typically does not edit documents (the ",
              "type": "text"
            },
            {
              "code": "~/Downloads",
              "type": "codeVoice"
            },
            {
              "text": " folder, for example). When it senses one of those cases it returns ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with an ",
              "type": "text"
            },
            {
              "code": "NSError",
              "type": "codeVoice"
            },
            {
              "text": " object that has recovery options like Duplicate, Cancel, and Unlock.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In an app that has adopted autosaving in place by overriding ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/autosavesInPlace",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to return ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you can override this method to customize the autosaving safety checking that ",
              "type": "text"
            },
            {
              "code": "NSDocument",
              "type": "codeVoice"
            },
            {
              "text": " does by default. You can remove the ",
              "type": "text"
            },
            {
              "code": "NSDocument",
              "type": "codeVoice"
            },
            {
              "text": " default checking by overriding this method and not invoking super. You can add to the ",
              "type": "text"
            },
            {
              "code": "NSDocument",
              "type": "codeVoice"
            },
            {
              "text": " default checking by invoking super and then doing your own checking if ",
              "type": "text"
            },
            {
              "code": "[super checkAutosavingSafetyAndReturnError:]",
              "type": "codeVoice"
            },
            {
              "text": " did not signal an error. For example, TextEdit overrides this method to ask the user what to do when opening a document file has been lossy and overwriting that file might therefore be lossy.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When autosaving in place is turned on an ",
              "type": "text"
            },
            {
              "code": "NSDocument",
              "type": "codeVoice"
            },
            {
              "text": " object may invoke this method when it receives notification from its ",
              "type": "text"
            },
            {
              "code": "NSUndoManager",
              "type": "codeVoice"
            },
            {
              "text": " object that the user changed the document, or undid or redid a change. If an error is returned, ",
              "type": "text"
            },
            {
              "code": "NSDocument",
              "type": "codeVoice"
            },
            {
              "text": " presents the error to the user, allowing the user to choose a recovery option. If the user chooses a recovery option, then ",
              "type": "text"
            },
            {
              "code": "NSDocument",
              "type": "codeVoice"
            },
            {
              "text": " invokes this method again until no error is signaled, to make sure that all checks have been done. This means that when you signal an error and the user’s choice of recovery option indicates that they have seen and disregarded a safety concern, you must record that fact and not do that particular safety check again. Once all errors are handled, ",
              "type": "text"
            },
            {
              "code": "NSDocument",
              "type": "codeVoice"
            },
            {
              "text": " continues by invoking ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/updateChangeCount(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". If the user does not recover from an error, then ",
              "type": "text"
            },
            {
              "code": "NSDocument",
              "type": "codeVoice"
            },
            {
              "text": " invokes one of the ",
              "type": "text"
            },
            {
              "code": "NSUndoManager",
              "type": "codeVoice"
            },
            {
              "text": " methods ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/undomanager/1412189-undo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/undomanager/1417030-redo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to roll back the change. So, some of the ",
              "type": "text"
            },
            {
              "code": "NSError",
              "type": "codeVoice"
            },
            {
              "text": " recovery options the user can choose, like the ",
              "type": "text"
            },
            {
              "code": "NSDocument",
              "type": "codeVoice"
            },
            {
              "text": " options Duplicate and Cancel, should indicate failed recovery and cause the document to remain unchanged afterward.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "In Swift, this method is marked with the ",
                  "type": "text"
                },
                {
                  "code": "throws",
                  "type": "codeVoice"
                },
                {
                  "text": " keyword to indicate that it throws an error in cases of failure.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "When overriding this method, use the ",
                  "type": "text"
                },
                {
                  "code": "throw",
                  "type": "codeVoice"
                },
                {
                  "text": " statement to throw an ",
                  "type": "text"
                },
                {
                  "code": "NSError",
                  "type": "codeVoice"
                },
                {
                  "text": ", as described in ",
                  "type": "text"
                },
                {
                  "identifier": "https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " in ",
                  "type": "text"
                },
                {
                  "identifier": "https://docs.swift.org/swift-book/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "About Imported Cocoa Error Parameters",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Handling Errors in Swift",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument": {
      "abstract": [
        {
          "text": "An abstract class that defines the interface for macOS documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDocument"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDocument"
        }
      ],
      "role": "symbol",
      "title": "NSDocument",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/autosave(withDelegate:didAutosave:contextInfo:)": {
      "abstract": [
        {
          "text": "Autosaves the document’s contents to an appropriate location in the file system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autosave"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withDelegate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "didAutosave"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "contextInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/autosave(withDelegate:didAutosave:contextInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autosaveDocumentWithDelegate:didAutosaveSelector:contextInfo:"
        }
      ],
      "role": "symbol",
      "title": "autosave(withDelegate:didAutosave:contextInfo:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/autosave(withdelegate:didautosave:contextinfo:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/autosave(withImplicitCancellability:completionHandler:)": {
      "abstract": [
        {
          "text": "Autosaves the document’s contents to an appropriate file-system location, as needed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autosave"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withImplicitCancellability"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/autosave(withImplicitCancellability:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autosaveWithImplicitCancellability:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "autosave(withImplicitCancellability:completionHandler:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/autosave(withimplicitcancellability:completionhandler:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/autosavesInPlace": {
      "abstract": [
        {
          "text": "Returns whether the receiver supports autosaving in place.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autosavesInPlace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/autosavesInPlace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autosavesInPlace"
        }
      ],
      "role": "symbol",
      "title": "autosavesInPlace",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/autosavesinplace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/backupFileURL": {
      "abstract": [
        {
          "text": "The URL for the document’s backup file that was created during an autosave operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backupFileURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/backupFileURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backupFileURL"
        }
      ],
      "role": "symbol",
      "title": "backupFileURL",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/backupfileurl"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/checkAutosavingSafety()": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether it is safe to autosave document changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "checkAutosavingSafety"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/checkAutosavingSafety()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "checkAutosavingSafetyAndReturnError:"
        }
      ],
      "role": "symbol",
      "title": "checkAutosavingSafety()",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/checkautosavingsafety()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/hasUnautosavedChanges": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the document has changes that have not been autosaved.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasUnautosavedChanges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/hasUnautosavedChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasUnautosavedChanges"
        }
      ],
      "role": "symbol",
      "title": "hasUnautosavedChanges",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/hasunautosavedchanges"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/scheduleAutosaving()": {
      "abstract": [
        {
          "text": "Schedules periodic autosaving for the purpose of crash protection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduleAutosaving"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/scheduleAutosaving()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scheduleAutosaving"
        }
      ],
      "role": "symbol",
      "title": "scheduleAutosaving()",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/scheduleautosaving()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/updateChangeCount(_:)": {
      "abstract": [
        {
          "text": "Updates the receiver’s change count according to the given change type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateChangeCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDocument",
          "text": "NSDocument"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDocumentChangeType",
          "text": "ChangeType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/updateChangeCount(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateChangeCount:"
        }
      ],
      "role": "symbol",
      "title": "updateChangeCount(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/updatechangecount(_:)"
    },
    "doc://com.apple.documentation/documentation/foundation/undomanager/1412189-undo": {
      "abstract": [
        {
          "text": "Closes the top-level undo group if necessary, and then performs undo operations on the group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "undo"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/undomanager/1412189-undo",
      "kind": "symbol",
      "role": "symbol",
      "title": "undo()",
      "type": "topic",
      "url": "/documentation/foundation/undomanager/1412189-undo"
    },
    "doc://com.apple.documentation/documentation/foundation/undomanager/1417030-redo": {
      "abstract": [
        {
          "text": "Performs the operations in the last group on the redo stack, if there are any, recording them on the undo stack as a single group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "redo"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/undomanager/1417030-redo",
      "kind": "symbol",
      "role": "symbol",
      "title": "redo()",
      "type": "topic",
      "url": "/documentation/foundation/undomanager/1417030-redo"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "https://docs.swift.org/swift-book/": {
      "identifier": "https://docs.swift.org/swift-book/",
      "title": "The Swift Programming Language",
      "titleInlineContent": [
        {
          "text": "The Swift Programming Language",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://docs.swift.org/swift-book/"
    },
    "https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html": {
      "identifier": "https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html",
      "title": "Error Handling",
      "titleInlineContent": [
        {
          "text": "Error Handling",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Autosaving-the-Document",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/hasUnautosavedChanges",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/scheduleAutosaving()",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/autosave(withDelegate:didAutosave:contextInfo:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/autosave(withImplicitCancellability:completionHandler:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/backupFileURL"
      ],
      "title": "Autosaving the Document"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "checkAutosavingSafetyAndReturnError:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "checkAutosavingSafetyAndReturnError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Autosaving-the-Document",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/hasUnautosavedChanges",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/scheduleAutosaving()",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/autosave(withDelegate:didAutosave:contextInfo:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/autosave(withImplicitCancellability:completionHandler:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/backupFileURL"
              ],
              "title": "Autosaving the Document"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "checkAutosavingSafetyAndReturnError:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "outError"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "If ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/false",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " is returned, a pointer to an error object that encapsulates the reason the document should not be autosaved.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "outError"
              }
            ]
          }
        },
        {
          "op": "add",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/true",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if autosaving the document is probably safe; otherwise, ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/false",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1checkAutosavingSafety()/title",
          "value": "checkAutosavingSafetyAndReturnError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1checkAutosavingSafety()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "checkAutosavingSafetyAndReturnError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/title",
          "value": "NSDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1hasUnautosavedChanges/title",
          "value": "hasUnautosavedChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1hasUnautosavedChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasUnautosavedChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1autosave(withDelegate:didAutosave:contextInfo:)/title",
          "value": "autosaveDocumentWithDelegate:didAutosaveSelector:contextInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1autosave(withDelegate:didAutosave:contextInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "autosaveDocumentWithDelegate:didAutosaveSelector:contextInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1updateChangeCount(_:)/title",
          "value": "updateChangeCount:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1updateChangeCount(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateChangeCount:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1autosave(withImplicitCancellability:completionHandler:)/title",
          "value": "autosaveWithImplicitCancellability:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1autosave(withImplicitCancellability:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "autosaveWithImplicitCancellability:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1scheduleAutosaving()/title",
          "value": "scheduleAutosaving"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1scheduleAutosaving()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scheduleAutosaving"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1undomanager~11412189-undo/title",
          "value": "undo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1autosavesInPlace/title",
          "value": "autosavesInPlace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1autosavesInPlace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autosavesInPlace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1backupFileURL/title",
          "value": "backupFileURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1backupFileURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backupFileURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1undomanager~11417030-redo/title",
          "value": "redo"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdocument/checkautosavingsafety()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsdocument/checkautosavingsafety()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
