{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"print"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSettings"},{"kind":"text","text":" "},{"kind":"internalParam","text":"printSettings"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPrintInfo","text":"NSPrintInfo","preciseIdentifier":"c:objc(cs)NSPrintInfo"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey","text":"AttributeKey","preciseIdentifier":"c:@T@NSPrintInfoAttributeKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"showPrintPanel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"didPrint","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"didPrintSelector","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10ObjectiveC8SelectorV","identifier":"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV","text":"Selector","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"contextInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sv","identifier":"doc://com.externally.resolved.symbol/s:Sv","text":"UnsafeMutableRawPointer","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The print settings dictionary to use.","type":"text"}],"type":"paragraph"}],"name":"printSettings"},{"content":[{"inlineContent":[{"type":"text","text":"A Boolean value indicating whether the print panel is shown."}],"type":"paragraph"}],"name":"showPrintPanel"},{"content":[{"inlineContent":[{"text":"The delegate to which the selector message is sent.","type":"text"}],"type":"paragraph"}],"name":"delegate"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The selector of the message sent to the delegate."}]}],"name":"didPrintSelector"},{"content":[{"inlineContent":[{"text":"Object passed with the callback to provide any additional context information.","type":"text"}],"type":"paragraph"}],"name":"contextInfo"}]},{"kind":"content","content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"If showing of the print panel is specified by ","type":"text"},{"type":"codeVoice","code":"showPrintPanel"},{"text":", the method presents it first and prints only if the user approves the panel. The ","type":"text"},{"type":"codeVoice","code":"NSPrintInfo"},{"text":" attributes in the passed-in ","type":"text"},{"type":"codeVoice","code":"printSettings"},{"text":" dictionary are added to a copy of the document’s print info, and the resulting print info settings are used for the operation. When printing is complete or canceled, the method sends the message selected by ","type":"text"},{"type":"codeVoice","code":"didPrintSelector"},{"text":" to the ","type":"text"},{"type":"codeVoice","code":"delegate"},{"text":", with the ","type":"text"},{"type":"codeVoice","code":"contextInfo"},{"text":" as the last argument. The method selected by ","type":"text"},{"type":"codeVoice","code":"didPrintSelector"},{"text":" must have the same signature as:","type":"text"}],"type":"paragraph"},{"code":["- (void)document:(NSDocument *)document didPrint:(BOOL)didPrintSuccessfully  contextInfo: (void *)contextInfo"],"syntax":"objc","type":"codeListing"},{"inlineContent":[{"type":"text","text":"The default implementation of this method invokes "},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/printOperation(withSettings:)","type":"reference"},{"type":"text","text":". If "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" is returned it presents the error to the user in a document-modal panel before messaging the delegate. Otherwise it invokes "},{"code":"[thePrintOperation setShowsPrintPanel:showPrintPanel]","type":"codeVoice"},{"type":"text","text":" then "},{"code":"[self runModalPrintOperation:thePrintOperation delegate:delegate didRunSelector:didPrintSelector contextInfo:contextInfo]","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"text":"For backward binary compatibility with OS X v10.3 and earlier, the default implementation of this method invokes ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/printShowingPrintPanel:","type":"reference"},{"text":" if it is overridden. When doing this it uses private functionality to arrange for the print settings to take effect (despite the fact that the override of ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/printShowingPrintPanel:","type":"reference"},{"text":" can’t possibly know about them) and to get notified when the print operation has been completed, so it can message the delegate at the correct time. Correct messaging of the delegate is necessary for correct handling of the Print Apple event.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"text":"Prints the document’s contents, optionally displaying a print panel to the user.","type":"text"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"print"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSettings"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSPrintInfo","kind":"typeIdentifier","text":"NSPrintInfo"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSPrintInfoAttributeKey","kind":"typeIdentifier","text":"AttributeKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"showPrintPanel"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"didPrint"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"contextInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"printDocumentWithSettings:showPrintPanel:delegate:didPrintSelector:contextInfo:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"AppKit"}],"title":"print(withSettings:showPrintPanel:delegate:didPrint:contextInfo:)","platforms":[{"unavailable":false,"name":"macOS","deprecated":false,"beta":false}],"externalID":"c:objc(cs)NSDocument(im)printDocumentWithSettings:showPrintPanel:delegate:didPrintSelector:contextInfo:"},"seeAlsoSections":[{"title":"Printing the Document","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/printInfo","doc://com.apple.appkit/documentation/AppKit/NSDocument/preparePageLayout(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayout(with:delegate:didRun:contextInfo:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPrintOperation(_:delegate:didRun:contextInfo:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/shouldChangePrintInfo(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/printOperation(withSettings:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/pdfPrintOperation","doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToPDF(_:)"],"anchor":"Printing-the-Document","generated":true}],"sections":[],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSDocument/print(withSettings:showPrintPanel:delegate:didPrint:contextInfo:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDocument"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsdocument/print(withsettings:showprintpanel:delegate:didprint:contextinfo:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsdocument/print(withsettings:showprintpanel:delegate:didprint:contextinfo:)"]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSDocument/printOperation(withSettings:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/printOperation(withSettings:)","type":"topic","url":"/documentation/appkit/nsdocument/printoperation(withsettings:)","navigatorTitle":[{"text":"printOperationWithSettings:error:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"printOperation"},{"text":"(","kind":"text"},{"text":"withSettings","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"NSPrintInfo","preciseIdentifier":"c:objc(cs)NSPrintInfo","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"AttributeKey","preciseIdentifier":"c:@T@NSPrintInfoAttributeKey","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSPrintOperation","text":"NSPrintOperation","kind":"typeIdentifier"}],"title":"printOperation(withSettings:)","abstract":[{"type":"text","text":"Creates and returns a print operation for the document’s contents."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSPrintInfo":{"navigatorTitle":[{"kind":"identifier","text":"NSPrintInfo"}],"title":"NSPrintInfo","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSPrintInfo"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPrintInfo","abstract":[{"text":"An object that stores information that’s used to generate printed output.","type":"text"}],"role":"symbol","url":"/documentation/appkit/nsprintinfo","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPrintOperation(_:delegate:didRun:contextInfo:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPrintOperation(_:delegate:didRun:contextInfo:)","type":"topic","url":"/documentation/appkit/nsdocument/runmodalprintoperation(_:delegate:didrun:contextinfo:)","navigatorTitle":[{"text":"runModalPrintOperation:delegate:didRunSelector:contextInfo:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"runModalPrintOperation","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSPrintOperation","kind":"typeIdentifier","text":"NSPrintOperation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"didRun"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"contextInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"runModalPrintOperation(_:delegate:didRun:contextInfo:)","abstract":[{"type":"text","text":"Runs the specified print operation modally."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/print(withSettings:showPrintPanel:delegate:didPrint:contextInfo:)":{"url":"/documentation/appkit/nsdocument/print(withsettings:showprintpanel:delegate:didprint:contextinfo:)","title":"print(withSettings:showPrintPanel:delegate:didPrint:contextInfo:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/print(withSettings:showPrintPanel:delegate:didPrint:contextInfo:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"print","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withSettings","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"NSPrintInfo","preciseIdentifier":"c:objc(cs)NSPrintInfo","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"AttributeKey","preciseIdentifier":"c:@T@NSPrintInfoAttributeKey","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"showPrintPanel","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"didPrint","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"contextInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Prints the document’s contents, optionally displaying a print panel to the user."}],"kind":"symbol","navigatorTitle":[{"text":"printDocumentWithSettings:showPrintPanel:delegate:didPrintSelector:contextInfo:","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/printShowingPrintPanel:":{"fragments":[{"text":"- ","kind":"text"},{"text":"printShowingPrintPanel:","kind":"identifier"}],"title":"printShowingPrintPanel:","url":"/documentation/appkit/nsdocument/printshowingprintpanel:","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/printShowingPrintPanel:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"printShowingPrintPanel:"}],"kind":"symbol","abstract":[{"text":"Prints the current document’s data.","type":"text"}],"deprecated":true},"doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToPDF(_:)":{"navigatorTitle":[{"kind":"identifier","text":"saveDocumentToPDF:"}],"type":"topic","kind":"symbol","title":"saveToPDF(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToPDF(_:)","role":"symbol","url":"/documentation/appkit/nsdocument/savetopdf(_:)","abstract":[{"text":"Exports a PDF representation of the document’s current contents.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"saveToPDF"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/pdfPrintOperation":{"navigatorTitle":[{"kind":"identifier","text":"PDFPrintOperation"}],"type":"topic","kind":"symbol","title":"pdfPrintOperation","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/pdfPrintOperation","role":"symbol","url":"/documentation/appkit/nsdocument/pdfprintoperation","abstract":[{"text":"A print operation you can use to create a PDF representation of the document’s current contents.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pdfPrintOperation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSPrintOperation","kind":"typeIdentifier","text":"NSPrintOperation"}]},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/printInfo":{"type":"topic","navigatorTitle":[{"text":"printInfo","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/printInfo","kind":"symbol","url":"/documentation/appkit/nsdocument/printinfo","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"printInfo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSPrintInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPrintInfo"}],"abstract":[{"type":"text","text":"The printing information associated with the document."}],"role":"symbol","title":"printInfo"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayout(with:delegate:didRun:contextInfo:)":{"url":"/documentation/appkit/nsdocument/runmodalpagelayout(with:delegate:didrun:contextinfo:)","title":"runModalPageLayout(with:delegate:didRun:contextInfo:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayout(with:delegate:didRun:contextInfo:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"runModalPageLayout","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPrintInfo","preciseIdentifier":"c:objc(cs)NSPrintInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"didRun","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"contextInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Runs the modal page layout panel with the receiver’s printing information object."}],"kind":"symbol","navigatorTitle":[{"text":"runModalPageLayoutWithPrintInfo:delegate:didRunSelector:contextInfo:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:Sv":{"role":"symbol","abstract":[{"type":"text","text":"A raw pointer for accessing and manipulating untyped data."}],"title":"UnsafeMutableRawPointer","kind":"symbol","url":"/documentation/Swift/UnsafeMutableRawPointer","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnsafeMutableRawPointer","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:Sv","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/shouldChangePrintInfo(_:)":{"url":"/documentation/appkit/nsdocument/shouldchangeprintinfo(_:)","title":"shouldChangePrintInfo(_:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/shouldChangePrintInfo(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"shouldChangePrintInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSPrintInfo","preciseIdentifier":"c:objc(cs)NSPrintInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether the document allows changes to the default printing information."}],"kind":"symbol","navigatorTitle":[{"text":"shouldChangePrintInfo:","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV":{"type":"topic","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"Selector"}],"url":"/documentation/objectivec/selector","title":"Selector","abstract":[{"type":"text","text":""}],"identifier":"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey":{"navigatorTitle":[{"text":"AttributeKey","kind":"identifier"}],"title":"NSPrintInfo.AttributeKey","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AttributeKey","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/AttributeKey","abstract":[{"type":"text","text":"Constants that specify print job attributes."}],"role":"symbol","url":"/documentation/appkit/nsprintinfo/attributekey","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/preparePageLayout(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/preparePageLayout(_:)","type":"topic","url":"/documentation/appkit/nsdocument/preparepagelayout(_:)","navigatorTitle":[{"text":"preparePageLayout:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preparePageLayout"},{"text":"(","kind":"text"},{"text":"NSPageLayout","preciseIdentifier":"c:objc(cs)NSPageLayout","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"preparePageLayout(_:)","abstract":[{"type":"text","text":"Adds document-specific content to the Page Layout panel."}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.externally.resolved.symbol/c:@T@SEL":{"identifier":"doc://com.externally.resolved.symbol/c:@T@SEL","type":"topic","abstract":[{"type":"text","text":"Defines an opaque type that represents a method selector."}],"url":"/documentation/objectivec/sel","title":"SEL","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDocument":{"abstract":[{"text":"An abstract class that defines the interface for macOS documents.","type":"text"}],"type":"topic","title":"NSDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDocument","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument","role":"symbol","url":"/documentation/appkit/nsdocument","navigatorTitle":[{"text":"NSDocument","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"macOS","unavailable":false,"beta":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"op":"replace","path":"/metadata/title","value":"printDocumentWithSettings:showPrintPanel:delegate:didPrintSelector:contextInfo:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"printDocumentWithSettings:showPrintPanel:delegate:didPrintSelector:contextInfo:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDocument"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Printing-the-Document","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/printInfo","doc://com.apple.appkit/documentation/AppKit/NSDocument/preparePageLayout(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayout(with:delegate:didRun:contextInfo:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPrintOperation(_:delegate:didRun:contextInfo:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/shouldChangePrintInfo(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/printOperation(withSettings:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/pdfPrintOperation","doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToPDF(_:)"],"title":"Printing the Document","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"printDocumentWithSettings:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary<NSString *,id>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"printSettings"},{"kind":"text","text":" "},{"kind":"identifier","text":"showPrintPanel:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"showPrintPanel"},{"kind":"text","text":" "},{"text":"delegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didPrintSelector:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SEL","identifier":"doc://com.externally.resolved.symbol/c:@T@SEL","preciseIdentifier":"c:@T@SEL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"didPrintSelector","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"contextInfo:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"contextInfo"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"]}]}},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"printSettings","content":[{"type":"paragraph","inlineContent":[{"text":"The print settings dictionary to use.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A Boolean value indicating whether the print panel is shown."}]}],"name":"showPrintPanel"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate to which the selector message is sent."}]}],"name":"delegate"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The selector of the message sent to the delegate.","type":"text"}]}],"name":"didPrintSelector"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Object passed with the callback to provide any additional context information."}]}],"name":"contextInfo"}]}},{"value":"printOperationWithSettings:error:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1printOperation(withSettings:)/title","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1printOperation(withSettings:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"printOperationWithSettings:error:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/title","value":"NSPrintInfo"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/fragments","value":[{"text":"NSPrintInfo","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/navigatorTitle","value":[{"kind":"identifier","text":"NSPrintInfo"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1runModalPrintOperation(_:delegate:didRun:contextInfo:)/title","value":"runModalPrintOperation:delegate:didRunSelector:contextInfo:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1runModalPrintOperation(_:delegate:didRun:contextInfo:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"runModalPrintOperation:delegate:didRunSelector:contextInfo:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1print(withSettings:showPrintPanel:delegate:didPrint:contextInfo:)/title","value":"printDocumentWithSettings:showPrintPanel:delegate:didPrintSelector:contextInfo:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1print(withSettings:showPrintPanel:delegate:didPrint:contextInfo:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"printDocumentWithSettings:showPrintPanel:delegate:didPrintSelector:contextInfo:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1saveToPDF(_:)/title","value":"saveDocumentToPDF:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1saveToPDF(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"saveDocumentToPDF:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1pdfPrintOperation/title","value":"PDFPrintOperation"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1pdfPrintOperation/fragments","value":[{"kind":"identifier","text":"PDFPrintOperation"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1printInfo/title","value":"printInfo"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1printInfo/fragments","value":[{"kind":"identifier","text":"printInfo"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1runModalPageLayout(with:delegate:didRun:contextInfo:)/title","value":"runModalPageLayoutWithPrintInfo:delegate:didRunSelector:contextInfo:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1runModalPageLayout(with:delegate:didRun:contextInfo:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"runModalPageLayoutWithPrintInfo:delegate:didRunSelector:contextInfo:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1shouldChangePrintInfo(_:)/title","value":"shouldChangePrintInfo:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1shouldChangePrintInfo(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"shouldChangePrintInfo:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey/title","value":"NSPrintInfoAttributeKey"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey/fragments","value":[{"text":"NSPrintInfoAttributeKey","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1AttributeKey/navigatorTitle","value":[{"text":"NSPrintInfoAttributeKey","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1preparePageLayout(_:)/title","value":"preparePageLayout:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1preparePageLayout(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"preparePageLayout:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/title","value":"NSDocument"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/fragments","value":[{"text":"NSDocument","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/navigatorTitle","value":[{"text":"NSDocument","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}