{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSDocument/printDocument(_:)"},"kind":"symbol","seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/printInfo","doc://com.apple.appkit/documentation/AppKit/NSDocument/shouldChangePrintInfo(_:)"],"anchor":"Related-Documentation"},{"title":"Handling User Actions","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/runPageLayout(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSaved(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/save(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/saveAs(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/saveTo(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/save(withDelegate:didSave:contextInfo:)"],"anchor":"Handling-User-Actions","generated":true}],"abstract":[{"text":"Prints the receiver in response to the user choosing the Print menu command.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/appkit/nsdocument/printdocument(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsdocument/printdocument(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDocument"]]},"metadata":{"externalID":"c:objc(cs)NSDocument(im)printDocument:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"printDocument"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"title":"printDocument(_:)","modules":[{"name":"AppKit"}],"role":"symbol","roleHeading":"Instance Method","platforms":[{"deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"navigatorTitle":[{"kind":"identifier","text":"printDocument:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@IBAction"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"printDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The control sending the message."}]}],"name":"sender"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"An ","type":"text"},{"code":"NSDocument","type":"codeVoice"},{"text":" object receives this action message as it travels up the responder chain. The default implementation invokes ","type":"text"},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/print(withSettings:showPrintPanel:delegate:didPrint:contextInfo:)","isActive":true},{"text":".","type":"text"}]}]}],"sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit/NSDocument/print(withSettings:showPrintPanel:delegate:didPrint:contextInfo:)":{"url":"/documentation/appkit/nsdocument/print(withsettings:showprintpanel:delegate:didprint:contextinfo:)","title":"print(withSettings:showPrintPanel:delegate:didPrint:contextInfo:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/print(withSettings:showPrintPanel:delegate:didPrint:contextInfo:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"print","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withSettings","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"NSPrintInfo","preciseIdentifier":"c:objc(cs)NSPrintInfo","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"AttributeKey","preciseIdentifier":"c:@T@NSPrintInfoAttributeKey","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"showPrintPanel","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"didPrint","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"contextInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Prints the document’s contents, optionally displaying a print panel to the user."}],"kind":"symbol","navigatorTitle":[{"text":"printDocumentWithSettings:showPrintPanel:delegate:didPrintSelector:contextInfo:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/shouldChangePrintInfo(_:)":{"url":"/documentation/appkit/nsdocument/shouldchangeprintinfo(_:)","title":"shouldChangePrintInfo(_:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/shouldChangePrintInfo(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"shouldChangePrintInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSPrintInfo","preciseIdentifier":"c:objc(cs)NSPrintInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether the document allows changes to the default printing information."}],"kind":"symbol","navigatorTitle":[{"text":"shouldChangePrintInfo:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/save(withDelegate:didSave:contextInfo:)":{"url":"/documentation/appkit/nsdocument/save(withdelegate:didsave:contextinfo:)","title":"save(withDelegate:didSave:contextInfo:)","role":"symbol","abstract":[{"type":"text","text":"Saves the document and delivers the results to the provided delegate object."}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/save(withDelegate:didSave:contextInfo:)","navigatorTitle":[{"text":"saveDocumentWithDelegate:didSaveSelector:contextInfo:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"save","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withDelegate"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"didSave"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contextInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/saveAs(_:)":{"kind":"symbol","title":"saveAs(_:)","navigatorTitle":[{"text":"saveDocumentAs:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The action method invoked in the receiver as first responder when the user chooses the Save As menu command."}],"url":"/documentation/appkit/nsdocument/saveas(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/saveAs(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"saveAs","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/runPageLayout(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/runPageLayout(_:)","kind":"symbol","navigatorTitle":[{"text":"runPageLayout:","kind":"identifier"}],"title":"runPageLayout(_:)","abstract":[{"type":"text","text":"The action method invoked in the receiver as first responder when the user chooses the Page Setup menu command."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"runPageLayout","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nsdocument/runpagelayout(_:)"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/printDocument(_:)":{"title":"printDocument(_:)","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/printDocument(_:)","navigatorTitle":[{"kind":"identifier","text":"printDocument:"}],"abstract":[{"text":"Prints the receiver in response to the user choosing the Print menu command.","type":"text"}],"type":"topic","kind":"symbol","url":"/documentation/appkit/nsdocument/printdocument(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"printDocument"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/saveTo(_:)":{"kind":"symbol","title":"saveTo(_:)","navigatorTitle":[{"text":"saveDocumentTo:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The action method invoked in the receiver as first responder when the user chooses the Save To menu command.","type":"text"}],"url":"/documentation/appkit/nsdocument/saveto(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/saveTo(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"saveTo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSDocument":{"abstract":[{"text":"An abstract class that defines the interface for macOS documents.","type":"text"}],"type":"topic","title":"NSDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDocument","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument","role":"symbol","url":"/documentation/appkit/nsdocument","navigatorTitle":[{"text":"NSDocument","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/save(_:)":{"kind":"symbol","title":"save(_:)","navigatorTitle":[{"kind":"identifier","text":"saveDocument:"}],"role":"symbol","abstract":[{"type":"text","text":"The action method invoked in the receiver as first responder when the user chooses the Save menu command."}],"url":"/documentation/appkit/nsdocument/save(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/save(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"save","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSaved(_:)":{"role":"symbol","url":"/documentation/appkit/nsdocument/reverttosaved(_:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSaved(_:)","title":"revertToSaved(_:)","abstract":[{"type":"text","text":"The action of the File menu item Revert in a document-based app."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"revertDocumentToSaved:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"revertToSaved"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/printInfo":{"type":"topic","navigatorTitle":[{"text":"printInfo","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/printInfo","kind":"symbol","url":"/documentation/appkit/nsdocument/printinfo","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"printInfo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSPrintInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPrintInfo"}],"abstract":[{"type":"text","text":"The printing information associated with the document."}],"role":"symbol","title":"printInfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"name":"macOS","beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"printDocument:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"printDocument:"}]},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDocument"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/printInfo","doc://com.apple.appkit/documentation/AppKit/NSDocument/shouldChangePrintInfo(_:)"],"anchor":"Related-Documentation"},{"generated":true,"title":"Handling User Actions","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/runPageLayout(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSaved(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/save(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/saveAs(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/saveTo(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/save(withDelegate:didSave:contextInfo:)"],"anchor":"Handling-User-Actions"}],"op":"replace","path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"printDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The control sending the message."}]}],"name":"sender"}],"kind":"parameters"},"op":"replace","path":"/primaryContentSections/1"},{"op":"replace","value":"printDocumentWithSettings:showPrintPanel:delegate:didPrintSelector:contextInfo:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1print(withSettings:showPrintPanel:delegate:didPrint:contextInfo:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"printDocumentWithSettings:showPrintPanel:delegate:didPrintSelector:contextInfo:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1print(withSettings:showPrintPanel:delegate:didPrint:contextInfo:)/fragments"},{"op":"replace","value":"shouldChangePrintInfo:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1shouldChangePrintInfo(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"shouldChangePrintInfo:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1shouldChangePrintInfo(_:)/fragments"},{"op":"replace","value":"saveDocumentWithDelegate:didSaveSelector:contextInfo:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1save(withDelegate:didSave:contextInfo:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"saveDocumentWithDelegate:didSaveSelector:contextInfo:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1save(withDelegate:didSave:contextInfo:)/fragments"},{"op":"replace","value":"saveDocumentAs:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1saveAs(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"saveDocumentAs:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1saveAs(_:)/fragments"},{"op":"replace","value":"runPageLayout:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1runPageLayout(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"runPageLayout:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1runPageLayout(_:)/fragments"},{"op":"replace","value":"printDocument:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1printDocument(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"printDocument:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1printDocument(_:)/fragments"},{"op":"replace","value":"saveDocumentTo:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1saveTo(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"saveDocumentTo:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1saveTo(_:)/fragments"},{"op":"replace","value":"NSDocument","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSDocument"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/fragments"},{"op":"replace","value":[{"text":"NSDocument","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/navigatorTitle"},{"op":"replace","value":"saveDocument:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1save(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"saveDocument:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1save(_:)/fragments"},{"op":"replace","value":"revertDocumentToSaved:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1revertToSaved(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"revertDocumentToSaved:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1revertToSaved(_:)/fragments"},{"op":"replace","value":"printInfo","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1printInfo/title"},{"op":"replace","value":[{"text":"printInfo","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1printInfo/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}