{
  "abstract": [
    {
      "text": "Reads and loads document data.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/read(from:ofType:)-1vttv",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromURL:ofType:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSDocument(im)readFromURL:ofType:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "readFromURL:ofType:"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "readFromURL:ofType:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.4",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "readFromURL:ofType:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "readFromURL:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSURL",
              "text": "NSURL"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "url"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ofType:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "type"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Reads and loads document data of type ",
              "type": "text"
            },
            {
              "code": "docType",
              "type": "codeVoice"
            },
            {
              "text": " from the URL ",
              "type": "text"
            },
            {
              "code": "aURL",
              "type": "codeVoice"
            },
            {
              "text": ", returning whether the operation was successful. This method only supports URLs of the ",
              "type": "text"
            },
            {
              "code": "file:",
              "type": "codeVoice"
            },
            {
              "text": " scheme and calls ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromFile:ofType:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument": {
      "abstract": [
        {
          "text": "An abstract class that defines the interface for macOS documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDocument"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDocument"
        }
      ],
      "role": "symbol",
      "title": "NSDocument",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/dataRepresentationOfType:": {
      "abstract": [
        {
          "text": "A primitive method to return a data object that represents the data of the receiver in a given type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "dataRepresentationOfType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/dataRepresentationOfType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataRepresentationOfType:"
        }
      ],
      "role": "symbol",
      "title": "dataRepresentationOfType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/datarepresentationoftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileAttributesToWriteToFile:ofType:saveOperation:": {
      "abstract": [
        {
          "text": "Returns the file attributes that should be written to the named document file of the specified type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "fileAttributesToWriteToFile:ofType:saveOperation:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileAttributesToWriteToFile:ofType:saveOperation:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileAttributesToWriteToFile:ofType:saveOperation:"
        }
      ],
      "role": "symbol",
      "title": "fileAttributesToWriteToFile:ofType:saveOperation:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/fileattributestowritetofile:oftype:saveoperation:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileName": {
      "abstract": [
        {
          "text": "Returns the fully qualified pathname under which the receiver has been saved.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "fileName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileName"
        }
      ],
      "role": "symbol",
      "title": "fileName",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/filename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileWrapperRepresentationOfType:": {
      "abstract": [
        {
          "text": "Returns a file wrapper object that represents the data of the receiver in a given type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "fileWrapperRepresentationOfType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileWrapperRepresentationOfType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileWrapperRepresentationOfType:"
        }
      ],
      "role": "symbol",
      "title": "fileWrapperRepresentationOfType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/filewrapperrepresentationoftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfFile:ofType:": {
      "abstract": [
        {
          "text": "Initializes and returns a document object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithContentsOfFile:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfFile:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithContentsOfFile:ofType:"
        }
      ],
      "role": "symbol",
      "title": "initWithContentsOfFile:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/initwithcontentsoffile:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfURL:ofType:": {
      "abstract": [
        {
          "text": "Initializes and returns a document object of a given type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithContentsOfURL:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfURL:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithContentsOfURL:ofType:"
        }
      ],
      "role": "symbol",
      "title": "initWithContentsOfURL:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/initwithcontentsofurl:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/loadDataRepresentation:ofType:": {
      "abstract": [
        {
          "text": "Loads the document data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "loadDataRepresentation:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/loadDataRepresentation:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadDataRepresentation:ofType:"
        }
      ],
      "role": "symbol",
      "title": "loadDataRepresentation:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/loaddatarepresentation:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/loadFileWrapperRepresentation:ofType:": {
      "abstract": [
        {
          "text": "Loads document data from a given file wrapper.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "loadFileWrapperRepresentation:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/loadFileWrapperRepresentation:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadFileWrapperRepresentation:ofType:"
        }
      ],
      "role": "symbol",
      "title": "loadFileWrapperRepresentation:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/loadfilewrapperrepresentation:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/printShowingPrintPanel:": {
      "abstract": [
        {
          "text": "Prints the current document’s data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "printShowingPrintPanel:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/printShowingPrintPanel:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printShowingPrintPanel:"
        }
      ],
      "role": "symbol",
      "title": "printShowingPrintPanel:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/printshowingprintpanel:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/read(from:ofType:)-1vttv": {
      "abstract": [
        {
          "text": "Sets the contents of this document by reading from a file or file package, of a specified type, located by a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "read"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/read(from:ofType:)-1vttv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readFromURL:ofType:error:"
        }
      ],
      "role": "symbol",
      "title": "read(from:ofType:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/read(from:oftype:)-1vttv"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromFile:ofType:": {
      "abstract": [
        {
          "text": "Reads and loads document data of the given type from the given file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "readFromFile:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromFile:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readFromFile:ofType:"
        }
      ],
      "role": "symbol",
      "title": "readFromFile:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/readfromfile:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromURL:ofType:": {
      "abstract": [
        {
          "text": "Reads and loads document data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "readFromURL:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromURL:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readFromURL:ofType:"
        }
      ],
      "role": "symbol",
      "title": "readFromURL:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/readfromurl:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromFile:ofType:": {
      "abstract": [
        {
          "text": "Reverts the receiver to the data stored in the file system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "revertToSavedFromFile:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromFile:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "revertToSavedFromFile:ofType:"
        }
      ],
      "role": "symbol",
      "title": "revertToSavedFromFile:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/reverttosavedfromfile:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromURL:ofType:": {
      "abstract": [
        {
          "text": "Reverts the receiver.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "revertToSavedFromURL:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromURL:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "revertToSavedFromURL:ofType:"
        }
      ],
      "role": "symbol",
      "title": "revertToSavedFromURL:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/reverttosavedfromurl:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayoutWithPrintInfo:": {
      "abstract": [
        {
          "text": "Runs the page layout modal panel with the receiver’s printing information object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "runModalPageLayoutWithPrintInfo:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayoutWithPrintInfo:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModalPageLayoutWithPrintInfo:"
        }
      ],
      "role": "symbol",
      "title": "runModalPageLayoutWithPrintInfo:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/runmodalpagelayoutwithprintinfo:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:": {
      "abstract": [
        {
          "text": "Called after the user has been given the opportunity to select a destination through the modal Save panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:"
        }
      ],
      "role": "symbol",
      "title": "saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/savetofile:saveoperation:delegate:didsaveselector:contextinfo:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToURL:ofType:forSaveOperation:error:": {
      "abstract": [
        {
          "text": "Saves the contents of the document to a file or file package located by a URL, formatted to a specified type, for a particular kind of save operation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "saveToURL:ofType:forSaveOperation:error:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToURL:ofType:forSaveOperation:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveToURL:ofType:forSaveOperation:error:"
        }
      ],
      "role": "symbol",
      "title": "saveToURL:ofType:forSaveOperation:error:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/savetourl:oftype:forsaveoperation:error:"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSURL": {
      "abstract": [
        {
          "text": "An object representing the location of a resource that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSURL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSURL",
      "type": "topic",
      "url": "/documentation/foundation/nsurl"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/dataRepresentationOfType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileAttributesToWriteToFile:ofType:saveOperation:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileName",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileWrapperRepresentationOfType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfFile:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfURL:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/loadDataRepresentation:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/loadFileWrapperRepresentation:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/printShowingPrintPanel:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromFile:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromFile:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromURL:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayoutWithPrintInfo:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToURL:ofType:forSaveOperation:error:"
      ],
      "title": "Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/title",
          "value": "NSDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSURL/abstract",
          "value": [
            {
              "text": "An object that represents the location of a resource, such as an item on a remote server or the path to a local file. ",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1read(from:ofType:)-1vttv/title",
          "value": "readFromURL:ofType:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1read(from:ofType:)-1vttv/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readFromURL:ofType:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdocument/readfromurl:oftype:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
