{"metadata":{"extendedModule":"AppKit","role":"symbol","modules":[{"name":"AppKit"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)NSDocument(im)restoreStateWithCoder:","navigatorTitle":[{"kind":"identifier","text":"restoreStateWithCoder:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"restoreState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"kind":"text","text":")"}],"platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"10.7","name":"macOS","beta":false}],"symbolKind":"method","title":"restoreState(with:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Handling Window Restoration","anchor":"Handling-Window-Restoration","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/allowedClasses(forRestorableStateKeyPath:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/encodeRestorableState(with:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/restorableStateKeyPaths","doc://com.apple.appkit/documentation/AppKit/NSDocument/invalidateRestorableState()","doc://com.apple.appkit/documentation/AppKit/NSDocument/restoreWindow(withIdentifier:state:completionHandler:)"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"restoreState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"coder"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSCoder","text":"NSCoder"},{"kind":"text","text":")"}]}]},{"parameters":[{"name":"coder","content":[{"type":"paragraph","inlineContent":[{"text":"The coder object to use to restore the document’s interface-related state.","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method is part of the window restoration system and is called at launch time to restore the window-related state of your document object. The default implementation restores some basic information about the document. If you override this method, you must call "},{"type":"codeVoice","code":"super"},{"type":"text","text":" at some point in your implementation."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Subclasses can override this method and use it to restore the document-related information that was saved in the "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/encodeRestorableState(with:)"},{"type":"text","text":" method. You can also use this method to reconfigure the document (or its associated window controller and window) to their previous appearance."}]},{"name":"Note","type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"If the user’s computer is configured to close all windows when an app quits, the system automatically removes any preserved state as part of that process. As a result, the system doesn’t call "},{"type":"codeVoice","code":"restoreState(with:)"},{"type":"text","text":" the next time your app launches."}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For information about using a coder object to read data from an archive, see "},{"identifier":"doc://com.apple.documentation/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types","type":"reference","isActive":true},{"type":"text","text":"."}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSDocument/restoreState(with:)"},"abstract":[{"type":"text","text":"Restores the interface-related state of the document."}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsdocument/restorestate(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsdocument/restorestate(with:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDocument"]]},"references":{"doc://com.apple.appkit/documentation/AppKit/NSDocument":{"abstract":[{"text":"An abstract class that defines the interface for macOS documents.","type":"text"}],"type":"topic","title":"NSDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDocument","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument","role":"symbol","url":"/documentation/appkit/nsdocument","navigatorTitle":[{"text":"NSDocument","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/restoreState(with:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/restoreState(with:)","abstract":[{"text":"Restores the interface-related state of the document.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"restoreState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"title":"restoreState(with:)","url":"/documentation/appkit/nsdocument/restorestate(with:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"restoreStateWithCoder:"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/encodeRestorableState(with:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/encodeRestorableState(with:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"encodeRestorableStateWithCoder:"}],"role":"symbol","type":"topic","title":"encodeRestorableState(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeRestorableState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Saves the interface-related state of the document."}],"url":"/documentation/appkit/nsdocument/encoderestorablestate(with:)"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/allowedClasses(forRestorableStateKeyPath:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowedClasses","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forRestorableStateKeyPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> [","kind":"text"},{"text":"AnyClass","kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa"},{"text":"]","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/allowedClasses(forRestorableStateKeyPath:)","navigatorTitle":[{"text":"allowedClassesForRestorableStateKeyPath:","kind":"identifier"}],"abstract":[{"text":"Returns the classes that support secure coding.","type":"text"}],"type":"topic","title":"allowedClasses(forRestorableStateKeyPath:)","url":"/documentation/appkit/nsdocument/allowedclasses(forrestorablestatekeypath:)"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types":{"abstract":[{"type":"text","text":"Make your data types encodable and decodable for compatibility with external representations such as JSON."}],"type":"topic","title":"Encoding and Decoding Custom Types","kind":"article","identifier":"doc://com.apple.documentation/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types","role":"article","url":"/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/restorableStateKeyPaths":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/restorableStateKeyPaths","url":"/documentation/appkit/nsdocument/restorablestatekeypaths","navigatorTitle":[{"text":"restorableStateKeyPaths","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restorableStateKeyPaths","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"kind":"symbol","type":"topic","title":"restorableStateKeyPaths","role":"symbol","abstract":[{"text":"Returns an array of key paths that represent the restorable attributes of the document.","type":"text"}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSCoder":{"type":"topic","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSCoder"}],"url":"/documentation/foundation/nscoder","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSCoder","role":"symbol","title":"NSCoder","kind":"symbol","abstract":[{"type":"text","text":"An abstract class that serves as the basis for objects that enable archiving and distribution of other objects."}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/invalidateRestorableState()":{"navigatorTitle":[{"text":"invalidateRestorableState","kind":"identifier"}],"title":"invalidateRestorableState()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidateRestorableState","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/invalidateRestorableState()","abstract":[{"text":"Marks the document’s interface-related state as dirty.","type":"text"}],"role":"symbol","url":"/documentation/appkit/nsdocument/invalidaterestorablestate()","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/restoreWindow(withIdentifier:state:completionHandler:)":{"abstract":[{"text":"Restores a window that was associated with a document, after that document is reopened.","type":"text"}],"type":"topic","title":"restoreWindow(withIdentifier:state:completionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restoreWindow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSUserInterfaceItemIdentifier","preciseIdentifier":"c:@T@NSUserInterfaceItemIdentifier","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"state","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"NSWindow","preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier"},{"text":"?, (any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/restoreWindow(withIdentifier:state:completionHandler:)","role":"symbol","url":"/documentation/appkit/nsdocument/restorewindow(withidentifier:state:completionhandler:)","navigatorTitle":[{"text":"restoreDocumentWindowWithIdentifier:state:completionHandler:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"10.7","name":"macOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"restoreStateWithCoder:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"restoreStateWithCoder:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDocument"]]},"path":"/hierarchy"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Handling Window Restoration","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/allowedClasses(forRestorableStateKeyPath:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/encodeRestorableState(with:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/restorableStateKeyPaths","doc://com.apple.appkit/documentation/AppKit/NSDocument/invalidateRestorableState()","doc://com.apple.appkit/documentation/AppKit/NSDocument/restoreWindow(withIdentifier:state:completionHandler:)"],"generated":true,"anchor":"Handling-Window-Restoration"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"restoreStateWithCoder:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSCoder","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"coder"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"coder","content":[{"inlineContent":[{"text":"The coder object to use to restore the document’s interface-related state.","type":"text"}],"type":"paragraph"}]}]},"op":"replace","path":"/primaryContentSections/1"},{"value":"NSDocument","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/title","op":"replace"},{"value":[{"text":"NSDocument","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSDocument"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/navigatorTitle","op":"replace"},{"value":"restoreStateWithCoder:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1restoreState(with:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"restoreStateWithCoder:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1restoreState(with:)/fragments","op":"replace"},{"value":"encodeRestorableStateWithCoder:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1encodeRestorableState(with:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"encodeRestorableStateWithCoder:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1encodeRestorableState(with:)/fragments","op":"replace"},{"value":"allowedClassesForRestorableStateKeyPath:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1allowedClasses(forRestorableStateKeyPath:)/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"allowedClassesForRestorableStateKeyPath:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1allowedClasses(forRestorableStateKeyPath:)/fragments","op":"replace"},{"value":"restorableStateKeyPaths","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1restorableStateKeyPaths/title","op":"replace"},{"value":[{"text":"restorableStateKeyPaths","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1restorableStateKeyPaths/fragments","op":"replace"},{"value":"invalidateRestorableState","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1invalidateRestorableState()/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"invalidateRestorableState"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1invalidateRestorableState()/fragments","op":"replace"},{"value":"restoreDocumentWindowWithIdentifier:state:completionHandler:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1restoreWindow(withIdentifier:state:completionHandler:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"restoreDocumentWindowWithIdentifier:state:completionHandler:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1restoreWindow(withIdentifier:state:completionHandler:)/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}