{
  "abstract": [
    {
      "text": "Runs the page layout modal panel with the receiver’s printing information object.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayout(with:delegate:didRun:contextInfo:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayoutWithPrintInfo:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSDocument(im)runModalPageLayoutWithPrintInfo:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "runModalPageLayoutWithPrintInfo:"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "runModalPageLayoutWithPrintInfo:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.4",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "runModalPageLayoutWithPrintInfo:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "runModalPageLayoutWithPrintInfo:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSPrintInfo",
              "text": "NSPrintInfo"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "printInfo"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Runs the page layout modal panel with the receiver’s printing information object (",
              "type": "text"
            },
            {
              "code": "printInfo",
              "type": "codeVoice"
            },
            {
              "text": ") as argument and returns the result constant (indicating the button pressed by the user). To run as sheet on the receiver’s document window, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayout(with:delegate:didRun:contextInfo:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument": {
      "abstract": [
        {
          "text": "An abstract class that defines the interface for macOS documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDocument"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDocument"
        }
      ],
      "role": "symbol",
      "title": "NSDocument",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/dataRepresentationOfType:": {
      "abstract": [
        {
          "text": "A primitive method to return a data object that represents the data of the receiver in a given type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "dataRepresentationOfType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/dataRepresentationOfType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataRepresentationOfType:"
        }
      ],
      "role": "symbol",
      "title": "dataRepresentationOfType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/datarepresentationoftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileAttributesToWriteToFile:ofType:saveOperation:": {
      "abstract": [
        {
          "text": "Returns the file attributes that should be written to the named document file of the specified type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "fileAttributesToWriteToFile:ofType:saveOperation:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileAttributesToWriteToFile:ofType:saveOperation:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileAttributesToWriteToFile:ofType:saveOperation:"
        }
      ],
      "role": "symbol",
      "title": "fileAttributesToWriteToFile:ofType:saveOperation:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/fileattributestowritetofile:oftype:saveoperation:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileName": {
      "abstract": [
        {
          "text": "Returns the fully qualified pathname under which the receiver has been saved.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "fileName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileName"
        }
      ],
      "role": "symbol",
      "title": "fileName",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/filename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileWrapperRepresentationOfType:": {
      "abstract": [
        {
          "text": "Returns a file wrapper object that represents the data of the receiver in a given type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "fileWrapperRepresentationOfType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileWrapperRepresentationOfType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileWrapperRepresentationOfType:"
        }
      ],
      "role": "symbol",
      "title": "fileWrapperRepresentationOfType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/filewrapperrepresentationoftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfFile:ofType:": {
      "abstract": [
        {
          "text": "Initializes and returns a document object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithContentsOfFile:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfFile:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithContentsOfFile:ofType:"
        }
      ],
      "role": "symbol",
      "title": "initWithContentsOfFile:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/initwithcontentsoffile:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfURL:ofType:": {
      "abstract": [
        {
          "text": "Initializes and returns a document object of a given type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithContentsOfURL:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfURL:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithContentsOfURL:ofType:"
        }
      ],
      "role": "symbol",
      "title": "initWithContentsOfURL:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/initwithcontentsofurl:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/loadDataRepresentation:ofType:": {
      "abstract": [
        {
          "text": "Loads the document data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "loadDataRepresentation:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/loadDataRepresentation:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadDataRepresentation:ofType:"
        }
      ],
      "role": "symbol",
      "title": "loadDataRepresentation:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/loaddatarepresentation:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/loadFileWrapperRepresentation:ofType:": {
      "abstract": [
        {
          "text": "Loads document data from a given file wrapper.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "loadFileWrapperRepresentation:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/loadFileWrapperRepresentation:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadFileWrapperRepresentation:ofType:"
        }
      ],
      "role": "symbol",
      "title": "loadFileWrapperRepresentation:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/loadfilewrapperrepresentation:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/printShowingPrintPanel:": {
      "abstract": [
        {
          "text": "Prints the current document’s data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "printShowingPrintPanel:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/printShowingPrintPanel:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printShowingPrintPanel:"
        }
      ],
      "role": "symbol",
      "title": "printShowingPrintPanel:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/printshowingprintpanel:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromFile:ofType:": {
      "abstract": [
        {
          "text": "Reads and loads document data of the given type from the given file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "readFromFile:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromFile:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readFromFile:ofType:"
        }
      ],
      "role": "symbol",
      "title": "readFromFile:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/readfromfile:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromURL:ofType:": {
      "abstract": [
        {
          "text": "Reads and loads document data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "readFromURL:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromURL:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readFromURL:ofType:"
        }
      ],
      "role": "symbol",
      "title": "readFromURL:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/readfromurl:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromFile:ofType:": {
      "abstract": [
        {
          "text": "Reverts the receiver to the data stored in the file system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "revertToSavedFromFile:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromFile:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "revertToSavedFromFile:ofType:"
        }
      ],
      "role": "symbol",
      "title": "revertToSavedFromFile:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/reverttosavedfromfile:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromURL:ofType:": {
      "abstract": [
        {
          "text": "Reverts the receiver.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "revertToSavedFromURL:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromURL:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "revertToSavedFromURL:ofType:"
        }
      ],
      "role": "symbol",
      "title": "revertToSavedFromURL:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/reverttosavedfromurl:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayout(with:delegate:didRun:contextInfo:)": {
      "abstract": [
        {
          "text": "Runs the modal page layout panel with the receiver’s printing information object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModalPageLayout"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "didRun"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "contextInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayout(with:delegate:didRun:contextInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModalPageLayoutWithPrintInfo:delegate:didRunSelector:contextInfo:"
        }
      ],
      "role": "symbol",
      "title": "runModalPageLayout(with:delegate:didRun:contextInfo:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/runmodalpagelayout(with:delegate:didrun:contextinfo:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayoutWithPrintInfo:": {
      "abstract": [
        {
          "text": "Runs the page layout modal panel with the receiver’s printing information object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "runModalPageLayoutWithPrintInfo:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayoutWithPrintInfo:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModalPageLayoutWithPrintInfo:"
        }
      ],
      "role": "symbol",
      "title": "runModalPageLayoutWithPrintInfo:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/runmodalpagelayoutwithprintinfo:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:": {
      "abstract": [
        {
          "text": "Called after the user has been given the opportunity to select a destination through the modal Save panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:"
        }
      ],
      "role": "symbol",
      "title": "saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/savetofile:saveoperation:delegate:didsaveselector:contextinfo:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToURL:ofType:forSaveOperation:error:": {
      "abstract": [
        {
          "text": "Saves the contents of the document to a file or file package located by a URL, formatted to a specified type, for a particular kind of save operation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "saveToURL:ofType:forSaveOperation:error:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToURL:ofType:forSaveOperation:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveToURL:ofType:forSaveOperation:error:"
        }
      ],
      "role": "symbol",
      "title": "saveToURL:ofType:forSaveOperation:error:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/savetourl:oftype:forsaveoperation:error:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo": {
      "abstract": [
        {
          "text": "An object that stores information that’s used to generate printed output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintInfo"
        }
      ],
      "role": "symbol",
      "title": "NSPrintInfo",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/dataRepresentationOfType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileAttributesToWriteToFile:ofType:saveOperation:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileName",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileWrapperRepresentationOfType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfFile:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfURL:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/loadDataRepresentation:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/loadFileWrapperRepresentation:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/printShowingPrintPanel:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromFile:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromURL:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromFile:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromURL:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToURL:ofType:forSaveOperation:error:"
      ],
      "title": "Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/title",
          "value": "NSPrintInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/title",
          "value": "NSDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1runModalPageLayout(with:delegate:didRun:contextInfo:)/title",
          "value": "runModalPageLayoutWithPrintInfo:delegate:didRunSelector:contextInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1runModalPageLayout(with:delegate:didRun:contextInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModalPageLayoutWithPrintInfo:delegate:didRunSelector:contextInfo:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdocument/runmodalpagelayoutwithprintinfo:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
