{
  "abstract": [
    {
      "text": "The action method invoked in the receiver as first responder when the user chooses the Page Setup menu command.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDocument/runPageLayout(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSDocument(im)runPageLayout:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "runPageLayout"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "runPageLayout:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "runPageLayout(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@IBAction"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "runPageLayout"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "sender"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The control sending the message.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sender"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default implementation invokes ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayout(with:delegate:didRun:contextInfo:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with the document’s current NSPrintInfo object as argument; if the user clicks the OK button and the document authorizes changes to its printing information (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/shouldChangePrintInfo(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "), the method sets the document’s new ",
              "type": "text"
            },
            {
              "code": "NSPrintInfo",
              "type": "codeVoice"
            },
            {
              "text": " object and increments the document’s change count.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument": {
      "abstract": [
        {
          "text": "An abstract class that defines the interface for macOS documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDocument"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDocument"
        }
      ],
      "role": "symbol",
      "title": "NSDocument",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/printDocument(_:)": {
      "abstract": [
        {
          "text": "Prints the receiver in response to the user choosing the Print menu command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printDocument"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/printDocument(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printDocument:"
        }
      ],
      "role": "symbol",
      "title": "printDocument(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/printdocument(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/printInfo": {
      "abstract": [
        {
          "text": "The printing information associated with the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/printInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printInfo"
        }
      ],
      "role": "symbol",
      "title": "printInfo",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/printinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSaved(_:)": {
      "abstract": [
        {
          "text": "The action of the File menu item Revert in a document-based app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "revertToSaved"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSaved(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "revertDocumentToSaved:"
        }
      ],
      "role": "symbol",
      "title": "revertToSaved(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/reverttosaved(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayout(with:delegate:didRun:contextInfo:)": {
      "abstract": [
        {
          "text": "Runs the modal page layout panel with the receiver’s printing information object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModalPageLayout"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "didRun"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "contextInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayout(with:delegate:didRun:contextInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModalPageLayoutWithPrintInfo:delegate:didRunSelector:contextInfo:"
        }
      ],
      "role": "symbol",
      "title": "runModalPageLayout(with:delegate:didRun:contextInfo:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/runmodalpagelayout(with:delegate:didrun:contextinfo:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/runPageLayout(_:)": {
      "abstract": [
        {
          "text": "The action method invoked in the receiver as first responder when the user chooses the Page Setup menu command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runPageLayout"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/runPageLayout(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runPageLayout:"
        }
      ],
      "role": "symbol",
      "title": "runPageLayout(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/runpagelayout(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/save(_:)": {
      "abstract": [
        {
          "text": "The action method invoked in the receiver as first responder when the user chooses the Save menu command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "save"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/save(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveDocument:"
        }
      ],
      "role": "symbol",
      "title": "save(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/save(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/save(withDelegate:didSave:contextInfo:)": {
      "abstract": [
        {
          "text": "Saves the document and delivers the results to the provided delegate object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "save"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withDelegate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "didSave"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "contextInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/save(withDelegate:didSave:contextInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveDocumentWithDelegate:didSaveSelector:contextInfo:"
        }
      ],
      "role": "symbol",
      "title": "save(withDelegate:didSave:contextInfo:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/save(withdelegate:didsave:contextinfo:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveAs(_:)": {
      "abstract": [
        {
          "text": "The action method invoked in the receiver as first responder when the user chooses the Save As menu command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saveAs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveAs(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveDocumentAs:"
        }
      ],
      "role": "symbol",
      "title": "saveAs(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/saveas(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveTo(_:)": {
      "abstract": [
        {
          "text": "The action method invoked in the receiver as first responder when the user chooses the Save To menu command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saveTo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveTo(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveDocumentTo:"
        }
      ],
      "role": "symbol",
      "title": "saveTo(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/saveto(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/shouldChangePrintInfo(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the document allows changes to the default printing information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldChangePrintInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/shouldChangePrintInfo(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldChangePrintInfo:"
        }
      ],
      "role": "symbol",
      "title": "shouldChangePrintInfo(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/shouldchangeprintinfo(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/updateChangeCount(_:)": {
      "abstract": [
        {
          "text": "Updates the receiver’s change count according to the given change type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateChangeCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDocument",
          "text": "NSDocument"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDocumentChangeType",
          "text": "ChangeType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/updateChangeCount(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateChangeCount:"
        }
      ],
      "role": "symbol",
      "title": "updateChangeCount(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/updatechangecount(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/updateChangeCount(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/printInfo"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Handling-User-Actions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/printDocument(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSaved(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/save(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveAs(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveTo(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/save(withDelegate:didSave:contextInfo:)"
      ],
      "title": "Handling User Actions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "runPageLayout:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runPageLayout:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/updateChangeCount(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/printInfo"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Handling-User-Actions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/printDocument(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSaved(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/save(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveAs(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveTo(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/save(withDelegate:didSave:contextInfo:)"
              ],
              "title": "Handling User Actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "runPageLayout:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "sender"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The control sending the message.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "sender"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1saveTo(_:)/title",
          "value": "saveDocumentTo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1saveTo(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveDocumentTo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1revertToSaved(_:)/title",
          "value": "revertDocumentToSaved:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1revertToSaved(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "revertDocumentToSaved:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1updateChangeCount(_:)/title",
          "value": "updateChangeCount:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1updateChangeCount(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateChangeCount:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1printDocument(_:)/title",
          "value": "printDocument:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1printDocument(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printDocument:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1runModalPageLayout(with:delegate:didRun:contextInfo:)/title",
          "value": "runModalPageLayoutWithPrintInfo:delegate:didRunSelector:contextInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1runModalPageLayout(with:delegate:didRun:contextInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModalPageLayoutWithPrintInfo:delegate:didRunSelector:contextInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/title",
          "value": "NSDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1saveAs(_:)/title",
          "value": "saveDocumentAs:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1saveAs(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveDocumentAs:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1runPageLayout(_:)/title",
          "value": "runPageLayout:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1runPageLayout(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runPageLayout:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1save(withDelegate:didSave:contextInfo:)/title",
          "value": "saveDocumentWithDelegate:didSaveSelector:contextInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1save(withDelegate:didSave:contextInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveDocumentWithDelegate:didSaveSelector:contextInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1save(_:)/title",
          "value": "saveDocument:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1save(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveDocument:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1shouldChangePrintInfo(_:)/title",
          "value": "shouldChangePrintInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1shouldChangePrintInfo(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "shouldChangePrintInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1printInfo/title",
          "value": "printInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1printInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "printInfo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdocument/runpagelayout(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsdocument/runpagelayout(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
