{"sections":[],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToURL:ofType:forSaveOperation:error:","interfaceLanguage":"occ"},"seeAlsoSections":[{"generated":true,"title":"Methods","anchor":"Methods","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/dataRepresentationOfType:","doc://com.apple.appkit/documentation/AppKit/NSDocument/fileAttributesToWriteToFile:ofType:saveOperation:","doc://com.apple.appkit/documentation/AppKit/NSDocument/fileName","doc://com.apple.appkit/documentation/AppKit/NSDocument/fileWrapperRepresentationOfType:","doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfFile:ofType:","doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfURL:ofType:","doc://com.apple.appkit/documentation/AppKit/NSDocument/loadDataRepresentation:ofType:","doc://com.apple.appkit/documentation/AppKit/NSDocument/loadFileWrapperRepresentation:ofType:","doc://com.apple.appkit/documentation/AppKit/NSDocument/printShowingPrintPanel:","doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromFile:ofType:","doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromURL:ofType:","doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromFile:ofType:","doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromURL:ofType:","doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayoutWithPrintInfo:","doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:"]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/save(to:ofType:for:completionHandler:)","isActive":true,"type":"reference"},{"text":" instead.","type":"text"}]}],"kind":"symbol","variants":[{"paths":["/documentation/appkit/nsdocument/savetourl:oftype:forsaveoperation:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDocument"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Saves the contents of the document to a file or file package located by a URL, formatted to a specified type, for a particular kind of save operation."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"saveToURL:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"url","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ofType:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"typeName","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forSaveOperation:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/SaveOperationType","text":"NSSaveOperationType","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSSaveOperationType"},{"text":") ","kind":"text"},{"text":"saveOperation","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"outError"},{"kind":"text","text":";"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The location of the file or file package to which the document contents are saved."}]}],"name":"url"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The string that identifies the document type."}]}],"name":"typeName"},{"content":[{"inlineContent":[{"type":"text","text":"The type of save operation."}],"type":"paragraph"}],"name":"saveOperation"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On return, if the document contents could not be saved, a pointer to an error object that encapsulates the reason they could not be saved."}]}],"name":"outError"}]},{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":""},{"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference","isActive":true},{"type":"text","text":" if the document contents were successfully saved; otherwise, "},{"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"Discussion"},{"inlineContent":[{"text":"You can override this method to do things that need to be done before or after any save operation. If you override this method, you must call ","type":"text"},{"code":"super","type":"codeVoice"},{"text":" at some point in your implementation.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"modules":[{"name":"AppKit"}],"title":"saveToURL:ofType:forSaveOperation:error:","fragments":[{"text":"- ","kind":"text"},{"text":"saveToURL:ofType:forSaveOperation:error:","kind":"identifier"}],"navigatorTitle":[{"text":"saveToURL:ofType:forSaveOperation:error:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:objc(cs)NSDocument(im)saveToURL:ofType:forSaveOperation:error:","role":"symbol","platforms":[{"beta":false,"name":"macOS","deprecatedAt":"10.6","deprecated":false,"introducedAt":"10.4","unavailable":false}]},"references":{"doc://com.apple.documentation/documentation/swift/false":{"title":"false","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/false","role":"symbol","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","url":"/documentation/swift/false"},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/fileAttributesToWriteToFile:ofType:saveOperation:":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Returns the file attributes that should be written to the named document file of the specified type."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/fileAttributesToWriteToFile:ofType:saveOperation:","navigatorTitle":[{"kind":"identifier","text":"fileAttributesToWriteToFile:ofType:saveOperation:"}],"deprecated":true,"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fileAttributesToWriteToFile:ofType:saveOperation:"}],"title":"fileAttributesToWriteToFile:ofType:saveOperation:","url":"/documentation/appkit/nsdocument/fileattributestowritetofile:oftype:saveoperation:"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/SaveOperationType":{"abstract":[{"type":"text","text":"Constants for specifying the type of document-save operation to perform."}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/SaveOperationType","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SaveOperationType","kind":"identifier"}],"title":"NSDocument.SaveOperationType","url":"/documentation/appkit/nsdocument/saveoperationtype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SaveOperationType","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/printShowingPrintPanel:":{"fragments":[{"text":"- ","kind":"text"},{"text":"printShowingPrintPanel:","kind":"identifier"}],"title":"printShowingPrintPanel:","url":"/documentation/appkit/nsdocument/printshowingprintpanel:","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/printShowingPrintPanel:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"printShowingPrintPanel:"}],"kind":"symbol","abstract":[{"text":"Prints the current document’s data.","type":"text"}],"deprecated":true},"doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfFile:ofType:":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Initializes and returns a document object."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfFile:ofType:","navigatorTitle":[{"kind":"identifier","text":"initWithContentsOfFile:ofType:"}],"deprecated":true,"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithContentsOfFile:ofType:"}],"title":"initWithContentsOfFile:ofType:","url":"/documentation/appkit/nsdocument/initwithcontentsoffile:oftype:"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromURL:ofType:":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromURL:ofType:","deprecated":true,"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"readFromURL:ofType:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"readFromURL:ofType:"}],"type":"topic","title":"readFromURL:ofType:","url":"/documentation/appkit/nsdocument/readfromurl:oftype:","kind":"symbol","abstract":[{"type":"text","text":"Reads and loads document data."}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToURL:ofType:forSaveOperation:error:":{"role":"symbol","type":"topic","title":"saveToURL:ofType:forSaveOperation:error:","url":"/documentation/appkit/nsdocument/savetourl:oftype:forsaveoperation:error:","navigatorTitle":[{"text":"saveToURL:ofType:forSaveOperation:error:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToURL:ofType:forSaveOperation:error:","deprecated":true,"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"saveToURL:ofType:forSaveOperation:error:"}],"abstract":[{"type":"text","text":"Saves the contents of the document to a file or file package located by a URL, formatted to a specified type, for a particular kind of save operation."}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromFile:ofType:":{"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"readFromFile:ofType:"}],"title":"readFromFile:ofType:","abstract":[{"type":"text","text":"Reads and loads document data of the given type from the given file."}],"url":"/documentation/appkit/nsdocument/readfromfile:oftype:","role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromFile:ofType:","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"readFromFile:ofType:"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/fileWrapperRepresentationOfType:":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/fileWrapperRepresentationOfType:","deprecated":true,"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"fileWrapperRepresentationOfType:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"fileWrapperRepresentationOfType:"}],"type":"topic","title":"fileWrapperRepresentationOfType:","url":"/documentation/appkit/nsdocument/filewrapperrepresentationoftype:","kind":"symbol","abstract":[{"type":"text","text":"Returns a file wrapper object that represents the data of the receiver in a given type."}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSString","kind":"identifier"}],"title":"NSString","kind":"symbol","url":"/documentation/foundation/nsstring","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayoutWithPrintInfo:":{"deprecated":true,"title":"runModalPageLayoutWithPrintInfo:","abstract":[{"type":"text","text":"Runs the page layout modal panel with the receiver’s printing information object."}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"runModalPageLayoutWithPrintInfo:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayoutWithPrintInfo:","kind":"symbol","url":"/documentation/appkit/nsdocument/runmodalpagelayoutwithprintinfo:","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"runModalPageLayoutWithPrintInfo:"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/fileName":{"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fileName"}],"title":"fileName","abstract":[{"type":"text","text":"Returns the fully qualified pathname under which the receiver has been saved."}],"url":"/documentation/appkit/nsdocument/filename","role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/fileName","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"fileName"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfURL:ofType:":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfURL:ofType:","deprecated":true,"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithContentsOfURL:ofType:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithContentsOfURL:ofType:"}],"type":"topic","title":"initWithContentsOfURL:ofType:","url":"/documentation/appkit/nsdocument/initwithcontentsofurl:oftype:","kind":"symbol","abstract":[{"type":"text","text":"Initializes and returns a document object of a given type."}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromFile:ofType:":{"deprecated":true,"title":"revertToSavedFromFile:ofType:","abstract":[{"text":"Reverts the receiver to the data stored in the file system.","type":"text"}],"fragments":[{"text":"- ","kind":"text"},{"text":"revertToSavedFromFile:ofType:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromFile:ofType:","kind":"symbol","url":"/documentation/appkit/nsdocument/reverttosavedfromfile:oftype:","role":"symbol","type":"topic","navigatorTitle":[{"text":"revertToSavedFromFile:ofType:","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromURL:ofType:":{"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"revertToSavedFromURL:ofType:"}],"title":"revertToSavedFromURL:ofType:","abstract":[{"type":"text","text":"Reverts the receiver."}],"url":"/documentation/appkit/nsdocument/reverttosavedfromurl:oftype:","role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromURL:ofType:","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"revertToSavedFromURL:ofType:"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:":{"url":"/documentation/appkit/nsdocument/savetofile:saveoperation:delegate:didsaveselector:contextinfo:","fragments":[{"text":"- ","kind":"text"},{"text":"saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:","title":"saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:","kind":"symbol","navigatorTitle":[{"text":"saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:","kind":"identifier"}],"abstract":[{"text":"Called after the user has been given the opportunity to select a destination through the modal Save panel.","type":"text"}],"type":"topic","deprecated":true},"doc://com.apple.appkit/documentation/AppKit/NSDocument/loadFileWrapperRepresentation:ofType:":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Loads document data from a given file wrapper."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/loadFileWrapperRepresentation:ofType:","navigatorTitle":[{"kind":"identifier","text":"loadFileWrapperRepresentation:ofType:"}],"deprecated":true,"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadFileWrapperRepresentation:ofType:"}],"title":"loadFileWrapperRepresentation:ofType:","url":"/documentation/appkit/nsdocument/loadfilewrapperrepresentation:oftype:"},"doc://com.externally.resolved.symbol/c:objc(cs)NSError":{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","title":"NSError","fragments":[{"text":"class ","kind":"text"},{"text":"NSError","kind":"identifier"}],"abstract":[{"text":"Information about an error condition including a domain, a domain-specific error code, and application-specific information.","type":"text"}],"role":"symbol","url":"/documentation/foundation/nserror","type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDocument":{"abstract":[{"text":"An abstract class that defines the interface for macOS documents.","type":"text"}],"type":"topic","title":"NSDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDocument","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument","role":"symbol","url":"/documentation/appkit/nsdocument","navigatorTitle":[{"text":"NSDocument","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/save(to:ofType:for:completionHandler:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/save(to:ofType:for:completionHandler:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"save","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"ofType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSDocument","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDocument"},{"text":".","kind":"text"},{"text":"SaveOperationType","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSSaveOperationType"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","url":"/documentation/appkit/nsdocument/save(to:oftype:for:completionhandler:)","navigatorTitle":[{"text":"saveToURL:ofType:forSaveOperation:completionHandler:","kind":"identifier"}],"abstract":[{"text":"Saves the contents of the document to a file or file package located by a URL, that is formatted to a specified type, for a particular kind of save operation, and invokes the passed-in completion handler.","type":"text"}],"title":"save(to:ofType:for:completionHandler:)"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/dataRepresentationOfType:":{"type":"topic","title":"dataRepresentationOfType:","abstract":[{"text":"A primitive method to return a data object that represents the data of the receiver in a given type.","type":"text"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"dataRepresentationOfType:","kind":"identifier"}],"navigatorTitle":[{"text":"dataRepresentationOfType:","kind":"identifier"}],"url":"/documentation/appkit/nsdocument/datarepresentationoftype:","kind":"symbol","deprecated":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/dataRepresentationOfType:"},"doc://com.externally.resolved.symbol/c:objc(cs)NSURL":{"role":"symbol","url":"/documentation/foundation/nsurl","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSURL","title":"NSURL","abstract":[{"text":"An object representing the location of a resource that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"type":"topic","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSURL"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/loadDataRepresentation:ofType:":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/loadDataRepresentation:ofType:","deprecated":true,"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"loadDataRepresentation:ofType:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"loadDataRepresentation:ofType:"}],"type":"topic","title":"loadDataRepresentation:ofType:","url":"/documentation/appkit/nsdocument/loaddatarepresentation:oftype:","kind":"symbol","abstract":[{"type":"text","text":"Loads the document data."}]}},"variantOverrides":[{"patch":[{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1SaveOperationType/title","value":"NSSaveOperationType","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1SaveOperationType/fragments","value":[{"text":"NSSaveOperationType","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1SaveOperationType/navigatorTitle","value":[{"kind":"identifier","text":"NSSaveOperationType"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","value":[{"type":"text","text":"A static, plain-text Unicode string object."}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/title","value":"NSDocument","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/fragments","value":[{"kind":"identifier","text":"NSDocument"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/navigatorTitle","value":[{"kind":"identifier","text":"NSDocument"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1save(to:ofType:for:completionHandler:)/title","value":"saveToURL:ofType:forSaveOperation:completionHandler:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1save(to:ofType:for:completionHandler:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"saveToURL:ofType:forSaveOperation:completionHandler:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSURL/abstract","value":[{"type":"text","text":"An object that represents the location of a resource, such as an item on a remote server or the path to a local file. "}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}