{"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/updateChangeCount(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/fileType","doc://com.apple.appkit/documentation/AppKit/NSDocument/fileURL"],"title":"Related Documentation","anchor":"Related-Documentation"},{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/printDocument(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/runPageLayout(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSaved(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/save(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/saveTo(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/save(withDelegate:didSave:contextInfo:)"],"title":"Handling User Actions","anchor":"Handling-User-Actions"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@IBAction"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"saveAs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"sender","content":[{"type":"paragraph","inlineContent":[{"text":"The control sending the message.","type":"text"}]}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"The default implementation runs the modal Save panel to get the file location under which to save the document. It writes the document to this file, sets the document’s file location and document type (if a native type), and clears the document’s edited status.","type":"text"}],"type":"paragraph"}]}],"metadata":{"roleHeading":"Instance Method","platforms":[{"name":"macOS","unavailable":false,"deprecated":false,"beta":false}],"navigatorTitle":[{"text":"saveDocumentAs:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"saveAs","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"modules":[{"name":"AppKit"}],"role":"symbol","title":"saveAs(_:)","externalID":"c:objc(cs)NSDocument(im)saveDocumentAs:"},"kind":"symbol","variants":[{"paths":["/documentation/appkit/nsdocument/saveas(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsdocument/saveas(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSDocument/saveAs(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDocument"]]},"abstract":[{"type":"text","text":"The action method invoked in the receiver as first responder when the user chooses the Save As menu command."}],"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/save(_:)":{"kind":"symbol","title":"save(_:)","navigatorTitle":[{"kind":"identifier","text":"saveDocument:"}],"role":"symbol","abstract":[{"type":"text","text":"The action method invoked in the receiver as first responder when the user chooses the Save menu command."}],"url":"/documentation/appkit/nsdocument/save(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/save(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"save","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/runPageLayout(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/runPageLayout(_:)","kind":"symbol","navigatorTitle":[{"text":"runPageLayout:","kind":"identifier"}],"title":"runPageLayout(_:)","abstract":[{"type":"text","text":"The action method invoked in the receiver as first responder when the user chooses the Page Setup menu command."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"runPageLayout","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nsdocument/runpagelayout(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/printDocument(_:)":{"title":"printDocument(_:)","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/printDocument(_:)","navigatorTitle":[{"kind":"identifier","text":"printDocument:"}],"abstract":[{"text":"Prints the receiver in response to the user choosing the Print menu command.","type":"text"}],"type":"topic","kind":"symbol","url":"/documentation/appkit/nsdocument/printdocument(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"printDocument"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument":{"abstract":[{"text":"An abstract class that defines the interface for macOS documents.","type":"text"}],"type":"topic","title":"NSDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDocument","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument","role":"symbol","url":"/documentation/appkit/nsdocument","navigatorTitle":[{"text":"NSDocument","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/save(withDelegate:didSave:contextInfo:)":{"url":"/documentation/appkit/nsdocument/save(withdelegate:didsave:contextinfo:)","title":"save(withDelegate:didSave:contextInfo:)","role":"symbol","abstract":[{"type":"text","text":"Saves the document and delivers the results to the provided delegate object."}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/save(withDelegate:didSave:contextInfo:)","navigatorTitle":[{"text":"saveDocumentWithDelegate:didSaveSelector:contextInfo:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"save","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withDelegate"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"didSave"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contextInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSaved(_:)":{"role":"symbol","url":"/documentation/appkit/nsdocument/reverttosaved(_:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSaved(_:)","title":"revertToSaved(_:)","abstract":[{"type":"text","text":"The action of the File menu item Revert in a document-based app."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"revertDocumentToSaved:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"revertToSaved"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/fileURL":{"title":"fileURL","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/fileURL","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fileURL","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"The location of the document’s on-disk representation.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"fileURL","kind":"identifier"}],"url":"/documentation/appkit/nsdocument/fileurl"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/saveAs(_:)":{"kind":"symbol","title":"saveAs(_:)","navigatorTitle":[{"text":"saveDocumentAs:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The action method invoked in the receiver as first responder when the user chooses the Save As menu command."}],"url":"/documentation/appkit/nsdocument/saveas(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/saveAs(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"saveAs","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/fileType":{"url":"/documentation/appkit/nsdocument/filetype","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"fileType"}],"role":"symbol","type":"topic","title":"fileType","abstract":[{"text":"The name of the document type, as specified in the app’s information property-list file.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/fileType"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/saveTo(_:)":{"kind":"symbol","title":"saveTo(_:)","navigatorTitle":[{"text":"saveDocumentTo:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The action method invoked in the receiver as first responder when the user chooses the Save To menu command.","type":"text"}],"url":"/documentation/appkit/nsdocument/saveto(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/saveTo(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"saveTo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/updateChangeCount(_:)":{"title":"updateChangeCount(_:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/updateChangeCount(_:)","url":"/documentation/appkit/nsdocument/updatechangecount(_:)","navigatorTitle":[{"kind":"identifier","text":"updateChangeCount:"}],"abstract":[{"text":"Updates the receiver’s change count according to the given change type.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateChangeCount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDocument","preciseIdentifier":"c:objc(cs)NSDocument"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ChangeType","preciseIdentifier":"c:@E@NSDocumentChangeType"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}],"op":"replace","path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"saveDocumentAs:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"saveDocumentAs:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDocument"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/updateChangeCount(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/fileType","doc://com.apple.appkit/documentation/AppKit/NSDocument/fileURL"]},{"title":"Handling User Actions","generated":true,"anchor":"Handling-User-Actions","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/printDocument(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/runPageLayout(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSaved(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/save(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/saveTo(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/save(withDelegate:didSave:contextInfo:)"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"saveDocumentAs:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"sender","content":[{"type":"paragraph","inlineContent":[{"text":"The control sending the message.","type":"text"}]}]}]},"op":"replace"},{"op":"replace","value":"saveDocument:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1save(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"saveDocument:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1save(_:)/fragments"},{"op":"replace","value":"runPageLayout:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1runPageLayout(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"runPageLayout:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1runPageLayout(_:)/fragments"},{"op":"replace","value":"printDocument:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1printDocument(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"printDocument:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1printDocument(_:)/fragments"},{"op":"replace","value":"NSDocument","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/title"},{"op":"replace","value":[{"text":"NSDocument","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/fragments"},{"op":"replace","value":[{"text":"NSDocument","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/navigatorTitle"},{"op":"replace","value":"saveDocumentWithDelegate:didSaveSelector:contextInfo:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1save(withDelegate:didSave:contextInfo:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"saveDocumentWithDelegate:didSaveSelector:contextInfo:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1save(withDelegate:didSave:contextInfo:)/fragments"},{"op":"replace","value":"revertDocumentToSaved:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1revertToSaved(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"revertDocumentToSaved:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1revertToSaved(_:)/fragments"},{"op":"replace","value":"fileURL","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1fileURL/title"},{"op":"replace","value":[{"text":"fileURL","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1fileURL/fragments"},{"op":"replace","value":"saveDocumentAs:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1saveAs(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"saveDocumentAs:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1saveAs(_:)/fragments"},{"op":"replace","value":"fileType","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1fileType/title"},{"op":"replace","value":[{"kind":"identifier","text":"fileType"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1fileType/fragments"},{"op":"replace","value":"saveDocumentTo:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1saveTo(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"saveDocumentTo:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1saveTo(_:)/fragments"},{"op":"replace","value":"updateChangeCount:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1updateChangeCount(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"updateChangeCount:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1updateChangeCount(_:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}