{
  "abstract": [
    {
      "text": "Determines whether the system should close the document and its associated window.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDocument/shouldCloseWindowController(_:delegate:shouldClose:contextInfo:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSDocument(im)shouldCloseWindowController:delegate:shouldCloseSelector:contextInfo:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "shouldCloseWindowController"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSWindowController",
        "text": "NSWindowController"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "delegate"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "shouldClose"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10ObjectiveC8SelectorV",
        "text": "Selector"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "contextInfo"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sv",
        "text": "UnsafeMutableRawPointer"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "shouldCloseWindowController:delegate:shouldCloseSelector:contextInfo:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "shouldCloseWindowController(_:delegate:shouldClose:contextInfo:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "shouldCloseWindowController"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "windowController"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSWindowController",
              "text": "NSWindowController"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "delegate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "shouldClose"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "shouldCloseSelector"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10ObjectiveC8SelectorV",
              "text": "Selector"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "contextInfo"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The window controller that is closed.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "windowController"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The delegate to which the selector message is sent.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "delegate"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The selector of the message sent to the delegate.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "shouldCloseSelector"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Object passed with the callback to provide any additional context information.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "contextInfo"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the window controller is the document’s last one, or is marked as causing the document to close, this method calls the method in the ",
              "type": "text"
            },
            {
              "code": "shouldCloseSelector",
              "type": "codeVoice"
            },
            {
              "text": " parameter with the result of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/canClose(withDelegate:shouldClose:contextInfo:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". In all other cases, this method calls ",
              "type": "text"
            },
            {
              "code": "shouldCloseSelector",
              "type": "codeVoice"
            },
            {
              "text": " with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This method is called automatically by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for any window that has a window controller and a document associated with it. ",
              "type": "text"
            },
            {
              "code": "NSWindow",
              "type": "codeVoice"
            },
            {
              "text": " calls this method prior to sending its ",
              "type": "text"
            },
            {
              "code": "delegate",
              "type": "codeVoice"
            },
            {
              "text": " the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate/windowShouldClose(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " message. Pass the ",
              "type": "text"
            },
            {
              "code": "contextInfo",
              "type": "codeVoice"
            },
            {
              "text": " object with the callback.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "shouldCloseSelector",
              "type": "codeVoice"
            },
            {
              "text": " callback method should have the following signature:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "- (void)document:(NSDocument *)document shouldClose:(BOOL)shouldClose  contextInfo:(void  *)contextInfo"
          ],
          "syntax": "objc",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument": {
      "abstract": [
        {
          "text": "An abstract class that defines the interface for macOS documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDocument"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDocument"
        }
      ],
      "role": "symbol",
      "title": "NSDocument",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/addWindowController(_:)": {
      "abstract": [
        {
          "text": "Adds the specified window controller to the current document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addWindowController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindowController",
          "text": "NSWindowController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/addWindowController(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addWindowController:"
        }
      ],
      "role": "symbol",
      "title": "addWindowController(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/addwindowcontroller(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/canClose(withDelegate:shouldClose:contextInfo:)": {
      "abstract": [
        {
          "text": "Determines whether to close the document, prompting the user as needed to choose a course of action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canClose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withDelegate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldClose"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "contextInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/canClose(withDelegate:shouldClose:contextInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canCloseDocumentWithDelegate:shouldCloseSelector:contextInfo:"
        }
      ],
      "role": "symbol",
      "title": "canClose(withDelegate:shouldClose:contextInfo:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/canclose(withdelegate:shouldclose:contextinfo:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/makeWindowControllers()": {
      "abstract": [
        {
          "text": "Creates the window controller objects that the document uses to display its content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeWindowControllers"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/makeWindowControllers()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeWindowControllers"
        }
      ],
      "role": "symbol",
      "title": "makeWindowControllers()",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/makewindowcontrollers()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/removeWindowController(_:)": {
      "abstract": [
        {
          "text": "Removes the specified window controller from the receiver’s array of window controllers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeWindowController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindowController",
          "text": "NSWindowController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/removeWindowController(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeWindowController:"
        }
      ],
      "role": "symbol",
      "title": "removeWindowController(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/removewindowcontroller(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/shouldCloseWindowController(_:delegate:shouldClose:contextInfo:)": {
      "abstract": [
        {
          "text": "Determines whether the system should close the document and its associated window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldCloseWindowController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindowController",
          "text": "NSWindowController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "shouldClose"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "contextInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/shouldCloseWindowController(_:delegate:shouldClose:contextInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldCloseWindowController:delegate:shouldCloseSelector:contextInfo:"
        }
      ],
      "role": "symbol",
      "title": "shouldCloseWindowController(_:delegate:shouldClose:contextInfo:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/shouldclosewindowcontroller(_:delegate:shouldclose:contextinfo:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/windowControllerDidLoadNib(_:)": {
      "abstract": [
        {
          "text": "Called after one of the document’s window controllers loads its nib file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windowControllerDidLoadNib"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindowController",
          "text": "NSWindowController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/windowControllerDidLoadNib(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "windowControllerDidLoadNib:"
        }
      ],
      "role": "symbol",
      "title": "windowControllerDidLoadNib(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/windowcontrollerdidloadnib(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/windowControllerWillLoadNib(_:)": {
      "abstract": [
        {
          "text": "Called before one of the document’s window controllers loads its nib file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windowControllerWillLoadNib"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindowController",
          "text": "NSWindowController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/windowControllerWillLoadNib(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "windowControllerWillLoadNib:"
        }
      ],
      "role": "symbol",
      "title": "windowControllerWillLoadNib(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/windowcontrollerwillloadnib(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/windowControllers": {
      "abstract": [
        {
          "text": "The document’s current window controllers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windowControllers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindowController",
          "text": "NSWindowController"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/windowControllers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "windowControllers"
        }
      ],
      "role": "symbol",
      "title": "windowControllers",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/windowcontrollers"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/windowNibName": {
      "abstract": [
        {
          "text": "The name of the document’s sole nib file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windowNibName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNib",
          "text": "NSNib"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNibName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/windowNibName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "windowNibName"
        }
      ],
      "role": "symbol",
      "title": "windowNibName",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/windownibname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow": {
      "abstract": [
        {
          "text": "A window that an app displays on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "role": "symbol",
      "title": "NSWindow",
      "type": "topic",
      "url": "/documentation/appkit/nswindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/performClose(_:)": {
      "abstract": [
        {
          "text": "Simulates the user clicking the close button by momentarily highlighting the button and then closing the window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performClose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/performClose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performClose:"
        }
      ],
      "role": "symbol",
      "title": "performClose(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/performclose(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowController": {
      "abstract": [
        {
          "text": "A controller that manages a window, usually a window stored in a nib file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindowController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowController"
        }
      ],
      "role": "symbol",
      "title": "NSWindowController",
      "type": "topic",
      "url": "/documentation/appkit/nswindowcontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate/windowShouldClose(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user has attempted to close a window or the window has received a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/performClose(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windowShouldClose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate/windowShouldClose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "windowShouldClose:"
        }
      ],
      "role": "symbol",
      "title": "windowShouldClose(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nswindowdelegate/windowshouldclose(_:)"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@SEL": {
      "abstract": [
        {
          "text": "Defines an opaque type that represents a method selector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@SEL",
      "kind": "symbol",
      "role": "symbol",
      "title": "SEL",
      "type": "topic",
      "url": "/documentation/objectivec/sel"
    },
    "doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Selector"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Selector",
      "type": "topic",
      "url": "/documentation/objectivec/selector"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-and-Managing-Window-Controllers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/makeWindowControllers()",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/addWindowController(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/removeWindowController(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/windowControllers",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/windowNibName",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/windowControllerDidLoadNib(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/windowControllerWillLoadNib(_:)"
      ],
      "title": "Creating and Managing Window Controllers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "shouldCloseWindowController:delegate:shouldCloseSelector:contextInfo:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "shouldCloseWindowController:delegate:shouldCloseSelector:contextInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-and-Managing-Window-Controllers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/makeWindowControllers()",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/addWindowController(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/removeWindowController(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/windowControllers",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/windowNibName",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/windowControllerDidLoadNib(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDocument/windowControllerWillLoadNib(_:)"
              ],
              "title": "Creating and Managing Window Controllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "shouldCloseWindowController:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSWindowController",
                    "text": "NSWindowController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "windowController"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "delegate:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "delegate"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "shouldCloseSelector:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@SEL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SEL",
                    "text": "SEL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "shouldCloseSelector"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "contextInfo:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "contextInfo"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The window controller that is closed.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "windowController"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The delegate to which the selector message is sent.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "delegate"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The selector of the message sent to the delegate.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "shouldCloseSelector"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Object passed with the callback to provide any additional context information.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "contextInfo"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1windowControllerDidLoadNib(_:)/title",
          "value": "windowControllerDidLoadNib:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1windowControllerDidLoadNib(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "windowControllerDidLoadNib:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1windowControllers/title",
          "value": "windowControllers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1windowControllers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "windowControllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1windowControllerWillLoadNib(_:)/title",
          "value": "windowControllerWillLoadNib:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1windowControllerWillLoadNib(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "windowControllerWillLoadNib:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1removeWindowController(_:)/title",
          "value": "removeWindowController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1removeWindowController(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeWindowController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1windowNibName/title",
          "value": "windowNibName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1windowNibName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "windowNibName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1performClose(_:)/title",
          "value": "performClose:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1performClose(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performClose:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/title",
          "value": "NSDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowDelegate~1windowShouldClose(_:)/title",
          "value": "windowShouldClose:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowDelegate~1windowShouldClose(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "windowShouldClose:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1makeWindowControllers()/title",
          "value": "makeWindowControllers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1makeWindowControllers()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "makeWindowControllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title",
          "value": "NSWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1shouldCloseWindowController(_:delegate:shouldClose:contextInfo:)/title",
          "value": "shouldCloseWindowController:delegate:shouldCloseSelector:contextInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1shouldCloseWindowController(_:delegate:shouldClose:contextInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "shouldCloseWindowController:delegate:shouldCloseSelector:contextInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowController/title",
          "value": "NSWindowController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1canClose(withDelegate:shouldClose:contextInfo:)/title",
          "value": "canCloseDocumentWithDelegate:shouldCloseSelector:contextInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1canClose(withDelegate:shouldClose:contextInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canCloseDocumentWithDelegate:shouldCloseSelector:contextInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1addWindowController(_:)/title",
          "value": "addWindowController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1addWindowController(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addWindowController:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdocument/shouldclosewindowcontroller(_:delegate:shouldclose:contextinfo:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsdocument/shouldclosewindowcontroller(_:delegate:shouldclose:contextinfo:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
