{"variants":[{"paths":["/documentation/appkit/nsdocument/showwindows()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsdocument/showwindows()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"showWindows","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showWindows","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"AppKit"}],"symbolKind":"method","title":"showWindows()","navigatorTitle":[{"text":"showWindows","kind":"identifier"}],"platforms":[{"name":"macOS","beta":false,"unavailable":false,"deprecated":false}],"externalID":"c:objc(cs)NSDocument(im)showWindows","role":"symbol"},"kind":"symbol","seeAlsoSections":[{"anchor":"Managing-Document-Windows","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/setWindow(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/windowForSheet","doc://com.apple.appkit/documentation/AppKit/NSDocument/displayName","doc://com.apple.appkit/documentation/AppKit/NSDocument/defaultDraftName()","doc://com.apple.appkit/documentation/AppKit/NSDocument/encodeRestorableState(with:backgroundQueue:)"],"title":"Managing Document Windows","generated":true}],"abstract":[{"type":"text","text":"Displays all of the document’s windows, bringing them to the front and making them main or key as necessary."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDocument"]]},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSDocument/showWindows()","interfaceLanguage":"swift"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSDocument/encodeRestorableState(with:backgroundQueue:)":{"url":"/documentation/appkit/nsdocument/encoderestorablestate(with:backgroundqueue:)","abstract":[{"text":"Saves the interface-related state of the document.","type":"text"}],"role":"symbol","title":"encodeRestorableState(with:backgroundQueue:)","navigatorTitle":[{"text":"encodeRestorableStateWithCoder:backgroundQueue:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/encodeRestorableState(with:backgroundQueue:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeRestorableState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"kind":"text","text":", "},{"kind":"externalParam","text":"backgroundQueue"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSOperationQueue","text":"OperationQueue","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/windowForSheet":{"url":"/documentation/appkit/nsdocument/windowforsheet","abstract":[{"text":"Returns the document window to use as the parent of a document-modal sheet.","type":"text"}],"role":"symbol","title":"windowForSheet","navigatorTitle":[{"kind":"identifier","text":"windowForSheet"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/windowForSheet","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"windowForSheet"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier","text":"NSWindow"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/displayName":{"title":"displayName","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/displayName","navigatorTitle":[{"kind":"identifier","text":"displayName"}],"kind":"symbol","type":"topic","url":"/documentation/appkit/nsdocument/displayname","abstract":[{"text":"The name of the document as displayed in the title bars of the document’s windows and in alert dialogs related to the document.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/showWindows()":{"url":"/documentation/appkit/nsdocument/showwindows()","abstract":[{"text":"Displays all of the document’s windows, bringing them to the front and making them main or key as necessary.","type":"text"}],"role":"symbol","title":"showWindows()","navigatorTitle":[{"kind":"identifier","text":"showWindows"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/showWindows()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showWindows"},{"kind":"text","text":"()"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/defaultDraftName()":{"abstract":[{"text":"Returns the default draft name for the document subclass.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/defaultDraftName()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultDraftName"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"defaultDraftName"}],"type":"topic","title":"defaultDraftName()","role":"symbol","url":"/documentation/appkit/nsdocument/defaultdraftname()"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/setWindow(_:)":{"title":"setWindow(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/setWindow(_:)","navigatorTitle":[{"kind":"identifier","text":"setWindow:"}],"kind":"symbol","type":"topic","url":"/documentation/appkit/nsdocument/setwindow(_:)","abstract":[{"text":"Sets the window outlet of this document to the specified value.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setWindow"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier","text":"NSWindow"},{"kind":"text","text":"?)"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument":{"abstract":[{"text":"An abstract class that defines the interface for macOS documents.","type":"text"}],"type":"topic","title":"NSDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDocument","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument","role":"symbol","url":"/documentation/appkit/nsdocument","navigatorTitle":[{"text":"NSDocument","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"path":"/metadata/title","value":"showWindows","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"showWindows","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDocument"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/setWindow(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/windowForSheet","doc://com.apple.appkit/documentation/AppKit/NSDocument/displayName","doc://com.apple.appkit/documentation/AppKit/NSDocument/defaultDraftName()","doc://com.apple.appkit/documentation/AppKit/NSDocument/encodeRestorableState(with:backgroundQueue:)"],"title":"Managing Document Windows","generated":true,"anchor":"Managing-Document-Windows"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"showWindows","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1encodeRestorableState(with:backgroundQueue:)/title","value":"encodeRestorableStateWithCoder:backgroundQueue:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1encodeRestorableState(with:backgroundQueue:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"encodeRestorableStateWithCoder:backgroundQueue:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1windowForSheet/title","value":"windowForSheet","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1windowForSheet/fragments","value":[{"kind":"identifier","text":"windowForSheet"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1displayName/title","value":"displayName","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1displayName/fragments","value":[{"text":"displayName","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1showWindows()/title","value":"showWindows","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1showWindows()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showWindows"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1defaultDraftName()/title","value":"defaultDraftName","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1defaultDraftName()/fragments","value":[{"text":"- ","kind":"text"},{"text":"defaultDraftName","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1setWindow(_:)/title","value":"setWindow:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1setWindow(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setWindow:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/title","value":"NSDocument","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/fragments","value":[{"text":"NSDocument","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/navigatorTitle","value":[{"text":"NSDocument","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}