{"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/browseVersions(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/isBrowsingVersions"],"anchor":"Browsing-Document-Versions","title":"Browsing Document Versions"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDocument"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSDocument/stopBrowsingVersions(completionHandler:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopBrowsingVersions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (() -> "},{"identifier":"doc://com.externally.resolved.symbol/s:s4Voida","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")? = nil)"}]},{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopBrowsingVersions"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"}]}]},{"kind":"parameters","parameters":[{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion handler block to call when the Versions browser is fully dismissed. AppKit calls this block on your app’s main thread, waiting for any dismissal animations to complete before calling it. The block block has no return value and no parameters."}]}]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"Discussion","text":"Discussion"}]}],"metadata":{"navigatorTitle":[{"text":"stopBrowsingVersionsWithCompletionHandler:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","title":"stopBrowsingVersions(completionHandler:)","externalID":"c:objc(cs)NSDocument(im)stopBrowsingVersionsWithCompletionHandler:","modules":[{"name":"AppKit"}],"platforms":[{"name":"macOS","introducedAt":"10.12","deprecated":false,"unavailable":false,"beta":false}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopBrowsingVersions","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"symbolKind":"method"},"variants":[{"paths":["/documentation/appkit/nsdocument/stopbrowsingversions(completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsdocument/stopbrowsingversions(completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Dismiss the Versions browser for the current document.","type":"text"}],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDocument":{"abstract":[{"text":"An abstract class that defines the interface for macOS documents.","type":"text"}],"type":"topic","title":"NSDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDocument","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument","role":"symbol","url":"/documentation/appkit/nsdocument","navigatorTitle":[{"text":"NSDocument","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/isBrowsingVersions":{"abstract":[{"type":"text","text":"A Boolean value that indicates whether the document is currently displaying the Versions browser."}],"url":"/documentation/appkit/nsdocument/isbrowsingversions","kind":"symbol","role":"symbol","title":"isBrowsingVersions","navigatorTitle":[{"text":"browsingVersions","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/isBrowsingVersions","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isBrowsingVersions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/browseVersions(_:)":{"navigatorTitle":[{"text":"browseDocumentVersions:","kind":"identifier"}],"title":"browseVersions(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"browseVersions","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/browseVersions(_:)","abstract":[{"type":"text","text":"Opens the Versions browser in the document’s main window."}],"role":"symbol","url":"/documentation/appkit/nsdocument/browseversions(_:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/stopBrowsingVersions(completionHandler:)":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"stopBrowsingVersionsWithCompletionHandler:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/stopBrowsingVersions(completionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopBrowsingVersions","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"kind":"symbol","url":"/documentation/appkit/nsdocument/stopbrowsingversions(completionhandler:)","abstract":[{"text":"Dismiss the Versions browser for the current document.","type":"text"}],"title":"stopBrowsingVersions(completionHandler:)"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:s4Voida":{"type":"topic","role":"symbol","abstract":[{"text":"The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.","type":"text"}],"kind":"symbol","url":"/documentation/Swift/Void","title":"Void","identifier":"doc://com.externally.resolved.symbol/s:s4Voida","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Void","kind":"identifier"},{"text":" = ()","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"name":"macOS","beta":false,"introducedAt":"10.12","unavailable":false,"deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"stopBrowsingVersionsWithCompletionHandler:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"stopBrowsingVersionsWithCompletionHandler:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDocument"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Browsing-Document-Versions","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/browseVersions(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/isBrowsingVersions"],"title":"Browsing Document Versions"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"stopBrowsingVersionsWithCompletionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)()) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"/primaryContentSections/1","op":"replace","value":{"parameters":[{"name":"completionHandler","content":[{"inlineContent":[{"text":"The completion handler block to call when the Versions browser is fully dismissed. AppKit calls this block on your app’s main thread, waiting for any dismissal animations to complete before calling it. The block block has no return value and no parameters.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/title","value":"NSDocument","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/fragments","value":[{"kind":"identifier","text":"NSDocument"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/navigatorTitle","value":[{"text":"NSDocument","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1isBrowsingVersions/title","value":"browsingVersions","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1isBrowsingVersions/fragments","value":[{"kind":"identifier","text":"browsingVersions"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1browseVersions(_:)/title","value":"browseDocumentVersions:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1browseVersions(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"browseDocumentVersions:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1stopBrowsingVersions(completionHandler:)/title","value":"stopBrowsingVersionsWithCompletionHandler:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1stopBrowsingVersions(completionHandler:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"stopBrowsingVersionsWithCompletionHandler:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}