{"abstract":[{"text":"Unlocks the document in response to the user choosing the Unlock menu item.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSDocument/unlock(_:)"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/lock(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/lock(completionHandler:)-6zuhh","doc://com.apple.appkit/documentation/AppKit/NSDocument/lock(completionHandler:)-161qv","doc://com.apple.appkit/documentation/AppKit/NSDocument/unlock(completionHandler:)-8p8zd","doc://com.apple.appkit/documentation/AppKit/NSDocument/unlock(completionHandler:)-6m7rh","doc://com.apple.appkit/documentation/AppKit/NSDocument/isLocked"],"anchor":"Locking-the-Document","title":"Locking the Document"}],"metadata":{"title":"unlock(_:)","navigatorTitle":[{"kind":"identifier","text":"unlockDocument:"}],"modules":[{"name":"AppKit"}],"platforms":[{"unavailable":false,"beta":false,"introducedAt":"10.8","name":"macOS","deprecated":false}],"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unlock"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)NSDocument(im)unlockDocument:"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDocument"]]},"variants":[{"paths":["/documentation/appkit/nsdocument/unlock(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsdocument/unlock(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@IBAction"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unlock"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"},{"parameters":[{"name":"sender","content":[{"type":"paragraph","inlineContent":[{"text":"The control sending the message.","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is the action of the Unlock menu item in a document-based app. This action method invokes the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/unlock(completionHandler:)-8p8zd"},{"type":"text","text":" method by default."}]}]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSDocument/unlock(completionHandler:)-6m7rh":{"navigatorTitle":[{"kind":"identifier","text":"unlockWithCompletionHandler:"}],"title":"unlock(completionHandler:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unlock"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (((any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/unlock(completionHandler:)-6m7rh","abstract":[{"text":"Allows the user to make modifications to the document’s file.","type":"text"}],"role":"symbol","url":"/documentation/appkit/nsdocument/unlock(completionhandler:)-6m7rh","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/isLocked":{"url":"/documentation/appkit/nsdocument/islocked","kind":"symbol","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/isLocked","abstract":[{"type":"text","text":"A Boolean value that indicates whether or not the file can be written to."}],"navigatorTitle":[{"kind":"identifier","text":"locked"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLocked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isLocked"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/lock(completionHandler:)-6zuhh":{"url":"/documentation/appkit/nsdocument/lock(completionhandler:)-6zuhh","kind":"symbol","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/lock(completionHandler:)-6zuhh","abstract":[{"text":"Prevents the user from making further changes to the document.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"lockDocumentWithCompletionHandler:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"lock","kind":"identifier"},{"kind":"text","text":"("},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"title":"lock(completionHandler:)"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/lock(completionHandler:)-161qv":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/lock(completionHandler:)-161qv","abstract":[{"type":"text","text":"Prevents the user from making changes to the document’s file."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"lockWithCompletionHandler:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lock"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (((any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"title":"lock(completionHandler:)","kind":"symbol","url":"/documentation/appkit/nsdocument/lock(completionhandler:)-161qv","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/unlock(_:)":{"abstract":[{"type":"text","text":"Unlocks the document in response to the user choosing the Unlock menu item."}],"url":"/documentation/appkit/nsdocument/unlock(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unlock"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/unlock(_:)","title":"unlock(_:)","navigatorTitle":[{"kind":"identifier","text":"unlockDocument:"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/lock(_:)":{"url":"/documentation/appkit/nsdocument/lock(_:)","role":"symbol","kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/lock(_:)","navigatorTitle":[{"text":"lockDocument:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lock","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"title":"lock(_:)","abstract":[{"text":"Locks the document in response to the user choosing the Lock menu item.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/unlock(completionHandler:)-8p8zd":{"abstract":[{"type":"text","text":"Allows the user to make modifications to the document."}],"url":"/documentation/appkit/nsdocument/unlock(completionhandler:)-8p8zd","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unlock"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/unlock(completionHandler:)-8p8zd","title":"unlock(completionHandler:)","navigatorTitle":[{"kind":"identifier","text":"unlockDocumentWithCompletionHandler:"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSDocument":{"abstract":[{"text":"An abstract class that defines the interface for macOS documents.","type":"text"}],"type":"topic","title":"NSDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDocument","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument","role":"symbol","url":"/documentation/appkit/nsdocument","navigatorTitle":[{"text":"NSDocument","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"macOS","introducedAt":"10.8","beta":false,"unavailable":false,"deprecated":false}]},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"unlockDocument:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unlockDocument:"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDocument"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Locking the Document","generated":true,"anchor":"Locking-the-Document","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/lock(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/lock(completionHandler:)-6zuhh","doc://com.apple.appkit/documentation/AppKit/NSDocument/lock(completionHandler:)-161qv","doc://com.apple.appkit/documentation/AppKit/NSDocument/unlock(completionHandler:)-8p8zd","doc://com.apple.appkit/documentation/AppKit/NSDocument/unlock(completionHandler:)-6m7rh","doc://com.apple.appkit/documentation/AppKit/NSDocument/isLocked"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"unlockDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]},"path":"/primaryContentSections/0"},{"op":"replace","path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The control sending the message.","type":"text"}],"type":"paragraph"}],"name":"sender"}],"kind":"parameters"}},{"op":"replace","value":"unlockWithCompletionHandler:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1unlock(completionHandler:)-6m7rh/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"unlockWithCompletionHandler:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1unlock(completionHandler:)-6m7rh/fragments"},{"op":"replace","value":"locked","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1isLocked/title"},{"value":[{"kind":"identifier","text":"locked"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1isLocked/fragments","op":"replace"},{"value":"lockDocumentWithCompletionHandler:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1lock(completionHandler:)-6zuhh/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"lockDocumentWithCompletionHandler:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1lock(completionHandler:)-6zuhh/fragments","op":"replace"},{"value":"lockWithCompletionHandler:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1lock(completionHandler:)-161qv/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"lockWithCompletionHandler:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1lock(completionHandler:)-161qv/fragments","op":"replace"},{"value":"unlockDocument:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1unlock(_:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"unlockDocument:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1unlock(_:)/fragments","op":"replace"},{"value":"lockDocument:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1lock(_:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"lockDocument:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1lock(_:)/fragments","op":"replace"},{"value":"unlockDocumentWithCompletionHandler:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1unlock(completionHandler:)-8p8zd/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unlockDocumentWithCompletionHandler:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1unlock(completionHandler:)-8p8zd/fragments","op":"replace"},{"value":"NSDocument","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSDocument"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"NSDocument"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}