{"seeAlsoSections":[{"generated":true,"title":"Displaying Errors to the User","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/presentError(_:modalFor:delegate:didPresent:contextInfo:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/presentError(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/willPresentError(_:)"],"anchor":"Displaying-Errors-to-the-User"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsdocument/willnotpresenterror(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsdocument/willnotpresenterror(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSDocument/willNotPresentError(_:)"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willNotPresentError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s5ErrorP","identifier":"doc://com.externally.resolved.symbol/s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"An ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/foundation/nserror","type":"reference","isActive":true},{"text":" object returned by another ","type":"text"},{"type":"codeVoice","code":"NSDocument"},{"text":" method.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"inlineContent":[{"type":"text","text":"Some "},{"type":"codeVoice","code":"NSDocument"},{"type":"text","text":" methods, like those involved in writing, may not immediately delete temporary files if there is a chance that the error can be recovered from and the operation can continue. To make sure that cleanup is always done, you should invoke this method with "},{"type":"codeVoice","code":"NSDocument"},{"type":"text","text":" errors that are not going to be passed to one of the "},{"type":"codeVoice","code":"presentError:..."},{"type":"text","text":" methods. For example, the "},{"type":"codeVoice","code":"NSDocument"},{"type":"text","text":" implementation of the "},{"type":"codeVoice","code":"NSFilePresenter"},{"type":"text","text":" method "},{"identifier":"doc://com.apple.documentation/documentation/foundation/nsfilepresenter/1414407-savepresenteditemchanges","type":"reference","isActive":true},{"type":"text","text":" invokes this method when it invokes "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/autosave(withImplicitCancellability:completionHandler:)","type":"reference","isActive":true},{"type":"text","text":" and the completion handler is passed an "},{"type":"codeVoice","code":"NSError"},{"type":"text","text":" object, because it does not present the error to the user."}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDocument"]]},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"AppKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willNotPresentError","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":[{"beta":false,"unavailable":false,"introducedAt":"10.7","name":"macOS","deprecated":false}],"role":"symbol","title":"willNotPresentError(_:)","navigatorTitle":[{"text":"willNotPresentError:","kind":"identifier"}],"externalID":"c:objc(cs)NSDocument(im)willNotPresentError:"},"abstract":[{"type":"text","text":"Confirms that the error object is not to be presented to the user and the error cannot be recovered from, so cleanup can be done."}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSDocument/willPresentError(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"willPresentError","kind":"identifier"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":") -> any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"}],"url":"/documentation/appkit/nsdocument/willpresenterror(_:)","abstract":[{"text":"Called when the receiver is about to present an error.","type":"text"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/willPresentError(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"willPresentError:"}],"title":"willPresentError(_:)"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/foundation/nsfilepresenter/1414407-savepresenteditemchanges":{"type":"topic","role":"symbol","fragments":[{"text":"func ","kind":"text"},{"text":"savePresentedItemChanges","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"identifier"},{"text":": ((any Error)?) -> Void)","kind":"text"}],"url":"/documentation/foundation/nsfilepresenter/1414407-savepresenteditemchanges","kind":"symbol","abstract":[{"text":"Tells your object to save any unsaved changes for the presented item.","type":"text"}],"title":"savePresentedItemChanges(completionHandler:)","identifier":"doc://com.apple.documentation/documentation/foundation/nsfilepresenter/1414407-savepresenteditemchanges"},"doc://com.externally.resolved.symbol/c:objc(cs)NSError":{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","title":"NSError","fragments":[{"text":"class ","kind":"text"},{"text":"NSError","kind":"identifier"}],"abstract":[{"text":"Information about an error condition including a domain, a domain-specific error code, and application-specific information.","type":"text"}],"role":"symbol","url":"/documentation/foundation/nserror","type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/foundation/nserror":{"identifier":"doc://com.apple.documentation/documentation/foundation/nserror","kind":"symbol","title":"NSError","fragments":[{"kind":"text","text":"class "},{"text":"NSError","kind":"identifier"}],"abstract":[{"type":"text","text":"Information about an error condition including a domain, a domain-specific error code, and application-specific information."}],"url":"/documentation/foundation/nserror","role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/willNotPresentError(_:)":{"url":"/documentation/appkit/nsdocument/willnotpresenterror(_:)","title":"willNotPresentError(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willNotPresentError"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"willNotPresentError:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/willNotPresentError(_:)","abstract":[{"text":"Confirms that the error object is not to be presented to the user and the error cannot be recovered from, so cleanup can be done.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/presentError(_:)":{"url":"/documentation/appkit/nsdocument/presenterror(_:)","role":"symbol","kind":"symbol","title":"presentError(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentError:"}],"abstract":[{"type":"text","text":"Presents an error alert to the user as a modal panel."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentError"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/presentError(_:)"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSDocument":{"abstract":[{"text":"An abstract class that defines the interface for macOS documents.","type":"text"}],"type":"topic","title":"NSDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDocument","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument","role":"symbol","url":"/documentation/appkit/nsdocument","navigatorTitle":[{"text":"NSDocument","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSDocument/autosave(withImplicitCancellability:completionHandler:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"autosaveWithImplicitCancellability:completionHandler:","kind":"identifier"}],"url":"/documentation/appkit/nsdocument/autosave(withimplicitcancellability:completionhandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autosave","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withImplicitCancellability","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/autosave(withImplicitCancellability:completionHandler:)","title":"autosave(withImplicitCancellability:completionHandler:)","abstract":[{"text":"Autosaves the document’s contents to an appropriate file-system location, as needed.","type":"text"}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSDocument/presentError(_:modalFor:delegate:didPresent:contextInfo:)":{"title":"presentError(_:modalFor:delegate:didPresent:contextInfo:)","role":"symbol","url":"/documentation/appkit/nsdocument/presenterror(_:modalfor:delegate:didpresent:contextinfo:)","navigatorTitle":[{"text":"presentError:modalForWindow:delegate:didPresentSelector:contextInfo:","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Presents an error alert to the user as a modal panel.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentError","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"modalFor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"didPresent","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"contextInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDocument/presentError(_:modalFor:delegate:didPresent:contextInfo:)"},"doc://com.externally.resolved.symbol/s:s5ErrorP":{"abstract":[{"text":"A type representing an error value that can be thrown.","type":"text"}],"url":"/documentation/Swift/Error","kind":"symbol","role":"symbol","title":"Error","identifier":"doc://com.externally.resolved.symbol/s:s5ErrorP","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:s8SendableP","text":"Sendable","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"introducedAt":"10.7","name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"willNotPresentError:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"willNotPresentError:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDocument"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDocument/presentError(_:modalFor:delegate:didPresent:contextInfo:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/presentError(_:)","doc://com.apple.appkit/documentation/AppKit/NSDocument/willPresentError(_:)"],"anchor":"Displaying-Errors-to-the-User","title":"Displaying Errors to the User"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"willNotPresentError:"},{"kind":"text","text":"("},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/nserror"},{"type":"text","text":" object returned by another "},{"code":"NSDocument","type":"codeVoice"},{"type":"text","text":" method."}]}],"name":"error"}]},"path":"/primaryContentSections/1"},{"value":"willPresentError:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1willPresentError(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"willPresentError:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1willPresentError(_:)/fragments"},{"value":"savePresentedItemChangesWithCompletionHandler:","op":"replace","path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsfilepresenter~11414407-savepresenteditemchanges/title"},{"value":"willNotPresentError:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1willNotPresentError(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"willNotPresentError:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1willNotPresentError(_:)/fragments"},{"value":"presentError:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1presentError(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"presentError:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1presentError(_:)/fragments"},{"value":"NSDocument","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/title"},{"value":[{"text":"NSDocument","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/fragments"},{"value":[{"text":"NSDocument","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/navigatorTitle"},{"value":"autosaveWithImplicitCancellability:completionHandler:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1autosave(withImplicitCancellability:completionHandler:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"autosaveWithImplicitCancellability:completionHandler:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1autosave(withImplicitCancellability:completionHandler:)/fragments"},{"value":"presentError:modalForWindow:delegate:didPresentSelector:contextInfo:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1presentError(_:modalFor:delegate:didPresent:contextInfo:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentError:modalForWindow:delegate:didPresentSelector:contextInfo:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1presentError(_:modalFor:delegate:didPresent:contextInfo:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}