{
  "abstract": [
    {
      "text": "This method is called by action methods to save document contents to a file.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/writeSafely(to:ofType:for:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDocument/writeWithBackupToFile:ofType:saveOperation:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSDocument(im)writeWithBackupToFile:ofType:saveOperation:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "writeWithBackupToFile:ofType:saveOperation:"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "writeWithBackupToFile:ofType:saveOperation:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.4",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "writeWithBackupToFile:ofType:saveOperation:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "writeWithBackupToFile:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "fullDocumentPath"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ofType:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "documentTypeName"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "saveOperation:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/SaveOperationType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSSaveOperationType",
              "text": "NSSaveOperationType"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "saveOperationType"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is called by action methods like ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/save(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveAs(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveTo(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". It is responsible for handling backup of the existing file, if any, and removal of that backup if ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/keepBackupFile",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " returns ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". In between those two things, it calls ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/writeToFile:ofType:originalFile:saveOperation:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to write the document of type ",
              "type": "text"
            },
            {
              "code": "docType",
              "type": "codeVoice"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "code": "fullDocumentPath",
              "type": "codeVoice"
            },
            {
              "text": ". You should never need to call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/writeWithBackupToFile:ofType:saveOperation:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", but subclasses that want to change the way the backup works can override it. The ",
              "type": "text"
            },
            {
              "code": "saveOperationType",
              "type": "codeVoice"
            },
            {
              "text": " argument is one of the constants listed in ",
              "type": "text"
            },
            {
              "code": "Constants",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you override this method, you should invoke ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileAttributesToWriteToFile:ofType:saveOperation:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and set the variables returned from this method when writing ",
              "type": "text"
            },
            {
              "code": "fullDocumentPath",
              "type": "codeVoice"
            },
            {
              "text": ". ",
              "type": "text"
            },
            {
              "code": "NSFileManager",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilemanager/1557001-changefileattributes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " can be used to do this.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument": {
      "abstract": [
        {
          "text": "An abstract class that defines the interface for macOS documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDocument"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDocument"
        }
      ],
      "role": "symbol",
      "title": "NSDocument",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/SaveOperationType": {
      "abstract": [
        {
          "text": "Constants for specifying the type of document-save operation to perform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SaveOperationType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/SaveOperationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SaveOperationType"
        }
      ],
      "role": "symbol",
      "title": "NSDocument.SaveOperationType",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/saveoperationtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/dataRepresentationOfType:": {
      "abstract": [
        {
          "text": "A primitive method to return a data object that represents the data of the receiver in a given type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "dataRepresentationOfType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/dataRepresentationOfType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataRepresentationOfType:"
        }
      ],
      "role": "symbol",
      "title": "dataRepresentationOfType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/datarepresentationoftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileAttributesToWriteToFile:ofType:saveOperation:": {
      "abstract": [
        {
          "text": "Returns the file attributes that should be written to the named document file of the specified type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "fileAttributesToWriteToFile:ofType:saveOperation:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileAttributesToWriteToFile:ofType:saveOperation:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileAttributesToWriteToFile:ofType:saveOperation:"
        }
      ],
      "role": "symbol",
      "title": "fileAttributesToWriteToFile:ofType:saveOperation:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/fileattributestowritetofile:oftype:saveoperation:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileName": {
      "abstract": [
        {
          "text": "Returns the fully qualified pathname under which the receiver has been saved.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "fileName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileName"
        }
      ],
      "role": "symbol",
      "title": "fileName",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/filename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileWrapperRepresentationOfType:": {
      "abstract": [
        {
          "text": "Returns a file wrapper object that represents the data of the receiver in a given type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "fileWrapperRepresentationOfType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileWrapperRepresentationOfType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileWrapperRepresentationOfType:"
        }
      ],
      "role": "symbol",
      "title": "fileWrapperRepresentationOfType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/filewrapperrepresentationoftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfFile:ofType:": {
      "abstract": [
        {
          "text": "Initializes and returns a document object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithContentsOfFile:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfFile:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithContentsOfFile:ofType:"
        }
      ],
      "role": "symbol",
      "title": "initWithContentsOfFile:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/initwithcontentsoffile:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfURL:ofType:": {
      "abstract": [
        {
          "text": "Initializes and returns a document object of a given type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithContentsOfURL:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfURL:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithContentsOfURL:ofType:"
        }
      ],
      "role": "symbol",
      "title": "initWithContentsOfURL:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/initwithcontentsofurl:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/keepBackupFile": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the document archives previously saved versions of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keepBackupFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/keepBackupFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keepBackupFile"
        }
      ],
      "role": "symbol",
      "title": "keepBackupFile",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/keepbackupfile"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/loadDataRepresentation:ofType:": {
      "abstract": [
        {
          "text": "Loads the document data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "loadDataRepresentation:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/loadDataRepresentation:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadDataRepresentation:ofType:"
        }
      ],
      "role": "symbol",
      "title": "loadDataRepresentation:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/loaddatarepresentation:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/loadFileWrapperRepresentation:ofType:": {
      "abstract": [
        {
          "text": "Loads document data from a given file wrapper.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "loadFileWrapperRepresentation:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/loadFileWrapperRepresentation:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadFileWrapperRepresentation:ofType:"
        }
      ],
      "role": "symbol",
      "title": "loadFileWrapperRepresentation:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/loadfilewrapperrepresentation:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/printShowingPrintPanel:": {
      "abstract": [
        {
          "text": "Prints the current document’s data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "printShowingPrintPanel:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/printShowingPrintPanel:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printShowingPrintPanel:"
        }
      ],
      "role": "symbol",
      "title": "printShowingPrintPanel:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/printshowingprintpanel:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromFile:ofType:": {
      "abstract": [
        {
          "text": "Reads and loads document data of the given type from the given file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "readFromFile:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromFile:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readFromFile:ofType:"
        }
      ],
      "role": "symbol",
      "title": "readFromFile:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/readfromfile:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromURL:ofType:": {
      "abstract": [
        {
          "text": "Reads and loads document data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "readFromURL:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromURL:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readFromURL:ofType:"
        }
      ],
      "role": "symbol",
      "title": "readFromURL:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/readfromurl:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromFile:ofType:": {
      "abstract": [
        {
          "text": "Reverts the receiver to the data stored in the file system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "revertToSavedFromFile:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromFile:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "revertToSavedFromFile:ofType:"
        }
      ],
      "role": "symbol",
      "title": "revertToSavedFromFile:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/reverttosavedfromfile:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromURL:ofType:": {
      "abstract": [
        {
          "text": "Reverts the receiver.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "revertToSavedFromURL:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromURL:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "revertToSavedFromURL:ofType:"
        }
      ],
      "role": "symbol",
      "title": "revertToSavedFromURL:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/reverttosavedfromurl:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayoutWithPrintInfo:": {
      "abstract": [
        {
          "text": "Runs the page layout modal panel with the receiver’s printing information object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "runModalPageLayoutWithPrintInfo:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayoutWithPrintInfo:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModalPageLayoutWithPrintInfo:"
        }
      ],
      "role": "symbol",
      "title": "runModalPageLayoutWithPrintInfo:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/runmodalpagelayoutwithprintinfo:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/save(_:)": {
      "abstract": [
        {
          "text": "The action method invoked in the receiver as first responder when the user chooses the Save menu command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "save"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/save(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveDocument:"
        }
      ],
      "role": "symbol",
      "title": "save(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/save(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveAs(_:)": {
      "abstract": [
        {
          "text": "The action method invoked in the receiver as first responder when the user chooses the Save As menu command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saveAs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveAs(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveDocumentAs:"
        }
      ],
      "role": "symbol",
      "title": "saveAs(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/saveas(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveTo(_:)": {
      "abstract": [
        {
          "text": "The action method invoked in the receiver as first responder when the user chooses the Save To menu command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saveTo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveTo(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveDocumentTo:"
        }
      ],
      "role": "symbol",
      "title": "saveTo(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/saveto(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:": {
      "abstract": [
        {
          "text": "Called after the user has been given the opportunity to select a destination through the modal Save panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:"
        }
      ],
      "role": "symbol",
      "title": "saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/savetofile:saveoperation:delegate:didsaveselector:contextinfo:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/writeSafely(to:ofType:for:)": {
      "abstract": [
        {
          "text": "Writes the contents of the document to a file or file package located by a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeSafely"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDocument",
          "text": "NSDocument"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSaveOperationType",
          "text": "SaveOperationType"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/writeSafely(to:ofType:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeSafelyToURL:ofType:forSaveOperation:error:"
        }
      ],
      "role": "symbol",
      "title": "writeSafely(to:ofType:for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/writesafely(to:oftype:for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/writeToFile:ofType:originalFile:saveOperation:": {
      "abstract": [
        {
          "text": "Writes the receiver document’s contents to a file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "writeToFile:ofType:originalFile:saveOperation:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/writeToFile:ofType:originalFile:saveOperation:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeToFile:ofType:originalFile:saveOperation:"
        }
      ],
      "role": "symbol",
      "title": "writeToFile:ofType:originalFile:saveOperation:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/writetofile:oftype:originalfile:saveoperation:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/writeWithBackupToFile:ofType:saveOperation:": {
      "abstract": [
        {
          "text": "This method is called by action methods to save document contents to a file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "writeWithBackupToFile:ofType:saveOperation:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/writeWithBackupToFile:ofType:saveOperation:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeWithBackupToFile:ofType:saveOperation:"
        }
      ],
      "role": "symbol",
      "title": "writeWithBackupToFile:ofType:saveOperation:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/writewithbackuptofile:oftype:saveoperation:"
    },
    "doc://com.apple.documentation/documentation/foundation/nsfilemanager/1557001-changefileattributes": {
      "abstract": [
        {
          "text": "Changes the attributes of a given file or directory. ",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilemanager/1557001-changefileattributes",
      "kind": "symbol",
      "role": "symbol",
      "title": "changeFileAttributes:atPath:",
      "type": "topic",
      "url": "/documentation/foundation/nsfilemanager/1557001-changefileattributes"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/dataRepresentationOfType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileAttributesToWriteToFile:ofType:saveOperation:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileName",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/fileWrapperRepresentationOfType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfFile:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfURL:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/loadDataRepresentation:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/loadFileWrapperRepresentation:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/printShowingPrintPanel:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromFile:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/readFromURL:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromFile:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/revertToSavedFromURL:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/runModalPageLayoutWithPrintInfo:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocument/saveToFile:saveOperation:delegate:didSaveSelector:contextInfo:"
      ],
      "title": "Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1writeSafely(to:ofType:for:)/title",
          "value": "writeSafelyToURL:ofType:forSaveOperation:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1writeSafely(to:ofType:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeSafelyToURL:ofType:forSaveOperation:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1keepBackupFile/title",
          "value": "keepBackupFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1keepBackupFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keepBackupFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/title",
          "value": "NSDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1saveTo(_:)/title",
          "value": "saveDocumentTo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1saveTo(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveDocumentTo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1save(_:)/title",
          "value": "saveDocument:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1save(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveDocument:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1SaveOperationType/title",
          "value": "NSSaveOperationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1SaveOperationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSaveOperationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1SaveOperationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSaveOperationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1saveAs(_:)/title",
          "value": "saveDocumentAs:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1saveAs(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveDocumentAs:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    },
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsfilemanager~11557001-changefileattributes/title",
          "value": "changeFileAttributes(_:atPath:)"
        },
        {
          "op": "add",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsfilemanager~11557001-changefileattributes/fragments",
          "value": [
            {
              "kind": "text",
              "text": "func "
            },
            {
              "kind": "identifier",
              "text": "changeFileAttributes"
            },
            {
              "kind": "text",
              "text": "([AnyHashable : Any], "
            },
            {
              "kind": "identifier",
              "text": "atPath"
            },
            {
              "kind": "text",
              "text": ": String) -> Bool"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdocument/writewithbackuptofile:oftype:saveoperation:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
