{
  "abstract": [
    {
      "text": "Creates a new UDP session over the network associated with the command.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Pass the Swift ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommand/interface-46dq",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property or the ObjectiveC ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommand/interface-7rt15",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/Network/nw_parameters_require_interface(_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "function from the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/Network",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " framework instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommand"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommand/createUDPSession(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NEHotspotHelperCommand(im)createUDPSession:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "createUDPSession"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NWEndpoint",
        "text": "NWEndpoint"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NWUDPSession",
        "text": "NWUDPSession"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "createUDPSession:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.0",
        "message": "Use the `interface` property with `nw_parameters_require_interface`",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.0",
        "message": "Use the `interface` property with `nw_parameters_require_interface`",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.1",
        "message": "Use the `interface` property with `nw_parameters_require_interface`",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "message": "Use the `interface` property with `nw_parameters_require_interface`",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "createUDPSession(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "createUDPSession"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "endpoint"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWEndpoint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NWEndpoint",
              "text": "NWEndpoint"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSession",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NWUDPSession",
              "text": "NWUDPSession"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The remote host and port of the session.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "endpoint"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A UDP session that will connect over the network associated with the command.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The UDP session is started automatically. Use KVO to observe the session’s state property to be notified when the session is ready to send and receive UDP datagrams. For information about KVO see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/KeyValueObserving/KeyValueObserving.html#//apple_ref/doc/uid/10000177i",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/Network"
    },
    "doc://com.apple.documentation/documentation/Network/nw_parameters_require_interface(_:_:)": {
      "abstract": [
        {
          "text": "Sets a specific interface to require on connections, listeners, and browsers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_parameters_require_interface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "parameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_parameters_t",
          "text": "nw_parameters_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "interface"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@nw_interface_t",
          "text": "nw_interface_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Network/nw_parameters_require_interface(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "nw_parameters_require_interface(_:_:)",
      "type": "topic",
      "url": "/documentation/Network/nw_parameters_require_interface(_:_:)"
    },
    "doc://com.apple.documentation/documentation/foundation/nsmutableurlrequest/1619006-bind": {
      "abstract": [
        {
          "text": "Binds a URL request to the network interface associated with the hotspot helper command instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "bind"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": NEHotspotHelperCommand)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsmutableurlrequest/1619006-bind",
      "kind": "symbol",
      "role": "symbol",
      "title": "bind(to:)",
      "type": "topic",
      "url": "/documentation/foundation/nsmutableurlrequest/1619006-bind"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommand": {
      "abstract": [
        {
          "text": "A command for the hotspot helper to handle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEHotspotHelperCommand"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotHelperCommand"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperCommand",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelpercommand"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommand/createTCPConnection(_:)": {
      "abstract": [
        {
          "text": "Create a new TCP connection over the network associated with the command.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createTCPConnection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NWEndpoint",
          "text": "NWEndpoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NWTCPConnection",
          "text": "NWTCPConnection"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommand/createTCPConnection(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createTCPConnection:"
        }
      ],
      "role": "symbol",
      "title": "createTCPConnection(_:)",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelpercommand/createtcpconnection(_:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommand/createUDPSession(_:)": {
      "abstract": [
        {
          "text": "Creates a new UDP session over the network associated with the command.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createUDPSession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NWEndpoint",
          "text": "NWEndpoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NWUDPSession",
          "text": "NWUDPSession"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommand/createUDPSession(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createUDPSession:"
        }
      ],
      "role": "symbol",
      "title": "createUDPSession(_:)",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelpercommand/createudpsession(_:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommand/interface-46dq": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interface"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Network11NWInterfaceV",
          "text": "NWInterface"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommand/interface-46dq",
      "kind": "symbol",
      "role": "symbol",
      "title": "interface",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelpercommand/interface-46dq"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommand/interface-7rt15": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "interface"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommand/interface-7rt15",
      "kind": "symbol",
      "role": "symbol",
      "title": "interface",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelpercommand/interface-7rt15"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWBonjourServiceEndpoint": {
      "abstract": [
        {
          "text": "A network endpoint specified as a Bonjour service name, type, and domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NWBonjourServiceEndpoint"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWBonjourServiceEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWBonjourServiceEndpoint"
        }
      ],
      "role": "symbol",
      "title": "NWBonjourServiceEndpoint",
      "type": "topic",
      "url": "/documentation/networkextension/nwbonjourserviceendpoint"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWEndpoint": {
      "abstract": [
        {
          "text": "An abstract base class, shared by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWHostEndpoint",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWBonjourServiceEndpoint",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", that represents the source or destination of a network connection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NWEndpoint"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWEndpoint"
        }
      ],
      "role": "symbol",
      "title": "NWEndpoint",
      "type": "topic",
      "url": "/documentation/networkextension/nwendpoint"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWHostEndpoint": {
      "abstract": [
        {
          "text": "A network endpoint specified by DNS name (or IP address) and port.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NWHostEndpoint"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWHostEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWHostEndpoint"
        }
      ],
      "role": "symbol",
      "title": "NWHostEndpoint",
      "type": "topic",
      "url": "/documentation/networkextension/nwhostendpoint"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSession": {
      "abstract": [
        {
          "text": "An object to manage a UDP session to a network endpoint.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NWUDPSession"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWUDPSession"
        }
      ],
      "role": "symbol",
      "title": "NWUDPSession",
      "type": "topic",
      "url": "/documentation/networkextension/nwudpsession"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/KeyValueObserving/KeyValueObserving.html#//apple_ref/doc/uid/10000177i": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/KeyValueObserving/KeyValueObserving.html#//apple_ref/doc/uid/10000177i",
      "title": "Key-Value Observing Programming Guide",
      "titleInlineContent": [
        {
          "text": "Key-Value Observing Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/KeyValueObserving/KeyValueObserving.html#//apple_ref/doc/uid/10000177i"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Networking-on-the-hotspot-network",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsmutableurlrequest/1619006-bind",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommand/createTCPConnection(_:)"
      ],
      "title": "Networking on the hotspot network"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "createUDPSession:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "createUDPSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommand"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Networking-on-the-hotspot-network",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/foundation/nsmutableurlrequest/1619006-bind",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommand/createTCPConnection(_:)"
              ],
              "title": "Networking on the hotspot network"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSession",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NWUDPSession",
                    "text": "NWUDPSession"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "createUDPSession:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWEndpoint",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NWEndpoint",
                    "text": "NWEndpoint"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "endpoint"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The remote host and port of the session.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "endpoint"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A UDP session that will connect over the network associated with the command.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Pass the Swift ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommand/interface-46dq",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property or the ObjectiveC ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommand/interface-7rt15",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "to the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Network/nw_parameters_require_interface(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "function from the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Network",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " framework instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommand~1createUDPSession(_:)/title",
          "value": "createUDPSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommand~1createUDPSession(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "createUDPSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWBonjourServiceEndpoint/title",
          "value": "NWBonjourServiceEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWBonjourServiceEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWBonjourServiceEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWBonjourServiceEndpoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NWBonjourServiceEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWEndpoint/title",
          "value": "NWEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWEndpoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NWEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommand~1createTCPConnection(_:)/title",
          "value": "createTCPConnection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommand~1createTCPConnection(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "createTCPConnection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsmutableurlrequest~11619006-bind/title",
          "value": "bindToHotspotHelperCommand:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWUDPSession/title",
          "value": "NWUDPSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWUDPSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWUDPSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWUDPSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NWUDPSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommand/title",
          "value": "NEHotspotHelperCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotHelperCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotHelperCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWHostEndpoint/title",
          "value": "NWHostEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWHostEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWHostEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWHostEndpoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NWHostEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Network~1nw_parameters_require_interface(_:_:)/title",
          "value": "nw_parameters_require_interface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Network~1nw_parameters_require_interface(_:_:)/fragments",
          "value": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nw_parameters_require_interface"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_parameters_t",
              "text": "nw_parameters_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "parameters"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@nw_interface_t",
              "text": "nw_interface_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "interface"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nehotspothelpercommand/createudpsession(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nehotspothelpercommand/createudpsession(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
