{
  "abstract": [
    {
      "text": "Constants indicating the type of action being performed on an item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UICollectionUpdateAction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Action"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Action"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UICollectionViewUpdateItem.Action"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Action"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem": {
      "abstract": [
        {
          "text": "An object that describes a single change to make to an item in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewUpdateItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewUpdateItem"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewUpdateItem",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewupdateitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action": {
      "abstract": [
        {
          "text": "Constants indicating the type of action being performed on an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Action"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Action"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewUpdateItem.Action",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewupdateitem/action"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/delete": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delete"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/delete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionUpdateActionDelete"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewUpdateItem.Action.delete",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewupdateitem/action/delete"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewupdateitem/action/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/insert": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insert"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/insert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionUpdateActionInsert"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewUpdateItem.Action.insert",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewupdateitem/action/insert"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/move": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "move"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/move",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionUpdateActionMove"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewUpdateItem.Action.move",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewupdateitem/action/move"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/none": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionUpdateActionNone"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewUpdateItem.Action.none",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewupdateitem/action/none"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/reload": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reload"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/reload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionUpdateActionReload"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewUpdateItem.Action.reload",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewupdateitem/action/reload"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/indexPathAfterUpdate": {
      "abstract": [
        {
          "text": "The index path of the item after the update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexPathAfterUpdate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/indexPathAfterUpdate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexPathAfterUpdate"
        }
      ],
      "role": "symbol",
      "title": "indexPathAfterUpdate",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewupdateitem/indexpathafterupdate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/indexPathBeforeUpdate": {
      "abstract": [
        {
          "text": "The index path of the item before the update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexPathBeforeUpdate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/indexPathBeforeUpdate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexPathBeforeUpdate"
        }
      ],
      "role": "symbol",
      "title": "indexPathBeforeUpdate",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewupdateitem/indexpathbeforeupdate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/updateAction": {
      "abstract": [
        {
          "text": "The action being performed on the item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionViewUpdateItem",
          "text": "UICollectionViewUpdateItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UICollectionUpdateAction",
          "text": "Action"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/updateAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateAction"
        }
      ],
      "role": "symbol",
      "title": "updateAction",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewupdateitem/updateaction"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-the-item-changes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/indexPathBeforeUpdate",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/indexPathAfterUpdate",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/updateAction"
      ],
      "title": "Accessing the item changes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/none",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/insert",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/delete",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/reload",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/move"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UICollectionUpdateAction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionUpdateAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionUpdateAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/none",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/insert",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/delete",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/reload",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/Action/move"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-the-item-changes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/indexPathBeforeUpdate",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/indexPathAfterUpdate",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem/updateAction"
              ],
              "title": "Accessing the item changes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UICollectionUpdateAction"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem~1updateAction/title",
          "value": "updateAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem~1updateAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "updateAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem~1Action~1reload/title",
          "value": "UICollectionUpdateActionReload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem~1Action~1reload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionUpdateActionReload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem~1Action~1delete/title",
          "value": "UICollectionUpdateActionDelete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem~1Action~1delete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionUpdateActionDelete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem~1indexPathAfterUpdate/title",
          "value": "indexPathAfterUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem~1indexPathAfterUpdate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "indexPathAfterUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem~1Action~1none/title",
          "value": "UICollectionUpdateActionNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem~1Action~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionUpdateActionNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem~1Action~1insert/title",
          "value": "UICollectionUpdateActionInsert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem~1Action~1insert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionUpdateActionInsert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem~1Action/title",
          "value": "UICollectionUpdateAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem~1Action/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionUpdateAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem~1Action/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionUpdateAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem~1indexPathBeforeUpdate/title",
          "value": "indexPathBeforeUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem~1indexPathBeforeUpdate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "indexPathBeforeUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem/title",
          "value": "UICollectionViewUpdateItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewUpdateItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewUpdateItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem~1Action~1move/title",
          "value": "UICollectionUpdateActionMove"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem~1Action~1move/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionUpdateActionMove"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicollectionviewupdateitem/action"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uicollectionviewupdateitem/action"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
