{
  "diffAvailability": {
    "beta": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowParameters"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowParameters/init(sourceFrame:nextFrame:submissionMode:destinationOpticalFlow:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VTOpticalFlowParameters(im)initWithSourceFrame:nextFrame:submissionMode:destinationOpticalFlow:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "?("
      },
      {
        "kind": "externalParam",
        "text": "sourceFrame"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)VTFrameProcessorFrame",
        "text": "VTFrameProcessorFrame"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "nextFrame"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)VTFrameProcessorFrame",
        "text": "VTFrameProcessorFrame"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "submissionMode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)VTOpticalFlowParameters",
        "text": "VTOpticalFlowParameters"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@VTOpticalFlowParametersSubmissionMode",
        "text": "SubmissionMode"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "destinationOpticalFlow"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)VTFrameProcessorOpticalFlow",
        "text": "VTFrameProcessorOpticalFlow"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithSourceFrame:nextFrame:submissionMode:destinationOpticalFlow:"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(sourceFrame:nextFrame:submissionMode:destinationOpticalFlow:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "?("
            },
            {
              "kind": "externalParam",
              "text": "sourceFrame"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorFrame",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)VTFrameProcessorFrame",
              "text": "VTFrameProcessorFrame"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "nextFrame"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorFrame",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)VTFrameProcessorFrame",
              "text": "VTFrameProcessorFrame"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "submissionMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowParameters",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)VTOpticalFlowParameters",
              "text": "VTOpticalFlowParameters"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowParameters/SubmissionMode-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@VTOpticalFlowParametersSubmissionMode",
              "text": "SubmissionMode"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "destinationOpticalFlow"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorOpticalFlow",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)VTFrameProcessorOpticalFlow",
              "text": "VTFrameProcessorOpticalFlow"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Current source frame. Must be non nil.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sourceFrame"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Next source frame in presentation time order.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "nextFrame"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Set to VTOpticalFlowParametersSubmissionModeSequential to indicate that current submission follow presentation time order without jump or skip when compared to previous submission. VTOpticalFlowParametersSubmissionModeSequential will yield better performance. Set to  VTOpticalFlowParametersSubmissionModeRandom to indicate a skip or a jump in frame sequence. If VTOpticalFlowParametersSubmissionModeRandom is set internal cache will be cleared during processWithParameters call.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "submissionMode"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "User allocated VTFrameProcessorMutableOpticalFlow that will receive the results.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "destinationOpticalFlow"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Init will return nil if sourceFrame or nextFrame is nil, or sourceFrame and nextFrame are different pixelFormats..",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorFrame": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTFrameProcessorFrame"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorFrame"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorFrame",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorframe"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorOpticalFlow": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTFrameProcessorOpticalFlow"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorOpticalFlow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorOpticalFlow"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorOpticalFlow",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessoropticalflow"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowParameters": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTOpticalFlowParameters"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTOpticalFlowParameters"
        }
      ],
      "role": "symbol",
      "title": "VTOpticalFlowParameters",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtopticalflowparameters"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowParameters/SubmissionMode-swift.enum": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SubmissionMode"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowParameters/SubmissionMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SubmissionMode"
        }
      ],
      "role": "symbol",
      "title": "VTOpticalFlowParameters.SubmissionMode",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtopticalflowparameters/submissionmode-swift.enum"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowParameters/init(sourceFrame:nextFrame:submissionMode:destinationOpticalFlow:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "sourceFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VTFrameProcessorFrame",
          "text": "VTFrameProcessorFrame"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "nextFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VTFrameProcessorFrame",
          "text": "VTFrameProcessorFrame"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "submissionMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VTOpticalFlowParameters",
          "text": "VTOpticalFlowParameters"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VTOpticalFlowParametersSubmissionMode",
          "text": "SubmissionMode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "destinationOpticalFlow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VTFrameProcessorOpticalFlow",
          "text": "VTFrameProcessorOpticalFlow"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowParameters/init(sourceFrame:nextFrame:submissionMode:destinationOpticalFlow:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSourceFrame:nextFrame:submissionMode:destinationOpticalFlow:"
        }
      ],
      "role": "symbol",
      "title": "init(sourceFrame:nextFrame:submissionMode:destinationOpticalFlow:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtopticalflowparameters/init(sourceframe:nextframe:submissionmode:destinationopticalflow:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithSourceFrame:nextFrame:submissionMode:destinationOpticalFlow:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSourceFrame:nextFrame:submissionMode:destinationOpticalFlow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowParameters"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithSourceFrame:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorFrame",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VTFrameProcessorFrame",
                    "text": "VTFrameProcessorFrame"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "sourceFrame"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "nextFrame:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorFrame",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VTFrameProcessorFrame",
                    "text": "VTFrameProcessorFrame"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "nextFrame"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "submissionMode:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTOpticalFlowParameters/SubmissionMode-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@VTOpticalFlowParametersSubmissionMode",
                    "text": "VTOpticalFlowParametersSubmissionMode"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "submissionMode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "destinationOpticalFlow:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorOpticalFlow",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VTFrameProcessorOpticalFlow",
                    "text": "VTFrameProcessorOpticalFlow"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "destinationOpticalFlow"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Current source frame. Must be non nil.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "sourceFrame"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Next source frame in presentation time order.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "nextFrame"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Set to VTOpticalFlowParametersSubmissionModeSequential to indicate that current submission follow presentation time order without jump or skip when compared to previous submission. VTOpticalFlowParametersSubmissionModeSequential will yield better performance. Set to  VTOpticalFlowParametersSubmissionModeRandom to indicate a skip or a jump in frame sequence. If VTOpticalFlowParametersSubmissionModeRandom is set internal cache will be cleared during processWithParameters call.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "submissionMode"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "User allocated VTFrameProcessorMutableOpticalFlow that will receive the results.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "destinationOpticalFlow"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowParameters~1init(sourceFrame:nextFrame:submissionMode:destinationOpticalFlow:)/title",
          "value": "initWithSourceFrame:nextFrame:submissionMode:destinationOpticalFlow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowParameters~1init(sourceFrame:nextFrame:submissionMode:destinationOpticalFlow:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSourceFrame:nextFrame:submissionMode:destinationOpticalFlow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowParameters~1SubmissionMode-swift.enum/title",
          "value": "VTOpticalFlowParametersSubmissionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowParameters~1SubmissionMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTOpticalFlowParametersSubmissionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowParameters~1SubmissionMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTOpticalFlowParametersSubmissionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorFrame/title",
          "value": "VTFrameProcessorFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorFrame/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorOpticalFlow/title",
          "value": "VTFrameProcessorOpticalFlow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorOpticalFlow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorOpticalFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorOpticalFlow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorOpticalFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowParameters/title",
          "value": "VTOpticalFlowParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTOpticalFlowParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTOpticalFlowParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTOpticalFlowParameters"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vtopticalflowparameters/init(sourceframe:nextframe:submissionmode:destinationopticalflow:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/vtopticalflowparameters/init(sourceframe:nextframe:submissionmode:destinationopticalflow:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
