{
  "abstract": [
    {
      "text": "Adds an indefinite symbol effect to the image view with the specified options and animation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect(_:options:animated:completion:)-896qd"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "s:So11UIImageViewC5UIKitE15addSymbolEffect_7options8animated10completionyx_7Symbols0eF7OptionsVSbyAC08UISymbolF17CompletionContextVcSgtAH08DiscreteeF0RzAH0eF0RzlF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "addSymbolEffect"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "keyword",
        "text": "some"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7Symbols20DiscreteSymbolEffectP",
        "text": "DiscreteSymbolEffect"
      },
      {
        "kind": "text",
        "text": " & "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7Symbols12SymbolEffectP",
        "text": "SymbolEffect"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "options"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
        "text": "SymbolEffectOptions"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "animated"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "completion"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:5UIKit24UISymbolEffectCompletiona",
        "text": "UISymbolEffectCompletion"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "addSymbolEffect(_:options:animated:completion:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@preconcurrency"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "addSymbolEffect"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "effect"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "some"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:7Symbols20DiscreteSymbolEffectP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7Symbols20DiscreteSymbolEffectP",
              "text": "DiscreteSymbolEffect"
            },
            {
              "kind": "text",
              "text": " & "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:7Symbols12SymbolEffectP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7Symbols12SymbolEffectP",
              "text": "SymbolEffect"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:7Symbols19SymbolEffectOptionsV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
              "text": "SymbolEffectOptions"
            },
            {
              "kind": "text",
              "text": " = .default, "
            },
            {
              "kind": "externalParam",
              "text": "animated"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " = true, "
            },
            {
              "kind": "externalParam",
              "text": "completion"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISymbolEffectCompletion-7qt7g",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit24UISymbolEffectCompletiona",
              "text": "UISymbolEffectCompletion"
            },
            {
              "kind": "text",
              "text": "? = nil)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The symbol effect to add.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "effect"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The options for the symbol effect.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "options"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A Boolean value that indicates whether to animate the addition of a scale, appear, or disappear effect.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "animated"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A completion handler the system calls after the effect’s addition is complete.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "completion"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView": {
      "abstract": [
        {
          "text": "A view that displays a single image or a sequence of animated images in your interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImageView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageView"
        }
      ],
      "role": "symbol",
      "title": "UIImageView",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect(_:options:animated:completion:)-18jqj": {
      "abstract": [
        {
          "text": "Adds a discrete symbol effect to the image view with the specified options and animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols22IndefiniteSymbolEffectP",
          "text": "IndefiniteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit24UISymbolEffectCompletiona",
          "text": "UISymbolEffectCompletion"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect(_:options:animated:completion:)-18jqj",
      "kind": "symbol",
      "role": "symbol",
      "title": "addSymbolEffect(_:options:animated:completion:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/addsymboleffect(_:options:animated:completion:)-18jqj"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect(_:options:animated:completion:)-2ixnm": {
      "abstract": [
        {
          "text": "Adds a discrete, indefinite symbol effect to the image view with the specified options and animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols20DiscreteSymbolEffectP",
          "text": "DiscreteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols22IndefiniteSymbolEffectP",
          "text": "IndefiniteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit24UISymbolEffectCompletiona",
          "text": "UISymbolEffectCompletion"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect(_:options:animated:completion:)-2ixnm",
      "kind": "symbol",
      "role": "symbol",
      "title": "addSymbolEffect(_:options:animated:completion:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/addsymboleffect(_:options:animated:completion:)-2ixnm"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect(_:options:animated:completion:)-896qd": {
      "abstract": [
        {
          "text": "Adds an indefinite symbol effect to the image view with the specified options and animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols20DiscreteSymbolEffectP",
          "text": "DiscreteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit24UISymbolEffectCompletiona",
          "text": "UISymbolEffectCompletion"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect(_:options:animated:completion:)-896qd",
      "kind": "symbol",
      "role": "symbol",
      "title": "addSymbolEffect(_:options:animated:completion:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/addsymboleffect(_:options:animated:completion:)-896qd"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeAllSymbolEffects(options:animated:)": {
      "abstract": [
        {
          "text": "Removes all symbol effects from the image view, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffects"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeAllSymbolEffects(options:animated:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeAllSymbolEffects(options:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/removeallsymboleffects(options:animated:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffect(ofType:options:animated:completion:)-218lh": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified indefinite effect type, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols22IndefiniteSymbolEffectP",
          "text": "IndefiniteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit24UISymbolEffectCompletiona",
          "text": "UISymbolEffectCompletion"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffect(ofType:options:animated:completion:)-218lh",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeSymbolEffect(ofType:options:animated:completion:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/removesymboleffect(oftype:options:animated:completion:)-218lh"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffect(ofType:options:animated:completion:)-2boi2": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified discrete effect type, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols20DiscreteSymbolEffectP",
          "text": "DiscreteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit24UISymbolEffectCompletiona",
          "text": "UISymbolEffectCompletion"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffect(ofType:options:animated:completion:)-2boi2",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeSymbolEffect(ofType:options:animated:completion:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/removesymboleffect(oftype:options:animated:completion:)-2boi2"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffect(ofType:options:animated:completion:)-31zec": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified discrete, indefinite effect type, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols20DiscreteSymbolEffectP",
          "text": "DiscreteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols22IndefiniteSymbolEffectP",
          "text": "IndefiniteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit24UISymbolEffectCompletiona",
          "text": "UISymbolEffectCompletion"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffect(ofType:options:animated:completion:)-31zec",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeSymbolEffect(ofType:options:animated:completion:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/removesymboleffect(oftype:options:animated:completion:)-31zec"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/setSymbolImage(_:contentTransition:options:completion:)": {
      "abstract": [
        {
          "text": "Sets a symbol image using the specified content-transition effect, options, and completion handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setSymbolImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contentTransition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols29ContentTransitionSymbolEffectP",
          "text": "ContentTransitionSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit24UISymbolEffectCompletiona",
          "text": "UISymbolEffectCompletion"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/setSymbolImage(_:contentTransition:options:completion:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setSymbolImage(_:contentTransition:options:completion:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/setsymbolimage(_:contenttransition:options:completion:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISymbolEffectCompletion-7qt7g": {
      "abstract": [
        {
          "text": "A completion handler for adding and removing symbol effects and transitions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISymbolEffectCompletion"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISymbolEffectCompletion-7qt7g",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISymbolEffectCompletion"
        }
      ],
      "role": "symbol",
      "title": "UISymbolEffectCompletion",
      "type": "topic",
      "url": "/documentation/uikit/uisymboleffectcompletion-7qt7g"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISymbolEffectCompletionContext-swift.struct": {
      "abstract": [
        {
          "text": "Information about a symbol effect’s addition or removal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISymbolEffectCompletionContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISymbolEffectCompletionContext-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISymbolEffectCompletionContext"
        }
      ],
      "role": "symbol",
      "title": "UISymbolEffectCompletionContext",
      "type": "topic",
      "url": "/documentation/uikit/uisymboleffectcompletioncontext-swift.struct"
    },
    "doc://com.externally.resolved.symbol/s:7Symbols12SymbolEffectP": {
      "abstract": [
        {
          "text": "A presentation effect that you apply to a symbol-based image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7Symbols12SymbolEffectP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SymbolEffect",
      "type": "topic",
      "url": "/documentation/Symbols/SymbolEffect"
    },
    "doc://com.externally.resolved.symbol/s:7Symbols19SymbolEffectOptionsV": {
      "abstract": [
        {
          "text": "Options that configure how effects apply to symbol-based images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SymbolEffectOptions"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7Symbols19SymbolEffectOptionsV",
      "kind": "symbol",
      "role": "symbol",
      "title": "SymbolEffectOptions",
      "type": "topic",
      "url": "/documentation/Symbols/SymbolEffectOptions"
    },
    "doc://com.externally.resolved.symbol/s:7Symbols20DiscreteSymbolEffectP": {
      "abstract": [
        {
          "text": "An effect that performs a transient animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DiscreteSymbolEffect"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7Symbols20DiscreteSymbolEffectP",
      "kind": "symbol",
      "role": "symbol",
      "title": "DiscreteSymbolEffect",
      "type": "topic",
      "url": "/documentation/Symbols/DiscreteSymbolEffect"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-symbol-effects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect(_:options:animated:completion:)-18jqj",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect(_:options:animated:completion:)-2ixnm",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/setSymbolImage(_:contentTransition:options:completion:)",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffect(ofType:options:animated:completion:)-218lh",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffect(ofType:options:animated:completion:)-31zec",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffect(ofType:options:animated:completion:)-2boi2",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeAllSymbolEffects(options:animated:)",
        "doc://com.apple.uikit/documentation/UIKit/UISymbolEffectCompletion-7qt7g",
        "doc://com.apple.uikit/documentation/UIKit/UISymbolEffectCompletionContext-swift.struct"
      ],
      "title": "Configuring symbol effects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView/title",
          "value": "UIImageView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiimageview/addsymboleffect(_:options:animated:completion:)-896qd"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
