{"seeAlsoSections":[{"title":"Animating a sequence of images","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImageView/animationImages","doc://com.apple.uikit/documentation/UIKit/UIImageView/highlightedAnimationImages","doc://com.apple.uikit/documentation/UIKit/UIImageView/animationRepeatCount","doc://com.apple.uikit/documentation/UIKit/UIImageView/startAnimating()","doc://com.apple.uikit/documentation/UIKit/UIImageView/stopAnimating()","doc://com.apple.uikit/documentation/UIKit/UIImageView/isAnimating"],"anchor":"Animating-a-sequence-of-images"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImageView"]]},"kind":"symbol","sections":[],"abstract":[{"text":"The amount of time it takes to go through one cycle of the images.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animationDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"inlineContent":[{"text":"The time duration is measured in seconds. The default value of this property is ","type":"text"},{"type":"codeVoice","code":"0.0"},{"type":"text","text":", which causes the image view to use a duration equal to the number of images multiplied by 1/30th of a second. Thus, if you had 30 images, the duration would be 1 second."}],"type":"paragraph"}]}],"variants":[{"paths":["/documentation/uikit/uiimageview/animationduration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiimageview/animationduration"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"animationDuration","kind":"identifier"}],"externalID":"c:objc(cs)UIImageView(py)animationDuration","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationDuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"title":"animationDuration","platforms":[{"beta":false,"unavailable":false,"introducedAt":"2.0","deprecated":false,"name":"iOS"},{"beta":false,"unavailable":false,"introducedAt":"2.0","deprecated":false,"name":"iPadOS"},{"beta":false,"unavailable":false,"introducedAt":"13.1","deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"deprecated":false,"beta":false,"name":"tvOS"},{"introducedAt":"1.0","unavailable":false,"deprecated":false,"beta":false,"name":"visionOS"}],"role":"symbol","modules":[{"name":"UIKit"}],"roleHeading":"Instance Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIImageView/animationDuration"},"references":{"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval":{"role":"symbol","kind":"symbol","url":"/documentation/foundation/timeinterval","title":"TimeInterval","identifier":"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval","type":"topic","fragments":[{"text":"typealias ","kind":"text"},{"kind":"identifier","text":"TimeInterval"}],"abstract":[{"type":"text","text":"A number of seconds."}]},"doc://com.apple.uikit/documentation/UIKit/UIImageView/animationDuration":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationDuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"url":"/documentation/uikit/uiimageview/animationduration","navigatorTitle":[{"kind":"identifier","text":"animationDuration"}],"title":"animationDuration","abstract":[{"type":"text","text":"The amount of time it takes to go through one cycle of the images."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImageView/animationDuration"},"doc://com.apple.uikit/documentation/UIKit/UIImage":{"kind":"symbol","role":"symbol","title":"UIImage","navigatorTitle":[{"text":"UIImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImage","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","url":"/documentation/uikit/uiimage","abstract":[{"type":"text","text":"An object that manages image data in your app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImageView/animationRepeatCount":{"title":"animationRepeatCount","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animationRepeatCount"}],"abstract":[{"text":"Specifies the number of times to repeat the animation.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImageView/animationRepeatCount","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationRepeatCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"kind":"symbol","url":"/documentation/uikit/uiimageview/animationrepeatcount"},"doc://com.apple.uikit/documentation/UIKit/UIImageView":{"role":"symbol","url":"/documentation/uikit/uiimageview","navigatorTitle":[{"kind":"identifier","text":"UIImageView"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIImageView"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImageView","abstract":[{"text":"A view that displays a single image or a sequence of animated images in your interface.","type":"text"}],"kind":"symbol","title":"UIImageView","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImageView/startAnimating()":{"url":"/documentation/uikit/uiimageview/startanimating()","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImageView/startAnimating()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startAnimating"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startAnimating","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","title":"startAnimating()","kind":"symbol","abstract":[{"type":"text","text":"Starts animating the images in the receiver."}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImageView/stopAnimating()":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopAnimating"},{"kind":"text","text":"()"}],"url":"/documentation/uikit/uiimageview/stopanimating()","title":"stopAnimating()","navigatorTitle":[{"kind":"identifier","text":"stopAnimating"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImageView/stopAnimating()","abstract":[{"type":"text","text":"Stops animating the images in the receiver."}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImageView/animationImages":{"type":"topic","abstract":[{"type":"text","text":"An array of "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","isActive":true,"type":"reference"},{"text":" objects to use for an animation.","type":"text"}],"kind":"symbol","url":"/documentation/uikit/uiimageview/animationimages","navigatorTitle":[{"kind":"identifier","text":"animationImages"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImageView/animationImages","role":"symbol","title":"animationImages","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationImages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"]?"}]},"doc://com.apple.uikit/documentation/UIKit/UIImageView/isAnimating":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isAnimating","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"/documentation/uikit/uiimageview/isanimating","navigatorTitle":[{"kind":"identifier","text":"animating"}],"title":"isAnimating","abstract":[{"type":"text","text":"Returns a Boolean value indicating whether the animation is running."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImageView/isAnimating"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImageView/highlightedAnimationImages":{"title":"highlightedAnimationImages","kind":"symbol","navigatorTitle":[{"text":"highlightedAnimationImages","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImageView/highlightedAnimationImages","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"highlightedAnimationImages","kind":"identifier"},{"text":": [","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"abstract":[{"text":"An array of ","type":"text"},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","isActive":true},{"text":" objects to use for an animation when the view is highlighted.","type":"text"}],"url":"/documentation/uikit/uiimageview/highlightedanimationimages"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"2.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"2.0"},{"deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1"},{"deprecated":false,"beta":false,"name":"tvOS","unavailable":false},{"deprecated":false,"beta":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0"}],"path":"/metadata/platforms"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"animationDuration","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"animationDuration","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImageView"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImageView/animationImages","doc://com.apple.uikit/documentation/UIKit/UIImageView/highlightedAnimationImages","doc://com.apple.uikit/documentation/UIKit/UIImageView/animationRepeatCount","doc://com.apple.uikit/documentation/UIKit/UIImageView/startAnimating()","doc://com.apple.uikit/documentation/UIKit/UIImageView/stopAnimating()","doc://com.apple.uikit/documentation/UIKit/UIImageView/isAnimating"],"title":"Animating a sequence of images","generated":true,"anchor":"Animating-a-sequence-of-images"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSTimeInterval","identifier":"doc://com.externally.resolved.symbol/c:@T@NSTimeInterval","kind":"typeIdentifier","text":"NSTimeInterval"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationDuration"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"NSTimeInterval","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSTimeInterval/title","op":"replace"},{"value":"animationDuration","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView~1animationDuration/title","op":"replace"},{"value":[{"text":"animationDuration","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView~1animationDuration/fragments","op":"replace"},{"op":"replace","value":"UIImage","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title"},{"op":"replace","value":[{"text":"UIImage","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments"},{"op":"replace","value":[{"text":"UIImage","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle"},{"op":"replace","value":"animationRepeatCount","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView~1animationRepeatCount/title"},{"op":"replace","value":[{"text":"animationRepeatCount","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView~1animationRepeatCount/fragments"},{"op":"replace","value":"UIImageView","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView/title"},{"op":"replace","value":[{"text":"UIImageView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView/fragments"},{"value":[{"kind":"identifier","text":"UIImageView"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView/navigatorTitle"},{"value":"startAnimating","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView~1startAnimating()/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startAnimating"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView~1startAnimating()/fragments"},{"value":"stopAnimating","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView~1stopAnimating()/title"},{"value":[{"text":"- ","kind":"text"},{"text":"stopAnimating","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView~1stopAnimating()/fragments"},{"value":"animationImages","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView~1animationImages/title"},{"value":[{"kind":"identifier","text":"animationImages"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView~1animationImages/fragments"},{"value":"animating","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView~1isAnimating/title"},{"value":[{"text":"animating","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView~1isAnimating/fragments"},{"value":"highlightedAnimationImages","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView~1highlightedAnimationImages/title"},{"value":[{"kind":"identifier","text":"highlightedAnimationImages"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView~1highlightedAnimationImages/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}