{
  "abstract": [
    {
      "text": "Sets a symbol image using the specified content-transition effect and options.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIImageView/setSymbolImage:withContentTransition:options:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIImageView(im)setSymbolImage:withContentTransition:options:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "setSymbolImage:withContentTransition:options:"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setSymbolImage:withContentTransition:options:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setSymbolImage:withContentTransition:options:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "setSymbolImage:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIImage",
              "text": "UIImage"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "symbolImage"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "withContentTransition:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSSymbolContentTransition",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSSymbolContentTransition",
              "text": "NSSymbolContentTransition"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "transition"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "options:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSSymbolEffectOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSSymbolEffectOptions",
              "text": "NSSymbolEffectOptions"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The symbol image to set.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "symbolImage"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The content transition to use when setting the symbol image.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "transition"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The options to use when setting the symbol image.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "options"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage": {
      "abstract": [
        {
          "text": "An object that manages image data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "role": "symbol",
      "title": "UIImage",
      "type": "topic",
      "url": "/documentation/uikit/uiimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView": {
      "abstract": [
        {
          "text": "A view that displays a single image or a sequence of animated images in your interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImageView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageView"
        }
      ],
      "role": "symbol",
      "title": "UIImageView",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect:": {
      "abstract": [
        {
          "text": "Adds a symbol effect to the image view with default options and animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addSymbolEffect:"
        }
      ],
      "role": "symbol",
      "title": "addSymbolEffect:",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/addsymboleffect:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect:options:": {
      "abstract": [
        {
          "text": "Adds a symbol effect to the image view with the specified options and default animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect:options:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addSymbolEffect:options:"
        }
      ],
      "role": "symbol",
      "title": "addSymbolEffect:options:",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/addsymboleffect:options:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect:options:animated:": {
      "abstract": [
        {
          "text": "Adds a symbol effect to the image view with the specified options and animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect:options:animated:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect:options:animated:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addSymbolEffect:options:animated:"
        }
      ],
      "role": "symbol",
      "title": "addSymbolEffect:options:animated:",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/addsymboleffect:options:animated:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect:options:animated:completion:": {
      "abstract": [
        {
          "text": "Adds a symbol effect to the image view with the specified options, animation, and completion handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect:options:animated:completion:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect:options:animated:completion:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addSymbolEffect:options:animated:completion:"
        }
      ],
      "role": "symbol",
      "title": "addSymbolEffect:options:animated:completion:",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/addsymboleffect:options:animated:completion:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeAllSymbolEffects": {
      "abstract": [
        {
          "text": "Removes all symbol effects from the image view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffects"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeAllSymbolEffects",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffects"
        }
      ],
      "role": "symbol",
      "title": "removeAllSymbolEffects",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/removeallsymboleffects"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeAllSymbolEffectsWithOptions:": {
      "abstract": [
        {
          "text": "Removes all symbol effects from the image view, using the specified options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffectsWithOptions:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeAllSymbolEffectsWithOptions:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffectsWithOptions:"
        }
      ],
      "role": "symbol",
      "title": "removeAllSymbolEffectsWithOptions:",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/removeallsymboleffectswithoptions:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeAllSymbolEffectsWithOptions:animated:": {
      "abstract": [
        {
          "text": "Removes all symbol effects from the image view, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffectsWithOptions:animated:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeAllSymbolEffectsWithOptions:animated:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffectsWithOptions:animated:"
        }
      ],
      "role": "symbol",
      "title": "removeAllSymbolEffectsWithOptions:animated:",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/removeallsymboleffectswithoptions:animated:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffectOfType:": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified effect type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffectOfType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:"
        }
      ],
      "role": "symbol",
      "title": "removeSymbolEffectOfType:",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/removesymboleffectoftype:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffectOfType:options:": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified effect type, using the specified options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:options:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffectOfType:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:options:"
        }
      ],
      "role": "symbol",
      "title": "removeSymbolEffectOfType:options:",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/removesymboleffectoftype:options:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffectOfType:options:animated:": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified effect type, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:options:animated:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffectOfType:options:animated:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:options:animated:"
        }
      ],
      "role": "symbol",
      "title": "removeSymbolEffectOfType:options:animated:",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/removesymboleffectoftype:options:animated:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffectOfType:options:animated:completion:": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified effect type, using the specified options, animation setting, and completion handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:options:animated:completion:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffectOfType:options:animated:completion:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:options:animated:completion:"
        }
      ],
      "role": "symbol",
      "title": "removeSymbolEffectOfType:options:animated:completion:",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/removesymboleffectoftype:options:animated:completion:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/setSymbolImage:withContentTransition:": {
      "abstract": [
        {
          "text": "Sets a symbol image using the specified content-transition effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setSymbolImage:withContentTransition:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/setSymbolImage:withContentTransition:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setSymbolImage:withContentTransition:"
        }
      ],
      "role": "symbol",
      "title": "setSymbolImage:withContentTransition:",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/setsymbolimage:withcontenttransition:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/setSymbolImage:withContentTransition:options:": {
      "abstract": [
        {
          "text": "Sets a symbol image using the specified content-transition effect and options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setSymbolImage:withContentTransition:options:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/setSymbolImage:withContentTransition:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setSymbolImage:withContentTransition:options:"
        }
      ],
      "role": "symbol",
      "title": "setSymbolImage:withContentTransition:options:",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/setsymbolimage:withcontenttransition:options:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView/setSymbolImage:withContentTransition:options:completion:": {
      "abstract": [
        {
          "text": "Sets a symbol image using the specified content-transition effect, options, and completion handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setSymbolImage:withContentTransition:options:completion:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView/setSymbolImage:withContentTransition:options:completion:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setSymbolImage:withContentTransition:options:completion:"
        }
      ],
      "role": "symbol",
      "title": "setSymbolImage:withContentTransition:options:completion:",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview/setsymbolimage:withcontenttransition:options:completion:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISymbolEffectCompletion-6rxwa": {
      "abstract": [
        {
          "text": "A completion handler for adding and removing symbol effects and transitions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UISymbolEffectCompletion"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISymbolEffectCompletion-6rxwa",
      "kind": "symbol",
      "role": "symbol",
      "title": "UISymbolEffectCompletion",
      "type": "topic",
      "url": "/documentation/uikit/uisymboleffectcompletion-6rxwa"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISymbolEffectCompletionContext-c.class": {
      "abstract": [
        {
          "text": "Information about a symbol effect’s addition or removal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UISymbolEffectCompletionContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISymbolEffectCompletionContext-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UISymbolEffectCompletionContext",
      "type": "topic",
      "url": "/documentation/uikit/uisymboleffectcompletioncontext-c.class"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSSymbolContentTransition": {
      "abstract": [
        {
          "text": "An abstract base class for transitions you can apply to symbol-based images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "@interface"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSymbolContentTransition"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSObject",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSSymbolContentTransition",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSymbolContentTransition",
      "type": "topic",
      "url": "/documentation/Symbols/NSSymbolContentTransition"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSSymbolEffectOptions": {
      "abstract": [
        {
          "text": "Options that configure how effects apply to symbol-based images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "@interface"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSObject",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSSymbolEffectOptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSymbolEffectOptions",
      "type": "topic",
      "url": "/documentation/Symbols/NSSymbolEffectOptions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-symbol-effects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect:",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect:options:",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect:options:animated:",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/addSymbolEffect:options:animated:completion:",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/setSymbolImage:withContentTransition:",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/setSymbolImage:withContentTransition:options:completion:",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffectOfType:",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffectOfType:options:",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffectOfType:options:animated:",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeSymbolEffectOfType:options:animated:completion:",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeAllSymbolEffects",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeAllSymbolEffectsWithOptions:",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView/removeAllSymbolEffectsWithOptions:animated:",
        "doc://com.apple.uikit/documentation/UIKit/UISymbolEffectCompletion-6rxwa",
        "doc://com.apple.uikit/documentation/UIKit/UISymbolEffectCompletionContext-c.class"
      ],
      "title": "Configuring symbol effects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView/title",
          "value": "UIImageView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title",
          "value": "UIImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiimageview/setsymbolimage:withcontenttransition:options:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
