{
  "abstract": [
    {
      "text": "Constants that control the presentation of the app, typically for fullscreen apps such as games or kiosks.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSApplicationPresentationOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PresentationOptions"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PresentationOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSApplication.PresentationOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PresentationOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "There are restrictions on the combination of presentation options that can be set simultaneously:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideDock",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideDock",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " are mutually exclusive: You may specify one or the other, but not both.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideMenuBar",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideMenuBar",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " are mutually exclusive: You may specify one or the other, but not both.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you specify ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideMenuBar",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", it must be accompanied by ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideDock",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you specify ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideMenuBar",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", it must be accompanied by either ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideDock",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideDock",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you specify any of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableProcessSwitching",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableForceQuit",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableSessionTermination",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableMenuBarTransparency",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", it must be accompanied by either ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideDock",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideDock",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideToolbar",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " may be used only when both ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/fullScreen",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideMenuBar",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " are also set.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "When ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " receives a parameter value that does not conform to these requirements, it raises an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsexceptionname/1415426-invalidargumentexception",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication": {
      "abstract": [
        {
          "text": "An object that manages an app’s main event loop and resources used by all of that app’s objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSApplication"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplication"
        }
      ],
      "role": "symbol",
      "title": "NSApplication",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct": {
      "abstract": [
        {
          "text": "Constants that control the presentation of the app, typically for fullscreen apps such as games or kiosks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PresentationOptions"
        }
      ],
      "role": "symbol",
      "title": "NSApplication.PresentationOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideDock": {
      "abstract": [
        {
          "text": "The dock is normally hidden, but automatically appears when moused near.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoHideDock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideDock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationAutoHideDock"
        }
      ],
      "role": "symbol",
      "title": "autoHideDock",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/autohidedock"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideMenuBar": {
      "abstract": [
        {
          "text": "The menu bar is normally hidden, but automatically appears when moused near.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoHideMenuBar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideMenuBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationAutoHideMenuBar"
        }
      ],
      "role": "symbol",
      "title": "autoHideMenuBar",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/autohidemenubar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideToolbar": {
      "abstract": [
        {
          "text": "When in fullscreen mode the window toolbar is detached from window and hides and shows with autoHidden menuBar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoHideToolbar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideToolbar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationAutoHideToolbar"
        }
      ],
      "role": "symbol",
      "title": "autoHideToolbar",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/autohidetoolbar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableAppleMenu": {
      "abstract": [
        {
          "text": "All Apple Menu items are disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableAppleMenu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableAppleMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationDisableAppleMenu"
        }
      ],
      "role": "symbol",
      "title": "disableAppleMenu",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/disableapplemenu"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableCursorLocationAssistance": {
      "abstract": [
        {
          "text": "The behavior that allows the user to shake the mouse to locate the cursor is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableCursorLocationAssistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableCursorLocationAssistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationDisableCursorLocationAssistance"
        }
      ],
      "role": "symbol",
      "title": "disableCursorLocationAssistance",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/disablecursorlocationassistance"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableForceQuit": {
      "abstract": [
        {
          "text": "The force quit panel (displayed by pressing Command + Option + Esc) is disabled",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableForceQuit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableForceQuit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationDisableForceQuit"
        }
      ],
      "role": "symbol",
      "title": "disableForceQuit",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/disableforcequit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableHideApplication": {
      "abstract": [
        {
          "text": "The app’s “Hide” menu item is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableHideApplication"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableHideApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationDisableHideApplication"
        }
      ],
      "role": "symbol",
      "title": "disableHideApplication",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/disablehideapplication"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableMenuBarTransparency": {
      "abstract": [
        {
          "text": "The menu bar transparency appearance is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableMenuBarTransparency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableMenuBarTransparency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationDisableMenuBarTransparency"
        }
      ],
      "role": "symbol",
      "title": "disableMenuBarTransparency",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/disablemenubartransparency"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableProcessSwitching": {
      "abstract": [
        {
          "text": "The process switching user interface (Command + Tab to cycle through apps) is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableProcessSwitching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableProcessSwitching",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationDisableProcessSwitching"
        }
      ],
      "role": "symbol",
      "title": "disableProcessSwitching",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/disableprocessswitching"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableSessionTermination": {
      "abstract": [
        {
          "text": "The panel that shows the Restart, Shut Down, and Log Out options that are displayed as a result of pushing the power key is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableSessionTermination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableSessionTermination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationDisableSessionTermination"
        }
      ],
      "role": "symbol",
      "title": "disableSessionTermination",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/disablesessiontermination"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/fullScreen": {
      "abstract": [
        {
          "text": "The app is in fullscreen mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullScreen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/fullScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationFullScreen"
        }
      ],
      "role": "symbol",
      "title": "fullScreen",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/fullscreen"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideDock": {
      "abstract": [
        {
          "text": "The dock is entirely hidden and disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hideDock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideDock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationHideDock"
        }
      ],
      "role": "symbol",
      "title": "hideDock",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/hidedock"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideMenuBar": {
      "abstract": [
        {
          "text": "The menu bar is entirely hidden and disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hideMenuBar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideMenuBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationHideMenuBar"
        }
      ],
      "role": "symbol",
      "title": "hideMenuBar",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/hidemenubar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/init(rawValue:)": {
      "abstract": [
        {
          "text": "Initializes a new presentation options structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/appearance": {
      "abstract": [
        {
          "text": "The appearance associated with the app’s windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appearance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAppearance",
          "text": "NSAppearance"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/appearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appearance"
        }
      ],
      "role": "symbol",
      "title": "appearance",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/appearance"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/currentSystemPresentationOptions": {
      "abstract": [
        {
          "text": "The set of app presentation options that are currently in effect for the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSystemPresentationOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/currentSystemPresentationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSystemPresentationOptions"
        }
      ],
      "role": "symbol",
      "title": "currentSystemPresentationOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/currentsystempresentationoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/effectiveAppearance": {
      "abstract": [
        {
          "text": "The appearance that AppKit uses to draw the app’s interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "effectiveAppearance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAppearance",
          "text": "NSAppearance"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/effectiveAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "effectiveAppearance"
        }
      ],
      "role": "symbol",
      "title": "effectiveAppearance",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/effectiveappearance"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/presentationOptions-swift.property": {
      "abstract": [
        {
          "text": "The presentation options that should be in effect for the system when this app is active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentationOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/presentationOptions-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentationOptions"
        }
      ],
      "role": "symbol",
      "title": "presentationOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplicationPresentationOptions/NSApplicationPresentationDefault": {
      "abstract": [
        {
          "text": "This is the default presentation mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSApplicationPresentationDefault"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplicationPresentationOptions/NSApplicationPresentationDefault",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSApplicationPresentationDefault",
      "type": "topic",
      "url": "/documentation/appkit/nsapplicationpresentationoptions/nsapplicationpresentationdefault"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexceptionname/1415426-invalidargumentexception": {
      "abstract": [
        {
          "text": "Name of an exception that occurs when you pass an invalid argument to a method, such as a `nil` pointer where a non-`nil` object is required.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "invalidArgumentException"
        },
        {
          "kind": "text",
          "text": ": NSExceptionName"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexceptionname/1415426-invalidargumentexception",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidArgumentException",
      "type": "topic",
      "url": "/documentation/foundation/nsexceptionname/1415426-invalidargumentexception"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-Apps-Appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/appearance",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/effectiveAppearance",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/currentSystemPresentationOptions",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/presentationOptions-swift.property"
      ],
      "title": "Managing the App’s Appearance"
    }
  ],
  "topicSections": [
    {
      "anchor": "Presentation-Options",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideDock",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideDock",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideMenuBar",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideMenuBar",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableAppleMenu",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableProcessSwitching",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableForceQuit",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableSessionTermination",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableHideApplication",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableMenuBarTransparency",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/fullScreen",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideToolbar",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableCursorLocationAssistance"
      ],
      "title": "Presentation Options"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSApplicationPresentationOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Presentation-Options",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSApplicationPresentationOptions/NSApplicationPresentationDefault",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideDock",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideDock",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideMenuBar",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/hideMenuBar",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableAppleMenu",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableProcessSwitching",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableForceQuit",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableSessionTermination",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableHideApplication",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableMenuBarTransparency",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/fullScreen",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/autoHideToolbar",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct/disableCursorLocationAssistance"
              ],
              "title": "Presentation Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-Apps-Appearance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/appearance",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/effectiveAppearance",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/currentSystemPresentationOptions",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/presentationOptions-swift.property"
              ],
              "title": "Managing the App’s Appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSApplicationPresentationOptions"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct/title",
          "value": "NSApplicationPresentationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1hideDock/title",
          "value": "NSApplicationPresentationHideDock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1hideDock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationHideDock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1autoHideToolbar/title",
          "value": "NSApplicationPresentationAutoHideToolbar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1autoHideToolbar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationAutoHideToolbar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableAppleMenu/title",
          "value": "NSApplicationPresentationDisableAppleMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableAppleMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationDisableAppleMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1autoHideDock/title",
          "value": "NSApplicationPresentationAutoHideDock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1autoHideDock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationAutoHideDock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1fullScreen/title",
          "value": "NSApplicationPresentationFullScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1fullScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationFullScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1hideMenuBar/title",
          "value": "NSApplicationPresentationHideMenuBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1hideMenuBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationHideMenuBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1appearance/title",
          "value": "appearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1appearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1presentationOptions-swift.property/title",
          "value": "presentationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1presentationOptions-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "presentationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsexceptionname~11415426-invalidargumentexception/title",
          "value": "NSInvalidArgumentException"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1autoHideMenuBar/title",
          "value": "NSApplicationPresentationAutoHideMenuBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1autoHideMenuBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationAutoHideMenuBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1effectiveAppearance/title",
          "value": "effectiveAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1effectiveAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "effectiveAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableSessionTermination/title",
          "value": "NSApplicationPresentationDisableSessionTermination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableSessionTermination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationDisableSessionTermination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableCursorLocationAssistance/title",
          "value": "NSApplicationPresentationDisableCursorLocationAssistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableCursorLocationAssistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationDisableCursorLocationAssistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableForceQuit/title",
          "value": "NSApplicationPresentationDisableForceQuit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableForceQuit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationDisableForceQuit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableMenuBarTransparency/title",
          "value": "NSApplicationPresentationDisableMenuBarTransparency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableMenuBarTransparency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationDisableMenuBarTransparency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableProcessSwitching/title",
          "value": "NSApplicationPresentationDisableProcessSwitching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableProcessSwitching/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationDisableProcessSwitching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1currentSystemPresentationOptions/title",
          "value": "currentSystemPresentationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1currentSystemPresentationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSystemPresentationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/title",
          "value": "NSApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableHideApplication/title",
          "value": "NSApplicationPresentationDisableHideApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct~1disableHideApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationDisableHideApplication"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsapplication/presentationoptions-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsapplication/presentationoptions-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
