{
  "abstract": [
    {
      "text": "The presentation options that should be in effect for the system when this app is active.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSApplication/presentationOptions-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSApplication(py)presentationOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "presentationOptions"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSApplication",
        "text": "NSApplication"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
        "text": "PresentationOptions"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "presentationOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "presentationOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "presentationOptions"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSApplication",
              "text": "NSApplication"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
              "text": "PresentationOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This value contains a bitwise OR of the constants listed in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Trying to set the property to an invalid combination of option flags raises an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsexceptionname/1415426-invalidargumentexception",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " exception. See the constants for a description of the valid combinations.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication": {
      "abstract": [
        {
          "text": "An object that manages an app’s main event loop and resources used by all of that app’s objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSApplication"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplication"
        }
      ],
      "role": "symbol",
      "title": "NSApplication",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct": {
      "abstract": [
        {
          "text": "Constants that control the presentation of the app, typically for fullscreen apps such as games or kiosks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PresentationOptions"
        }
      ],
      "role": "symbol",
      "title": "NSApplication.PresentationOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/appearance": {
      "abstract": [
        {
          "text": "The appearance associated with the app’s windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appearance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAppearance",
          "text": "NSAppearance"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/appearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appearance"
        }
      ],
      "role": "symbol",
      "title": "appearance",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/appearance"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/currentSystemPresentationOptions": {
      "abstract": [
        {
          "text": "The set of app presentation options that are currently in effect for the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSystemPresentationOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/currentSystemPresentationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSystemPresentationOptions"
        }
      ],
      "role": "symbol",
      "title": "currentSystemPresentationOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/currentsystempresentationoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/effectiveAppearance": {
      "abstract": [
        {
          "text": "The appearance that AppKit uses to draw the app’s interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "effectiveAppearance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAppearance",
          "text": "NSAppearance"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/effectiveAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "effectiveAppearance"
        }
      ],
      "role": "symbol",
      "title": "effectiveAppearance",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/effectiveappearance"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/presentationOptions-swift.property": {
      "abstract": [
        {
          "text": "The presentation options that should be in effect for the system when this app is active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentationOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
          "text": "PresentationOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/presentationOptions-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentationOptions"
        }
      ],
      "role": "symbol",
      "title": "presentationOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/presentationoptions-swift.property"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexceptionname/1415426-invalidargumentexception": {
      "abstract": [
        {
          "text": "Name of an exception that occurs when you pass an invalid argument to a method, such as a `nil` pointer where a non-`nil` object is required.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "invalidArgumentException"
        },
        {
          "kind": "text",
          "text": ": NSExceptionName"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexceptionname/1415426-invalidargumentexception",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidArgumentException",
      "type": "topic",
      "url": "/documentation/foundation/nsexceptionname/1415426-invalidargumentexception"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-Apps-Appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/appearance",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/effectiveAppearance",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/currentSystemPresentationOptions",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct"
      ],
      "title": "Managing the App’s Appearance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "presentationOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "presentationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-Apps-Appearance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/appearance",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/effectiveAppearance",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/currentSystemPresentationOptions",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct"
              ],
              "title": "Managing the App’s Appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/PresentationOptions-swift.struct",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSApplicationPresentationOptions",
                    "text": "NSApplicationPresentationOptions"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "presentationOptions"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1presentationOptions-swift.property/title",
          "value": "presentationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1presentationOptions-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "presentationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct/title",
          "value": "NSApplicationPresentationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1PresentationOptions-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplicationPresentationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1appearance/title",
          "value": "appearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1appearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1currentSystemPresentationOptions/title",
          "value": "currentSystemPresentationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1currentSystemPresentationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSystemPresentationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1effectiveAppearance/title",
          "value": "effectiveAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1effectiveAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "effectiveAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/title",
          "value": "NSApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsexceptionname~11415426-invalidargumentexception/title",
          "value": "NSInvalidArgumentException"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsapplication/presentationoptions-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsapplication/presentationoptions-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
