{"seeAlsoSections":[{"anchor":"Notifications","title":"Notifications","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSApplication/didBecomeActiveNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/didChangeScreenParametersNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/didFinishLaunchingNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/didHideNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/didResignActiveNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/didUnhideNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/didUpdateNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/willBecomeActiveNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/willFinishLaunchingNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/willHideNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/willTerminateNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/willUnhideNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/willUpdateNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/didFinishRestoringWindowsNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/didChangeOcclusionStateNotification"]}],"kind":"symbol","metadata":{"platforms":[{"name":"macOS","beta":false,"unavailable":false,"deprecated":false}],"role":"symbol","roleHeading":"Type Property","externalID":"c:@NSApplicationWillResignActiveNotification","navigatorTitle":[{"kind":"identifier","text":"NSApplicationWillResignActiveNotification"}],"symbolKind":"property","modules":[{"name":"AppKit"}],"title":"willResignActiveNotification","extendedModule":"AppKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"willResignActiveNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName","text":"Name"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsapplication/willresignactivenotification"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsapplication/willresignactivenotification"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSApplication/willResignActiveNotification"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSApplication"]]},"abstract":[{"type":"text","text":"Posted immediately before the app gives up its active status to another app."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"willResignActiveNotification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSNotification","text":"NSNotification"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSNotificationName","text":"Name"}],"platforms":["macOS"],"languages":["swift"]}]},{"content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"The notification object is "},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/shared","type":"reference"},{"type":"text","text":". This notification doesn’t contain a "},{"type":"codeVoice","code":"userInfo"},{"type":"text","text":" dictionary."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSApplication/willFinishLaunchingNotification":{"url":"/documentation/appkit/nsapplication/willfinishlaunchingnotification","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/willFinishLaunchingNotification","role":"symbol","abstract":[{"type":"text","text":"Posted at the start of the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/finishLaunching()"},{"text":" method to indicate that the app has completed its initialization process and is about to finish launching.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willFinishLaunchingNotification","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}],"title":"willFinishLaunchingNotification","navigatorTitle":[{"text":"NSApplicationWillFinishLaunchingNotification","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSApplication/willUnhideNotification":{"title":"willUnhideNotification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"willUnhideNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName","text":"Name"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/willUnhideNotification","url":"/documentation/appkit/nsapplication/willunhidenotification","role":"symbol","abstract":[{"text":"Posted at the start of the ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/unhideWithoutActivation()","type":"reference","isActive":true},{"text":" method to indicate that the app is about to become visible.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSApplicationWillUnhideNotification"}],"type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSApplication/willBecomeActiveNotification":{"role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Posted immediately before the app becomes active.","type":"text"}],"url":"/documentation/appkit/nsapplication/willbecomeactivenotification","navigatorTitle":[{"text":"NSApplicationWillBecomeActiveNotification","kind":"identifier"}],"title":"willBecomeActiveNotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/willBecomeActiveNotification","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willBecomeActiveNotification","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSApplication/didChangeScreenParametersNotification":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/didChangeScreenParametersNotification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangeScreenParametersNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"NSApplicationDidChangeScreenParametersNotification","kind":"identifier"}],"title":"didChangeScreenParametersNotification","type":"topic","url":"/documentation/appkit/nsapplication/didchangescreenparametersnotification","abstract":[{"type":"text","text":"Posted when the configuration of the displays attached to the computer is changed."}]},"doc://com.apple.appkit/documentation/AppKit/NSApplication/finishLaunching()":{"navigatorTitle":[{"text":"finishLaunching","kind":"identifier"}],"title":"finishLaunching()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finishLaunching","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/finishLaunching()","abstract":[{"type":"text","text":"Activates the app, opens any files specified by the "},{"type":"codeVoice","code":"NSOpen"},{"type":"text","text":" user default, and unhighlights the app’s icon."}],"role":"symbol","url":"/documentation/appkit/nsapplication/finishlaunching()","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSApplication/didUpdateNotification":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/didUpdateNotification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"role":"symbol","navigatorTitle":[{"text":"NSApplicationDidUpdateNotification","kind":"identifier"}],"title":"didUpdateNotification","type":"topic","url":"/documentation/appkit/nsapplication/didupdatenotification","abstract":[{"type":"text","text":"Posted at the end of the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/updateWindows()"},{"type":"text","text":" method to indicate that the app has finished updating its windows."}]},"doc://com.apple.appkit/documentation/AppKit/NSApplication/shared":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/shared","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSApplication","preciseIdentifier":"c:objc(cs)NSApplication"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sharedApplication"}],"title":"shared","type":"topic","url":"/documentation/appkit/nsapplication/shared","abstract":[{"type":"text","text":"Returns the application instance, creating it if it doesn’t exist yet."}]},"doc://com.apple.appkit/documentation/AppKit/NSApplication/didFinishLaunchingNotification":{"url":"/documentation/appkit/nsapplication/didfinishlaunchingnotification","title":"didFinishLaunchingNotification","kind":"symbol","abstract":[{"type":"text","text":"Posted at the end of the "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/finishLaunching()","isActive":true,"type":"reference"},{"type":"text","text":" method to indicate that the app has completed launching and is ready to run."}],"type":"topic","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/didFinishLaunchingNotification","navigatorTitle":[{"text":"NSApplicationDidFinishLaunchingNotification","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishLaunchingNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSApplication/unhideWithoutActivation()":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/unhideWithoutActivation()","navigatorTitle":[{"kind":"identifier","text":"unhideWithoutActivation"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unhideWithoutActivation"},{"kind":"text","text":"()"}],"kind":"symbol","abstract":[{"text":"Restores hidden windows without activating their owner (the receiver).","type":"text"}],"type":"topic","title":"unhideWithoutActivation()","role":"symbol","url":"/documentation/appkit/nsapplication/unhidewithoutactivation()"},"doc://com.externally.resolved.symbol/c:objc(cs)NSNotification":{"fragments":[{"text":"class ","kind":"text"},{"text":"NSNotification","kind":"identifier"}],"url":"/documentation/foundation/nsnotification","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSNotification","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"An object containing information broadcast to registered observers that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"title":"NSNotification"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSApplication/didBecomeActiveNotification":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didBecomeActiveNotification","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"abstract":[{"type":"text","text":"Posted immediately after the app becomes active."}],"navigatorTitle":[{"kind":"identifier","text":"NSApplicationDidBecomeActiveNotification"}],"type":"topic","url":"/documentation/appkit/nsapplication/didbecomeactivenotification","title":"didBecomeActiveNotification","role":"symbol","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/didBecomeActiveNotification"},"doc://com.apple.appkit/documentation/AppKit/NSApplication/didHideNotification":{"abstract":[{"text":"Posted at the end of the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/hide(_:)","type":"reference"},{"text":" method to indicate that the app is now hidden.","type":"text"}],"type":"topic","url":"/documentation/appkit/nsapplication/didhidenotification","kind":"symbol","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/didHideNotification","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didHideNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"title":"didHideNotification","navigatorTitle":[{"text":"NSApplicationDidHideNotification","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSApplication/willResignActiveNotification":{"url":"/documentation/appkit/nsapplication/willresignactivenotification","title":"willResignActiveNotification","kind":"symbol","abstract":[{"type":"text","text":"Posted immediately before the app gives up its active status to another app."}],"type":"topic","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/willResignActiveNotification","navigatorTitle":[{"text":"NSApplicationWillResignActiveNotification","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"willResignActiveNotification","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSApplication/willTerminateNotification":{"title":"willTerminateNotification","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"willTerminateNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName","text":"Name"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/willTerminateNotification","url":"/documentation/appkit/nsapplication/willterminatenotification","role":"symbol","abstract":[{"text":"Sends a notification to termintate the app.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSApplicationWillTerminateNotification"}],"type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@NSNotificationName":{"abstract":[{"text":"A structure that defines the name of a notification.","type":"text"}],"type":"topic","identifier":"doc://com.externally.resolved.symbol/c:@T@NSNotificationName","url":"/documentation/foundation/nsnotification/name","kind":"symbol","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"NSNotification.Name"}],"role":"symbol","title":"NSNotification.Name"},"doc://com.apple.appkit/documentation/AppKit/NSApplication/didFinishRestoringWindowsNotification":{"navigatorTitle":[{"text":"NSApplicationDidFinishRestoringWindowsNotification","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/didFinishRestoringWindowsNotification","abstract":[{"type":"text","text":"Posted when the app has finished restoring windows."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didFinishRestoringWindowsNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"title":"didFinishRestoringWindowsNotification","url":"/documentation/appkit/nsapplication/didfinishrestoringwindowsnotification","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSApplication/didUnhideNotification":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUnhideNotification","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Posted at the end of the "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/unhideWithoutActivation()","type":"reference","isActive":true},{"text":" method to indicate that the app is now visible.","type":"text"}],"navigatorTitle":[{"text":"NSApplicationDidUnhideNotification","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nsapplication/didunhidenotification","title":"didUnhideNotification","role":"symbol","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/didUnhideNotification"},"doc://com.apple.appkit/documentation/AppKit/NSApplication/updateWindows()":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Sends an "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/update()","type":"reference","isActive":true},{"type":"text","text":" message to each onscreen window."}],"kind":"symbol","url":"/documentation/appkit/nsapplication/updatewindows()","title":"updateWindows()","identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/updateWindows()","navigatorTitle":[{"kind":"identifier","text":"updateWindows"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateWindows"},{"kind":"text","text":"()"}]},"doc://com.apple.appkit/documentation/AppKit/NSApplication/didChangeOcclusionStateNotification":{"abstract":[{"type":"text","text":"Posted when the app’s occlusion state changes."}],"url":"/documentation/appkit/nsapplication/didchangeocclusionstatenotification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangeOcclusionStateNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName","text":"Name"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/didChangeOcclusionStateNotification","title":"didChangeOcclusionStateNotification","navigatorTitle":[{"kind":"identifier","text":"NSApplicationDidChangeOcclusionStateNotification"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSApplication/didResignActiveNotification":{"abstract":[{"type":"text","text":"Posted immediately after the app gives up its active status to another app."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/didResignActiveNotification","navigatorTitle":[{"text":"NSApplicationDidResignActiveNotification","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"didResignActiveNotification","url":"/documentation/appkit/nsapplication/didresignactivenotification","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"didResignActiveNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Name","preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSApplication/willHideNotification":{"title":"willHideNotification","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Posted at the start of the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/hide(_:)"},{"type":"text","text":" method to indicate that the app is about to be hidden."}],"navigatorTitle":[{"kind":"identifier","text":"NSApplicationWillHideNotification"}],"url":"/documentation/appkit/nsapplication/willhidenotification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"willHideNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName","text":"Name"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/willHideNotification"},"doc://com.apple.appkit/documentation/AppKit/NSApplication/willUpdateNotification":{"kind":"symbol","abstract":[{"type":"text","text":"Posted at the start of the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/updateWindows()"},{"type":"text","text":" method to indicate that the app is about to update its windows."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"willUpdateNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName","text":"Name"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/willUpdateNotification","url":"/documentation/appkit/nsapplication/willupdatenotification","navigatorTitle":[{"kind":"identifier","text":"NSApplicationWillUpdateNotification"}],"title":"willUpdateNotification"},"doc://com.apple.appkit/documentation/AppKit/NSApplication/hide(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hide"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"url":"/documentation/appkit/nsapplication/hide(_:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"hide:"}],"title":"hide(_:)","abstract":[{"type":"text","text":"Hides all the receiver’s windows, and the next app in line is activated."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication/hide(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSApplication":{"abstract":[{"type":"text","text":"An object that manages an app’s main event loop and resources used by all of that app’s objects."}],"url":"/documentation/appkit/nsapplication","kind":"symbol","role":"symbol","title":"NSApplication","navigatorTitle":[{"text":"NSApplication","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSApplication","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSApplication","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":[{"beta":false,"unavailable":false,"name":"macOS","deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Global Variable","path":"/metadata/roleHeading"},{"op":"replace","value":"NSApplicationWillResignActiveNotification","path":"/metadata/title"},{"path":"/metadata/symbolKind","value":"var","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"NSApplicationWillResignActiveNotification"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSApplication/didBecomeActiveNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/didChangeScreenParametersNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/didFinishLaunchingNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/didHideNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/didResignActiveNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/didUnhideNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/didUpdateNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/willBecomeActiveNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/willFinishLaunchingNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/willHideNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/willTerminateNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/willUnhideNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/willUpdateNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/didFinishRestoringWindowsNotification","doc://com.apple.appkit/documentation/AppKit/NSApplication/didChangeOcclusionStateNotification"],"anchor":"Notifications","title":"Notifications","generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSNotificationName","preciseIdentifier":"c:@T@NSNotificationName","text":"NSNotificationName","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"NSApplicationWillResignActiveNotification","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1willFinishLaunchingNotification/title","op":"replace","value":"NSApplicationWillFinishLaunchingNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1willFinishLaunchingNotification/fragments","op":"replace","value":[{"text":"NSApplicationWillFinishLaunchingNotification","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1willUnhideNotification/title","op":"replace","value":"NSApplicationWillUnhideNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1willUnhideNotification/fragments","op":"replace","value":[{"text":"NSApplicationWillUnhideNotification","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1willBecomeActiveNotification/title","op":"replace","value":"NSApplicationWillBecomeActiveNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1willBecomeActiveNotification/fragments","op":"replace","value":[{"text":"NSApplicationWillBecomeActiveNotification","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1didChangeScreenParametersNotification/title","op":"replace","value":"NSApplicationDidChangeScreenParametersNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1didChangeScreenParametersNotification/fragments","op":"replace","value":[{"kind":"identifier","text":"NSApplicationDidChangeScreenParametersNotification"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1finishLaunching()/title","op":"replace","value":"finishLaunching"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1finishLaunching()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"finishLaunching","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1didUpdateNotification/title","op":"replace","value":"NSApplicationDidUpdateNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1didUpdateNotification/fragments","op":"replace","value":[{"kind":"identifier","text":"NSApplicationDidUpdateNotification"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1shared/title","op":"replace","value":"sharedApplication"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1shared/fragments","op":"replace","value":[{"text":"sharedApplication","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1didFinishLaunchingNotification/title","op":"replace","value":"NSApplicationDidFinishLaunchingNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1didFinishLaunchingNotification/fragments","op":"replace","value":[{"kind":"identifier","text":"NSApplicationDidFinishLaunchingNotification"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1unhideWithoutActivation()/title","op":"replace","value":"unhideWithoutActivation"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1unhideWithoutActivation()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"unhideWithoutActivation","kind":"identifier"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSNotification/abstract","op":"replace","value":[{"text":"A container for information broadcast through a notification center to all registered observers.","type":"text"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1didBecomeActiveNotification/title","op":"replace","value":"NSApplicationDidBecomeActiveNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1didBecomeActiveNotification/fragments","op":"replace","value":[{"text":"NSApplicationDidBecomeActiveNotification","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1didHideNotification/title","op":"replace","value":"NSApplicationDidHideNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1didHideNotification/fragments","op":"replace","value":[{"text":"NSApplicationDidHideNotification","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1willResignActiveNotification/title","op":"replace","value":"NSApplicationWillResignActiveNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1willResignActiveNotification/fragments","op":"replace","value":[{"text":"NSApplicationWillResignActiveNotification","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1willTerminateNotification/title","op":"replace","value":"NSApplicationWillTerminateNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1willTerminateNotification/fragments","op":"replace","value":[{"kind":"identifier","text":"NSApplicationWillTerminateNotification"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSNotificationName/title","op":"replace","value":"NSNotificationName"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1didFinishRestoringWindowsNotification/title","op":"replace","value":"NSApplicationDidFinishRestoringWindowsNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1didFinishRestoringWindowsNotification/fragments","op":"replace","value":[{"text":"NSApplicationDidFinishRestoringWindowsNotification","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1didUnhideNotification/title","op":"replace","value":"NSApplicationDidUnhideNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1didUnhideNotification/fragments","op":"replace","value":[{"kind":"identifier","text":"NSApplicationDidUnhideNotification"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1updateWindows()/title","op":"replace","value":"updateWindows"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1updateWindows()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"updateWindows","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1didChangeOcclusionStateNotification/title","op":"replace","value":"NSApplicationDidChangeOcclusionStateNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1didChangeOcclusionStateNotification/fragments","op":"replace","value":[{"kind":"identifier","text":"NSApplicationDidChangeOcclusionStateNotification"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1didResignActiveNotification/title","op":"replace","value":"NSApplicationDidResignActiveNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1didResignActiveNotification/fragments","op":"replace","value":[{"kind":"identifier","text":"NSApplicationDidResignActiveNotification"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1willHideNotification/title","op":"replace","value":"NSApplicationWillHideNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1willHideNotification/fragments","op":"replace","value":[{"kind":"identifier","text":"NSApplicationWillHideNotification"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1willUpdateNotification/title","op":"replace","value":"NSApplicationWillUpdateNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1willUpdateNotification/fragments","op":"replace","value":[{"kind":"identifier","text":"NSApplicationWillUpdateNotification"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1hide(_:)/title","op":"replace","value":"hide:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1hide(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"hide:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/title","op":"replace","value":"NSApplication"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/fragments","op":"replace","value":[{"kind":"identifier","text":"NSApplication"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSApplication"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}