{
  "abstract": [
    {
      "text": "The section allows users to page its content orthogonally one group at a time, centering each group.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/groupPagingCentered"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UICollectionLayoutSectionOrthogonalScrollingBehavior@UICollectionLayoutSectionOrthogonalScrollingBehaviorGroupPagingCentered",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "groupPagingCentered"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UICollectionLayoutSectionOrthogonalScrollingBehaviorGroupPagingCentered"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UICollectionLayoutSectionOrthogonalScrollingBehavior.groupPagingCentered"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "groupPagingCentered"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior": {
      "abstract": [
        {
          "text": "The scrolling behavior of the layout’s sections in relation to the main layout axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionLayoutSectionOrthogonalScrollingBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutSectionOrthogonalScrollingBehavior"
        }
      ],
      "role": "symbol",
      "title": "UICollectionLayoutSectionOrthogonalScrollingBehavior",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingbehavior"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/continuous": {
      "abstract": [
        {
          "text": "The section allows users to scroll its content orthogonally with continuous scrolling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continuous"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/continuous",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutSectionOrthogonalScrollingBehaviorContinuous"
        }
      ],
      "role": "symbol",
      "title": "UICollectionLayoutSectionOrthogonalScrollingBehavior.continuous",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingbehavior/continuous"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/continuousGroupLeadingBoundary": {
      "abstract": [
        {
          "text": "The section allows users to scroll its content orthogonally, coming to a natural stop at the leading boundary of the visible group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continuousGroupLeadingBoundary"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/continuousGroupLeadingBoundary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutSectionOrthogonalScrollingBehaviorContinuousGroupLeadingBoundary"
        }
      ],
      "role": "symbol",
      "title": "UICollectionLayoutSectionOrthogonalScrollingBehavior.continuousGroupLeadingBoundary",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingbehavior/continuousgroupleadingboundary"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/groupPaging": {
      "abstract": [
        {
          "text": "The section allows users to page its content orthogonally one group at a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "groupPaging"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/groupPaging",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutSectionOrthogonalScrollingBehaviorGroupPaging"
        }
      ],
      "role": "symbol",
      "title": "UICollectionLayoutSectionOrthogonalScrollingBehavior.groupPaging",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingbehavior/grouppaging"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/groupPagingCentered": {
      "abstract": [
        {
          "text": "The section allows users to page its content orthogonally one group at a time, centering each group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "groupPagingCentered"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/groupPagingCentered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutSectionOrthogonalScrollingBehaviorGroupPagingCentered"
        }
      ],
      "role": "symbol",
      "title": "UICollectionLayoutSectionOrthogonalScrollingBehavior.groupPagingCentered",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingbehavior/grouppagingcentered"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/none": {
      "abstract": [
        {
          "text": "The section does not allow users to scroll its content orthogonally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutSectionOrthogonalScrollingBehaviorNone"
        }
      ],
      "role": "symbol",
      "title": "UICollectionLayoutSectionOrthogonalScrollingBehavior.none",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingbehavior/none"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/paging": {
      "abstract": [
        {
          "text": "The section allows users to page its content orthogonally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paging"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/paging",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutSectionOrthogonalScrollingBehaviorPaging"
        }
      ],
      "role": "symbol",
      "title": "UICollectionLayoutSectionOrthogonalScrollingBehavior.paging",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingbehavior/paging"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/none",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/continuous",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/continuousGroupLeadingBoundary",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/paging",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/groupPaging"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingBehaviorGroupPagingCentered"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingBehaviorGroupPagingCentered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/none",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/continuous",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/continuousGroupLeadingBoundary",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/paging",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior/groupPaging"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UICollectionLayoutSectionOrthogonalScrollingBehaviorGroupPagingCentered"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingBehavior~1continuous/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingBehaviorContinuous"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingBehavior~1continuous/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingBehaviorContinuous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingBehavior~1groupPaging/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingBehaviorGroupPaging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingBehavior~1groupPaging/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingBehaviorGroupPaging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingBehavior~1groupPagingCentered/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingBehaviorGroupPagingCentered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingBehavior~1groupPagingCentered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingBehaviorGroupPagingCentered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingBehavior~1paging/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingBehaviorPaging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingBehavior~1paging/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingBehaviorPaging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingBehavior~1continuousGroupLeadingBoundary/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingBehaviorContinuousGroupLeadingBoundary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingBehavior~1continuousGroupLeadingBoundary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingBehaviorContinuousGroupLeadingBoundary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingBehavior~1none/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingBehaviorNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingBehavior~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingBehaviorNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingBehavior/title",
          "value": "UICollectionLayoutSectionOrthogonalScrollingBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionLayoutSectionOrthogonalScrollingBehavior"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingbehavior/grouppagingcentered"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingbehavior/grouppagingcentered"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
