{
  "abstract": [
    {
      "text": "The device’s serial number as a string.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey/serialNumberString"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "IOUSBHost",
    "externalID": "c:@IOUSBHostDevicePropertyKeySerialNumberString",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "serialNumberString"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@IOUSBHostDevicePropertyKey",
        "text": "IOUSBHostDevicePropertyKey"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOUSBHostDevicePropertyKeySerialNumberString"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "serialNumberString"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "serialNumberString"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@IOUSBHostDevicePropertyKey",
              "text": "IOUSBHostDevicePropertyKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey": {
      "abstract": [
        {
          "text": "Properties of a USB device that describe its state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostDevicePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostDevicePropertyKey"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostDevicePropertyKey",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostdevicepropertykey"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey/containerID": {
      "abstract": [
        {
          "text": "The device’s container ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containerID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostDevicePropertyKey",
          "text": "IOUSBHostDevicePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey/containerID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostDevicePropertyKeyContainerID"
        }
      ],
      "role": "symbol",
      "title": "containerID",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostdevicepropertykey/containerid"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey/currentConfiguration": {
      "abstract": [
        {
          "text": "The device’s current configuration value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostDevicePropertyKey",
          "text": "IOUSBHostDevicePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey/currentConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostDevicePropertyKeyCurrentConfiguration"
        }
      ],
      "role": "symbol",
      "title": "currentConfiguration",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostdevicepropertykey/currentconfiguration"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey/serialNumberString": {
      "abstract": [
        {
          "text": "The device’s serial number as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serialNumberString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostDevicePropertyKey",
          "text": "IOUSBHostDevicePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey/serialNumberString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostDevicePropertyKeySerialNumberString"
        }
      ],
      "role": "symbol",
      "title": "serialNumberString",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostdevicepropertykey/serialnumberstring"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey/vendorString": {
      "abstract": [
        {
          "text": "The device’s vendor name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vendorString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostDevicePropertyKey",
          "text": "IOUSBHostDevicePropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey/vendorString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostDevicePropertyKeyVendorString"
        }
      ],
      "role": "symbol",
      "title": "vendorString",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostdevicepropertykey/vendorstring"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPropertyKey": {
      "abstract": [
        {
          "text": "Properties that the USB host device and interface classes share.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPropertyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostPropertyKey"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostPropertyKey",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpropertykey"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey/currentConfiguration",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey/containerID",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey/vendorString",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPropertyKey"
      ],
      "title": "Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOUSBHostDevicePropertyKeySerialNumberString"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostDevicePropertyKeySerialNumberString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iousbhost/documentation/IOUSBHost"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey/currentConfiguration",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey/containerID",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey/vendorString",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPropertyKey"
              ],
              "title": "Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevicePropertyKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@IOUSBHostDevicePropertyKey",
                    "text": "IOUSBHostDevicePropertyKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOUSBHostDevicePropertyKeySerialNumberString"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevicePropertyKey~1serialNumberString/title",
          "value": "IOUSBHostDevicePropertyKeySerialNumberString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevicePropertyKey~1serialNumberString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostDevicePropertyKeySerialNumberString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevicePropertyKey/title",
          "value": "IOUSBHostDevicePropertyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevicePropertyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostDevicePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevicePropertyKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostDevicePropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevicePropertyKey~1currentConfiguration/title",
          "value": "IOUSBHostDevicePropertyKeyCurrentConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevicePropertyKey~1currentConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostDevicePropertyKeyCurrentConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevicePropertyKey~1vendorString/title",
          "value": "IOUSBHostDevicePropertyKeyVendorString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevicePropertyKey~1vendorString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostDevicePropertyKeyVendorString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPropertyKey/title",
          "value": "IOUSBHostPropertyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPropertyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostPropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPropertyKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostPropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevicePropertyKey~1containerID/title",
          "value": "IOUSBHostDevicePropertyKeyContainerID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevicePropertyKey~1containerID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostDevicePropertyKeyContainerID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhostdevicepropertykey/serialnumberstring"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbhostdevicepropertykey/serialnumberstring"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
