{
  "abstract": [
    {
      "text": "The attachment for with the text item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITextItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextItem/textAttachment"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UITextItem(py)textAttachment",
    "fragments": [
      {
        "kind": "identifier",
        "text": "textAttachment"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "textAttachment"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "textAttachment"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "strong"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextAttachment",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSTextAttachment",
              "text": "NSTextAttachment"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "textAttachment"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextAttachment": {
      "abstract": [
        {
          "text": "The values for the attachment characteristics of attributed strings and related objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextAttachment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextAttachment"
        }
      ],
      "role": "symbol",
      "title": "NSTextAttachment",
      "type": "topic",
      "url": "/documentation/uikit/nstextattachment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextItem": {
      "abstract": [
        {
          "text": "An object for attaching custom actions and menus to links, text attachments, or other specific text in a text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextItem"
        }
      ],
      "role": "symbol",
      "title": "UITextItem",
      "type": "topic",
      "url": "/documentation/uikit/uitextitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextItem/link": {
      "abstract": [
        {
          "text": "The URL associated with the link text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "link"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextItem/link",
      "kind": "symbol",
      "role": "symbol",
      "title": "link",
      "type": "topic",
      "url": "/documentation/uikit/uitextitem/link"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextItem/tagIdentifier": {
      "abstract": [
        {
          "text": "The tag associated with the text item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "tagIdentifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextItem/tagIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "tagIdentifier",
      "type": "topic",
      "url": "/documentation/uikit/uitextitem/tagidentifier"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextItem/textAttachment": {
      "abstract": [
        {
          "text": "The attachment for with the text item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "textAttachment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextItem/textAttachment",
      "kind": "symbol",
      "role": "symbol",
      "title": "textAttachment",
      "type": "topic",
      "url": "/documentation/uikit/uitextitem/textattachment"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-value",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextItem/link",
        "doc://com.apple.uikit/documentation/UIKit/UITextItem/tagIdentifier"
      ],
      "title": "Getting the value"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItem/title",
          "value": "UITextItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextAttachment/title",
          "value": "NSTextAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAttachment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextitem/textattachment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
