{
  "abstract": [
    {
      "text": "Error codes returned by HealthKit.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "HKError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.healthkit/documentation/HealthKit/executing-statistics-collection-queries"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError": {
      "abstract": [
        {
          "text": "An error returned from a HealthKit method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKError"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKError"
        }
      ],
      "role": "symbol",
      "title": "HKError",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code": {
      "abstract": [
        {
          "text": "Error codes returned by HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAnotherWorkoutSessionStarted": {
      "abstract": [
        {
          "text": "Another app started a workout session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorAnotherWorkoutSessionStarted"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAnotherWorkoutSessionStarted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorAnotherWorkoutSessionStarted"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorAnotherWorkoutSessionStarted",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/erroranotherworkoutsessionstarted"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAuthorizationDenied": {
      "abstract": [
        {
          "text": "The user hasn’t given the app permission to save data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorAuthorizationDenied"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAuthorizationDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorAuthorizationDenied"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorAuthorizationDenied",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errorauthorizationdenied"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAuthorizationNotDetermined": {
      "abstract": [
        {
          "text": "The app hasn’t yet asked the user for the authorization required to complete the task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorAuthorizationNotDetermined"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAuthorizationNotDetermined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorAuthorizationNotDetermined"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorAuthorizationNotDetermined",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errorauthorizationnotdetermined"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorBackgroundWorkoutSessionNotAllowed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorBackgroundWorkoutSessionNotAllowed"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorBackgroundWorkoutSessionNotAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorBackgroundWorkoutSessionNotAllowed"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorBackgroundWorkoutSessionNotAllowed",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errorbackgroundworkoutsessionnotallowed"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorDataSizeExceeded": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDataSizeExceeded"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorDataSizeExceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorDataSizeExceeded"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorDataSizeExceeded",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errordatasizeexceeded"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorDatabaseInaccessible": {
      "abstract": [
        {
          "text": "The HealthKit data is unavailable because it’s protected and the device is locked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDatabaseInaccessible"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorDatabaseInaccessible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorDatabaseInaccessible"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorDatabaseInaccessible",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errordatabaseinaccessible"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorHealthDataRestricted": {
      "abstract": [
        {
          "text": "A Mobile Device Management (MDM) profile restricts the use of HealthKit on this device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorHealthDataRestricted"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorHealthDataRestricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorHealthDataRestricted"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorHealthDataRestricted",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errorhealthdatarestricted"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorHealthDataUnavailable": {
      "abstract": [
        {
          "text": "HealthKit accessed on an unsupported device, such as an iPad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorHealthDataUnavailable"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorHealthDataUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorHealthDataUnavailable"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorHealthDataUnavailable",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errorhealthdataunavailable"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorInvalidArgument": {
      "abstract": [
        {
          "text": "The app passed an invalid argument to the HealthKit API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorInvalidArgument"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorInvalidArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorInvalidArgument"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorInvalidArgument",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errorinvalidargument"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorNoData": {
      "abstract": [
        {
          "text": "Data is unavailable for the requested query and predicate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorNoData"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorNoData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorNoData"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorNoData",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errornodata"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorNotPermissibleForGuestUserMode": {
      "abstract": [
        {
          "text": "The app attempted to write HealthKit data while in a Guest User session in visionOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorNotPermissibleForGuestUserMode"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorNotPermissibleForGuestUserMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorNotPermissibleForGuestUserMode"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorNotPermissibleForGuestUserMode",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errornotpermissibleforguestusermode"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorRequiredAuthorizationDenied": {
      "abstract": [
        {
          "text": "The user hasn’t granted the application authorization to access all the required clinical record types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorRequiredAuthorizationDenied"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorRequiredAuthorizationDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorRequiredAuthorizationDenied"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorRequiredAuthorizationDenied",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errorrequiredauthorizationdenied"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorUserCanceled": {
      "abstract": [
        {
          "text": "The user canceled the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorUserCanceled"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorUserCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorUserCanceled"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorUserCanceled",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errorusercanceled"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorUserExitedWorkoutSession": {
      "abstract": [
        {
          "text": "The user exited your application while a workout session was running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorUserExitedWorkoutSession"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorUserExitedWorkoutSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorUserExitedWorkoutSession"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorUserExitedWorkoutSession",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/erroruserexitedworkoutsession"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorWorkoutActivityNotAllowed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorWorkoutActivityNotAllowed"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorWorkoutActivityNotAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorWorkoutActivityNotAllowed"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.errorWorkoutActivityNotAllowed",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/errorworkoutactivitynotallowed"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/init(rawvalue:)"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/noError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11HKErrorCodeLeV",
          "text": "HKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/noError",
      "kind": "symbol",
      "role": "symbol",
      "title": "noError",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/noerror"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/unknownError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/unknownError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKUnknownError"
        }
      ],
      "role": "symbol",
      "title": "HKError.Code.unknownError",
      "type": "topic",
      "url": "/documentation/healthkit/hkerror/code/unknownerror"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKErrorCode/HKNoError": {
      "abstract": [
        {
          "text": "No error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "HKNoError"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKErrorCode/HKNoError",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKNoError",
      "type": "topic",
      "url": "/documentation/healthkit/hkerrorcode/hknoerror"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKErrorDomain": {
      "abstract": [
        {
          "text": "The domain for all HealthKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "HKErrorDomain",
      "type": "topic",
      "url": "/documentation/healthkit/hkerrordomain"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/executing-statistics-collection-queries": {
      "abstract": [
        {
          "text": "Calculate statistical data for graphs and charts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/executing-statistics-collection-queries",
      "kind": "article",
      "role": "article",
      "title": "Executing Statistics Collection Queries",
      "type": "topic",
      "url": "/documentation/healthkit/executing-statistics-collection-queries"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKError",
        "doc://com.apple.healthkit/documentation/HealthKit/HKErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorHealthDataUnavailable",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorHealthDataRestricted",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorInvalidArgument",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAuthorizationDenied",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAuthorizationNotDetermined",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorRequiredAuthorizationDenied",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorDatabaseInaccessible",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorUserCanceled",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAnotherWorkoutSessionStarted",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorUserExitedWorkoutSession",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorNoData"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorBackgroundWorkoutSessionNotAllowed",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorDataSizeExceeded",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorNotPermissibleForGuestUserMode",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorWorkoutActivityNotAllowed",
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/unknownError"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/noError"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorHealthDataUnavailable",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorHealthDataRestricted",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorInvalidArgument",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAuthorizationDenied",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAuthorizationNotDetermined",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorRequiredAuthorizationDenied",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorDatabaseInaccessible",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorUserCanceled",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorAnotherWorkoutSessionStarted",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorUserExitedWorkoutSession",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorNoData"
              ],
              "title": "Errors"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorBackgroundWorkoutSessionNotAllowed",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorDataSizeExceeded",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorNotPermissibleForGuestUserMode",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/errorWorkoutActivityNotAllowed",
                "doc://com.apple.healthkit/documentation/HealthKit/HKError/Code/unknownError",
                "doc://com.apple.healthkit/documentation/HealthKit/HKErrorCode/HKNoError"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorHealthDataUnavailable/title",
          "value": "HKErrorHealthDataUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorHealthDataUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorHealthDataUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorInvalidArgument/title",
          "value": "HKErrorInvalidArgument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorInvalidArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorInvalidArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKErrorDomain/title",
          "value": "HKErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorNoData/title",
          "value": "HKErrorNoData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorNoData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorNoData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code/title",
          "value": "HKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorAnotherWorkoutSessionStarted/title",
          "value": "HKErrorAnotherWorkoutSessionStarted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorAnotherWorkoutSessionStarted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorAnotherWorkoutSessionStarted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorAuthorizationDenied/title",
          "value": "HKErrorAuthorizationDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorAuthorizationDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorAuthorizationDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorDatabaseInaccessible/title",
          "value": "HKErrorDatabaseInaccessible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorDatabaseInaccessible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorDatabaseInaccessible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorAuthorizationNotDetermined/title",
          "value": "HKErrorAuthorizationNotDetermined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorAuthorizationNotDetermined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorAuthorizationNotDetermined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorNotPermissibleForGuestUserMode/title",
          "value": "HKErrorNotPermissibleForGuestUserMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorNotPermissibleForGuestUserMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorNotPermissibleForGuestUserMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorDataSizeExceeded/title",
          "value": "HKErrorDataSizeExceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorDataSizeExceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorDataSizeExceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorUserCanceled/title",
          "value": "HKErrorUserCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorUserCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorUserCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorWorkoutActivityNotAllowed/title",
          "value": "HKErrorWorkoutActivityNotAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorWorkoutActivityNotAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorWorkoutActivityNotAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1unknownError/title",
          "value": "HKUnknownError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1unknownError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKUnknownError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorRequiredAuthorizationDenied/title",
          "value": "HKErrorRequiredAuthorizationDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorRequiredAuthorizationDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorRequiredAuthorizationDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorHealthDataRestricted/title",
          "value": "HKErrorHealthDataRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorHealthDataRestricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorHealthDataRestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorUserExitedWorkoutSession/title",
          "value": "HKErrorUserExitedWorkoutSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorUserExitedWorkoutSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorUserExitedWorkoutSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorBackgroundWorkoutSessionNotAllowed/title",
          "value": "HKErrorBackgroundWorkoutSessionNotAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKError~1Code~1errorBackgroundWorkoutSessionNotAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKErrorBackgroundWorkoutSessionNotAllowed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
