{
  "abstract": [
    {
      "text": "An array of durations at specific radio signal attenuations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/attenuationDurations"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ENExposureInfo(py)attenuationDurations",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "attenuationDurations"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSNumber",
        "text": "NSNumber"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "Exposure Notification"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "attenuationDurations"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "attenuationDurations"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "attenuationDurations"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": "] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An array that contains the duration, in seconds, at certain attenuations, using an aggregated maximum exposures of 30 minutes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "array[0]",
              "type": "codeVoice"
            },
            {
              "text": " =  Sum of durations for all exposures when the attenuation value was ",
              "type": "text"
            },
            {
              "code": "Attenuation <= X",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "array[1]",
              "type": "codeVoice"
            },
            {
              "text": " =  Sum of durations for all exposures when attenuation value was ",
              "type": "text"
            },
            {
              "code": "X < Attenuation <= Y",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "array[2]",
              "type": "codeVoice"
            },
            {
              "text": " =  Sum of durations for all exposures when attenuation value was ",
              "type": "text"
            },
            {
              "code": "Y < Attenuation",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/attenuationDurationThresholds",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to configure the ",
              "type": "text"
            },
            {
              "code": "X",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "Y",
              "type": "codeVoice"
            },
            {
              "text": " values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification": {
      "abstract": [
        {
          "text": "Implement a COVID-19 exposure notification system that protects user privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
      "kind": "symbol",
      "role": "collection",
      "title": "Exposure Notification",
      "type": "topic",
      "url": "/documentation/exposurenotification"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENAttenuation": {
      "abstract": [
        {
          "text": "The signal strength value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENAttenuation"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENAttenuation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENAttenuation"
        }
      ],
      "role": "symbol",
      "title": "ENAttenuation",
      "type": "topic",
      "url": "/documentation/exposurenotification/enattenuation"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDaysSinceOnsetOfSymptomsUnknown": {
      "abstract": [
        {
          "text": "A value used when the number of days since onset of symptoms is unknown.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENDaysSinceOnsetOfSymptomsUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDaysSinceOnsetOfSymptomsUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENDaysSinceOnsetOfSymptomsUnknown"
        }
      ],
      "role": "symbol",
      "title": "ENDaysSinceOnsetOfSymptomsUnknown",
      "type": "topic",
      "url": "/documentation/exposurenotification/endayssinceonsetofsymptomsunknown"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/attenuationDurationThresholds": {
      "abstract": [
        {
          "text": "The configurable signal-loss thresholds for calculating exposure risk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attenuationDurationThresholds"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/attenuationDurationThresholds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attenuationDurationThresholds"
        }
      ],
      "role": "symbol",
      "title": "attenuationDurationThresholds",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/attenuationdurationthresholds"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo": {
      "abstract": [
        {
          "text": "The incident information related to a potential exposure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENExposureInfo"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENExposureInfo"
        }
      ],
      "role": "symbol",
      "title": "ENExposureInfo",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/attenuationDurations": {
      "abstract": [
        {
          "text": "An array of durations at specific radio signal attenuations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attenuationDurations"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/attenuationDurations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attenuationDurations"
        }
      ],
      "role": "symbol",
      "title": "attenuationDurations",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/attenuationdurations"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/attenuationValue": {
      "abstract": [
        {
          "text": "The attenutation risk level value for the exposure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attenuationValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ENAttenuation",
          "text": "ENAttenuation"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/attenuationValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attenuationValue"
        }
      ],
      "role": "symbol",
      "title": "attenuationValue",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/attenuationvalue"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/date": {
      "abstract": [
        {
          "text": "The date the exposure occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "date"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/date",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "date"
        }
      ],
      "role": "symbol",
      "title": "date",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/date"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/daysSinceOnsetOfSymptoms": {
      "abstract": [
        {
          "text": "The number of days since the onset of symptoms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "daysSinceOnsetOfSymptoms"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/daysSinceOnsetOfSymptoms",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "daysSinceOnsetOfSymptoms"
        }
      ],
      "role": "symbol",
      "title": "daysSinceOnsetOfSymptoms",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/dayssinceonsetofsymptoms"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/diagnosisReportType": {
      "abstract": [
        {
          "text": "The method used to report the positive diagnosis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "diagnosisReportType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENDiagnosisReportType",
          "text": "ENDiagnosisReportType"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/diagnosisReportType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "diagnosisReportType"
        }
      ],
      "role": "symbol",
      "title": "diagnosisReportType",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/diagnosisreporttype"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/duration": {
      "abstract": [
        {
          "text": "The length of time that the contact was in proximity to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/duration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "duration"
        }
      ],
      "role": "symbol",
      "title": "duration",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/duration"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/metadata": {
      "abstract": [
        {
          "text": "The metadata associated with the exposure information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/metadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadata"
        }
      ],
      "role": "symbol",
      "title": "metadata",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/metadata"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/totalRiskScore": {
      "abstract": [
        {
          "text": "The value that represents the total risk score the framework calculates for this exposure incident.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalRiskScore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ENRiskScore",
          "text": "ENRiskScore"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/totalRiskScore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalRiskScore"
        }
      ],
      "role": "symbol",
      "title": "totalRiskScore",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/totalriskscore"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/totalRiskScoreFullRange": {
      "abstract": [
        {
          "text": "The value that represents the full-range total risk score the framework calculates for this exposure incident.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalRiskScoreFullRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/totalRiskScoreFullRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalRiskScoreFullRange"
        }
      ],
      "role": "symbol",
      "title": "totalRiskScoreFullRange",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/totalriskscorefullrange"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/transmissionRiskLevel": {
      "abstract": [
        {
          "text": "The transmission risk associated with a diagnosis key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transmissionRiskLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ENRiskLevel",
          "text": "ENRiskLevel"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/transmissionRiskLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transmissionRiskLevel"
        }
      ],
      "role": "symbol",
      "title": "transmissionRiskLevel",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/transmissionrisklevel"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Exposure-Criteria",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/attenuationValue",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/date",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/duration",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/totalRiskScore",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/totalRiskScoreFullRange",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/transmissionRiskLevel",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENAttenuation",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/metadata",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/daysSinceOnsetOfSymptoms",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/diagnosisReportType",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDaysSinceOnsetOfSymptomsUnknown"
      ],
      "title": "Exposure Criteria"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "attenuationDurations"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attenuationDurations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Exposure-Criteria",
              "generated": true,
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/attenuationValue",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/date",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/duration",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/totalRiskScore",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/totalRiskScoreFullRange",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/transmissionRiskLevel",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENAttenuation",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/metadata",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/daysSinceOnsetOfSymptoms",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/diagnosisReportType",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDaysSinceOnsetOfSymptomsUnknown"
              ],
              "title": "Exposure Criteria"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSNumber *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "attenuationDurations"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1daysSinceOnsetOfSymptoms/title",
          "value": "daysSinceOnsetOfSymptoms"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1daysSinceOnsetOfSymptoms/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "daysSinceOnsetOfSymptoms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDaysSinceOnsetOfSymptomsUnknown/title",
          "value": "ENDaysSinceOnsetOfSymptomsUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDaysSinceOnsetOfSymptomsUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDaysSinceOnsetOfSymptomsUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1attenuationDurations/title",
          "value": "attenuationDurations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1attenuationDurations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attenuationDurations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1duration/title",
          "value": "duration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1duration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "duration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1totalRiskScore/title",
          "value": "totalRiskScore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1totalRiskScore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalRiskScore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1totalRiskScoreFullRange/title",
          "value": "totalRiskScoreFullRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1totalRiskScoreFullRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalRiskScoreFullRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1attenuationDurationThresholds/title",
          "value": "attenuationDurationThresholds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1attenuationDurationThresholds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attenuationDurationThresholds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1date/title",
          "value": "date"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1date/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "date"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1metadata/title",
          "value": "metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENAttenuation/title",
          "value": "ENAttenuation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENAttenuation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENAttenuation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENAttenuation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENAttenuation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo/title",
          "value": "ENExposureInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1diagnosisReportType/title",
          "value": "diagnosisReportType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1diagnosisReportType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "diagnosisReportType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1transmissionRiskLevel/title",
          "value": "transmissionRiskLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1transmissionRiskLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transmissionRiskLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1attenuationValue/title",
          "value": "attenuationValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1attenuationValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attenuationValue"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exposurenotification/enexposureinfo/attenuationdurations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exposurenotification/enexposureinfo/attenuationdurations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
