{
  "abstract": [
    {
      "text": "The image data corresponds to a TIFF image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/TIFF"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ITLibArtworkFormat@ITLibArtworkFormatTIFF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TIFF"
      }
    ],
    "modules": [
      {
        "name": "iTunes Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ITLibArtworkFormatTIFF"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ITLibArtworkFormat.TIFF"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TIFF"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary": {
      "abstract": [
        {
          "text": "Retrieve the properties of the media in the user’s iTunes library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "iTunes Library",
      "type": "topic",
      "url": "/documentation/ituneslibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtwork/imageDataFormat": {
      "abstract": [
        {
          "text": "The format of the artwork image data that ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtwork/imageData",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageDataFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ITLibArtworkFormat",
          "text": "ITLibArtworkFormat"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtwork/imageDataFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageDataFormat"
        }
      ],
      "role": "symbol",
      "title": "imageDataFormat",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibartwork/imagedataformat"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat": {
      "abstract": [
        {
          "text": "These constants specify the possible formats of the data that ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtwork/imageDataFormat",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibArtworkFormat"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibArtworkFormat"
        }
      ],
      "role": "symbol",
      "title": "ITLibArtworkFormat",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibartworkformat"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/BMP": {
      "abstract": [
        {
          "text": "The image data corresponds to a bitmap image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BMP"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/BMP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibArtworkFormatBMP"
        }
      ],
      "role": "symbol",
      "title": "ITLibArtworkFormat.BMP",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibartworkformat/bmp"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/GIF": {
      "abstract": [
        {
          "text": "The image data corresponds to a GIF image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GIF"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/GIF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibArtworkFormatGIF"
        }
      ],
      "role": "symbol",
      "title": "ITLibArtworkFormat.GIF",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibartworkformat/gif"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/JPEG": {
      "abstract": [
        {
          "text": "The image data corresponds to a JPEG image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JPEG"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/JPEG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibArtworkFormatJPEG"
        }
      ],
      "role": "symbol",
      "title": "ITLibArtworkFormat.JPEG",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibartworkformat/jpeg"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/JPEG2000": {
      "abstract": [
        {
          "text": "The image data corresponds to a JPEG2000 image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JPEG2000"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/JPEG2000",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibArtworkFormatJPEG2000"
        }
      ],
      "role": "symbol",
      "title": "ITLibArtworkFormat.JPEG2000",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibartworkformat/jpeg2000"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/PICT": {
      "abstract": [
        {
          "text": "The image data corresponds to a PICT image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PICT"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/PICT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibArtworkFormatPICT"
        }
      ],
      "role": "symbol",
      "title": "ITLibArtworkFormat.PICT",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibartworkformat/pict"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/PNG": {
      "abstract": [
        {
          "text": "The image data corresponds to a PNG image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PNG"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/PNG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibArtworkFormatPNG"
        }
      ],
      "role": "symbol",
      "title": "ITLibArtworkFormat.PNG",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibartworkformat/png"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/TIFF": {
      "abstract": [
        {
          "text": "The image data corresponds to a TIFF image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TIFF"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/TIFF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibArtworkFormatTIFF"
        }
      ],
      "role": "symbol",
      "title": "ITLibArtworkFormat.TIFF",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibartworkformat/tiff"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/bitmap": {
      "abstract": [
        {
          "text": "The image data corresponds to a bitmap image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bitmap"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/bitmap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibArtworkFormatBitmap"
        }
      ],
      "role": "symbol",
      "title": "ITLibArtworkFormat.bitmap",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibartworkformat/bitmap"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/none": {
      "abstract": [
        {
          "text": "The image data format is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibArtworkFormatNone"
        }
      ],
      "role": "symbol",
      "title": "ITLibArtworkFormat.none",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibartworkformat/none"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Artwork-Formats",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/none",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/bitmap",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/JPEG",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/JPEG2000",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/GIF",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/PNG",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/BMP",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/PICT"
      ],
      "title": "Artwork Formats"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ITLibArtworkFormatTIFF"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibArtworkFormatTIFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Artwork-Formats",
              "generated": true,
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/none",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/bitmap",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/JPEG",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/JPEG2000",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/GIF",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/PNG",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/BMP",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibArtworkFormat/PICT"
              ],
              "title": "Artwork Formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ITLibArtworkFormatTIFF"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat~1TIFF/title",
          "value": "ITLibArtworkFormatTIFF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat~1TIFF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibArtworkFormatTIFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat~1JPEG/title",
          "value": "ITLibArtworkFormatJPEG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat~1JPEG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibArtworkFormatJPEG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat~1GIF/title",
          "value": "ITLibArtworkFormatGIF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat~1GIF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibArtworkFormatGIF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat~1PICT/title",
          "value": "ITLibArtworkFormatPICT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat~1PICT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibArtworkFormatPICT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat~1BMP/title",
          "value": "ITLibArtworkFormatBMP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat~1BMP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibArtworkFormatBMP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat~1none/title",
          "value": "ITLibArtworkFormatNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibArtworkFormatNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtwork~1imageDataFormat/title",
          "value": "imageDataFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtwork~1imageDataFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageDataFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat/title",
          "value": "ITLibArtworkFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibArtworkFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibArtworkFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat~1bitmap/title",
          "value": "ITLibArtworkFormatBitmap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat~1bitmap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibArtworkFormatBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat~1PNG/title",
          "value": "ITLibArtworkFormatPNG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat~1PNG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibArtworkFormatPNG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat~1JPEG2000/title",
          "value": "ITLibArtworkFormatJPEG2000"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibArtworkFormat~1JPEG2000/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibArtworkFormatJPEG2000"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/ituneslibrary/itlibartworkformat/tiff"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/ituneslibrary/itlibartworkformat/tiff"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
