{
  "abstract": [
    {
      "text": "The scheduled ride is out of the ride area and requires the user to open the app to fix the problem.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunchRideScheduledTooFar"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INRequestRideIntentResponseCode@INRequestRideIntentResponseCodeFailureRequiringAppLaunchRideScheduledTooFar",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "failureRequiringAppLaunchRideScheduledTooFar"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INRequestRideIntentResponseCodeFailureRequiringAppLaunchRideScheduledTooFar"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INRequestRideIntentResponseCode.failureRequiringAppLaunchRideScheduledTooFar"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "failureRequiringAppLaunchRideScheduledTooFar"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode": {
      "abstract": [
        {
          "text": "Constants indicating the state of the response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRequestRideIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestRideIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INRequestRideIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/inrequestrideintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failure": {
      "abstract": [
        {
          "text": "You were unable to book the ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestRideIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INRequestRideIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/inrequestrideintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [
        {
          "text": "The user must launch your app to book the ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestRideIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INRequestRideIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/inrequestrideintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunchMustVerifyCredentials": {
      "abstract": [
        {
          "text": "The user must launch your app and verify their credentials to continue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunchMustVerifyCredentials"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunchMustVerifyCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestRideIntentResponseCodeFailureRequiringAppLaunchMustVerifyCredentials"
        }
      ],
      "role": "symbol",
      "title": "INRequestRideIntentResponseCode.failureRequiringAppLaunchMustVerifyCredentials",
      "type": "topic",
      "url": "/documentation/intents/inrequestrideintentresponsecode/failurerequiringapplaunchmustverifycredentials"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunchNoServiceInArea": {
      "abstract": [
        {
          "text": "You do not provide rides in the area requested by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunchNoServiceInArea"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunchNoServiceInArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestRideIntentResponseCodeFailureRequiringAppLaunchNoServiceInArea"
        }
      ],
      "role": "symbol",
      "title": "INRequestRideIntentResponseCode.failureRequiringAppLaunchNoServiceInArea",
      "type": "topic",
      "url": "/documentation/intents/inrequestrideintentresponsecode/failurerequiringapplaunchnoserviceinarea"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunchPreviousRideNeedsCompletion": {
      "abstract": [
        {
          "text": "An existing ride is currently in progress and the app can’t book a new ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunchPreviousRideNeedsCompletion"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunchPreviousRideNeedsCompletion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestRideIntentResponseCodeFailureRequiringAppLaunchPreviousRideNeedsCompletion"
        }
      ],
      "role": "symbol",
      "title": "INRequestRideIntentResponseCode.failureRequiringAppLaunchPreviousRideNeedsCompletion",
      "type": "topic",
      "url": "/documentation/intents/inrequestrideintentresponsecode/failurerequiringapplaunchpreviousrideneedscompletion"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunchRideScheduledTooFar": {
      "abstract": [
        {
          "text": "The scheduled ride is out of the ride area and requires the user to open the app to fix the problem.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunchRideScheduledTooFar"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunchRideScheduledTooFar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestRideIntentResponseCodeFailureRequiringAppLaunchRideScheduledTooFar"
        }
      ],
      "role": "symbol",
      "title": "INRequestRideIntentResponseCode.failureRequiringAppLaunchRideScheduledTooFar",
      "type": "topic",
      "url": "/documentation/intents/inrequestrideintentresponsecode/failurerequiringapplaunchridescheduledtoofar"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunchServiceTemporarilyUnavailable": {
      "abstract": [
        {
          "text": "Your service is temporarily unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunchServiceTemporarilyUnavailable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunchServiceTemporarilyUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestRideIntentResponseCodeFailureRequiringAppLaunchServiceTemporarilyUnavailable"
        }
      ],
      "role": "symbol",
      "title": "INRequestRideIntentResponseCode.failureRequiringAppLaunchServiceTemporarilyUnavailable",
      "type": "topic",
      "url": "/documentation/intents/inrequestrideintentresponsecode/failurerequiringapplaunchservicetemporarilyunavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/inProgress": {
      "abstract": [
        {
          "text": "You are in the process of handling the intent.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inProgress"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/inProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestRideIntentResponseCodeInProgress"
        }
      ],
      "role": "symbol",
      "title": "INRequestRideIntentResponseCode.inProgress",
      "type": "topic",
      "url": "/documentation/intents/inrequestrideintentresponsecode/inprogress"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/ready": {
      "abstract": [
        {
          "text": "You are ready to handle the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestRideIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INRequestRideIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/inrequestrideintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/success": {
      "abstract": [
        {
          "text": "You successfully handled the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestRideIntentResponseCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "INRequestRideIntentResponseCode.success",
      "type": "topic",
      "url": "/documentation/intents/inrequestrideintentresponsecode/success"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/unspecified": {
      "abstract": [
        {
          "text": "There is no specified response code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestRideIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INRequestRideIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/inrequestrideintentresponsecode/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/unspecified",
        "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/ready",
        "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/inProgress",
        "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/success",
        "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failure",
        "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunch",
        "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunchMustVerifyCredentials",
        "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunchNoServiceInArea",
        "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunchServiceTemporarilyUnavailable",
        "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunchPreviousRideNeedsCompletion"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INRequestRideIntentResponseCodeFailureRequiringAppLaunchRideScheduledTooFar"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestRideIntentResponseCodeFailureRequiringAppLaunchRideScheduledTooFar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/unspecified",
                "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/ready",
                "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/inProgress",
                "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/success",
                "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failure",
                "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunch",
                "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunchMustVerifyCredentials",
                "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunchNoServiceInArea",
                "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunchServiceTemporarilyUnavailable",
                "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentResponseCode/failureRequiringAppLaunchPreviousRideNeedsCompletion"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INRequestRideIntentResponseCodeFailureRequiringAppLaunchRideScheduledTooFar"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1unspecified/title",
          "value": "INRequestRideIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestRideIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode/title",
          "value": "INRequestRideIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestRideIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestRideIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1failureRequiringAppLaunchMustVerifyCredentials/title",
          "value": "INRequestRideIntentResponseCodeFailureRequiringAppLaunchMustVerifyCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1failureRequiringAppLaunchMustVerifyCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestRideIntentResponseCodeFailureRequiringAppLaunchMustVerifyCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1failureRequiringAppLaunchPreviousRideNeedsCompletion/title",
          "value": "INRequestRideIntentResponseCodeFailureRequiringAppLaunchPreviousRideNeedsCompletion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1failureRequiringAppLaunchPreviousRideNeedsCompletion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestRideIntentResponseCodeFailureRequiringAppLaunchPreviousRideNeedsCompletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1success/title",
          "value": "INRequestRideIntentResponseCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestRideIntentResponseCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INRequestRideIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestRideIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1failure/title",
          "value": "INRequestRideIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestRideIntentResponseCodeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1ready/title",
          "value": "INRequestRideIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestRideIntentResponseCodeReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1failureRequiringAppLaunchNoServiceInArea/title",
          "value": "INRequestRideIntentResponseCodeFailureRequiringAppLaunchNoServiceInArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1failureRequiringAppLaunchNoServiceInArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestRideIntentResponseCodeFailureRequiringAppLaunchNoServiceInArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1failureRequiringAppLaunchServiceTemporarilyUnavailable/title",
          "value": "INRequestRideIntentResponseCodeFailureRequiringAppLaunchServiceTemporarilyUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1failureRequiringAppLaunchServiceTemporarilyUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestRideIntentResponseCodeFailureRequiringAppLaunchServiceTemporarilyUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1inProgress/title",
          "value": "INRequestRideIntentResponseCodeInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1inProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestRideIntentResponseCodeInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1failureRequiringAppLaunchRideScheduledTooFar/title",
          "value": "INRequestRideIntentResponseCodeFailureRequiringAppLaunchRideScheduledTooFar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentResponseCode~1failureRequiringAppLaunchRideScheduledTooFar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestRideIntentResponseCodeFailureRequiringAppLaunchRideScheduledTooFar"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inrequestrideintentresponsecode/failurerequiringapplaunchridescheduledtoofar"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inrequestrideintentresponsecode/failurerequiringapplaunchridescheduledtoofar"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
