{
  "abstract": [
    {
      "text": "The bundle ID for the selected broadcast service.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "No longer supported",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.replaykit/documentation/ReplayKit",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController/broadcastExtensionBundleID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)RPBroadcastController(py)broadcastExtensionBundleID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "broadcastExtensionBundleID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "ReplayKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "broadcastExtensionBundleID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.0",
        "message": "No longer supported",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.0",
        "message": "No longer supported",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "No longer supported",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.0",
        "message": "No longer supported",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "No longer supported",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "broadcastExtensionBundleID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "broadcastExtensionBundleID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit": {
      "abstract": [
        {
          "text": "Record or stream video from the screen, and audio from the app and microphone.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ReplayKit",
      "type": "topic",
      "url": "/documentation/replaykit"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController": {
      "abstract": [
        {
          "text": "An object containing methods for starting and controlling a broadcast.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPBroadcastController"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPBroadcastController"
        }
      ],
      "role": "symbol",
      "title": "RPBroadcastController",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastcontroller"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController/broadcastExtensionBundleID": {
      "abstract": [
        {
          "text": "The bundle ID for the selected broadcast service.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "broadcastExtensionBundleID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController/broadcastExtensionBundleID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "broadcastExtensionBundleID"
        }
      ],
      "role": "symbol",
      "title": "broadcastExtensionBundleID",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastcontroller/broadcastextensionbundleid"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController/isBroadcasting": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the controller is broadcasting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isBroadcasting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController/isBroadcasting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "broadcasting"
        }
      ],
      "role": "symbol",
      "title": "isBroadcasting",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastcontroller/isbroadcasting"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController/isPaused": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the broadcast is paused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPaused"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController/isPaused",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paused"
        }
      ],
      "role": "symbol",
      "title": "isPaused",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastcontroller/ispaused"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Retrieving-Information-About-the-Broadcast",
      "generated": true,
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController/isBroadcasting",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController/isPaused"
      ],
      "title": "Retrieving Information About the Broadcast"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "broadcastExtensionBundleID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "broadcastExtensionBundleID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.replaykit/documentation/ReplayKit",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Retrieving-Information-About-the-Broadcast",
              "generated": true,
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController/isBroadcasting",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController/isPaused"
              ],
              "title": "Retrieving Information About the Broadcast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "broadcastExtensionBundleID"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "broadcastExtensionBundleID"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "No longer supported",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastController~1broadcastExtensionBundleID/title",
          "value": "broadcastExtensionBundleID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastController~1broadcastExtensionBundleID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "broadcastExtensionBundleID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastController~1isPaused/title",
          "value": "paused"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastController~1isPaused/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paused"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastController~1isBroadcasting/title",
          "value": "broadcasting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastController~1isBroadcasting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "broadcasting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastController/title",
          "value": "RPBroadcastController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/replaykit/rpbroadcastcontroller/broadcastextensionbundleid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/replaykit/rpbroadcastcontroller/broadcastextensionbundleid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
