{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"NSTokenFieldDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSTokenFieldDelegate","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTokenFieldDelegate"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"text":"The token field’s delegate","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"Returns the token field’s delegate.","type":"text"}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSTokenField/delegate","interfaceLanguage":"swift"},"metadata":{"platforms":[{"beta":false,"deprecated":false,"unavailable":false,"name":"macOS"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"NSTokenFieldDelegate","preciseIdentifier":"c:objc(pl)NSTokenFieldDelegate"},{"kind":"text","text":")?"}],"modules":[{"name":"AppKit"}],"role":"symbol","externalID":"c:objc(cs)NSTokenField(py)delegate","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"roleHeading":"Instance Property","title":"delegate","symbolKind":"property"},"variants":[{"paths":["/documentation/appkit/nstokenfield/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nstokenfield/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTokenField"]]},"kind":"symbol","references":{"doc://com.apple.appkit/documentation/AppKit/NSTokenFieldDelegate":{"title":"NSTokenFieldDelegate","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTokenFieldDelegate","url":"/documentation/appkit/nstokenfielddelegate","navigatorTitle":[{"kind":"identifier","text":"NSTokenFieldDelegate"}],"abstract":[{"text":"A set of optional methods implemented by delegates of ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTokenField","type":"reference","isActive":true},{"text":" objects.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSTokenFieldDelegate"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSTokenField":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSTokenField","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTokenField","url":"/documentation/appkit/nstokenfield","title":"NSTokenField","role":"symbol","abstract":[{"text":"A text field that converts text into visually distinct tokens.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTokenField","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSTokenField/delegate":{"url":"/documentation/appkit/nstokenfield/delegate","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTokenField/delegate","type":"topic","title":"delegate","kind":"symbol","abstract":[{"type":"text","text":"Returns the token field’s delegate."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSTokenFieldDelegate","text":"NSTokenFieldDelegate"},{"kind":"text","text":")?"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"value":[{"name":"macOS","beta":false,"unavailable":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"delegate","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"delegate","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTokenField"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":null,"op":"add","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)NSTokenFieldDelegate","text":"id<NSTokenFieldDelegate>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":"NSTokenFieldDelegate","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldDelegate/title"},{"value":[{"kind":"identifier","text":"NSTokenFieldDelegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldDelegate/fragments"},{"value":[{"kind":"identifier","text":"NSTokenFieldDelegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldDelegate/navigatorTitle"},{"value":"NSTokenField","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField/title"},{"value":[{"text":"NSTokenField","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField/fragments"},{"value":[{"kind":"identifier","text":"NSTokenField"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField/navigatorTitle"},{"value":"delegate","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField~1delegate/title"},{"value":[{"text":"delegate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField~1delegate/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}