{"seeAlsoSections":[{"title":"Accessing Query Properties","anchor":"Accessing-Query-Properties","generated":true,"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordQueryDescriptor/sourceTypes","doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordQueryDescriptor/predicate"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/healthkit/hkverifiableclinicalrecordquerydescriptor/recordtypes"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordQueryDescriptor"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordQueryDescriptor/recordTypes"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"recordTypes","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@T@HKVerifiableClinicalRecordCredentialType","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType","text":"HKVerifiableClinicalRecordCredentialType","kind":"typeIdentifier"},{"text":"]","kind":"text"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"For a list of valid record types, see ","type":"text"},{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"The types of records returned by this query."}],"metadata":{"modules":[{"name":"HealthKit"}],"title":"recordTypes","externalID":"s:9HealthKit41HKVerifiableClinicalRecordQueryDescriptorV11recordTypesSaySo0cdE14CredentialTypeaGvp","symbolKind":"property","roleHeading":"Instance Property","platforms":[{"introducedAt":"15.4","unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"introducedAt":"15.4","unavailable":false,"beta":false,"name":"iPadOS","deprecated":false},{"introducedAt":"15.4","unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false},{"introducedAt":"13.0","unavailable":false,"beta":false,"name":"macOS","deprecated":false},{"unavailable":false,"beta":false,"name":"visionOS","deprecated":false}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recordTypes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"HKVerifiableClinicalRecordCredentialType","preciseIdentifier":"c:@T@HKVerifiableClinicalRecordCredentialType","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordQueryDescriptor":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKVerifiableClinicalRecordQueryDescriptor"}],"type":"topic","url":"/documentation/healthkit/hkverifiableclinicalrecordquerydescriptor","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKVerifiableClinicalRecordQueryDescriptor"}],"abstract":[{"text":"A query interface that provides one-time access to a SMART Health Card or EU Digital COVID Certificate using Swift concurrency.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordQueryDescriptor","title":"HKVerifiableClinicalRecordQueryDescriptor"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordQueryDescriptor/sourceTypes":{"title":"sourceTypes","kind":"symbol","type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordQueryDescriptor/sourceTypes","url":"/documentation/healthkit/hkverifiableclinicalrecordquerydescriptor/sourcetypes","role":"symbol","abstract":[{"type":"text","text":"The source for the verifiable clinical records, for example from a SMART Health Card or an EU Digital COVID Certificate."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sourceTypes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"HKVerifiableClinicalRecordSourceType","preciseIdentifier":"c:@T@HKVerifiableClinicalRecordSourceType","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKVerifiableClinicalRecordCredentialType"}],"type":"topic","url":"/documentation/healthkit/hkverifiableclinicalrecordcredentialtype","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HKVerifiableClinicalRecordCredentialType"}],"abstract":[{"text":"The type of record returned by a verifiable clinical record query.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordCredentialType","title":"HKVerifiableClinicalRecordCredentialType"},"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordQueryDescriptor/predicate":{"role":"symbol","url":"/documentation/healthkit/hkverifiableclinicalrecordquerydescriptor/predicate","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordQueryDescriptor/predicate","title":"predicate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"predicate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSPredicate","preciseIdentifier":"c:objc(cs)NSPredicate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"A predicate that limits the results returned by the query."}],"kind":"symbol","type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordQueryDescriptor/recordTypes":{"abstract":[{"type":"text","text":"The types of records returned by this query."}],"title":"recordTypes","type":"topic","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordQueryDescriptor/recordTypes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordTypes"},{"text":": [","kind":"text"},{"text":"HKVerifiableClinicalRecordCredentialType","preciseIdentifier":"c:@T@HKVerifiableClinicalRecordCredentialType","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkverifiableclinicalrecordquerydescriptor/recordtypes"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordCredentialType/title","value":"HKVerifiableClinicalRecordCredentialType"},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordCredentialType/fragments","value":[{"kind":"identifier","text":"HKVerifiableClinicalRecordCredentialType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordCredentialType/navigatorTitle","value":[{"kind":"identifier","text":"HKVerifiableClinicalRecordCredentialType"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}