{
  "abstract": [
    {
      "text": "An error occurred during Create ML training due to an invalid transformation or image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNErrorCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNErrorCode/turiCoreErrorCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@VNErrorCode@VNErrorTuriCoreErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "turiCoreErrorCode"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNErrorTuriCoreErrorCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "VNErrorCode.turiCoreErrorCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "turiCoreErrorCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNErrorCode": {
      "abstract": [
        {
          "text": "Constants that identify errors from the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNErrorCode"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNErrorCode"
        }
      ],
      "role": "symbol",
      "title": "VNErrorCode",
      "type": "topic",
      "url": "/documentation/vision/vnerrorcode"
    },
    "doc://com.apple.vision/documentation/Vision/VNErrorCode/OK": {
      "abstract": [
        {
          "text": "The operation finished without error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OK"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNErrorCode/OK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNErrorOK"
        }
      ],
      "role": "symbol",
      "title": "VNErrorCode.OK",
      "type": "topic",
      "url": "/documentation/vision/vnerrorcode/ok"
    },
    "doc://com.apple.vision/documentation/Vision/VNErrorCode/dataUnavailable": {
      "abstract": [
        {
          "text": "The data isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataUnavailable"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNErrorCode/dataUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNErrorDataUnavailable"
        }
      ],
      "role": "symbol",
      "title": "VNErrorCode.dataUnavailable",
      "type": "topic",
      "url": "/documentation/vision/vnerrorcode/dataunavailable"
    },
    "doc://com.apple.vision/documentation/Vision/VNErrorCode/internalError": {
      "abstract": [
        {
          "text": "An internal error occurred within the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNErrorCode/internalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNErrorInternalError"
        }
      ],
      "role": "symbol",
      "title": "VNErrorCode.internalError",
      "type": "topic",
      "url": "/documentation/vision/vnerrorcode/internalerror"
    },
    "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidArgument": {
      "abstract": [
        {
          "text": "An app passed an invalid parameter to a request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidArgument"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNErrorInvalidArgument"
        }
      ],
      "role": "symbol",
      "title": "VNErrorCode.invalidArgument",
      "type": "topic",
      "url": "/documentation/vision/vnerrorcode/invalidargument"
    },
    "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidFormat": {
      "abstract": [
        {
          "text": "The format of the image is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidFormat"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNErrorInvalidFormat"
        }
      ],
      "role": "symbol",
      "title": "VNErrorCode.invalidFormat",
      "type": "topic",
      "url": "/documentation/vision/vnerrorcode/invalidformat"
    },
    "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidImage": {
      "abstract": [
        {
          "text": "The image is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidImage"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNErrorInvalidImage"
        }
      ],
      "role": "symbol",
      "title": "VNErrorCode.invalidImage",
      "type": "topic",
      "url": "/documentation/vision/vnerrorcode/invalidimage"
    },
    "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidModel": {
      "abstract": [
        {
          "text": "The Core ML model is incompatible with the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidModel"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNErrorInvalidModel"
        }
      ],
      "role": "symbol",
      "title": "VNErrorCode.invalidModel",
      "type": "topic",
      "url": "/documentation/vision/vnerrorcode/invalidmodel"
    },
    "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidOperation": {
      "abstract": [
        {
          "text": "An app requested an unsupported operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidOperation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNErrorInvalidOperation"
        }
      ],
      "role": "symbol",
      "title": "VNErrorCode.invalidOperation",
      "type": "topic",
      "url": "/documentation/vision/vnerrorcode/invalidoperation"
    },
    "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidOption": {
      "abstract": [
        {
          "text": "An app specified an invalid option on a request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidOption"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNErrorInvalidOption"
        }
      ],
      "role": "symbol",
      "title": "VNErrorCode.invalidOption",
      "type": "topic",
      "url": "/documentation/vision/vnerrorcode/invalidoption"
    },
    "doc://com.apple.vision/documentation/Vision/VNErrorCode/ioError": {
      "abstract": [
        {
          "text": "An I/O error for an image, image sequence, or Core ML model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ioError"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNErrorCode/ioError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNErrorIOError"
        }
      ],
      "role": "symbol",
      "title": "VNErrorCode.ioError",
      "type": "topic",
      "url": "/documentation/vision/vnerrorcode/ioerror"
    },
    "doc://com.apple.vision/documentation/Vision/VNErrorCode/missingOption": {
      "abstract": [
        {
          "text": "A request is missing a required option.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingOption"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNErrorCode/missingOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNErrorMissingOption"
        }
      ],
      "role": "symbol",
      "title": "VNErrorCode.missingOption",
      "type": "topic",
      "url": "/documentation/vision/vnerrorcode/missingoption"
    },
    "doc://com.apple.vision/documentation/Vision/VNErrorCode/notImplemented": {
      "abstract": [
        {
          "text": "The method isn’t implemented in the underlying model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notImplemented"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNErrorCode/notImplemented",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNErrorNotImplemented"
        }
      ],
      "role": "symbol",
      "title": "VNErrorCode.notImplemented",
      "type": "topic",
      "url": "/documentation/vision/vnerrorcode/notimplemented"
    },
    "doc://com.apple.vision/documentation/Vision/VNErrorCode/operationFailed": {
      "abstract": [
        {
          "text": "The requested operation failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationFailed"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNErrorCode/operationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNErrorOperationFailed"
        }
      ],
      "role": "symbol",
      "title": "VNErrorCode.operationFailed",
      "type": "topic",
      "url": "/documentation/vision/vnerrorcode/operationfailed"
    },
    "doc://com.apple.vision/documentation/Vision/VNErrorCode/outOfBoundsError": {
      "abstract": [
        {
          "text": "An app attempted to access data that’s out-of-bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outOfBoundsError"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNErrorCode/outOfBoundsError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNErrorOutOfBoundsError"
        }
      ],
      "role": "symbol",
      "title": "VNErrorCode.outOfBoundsError",
      "type": "topic",
      "url": "/documentation/vision/vnerrorcode/outofboundserror"
    },
    "doc://com.apple.vision/documentation/Vision/VNErrorCode/outOfMemory": {
      "abstract": [
        {
          "text": "The system doesn’t have enough memory to complete the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outOfMemory"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNErrorCode/outOfMemory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNErrorOutOfMemory"
        }
      ],
      "role": "symbol",
      "title": "VNErrorCode.outOfMemory",
      "type": "topic",
      "url": "/documentation/vision/vnerrorcode/outofmemory"
    },
    "doc://com.apple.vision/documentation/Vision/VNErrorCode/turiCoreErrorCode": {
      "abstract": [
        {
          "text": "An error occurred during Create ML training due to an invalid transformation or image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "turiCoreErrorCode"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNErrorCode/turiCoreErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNErrorTuriCoreErrorCode"
        }
      ],
      "role": "symbol",
      "title": "VNErrorCode.turiCoreErrorCode",
      "type": "topic",
      "url": "/documentation/vision/vnerrorcode/turicoreerrorcode"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNErrorCode/OK",
        "doc://com.apple.vision/documentation/Vision/VNErrorCode/dataUnavailable",
        "doc://com.apple.vision/documentation/Vision/VNErrorCode/internalError",
        "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidArgument",
        "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidFormat",
        "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidImage",
        "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidModel",
        "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidOperation",
        "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidOption",
        "doc://com.apple.vision/documentation/Vision/VNErrorCode/ioError",
        "doc://com.apple.vision/documentation/Vision/VNErrorCode/missingOption",
        "doc://com.apple.vision/documentation/Vision/VNErrorCode/notImplemented",
        "doc://com.apple.vision/documentation/Vision/VNErrorCode/operationFailed",
        "doc://com.apple.vision/documentation/Vision/VNErrorCode/outOfBoundsError",
        "doc://com.apple.vision/documentation/Vision/VNErrorCode/outOfMemory"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNErrorTuriCoreErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNErrorTuriCoreErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision",
                "doc://com.apple.vision/documentation/Vision/VNErrorCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNErrorCode/OK",
                "doc://com.apple.vision/documentation/Vision/VNErrorCode/dataUnavailable",
                "doc://com.apple.vision/documentation/Vision/VNErrorCode/internalError",
                "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidArgument",
                "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidFormat",
                "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidImage",
                "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidModel",
                "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidOperation",
                "doc://com.apple.vision/documentation/Vision/VNErrorCode/invalidOption",
                "doc://com.apple.vision/documentation/Vision/VNErrorCode/ioError",
                "doc://com.apple.vision/documentation/Vision/VNErrorCode/missingOption",
                "doc://com.apple.vision/documentation/Vision/VNErrorCode/notImplemented",
                "doc://com.apple.vision/documentation/Vision/VNErrorCode/operationFailed",
                "doc://com.apple.vision/documentation/Vision/VNErrorCode/outOfBoundsError",
                "doc://com.apple.vision/documentation/Vision/VNErrorCode/outOfMemory"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "VNErrorTuriCoreErrorCode"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1invalidImage/title",
          "value": "VNErrorInvalidImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1invalidImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNErrorInvalidImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode/title",
          "value": "VNErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1invalidModel/title",
          "value": "VNErrorInvalidModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1invalidModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNErrorInvalidModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1missingOption/title",
          "value": "VNErrorMissingOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1missingOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNErrorMissingOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1OK/title",
          "value": "VNErrorOK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1OK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNErrorOK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1invalidFormat/title",
          "value": "VNErrorInvalidFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1invalidFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNErrorInvalidFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1turiCoreErrorCode/title",
          "value": "VNErrorTuriCoreErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1turiCoreErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNErrorTuriCoreErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1invalidOperation/title",
          "value": "VNErrorInvalidOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1invalidOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNErrorInvalidOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1dataUnavailable/title",
          "value": "VNErrorDataUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1dataUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNErrorDataUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1invalidArgument/title",
          "value": "VNErrorInvalidArgument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1invalidArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNErrorInvalidArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1internalError/title",
          "value": "VNErrorInternalError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1internalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNErrorInternalError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1ioError/title",
          "value": "VNErrorIOError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1ioError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNErrorIOError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1outOfBoundsError/title",
          "value": "VNErrorOutOfBoundsError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1outOfBoundsError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNErrorOutOfBoundsError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1operationFailed/title",
          "value": "VNErrorOperationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1operationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNErrorOperationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1outOfMemory/title",
          "value": "VNErrorOutOfMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1outOfMemory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNErrorOutOfMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1notImplemented/title",
          "value": "VNErrorNotImplemented"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1notImplemented/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNErrorNotImplemented"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1invalidOption/title",
          "value": "VNErrorInvalidOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNErrorCode~1invalidOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNErrorInvalidOption"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnerrorcode/turicoreerrorcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnerrorcode/turicoreerrorcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
