{
  "abstract": [
    {
      "text": "A task that uses captured speech for short, confirmation-style requests.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.speech/documentation/Speech",
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskHint"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskHint/confirmation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SFSpeechRecognitionTaskHint@SFSpeechRecognitionTaskHintConfirmation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "confirmation"
      }
    ],
    "modules": [
      {
        "name": "Speech"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SFSpeechRecognitionTaskHintConfirmation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SFSpeechRecognitionTaskHint.confirmation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "confirmation"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this hint type when you are using speech recognition to handle confirmation commands, such as “yes,” “no,” or “maybe.”",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.speech/documentation/Speech": {
      "abstract": [
        {
          "text": "Perform speech recognition on live or prerecorded audio, and receive transcriptions, alternative interpretations, and confidence levels of the results.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech",
      "kind": "symbol",
      "role": "collection",
      "title": "Speech",
      "type": "topic",
      "url": "/documentation/speech"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskHint": {
      "abstract": [
        {
          "text": "The type of task for which you are using speech recognition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionTaskHint"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskHint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionTaskHint"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognitionTaskHint",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognitiontaskhint"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskHint/confirmation": {
      "abstract": [
        {
          "text": "A task that uses captured speech for short, confirmation-style requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirmation"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskHint/confirmation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionTaskHintConfirmation"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognitionTaskHint.confirmation",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognitiontaskhint/confirmation"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskHint/dictation": {
      "abstract": [
        {
          "text": "A task that uses captured speech for text entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dictation"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskHint/dictation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionTaskHintDictation"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognitionTaskHint.dictation",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognitiontaskhint/dictation"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskHint/search": {
      "abstract": [
        {
          "text": "A task that uses captured speech to specify search terms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "search"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskHint/search",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionTaskHintSearch"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognitionTaskHint.search",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognitiontaskhint/search"
    },
    "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskHint/unspecified": {
      "abstract": [
        {
          "text": "An unspecified type of task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskHint/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSpeechRecognitionTaskHintUnspecified"
        }
      ],
      "role": "symbol",
      "title": "SFSpeechRecognitionTaskHint.unspecified",
      "type": "topic",
      "url": "/documentation/speech/sfspeechrecognitiontaskhint/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Hints",
      "generated": true,
      "identifiers": [
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskHint/unspecified",
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskHint/dictation",
        "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskHint/search"
      ],
      "title": "Hints"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SFSpeechRecognitionTaskHintConfirmation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionTaskHintConfirmation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.speech/documentation/Speech",
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskHint"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Hints",
              "generated": true,
              "identifiers": [
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskHint/unspecified",
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskHint/dictation",
                "doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskHint/search"
              ],
              "title": "Hints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SFSpeechRecognitionTaskHintConfirmation"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskHint~1unspecified/title",
          "value": "SFSpeechRecognitionTaskHintUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskHint~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionTaskHintUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskHint/title",
          "value": "SFSpeechRecognitionTaskHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskHint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionTaskHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskHint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionTaskHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskHint~1confirmation/title",
          "value": "SFSpeechRecognitionTaskHintConfirmation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskHint~1confirmation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionTaskHintConfirmation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskHint~1dictation/title",
          "value": "SFSpeechRecognitionTaskHintDictation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskHint~1dictation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionTaskHintDictation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskHint~1search/title",
          "value": "SFSpeechRecognitionTaskHintSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskHint~1search/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSpeechRecognitionTaskHintSearch"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/speech/sfspeechrecognitiontaskhint/confirmation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/speech/sfspeechrecognitiontaskhint/confirmation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
