{"metadata":{"navigatorTitle":[{"text":"addTrackingRect:owner:userData:assumeInside:","kind":"identifier"}],"extendedModule":"AppKit","modules":[{"name":"AppKit"}],"roleHeading":"Instance Method","title":"addTrackingRect(_:owner:userData:assumeInside:)","externalID":"c:objc(cs)NSView(im)addTrackingRect:owner:userData:assumeInside:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrackingRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"text":", ","kind":"text"},{"text":"owner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":", ","kind":"text"},{"text":"userData","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutableRawPointer","kind":"typeIdentifier","preciseIdentifier":"s:Sv"},{"text":"?, ","kind":"text"},{"text":"assumeInside","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"NSView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView"},{"text":".","kind":"text"},{"text":"TrackingRectTag","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTrackingRectTag"}],"platforms":[{"beta":false,"unavailable":false,"deprecated":false,"name":"macOS"}],"role":"symbol","symbolKind":"method"},"kind":"symbol","sections":[],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSView/addTrackingRect(_:owner:userData:assumeInside:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSView"]]},"abstract":[{"text":"Establishes  an area for tracking mouse-entered and mouse-exited events within the view and returns a tag that identifies the tracking rectangle.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSView/addTrackingArea(_:)","doc://com.apple.appkit/documentation/AppKit/NSEvent/userData"],"anchor":"Related-Documentation"},{"title":"Managing Tracking Rectangles","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSView/removeTrackingRect(_:)","doc://com.apple.appkit/documentation/AppKit/NSView/TrackingRectTag"],"anchor":"Managing-Tracking-Rectangles","generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTrackingRect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rect"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier","text":"NSRect","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"owner"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userData"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sv","kind":"typeIdentifier","text":"UnsafeMutableRawPointer","identifier":"doc://com.externally.resolved.symbol/s:Sv"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"assumeInside"},{"kind":"text","text":" "},{"kind":"internalParam","text":"flag"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSView","kind":"typeIdentifier","text":"NSView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSTrackingRectTag","kind":"typeIdentifier","text":"TrackingRectTag","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/TrackingRectTag"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A rectangle that defines a region of the view for tracking mouse-entered and mouse-exited events."}],"type":"paragraph"}],"name":"rect"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The object that gets sent the event messages. It can be the view itself or some other object (such as an NSCursor or a custom drawing tool object), as long as it responds to both "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseEntered(with:)","isActive":true},{"type":"text","text":" and "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseExited(with:)","isActive":true},{"type":"text","text":"."}]}],"name":"owner"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Data stored in the "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","isActive":true},{"type":"text","text":" object for each tracking event."}]}],"name":"data"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true"},{"type":"text","text":", the first event will be generated when the cursor leaves "},{"type":"codeVoice","code":"aRect"},{"type":"text","text":", regardless if the cursor is inside "},{"type":"codeVoice","code":"aRect"},{"type":"text","text":" when the tracking rectangle is added. If "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false"},{"type":"text","text":" the first event will be generated when the cursor leaves "},{"type":"codeVoice","code":"aRect"},{"type":"text","text":" if the cursor is initially inside "},{"type":"codeVoice","code":"aRect"},{"type":"text","text":", or when the cursor enters "},{"type":"codeVoice","code":"aRect"},{"type":"text","text":" if the cursor is initially outside "},{"type":"codeVoice","code":"aRect"},{"type":"text","text":".  You usually want to set this flag to "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false"},{"type":"text","text":"."}]}],"name":"flag"}]},{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A tag that identifies the tracking rectangle. It is stored in the associated "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","isActive":true,"type":"reference"},{"type":"text","text":" objects and can be used to remove the tracking rectangle."}]}],"kind":"content"},{"content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Tracking rectangles provide a general mechanism that can be used to trigger actions based on the cursor location (for example, a status bar or hint field that provides information on the item the cursor lies over). To simply change the cursor over a particular area, use ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/addCursorRect(_:cursor:)","isActive":true,"type":"reference"},{"text":". If you must use tracking rectangles to change the cursor, the ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor","isActive":true,"type":"reference"},{"text":" class specification describes the additional methods that must be invoked to change cursors by using tracking rectangles.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"In macOS 10.5 and later, tracking areas provide a greater range of functionality (see ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/addTrackingArea(_:)"},{"text":").","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["/documentation/appkit/nsview/addtrackingrect(_:owner:userdata:assumeinside:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsview/addtrackingrect(_:owner:userdata:assumeinside:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSEvent":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSEvent"}],"role":"symbol","type":"topic","title":"NSEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSEvent"}],"abstract":[{"type":"text","text":"An object that contains information about an input action, such as a mouse click or a key press."}],"url":"/documentation/appkit/nsevent"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseEntered(with:)":{"abstract":[{"text":"Informs the receiver that the cursor has entered a tracking rectangle.","type":"text"}],"navigatorTitle":[{"text":"mouseEntered:","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseEntered(with:)","url":"/documentation/appkit/nsresponder/mouseentered(with:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseEntered","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"mouseEntered(with:)"},"doc://com.externally.resolved.symbol/c:@T@NSRect":{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","role":"symbol","type":"topic","url":"/documentation/foundation/nsrect","abstract":[{"text":"A rectangle.","type":"text"}],"fragments":[{"text":"typealias ","kind":"text"},{"text":"NSRect","kind":"identifier"}],"title":"NSRect","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSView":{"abstract":[{"text":"The infrastructure for drawing, printing, and handling events in an app.","type":"text"}],"url":"/documentation/appkit/nsview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","title":"NSView","navigatorTitle":[{"kind":"identifier","text":"NSView"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSView/addTrackingRect(_:owner:userData:assumeInside:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/addTrackingRect(_:owner:userData:assumeInside:)","abstract":[{"type":"text","text":"Establishes  an area for tracking mouse-entered and mouse-exited events within the view and returns a tag that identifies the tracking rectangle."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTrackingRect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","text":"NSRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"owner"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"assumeInside"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","text":"NSView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTrackingRectTag","text":"TrackingRectTag"}],"title":"addTrackingRect(_:owner:userData:assumeInside:)","url":"/documentation/appkit/nsview/addtrackingrect(_:owner:userdata:assumeinside:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addTrackingRect:owner:userData:assumeInside:"}]},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSView/addCursorRect(_:cursor:)":{"url":"/documentation/appkit/nsview/addcursorrect(_:cursor:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"addCursorRect:cursor:"}],"role":"symbol","type":"topic","title":"addCursorRect(_:cursor:)","abstract":[{"type":"text","text":"Establishes  the cursor to be used when the mouse pointer lies within a specified region."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCursorRect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","text":"NSRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cursor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCursor","text":"NSCursor"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/addCursorRect(_:cursor:)"},"doc://com.apple.appkit/documentation/AppKit/NSView/TrackingRectTag":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"TrackingRectTag"}],"url":"/documentation/appkit/nsview/trackingrecttag","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/TrackingRectTag","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TrackingRectTag"}],"type":"topic","abstract":[{"text":"This type describes the rectangle used to track the mouse.","type":"text"}],"title":"NSView.TrackingRectTag"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.externally.resolved.symbol/s:Sv":{"role":"symbol","abstract":[{"type":"text","text":"A raw pointer for accessing and manipulating untyped data."}],"title":"UnsafeMutableRawPointer","kind":"symbol","url":"/documentation/Swift/UnsafeMutableRawPointer","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnsafeMutableRawPointer","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:Sv","type":"topic"},"doc://com.apple.documentation/documentation/swift/false":{"title":"false","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/false","role":"symbol","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","url":"/documentation/swift/false"},"doc://com.apple.appkit/documentation/AppKit/NSView/removeTrackingRect(_:)":{"type":"topic","role":"symbol","title":"removeTrackingRect(_:)","url":"/documentation/appkit/nsview/removetrackingrect(_:)","navigatorTitle":[{"kind":"identifier","text":"removeTrackingRect:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/removeTrackingRect(_:)","kind":"symbol","abstract":[{"type":"text","text":"Removes the tracking rectangle identified by a tag."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeTrackingRect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSView","preciseIdentifier":"c:objc(cs)NSView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"TrackingRectTag","preciseIdentifier":"c:@T@NSTrackingRectTag"},{"kind":"text","text":")"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent/userData":{"title":"userData","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent/userData","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UnsafeMutableRawPointer","kind":"typeIdentifier","preciseIdentifier":"s:Sv"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The data associated with a mouse-tracking event."}],"kind":"symbol","navigatorTitle":[{"text":"userData","kind":"identifier"}],"url":"/documentation/appkit/nsevent/userdata"},"doc://com.apple.appkit/documentation/AppKit/NSView/addTrackingArea(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTrackingArea"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSTrackingArea","kind":"typeIdentifier","text":"NSTrackingArea"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","abstract":[{"text":"Adds a given tracking area to the view.","type":"text"}],"url":"/documentation/appkit/nsview/addtrackingarea(_:)","navigatorTitle":[{"kind":"identifier","text":"addTrackingArea:"}],"title":"addTrackingArea(_:)","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/addTrackingArea(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseExited(with:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseExited","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":")","kind":"text"}],"url":"/documentation/appkit/nsresponder/mouseexited(with:)","title":"mouseExited(with:)","abstract":[{"text":"Informs the receiver that the cursor has exited a tracking rectangle.","type":"text"}],"navigatorTitle":[{"text":"mouseExited:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseExited(with:)","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCursor":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCursor"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor","navigatorTitle":[{"kind":"identifier","text":"NSCursor"}],"abstract":[{"text":"A pointer (also called a cursor).","type":"text"}],"type":"topic","title":"NSCursor","url":"/documentation/appkit/nscursor"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"beta":false,"unavailable":false,"name":"macOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"addTrackingRect:owner:userData:assumeInside:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addTrackingRect:owner:userData:assumeInside:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSView"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSView/addTrackingArea(_:)","doc://com.apple.appkit/documentation/AppKit/NSEvent/userData"]},{"anchor":"Managing-Tracking-Rectangles","title":"Managing Tracking Rectangles","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSView/removeTrackingRect(_:)","doc://com.apple.appkit/documentation/AppKit/NSView/TrackingRectTag"],"generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@NSTrackingRectTag","kind":"typeIdentifier","text":"NSTrackingRectTag","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/TrackingRectTag"},{"kind":"text","text":") "},{"kind":"identifier","text":"addTrackingRect:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier","text":"NSRect","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"rect"},{"kind":"text","text":" "},{"kind":"identifier","text":"owner:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"owner"},{"kind":"text","text":" "},{"kind":"identifier","text":"userData:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"data"},{"kind":"text","text":" "},{"kind":"identifier","text":"assumeInside:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"flag"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":{"parameters":[{"name":"rect","content":[{"inlineContent":[{"text":"A rectangle that defines a region of the view for tracking mouse-entered and mouse-exited events.","type":"text"}],"type":"paragraph"}]},{"name":"owner","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The object that gets sent the event messages. It can be the view itself or some other object (such as an NSCursor or a custom drawing tool object), as long as it responds to both "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseEntered(with:)"},{"type":"text","text":" and "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseExited(with:)"},{"type":"text","text":"."}]}]},{"name":"data","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Data stored in the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent"},{"type":"text","text":" object for each tracking event."}]}]},{"name":"flag","content":[{"type":"paragraph","inlineContent":[{"text":"If ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true"},{"text":", the first event will be generated when the cursor leaves ","type":"text"},{"code":"aRect","type":"codeVoice"},{"text":", regardless if the cursor is inside ","type":"text"},{"code":"aRect","type":"codeVoice"},{"text":" when the tracking rectangle is added. If ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false"},{"text":" the first event will be generated when the cursor leaves ","type":"text"},{"code":"aRect","type":"codeVoice"},{"text":" if the cursor is initially inside ","type":"text"},{"code":"aRect","type":"codeVoice"},{"text":", or when the cursor enters ","type":"text"},{"code":"aRect","type":"codeVoice"},{"text":" if the cursor is initially outside ","type":"text"},{"code":"aRect","type":"codeVoice"},{"text":".  You usually want to set this flag to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false"},{"text":".","type":"text"}]}]}],"kind":"parameters"},"path":"/primaryContentSections/1"},{"path":"/primaryContentSections/2","op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"A tag that identifies the tracking rectangle. It is stored in the associated "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent"},{"type":"text","text":" objects and can be used to remove the tracking rectangle."}],"type":"paragraph"}]}},{"op":"replace","value":"NSEvent","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title"},{"op":"replace","value":[{"text":"NSEvent","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments"},{"op":"replace","value":[{"text":"NSEvent","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle"},{"op":"replace","value":"mouseEntered:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseEntered(with:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mouseEntered:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseEntered(with:)/fragments"},{"op":"replace","value":"NSView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title"},{"op":"replace","value":[{"text":"NSView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments"},{"op":"replace","value":[{"text":"NSView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle"},{"op":"replace","value":"addTrackingRect:owner:userData:assumeInside:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1addTrackingRect(_:owner:userData:assumeInside:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addTrackingRect:owner:userData:assumeInside:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1addTrackingRect(_:owner:userData:assumeInside:)/fragments"},{"op":"replace","value":"addCursorRect:cursor:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1addCursorRect(_:cursor:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCursorRect:cursor:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1addCursorRect(_:cursor:)/fragments"},{"op":"replace","value":"NSTrackingRectTag","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1TrackingRectTag/title"},{"op":"replace","value":[{"text":"NSTrackingRectTag","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1TrackingRectTag/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSTrackingRectTag"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1TrackingRectTag/navigatorTitle"},{"op":"replace","value":"removeTrackingRect:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1removeTrackingRect(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeTrackingRect:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1removeTrackingRect(_:)/fragments"},{"op":"replace","value":"userData","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1userData/title"},{"op":"replace","value":[{"kind":"identifier","text":"userData"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1userData/fragments"},{"op":"replace","value":"addTrackingArea:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1addTrackingArea(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addTrackingArea:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1addTrackingArea(_:)/fragments"},{"op":"replace","value":"mouseExited:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseExited(with:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"mouseExited:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseExited(with:)/fragments"},{"op":"replace","value":"NSCursor","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSCursor"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSCursor"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}