{
  "abstract": [
    {
      "text": "A layout anchor representing the baseline for the topmost line of text in the view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSView/firstBaselineAnchor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:objc(cs)NSView(py)firstBaselineAnchor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "firstBaselineAnchor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSLayoutYAxisAnchor",
        "text": "NSLayoutYAxisAnchor"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "firstBaselineAnchor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "firstBaselineAnchor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "firstBaselineAnchor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutYAxisAnchor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSLayoutYAxisAnchor",
              "text": "NSLayoutYAxisAnchor"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For views with multiple lines of text, this anchor represents the baseline of the top row of text. Use this anchor to create constraints with this baseline. You can only combine this anchor with other ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/NSLayoutYAxisAnchor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " anchors. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/NSLayoutAnchor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutYAxisAnchor": {
      "abstract": [
        {
          "text": "A factory class for creating vertical layout constraint objects using a fluent API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutYAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutYAxisAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutYAxisAnchor"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutYAxisAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutyaxisanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/bottomAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the bottom edge of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutYAxisAnchor",
          "text": "NSLayoutYAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/bottomAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bottomAnchor"
        }
      ],
      "role": "symbol",
      "title": "bottomAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nsview/bottomanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/centerXAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the horizontal center of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerXAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutXAxisAnchor",
          "text": "NSLayoutXAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/centerXAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "centerXAnchor"
        }
      ],
      "role": "symbol",
      "title": "centerXAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nsview/centerxanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/centerYAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the vertical center of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerYAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutYAxisAnchor",
          "text": "NSLayoutYAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/centerYAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "centerYAnchor"
        }
      ],
      "role": "symbol",
      "title": "centerYAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nsview/centeryanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/firstBaselineAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the baseline for the topmost line of text in the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "firstBaselineAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutYAxisAnchor",
          "text": "NSLayoutYAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/firstBaselineAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "firstBaselineAnchor"
        }
      ],
      "role": "symbol",
      "title": "firstBaselineAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nsview/firstbaselineanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/heightAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the height of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heightAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutDimension",
          "text": "NSLayoutDimension"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/heightAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "heightAnchor"
        }
      ],
      "role": "symbol",
      "title": "heightAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nsview/heightanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/lastBaselineAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the baseline for the bottommost line of text in the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastBaselineAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutYAxisAnchor",
          "text": "NSLayoutYAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/lastBaselineAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lastBaselineAnchor"
        }
      ],
      "role": "symbol",
      "title": "lastBaselineAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nsview/lastbaselineanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/leadingAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the leading edge of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leadingAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutXAxisAnchor",
          "text": "NSLayoutXAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/leadingAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leadingAnchor"
        }
      ],
      "role": "symbol",
      "title": "leadingAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nsview/leadinganchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/leftAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the left edge of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutXAxisAnchor",
          "text": "NSLayoutXAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/leftAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leftAnchor"
        }
      ],
      "role": "symbol",
      "title": "leftAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nsview/leftanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rightAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the right edge of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutXAxisAnchor",
          "text": "NSLayoutXAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rightAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rightAnchor"
        }
      ],
      "role": "symbol",
      "title": "rightAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rightanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/topAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the top edge of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutYAxisAnchor",
          "text": "NSLayoutYAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/topAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "topAnchor"
        }
      ],
      "role": "symbol",
      "title": "topAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nsview/topanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/trailingAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the trailing edge of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailingAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutXAxisAnchor",
          "text": "NSLayoutXAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/trailingAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trailingAnchor"
        }
      ],
      "role": "symbol",
      "title": "trailingAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nsview/trailinganchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/widthAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the width of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widthAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutDimension",
          "text": "NSLayoutDimension"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/widthAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "widthAnchor"
        }
      ],
      "role": "symbol",
      "title": "widthAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nsview/widthanchor"
    },
    "doc://com.apple.documentation/documentation/UIKit/NSLayoutAnchor": {
      "abstract": [
        {
          "text": "A factory class for creating layout constraint objects using a fluent API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutAnchor"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "AnchorType"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "AnchorType"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/NSLayoutAnchor",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLayoutAnchor",
      "type": "topic",
      "url": "/documentation/UIKit/NSLayoutAnchor"
    },
    "doc://com.apple.documentation/documentation/UIKit/NSLayoutYAxisAnchor": {
      "abstract": [
        {
          "text": "A factory class for creating vertical layout constraint objects using a fluent API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutYAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/NSLayoutYAxisAnchor",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLayoutYAxisAnchor",
      "type": "topic",
      "url": "/documentation/UIKit/NSLayoutYAxisAnchor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Constraints-Using-Layout-Anchors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/bottomAnchor",
        "doc://com.apple.appkit/documentation/AppKit/NSView/centerXAnchor",
        "doc://com.apple.appkit/documentation/AppKit/NSView/centerYAnchor",
        "doc://com.apple.appkit/documentation/AppKit/NSView/heightAnchor",
        "doc://com.apple.appkit/documentation/AppKit/NSView/lastBaselineAnchor",
        "doc://com.apple.appkit/documentation/AppKit/NSView/leadingAnchor",
        "doc://com.apple.appkit/documentation/AppKit/NSView/leftAnchor",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rightAnchor",
        "doc://com.apple.appkit/documentation/AppKit/NSView/topAnchor",
        "doc://com.apple.appkit/documentation/AppKit/NSView/trailingAnchor",
        "doc://com.apple.appkit/documentation/AppKit/NSView/widthAnchor"
      ],
      "title": "Creating Constraints Using Layout Anchors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "firstBaselineAnchor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "firstBaselineAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Constraints-Using-Layout-Anchors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/bottomAnchor",
                "doc://com.apple.appkit/documentation/AppKit/NSView/centerXAnchor",
                "doc://com.apple.appkit/documentation/AppKit/NSView/centerYAnchor",
                "doc://com.apple.appkit/documentation/AppKit/NSView/heightAnchor",
                "doc://com.apple.appkit/documentation/AppKit/NSView/lastBaselineAnchor",
                "doc://com.apple.appkit/documentation/AppKit/NSView/leadingAnchor",
                "doc://com.apple.appkit/documentation/AppKit/NSView/leftAnchor",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rightAnchor",
                "doc://com.apple.appkit/documentation/AppKit/NSView/topAnchor",
                "doc://com.apple.appkit/documentation/AppKit/NSView/trailingAnchor",
                "doc://com.apple.appkit/documentation/AppKit/NSView/widthAnchor"
              ],
              "title": "Creating Constraints Using Layout Anchors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutYAxisAnchor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSLayoutYAxisAnchor",
                    "text": "NSLayoutYAxisAnchor"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "firstBaselineAnchor"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1lastBaselineAnchor/title",
          "value": "lastBaselineAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1lastBaselineAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lastBaselineAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1centerXAnchor/title",
          "value": "centerXAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1centerXAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "centerXAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1widthAnchor/title",
          "value": "widthAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1widthAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "widthAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1leftAnchor/title",
          "value": "leftAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1leftAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leftAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rightAnchor/title",
          "value": "rightAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rightAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rightAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutYAxisAnchor/title",
          "value": "NSLayoutYAxisAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutYAxisAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutYAxisAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutYAxisAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutYAxisAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1bottomAnchor/title",
          "value": "bottomAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1bottomAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bottomAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1leadingAnchor/title",
          "value": "leadingAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1leadingAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leadingAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1centerYAnchor/title",
          "value": "centerYAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1centerYAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "centerYAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1NSLayoutYAxisAnchor/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSLayoutYAxisAnchor"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSLayoutAnchor",
              "text": "NSLayoutAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1trailingAnchor/title",
          "value": "trailingAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1trailingAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trailingAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1heightAnchor/title",
          "value": "heightAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1heightAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "heightAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1firstBaselineAnchor/title",
          "value": "firstBaselineAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1firstBaselineAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "firstBaselineAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1topAnchor/title",
          "value": "topAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1topAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "topAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1NSLayoutAnchor/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSLayoutAnchor"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsview/firstbaselineanchor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsview/firstbaselineanchor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
