{
  "abstract": [
    {
      "text": "The type of focus ring drawn around the view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSView/focusRingType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:objc(cs)NSView(py)focusRingType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "focusRingType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSFocusRingType",
        "text": "NSFocusRingType"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "focusRingType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "focusRingType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "focusRingType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFocusRingType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSFocusRingType",
              "text": "NSFocusRingType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "code": "enum",
              "type": "codeVoice"
            },
            {
              "text": " constant identifying a type of focus ring. Possible values are listed in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFocusRingType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this property to specify the type of focus ring to draw. For a list of possible values, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFocusRingType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To disable drawing of a view’s focus ring, set the value of this property to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFocusRingType/none",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You should only disable the default drawing of a view’s focus ring when you want the view to draw its own focus ring. For example, you might disable focus ring drawing when the view uses its background color to indicate focus or when the view does not have sufficient space to display a focus ring.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Changing the value in this property does not cause the view to draw the actual focus ring. You are responsible for drawing the focus ring in your view’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/draw(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method whenever your view is made the first responder.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To ensure the correct redrawing of focus rings, note that AppKit may automatically draw parts of a window in addition to those that are marked as needing display. For example, AppKit may redraw parts of the first responder view in an app’s key window, if that view’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/focusRingType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property is set to a value other than ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFocusRingType/none",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". If your view can become first responder, but doesn’t draw a focus ring, set ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/focusRingType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFocusRingType/none",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to prevent AppKit from unnecessarily redrawing the view’s focus ring.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFocusRingType": {
      "abstract": [
        {
          "text": "Constants that describe the style of the focus ring.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFocusRingType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFocusRingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFocusRingType"
        }
      ],
      "role": "symbol",
      "title": "NSFocusRingType",
      "type": "topic",
      "url": "/documentation/appkit/nsfocusringtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFocusRingType/none": {
      "abstract": [
        {
          "text": "No focus ring.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFocusRingType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFocusRingTypeNone"
        }
      ],
      "role": "symbol",
      "title": "NSFocusRingType.none",
      "type": "topic",
      "url": "/documentation/appkit/nsfocusringtype/none"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/defaultFocusRingType": {
      "abstract": [
        {
          "text": "Returns the default focus ring type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultFocusRingType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFocusRingType",
          "text": "NSFocusRingType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/defaultFocusRingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultFocusRingType"
        }
      ],
      "role": "symbol",
      "title": "defaultFocusRingType",
      "type": "topic",
      "url": "/documentation/appkit/nsview/defaultfocusringtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/draw(_:)": {
      "abstract": [
        {
          "text": "Overridden by subclasses to draw the view’s image within the specified rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draw"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/draw(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawRect:"
        }
      ],
      "role": "symbol",
      "title": "draw(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/draw(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/drawFocusRingMask()": {
      "abstract": [
        {
          "text": "Draws the focus ring mask for the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawFocusRingMask"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/drawFocusRingMask()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawFocusRingMask"
        }
      ],
      "role": "symbol",
      "title": "drawFocusRingMask()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/drawfocusringmask()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/focusRingMaskBounds": {
      "abstract": [
        {
          "text": "The focus ring mask bounds, specified in the view’s coordinate space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusRingMaskBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/focusRingMaskBounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "focusRingMaskBounds"
        }
      ],
      "role": "symbol",
      "title": "focusRingMaskBounds",
      "type": "topic",
      "url": "/documentation/appkit/nsview/focusringmaskbounds"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/focusRingType": {
      "abstract": [
        {
          "text": "The type of focus ring drawn around the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusRingType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFocusRingType",
          "text": "NSFocusRingType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/focusRingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "focusRingType"
        }
      ],
      "role": "symbol",
      "title": "focusRingType",
      "type": "topic",
      "url": "/documentation/appkit/nsview/focusringtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/noteFocusRingMaskChanged()": {
      "abstract": [
        {
          "text": "Invoked to notify the view that the focus ring mask requires updating.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noteFocusRingMaskChanged"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/noteFocusRingMaskChanged()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "noteFocusRingMaskChanged"
        }
      ],
      "role": "symbol",
      "title": "noteFocusRingMaskChanged()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/notefocusringmaskchanged()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/setKeyboardFocusRingNeedsDisplay(_:)": {
      "abstract": [
        {
          "text": "Invalidates the area around the focus ring.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setKeyboardFocusRingNeedsDisplay"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/setKeyboardFocusRingNeedsDisplay(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setKeyboardFocusRingNeedsDisplayInRect:"
        }
      ],
      "role": "symbol",
      "title": "setKeyboardFocusRingNeedsDisplay(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/setkeyboardfocusringneedsdisplay(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Drawing-the-Focus-Ring",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/focusRingMaskBounds",
        "doc://com.apple.appkit/documentation/AppKit/NSView/drawFocusRingMask()",
        "doc://com.apple.appkit/documentation/AppKit/NSView/noteFocusRingMaskChanged()",
        "doc://com.apple.appkit/documentation/AppKit/NSView/setKeyboardFocusRingNeedsDisplay(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/defaultFocusRingType"
      ],
      "title": "Drawing the Focus Ring"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "focusRingType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focusRingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Drawing-the-Focus-Ring",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/focusRingMaskBounds",
                "doc://com.apple.appkit/documentation/AppKit/NSView/drawFocusRingMask()",
                "doc://com.apple.appkit/documentation/AppKit/NSView/noteFocusRingMaskChanged()",
                "doc://com.apple.appkit/documentation/AppKit/NSView/setKeyboardFocusRingNeedsDisplay(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/defaultFocusRingType"
              ],
              "title": "Drawing the Focus Ring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFocusRingType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSFocusRingType",
                    "text": "NSFocusRingType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "focusRingType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFocusRingType~1none/title",
          "value": "NSFocusRingTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFocusRingType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFocusRingTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1focusRingMaskBounds/title",
          "value": "focusRingMaskBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1focusRingMaskBounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focusRingMaskBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1focusRingType/title",
          "value": "focusRingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1focusRingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focusRingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1draw(_:)/title",
          "value": "drawRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1draw(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFocusRingType/title",
          "value": "NSFocusRingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFocusRingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFocusRingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFocusRingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFocusRingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1drawFocusRingMask()/title",
          "value": "drawFocusRingMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1drawFocusRingMask()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawFocusRingMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1defaultFocusRingType/title",
          "value": "defaultFocusRingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1defaultFocusRingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultFocusRingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1noteFocusRingMaskChanged()/title",
          "value": "noteFocusRingMaskChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1noteFocusRingMaskChanged()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "noteFocusRingMaskChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1setKeyboardFocusRingNeedsDisplay(_:)/title",
          "value": "setKeyboardFocusRingNeedsDisplayInRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1setKeyboardFocusRingNeedsDisplay(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setKeyboardFocusRingNeedsDisplayInRect:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsview/focusringtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsview/focusringtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
