{
  "abstract": [
    {
      "text": "A property wrapper that notifies the system that a property value change has invalidated an aspect of the containing view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "s:So6NSViewC6AppKitE12InvalidatingV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Invalidating"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Invalidating"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.1",
        "name": "Swift",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSView.Invalidating"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@propertyWrapper"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Invalidating"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "genericParameter",
              "text": "Value"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "genericParameter",
              "text": "InvalidationType"
            },
            {
              "kind": "text",
              "text": "> "
            },
            {
              "kind": "keyword",
              "text": "where"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "text": "Value"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SQ",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SQ",
              "text": "Equatable"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "text": "InvalidationType"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSViewInvalidating",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:6AppKit18NSViewInvalidatingP",
              "text": "NSViewInvalidating"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this wrapper when a change in the property value invalidates the display, layout, configuration, constraints, or intrinsic sizing of a view. This wrapper performs any actions necessary to notify the system that your view is invalid and requires an update. The actions depend on the invalidation types you specify. For more information on available invalidation types, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSViewInvalidating",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following example uses the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " wrapper with the ",
              "type": "text"
            },
            {
              "code": "display",
              "type": "codeVoice"
            },
            {
              "text": " type on the property ",
              "type": "text"
            },
            {
              "code": "fillColor",
              "type": "codeVoice"
            },
            {
              "text": " and the ",
              "type": "text"
            },
            {
              "code": "display",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "layout",
              "type": "codeVoice"
            },
            {
              "text": " type on the property ",
              "type": "text"
            },
            {
              "code": "badgePosition",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "class MyView: NSView {",
            "    @Invalidating(.display) var fillColor: NSColor",
            "    ",
            "    @Invalidating(.display, .layout) var badgePosition: NSRectEdge",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When you change the fill color, the property wrapper sets ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/needsDisplay",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to true, causing the system to redraw the view. When you change the badge position, the property wrapper also sets ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/needsLayout",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to true, causing the system to update the view’s subviews before it redraws.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Functions such as ",
              "type": "text"
            },
            {
              "code": "setNeedsDisplay",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "setNeedsLayout",
              "type": "codeVoice"
            },
            {
              "text": " perform changes on the next update cycle. You can make changes to multiple properties and views before any of those views update. Consolidating the updates to one update cycle is usually better for performance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You only use ",
                  "type": "text"
                },
                {
                  "code": "NSView.Invalidating",
                  "type": "codeVoice"
                },
                {
                  "text": " on subclasses of ",
                  "type": "text"
                },
                {
                  "code": "NSView",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating": {
      "abstract": [
        {
          "text": "A property wrapper that notifies the system that a property value change has invalidated an aspect of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Invalidating"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Invalidating"
        }
      ],
      "role": "symbol",
      "title": "NSView.Invalidating",
      "type": "topic",
      "url": "/documentation/appkit/nsview/invalidating"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates an aspect of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/invalidating/init(wrappedvalue:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates aspects of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/invalidating/init(wrappedvalue:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates aspects of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/invalidating/init(wrappedvalue:_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates aspects of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/invalidating/init(wrappedvalue:_:_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates aspects of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/invalidating/init(wrappedvalue:_:_:_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates aspects of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/invalidating/init(wrappedvalue:_:_:_:_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates aspects of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType7"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType7"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/invalidating/init(wrappedvalue:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates aspects of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType7"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType8"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType7"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/invalidating/init(wrappedvalue:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates aspects of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType7"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType9"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType7"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType9"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/invalidating/init(wrappedvalue:_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates aspects of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType7"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType9"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType10"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType7"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType9"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType10"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/invalidating/init(wrappedvalue:_:_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/needsDisplay": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the view needs to be redrawn before being displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "needsDisplay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/needsDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "needsDisplay"
        }
      ],
      "role": "symbol",
      "title": "needsDisplay",
      "type": "topic",
      "url": "/documentation/appkit/nsview/needsdisplay"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/needsLayout": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view needs a layout pass before it can be drawn.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "needsLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/needsLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "needsLayout"
        }
      ],
      "role": "symbol",
      "title": "needsLayout",
      "type": "topic",
      "url": "/documentation/appkit/nsview/needslayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSViewInvalidating": {
      "abstract": [
        {
          "text": "Implements a type of invalidation that can occur on a view that requires an update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSViewInvalidating"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSViewInvalidating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewInvalidating"
        }
      ],
      "role": "symbol",
      "title": "NSViewInvalidating",
      "type": "topic",
      "url": "/documentation/appkit/nsviewinvalidating"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Updating-the-View-When-Property-Values-Change",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSViewInvalidating"
      ],
      "title": "Updating the View When Property Values Change"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-Invalidating-Property-Wrapper",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:_:_:_:)"
      ],
      "title": "Creating an Invalidating Property Wrapper"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1needsDisplay/title",
          "value": "needsDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1needsDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "needsDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1needsLayout/title",
          "value": "needsLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1needsLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "needsLayout"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsview/invalidating"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
