{
  "abstract": [
    {
      "text": "The Core Animation layer that the view uses as its backing store.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSView/layer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSView(py)layer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "layer"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CALayer",
        "text": "CALayer"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "layer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "layer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "layer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CALayer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CALayer",
              "text": "CALayer"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this property to set or get the layer associated with the view, if any. When set, the layer serves as the backing store for the view’s contents.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum": {
      "abstract": [
        {
          "text": "These constants specify the location of the layer content when the content is not rerendered in response to view resizing. For more information, see the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsPlacement-swift.property",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayerContentsPlacement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayerContentsPlacement"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsPlacement",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsplacement-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify how layer resizing is handled when a view is layer-backed or layer-hosting. For more information, see the  ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsRedrawPolicy-swift.property",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayerContentsRedrawPolicy"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayerContentsRedrawPolicy"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsRedrawPolicy",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsredrawpolicy-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/canDrawSubviewsIntoLayer": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view incorporates content from its subviews into its own layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canDrawSubviewsIntoLayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/canDrawSubviewsIntoLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canDrawSubviewsIntoLayer"
        }
      ],
      "role": "symbol",
      "title": "canDrawSubviewsIntoLayer",
      "type": "topic",
      "url": "/documentation/appkit/nsview/candrawsubviewsintolayer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/layer": {
      "abstract": [
        {
          "text": "The Core Animation layer that the view uses as its backing store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CALayer",
          "text": "CALayer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/layer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layer"
        }
      ],
      "role": "symbol",
      "title": "layer",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsPlacement-swift.property": {
      "abstract": [
        {
          "text": "The current layer contents placement policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerContentsPlacement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSViewLayerContentsPlacement",
          "text": "LayerContentsPlacement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsPlacement-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerContentsPlacement"
        }
      ],
      "role": "symbol",
      "title": "layerContentsPlacement",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsplacement-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsRedrawPolicy-swift.property": {
      "abstract": [
        {
          "text": "The contents redraw policy for the view’s layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerContentsRedrawPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSViewLayerContentsRedrawPolicy",
          "text": "LayerContentsRedrawPolicy"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsRedrawPolicy-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerContentsRedrawPolicy"
        }
      ],
      "role": "symbol",
      "title": "layerContentsRedrawPolicy",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsredrawpolicy-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/layerUsesCoreImageFilters": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view’s layer uses Core Image filters and needs in-process rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerUsesCoreImageFilters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/layerUsesCoreImageFilters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerUsesCoreImageFilters"
        }
      ],
      "role": "symbol",
      "title": "layerUsesCoreImageFilters",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layerusescoreimagefilters"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/makeBackingLayer()": {
      "abstract": [
        {
          "text": "Creates the view’s backing layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeBackingLayer"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CALayer",
          "text": "CALayer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/makeBackingLayer()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeBackingLayer"
        }
      ],
      "role": "symbol",
      "title": "makeBackingLayer()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/makebackinglayer()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/wantsLayer": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view uses a layer as its backing store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wantsLayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/wantsLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wantsLayer"
        }
      ],
      "role": "symbol",
      "title": "wantsLayer",
      "type": "topic",
      "url": "/documentation/appkit/nsview/wantslayer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/wantsUpdateLayer": {
      "abstract": [
        {
          "text": "A Boolean value indicating which drawing path the view takes when updating its contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wantsUpdateLayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/wantsUpdateLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wantsUpdateLayer"
        }
      ],
      "role": "symbol",
      "title": "wantsUpdateLayer",
      "type": "topic",
      "url": "/documentation/appkit/nsview/wantsupdatelayer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSViewLayerContentScaleDelegate": {
      "abstract": [
        {
          "text": "An optional layer delegate method for handling resolution changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSViewLayerContentScaleDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSViewLayerContentScaleDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewLayerContentScaleDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSViewLayerContentScaleDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsviewlayercontentscaledelegate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)CALayer": {
      "abstract": [
        {
          "text": "An object that manages image-based content and allows you to perform animations on that content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CALayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "CALayer",
      "type": "topic",
      "url": "/documentation/QuartzCore/CALayer"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-Views-Layer",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/wantsLayer",
        "doc://com.apple.appkit/documentation/AppKit/NSView/wantsUpdateLayer",
        "doc://com.apple.appkit/documentation/AppKit/NSView/makeBackingLayer()",
        "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsPlacement-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsRedrawPolicy-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSView/canDrawSubviewsIntoLayer",
        "doc://com.apple.appkit/documentation/AppKit/NSView/layerUsesCoreImageFilters",
        "doc://com.apple.appkit/documentation/AppKit/NSViewLayerContentScaleDelegate"
      ],
      "title": "Managing the View’s Layer"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "layer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-Views-Layer",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/wantsLayer",
                "doc://com.apple.appkit/documentation/AppKit/NSView/wantsUpdateLayer",
                "doc://com.apple.appkit/documentation/AppKit/NSView/makeBackingLayer()",
                "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsPlacement-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsRedrawPolicy-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsRedrawPolicy-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSView/canDrawSubviewsIntoLayer",
                "doc://com.apple.appkit/documentation/AppKit/NSView/layerUsesCoreImageFilters",
                "doc://com.apple.appkit/documentation/AppKit/NSViewLayerContentScaleDelegate"
              ],
              "title": "Managing the View’s Layer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CALayer",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CALayer",
                    "text": "CALayer"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "layer"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1wantsLayer/title",
          "value": "wantsLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1wantsLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wantsLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)CALayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CALayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layerUsesCoreImageFilters/title",
          "value": "layerUsesCoreImageFilters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layerUsesCoreImageFilters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layerUsesCoreImageFilters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layerContentsPlacement-swift.property/title",
          "value": "layerContentsPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layerContentsPlacement-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layerContentsPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSViewLayerContentScaleDelegate/title",
          "value": "NSViewLayerContentScaleDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSViewLayerContentScaleDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentScaleDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSViewLayerContentScaleDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentScaleDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1makeBackingLayer()/title",
          "value": "makeBackingLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1makeBackingLayer()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "makeBackingLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layerContentsRedrawPolicy-swift.property/title",
          "value": "layerContentsRedrawPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layerContentsRedrawPolicy-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layerContentsRedrawPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1canDrawSubviewsIntoLayer/title",
          "value": "canDrawSubviewsIntoLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1canDrawSubviewsIntoLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canDrawSubviewsIntoLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1wantsUpdateLayer/title",
          "value": "wantsUpdateLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1wantsUpdateLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wantsUpdateLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsRedrawPolicy-swift.enum/title",
          "value": "NSViewLayerContentsRedrawPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsRedrawPolicy-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsRedrawPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsRedrawPolicy-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsRedrawPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layer/title",
          "value": "layer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum/title",
          "value": "NSViewLayerContentsPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsview/layer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsview/layer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
