{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSView/previousKeyView","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSView"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"unowned(unsafe)","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previousKeyView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The value in this property is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if there is no view preceding the current view in the key view loop. The view in this property should, if possible, be made first responder when the user navigates backward from the current view using keyboard interface control.","type":"text"}]}]}],"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(following:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/selectNextKeyView(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/selectPreviousKeyView(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(preceding:)"]},{"anchor":"Managing-the-Key-View-Loop","title":"Managing the Key-View Loop","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSView/canBecomeKeyView","doc://com.apple.appkit/documentation/AppKit/NSView/needsPanelToBecomeKey","doc://com.apple.appkit/documentation/AppKit/NSView/nextKeyView","doc://com.apple.appkit/documentation/AppKit/NSView/nextValidKeyView","doc://com.apple.appkit/documentation/AppKit/NSView/previousValidKeyView"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsview/previouskeyview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsview/previouskeyview"]}],"metadata":{"symbolKind":"property","modules":[{"name":"AppKit"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"previousKeyView"}],"externalID":"c:objc(cs)NSView(py)previousKeyView","extendedModule":"AppKit","platforms":[{"unavailable":false,"name":"macOS","beta":false,"deprecated":false}],"title":"previousKeyView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previousKeyView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSView","preciseIdentifier":"c:objc(cs)NSView"},{"kind":"text","text":"?"}]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The view object preceding the current view in the key view loop."}],"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSView/previousValidKeyView":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/previousValidKeyView","type":"topic","abstract":[{"text":"The closest view object in the key view loop that precedes the current view and accepts first responder status.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previousValidKeyView","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","text":"NSView"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"previousValidKeyView"}],"title":"previousValidKeyView","url":"/documentation/appkit/nsview/previousvalidkeyview","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(preceding:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectKeyView"},{"kind":"text","text":"("},{"text":"preceding","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","text":"NSView"},{"kind":"text","text":")"}],"url":"/documentation/appkit/nswindow/selectkeyview(preceding:)","role":"symbol","navigatorTitle":[{"text":"selectKeyViewPrecedingView:","kind":"identifier"}],"title":"selectKeyView(preceding:)","abstract":[{"text":"Gives key view status to the view that precedes the given view.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(preceding:)"},"doc://com.apple.appkit/documentation/AppKit/NSView/nextKeyView":{"url":"/documentation/appkit/nsview/nextkeyview","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextKeyView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView"},{"text":"?","kind":"text"}],"title":"nextKeyView","kind":"symbol","abstract":[{"type":"text","text":"The view object that follows the current view in the key view loop."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/nextKeyView","role":"symbol","type":"topic","navigatorTitle":[{"text":"nextKeyView","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSView/needsPanelToBecomeKey":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/needsPanelToBecomeKey","type":"topic","abstract":[{"text":"A Boolean value indicating whether the view needs its panel to become the key window before it can handle keyboard input and navigation.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"needsPanelToBecomeKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"needsPanelToBecomeKey","kind":"identifier"}],"title":"needsPanelToBecomeKey","url":"/documentation/appkit/nsview/needspaneltobecomekey","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectPreviousKeyView(_:)":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectPreviousKeyView(_:)","abstract":[{"text":"Searches for a candidate previous key view and, if it finds one, tries to make it the first responder.","type":"text"}],"role":"symbol","title":"selectPreviousKeyView(_:)","url":"/documentation/appkit/nswindow/selectpreviouskeyview(_:)","kind":"symbol","navigatorTitle":[{"text":"selectPreviousKeyView:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectPreviousKeyView"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}]},"doc://com.apple.appkit/documentation/AppKit/NSView":{"abstract":[{"text":"The infrastructure for drawing, printing, and handling events in an app.","type":"text"}],"url":"/documentation/appkit/nsview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","title":"NSView","navigatorTitle":[{"kind":"identifier","text":"NSView"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSView/previousKeyView":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/previousKeyView","type":"topic","abstract":[{"text":"The view object preceding the current view in the key view loop.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previousKeyView","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","text":"NSView"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"previousKeyView"}],"title":"previousKeyView","url":"/documentation/appkit/nsview/previouskeyview","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSView/nextValidKeyView":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/nextValidKeyView","type":"topic","abstract":[{"text":"The closest view object in the key view loop that follows the current view in the key view loop and accepts first responder status.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextValidKeyView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSView","preciseIdentifier":"c:objc(cs)NSView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"nextValidKeyView","kind":"identifier"}],"title":"nextValidKeyView","url":"/documentation/appkit/nsview/nextvalidkeyview","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(following:)":{"kind":"symbol","title":"selectKeyView(following:)","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(following:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectKeyView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"following"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSView","text":"NSView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Gives key view status to the view that follows the given view."}],"type":"topic","url":"/documentation/appkit/nswindow/selectkeyview(following:)","navigatorTitle":[{"text":"selectKeyViewFollowingView:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectNextKeyView(_:)":{"url":"/documentation/appkit/nswindow/selectnextkeyview(_:)","abstract":[{"type":"text","text":"Searches for a candidate next key view and, if it finds one, tries to make it the first responder."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectNextKeyView(_:)","navigatorTitle":[{"text":"selectNextKeyView:","kind":"identifier"}],"role":"symbol","type":"topic","title":"selectNextKeyView(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectNextKeyView"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}]},"doc://com.apple.appkit/documentation/AppKit/NSView/canBecomeKeyView":{"abstract":[{"type":"text","text":"A Boolean value indicating whether the view can become key view."}],"title":"canBecomeKeyView","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/canBecomeKeyView","type":"topic","navigatorTitle":[{"text":"canBecomeKeyView","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canBecomeKeyView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"/documentation/appkit/nsview/canbecomekeyview","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"previousKeyView","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"previousKeyView"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSView"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"anchor":"Related-Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(following:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/selectNextKeyView(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/selectPreviousKeyView(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(preceding:)"],"title":"Related Documentation"},{"anchor":"Managing-the-Key-View-Loop","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSView/canBecomeKeyView","doc://com.apple.appkit/documentation/AppKit/NSView/needsPanelToBecomeKey","doc://com.apple.appkit/documentation/AppKit/NSView/nextKeyView","doc://com.apple.appkit/documentation/AppKit/NSView/nextValidKeyView","doc://com.apple.appkit/documentation/AppKit/NSView/previousValidKeyView"],"title":"Managing the Key-View Loop"}],"op":"replace"},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","kind":"typeIdentifier","text":"NSView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"previousKeyView"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"]}]}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1previousValidKeyView/title","value":"previousValidKeyView","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1previousValidKeyView/fragments","value":[{"text":"previousValidKeyView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectKeyView(preceding:)/title","value":"selectKeyViewPrecedingView:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectKeyView(preceding:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectKeyViewPrecedingView:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1nextKeyView/title","value":"nextKeyView","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1nextKeyView/fragments","value":[{"kind":"identifier","text":"nextKeyView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1needsPanelToBecomeKey/title","value":"needsPanelToBecomeKey","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1needsPanelToBecomeKey/fragments","value":[{"kind":"identifier","text":"needsPanelToBecomeKey"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectPreviousKeyView(_:)/title","value":"selectPreviousKeyView:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectPreviousKeyView(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"selectPreviousKeyView:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title","value":"NSView","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments","value":[{"text":"NSView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle","value":[{"text":"NSView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1previousKeyView/title","value":"previousKeyView","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1previousKeyView/fragments","value":[{"text":"previousKeyView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1nextValidKeyView/title","value":"nextValidKeyView","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1nextValidKeyView/fragments","value":[{"text":"nextValidKeyView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectKeyView(following:)/title","value":"selectKeyViewFollowingView:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectKeyView(following:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"selectKeyViewFollowingView:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectNextKeyView(_:)/title","value":"selectNextKeyView:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectNextKeyView(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectNextKeyView:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1canBecomeKeyView/title","value":"canBecomeKeyView","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1canBecomeKeyView/fragments","value":[{"kind":"identifier","text":"canBecomeKeyView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}