{"abstract":[{"type":"text","text":"The closest view object in the key view loop that precedes the current view and accepts first responder status."}],"metadata":{"title":"previousValidKeyView","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previousValidKeyView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSView","preciseIdentifier":"c:objc(cs)NSView","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"previousValidKeyView"}],"externalID":"c:objc(cs)NSView(py)previousValidKeyView","roleHeading":"Instance Property","extendedModule":"AppKit","modules":[{"name":"AppKit"}],"role":"symbol","symbolKind":"property","platforms":[{"beta":false,"unavailable":false,"name":"macOS","deprecated":false}]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"unowned(unsafe)"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previousValidKeyView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","text":"NSView"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"Discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The value in this property is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if there is no view that precedes the current view and accepts the first responder status. AppKit ignores hidden views when it determines the previous valid key view."}]}],"kind":"content"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSView/previousValidKeyView"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsview/previousvalidkeyview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsview/previousvalidkeyview"]}],"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(following:)","doc://com.apple.appkit/documentation/AppKit/NSView/isHidden","doc://com.apple.appkit/documentation/AppKit/NSWindow/selectNextKeyView(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/selectPreviousKeyView(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(preceding:)"]},{"anchor":"Managing-the-Key-View-Loop","generated":true,"title":"Managing the Key-View Loop","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSView/canBecomeKeyView","doc://com.apple.appkit/documentation/AppKit/NSView/needsPanelToBecomeKey","doc://com.apple.appkit/documentation/AppKit/NSView/nextKeyView","doc://com.apple.appkit/documentation/AppKit/NSView/nextValidKeyView","doc://com.apple.appkit/documentation/AppKit/NSView/previousKeyView"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSView"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(preceding:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectKeyView"},{"kind":"text","text":"("},{"text":"preceding","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","text":"NSView"},{"kind":"text","text":")"}],"url":"/documentation/appkit/nswindow/selectkeyview(preceding:)","role":"symbol","navigatorTitle":[{"text":"selectKeyViewPrecedingView:","kind":"identifier"}],"title":"selectKeyView(preceding:)","abstract":[{"text":"Gives key view status to the view that precedes the given view.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(preceding:)"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSView/isHidden":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"hidden","kind":"identifier"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether the view is hidden."}],"url":"/documentation/appkit/nsview/ishidden","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isHidden","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/isHidden","title":"isHidden"},"doc://com.apple.appkit/documentation/AppKit/NSView/needsPanelToBecomeKey":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/needsPanelToBecomeKey","type":"topic","abstract":[{"text":"A Boolean value indicating whether the view needs its panel to become the key window before it can handle keyboard input and navigation.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"needsPanelToBecomeKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"needsPanelToBecomeKey","kind":"identifier"}],"title":"needsPanelToBecomeKey","url":"/documentation/appkit/nsview/needspaneltobecomekey","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSView/canBecomeKeyView":{"abstract":[{"type":"text","text":"A Boolean value indicating whether the view can become key view."}],"title":"canBecomeKeyView","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/canBecomeKeyView","type":"topic","navigatorTitle":[{"text":"canBecomeKeyView","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canBecomeKeyView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"/documentation/appkit/nsview/canbecomekeyview","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(following:)":{"kind":"symbol","title":"selectKeyView(following:)","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(following:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectKeyView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"following"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSView","text":"NSView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Gives key view status to the view that follows the given view."}],"type":"topic","url":"/documentation/appkit/nswindow/selectkeyview(following:)","navigatorTitle":[{"text":"selectKeyViewFollowingView:","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectPreviousKeyView(_:)":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectPreviousKeyView(_:)","abstract":[{"text":"Searches for a candidate previous key view and, if it finds one, tries to make it the first responder.","type":"text"}],"role":"symbol","title":"selectPreviousKeyView(_:)","url":"/documentation/appkit/nswindow/selectpreviouskeyview(_:)","kind":"symbol","navigatorTitle":[{"text":"selectPreviousKeyView:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectPreviousKeyView"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}]},"doc://com.apple.appkit/documentation/AppKit/NSView/previousKeyView":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/previousKeyView","type":"topic","abstract":[{"text":"The view object preceding the current view in the key view loop.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previousKeyView","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","text":"NSView"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"previousKeyView"}],"title":"previousKeyView","url":"/documentation/appkit/nsview/previouskeyview","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSView/previousValidKeyView":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/previousValidKeyView","type":"topic","abstract":[{"text":"The closest view object in the key view loop that precedes the current view and accepts first responder status.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previousValidKeyView","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","text":"NSView"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"previousValidKeyView"}],"title":"previousValidKeyView","url":"/documentation/appkit/nsview/previousvalidkeyview","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSView/nextKeyView":{"url":"/documentation/appkit/nsview/nextkeyview","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextKeyView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView"},{"text":"?","kind":"text"}],"title":"nextKeyView","kind":"symbol","abstract":[{"type":"text","text":"The view object that follows the current view in the key view loop."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/nextKeyView","role":"symbol","type":"topic","navigatorTitle":[{"text":"nextKeyView","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSView/nextValidKeyView":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/nextValidKeyView","type":"topic","abstract":[{"text":"The closest view object in the key view loop that follows the current view in the key view loop and accepts first responder status.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextValidKeyView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSView","preciseIdentifier":"c:objc(cs)NSView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"nextValidKeyView","kind":"identifier"}],"title":"nextValidKeyView","url":"/documentation/appkit/nsview/nextvalidkeyview","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSView":{"abstract":[{"text":"The infrastructure for drawing, printing, and handling events in an app.","type":"text"}],"url":"/documentation/appkit/nsview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","title":"NSView","navigatorTitle":[{"kind":"identifier","text":"NSView"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectNextKeyView(_:)":{"url":"/documentation/appkit/nswindow/selectnextkeyview(_:)","abstract":[{"type":"text","text":"Searches for a candidate next key view and, if it finds one, tries to make it the first responder."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectNextKeyView(_:)","navigatorTitle":[{"text":"selectNextKeyView:","kind":"identifier"}],"role":"symbol","type":"topic","title":"selectNextKeyView(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectNextKeyView"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"name":"macOS","deprecated":false,"beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"previousValidKeyView","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"previousValidKeyView"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSView"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(following:)","doc://com.apple.appkit/documentation/AppKit/NSView/isHidden","doc://com.apple.appkit/documentation/AppKit/NSWindow/selectNextKeyView(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/selectPreviousKeyView(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(preceding:)"]},{"anchor":"Managing-the-Key-View-Loop","title":"Managing the Key-View Loop","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSView/canBecomeKeyView","doc://com.apple.appkit/documentation/AppKit/NSView/needsPanelToBecomeKey","doc://com.apple.appkit/documentation/AppKit/NSView/nextKeyView","doc://com.apple.appkit/documentation/AppKit/NSView/nextValidKeyView","doc://com.apple.appkit/documentation/AppKit/NSView/previousKeyView"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","preciseIdentifier":"c:objc(cs)NSView","text":"NSView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"previousValidKeyView"},{"kind":"text","text":";"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":"selectKeyViewPrecedingView:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectKeyView(preceding:)/title","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectKeyView(preceding:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectKeyViewPrecedingView:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1isHidden/title","op":"replace","value":"hidden"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1isHidden/fragments","op":"replace","value":[{"kind":"identifier","text":"hidden"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1needsPanelToBecomeKey/title","op":"replace","value":"needsPanelToBecomeKey"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1needsPanelToBecomeKey/fragments","op":"replace","value":[{"kind":"identifier","text":"needsPanelToBecomeKey"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1canBecomeKeyView/title","op":"replace","value":"canBecomeKeyView"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1canBecomeKeyView/fragments","op":"replace","value":[{"text":"canBecomeKeyView","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectKeyView(following:)/title","op":"replace","value":"selectKeyViewFollowingView:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectKeyView(following:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectKeyViewFollowingView:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectPreviousKeyView(_:)/title","op":"replace","value":"selectPreviousKeyView:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectPreviousKeyView(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectPreviousKeyView:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1previousKeyView/title","op":"replace","value":"previousKeyView"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1previousKeyView/fragments","op":"replace","value":[{"kind":"identifier","text":"previousKeyView"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1previousValidKeyView/title","op":"replace","value":"previousValidKeyView"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1previousValidKeyView/fragments","op":"replace","value":[{"text":"previousValidKeyView","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1nextKeyView/title","op":"replace","value":"nextKeyView"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1nextKeyView/fragments","op":"replace","value":[{"kind":"identifier","text":"nextKeyView"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1nextValidKeyView/title","op":"replace","value":"nextValidKeyView"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1nextValidKeyView/fragments","op":"replace","value":[{"kind":"identifier","text":"nextValidKeyView"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title","op":"replace","value":"NSView"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments","op":"replace","value":[{"text":"NSView","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSView"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectNextKeyView(_:)/title","op":"replace","value":"selectNextKeyView:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectNextKeyView(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"selectNextKeyView:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}