{
  "abstract": [
    {
      "text": "Requests permission for ",
      "type": "text"
    },
    {
      "code": "aRulerView",
      "type": "codeVoice"
    },
    {
      "text": " to add ",
      "type": "text"
    },
    {
      "code": "aMarker",
      "type": "codeVoice"
    },
    {
      "text": ", an NSRulerMarker being dragged onto the ruler by the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldAdd:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:objc(cs)NSView(im)rulerView:shouldAddMarker:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rulerView"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSRulerView",
        "text": "NSRulerView"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "shouldAdd"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSRulerMarker",
        "text": "NSRulerMarker"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "rulerView:shouldAddMarker:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "rulerView(_:shouldAdd:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rulerView"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "ruler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRulerView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSRulerView",
              "text": "NSRulerView"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "shouldAdd"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "marker"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRulerMarker",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSRulerMarker",
              "text": "NSRulerMarker"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the client returns ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " the ruler view accepts the new marker and begins tracking its movement; if the client returns ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " the ruler view refuses the new marker.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRulerMarker": {
      "abstract": [
        {
          "text": "A symbol on a ruler view, indicating a location for the graphics element it represents in the client of the ruler view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRulerMarker"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRulerMarker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRulerMarker"
        }
      ],
      "role": "symbol",
      "title": "NSRulerMarker",
      "type": "topic",
      "url": "/documentation/appkit/nsrulermarker"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRulerView": {
      "abstract": [
        {
          "text": "A ruler and the markers above or to the side of a scroll view’s document view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRulerView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRulerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRulerView"
        }
      ],
      "role": "symbol",
      "title": "NSRulerView",
      "type": "topic",
      "url": "/documentation/appkit/nsrulerview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didAdd:)": {
      "abstract": [
        {
          "text": "Informs the client that ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": " allowed the user to add ",
          "type": "text"
        },
        {
          "code": "aMarker",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didAdd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerMarker",
          "text": "NSRulerMarker"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didAdd:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:didAddMarker:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:didAdd:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:didadd:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didMove:)": {
      "abstract": [
        {
          "text": "Informs the client that ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": " allowed the user to move ",
          "type": "text"
        },
        {
          "code": "aMarker",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didMove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerMarker",
          "text": "NSRulerMarker"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didMove:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:didMoveMarker:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:didMove:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:didmove:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didRemove:)": {
      "abstract": [
        {
          "text": "Informs the client that ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": " allowed the user to remove ",
          "type": "text"
        },
        {
          "code": "aMarker",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRemove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerMarker",
          "text": "NSRulerMarker"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didRemove:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:didRemoveMarker:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:didRemove:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:didremove:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:handleMouseDownWith:)": {
      "abstract": [
        {
          "text": "Informs the client that the user has pressed the mouse button while the cursor is in the ruler area of ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handleMouseDownWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:handleMouseDownWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:handleMouseDown:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:handleMouseDownWith:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:handlemousedownwith:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:locationFor:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "locationFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:locationFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:locationForPoint:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:locationFor:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:locationfor:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:pointForLocation:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "pointForLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:pointForLocation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:pointForLocation:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:pointForLocation:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:pointforlocation:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldAdd:)": {
      "abstract": [
        {
          "text": "Requests permission for ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": " to add ",
          "type": "text"
        },
        {
          "code": "aMarker",
          "type": "codeVoice"
        },
        {
          "text": ", an NSRulerMarker being dragged onto the ruler by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldAdd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerMarker",
          "text": "NSRulerMarker"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldAdd:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:shouldAddMarker:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:shouldAdd:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:shouldadd:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldMove:)": {
      "abstract": [
        {
          "text": "Requests permission for ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": " to move ",
          "type": "text"
        },
        {
          "code": "aMarker",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldMove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerMarker",
          "text": "NSRulerMarker"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldMove:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:shouldMoveMarker:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:shouldMove:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:shouldmove:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldRemove:)": {
      "abstract": [
        {
          "text": "Requests permission for ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": " to remove ",
          "type": "text"
        },
        {
          "code": "aMarker",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldRemove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerMarker",
          "text": "NSRulerMarker"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldRemove:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:shouldRemoveMarker:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:shouldRemove:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:shouldremove:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willAdd:atLocation:)": {
      "abstract": [
        {
          "text": "Informs the client that ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": " will add the new NSRulerMarker, ",
          "type": "text"
        },
        {
          "code": "aMarker",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willAdd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerMarker",
          "text": "NSRulerMarker"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "atLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willAdd:atLocation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:willAddMarker:atLocation:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:willAdd:atLocation:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:willadd:atlocation:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willMove:toLocation:)": {
      "abstract": [
        {
          "text": "Informs the client that ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": " will move ",
          "type": "text"
        },
        {
          "code": "aMarker",
          "type": "codeVoice"
        },
        {
          "text": ", an NSRulerMarker already on the ruler view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willMove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerMarker",
          "text": "NSRulerMarker"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willMove:toLocation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:willMoveMarker:toLocation:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:willMove:toLocation:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:willmove:tolocation:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willSetClientView:)": {
      "abstract": [
        {
          "text": "Informs the client view that ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": " is about to be appropriated by ",
          "type": "text"
        },
        {
          "code": "newClient",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willSetClientView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willSetClientView:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:willSetClientView:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:willSetClientView:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:willsetclientview:)"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Synchronizing-with-Ruler-Views",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didAdd:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didMove:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didRemove:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:handleMouseDownWith:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:locationFor:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:pointForLocation:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldMove:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldRemove:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willAdd:atLocation:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willMove:toLocation:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willSetClientView:)"
      ],
      "title": "Synchronizing with Ruler Views"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "rulerView:shouldAddMarker:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:shouldAddMarker:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Synchronizing-with-Ruler-Views",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didAdd:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didMove:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didRemove:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:handleMouseDownWith:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:locationFor:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:pointForLocation:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldMove:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldRemove:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willAdd:atLocation:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willMove:toLocation:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willSetClientView:)"
              ],
              "title": "Synchronizing with Ruler Views"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "rulerView:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRulerView",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSRulerView",
                    "text": "NSRulerView"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "ruler"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "shouldAddMarker:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRulerMarker",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSRulerMarker",
                    "text": "NSRulerMarker"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "marker"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:willSetClientView:)/title",
          "value": "rulerView:willSetClientView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:willSetClientView:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:willSetClientView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:shouldAdd:)/title",
          "value": "rulerView:shouldAddMarker:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:shouldAdd:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:shouldAddMarker:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:pointForLocation:)/title",
          "value": "rulerView:pointForLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:pointForLocation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:pointForLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:shouldRemove:)/title",
          "value": "rulerView:shouldRemoveMarker:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:shouldRemove:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:shouldRemoveMarker:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:didAdd:)/title",
          "value": "rulerView:didAddMarker:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:didAdd:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:didAddMarker:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:didMove:)/title",
          "value": "rulerView:didMoveMarker:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:didMove:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:didMoveMarker:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:handleMouseDownWith:)/title",
          "value": "rulerView:handleMouseDown:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:handleMouseDownWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:handleMouseDown:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:shouldMove:)/title",
          "value": "rulerView:shouldMoveMarker:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:shouldMove:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:shouldMoveMarker:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRulerMarker/title",
          "value": "NSRulerMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRulerMarker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRulerMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRulerMarker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRulerMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:didRemove:)/title",
          "value": "rulerView:didRemoveMarker:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:didRemove:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:didRemoveMarker:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:locationFor:)/title",
          "value": "rulerView:locationForPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:locationFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:locationForPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:willAdd:atLocation:)/title",
          "value": "rulerView:willAddMarker:atLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:willAdd:atLocation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:willAddMarker:atLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:willMove:toLocation:)/title",
          "value": "rulerView:willMoveMarker:toLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:willMove:toLocation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:willMoveMarker:toLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRulerView/title",
          "value": "NSRulerView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRulerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRulerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRulerView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRulerView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsview/rulerview(_:shouldadd:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsview/rulerview(_:shouldadd:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
