{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSView/updateTrackingAreas()","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Invoked automatically when the view’s geometry changes such that its tracking areas need to be recalculated.","type":"text"}],"metadata":{"role":"symbol","platforms":[{"introducedAt":"10.5","name":"macOS","unavailable":false,"beta":false,"deprecated":false}],"navigatorTitle":[{"text":"updateTrackingAreas","kind":"identifier"}],"modules":[{"name":"AppKit"}],"title":"updateTrackingAreas()","extendedModule":"AppKit","roleHeading":"Instance Method","externalID":"c:objc(cs)NSView(im)updateTrackingAreas","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateTrackingAreas","kind":"identifier"},{"text":"()","kind":"text"}]},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsview/updatetrackingareas()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsview/updatetrackingareas()"]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSView/addTrackingArea(_:)","doc://com.apple.appkit/documentation/AppKit/NSView/removeTrackingArea(_:)","doc://com.apple.appkit/documentation/AppKit/NSView/trackingAreas","doc://com.apple.appkit/documentation/AppKit/NSView/didUpdateTrackingAreasNotification"],"title":"Managing Tracking Areas","generated":true,"anchor":"Managing-Tracking-Areas"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateTrackingAreas","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"You should override this method to remove out of date tracking areas and add recomputed tracking areas; your implementation should call ","type":"text"},{"type":"codeVoice","code":"super"},{"text":".","type":"text"}]}],"kind":"content"}],"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSView":{"abstract":[{"text":"The infrastructure for drawing, printing, and handling events in an app.","type":"text"}],"url":"/documentation/appkit/nsview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","title":"NSView","navigatorTitle":[{"kind":"identifier","text":"NSView"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSView/trackingAreas":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackingAreas"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSTrackingArea","preciseIdentifier":"c:objc(cs)NSTrackingArea"},{"kind":"text","text":"]"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackingAreas"}],"title":"trackingAreas","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/trackingAreas","url":"/documentation/appkit/nsview/trackingareas","kind":"symbol","role":"symbol","abstract":[{"text":"An array of the view’s tracking areas.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSView/addTrackingArea(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTrackingArea"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSTrackingArea","kind":"typeIdentifier","text":"NSTrackingArea"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","abstract":[{"text":"Adds a given tracking area to the view.","type":"text"}],"url":"/documentation/appkit/nsview/addtrackingarea(_:)","navigatorTitle":[{"kind":"identifier","text":"addTrackingArea:"}],"title":"addTrackingArea(_:)","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/addTrackingArea(_:)"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSView/removeTrackingArea(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeTrackingArea"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSTrackingArea","kind":"typeIdentifier","text":"NSTrackingArea"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeTrackingArea:"}],"title":"removeTrackingArea(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/removeTrackingArea(_:)","url":"/documentation/appkit/nsview/removetrackingarea(_:)","kind":"symbol","role":"symbol","abstract":[{"text":"Removes a given tracking area from the view.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSView/updateTrackingAreas()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateTrackingAreas"},{"kind":"text","text":"()"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateTrackingAreas"}],"title":"updateTrackingAreas()","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/updateTrackingAreas()","url":"/documentation/appkit/nsview/updatetrackingareas()","kind":"symbol","role":"symbol","abstract":[{"text":"Invoked automatically when the view’s geometry changes such that its tracking areas need to be recalculated.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSView/didUpdateTrackingAreasNotification":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateTrackingAreasNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName","text":"Name"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSViewDidUpdateTrackingAreasNotification"}],"title":"didUpdateTrackingAreasNotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/didUpdateTrackingAreasNotification","url":"/documentation/appkit/nsview/didupdatetrackingareasnotification","kind":"symbol","role":"symbol","abstract":[{"text":"Posted whenever a view recalculates its tracking areas.","type":"text"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"10.5","name":"macOS","unavailable":false,"beta":false,"deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"updateTrackingAreas"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"updateTrackingAreas","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSView"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Managing-Tracking-Areas","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSView/addTrackingArea(_:)","doc://com.apple.appkit/documentation/AppKit/NSView/removeTrackingArea(_:)","doc://com.apple.appkit/documentation/AppKit/NSView/trackingAreas","doc://com.apple.appkit/documentation/AppKit/NSView/didUpdateTrackingAreasNotification"],"title":"Managing Tracking Areas"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateTrackingAreas"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"NSView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSView"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments"},{"op":"replace","value":[{"text":"NSView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle"},{"op":"replace","value":"trackingAreas","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1trackingAreas/title"},{"op":"replace","value":[{"kind":"identifier","text":"trackingAreas"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1trackingAreas/fragments"},{"op":"replace","value":"addTrackingArea:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1addTrackingArea(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addTrackingArea:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1addTrackingArea(_:)/fragments"},{"op":"replace","value":"removeTrackingArea:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1removeTrackingArea(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeTrackingArea:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1removeTrackingArea(_:)/fragments"},{"op":"replace","value":"updateTrackingAreas","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1updateTrackingAreas()/title"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1updateTrackingAreas()/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateTrackingAreas"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1didUpdateTrackingAreasNotification/title","op":"replace","value":"NSViewDidUpdateTrackingAreasNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1didUpdateTrackingAreasNotification/fragments","op":"replace","value":[{"text":"NSViewDidUpdateTrackingAreasNotification","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}