{
  "abstract": [
    {
      "text": "The scale (in units per second) of the ",
      "type": "text"
    },
    {
      "code": "videoTimeScale",
      "type": "codeVoice"
    },
    {
      "text": " and ",
      "type": "text"
    },
    {
      "code": "videoRefreshPeriod",
      "type": "codeVoice"
    },
    {
      "text": " fields.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corevideo/documentation/CoreVideo",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/videoTimeScale"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@CVTimeStamp@FI@videoTimeScale",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "videoTimeScale"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "Core Video"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "videoTimeScale"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "videoTimeScale"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "videoTimeScale"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corevideo/documentation/CoreVideo": {
      "abstract": [
        {
          "text": "Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Video",
      "type": "topic",
      "url": "/documentation/corevideo"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp": {
      "abstract": [
        {
          "text": "A structure for defining a display timestamp.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVTimeStamp"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CVTimeStamp"
        }
      ],
      "role": "symbol",
      "title": "CVTimeStamp",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestamp"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/flags": {
      "abstract": [
        {
          "text": "A bit field containing additional information about the timestamp.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/flags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flags"
        }
      ],
      "role": "symbol",
      "title": "flags",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestamp/flags"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/hostTime": {
      "abstract": [
        {
          "text": "The system time measured by the timestamp.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hostTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/hostTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hostTime"
        }
      ],
      "role": "symbol",
      "title": "hostTime",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestamp/hosttime"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/rateScalar": {
      "abstract": [
        {
          "text": "The current rate of the device as measured by the timestamps, divided by the nominal rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rateScalar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/rateScalar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rateScalar"
        }
      ],
      "role": "symbol",
      "title": "rateScalar",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestamp/ratescalar"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/reserved": {
      "abstract": [
        {
          "text": "Reserved. Do not use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reserved"
        }
      ],
      "role": "symbol",
      "title": "reserved",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestamp/reserved"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/smpteTime": {
      "abstract": [
        {
          "text": "The SMPTE time representation of the timestamp.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smpteTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CVSMPTETime",
          "text": "CVSMPTETime"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/smpteTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "smpteTime"
        }
      ],
      "role": "symbol",
      "title": "smpteTime",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestamp/smptetime"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/version": {
      "abstract": [
        {
          "text": "The current ",
          "type": "text"
        },
        {
          "code": "CVTimeStamp",
          "type": "codeVoice"
        },
        {
          "text": " structure is version 0. Some functions require you to specify a version when passing in a timestamp structure to be filled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestamp/version"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/videoRefreshPeriod": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoRefreshPeriod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/videoRefreshPeriod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "videoRefreshPeriod"
        }
      ],
      "role": "symbol",
      "title": "videoRefreshPeriod",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestamp/videorefreshperiod"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/videoTime": {
      "abstract": [
        {
          "text": "The start of a frame (or field for interlaced video).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/videoTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "videoTime"
        }
      ],
      "role": "symbol",
      "title": "videoTime",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestamp/videotime"
    },
    "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/videoTimeScale": {
      "abstract": [
        {
          "text": "The scale (in units per second) of the ",
          "type": "text"
        },
        {
          "code": "videoTimeScale",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "videoRefreshPeriod",
          "type": "codeVoice"
        },
        {
          "text": " fields.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoTimeScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/videoTimeScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "videoTimeScale"
        }
      ],
      "role": "symbol",
      "title": "videoTimeScale",
      "type": "topic",
      "url": "/documentation/corevideo/cvtimestamp/videotimescale"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/flags",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/hostTime",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/rateScalar",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/reserved",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/smpteTime",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/version",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/videoRefreshPeriod",
        "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/videoTime"
      ],
      "title": "Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "videoTimeScale"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "videoTimeScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corevideo/documentation/CoreVideo",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/flags",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/hostTime",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/rateScalar",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/reserved",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/smpteTime",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/version",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/videoRefreshPeriod",
                "doc://com.apple.corevideo/documentation/CoreVideo/CVTimeStamp/videoTime"
              ],
              "title": "Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@int32_t",
                    "text": "int32_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "videoTimeScale"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp~1rateScalar/title",
          "value": "rateScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp~1rateScalar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rateScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp~1flags/title",
          "value": "flags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp~1flags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp~1smpteTime/title",
          "value": "smpteTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp~1smpteTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "smpteTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp~1videoRefreshPeriod/title",
          "value": "videoRefreshPeriod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp~1videoRefreshPeriod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "videoRefreshPeriod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp~1videoTime/title",
          "value": "videoTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp~1videoTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "videoTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp/title",
          "value": "CVTimeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CVTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp~1videoTimeScale/title",
          "value": "videoTimeScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp~1videoTimeScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "videoTimeScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp~1reserved/title",
          "value": "reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp~1reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp~1hostTime/title",
          "value": "hostTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corevideo~1documentation~1CoreVideo~1CVTimeStamp~1hostTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hostTime"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corevideo/cvtimestamp/videotimescale"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corevideo/cvtimestamp/videotimescale"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
