{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pencilkit/documentation/PencilKit","doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","metadata":{"platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.1"},{"name":"visionOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"1.0"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"overrideUserInterfaceStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIUserInterfaceStyle","text":"UIUserInterfaceStyle"}],"title":"overrideUserInterfaceStyle","navigatorTitle":[{"kind":"identifier","text":"overrideUserInterfaceStyle"}],"externalID":"c:objc(cs)PKToolPicker(py)overrideUserInterfaceStyle","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"PencilKit"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"overrideUserInterfaceStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIUserInterfaceStyle","preciseIdentifier":"c:@E@UIUserInterfaceStyle","identifier":"doc://com.externally.resolved.symbol/c:@E@UIUserInterfaceStyle"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]},{"kind":"content","content":[{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"If you set this property, consider if you need to set "},{"isActive":true,"identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/colorUserInterfaceStyle","type":"reference"},{"type":"text","text":" to a select a different user interface style. The default user interface style is "},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/UIKit/UIUserInterfaceStyle/unspecified","type":"reference"},{"type":"text","text":"."}],"type":"paragraph"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/overrideUserInterfaceStyle"},"seeAlsoSections":[{"anchor":"Customizing-picker-behavior","generated":true,"identifiers":["doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/isRulerActive","doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/colorUserInterfaceStyle","doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/showsDrawingPolicyControls","doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/stateAutosaveName"],"title":"Customizing picker behavior"}],"abstract":[{"type":"text","text":"The specific user interface style to apply to the tool picker."}],"variants":[{"paths":["/documentation/pencilkit/pktoolpicker/overrideuserinterfacestyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/pencilkit/pktoolpicker/overrideuserinterfacestyle"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.documentation/documentation/UIKit/UIUserInterfaceStyle/unspecified":{"title":"UIUserInterfaceStyle.unspecified","url":"/documentation/UIKit/UIUserInterfaceStyle/unspecified","role":"symbol","kind":"symbol","identifier":"doc://com.apple.documentation/documentation/UIKit/UIUserInterfaceStyle/unspecified","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unspecified","kind":"identifier"}],"abstract":[{"text":"An unspecified interface style.","type":"text"}],"type":"topic"},"doc://com.externally.resolved.symbol/c:@E@UIUserInterfaceStyle":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIUserInterfaceStyle","kind":"identifier"}],"role":"symbol","title":"UIUserInterfaceStyle","abstract":[{"type":"text","text":"Constants that indicate the interface style for the app."}],"kind":"symbol","url":"/documentation/UIKit/UIUserInterfaceStyle","identifier":"doc://com.externally.resolved.symbol/c:@E@UIUserInterfaceStyle"},"doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/overrideUserInterfaceStyle":{"type":"topic","abstract":[{"text":"The specific user interface style to apply to the tool picker.","type":"text"}],"title":"overrideUserInterfaceStyle","navigatorTitle":[{"kind":"identifier","text":"overrideUserInterfaceStyle"}],"role":"symbol","kind":"symbol","url":"/documentation/pencilkit/pktoolpicker/overrideuserinterfacestyle","identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/overrideUserInterfaceStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"overrideUserInterfaceStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIUserInterfaceStyle","kind":"typeIdentifier","text":"UIUserInterfaceStyle"}]},"doc://com.apple.pencilkit/documentation/PencilKit":{"type":"topic","url":"/documentation/pencilkit","kind":"symbol","abstract":[{"type":"text","text":"Capture touch and Apple Pencil input as a drawing, and display that content from your app."}],"title":"PencilKit","role":"collection","identifier":"doc://com.apple.pencilkit/documentation/PencilKit"},"doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/stateAutosaveName":{"type":"topic","url":"/documentation/pencilkit/pktoolpicker/stateautosavename","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"stateAutosaveName"}],"abstract":[{"type":"text","text":"The name used to automatically save the tool picker’s state in the defaults system."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stateAutosaveName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"title":"stateAutosaveName","role":"symbol","identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/stateAutosaveName"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","url":"/documentation/technologies","kind":"technologies","abstract":[{"text":"","type":"text"}],"title":"Technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/isRulerActive":{"title":"isRulerActive","role":"symbol","abstract":[{"text":"A Boolean value that indicates whether the ruler is visible on the canvas.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"rulerActive","kind":"identifier"}],"identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/isRulerActive","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isRulerActive","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"/documentation/pencilkit/pktoolpicker/isruleractive","kind":"symbol"},"doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker":{"url":"/documentation/pencilkit/pktoolpicker","kind":"symbol","type":"topic","role":"symbol","title":"PKToolPicker","identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKToolPicker"}],"abstract":[{"type":"text","text":"A tool palette that displays a selection of drawing tools and colors for tools that a person can choose from."}],"navigatorTitle":[{"kind":"identifier","text":"PKToolPicker"}]},"doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/colorUserInterfaceStyle":{"title":"colorUserInterfaceStyle","navigatorTitle":[{"kind":"identifier","text":"colorUserInterfaceStyle"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorUserInterfaceStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIUserInterfaceStyle","text":"UIUserInterfaceStyle"}],"url":"/documentation/pencilkit/pktoolpicker/coloruserinterfacestyle","abstract":[{"type":"text","text":"The user interface style for the tool picker."}],"identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/colorUserInterfaceStyle","type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/showsDrawingPolicyControls":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showsDrawingPolicyControls","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","title":"showsDrawingPolicyControls","navigatorTitle":[{"text":"showsDrawingPolicyControls","kind":"identifier"}],"abstract":[{"text":"A Boolean value that indicates whether the default drawing policy UI is visible.","type":"text"}],"url":"/documentation/pencilkit/pktoolpicker/showsdrawingpolicycontrols","identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/showsDrawingPolicyControls"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"introducedAt":"13.0","name":"iOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"13.0","name":"iPadOS","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"13.1","deprecated":false},{"name":"visionOS","unavailable":false,"beta":false,"introducedAt":"1.0","deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"overrideUserInterfaceStyle","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"overrideUserInterfaceStyle"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pencilkit/documentation/PencilKit","doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/isRulerActive","doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/colorUserInterfaceStyle","doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/showsDrawingPolicyControls","doc://com.apple.pencilkit/documentation/PencilKit/PKToolPicker/stateAutosaveName"],"generated":true,"anchor":"Customizing-picker-behavior","title":"Customizing picker behavior"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@E@UIUserInterfaceStyle","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@E@UIUserInterfaceStyle","text":"UIUserInterfaceStyle"},{"kind":"text","text":" "},{"kind":"identifier","text":"overrideUserInterfaceStyle"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"value":"UIUserInterfaceStyleUnspecified","path":"/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIUserInterfaceStyle~1unspecified/title","op":"replace"},{"value":[{"text":"UIUserInterfaceStyleUnspecified","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIUserInterfaceStyle~1unspecified/fragments","op":"replace"},{"value":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIUserInterfaceStyle"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@E@UIUserInterfaceStyle/fragments","op":"replace"},{"value":"overrideUserInterfaceStyle","path":"/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1overrideUserInterfaceStyle/title","op":"replace"},{"value":[{"kind":"identifier","text":"overrideUserInterfaceStyle"}],"path":"/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1overrideUserInterfaceStyle/fragments","op":"replace"},{"value":"stateAutosaveName","path":"/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1stateAutosaveName/title","op":"replace"},{"value":[{"kind":"identifier","text":"stateAutosaveName"}],"path":"/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1stateAutosaveName/fragments","op":"replace"},{"value":"rulerActive","path":"/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1isRulerActive/title","op":"replace"},{"value":[{"text":"rulerActive","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1isRulerActive/fragments","op":"replace"},{"value":"PKToolPicker","path":"/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker/title","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker/fragments","value":[{"kind":"identifier","text":"PKToolPicker"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker/navigatorTitle","value":[{"text":"PKToolPicker","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1colorUserInterfaceStyle/title","value":"colorUserInterfaceStyle"},{"op":"replace","path":"/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1colorUserInterfaceStyle/fragments","value":[{"kind":"identifier","text":"colorUserInterfaceStyle"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1showsDrawingPolicyControls/title","value":"showsDrawingPolicyControls"},{"op":"replace","path":"/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPicker~1showsDrawingPolicyControls/fragments","value":[{"kind":"identifier","text":"showsDrawingPolicyControls"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}