{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.colorsync/documentation/ColorSync"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMGetBundle(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@ColorSyncCMMGetBundle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ColorSyncCMMGetBundle"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ColorSyncCMMRef",
        "text": "ColorSyncCMM"
      },
      {
        "kind": "text",
        "text": "!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s9UnmanagedV",
        "text": "Unmanaged"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFBundleRef",
        "text": "CFBundle"
      },
      {
        "kind": "text",
        "text": ">?"
      }
    ],
    "modules": [
      {
        "name": "ColorSync"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ColorSyncCMMGetBundle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "ColorSyncCMMGetBundle(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ColorSyncCMMGetBundle"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMM",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ColorSyncCMMRef",
              "text": "ColorSyncCMM"
            },
            {
              "kind": "text",
              "text": "!) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s9UnmanagedV",
              "text": "Unmanaged"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFBundleRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFBundleRef",
              "text": "CFBundle"
            },
            {
              "kind": "text",
              "text": ">?"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.colorsync/documentation/ColorSync": {
      "abstract": [
        {
          "text": "Reproduce colors accurately across a range of input, output, and display devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync",
      "kind": "symbol",
      "role": "collection",
      "title": "ColorSync",
      "type": "topic",
      "url": "/documentation/colorsync"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/CGDisplayCreateUUIDFromDisplayID(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGDisplayCreateUUIDFromDisplayID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFUUIDRef",
          "text": "CFUUID"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/CGDisplayCreateUUIDFromDisplayID(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGDisplayCreateUUIDFromDisplayID"
        }
      ],
      "role": "symbol",
      "title": "CGDisplayCreateUUIDFromDisplayID(_:)",
      "type": "topic",
      "url": "/documentation/colorsync/cgdisplaycreateuuidfromdisplayid(_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/CGDisplayGetDisplayIDFromUUID(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGDisplayGetDisplayIDFromUUID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFUUIDRef",
          "text": "CFUUID"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/CGDisplayGetDisplayIDFromUUID(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGDisplayGetDisplayIDFromUUID"
        }
      ],
      "role": "symbol",
      "title": "CGDisplayGetDisplayIDFromUUID(_:)",
      "type": "topic",
      "url": "/documentation/colorsync/cgdisplaygetdisplayidfromuuid(_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncCMM"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncCMM"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncCMM",
      "type": "topic",
      "url": "/documentation/colorsync/colorsynccmm"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMCopyCMMIdentifier(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncCMMCopyCMMIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ColorSyncCMMRef",
          "text": "ColorSyncCMM"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMCopyCMMIdentifier(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncCMMCopyCMMIdentifier"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncCMMCopyCMMIdentifier(_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsynccmmcopycmmidentifier(_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMCopyLocalizedName(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncCMMCopyLocalizedName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ColorSyncCMMRef",
          "text": "ColorSyncCMM"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMCopyLocalizedName(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncCMMCopyLocalizedName"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncCMMCopyLocalizedName(_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsynccmmcopylocalizedname(_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMCreate(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncCMMCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFBundleRef",
          "text": "CFBundle"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ColorSyncCMMRef",
          "text": "ColorSyncCMM"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMCreate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncCMMCreate"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncCMMCreate(_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsynccmmcreate(_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMGetBundle(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncCMMGetBundle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ColorSyncCMMRef",
          "text": "ColorSyncCMM"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFBundleRef",
          "text": "CFBundle"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMGetBundle(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncCMMGetBundle"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncCMMGetBundle(_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsynccmmgetbundle(_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMGetTypeID()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncCMMGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncCMMGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncCMMGetTypeID()",
      "type": "topic",
      "url": "/documentation/colorsync/colorsynccmmgettypeid()"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDeviceCopyDeviceInfo(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncDeviceCopyDeviceInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFUUIDRef",
          "text": "CFUUID"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDeviceCopyDeviceInfo(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncDeviceCopyDeviceInfo"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncDeviceCopyDeviceInfo(_:_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncdevicecopydeviceinfo(_:_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDeviceSetCustomProfiles(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncDeviceSetCustomProfiles"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFUUIDRef",
          "text": "CFUUID"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDeviceSetCustomProfiles(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncDeviceSetCustomProfiles"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncDeviceSetCustomProfiles(_:_:_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncdevicesetcustomprofiles(_:_:_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncIterateDeviceProfiles(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncIterateDeviceProfiles"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ColorSyncDeviceProfileIterateCallback",
          "text": "ColorSyncDeviceProfileIterateCallback"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncIterateDeviceProfiles(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncIterateDeviceProfiles"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncIterateDeviceProfiles(_:_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsynciteratedeviceprofiles(_:_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncIterateInstalledCMMs(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncIterateInstalledCMMs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ColorSyncCMMIterateCallback",
          "text": "ColorSyncCMMIterateCallback"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncIterateInstalledCMMs(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncIterateInstalledCMMs"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncIterateInstalledCMMs(_:_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsynciterateinstalledcmms(_:_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncIterateInstalledProfiles(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncIterateInstalledProfiles"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ColorSyncProfileIterateCallback",
          "text": "ColorSyncProfileIterateCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?)"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncIterateInstalledProfiles(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncIterateInstalledProfiles"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncIterateInstalledProfiles(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsynciterateinstalledprofiles(_:_:_:_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileContainsTag(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncProfileContainsTag"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ColorSyncProfileRef",
          "text": "ColorSyncProfile"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileContainsTag(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncProfileContainsTag"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncProfileContainsTag(_:_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncprofilecontainstag(_:_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileCopyData(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncProfileCopyData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ColorSyncProfileRef",
          "text": "ColorSyncProfile"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileCopyData(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncProfileCopyData"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncProfileCopyData(_:_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncprofilecopydata(_:_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileCopyDescriptionString(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncProfileCopyDescriptionString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ColorSyncProfileRef",
          "text": "ColorSyncProfile"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileCopyDescriptionString(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncProfileCopyDescriptionString"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncProfileCopyDescriptionString(_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncprofilecopydescriptionstring(_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileCopyHeader(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncProfileCopyHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ColorSyncProfileRef",
          "text": "ColorSyncProfile"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileCopyHeader(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncProfileCopyHeader"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncProfileCopyHeader(_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncprofilecopyheader(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFBundleRef": {
      "abstract": [
        {
          "text": "A reference to a CFBundle object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFBundle"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFBundleRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFBundle",
      "type": "topic",
      "url": "/documentation/corefoundation/cfbundle"
    },
    "doc://com.externally.resolved.symbol/s:s9UnmanagedV": {
      "abstract": [
        {
          "text": "A type for propagating an unmanaged object reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Unmanaged",
      "type": "topic",
      "url": "/documentation/Swift/Unmanaged"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Additional-functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.colorsync/documentation/ColorSync/CGDisplayCreateUUIDFromDisplayID(_:)",
        "doc://com.apple.colorsync/documentation/ColorSync/CGDisplayGetDisplayIDFromUUID(_:)",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMCopyCMMIdentifier(_:)",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMCopyLocalizedName(_:)",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMCreate(_:)",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMGetTypeID()",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDeviceCopyDeviceInfo(_:_:)",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDeviceSetCustomProfiles(_:_:_:)",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncIterateDeviceProfiles(_:_:)",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncIterateInstalledCMMs(_:_:)",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncIterateInstalledProfiles(_:_:_:_:)",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileContainsTag(_:_:)",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileCopyData(_:_:)",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileCopyDescriptionString(_:)",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileCopyHeader(_:)"
      ],
      "title": "Additional functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ColorSyncCMMGetBundle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncCMMGetBundle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.colorsync/documentation/ColorSync"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Additional-functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.colorsync/documentation/ColorSync/CGDisplayCreateUUIDFromDisplayID(_:)",
                "doc://com.apple.colorsync/documentation/ColorSync/CGDisplayGetDisplayIDFromUUID(_:)",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMCopyCMMIdentifier(_:)",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMCopyLocalizedName(_:)",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMCreate(_:)",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMMGetTypeID()",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDeviceCopyDeviceInfo(_:_:)",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncDeviceSetCustomProfiles(_:_:_:)",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncIterateDeviceProfiles(_:_:)",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncIterateInstalledCMMs(_:_:)",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncIterateInstalledProfiles(_:_:_:_:)",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileContainsTag(_:_:)",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileCopyData(_:_:)",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileCopyDescriptionString(_:)",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileCopyHeader(_:)"
              ],
              "title": "Additional functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFBundleRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFBundleRef",
                    "text": "CFBundleRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ColorSyncCMMGetBundle"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCMM",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ColorSyncCMMRef",
                    "text": "ColorSyncCMMRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": ""
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFBundleRef/title",
          "value": "CFBundleRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCMMGetBundle(_:)/title",
          "value": "ColorSyncCMMGetBundle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCMMGetBundle(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncCMMGetBundle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncIterateInstalledCMMs(_:_:)/title",
          "value": "ColorSyncIterateInstalledCMMs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncIterateInstalledCMMs(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncIterateInstalledCMMs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfileCopyData(_:_:)/title",
          "value": "ColorSyncProfileCopyData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfileCopyData(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncProfileCopyData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCMMCopyLocalizedName(_:)/title",
          "value": "ColorSyncCMMCopyLocalizedName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCMMCopyLocalizedName(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncCMMCopyLocalizedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCMMCopyCMMIdentifier(_:)/title",
          "value": "ColorSyncCMMCopyCMMIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCMMCopyCMMIdentifier(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncCMMCopyCMMIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncDeviceCopyDeviceInfo(_:_:)/title",
          "value": "ColorSyncDeviceCopyDeviceInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncDeviceCopyDeviceInfo(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncDeviceCopyDeviceInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncIterateDeviceProfiles(_:_:)/title",
          "value": "ColorSyncIterateDeviceProfiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncIterateDeviceProfiles(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncIterateDeviceProfiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCMMCreate(_:)/title",
          "value": "ColorSyncCMMCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCMMCreate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncCMMCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncIterateInstalledProfiles(_:_:_:_:)/title",
          "value": "ColorSyncIterateInstalledProfiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncIterateInstalledProfiles(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncIterateInstalledProfiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfileContainsTag(_:_:)/title",
          "value": "ColorSyncProfileContainsTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfileContainsTag(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncProfileContainsTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfileCopyDescriptionString(_:)/title",
          "value": "ColorSyncProfileCopyDescriptionString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfileCopyDescriptionString(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncProfileCopyDescriptionString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1CGDisplayCreateUUIDFromDisplayID(_:)/title",
          "value": "CGDisplayCreateUUIDFromDisplayID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1CGDisplayCreateUUIDFromDisplayID(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGDisplayCreateUUIDFromDisplayID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCMM/title",
          "value": "ColorSyncCMMRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCMM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncCMMRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCMM/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncCMMRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfileCopyHeader(_:)/title",
          "value": "ColorSyncProfileCopyHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfileCopyHeader(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncProfileCopyHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCMMGetTypeID()/title",
          "value": "ColorSyncCMMGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCMMGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncCMMGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncDeviceSetCustomProfiles(_:_:_:)/title",
          "value": "ColorSyncDeviceSetCustomProfiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncDeviceSetCustomProfiles(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncDeviceSetCustomProfiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1CGDisplayGetDisplayIDFromUUID(_:)/title",
          "value": "CGDisplayGetDisplayIDFromUUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1CGDisplayGetDisplayIDFromUUID(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGDisplayGetDisplayIDFromUUID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/colorsync/colorsynccmmgetbundle(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/colorsync/colorsynccmmgetbundle(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
