{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.colorsync/documentation/ColorSync"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileIsWideGamut(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@ColorSyncProfileIsWideGamut",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ColorSyncProfileIsWideGamut"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ColorSyncProfileRef",
        "text": "ColorSyncProfile"
      },
      {
        "kind": "text",
        "text": "!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "ColorSync"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ColorSyncProfileIsWideGamut"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "ColorSyncProfileIsWideGamut(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ColorSyncProfileIsWideGamut"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfile",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ColorSyncProfileRef",
              "text": "ColorSyncProfile"
            },
            {
              "kind": "text",
              "text": "!) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.colorsync/documentation/ColorSync": {
      "abstract": [
        {
          "text": "Reproduce colors accurately across a range of input, output, and display devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync",
      "kind": "symbol",
      "role": "collection",
      "title": "ColorSync",
      "type": "topic",
      "url": "/documentation/colorsync"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncAPIVersion()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncAPIVersion"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncAPIVersion()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncAPIVersion"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncAPIVersion()",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncapiversion()"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCreateCodeFragment(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncCreateCodeFragment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCreateCodeFragment(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncCreateCodeFragment"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncCreateCodeFragment(_:_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsynccreatecodefragment(_:_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncIterateInstalledProfilesWithOptions(_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncIterateInstalledProfilesWithOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ColorSyncProfileIterateCallback",
          "text": "ColorSyncProfileIterateCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?)"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncIterateInstalledProfilesWithOptions(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncIterateInstalledProfilesWithOptions"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncIterateInstalledProfilesWithOptions(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsynciterateinstalledprofileswithoptions(_:_:_:_:_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfile": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncProfile"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncProfile"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncProfile",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncprofile"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileIsHLGBased(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncProfileIsHLGBased"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ColorSyncProfileRef",
          "text": "ColorSyncProfile"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileIsHLGBased(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncProfileIsHLGBased"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncProfileIsHLGBased(_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncprofileishlgbased(_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileIsMatrixBased(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncProfileIsMatrixBased"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ColorSyncProfileRef",
          "text": "ColorSyncProfile"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileIsMatrixBased(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncProfileIsMatrixBased"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncProfileIsMatrixBased(_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncprofileismatrixbased(_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileIsPQBased(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncProfileIsPQBased"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ColorSyncProfileRef",
          "text": "ColorSyncProfile"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileIsPQBased(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncProfileIsPQBased"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncProfileIsPQBased(_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncprofileispqbased(_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileIsWideGamut(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncProfileIsWideGamut"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ColorSyncProfileRef",
          "text": "ColorSyncProfile"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileIsWideGamut(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncProfileIsWideGamut"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncProfileIsWideGamut(_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsyncprofileiswidegamut(_:)"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncTransformGetProfileSequence(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorSyncTransformGetProfileSequence"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ColorSyncTransformRef",
          "text": "ColorSyncTransform"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncTransformGetProfileSequence(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorSyncTransformGetProfileSequence"
        }
      ],
      "role": "symbol",
      "title": "ColorSyncTransformGetProfileSequence(_:)",
      "type": "topic",
      "url": "/documentation/colorsync/colorsynctransformgetprofilesequence(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncAPIVersion()",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCreateCodeFragment(_:_:)",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncIterateInstalledProfilesWithOptions(_:_:_:_:_:)",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileIsHLGBased(_:)",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileIsMatrixBased(_:)",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileIsPQBased(_:)",
        "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncTransformGetProfileSequence(_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ColorSyncProfileIsWideGamut"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncProfileIsWideGamut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.colorsync/documentation/ColorSync"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncAPIVersion()",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncCreateCodeFragment(_:_:)",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncIterateInstalledProfilesWithOptions(_:_:_:_:_:)",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileIsHLGBased(_:)",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileIsMatrixBased(_:)",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfileIsPQBased(_:)",
                "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncTransformGetProfileSequence(_:)"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:b",
                    "text": "bool"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ColorSyncProfileIsWideGamut"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.colorsync/documentation/ColorSync/ColorSyncProfile",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ColorSyncProfileRef",
                    "text": "ColorSyncProfileRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": ""
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfileIsHLGBased(_:)/title",
          "value": "ColorSyncProfileIsHLGBased"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfileIsHLGBased(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncProfileIsHLGBased"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfileIsPQBased(_:)/title",
          "value": "ColorSyncProfileIsPQBased"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfileIsPQBased(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncProfileIsPQBased"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncIterateInstalledProfilesWithOptions(_:_:_:_:_:)/title",
          "value": "ColorSyncIterateInstalledProfilesWithOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncIterateInstalledProfilesWithOptions(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncIterateInstalledProfilesWithOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfile/title",
          "value": "ColorSyncProfileRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncProfileRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncProfileRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCreateCodeFragment(_:_:)/title",
          "value": "ColorSyncCreateCodeFragment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncCreateCodeFragment(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncCreateCodeFragment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncTransformGetProfileSequence(_:)/title",
          "value": "ColorSyncTransformGetProfileSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncTransformGetProfileSequence(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncTransformGetProfileSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfileIsMatrixBased(_:)/title",
          "value": "ColorSyncProfileIsMatrixBased"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfileIsMatrixBased(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncProfileIsMatrixBased"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncAPIVersion()/title",
          "value": "ColorSyncAPIVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncAPIVersion()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncAPIVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfileIsWideGamut(_:)/title",
          "value": "ColorSyncProfileIsWideGamut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1ColorSyncProfileIsWideGamut(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ColorSyncProfileIsWideGamut"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/colorsync/colorsyncprofileiswidegamut(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/colorsync/colorsyncprofileiswidegamut(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
