{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.colorsync/documentation/ColorSync"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_STARTING"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@CS_AVAILABLE_STARTING",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CS_AVAILABLE_STARTING"
      }
    ],
    "modules": [
      {
        "name": "ColorSync"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CS_AVAILABLE_STARTING"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Macro",
    "symbolKind": "macro",
    "title": "CS_AVAILABLE_STARTING"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "#define"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CS_AVAILABLE_STARTING"
            },
            {
              "kind": "text",
              "text": "(...)"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.colorsync/documentation/ColorSync": {
      "abstract": [
        {
          "text": "Reproduce colors accurately across a range of input, output, and display devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync",
      "kind": "symbol",
      "role": "collection",
      "title": "ColorSync",
      "type": "topic",
      "url": "/documentation/colorsync"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_ITERATE_ASYNC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "COLORSYNC_ITERATE_ASYNC"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_ITERATE_ASYNC",
      "kind": "symbol",
      "role": "symbol",
      "title": "COLORSYNC_ITERATE_ASYNC",
      "type": "topic",
      "url": "/documentation/colorsync/colorsync_iterate_async"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_MD5_LENGTH": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COLORSYNC_MD5_LENGTH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_MD5_LENGTH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COLORSYNC_MD5_LENGTH"
        }
      ],
      "role": "symbol",
      "title": "COLORSYNC_MD5_LENGTH",
      "type": "topic",
      "url": "/documentation/colorsync/colorsync_md5_length"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_PROFILE_INSTALL_ENTITLEMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COLORSYNC_PROFILE_INSTALL_ENTITLEMENT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_PROFILE_INSTALL_ENTITLEMENT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COLORSYNC_PROFILE_INSTALL_ENTITLEMENT"
        }
      ],
      "role": "symbol",
      "title": "COLORSYNC_PROFILE_INSTALL_ENTITLEMENT",
      "type": "topic",
      "url": "/documentation/colorsync/colorsync_profile_install_entitlement"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/CSEXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSEXPORT"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/CSEXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSEXPORT",
      "type": "topic",
      "url": "/documentation/colorsync/csexport"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/CSEXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSEXTERN"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/CSEXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSEXTERN",
      "type": "topic",
      "url": "/documentation/colorsync/csextern"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/CSEXTERN_DESKTOP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSEXTERN_DESKTOP"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/CSEXTERN_DESKTOP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSEXTERN_DESKTOP",
      "type": "topic",
      "url": "/documentation/colorsync/csextern_desktop"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/CSLOCAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CSLOCAL"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/CSLOCAL",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSLOCAL",
      "type": "topic",
      "url": "/documentation/colorsync/cslocal"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_BUT_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CS_AVAILABLE_BUT_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_BUT_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "CS_AVAILABLE_BUT_DEPRECATED",
      "type": "topic",
      "url": "/documentation/colorsync/cs_available_but_deprecated"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_BUT_DEPRECATED1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CS_AVAILABLE_BUT_DEPRECATED1"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_BUT_DEPRECATED1",
      "kind": "symbol",
      "role": "symbol",
      "title": "CS_AVAILABLE_BUT_DEPRECATED1",
      "type": "topic",
      "url": "/documentation/colorsync/cs_available_but_deprecated1"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_BUT_DEPRECATED2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CS_AVAILABLE_BUT_DEPRECATED2"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_BUT_DEPRECATED2",
      "kind": "symbol",
      "role": "symbol",
      "title": "CS_AVAILABLE_BUT_DEPRECATED2",
      "type": "topic",
      "url": "/documentation/colorsync/cs_available_but_deprecated2"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_BUT_DEPRECATED3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CS_AVAILABLE_BUT_DEPRECATED3"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_BUT_DEPRECATED3",
      "kind": "symbol",
      "role": "symbol",
      "title": "CS_AVAILABLE_BUT_DEPRECATED3",
      "type": "topic",
      "url": "/documentation/colorsync/cs_available_but_deprecated3"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_BUT_DEPRECATED4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CS_AVAILABLE_BUT_DEPRECATED4"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_BUT_DEPRECATED4",
      "kind": "symbol",
      "role": "symbol",
      "title": "CS_AVAILABLE_BUT_DEPRECATED4",
      "type": "topic",
      "url": "/documentation/colorsync/cs_available_but_deprecated4"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_BUT_DEPRECATED5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CS_AVAILABLE_BUT_DEPRECATED5"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_BUT_DEPRECATED5",
      "kind": "symbol",
      "role": "symbol",
      "title": "CS_AVAILABLE_BUT_DEPRECATED5",
      "type": "topic",
      "url": "/documentation/colorsync/cs_available_but_deprecated5"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_DESKTOP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CS_AVAILABLE_DESKTOP"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_DESKTOP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CS_AVAILABLE_DESKTOP",
      "type": "topic",
      "url": "/documentation/colorsync/cs_available_desktop"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_STARTING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CS_AVAILABLE_STARTING"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_STARTING",
      "kind": "symbol",
      "role": "symbol",
      "title": "CS_AVAILABLE_STARTING",
      "type": "topic",
      "url": "/documentation/colorsync/cs_available_starting"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_STARTING1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CS_AVAILABLE_STARTING1"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_STARTING1",
      "kind": "symbol",
      "role": "symbol",
      "title": "CS_AVAILABLE_STARTING1",
      "type": "topic",
      "url": "/documentation/colorsync/cs_available_starting1"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Macros",
      "generated": true,
      "identifiers": [
        "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_ITERATE_ASYNC",
        "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_MD5_LENGTH",
        "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_PROFILE_INSTALL_ENTITLEMENT",
        "doc://com.apple.colorsync/documentation/ColorSync/CSEXPORT",
        "doc://com.apple.colorsync/documentation/ColorSync/CSEXTERN",
        "doc://com.apple.colorsync/documentation/ColorSync/CSEXTERN_DESKTOP",
        "doc://com.apple.colorsync/documentation/ColorSync/CSLOCAL",
        "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_BUT_DEPRECATED",
        "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_BUT_DEPRECATED1",
        "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_BUT_DEPRECATED2",
        "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_BUT_DEPRECATED3",
        "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_BUT_DEPRECATED4",
        "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_BUT_DEPRECATED5",
        "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_DESKTOP",
        "doc://com.apple.colorsync/documentation/ColorSync/CS_AVAILABLE_STARTING1"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1COLORSYNC_PROFILE_INSTALL_ENTITLEMENT/title",
          "value": "COLORSYNC_PROFILE_INSTALL_ENTITLEMENT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1COLORSYNC_PROFILE_INSTALL_ENTITLEMENT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COLORSYNC_PROFILE_INSTALL_ENTITLEMENT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1COLORSYNC_MD5_LENGTH/title",
          "value": "COLORSYNC_MD5_LENGTH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1COLORSYNC_MD5_LENGTH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COLORSYNC_MD5_LENGTH"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/colorsync/cs_available_starting"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
