{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.colorsync/documentation/ColorSync"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncSigCmykData"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kColorSyncSigCmykData",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kColorSyncSigCmykData"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s9UnmanagedV",
        "text": "Unmanaged"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": ">!"
      }
    ],
    "modules": [
      {
        "name": "ColorSync"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kColorSyncSigCmykData"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kColorSyncSigCmykData"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kColorSyncSigCmykData"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s9UnmanagedV",
              "text": "Unmanaged"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": ">!"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.colorsync/documentation/ColorSync": {
      "abstract": [
        {
          "text": "Reproduce colors accurately across a range of input, output, and display devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync",
      "kind": "symbol",
      "role": "collection",
      "title": "ColorSync",
      "type": "topic",
      "url": "/documentation/colorsync"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_MD5_LENGTH": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COLORSYNC_MD5_LENGTH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_MD5_LENGTH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COLORSYNC_MD5_LENGTH"
        }
      ],
      "role": "symbol",
      "title": "COLORSYNC_MD5_LENGTH",
      "type": "topic",
      "url": "/documentation/colorsync/colorsync_md5_length"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_PROFILE_INSTALL_ENTITLEMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COLORSYNC_PROFILE_INSTALL_ENTITLEMENT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_PROFILE_INSTALL_ENTITLEMENT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COLORSYNC_PROFILE_INSTALL_ENTITLEMENT"
        }
      ],
      "role": "symbol",
      "title": "COLORSYNC_PROFILE_INSTALL_ENTITLEMENT",
      "type": "topic",
      "url": "/documentation/colorsync/colorsync_profile_install_entitlement"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kCMMApplyTransformProcName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMApplyTransformProcName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kCMMApplyTransformProcName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMApplyTransformProcName"
        }
      ],
      "role": "symbol",
      "title": "kCMMApplyTransformProcName",
      "type": "topic",
      "url": "/documentation/colorsync/kcmmapplytransformprocname"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kCMMCreateTransformPropertyProcName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMCreateTransformPropertyProcName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kCMMCreateTransformPropertyProcName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMCreateTransformPropertyProcName"
        }
      ],
      "role": "symbol",
      "title": "kCMMCreateTransformPropertyProcName",
      "type": "topic",
      "url": "/documentation/colorsync/kcmmcreatetransformpropertyprocname"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kCMMInitializeLinkProfileProcName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMInitializeLinkProfileProcName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kCMMInitializeLinkProfileProcName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMInitializeLinkProfileProcName"
        }
      ],
      "role": "symbol",
      "title": "kCMMInitializeLinkProfileProcName",
      "type": "topic",
      "url": "/documentation/colorsync/kcmminitializelinkprofileprocname"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kCMMInitializeTransformProcName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMInitializeTransformProcName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kCMMInitializeTransformProcName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMInitializeTransformProcName"
        }
      ],
      "role": "symbol",
      "title": "kCMMInitializeTransformProcName",
      "type": "topic",
      "url": "/documentation/colorsync/kcmminitializetransformprocname"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSync10BitInteger": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSync10BitInteger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ColorSyncDataDepth",
          "text": "ColorSyncDataDepth"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSync10BitInteger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSync10BitInteger"
        }
      ],
      "role": "symbol",
      "title": "kColorSync10BitInteger",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsync10bitinteger"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSync16BitFloat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSync16BitFloat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ColorSyncDataDepth",
          "text": "ColorSyncDataDepth"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSync16BitFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSync16BitFloat"
        }
      ],
      "role": "symbol",
      "title": "kColorSync16BitFloat",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsync16bitfloat"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSync16BitInteger": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSync16BitInteger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ColorSyncDataDepth",
          "text": "ColorSyncDataDepth"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSync16BitInteger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSync16BitInteger"
        }
      ],
      "role": "symbol",
      "title": "kColorSync16BitInteger",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsync16bitinteger"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSync1BitGamut": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSync1BitGamut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ColorSyncDataDepth",
          "text": "ColorSyncDataDepth"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSync1BitGamut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSync1BitGamut"
        }
      ],
      "role": "symbol",
      "title": "kColorSync1BitGamut",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsync1bitgamut"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitFloat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSync32BitFloat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ColorSyncDataDepth",
          "text": "ColorSyncDataDepth"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSync32BitFloat"
        }
      ],
      "role": "symbol",
      "title": "kColorSync32BitFloat",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsync32bitfloat"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitInteger": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSync32BitInteger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ColorSyncDataDepth",
          "text": "ColorSyncDataDepth"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitInteger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSync32BitInteger"
        }
      ],
      "role": "symbol",
      "title": "kColorSync32BitInteger",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsync32bitinteger"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitNamedColorIndex": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSync32BitNamedColorIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ColorSyncDataDepth",
          "text": "ColorSyncDataDepth"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitNamedColorIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSync32BitNamedColorIndex"
        }
      ],
      "role": "symbol",
      "title": "kColorSync32BitNamedColorIndex",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsync32bitnamedcolorindex"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSync8BitInteger": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSync8BitInteger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ColorSyncDataDepth",
          "text": "ColorSyncDataDepth"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSync8BitInteger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSync8BitInteger"
        }
      ],
      "role": "symbol",
      "title": "kColorSync8BitInteger",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsync8bitinteger"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncACESCGLinearProfile": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncACESCGLinearProfile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncACESCGLinearProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncACESCGLinearProfile"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncACESCGLinearProfile",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsyncacescglinearprofile"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncSigCmykData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncSigCmykData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncSigCmykData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncSigCmykData"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncSigCmykData",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsyncsigcmykdata"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    },
    "doc://com.externally.resolved.symbol/s:s9UnmanagedV": {
      "abstract": [
        {
          "text": "A type for propagating an unmanaged object reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Unmanaged",
      "type": "topic",
      "url": "/documentation/Swift/Unmanaged"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_MD5_LENGTH",
        "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_PROFILE_INSTALL_ENTITLEMENT",
        "doc://com.apple.colorsync/documentation/ColorSync/kCMMApplyTransformProcName",
        "doc://com.apple.colorsync/documentation/ColorSync/kCMMCreateTransformPropertyProcName",
        "doc://com.apple.colorsync/documentation/ColorSync/kCMMInitializeLinkProfileProcName",
        "doc://com.apple.colorsync/documentation/ColorSync/kCMMInitializeTransformProcName",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSync1BitGamut",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSync10BitInteger",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSync16BitFloat",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSync16BitInteger",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitFloat",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitInteger",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitNamedColorIndex",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSync8BitInteger",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncACESCGLinearProfile"
      ],
      "title": "Variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kColorSyncSigCmykData"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncSigCmykData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.colorsync/documentation/ColorSync"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_MD5_LENGTH",
                "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_PROFILE_INSTALL_ENTITLEMENT",
                "doc://com.apple.colorsync/documentation/ColorSync/kCMMApplyTransformProcName",
                "doc://com.apple.colorsync/documentation/ColorSync/kCMMCreateTransformPropertyProcName",
                "doc://com.apple.colorsync/documentation/ColorSync/kCMMInitializeLinkProfileProcName",
                "doc://com.apple.colorsync/documentation/ColorSync/kCMMInitializeTransformProcName",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSync1BitGamut",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSync10BitInteger",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSync16BitFloat",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSync16BitInteger",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitFloat",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitInteger",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitNamedColorIndex",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSync8BitInteger",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncACESCGLinearProfile"
              ],
              "title": "Variables"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kColorSyncSigCmykData"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1COLORSYNC_MD5_LENGTH/title",
          "value": "COLORSYNC_MD5_LENGTH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1COLORSYNC_MD5_LENGTH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COLORSYNC_MD5_LENGTH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync32BitInteger/title",
          "value": "kColorSync32BitInteger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync32BitInteger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSync32BitInteger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync32BitFloat/title",
          "value": "kColorSync32BitFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync32BitFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSync32BitFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kCMMApplyTransformProcName/title",
          "value": "kCMMApplyTransformProcName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kCMMApplyTransformProcName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMApplyTransformProcName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncACESCGLinearProfile/title",
          "value": "kColorSyncACESCGLinearProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncACESCGLinearProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncACESCGLinearProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kCMMInitializeLinkProfileProcName/title",
          "value": "kCMMInitializeLinkProfileProcName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kCMMInitializeLinkProfileProcName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMInitializeLinkProfileProcName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1COLORSYNC_PROFILE_INSTALL_ENTITLEMENT/title",
          "value": "COLORSYNC_PROFILE_INSTALL_ENTITLEMENT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1COLORSYNC_PROFILE_INSTALL_ENTITLEMENT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COLORSYNC_PROFILE_INSTALL_ENTITLEMENT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kCMMInitializeTransformProcName/title",
          "value": "kCMMInitializeTransformProcName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kCMMInitializeTransformProcName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMInitializeTransformProcName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync16BitFloat/title",
          "value": "kColorSync16BitFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync16BitFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSync16BitFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync16BitInteger/title",
          "value": "kColorSync16BitInteger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync16BitInteger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSync16BitInteger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncSigCmykData/title",
          "value": "kColorSyncSigCmykData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncSigCmykData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncSigCmykData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync8BitInteger/title",
          "value": "kColorSync8BitInteger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync8BitInteger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSync8BitInteger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync10BitInteger/title",
          "value": "kColorSync10BitInteger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync10BitInteger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSync10BitInteger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync32BitNamedColorIndex/title",
          "value": "kColorSync32BitNamedColorIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync32BitNamedColorIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSync32BitNamedColorIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kCMMCreateTransformPropertyProcName/title",
          "value": "kCMMCreateTransformPropertyProcName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kCMMCreateTransformPropertyProcName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMCreateTransformPropertyProcName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync1BitGamut/title",
          "value": "kColorSync1BitGamut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync1BitGamut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSync1BitGamut"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/colorsync/kcolorsyncsigcmykdata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/colorsync/kcolorsyncsigcmykdata"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
