{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.colorsync/documentation/ColorSync"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncByteOrderDefault"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kColorSyncAlphaInfoMask@kColorSyncByteOrderDefault",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kColorSyncByteOrderDefault"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "ColorSync"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kColorSyncByteOrderDefault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kColorSyncByteOrderDefault"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kColorSyncByteOrderDefault"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.colorsync/documentation/ColorSync": {
      "abstract": [
        {
          "text": "Reproduce colors accurately across a range of input, output, and display devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync",
      "kind": "symbol",
      "role": "collection",
      "title": "ColorSync",
      "type": "topic",
      "url": "/documentation/colorsync"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSync16BitFloat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSync16BitFloat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ColorSyncDataDepth",
          "text": "ColorSyncDataDepth"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSync16BitFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSync16BitFloat"
        }
      ],
      "role": "symbol",
      "title": "kColorSync16BitFloat",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsync16bitfloat"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitFloat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSync32BitFloat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ColorSyncDataDepth",
          "text": "ColorSyncDataDepth"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSync32BitFloat"
        }
      ],
      "role": "symbol",
      "title": "kColorSync32BitFloat",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsync32bitfloat"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitNamedColorIndex": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSync32BitNamedColorIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ColorSyncDataDepth",
          "text": "ColorSyncDataDepth"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitNamedColorIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSync32BitNamedColorIndex"
        }
      ],
      "role": "symbol",
      "title": "kColorSync32BitNamedColorIndex",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsync32bitnamedcolorindex"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSync8BitInteger": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSync8BitInteger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ColorSyncDataDepth",
          "text": "ColorSyncDataDepth"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSync8BitInteger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSync8BitInteger"
        }
      ],
      "role": "symbol",
      "title": "kColorSync8BitInteger",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsync8bitinteger"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncAlphaInfoMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncAlphaInfoMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncAlphaInfoMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncAlphaInfoMask"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncAlphaInfoMask",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsyncalphainfomask"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncAlphaNoneSkipLast": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncAlphaNoneSkipLast"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ColorSyncAlphaInfo",
          "text": "ColorSyncAlphaInfo"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncAlphaNoneSkipLast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncAlphaNoneSkipLast"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncAlphaNoneSkipLast",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsyncalphanoneskiplast"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncAlphaPremultipliedFirst": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncAlphaPremultipliedFirst"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ColorSyncAlphaInfo",
          "text": "ColorSyncAlphaInfo"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncAlphaPremultipliedFirst",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncAlphaPremultipliedFirst"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncAlphaPremultipliedFirst",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsyncalphapremultipliedfirst"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncAlphaPremultipliedLast": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncAlphaPremultipliedLast"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ColorSyncAlphaInfo",
          "text": "ColorSyncAlphaInfo"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncAlphaPremultipliedLast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncAlphaPremultipliedLast"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncAlphaPremultipliedLast",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsyncalphapremultipliedlast"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncByteOrderDefault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncByteOrderDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncByteOrderDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncByteOrderDefault"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncByteOrderDefault",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsyncbyteorderdefault"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncByteOrderMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncByteOrderMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncByteOrderMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncByteOrderMask"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncByteOrderMask",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsyncbyteordermask"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSync16BitFloat",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitFloat",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitNamedColorIndex",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSync8BitInteger",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncAlphaInfoMask",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncAlphaNoneSkipLast",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncAlphaPremultipliedFirst",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncAlphaPremultipliedLast",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncByteOrderMask"
      ],
      "title": "Enumeration cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kColorSyncByteOrderDefault"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncByteOrderDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.colorsync/documentation/ColorSync"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSync16BitFloat",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitFloat",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSync32BitNamedColorIndex",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSync8BitInteger",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncAlphaInfoMask",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncAlphaNoneSkipLast",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncAlphaPremultipliedFirst",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncAlphaPremultipliedLast",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncByteOrderMask"
              ],
              "title": "Enumeration cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kColorSyncByteOrderDefault"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncAlphaInfoMask/title",
          "value": "kColorSyncAlphaInfoMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncAlphaInfoMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncAlphaInfoMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync8BitInteger/title",
          "value": "kColorSync8BitInteger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync8BitInteger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSync8BitInteger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncByteOrderMask/title",
          "value": "kColorSyncByteOrderMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncByteOrderMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncByteOrderMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncAlphaPremultipliedLast/title",
          "value": "kColorSyncAlphaPremultipliedLast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncAlphaPremultipliedLast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncAlphaPremultipliedLast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncAlphaNoneSkipLast/title",
          "value": "kColorSyncAlphaNoneSkipLast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncAlphaNoneSkipLast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncAlphaNoneSkipLast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync16BitFloat/title",
          "value": "kColorSync16BitFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync16BitFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSync16BitFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncAlphaPremultipliedFirst/title",
          "value": "kColorSyncAlphaPremultipliedFirst"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncAlphaPremultipliedFirst/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncAlphaPremultipliedFirst"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync32BitNamedColorIndex/title",
          "value": "kColorSync32BitNamedColorIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync32BitNamedColorIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSync32BitNamedColorIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync32BitFloat/title",
          "value": "kColorSync32BitFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSync32BitFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSync32BitFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncByteOrderDefault/title",
          "value": "kColorSyncByteOrderDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncByteOrderDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncByteOrderDefault"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/colorsync/kcolorsyncbyteorderdefault"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/colorsync/kcolorsyncbyteorderdefault"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
