{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.colorsync/documentation/ColorSync"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncHLGDerivative"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kColorSyncHLGDerivative",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kColorSyncHLGDerivative"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s9UnmanagedV",
        "text": "Unmanaged"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": ">!"
      }
    ],
    "modules": [
      {
        "name": "ColorSync"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kColorSyncHLGDerivative"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kColorSyncHLGDerivative"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kColorSyncHLGDerivative"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s9UnmanagedV",
              "text": "Unmanaged"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": ">!"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.colorsync/documentation/ColorSync": {
      "abstract": [
        {
          "text": "Reproduce colors accurately across a range of input, output, and display devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync",
      "kind": "symbol",
      "role": "collection",
      "title": "ColorSync",
      "type": "topic",
      "url": "/documentation/colorsync"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_API_VERSION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COLORSYNC_API_VERSION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_API_VERSION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COLORSYNC_API_VERSION"
        }
      ],
      "role": "symbol",
      "title": "COLORSYNC_API_VERSION",
      "type": "topic",
      "url": "/documentation/colorsync/colorsync_api_version"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/icVersion4Number": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "icVersion4Number"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/icVersion4Number",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "icVersion4Number"
        }
      ],
      "role": "symbol",
      "title": "icVersion4Number",
      "type": "topic",
      "url": "/documentation/colorsync/icversion4number"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncExtendedRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncExtendedRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncExtendedRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncExtendedRange"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncExtendedRange",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsyncextendedrange"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncHDRDerivative": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncHDRDerivative"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncHDRDerivative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncHDRDerivative"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncHDRDerivative",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsynchdrderivative"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncHLGDerivative": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncHLGDerivative"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncHLGDerivative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncHLGDerivative"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncHLGDerivative",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsynchlgderivative"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncPQDerivative": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncPQDerivative"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncPQDerivative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncPQDerivative"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncPQDerivative",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsyncpqderivative"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncProfileCacheSeed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncProfileCacheSeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncProfileCacheSeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncProfileCacheSeed"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncProfileCacheSeed",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsyncprofilecacheseed"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncProfileIsValid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncProfileIsValid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncProfileIsValid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncProfileIsValid"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncProfileIsValid",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsyncprofileisvalid"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncProfileRepositoryChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncProfileRepositoryChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncProfileRepositoryChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncProfileRepositoryChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncProfileRepositoryChangeNotification",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsyncprofilerepositorychangenotification"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncRegistrationUpdateWindowServer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncRegistrationUpdateWindowServer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncRegistrationUpdateWindowServer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncRegistrationUpdateWindowServer"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncRegistrationUpdateWindowServer",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsyncregistrationupdatewindowserver"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncTransformCodeFragmentMD5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncTransformCodeFragmentMD5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncTransformCodeFragmentMD5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncTransformCodeFragmentMD5"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncTransformCodeFragmentMD5",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsynctransformcodefragmentmd5"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncTransformInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncTransformInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncTransformInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncTransformInfo"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncTransformInfo",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsynctransforminfo"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncTransformProfileSequnce": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncTransformProfileSequnce"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncTransformProfileSequnce",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncTransformProfileSequnce"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncTransformProfileSequnce",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsynctransformprofilesequnce"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncWaitForCacheReply": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncWaitForCacheReply"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncWaitForCacheReply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncWaitForCacheReply"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncWaitForCacheReply",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsyncwaitforcachereply"
    },
    "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncWebSafeColorsProfile": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kColorSyncWebSafeColorsProfile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncWebSafeColorsProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kColorSyncWebSafeColorsProfile"
        }
      ],
      "role": "symbol",
      "title": "kColorSyncWebSafeColorsProfile",
      "type": "topic",
      "url": "/documentation/colorsync/kcolorsyncwebsafecolorsprofile"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    },
    "doc://com.externally.resolved.symbol/s:s9UnmanagedV": {
      "abstract": [
        {
          "text": "A type for propagating an unmanaged object reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Unmanaged",
      "type": "topic",
      "url": "/documentation/Swift/Unmanaged"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_API_VERSION",
        "doc://com.apple.colorsync/documentation/ColorSync/icVersion4Number",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncExtendedRange",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncHDRDerivative",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncPQDerivative",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncProfileCacheSeed",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncProfileIsValid",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncProfileRepositoryChangeNotification",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncRegistrationUpdateWindowServer",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncTransformCodeFragmentMD5",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncTransformInfo",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncTransformProfileSequnce",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncWaitForCacheReply",
        "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncWebSafeColorsProfile"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kColorSyncHLGDerivative"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncHLGDerivative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.colorsync/documentation/ColorSync"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.colorsync/documentation/ColorSync/COLORSYNC_API_VERSION",
                "doc://com.apple.colorsync/documentation/ColorSync/icVersion4Number",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncExtendedRange",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncHDRDerivative",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncPQDerivative",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncProfileCacheSeed",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncProfileIsValid",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncProfileRepositoryChangeNotification",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncRegistrationUpdateWindowServer",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncTransformCodeFragmentMD5",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncTransformInfo",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncTransformProfileSequnce",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncWaitForCacheReply",
                "doc://com.apple.colorsync/documentation/ColorSync/kColorSyncWebSafeColorsProfile"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kColorSyncHLGDerivative"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncRegistrationUpdateWindowServer/title",
          "value": "kColorSyncRegistrationUpdateWindowServer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncRegistrationUpdateWindowServer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncRegistrationUpdateWindowServer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncTransformCodeFragmentMD5/title",
          "value": "kColorSyncTransformCodeFragmentMD5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncTransformCodeFragmentMD5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncTransformCodeFragmentMD5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncExtendedRange/title",
          "value": "kColorSyncExtendedRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncExtendedRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncExtendedRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncHLGDerivative/title",
          "value": "kColorSyncHLGDerivative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncHLGDerivative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncHLGDerivative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncWebSafeColorsProfile/title",
          "value": "kColorSyncWebSafeColorsProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncWebSafeColorsProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncWebSafeColorsProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1icVersion4Number/title",
          "value": "icVersion4Number"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1icVersion4Number/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "icVersion4Number"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncTransformInfo/title",
          "value": "kColorSyncTransformInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncTransformInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncTransformInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncProfileRepositoryChangeNotification/title",
          "value": "kColorSyncProfileRepositoryChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncProfileRepositoryChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncProfileRepositoryChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncProfileIsValid/title",
          "value": "kColorSyncProfileIsValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncProfileIsValid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncProfileIsValid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncWaitForCacheReply/title",
          "value": "kColorSyncWaitForCacheReply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncWaitForCacheReply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncWaitForCacheReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncTransformProfileSequnce/title",
          "value": "kColorSyncTransformProfileSequnce"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncTransformProfileSequnce/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncTransformProfileSequnce"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncProfileCacheSeed/title",
          "value": "kColorSyncProfileCacheSeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncProfileCacheSeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncProfileCacheSeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncPQDerivative/title",
          "value": "kColorSyncPQDerivative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncPQDerivative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncPQDerivative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncHDRDerivative/title",
          "value": "kColorSyncHDRDerivative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1kColorSyncHDRDerivative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kColorSyncHDRDerivative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1COLORSYNC_API_VERSION/title",
          "value": "COLORSYNC_API_VERSION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.colorsync~1documentation~1ColorSync~1COLORSYNC_API_VERSION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COLORSYNC_API_VERSION"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/colorsync/kcolorsynchlgderivative"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/colorsync/kcolorsynchlgderivative"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
