{
  "abstract": [
    {
      "text": "Draws the annotation on its associated page.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/draw(with:in:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/draw(with:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "PDFKit",
    "externalID": "c:objc(cs)PDFAnnotation(im)drawWithBox:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "draw"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "with"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@PDFDisplayBox",
        "text": "PDFDisplayBox"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "drawWithBox:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "draw(with:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "draw"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "with"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "box"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayBox",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PDFDisplayBox",
              "text": "PDFDisplayBox"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The bounding box to draw the annotation in.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "box"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.pdfkit/documentation/PDFKit/adding-custom-graphics-to-a-pdf"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The annotation is drawn relative to the origin of ",
              "type": "text"
            },
            {
              "code": "box",
              "type": "codeVoice"
            },
            {
              "text": " in page-space coordinates.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Page space is a 72 dpi coordinate system with the origin at the lower-left corner of the current page.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation": {
      "abstract": [
        {
          "text": "An annotation in a PDF document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotation"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotation"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotation",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotation"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/draw(with:)": {
      "abstract": [
        {
          "text": "Draws the annotation on its associated page.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draw"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFDisplayBox",
          "text": "PDFDisplayBox"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/draw(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawWithBox:"
        }
      ],
      "role": "symbol",
      "title": "draw(with:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotation/draw(with:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/draw(with:in:)": {
      "abstract": [
        {
          "text": "Draws the annotation in a graphics context using page-space coordinates relative to the origin of the specified box.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draw"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFDisplayBox",
          "text": "PDFDisplayBox"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGContextRef",
          "text": "CGContext"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/draw(with:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawWithBox:inContext:"
        }
      ],
      "role": "symbol",
      "title": "draw(with:in:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotation/draw(with:in:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/init(bounds:)": {
      "abstract": [
        {
          "text": "Creates a PDF annotation object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/init(bounds:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithBounds:"
        }
      ],
      "role": "symbol",
      "title": "init(bounds:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotation/init(bounds:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/init(dictionary:forPage:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "dictionary"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "forPage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFPage",
          "text": "PDFPage"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/init(dictionary:forPage:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDictionary:forPage:"
        }
      ],
      "role": "symbol",
      "title": "init(dictionary:forPage:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotation/init(dictionary:forpage:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/removeAllAppearanceStreams()": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllAppearanceStreams"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/removeAllAppearanceStreams()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllAppearanceStreams"
        }
      ],
      "role": "symbol",
      "title": "removeAllAppearanceStreams()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotation/removeallappearancestreams()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayBox": {
      "abstract": [
        {
          "text": "The following box types may be used with ",
          "type": "text"
        },
        {
          "code": "PDFPage",
          "type": "codeVoice"
        },
        {
          "text": " drawing and bounds-setting methods. See the Adobe PDF Specification for more information on box types, units, and coordinate systems.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFDisplayBox"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDisplayBox"
        }
      ],
      "role": "symbol",
      "title": "PDFDisplayBox",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfdisplaybox"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/bounds(for:)": {
      "abstract": [
        {
          "text": "Returns the bounds for the specified PDF display box.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bounds"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFDisplayBox",
          "text": "PDFDisplayBox"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/bounds(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "boundsForBox:"
        }
      ],
      "role": "symbol",
      "title": "bounds(for:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfpage/bounds(for:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/adding-custom-graphics-to-a-pdf": {
      "abstract": [
        {
          "text": "Create and add custom annotation and page graphics to your PDF document.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/adding-custom-graphics-to-a-pdf",
      "kind": "article",
      "role": "article",
      "title": "Adding Custom Graphics to a PDF",
      "type": "topic",
      "url": "/documentation/pdfkit/adding-custom-graphics-to-a-pdf"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/bounds(for:)"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Deprecated-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/init(bounds:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/init(dictionary:forPage:)",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/removeAllAppearanceStreams()"
      ],
      "title": "Deprecated Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.12",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "drawWithBox:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawWithBox:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFPage/bounds(for:)"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Deprecated-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/init(bounds:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/init(dictionary:forPage:)",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/removeAllAppearanceStreams()"
              ],
              "title": "Deprecated Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "drawWithBox:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFDisplayBox",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@PDFDisplayBox",
                    "text": "PDFDisplayBox"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "box"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The bounding box to draw the annotation in.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "box"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotation/draw(with:in:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1init(dictionary:forPage:)/title",
          "value": "initWithDictionary:forPage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1init(dictionary:forPage:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDictionary:forPage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayBox/title",
          "value": "PDFDisplayBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDisplayBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFDisplayBox/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFDisplayBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1draw(with:)/title",
          "value": "drawWithBox:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1draw(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawWithBox:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation/title",
          "value": "PDFAnnotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1draw(with:in:)/title",
          "value": "drawWithBox:inContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1draw(with:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawWithBox:inContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1removeAllAppearanceStreams()/title",
          "value": "removeAllAppearanceStreams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1removeAllAppearanceStreams()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAllAppearanceStreams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage~1bounds(for:)/title",
          "value": "boundsForBox:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFPage~1bounds(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "boundsForBox:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1init(bounds:)/title",
          "value": "initWithBounds:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotation~1init(bounds:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithBounds:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfannotation/draw(with:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfannotation/draw(with:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
