{
  "abstract": [
    {
      "text": "The default argument for initializing the host object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObjectInitOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObjectInitOptions/IOUSBHostObjectInitOptionsNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@IOUSBHostObjectInitOptions@IOUSBHostObjectInitOptionsNone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "IOUSBHostObjectInitOptionsNone"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOUSBHostObjectInitOptionsNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "IOUSBHostObjectInitOptionsNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "IOUSBHostObjectInitOptionsNone"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObjectInitOptions": {
      "abstract": [
        {
          "text": "Options for initializing the host object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostObjectInitOptions"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObjectInitOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostObjectInitOptions"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostObjectInitOptions",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostobjectinitoptions"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObjectInitOptions/IOUSBHostObjectInitOptionsNone": {
      "abstract": [
        {
          "text": "The default argument for initializing the host object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOUSBHostObjectInitOptionsNone"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObjectInitOptions/IOUSBHostObjectInitOptionsNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOUSBHostObjectInitOptionsNone",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostobjectinitoptions/iousbhostobjectinitoptionsnone"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObjectInitOptions/deviceCapture": {
      "abstract": [
        {
          "text": "The option to capture the device and terminate existing drivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceCapture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IOUSBHostObjectInitOptions",
          "text": "IOUSBHostObjectInitOptions"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObjectInitOptions/deviceCapture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostObjectInitOptionsDeviceCapture"
        }
      ],
      "role": "symbol",
      "title": "deviceCapture",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostobjectinitoptions/devicecapture"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostObjectInitOptions/deviceCapture"
      ],
      "title": "Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostObjectInitOptions~1deviceCapture/title",
          "value": "IOUSBHostObjectInitOptionsDeviceCapture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostObjectInitOptions~1deviceCapture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostObjectInitOptionsDeviceCapture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostObjectInitOptions/title",
          "value": "IOUSBHostObjectInitOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostObjectInitOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostObjectInitOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostObjectInitOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostObjectInitOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhostobjectinitoptions/iousbhostobjectinitoptionsnone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
