{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/palette"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ICScannerPixelDataType@ICScannerPixelDataTypePalette",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "palette"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICScannerPixelDataTypePalette"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ICScannerPixelDataType.palette"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "palette"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType": {
      "abstract": [
        {
          "text": "The pixel data types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerPixelDataType"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerPixelDataType"
        }
      ],
      "role": "symbol",
      "title": "ICScannerPixelDataType",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerpixeldatatype"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/BW": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BW"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/BW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerPixelDataTypeBW"
        }
      ],
      "role": "symbol",
      "title": "ICScannerPixelDataType.BW",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerpixeldatatype/bw"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/CIEXYZ": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CIEXYZ"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/CIEXYZ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerPixelDataTypeCIEXYZ"
        }
      ],
      "role": "symbol",
      "title": "ICScannerPixelDataType.CIEXYZ",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerpixeldatatype/ciexyz"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/CMY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMY"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/CMY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerPixelDataTypeCMY"
        }
      ],
      "role": "symbol",
      "title": "ICScannerPixelDataType.CMY",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerpixeldatatype/cmy"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/CMYK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMYK"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/CMYK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerPixelDataTypeCMYK"
        }
      ],
      "role": "symbol",
      "title": "ICScannerPixelDataType.CMYK",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerpixeldatatype/cmyk"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/RGB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RGB"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/RGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerPixelDataTypeRGB"
        }
      ],
      "role": "symbol",
      "title": "ICScannerPixelDataType.RGB",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerpixeldatatype/rgb"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/YUV": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "YUV"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/YUV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerPixelDataTypeYUV"
        }
      ],
      "role": "symbol",
      "title": "ICScannerPixelDataType.YUV",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerpixeldatatype/yuv"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/YUVK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "YUVK"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/YUVK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerPixelDataTypeYUVK"
        }
      ],
      "role": "symbol",
      "title": "ICScannerPixelDataType.YUVK",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerpixeldatatype/yuvk"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/gray": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gray"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/gray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerPixelDataTypeGray"
        }
      ],
      "role": "symbol",
      "title": "ICScannerPixelDataType.gray",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerpixeldatatype/gray"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/palette": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "palette"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/palette",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerPixelDataTypePalette"
        }
      ],
      "role": "symbol",
      "title": "ICScannerPixelDataType.palette",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerpixeldatatype/palette"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/BW",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/CIEXYZ",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/CMY",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/CMYK",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/gray",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/RGB",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/YUV",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/YUVK"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICScannerPixelDataTypePalette"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerPixelDataTypePalette"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/BW",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/CIEXYZ",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/CMY",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/CMYK",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/gray",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/RGB",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/YUV",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerPixelDataType/YUVK"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ICScannerPixelDataTypePalette"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType~1CMY/title",
          "value": "ICScannerPixelDataTypeCMY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType~1CMY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerPixelDataTypeCMY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType~1BW/title",
          "value": "ICScannerPixelDataTypeBW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType~1BW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerPixelDataTypeBW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType~1YUV/title",
          "value": "ICScannerPixelDataTypeYUV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType~1YUV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerPixelDataTypeYUV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType~1palette/title",
          "value": "ICScannerPixelDataTypePalette"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType~1palette/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerPixelDataTypePalette"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType/title",
          "value": "ICScannerPixelDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerPixelDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerPixelDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType~1gray/title",
          "value": "ICScannerPixelDataTypeGray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType~1gray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerPixelDataTypeGray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType~1RGB/title",
          "value": "ICScannerPixelDataTypeRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType~1RGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerPixelDataTypeRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType~1CMYK/title",
          "value": "ICScannerPixelDataTypeCMYK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType~1CMYK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerPixelDataTypeCMYK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType~1CIEXYZ/title",
          "value": "ICScannerPixelDataTypeCIEXYZ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType~1CIEXYZ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerPixelDataTypeCIEXYZ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType~1YUVK/title",
          "value": "ICScannerPixelDataTypeYUVK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerPixelDataType~1YUVK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerPixelDataTypeYUVK"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icscannerpixeldatatype/palette"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icscannerpixeldatatype/palette"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
