{
  "abstract": [
    {
      "text": "An object that retrieves data corresponding to a representative image for",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "the URL.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPLinkMetadata"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPLinkMetadata/imageProvider"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)LPLinkMetadata(py)imageProvider",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "imageProvider"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSItemProvider",
        "text": "NSItemProvider"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Link Presentation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "imageProvider"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "imageProvider"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "imageProvider"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSItemProvider",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSItemProvider",
              "text": "NSItemProvider"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation": {
      "abstract": [
        {
          "text": "Fetch, provide, and present rich links in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation",
      "kind": "symbol",
      "role": "collection",
      "title": "Link Presentation",
      "type": "topic",
      "url": "/documentation/linkpresentation"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPLinkMetadata": {
      "abstract": [
        {
          "text": "An object that contains metadata about a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LPLinkMetadata"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPLinkMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LPLinkMetadata"
        }
      ],
      "role": "symbol",
      "title": "LPLinkMetadata",
      "type": "topic",
      "url": "/documentation/linkpresentation/lplinkmetadata"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPLinkMetadata/iconProvider": {
      "abstract": [
        {
          "text": "An object that retrieves data corresponding to a representative icon for the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iconProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSItemProvider",
          "text": "NSItemProvider"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPLinkMetadata/iconProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iconProvider"
        }
      ],
      "role": "symbol",
      "title": "iconProvider",
      "type": "topic",
      "url": "/documentation/linkpresentation/lplinkmetadata/iconprovider"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPLinkMetadata/imageProvider": {
      "abstract": [
        {
          "text": "An object that retrieves data corresponding to a representative image for",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "the URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSItemProvider",
          "text": "NSItemProvider"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPLinkMetadata/imageProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageProvider"
        }
      ],
      "role": "symbol",
      "title": "imageProvider",
      "type": "topic",
      "url": "/documentation/linkpresentation/lplinkmetadata/imageprovider"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSItemProvider": {
      "abstract": [
        {
          "text": "An item provider for conveying data or a file between processes during drag-and-drop or copy-and-paste activities, or from a host app to an app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSItemProvider"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSItemProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSItemProvider",
      "type": "topic",
      "url": "/documentation/foundation/nsitemprovider"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-links-images",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPLinkMetadata/iconProvider"
      ],
      "title": "Getting the link’s images"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "imageProvider"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Link-Presentation/documentation/LinkPresentation",
                "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPLinkMetadata"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-links-images",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPLinkMetadata/iconProvider"
              ],
              "title": "Getting the link’s images"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "retain"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSItemProvider",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSItemProvider",
                    "text": "NSItemProvider"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "imageProvider"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPLinkMetadata/title",
          "value": "LPLinkMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPLinkMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LPLinkMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPLinkMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LPLinkMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPLinkMetadata~1imageProvider/title",
          "value": "imageProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPLinkMetadata~1imageProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPLinkMetadata~1iconProvider/title",
          "value": "iconProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPLinkMetadata~1iconProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "iconProvider"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/linkpresentation/lplinkmetadata/imageprovider"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/linkpresentation/lplinkmetadata/imageprovider"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
