{
  "abstract": [
    {
      "text": "The callback invoked to request the run delegate to determine and return the typographic ascent of glyphs in the run. This callback may be ",
      "type": "text"
    },
    {
      "code": "NULL",
      "type": "codeVoice"
    },
    {
      "text": ", which is equivalent to a ",
      "type": "text"
    },
    {
      "code": "getAscent",
      "type": "codeVoice"
    },
    {
      "text": " callback that always returns 0.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getAscent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@CTRunDelegateCallbacks@FI@getAscent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "getAscent"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CTRunDelegateGetAscentCallback",
        "text": "CTRunDelegateGetAscentCallback"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "getAscent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "getAscent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "getAscent"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateGetAscentCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CTRunDelegateGetAscentCallback",
              "text": "CTRunDelegateGetAscentCallback"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks": {
      "abstract": [
        {
          "text": "A structure holding pointers to callbacks implemented by the run delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunDelegateCallbacks"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunDelegateCallbacks"
        }
      ],
      "role": "symbol",
      "title": "CTRunDelegateCallbacks",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegatecallbacks"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/dealloc": {
      "abstract": [
        {
          "text": "The callback invoked when the retain count of a CTRunDelegate reaches 0 and the CTRunDelegate is deallocated. This callback may be ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dealloc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunDelegateDeallocateCallback",
          "text": "CTRunDelegateDeallocateCallback"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/dealloc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dealloc"
        }
      ],
      "role": "symbol",
      "title": "dealloc",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegatecallbacks/dealloc"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getAscent": {
      "abstract": [
        {
          "text": "The callback invoked to request the run delegate to determine and return the typographic ascent of glyphs in the run. This callback may be ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ", which is equivalent to a ",
          "type": "text"
        },
        {
          "code": "getAscent",
          "type": "codeVoice"
        },
        {
          "text": " callback that always returns 0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getAscent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunDelegateGetAscentCallback",
          "text": "CTRunDelegateGetAscentCallback"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getAscent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getAscent"
        }
      ],
      "role": "symbol",
      "title": "getAscent",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegatecallbacks/getascent"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getDescent": {
      "abstract": [
        {
          "text": "The callback invoked to request the run delegate to determine and return the typographic descent of glyphs in the run. This callback may be ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ", which is equivalent to a ",
          "type": "text"
        },
        {
          "code": "getDescent",
          "type": "codeVoice"
        },
        {
          "text": " callback that always returns 0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getDescent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunDelegateGetDescentCallback",
          "text": "CTRunDelegateGetDescentCallback"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getDescent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getDescent"
        }
      ],
      "role": "symbol",
      "title": "getDescent",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegatecallbacks/getdescent"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getWidth": {
      "abstract": [
        {
          "text": "The callback invoked to request the run delegate to determine and return the typographic width of glyphs in the run. This callback may be ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ", which is equivalent to a ",
          "type": "text"
        },
        {
          "code": "getWidth",
          "type": "codeVoice"
        },
        {
          "text": " callback that always returns 0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunDelegateGetWidthCallback",
          "text": "CTRunDelegateGetWidthCallback"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getWidth"
        }
      ],
      "role": "symbol",
      "title": "getWidth",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegatecallbacks/getwidth"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/version": {
      "abstract": [
        {
          "text": "The version number of the callbacks being passed in as a parameter to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCreate(_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ". The initial version is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTRunDelegateVersion1",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegatecallbacks/version"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCreate(_:_:)": {
      "abstract": [
        {
          "text": "Creates an immutable instance of a run delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunDelegateCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CTRunDelegateCallbacks",
          "text": "CTRunDelegateCallbacks"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunDelegateRef",
          "text": "CTRunDelegate"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCreate(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunDelegateCreate"
        }
      ],
      "role": "symbol",
      "title": "CTRunDelegateCreate(_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegatecreate(_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateGetAscentCallback": {
      "abstract": [
        {
          "text": "Defines a pointer to a function that determines typographic ascent of glyphs in the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunDelegateGetAscentCallback"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateGetAscentCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunDelegateGetAscentCallback"
        }
      ],
      "role": "symbol",
      "title": "CTRunDelegateGetAscentCallback",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegategetascentcallback"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTRunDelegateVersion1": {
      "abstract": [
        {
          "text": "Version 1 of the run delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTRunDelegateVersion1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTRunDelegateVersion1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRunDelegateVersion1"
        }
      ],
      "role": "symbol",
      "title": "kCTRunDelegateVersion1",
      "type": "topic",
      "url": "/documentation/coretext/kctrundelegateversion1"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/dealloc",
        "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getDescent",
        "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getWidth",
        "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/version"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "getAscent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "getAscent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/dealloc",
                "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getDescent",
                "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getWidth",
                "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/version"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateGetAscentCallback",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CTRunDelegateGetAscentCallback",
                    "text": "CTRunDelegateGetAscentCallback"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "getAscent"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks/title",
          "value": "CTRunDelegateCallbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateGetAscentCallback/title",
          "value": "CTRunDelegateGetAscentCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateGetAscentCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateGetAscentCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateGetAscentCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateGetAscentCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1getAscent/title",
          "value": "getAscent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1getAscent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "getAscent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1getDescent/title",
          "value": "getDescent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1getDescent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "getDescent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1getWidth/title",
          "value": "getWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1getWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "getWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1dealloc/title",
          "value": "dealloc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1dealloc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dealloc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCreate(_:_:)/title",
          "value": "CTRunDelegateCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCreate(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTRunDelegateVersion1/title",
          "value": "kCTRunDelegateVersion1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTRunDelegateVersion1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRunDelegateVersion1"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctrundelegatecallbacks/getascent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctrundelegatecallbacks/getascent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
