{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/init(version:dealloc:getAscent:getDescent:getWidth:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So22CTRunDelegateCallbacksa7version7dealloc9getAscent0F7Descent0F5WidthABSi_ySvXC14CoreFoundation7CGFloatVSvXCAJSvXCAJSvXCtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "version"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFIndex",
        "text": "CFIndex"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "dealloc"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CTRunDelegateDeallocateCallback",
        "text": "CTRunDelegateDeallocateCallback"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "getAscent"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CTRunDelegateGetAscentCallback",
        "text": "CTRunDelegateGetAscentCallback"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "getDescent"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CTRunDelegateGetDescentCallback",
        "text": "CTRunDelegateGetDescentCallback"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "getWidth"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CTRunDelegateGetWidthCallback",
        "text": "CTRunDelegateGetWidthCallback"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(version:dealloc:getAscent:getDescent:getWidth:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "version"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFIndex",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFIndex",
              "text": "CFIndex"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "dealloc"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateDeallocateCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CTRunDelegateDeallocateCallback",
              "text": "CTRunDelegateDeallocateCallback"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "getAscent"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateGetAscentCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CTRunDelegateGetAscentCallback",
              "text": "CTRunDelegateGetAscentCallback"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "getDescent"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateGetDescentCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CTRunDelegateGetDescentCallback",
              "text": "CTRunDelegateGetDescentCallback"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "getWidth"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateGetWidthCallback",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CTRunDelegateGetWidthCallback",
              "text": "CTRunDelegateGetWidthCallback"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks": {
      "abstract": [
        {
          "text": "A structure holding pointers to callbacks implemented by the run delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunDelegateCallbacks"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunDelegateCallbacks"
        }
      ],
      "role": "symbol",
      "title": "CTRunDelegateCallbacks",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegatecallbacks"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/init(version:dealloc:getAscent:getDescent:getWidth:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dealloc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunDelegateDeallocateCallback",
          "text": "CTRunDelegateDeallocateCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "getAscent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunDelegateGetAscentCallback",
          "text": "CTRunDelegateGetAscentCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "getDescent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunDelegateGetDescentCallback",
          "text": "CTRunDelegateGetDescentCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "getWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunDelegateGetWidthCallback",
          "text": "CTRunDelegateGetWidthCallback"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/init(version:dealloc:getAscent:getDescent:getWidth:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(version:dealloc:getAscent:getDescent:getWidth:)",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegatecallbacks/init(version:dealloc:getascent:getdescent:getwidth:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateDeallocateCallback": {
      "abstract": [
        {
          "text": "Defines a pointer to a function that is invoked when a CTRunDelegate object is deallocated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunDelegateDeallocateCallback"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateDeallocateCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunDelegateDeallocateCallback"
        }
      ],
      "role": "symbol",
      "title": "CTRunDelegateDeallocateCallback",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegatedeallocatecallback"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateGetAscentCallback": {
      "abstract": [
        {
          "text": "Defines a pointer to a function that determines typographic ascent of glyphs in the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunDelegateGetAscentCallback"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateGetAscentCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunDelegateGetAscentCallback"
        }
      ],
      "role": "symbol",
      "title": "CTRunDelegateGetAscentCallback",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegategetascentcallback"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateGetDescentCallback": {
      "abstract": [
        {
          "text": "Defines a pointer to a function that determines typographic descent of glyphs in the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunDelegateGetDescentCallback"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateGetDescentCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunDelegateGetDescentCallback"
        }
      ],
      "role": "symbol",
      "title": "CTRunDelegateGetDescentCallback",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegategetdescentcallback"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateGetWidthCallback": {
      "abstract": [
        {
          "text": "Defines a pointer to a function that determines the typographic width of glyphs in the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunDelegateGetWidthCallback"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateGetWidthCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunDelegateGetWidthCallback"
        }
      ],
      "role": "symbol",
      "title": "CTRunDelegateGetWidthCallback",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegategetwidthcallback"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFIndex": {
      "abstract": [
        {
          "text": "Priority values used for kAXPriorityKey",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFIndex",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFIndex",
      "type": "topic",
      "url": "/documentation/corefoundation/cfindex"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks/title",
          "value": "CTRunDelegateCallbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateGetDescentCallback/title",
          "value": "CTRunDelegateGetDescentCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateGetDescentCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateGetDescentCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateGetDescentCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateGetDescentCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateGetAscentCallback/title",
          "value": "CTRunDelegateGetAscentCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateGetAscentCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateGetAscentCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateGetAscentCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateGetAscentCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateGetWidthCallback/title",
          "value": "CTRunDelegateGetWidthCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateGetWidthCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateGetWidthCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateGetWidthCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateGetWidthCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateDeallocateCallback/title",
          "value": "CTRunDelegateDeallocateCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateDeallocateCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateDeallocateCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateDeallocateCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateDeallocateCallback"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctrundelegatecallbacks/init(version:dealloc:getascent:getdescent:getwidth:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
