{
  "abstract": [
    {
      "text": "Initializes a new instance with an array of call stack addresses and a source code location.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext/init(callStackAddresses:location:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)XCTSourceCodeContext(im)initWithCallStackAddresses:location:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "callStackAddresses"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSNumber",
        "text": "NSNumber"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "location"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)XCTSourceCodeLocation",
        "text": "XCTSourceCodeLocation"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithCallStackAddresses:location:"
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(callStackAddresses:location:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "callStackAddresses"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "location"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeLocation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)XCTSourceCodeLocation",
              "text": "XCTSourceCodeLocation"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of call stack return addresses.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "callStackAddresses"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A representation of a location in source code.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "location"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The call stack addresses could be from ",
              "type": "text"
            },
            {
              "code": "NSThread.callStackReturnAddresses",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "NSException.callStackReturnAddresses",
              "type": "codeVoice"
            },
            {
              "text": ", or another source.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext": {
      "abstract": [
        {
          "text": "An object that contains call stack and source code location details to provide context for a point of execution in a test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTSourceCodeContext"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTSourceCodeContext"
        }
      ],
      "role": "symbol",
      "title": "XCTSourceCodeContext",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodecontext"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext/init()": {
      "abstract": [
        {
          "text": "Initializes a new instance with a call stack from the executing thread and no location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodecontext/init()"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext/init(callStack:location:)": {
      "abstract": [
        {
          "text": "Initializes a new instance with a provided call stack and source code location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "callStack"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTSourceCodeFrame",
          "text": "XCTSourceCodeFrame"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTSourceCodeLocation",
          "text": "XCTSourceCodeLocation"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext/init(callStack:location:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCallStack:location:"
        }
      ],
      "role": "symbol",
      "title": "init(callStack:location:)",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodecontext/init(callstack:location:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext/init(callStackAddresses:location:)": {
      "abstract": [
        {
          "text": "Initializes a new instance with an array of call stack addresses and a source code location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "callStackAddresses"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTSourceCodeLocation",
          "text": "XCTSourceCodeLocation"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext/init(callStackAddresses:location:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCallStackAddresses:location:"
        }
      ],
      "role": "symbol",
      "title": "init(callStackAddresses:location:)",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodecontext/init(callstackaddresses:location:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext/init(location:)": {
      "abstract": [
        {
          "text": "Initializes a new instance with a call stack from the executing thread and a provided source code location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTSourceCodeLocation",
          "text": "XCTSourceCodeLocation"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext/init(location:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocation:"
        }
      ],
      "role": "symbol",
      "title": "init(location:)",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodecontext/init(location:)"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeLocation": {
      "abstract": [
        {
          "text": "An object that contains a file URL and line number that represents a distinct location in source code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTSourceCodeLocation"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTSourceCodeLocation"
        }
      ],
      "role": "symbol",
      "title": "XCTSourceCodeLocation",
      "type": "topic",
      "url": "/documentation/xctest/xctsourcecodelocation"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext/init(callStack:location:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext/init(location:)",
        "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext/init()"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithCallStackAddresses:location:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCallStackAddresses:location:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest",
                "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Initializers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext/init(callStack:location:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext/init(location:)",
                "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeContext/init()"
              ],
              "title": "Initializers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithCallStackAddresses:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSNumber *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "callStackAddresses"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "location:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTSourceCodeLocation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)XCTSourceCodeLocation",
                    "text": "XCTSourceCodeLocation"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "location"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of call stack return addresses.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "callStackAddresses"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A representation of a location in source code.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "location"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeContext/title",
          "value": "XCTSourceCodeContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeContext~1init(callStack:location:)/title",
          "value": "initWithCallStack:location:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeContext~1init(callStack:location:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCallStack:location:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeContext~1init(location:)/title",
          "value": "initWithLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeContext~1init(location:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeLocation/title",
          "value": "XCTSourceCodeLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTSourceCodeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeContext~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeContext~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeContext~1init(callStackAddresses:location:)/title",
          "value": "initWithCallStackAddresses:location:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTSourceCodeContext~1init(callStackAddresses:location:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCallStackAddresses:location:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctsourcecodecontext/init(callstackaddresses:location:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctsourcecodecontext/init(callstackaddresses:location:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
