{
  "abstract": [
    {
      "text": "The secondary label of the table cell, if one exists.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use a content configuration to manage the cell’s text instead. Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/defaultContentConfiguration()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to get a default list content configuration, set your secondary text to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/secondaryText",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property of the configuration, and apply the configuration by setting it to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/contentConfiguration-9ktox",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property of the cell.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/detailTextLabel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UITableViewCell(py)detailTextLabel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "detailTextLabel"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UILabel",
        "text": "UILabel"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "detailTextLabel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.4",
        "introducedAt": "3.0",
        "message": "Use UIListContentConfiguration instead, this property will be deprecated in a future release.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.4",
        "introducedAt": "3.0",
        "message": "Use UIListContentConfiguration instead, this property will be deprecated in a future release.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "message": "Use UIListContentConfiguration instead, this property will be deprecated in a future release.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "message": "Use UIListContentConfiguration instead, this property will be deprecated in a future release.",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.4",
        "introducedAt": "1.0",
        "message": "Use UIListContentConfiguration instead, this property will be deprecated in a future release.",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "detailTextLabel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "detailTextLabel"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UILabel",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UILabel",
              "text": "UILabel"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/configuring-the-cells-for-your-table"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Holds the secondary (or detail) label of the cell. ",
              "type": "text"
            },
            {
              "code": "UITableViewCell",
              "type": "codeVoice"
            },
            {
              "text": " adds an appropriate label when you create the cell in a style that supports secondary labels. If the style doesn’t support detail labels, ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " returns. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/CellStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for descriptions of the main label in currently defined cell styles.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This property is mutually exclusive with a content configuration. Setting a non-",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " value for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/contentConfiguration-9ktox",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " resets this property to ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILabel": {
      "abstract": [
        {
          "text": "A view that displays one or more lines of informational text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UILabel"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILabel"
        }
      ],
      "role": "symbol",
      "title": "UILabel",
      "type": "topic",
      "url": "/documentation/uikit/uilabel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/secondaryText": {
      "abstract": [
        {
          "text": "The secondary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondaryText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/secondaryText",
      "kind": "symbol",
      "role": "symbol",
      "title": "secondaryText",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/secondarytext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell": {
      "abstract": [
        {
          "text": "The visual representation of a single row in a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableViewCell"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewCell"
        }
      ],
      "role": "symbol",
      "title": "UITableViewCell",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/CellStyle": {
      "abstract": [
        {
          "text": "An enumeration for the various styles of cells.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CellStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/CellStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CellStyle"
        }
      ],
      "role": "symbol",
      "title": "UITableViewCell.CellStyle",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/cellstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/accessoryAction": {
      "abstract": [
        {
          "text": "The selector defining the action message to invoke when users tap the accessory view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessoryAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/accessoryAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessoryAction",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/accessoryaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/contentConfiguration-9ktox": {
      "abstract": [
        {
          "text": "The current content configuration of the cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentConfiguration"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit22UIContentConfigurationP",
          "text": "UIContentConfiguration"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/contentConfiguration-9ktox",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/contentconfiguration-9ktox"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/defaultContentConfiguration()": {
      "abstract": [
        {
          "text": "Retrieves a default list content configuration for the cell’s style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultContentConfiguration"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/defaultContentConfiguration()",
      "kind": "symbol",
      "role": "symbol",
      "title": "defaultContentConfiguration()",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/defaultcontentconfiguration()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/detailTextLabel": {
      "abstract": [
        {
          "text": "The secondary label of the table cell, if one exists.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detailTextLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UILabel",
          "text": "UILabel"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/detailTextLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "detailTextLabel"
        }
      ],
      "role": "symbol",
      "title": "detailTextLabel",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/detailtextlabel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/editAction": {
      "abstract": [
        {
          "text": "The selector defining the action message to invoke when users tap the insert or delete button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "editAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/editAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "editAction",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/editaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/font": {
      "abstract": [
        {
          "text": "The font of the title.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "font"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/font",
      "kind": "symbol",
      "role": "symbol",
      "title": "font",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/font"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/hidesAccessoryWhenEditing": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the accessory view is hidden when the cell is being edited.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "hidesAccessoryWhenEditing"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/hidesAccessoryWhenEditing",
      "kind": "symbol",
      "role": "symbol",
      "title": "hidesAccessoryWhenEditing",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/hidesaccessorywhenediting"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/image": {
      "abstract": [
        {
          "text": "The image to use as content for the cell.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/image",
      "kind": "symbol",
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/image"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/imageView": {
      "abstract": [
        {
          "text": "The image view of the table cell.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImageView",
          "text": "UIImageView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/imageView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageView"
        }
      ],
      "role": "symbol",
      "title": "imageView",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/imageview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/init(style:reuseIdentifier:)": {
      "abstract": [
        {
          "text": "Initializes a table cell with a style and a reuse identifier and returns it to the caller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableViewCell",
          "text": "UITableViewCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITableViewCellStyle",
          "text": "CellStyle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reuseIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/init(style:reuseIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithStyle:reuseIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "init(style:reuseIdentifier:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/init(style:reuseidentifier:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/initWithFrame:reuseIdentifier:": {
      "abstract": [
        {
          "text": "Initializes and returns a table cell object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithFrame:reuseIdentifier:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/initWithFrame:reuseIdentifier:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFrame:reuseIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "initWithFrame:reuseIdentifier:",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/initwithframe:reuseidentifier:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/lineBreakMode": {
      "abstract": [
        {
          "text": "The mode for wrapping and truncating text in the cell.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "lineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/lineBreakMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "lineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/linebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/selectedImage": {
      "abstract": [
        {
          "text": "The image to use a cell content when the cell is selected.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "selectedImage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/selectedImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "selectedImage",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/selectedimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/selectedTextColor": {
      "abstract": [
        {
          "text": "The color of the title text when the cell is selected.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "selectedTextColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/selectedTextColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "selectedTextColor",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/selectedtextcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/target": {
      "abstract": [
        {
          "text": "The target object to receive action messages.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "target"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/target",
      "kind": "symbol",
      "role": "symbol",
      "title": "target",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/target"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/text": {
      "abstract": [
        {
          "text": "The text of the cell.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/text",
      "kind": "symbol",
      "role": "symbol",
      "title": "text",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/text"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/textAlignment": {
      "abstract": [
        {
          "text": "A constant that specifies the alignment of text in the cell.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "textAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/textAlignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "textAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/textalignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/textColor": {
      "abstract": [
        {
          "text": "The color of the title text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "textColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/textColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "textColor",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/textcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/textLabel": {
      "abstract": [
        {
          "text": "The label to use for the main textual content of the table cell.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UILabel",
          "text": "UILabel"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/textLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textLabel"
        }
      ],
      "role": "symbol",
      "title": "textLabel",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/textlabel"
    },
    "doc://com.apple.uikit/documentation/UIKit/configuring-the-cells-for-your-table": {
      "abstract": [
        {
          "text": "Specify the appearance and content of your table’s rows by defining one or more prototype cells in your storyboard.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/configuring-the-cells-for-your-table",
      "kind": "article",
      "role": "article",
      "title": "Configuring the cells for your table",
      "type": "topic",
      "url": "/documentation/uikit/configuring-the-cells-for-your-table"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/init(style:reuseIdentifier:)"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/textLabel",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/imageView"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.4",
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.4",
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.4",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "detailTextLabel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "detailTextLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/init(style:reuseIdentifier:)"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Deprecated",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/textLabel",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/imageView",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/initWithFrame:reuseIdentifier:",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/text",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/font",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/textAlignment",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/textColor",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/selectedTextColor",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/lineBreakMode",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/image",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/selectedImage",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/hidesAccessoryWhenEditing",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/target",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/editAction",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/accessoryAction"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UILabel",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UILabel",
                    "text": "UILabel"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "detailTextLabel"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use a content configuration to manage the cell’s text instead. Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/defaultContentConfiguration()",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to get a default list content configuration, set your secondary text to the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/secondaryText",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property of the configuration, and apply the configuration by setting it to the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/contentConfiguration-9ktox",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property of the cell.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1init(style:reuseIdentifier:)/title",
          "value": "initWithStyle:reuseIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1init(style:reuseIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithStyle:reuseIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILabel/title",
          "value": "UILabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UILabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILabel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1detailTextLabel/title",
          "value": "detailTextLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1detailTextLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "detailTextLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1CellStyle/title",
          "value": "UITableViewCellStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1CellStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewCellStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1CellStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewCellStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell/title",
          "value": "UITableViewCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1textLabel/title",
          "value": "textLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1textLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1imageView/title",
          "value": "imageView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1imageView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitableviewcell/detailtextlabel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitableviewcell/detailtextlabel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
