{
  "abstract": [
    {
      "text": "The editing style of the cell.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/editingStyle-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UITableViewCell(py)editingStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "editingStyle"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UITableViewCell",
        "text": "UITableViewCell"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UITableViewCellEditingStyle",
        "text": "EditingStyle"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "editingStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "editingStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "editingStyle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UITableViewCell",
              "text": "UITableViewCell"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/EditingStyle-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UITableViewCellEditingStyle",
              "text": "EditingStyle"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "One of the constants described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/EditingStyle-swift.enum",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is used as the value of this property; it specifies whether the cell is in an editable state and, if it is, whether it shows an insertion or deletion control. The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/EditingStyle-swift.enum/none",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (not editable). The delegate returns the value of this property for a particular cell in its implementation of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDelegate/tableView(_:editingStyleForRowAt:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell": {
      "abstract": [
        {
          "text": "The visual representation of a single row in a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableViewCell"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewCell"
        }
      ],
      "role": "symbol",
      "title": "UITableViewCell",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/EditingStyle-swift.enum": {
      "abstract": [
        {
          "text": "The editing control used by a cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EditingStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/EditingStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EditingStyle"
        }
      ],
      "role": "symbol",
      "title": "UITableViewCell.EditingStyle",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/editingstyle-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/EditingStyle-swift.enum/none": {
      "abstract": [
        {
          "text": "The cell has no editing control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/EditingStyle-swift.enum/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewCellEditingStyleNone"
        }
      ],
      "role": "symbol",
      "title": "UITableViewCell.EditingStyle.none",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/editingstyle-swift.enum/none"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/editingStyle-swift.property": {
      "abstract": [
        {
          "text": "The editing style of the cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "editingStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableViewCell",
          "text": "UITableViewCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITableViewCellEditingStyle",
          "text": "EditingStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/editingStyle-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "editingStyle"
        }
      ],
      "role": "symbol",
      "title": "editingStyle",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/editingstyle-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/isEditing": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the cell is in an editable state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEditing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/isEditing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "editing"
        }
      ],
      "role": "symbol",
      "title": "isEditing",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/isediting"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/setEditing(_:animated:)": {
      "abstract": [
        {
          "text": "Toggles the cell into and out of editing mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setEditing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/setEditing(_:animated:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setEditing:animated:"
        }
      ],
      "role": "symbol",
      "title": "setEditing(_:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/setediting(_:animated:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/showingDeleteConfirmation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the cell is currently showing the delete-confirmation button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showingDeleteConfirmation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/showingDeleteConfirmation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showingDeleteConfirmation"
        }
      ],
      "role": "symbol",
      "title": "showingDeleteConfirmation",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/showingdeleteconfirmation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/showsReorderControl": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the cell shows the reordering control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsReorderControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/showsReorderControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showsReorderControl"
        }
      ],
      "role": "symbol",
      "title": "showsReorderControl",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/showsreordercontrol"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDelegate/tableView(_:editingStyleForRowAt:)": {
      "abstract": [
        {
          "text": "Asks the delegate for the editing style of a row at a particular location in a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableView",
          "text": "UITableView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "editingStyleForRowAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableViewCell",
          "text": "UITableViewCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITableViewCellEditingStyle",
          "text": "EditingStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDelegate/tableView(_:editingStyleForRowAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tableView:editingStyleForRowAtIndexPath:"
        }
      ],
      "role": "symbol",
      "title": "tableView(_:editingStyleForRowAt:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdelegate/tableview(_:editingstyleforrowat:)"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Editing-the-cell",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/isEditing",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/setEditing(_:animated:)",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/EditingStyle-swift.enum",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/showingDeleteConfirmation",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/showsReorderControl"
      ],
      "title": "Editing the cell"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "editingStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "editingStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Editing-the-cell",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/isEditing",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/setEditing(_:animated:)",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/EditingStyle-swift.enum",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/showingDeleteConfirmation",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/showsReorderControl"
              ],
              "title": "Editing the cell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/EditingStyle-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@UITableViewCellEditingStyle",
                    "text": "UITableViewCellEditingStyle"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "editingStyle"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1showsReorderControl/title",
          "value": "showsReorderControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1showsReorderControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showsReorderControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1setEditing(_:animated:)/title",
          "value": "setEditing:animated:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1setEditing(_:animated:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setEditing:animated:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1isEditing/title",
          "value": "editing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1isEditing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "editing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1showingDeleteConfirmation/title",
          "value": "showingDeleteConfirmation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1showingDeleteConfirmation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showingDeleteConfirmation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell/title",
          "value": "UITableViewCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1EditingStyle-swift.enum/title",
          "value": "UITableViewCellEditingStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1EditingStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewCellEditingStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1EditingStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewCellEditingStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1editingStyle-swift.property/title",
          "value": "editingStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1editingStyle-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "editingStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1EditingStyle-swift.enum~1none/title",
          "value": "UITableViewCellEditingStyleNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1EditingStyle-swift.enum~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewCellEditingStyleNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDelegate~1tableView(_:editingStyleForRowAt:)/title",
          "value": "tableView:editingStyleForRowAtIndexPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDelegate~1tableView(_:editingStyleForRowAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tableView:editingStyleForRowAtIndexPath:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitableviewcell/editingstyle-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitableviewcell/editingstyle-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
