{
  "abstract": [
    {
      "text": "The selector defining the action message to invoke when users tap the insert or delete button.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Instead, use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDataSource/tableView(_:commit:forRowAt:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDelegate/tableView(_:accessoryButtonTappedForRowWith:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for handling taps on cells.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/editAction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UITableViewCell(py)editAction",
    "fragments": [
      {
        "kind": "identifier",
        "text": "editAction"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "editAction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "3.0",
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "3.0",
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "editAction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@SEL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SEL",
              "text": "SEL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "editAction"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the cell’s table is in editing mode, the cell displays a green insert control or a red delete control to the left of it. (The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/selectedBackgroundView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " constant applied to the cell via the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/editingStyle-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property determines which control is used.) Typically, the associated ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object sets the editing action for all cells; you can use this property to alter the editing action for individual cells. If the value of this property is ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": ", no action message is sent.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView": {
      "abstract": [
        {
          "text": "A view that presents data using rows in a single column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableView"
        }
      ],
      "role": "symbol",
      "title": "UITableView",
      "type": "topic",
      "url": "/documentation/uikit/uitableview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell": {
      "abstract": [
        {
          "text": "The visual representation of a single row in a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableViewCell"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewCell"
        }
      ],
      "role": "symbol",
      "title": "UITableViewCell",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/accessoryAction": {
      "abstract": [
        {
          "text": "The selector defining the action message to invoke when users tap the accessory view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessoryAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/accessoryAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessoryAction",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/accessoryaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/detailTextLabel": {
      "abstract": [
        {
          "text": "The secondary label of the table cell, if one exists.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detailTextLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UILabel",
          "text": "UILabel"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/detailTextLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "detailTextLabel"
        }
      ],
      "role": "symbol",
      "title": "detailTextLabel",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/detailtextlabel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/editAction": {
      "abstract": [
        {
          "text": "The selector defining the action message to invoke when users tap the insert or delete button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "editAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/editAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "editAction",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/editaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/editingStyle-swift.property": {
      "abstract": [
        {
          "text": "The editing style of the cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "editingStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableViewCell",
          "text": "UITableViewCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITableViewCellEditingStyle",
          "text": "EditingStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/editingStyle-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "editingStyle"
        }
      ],
      "role": "symbol",
      "title": "editingStyle",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/editingstyle-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/font": {
      "abstract": [
        {
          "text": "The font of the title.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "font"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/font",
      "kind": "symbol",
      "role": "symbol",
      "title": "font",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/font"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/hidesAccessoryWhenEditing": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the accessory view is hidden when the cell is being edited.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "hidesAccessoryWhenEditing"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/hidesAccessoryWhenEditing",
      "kind": "symbol",
      "role": "symbol",
      "title": "hidesAccessoryWhenEditing",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/hidesaccessorywhenediting"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/image": {
      "abstract": [
        {
          "text": "The image to use as content for the cell.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/image",
      "kind": "symbol",
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/image"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/imageView": {
      "abstract": [
        {
          "text": "The image view of the table cell.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImageView",
          "text": "UIImageView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/imageView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageView"
        }
      ],
      "role": "symbol",
      "title": "imageView",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/imageview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/initWithFrame:reuseIdentifier:": {
      "abstract": [
        {
          "text": "Initializes and returns a table cell object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithFrame:reuseIdentifier:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/initWithFrame:reuseIdentifier:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFrame:reuseIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "initWithFrame:reuseIdentifier:",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/initwithframe:reuseidentifier:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/lineBreakMode": {
      "abstract": [
        {
          "text": "The mode for wrapping and truncating text in the cell.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "lineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/lineBreakMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "lineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/linebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/selectedBackgroundView": {
      "abstract": [
        {
          "text": "The view to use as the background for a selected cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedBackgroundView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/selectedBackgroundView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedBackgroundView"
        }
      ],
      "role": "symbol",
      "title": "selectedBackgroundView",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/selectedbackgroundview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/selectedImage": {
      "abstract": [
        {
          "text": "The image to use a cell content when the cell is selected.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "selectedImage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/selectedImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "selectedImage",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/selectedimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/selectedTextColor": {
      "abstract": [
        {
          "text": "The color of the title text when the cell is selected.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "selectedTextColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/selectedTextColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "selectedTextColor",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/selectedtextcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/target": {
      "abstract": [
        {
          "text": "The target object to receive action messages.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "target"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/target",
      "kind": "symbol",
      "role": "symbol",
      "title": "target",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/target"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/text": {
      "abstract": [
        {
          "text": "The text of the cell.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/text",
      "kind": "symbol",
      "role": "symbol",
      "title": "text",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/text"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/textAlignment": {
      "abstract": [
        {
          "text": "A constant that specifies the alignment of text in the cell.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "textAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/textAlignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "textAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/textalignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/textColor": {
      "abstract": [
        {
          "text": "The color of the title text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "textColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/textColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "textColor",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/textcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/textLabel": {
      "abstract": [
        {
          "text": "The label to use for the main textual content of the table cell.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UILabel",
          "text": "UILabel"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/textLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textLabel"
        }
      ],
      "role": "symbol",
      "title": "textLabel",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/textlabel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDataSource/tableView(_:commit:forRowAt:)": {
      "abstract": [
        {
          "text": "Asks the data source to commit the insertion or deletion of a specified row.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableView",
          "text": "UITableView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "commit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableViewCell",
          "text": "UITableViewCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITableViewCellEditingStyle",
          "text": "EditingStyle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forRowAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDataSource/tableView(_:commit:forRowAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tableView:commitEditingStyle:forRowAtIndexPath:"
        }
      ],
      "role": "symbol",
      "title": "tableView(_:commit:forRowAt:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdatasource/tableview(_:commit:forrowat:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDelegate/tableView(_:accessoryButtonTappedForRowWith:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user tapped the detail button for the specified row.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableView",
          "text": "UITableView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "accessoryButtonTappedForRowWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDelegate/tableView(_:accessoryButtonTappedForRowWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tableView:accessoryButtonTappedForRowWithIndexPath:"
        }
      ],
      "role": "symbol",
      "title": "tableView(_:accessoryButtonTappedForRowWith:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdelegate/tableview(_:accessorybuttontappedforrowwith:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@SEL": {
      "abstract": [
        {
          "text": "Defines an opaque type that represents a method selector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@SEL",
      "kind": "symbol",
      "role": "symbol",
      "title": "SEL",
      "type": "topic",
      "url": "/documentation/objectivec/sel"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/textLabel",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/detailTextLabel",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/imageView",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/initWithFrame:reuseIdentifier:",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/text",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/font",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/textAlignment",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/textColor",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/selectedTextColor",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/lineBreakMode",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/image",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/selectedImage",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/hidesAccessoryWhenEditing",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/target",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/accessoryAction"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1selectedBackgroundView/title",
          "value": "selectedBackgroundView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1selectedBackgroundView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedBackgroundView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1detailTextLabel/title",
          "value": "detailTextLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1detailTextLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "detailTextLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/title",
          "value": "UITableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1imageView/title",
          "value": "imageView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1imageView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDataSource~1tableView(_:commit:forRowAt:)/title",
          "value": "tableView:commitEditingStyle:forRowAtIndexPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDataSource~1tableView(_:commit:forRowAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tableView:commitEditingStyle:forRowAtIndexPath:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell/title",
          "value": "UITableViewCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDelegate~1tableView(_:accessoryButtonTappedForRowWith:)/title",
          "value": "tableView:accessoryButtonTappedForRowWithIndexPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDelegate~1tableView(_:accessoryButtonTappedForRowWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tableView:accessoryButtonTappedForRowWithIndexPath:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1textLabel/title",
          "value": "textLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1textLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1editingStyle-swift.property/title",
          "value": "editingStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1editingStyle-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "editingStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitableviewcell/editaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
