{"variants":[{"paths":["/documentation/uikit/uitableviewcell/updateconfigurationusingstate:"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITableViewCell/configurationUpdateHandler-746ya"],"generated":true,"anchor":"Table-view-cells","title":"Table view cells"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateConfigurationUsingState:"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-c.class","kind":"typeIdentifier","text":"UICellConfigurationState","preciseIdentifier":"c:objc(cs)UICellConfigurationState"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"state"},{"kind":"text","text":";"}]}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"Discussion"},{"inlineContent":[{"type":"text","text":"Avoid calling this method directly. Instead, use "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UITableViewCell/setNeedsUpdateConfiguration()"},{"type":"text","text":" to request an update."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Override this method in a subclass to update the cell’s configuration using the provided state."}],"type":"paragraph"},{"inlineContent":[{"text":"In iOS 18 and later, UIKit supports automatic trait tracking inside this method for traits from this cell’s ","type":"text"},{"code":"traitCollection","type":"codeVoice"},{"text":". For more information, see ","type":"text"},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"Updates the cell’s configuration using the current state."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITableViewCell"]]},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UITableViewCell/updateConfigurationUsingState:","interfaceLanguage":"occ"},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"updateConfigurationUsingState:"}],"platforms":[{"unavailable":false,"beta":false,"introducedAt":"14.0","name":"iOS","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"14.0","name":"iPadOS","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"14.0","name":"tvOS","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"1.0","name":"visionOS","deprecated":false}],"externalID":"c:objc(cs)UITableViewCell(im)updateConfigurationUsingState:","modules":[{"name":"UIKit"}],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateConfigurationUsingState:"}],"title":"updateConfigurationUsingState:"},"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-c.class":{"abstract":[{"text":"An object that encapsulates a cell’s state.","type":"text"}],"fragments":[{"kind":"identifier","text":"UICellConfigurationState"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-c.class","role":"symbol","type":"topic","title":"UICellConfigurationState","kind":"symbol","url":"/documentation/uikit/uicellconfigurationstate-c.class"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking":{"kind":"article","abstract":[{"text":"Reduce the need to manually register for trait changes when you use traits within a method or closure that supports automatic trait tracking.","type":"text"}],"url":"/documentation/uikit/automatic-trait-tracking","identifier":"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking","title":"Automatic trait tracking","role":"collectionGroup","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITableViewCell":{"navigatorTitle":[{"text":"UITableViewCell","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITableViewCell","kind":"identifier"}],"url":"/documentation/uikit/uitableviewcell","abstract":[{"type":"text","text":"The visual representation of a single row in a table view."}],"title":"UITableViewCell","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITableViewCell","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITableViewCell/setNeedsUpdateConfiguration()":{"type":"topic","abstract":[{"text":"Informs the cell to update its configuration for its current state.","type":"text"}],"url":"/documentation/uikit/uitableviewcell/setneedsupdateconfiguration()","identifier":"doc://com.apple.uikit/documentation/UIKit/UITableViewCell/setNeedsUpdateConfiguration()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setNeedsUpdateConfiguration","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"setNeedsUpdateConfiguration","kind":"identifier"}],"title":"setNeedsUpdateConfiguration()","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITableViewCell/configurationUpdateHandler-746ya":{"kind":"symbol","abstract":[{"type":"text","text":"A block for handling updates to the cell’s configuration using the current state."}],"url":"/documentation/uikit/uitableviewcell/configurationupdatehandler-746ya","identifier":"doc://com.apple.uikit/documentation/UIKit/UITableViewCell/configurationUpdateHandler-746ya","title":"configurationUpdateHandler","role":"symbol","type":"topic","fragments":[{"text":"configurationUpdateHandler","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UITableViewCell/updateConfigurationUsingState:":{"kind":"symbol","title":"updateConfigurationUsingState:","abstract":[{"type":"text","text":"Updates the cell’s configuration using the current state."}],"url":"/documentation/uikit/uitableviewcell/updateconfigurationusingstate:","identifier":"doc://com.apple.uikit/documentation/UIKit/UITableViewCell/updateConfigurationUsingState:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateConfigurationUsingState:"}],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"updateConfigurationUsingState:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell/title","value":"UITableViewCell"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell/fragments","value":[{"text":"UITableViewCell","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell/navigatorTitle","value":[{"kind":"identifier","text":"UITableViewCell"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1setNeedsUpdateConfiguration()/title","value":"setNeedsUpdateConfiguration"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1setNeedsUpdateConfiguration()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setNeedsUpdateConfiguration"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}