{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"text":"(_bridgedUpdateConfigurationUsingState:) ","kind":"text"},{"text":"@preconcurrency","kind":"attribute"},{"text":" ","kind":"text"},{"text":"dynamic","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"using","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"state","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UICellConfigurationState","preciseIdentifier":"s:5UIKit24UICellConfigurationStateV","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-swift.struct"},{"text":")","kind":"text"}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"inlineContent":[{"text":"Avoid calling this method directly. Instead, use ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITableViewCell/setNeedsUpdateConfiguration()","isActive":true,"type":"reference"},{"text":" to request an update.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Override this method in a subclass to update the cell’s configuration using the provided state."}],"type":"paragraph"},{"inlineContent":[{"text":"In iOS 18 and later, UIKit supports automatic trait tracking inside this method for traits from this cell’s ","type":"text"},{"code":"traitCollection","type":"codeVoice"},{"text":". For more information, see ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}],"metadata":{"platforms":[{"deprecated":false,"introducedAt":"14.0","unavailable":false,"beta":false,"name":"iOS"},{"deprecated":false,"introducedAt":"14.0","unavailable":false,"beta":false,"name":"iPadOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"},{"deprecated":false,"introducedAt":"14.0","unavailable":false,"beta":false,"name":"tvOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"visionOS"}],"modules":[{"name":"UIKit"}],"title":"updateConfiguration(using:)","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateConfiguration"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5UIKit24UICellConfigurationStateV","kind":"typeIdentifier","text":"UICellConfigurationState"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","extendedModule":"UIKit","externalID":"c:@CM@UIKit@@objc(cs)UITableViewCell(im)_bridgedUpdateConfigurationUsingState:"},"variants":[{"paths":["/documentation/uikit/uitableviewcell/updateconfiguration(using:)"],"traits":[{"interfaceLanguage":"swift"}]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITableViewCell/configurationUpdateHandler-974"],"generated":true,"anchor":"Table-view-cells","title":"Table view cells"}],"sections":[],"abstract":[{"text":"Updates the cell’s configuration using the current state.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITableViewCell"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UITableViewCell/updateConfiguration(using:)"},"references":{"doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-swift.struct":{"role":"symbol","url":"/documentation/uikit/uicellconfigurationstate-swift.struct","abstract":[{"text":"A structure that encapsulates a cell’s state.","type":"text"}],"type":"topic","title":"UICellConfigurationState","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICellConfigurationState","kind":"identifier"}],"navigatorTitle":[{"text":"UICellConfigurationState","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-swift.struct","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITableViewCell":{"navigatorTitle":[{"text":"UITableViewCell","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITableViewCell","kind":"identifier"}],"url":"/documentation/uikit/uitableviewcell","abstract":[{"type":"text","text":"The visual representation of a single row in a table view."}],"title":"UITableViewCell","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITableViewCell","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITableViewCell/configurationUpdateHandler-974":{"url":"/documentation/uikit/uitableviewcell/configurationupdatehandler-974","identifier":"doc://com.apple.uikit/documentation/UIKit/UITableViewCell/configurationUpdateHandler-974","role":"symbol","kind":"symbol","type":"topic","title":"configurationUpdateHandler","abstract":[{"text":"A block for handling updates to the cell’s configuration using the current state.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configurationUpdateHandler","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableViewCell","kind":"typeIdentifier","text":"UITableViewCell"},{"kind":"text","text":"."},{"preciseIdentifier":"s:So15UITableViewCellC5UIKitE26ConfigurationUpdateHandlera","kind":"typeIdentifier","text":"ConfigurationUpdateHandler"},{"kind":"text","text":"?"}]},"doc://com.apple.uikit/documentation/UIKit/UITableViewCell/setNeedsUpdateConfiguration()":{"type":"topic","abstract":[{"text":"Informs the cell to update its configuration for its current state.","type":"text"}],"url":"/documentation/uikit/uitableviewcell/setneedsupdateconfiguration()","identifier":"doc://com.apple.uikit/documentation/UIKit/UITableViewCell/setNeedsUpdateConfiguration()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setNeedsUpdateConfiguration","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"setNeedsUpdateConfiguration","kind":"identifier"}],"title":"setNeedsUpdateConfiguration()","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITableViewCell/updateConfiguration(using:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"using","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5UIKit24UICellConfigurationStateV","kind":"typeIdentifier","text":"UICellConfigurationState"},{"kind":"text","text":")"}],"type":"topic","title":"updateConfiguration(using:)","url":"/documentation/uikit/uitableviewcell/updateconfiguration(using:)","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITableViewCell/updateConfiguration(using:)","abstract":[{"type":"text","text":"Updates the cell’s configuration using the current state."}]},"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking":{"kind":"article","abstract":[{"text":"Reduce the need to manually register for trait changes when you use traits within a method or closure that supports automatic trait tracking.","type":"text"}],"url":"/documentation/uikit/automatic-trait-tracking","identifier":"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking","title":"Automatic trait tracking","role":"collectionGroup","type":"topic"}},"variantOverrides":[{"patch":[{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell/title","op":"replace","value":"UITableViewCell"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell/fragments","op":"replace","value":[{"text":"UITableViewCell","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell/navigatorTitle","op":"replace","value":[{"text":"UITableViewCell","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1setNeedsUpdateConfiguration()/title","op":"replace","value":"setNeedsUpdateConfiguration"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewCell~1setNeedsUpdateConfiguration()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setNeedsUpdateConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}