{
  "abstract": [
    {
      "text": "Values that describe where and how the framework extends segments of a selection.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@NSTextLayoutManagerSegmentOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SegmentOptions"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SegmentOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSTextLayoutManager.SegmentOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SegmentOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager": {
      "abstract": [
        {
          "text": "The primary class that you use to manage text layout and presentation for custom text displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextLayoutManager"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutManager"
        }
      ],
      "role": "symbol",
      "title": "NSTextLayoutManager",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanager"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions": {
      "abstract": [
        {
          "text": "Values that describe where and how the framework extends segments of a selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SegmentOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SegmentOptions"
        }
      ],
      "role": "symbol",
      "title": "NSTextLayoutManager.SegmentOptions",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanager/segmentoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/headSegmentExtended": {
      "abstract": [
        {
          "text": "Returns the value that causes the framework to extend the segment to the tail edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headSegmentExtended"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextLayoutManager",
          "text": "NSTextLayoutManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextLayoutManagerSegmentOptions",
          "text": "SegmentOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/headSegmentExtended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutManagerSegmentOptionsHeadSegmentExtended"
        }
      ],
      "role": "symbol",
      "title": "headSegmentExtended",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanager/segmentoptions/headsegmentextended"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/init(rawValue:)": {
      "abstract": [
        {
          "text": "Cceates a new segment option using the value you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanager/segmentoptions/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/middleFragmentsExcluded": {
      "abstract": [
        {
          "text": "Returns the value that causes the framework to enumerate segments in only the first and last line fragments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "middleFragmentsExcluded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextLayoutManager",
          "text": "NSTextLayoutManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextLayoutManagerSegmentOptions",
          "text": "SegmentOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/middleFragmentsExcluded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutManagerSegmentOptionsMiddleFragmentsExcluded"
        }
      ],
      "role": "symbol",
      "title": "middleFragmentsExcluded",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanager/segmentoptions/middlefragmentsexcluded"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/rangeNotRequired": {
      "abstract": [
        {
          "text": "Returns the value that causes the framework enumerate text segment rectangles, but avoids preparing a range object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rangeNotRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextLayoutManager",
          "text": "NSTextLayoutManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextLayoutManagerSegmentOptions",
          "text": "SegmentOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/rangeNotRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutManagerSegmentOptionsRangeNotRequired"
        }
      ],
      "role": "symbol",
      "title": "rangeNotRequired",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanager/segmentoptions/rangenotrequired"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/tailSegmentExtended": {
      "abstract": [
        {
          "text": "Returns the value that causes the framework to extend the segment to the tail edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tailSegmentExtended"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextLayoutManager",
          "text": "NSTextLayoutManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextLayoutManagerSegmentOptions",
          "text": "SegmentOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/tailSegmentExtended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutManagerSegmentOptionsTailSegmentExtended"
        }
      ],
      "role": "symbol",
      "title": "tailSegmentExtended",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanager/segmentoptions/tailsegmentextended"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/upstreamAffinity": {
      "abstract": [
        {
          "text": "Returns the value that causes the framework to the place the segment based on the upstream affinity for an empty range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "upstreamAffinity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextLayoutManager",
          "text": "NSTextLayoutManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextLayoutManagerSegmentOptions",
          "text": "SegmentOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/upstreamAffinity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutManagerSegmentOptionsUpstreamAffinity"
        }
      ],
      "role": "symbol",
      "title": "upstreamAffinity",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanager/segmentoptions/upstreamaffinity"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentType": {
      "abstract": [
        {
          "text": "Values that describe the rendering of selection boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SegmentType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SegmentType"
        }
      ],
      "role": "symbol",
      "title": "NSTextLayoutManager.SegmentType",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanager/segmenttype"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/ensureLayout(for:)-3duae": {
      "abstract": [
        {
          "text": "Performs the layout for specified text range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ensureLayout"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextRange",
          "text": "NSTextRange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/ensureLayout(for:)-3duae",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ensureLayoutForRange:"
        }
      ],
      "role": "symbol",
      "title": "ensureLayout(for:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanager/ensurelayout(for:)-3duae"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/ensureLayout(for:)-6ptsj": {
      "abstract": [
        {
          "text": "Performs the layout for filling the bounds you specify inside the last text container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ensureLayout"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/ensureLayout(for:)-6ptsj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ensureLayoutForBounds:"
        }
      ],
      "role": "symbol",
      "title": "ensureLayout(for:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanager/ensurelayout(for:)-6ptsj"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/enumerateTextLayoutFragments(from:options:using:)": {
      "abstract": [
        {
          "text": "Enumerates the text layout fragments starting at the specified location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enumerateTextLayoutFragments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextLayoutFragment",
          "text": "NSTextLayoutFragment"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextLayoutFragmentEnumerationOptions",
          "text": "EnumerationOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextLayoutFragment",
          "text": "NSTextLayoutFragment"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/enumerateTextLayoutFragments(from:options:using:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateTextLayoutFragmentsFromLocation:options:usingBlock:"
        }
      ],
      "role": "symbol",
      "title": "enumerateTextLayoutFragments(from:options:using:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanager/enumeratetextlayoutfragments(from:options:using:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/invalidateLayout(for:)": {
      "abstract": [
        {
          "text": "Invalidates the layout information for specified text range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidateLayout"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextRange",
          "text": "NSTextRange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/invalidateLayout(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidateLayoutForRange:"
        }
      ],
      "role": "symbol",
      "title": "invalidateLayout(for:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanager/invalidatelayout(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/textLayoutFragment(for:)-4dhrx": {
      "abstract": [
        {
          "text": "Returns the text layout fragment at the position you specify in the text container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textLayoutFragment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextLayoutFragment",
          "text": "NSTextLayoutFragment"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/textLayoutFragment(for:)-4dhrx",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textLayoutFragmentForPosition:"
        }
      ],
      "role": "symbol",
      "title": "textLayoutFragment(for:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanager/textlayoutfragment(for:)-4dhrx"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/textLayoutFragment(for:)-68dez": {
      "abstract": [
        {
          "text": "Returns the text layout fragment from the document at the specified location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textLayoutFragment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextLayoutFragment",
          "text": "NSTextLayoutFragment"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/textLayoutFragment(for:)-68dez",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textLayoutFragmentForLocation:"
        }
      ],
      "role": "symbol",
      "title": "textLayoutFragment(for:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanager/textlayoutfragment(for:)-68dez"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/textViewportLayoutController": {
      "abstract": [
        {
          "text": "Returns text viewport layout controller associated with the layout manager’s text container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textViewportLayoutController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextViewportLayoutController",
          "text": "NSTextViewportLayoutController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/textViewportLayoutController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textViewportLayoutController"
        }
      ],
      "role": "symbol",
      "title": "textViewportLayoutController",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanager/textviewportlayoutcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManagerSegmentOptions/NSTextLayoutManagerSegmentOptionsNone": {
      "abstract": [
        {
          "text": "The value that represents the empty options set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutManagerSegmentOptionsNone"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManagerSegmentOptions/NSTextLayoutManagerSegmentOptionsNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutManagerSegmentOptionsNone",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanagersegmentoptions/nstextlayoutmanagersegmentoptionsnone"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Causing-layout-generation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/textViewportLayoutController",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/invalidateLayout(for:)",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/textLayoutFragment(for:)-68dez",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/textLayoutFragment(for:)-4dhrx",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/ensureLayout(for:)-6ptsj",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/ensureLayout(for:)-3duae",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/enumerateTextLayoutFragments(from:options:using:)",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentType"
      ],
      "title": "Causing layout generation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-segment-options",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/init(rawValue:)"
      ],
      "title": "Creating segment options"
    },
    {
      "anchor": "Getting-segment-options",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/headSegmentExtended",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/middleFragmentsExcluded",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/rangeNotRequired",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/tailSegmentExtended",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/upstreamAffinity"
      ],
      "title": "Getting segment options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextLayoutManagerSegmentOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManagerSegmentOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManagerSegmentOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-segment-options",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/headSegmentExtended",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/middleFragmentsExcluded",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/rangeNotRequired",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/tailSegmentExtended",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentOptions/upstreamAffinity"
              ],
              "title": "Getting segment options"
            },
            {
              "anchor": "Constants-that-describe-segment-options",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManagerSegmentOptions/NSTextLayoutManagerSegmentOptionsNone"
              ],
              "title": "Constants that describe segment options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Causing-layout-generation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/textViewportLayoutController",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/invalidateLayout(for:)",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/textLayoutFragment(for:)-68dez",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/textLayoutFragment(for:)-4dhrx",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/ensureLayout(for:)-6ptsj",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/ensureLayout(for:)-3duae",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/enumerateTextLayoutFragments(from:options:using:)",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager/SegmentType"
              ],
              "title": "Causing layout generation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTextLayoutManagerSegmentOptions"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1SegmentOptions~1middleFragmentsExcluded/title",
          "value": "NSTextLayoutManagerSegmentOptionsMiddleFragmentsExcluded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1SegmentOptions~1middleFragmentsExcluded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManagerSegmentOptionsMiddleFragmentsExcluded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1enumerateTextLayoutFragments(from:options:using:)/title",
          "value": "enumerateTextLayoutFragmentsFromLocation:options:usingBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1enumerateTextLayoutFragments(from:options:using:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enumerateTextLayoutFragmentsFromLocation:options:usingBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1ensureLayout(for:)-6ptsj/title",
          "value": "ensureLayoutForBounds:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1ensureLayout(for:)-6ptsj/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "ensureLayoutForBounds:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1SegmentOptions/title",
          "value": "NSTextLayoutManagerSegmentOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1SegmentOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManagerSegmentOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1SegmentOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManagerSegmentOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1SegmentOptions~1headSegmentExtended/title",
          "value": "NSTextLayoutManagerSegmentOptionsHeadSegmentExtended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1SegmentOptions~1headSegmentExtended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManagerSegmentOptionsHeadSegmentExtended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1textLayoutFragment(for:)-68dez/title",
          "value": "textLayoutFragmentForLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1textLayoutFragment(for:)-68dez/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textLayoutFragmentForLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1invalidateLayout(for:)/title",
          "value": "invalidateLayoutForRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1invalidateLayout(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "invalidateLayoutForRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1SegmentOptions~1upstreamAffinity/title",
          "value": "NSTextLayoutManagerSegmentOptionsUpstreamAffinity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1SegmentOptions~1upstreamAffinity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManagerSegmentOptionsUpstreamAffinity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager/title",
          "value": "NSTextLayoutManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1SegmentOptions~1tailSegmentExtended/title",
          "value": "NSTextLayoutManagerSegmentOptionsTailSegmentExtended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1SegmentOptions~1tailSegmentExtended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManagerSegmentOptionsTailSegmentExtended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1textLayoutFragment(for:)-4dhrx/title",
          "value": "textLayoutFragmentForPosition:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1textLayoutFragment(for:)-4dhrx/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textLayoutFragmentForPosition:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1ensureLayout(for:)-3duae/title",
          "value": "ensureLayoutForRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1ensureLayout(for:)-3duae/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "ensureLayoutForRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1SegmentOptions~1rangeNotRequired/title",
          "value": "NSTextLayoutManagerSegmentOptionsRangeNotRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1SegmentOptions~1rangeNotRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManagerSegmentOptionsRangeNotRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1SegmentType/title",
          "value": "NSTextLayoutManagerSegmentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1SegmentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManagerSegmentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1SegmentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManagerSegmentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1textViewportLayoutController/title",
          "value": "textViewportLayoutController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager~1textViewportLayoutController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textViewportLayoutController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nstextlayoutmanager/segmentoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nstextlayoutmanager/segmentoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
