{
  "abstract": [
    {
      "text": "Returns a projective-transformation structure that defines the mapping between a source quadrilateral and a destination quadrilateral.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/init(source:destination:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Accelerate",
    "externalID": "s:So27vImage_PerpsectiveTransformV10AccelerateE6source11destinationABSgSo7CGPointV_A3Ht_AH_A3Httcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "?("
      },
      {
        "kind": "externalParam",
        "text": "source"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@vImage_PerpsectiveTransform",
        "text": "vImage_PerpsectiveTransform"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So27vImage_PerpsectiveTransformV10AccelerateE19QuadrilateralPointsa",
        "text": "QuadrilateralPoints"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "destination"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@vImage_PerpsectiveTransform",
        "text": "vImage_PerpsectiveTransform"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So27vImage_PerpsectiveTransformV10AccelerateE19QuadrilateralPointsa",
        "text": "QuadrilateralPoints"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(source:destination:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "?("
            },
            {
              "kind": "externalParam",
              "text": "source"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@vImage_PerpsectiveTransform",
              "text": "vImage_PerpsectiveTransform"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/QuadrilateralPoints",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So27vImage_PerpsectiveTransformV10AccelerateE19QuadrilateralPointsa",
              "text": "QuadrilateralPoints"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "destination"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@vImage_PerpsectiveTransform",
              "text": "vImage_PerpsectiveTransform"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/QuadrilateralPoints",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So27vImage_PerpsectiveTransformV10AccelerateE19QuadrilateralPointsa",
              "text": "QuadrilateralPoints"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The four source points.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "source"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The four destination points.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "destination"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform": {
      "abstract": [
        {
          "text": "A projective-transformation matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_PerpsectiveTransform"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_PerpsectiveTransform"
        }
      ],
      "role": "symbol",
      "title": "vImage_PerpsectiveTransform",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/QuadrilateralPoints": {
      "abstract": [
        {
          "text": "A tuple of four points that define a quadrilateral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QuadrilateralPoints"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/QuadrilateralPoints",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QuadrilateralPoints"
        }
      ],
      "role": "symbol",
      "title": "vImage_PerpsectiveTransform.QuadrilateralPoints",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform/quadrilateralpoints"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/init()": {
      "abstract": [
        {
          "text": "Creates a projective-transformation structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform/init()"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/init(a:b:c:d:tx:ty:vx:vy:v:)": {
      "abstract": [
        {
          "text": "Creates a projective-transformation structure from the specified single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "a"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "b"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "c"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "d"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "tx"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "vx"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "vy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "v"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/init(a:b:c:d:tx:ty:vx:vy:v:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(a:b:c:d:tx:ty:vx:vy:v:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform/init(a:b:c:d:tx:ty:vx:vy:v:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/init(source:destination:)": {
      "abstract": [
        {
          "text": "Returns a projective-transformation structure that defines the mapping between a source quadrilateral and a destination quadrilateral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "source"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_PerpsectiveTransform",
          "text": "vImage_PerpsectiveTransform"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So27vImage_PerpsectiveTransformV10AccelerateE19QuadrilateralPointsa",
          "text": "QuadrilateralPoints"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "destination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_PerpsectiveTransform",
          "text": "vImage_PerpsectiveTransform"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So27vImage_PerpsectiveTransformV10AccelerateE19QuadrilateralPointsa",
          "text": "QuadrilateralPoints"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/init(source:destination:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(source:destination:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform/init(source:destination:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-projective-transformation-structure",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/init()",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/init(a:b:c:d:tx:ty:vx:vy:v:)"
      ],
      "title": "Creating a projective-transformation structure"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform/title",
          "value": "vImage_PerpsectiveTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_PerpsectiveTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_PerpsectiveTransform"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vimage_perpsectivetransform/init(source:destination:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
