{
  "abstract": [
    {
      "text": "The user has partially played the media item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPlayStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPlayStatus/partiallyPlayed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ITLibMediaItemPlayStatus@ITLibMediaItemPlayStatusPartiallyPlayed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "partiallyPlayed"
      }
    ],
    "modules": [
      {
        "name": "iTunes Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ITLibMediaItemPlayStatusPartiallyPlayed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ITLibMediaItemPlayStatus.partiallyPlayed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "partiallyPlayed"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary": {
      "abstract": [
        {
          "text": "Retrieve the properties of the media in the user’s iTunes library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "iTunes Library",
      "type": "topic",
      "url": "/documentation/ituneslibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPlayStatus": {
      "abstract": [
        {
          "text": "These constants specify the play status of the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPlayStatus"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPlayStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPlayStatus"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemPlayStatus",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemplaystatus"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPlayStatus/none": {
      "abstract": [
        {
          "text": "The user has played the media item or iTunes doesn’t track the play status for this kind of media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPlayStatus/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPlayStatusNone"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemPlayStatus.none",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemplaystatus/none"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPlayStatus/partiallyPlayed": {
      "abstract": [
        {
          "text": "The user has partially played the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "partiallyPlayed"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPlayStatus/partiallyPlayed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPlayStatusPartiallyPlayed"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemPlayStatus.partiallyPlayed",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemplaystatus/partiallyplayed"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPlayStatus/unplayed": {
      "abstract": [
        {
          "text": "The user hasn’t played the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unplayed"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPlayStatus/unplayed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemPlayStatusUnplayed"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemPlayStatus.unplayed",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemplaystatus/unplayed"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Media-Item-Play-Statuses",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPlayStatus/none",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPlayStatus/unplayed"
      ],
      "title": "Media Item Play Statuses"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ITLibMediaItemPlayStatusPartiallyPlayed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPlayStatusPartiallyPlayed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPlayStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Media-Item-Play-Statuses",
              "generated": true,
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPlayStatus/none",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemPlayStatus/unplayed"
              ],
              "title": "Media Item Play Statuses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ITLibMediaItemPlayStatusPartiallyPlayed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPlayStatus~1unplayed/title",
          "value": "ITLibMediaItemPlayStatusUnplayed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPlayStatus~1unplayed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPlayStatusUnplayed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPlayStatus~1none/title",
          "value": "ITLibMediaItemPlayStatusNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPlayStatus~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPlayStatusNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPlayStatus/title",
          "value": "ITLibMediaItemPlayStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPlayStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPlayStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPlayStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPlayStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPlayStatus~1partiallyPlayed/title",
          "value": "ITLibMediaItemPlayStatusPartiallyPlayed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemPlayStatus~1partiallyPlayed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemPlayStatusPartiallyPlayed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/ituneslibrary/itlibmediaitemplaystatus/partiallyplayed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/ituneslibrary/itlibmediaitemplaystatus/partiallyplayed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
