{
  "abstract": [
    {
      "text": "The framework couldn’t find the specified placemark.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKError/placemarkNotFound"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11MKErrorCodeLeV17placemarkNotFoundSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "placemarkNotFound"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC11MKErrorCodeLeV",
        "text": "MKError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MKErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "placemarkNotFound"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "placemarkNotFound"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC11MKErrorCodeLeV",
              "text": "MKError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MKErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKError": {
      "abstract": [
        {
          "text": "Error constants for the MapKit framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKError"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKError"
        }
      ],
      "role": "symbol",
      "title": "MKError",
      "type": "topic",
      "url": "/documentation/mapkit/mkerror"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKError/Code": {
      "abstract": [
        {
          "text": "Error constants for the MapKit framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MKError.Code",
      "type": "topic",
      "url": "/documentation/mapkit/mkerror/code"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKError/decodingFailed": {
      "abstract": [
        {
          "text": "GeoJSON decoding failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decodingFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MKErrorCodeLeV",
          "text": "MKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKError/decodingFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "decodingFailed",
      "type": "topic",
      "url": "/documentation/mapkit/mkerror/decodingfailed"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKError/directionsNotFound": {
      "abstract": [
        {
          "text": "Directions to the specified location aren’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directionsNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MKErrorCodeLeV",
          "text": "MKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKError/directionsNotFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "directionsNotFound",
      "type": "topic",
      "url": "/documentation/mapkit/mkerror/directionsnotfound"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKError/loadingThrottled": {
      "abstract": [
        {
          "text": "The data didn’t load because data throttling is in effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadingThrottled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MKErrorCodeLeV",
          "text": "MKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKError/loadingThrottled",
      "kind": "symbol",
      "role": "symbol",
      "title": "loadingThrottled",
      "type": "topic",
      "url": "/documentation/mapkit/mkerror/loadingthrottled"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKError/placemarkNotFound": {
      "abstract": [
        {
          "text": "The framework couldn’t find the specified placemark.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "placemarkNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MKErrorCodeLeV",
          "text": "MKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKError/placemarkNotFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "placemarkNotFound",
      "type": "topic",
      "url": "/documentation/mapkit/mkerror/placemarknotfound"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKError/serverFailure": {
      "abstract": [
        {
          "text": "The map server was unable to return the desired information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MKErrorCodeLeV",
          "text": "MKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKError/serverFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "serverFailure",
      "type": "topic",
      "url": "/documentation/mapkit/mkerror/serverfailure"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKError/unknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MKErrorCodeLeV",
          "text": "MKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKError/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/mapkit/mkerror/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKError/decodingFailed",
        "doc://com.apple.mapkit/documentation/MapKit/MKError/directionsNotFound",
        "doc://com.apple.mapkit/documentation/MapKit/MKError/loadingThrottled",
        "doc://com.apple.mapkit/documentation/MapKit/MKError/serverFailure",
        "doc://com.apple.mapkit/documentation/MapKit/MKError/unknown",
        "doc://com.apple.mapkit/documentation/MapKit/MKError/Code"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKError~1Code/title",
          "value": "MKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkerror/placemarknotfound"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
