{
  "abstract": [
    {
      "text": "The radius, in units of local coordinate space, of the area from which light emanates.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO",
        "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/areaRadius"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MDLAreaLight(py)areaRadius",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "areaRadius"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "areaRadius"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "areaRadius"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "areaRadius"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The effect of radius on a light’s shape depends on the value of its inherited ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLight/lightType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/linear",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ": The light is shaped like a line segment, centered on the origin of its local coordinate space and extending along the x-axis with a total length of twice the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/areaRadius",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " value.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/discArea",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ": The light is shaped like a circle or ellipse in the xy-plane of its local coordinate space. If the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/aspect",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " value is ",
                      "type": "text"
                    },
                    {
                      "code": "1.0",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/areaRadius",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " value is the circle’s radius. If the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/aspect",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " value is less than one, the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/areaRadius",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " value is the major radius of the ellipse, and the minor radius is equal to the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/areaRadius",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " value times the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/aspect",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " value.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/rectangularArea",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ": The light is shaped like a rectangle in the xy-plane of its local coordinate space. If the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/aspect",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " value is ",
                      "type": "text"
                    },
                    {
                      "code": "1.0",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", the light is a square and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/areaRadius",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " value is half the square’s width or length. If the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/aspect",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " value is less than one, the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/areaRadius",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " value is half the rectangle’s longer dimension, and the shorter dimension is the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/areaRadius",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " value, times the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/aspect",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " value, times two.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/superElliptical",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ": The light is shaped like a superellipse—a two-dimensional figure in the xy-plane of its local coordinate space that can vary between shapes such as stars, diamonds, circles, and squares with rounded corners. The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/superEllipticPower",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property determines the general shape of the light, and the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/aspect",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property controls the ratio of the longer and shorter dimensions of the shape.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight": {
      "abstract": [
        {
          "text": "A light source that illuminates a 3D scene from an area with a specific shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLAreaLight"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLAreaLight"
        }
      ],
      "role": "symbol",
      "title": "MDLAreaLight",
      "type": "topic",
      "url": "/documentation/modelio/mdlarealight"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/areaRadius": {
      "abstract": [
        {
          "text": "The radius, in units of local coordinate space, of the area from which light emanates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "areaRadius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/areaRadius",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "areaRadius"
        }
      ],
      "role": "symbol",
      "title": "areaRadius",
      "type": "topic",
      "url": "/documentation/modelio/mdlarealight/arearadius"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/aspect": {
      "abstract": [
        {
          "text": "The aspect ratio of the light’s shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aspect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/aspect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "aspect"
        }
      ],
      "role": "symbol",
      "title": "aspect",
      "type": "topic",
      "url": "/documentation/modelio/mdlarealight/aspect"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/superEllipticPower": {
      "abstract": [
        {
          "text": "A vector that controls the roundness of a superelliptical light in the x- and y-axis directions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "superEllipticPower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_float2",
          "text": "vector_float2"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/superEllipticPower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "superEllipticPower"
        }
      ],
      "role": "symbol",
      "title": "superEllipticPower",
      "type": "topic",
      "url": "/documentation/modelio/mdlarealight/superellipticpower"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLight/lightType": {
      "abstract": [
        {
          "text": "The type of the light.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lightType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLLightType",
          "text": "MDLLightType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLight/lightType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lightType"
        }
      ],
      "role": "symbol",
      "title": "lightType",
      "type": "topic",
      "url": "/documentation/modelio/mdllight/lighttype"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/discArea": {
      "abstract": [
        {
          "text": "The light source illuminates a scene in all directions from an area in the shape of a disc.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discArea"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/discArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightTypeDiscArea"
        }
      ],
      "role": "symbol",
      "title": "MDLLightType.discArea",
      "type": "topic",
      "url": "/documentation/modelio/mdllighttype/discarea"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/linear": {
      "abstract": [
        {
          "text": "The light source illuminates a scene in all directions from an area in the shape of a line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linear"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/linear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightTypeLinear"
        }
      ],
      "role": "symbol",
      "title": "MDLLightType.linear",
      "type": "topic",
      "url": "/documentation/modelio/mdllighttype/linear"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/rectangularArea": {
      "abstract": [
        {
          "text": "The light source illuminates a scene in all directions from an area in the shape of a rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rectangularArea"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/rectangularArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightTypeRectangularArea"
        }
      ],
      "role": "symbol",
      "title": "MDLLightType.rectangularArea",
      "type": "topic",
      "url": "/documentation/modelio/mdllighttype/rectangulararea"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/superElliptical": {
      "abstract": [
        {
          "text": "The light source illuminates a scene in all directions from an area in the shape of a superellipse.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "superElliptical"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/superElliptical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightTypeSuperElliptical"
        }
      ],
      "role": "symbol",
      "title": "MDLLightType.superElliptical",
      "type": "topic",
      "url": "/documentation/modelio/mdllighttype/superelliptical"
    },
    "doc://com.externally.resolved.symbol/s:Sf": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-a-Lights-Shape",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/aspect",
        "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/superEllipticPower"
      ],
      "title": "Managing a Light’s Shape"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "areaRadius"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "areaRadius"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO",
                "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-a-Lights-Shape",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/aspect",
                "doc://com.apple.modelio/documentation/ModelIO/MDLAreaLight/superEllipticPower"
              ],
              "title": "Managing a Light’s Shape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readwrite"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:f",
                    "text": "float"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "areaRadius"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1discArea/title",
          "value": "MDLLightTypeDiscArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1discArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightTypeDiscArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAreaLight~1superEllipticPower/title",
          "value": "superEllipticPower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAreaLight~1superEllipticPower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "superEllipticPower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAreaLight~1aspect/title",
          "value": "aspect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAreaLight~1aspect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "aspect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1linear/title",
          "value": "MDLLightTypeLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1linear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightTypeLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1rectangularArea/title",
          "value": "MDLLightTypeRectangularArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1rectangularArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightTypeRectangularArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLight~1lightType/title",
          "value": "lightType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLight~1lightType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lightType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAreaLight/title",
          "value": "MDLAreaLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAreaLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLAreaLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAreaLight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLAreaLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAreaLight~1areaRadius/title",
          "value": "areaRadius"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAreaLight~1areaRadius/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "areaRadius"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1superElliptical/title",
          "value": "MDLLightTypeSuperElliptical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1superElliptical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightTypeSuperElliptical"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlarealight/arearadius"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlarealight/arearadius"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
