{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/OptionSet-Implementations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "OptionSet Implementations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader": {
      "abstract": [
        {
          "text": "A protocol that defines the requirements for a format reader, which represents a single media asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEFormatReader"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFormatReader"
        }
      ],
      "role": "symbol",
      "title": "MEFormatReader",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreader"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus": {
      "abstract": [
        {
          "text": "Informational status flags that the format reader returns after parsing additional fragments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEFormatReaderParseAdditionalFragmentsStatus"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFormatReaderParseAdditionalFragmentsStatus"
        }
      ],
      "role": "symbol",
      "title": "MEFormatReaderParseAdditionalFragmentsStatus",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/contains(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a given element is a",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "member of the option set.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Self",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "Self.Element",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contains"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/contains(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "contains(_:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/contains(_:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/formIntersection(_:)": {
      "abstract": [
        {
          "text": "Removes all elements of this option set that are not",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "also present in the given set.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "RawValue",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "FixedWidthInteger",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formIntersection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/formIntersection(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "formIntersection(_:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/formintersection(_:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/formSymmetricDifference(_:)": {
      "abstract": [
        {
          "text": "Replaces this set with a new set containing all elements",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "contained in either this set or the given set, but not in both.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "RawValue",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "FixedWidthInteger",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formSymmetricDifference"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/formSymmetricDifference(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "formSymmetricDifference(_:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/formsymmetricdifference(_:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/formUnion(_:)": {
      "abstract": [
        {
          "text": "Inserts the elements of another set into this option set.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "RawValue",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "FixedWidthInteger",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formUnion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/formUnion(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "formUnion(_:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/formunion(_:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/init()": {
      "abstract": [
        {
          "text": "Creates an empty option set.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "RawValue",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "FixedWidthInteger",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/init()"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/insert(_:)": {
      "abstract": [
        {
          "text": "Adds the given element to the option set if it is not already a member.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Self",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "Self.Element",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": ") -> (inserted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", memberAfterInsert"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/insert(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "insert(_:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/insert(_:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/intersection(_:)": {
      "abstract": [
        {
          "text": "Returns a new option set with only the elements contained in both this",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "set and the given set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intersection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/intersection(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "intersection(_:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/intersection(_:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/remove(_:)": {
      "abstract": [
        {
          "text": "Removes the given element and all elements subsumed by it.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Self",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "Self.Element",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/remove(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "remove(_:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/remove(_:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/symmetricDifference(_:)": {
      "abstract": [
        {
          "text": "Returns a new option set with the elements contained in this set or in",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "the given set, but not in both.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "symmetricDifference"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/symmetricDifference(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "symmetricDifference(_:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/symmetricdifference(_:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/union(_:)": {
      "abstract": [
        {
          "text": "Returns a new option set of the elements contained in this set, in the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "given set, or in both.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "union"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/union(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "union(_:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/union(_:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/update(with:)": {
      "abstract": [
        {
          "text": "Inserts the given element into the set.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Self",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "Self.Element",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "update"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/update(with:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "update(with:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/update(with:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/init()"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/contains(_:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/formIntersection(_:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/formSymmetricDifference(_:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/formUnion(_:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/insert(_:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/intersection(_:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/remove(_:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/symmetricDifference(_:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/union(_:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/update(with:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReader/title",
          "value": "MEFormatReader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderParseAdditionalFragmentsStatus/title",
          "value": "MEFormatReaderParseAdditionalFragmentsStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderParseAdditionalFragmentsStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReaderParseAdditionalFragmentsStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderParseAdditionalFragmentsStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReaderParseAdditionalFragmentsStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/optionset-implementations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
