{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/SetAlgebra-Implementations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "SetAlgebra Implementations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader": {
      "abstract": [
        {
          "text": "A protocol that defines the requirements for a format reader, which represents a single media asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEFormatReader"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFormatReader"
        }
      ],
      "role": "symbol",
      "title": "MEFormatReader",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreader"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus": {
      "abstract": [
        {
          "text": "Informational status flags that the format reader returns after parsing additional fragments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEFormatReaderParseAdditionalFragmentsStatus"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFormatReaderParseAdditionalFragmentsStatus"
        }
      ],
      "role": "symbol",
      "title": "MEFormatReaderParseAdditionalFragmentsStatus",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/init(_:)": {
      "abstract": [
        {
          "text": "Creates a new set from a finite sequence of items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "S"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "S"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/init(_:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/init(arrayLiteral:)": {
      "abstract": [
        {
          "text": "Creates a set containing the elements of the given array literal.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "ArrayLiteralElement",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "Self.Element",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "arrayLiteral"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "...)"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/init(arrayLiteral:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(arrayLiteral:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/init(arrayliteral:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/isDisjoint(with:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the set has no members in",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "common with the given set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDisjoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/isDisjoint(with:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "isDisjoint(with:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/isdisjoint(with:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/isEmpty": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the set has no elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEmpty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/isEmpty",
      "kind": "symbol",
      "role": "symbol",
      "title": "isEmpty",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/isempty"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/isStrictSubset(of:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether this set is a strict",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "subset of the given set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isStrictSubset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/isStrictSubset(of:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "isStrictSubset(of:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/isstrictsubset(of:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/isStrictSuperset(of:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether this set is a strict",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "superset of the given set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isStrictSuperset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/isStrictSuperset(of:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "isStrictSuperset(of:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/isstrictsuperset(of:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/isSubset(of:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the set is a subset of",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "another set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSubset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/isSubset(of:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "isSubset(of:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/issubset(of:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/isSuperset(of:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the set is a superset of",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "the given set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSuperset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/isSuperset(of:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "isSuperset(of:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/issuperset(of:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/subtract(_:)": {
      "abstract": [
        {
          "text": "Removes the elements of the given set from this set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtract"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/subtract(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "subtract(_:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/subtract(_:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/subtracting(_:)": {
      "abstract": [
        {
          "text": "Returns a new set containing the elements of this set that do not occur",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "in the given set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtracting"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/subtracting(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "subtracting(_:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/subtracting(_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/init(_:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/init(arrayLiteral:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/isEmpty"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/isDisjoint(with:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/isStrictSubset(of:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/isStrictSuperset(of:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/isSubset(of:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/isSuperset(of:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/subtract(_:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/subtracting(_:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderParseAdditionalFragmentsStatus/title",
          "value": "MEFormatReaderParseAdditionalFragmentsStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderParseAdditionalFragmentsStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReaderParseAdditionalFragmentsStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderParseAdditionalFragmentsStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReaderParseAdditionalFragmentsStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReader/title",
          "value": "MEFormatReader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReader"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/setalgebra-implementations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
