{
  "abstract": [
    {
      "text": "Configure audio processing settings using standard key and value constants.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/audio-settings"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio settings"
  },
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOENGINE_HAVE_AUAUDIOUNIT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOENGINE_HAVE_AUAUDIOUNIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
        }
      ],
      "role": "symbol",
      "title": "AVAUDIOENGINE_HAVE_AUAUDIOUNIT",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioengine_have_auaudiounit"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioBuffer": {
      "abstract": [
        {
          "text": "An object that represents a buffer of audio data with a format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioBuffer"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioBuffer"
        }
      ],
      "role": "symbol",
      "title": "AVAudioBuffer",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiobuffer"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout": {
      "abstract": [
        {
          "text": "An object that describes the roles of a set of audio channels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioChannelLayout"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "AVAudioChannelLayout",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiochannellayout"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioFile": {
      "abstract": [
        {
          "text": "An object that represents an audio file that the system can open for reading or writing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioFile"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioFile"
        }
      ],
      "role": "symbol",
      "title": "AVAudioFile",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiofile"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioFormat": {
      "abstract": [
        {
          "text": "An object that describes the representation of an audio format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioFormat"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioFormat"
        }
      ],
      "role": "symbol",
      "title": "AVAudioFormat",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioformat"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioQuality": {
      "abstract": [
        {
          "text": "The values that specify the sample rate audio quality for encoding and conversion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioQuality"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioQuality"
        }
      ],
      "role": "symbol",
      "title": "AVAudioQuality",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioquality"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioTime": {
      "abstract": [
        {
          "text": "An object you use to represent a moment in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioTime"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioTime"
        }
      ],
      "role": "symbol",
      "title": "AVAudioTime",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiotime"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVChannelLayoutKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVChannelLayoutKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVChannelLayoutKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVChannelLayoutKey"
        }
      ],
      "role": "symbol",
      "title": "AVChannelLayoutKey",
      "type": "topic",
      "url": "/documentation/avfaudio/avchannellayoutkey"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderAudioQualityKey": {
      "abstract": [
        {
          "text": "A constant that represents an integer from the audio quality enumeration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVEncoderAudioQualityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderAudioQualityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVEncoderAudioQualityKey"
        }
      ],
      "role": "symbol",
      "title": "AVEncoderAudioQualityKey",
      "type": "topic",
      "url": "/documentation/avfaudio/avencoderaudioqualitykey"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine": {
      "abstract": [
        {
          "text": "Perform advanced real-time and offline audio processing, implement 3D spatialization, and work with MIDI and samplers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Engine",
      "type": "topic",
      "url": "/documentation/avfaudio/audio-engine"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/encoder-bit-rate-strategy-values": {
      "abstract": [
        {
          "text": "The constants that represent the possible bit rate strategy values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/encoder-bit-rate-strategy-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Encoder Bit Rate Strategy Values",
      "type": "topic",
      "url": "/documentation/avfaudio/encoder-bit-rate-strategy-values"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/encoder-settings": {
      "abstract": [
        {
          "text": "The constants that define the audio encoder settings for the audio recorder class.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/encoder-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Encoder Settings",
      "type": "topic",
      "url": "/documentation/avfaudio/encoder-settings"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/format-settings": {
      "abstract": [
        {
          "text": "The audio settings that apply to all audio formats that the audio player and recorder classes support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/format-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Settings",
      "type": "topic",
      "url": "/documentation/avfaudio/format-settings"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/linear-pcm-format-settings": {
      "abstract": [
        {
          "text": "The audio settings that apply to linear PCM audio formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/linear-pcm-format-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Linear PCM Format Settings",
      "type": "topic",
      "url": "/documentation/avfaudio/linear-pcm-format-settings"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/sample-rate-conversion-settings": {
      "abstract": [
        {
          "text": "The constants that define sample rate converter audio quality settings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/sample-rate-conversion-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sample Rate Conversion Settings",
      "type": "topic",
      "url": "/documentation/avfaudio/sample-rate-conversion-settings"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/time-pitch-algorithm-settings": {
      "abstract": [
        {
          "text": "The constants that define the values for the time pitch algorithms.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/time-pitch-algorithm-settings",
      "kind": "article",
      "role": "article",
      "title": "Time Pitch Algorithm Settings",
      "type": "topic",
      "url": "/documentation/AVFoundation/time-pitch-algorithm-settings"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Supporting-data-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioBuffer",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioFile",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioTime"
      ],
      "title": "Supporting data types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Formats",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioFormat",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVChannelLayoutKey",
        "doc://com.apple.avfaudio/documentation/AVFAudio/linear-pcm-format-settings",
        "doc://com.apple.avfaudio/documentation/AVFAudio/format-settings"
      ],
      "title": "Formats"
    },
    {
      "anchor": "Settings",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/sample-rate-conversion-settings",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioQuality",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderAudioQualityKey",
        "doc://com.apple.avfaudio/documentation/AVFAudio/encoder-settings",
        "doc://com.apple.documentation/documentation/AVFoundation/time-pitch-algorithm-settings"
      ],
      "title": "Settings"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/encoder-bit-rate-strategy-values",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Formats",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioFormat",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVChannelLayoutKey",
                "doc://com.apple.avfaudio/documentation/AVFAudio/linear-pcm-format-settings",
                "doc://com.apple.avfaudio/documentation/AVFAudio/format-settings"
              ],
              "title": "Formats"
            },
            {
              "anchor": "Settings",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/sample-rate-conversion-settings",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioQuality",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderAudioQualityKey",
                "doc://com.apple.avfaudio/documentation/AVFAudio/encoder-settings",
                "doc://com.apple.documentation/documentation/AVFoundation/time-pitch-algorithm-settings"
              ],
              "title": "Settings"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/encoder-bit-rate-strategy-values",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Supporting-data-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioBuffer",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioFile",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioTime"
              ],
              "title": "Supporting data types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioBuffer/title",
          "value": "AVAudioBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioFile/title",
          "value": "AVAudioFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAUDIOENGINE_HAVE_AUAUDIOUNIT/title",
          "value": "AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAUDIOENGINE_HAVE_AUAUDIOUNIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVChannelLayoutKey/title",
          "value": "AVChannelLayoutKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVChannelLayoutKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVChannelLayoutKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioQuality/title",
          "value": "AVAudioQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioQuality/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioChannelLayout/title",
          "value": "AVAudioChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioChannelLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioTime/title",
          "value": "AVAudioTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioTime/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVEncoderAudioQualityKey/title",
          "value": "AVEncoderAudioQualityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVEncoderAudioQualityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVEncoderAudioQualityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioFormat/title",
          "value": "AVAudioFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/audio-settings"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/audio-settings"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
