{
  "abstract": [
    {
      "text": "Inspect and configure audio device settings including input gain, sample rate, and channel counts.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/audio-hardware"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio hardware"
  },
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession": {
      "abstract": [
        {
          "text": "An object that communicates to the system how you intend to use audio in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/inputGain": {
      "abstract": [
        {
          "text": "The gain applied to inputs associated with the session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputGain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/inputGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputGain"
        }
      ],
      "role": "symbol",
      "title": "inputGain",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/inputgain"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/inputLatency": {
      "abstract": [
        {
          "text": "The latency for audio input, in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/inputLatency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputLatency"
        }
      ],
      "role": "symbol",
      "title": "inputLatency",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/inputlatency"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/inputNumberOfChannels": {
      "abstract": [
        {
          "text": "The number of audio input channels for the current route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputNumberOfChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/inputNumberOfChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputNumberOfChannels"
        }
      ],
      "role": "symbol",
      "title": "inputNumberOfChannels",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/inputnumberofchannels"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/ioBufferDuration": {
      "abstract": [
        {
          "text": "The current I/O buffer duration, in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ioBufferDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/ioBufferDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBufferDuration"
        }
      ],
      "role": "symbol",
      "title": "ioBufferDuration",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/iobufferduration"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isInputGainSettable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can set the input gain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isInputGainSettable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isInputGainSettable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputGainSettable"
        }
      ],
      "role": "symbol",
      "title": "isInputGainSettable",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/isinputgainsettable"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/maximumInputNumberOfChannels": {
      "abstract": [
        {
          "text": "The maximum number of input channels available for the current audio route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumInputNumberOfChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/maximumInputNumberOfChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumInputNumberOfChannels"
        }
      ],
      "role": "symbol",
      "title": "maximumInputNumberOfChannels",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/maximuminputnumberofchannels"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/maximumOutputNumberOfChannels": {
      "abstract": [
        {
          "text": "The maximum number of output channels available for the current audio route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumOutputNumberOfChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/maximumOutputNumberOfChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumOutputNumberOfChannels"
        }
      ],
      "role": "symbol",
      "title": "maximumOutputNumberOfChannels",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/maximumoutputnumberofchannels"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/outputLatency": {
      "abstract": [
        {
          "text": "The latency for audio output, in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/outputLatency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputLatency"
        }
      ],
      "role": "symbol",
      "title": "outputLatency",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/outputlatency"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/outputNumberOfChannels": {
      "abstract": [
        {
          "text": "The number of audio output channels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputNumberOfChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/outputNumberOfChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputNumberOfChannels"
        }
      ],
      "role": "symbol",
      "title": "outputNumberOfChannels",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/outputnumberofchannels"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/outputVolume": {
      "abstract": [
        {
          "text": "The systemwide output volume set by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputVolume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/outputVolume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputVolume"
        }
      ],
      "role": "symbol",
      "title": "outputVolume",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/outputvolume"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredIOBufferDuration": {
      "abstract": [
        {
          "text": "The preferred I/O buffer duration, in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredIOBufferDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredIOBufferDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredIOBufferDuration"
        }
      ],
      "role": "symbol",
      "title": "preferredIOBufferDuration",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/preferrediobufferduration"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredInputNumberOfChannels": {
      "abstract": [
        {
          "text": "The preferred number of input channels for the current route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredInputNumberOfChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredInputNumberOfChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredInputNumberOfChannels"
        }
      ],
      "role": "symbol",
      "title": "preferredInputNumberOfChannels",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/preferredinputnumberofchannels"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredOutputNumberOfChannels": {
      "abstract": [
        {
          "text": "The preferred number of output channels for the current route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredOutputNumberOfChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredOutputNumberOfChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredOutputNumberOfChannels"
        }
      ],
      "role": "symbol",
      "title": "preferredOutputNumberOfChannels",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/preferredoutputnumberofchannels"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredSampleRate": {
      "abstract": [
        {
          "text": "The preferred sample rate, in hertz.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredSampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredSampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredSampleRate"
        }
      ],
      "role": "symbol",
      "title": "preferredSampleRate",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/preferredsamplerate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/sampleRate": {
      "abstract": [
        {
          "text": "The current audio sample rate, in hertz.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/sampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sampleRate"
        }
      ],
      "role": "symbol",
      "title": "sampleRate",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/samplerate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setInputGain(_:)": {
      "abstract": [
        {
          "text": "Changes the input gain to the specified value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setInputGain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setInputGain(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setInputGain:error:"
        }
      ],
      "role": "symbol",
      "title": "setInputGain(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/setinputgain(_:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredIOBufferDuration(_:)": {
      "abstract": [
        {
          "text": "Sets the preferred audio I/O buffer duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPreferredIOBufferDuration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredIOBufferDuration(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPreferredIOBufferDuration:error:"
        }
      ],
      "role": "symbol",
      "title": "setPreferredIOBufferDuration(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/setpreferrediobufferduration(_:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredInputNumberOfChannels(_:)": {
      "abstract": [
        {
          "text": "Sets the preferred number of input channels for the current route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPreferredInputNumberOfChannels"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredInputNumberOfChannels(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPreferredInputNumberOfChannels:error:"
        }
      ],
      "role": "symbol",
      "title": "setPreferredInputNumberOfChannels(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/setpreferredinputnumberofchannels(_:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredOutputNumberOfChannels(_:)": {
      "abstract": [
        {
          "text": "Sets the preferred number of output channels for the current route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPreferredOutputNumberOfChannels"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredOutputNumberOfChannels(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPreferredOutputNumberOfChannels:error:"
        }
      ],
      "role": "symbol",
      "title": "setPreferredOutputNumberOfChannels(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/setpreferredoutputnumberofchannels(_:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredSampleRate(_:)": {
      "abstract": [
        {
          "text": "Sets the preferred sample rate for audio input and output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPreferredSampleRate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredSampleRate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPreferredSampleRate:error:"
        }
      ],
      "role": "symbol",
      "title": "setPreferredSampleRate(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/setpreferredsamplerate(_:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setSupportsMultichannelContent(_:)": {
      "abstract": [
        {
          "text": "Sets whether your app supplies multichannel audio content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setSupportsMultichannelContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setSupportsMultichannelContent(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setSupportsMultichannelContent:error:"
        }
      ],
      "role": "symbol",
      "title": "setSupportsMultichannelContent(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/setsupportsmultichannelcontent(_:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/supportsMultichannelContent": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app supplies multichannel audio content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsMultichannelContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/supportsMultichannelContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsMultichannelContent"
        }
      ],
      "role": "symbol",
      "title": "supportsMultichannelContent",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/supportsmultichannelcontent"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Configuring-sample-rate",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/sampleRate",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredSampleRate",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredSampleRate(_:)"
      ],
      "title": "Configuring sample rate"
    },
    {
      "anchor": "Setting-input-gain",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/inputGain",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isInputGainSettable",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setInputGain(_:)"
      ],
      "title": "Setting input gain"
    },
    {
      "anchor": "Configuring-IO-buffer-duration",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/ioBufferDuration",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredIOBufferDuration",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredIOBufferDuration(_:)"
      ],
      "title": "Configuring I/O buffer duration"
    },
    {
      "anchor": "Inspecting-latency",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/inputLatency",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/outputLatency"
      ],
      "title": "Inspecting latency"
    },
    {
      "anchor": "Inspecting-output-volume",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/outputVolume"
      ],
      "title": "Inspecting output volume"
    },
    {
      "anchor": "Setting-the-number-of-input-channels",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredInputNumberOfChannels",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredInputNumberOfChannels(_:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/inputNumberOfChannels",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/maximumInputNumberOfChannels"
      ],
      "title": "Setting the number of input channels"
    },
    {
      "anchor": "Setting-the-number-of-output-channels",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredOutputNumberOfChannels",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredOutputNumberOfChannels(_:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/outputNumberOfChannels",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/maximumOutputNumberOfChannels"
      ],
      "title": "Setting the number of output channels"
    },
    {
      "anchor": "Configuring-multichannel-support",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/supportsMultichannelContent",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setSupportsMultichannelContent(_:)"
      ],
      "title": "Configuring multichannel support"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-sample-rate",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/sampleRate",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredSampleRate",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredSampleRate(_:)"
              ],
              "title": "Configuring sample rate"
            },
            {
              "anchor": "Setting-input-gain",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/inputGain",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isInputGainSettable",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setInputGain(_:)"
              ],
              "title": "Setting input gain"
            },
            {
              "anchor": "Configuring-IO-buffer-duration",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/ioBufferDuration",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredIOBufferDuration",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredIOBufferDuration(_:)"
              ],
              "title": "Configuring I/O buffer duration"
            },
            {
              "anchor": "Inspecting-latency",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/inputLatency",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/outputLatency"
              ],
              "title": "Inspecting latency"
            },
            {
              "anchor": "Inspecting-output-volume",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/outputVolume"
              ],
              "title": "Inspecting output volume"
            },
            {
              "anchor": "Setting-the-number-of-input-channels",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredInputNumberOfChannels",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredInputNumberOfChannels(_:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/inputNumberOfChannels",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/maximumInputNumberOfChannels"
              ],
              "title": "Setting the number of input channels"
            },
            {
              "anchor": "Setting-the-number-of-output-channels",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredOutputNumberOfChannels",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredOutputNumberOfChannels(_:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/outputNumberOfChannels",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/maximumOutputNumberOfChannels"
              ],
              "title": "Setting the number of output channels"
            },
            {
              "anchor": "Configuring-multichannel-support",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/supportsMultichannelContent",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setSupportsMultichannelContent(_:)"
              ],
              "title": "Configuring multichannel support"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1preferredOutputNumberOfChannels/title",
          "value": "preferredOutputNumberOfChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1preferredOutputNumberOfChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredOutputNumberOfChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setInputGain(_:)/title",
          "value": "setInputGain:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setInputGain(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setInputGain:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1inputGain/title",
          "value": "inputGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1inputGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1supportsMultichannelContent/title",
          "value": "supportsMultichannelContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1supportsMultichannelContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsMultichannelContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1inputLatency/title",
          "value": "inputLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1inputLatency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1outputLatency/title",
          "value": "outputLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1outputLatency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/title",
          "value": "AVAudioSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1preferredInputNumberOfChannels/title",
          "value": "preferredInputNumberOfChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1preferredInputNumberOfChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredInputNumberOfChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setPreferredInputNumberOfChannels(_:)/title",
          "value": "setPreferredInputNumberOfChannels:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setPreferredInputNumberOfChannels(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPreferredInputNumberOfChannels:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1ioBufferDuration/title",
          "value": "IOBufferDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1ioBufferDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBufferDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setPreferredSampleRate(_:)/title",
          "value": "setPreferredSampleRate:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setPreferredSampleRate(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPreferredSampleRate:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1inputNumberOfChannels/title",
          "value": "inputNumberOfChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1inputNumberOfChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputNumberOfChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1preferredSampleRate/title",
          "value": "preferredSampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1preferredSampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredSampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1maximumInputNumberOfChannels/title",
          "value": "maximumInputNumberOfChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1maximumInputNumberOfChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumInputNumberOfChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1sampleRate/title",
          "value": "sampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1sampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1outputVolume/title",
          "value": "outputVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1outputVolume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setSupportsMultichannelContent(_:)/title",
          "value": "setSupportsMultichannelContent:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setSupportsMultichannelContent(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setSupportsMultichannelContent:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1preferredIOBufferDuration/title",
          "value": "preferredIOBufferDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1preferredIOBufferDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredIOBufferDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1outputNumberOfChannels/title",
          "value": "outputNumberOfChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1outputNumberOfChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputNumberOfChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1maximumOutputNumberOfChannels/title",
          "value": "maximumOutputNumberOfChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1maximumOutputNumberOfChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumOutputNumberOfChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setPreferredIOBufferDuration(_:)/title",
          "value": "setPreferredIOBufferDuration:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setPreferredIOBufferDuration(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPreferredIOBufferDuration:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setPreferredOutputNumberOfChannels(_:)/title",
          "value": "setPreferredOutputNumberOfChannels:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setPreferredOutputNumberOfChannels(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPreferredOutputNumberOfChannels:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1isInputGainSettable/title",
          "value": "inputGainSettable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1isInputGainSettable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputGainSettable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/audio-hardware"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/audio-hardware"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
