{
  "abstract": [
    {
      "text": "An object that provides details about an audio unit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVAudioUnitComponent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVAudioUnitComponent"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioUnitComponent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVAudioUnitComponent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioUnitComponent"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Details can include information such as type, subtype, manufacturer, and location. An ",
              "type": "text"
            },
            {
              "code": "AVAudioUnitComponent",
              "type": "codeVoice"
            },
            {
              "text": " can include user tags, which you can query later for display.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent": {
      "abstract": [
        {
          "text": "An object that provides details about an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitComponent"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitComponent"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitComponent",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/allTagNames": {
      "abstract": [
        {
          "text": "An array of tag names for the audio unit component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allTagNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/allTagNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allTagNames"
        }
      ],
      "role": "symbol",
      "title": "allTagNames",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/alltagnames"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/audioComponent": {
      "abstract": [
        {
          "text": "The underlying audio component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioComponent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioComponent",
          "text": "AudioComponent"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/audioComponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audioComponent"
        }
      ],
      "role": "symbol",
      "title": "audioComponent",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/audiocomponent"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/audioComponentDescription": {
      "abstract": [
        {
          "text": "The audio component description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioComponentDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioComponentDescription",
          "text": "AudioComponentDescription"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/audioComponentDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audioComponentDescription"
        }
      ],
      "role": "symbol",
      "title": "audioComponentDescription",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/audiocomponentdescription"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/availableArchitectures": {
      "abstract": [
        {
          "text": "An array of architectures that the audio unit supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableArchitectures"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/availableArchitectures",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableArchitectures"
        }
      ],
      "role": "symbol",
      "title": "availableArchitectures",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/availablearchitectures"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/componentURL": {
      "abstract": [
        {
          "text": "The URL of the audio unit component.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "componentURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/componentURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "componentURL"
        }
      ],
      "role": "symbol",
      "title": "componentURL",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/componenturl"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/configurationDictionary": {
      "abstract": [
        {
          "text": "The audio unit component’s configuration dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationDictionary"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/configurationDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configurationDictionary"
        }
      ],
      "role": "symbol",
      "title": "configurationDictionary",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/configurationdictionary"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasCustomView": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the audio unit component has a custom view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasCustomView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasCustomView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasCustomView"
        }
      ],
      "role": "symbol",
      "title": "hasCustomView",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/hascustomview"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasMIDIInput": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the audio unit component has MIDI input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasMIDIInput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasMIDIInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasMIDIInput"
        }
      ],
      "role": "symbol",
      "title": "hasMIDIInput",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/hasmidiinput"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasMIDIOutput": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the audio unit component has MIDI output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasMIDIOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasMIDIOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasMIDIOutput"
        }
      ],
      "role": "symbol",
      "title": "hasMIDIOutput",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/hasmidioutput"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/icon": {
      "abstract": [
        {
          "text": "An icon that represents the component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "icon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/icon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "icon"
        }
      ],
      "role": "symbol",
      "title": "icon",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/icon"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/iconURL": {
      "abstract": [
        {
          "text": "The URL of an icon that represents the audio unit component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iconURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/iconURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iconURL"
        }
      ],
      "role": "symbol",
      "title": "iconURL",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/iconurl"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/isSandboxSafe": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the audio unit component is safe for sandboxing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSandboxSafe"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/isSandboxSafe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sandboxSafe"
        }
      ],
      "role": "symbol",
      "title": "isSandboxSafe",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/issandboxsafe"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/localizedTypeName": {
      "abstract": [
        {
          "text": "The localized type name of the component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedTypeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/localizedTypeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedTypeName"
        }
      ],
      "role": "symbol",
      "title": "localizedTypeName",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/localizedtypename"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/manufacturerName": {
      "abstract": [
        {
          "text": "The name of the manufacturer of the audio unit component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manufacturerName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/manufacturerName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "manufacturerName"
        }
      ],
      "role": "symbol",
      "title": "manufacturerName",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/manufacturername"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/name": {
      "abstract": [
        {
          "text": "The name of the audio unit component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/name"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/passesAUVal": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the audio unit component passes the validation tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passesAUVal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/passesAUVal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "passesAUVal"
        }
      ],
      "role": "symbol",
      "title": "passesAUVal",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/passesauval"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/supportsNumberInputChannels(_:outputChannels:)": {
      "abstract": [
        {
          "text": "Gets a Boolean value that indicates whether the audio unit component supports the specified number of input and output channels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsNumberInputChannels"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "outputChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/supportsNumberInputChannels(_:outputChannels:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsNumberInputChannels:outputChannels:"
        }
      ],
      "role": "symbol",
      "title": "supportsNumberInputChannels(_:outputChannels:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/supportsnumberinputchannels(_:outputchannels:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/typeName": {
      "abstract": [
        {
          "text": "The audio unit component type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/typeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typeName"
        }
      ],
      "role": "symbol",
      "title": "typeName",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/typename"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/userTagNames": {
      "abstract": [
        {
          "text": "An array of tags the user creates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userTagNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/userTagNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userTagNames"
        }
      ],
      "role": "symbol",
      "title": "userTagNames",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/usertagnames"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/version": {
      "abstract": [
        {
          "text": "The audio unit component version number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/version"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/versionString": {
      "abstract": [
        {
          "text": "A string that represents the audio unit component version number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "versionString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/versionString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "versionString"
        }
      ],
      "role": "symbol",
      "title": "versionString",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/versionstring"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponentManager": {
      "abstract": [
        {
          "text": "An object that provides a way to search and query audio components that the system registers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitComponentManager"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponentManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitComponentManager"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitComponentManager",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponentmanager"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponentTagsDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that indicates when component tags change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitComponentTagsDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponentTagsDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioUnitComponentTagsDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponenttagsdidchangenotification"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitManufacturerNameApple": {
      "abstract": [
        {
          "text": "The audio unit manufacturer is Apple.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitManufacturerNameApple"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitManufacturerNameApple",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitManufacturerNameApple"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitManufacturerNameApple",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitmanufacturernameapple"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeEffect": {
      "abstract": [
        {
          "text": "An audio unit type that represents an effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeEffect"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypeEffect",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypeeffect"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeFormatConverter": {
      "abstract": [
        {
          "text": "An audio unit type that represents a format converter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeFormatConverter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeFormatConverter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeFormatConverter"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypeFormatConverter",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypeformatconverter"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeGenerator": {
      "abstract": [
        {
          "text": "An audio unit type that represents a generator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeGenerator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeGenerator"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypeGenerator",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypegenerator"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMIDIProcessor": {
      "abstract": [
        {
          "text": "An audio unit type that represents a MIDI processor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeMIDIProcessor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMIDIProcessor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeMIDIProcessor"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypeMIDIProcessor",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypemidiprocessor"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMixer": {
      "abstract": [
        {
          "text": "An audio unit type that represents a mixer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeMixer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMixer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeMixer"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypeMixer",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypemixer"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMusicDevice": {
      "abstract": [
        {
          "text": "An audio unit type that represents a music device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeMusicDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMusicDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeMusicDevice"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypeMusicDevice",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypemusicdevice"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMusicEffect": {
      "abstract": [
        {
          "text": "An audio unit type that represents a music effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeMusicEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMusicEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeMusicEffect"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypeMusicEffect",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypemusiceffect"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeOfflineEffect": {
      "abstract": [
        {
          "text": "An audio unit type that represents an offline effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeOfflineEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeOfflineEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeOfflineEffect"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypeOfflineEffect",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypeofflineeffect"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeOutput": {
      "abstract": [
        {
          "text": "An audio unit type that represents an output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeOutput"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypeOutput",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypeoutput"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypePanner": {
      "abstract": [
        {
          "text": "An audio unit type that represents a panner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypePanner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypePanner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypePanner"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypePanner",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypepanner"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Component-management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponentManager"
      ],
      "title": "Component management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-audio-unit-components-audio-unit",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/audioComponent"
      ],
      "title": "Getting the audio unit component’s audio unit"
    },
    {
      "anchor": "Getting-audio-unit-component-information",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/audioComponentDescription",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/availableArchitectures",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/configurationDictionary",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasCustomView",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasMIDIInput",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasMIDIOutput",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/manufacturerName",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/name",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/passesAUVal",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/isSandboxSafe",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/supportsNumberInputChannels(_:outputChannels:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/typeName",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/version",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/versionString",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/componentURL"
      ],
      "title": "Getting audio unit component information"
    },
    {
      "anchor": "Getting-audio-unit-component-tags",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/iconURL",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/icon",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/localizedTypeName",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/allTagNames",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/userTagNames"
      ],
      "title": "Getting audio unit component tags"
    },
    {
      "anchor": "Audio-unit-manufacturer-names",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitManufacturerNameApple"
      ],
      "title": "Audio unit manufacturer names"
    },
    {
      "anchor": "Audio-unit-types",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeOutput",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMusicDevice",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMusicEffect",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeFormatConverter",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeEffect",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMixer",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypePanner",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeGenerator",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeOfflineEffect",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMIDIProcessor"
      ],
      "title": "Audio unit types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioUnitComponent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-audio-unit-components-audio-unit",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/audioComponent"
              ],
              "title": "Getting the audio unit component’s audio unit"
            },
            {
              "anchor": "Getting-audio-unit-component-information",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/audioComponentDescription",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/availableArchitectures",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/configurationDictionary",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasCustomView",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasMIDIInput",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasMIDIOutput",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/manufacturerName",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/name",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/passesAUVal",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/isSandboxSafe",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/supportsNumberInputChannels(_:outputChannels:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/typeName",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/version",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/versionString",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/componentURL"
              ],
              "title": "Getting audio unit component information"
            },
            {
              "anchor": "Getting-audio-unit-component-tags",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/iconURL",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/icon",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/localizedTypeName",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/allTagNames",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/userTagNames"
              ],
              "title": "Getting audio unit component tags"
            },
            {
              "anchor": "Notifications",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponentTagsDidChangeNotification"
              ],
              "title": "Notifications"
            },
            {
              "anchor": "Audio-unit-manufacturer-names",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitManufacturerNameApple"
              ],
              "title": "Audio unit manufacturer names"
            },
            {
              "anchor": "Audio-unit-types",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeOutput",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMusicDevice",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMusicEffect",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeFormatConverter",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeEffect",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMixer",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypePanner",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeGenerator",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeOfflineEffect",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMIDIProcessor"
              ],
              "title": "Audio unit types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Component-management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponentManager"
              ],
              "title": "Component management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAudioUnitComponent"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1userTagNames/title",
          "value": "userTagNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1userTagNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userTagNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1icon/title",
          "value": "icon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1icon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "icon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeEffect/title",
          "value": "AVAudioUnitTypeEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitManufacturerNameApple/title",
          "value": "AVAudioUnitManufacturerNameApple"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitManufacturerNameApple/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitManufacturerNameApple"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1hasMIDIOutput/title",
          "value": "hasMIDIOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1hasMIDIOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasMIDIOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1passesAUVal/title",
          "value": "passesAUVal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1passesAUVal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "passesAUVal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeFormatConverter/title",
          "value": "AVAudioUnitTypeFormatConverter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeFormatConverter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeFormatConverter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1hasCustomView/title",
          "value": "hasCustomView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1hasCustomView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasCustomView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeGenerator/title",
          "value": "AVAudioUnitTypeGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1audioComponentDescription/title",
          "value": "audioComponentDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1audioComponentDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "audioComponentDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypePanner/title",
          "value": "AVAudioUnitTypePanner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypePanner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypePanner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1manufacturerName/title",
          "value": "manufacturerName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1manufacturerName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "manufacturerName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1localizedTypeName/title",
          "value": "localizedTypeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1localizedTypeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedTypeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent/title",
          "value": "AVAudioUnitComponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1supportsNumberInputChannels(_:outputChannels:)/title",
          "value": "supportsNumberInputChannels:outputChannels:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1supportsNumberInputChannels(_:outputChannels:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "supportsNumberInputChannels:outputChannels:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1allTagNames/title",
          "value": "allTagNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1allTagNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allTagNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeOfflineEffect/title",
          "value": "AVAudioUnitTypeOfflineEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeOfflineEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeOfflineEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1versionString/title",
          "value": "versionString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1versionString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "versionString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeMusicEffect/title",
          "value": "AVAudioUnitTypeMusicEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeMusicEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeMusicEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1availableArchitectures/title",
          "value": "availableArchitectures"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1availableArchitectures/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availableArchitectures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeMusicDevice/title",
          "value": "AVAudioUnitTypeMusicDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeMusicDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeMusicDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1audioComponent/title",
          "value": "audioComponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1audioComponent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "audioComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1hasMIDIInput/title",
          "value": "hasMIDIInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1hasMIDIInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasMIDIInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponentManager/title",
          "value": "AVAudioUnitComponentManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponentManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitComponentManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponentManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitComponentManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1typeName/title",
          "value": "typeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1typeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "typeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1componentURL/title",
          "value": "componentURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1componentURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "componentURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeOutput/title",
          "value": "AVAudioUnitTypeOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1configurationDictionary/title",
          "value": "configurationDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1configurationDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "configurationDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1isSandboxSafe/title",
          "value": "sandboxSafe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1isSandboxSafe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sandboxSafe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1iconURL/title",
          "value": "iconURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1iconURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "iconURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeMIDIProcessor/title",
          "value": "AVAudioUnitTypeMIDIProcessor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeMIDIProcessor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeMIDIProcessor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeMixer/title",
          "value": "AVAudioUnitTypeMixer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeMixer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeMixer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiounitcomponent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiounitcomponent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
