{
  "abstract": [
    {
      "text": "A subclass of the audio node class that, processes audio either in real time or nonreal time, depending on the type of the audio unit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVAudioUnit",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVAudioUnit"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioUnit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVAudioUnit"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioUnit"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/creating-an-audio-unit-extension"
      ]
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioNode": {
      "abstract": [
        {
          "text": "An object you use for audio generation, processing, or an I/O block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioNode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioNode"
        }
      ],
      "role": "symbol",
      "title": "AVAudioNode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudionode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit": {
      "abstract": [
        {
          "text": "A subclass of the audio node class that, processes audio either in real time or nonreal time, depending on the type of the audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnit"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnit"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnit",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounit"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/auAudioUnit": {
      "abstract": [
        {
          "text": "The audio unit class wrapping or underlying the implementation’s audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auAudioUnit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AUAudioUnit",
          "text": "AUAudioUnit"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/auAudioUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnit"
        }
      ],
      "role": "symbol",
      "title": "auAudioUnit",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounit/auaudiounit"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/audioComponentDescription": {
      "abstract": [
        {
          "text": "The audio component description that represents the underlying Core Audio audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioComponentDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioComponentDescription",
          "text": "AudioComponentDescription"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/audioComponentDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audioComponentDescription"
        }
      ],
      "role": "symbol",
      "title": "audioComponentDescription",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounit/audiocomponentdescription"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/audioUnit": {
      "abstract": [
        {
          "text": "The underlying Core Audio audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioUnit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioUnit",
          "text": "AudioUnit"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/audioUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audioUnit"
        }
      ],
      "role": "symbol",
      "title": "audioUnit",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounit/audiounit"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/instantiate(with:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates an instance of an audio unit component asynchronously and wraps it in an audio unit class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instantiate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioComponentDescription",
          "text": "AudioComponentDescription"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioComponentInstantiationOptions",
          "text": "AudioComponentInstantiationOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioUnit",
          "text": "AVAudioUnit"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/instantiate(with:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instantiateWithComponentDescription:options:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "instantiate(with:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounit/instantiate(with:options:completionhandler:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/loadPreset(at:)": {
      "abstract": [
        {
          "text": "Loads an audio unit using a specified preset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadPreset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/loadPreset(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadAudioUnitPresetAtURL:error:"
        }
      ],
      "role": "symbol",
      "title": "loadPreset(at:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounit/loadpreset(at:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/manufacturerName": {
      "abstract": [
        {
          "text": "The name of the manufacturer of the audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manufacturerName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/manufacturerName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "manufacturerName"
        }
      ],
      "role": "symbol",
      "title": "manufacturerName",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounit/manufacturername"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/name": {
      "abstract": [
        {
          "text": "The name of the audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounit/name"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/version": {
      "abstract": [
        {
          "text": "The version number of the audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounit/version"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEffect": {
      "abstract": [
        {
          "text": "An object that processes audio in real time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitEffect"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitEffect"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitEffect",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiouniteffect"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitGenerator": {
      "abstract": [
        {
          "text": "An object that generates audio output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitGenerator"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitGenerator"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitGenerator",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitgenerator"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitMIDIInstrument": {
      "abstract": [
        {
          "text": "An object that represents music devices or remote instruments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitMIDIInstrument"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitMIDIInstrument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitMIDIInstrument"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitMIDIInstrument",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitmidiinstrument"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTimeEffect": {
      "abstract": [
        {
          "text": "An object that processes audio in nonreal time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTimeEffect"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTimeEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTimeEffect"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTimeEffect",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittimeeffect"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/creating-an-audio-unit-extension": {
      "abstract": [
        {
          "text": "Build an extension by using an Xcode template.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/creating-an-audio-unit-extension",
      "kind": "article",
      "role": "article",
      "title": "Creating an audio unit extension",
      "type": "topic",
      "url": "/documentation/avfaudio/creating-an-audio-unit-extension"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/using-voice-processing": {
      "abstract": [
        {
          "text": "Add voice-processing capabilities to your app by using audio engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/using-voice-processing",
      "kind": "article",
      "role": "sampleCode",
      "title": "Using voice processing",
      "type": "topic",
      "url": "/documentation/avfaudio/using-voice-processing"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioNode"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEffect",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitGenerator",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitMIDIInstrument",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTimeEffect"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/creating-an-audio-unit-extension",
        "doc://com.apple.avfaudio/documentation/AVFAudio/using-voice-processing"
      ],
      "title": "Essentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-Core-Audio-audio-unit",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/audioUnit"
      ],
      "title": "Getting the Core Audio audio unit"
    },
    {
      "anchor": "Loading-an-audio-preset-file",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/loadPreset(at:)"
      ],
      "title": "Loading an audio preset file"
    },
    {
      "anchor": "Creating-an-audio-unit-component",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/instantiate(with:options:completionHandler:)"
      ],
      "title": "Creating an audio unit component"
    },
    {
      "anchor": "Getting-audio-unit-values",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/audioComponentDescription",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/manufacturerName",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/name",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/version",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/auAudioUnit"
      ],
      "title": "Getting audio unit values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioUnit"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-Core-Audio-audio-unit",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/audioUnit"
              ],
              "title": "Getting the Core Audio audio unit"
            },
            {
              "anchor": "Loading-an-audio-preset-file",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/loadPreset(at:)"
              ],
              "title": "Loading an audio preset file"
            },
            {
              "anchor": "Creating-an-audio-unit-component",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/instantiate(with:options:completionHandler:)"
              ],
              "title": "Creating an audio unit component"
            },
            {
              "anchor": "Getting-audio-unit-values",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/audioComponentDescription",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/manufacturerName",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/name",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/version",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit/auAudioUnit"
              ],
              "title": "Getting audio unit values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioNode"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEffect",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitGenerator",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitMIDIInstrument",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTimeEffect"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/creating-an-audio-unit-extension",
                "doc://com.apple.avfaudio/documentation/AVFAudio/using-voice-processing"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAudioUnit"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioNode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVAudioNode",
                    "text": "AVAudioNode"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit~1auAudioUnit/title",
          "value": "AUAudioUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit~1auAudioUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEffect/title",
          "value": "AVAudioUnitEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEffect/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioNode/title",
          "value": "AVAudioNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit~1manufacturerName/title",
          "value": "manufacturerName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit~1manufacturerName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "manufacturerName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit~1instantiate(with:options:completionHandler:)/title",
          "value": "instantiateWithComponentDescription:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit~1instantiate(with:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "instantiateWithComponentDescription:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitGenerator/title",
          "value": "AVAudioUnitGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit~1audioUnit/title",
          "value": "audioUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit~1audioUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "audioUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit~1audioComponentDescription/title",
          "value": "audioComponentDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit~1audioComponentDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "audioComponentDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTimeEffect/title",
          "value": "AVAudioUnitTimeEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTimeEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTimeEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTimeEffect/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTimeEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit/title",
          "value": "AVAudioUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit~1loadPreset(at:)/title",
          "value": "loadAudioUnitPresetAtURL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit~1loadPreset(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadAudioUnitPresetAtURL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitMIDIInstrument/title",
          "value": "AVAudioUnitMIDIInstrument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitMIDIInstrument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitMIDIInstrument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitMIDIInstrument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitMIDIInstrument"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiounit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiounit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
