{
  "abstract": [
    {
      "text": "The types of rendering algorithms available per input bus of the environment node.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVAudio3DMixingRenderingAlgorithm",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVAudio3DMixingRenderingAlgorithm"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudio3DMixingRenderingAlgorithm"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AVAudio3DMixingRenderingAlgorithm"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithm"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The rendering algorithms differ in quality and CPU cost. ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/equalPowerPanning",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is the simplest panning algorithm and the least expensive computationally.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When rendering to multichannel hardware, most of the rendering algorithms only render to channels 1 and 2, excluding ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/soundField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/auto",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DAngularOrientation": {
      "abstract": [
        {
          "text": "A structure that represents the angular orientation of the listener in 3D space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DAngularOrientation"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DAngularOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DAngularOrientation"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DAngularOrientation",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dangularorientation"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing": {
      "abstract": [
        {
          "text": "A collection of properties that define 3D mixing properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DMixing"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixing"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixing",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixing"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingPointSourceInHeadMode": {
      "abstract": [
        {
          "text": "The in-head modes for a point source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingPointSourceInHeadMode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingPointSourceInHeadMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingPointSourceInHeadMode"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingPointSourceInHeadMode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingpointsourceinheadmode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm": {
      "abstract": [
        {
          "text": "The types of rendering algorithms available per input bus of the environment node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingRenderingAlgorithm",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/HRTF": {
      "abstract": [
        {
          "text": "A high-quality algorithm that uses filtering to emulate 3D space in headphones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HRTF"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/HRTF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithmHRTF"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingRenderingAlgorithm.HRTF",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm/hrtf"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/HRTFHQ": {
      "abstract": [
        {
          "text": "A higher-quality head-related transfer function rendering algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HRTFHQ"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/HRTFHQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithmHRTFHQ"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingRenderingAlgorithm.HRTFHQ",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm/hrtfhq"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/auto": {
      "abstract": [
        {
          "text": "Automatically selects the highest-quality rendering algorithm available for the current playback hardware.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auto"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/auto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithmAuto"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingRenderingAlgorithm.auto",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm/auto"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/equalPowerPanning": {
      "abstract": [
        {
          "text": "An algorithm that pans the data of the mixer bus into a stereo field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "equalPowerPanning"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/equalPowerPanning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithmEqualPowerPanning"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingRenderingAlgorithm.equalPowerPanning",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm/equalpowerpanning"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm/init(rawvalue:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/soundField": {
      "abstract": [
        {
          "text": "An algorithm that renders to multichannel hardware.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "soundField"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/soundField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithmSoundField"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingRenderingAlgorithm.soundField",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm/soundfield"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/sphericalHead": {
      "abstract": [
        {
          "text": "An algorithm that emulates 3D space in headphones by simulating interaural time delays and other spatial cues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sphericalHead"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/sphericalHead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithmSphericalHead"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingRenderingAlgorithm.sphericalHead",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm/sphericalhead"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/stereoPassThrough": {
      "abstract": [
        {
          "text": "An algorithm to use when the source data doesn’t need localization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stereoPassThrough"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/stereoPassThrough",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithmStereoPassThrough"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingRenderingAlgorithm.stereoPassThrough",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm/stereopassthrough"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingSourceMode": {
      "abstract": [
        {
          "text": "The source modes for the input bus of the audio environment node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingSourceMode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingSourceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingSourceMode"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingSourceMode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingsourcemode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DPoint": {
      "abstract": [
        {
          "text": "A structure that represents a point in 3D space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DPoint"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DPoint"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DPoint",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dpoint"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVector": {
      "abstract": [
        {
          "text": "A structure that represents a vector in 3D space, in degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DVector"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DVector"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DVector",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dvector"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVectorOrientation": {
      "abstract": [
        {
          "text": "A structure that represents two orthogonal vectors that describe the orientation of the listener in 3D space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DVectorOrientation"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVectorOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DVectorOrientation"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DVectorOrientation",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dvectororientation"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentDistanceAttenuationParameters": {
      "abstract": [
        {
          "text": "An object that specifies the amount of attenuation distance, the gradual loss in audio intensity, and other characteristics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentDistanceAttenuationParameters"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentDistanceAttenuationParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentDistanceAttenuationParameters"
        }
      ],
      "role": "symbol",
      "title": "AVAudioEnvironmentDistanceAttenuationParameters",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentdistanceattenuationparameters"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode": {
      "abstract": [
        {
          "text": "An object that simulates a 3D audio environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentNode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentNode"
        }
      ],
      "role": "symbol",
      "title": "AVAudioEnvironmentNode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentnode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentOutputType": {
      "abstract": [
        {
          "text": "The output types for using with the automatic 3D mixing rendering algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentOutputType"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentOutputType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentOutputType"
        }
      ],
      "role": "symbol",
      "title": "AVAudioEnvironmentOutputType",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentoutputtype"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentReverbParameters": {
      "abstract": [
        {
          "text": "A class that encapsulates the parameters that you use to control the reverb of the environment node class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentReverbParameters"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentReverbParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentReverbParameters"
        }
      ],
      "role": "symbol",
      "title": "AVAudioEnvironmentReverbParameters",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentreverbparameters"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Spatial-audio",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentDistanceAttenuationParameters",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentReverbParameters",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DPoint",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVectorOrientation",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DAngularOrientation",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingSourceMode",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentOutputType",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingPointSourceInHeadMode",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVector"
      ],
      "title": "Spatial audio"
    }
  ],
  "topicSections": [
    {
      "anchor": "Rendering-Algorithms",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/auto",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/equalPowerPanning",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/HRTF",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/HRTFHQ",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/soundField",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/sphericalHead",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/stereoPassThrough"
      ],
      "title": "Rendering Algorithms"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudio3DMixingRenderingAlgorithm"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Rendering-Algorithms",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/auto",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/equalPowerPanning",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/HRTF",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/HRTFHQ",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/soundField",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/sphericalHead",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm/stereoPassThrough"
              ],
              "title": "Rendering Algorithms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Spatial-audio",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentDistanceAttenuationParameters",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentReverbParameters",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DPoint",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVectorOrientation",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DAngularOrientation",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingSourceMode",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentOutputType",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingPointSourceInHeadMode",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVector"
              ],
              "title": "Spatial audio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAudio3DMixingRenderingAlgorithm"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingSourceMode/title",
          "value": "AVAudio3DMixingSourceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingSourceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingSourceMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing/title",
          "value": "AVAudio3DMixing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1HRTF/title",
          "value": "AVAudio3DMixingRenderingAlgorithmHRTF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1HRTF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithmHRTF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DVectorOrientation/title",
          "value": "AVAudio3DVectorOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DVectorOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DVectorOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DVectorOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DVectorOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1auto/title",
          "value": "AVAudio3DMixingRenderingAlgorithmAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1auto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithmAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DVector/title",
          "value": "AVAudio3DVector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DVector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DVector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DVector/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DVector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DPoint/title",
          "value": "AVAudio3DPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DPoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingPointSourceInHeadMode/title",
          "value": "AVAudio3DMixingPointSourceInHeadMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingPointSourceInHeadMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingPointSourceInHeadMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingPointSourceInHeadMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingPointSourceInHeadMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1equalPowerPanning/title",
          "value": "AVAudio3DMixingRenderingAlgorithmEqualPowerPanning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1equalPowerPanning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithmEqualPowerPanning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentOutputType/title",
          "value": "AVAudioEnvironmentOutputType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentOutputType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentOutputType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DAngularOrientation/title",
          "value": "AVAudio3DAngularOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DAngularOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DAngularOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DAngularOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DAngularOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentDistanceAttenuationParameters/title",
          "value": "AVAudioEnvironmentDistanceAttenuationParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentDistanceAttenuationParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentDistanceAttenuationParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentDistanceAttenuationParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentDistanceAttenuationParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode/title",
          "value": "AVAudioEnvironmentNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1HRTFHQ/title",
          "value": "AVAudio3DMixingRenderingAlgorithmHRTFHQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1HRTFHQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithmHRTFHQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1soundField/title",
          "value": "AVAudio3DMixingRenderingAlgorithmSoundField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1soundField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithmSoundField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1stereoPassThrough/title",
          "value": "AVAudio3DMixingRenderingAlgorithmStereoPassThrough"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1stereoPassThrough/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithmStereoPassThrough"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1sphericalHead/title",
          "value": "AVAudio3DMixingRenderingAlgorithmSphericalHead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm~1sphericalHead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithmSphericalHead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentReverbParameters/title",
          "value": "AVAudioEnvironmentReverbParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentReverbParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentReverbParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentReverbParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentReverbParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm/title",
          "value": "AVAudio3DMixingRenderingAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithm"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
