{
  "abstract": [
    {
      "text": "An audio unit type that represents a music effect.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMusicEffect"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@AVAudioUnitTypeMusicEffect",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVAudioUnitTypeMusicEffect"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioUnitTypeMusicEffect"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "AVAudioUnitTypeMusicEffect"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeMusicEffect"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeEffect": {
      "abstract": [
        {
          "text": "An audio unit type that represents an effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeEffect"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypeEffect",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypeeffect"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeFormatConverter": {
      "abstract": [
        {
          "text": "An audio unit type that represents a format converter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeFormatConverter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeFormatConverter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeFormatConverter"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypeFormatConverter",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypeformatconverter"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeGenerator": {
      "abstract": [
        {
          "text": "An audio unit type that represents a generator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeGenerator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeGenerator"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypeGenerator",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypegenerator"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMIDIProcessor": {
      "abstract": [
        {
          "text": "An audio unit type that represents a MIDI processor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeMIDIProcessor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMIDIProcessor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeMIDIProcessor"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypeMIDIProcessor",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypemidiprocessor"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMixer": {
      "abstract": [
        {
          "text": "An audio unit type that represents a mixer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeMixer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMixer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeMixer"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypeMixer",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypemixer"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMusicDevice": {
      "abstract": [
        {
          "text": "An audio unit type that represents a music device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeMusicDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMusicDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeMusicDevice"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypeMusicDevice",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypemusicdevice"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMusicEffect": {
      "abstract": [
        {
          "text": "An audio unit type that represents a music effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeMusicEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMusicEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeMusicEffect"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypeMusicEffect",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypemusiceffect"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeOfflineEffect": {
      "abstract": [
        {
          "text": "An audio unit type that represents an offline effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeOfflineEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeOfflineEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeOfflineEffect"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypeOfflineEffect",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypeofflineeffect"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeOutput": {
      "abstract": [
        {
          "text": "An audio unit type that represents an output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypeOutput"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypeOutput",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypeoutput"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypePanner": {
      "abstract": [
        {
          "text": "An audio unit type that represents a panner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypePanner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypePanner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitTypePanner"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitTypePanner",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounittypepanner"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-unit-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeOutput",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMusicDevice",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeFormatConverter",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeEffect",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMixer",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypePanner",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeGenerator",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeOfflineEffect",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMIDIProcessor"
      ],
      "title": "Audio unit types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioUnitTypeMusicEffect"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeMusicEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-unit-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeOutput",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMusicDevice",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeFormatConverter",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeEffect",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMixer",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypePanner",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeGenerator",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeOfflineEffect",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitTypeMIDIProcessor"
              ],
              "title": "Audio unit types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAudioUnitTypeMusicEffect"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeOutput/title",
          "value": "AVAudioUnitTypeOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeMusicDevice/title",
          "value": "AVAudioUnitTypeMusicDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeMusicDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeMusicDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeMIDIProcessor/title",
          "value": "AVAudioUnitTypeMIDIProcessor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeMIDIProcessor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeMIDIProcessor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypePanner/title",
          "value": "AVAudioUnitTypePanner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypePanner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypePanner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeMusicEffect/title",
          "value": "AVAudioUnitTypeMusicEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeMusicEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeMusicEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeGenerator/title",
          "value": "AVAudioUnitTypeGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeMixer/title",
          "value": "AVAudioUnitTypeMixer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeMixer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeMixer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeOfflineEffect/title",
          "value": "AVAudioUnitTypeOfflineEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeOfflineEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeOfflineEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeEffect/title",
          "value": "AVAudioUnitTypeEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeFormatConverter/title",
          "value": "AVAudioUnitTypeFormatConverter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitTypeFormatConverter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitTypeFormatConverter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiounittypemusiceffect"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiounittypemusiceffect"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
