{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitGenerator"},"kind":"symbol","abstract":[{"text":"An object that generates audio output.","type":"text"}],"variants":[{"paths":["/documentation/avfaudio/avaudiounitgenerator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avfaudio/avaudiounitgenerator"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfaudio/documentation/AVFAudio"]]},"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixing","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioStereoMixing","doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"kind":"relationships","type":"conformsTo"}],"topicSections":[{"title":"Creating an audio unit generator","identifiers":["doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitGenerator/init(audioComponentDescription:)"],"anchor":"Creating-an-audio-unit-generator"},{"title":"Getting and setting the bypass status","identifiers":["doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitGenerator/bypass"],"anchor":"Getting-and-setting-the-bypass-status"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVAudioUnitGenerator","kind":"identifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"},{"content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A generator represents an "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/AudioToolbox/AudioUnit"},{"type":"text","text":" of type "},{"type":"codeVoice","code":"kAudioUnitType_Generator"},{"type":"text","text":" or "},{"type":"codeVoice","code":"kAudioUnitType_RemoteGenerator"},{"type":"text","text":". A generator has no audio input, but produces audio output. An example is a tone generator."}]}],"kind":"content"}],"metadata":{"symbolKind":"class","modules":[{"name":"AVFAudio"}],"platforms":[{"beta":false,"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"8.0"},{"beta":false,"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"8.0"},{"beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"13.1"},{"beta":false,"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"10.10"},{"beta":false,"name":"tvOS","deprecated":false,"unavailable":false,"introducedAt":"9.0"},{"beta":false,"name":"visionOS","deprecated":false,"unavailable":false,"introducedAt":"1.0"}],"title":"AVAudioUnitGenerator","navigatorTitle":[{"text":"AVAudioUnitGenerator","kind":"identifier"}],"roleHeading":"Class","role":"symbol","externalID":"c:objc(cs)AVAudioUnitGenerator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVAudioUnitGenerator","kind":"identifier"}]},"references":{"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"url":"/documentation/Swift/CustomDebugStringConvertible","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","title":"CustomDebugStringConvertible","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomDebugStringConvertible"}],"abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}],"role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"type":"topic","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"symbol","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSObjectProtocol"}],"url":"/documentation/objectivec/nsobjectprotocol"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"title":"CustomStringConvertible","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomStringConvertible","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A type with a customized textual representation.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","url":"/documentation/Swift/CustomStringConvertible","type":"topic","role":"symbol"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitGenerator/bypass":{"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitGenerator/bypass","kind":"symbol","abstract":[{"type":"text","text":"The bypass state of the audio unit."}],"type":"topic","title":"bypass","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bypass"}],"url":"/documentation/avfaudio/avaudiounitgenerator/bypass","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bypass","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitGenerator/init(audioComponentDescription:)":{"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitGenerator/init(audioComponentDescription:)","kind":"symbol","abstract":[{"type":"text","text":"Creates a generator audio unit with the specified description."}],"type":"topic","title":"init(audioComponentDescription:)","role":"symbol","navigatorTitle":[{"text":"initWithAudioComponentDescription:","kind":"identifier"}],"url":"/documentation/avfaudio/avaudiounitgenerator/init(audiocomponentdescription:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"audioComponentDescription"},{"kind":"text","text":": "},{"text":"AudioComponentDescription","kind":"typeIdentifier","preciseIdentifier":"c:@S@AudioComponentDescription"},{"text":")","kind":"text"}]},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitGenerator":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVAudioUnitGenerator"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVAudioUnitGenerator"}],"type":"topic","title":"AVAudioUnitGenerator","url":"/documentation/avfaudio/avaudiounitgenerator","abstract":[{"type":"text","text":"An object that generates audio output."}],"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitGenerator"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVAudio3DMixing"}],"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AVAudio3DMixing"}],"abstract":[{"type":"text","text":"A collection of properties that define 3D mixing properties."}],"url":"/documentation/avfaudio/avaudio3dmixing","title":"AVAudio3DMixing"},"doc://com.apple.documentation/documentation/AudioToolbox/AudioUnit":{"role":"symbol","url":"/documentation/AudioToolbox/AudioUnit","kind":"symbol","abstract":[{"text":"The data type for a plug-in component that provides audio processing or audio data generation.","type":"text"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioUnit","kind":"identifier"},{"text":" = ","kind":"text"},{"text":"AudioComponentInstance","preciseIdentifier":"c:@T@AudioComponentInstance","kind":"typeIdentifier"}],"type":"topic","identifier":"doc://com.apple.documentation/documentation/AudioToolbox/AudioUnit","title":"AudioUnit"},"doc://com.apple.avfaudio/documentation/AVFAudio":{"url":"/documentation/avfaudio","kind":"symbol","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio","title":"AVFAudio","type":"topic","abstract":[{"text":"Play, record, and process audio; configure your app’s system audio behavior.","type":"text"}],"role":"collection"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit":{"role":"symbol","navigatorTitle":[{"text":"AVAudioUnit","kind":"identifier"}],"abstract":[{"text":"A subclass of the audio node class that, processes audio either in real time or nonreal time, depending on the type of the audio unit.","type":"text"}],"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit","kind":"symbol","title":"AVAudioUnit","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVAudioUnit","kind":"identifier"}],"type":"topic","url":"/documentation/avfaudio/avaudiounit"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixing":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVAudioMixing"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AVAudioMixing"}],"type":"topic","title":"AVAudioMixing","url":"/documentation/avfaudio/avaudiomixing","abstract":[{"text":"A collection of properties that are applicable to the input bus of a mixer node.","type":"text"}],"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixing"},"doc://com.externally.resolved.symbol/s:SQ":{"identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Equatable"}],"url":"/documentation/Swift/Equatable","type":"topic","kind":"symbol","abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"title":"Equatable","role":"symbol"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"url":"/documentation/Swift/CVarArg","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","title":"CVarArg","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"abstract":[{"text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.","type":"text"}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","kind":"technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioStereoMixing":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVAudioStereoMixing"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVAudioStereoMixing"}],"type":"topic","title":"AVAudioStereoMixing","url":"/documentation/avfaudio/avaudiostereomixing","abstract":[{"type":"text","text":"A protocol that defines stereo mixing properties a mixer uses."}],"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioStereoMixing"},"doc://com.externally.resolved.symbol/s:SH":{"identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SQ","kind":"typeIdentifier","text":"Equatable"}],"url":"/documentation/Swift/Hashable","type":"topic","kind":"symbol","abstract":[{"text":"A type that can be hashed into a `Hasher` to produce an integer hash value.","type":"text"}],"title":"Hashable","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS","introducedAt":"8.0"},{"deprecated":false,"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"8.0"},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.1"},{"deprecated":false,"unavailable":false,"name":"macOS","beta":false,"introducedAt":"10.10"},{"deprecated":false,"unavailable":false,"name":"tvOS","beta":false,"introducedAt":"9.0"},{"name":"visionOS","deprecated":false,"beta":false,"introducedAt":"1.0","unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Class","path":"/metadata/roleHeading","op":"replace"},{"value":"AVAudioUnitGenerator","path":"/metadata/title","op":"replace"},{"value":"class","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"AVAudioUnitGenerator","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AVAudioUnitGenerator"}],"path":"/metadata/navigatorTitle","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfaudio/documentation/AVFAudio"]]},"path":"/hierarchy","op":"replace"},{"value":[{"title":"Creating an audio unit generator","identifiers":["doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitGenerator/init(audioComponentDescription:)"],"anchor":"Creating-an-audio-unit-generator"},{"title":"Getting and setting the bypass status","identifiers":["doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitGenerator/bypass"],"anchor":"Getting-and-setting-the-bypass-status"}],"path":"/topicSections","op":"replace"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixing"]}],"path":"/relationshipsSections","op":"replace"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVAudioUnitGenerator","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"AVAudioUnit","kind":"typeIdentifier","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnit","preciseIdentifier":"c:objc(cs)AVAudioUnit"}]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","op":"replace","value":"NSObject"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitGenerator~1bypass/title","op":"replace","value":"bypass"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitGenerator~1bypass/fragments","op":"replace","value":[{"kind":"identifier","text":"bypass"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitGenerator~1init(audioComponentDescription:)/title","op":"replace","value":"initWithAudioComponentDescription:"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitGenerator~1init(audioComponentDescription:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithAudioComponentDescription:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitGenerator/title","op":"replace","value":"AVAudioUnitGenerator"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitGenerator/fragments","op":"replace","value":[{"text":"AVAudioUnitGenerator","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitGenerator/navigatorTitle","op":"replace","value":[{"text":"AVAudioUnitGenerator","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing/title","op":"replace","value":"AVAudio3DMixing"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing/fragments","op":"replace","value":[{"text":"AVAudio3DMixing","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing/navigatorTitle","op":"replace","value":[{"text":"AVAudio3DMixing","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AudioUnit/fragments","op":"replace","value":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioComponentInstance","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioComponentInstance"},{"text":" ","kind":"text"},{"text":"AudioUnit","kind":"identifier"},{"text":";","kind":"text"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit/title","op":"replace","value":"AVAudioUnit"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit/fragments","op":"replace","value":[{"text":"AVAudioUnit","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnit/navigatorTitle","op":"replace","value":[{"text":"AVAudioUnit","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioMixing/title","op":"replace","value":"AVAudioMixing"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioMixing/fragments","op":"replace","value":[{"kind":"identifier","text":"AVAudioMixing"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioMixing/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AVAudioMixing"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioStereoMixing/title","op":"replace","value":"AVAudioStereoMixing"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioStereoMixing/fragments","op":"replace","value":[{"kind":"identifier","text":"AVAudioStereoMixing"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioStereoMixing/navigatorTitle","op":"replace","value":[{"text":"AVAudioStereoMixing","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}