{
  "abstract": [
    {
      "text": "A protocol that defines the methods to respond to audio recording events and encoding errors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)AVAudioRecorderDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVAudioRecorderDelegate"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioRecorderDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "AVAudioRecorderDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioRecorderDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s8SendableP",
              "text": "Sendable"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorder/delegate": {
      "abstract": [
        {
          "text": "The delegate object for the audio recorder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVAudioRecorderDelegate",
          "text": "AVAudioRecorderDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorder/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiorecorder/delegate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate": {
      "abstract": [
        {
          "text": "A protocol that defines the methods to respond to audio recording events and encoding errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioRecorderDelegate"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioRecorderDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVAudioRecorderDelegate",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiorecorderdelegate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderBeginInterruption(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the system interrupted the audio recording.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioRecorderBeginInterruption"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioRecorder",
          "text": "AVAudioRecorder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderBeginInterruption(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audioRecorderBeginInterruption:"
        }
      ],
      "role": "symbol",
      "title": "audioRecorderBeginInterruption(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiorecorderdelegate/audiorecorderbegininterruption(_:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderDidFinishRecording(_:successfully:)": {
      "abstract": [
        {
          "text": "Tells the delegate when recording stops or finishes due to reaching its time limit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioRecorderDidFinishRecording"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioRecorder",
          "text": "AVAudioRecorder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "successfully"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderDidFinishRecording(_:successfully:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audioRecorderDidFinishRecording:successfully:"
        }
      ],
      "role": "symbol",
      "title": "audioRecorderDidFinishRecording(_:successfully:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiorecorderdelegate/audiorecorderdidfinishrecording(_:successfully:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEncodeErrorDidOccur(_:error:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the audio recorder encountered an encoding error during recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioRecorderEncodeErrorDidOccur"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioRecorder",
          "text": "AVAudioRecorder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEncodeErrorDidOccur(_:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audioRecorderEncodeErrorDidOccur:error:"
        }
      ],
      "role": "symbol",
      "title": "audioRecorderEncodeErrorDidOccur(_:error:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiorecorderdelegate/audiorecorderencodeerrordidoccur(_:error:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the audio session interruption ended.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioRecorderEndInterruption"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioRecorder",
          "text": "AVAudioRecorder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audioRecorderEndInterruption:"
        }
      ],
      "role": "symbol",
      "title": "audioRecorderEndInterruption(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiorecorderdelegate/audiorecorderendinterruption(_:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:withFlags:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the audio session interruption ended with flags.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioRecorderEndInterruption"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioRecorder",
          "text": "AVAudioRecorder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:withFlags:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audioRecorderEndInterruption:withFlags:"
        }
      ],
      "role": "symbol",
      "title": "audioRecorderEndInterruption(_:withFlags:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiorecorderdelegate/audiorecorderendinterruption(_:withflags:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:withOptions:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the audio session interruption ended with options.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioRecorderEndInterruption"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioRecorder",
          "text": "AVAudioRecorder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:withOptions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audioRecorderEndInterruption:withOptions:"
        }
      ],
      "role": "symbol",
      "title": "audioRecorderEndInterruption(_:withOptions:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiorecorderdelegate/audiorecorderendinterruption(_:withoptions:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-recorder-events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorder/delegate"
      ],
      "title": "Responding to recorder events"
    }
  ],
  "topicSections": [
    {
      "anchor": "Responding-to-Recording-Completion",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderDidFinishRecording(_:successfully:)"
      ],
      "title": "Responding to Recording Completion"
    },
    {
      "anchor": "Responding-to-Audio-Encoding-Errors",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEncodeErrorDidOccur(_:error:)"
      ],
      "title": "Responding to Audio Encoding Errors"
    },
    {
      "anchor": "Responding-to-Audio-Interruptions",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderBeginInterruption(_:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:withOptions:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:withFlags:)"
      ],
      "title": "Responding to Audio Interruptions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioRecorderDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioRecorderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioRecorderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Responding-to-Recording-Completion",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderDidFinishRecording(_:successfully:)"
              ],
              "title": "Responding to Recording Completion"
            },
            {
              "anchor": "Responding-to-Audio-Encoding-Errors",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEncodeErrorDidOccur(_:error:)"
              ],
              "title": "Responding to Audio Encoding Errors"
            },
            {
              "anchor": "Responding-to-Audio-Interruptions",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderBeginInterruption(_:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:withOptions:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:withFlags:)"
              ],
              "title": "Responding to Audio Interruptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-recorder-events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorder/delegate"
              ],
              "title": "Responding to recorder events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAudioRecorderDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderEndInterruption(_:withOptions:)/title",
          "value": "audioRecorderEndInterruption:withOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderEndInterruption(_:withOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "audioRecorderEndInterruption:withOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderEndInterruption(_:withFlags:)/title",
          "value": "audioRecorderEndInterruption:withFlags:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderEndInterruption(_:withFlags:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "audioRecorderEndInterruption:withFlags:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderBeginInterruption(_:)/title",
          "value": "audioRecorderBeginInterruption:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderBeginInterruption(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "audioRecorderBeginInterruption:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderEndInterruption(_:)/title",
          "value": "audioRecorderEndInterruption:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderEndInterruption(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "audioRecorderEndInterruption:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderDidFinishRecording(_:successfully:)/title",
          "value": "audioRecorderDidFinishRecording:successfully:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderDidFinishRecording(_:successfully:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "audioRecorderDidFinishRecording:successfully:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate/title",
          "value": "AVAudioRecorderDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioRecorderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioRecorderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorder~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorder~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderEncodeErrorDidOccur(_:error:)/title",
          "value": "audioRecorderEncodeErrorDidOccur:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderEncodeErrorDidOccur(_:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "audioRecorderEncodeErrorDidOccur:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiorecorderdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiorecorderdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
