{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitMIDIInstrument_MixingConformance"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@AVAudioUnitMIDIInstrument_MixingConformance",
    "fragments": [
      {
        "kind": "identifier",
        "text": "AVAudioUnitMIDIInstrument_MixingConformance"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioUnitMIDIInstrument_MixingConformance"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Macro",
    "symbolKind": "macro",
    "title": "AVAudioUnitMIDIInstrument_MixingConformance"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "#define"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioUnitMIDIInstrument_MixingConformance"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAS_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAS_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAS_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAS_EXPORT",
      "type": "topic",
      "url": "/documentation/avfaudio/avas_export"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOENGINE_HAVE_AUAUDIOUNIT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOENGINE_HAVE_AUAUDIOUNIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
        }
      ],
      "role": "symbol",
      "title": "AVAUDIOENGINE_HAVE_AUAUDIOUNIT",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioengine_have_auaudiounit"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOENGINE_HAVE_MUSICPLAYER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAUDIOENGINE_HAVE_MUSICPLAYER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOENGINE_HAVE_MUSICPLAYER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAUDIOENGINE_HAVE_MUSICPLAYER"
        }
      ],
      "role": "symbol",
      "title": "AVAUDIOENGINE_HAVE_MUSICPLAYER",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioengine_have_musicplayer"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOFORMAT_HAVE_CMFORMATDESCRIPTION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAUDIOFORMAT_HAVE_CMFORMATDESCRIPTION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOFORMAT_HAVE_CMFORMATDESCRIPTION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAUDIOFORMAT_HAVE_CMFORMATDESCRIPTION"
        }
      ],
      "role": "symbol",
      "title": "AVAUDIOFORMAT_HAVE_CMFORMATDESCRIPTION",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioformat_have_cmformatdescription"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOIONODE_HAVE_AUDIOUNIT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAUDIOIONODE_HAVE_AUDIOUNIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOIONODE_HAVE_AUDIOUNIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAUDIOIONODE_HAVE_AUDIOUNIT"
        }
      ],
      "role": "symbol",
      "title": "AVAUDIOIONODE_HAVE_AUDIOUNIT",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioionode_have_audiounit"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIONODE_HAVE_AUAUDIOUNIT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAUDIONODE_HAVE_AUAUDIOUNIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIONODE_HAVE_AUAUDIOUNIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAUDIONODE_HAVE_AUAUDIOUNIT"
        }
      ],
      "role": "symbol",
      "title": "AVAUDIONODE_HAVE_AUAUDIOUNIT",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudionode_have_auaudiounit"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOUNITCOMPONENT_HAVE_AUDIOCOMPONENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAUDIOUNITCOMPONENT_HAVE_AUDIOCOMPONENT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOUNITCOMPONENT_HAVE_AUDIOCOMPONENT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAUDIOUNITCOMPONENT_HAVE_AUDIOCOMPONENT"
        }
      ],
      "role": "symbol",
      "title": "AVAUDIOUNITCOMPONENT_HAVE_AUDIOCOMPONENT",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent_have_audiocomponent"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOUNIT_HAVE_AUDIOUNIT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAUDIOUNIT_HAVE_AUDIOUNIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOUNIT_HAVE_AUDIOUNIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAUDIOUNIT_HAVE_AUDIOUNIT"
        }
      ],
      "role": "symbol",
      "title": "AVAUDIOUNIT_HAVE_AUDIOUNIT",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounit_have_audiounit"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAudioApplication_h"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioApplication_h",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioapplication_h"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitMIDIInstrument_MixingConformance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitMIDIInstrument_MixingConformance"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitMIDIInstrument_MixingConformance",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioUnitMIDIInstrument_MixingConformance",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitmidiinstrument_mixingconformance"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVLinearPCMIsNonInterleavedKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVLinearPCMIsNonInterleavedKey"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVLinearPCMIsNonInterleavedKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVLinearPCMIsNonInterleavedKey",
      "type": "topic",
      "url": "/documentation/avfaudio/avlinearpcmisnoninterleavedkey"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeeechSynthesisProvider_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVSpeeechSynthesisProvider_h"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeeechSynthesisProvider_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVSpeeechSynthesisProvider_h",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeeechsynthesisprovider_h"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AudioSession_AVAudioRoutingArbiter_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioSession_AVAudioRoutingArbiter_h"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AudioSession_AVAudioRoutingArbiter_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioSession_AVAudioRoutingArbiter_h",
      "type": "topic",
      "url": "/documentation/avfaudio/audiosession_avaudioroutingarbiter_h"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AudioSession_AVAudioSessionRoute_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioSession_AVAudioSessionRoute_h"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AudioSession_AVAudioSessionRoute_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioSession_AVAudioSessionRoute_h",
      "type": "topic",
      "url": "/documentation/avfaudio/audiosession_avaudiosessionroute_h"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AudioSession_AVAudioSessionTypes_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioSession_AVAudioSessionTypes_h"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AudioSession_AVAudioSessionTypes_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioSession_AVAudioSessionTypes_h",
      "type": "topic",
      "url": "/documentation/avfaudio/audiosession_avaudiosessiontypes_h"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AudioSession_AVAudioSession_Deprecated_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioSession_AVAudioSession_Deprecated_h"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AudioSession_AVAudioSession_Deprecated_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioSession_AVAudioSession_Deprecated_h",
      "type": "topic",
      "url": "/documentation/avfaudio/audiosession_avaudiosession_deprecated_h"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Macros",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAS_EXPORT",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOENGINE_HAVE_AUAUDIOUNIT",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOENGINE_HAVE_MUSICPLAYER",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOFORMAT_HAVE_CMFORMATDESCRIPTION",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOIONODE_HAVE_AUDIOUNIT",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIONODE_HAVE_AUAUDIOUNIT",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOUNITCOMPONENT_HAVE_AUDIOCOMPONENT",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAUDIOUNIT_HAVE_AUDIOUNIT",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication_h",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVLinearPCMIsNonInterleavedKey",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeeechSynthesisProvider_h",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AudioSession_AVAudioRoutingArbiter_h",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AudioSession_AVAudioSessionRoute_h",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AudioSession_AVAudioSessionTypes_h",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AudioSession_AVAudioSession_Deprecated_h"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAUDIOUNIT_HAVE_AUDIOUNIT/title",
          "value": "AVAUDIOUNIT_HAVE_AUDIOUNIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAUDIOUNIT_HAVE_AUDIOUNIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAUDIOUNIT_HAVE_AUDIOUNIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAUDIOIONODE_HAVE_AUDIOUNIT/title",
          "value": "AVAUDIOIONODE_HAVE_AUDIOUNIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAUDIOIONODE_HAVE_AUDIOUNIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAUDIOIONODE_HAVE_AUDIOUNIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAUDIOENGINE_HAVE_MUSICPLAYER/title",
          "value": "AVAUDIOENGINE_HAVE_MUSICPLAYER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAUDIOENGINE_HAVE_MUSICPLAYER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAUDIOENGINE_HAVE_MUSICPLAYER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAUDIOUNITCOMPONENT_HAVE_AUDIOCOMPONENT/title",
          "value": "AVAUDIOUNITCOMPONENT_HAVE_AUDIOCOMPONENT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAUDIOUNITCOMPONENT_HAVE_AUDIOCOMPONENT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAUDIOUNITCOMPONENT_HAVE_AUDIOCOMPONENT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAUDIOFORMAT_HAVE_CMFORMATDESCRIPTION/title",
          "value": "AVAUDIOFORMAT_HAVE_CMFORMATDESCRIPTION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAUDIOFORMAT_HAVE_CMFORMATDESCRIPTION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAUDIOFORMAT_HAVE_CMFORMATDESCRIPTION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAUDIOENGINE_HAVE_AUAUDIOUNIT/title",
          "value": "AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAUDIOENGINE_HAVE_AUAUDIOUNIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAUDIONODE_HAVE_AUAUDIOUNIT/title",
          "value": "AVAUDIONODE_HAVE_AUAUDIOUNIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAUDIONODE_HAVE_AUAUDIOUNIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAUDIONODE_HAVE_AUAUDIOUNIT"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiounitmidiinstrument_mixingconformance"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
