{
  "abstract": [
    {
      "text": "Constants that represent preset audio distortions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVAudioUnitDistortionPreset",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVAudioUnitDistortionPreset"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioUnitDistortionPreset"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AVAudioUnitDistortionPreset"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPreset"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortion/loadFactoryPreset(_:)": {
      "abstract": [
        {
          "text": "Configures the audio distortion unit by loading a distortion preset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadFactoryPreset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioUnitDistortionPreset",
          "text": "AVAudioUnitDistortionPreset"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortion/loadFactoryPreset(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadFactoryPreset:"
        }
      ],
      "role": "symbol",
      "title": "loadFactoryPreset(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortion/loadfactorypreset(_:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset": {
      "abstract": [
        {
          "text": "Constants that represent preset audio distortions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPreset"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPreset"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/drumsBitBrush": {
      "abstract": [
        {
          "text": "A preset that represents a bit brush drums distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drumsBitBrush"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/drumsBitBrush",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetDrumsBitBrush"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.drumsBitBrush",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/drumsbitbrush"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/drumsBufferBeats": {
      "abstract": [
        {
          "text": "A preset that represents a buffer beat drums distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drumsBufferBeats"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/drumsBufferBeats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetDrumsBufferBeats"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.drumsBufferBeats",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/drumsbufferbeats"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/drumsLoFi": {
      "abstract": [
        {
          "text": "A preset that represents a low fidelity drums distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drumsLoFi"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/drumsLoFi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetDrumsLoFi"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.drumsLoFi",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/drumslofi"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/init(rawvalue:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiBrokenSpeaker": {
      "abstract": [
        {
          "text": "A preset that represents a broken speaker distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiBrokenSpeaker"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiBrokenSpeaker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetMultiBrokenSpeaker"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.multiBrokenSpeaker",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/multibrokenspeaker"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiCellphoneConcert": {
      "abstract": [
        {
          "text": "A preset that represents a cellphone concert distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiCellphoneConcert"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiCellphoneConcert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetMultiCellphoneConcert"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.multiCellphoneConcert",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/multicellphoneconcert"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDecimated1": {
      "abstract": [
        {
          "text": "A preset that represents a variant of the decimated distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiDecimated1"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDecimated1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetMultiDecimated1"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.multiDecimated1",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/multidecimated1"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDecimated2": {
      "abstract": [
        {
          "text": "A preset that represents a variant of the decimated distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiDecimated2"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDecimated2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetMultiDecimated2"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.multiDecimated2",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/multidecimated2"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDecimated3": {
      "abstract": [
        {
          "text": "A preset that represents a variant of the decimated distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiDecimated3"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDecimated3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetMultiDecimated3"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.multiDecimated3",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/multidecimated3"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDecimated4": {
      "abstract": [
        {
          "text": "A preset that represents a variant of the decimated distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiDecimated4"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDecimated4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetMultiDecimated4"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.multiDecimated4",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/multidecimated4"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDistortedCubed": {
      "abstract": [
        {
          "text": "A preset that represents a distorted cubed distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiDistortedCubed"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDistortedCubed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetMultiDistortedCubed"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.multiDistortedCubed",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/multidistortedcubed"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDistortedFunk": {
      "abstract": [
        {
          "text": "A preset that represents a distorted funk distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiDistortedFunk"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDistortedFunk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetMultiDistortedFunk"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.multiDistortedFunk",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/multidistortedfunk"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDistortedSquared": {
      "abstract": [
        {
          "text": "A preset that represents a distorted squared distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiDistortedSquared"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDistortedSquared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetMultiDistortedSquared"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.multiDistortedSquared",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/multidistortedsquared"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEcho1": {
      "abstract": [
        {
          "text": "A preset that represents a variant of an echo distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiEcho1"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEcho1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetMultiEcho1"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.multiEcho1",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/multiecho1"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEcho2": {
      "abstract": [
        {
          "text": "A preset that represents a variant of an echo distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiEcho2"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEcho2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetMultiEcho2"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.multiEcho2",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/multiecho2"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEchoTight1": {
      "abstract": [
        {
          "text": "A preset that represents a variant of a tight echo distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiEchoTight1"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEchoTight1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetMultiEchoTight1"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.multiEchoTight1",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/multiechotight1"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEchoTight2": {
      "abstract": [
        {
          "text": "A preset that represents a variant of a tight echo distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiEchoTight2"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEchoTight2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetMultiEchoTight2"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.multiEchoTight2",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/multiechotight2"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEverythingIsBroken": {
      "abstract": [
        {
          "text": "A preset that represents an everything-is-broken distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiEverythingIsBroken"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEverythingIsBroken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetMultiEverythingIsBroken"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.multiEverythingIsBroken",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/multieverythingisbroken"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechAlienChatter": {
      "abstract": [
        {
          "text": "A preset that represents an alien chatter distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speechAlienChatter"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechAlienChatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetSpeechAlienChatter"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.speechAlienChatter",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/speechalienchatter"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechCosmicInterference": {
      "abstract": [
        {
          "text": "A preset that represents a cosmic interference distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speechCosmicInterference"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechCosmicInterference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetSpeechCosmicInterference"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.speechCosmicInterference",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/speechcosmicinterference"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechGoldenPi": {
      "abstract": [
        {
          "text": "A preset that represents a golden pi distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speechGoldenPi"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechGoldenPi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetSpeechGoldenPi"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.speechGoldenPi",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/speechgoldenpi"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechRadioTower": {
      "abstract": [
        {
          "text": "A preset that represents a radio tower distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speechRadioTower"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechRadioTower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetSpeechRadioTower"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.speechRadioTower",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/speechradiotower"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechWaves": {
      "abstract": [
        {
          "text": "A preset that represents a speech wave distortion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speechWaves"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechWaves",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitDistortionPresetSpeechWaves"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitDistortionPreset.speechWaves",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitdistortionpreset/speechwaves"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-distortion",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortion/loadFactoryPreset(_:)"
      ],
      "title": "Configuring the distortion"
    }
  ],
  "topicSections": [
    {
      "anchor": "Presets",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/drumsBitBrush",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/drumsBufferBeats",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/drumsLoFi",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiBrokenSpeaker",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiCellphoneConcert",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDecimated1",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDecimated2",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDecimated3",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDecimated4",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDistortedFunk",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDistortedCubed",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDistortedSquared",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEcho1",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEcho2",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEchoTight1",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEchoTight2",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEverythingIsBroken",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechAlienChatter",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechCosmicInterference",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechGoldenPi",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechRadioTower",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechWaves"
      ],
      "title": "Presets"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioUnitDistortionPreset"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Presets",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/drumsBitBrush",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/drumsBufferBeats",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/drumsLoFi",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiBrokenSpeaker",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiCellphoneConcert",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDecimated1",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDecimated2",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDecimated3",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDecimated4",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDistortedFunk",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDistortedCubed",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiDistortedSquared",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEcho1",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEcho2",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEchoTight1",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEchoTight2",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/multiEverythingIsBroken",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechAlienChatter",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechCosmicInterference",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechGoldenPi",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechRadioTower",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortionPreset/speechWaves"
              ],
              "title": "Presets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-distortion",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitDistortion/loadFactoryPreset(_:)"
              ],
              "title": "Configuring the distortion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAudioUnitDistortionPreset"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1speechWaves/title",
          "value": "AVAudioUnitDistortionPresetSpeechWaves"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1speechWaves/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetSpeechWaves"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortion~1loadFactoryPreset(_:)/title",
          "value": "loadFactoryPreset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortion~1loadFactoryPreset(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadFactoryPreset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset/title",
          "value": "AVAudioUnitDistortionPreset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiDistortedSquared/title",
          "value": "AVAudioUnitDistortionPresetMultiDistortedSquared"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiDistortedSquared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetMultiDistortedSquared"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiDecimated1/title",
          "value": "AVAudioUnitDistortionPresetMultiDecimated1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiDecimated1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetMultiDecimated1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1speechAlienChatter/title",
          "value": "AVAudioUnitDistortionPresetSpeechAlienChatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1speechAlienChatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetSpeechAlienChatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiDecimated2/title",
          "value": "AVAudioUnitDistortionPresetMultiDecimated2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiDecimated2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetMultiDecimated2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiEcho2/title",
          "value": "AVAudioUnitDistortionPresetMultiEcho2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiEcho2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetMultiEcho2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiEchoTight2/title",
          "value": "AVAudioUnitDistortionPresetMultiEchoTight2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiEchoTight2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetMultiEchoTight2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiBrokenSpeaker/title",
          "value": "AVAudioUnitDistortionPresetMultiBrokenSpeaker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiBrokenSpeaker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetMultiBrokenSpeaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiDecimated3/title",
          "value": "AVAudioUnitDistortionPresetMultiDecimated3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiDecimated3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetMultiDecimated3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1drumsLoFi/title",
          "value": "AVAudioUnitDistortionPresetDrumsLoFi"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1drumsLoFi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetDrumsLoFi"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiDistortedFunk/title",
          "value": "AVAudioUnitDistortionPresetMultiDistortedFunk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiDistortedFunk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetMultiDistortedFunk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiEcho1/title",
          "value": "AVAudioUnitDistortionPresetMultiEcho1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiEcho1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetMultiEcho1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiCellphoneConcert/title",
          "value": "AVAudioUnitDistortionPresetMultiCellphoneConcert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiCellphoneConcert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetMultiCellphoneConcert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiDistortedCubed/title",
          "value": "AVAudioUnitDistortionPresetMultiDistortedCubed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiDistortedCubed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetMultiDistortedCubed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1speechGoldenPi/title",
          "value": "AVAudioUnitDistortionPresetSpeechGoldenPi"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1speechGoldenPi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetSpeechGoldenPi"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiEverythingIsBroken/title",
          "value": "AVAudioUnitDistortionPresetMultiEverythingIsBroken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiEverythingIsBroken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetMultiEverythingIsBroken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiDecimated4/title",
          "value": "AVAudioUnitDistortionPresetMultiDecimated4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiDecimated4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetMultiDecimated4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1speechRadioTower/title",
          "value": "AVAudioUnitDistortionPresetSpeechRadioTower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1speechRadioTower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetSpeechRadioTower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1speechCosmicInterference/title",
          "value": "AVAudioUnitDistortionPresetSpeechCosmicInterference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1speechCosmicInterference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetSpeechCosmicInterference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1drumsBufferBeats/title",
          "value": "AVAudioUnitDistortionPresetDrumsBufferBeats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1drumsBufferBeats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetDrumsBufferBeats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1drumsBitBrush/title",
          "value": "AVAudioUnitDistortionPresetDrumsBitBrush"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1drumsBitBrush/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetDrumsBitBrush"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiEchoTight1/title",
          "value": "AVAudioUnitDistortionPresetMultiEchoTight1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitDistortionPreset~1multiEchoTight1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitDistortionPresetMultiEchoTight1"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiounitdistortionpreset"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiounitdistortionpreset"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
