{
  "abstract": [
    {
      "text": "A collection of properties that define 3D mixing properties.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)AVAudio3DMixing",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVAudio3DMixing"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudio3DMixing"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "AVAudio3DMixing"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudio3DMixing"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Only the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class implements these properties.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixing",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " protocol adopts these properties. As a result, many classes inherit this protocol by adopting ",
                  "type": "text"
                },
                {
                  "code": "AVAudioMixing",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DAngularOrientation": {
      "abstract": [
        {
          "text": "A structure that represents the angular orientation of the listener in 3D space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DAngularOrientation"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DAngularOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DAngularOrientation"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DAngularOrientation",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dangularorientation"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing": {
      "abstract": [
        {
          "text": "A collection of properties that define 3D mixing properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DMixing"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixing"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixing",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixing"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/obstruction": {
      "abstract": [
        {
          "text": "A value that simulates filtering of the direct path of sound due to an obstacle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "obstruction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/obstruction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "obstruction"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "obstruction",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixing/obstruction"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/occlusion": {
      "abstract": [
        {
          "text": "A value that simulates filtering of the direct and reverb paths of sound due to an obstacle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "occlusion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/occlusion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "occlusion"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "occlusion",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixing/occlusion"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/pointSourceInHeadMode": {
      "abstract": [
        {
          "text": "The in-head mode for a point source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointSourceInHeadMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudio3DMixingPointSourceInHeadMode",
          "text": "AVAudio3DMixingPointSourceInHeadMode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/pointSourceInHeadMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pointSourceInHeadMode"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "pointSourceInHeadMode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixing/pointsourceinheadmode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/position": {
      "abstract": [
        {
          "text": "The location of the source in the 3D environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "position"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AVAudio3DPoint",
          "text": "AVAudio3DPoint"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/position",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "position"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "position",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixing/position"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/rate": {
      "abstract": [
        {
          "text": "A value that changes the playback rate of the input signal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/rate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rate"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "rate",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixing/rate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/renderingAlgorithm": {
      "abstract": [
        {
          "text": "The type of rendering algorithm the mixer uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "renderingAlgorithm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudio3DMixingRenderingAlgorithm",
          "text": "AVAudio3DMixingRenderingAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/renderingAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "renderingAlgorithm"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "renderingAlgorithm",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixing/renderingalgorithm"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/reverbBlend": {
      "abstract": [
        {
          "text": "A value that controls the blend of dry and reverb processed audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbBlend"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/reverbBlend",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reverbBlend"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "reverbBlend",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixing/reverbblend"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/sourceMode": {
      "abstract": [
        {
          "text": "The source mode for the input bus of the audio environment node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudio3DMixingSourceMode",
          "text": "AVAudio3DMixingSourceMode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/sourceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceMode"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "sourceMode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixing/sourcemode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingPointSourceInHeadMode": {
      "abstract": [
        {
          "text": "The in-head modes for a point source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingPointSourceInHeadMode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingPointSourceInHeadMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingPointSourceInHeadMode"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingPointSourceInHeadMode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingpointsourceinheadmode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm": {
      "abstract": [
        {
          "text": "The types of rendering algorithms available per input bus of the environment node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingRenderingAlgorithm",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingSourceMode": {
      "abstract": [
        {
          "text": "The source modes for the input bus of the audio environment node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingSourceMode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingSourceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingSourceMode"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingSourceMode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingsourcemode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DPoint": {
      "abstract": [
        {
          "text": "A structure that represents a point in 3D space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DPoint"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DPoint"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DPoint",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dpoint"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVector": {
      "abstract": [
        {
          "text": "A structure that represents a vector in 3D space, in degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DVector"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DVector"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DVector",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dvector"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVectorOrientation": {
      "abstract": [
        {
          "text": "A structure that represents two orthogonal vectors that describe the orientation of the listener in 3D space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DVectorOrientation"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVectorOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DVectorOrientation"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DVectorOrientation",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dvectororientation"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentDistanceAttenuationParameters": {
      "abstract": [
        {
          "text": "An object that specifies the amount of attenuation distance, the gradual loss in audio intensity, and other characteristics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentDistanceAttenuationParameters"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentDistanceAttenuationParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentDistanceAttenuationParameters"
        }
      ],
      "role": "symbol",
      "title": "AVAudioEnvironmentDistanceAttenuationParameters",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentdistanceattenuationparameters"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode": {
      "abstract": [
        {
          "text": "An object that simulates a 3D audio environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentNode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentNode"
        }
      ],
      "role": "symbol",
      "title": "AVAudioEnvironmentNode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentnode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentOutputType": {
      "abstract": [
        {
          "text": "The output types for using with the automatic 3D mixing rendering algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentOutputType"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentOutputType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentOutputType"
        }
      ],
      "role": "symbol",
      "title": "AVAudioEnvironmentOutputType",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentoutputtype"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentReverbParameters": {
      "abstract": [
        {
          "text": "A class that encapsulates the parameters that you use to control the reverb of the environment node class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentReverbParameters"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentReverbParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentReverbParameters"
        }
      ],
      "role": "symbol",
      "title": "AVAudioEnvironmentReverbParameters",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentreverbparameters"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioInputNode": {
      "abstract": [
        {
          "text": "An object that connects to the system’s audio input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioInputNode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioInputNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioInputNode"
        }
      ],
      "role": "symbol",
      "title": "AVAudioInputNode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioinputnode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixerNode": {
      "abstract": [
        {
          "text": "An object that takes any number of inputs and converts them into a single output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioMixerNode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixerNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioMixerNode"
        }
      ],
      "role": "symbol",
      "title": "AVAudioMixerNode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiomixernode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixing": {
      "abstract": [
        {
          "text": "A collection of properties that are applicable to the input bus of a mixer node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioMixing"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioMixing"
        }
      ],
      "role": "symbol",
      "title": "AVAudioMixing",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiomixing"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixingDestination": {
      "abstract": [
        {
          "text": "An object that represents a connection to a mixer node from a node that conforms to the audio mixing protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioMixingDestination"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixingDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioMixingDestination"
        }
      ],
      "role": "symbol",
      "title": "AVAudioMixingDestination",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiomixingdestination"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioPlayerNode": {
      "abstract": [
        {
          "text": "An object for scheduling the playback of buffers or segments of audio files.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioPlayerNode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioPlayerNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioPlayerNode"
        }
      ],
      "role": "symbol",
      "title": "AVAudioPlayerNode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioplayernode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSourceNode": {
      "abstract": [
        {
          "text": "An object that supplies audio data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSourceNode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSourceNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSourceNode"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSourceNode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosourcenode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitGenerator": {
      "abstract": [
        {
          "text": "An object that generates audio output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitGenerator"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitGenerator"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitGenerator",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitgenerator"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitMIDIInstrument": {
      "abstract": [
        {
          "text": "An object that represents music devices or remote instruments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitMIDIInstrument"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitMIDIInstrument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitMIDIInstrument"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitMIDIInstrument",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitmidiinstrument"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitSampler": {
      "abstract": [
        {
          "text": "An object that you configure with one or more instrument samples, based on Apple’s Sampler audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitSampler"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitSampler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitSampler"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitSampler",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitsampler"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixing"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioInputNode",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixerNode",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixingDestination",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioPlayerNode",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSourceNode",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitGenerator",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitMIDIInstrument",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitSampler"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Spatial-audio",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentDistanceAttenuationParameters",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentReverbParameters",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DPoint",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVectorOrientation",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DAngularOrientation",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingSourceMode",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentOutputType",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingPointSourceInHeadMode",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVector"
      ],
      "title": "Spatial audio"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-3D-Mixing-Parameters",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/obstruction",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/occlusion",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/position",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/rate",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/pointSourceInHeadMode",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/reverbBlend",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/sourceMode"
      ],
      "title": "Getting the 3D Mixing Parameters"
    },
    {
      "anchor": "Getting-and-Setting-the-Rendering-Algorithm",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/renderingAlgorithm",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm"
      ],
      "title": "Getting and Setting the Rendering Algorithm"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudio3DMixing"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-3D-Mixing-Parameters",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/obstruction",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/occlusion",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/position",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/rate",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/pointSourceInHeadMode",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/reverbBlend",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/sourceMode"
              ],
              "title": "Getting the 3D Mixing Parameters"
            },
            {
              "anchor": "Getting-and-Setting-the-Rendering-Algorithm",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing/renderingAlgorithm",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm"
              ],
              "title": "Getting and Setting the Rendering Algorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixing"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Spatial-audio",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentDistanceAttenuationParameters",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentReverbParameters",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DPoint",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVectorOrientation",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DAngularOrientation",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingSourceMode",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentOutputType",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingPointSourceInHeadMode",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVector"
              ],
              "title": "Spatial audio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAudio3DMixing"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentOutputType/title",
          "value": "AVAudioEnvironmentOutputType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentOutputType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentOutputType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm/title",
          "value": "AVAudio3DMixingRenderingAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingPointSourceInHeadMode/title",
          "value": "AVAudio3DMixingPointSourceInHeadMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingPointSourceInHeadMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingPointSourceInHeadMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingPointSourceInHeadMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingPointSourceInHeadMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing~1pointSourceInHeadMode/title",
          "value": "pointSourceInHeadMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing~1pointSourceInHeadMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pointSourceInHeadMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSourceNode/title",
          "value": "AVAudioSourceNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSourceNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSourceNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSourceNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSourceNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing~1occlusion/title",
          "value": "occlusion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing~1occlusion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "occlusion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing~1renderingAlgorithm/title",
          "value": "renderingAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing~1renderingAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "renderingAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing~1rate/title",
          "value": "rate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing~1rate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing/title",
          "value": "AVAudio3DMixing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DAngularOrientation/title",
          "value": "AVAudio3DAngularOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DAngularOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DAngularOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DAngularOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DAngularOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingSourceMode/title",
          "value": "AVAudio3DMixingSourceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingSourceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingSourceMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DVector/title",
          "value": "AVAudio3DVector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DVector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DVector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DVector/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DVector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode/title",
          "value": "AVAudioEnvironmentNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioInputNode/title",
          "value": "AVAudioInputNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioInputNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioInputNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioInputNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioInputNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing~1position/title",
          "value": "position"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing~1position/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "position"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioPlayerNode/title",
          "value": "AVAudioPlayerNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioPlayerNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioPlayerNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioPlayerNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioPlayerNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing~1obstruction/title",
          "value": "obstruction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing~1obstruction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "obstruction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing~1sourceMode/title",
          "value": "sourceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing~1sourceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioMixingDestination/title",
          "value": "AVAudioMixingDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioMixingDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioMixingDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioMixingDestination/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioMixingDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DVectorOrientation/title",
          "value": "AVAudio3DVectorOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DVectorOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DVectorOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DVectorOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DVectorOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentDistanceAttenuationParameters/title",
          "value": "AVAudioEnvironmentDistanceAttenuationParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentDistanceAttenuationParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentDistanceAttenuationParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentDistanceAttenuationParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentDistanceAttenuationParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentReverbParameters/title",
          "value": "AVAudioEnvironmentReverbParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentReverbParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentReverbParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentReverbParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentReverbParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitSampler/title",
          "value": "AVAudioUnitSampler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitSampler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitSampler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitSampler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitSampler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitGenerator/title",
          "value": "AVAudioUnitGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioMixerNode/title",
          "value": "AVAudioMixerNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioMixerNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioMixerNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioMixerNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioMixerNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DPoint/title",
          "value": "AVAudio3DPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DPoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitMIDIInstrument/title",
          "value": "AVAudioUnitMIDIInstrument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitMIDIInstrument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitMIDIInstrument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitMIDIInstrument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitMIDIInstrument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioMixing/title",
          "value": "AVAudioMixing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioMixing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioMixing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioMixing/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioMixing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing~1reverbBlend/title",
          "value": "reverbBlend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing~1reverbBlend/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reverbBlend"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudio3dmixing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudio3dmixing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
