{
  "abstract": [
    {
      "text": "Filter types available to use with the filter type property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVAudioUnitEQFilterType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVAudioUnitEQFilterType"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioUnitEQFilterType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AVAudioUnitEQFilterType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioUnitEQFilterType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType": {
      "abstract": [
        {
          "text": "Filter types available to use with the filter type property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitEQFilterType"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitEQFilterType"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitEQFilterType",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiouniteqfiltertype"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/bandPass": {
      "abstract": [
        {
          "text": "A type that represents a bandpass filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bandPass"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/bandPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitEQFilterTypeBandPass"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitEQFilterType.bandPass",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiouniteqfiltertype/bandpass"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/bandStop": {
      "abstract": [
        {
          "text": "A type that represents a band-stop filter, also known as a notch filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bandStop"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/bandStop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitEQFilterTypeBandStop"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitEQFilterType.bandStop",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiouniteqfiltertype/bandstop"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/highPass": {
      "abstract": [
        {
          "text": "A type that represents a simple Butterworth second-order high-pass filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highPass"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/highPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitEQFilterTypeHighPass"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitEQFilterType.highPass",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiouniteqfiltertype/highpass"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/highShelf": {
      "abstract": [
        {
          "text": "A type that represents a high-shelf filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highShelf"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/highShelf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitEQFilterTypeHighShelf"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitEQFilterType.highShelf",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiouniteqfiltertype/highshelf"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiouniteqfiltertype/init(rawvalue:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/lowPass": {
      "abstract": [
        {
          "text": "A type that represents a simple Butterworth second-order low-pass filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowPass"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/lowPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitEQFilterTypeLowPass"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitEQFilterType.lowPass",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiouniteqfiltertype/lowpass"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/lowShelf": {
      "abstract": [
        {
          "text": "A type that represents a low-shelf filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowShelf"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/lowShelf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitEQFilterTypeLowShelf"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitEQFilterType.lowShelf",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiouniteqfiltertype/lowshelf"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/parametric": {
      "abstract": [
        {
          "text": "A type that represents a parametric filter that derives from a Butterworth analog prototype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parametric"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/parametric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitEQFilterTypeParametric"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitEQFilterType.parametric",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiouniteqfiltertype/parametric"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/resonantHighPass": {
      "abstract": [
        {
          "text": "A type that represents a high-pass filter with resonance support using the bandwidth parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resonantHighPass"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/resonantHighPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitEQFilterTypeResonantHighPass"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitEQFilterType.resonantHighPass",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiouniteqfiltertype/resonanthighpass"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/resonantHighShelf": {
      "abstract": [
        {
          "text": "A type that represents a high-shelf filter with resonance support using the bandwidth parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resonantHighShelf"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/resonantHighShelf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitEQFilterTypeResonantHighShelf"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitEQFilterType.resonantHighShelf",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiouniteqfiltertype/resonanthighshelf"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/resonantLowPass": {
      "abstract": [
        {
          "text": "A type that represents a low-pass filter with resonance support using the bandwidth parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resonantLowPass"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/resonantLowPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitEQFilterTypeResonantLowPass"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitEQFilterType.resonantLowPass",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiouniteqfiltertype/resonantlowpass"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/resonantLowShelf": {
      "abstract": [
        {
          "text": "A type that represents a low-shelf filter with resonance support using the bandwidth parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resonantLowShelf"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/resonantLowShelf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitEQFilterTypeResonantLowShelf"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitEQFilterType.resonantLowShelf",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiouniteqfiltertype/resonantlowshelf"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Filter-Types",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/parametric",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/lowPass",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/highPass",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/resonantLowPass",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/resonantHighPass",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/bandPass",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/bandStop",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/lowShelf",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/highShelf",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/resonantLowShelf",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/resonantHighShelf"
      ],
      "title": "Filter Types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioUnitEQFilterType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitEQFilterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitEQFilterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Filter-Types",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/parametric",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/lowPass",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/highPass",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/resonantLowPass",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/resonantHighPass",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/bandPass",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/bandStop",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/lowShelf",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/highShelf",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/resonantLowShelf",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitEQFilterType/resonantHighShelf"
              ],
              "title": "Filter Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAudioUnitEQFilterType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1resonantHighPass/title",
          "value": "AVAudioUnitEQFilterTypeResonantHighPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1resonantHighPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitEQFilterTypeResonantHighPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1lowPass/title",
          "value": "AVAudioUnitEQFilterTypeLowPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1lowPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitEQFilterTypeLowPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1resonantLowPass/title",
          "value": "AVAudioUnitEQFilterTypeResonantLowPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1resonantLowPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitEQFilterTypeResonantLowPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1resonantHighShelf/title",
          "value": "AVAudioUnitEQFilterTypeResonantHighShelf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1resonantHighShelf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitEQFilterTypeResonantHighShelf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1lowShelf/title",
          "value": "AVAudioUnitEQFilterTypeLowShelf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1lowShelf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitEQFilterTypeLowShelf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1bandPass/title",
          "value": "AVAudioUnitEQFilterTypeBandPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1bandPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitEQFilterTypeBandPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1bandStop/title",
          "value": "AVAudioUnitEQFilterTypeBandStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1bandStop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitEQFilterTypeBandStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1highPass/title",
          "value": "AVAudioUnitEQFilterTypeHighPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1highPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitEQFilterTypeHighPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType/title",
          "value": "AVAudioUnitEQFilterType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitEQFilterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitEQFilterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1parametric/title",
          "value": "AVAudioUnitEQFilterTypeParametric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1parametric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitEQFilterTypeParametric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1resonantLowShelf/title",
          "value": "AVAudioUnitEQFilterTypeResonantLowShelf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1resonantLowShelf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitEQFilterTypeResonantLowShelf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1highShelf/title",
          "value": "AVAudioUnitEQFilterTypeHighShelf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitEQFilterType~1highShelf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitEQFilterTypeHighShelf"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiouniteqfiltertype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiouniteqfiltertype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
