{
  "abstract": [
    {
      "text": "An object that simulates a 3D audio environment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVAudioEnvironmentNode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVAudioEnvironmentNode"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioEnvironmentNode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVAudioEnvironmentNode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentNode"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "AVAudioEnvironmentNode",
              "type": "codeVoice"
            },
            {
              "text": " class is a mixer node that simulates a 3D audio environment. Any node that conforms to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixing",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " can act as a source node, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioPlayerNode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The environment node has an implicit listener. You set the listener’s position and orientation, and the system then controls the way the user experiences the virtual world.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To help characterize the environment, this class defines properties for distance attenuation and reverberation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingSourceMode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " affects how inputs with different channel configurations render. Spatialization applies only to inputs with a mono channel connection format. This class doesn’t spatialize stereo inputs or support inputs with connection formats of more than two channels.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To set the node’s output to a multichannel format, use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioFormat",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that has one of the following ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/audio-channel-layout-tags",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_4",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_5_0",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_6_0",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_7_0",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_7_0_Front",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_8",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DAngularOrientation": {
      "abstract": [
        {
          "text": "A structure that represents the angular orientation of the listener in 3D space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DAngularOrientation"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DAngularOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DAngularOrientation"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DAngularOrientation",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dangularorientation"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing": {
      "abstract": [
        {
          "text": "A collection of properties that define 3D mixing properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DMixing"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixing"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixing",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixing"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingPointSourceInHeadMode": {
      "abstract": [
        {
          "text": "The in-head modes for a point source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingPointSourceInHeadMode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingPointSourceInHeadMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingPointSourceInHeadMode"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingPointSourceInHeadMode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingpointsourceinheadmode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm": {
      "abstract": [
        {
          "text": "The types of rendering algorithms available per input bus of the environment node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingRenderingAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingRenderingAlgorithm",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingrenderingalgorithm"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingSourceMode": {
      "abstract": [
        {
          "text": "The source modes for the input bus of the audio environment node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingSourceMode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingSourceMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DMixingSourceMode"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DMixingSourceMode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dmixingsourcemode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DPoint": {
      "abstract": [
        {
          "text": "A structure that represents a point in 3D space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DPoint"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DPoint"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DPoint",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dpoint"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVector": {
      "abstract": [
        {
          "text": "A structure that represents a vector in 3D space, in degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DVector"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DVector"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DVector",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dvector"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVectorOrientation": {
      "abstract": [
        {
          "text": "A structure that represents two orthogonal vectors that describe the orientation of the listener in 3D space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudio3DVectorOrientation"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVectorOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudio3DVectorOrientation"
        }
      ],
      "role": "symbol",
      "title": "AVAudio3DVectorOrientation",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudio3dvectororientation"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentDistanceAttenuationParameters": {
      "abstract": [
        {
          "text": "An object that specifies the amount of attenuation distance, the gradual loss in audio intensity, and other characteristics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentDistanceAttenuationParameters"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentDistanceAttenuationParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentDistanceAttenuationParameters"
        }
      ],
      "role": "symbol",
      "title": "AVAudioEnvironmentDistanceAttenuationParameters",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentdistanceattenuationparameters"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode": {
      "abstract": [
        {
          "text": "An object that simulates a 3D audio environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentNode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentNode"
        }
      ],
      "role": "symbol",
      "title": "AVAudioEnvironmentNode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentnode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/applicableRenderingAlgorithms": {
      "abstract": [
        {
          "text": "An array of rendering algorithms applicable to the environment node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicableRenderingAlgorithms"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/applicableRenderingAlgorithms",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicableRenderingAlgorithms"
        }
      ],
      "role": "symbol",
      "title": "applicableRenderingAlgorithms",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentnode/applicablerenderingalgorithms"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/distanceAttenuationParameters": {
      "abstract": [
        {
          "text": "The distance attenuation parameters for the environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distanceAttenuationParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioEnvironmentDistanceAttenuationParameters",
          "text": "AVAudioEnvironmentDistanceAttenuationParameters"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/distanceAttenuationParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "distanceAttenuationParameters"
        }
      ],
      "role": "symbol",
      "title": "distanceAttenuationParameters",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentnode/distanceattenuationparameters"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/init()": {
      "abstract": [
        {
          "text": "Creates a new environment node object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentnode/init()"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/isListenerHeadTrackingEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the listener orientation is automatically rotated based on head orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isListenerHeadTrackingEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/isListenerHeadTrackingEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "listenerHeadTrackingEnabled"
        }
      ],
      "role": "symbol",
      "title": "isListenerHeadTrackingEnabled",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentnode/islistenerheadtrackingenabled"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/listenerAngularOrientation": {
      "abstract": [
        {
          "text": "The listener’s angular orientation in the environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "listenerAngularOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AVAudio3DAngularOrientation",
          "text": "AVAudio3DAngularOrientation"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/listenerAngularOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "listenerAngularOrientation"
        }
      ],
      "role": "symbol",
      "title": "listenerAngularOrientation",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentnode/listenerangularorientation"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/listenerPosition": {
      "abstract": [
        {
          "text": "The listener’s position in the 3D environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "listenerPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AVAudio3DPoint",
          "text": "AVAudio3DPoint"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/listenerPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "listenerPosition"
        }
      ],
      "role": "symbol",
      "title": "listenerPosition",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentnode/listenerposition"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/listenerVectorOrientation": {
      "abstract": [
        {
          "text": "The listener’s vector orientation in the environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "listenerVectorOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AVAudio3DVectorOrientation",
          "text": "AVAudio3DVectorOrientation"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/listenerVectorOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "listenerVectorOrientation"
        }
      ],
      "role": "symbol",
      "title": "listenerVectorOrientation",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentnode/listenervectororientation"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/nextAvailableInputBus": {
      "abstract": [
        {
          "text": "An unused input bus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextAvailableInputBus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioNodeBus",
          "text": "AVAudioNodeBus"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/nextAvailableInputBus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nextAvailableInputBus"
        }
      ],
      "role": "symbol",
      "title": "nextAvailableInputBus",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentnode/nextavailableinputbus"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/outputType": {
      "abstract": [
        {
          "text": "The type of output hardware.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioEnvironmentOutputType",
          "text": "AVAudioEnvironmentOutputType"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/outputType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputType"
        }
      ],
      "role": "symbol",
      "title": "outputType",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentnode/outputtype"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/outputVolume": {
      "abstract": [
        {
          "text": "The mixer’s output volume.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputVolume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/outputVolume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputVolume"
        }
      ],
      "role": "symbol",
      "title": "outputVolume",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentnode/outputvolume"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/reverbParameters": {
      "abstract": [
        {
          "text": "The reverb parameters for the environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioEnvironmentReverbParameters",
          "text": "AVAudioEnvironmentReverbParameters"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/reverbParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reverbParameters"
        }
      ],
      "role": "symbol",
      "title": "reverbParameters",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentnode/reverbparameters"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentOutputType": {
      "abstract": [
        {
          "text": "The output types for using with the automatic 3D mixing rendering algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentOutputType"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentOutputType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentOutputType"
        }
      ],
      "role": "symbol",
      "title": "AVAudioEnvironmentOutputType",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentoutputtype"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentReverbParameters": {
      "abstract": [
        {
          "text": "A class that encapsulates the parameters that you use to control the reverb of the environment node class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentReverbParameters"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentReverbParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioEnvironmentReverbParameters"
        }
      ],
      "role": "symbol",
      "title": "AVAudioEnvironmentReverbParameters",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenvironmentreverbparameters"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioFormat": {
      "abstract": [
        {
          "text": "An object that describes the representation of an audio format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioFormat"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioFormat"
        }
      ],
      "role": "symbol",
      "title": "AVAudioFormat",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioformat"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixing": {
      "abstract": [
        {
          "text": "A collection of properties that are applicable to the input bus of a mixer node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioMixing"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioMixing"
        }
      ],
      "role": "symbol",
      "title": "AVAudioMixing",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiomixing"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioNode": {
      "abstract": [
        {
          "text": "An object you use for audio generation, processing, or an I/O block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioNode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioNode"
        }
      ],
      "role": "symbol",
      "title": "AVAudioNode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudionode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioPlayerNode": {
      "abstract": [
        {
          "text": "An object for scheduling the playback of buffers or segments of audio files.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioPlayerNode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioPlayerNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioPlayerNode"
        }
      ],
      "role": "symbol",
      "title": "AVAudioPlayerNode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioplayernode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioStereoMixing": {
      "abstract": [
        {
          "text": "A protocol that defines stereo mixing properties a mixer uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioStereoMixing"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioStereoMixing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioStereoMixing"
        }
      ],
      "role": "symbol",
      "title": "AVAudioStereoMixing",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiostereomixing"
    },
    "doc://com.apple.documentation/documentation/CoreAudioTypes/audio-channel-layout-tags": {
      "abstract": [
        {
          "text": "The identifiers that represent audio channel layouts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/audio-channel-layout-tags",
      "kind": "article",
      "role": "article",
      "title": "Audio Channel Layout Tags",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/audio-channel-layout-tags"
    },
    "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_4": {
      "abstract": [
        {
          "text": "A quadraphonic symmetrical layout, recommended for use by audio units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_AudioUnit_4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_4",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_AudioUnit_4",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_4"
    },
    "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_5_0": {
      "abstract": [
        {
          "text": "A 5-channel surround-based layout, recommended for use by audio units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_AudioUnit_5_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_5_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_AudioUnit_5_0",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_5_0"
    },
    "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_6_0": {
      "abstract": [
        {
          "text": "A 6-channel surround-based layout, recommended for use by audio units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_AudioUnit_6_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_6_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_AudioUnit_6_0",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_6_0"
    },
    "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_7_0": {
      "abstract": [
        {
          "text": "A 7-channel surround-based layout, recommended for use by audio units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_AudioUnit_7_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_7_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_AudioUnit_7_0",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_7_0"
    },
    "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_7_0_Front": {
      "abstract": [
        {
          "text": "An alternate 7-channel surround-based layout, for use by audio units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_AudioUnit_7_0_Front"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_7_0_Front",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_AudioUnit_7_0_Front",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_7_0_Front"
    },
    "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_8": {
      "abstract": [
        {
          "text": "An octagonal symmetrical layout, recommended for use by audio units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioChannelLayoutTag_AudioUnit_8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioChannelLayoutTag",
          "text": "AudioChannelLayoutTag"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_8",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioChannelLayoutTag_AudioUnit_8",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/kAudioChannelLayoutTag_AudioUnit_8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioNode"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixing",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioStereoMixing",
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Spatial-audio",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentDistanceAttenuationParameters",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentReverbParameters",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DPoint",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVectorOrientation",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DAngularOrientation",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingSourceMode",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentOutputType",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingPointSourceInHeadMode",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVector"
      ],
      "title": "Spatial audio"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-Environment-Node",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/init()"
      ],
      "title": "Creating an Environment Node"
    },
    {
      "anchor": "Getting-and-Setting-Positional-Properties",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/listenerPosition",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/listenerAngularOrientation",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/listenerVectorOrientation"
      ],
      "title": "Getting and Setting Positional Properties"
    },
    {
      "anchor": "Getting-Attenuation-and-Reverb-Properties",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/distanceAttenuationParameters",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/reverbParameters"
      ],
      "title": "Getting Attenuation and Reverb Properties"
    },
    {
      "anchor": "Getting-and-Setting-Environment-Properties",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/outputVolume",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/outputType"
      ],
      "title": "Getting and Setting Environment Properties"
    },
    {
      "anchor": "Getting-the-Available-Rendering-Algorithms",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/applicableRenderingAlgorithms"
      ],
      "title": "Getting the Available Rendering Algorithms"
    },
    {
      "anchor": "Getting-the-Head-Tracking-Status",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/isListenerHeadTrackingEnabled"
      ],
      "title": "Getting the Head Tracking Status"
    },
    {
      "anchor": "Getting-the-Input-Bus",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/nextAvailableInputBus"
      ],
      "title": "Getting the Input Bus"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioEnvironmentNode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-an-Environment-Node",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/init()"
              ],
              "title": "Creating an Environment Node"
            },
            {
              "anchor": "Getting-and-Setting-Positional-Properties",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/listenerPosition",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/listenerAngularOrientation",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/listenerVectorOrientation"
              ],
              "title": "Getting and Setting Positional Properties"
            },
            {
              "anchor": "Getting-Attenuation-and-Reverb-Properties",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/distanceAttenuationParameters",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/reverbParameters"
              ],
              "title": "Getting Attenuation and Reverb Properties"
            },
            {
              "anchor": "Getting-and-Setting-Environment-Properties",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/outputVolume",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/outputType"
              ],
              "title": "Getting and Setting Environment Properties"
            },
            {
              "anchor": "Getting-the-Available-Rendering-Algorithms",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/applicableRenderingAlgorithms"
              ],
              "title": "Getting the Available Rendering Algorithms"
            },
            {
              "anchor": "Getting-the-Head-Tracking-Status",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/isListenerHeadTrackingEnabled"
              ],
              "title": "Getting the Head Tracking Status"
            },
            {
              "anchor": "Getting-the-Input-Bus",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentNode/nextAvailableInputBus"
              ],
              "title": "Getting the Input Bus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioNode"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioMixing"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Spatial-audio",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentDistanceAttenuationParameters",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentReverbParameters",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixing",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DPoint",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVectorOrientation",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DAngularOrientation",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingSourceMode",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingRenderingAlgorithm",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEnvironmentOutputType",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DMixingPointSourceInHeadMode",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudio3DVector"
              ],
              "title": "Spatial audio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAudioEnvironmentNode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioNode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVAudioNode",
                    "text": "AVAudioNode"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing/title",
          "value": "AVAudio3DMixing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixing/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentDistanceAttenuationParameters/title",
          "value": "AVAudioEnvironmentDistanceAttenuationParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentDistanceAttenuationParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentDistanceAttenuationParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentDistanceAttenuationParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentDistanceAttenuationParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentOutputType/title",
          "value": "AVAudioEnvironmentOutputType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentOutputType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentOutputType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentOutputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode/title",
          "value": "AVAudioEnvironmentNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingSourceMode/title",
          "value": "AVAudio3DMixingSourceMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingSourceMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingSourceMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingSourceMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1isListenerHeadTrackingEnabled/title",
          "value": "listenerHeadTrackingEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1isListenerHeadTrackingEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "listenerHeadTrackingEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioFormat/title",
          "value": "AVAudioFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1outputType/title",
          "value": "outputType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1outputType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioMixing/title",
          "value": "AVAudioMixing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioMixing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioMixing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioMixing/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioMixing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm/title",
          "value": "AVAudio3DMixingRenderingAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingRenderingAlgorithm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingRenderingAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1applicableRenderingAlgorithms/title",
          "value": "applicableRenderingAlgorithms"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1applicableRenderingAlgorithms/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicableRenderingAlgorithms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_AudioUnit_8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_AudioUnit_8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_AudioUnit_7_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_AudioUnit_7_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioNode/title",
          "value": "AVAudioNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_AudioUnit_5_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_AudioUnit_5_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DPoint/title",
          "value": "AVAudio3DPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DPoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioPlayerNode/title",
          "value": "AVAudioPlayerNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioPlayerNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioPlayerNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioPlayerNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioPlayerNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1listenerVectorOrientation/title",
          "value": "listenerVectorOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1listenerVectorOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "listenerVectorOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DAngularOrientation/title",
          "value": "AVAudio3DAngularOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DAngularOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DAngularOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DAngularOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DAngularOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1outputVolume/title",
          "value": "outputVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1outputVolume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_AudioUnit_4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_AudioUnit_4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DVector/title",
          "value": "AVAudio3DVector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DVector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DVector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DVector/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DVector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1reverbParameters/title",
          "value": "reverbParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1reverbParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reverbParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1distanceAttenuationParameters/title",
          "value": "distanceAttenuationParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1distanceAttenuationParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "distanceAttenuationParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentReverbParameters/title",
          "value": "AVAudioEnvironmentReverbParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentReverbParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentReverbParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentReverbParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEnvironmentReverbParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_AudioUnit_6_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_AudioUnit_6_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1listenerPosition/title",
          "value": "listenerPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1listenerPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "listenerPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreAudioTypes~1kAudioChannelLayoutTag_AudioUnit_7_0_Front/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelLayoutTag_AudioUnit_7_0_Front"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1nextAvailableInputBus/title",
          "value": "nextAvailableInputBus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1nextAvailableInputBus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nextAvailableInputBus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioStereoMixing/title",
          "value": "AVAudioStereoMixing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioStereoMixing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioStereoMixing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioStereoMixing/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioStereoMixing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1listenerAngularOrientation/title",
          "value": "listenerAngularOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEnvironmentNode~1listenerAngularOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "listenerAngularOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DVectorOrientation/title",
          "value": "AVAudio3DVectorOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DVectorOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DVectorOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DVectorOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DVectorOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingPointSourceInHeadMode/title",
          "value": "AVAudio3DMixingPointSourceInHeadMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingPointSourceInHeadMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingPointSourceInHeadMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudio3DMixingPointSourceInHeadMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudio3DMixingPointSourceInHeadMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudioenvironmentnode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudioenvironmentnode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
