{
  "abstract": [
    {
      "text": "An object that manages one or more audio sessions that belong to an app.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVAudioApplication",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVAudioApplication"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioApplication"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVAudioApplication"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioApplication"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Access the shared audio application instance to control app-level audio operations, such as requesting microphone permission and controlling audio input muting.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication": {
      "abstract": [
        {
          "text": "An object that manages one or more audio sessions that belong to an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioApplication"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioApplication"
        }
      ],
      "role": "symbol",
      "title": "AVAudioApplication",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioapplication"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/MicrophoneInjectionPermission-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate an app’s permission to add audio to calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MicrophoneInjectionPermission"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/MicrophoneInjectionPermission-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MicrophoneInjectionPermission"
        }
      ],
      "role": "symbol",
      "title": "AVAudioApplication.MicrophoneInjectionPermission",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioapplication/microphoneinjectionpermission-swift.enum"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/inputMuteStateChangeNotification": {
      "abstract": [
        {
          "text": "A notification the system posts when the app’s audio input mute state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputMuteStateChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/inputMuteStateChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioApplicationInputMuteStateChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "inputMuteStateChangeNotification",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioapplication/inputmutestatechangenotification"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/isInputMuted": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app’s audio input is in a muted state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isInputMuted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/isInputMuted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputMuted"
        }
      ],
      "role": "symbol",
      "title": "isInputMuted",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioapplication/isinputmuted"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/microphoneInjectionPermission-swift.property": {
      "abstract": [
        {
          "text": "A value that indicates an app’s permission to add audio to calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "microphoneInjectionPermission"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioApplication",
          "text": "AVAudioApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioApplicationMicrophoneInjectionPermission",
          "text": "MicrophoneInjectionPermission"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/microphoneInjectionPermission-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "microphoneInjectionPermission"
        }
      ],
      "role": "symbol",
      "title": "microphoneInjectionPermission",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioapplication/microphoneinjectionpermission-swift.property"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/recordPermission-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate the app’s permission to record audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordPermission"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/recordPermission-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordPermission"
        }
      ],
      "role": "symbol",
      "title": "AVAudioApplication.recordPermission",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioapplication/recordpermission-swift.enum"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/recordPermission-swift.property": {
      "abstract": [
        {
          "text": "The app’s permission to record audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordPermission"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioApplication",
          "text": "AVAudioApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioApplicationRecordPermission",
          "text": "recordPermission"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/recordPermission-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordPermission"
        }
      ],
      "role": "symbol",
      "title": "recordPermission",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioapplication/recordpermission-swift.property"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/requestMicrophoneInjectionPermission(completionHandler:)": {
      "abstract": [
        {
          "text": "Requests the app’s permission to add audio to calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestMicrophoneInjectionPermission"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioApplication",
          "text": "AVAudioApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioApplicationMicrophoneInjectionPermission",
          "text": "MicrophoneInjectionPermission"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/requestMicrophoneInjectionPermission(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestMicrophoneInjectionPermissionWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestMicrophoneInjectionPermission(completionHandler:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioapplication/requestmicrophoneinjectionpermission(completionhandler:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/requestRecordPermission(completionHandler:)": {
      "abstract": [
        {
          "text": "Determines whether the app has permission to record audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestRecordPermission"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/requestRecordPermission(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestRecordPermissionWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestRecordPermission(completionHandler:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioapplication/requestrecordpermission(completionhandler:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/setInputMuteStateChangeHandler(_:)": {
      "abstract": [
        {
          "text": "Sets a callback to handle changes to application-level audio muting states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setInputMuteStateChangeHandler"
        },
        {
          "kind": "text",
          "text": "((("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/setInputMuteStateChangeHandler(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setInputMuteStateChangeHandler:error:"
        }
      ],
      "role": "symbol",
      "title": "setInputMuteStateChangeHandler(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioapplication/setinputmutestatechangehandler(_:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/setInputMuted(_:)": {
      "abstract": [
        {
          "text": "Sets a Boolean value that indicates whether the app’s audio input is in a muted state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setInputMuted"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/setInputMuted(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setInputMuted:error:"
        }
      ],
      "role": "symbol",
      "title": "setInputMuted(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioapplication/setinputmuted(_:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/shared": {
      "abstract": [
        {
          "text": "Accesses the shared audio application instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shared"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioApplication",
          "text": "AVAudioApplication"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/shared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedInstance"
        }
      ],
      "role": "symbol",
      "title": "shared",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioapplication/shared"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRoutingArbiter": {
      "abstract": [
        {
          "text": "An object for configuring macOS apps to participate in AirPods Automatic Switching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioRoutingArbiter"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRoutingArbiter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioRoutingArbiter"
        }
      ],
      "role": "symbol",
      "title": "AVAudioRoutingArbiter",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioroutingarbiter"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession": {
      "abstract": [
        {
          "text": "An object that communicates to the system how you intend to use audio in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/Adding-synthesized-speech-to-calls": {
      "abstract": [
        {
          "text": "Provide a more accessible experience by adding your app’s audio to a call.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/Adding-synthesized-speech-to-calls",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adding synthesized speech to calls",
      "type": "topic",
      "url": "/documentation/avfaudio/adding-synthesized-speech-to-calls"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/capturing-stereo-audio-from-built-in-microphones": {
      "abstract": [
        {
          "text": "Configure an iOS device’s built-in microphones to add stereo recording capabilities to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/capturing-stereo-audio-from-built-in-microphones",
      "kind": "article",
      "role": "sampleCode",
      "title": "Capturing stereo audio from built-In microphones",
      "type": "topic",
      "url": "/documentation/avfaudio/capturing-stereo-audio-from-built-in-microphones"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/handling-audio-interruptions": {
      "abstract": [
        {
          "text": "Observe audio session notifications to ensure that your app responds appropriately to interruptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/handling-audio-interruptions",
      "kind": "article",
      "role": "article",
      "title": "Handling audio interruptions",
      "type": "topic",
      "url": "/documentation/avfaudio/handling-audio-interruptions"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/responding-to-audio-route-changes": {
      "abstract": [
        {
          "text": "Observe audio session notifications to ensure that your app responds appropriately to route changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/responding-to-audio-route-changes",
      "kind": "article",
      "role": "article",
      "title": "Responding to audio route changes",
      "type": "topic",
      "url": "/documentation/avfaudio/responding-to-audio-route-changes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "System-audio",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/handling-audio-interruptions",
        "doc://com.apple.avfaudio/documentation/AVFAudio/responding-to-audio-route-changes",
        "doc://com.apple.avfaudio/documentation/AVFAudio/Adding-synthesized-speech-to-calls",
        "doc://com.apple.avfaudio/documentation/AVFAudio/capturing-stereo-audio-from-built-in-microphones",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRoutingArbiter"
      ],
      "title": "System audio"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-the-shared-instance",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/shared"
      ],
      "title": "Accessing the shared instance"
    },
    {
      "anchor": "Requesting-audio-recording-permission",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/requestRecordPermission(completionHandler:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/recordPermission-swift.property",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/recordPermission-swift.enum"
      ],
      "title": "Requesting audio recording permission"
    },
    {
      "anchor": "Requesting-microphone-injection-permission",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/requestMicrophoneInjectionPermission(completionHandler:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/microphoneInjectionPermission-swift.property",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/MicrophoneInjectionPermission-swift.enum"
      ],
      "title": "Requesting microphone injection permission"
    },
    {
      "anchor": "Managing-audio-input-mute-state",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/isInputMuted",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/setInputMuted(_:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/inputMuteStateChangeNotification",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/setInputMuteStateChangeHandler(_:)"
      ],
      "title": "Managing audio input mute state"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioApplication"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-the-shared-instance",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/shared"
              ],
              "title": "Accessing the shared instance"
            },
            {
              "anchor": "Requesting-audio-recording-permission",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/requestRecordPermission(completionHandler:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/recordPermission-swift.property",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/recordPermission-swift.enum"
              ],
              "title": "Requesting audio recording permission"
            },
            {
              "anchor": "Requesting-microphone-injection-permission",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/requestMicrophoneInjectionPermission(completionHandler:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/microphoneInjectionPermission-swift.property",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/MicrophoneInjectionPermission-swift.enum"
              ],
              "title": "Requesting microphone injection permission"
            },
            {
              "anchor": "Managing-audio-input-mute-state",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/isInputMuted",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/setInputMuted(_:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/inputMuteStateChangeNotification",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioApplication/setInputMuteStateChangeHandler(_:)"
              ],
              "title": "Managing audio input mute state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "System-audio",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/handling-audio-interruptions",
                "doc://com.apple.avfaudio/documentation/AVFAudio/responding-to-audio-route-changes",
                "doc://com.apple.avfaudio/documentation/AVFAudio/Adding-synthesized-speech-to-calls",
                "doc://com.apple.avfaudio/documentation/AVFAudio/capturing-stereo-audio-from-built-in-microphones",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRoutingArbiter"
              ],
              "title": "System audio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAudioApplication"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1recordPermission-swift.property/title",
          "value": "recordPermission"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1recordPermission-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recordPermission"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1inputMuteStateChangeNotification/title",
          "value": "AVAudioApplicationInputMuteStateChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1inputMuteStateChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioApplicationInputMuteStateChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1requestRecordPermission(completionHandler:)/title",
          "value": "requestRecordPermissionWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1requestRecordPermission(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestRecordPermissionWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1recordPermission-swift.enum/title",
          "value": "AVAudioApplicationRecordPermission"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1recordPermission-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioApplicationRecordPermission"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1recordPermission-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioApplicationRecordPermission"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1setInputMuted(_:)/title",
          "value": "setInputMuted:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1setInputMuted(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setInputMuted:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication/title",
          "value": "AVAudioApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1shared/title",
          "value": "sharedInstance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1shared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sharedInstance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1MicrophoneInjectionPermission-swift.enum/title",
          "value": "AVAudioApplicationMicrophoneInjectionPermission"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1MicrophoneInjectionPermission-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioApplicationMicrophoneInjectionPermission"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1MicrophoneInjectionPermission-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioApplicationMicrophoneInjectionPermission"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRoutingArbiter/title",
          "value": "AVAudioRoutingArbiter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRoutingArbiter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioRoutingArbiter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRoutingArbiter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioRoutingArbiter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1microphoneInjectionPermission-swift.property/title",
          "value": "microphoneInjectionPermission"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1microphoneInjectionPermission-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "microphoneInjectionPermission"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1setInputMuteStateChangeHandler(_:)/title",
          "value": "setInputMuteStateChangeHandler:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1setInputMuteStateChangeHandler(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setInputMuteStateChangeHandler:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1isInputMuted/title",
          "value": "inputMuted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1isInputMuted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputMuted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1requestMicrophoneInjectionPermission(completionHandler:)/title",
          "value": "requestMicrophoneInjectionPermissionWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioApplication~1requestMicrophoneInjectionPermission(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestMicrophoneInjectionPermissionWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/title",
          "value": "AVAudioSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudioapplication"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudioapplication"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
