{
  "abstract": [
    {
      "text": "The type that represents a block that renders the engine when operating in manual rendering mode.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngineManualRenderingBlock"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@AVAudioEngineManualRenderingBlock",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVAudioEngineManualRenderingBlock"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioEngineManualRenderingBlock"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "AVAudioEngineManualRenderingBlock"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioEngineManualRenderingBlock"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioFrameCount",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVAudioFrameCount",
              "text": "AVAudioFrameCount"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@AudioBufferList",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@AudioBufferList",
              "text": "AudioBufferList"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": ">?) -> "
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngineManualRenderingStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AVAudioEngineManualRenderingStatus",
              "text": "AVAudioEngineManualRenderingStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of PCM sample frames to render.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "numberOfFrames"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The PCM buffer the engine must render the audio for.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outBuffer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On exit, if an error occurs during rendering, a description of the error.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outError"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "One of the status codes from ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngineManualRenderingStatus",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Irrespective of the returned status code, on exit, the output buffer’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioPCMBuffer/frameLength",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " indicates the number of PCM samples the engine renders.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/isAutoShutdownEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether autoshutdown is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutoShutdownEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/isAutoShutdownEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autoShutdownEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAutoShutdownEnabled",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioengine/isautoshutdownenabled"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/isInManualRenderingMode": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the engine is operating in manual rendering mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isInManualRenderingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/isInManualRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isInManualRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "isInManualRenderingMode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioengine/isinmanualrenderingmode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingBlock": {
      "abstract": [
        {
          "text": "The block that renders the engine when operating in manual rendering mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manualRenderingBlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioEngineManualRenderingBlock",
          "text": "AVAudioEngineManualRenderingBlock"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "manualRenderingBlock"
        }
      ],
      "role": "symbol",
      "title": "manualRenderingBlock",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioengine/manualrenderingblock"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingFormat": {
      "abstract": [
        {
          "text": "The render format of the engine in manual rendering mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manualRenderingFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioFormat",
          "text": "AVAudioFormat"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "manualRenderingFormat"
        }
      ],
      "role": "symbol",
      "title": "manualRenderingFormat",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioengine/manualrenderingformat"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingMaximumFrameCount": {
      "abstract": [
        {
          "text": "The maximum number of PCM sample frames the engine produces in any single render call in manual rendering mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manualRenderingMaximumFrameCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioFrameCount",
          "text": "AVAudioFrameCount"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingMaximumFrameCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "manualRenderingMaximumFrameCount"
        }
      ],
      "role": "symbol",
      "title": "manualRenderingMaximumFrameCount",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioengine/manualrenderingmaximumframecount"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingMode": {
      "abstract": [
        {
          "text": "The manual rendering mode configured on the engine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manualRenderingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioEngineManualRenderingMode",
          "text": "AVAudioEngineManualRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "manualRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "manualRenderingMode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioengine/manualrenderingmode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingSampleTime": {
      "abstract": [
        {
          "text": "An indication of where the engine is on its render timeline in manual rendering mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manualRenderingSampleTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioFramePosition",
          "text": "AVAudioFramePosition"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingSampleTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "manualRenderingSampleTime"
        }
      ],
      "role": "symbol",
      "title": "manualRenderingSampleTime",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioengine/manualrenderingsampletime"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngineManualRenderingBlock": {
      "abstract": [
        {
          "text": "The type that represents a block that renders the engine when operating in manual rendering mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioEngineManualRenderingBlock"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngineManualRenderingBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioEngineManualRenderingBlock"
        }
      ],
      "role": "symbol",
      "title": "AVAudioEngineManualRenderingBlock",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenginemanualrenderingblock"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngineManualRenderingStatus": {
      "abstract": [
        {
          "text": "Status codes that return from the render call to the engine operating in manual rendering mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioEngineManualRenderingStatus"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngineManualRenderingStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioEngineManualRenderingStatus"
        }
      ],
      "role": "symbol",
      "title": "AVAudioEngineManualRenderingStatus",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioenginemanualrenderingstatus"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioFrameCount": {
      "abstract": [
        {
          "text": "A number of audio sample frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioFrameCount"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioFrameCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioFrameCount"
        }
      ],
      "role": "symbol",
      "title": "AVAudioFrameCount",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioframecount"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioPCMBuffer/frameLength": {
      "abstract": [
        {
          "text": "The current number of valid sample frames in the buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioFrameCount",
          "text": "AVAudioFrameCount"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioPCMBuffer/frameLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frameLength"
        }
      ],
      "role": "symbol",
      "title": "frameLength",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiopcmbuffer/framelength"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@AudioBufferList": {
      "abstract": [
        {
          "text": "A structure that stores a variable-length array of audio buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioBufferList"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@AudioBufferList",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioBufferList",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/AudioBufferList"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Manual-Rendering-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingBlock",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingFormat",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingMaximumFrameCount",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingMode",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingSampleTime",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/isAutoShutdownEnabled",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/isInManualRenderingMode"
      ],
      "title": "Getting Manual Rendering Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioEngineManualRenderingBlock"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEngineManualRenderingBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEngineManualRenderingBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Manual-Rendering-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingBlock",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingFormat",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingMaximumFrameCount",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingMode",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/manualRenderingSampleTime",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/isAutoShutdownEnabled",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioEngine/isInManualRenderingMode"
              ],
              "title": "Getting Manual Rendering Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BF$@E@AVAudioEngineManualRenderingStatus(#i#*$@S@AudioBufferList#*I)",
                    "text": "enum AVAudioEngineManualRenderingStatus (^)(unsigned int, struct AudioBufferList *, int *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAudioEngineManualRenderingBlock"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngine~1manualRenderingBlock/title",
          "value": "manualRenderingBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngine~1manualRenderingBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "manualRenderingBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngine~1isInManualRenderingMode/title",
          "value": "isInManualRenderingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngine~1isInManualRenderingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isInManualRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngine~1manualRenderingFormat/title",
          "value": "manualRenderingFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngine~1manualRenderingFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "manualRenderingFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngine~1manualRenderingMaximumFrameCount/title",
          "value": "manualRenderingMaximumFrameCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngine~1manualRenderingMaximumFrameCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "manualRenderingMaximumFrameCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngine~1manualRenderingMode/title",
          "value": "manualRenderingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngine~1manualRenderingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "manualRenderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@S@AudioBufferList/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioBufferList"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngineManualRenderingStatus/title",
          "value": "AVAudioEngineManualRenderingStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngineManualRenderingStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEngineManualRenderingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngineManualRenderingStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEngineManualRenderingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioPCMBuffer~1frameLength/title",
          "value": "frameLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioPCMBuffer~1frameLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frameLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngineManualRenderingBlock/title",
          "value": "AVAudioEngineManualRenderingBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngineManualRenderingBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEngineManualRenderingBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngineManualRenderingBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioEngineManualRenderingBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioFrameCount/title",
          "value": "AVAudioFrameCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioFrameCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioFrameCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioFrameCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioFrameCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngine~1manualRenderingSampleTime/title",
          "value": "manualRenderingSampleTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngine~1manualRenderingSampleTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "manualRenderingSampleTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngine~1isAutoShutdownEnabled/title",
          "value": "autoShutdownEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioEngine~1isAutoShutdownEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autoShutdownEnabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudioenginemanualrenderingblock"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudioenginemanualrenderingblock"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
