{
  "abstract": [
    {
      "text": "The speech quality of a voice.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceQuality"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVSpeechSynthesisVoiceQuality",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVSpeechSynthesisVoiceQuality"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVSpeechSynthesisVoiceQuality"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AVSpeechSynthesisVoiceQuality"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoiceQuality"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/Traits": {
      "abstract": [
        {
          "text": "Traits that describe a voice.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Traits"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/Traits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Traits"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesisVoice.Traits",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesisvoice/traits"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/audioFileSettings": {
      "abstract": [
        {
          "text": "A dictionary that contains audio file settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioFileSettings"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/audioFileSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audioFileSettings"
        }
      ],
      "role": "symbol",
      "title": "audioFileSettings",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesisvoice/audiofilesettings"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/gender": {
      "abstract": [
        {
          "text": "The gender for a voice.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVSpeechSynthesisVoiceGender",
          "text": "AVSpeechSynthesisVoiceGender"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/gender",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gender"
        }
      ],
      "role": "symbol",
      "title": "gender",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesisvoice/gender"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/identifier": {
      "abstract": [
        {
          "text": "The unique identifier of a voice.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesisvoice/identifier"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/name": {
      "abstract": [
        {
          "text": "The name of a voice.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesisvoice/name"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/quality": {
      "abstract": [
        {
          "text": "The speech quality of a voice.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVSpeechSynthesisVoiceQuality",
          "text": "AVSpeechSynthesisVoiceQuality"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/quality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "quality"
        }
      ],
      "role": "symbol",
      "title": "quality",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesisvoice/quality"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/voiceTraits": {
      "abstract": [
        {
          "text": "The traits of a voice.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voiceTraits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesisVoice",
          "text": "AVSpeechSynthesisVoice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVSpeechSynthesisVoiceTraits",
          "text": "Traits"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/voiceTraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "voiceTraits"
        }
      ],
      "role": "symbol",
      "title": "voiceTraits",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesisvoice/voicetraits"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceGender": {
      "abstract": [
        {
          "text": "The gender for a voice.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisVoiceGender"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceGender",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisVoiceGender"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesisVoiceGender",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesisvoicegender"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceQuality": {
      "abstract": [
        {
          "text": "The speech quality of a voice.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisVoiceQuality"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisVoiceQuality"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesisVoiceQuality",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesisvoicequality"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceQuality/default": {
      "abstract": [
        {
          "text": "A basic quality voice that’s  available on the device by default.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceQuality/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisVoiceQualityDefault"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesisVoiceQuality.default",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesisvoicequality/default"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceQuality/enhanced": {
      "abstract": [
        {
          "text": "An enhanced quality voice that you must download to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enhanced"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceQuality/enhanced",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisVoiceQualityEnhanced"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesisVoiceQuality.enhanced",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesisvoicequality/enhanced"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceQuality/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceQuality/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesisvoicequality/init(rawvalue:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceQuality/premium": {
      "abstract": [
        {
          "text": "A premium quality voice that you must download to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "premium"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceQuality/premium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisVoiceQualityPremium"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesisVoiceQuality.premium",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesisvoicequality/premium"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-voices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/identifier",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/name",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/quality",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/gender",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/voiceTraits",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/audioFileSettings",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceGender",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/Traits"
      ],
      "title": "Inspecting voices"
    }
  ],
  "topicSections": [
    {
      "anchor": "Voice-qualities",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceQuality/default",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceQuality/enhanced",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceQuality/premium"
      ],
      "title": "Voice qualities"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceQuality/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVSpeechSynthesisVoiceQuality"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoiceQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoiceQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Voice-qualities",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceQuality/default",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceQuality/enhanced",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceQuality/premium"
              ],
              "title": "Voice qualities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-voices",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/identifier",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/name",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/quality",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/gender",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/voiceTraits",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/audioFileSettings",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoiceGender",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice/Traits"
              ],
              "title": "Inspecting voices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVSpeechSynthesisVoiceQuality"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoiceQuality/title",
          "value": "AVSpeechSynthesisVoiceQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoiceQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoiceQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoiceQuality/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoiceQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1Traits/title",
          "value": "AVSpeechSynthesisVoiceTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1Traits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoiceTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1Traits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoiceTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1audioFileSettings/title",
          "value": "audioFileSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1audioFileSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "audioFileSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoiceQuality~1default/title",
          "value": "AVSpeechSynthesisVoiceQualityDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoiceQuality~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoiceQualityDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1voiceTraits/title",
          "value": "voiceTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1voiceTraits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "voiceTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoiceGender/title",
          "value": "AVSpeechSynthesisVoiceGender"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoiceGender/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoiceGender"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoiceGender/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoiceGender"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoiceQuality~1premium/title",
          "value": "AVSpeechSynthesisVoiceQualityPremium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoiceQuality~1premium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoiceQualityPremium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoiceQuality~1enhanced/title",
          "value": "AVSpeechSynthesisVoiceQualityEnhanced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoiceQuality~1enhanced/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoiceQualityEnhanced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1gender/title",
          "value": "gender"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1gender/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gender"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1quality/title",
          "value": "quality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1quality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "quality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avspeechsynthesisvoicequality"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avspeechsynthesisvoicequality"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
