{
  "abstract": [
    {
      "text": "An object that produces synthesized speech from text utterances and enables monitoring or controlling of ongoing speech.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVSpeechSynthesizer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVSpeechSynthesizer"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVSpeechSynthesizer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVSpeechSynthesizer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizer"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To speak some text, create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechUtterance",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance that contains the text and pass it to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/speak(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on a speech synthesizer instance. You can optionally also retrieve an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and set it on the utterance’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechUtterance/voice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to have the speech synthesizer use that voice when speaking the utterance’s text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The speech synthesizer maintains a queue of utterances that it speaks. If the synthesizer isn’t speaking, calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/speak(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " begins speaking that utterance either immediately or after pausing for its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechUtterance/preUtteranceDelay",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", if necessary. If the synthesizer is speaking, the synthesizer adds utterances to a queue and speaks them in the order it receives them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After speech begins, you can use the synthesizer object to pause or stop speech. After pausing, you can resume the speech from its paused point or stop the speech entirely and remove all remaining utterances in the queue.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can monitor the speech synthesizer by examining its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/isSpeaking",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/isPaused",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties, or by setting a delegate that conforms to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The delegate receives significant events as they occur during speech synthesis.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "code": "AVSpeechSynthesizer",
              "type": "codeVoice"
            },
            {
              "text": " also controls the route where the speech plays. For more information, see Directing speech output.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The system doesn’t automatically retain the speech synthesizer, so you need to manually retain it until speech concludes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechBoundary": {
      "abstract": [
        {
          "text": "Specifies when to pause or stop speech.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSpeechBoundary"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechBoundary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechBoundary"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechBoundary",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechboundary"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice": {
      "abstract": [
        {
          "text": "A distinct voice for use in speech synthesis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisVoice"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisVoice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisVoice"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesisVoice",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesisvoice"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer": {
      "abstract": [
        {
          "text": "An object that produces synthesized speech from text utterances and enables monitoring or controlling of ongoing speech.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesizer"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesizer"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesizer",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/BufferCallback": {
      "abstract": [
        {
          "text": "A type that defines a callback that receives a buffer of generated speech.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BufferCallback"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/BufferCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BufferCallback"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesizer.BufferCallback",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/buffercallback"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/MarkerCallback": {
      "abstract": [
        {
          "text": "A type that defines a callback that receives speech markers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MarkerCallback"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/MarkerCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MarkerCallback"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesizer.MarkerCallback",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/markercallback"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/PersonalVoiceAuthorizationStatus-swift.enum": {
      "abstract": [
        {
          "text": "An enumeration that models the personal voices authorization status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PersonalVoiceAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/PersonalVoiceAuthorizationStatus-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PersonalVoiceAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesizer.PersonalVoiceAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/personalvoiceauthorizationstatus-swift.enum"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/availableVoicesDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that indicates a change in available voices for speech synthesis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableVoicesDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/availableVoicesDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisAvailableVoicesDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "availableVoicesDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/availablevoicesdidchangenotification"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/continueSpeaking()": {
      "abstract": [
        {
          "text": "Resumes speech from its paused point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continueSpeaking"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/continueSpeaking()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "continueSpeaking"
        }
      ],
      "role": "symbol",
      "title": "continueSpeaking()",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/continuespeaking()"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/delegate": {
      "abstract": [
        {
          "text": "The delegate object for the speech synthesizer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVSpeechSynthesizerDelegate",
          "text": "AVSpeechSynthesizerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/delegate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/isPaused": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a speech synthesizer is in a paused state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPaused"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/isPaused",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paused"
        }
      ],
      "role": "symbol",
      "title": "isPaused",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/ispaused"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/isSpeaking": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the speech synthesizer is speaking or is in a paused state and has utterances to speak.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSpeaking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/isSpeaking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "speaking"
        }
      ],
      "role": "symbol",
      "title": "isSpeaking",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/isspeaking"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/mixToTelephonyUplink": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether to send synthesized speech to an active call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mixToTelephonyUplink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/mixToTelephonyUplink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mixToTelephonyUplink"
        }
      ],
      "role": "symbol",
      "title": "mixToTelephonyUplink",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/mixtotelephonyuplink"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/outputChannels": {
      "abstract": [
        {
          "text": "An array of audio session channels to route generated speech.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputChannels"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSessionChannelDescription",
          "text": "AVAudioSessionChannelDescription"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/outputChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputChannels"
        }
      ],
      "role": "symbol",
      "title": "outputChannels",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/outputchannels"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/pauseSpeaking(at:)": {
      "abstract": [
        {
          "text": "Pauses speech at the boundary you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pauseSpeaking"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVSpeechBoundary",
          "text": "AVSpeechBoundary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/pauseSpeaking(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pauseSpeakingAtBoundary:"
        }
      ],
      "role": "symbol",
      "title": "pauseSpeaking(at:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/pausespeaking(at:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/personalVoiceAuthorizationStatus-swift.type.property": {
      "abstract": [
        {
          "text": "Your app’s authorization to use personal voices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "personalVoiceAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesizer",
          "text": "AVSpeechSynthesizer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVSpeechSynthesisPersonalVoiceAuthorizationStatus",
          "text": "PersonalVoiceAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/personalVoiceAuthorizationStatus-swift.type.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "personalVoiceAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "personalVoiceAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/personalvoiceauthorizationstatus-swift.type.property"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/requestPersonalVoiceAuthorization(completionHandler:)": {
      "abstract": [
        {
          "text": "Prompts the user to authorize your app to use personal voices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestPersonalVoiceAuthorization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesizer",
          "text": "AVSpeechSynthesizer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVSpeechSynthesisPersonalVoiceAuthorizationStatus",
          "text": "PersonalVoiceAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/requestPersonalVoiceAuthorization(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestPersonalVoiceAuthorizationWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestPersonalVoiceAuthorization(completionHandler:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/requestpersonalvoiceauthorization(completionhandler:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/speak(_:)": {
      "abstract": [
        {
          "text": "Adds the utterance you specify to the speech synthesizer’s queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speak"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechUtterance",
          "text": "AVSpeechUtterance"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/speak(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "speakUtterance:"
        }
      ],
      "role": "symbol",
      "title": "speak(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/speak(_:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/stopSpeaking(at:)": {
      "abstract": [
        {
          "text": "Stops speech at the boundary you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopSpeaking"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVSpeechBoundary",
          "text": "AVSpeechBoundary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/stopSpeaking(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopSpeakingAtBoundary:"
        }
      ],
      "role": "symbol",
      "title": "stopSpeaking(at:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/stopspeaking(at:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/usesApplicationAudioSession": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether the app manages the audio session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usesApplicationAudioSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/usesApplicationAudioSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usesApplicationAudioSession"
        }
      ],
      "role": "symbol",
      "title": "usesApplicationAudioSession",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/usesapplicationaudiosession"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/write(_:toBufferCallback:)": {
      "abstract": [
        {
          "text": "Generates speech for the utterance and invokes the callback with the audio buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "write"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechUtterance",
          "text": "AVSpeechUtterance"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toBufferCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesizer",
          "text": "AVSpeechSynthesizer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVSpeechSynthesizerBufferCallback",
          "text": "BufferCallback"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/write(_:toBufferCallback:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeUtterance:toBufferCallback:"
        }
      ],
      "role": "symbol",
      "title": "write(_:toBufferCallback:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/write(_:tobuffercallback:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/write(_:toBufferCallback:toMarkerCallback:)": {
      "abstract": [
        {
          "text": "Generates audio buffers and associated metadata for storage or further speech synthesis processing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "write"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechUtterance",
          "text": "AVSpeechUtterance"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toBufferCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesizer",
          "text": "AVSpeechSynthesizer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVSpeechSynthesizerBufferCallback",
          "text": "BufferCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toMarkerCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesizer",
          "text": "AVSpeechSynthesizer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVSpeechSynthesizerMarkerCallback",
          "text": "MarkerCallback"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/write(_:toBufferCallback:toMarkerCallback:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeUtterance:toBufferCallback:toMarkerCallback:"
        }
      ],
      "role": "symbol",
      "title": "write(_:toBufferCallback:toMarkerCallback:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizer/write(_:tobuffercallback:tomarkercallback:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate": {
      "abstract": [
        {
          "text": "A delegate protocol that contains optional methods you can implement to respond to events that occur during speech synthesis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesizerDelegate"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesizerDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesizerDelegate",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesizerdelegate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechUtterance": {
      "abstract": [
        {
          "text": "An object that encapsulates the text for speech synthesis and parameters that affect the speech.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSpeechUtterance"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechUtterance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechUtterance"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechUtterance",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechutterance"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechUtterance/preUtteranceDelay": {
      "abstract": [
        {
          "text": "The amount of time the speech synthesizer pauses before speaking the utterance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preUtteranceDelay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechUtterance/preUtteranceDelay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preUtteranceDelay"
        }
      ],
      "role": "symbol",
      "title": "preUtteranceDelay",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechutterance/preutterancedelay"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechUtterance/voice": {
      "abstract": [
        {
          "text": "The voice the speech synthesizer uses when speaking the utterance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSpeechSynthesisVoice",
          "text": "AVSpeechSynthesisVoice"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechUtterance/voice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "voice"
        }
      ],
      "role": "symbol",
      "title": "voice",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechutterance/voice"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Controlling-speech",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/speak(_:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/continueSpeaking()",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/pauseSpeaking(at:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/stopSpeaking(at:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechBoundary"
      ],
      "title": "Controlling speech"
    },
    {
      "anchor": "Inspecting-a-speech-synthesizer",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/isSpeaking",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/isPaused"
      ],
      "title": "Inspecting a speech synthesizer"
    },
    {
      "anchor": "Managing-the-delegate",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/delegate",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate"
      ],
      "title": "Managing the delegate"
    },
    {
      "anchor": "Directing-speech-output",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/usesApplicationAudioSession",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/mixToTelephonyUplink",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/outputChannels",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/write(_:toBufferCallback:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/BufferCallback",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/write(_:toBufferCallback:toMarkerCallback:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/MarkerCallback"
      ],
      "title": "Directing speech output"
    },
    {
      "anchor": "Enabling-personal-voices",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/personalVoiceAuthorizationStatus-swift.type.property",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/availableVoicesDidChangeNotification",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/requestPersonalVoiceAuthorization(completionHandler:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/PersonalVoiceAuthorizationStatus-swift.enum"
      ],
      "title": "Enabling personal voices"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVSpeechSynthesizer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Controlling-speech",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/speak(_:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/continueSpeaking()",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/pauseSpeaking(at:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/stopSpeaking(at:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechBoundary"
              ],
              "title": "Controlling speech"
            },
            {
              "anchor": "Inspecting-a-speech-synthesizer",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/isSpeaking",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/isPaused"
              ],
              "title": "Inspecting a speech synthesizer"
            },
            {
              "anchor": "Managing-the-delegate",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/delegate",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizerDelegate"
              ],
              "title": "Managing the delegate"
            },
            {
              "anchor": "Directing-speech-output",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/usesApplicationAudioSession",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/mixToTelephonyUplink",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/outputChannels",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/write(_:toBufferCallback:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/BufferCallback",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/write(_:toBufferCallback:toMarkerCallback:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/MarkerCallback"
              ],
              "title": "Directing speech output"
            },
            {
              "anchor": "Enabling-personal-voices",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/personalVoiceAuthorizationStatus-swift.type.property",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/availableVoicesDidChangeNotification",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/requestPersonalVoiceAuthorization(completionHandler:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesizer/PersonalVoiceAuthorizationStatus-swift.enum"
              ],
              "title": "Enabling personal voices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVSpeechSynthesizer"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1outputChannels/title",
          "value": "outputChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1outputChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice/title",
          "value": "AVSpeechSynthesisVoice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisVoice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisVoice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1speak(_:)/title",
          "value": "speakUtterance:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1speak(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "speakUtterance:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1usesApplicationAudioSession/title",
          "value": "usesApplicationAudioSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1usesApplicationAudioSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usesApplicationAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1requestPersonalVoiceAuthorization(completionHandler:)/title",
          "value": "requestPersonalVoiceAuthorizationWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1requestPersonalVoiceAuthorization(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestPersonalVoiceAuthorizationWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1PersonalVoiceAuthorizationStatus-swift.enum/title",
          "value": "AVSpeechSynthesisPersonalVoiceAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1PersonalVoiceAuthorizationStatus-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisPersonalVoiceAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1PersonalVoiceAuthorizationStatus-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisPersonalVoiceAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1BufferCallback/title",
          "value": "AVSpeechSynthesizerBufferCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1BufferCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizerBufferCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1BufferCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizerBufferCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1pauseSpeaking(at:)/title",
          "value": "pauseSpeakingAtBoundary:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1pauseSpeaking(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pauseSpeakingAtBoundary:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1MarkerCallback/title",
          "value": "AVSpeechSynthesizerMarkerCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1MarkerCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizerMarkerCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1MarkerCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizerMarkerCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1availableVoicesDidChangeNotification/title",
          "value": "AVSpeechSynthesisAvailableVoicesDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1availableVoicesDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisAvailableVoicesDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechBoundary/title",
          "value": "AVSpeechBoundary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechBoundary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechBoundary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechBoundary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechBoundary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer/title",
          "value": "AVSpeechSynthesizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1write(_:toBufferCallback:)/title",
          "value": "writeUtterance:toBufferCallback:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1write(_:toBufferCallback:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeUtterance:toBufferCallback:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1write(_:toBufferCallback:toMarkerCallback:)/title",
          "value": "writeUtterance:toBufferCallback:toMarkerCallback:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1write(_:toBufferCallback:toMarkerCallback:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeUtterance:toBufferCallback:toMarkerCallback:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1continueSpeaking()/title",
          "value": "continueSpeaking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1continueSpeaking()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "continueSpeaking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate/title",
          "value": "AVSpeechSynthesizerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesizerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1personalVoiceAuthorizationStatus-swift.type.property/title",
          "value": "personalVoiceAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1personalVoiceAuthorizationStatus-swift.type.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "personalVoiceAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1isPaused/title",
          "value": "paused"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1isPaused/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paused"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechUtterance/title",
          "value": "AVSpeechUtterance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechUtterance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechUtterance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechUtterance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechUtterance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechUtterance~1preUtteranceDelay/title",
          "value": "preUtteranceDelay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechUtterance~1preUtteranceDelay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preUtteranceDelay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechUtterance~1voice/title",
          "value": "voice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechUtterance~1voice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "voice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1stopSpeaking(at:)/title",
          "value": "stopSpeakingAtBoundary:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1stopSpeaking(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopSpeakingAtBoundary:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1mixToTelephonyUplink/title",
          "value": "mixToTelephonyUplink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1mixToTelephonyUplink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mixToTelephonyUplink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1isSpeaking/title",
          "value": "speaking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesizer~1isSpeaking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "speaking"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avspeechsynthesizer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avspeechsynthesizer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
