{
  "abstract": [
    {
      "text": "Add custom audio-effect processing to apps like Logic Pro X and GarageBand by creating Audio Unit (AU) plug-ins.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/creating-custom-audio-effects"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "17.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "17.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "15.4",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Creating custom audio effects"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample app shows you how to create a custom audio effect plug-in using the latest Audio Unit standard (AUv3). The AUv3 standard builds on the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " model, which means you deliver your plug-in as an extension that’s contained in an app distributed through the App Store or your own store.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sample Audio Unit is a low-pass filter that allows frequencies at or below the cutoff frequency to pass through to the output. It attenuates frequencies above this point. It also lets you change the filter’s resonance, which boosts or attenuates a narrow band of frequencies around the cutoff point. You set these values by moving the draggable point around the plug-in’s user interface, as shown in the figure below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "graph.png",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The project has targets for both iOS and macOS. Each platform’s main app target has two supporting targets: ",
              "type": "text"
            },
            {
              "code": "AUv3FilterExtension",
              "type": "codeVoice"
            },
            {
              "text": ", which contains the plug-in packaged as an Audio Unit extension, and ",
              "type": "text"
            },
            {
              "code": "AUv3FilterFramework",
              "type": "codeVoice"
            },
            {
              "text": ", which bundles the plug-in’s code and resources.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/incorporating-audio-effects-and-instruments",
                  "isActive": true,
                  "overridingTitle": "Incorporating Audio Effects and Instruments",
                  "overridingTitleInlineContent": [
                    {
                      "text": "Incorporating Audio Effects and Instruments",
                      "type": "text"
                    }
                  ],
                  "type": "reference"
                },
                {
                  "text": " for details on how you can use this Audio Unit extension in a host app.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Create-a-Custom-Audio-Effect-Plug-In",
          "level": 3,
          "text": "Create a Custom Audio Effect Plug-In",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The extension itself contains two primary pieces: an Audio Unit proper and a factory object that creates it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sample app’s Audio Unit is ",
              "type": "text"
            },
            {
              "code": "AUv3FilterDemo",
              "type": "codeVoice"
            },
            {
              "text": ". This is a Swift class that subclasses ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit",
              "isActive": true,
              "overridingTitle": "AUAudioUnit",
              "overridingTitleInlineContent": [
                {
                  "text": "AUAudioUnit",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " and defines the plug-in’s interface, including key features like its parameters, presets, and I/O busses. A class called ",
              "type": "text"
            },
            {
              "code": "FilterDSPKernel",
              "type": "codeVoice"
            },
            {
              "text": " provides the plug-in’s digital signal processing (DSP) logic, and is written in C++ to ensure real-time safety. Because Swift can’t talk directly to C++, the sample project also includes an Objective-C++ adapter class called ",
              "type": "text"
            },
            {
              "code": "FilterDSPKernelAdapter",
              "type": "codeVoice"
            },
            {
              "text": " to act as an intermediary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "AUv3FilterDemoViewController",
              "type": "codeVoice"
            },
            {
              "text": " is the Audio Unit’s main view controller. It adopts the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnitFactory",
              "isActive": true,
              "overridingTitle": "AUAudioUnitFactory",
              "overridingTitleInlineContent": [
                {
                  "text": "AUAudioUnitFactory",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " protocol and is responsible for creating new instances of your plug-in. You implement the protocol’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnitFactory/createAudioUnit(with:)",
              "isActive": true,
              "overridingTitle": "createAudioUnit(with:)",
              "overridingTitleInlineContent": [
                {
                  "text": "createAudioUnit(with:)",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " factory method to return a new instance of ",
              "type": "text"
            },
            {
              "code": "AUv3FilterDemo",
              "type": "codeVoice"
            },
            {
              "text": " when a host app requests it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "extension AUv3FilterDemoViewController: AUAudioUnitFactory {",
            "    public func createAudioUnit(with componentDescription: AudioComponentDescription) throws -> AUAudioUnit {",
            "        audioUnit = try AUv3FilterDemo(componentDescription: componentDescription, options: [])",
            "        return audioUnit!",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "To ensure glitch-free performance, your plug-in’s audio processing must occur in a real-time safe context. Don’t allocate memory, perform file I/O, take locks, or interact with the Swift or Objective-C runtimes when rendering audio.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Add-Custom-Parameters-to-Your-Audio-Unit",
          "level": 3,
          "text": "Add Custom Parameters to Your Audio Unit",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In most Audio Units, you’ll provide one or more parameters to configure the audio processing. Your Audio Unit arranges its parameters into a tree structure, provided by an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUParameterTree",
              "isActive": true,
              "overridingTitle": "AUParameterTree",
              "overridingTitleInlineContent": [
                {
                  "text": "AUParameterTree",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": ". This object represents the root node of the plug-in’s tree of parameters and parameter groupings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "AUv3FilterDemo",
              "type": "codeVoice"
            },
            {
              "text": " has parameters to control the filter’s cutoff frequency and resonance. You create its parameters using a factory method on ",
              "type": "text"
            },
            {
              "code": "AUParameterTree",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "private enum AUv3FilterParam: AUParameterAddress {",
            "    case cutoff, resonance",
            "}",
            "",
            "/// The parameter to control the cutoff frequency (12 Hz - 20 kHz).",
            "var cutoffParam: AUParameter = {",
            "    let parameter =",
            "        AUParameterTree.createParameter(withIdentifier: \"cutoff\",",
            "                                        name: \"Cutoff\",",
            "                                        address: AUv3FilterParam.cutoff.rawValue,",
            "                                        min: 12.0,",
            "                                        max: 20_000.0,",
            "                                        unit: .hertz,",
            "                                        unitName: nil,",
            "                                        flags: [.flag_IsReadable,",
            "                                                .flag_IsWritable,",
            "                                                .flag_CanRamp],",
            "                                        valueStrings: nil,",
            "                                        dependentParameters: nil)",
            "    // Set default value",
            "    parameter.value = 0.0",
            "",
            "    return parameter",
            "}()",
            "",
            "/// The parameter to control the cutoff frequency's resonance (+/-20 dB).",
            "var resonanceParam: AUParameter = {",
            "    let parameter =",
            "        AUParameterTree.createParameter(withIdentifier: \"resonance\",",
            "                                        name: \"Resonance\",",
            "                                        address: AUv3FilterParam.resonance.rawValue,",
            "                                        min: -20.0,",
            "                                        max: 20.0,",
            "                                        unit: .decibels,",
            "                                        unitName: nil,",
            "                                        flags: [.flag_IsReadable,",
            "                                                .flag_IsWritable,",
            "                                                .flag_CanRamp],",
            "                                        valueStrings: nil,",
            "                                        dependentParameters: nil)",
            "    // Set the default value.",
            "    parameter.value = 20_000.0",
            "",
            "    return parameter",
            "}()"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The cutoff parameter defines a frequency range between 12 Hz and 20 kHz, and the resonance parameter defines a decibel range between -20 dB and 20 dB. Each parameter is readable and writeable, and also supports ramping, which means you can modify its value over time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You arrange the parameters into a tree by creating an ",
              "type": "text"
            },
            {
              "code": "AUParameterTree",
              "type": "codeVoice"
            },
            {
              "text": " instance and setting them as the tree’s children.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Create the audio unit's tree of parameters.",
            "parameterTree = AUParameterTree.createTree(withChildren: [cutoffParam,",
            "                                                          resonanceParam])"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Next, you bind handlers to the parameter tree’s readable and writeable values by installing closures for its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUParameterNode/implementorValueObserver",
              "isActive": true,
              "overridingTitle": "implementorValueObserver",
              "overridingTitleInlineContent": [
                {
                  "text": "implementorValueObserver",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUParameterNode/implementorValueProvider",
              "isActive": true,
              "overridingTitle": "implementorValueProvider",
              "overridingTitleInlineContent": [
                {
                  "text": "implementorValueProvider",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUParameterNode/implementorStringFromValueCallback",
              "isActive": true,
              "overridingTitle": "implementorStringFromValueCallback",
              "overridingTitleInlineContent": [
                {
                  "text": "implementorStringFromValueCallback",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " properties. These closures delegate to the filter adapter instance, which in turn communicates with the underlying DSP logic.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// A closure for observing all externally generated parameter value changes.",
            "parameterTree.implementorValueObserver = { param, value in",
            "    kernelAdapter.setParameter(param, value: value)",
            "}",
            "",
            "// A closure for returning state of the requested parameter.",
            "parameterTree.implementorValueProvider = { param in",
            "    return kernelAdapter.value(for: param)",
            "}",
            "",
            "// A closure for returning the string representation of the requested parameter value.",
            "parameterTree.implementorStringFromValueCallback = { param, value in",
            "    switch param.address {",
            "    case AUv3FilterParam.cutoff.rawValue:",
            "        return String(format: \"%.f\", value ?? param.value)",
            "    case AUv3FilterParam.resonance.rawValue:",
            "        return String(format: \"%.2f\", value ?? param.value)",
            "    default:",
            "        return \"?\"",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Connect-the-Parameters-to-Your-User-Interface",
          "level": 3,
          "text": "Connect the Parameters to Your User Interface",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The sample app’s iOS and macOS targets each provide a platform-specific user interface. You use a shared view controller called ",
              "type": "text"
            },
            {
              "code": "AUv3FilterDemoViewController",
              "type": "codeVoice"
            },
            {
              "text": " to coordinate the communication between the user interface and the Audio Unit. Connect your user interface to the Audio Unit’s parameters in the ",
              "type": "text"
            },
            {
              "code": "connectViewToAU()",
              "type": "codeVoice"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "private func connectViewToAU() {",
            "    guard needsConnection, let paramTree = audioUnit?.parameterTree else { return }",
            "",
            "    // Find the cutoff and resonance parameters in the parameter tree.",
            "    guard let cutoff = paramTree.value(forKey: \"cutoff\") as? AUParameter,",
            "        let resonance = paramTree.value(forKey: \"resonance\") as? AUParameter else {",
            "            fatalError(\"Required AU parameters not found.\")",
            "    }",
            "",
            "    // Set the instance variables.",
            "    cutoffParameter = cutoff",
            "    resonanceParameter = resonance",
            "",
            "    // Observe major state changes like a user selecting a user preset.",
            "    observer = audioUnit?.observe(\\.allParameterValues) { object, change in",
            "        DispatchQueue.main.async {",
            "            self.updateUI()",
            "        }",
            "    }",
            "",
            "    // Observe value changes to the cutoff and resonance parameters.",
            "    parameterObserverToken =",
            "        paramTree.token(byAddingParameterObserver: { [weak self] address, value in",
            "            guard let self = self else { return }",
            "",
            "            // An arbitrary queue is calling this closure. Ensure",
            "            // all UI updates dispatch back to the main thread.",
            "            if [cutoff.address, resonance.address].contains(address) {",
            "                DispatchQueue.main.async {",
            "                    self.updateUI()",
            "                }",
            "            }",
            "        })",
            "",
            "    // Indicate the view and the audio unit have a connection.",
            "    needsConnection = false",
            "",
            "    // Sync the UI with the parameter state.",
            "    updateUI()",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "As shown above, in the ",
              "type": "text"
            },
            {
              "code": "connectViewToAU()",
              "type": "codeVoice"
            },
            {
              "text": " method, you find the Audio Unit’s parameter tree and retrieve its cutoff and resonance parameters. You also add an observer closure to update the user interface as the plug-in’s parameter values change.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-Factory-Presets",
          "level": 3,
          "text": "Add Factory Presets",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Most audio plug-ins provide a collection of preset values known as ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "factory presets",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ". A factory preset is a preconfigured arrangement of the plug-in’s parameter values that provide a useful starting point for further customization. A host app presents these presets in its user interface so the user can select them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code example shows how to define the factory presets and their associated values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "public override var factoryPresets: [AUAudioUnitPreset] {",
            "    return [",
            "        AUAudioUnitPreset(number: 0, name: \"Prominent\"),",
            "        AUAudioUnitPreset(number: 1, name: \"Bright\"),",
            "        AUAudioUnitPreset(number: 2, name: \"Warm\")",
            "    ]",
            "}",
            "",
            "private let factoryPresetValues:[(cutoff: AUValue, resonance: AUValue)] = [",
            "    (2500.0, 5.0),    // \"Prominent\"",
            "    (14_000.0, 12.0), // \"Bright\"",
            "    (384.0, -3.0)     // \"Warm\"",
            "]"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Support-User-Presets",
          "level": 3,
          "text": "Support User Presets",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Factory presets provide a useful starting point for further user customization, but users also want the ability to save their changes and create their own custom presets. ",
              "type": "text"
            },
            {
              "code": "AUAudioUnit",
              "type": "codeVoice"
            },
            {
              "text": " provides built-in support for user presets. To enable this support in your Audio Unit, override the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/supportsUserPresets",
              "isActive": true,
              "overridingTitle": "supportsUserPresets",
              "overridingTitleInlineContent": [
                {
                  "text": "supportsUserPresets",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " property to return ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "/// Indicates that this audio unit supports persisting user presets.",
            "public override var supportsUserPresets: Bool {",
            "    return true",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Opting in to support for user presets automatically enables your Audio Unit to load, save, and delete user presets. The default implementation of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/userPresets",
              "isActive": true,
              "overridingTitle": "userPresets",
              "overridingTitleInlineContent": [
                {
                  "text": "userPresets",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/saveUserPreset(_:)",
              "isActive": true,
              "overridingTitle": "saveUserPreset()",
              "overridingTitleInlineContent": [
                {
                  "text": "saveUserPreset()",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/deleteUserPreset(_:)",
              "isActive": true,
              "overridingTitle": "deleteUserPreset()",
              "overridingTitleInlineContent": [
                {
                  "text": "deleteUserPreset()",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " API reads from and writes to an internal store, but you’re free to override this property and methods if you want to directly manage the persistence behavior. For example, you can override the default behavior to persist user presets to an iCloud container or some other remote location.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Select-Factory-and-User-Presets",
          "level": 3,
          "text": "Select Factory and User Presets",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A host app selects a factory or user preset by setting the plug-in’s ",
              "type": "text"
            },
            {
              "code": "currentPreset",
              "type": "codeVoice"
            },
            {
              "text": " property. You override this property and take the appropriate action depending on the preset type selected. If the user selected a factory preset (a preset ",
              "type": "text"
            },
            {
              "code": "number",
              "type": "codeVoice"
            },
            {
              "text": " greater than ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": "), look up its associated values and set the parameter values accordingly. If the user selected a user preset (a preset ",
              "type": "text"
            },
            {
              "code": "number",
              "type": "codeVoice"
            },
            {
              "text": " less than ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": "), restore the preset’s parameter state by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/presetState(for:)",
              "isActive": true,
              "overridingTitle": "presetState(for:)",
              "overridingTitleInlineContent": [
                {
                  "text": "presetState(for:)",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " method and setting the returned data as the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/fullStateForDocument",
              "isActive": true,
              "overridingTitle": "fullStateForDocument",
              "overridingTitleInlineContent": [
                {
                  "text": "fullStateForDocument",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "private var _currentPreset: AUAudioUnitPreset?",
            "",
            "/// The currently selected preset.",
            "public override var currentPreset: AUAudioUnitPreset? {",
            "    get { return _currentPreset }",
            "    set {",
            "        // If the newValue is nil, return.",
            "        guard let preset = newValue else {",
            "            _currentPreset = nil",
            "            return",
            "        }",
            "        ",
            "        // Factory presets need to always have a number >= 0.",
            "        if preset.number >= 0 {",
            "            let values = factoryPresetValues[preset.number]",
            "            parameters!.setParameterValues(cutoff: values.cutoff, resonance: values.resonance)",
            "            _currentPreset = preset",
            "        }",
            "        // User presets are always negative.",
            "        else {",
            "            // Attempt to restore the archived state for this user preset.",
            "            do {",
            "                fullStateForDocument = try presetState(for: preset)",
            "                // Set the currentPreset after successfully restoring the state.",
            "                _currentPreset = preset",
            "            } catch {",
            "                print(\"Unable to restore set for preset \\(preset.name)\")",
            "            }",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Package-Your-Plug-In-to-Run-In-Process",
          "level": 3,
          "text": "Package Your Plug-In to Run In-Process",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Like all App Extensions, AUv3 plug-ins run ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "out-of-process",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " by default, which means the extension runs in a separate process from the host app, and all communication between the two occurs over interprocess communication (IPC). This model provides increased security and stability for the host app. For example, if an AUv3 plug-in crashes, the host app won’t crash. However, the IPC communication adds a small amount of overhead to each render cycle, which may be unacceptable depending on the needs of a given application. In macOS only, you can package your plug-in to run ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "in-process",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", which eliminates the IPC communication as your Audio Unit runs as part of the host’s process.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Running an in-process plug-in requires an agreement between the host and the Audio Unit. The host requests in-process instantiation by passing the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AudioComponentInstantiationOptions/loadInProcess",
              "isActive": true,
              "overridingTitle": ".loadInProcess",
              "overridingTitleInlineContent": [
                {
                  "text": ".loadInProcess",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " option during the plug-in’s creation, and you need to package your Audio Unit as described and shown below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Your extension’s main binary can’t be dynamically loaded into another app, which means all executable code needs to reside in a separate framework bundle. However, the extension target still needs to contain at least one source file for the extension binary to be created, properly loaded, and linked with the framework bundle. To ensure the extension is created, add some unused placeholder code in your extension target, like that found in ",
              "type": "text"
            },
            {
              "code": "AUv3FilterExtension.swift",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import AUv3FilterFramework",
            "",
            "func placeholder() {",
            "    // This placeholder function ensures the extension loads correctly.",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The macOS sample packages all of the Audio Unit’s code into the ",
              "type": "text"
            },
            {
              "code": "AUv3FilterFramework",
              "type": "codeVoice"
            },
            {
              "text": " target. You indicate that the extension’s code exists in a separate bundle by adding an ",
              "type": "text"
            },
            {
              "code": "AudioComponentBundle",
              "type": "codeVoice"
            },
            {
              "text": " extension attribute to the target’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<key>NSExtension</key>",
            "<dict>",
            "    <key>NSExtensionAttributes</key>",
            "    <dict>",
            "        <key>AudioComponentBundle</key>",
            "        <string>com.example.apple-samplecode.AUv3FilterFramework</string>",
            "        ...",
            "    </dict>",
            "    ...",
            "</dict>"
          ],
          "syntax": null,
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If you’re using a xib or Storyboard for your user interface, override your view controller’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSViewController/init(nibName:bundle:)",
              "isActive": true,
              "overridingTitle": "init(nibName:bundle:)",
              "overridingTitleInlineContent": [
                {
                  "text": "init(nibName:bundle:)",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " initializer and pass the framework bundle to the superclass initializer. This ensures your user interface properly loads when the system requests your Audio Unit extension.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "public override init(nibName: NSNib.Name?, bundle: Bundle?) {",
            "    // Pass a reference to the owning framework bundle.",
            "    super.init(nibName: nibName, bundle: Bundle(for: type(of: self)))",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Finally, in the extension’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file, set the Audio Unit’s factory object, ",
              "type": "text"
            },
            {
              "code": "AUv3FilterDemoViewController",
              "type": "codeVoice"
            },
            {
              "text": ", as the extension’s principal class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<key>NSExtension</key>",
            "<dict>",
            "    <key>NSExtensionPrincipalClass</key>",
            "    <string>AUv3FilterFramework.AUv3FilterDemoViewController</string>",
            "    ...",
            "</dict>"
          ],
          "syntax": null,
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/incorporating-audio-effects-and-instruments",
                  "isActive": true,
                  "overridingTitle": "Incorporating Audio Effects and Instruments",
                  "overridingTitleInlineContent": [
                    {
                      "text": "Incorporating Audio Effects and Instruments",
                      "type": "text"
                    }
                  ],
                  "type": "reference"
                },
                {
                  "text": " for a host app you can use to load your plug-in both in-process and out-of-process.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "01d31f3fd2d8/CreatingCustomAudioEffects.zip": {
      "checksum": "01d31f3fd2d8e701a646f3350eef718a728ebc68a819b2e0bccfb09e74d3da86814fb0ec5648723ec93276b57332d5b3f24fe153d3fccb0747fca9b3fdd83d55",
      "identifier": "01d31f3fd2d8/CreatingCustomAudioEffects.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/01d31f3fd2d8/CreatingCustomAudioEffects.zip"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine": {
      "abstract": [
        {
          "text": "Perform advanced real-time and offline audio processing, implement 3D spatialization, and work with MIDI and samplers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Engine",
      "type": "topic",
      "url": "/documentation/avfaudio/audio-engine"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/audio-units": {
      "abstract": [
        {
          "text": "The data type for a plug-in component that provides audio processing or audio data generation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/audio-units",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Units",
      "type": "topic",
      "url": "/documentation/avfaudio/audio-units"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSViewController/init(nibName:bundle:)": {
      "abstract": [
        {
          "text": "Returns a view controller object initialized to the nib file in the specified bundle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "nibName"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "nibNameOrNil"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNib",
          "text": "NSNib"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNibName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "bundle"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "nibBundleOrNil"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBundle",
          "text": "Bundle"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSViewController/init(nibName:bundle:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(nibName:bundle:)",
      "type": "topic",
      "url": "/documentation/AppKit/NSViewController/init(nibName:bundle:)"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit": {
      "abstract": [
        {
          "text": "A class that defines a host’s interface to an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnit"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUAudioUnit",
      "type": "topic",
      "url": "/documentation/AudioToolbox/AUAudioUnit"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/deleteUserPreset(_:)": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteUserPreset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "userPreset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AUAudioUnitPreset",
          "text": "AUAudioUnitPreset"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/deleteUserPreset(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "deleteUserPreset(_:)",
      "type": "topic",
      "url": "/documentation/AudioToolbox/AUAudioUnit/deleteUserPreset(_:)"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/fullStateForDocument": {
      "abstract": [
        {
          "text": "A persistable snapshot of the audio unit’s properties and parameters, suitable for saving in a user’s document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullStateForDocument"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/fullStateForDocument",
      "kind": "symbol",
      "role": "symbol",
      "title": "fullStateForDocument",
      "type": "topic",
      "url": "/documentation/AudioToolbox/AUAudioUnit/fullStateForDocument"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/presetState(for:)": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presetState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "userPreset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AUAudioUnitPreset",
          "text": "AUAudioUnitPreset"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/presetState(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "presetState(for:)",
      "type": "topic",
      "url": "/documentation/AudioToolbox/AUAudioUnit/presetState(for:)"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/saveUserPreset(_:)": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saveUserPreset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "userPreset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AUAudioUnitPreset",
          "text": "AUAudioUnitPreset"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/saveUserPreset(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "saveUserPreset(_:)",
      "type": "topic",
      "url": "/documentation/AudioToolbox/AUAudioUnit/saveUserPreset(_:)"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/supportsUserPresets": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsUserPresets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/supportsUserPresets",
      "kind": "symbol",
      "role": "symbol",
      "title": "supportsUserPresets",
      "type": "topic",
      "url": "/documentation/AudioToolbox/AUAudioUnit/supportsUserPresets"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/userPresets": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userPresets"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AUAudioUnitPreset",
          "text": "AUAudioUnitPreset"
        },
        {
          "kind": "text",
          "text": "] { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/userPresets",
      "kind": "symbol",
      "role": "symbol",
      "title": "userPresets",
      "type": "topic",
      "url": "/documentation/AudioToolbox/AUAudioUnit/userPresets"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnitFactory": {
      "abstract": [
        {
          "text": "An object that creates a version 3 audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnitFactory"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSExtensionRequestHandling",
          "text": "NSExtensionRequestHandling"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnitFactory",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUAudioUnitFactory",
      "type": "topic",
      "url": "/documentation/AudioToolbox/AUAudioUnitFactory"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnitFactory/createAudioUnit(with:)": {
      "abstract": [
        {
          "text": "Creates an instance of an extension’s audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createAudioUnit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "desc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioComponentDescription",
          "text": "AudioComponentDescription"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AUAudioUnit",
          "text": "AUAudioUnit"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnitFactory/createAudioUnit(with:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "createAudioUnit(with:)",
      "type": "topic",
      "url": "/documentation/AudioToolbox/AUAudioUnitFactory/createAudioUnit(with:)"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/AUParameterNode/implementorStringFromValueCallback": {
      "abstract": [
        {
          "text": "The callback for providing a string representation of a parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "implementorStringFromValueCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUImplementorStringFromValueCallback",
          "text": "AUImplementorStringFromValueCallback"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUParameterNode/implementorStringFromValueCallback",
      "kind": "symbol",
      "role": "symbol",
      "title": "implementorStringFromValueCallback",
      "type": "topic",
      "url": "/documentation/AudioToolbox/AUParameterNode/implementorStringFromValueCallback"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/AUParameterNode/implementorValueObserver": {
      "abstract": [
        {
          "text": "The callback for parameter value changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "implementorValueObserver"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUImplementorValueObserver",
          "text": "AUImplementorValueObserver"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUParameterNode/implementorValueObserver",
      "kind": "symbol",
      "role": "symbol",
      "title": "implementorValueObserver",
      "type": "topic",
      "url": "/documentation/AudioToolbox/AUParameterNode/implementorValueObserver"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/AUParameterNode/implementorValueProvider": {
      "abstract": [
        {
          "text": "The callback for refreshing known stale values in a parameter tree.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "implementorValueProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUImplementorValueProvider",
          "text": "AUImplementorValueProvider"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUParameterNode/implementorValueProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "implementorValueProvider",
      "type": "topic",
      "url": "/documentation/AudioToolbox/AUParameterNode/implementorValueProvider"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/AUParameterTree": {
      "abstract": [
        {
          "text": "An object that represents a top-level group node that contains all of an audio unit’s parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUParameterTree"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUParameterTree",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUParameterTree",
      "type": "topic",
      "url": "/documentation/AudioToolbox/AUParameterTree"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/AudioComponentInstantiationOptions/loadInProcess": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadInProcess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioComponentInstantiationOptions",
          "text": "AudioComponentInstantiationOptions"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AudioComponentInstantiationOptions/loadInProcess",
      "kind": "symbol",
      "role": "symbol",
      "title": "loadInProcess",
      "type": "topic",
      "url": "/documentation/AudioToolbox/AudioComponentInstantiationOptions/loadInProcess"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/incorporating-audio-effects-and-instruments": {
      "abstract": [
        {
          "text": "Add custom audio processing and MIDI instruments to your app by hosting Audio Unit (AU) plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/incorporating-audio-effects-and-instruments",
      "kind": "article",
      "role": "sampleCode",
      "title": "Incorporating Audio Effects and Instruments",
      "type": "topic",
      "url": "/documentation/AudioToolbox/incorporating-audio-effects-and-instruments"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "graph.png": {
      "alt": "plug-in User Interface",
      "identifier": "graph.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/77036aca41724e5409050b93ab4a5b9c/graph.png"
        }
      ]
    },
    "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG",
      "title": "App Extensions",
      "titleInlineContent": [
        {
          "text": "App Extensions",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "01d31f3fd2d8/CreatingCustomAudioEffects.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Effects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/audio-units"
      ],
      "title": "Effects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Effects",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/audio-units"
              ],
              "title": "Effects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUAudioUnit~1supportsUserPresets/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "supportsUserPresets"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUAudioUnit~1userPresets/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "atomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<AUAudioUnitPreset *>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "userPresets"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUAudioUnit~1presetState(for:)/title",
          "value": "presetStateFor:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUAudioUnit~1presetState(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
              "text": "NSDictionary<NSString *,id>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "presetStateFor:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AUAudioUnitPreset",
              "text": "AUAudioUnitPreset"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "userPreset"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "error:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSError",
              "text": "NSError"
            },
            {
              "kind": "text",
              "text": " * *) "
            },
            {
              "kind": "internalParam",
              "text": "outError"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AudioComponentInstantiationOptions~1loadInProcess/title",
          "value": "kAudioComponentInstantiation_LoadInProcess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AudioComponentInstantiationOptions~1loadInProcess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioComponentInstantiation_LoadInProcess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUAudioUnitFactory/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUAudioUnitFactory"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSExtensionRequestHandling",
              "text": "NSExtensionRequestHandling"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUAudioUnit~1saveUserPreset(_:)/title",
          "value": "saveUserPreset:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUAudioUnit~1saveUserPreset(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "saveUserPreset:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AUAudioUnitPreset",
              "text": "AUAudioUnitPreset"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "userPreset"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "error:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSError",
              "text": "NSError"
            },
            {
              "kind": "text",
              "text": " * *) "
            },
            {
              "kind": "internalParam",
              "text": "outError"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUAudioUnit~1fullStateForDocument/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "atomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
              "text": "NSDictionary<NSString *,id>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "fullStateForDocument"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUAudioUnit/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUAudioUnit"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUParameterTree/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUParameterTree"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AUParameterGroup",
              "text": "AUParameterGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUParameterNode~1implementorStringFromValueCallback/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AUImplementorStringFromValueCallback",
              "text": "AUImplementorStringFromValueCallback"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "implementorStringFromValueCallback"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUParameterNode~1implementorValueObserver/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AUImplementorValueObserver",
              "text": "AUImplementorValueObserver"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "implementorValueObserver"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUAudioUnit~1deleteUserPreset(_:)/title",
          "value": "deleteUserPreset:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUAudioUnit~1deleteUserPreset(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "deleteUserPreset:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AUAudioUnitPreset",
              "text": "AUAudioUnitPreset"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "userPreset"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "error:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSError",
              "text": "NSError"
            },
            {
              "kind": "text",
              "text": " * *) "
            },
            {
              "kind": "internalParam",
              "text": "outError"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUAudioUnitFactory~1createAudioUnit(with:)/title",
          "value": "createAudioUnitWithComponentDescription:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUAudioUnitFactory~1createAudioUnit(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AUAudioUnit",
              "text": "AUAudioUnit"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "createAudioUnitWithComponentDescription:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@AudioComponentDescription",
              "text": "AudioComponentDescription"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "desc"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "error:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSError",
              "text": "NSError"
            },
            {
              "kind": "text",
              "text": " * *) "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUParameterNode~1implementorValueProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "atomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AUImplementorValueProvider",
              "text": "AUImplementorValueProvider"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "implementorValueProvider"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSViewController~1init(nibName:bundle:)/title",
          "value": "initWithNibName:bundle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSViewController~1init(nibName:bundle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "initWithNibName:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSNibName",
              "text": "NSNibName"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "nibNameOrNil"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bundle:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSBundle",
              "text": "NSBundle"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "nibBundleOrNil"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/creating-custom-audio-effects"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/creating-custom-audio-effects"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
