{
  "abstract": [
    {
      "text": "Review unsupported symbols and their replacements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated Symbols"
  },
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/1616458-interruption-flags": {
      "abstract": [
        {
          "text": "Constants that indicate the state of the audio session following an interruption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/1616458-interruption-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Interruption flags",
      "type": "topic",
      "url": "/documentation/avfaudio/1616458-interruption-flags"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession": {
      "abstract": [
        {
          "text": "An object that communicates to the system how you intend to use audio in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/currentHardwareInputNumberOfChannels": {
      "abstract": [
        {
          "text": "The number of audio hardware input channels.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentHardwareInputNumberOfChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/currentHardwareInputNumberOfChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentHardwareInputNumberOfChannels"
        }
      ],
      "role": "symbol",
      "title": "currentHardwareInputNumberOfChannels",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/currenthardwareinputnumberofchannels"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/currentHardwareOutputNumberOfChannels": {
      "abstract": [
        {
          "text": "The number of audio hardware output channels.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentHardwareOutputNumberOfChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/currentHardwareOutputNumberOfChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentHardwareOutputNumberOfChannels"
        }
      ],
      "role": "symbol",
      "title": "currentHardwareOutputNumberOfChannels",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/currenthardwareoutputnumberofchannels"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/currentHardwareSampleRate": {
      "abstract": [
        {
          "text": "The audio hardware sample rate, in hertz.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentHardwareSampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/currentHardwareSampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentHardwareSampleRate"
        }
      ],
      "role": "symbol",
      "title": "currentHardwareSampleRate",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/currenthardwaresamplerate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/delegate": {
      "abstract": [
        {
          "text": "The delegate object for the audio session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVAudioSessionDelegate",
          "text": "AVAudioSessionDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/delegate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/init": {
      "abstract": [
        {
          "text": "Gets a reference to the singleton audio session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/init",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/init"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/inputIsAvailable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a hardware audio input path is available.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputIsAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/inputIsAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputIsAvailable"
        }
      ],
      "role": "symbol",
      "title": "inputIsAvailable",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/inputisavailable"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredHardwareSampleRate": {
      "abstract": [
        {
          "text": "The preferred hardware sample rate, in hertz.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredHardwareSampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredHardwareSampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredHardwareSampleRate"
        }
      ],
      "role": "symbol",
      "title": "preferredHardwareSampleRate",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/preferredhardwaresamplerate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/recordPermission-swift.property": {
      "abstract": [
        {
          "text": "The current recording permission status.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordPermission"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioSessionRecordPermission",
          "text": "RecordPermission"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/recordPermission-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordPermission"
        }
      ],
      "role": "symbol",
      "title": "recordPermission",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/recordpermission-swift.property"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/requestRecordPermission(_:)": {
      "abstract": [
        {
          "text": "Requests the user’s permission to record audio.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestRecordPermission"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/requestRecordPermission(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestRecordPermission:"
        }
      ],
      "role": "symbol",
      "title": "requestRecordPermission(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/requestrecordpermission(_:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setActive(_:withFlags:)": {
      "abstract": [
        {
          "text": "Activates or deactivates your app’s audio session; provides flags for use by other audio sessions.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setActive"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setActive(_:withFlags:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setActive:withFlags:error:"
        }
      ],
      "role": "symbol",
      "title": "setActive(_:withFlags:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/setactive(_:withflags:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredHardwareSampleRate(_:)": {
      "abstract": [
        {
          "text": "Sets the preferred hardware sample rate for input and output.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPreferredHardwareSampleRate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredHardwareSampleRate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPreferredHardwareSampleRate:error:"
        }
      ],
      "role": "symbol",
      "title": "setPreferredHardwareSampleRate(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/setpreferredhardwaresamplerate(_:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionDelegate": {
      "abstract": [
        {
          "text": "A protocol that defines responses to changes in state for the audio session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSessionDelegate"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSessionDelegate",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosessiondelegate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Activating-an-audio-session",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setActive(_:withFlags:)"
      ],
      "title": "Activating an audio session"
    },
    {
      "anchor": "Requesting-permission-to-record",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/recordPermission-swift.property",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/requestRecordPermission(_:)"
      ],
      "title": "Requesting permission to record"
    },
    {
      "anchor": "Inspecting-audio-hardware",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/currentHardwareInputNumberOfChannels",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/currentHardwareOutputNumberOfChannels",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/currentHardwareSampleRate",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/inputIsAvailable",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredHardwareSampleRate",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredHardwareSampleRate(_:)"
      ],
      "title": "Inspecting audio hardware"
    },
    {
      "anchor": "Responding-to-audio-session-changes",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/delegate",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionDelegate"
      ],
      "title": "Responding to audio session changes"
    },
    {
      "anchor": "Handling-audio-session-interruptions",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/1616458-interruption-flags"
      ],
      "title": "Handling audio session interruptions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Activating-an-audio-session",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setActive(_:withFlags:)"
              ],
              "title": "Activating an audio session"
            },
            {
              "anchor": "Requesting-permission-to-record",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/recordPermission-swift.property",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/requestRecordPermission(_:)"
              ],
              "title": "Requesting permission to record"
            },
            {
              "anchor": "Inspecting-audio-hardware",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/currentHardwareInputNumberOfChannels",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/currentHardwareOutputNumberOfChannels",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/currentHardwareSampleRate",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/inputIsAvailable",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/preferredHardwareSampleRate",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setPreferredHardwareSampleRate(_:)"
              ],
              "title": "Inspecting audio hardware"
            },
            {
              "anchor": "Responding-to-audio-session-changes",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/delegate",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionDelegate"
              ],
              "title": "Responding to audio session changes"
            },
            {
              "anchor": "Handling-audio-session-interruptions",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/1616458-interruption-flags"
              ],
              "title": "Handling audio session interruptions"
            },
            {
              "anchor": "Initializers",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/init"
              ],
              "title": "Initializers"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1preferredHardwareSampleRate/title",
          "value": "preferredHardwareSampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1preferredHardwareSampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredHardwareSampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1requestRecordPermission(_:)/title",
          "value": "requestRecordPermission:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1requestRecordPermission(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestRecordPermission:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1recordPermission-swift.property/title",
          "value": "recordPermission"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1recordPermission-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recordPermission"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setActive(_:withFlags:)/title",
          "value": "setActive:withFlags:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setActive(_:withFlags:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setActive:withFlags:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1currentHardwareSampleRate/title",
          "value": "currentHardwareSampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1currentHardwareSampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentHardwareSampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/title",
          "value": "AVAudioSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1currentHardwareInputNumberOfChannels/title",
          "value": "currentHardwareInputNumberOfChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1currentHardwareInputNumberOfChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentHardwareInputNumberOfChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1currentHardwareOutputNumberOfChannels/title",
          "value": "currentHardwareOutputNumberOfChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1currentHardwareOutputNumberOfChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentHardwareOutputNumberOfChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSessionDelegate/title",
          "value": "AVAudioSessionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSessionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSessionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1inputIsAvailable/title",
          "value": "inputIsAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1inputIsAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputIsAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setPreferredHardwareSampleRate(_:)/title",
          "value": "setPreferredHardwareSampleRate:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setPreferredHardwareSampleRate(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPreferredHardwareSampleRate:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
