{
  "abstract": [
    {
      "text": "The constants that define the audio encoder settings for the audio recorder class.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine",
        "doc://com.apple.avfaudio/documentation/AVFAudio/audio-settings"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/encoder-settings"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Encoder Settings"
  },
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioQuality": {
      "abstract": [
        {
          "text": "The values that specify the sample rate audio quality for encoding and conversion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioQuality"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioQuality"
        }
      ],
      "role": "symbol",
      "title": "AVAudioQuality",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioquality"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderAudioQualityKey": {
      "abstract": [
        {
          "text": "A constant that represents an integer from the audio quality enumeration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVEncoderAudioQualityKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderAudioQualityKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVEncoderAudioQualityKey"
        }
      ],
      "role": "symbol",
      "title": "AVEncoderAudioQualityKey",
      "type": "topic",
      "url": "/documentation/avfaudio/avencoderaudioqualitykey"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderBitDepthHintKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVEncoderBitDepthHintKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderBitDepthHintKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVEncoderBitDepthHintKey"
        }
      ],
      "role": "symbol",
      "title": "AVEncoderBitDepthHintKey",
      "type": "topic",
      "url": "/documentation/avfaudio/avencoderbitdepthhintkey"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderBitRateKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVEncoderBitRateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderBitRateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVEncoderBitRateKey"
        }
      ],
      "role": "symbol",
      "title": "AVEncoderBitRateKey",
      "type": "topic",
      "url": "/documentation/avfaudio/avencoderbitratekey"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderBitRatePerChannelKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVEncoderBitRatePerChannelKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderBitRatePerChannelKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVEncoderBitRatePerChannelKey"
        }
      ],
      "role": "symbol",
      "title": "AVEncoderBitRatePerChannelKey",
      "type": "topic",
      "url": "/documentation/avfaudio/avencoderbitrateperchannelkey"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderBitRateStrategyKey": {
      "abstract": [
        {
          "text": "A constant that represents the bit rate strategy for the encoder to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVEncoderBitRateStrategyKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderBitRateStrategyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVEncoderBitRateStrategyKey"
        }
      ],
      "role": "symbol",
      "title": "AVEncoderBitRateStrategyKey",
      "type": "topic",
      "url": "/documentation/avfaudio/avencoderbitratestrategykey"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine": {
      "abstract": [
        {
          "text": "Perform advanced real-time and offline audio processing, implement 3D spatialization, and work with MIDI and samplers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Engine",
      "type": "topic",
      "url": "/documentation/avfaudio/audio-engine"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/audio-settings": {
      "abstract": [
        {
          "text": "Configure audio processing settings using standard key and value constants.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/audio-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio settings",
      "type": "topic",
      "url": "/documentation/avfaudio/audio-settings"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/sample-rate-conversion-settings": {
      "abstract": [
        {
          "text": "The constants that define sample rate converter audio quality settings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/sample-rate-conversion-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sample Rate Conversion Settings",
      "type": "topic",
      "url": "/documentation/avfaudio/sample-rate-conversion-settings"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/time-pitch-algorithm-settings": {
      "abstract": [
        {
          "text": "The constants that define the values for the time pitch algorithms.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/time-pitch-algorithm-settings",
      "kind": "article",
      "role": "article",
      "title": "Time Pitch Algorithm Settings",
      "type": "topic",
      "url": "/documentation/AVFoundation/time-pitch-algorithm-settings"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/sample-rate-conversion-settings",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioQuality",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderAudioQualityKey",
        "doc://com.apple.documentation/documentation/AVFoundation/time-pitch-algorithm-settings"
      ],
      "title": "Settings"
    }
  ],
  "topicSections": [
    {
      "anchor": "Settings",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderAudioQualityKey",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderBitRateKey",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderBitRatePerChannelKey",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderBitRateStrategyKey",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderBitDepthHintKey"
      ],
      "title": "Settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Settings",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderAudioQualityKey",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderBitRateKey",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderBitRatePerChannelKey",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderBitRateStrategyKey",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderBitDepthHintKey"
              ],
              "title": "Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/sample-rate-conversion-settings",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioQuality",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVEncoderAudioQualityKey",
                "doc://com.apple.documentation/documentation/AVFoundation/time-pitch-algorithm-settings"
              ],
              "title": "Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVEncoderBitDepthHintKey/title",
          "value": "AVEncoderBitDepthHintKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVEncoderBitDepthHintKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVEncoderBitDepthHintKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVEncoderBitRatePerChannelKey/title",
          "value": "AVEncoderBitRatePerChannelKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVEncoderBitRatePerChannelKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVEncoderBitRatePerChannelKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVEncoderBitRateStrategyKey/title",
          "value": "AVEncoderBitRateStrategyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVEncoderBitRateStrategyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVEncoderBitRateStrategyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVEncoderBitRateKey/title",
          "value": "AVEncoderBitRateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVEncoderBitRateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVEncoderBitRateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioQuality/title",
          "value": "AVAudioQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioQuality/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVEncoderAudioQualityKey/title",
          "value": "AVEncoderAudioQualityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVEncoderAudioQualityKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVEncoderAudioQualityKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/encoder-settings"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/encoder-settings"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
