{
  "abstract": [
    {
      "text": "The audio settings that apply to linear PCM audio formats.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine",
        "doc://com.apple.avfaudio/documentation/AVFAudio/audio-settings"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/linear-pcm-format-settings"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Linear PCM Format Settings"
  },
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout": {
      "abstract": [
        {
          "text": "An object that describes the roles of a set of audio channels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioChannelLayout"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "AVAudioChannelLayout",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiochannellayout"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioFormat": {
      "abstract": [
        {
          "text": "An object that describes the representation of an audio format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioFormat"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioFormat"
        }
      ],
      "role": "symbol",
      "title": "AVAudioFormat",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioformat"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVChannelLayoutKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVChannelLayoutKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVChannelLayoutKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVChannelLayoutKey"
        }
      ],
      "role": "symbol",
      "title": "AVChannelLayoutKey",
      "type": "topic",
      "url": "/documentation/avfaudio/avchannellayoutkey"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVLinearPCMBitDepthKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVLinearPCMBitDepthKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVLinearPCMBitDepthKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVLinearPCMBitDepthKey"
        }
      ],
      "role": "symbol",
      "title": "AVLinearPCMBitDepthKey",
      "type": "topic",
      "url": "/documentation/avfaudio/avlinearpcmbitdepthkey"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVLinearPCMIsBigEndianKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVLinearPCMIsBigEndianKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVLinearPCMIsBigEndianKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVLinearPCMIsBigEndianKey"
        }
      ],
      "role": "symbol",
      "title": "AVLinearPCMIsBigEndianKey",
      "type": "topic",
      "url": "/documentation/avfaudio/avlinearpcmisbigendiankey"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVLinearPCMIsFloatKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVLinearPCMIsFloatKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVLinearPCMIsFloatKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVLinearPCMIsFloatKey"
        }
      ],
      "role": "symbol",
      "title": "AVLinearPCMIsFloatKey",
      "type": "topic",
      "url": "/documentation/avfaudio/avlinearpcmisfloatkey"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVLinearPCMIsNonInterleaved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVLinearPCMIsNonInterleaved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVLinearPCMIsNonInterleaved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVLinearPCMIsNonInterleaved"
        }
      ],
      "role": "symbol",
      "title": "AVLinearPCMIsNonInterleaved",
      "type": "topic",
      "url": "/documentation/avfaudio/avlinearpcmisnoninterleaved"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine": {
      "abstract": [
        {
          "text": "Perform advanced real-time and offline audio processing, implement 3D spatialization, and work with MIDI and samplers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Engine",
      "type": "topic",
      "url": "/documentation/avfaudio/audio-engine"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/audio-settings": {
      "abstract": [
        {
          "text": "Configure audio processing settings using standard key and value constants.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/audio-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio settings",
      "type": "topic",
      "url": "/documentation/avfaudio/audio-settings"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/format-settings": {
      "abstract": [
        {
          "text": "The audio settings that apply to all audio formats that the audio player and recorder classes support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/format-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Settings",
      "type": "topic",
      "url": "/documentation/avfaudio/format-settings"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Formats",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioFormat",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVChannelLayoutKey",
        "doc://com.apple.avfaudio/documentation/AVFAudio/format-settings"
      ],
      "title": "Formats"
    }
  ],
  "topicSections": [
    {
      "anchor": "Settings",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVLinearPCMBitDepthKey",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVLinearPCMIsBigEndianKey",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVLinearPCMIsFloatKey",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVLinearPCMIsNonInterleaved"
      ],
      "title": "Settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Settings",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVLinearPCMBitDepthKey",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVLinearPCMIsBigEndianKey",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVLinearPCMIsFloatKey",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVLinearPCMIsNonInterleaved"
              ],
              "title": "Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Formats",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioFormat",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioChannelLayout",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVChannelLayoutKey",
                "doc://com.apple.avfaudio/documentation/AVFAudio/format-settings"
              ],
              "title": "Formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioChannelLayout/title",
          "value": "AVAudioChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioChannelLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioFormat/title",
          "value": "AVAudioFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVLinearPCMIsNonInterleaved/title",
          "value": "AVLinearPCMIsNonInterleaved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVLinearPCMIsNonInterleaved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVLinearPCMIsNonInterleaved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVChannelLayoutKey/title",
          "value": "AVChannelLayoutKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVChannelLayoutKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVChannelLayoutKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVLinearPCMIsBigEndianKey/title",
          "value": "AVLinearPCMIsBigEndianKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVLinearPCMIsBigEndianKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVLinearPCMIsBigEndianKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVLinearPCMBitDepthKey/title",
          "value": "AVLinearPCMBitDepthKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVLinearPCMBitDepthKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVLinearPCMBitDepthKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVLinearPCMIsFloatKey/title",
          "value": "AVLinearPCMIsFloatKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVLinearPCMIsFloatKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVLinearPCMIsFloatKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/linear-pcm-format-settings"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/linear-pcm-format-settings"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
