{
  "abstract": [
    {
      "text": "Add voice-processing capabilities to your app by using audio engine.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine",
        "doc://com.apple.avfaudio/documentation/AVFAudio/audio-units"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/using-voice-processing"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "17.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "17.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "15.4",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Using voice processing"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC 2019 session ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/videos/play/wwdc19/510/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Configure-the-Sample-Code-Project",
          "level": 3,
          "text": "Configure the Sample Code Project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Before you run the sample code project in Xcode, ensure you’re using iOS 17 or later.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "8599a413511b/UsingVoiceProcessing.zip": {
      "checksum": "8599a413511b5ec65151b21e0f8ffd96e7fd12db23ba4a638976ca8da2822e03314a5e9245b1de480d6de140075c177e1a253f13c8cac3c2c449cf2eebfa7a68",
      "identifier": "8599a413511b/UsingVoiceProcessing.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/8599a413511b/UsingVoiceProcessing.zip"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioPlayerNode": {
      "abstract": [
        {
          "text": "An object for scheduling the playback of buffers or segments of audio files.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioPlayerNode"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioPlayerNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioPlayerNode"
        }
      ],
      "role": "symbol",
      "title": "AVAudioPlayerNode",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioplayernode"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine": {
      "abstract": [
        {
          "text": "Perform advanced real-time and offline audio processing, implement 3D spatialization, and work with MIDI and samplers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/audio-engine",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Engine",
      "type": "topic",
      "url": "/documentation/avfaudio/audio-engine"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/audio-units": {
      "abstract": [
        {
          "text": "The data type for a plug-in component that provides audio processing or audio data generation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/audio-units",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Units",
      "type": "topic",
      "url": "/documentation/avfaudio/audio-units"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/playing-custom-audio-with-your-own-player": {
      "abstract": [
        {
          "text": "Construct an audio player to play your custom audio data, and optionally take advantage of the advanced features of AirPlay 2.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/playing-custom-audio-with-your-own-player",
      "kind": "article",
      "role": "sampleCode",
      "title": "Playing custom audio with your own player",
      "type": "topic",
      "url": "/documentation/avfaudio/playing-custom-audio-with-your-own-player"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/videos/play/wwdc19/510/": {
      "identifier": "https://developer.apple.com/videos/play/wwdc19/510/",
      "title": "510: What’s New in AVAudioEngine",
      "titleInlineContent": [
        {
          "text": "510: What’s New in AVAudioEngine",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc19/510/"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "8599a413511b/UsingVoiceProcessing.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Playback",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/playing-custom-audio-with-your-own-player",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioPlayerNode"
      ],
      "title": "Playback"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Playback",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/playing-custom-audio-with-your-own-player",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioPlayerNode"
              ],
              "title": "Playback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioPlayerNode/title",
          "value": "AVAudioPlayerNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioPlayerNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioPlayerNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioPlayerNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioPlayerNode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/using-voice-processing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/using-voice-processing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
