{
  "abstract": [
    {
      "text": "Tells the delegate when a routing event times out.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avrouting/documentation/AVRouting",
        "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:eventDidTimeOut:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)AVCustomRoutingControllerDelegate(im)customRoutingController:eventDidTimeOut:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "customRoutingController"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVCustomRoutingController",
        "text": "AVCustomRoutingController"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "eventDidTimeOut"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVCustomRoutingEvent",
        "text": "AVCustomRoutingEvent"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AVRouting"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "customRoutingController:eventDidTimeOut:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "customRoutingController(_:eventDidTimeOut:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "customRoutingController"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "controller"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVCustomRoutingController",
              "text": "AVCustomRoutingController"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "eventDidTimeOut"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "event"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingEvent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVCustomRoutingEvent",
              "text": "AVCustomRoutingEvent"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A custom routing controller.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "controller"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An event that times out.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "event"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Adopt this method to clean up any in-progress connection attempts.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avrouting/documentation/AVRouting": {
      "abstract": [
        {
          "text": "Display custom destinations to stream media in the system route picker.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avrouting/documentation/AVRouting",
      "kind": "symbol",
      "role": "collection",
      "title": "AVRouting",
      "type": "topic",
      "url": "/documentation/avrouting"
    },
    "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController": {
      "abstract": [
        {
          "text": "An object that manages the connection from a device to a destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCustomRoutingController"
        }
      ],
      "identifier": "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCustomRoutingController"
        }
      ],
      "role": "symbol",
      "title": "AVCustomRoutingController",
      "type": "topic",
      "url": "/documentation/avrouting/avcustomroutingcontroller"
    },
    "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate": {
      "abstract": [
        {
          "text": "A protocol for delegates of a custom routing controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCustomRoutingControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCustomRoutingControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVCustomRoutingControllerDelegate",
      "type": "topic",
      "url": "/documentation/avrouting/avcustomroutingcontrollerdelegate"
    },
    "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:didSelect:)": {
      "abstract": [
        {
          "text": "Tells the delegate when a user selects a custom item in the route picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customRoutingController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCustomRoutingController",
          "text": "AVCustomRoutingController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCustomRoutingActionItem",
          "text": "AVCustomRoutingActionItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:didSelect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "customRoutingController:didSelectItem:"
        }
      ],
      "role": "symbol",
      "title": "customRoutingController(_:didSelect:)",
      "type": "topic",
      "url": "/documentation/avrouting/avcustomroutingcontrollerdelegate/customroutingcontroller(_:didselect:)"
    },
    "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:eventDidTimeOut:)": {
      "abstract": [
        {
          "text": "Tells the delegate when a routing event times out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customRoutingController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCustomRoutingController",
          "text": "AVCustomRoutingController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "eventDidTimeOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCustomRoutingEvent",
          "text": "AVCustomRoutingEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:eventDidTimeOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "customRoutingController:eventDidTimeOut:"
        }
      ],
      "role": "symbol",
      "title": "customRoutingController(_:eventDidTimeOut:)",
      "type": "topic",
      "url": "/documentation/avrouting/avcustomroutingcontrollerdelegate/customroutingcontroller(_:eventdidtimeout:)"
    },
    "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:handle:completionHandler:)": {
      "abstract": [
        {
          "text": "Connects to, or disconnects from, a device when a user requests it in the picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customRoutingController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCustomRoutingController",
          "text": "AVCustomRoutingController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCustomRoutingEvent",
          "text": "AVCustomRoutingEvent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:handle:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "customRoutingController:handleEvent:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "customRoutingController(_:handle:completionHandler:)",
      "type": "topic",
      "url": "/documentation/avrouting/avcustomroutingcontrollerdelegate/customroutingcontroller(_:handle:completionhandler:)"
    },
    "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingEvent": {
      "abstract": [
        {
          "text": "An object that represents an event that occurs on a route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCustomRoutingEvent"
        }
      ],
      "identifier": "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCustomRoutingEvent"
        }
      ],
      "role": "symbol",
      "title": "AVCustomRoutingEvent",
      "type": "topic",
      "url": "/documentation/avrouting/avcustomroutingevent"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-controller-events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:handle:completionHandler:)",
        "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:didSelect:)"
      ],
      "title": "Handling controller events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "customRoutingController:eventDidTimeOut:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "customRoutingController:eventDidTimeOut:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avrouting/documentation/AVRouting",
                "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-controller-events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:handle:completionHandler:)",
                "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:didSelect:)"
              ],
              "title": "Handling controller events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "customRoutingController:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVCustomRoutingController",
                    "text": "AVCustomRoutingController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "controller"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "eventDidTimeOut:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingEvent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVCustomRoutingEvent",
                    "text": "AVCustomRoutingEvent"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "event"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A custom routing controller.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "controller"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An event that times out.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "event"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingControllerDelegate~1customRoutingController(_:eventDidTimeOut:)/title",
          "value": "customRoutingController:eventDidTimeOut:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingControllerDelegate~1customRoutingController(_:eventDidTimeOut:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "customRoutingController:eventDidTimeOut:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingControllerDelegate/title",
          "value": "AVCustomRoutingControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCustomRoutingControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCustomRoutingControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingEvent/title",
          "value": "AVCustomRoutingEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCustomRoutingEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCustomRoutingEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingController/title",
          "value": "AVCustomRoutingController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCustomRoutingController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCustomRoutingController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingControllerDelegate~1customRoutingController(_:handle:completionHandler:)/title",
          "value": "customRoutingController:handleEvent:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingControllerDelegate~1customRoutingController(_:handle:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "customRoutingController:handleEvent:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingControllerDelegate~1customRoutingController(_:didSelect:)/title",
          "value": "customRoutingController:didSelectItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingControllerDelegate~1customRoutingController(_:didSelect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "customRoutingController:didSelectItem:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avrouting/avcustomroutingcontrollerdelegate/customroutingcontroller(_:eventdidtimeout:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avrouting/avcustomroutingcontrollerdelegate/customroutingcontroller(_:eventdidtimeout:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
