{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customRoutingController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController","text":"AVCustomRoutingController","preciseIdentifier":"c:objc(cs)AVCustomRoutingController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"kind":"text","text":" "},{"text":"customActionItem","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCustomRoutingActionItem","identifier":"doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingActionItem","text":"AVCustomRoutingActionItem","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"]}]},{"parameters":[{"name":"controller","content":[{"inlineContent":[{"text":"A custom routing controller.","type":"text"}],"type":"paragraph"}]},{"name":"customActionItem","content":[{"type":"paragraph","inlineContent":[{"text":"The selected action item.","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avrouting/avcustomroutingcontrollerdelegate/customroutingcontroller(_:didselect:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avrouting/avcustomroutingcontrollerdelegate/customroutingcontroller(_:didselect:)"]}],"kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate when a user selects a custom item in the route picker."}],"seeAlsoSections":[{"anchor":"Handling-controller-events","identifiers":["doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:handle:completionHandler:)","doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:eventDidTimeOut:)"],"generated":true,"title":"Handling controller events"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avrouting/documentation/AVRouting","doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:didSelect:)"},"metadata":{"modules":[{"name":"AVRouting"}],"platforms":[{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"16.0","name":"iOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"16.0","name":"iPadOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"16.0","name":"Mac Catalyst"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"1.0","name":"visionOS"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customRoutingController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVCustomRoutingController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCustomRoutingController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCustomRoutingActionItem","text":"AVCustomRoutingActionItem"},{"kind":"text","text":")"}],"role":"symbol","title":"customRoutingController(_:didSelect:)","externalID":"c:objc(pl)AVCustomRoutingControllerDelegate(im)customRoutingController:didSelectItem:","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"customRoutingController:didSelectItem:"}]},"sections":[],"references":{"doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:eventDidTimeOut:)":{"url":"/documentation/avrouting/avcustomroutingcontrollerdelegate/customroutingcontroller(_:eventdidtimeout:)","title":"customRoutingController(_:eventDidTimeOut:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customRoutingController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCustomRoutingController","text":"AVCustomRoutingController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"eventDidTimeOut","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCustomRoutingEvent","text":"AVCustomRoutingEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Tells the delegate when a routing event times out.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:eventDidTimeOut:)","navigatorTitle":[{"text":"customRoutingController:eventDidTimeOut:","kind":"identifier"}],"type":"topic"},"doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:didSelect:)":{"url":"/documentation/avrouting/avcustomroutingcontrollerdelegate/customroutingcontroller(_:didselect:)","role":"symbol","identifier":"doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:didSelect:)","title":"customRoutingController(_:didSelect:)","abstract":[{"text":"Tells the delegate when a user selects a custom item in the route picker.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"customRoutingController:didSelectItem:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customRoutingController"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCustomRoutingController","text":"AVCustomRoutingController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSelect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVCustomRoutingActionItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCustomRoutingActionItem"},{"text":")","kind":"text"}]},"doc://com.apple.avrouting/documentation/AVRouting":{"abstract":[{"text":"Display custom destinations to stream media in the system route picker.","type":"text"}],"url":"/documentation/avrouting","role":"collection","identifier":"doc://com.apple.avrouting/documentation/AVRouting","kind":"symbol","type":"topic","title":"AVRouting"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","type":"topic"},"doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController":{"navigatorTitle":[{"kind":"identifier","text":"AVCustomRoutingController"}],"kind":"symbol","role":"symbol","abstract":[{"text":"An object that manages the connection from a device to a destination.","type":"text"}],"identifier":"doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController","title":"AVCustomRoutingController","url":"/documentation/avrouting/avcustomroutingcontroller","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AVCustomRoutingController"}]},"doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate":{"identifier":"doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate","url":"/documentation/avrouting/avcustomroutingcontrollerdelegate","title":"AVCustomRoutingControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"AVCustomRoutingControllerDelegate"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVCustomRoutingControllerDelegate"}],"abstract":[{"text":"A protocol for delegates of a custom routing controller.","type":"text"}]},"doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingActionItem":{"navigatorTitle":[{"text":"AVCustomRoutingActionItem","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"An object that represents a custom action item to display in a device route picker.","type":"text"}],"identifier":"doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingActionItem","title":"AVCustomRoutingActionItem","url":"/documentation/avrouting/avcustomroutingactionitem","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AVCustomRoutingActionItem","kind":"identifier"}]},"doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:handle:completionHandler:)":{"url":"/documentation/avrouting/avcustomroutingcontrollerdelegate/customroutingcontroller(_:handle:completionhandler:)","title":"customRoutingController(_:handle:completionHandler:)","kind":"symbol","required":true,"abstract":[{"text":"Connects to, or disconnects from, a device when a user requests it in the picker.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customRoutingController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCustomRoutingController","text":"AVCustomRoutingController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"handle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVCustomRoutingEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCustomRoutingEvent"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:handle:completionHandler:)","navigatorTitle":[{"text":"customRoutingController:handleEvent:completionHandler:","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"16.0","name":"iOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"16.0","name":"iPadOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"16.0","name":"Mac Catalyst"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"1.0","name":"visionOS"}]},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"customRoutingController:didSelectItem:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"customRoutingController:didSelectItem:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avrouting/documentation/AVRouting","doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Handling-controller-events","identifiers":["doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:handle:completionHandler:)","doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingControllerDelegate/customRoutingController(_:eventDidTimeOut:)"],"title":"Handling controller events","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"customRoutingController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVCustomRoutingController","identifier":"doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingController","preciseIdentifier":"c:objc(cs)AVCustomRoutingController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didSelectItem:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVCustomRoutingActionItem","identifier":"doc://com.apple.avrouting/documentation/AVRouting/AVCustomRoutingActionItem","preciseIdentifier":"c:objc(cs)AVCustomRoutingActionItem","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"customActionItem","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"]}]}},{"op":"replace","path":"/primaryContentSections/1","value":{"parameters":[{"name":"controller","content":[{"inlineContent":[{"text":"A custom routing controller.","type":"text"}],"type":"paragraph"}]},{"name":"customActionItem","content":[{"type":"paragraph","inlineContent":[{"text":"The selected action item.","type":"text"}]}]}],"kind":"parameters"}},{"op":"replace","value":"customRoutingController:eventDidTimeOut:","path":"/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingControllerDelegate~1customRoutingController(_:eventDidTimeOut:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"customRoutingController:eventDidTimeOut:"}],"path":"/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingControllerDelegate~1customRoutingController(_:eventDidTimeOut:)/fragments"},{"op":"replace","value":"customRoutingController:didSelectItem:","path":"/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingControllerDelegate~1customRoutingController(_:didSelect:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"customRoutingController:didSelectItem:"}],"path":"/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingControllerDelegate~1customRoutingController(_:didSelect:)/fragments"},{"op":"replace","value":"AVCustomRoutingController","path":"/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingController/title"},{"op":"replace","value":[{"text":"AVCustomRoutingController","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingController/fragments"},{"op":"replace","value":[{"text":"AVCustomRoutingController","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingController/navigatorTitle"},{"op":"replace","value":"AVCustomRoutingControllerDelegate","path":"/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingControllerDelegate/title"},{"op":"replace","value":[{"text":"AVCustomRoutingControllerDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingControllerDelegate/fragments"},{"path":"/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingControllerDelegate/navigatorTitle","value":[{"kind":"identifier","text":"AVCustomRoutingControllerDelegate"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingActionItem/title","value":"AVCustomRoutingActionItem","op":"replace"},{"path":"/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingActionItem/fragments","value":[{"kind":"identifier","text":"AVCustomRoutingActionItem"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingActionItem/navigatorTitle","value":[{"text":"AVCustomRoutingActionItem","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingControllerDelegate~1customRoutingController(_:handle:completionHandler:)/title","value":"customRoutingController:handleEvent:completionHandler:","op":"replace"},{"path":"/references/doc:~1~1com.apple.avrouting~1documentation~1AVRouting~1AVCustomRoutingControllerDelegate~1customRoutingController(_:handle:completionHandler:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"customRoutingController:handleEvent:completionHandler:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}