{
  "abstract": [
    {
      "text": "Tells the delegate that the audio session interruption ended with flags.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Observe audio session interruption notifications instead. See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/handling-audio-interruptions",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for more information.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:withFlags:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)AVAudioRecorderDelegate(im)audioRecorderEndInterruption:withFlags:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "audioRecorderEndInterruption"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVAudioRecorder",
        "text": "AVAudioRecorder"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "withFlags"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "audioRecorderEndInterruption:withFlags:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Deprecated - use AVAudioSession instead",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "2.0",
        "message": "Deprecated - use AVAudioSession instead",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "audioRecorderEndInterruption(_:withFlags:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "audioRecorderEndInterruption"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "recorder"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorder",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVAudioRecorder",
              "text": "AVAudioRecorder"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "withFlags"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The interrupted audio recorder.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "recorder"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The flags that indicate the state of the audio session.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "flags"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorder": {
      "abstract": [
        {
          "text": "An object that records audio data to a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioRecorder"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioRecorder"
        }
      ],
      "role": "symbol",
      "title": "AVAudioRecorder",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiorecorder"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate": {
      "abstract": [
        {
          "text": "A protocol that defines the methods to respond to audio recording events and encoding errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioRecorderDelegate"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioRecorderDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVAudioRecorderDelegate",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiorecorderdelegate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderBeginInterruption(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the system interrupted the audio recording.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioRecorderBeginInterruption"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioRecorder",
          "text": "AVAudioRecorder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderBeginInterruption(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audioRecorderBeginInterruption:"
        }
      ],
      "role": "symbol",
      "title": "audioRecorderBeginInterruption(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiorecorderdelegate/audiorecorderbegininterruption(_:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the audio session interruption ended.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioRecorderEndInterruption"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioRecorder",
          "text": "AVAudioRecorder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audioRecorderEndInterruption:"
        }
      ],
      "role": "symbol",
      "title": "audioRecorderEndInterruption(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiorecorderdelegate/audiorecorderendinterruption(_:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:withFlags:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the audio session interruption ended with flags.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioRecorderEndInterruption"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioRecorder",
          "text": "AVAudioRecorder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:withFlags:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audioRecorderEndInterruption:withFlags:"
        }
      ],
      "role": "symbol",
      "title": "audioRecorderEndInterruption(_:withFlags:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiorecorderdelegate/audiorecorderendinterruption(_:withflags:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:withOptions:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the audio session interruption ended with options.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioRecorderEndInterruption"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioRecorder",
          "text": "AVAudioRecorder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:withOptions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audioRecorderEndInterruption:withOptions:"
        }
      ],
      "role": "symbol",
      "title": "audioRecorderEndInterruption(_:withOptions:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiorecorderdelegate/audiorecorderendinterruption(_:withoptions:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/handling-audio-interruptions": {
      "abstract": [
        {
          "text": "Observe audio session notifications to ensure that your app responds appropriately to interruptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/handling-audio-interruptions",
      "kind": "article",
      "role": "article",
      "title": "Handling audio interruptions",
      "type": "topic",
      "url": "/documentation/avfaudio/handling-audio-interruptions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-Audio-Interruptions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderBeginInterruption(_:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:withOptions:)"
      ],
      "title": "Responding to Audio Interruptions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "6.0",
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "6.0",
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "audioRecorderEndInterruption:withFlags:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "audioRecorderEndInterruption:withFlags:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-Audio-Interruptions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderBeginInterruption(_:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorderDelegate/audioRecorderEndInterruption(_:withOptions:)"
              ],
              "title": "Responding to Audio Interruptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "audioRecorderEndInterruption:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioRecorder",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVAudioRecorder",
                    "text": "AVAudioRecorder"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "recorder"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "withFlags:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "flags"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The interrupted audio recorder.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "recorder"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The flags that indicate the state of the audio session.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "flags"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Observe audio session interruption notifications instead. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/handling-audio-interruptions",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for more information.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderBeginInterruption(_:)/title",
          "value": "audioRecorderBeginInterruption:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderBeginInterruption(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "audioRecorderBeginInterruption:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorder/title",
          "value": "AVAudioRecorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioRecorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioRecorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate/title",
          "value": "AVAudioRecorderDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioRecorderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioRecorderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderEndInterruption(_:withFlags:)/title",
          "value": "audioRecorderEndInterruption:withFlags:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderEndInterruption(_:withFlags:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "audioRecorderEndInterruption:withFlags:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderEndInterruption(_:withOptions:)/title",
          "value": "audioRecorderEndInterruption:withOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderEndInterruption(_:withOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "audioRecorderEndInterruption:withOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderEndInterruption(_:)/title",
          "value": "audioRecorderEndInterruption:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioRecorderDelegate~1audioRecorderEndInterruption(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "audioRecorderEndInterruption:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiorecorderdelegate/audiorecorderendinterruption(_:withflags:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiorecorderdelegate/audiorecorderendinterruption(_:withflags:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
