{
  "abstract": [
    {
      "text": "Fetches the turn-based matches from Game Center that the local player participates in.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/loadMatches(completionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GKTurnBasedMatch(cm)loadMatchesWithCompletionHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "loadMatches"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "completionHandler"
      },
      {
        "kind": "text",
        "text": ": ((["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)GKTurnBasedMatch",
        "text": "GKTurnBasedMatch"
      },
      {
        "kind": "text",
        "text": "]?, (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")?)"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "loadMatchesWithCompletionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "loadMatches(completionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "loadMatches"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ": ((["
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKTurnBasedMatch",
              "text": "GKTurnBasedMatch"
            },
            {
              "kind": "text",
              "text": "]?, (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")? = nil)"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "loadMatches"
            },
            {
              "kind": "text",
              "text": "() "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "throws"
            },
            {
              "kind": "text",
              "text": " -> ["
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKTurnBasedMatch",
              "text": "GKTurnBasedMatch"
            },
            {
              "kind": "text",
              "text": "]"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The block that GameKit calls when it completes the request.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "The block receives the following parameters:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "The local player’s matches, or ",
                            "type": "text"
                          },
                          {
                            "code": "nil",
                            "type": "codeVoice"
                          },
                          {
                            "text": " if there are none. If an error occurs, this parameter may be non-",
                            "type": "text"
                          },
                          {
                            "code": "nil",
                            "type": "codeVoice"
                          },
                          {
                            "text": ", containing a subset of the matches that GameKit loads before the error occurs.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "inlineContent": [
                          {
                            "text": "matches",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      }
                    ]
                  }
                },
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "Describes an error if it occurs, or ",
                            "type": "text"
                          },
                          {
                            "code": "nil",
                            "type": "codeVoice"
                          },
                          {
                            "text": " if the operation completes.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "inlineContent": [
                          {
                            "text": "error",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      }
                    ]
                  }
                }
              ],
              "type": "termList"
            }
          ],
          "name": "completionHandler"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.gamekit/documentation/GameKit/starting-turn-based-matches-and-passing-turns-between-players"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/matchData",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties of the match objects are ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " until you fetch the data from Game Center using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/loadMatchData(completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch": {
      "abstract": [
        {
          "text": "An object that encapsulates the match data for games where players take turns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatch"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatch"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedMatch",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/load(withID:withCompletionHandler:)": {
      "abstract": [
        {
          "text": "Loads a specific match with the specified identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "load"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withCompletionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKTurnBasedMatch",
          "text": "GKTurnBasedMatch"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/load(withID:withCompletionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadMatchWithID:withCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "load(withID:withCompletionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/load(withid:withcompletionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/loadMatchData(completionHandler:)": {
      "abstract": [
        {
          "text": "Fetches your game-specific data that you store in Game Center when ending a turn, saving a turn, or leaving a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadMatchData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/loadMatchData(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadMatchDataWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "loadMatchData(completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/loadmatchdata(completionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/loadMatches(completionHandler:)": {
      "abstract": [
        {
          "text": "Fetches the turn-based matches from Game Center that the local player participates in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadMatches"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKTurnBasedMatch",
          "text": "GKTurnBasedMatch"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/loadMatches(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadMatchesWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "loadMatches(completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/loadmatches(completionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/matchData": {
      "abstract": [
        {
          "text": "The game-specific data that you store in Game Center and pass between participants through a match object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/matchData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchData"
        }
      ],
      "role": "symbol",
      "title": "matchData",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/matchdata"
    },
    "doc://com.apple.gamekit/documentation/GameKit/starting-turn-based-matches-and-passing-turns-between-players": {
      "abstract": [
        {
          "text": "Let Game Center store and forward match data between players in a turn-based game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/starting-turn-based-matches-and-passing-turns-between-players",
      "kind": "article",
      "role": "article",
      "title": "Starting turn-based matches and passing turns between players",
      "type": "topic",
      "url": "/documentation/gamekit/starting-turn-based-matches-and-passing-turns-between-players"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Loading-Existing-Matches",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/load(withID:withCompletionHandler:)"
      ],
      "title": "Loading Existing Matches"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "loadMatchesWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "loadMatchesWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Loading-Existing-Matches",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/load(withID:withCompletionHandler:)"
              ],
              "title": "Loading Existing Matches"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "loadMatchesWithCompletionHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<GKTurnBasedMatch *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "matches"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The block that GameKit calls when it completes the request.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "The block receives the following parameters:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "The local player’s matches, or ",
                                  "type": "text"
                                },
                                {
                                  "code": "nil",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": " if there are none. If an error occurs, this parameter may be non-",
                                  "type": "text"
                                },
                                {
                                  "code": "nil",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": ", containing a subset of the matches that GameKit loads before the error occurs.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "inlineContent": [
                                {
                                  "text": "matches",
                                  "type": "text"
                                }
                              ],
                              "type": "emphasis"
                            }
                          ]
                        }
                      },
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "Describes an error if it occurs, or ",
                                  "type": "text"
                                },
                                {
                                  "code": "nil",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": " if the operation completes.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "inlineContent": [
                                {
                                  "text": "error",
                                  "type": "text"
                                }
                              ],
                              "type": "emphasis"
                            }
                          ]
                        }
                      }
                    ],
                    "type": "termList"
                  }
                ],
                "name": "completionHandler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1matchData/title",
          "value": "matchData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1matchData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "matchData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch/title",
          "value": "GKTurnBasedMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1load(withID:withCompletionHandler:)/title",
          "value": "loadMatchWithID:withCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1load(withID:withCompletionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "loadMatchWithID:withCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1loadMatchData(completionHandler:)/title",
          "value": "loadMatchDataWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1loadMatchData(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadMatchDataWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1loadMatches(completionHandler:)/title",
          "value": "loadMatchesWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1loadMatches(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "loadMatchesWithCompletionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkturnbasedmatch/loadmatches(completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gkturnbasedmatch/loadmatches(completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
