{
  "abstract": [
    {
      "text": "An unspecified interface style.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceStyle/unspecified"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIUserInterfaceStyle@UIUserInterfaceStyleUnspecified",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unspecified"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIUserInterfaceStyleUnspecified"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIUserInterfaceStyle.unspecified"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unspecified"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Choose this option when you want to follow the system’s interface style.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceStyle": {
      "abstract": [
        {
          "text": "Constants that indicate the interface style for the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserInterfaceStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceStyle"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceStyle",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfacestyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceStyle/dark": {
      "abstract": [
        {
          "text": "The dark interface style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dark"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceStyle/dark",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceStyleDark"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceStyle.dark",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfacestyle/dark"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceStyle/light": {
      "abstract": [
        {
          "text": "The light interface style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "light"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceStyle/light",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceStyleLight"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceStyle.light",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfacestyle/light"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceStyle/unspecified": {
      "abstract": [
        {
          "text": "An unspecified interface style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceStyle/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceStyleUnspecified"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceStyle.unspecified",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfacestyle/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Interface-styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceStyle/light",
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceStyle/dark"
      ],
      "title": "Interface styles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIUserInterfaceStyleUnspecified"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceStyleUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceStyle"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Interface-styles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceStyle/light",
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceStyle/dark"
              ],
              "title": "Interface styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIUserInterfaceStyleUnspecified"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceStyle~1unspecified/title",
          "value": "UIUserInterfaceStyleUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceStyle~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceStyleUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceStyle/title",
          "value": "UIUserInterfaceStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceStyle~1dark/title",
          "value": "UIUserInterfaceStyleDark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceStyle~1dark/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceStyleDark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceStyle~1light/title",
          "value": "UIUserInterfaceStyleLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceStyle~1light/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceStyleLight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiuserinterfacestyle/unspecified"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiuserinterfacestyle/unspecified"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
