{
  "abstract": [
    {
      "text": "An error that indicates a missing asset resource.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/missingResource"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC13PHPhotosErrorLeV15missingResourceSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "missingResource"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC13PHPhotosErrorLeV",
        "text": "PHPhotosError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@PHPhotosError",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "missingResource"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "missingResource"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC13PHPhotosErrorLeV",
              "text": "PHPhotosError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PHPhotosError",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents a framework error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPhotosError"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotosError"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for framework operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PHPhotosError.Code",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/code"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/accessRestricted": {
      "abstract": [
        {
          "text": "An error that indicates the system configuration restricts access to the asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessRestricted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13PHPhotosErrorLeV",
          "text": "PHPhotosError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHPhotosError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/accessRestricted",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessRestricted",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/accessrestricted"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/accessUserDenied": {
      "abstract": [
        {
          "text": "An error that indicates the user denied access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessUserDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13PHPhotosErrorLeV",
          "text": "PHPhotosError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHPhotosError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/accessUserDenied",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessUserDenied",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/accessuserdenied"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/changeNotSupported": {
      "abstract": [
        {
          "text": "An error that indicates the system doesn’t support the change request configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13PHPhotosErrorLeV",
          "text": "PHPhotosError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHPhotosError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/changeNotSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "changeNotSupported",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/changenotsupported"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/identifierNotFound": {
      "abstract": [
        {
          "text": "An error that indicates an identifier doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifierNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13PHPhotosErrorLeV",
          "text": "PHPhotosError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHPhotosError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/identifierNotFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "identifierNotFound",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/identifiernotfound"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/internalError": {
      "abstract": [
        {
          "text": "An error that indicates an internal error occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13PHPhotosErrorLeV",
          "text": "PHPhotosError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHPhotosError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/internalError",
      "kind": "symbol",
      "role": "symbol",
      "title": "internalError",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/internalerror"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/invalidResource": {
      "abstract": [
        {
          "text": "An error that indicates the asset resource validation failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidResource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13PHPhotosErrorLeV",
          "text": "PHPhotosError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHPhotosError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/invalidResource",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidResource",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/invalidresource"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/libraryInFileProviderSyncRoot": {
      "abstract": [
        {
          "text": "An error that indicates the Photos library bundle is in a file provider sync directory, and the framework doesn’t support it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "libraryInFileProviderSyncRoot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13PHPhotosErrorLeV",
          "text": "PHPhotosError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHPhotosError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/libraryInFileProviderSyncRoot",
      "kind": "symbol",
      "role": "symbol",
      "title": "libraryInFileProviderSyncRoot",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/libraryinfileprovidersyncroot"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/libraryVolumeOffline": {
      "abstract": [
        {
          "text": "An error that indicates the photo library isn’t available because the file system volume that stores it isn’t mounted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "libraryVolumeOffline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13PHPhotosErrorLeV",
          "text": "PHPhotosError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHPhotosError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/libraryVolumeOffline",
      "kind": "symbol",
      "role": "symbol",
      "title": "libraryVolumeOffline",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/libraryvolumeoffline"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/missingResource": {
      "abstract": [
        {
          "text": "An error that indicates a missing asset resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingResource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13PHPhotosErrorLeV",
          "text": "PHPhotosError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHPhotosError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/missingResource",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingResource",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/missingresource"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/multipleIdentifiersFound": {
      "abstract": [
        {
          "text": "An error that indicates that more than one identifier exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multipleIdentifiersFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13PHPhotosErrorLeV",
          "text": "PHPhotosError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHPhotosError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/multipleIdentifiersFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "multipleIdentifiersFound",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/multipleidentifiersfound"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/networkAccessRequired": {
      "abstract": [
        {
          "text": "An error that indicates the request for an asset resource failed because it requires network access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkAccessRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13PHPhotosErrorLeV",
          "text": "PHPhotosError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHPhotosError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/networkAccessRequired",
      "kind": "symbol",
      "role": "symbol",
      "title": "networkAccessRequired",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/networkaccessrequired"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/networkError": {
      "abstract": [
        {
          "text": "An error that indicates the request for an asset resource fails because of a network connection error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13PHPhotosErrorLeV",
          "text": "PHPhotosError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHPhotosError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/networkError",
      "kind": "symbol",
      "role": "symbol",
      "title": "networkError",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/networkerror"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/notEnoughSpace": {
      "abstract": [
        {
          "text": "An error that indicates insufficient space to perform the change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notEnoughSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13PHPhotosErrorLeV",
          "text": "PHPhotosError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHPhotosError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/notEnoughSpace",
      "kind": "symbol",
      "role": "symbol",
      "title": "notEnoughSpace",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/notenoughspace"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/operationInterrupted": {
      "abstract": [
        {
          "text": "An error that indicates an interruption occurs and the operation can’t complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationInterrupted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13PHPhotosErrorLeV",
          "text": "PHPhotosError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHPhotosError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/operationInterrupted",
      "kind": "symbol",
      "role": "symbol",
      "title": "operationInterrupted",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/operationinterrupted"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/persistentChangeDetailsUnavailable": {
      "abstract": [
        {
          "text": "An error that indicates the change details aren’t available for the persistent change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "persistentChangeDetailsUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13PHPhotosErrorLeV",
          "text": "PHPhotosError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHPhotosError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/persistentChangeDetailsUnavailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "persistentChangeDetailsUnavailable",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/persistentchangedetailsunavailable"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/persistentChangeTokenExpired": {
      "abstract": [
        {
          "text": "An error that indicates the library state is older than the available history of persistent changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "persistentChangeTokenExpired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13PHPhotosErrorLeV",
          "text": "PHPhotosError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHPhotosError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/persistentChangeTokenExpired",
      "kind": "symbol",
      "role": "symbol",
      "title": "persistentChangeTokenExpired",
      "type": "topic",
      "url": "/documentation/photos/phphotoserror-swift.struct/persistentchangetokenexpired"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/accessRestricted",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/accessUserDenied",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/changeNotSupported",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/identifierNotFound",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/internalError",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/invalidResource",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/libraryVolumeOffline",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/libraryInFileProviderSyncRoot",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/multipleIdentifiersFound",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/networkAccessRequired",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/networkError",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/notEnoughSpace",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/operationInterrupted",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/persistentChangeDetailsUnavailable",
        "doc://com.apple.photokit/documentation/Photos/PHPhotosError-swift.struct/persistentChangeTokenExpired"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code/title",
          "value": "PHPhotosError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotosError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotosError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phphotoserror-swift.struct/missingresource"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
