{
  "abstract": [
    {
      "text": "The material for the area behind the pages of a document.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/underPageBackground"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSVisualEffectMaterial@NSVisualEffectMaterialUnderPageBackground",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "underPageBackground"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSVisualEffectMaterialUnderPageBackground"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSVisualEffectView.Material.underPageBackground"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "underPageBackground"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This material supports Desktop Tinting in Dark Mode. With Desktop Tinting, the system modifies the material’s color dynamically by incorporating some of the color from the underlying desktop image.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView": {
      "abstract": [
        {
          "text": "A view that adds translucency and vibrancy effects to the views in your interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSVisualEffectView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectView"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum": {
      "abstract": [
        {
          "text": "Constants to specify the material shown by the visual effect view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Material"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Material"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/contentBackground": {
      "abstract": [
        {
          "text": "The material for the background of opaque content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentBackground"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/contentBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialContentBackground"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.contentBackground",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/contentbackground"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/fullScreenUI": {
      "abstract": [
        {
          "text": "The material for the background of a full-screen modal interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullScreenUI"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/fullScreenUI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialFullScreenUI"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.fullScreenUI",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/fullscreenui"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/headerView": {
      "abstract": [
        {
          "text": "The material for in-line header or footer views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headerView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/headerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialHeaderView"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.headerView",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/headerview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/hudWindow": {
      "abstract": [
        {
          "text": "The material for the background of heads-up display (HUD) windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hudWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/hudWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialHUDWindow"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.hudWindow",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/hudwindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/menu": {
      "abstract": [
        {
          "text": "The material for menus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menu"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/menu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialMenu"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.menu",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/menu"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/popover": {
      "abstract": [
        {
          "text": "The material for the background of popover windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popover"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/popover",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialPopover"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.popover",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/popover"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/selection": {
      "abstract": [
        {
          "text": "The material used to indicate a selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/selection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialSelection"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.selection",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/selection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/sheet": {
      "abstract": [
        {
          "text": "The material for the background of sheet windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sheet"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/sheet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialSheet"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.sheet",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/sheet"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/sidebar": {
      "abstract": [
        {
          "text": "The material for the background of window sidebars.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sidebar"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/sidebar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialSidebar"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.sidebar",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/sidebar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/titlebar": {
      "abstract": [
        {
          "text": "The material for a window’s titlebar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titlebar"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/titlebar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialTitlebar"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.titlebar",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/titlebar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/toolTip": {
      "abstract": [
        {
          "text": "The material for the background of a tool tip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolTip"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/toolTip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialToolTip"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.toolTip",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/tooltip"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/underPageBackground": {
      "abstract": [
        {
          "text": "The material for the area behind the pages of a document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "underPageBackground"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/underPageBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialUnderPageBackground"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.underPageBackground",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/underpagebackground"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/underWindowBackground": {
      "abstract": [
        {
          "text": "The material to show under a window’s background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "underWindowBackground"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/underWindowBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialUnderWindowBackground"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.underWindowBackground",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/underwindowbackground"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/windowBackground": {
      "abstract": [
        {
          "text": "The material for the background of opaque windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windowBackground"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/windowBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialWindowBackground"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.windowBackground",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/windowbackground"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Material-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/titlebar",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/selection",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/menu",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/popover",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/sidebar",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/headerView",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/sheet",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/windowBackground",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/hudWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/fullScreenUI",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/toolTip",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/contentBackground",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/underWindowBackground"
      ],
      "title": "Material Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSVisualEffectMaterialUnderPageBackground"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialUnderPageBackground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Material-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/titlebar",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/selection",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/menu",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/popover",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/sidebar",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/headerView",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/sheet",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/windowBackground",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/hudWindow",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/fullScreenUI",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/toolTip",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/contentBackground",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/underWindowBackground"
              ],
              "title": "Material Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSVisualEffectMaterialUnderPageBackground"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1menu/title",
          "value": "NSVisualEffectMaterialMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1menu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum/title",
          "value": "NSVisualEffectMaterial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1headerView/title",
          "value": "NSVisualEffectMaterialHeaderView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1headerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialHeaderView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1sidebar/title",
          "value": "NSVisualEffectMaterialSidebar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1sidebar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialSidebar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1sheet/title",
          "value": "NSVisualEffectMaterialSheet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1sheet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialSheet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1fullScreenUI/title",
          "value": "NSVisualEffectMaterialFullScreenUI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1fullScreenUI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialFullScreenUI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1hudWindow/title",
          "value": "NSVisualEffectMaterialHUDWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1hudWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialHUDWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1underPageBackground/title",
          "value": "NSVisualEffectMaterialUnderPageBackground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1underPageBackground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialUnderPageBackground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1titlebar/title",
          "value": "NSVisualEffectMaterialTitlebar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1titlebar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialTitlebar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1popover/title",
          "value": "NSVisualEffectMaterialPopover"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1popover/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialPopover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView/title",
          "value": "NSVisualEffectView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1windowBackground/title",
          "value": "NSVisualEffectMaterialWindowBackground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1windowBackground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialWindowBackground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1underWindowBackground/title",
          "value": "NSVisualEffectMaterialUnderWindowBackground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1underWindowBackground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialUnderWindowBackground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1toolTip/title",
          "value": "NSVisualEffectMaterialToolTip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1toolTip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialToolTip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1contentBackground/title",
          "value": "NSVisualEffectMaterialContentBackground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1contentBackground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialContentBackground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1selection/title",
          "value": "NSVisualEffectMaterialSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1selection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialSelection"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsvisualeffectview/material-swift.enum/underpagebackground"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsvisualeffectview/material-swift.enum/underpagebackground"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
