{
  "abstract": [
    {
      "text": "A response code that indicates an unknown state.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/unspecified"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INStartCallIntentResponseCode@INStartCallIntentResponseCodeUnspecified",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unspecified"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INStartCallIntentResponseCodeUnspecified"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INStartCallIntentResponseCode.unspecified"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unspecified"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode": {
      "abstract": [
        {
          "text": "Constants that indicate the response state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartCallIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INStartCallIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/instartcallintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/continueInApp": {
      "abstract": [
        {
          "text": "A response code that indicates your app extension is ready to transfer control to the app to start the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continueInApp"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/continueInApp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallIntentResponseCodeContinueInApp"
        }
      ],
      "role": "symbol",
      "title": "INStartCallIntentResponseCode.continueInApp",
      "type": "topic",
      "url": "/documentation/intents/instartcallintentresponsecode/continueinapp"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failure": {
      "abstract": [
        {
          "text": "A response code that indicates you were unable to perform the search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INStartCallIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/instartcallintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureAirplaneModeEnabled": {
      "abstract": [
        {
          "text": "A response code that indicates the call can’t start due to the user’s device being in airplane mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureAirplaneModeEnabled"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureAirplaneModeEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallIntentResponseCodeFailureAirplaneModeEnabled"
        }
      ],
      "role": "symbol",
      "title": "INStartCallIntentResponseCode.failureAirplaneModeEnabled",
      "type": "topic",
      "url": "/documentation/intents/instartcallintentresponsecode/failureairplanemodeenabled"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureAppConfigurationRequired": {
      "abstract": [
        {
          "text": "A response code that indicates the user must perform additional configuration steps before creating a call is possible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureAppConfigurationRequired"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureAppConfigurationRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallIntentResponseCodeFailureAppConfigurationRequired"
        }
      ],
      "role": "symbol",
      "title": "INStartCallIntentResponseCode.failureAppConfigurationRequired",
      "type": "topic",
      "url": "/documentation/intents/instartcallintentresponsecode/failureappconfigurationrequired"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureCallInProgress": {
      "abstract": [
        {
          "text": "A response code that indicates the current call failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureCallInProgress"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureCallInProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallIntentResponseCodeFailureCallInProgress"
        }
      ],
      "role": "symbol",
      "title": "INStartCallIntentResponseCode.failureCallInProgress",
      "type": "topic",
      "url": "/documentation/intents/instartcallintentresponsecode/failurecallinprogress"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureCallingServiceNotAvailable": {
      "abstract": [
        {
          "text": "A response code that indicates your app’s calling service isn’t currently available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureCallingServiceNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureCallingServiceNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallIntentResponseCodeFailureCallingServiceNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "INStartCallIntentResponseCode.failureCallingServiceNotAvailable",
      "type": "topic",
      "url": "/documentation/intents/instartcallintentresponsecode/failurecallingservicenotavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureContactNotSupportedByApp": {
      "abstract": [
        {
          "text": "A response code that indicates the app doesn’t support the specified contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureContactNotSupportedByApp"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureContactNotSupportedByApp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallIntentResponseCodeFailureContactNotSupportedByApp"
        }
      ],
      "role": "symbol",
      "title": "INStartCallIntentResponseCode.failureContactNotSupportedByApp",
      "type": "topic",
      "url": "/documentation/intents/instartcallintentresponsecode/failurecontactnotsupportedbyapp"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [
        {
          "text": "A response code that indicates the user must launch your app to start a call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INStartCallIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/instartcallintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureUnableToHandOff": {
      "abstract": [
        {
          "text": "A response code that indicates the app can’t hand off the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureUnableToHandOff"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureUnableToHandOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallIntentResponseCodeFailureUnableToHandOff"
        }
      ],
      "role": "symbol",
      "title": "INStartCallIntentResponseCode.failureUnableToHandOff",
      "type": "topic",
      "url": "/documentation/intents/instartcallintentresponsecode/failureunabletohandoff"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/ready": {
      "abstract": [
        {
          "text": "A response code that indicates app readiness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INStartCallIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/instartcallintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/unspecified": {
      "abstract": [
        {
          "text": "A response code that indicates an unknown state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INStartCallIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/instartcallintentresponsecode/unspecified"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/userConfirmationRequired": {
      "abstract": [
        {
          "text": "A response code that indicates the user must confirm the call information before starting the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userConfirmationRequired"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/userConfirmationRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallIntentResponseCodeUserConfirmationRequired"
        }
      ],
      "role": "symbol",
      "title": "INStartCallIntentResponseCode.userConfirmationRequired",
      "type": "topic",
      "url": "/documentation/intents/instartcallintentresponsecode/userconfirmationrequired"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Response-Code",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/ready",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/continueInApp",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/userConfirmationRequired",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failure",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureRequiringAppLaunch",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureCallingServiceNotAvailable",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureContactNotSupportedByApp",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureAirplaneModeEnabled",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureUnableToHandOff",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureAppConfigurationRequired",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureCallInProgress"
      ],
      "title": "Response Code"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INStartCallIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Response-Code",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/ready",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/continueInApp",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/userConfirmationRequired",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failure",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureRequiringAppLaunch",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureCallingServiceNotAvailable",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureContactNotSupportedByApp",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureAirplaneModeEnabled",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureUnableToHandOff",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureAppConfigurationRequired",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponseCode/failureCallInProgress"
              ],
              "title": "Response Code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INStartCallIntentResponseCodeUnspecified"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode/title",
          "value": "INStartCallIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1failureAppConfigurationRequired/title",
          "value": "INStartCallIntentResponseCodeFailureAppConfigurationRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1failureAppConfigurationRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentResponseCodeFailureAppConfigurationRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1failureContactNotSupportedByApp/title",
          "value": "INStartCallIntentResponseCodeFailureContactNotSupportedByApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1failureContactNotSupportedByApp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentResponseCodeFailureContactNotSupportedByApp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1failure/title",
          "value": "INStartCallIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentResponseCodeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1failureAirplaneModeEnabled/title",
          "value": "INStartCallIntentResponseCodeFailureAirplaneModeEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1failureAirplaneModeEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentResponseCodeFailureAirplaneModeEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1unspecified/title",
          "value": "INStartCallIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INStartCallIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1userConfirmationRequired/title",
          "value": "INStartCallIntentResponseCodeUserConfirmationRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1userConfirmationRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentResponseCodeUserConfirmationRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1ready/title",
          "value": "INStartCallIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentResponseCodeReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1failureCallingServiceNotAvailable/title",
          "value": "INStartCallIntentResponseCodeFailureCallingServiceNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1failureCallingServiceNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentResponseCodeFailureCallingServiceNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1continueInApp/title",
          "value": "INStartCallIntentResponseCodeContinueInApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1continueInApp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentResponseCodeContinueInApp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1failureCallInProgress/title",
          "value": "INStartCallIntentResponseCodeFailureCallInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1failureCallInProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentResponseCodeFailureCallInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1failureUnableToHandOff/title",
          "value": "INStartCallIntentResponseCodeFailureUnableToHandOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponseCode~1failureUnableToHandOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentResponseCodeFailureUnableToHandOff"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/instartcallintentresponsecode/unspecified"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/instartcallintentresponsecode/unspecified"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
