{
  "abstract": [
    {
      "text": "The attribute value for each vertex is a vector with 4 components, each of 16-bit floating-point type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/half4"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MDLVertexFormat@MDLVertexFormatHalf4",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "half4"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MDLVertexFormatHalf4"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MDLVertexFormat.half4"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "half4"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/format": {
      "abstract": [
        {
          "text": "The format of per-vertex data for the attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLVertexFormat",
          "text": "MDLVertexFormat"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/format",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "format"
        }
      ],
      "role": "symbol",
      "title": "format",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattribute/format"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat": {
      "abstract": [
        {
          "text": "Descriptions of the data size and layout for a vertex attribute, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttribute/format",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexFormat"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexFormat"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexFormat",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexformat"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/charBits": {
      "abstract": [
        {
          "text": "A bit mask for vertex attributes whose components are in 8-bit signed integer format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "charBits"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/charBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexFormatCharBits"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexFormat.charBits",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexformat/charbits"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/charNormalizedBits": {
      "abstract": [
        {
          "text": "A bit mask for vertex attributes whose components are in 8-bit signed normalized integer format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "charNormalizedBits"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/charNormalizedBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexFormatCharNormalizedBits"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexFormat.charNormalizedBits",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexformat/charnormalizedbits"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/floatBits": {
      "abstract": [
        {
          "text": "A bit mask for vertex attributes whose components are in 32-bit floating-point format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "floatBits"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/floatBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexFormatFloatBits"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexFormat.floatBits",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexformat/floatbits"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/half4": {
      "abstract": [
        {
          "text": "The attribute value for each vertex is a vector with 4 components, each of 16-bit floating-point type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "half4"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/half4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexFormatHalf4"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexFormat.half4",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexformat/half4"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/halfBits": {
      "abstract": [
        {
          "text": "A bit mask for vertex attributes whose components are in 16-bit floating-point format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "halfBits"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/halfBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexFormatHalfBits"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexFormat.halfBits",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexformat/halfbits"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/intBits": {
      "abstract": [
        {
          "text": "A bit mask for vertex attributes whose components are in 32-bit signed integer format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intBits"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/intBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexFormatIntBits"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexFormat.intBits",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexformat/intbits"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/invalid": {
      "abstract": [
        {
          "text": "The vertex attribute has just been initialized or its format is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalid"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/invalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexFormatInvalid"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexFormat.invalid",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexformat/invalid"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/packedBit": {
      "abstract": [
        {
          "text": "A bit mask for vertex attributes in packed vector formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "packedBit"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/packedBit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexFormatPackedBit"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexFormat.packedBit",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexformat/packedbit"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/shortBits": {
      "abstract": [
        {
          "text": "A bit mask for vertex attributes whose components are in 16-bit signed integer format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shortBits"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/shortBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexFormatShortBits"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexFormat.shortBits",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexformat/shortbits"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/shortNormalizedBits": {
      "abstract": [
        {
          "text": "A bit mask for vertex attributes whose components are in 16-bit signed normalized integer format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shortNormalizedBits"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/shortNormalizedBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexFormatShortNormalizedBits"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexFormat.shortNormalizedBits",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexformat/shortnormalizedbits"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uChar": {
      "abstract": [
        {
          "text": "The attribute value for each vertex is a scalar of unsigned 8-bit integer type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uChar"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uChar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexFormatUChar"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexFormat.uChar",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexformat/uchar"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uCharBits": {
      "abstract": [
        {
          "text": "A bit mask for vertex attributes whose components are in 8-bit unsigned integer format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uCharBits"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uCharBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexFormatUCharBits"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexFormat.uCharBits",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexformat/ucharbits"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uCharNormalizedBits": {
      "abstract": [
        {
          "text": "A bit mask for vertex attributes whose components are in 8-bit unsigned normalized integer format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uCharNormalizedBits"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uCharNormalizedBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexFormatUCharNormalizedBits"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexFormat.uCharNormalizedBits",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexformat/ucharnormalizedbits"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uIntBits": {
      "abstract": [
        {
          "text": "A bit mask for vertex attributes whose components are in 32-bit unsigned integer format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uIntBits"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uIntBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexFormatUIntBits"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexFormat.uIntBits",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexformat/uintbits"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uShortBits": {
      "abstract": [
        {
          "text": "A bit mask for vertex attributes whose components are in 16-bit unsigned integer format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uShortBits"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uShortBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexFormatUShortBits"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexFormat.uShortBits",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexformat/ushortbits"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uShortNormalizedBits": {
      "abstract": [
        {
          "text": "A bit mask for vertex attributes whose components are in 16-bit unsigned normalized integer format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uShortNormalizedBits"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uShortNormalizedBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexFormatUShortNormalizedBits"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexFormat.uShortNormalizedBits",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexformat/ushortnormalizedbits"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/invalid",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/packedBit",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uCharBits",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/charBits",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uCharNormalizedBits",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/charNormalizedBits",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uShortBits",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/shortBits",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uShortNormalizedBits",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/shortNormalizedBits",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uIntBits",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/intBits",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/halfBits",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/floatBits",
        "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uChar"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MDLVertexFormatHalf4"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormatHalf4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/invalid",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/packedBit",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uCharBits",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/charBits",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uCharNormalizedBits",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/charNormalizedBits",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uShortBits",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/shortBits",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uShortNormalizedBits",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/shortNormalizedBits",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uIntBits",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/intBits",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/halfBits",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/floatBits",
                "doc://com.apple.modelio/documentation/ModelIO/MDLVertexFormat/uChar"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MDLVertexFormatHalf4"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1floatBits/title",
          "value": "MDLVertexFormatFloatBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1floatBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormatFloatBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1packedBit/title",
          "value": "MDLVertexFormatPackedBit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1packedBit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormatPackedBit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1charBits/title",
          "value": "MDLVertexFormatCharBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1charBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormatCharBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1intBits/title",
          "value": "MDLVertexFormatIntBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1intBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormatIntBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1half4/title",
          "value": "MDLVertexFormatHalf4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1half4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormatHalf4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1uIntBits/title",
          "value": "MDLVertexFormatUIntBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1uIntBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormatUIntBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1uChar/title",
          "value": "MDLVertexFormatUChar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1uChar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormatUChar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1uShortBits/title",
          "value": "MDLVertexFormatUShortBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1uShortBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormatUShortBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1uShortNormalizedBits/title",
          "value": "MDLVertexFormatUShortNormalizedBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1uShortNormalizedBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormatUShortNormalizedBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1invalid/title",
          "value": "MDLVertexFormatInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1invalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormatInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1shortBits/title",
          "value": "MDLVertexFormatShortBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1shortBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormatShortBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1format/title",
          "value": "format"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttribute~1format/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "format"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1halfBits/title",
          "value": "MDLVertexFormatHalfBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1halfBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormatHalfBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat/title",
          "value": "MDLVertexFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1uCharNormalizedBits/title",
          "value": "MDLVertexFormatUCharNormalizedBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1uCharNormalizedBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormatUCharNormalizedBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1uCharBits/title",
          "value": "MDLVertexFormatUCharBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1uCharBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormatUCharBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1charNormalizedBits/title",
          "value": "MDLVertexFormatCharNormalizedBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1charNormalizedBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormatCharNormalizedBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1shortNormalizedBits/title",
          "value": "MDLVertexFormatShortNormalizedBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexFormat~1shortNormalizedBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexFormatShortNormalizedBits"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlvertexformat/half4"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlvertexformat/half4"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
