{
  "abstract": [
    {
      "text": "The device’s volume up button.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCUIDevice",
        "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/volumeUp"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@XCUIDeviceButton@XCUIDeviceButtonVolumeUp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "volumeUp"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCUIDeviceButtonVolumeUp"
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "XCUIDevice.Button.volumeUp"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "volumeUp"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This device button isn’t available for UI testing in the Simulator.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIDevice": {
      "abstract": [
        {
          "text": "A proxy that can simulate physical buttons, device orientation, and Siri interaction for an iOS, watchOS, or tvOS device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIDevice"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIDevice"
        }
      ],
      "role": "symbol",
      "title": "XCUIDevice",
      "type": "topic",
      "url": "/documentation/xctest/xcuidevice"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button": {
      "abstract": [
        {
          "text": "A physical button on an iOS device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Button"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Button"
        }
      ],
      "role": "symbol",
      "title": "XCUIDevice.Button",
      "type": "topic",
      "url": "/documentation/xctest/xcuidevice/button"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/action": {
      "abstract": [
        {
          "text": "The device’s action button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "action"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/action",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIDeviceButtonAction"
        }
      ],
      "role": "symbol",
      "title": "XCUIDevice.Button.action",
      "type": "topic",
      "url": "/documentation/xctest/xcuidevice/button/action"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/camera": {
      "abstract": [
        {
          "text": "The device’s Camera Control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "camera"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/camera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIDeviceButtonCamera"
        }
      ],
      "role": "symbol",
      "title": "XCUIDevice.Button.camera",
      "type": "topic",
      "url": "/documentation/xctest/xcuidevice/button/camera"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/home": {
      "abstract": [
        {
          "text": "The device’s home button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/home",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIDeviceButtonHome"
        }
      ],
      "role": "symbol",
      "title": "XCUIDevice.Button.home",
      "type": "topic",
      "url": "/documentation/xctest/xcuidevice/button/home"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/volumeDown": {
      "abstract": [
        {
          "text": "The device’s volume down button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "volumeDown"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/volumeDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIDeviceButtonVolumeDown"
        }
      ],
      "role": "symbol",
      "title": "XCUIDevice.Button.volumeDown",
      "type": "topic",
      "url": "/documentation/xctest/xcuidevice/button/volumedown"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/volumeUp": {
      "abstract": [
        {
          "text": "The device’s volume up button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "volumeUp"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/volumeUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIDeviceButtonVolumeUp"
        }
      ],
      "role": "symbol",
      "title": "XCUIDevice.Button.volumeUp",
      "type": "topic",
      "url": "/documentation/xctest/xcuidevice/button/volumeup"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Device-Buttons",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/home",
        "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/volumeDown",
        "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/action",
        "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/camera",
        "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/home",
        "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/volumeDown",
        "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/action",
        "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/camera"
      ],
      "title": "Device Buttons"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCUIDeviceButtonVolumeUp"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIDeviceButtonVolumeUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest",
                "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Device-Buttons",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/home",
                "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/volumeDown",
                "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/action",
                "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/camera",
                "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/home",
                "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/volumeDown",
                "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/action",
                "doc://com.apple.xctest/documentation/XCTest/XCUIDevice/Button/camera"
              ],
              "title": "Device Buttons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "XCUIDeviceButtonVolumeUp"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIDevice/title",
          "value": "XCUIDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIDevice~1Button~1action/title",
          "value": "XCUIDeviceButtonAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIDevice~1Button~1action/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIDeviceButtonAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIDevice~1Button/title",
          "value": "XCUIDeviceButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIDevice~1Button/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIDeviceButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIDevice~1Button/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIDeviceButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIDevice~1Button~1volumeDown/title",
          "value": "XCUIDeviceButtonVolumeDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIDevice~1Button~1volumeDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIDeviceButtonVolumeDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIDevice~1Button~1volumeUp/title",
          "value": "XCUIDeviceButtonVolumeUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIDevice~1Button~1volumeUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIDeviceButtonVolumeUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIDevice~1Button~1home/title",
          "value": "XCUIDeviceButtonHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIDevice~1Button~1home/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIDeviceButtonHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIDevice~1Button~1camera/title",
          "value": "XCUIDeviceButtonCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIDevice~1Button~1camera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIDeviceButtonCamera"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xcuidevice/button/volumeup"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xcuidevice/button/volumeup"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
