{
  "abstract": [
    {
      "text": "Strings that represent the possible values of the launch options direction mode key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/directions-mode-values"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Directions mode values"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For a list of possible values, see the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " documentation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDefault": {
      "abstract": [
        {
          "text": "Directions that match the user’s preferred transportation type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeDefault"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsDirectionsModeDefault",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsdirectionsmodedefault"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDriving": {
      "abstract": [
        {
          "text": "Driving directions between the specified start and end points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeDriving"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDriving",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeDriving"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsDirectionsModeDriving",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsdirectionsmodedriving"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeKey": {
      "abstract": [
        {
          "text": "The mode of transportation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeKey"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsDirectionsModeKey",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsdirectionsmodekey"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeTransit": {
      "abstract": [
        {
          "text": "Public transit directions between the specified start and end points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeTransit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeTransit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeTransit"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsDirectionsModeTransit",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsdirectionsmodetransit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeWalking": {
      "abstract": [
        {
          "text": "Walking directions between the specified start and end points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeWalking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeWalking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeWalking"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsDirectionsModeWalking",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsdirectionsmodewalking"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem": {
      "abstract": [
        {
          "text": "A point of interest on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapItem"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapItem"
        }
      ],
      "role": "symbol",
      "title": "MKMapItem",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem"
    },
    "doc://com.apple.mapkit/documentation/MapKit/launch-options-dictionary-keys": {
      "abstract": [
        {
          "text": "Launch options to specify when opening map items in the Maps app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/launch-options-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Launch options dictionary keys",
      "type": "topic",
      "url": "/documentation/mapkit/launch-options-dictionary-keys"
    },
    "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit": {
      "abstract": [],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MapKit for AppKit and UIKit",
      "type": "topic",
      "url": "/documentation/mapkit/mapkit-for-appkit-and-uikit"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Opening-items-at-launch-time",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/launch-options-dictionary-keys"
      ],
      "title": "Opening items at launch time"
    }
  ],
  "topicSections": [
    {
      "anchor": "Directions-keys",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDriving",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeWalking",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeTransit",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDefault"
      ],
      "title": "Directions keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Directions-keys",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDriving",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeWalking",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeTransit",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDefault"
              ],
              "title": "Directions keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Opening-items-at-launch-time",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/launch-options-dictionary-keys"
              ],
              "title": "Opening items at launch time"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeTransit/title",
          "value": "MKLaunchOptionsDirectionsModeTransit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeTransit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsDirectionsModeTransit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem/title",
          "value": "MKMapItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeKey/title",
          "value": "MKLaunchOptionsDirectionsModeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsDirectionsModeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeDriving/title",
          "value": "MKLaunchOptionsDirectionsModeDriving"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeDriving/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsDirectionsModeDriving"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeDefault/title",
          "value": "MKLaunchOptionsDirectionsModeDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsDirectionsModeDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeWalking/title",
          "value": "MKLaunchOptionsDirectionsModeWalking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeWalking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsDirectionsModeWalking"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/directions-mode-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/directions-mode-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
