{
  "abstract": [
    {
      "text": "Configure your routing app to support providing directions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/enabling-maps-capability-in-xcode"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Enabling Maps capability in Xcode"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A routing app, an iOS app that provides point-to-point directions, requires Maps capability to make those directions available to Maps and other apps. Maps capability allows an app to provide specific directions beyond what the Maps app supports, including subway routes, hiking trails, and bike paths. Use Xcode to enable Maps capability and select the supported modes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-Maps-Capability-to-Your-Project",
          "level": 3,
          "text": "Add Maps Capability to Your Project",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Open your project with Xcode. In the Project navigator, select your project.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Choose the target for the app in the Targets section of the outline view.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click the Signing & Capabilities tab in the project editor.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the toolbar, click the Library button (+) to open the Capabilities library and select Maps capability.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select one or more routing modes using the checkboxes displayed under the Maps capability.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The screenshot below shows the Maps capability:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3737976",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information on enabling capabilities in your app, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode/adding-capabilities-to-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For more information on providing directions in your app, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Xcode/adding-capabilities-to-your-app": {
      "abstract": [
        {
          "text": "Configure your target to include and customize capabilities that provide access to Apple’s app services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/adding-capabilities-to-your-app",
      "kind": "article",
      "role": "article",
      "title": "Adding capabilities to your app",
      "type": "topic",
      "url": "/documentation/Xcode/adding-capabilities-to-your-app"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDirections": {
      "abstract": [
        {
          "text": "A utility object that computes directions and travel-time information based on the route information you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKDirections"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDirections",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKDirections"
        }
      ],
      "role": "symbol",
      "title": "MKDirections",
      "type": "topic",
      "url": "/documentation/mapkit/mkdirections"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem": {
      "abstract": [
        {
          "text": "A point of interest on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapItem"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapItem"
        }
      ],
      "role": "symbol",
      "title": "MKMapItem",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapView": {
      "abstract": [
        {
          "text": "An embeddable map interface, similar to the one that the Maps app provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapView"
        }
      ],
      "role": "symbol",
      "title": "MKMapView",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids": {
      "abstract": [
        {
          "text": "Obtain information about a point of interest that persists over its lifetime.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids",
      "kind": "article",
      "role": "article",
      "title": "Identifying unique locations with Place IDs",
      "type": "topic",
      "url": "/documentation/mapkit/identifying-unique-locations-with-place-ids"
    },
    "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit": {
      "abstract": [],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MapKit for AppKit and UIKit",
      "type": "topic",
      "url": "/documentation/mapkit/mapkit-for-appkit-and-uikit"
    },
    "media-3737976": {
      "alt": "A screenshot showing the Maps capability with no route modes selected. ",
      "identifier": "media-3737976",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/552515a1d1d61d338158af21ea51563c/media-3737976@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapView",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapView",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItem"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView/title",
          "value": "MKMapView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem/title",
          "value": "MKMapItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections/title",
          "value": "MKDirections"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDirections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDirections"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/enabling-maps-capability-in-xcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/enabling-maps-capability-in-xcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
