{
  "abstract": [
    {
      "text": "Launch options to specify when opening map items in the Maps app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/launch-options-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Launch options dictionary keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You specify these keys in the launch options dictionary for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openMaps(with:launchOptions:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openInMaps(launchOptions:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsCameraKey": {
      "abstract": [
        {
          "text": "The virtual camera to use for viewing the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsCameraKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsCameraKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsCameraKey"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsCameraKey",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionscamerakey"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeKey": {
      "abstract": [
        {
          "text": "The mode of transportation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeKey"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsDirectionsModeKey",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsdirectionsmodekey"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapCenterKey": {
      "abstract": [
        {
          "text": "The coordinate value on which to center the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsMapCenterKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapCenterKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsMapCenterKey"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsMapCenterKey",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsmapcenterkey"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapSpanKey": {
      "abstract": [
        {
          "text": "The amount of the map to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsMapSpanKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapSpanKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsMapSpanKey"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsMapSpanKey",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsmapspankey"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapTypeKey": {
      "abstract": [
        {
          "text": "The type of map (standard, satellite, or hybrid) to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsMapTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsMapTypeKey"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsMapTypeKey",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsmaptypekey"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsShowsTrafficKey": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to display traffic information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsShowsTrafficKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsShowsTrafficKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsShowsTrafficKey"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsShowsTrafficKey",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsshowstraffickey"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem": {
      "abstract": [
        {
          "text": "A point of interest on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapItem"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapItem"
        }
      ],
      "role": "symbol",
      "title": "MKMapItem",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openInMaps(launchOptions:)": {
      "abstract": [
        {
          "text": "Opens the Maps app and displays the map item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openInMaps"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "launchOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openInMaps(launchOptions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openInMapsWithLaunchOptions:"
        }
      ],
      "role": "symbol",
      "title": "openInMaps(launchOptions:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/openinmaps(launchoptions:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openMaps(with:launchOptions:)": {
      "abstract": [
        {
          "text": "Opens the Maps app and displays the specified map items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openMaps"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItem",
          "text": "MKMapItem"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "launchOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openMaps(with:launchOptions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openMapsWithItems:launchOptions:"
        }
      ],
      "role": "symbol",
      "title": "openMaps(with:launchOptions:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/openmaps(with:launchoptions:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/directions-mode-values": {
      "abstract": [
        {
          "text": "Strings that represent the possible values of the launch options direction mode key.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/directions-mode-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Directions mode values",
      "type": "topic",
      "url": "/documentation/mapkit/directions-mode-values"
    },
    "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit": {
      "abstract": [],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MapKit for AppKit and UIKit",
      "type": "topic",
      "url": "/documentation/mapkit/mapkit-for-appkit-and-uikit"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Opening-items-at-launch-time",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/directions-mode-values"
      ],
      "title": "Opening items at launch time"
    }
  ],
  "topicSections": [
    {
      "anchor": "Launch-options",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeKey",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapTypeKey",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapCenterKey",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapSpanKey",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsShowsTrafficKey",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsCameraKey"
      ],
      "title": "Launch options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Launch-options",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeKey",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapTypeKey",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapCenterKey",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapSpanKey",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsShowsTrafficKey",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsCameraKey"
              ],
              "title": "Launch options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Opening-items-at-launch-time",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/directions-mode-values"
              ],
              "title": "Opening items at launch time"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem/title",
          "value": "MKMapItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsShowsTrafficKey/title",
          "value": "MKLaunchOptionsShowsTrafficKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsShowsTrafficKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsShowsTrafficKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsMapCenterKey/title",
          "value": "MKLaunchOptionsMapCenterKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsMapCenterKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsMapCenterKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsMapSpanKey/title",
          "value": "MKLaunchOptionsMapSpanKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsMapSpanKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsMapSpanKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsMapTypeKey/title",
          "value": "MKLaunchOptionsMapTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsMapTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsMapTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsCameraKey/title",
          "value": "MKLaunchOptionsCameraKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsCameraKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsCameraKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeKey/title",
          "value": "MKLaunchOptionsDirectionsModeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsDirectionsModeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1openInMaps(launchOptions:)/title",
          "value": "openInMapsWithLaunchOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1openInMaps(launchOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "openInMapsWithLaunchOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1openMaps(with:launchOptions:)/title",
          "value": "openMapsWithItems:launchOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1openMaps(with:launchOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "openMapsWithItems:launchOptions:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/launch-options-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/launch-options-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
