{
  "abstract": [
    {
      "text": "Create annotations to add indicators and additional details for specific locations on a map.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/mapkit-annotations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "MapKit annotations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAnnotation": {
      "abstract": [
        {
          "text": "An interface for associating your content with a specific map location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKAnnotation"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAnnotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAnnotation"
        }
      ],
      "role": "symbol",
      "title": "MKAnnotation",
      "type": "topic",
      "url": "/documentation/mapkit/mkannotation"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView": {
      "abstract": [
        {
          "text": "The visual representation of one of your annotation objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKAnnotationView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAnnotationView"
        }
      ],
      "role": "symbol",
      "title": "MKAnnotationView",
      "type": "topic",
      "url": "/documentation/mapkit/mkannotationview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKClusterAnnotation": {
      "abstract": [
        {
          "text": "An annotation that groups two or more distinct annotations into a single entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKClusterAnnotation"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKClusterAnnotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKClusterAnnotation"
        }
      ],
      "role": "symbol",
      "title": "MKClusterAnnotation",
      "type": "topic",
      "url": "/documentation/mapkit/mkclusterannotation"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItemAnnotation": {
      "abstract": [
        {
          "text": "An annotation that represents a map item",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapItemAnnotation"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItemAnnotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapItemAnnotation"
        }
      ],
      "role": "symbol",
      "title": "MKMapItemAnnotation",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitemannotation"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMarkerAnnotationView": {
      "abstract": [
        {
          "text": "An annotation view that displays a balloon-shaped marker at the designated location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMarkerAnnotationView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMarkerAnnotationView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMarkerAnnotationView"
        }
      ],
      "role": "symbol",
      "title": "MKMarkerAnnotationView",
      "type": "topic",
      "url": "/documentation/mapkit/mkmarkerannotationview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPinAnnotationView": {
      "abstract": [
        {
          "text": "An annotation view that displays a pin image on the map.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPinAnnotationView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPinAnnotationView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPinAnnotationView"
        }
      ],
      "role": "symbol",
      "title": "MKPinAnnotationView",
      "type": "topic",
      "url": "/documentation/mapkit/mkpinannotationview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPlacemark": {
      "abstract": [
        {
          "text": "A user-friendly description of a location on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPlacemark"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPlacemark",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPlacemark"
        }
      ],
      "role": "symbol",
      "title": "MKPlacemark",
      "type": "topic",
      "url": "/documentation/mapkit/mkplacemark"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPointAnnotation": {
      "abstract": [
        {
          "text": "A string-based piece of location-specific data that you apply to a specific point on a map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPointAnnotation"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointAnnotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPointAnnotation"
        }
      ],
      "role": "symbol",
      "title": "MKPointAnnotation",
      "type": "topic",
      "url": "/documentation/mapkit/mkpointannotation"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKUserLocation": {
      "abstract": [
        {
          "text": "An annotation that reflects the user’s location on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKUserLocation"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKUserLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKUserLocation"
        }
      ],
      "role": "symbol",
      "title": "MKUserLocation",
      "type": "topic",
      "url": "/documentation/mapkit/mkuserlocation"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKUserLocationView": {
      "abstract": [
        {
          "text": "A configurable annotation that shows the user’s location using the default MapKit style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKUserLocationView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKUserLocationView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKUserLocationView"
        }
      ],
      "role": "symbol",
      "title": "MKUserLocationView",
      "type": "topic",
      "url": "/documentation/mapkit/mkuserlocationview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapAnnotation": {
      "abstract": [
        {
          "text": "A customizable annotation that marks a map location.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapAnnotation"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapAnnotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapAnnotation"
        }
      ],
      "role": "symbol",
      "title": "MapAnnotation",
      "type": "topic",
      "url": "/documentation/mapkit/mapannotation"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapAnnotationProtocol": {
      "abstract": [
        {
          "text": "A protocol that represents the possible return types of annotations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapAnnotationProtocol"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapAnnotationProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapAnnotationProtocol"
        }
      ],
      "role": "symbol",
      "title": "MapAnnotationProtocol",
      "type": "topic",
      "url": "/documentation/mapkit/mapannotationprotocol"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapMarker": {
      "abstract": [
        {
          "text": "A balloon-shaped annotation used to indicate the location on a map.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapMarker"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapMarker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapMarker"
        }
      ],
      "role": "symbol",
      "title": "MapMarker",
      "type": "topic",
      "url": "/documentation/mapkit/mapmarker"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapPin": {
      "abstract": [
        {
          "text": "A pin-shaped annotation used to indicate a location on a map.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapPin"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapPin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapPin"
        }
      ],
      "role": "symbol",
      "title": "MapPin",
      "type": "topic",
      "url": "/documentation/mapkit/mappin"
    },
    "doc://com.apple.mapkit/documentation/MapKit/annotating-a-map-with-custom-data": {
      "abstract": [
        {
          "text": "Annotate a map with location-specific data using default and customized annotation views and callouts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/annotating-a-map-with-custom-data",
      "kind": "article",
      "role": "sampleCode",
      "title": "Annotating a Map with Custom Data",
      "type": "topic",
      "url": "/documentation/mapkit/annotating-a-map-with-custom-data"
    },
    "doc://com.apple.mapkit/documentation/MapKit/converting-a-user-s-location-to-a-descriptive-placemark": {
      "abstract": [
        {
          "text": "Transform the user’s location that displays on a map into an informative textual description by reverse geocoding.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/converting-a-user-s-location-to-a-descriptive-placemark",
      "kind": "article",
      "role": "article",
      "title": "Converting a user’s location to a descriptive placemark",
      "type": "topic",
      "url": "/documentation/mapkit/converting-a-user-s-location-to-a-descriptive-placemark"
    },
    "doc://com.apple.mapkit/documentation/MapKit/decluttering-a-map-with-mapkit-annotation-clustering": {
      "abstract": [
        {
          "text": "Enhance the readability of a map by replacing overlapping annotations with a clustering annotation view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/decluttering-a-map-with-mapkit-annotation-clustering",
      "kind": "article",
      "role": "sampleCode",
      "title": "Decluttering a Map with MapKit Annotation Clustering",
      "type": "topic",
      "url": "/documentation/mapkit/decluttering-a-map-with-mapkit-annotation-clustering"
    },
    "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit": {
      "abstract": [],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MapKit for AppKit and UIKit",
      "type": "topic",
      "url": "/documentation/mapkit/mapkit-for-appkit-and-uikit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/mapkit-overlays": {
      "abstract": [
        {
          "text": "Create overlays to highlight geographic regions or paths.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/mapkit-overlays",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MapKit overlays",
      "type": "topic",
      "url": "/documentation/mapkit/mapkit-overlays"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Annotations-and-overlays",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/mapkit-overlays"
      ],
      "title": "Annotations and overlays"
    }
  ],
  "topicSections": [
    {
      "anchor": "Location-annotations",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/annotating-a-map-with-custom-data",
        "doc://com.apple.mapkit/documentation/MapKit/MKPointAnnotation",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItemAnnotation",
        "doc://com.apple.mapkit/documentation/MapKit/MKMarkerAnnotationView",
        "doc://com.apple.mapkit/documentation/MapKit/MKPinAnnotationView"
      ],
      "title": "Location annotations"
    },
    {
      "anchor": "Grouped-annotations",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/decluttering-a-map-with-mapkit-annotation-clustering",
        "doc://com.apple.mapkit/documentation/MapKit/MKClusterAnnotation"
      ],
      "title": "Grouped annotations"
    },
    {
      "anchor": "User-location",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/converting-a-user-s-location-to-a-descriptive-placemark",
        "doc://com.apple.mapkit/documentation/MapKit/MKUserLocation",
        "doc://com.apple.mapkit/documentation/MapKit/MKUserLocationView"
      ],
      "title": "User location"
    },
    {
      "anchor": "Annotations-in-SwiftUI",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MapMarker",
        "doc://com.apple.mapkit/documentation/MapKit/MapPin",
        "doc://com.apple.mapkit/documentation/MapKit/MapAnnotation",
        "doc://com.apple.mapkit/documentation/MapKit/MapAnnotationProtocol"
      ],
      "title": "Annotations in SwiftUI"
    },
    {
      "anchor": "Shared-behavior",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKPlacemark",
        "doc://com.apple.mapkit/documentation/MapKit/MKAnnotation",
        "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView"
      ],
      "title": "Shared behavior"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Location-annotations",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/annotating-a-map-with-custom-data",
                "doc://com.apple.mapkit/documentation/MapKit/MKPointAnnotation",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItemAnnotation",
                "doc://com.apple.mapkit/documentation/MapKit/MKMarkerAnnotationView",
                "doc://com.apple.mapkit/documentation/MapKit/MKPinAnnotationView"
              ],
              "title": "Location annotations"
            },
            {
              "anchor": "Grouped-annotations",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/decluttering-a-map-with-mapkit-annotation-clustering",
                "doc://com.apple.mapkit/documentation/MapKit/MKClusterAnnotation"
              ],
              "title": "Grouped annotations"
            },
            {
              "anchor": "User-location",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/converting-a-user-s-location-to-a-descriptive-placemark",
                "doc://com.apple.mapkit/documentation/MapKit/MKUserLocation",
                "doc://com.apple.mapkit/documentation/MapKit/MKUserLocationView"
              ],
              "title": "User location"
            },
            {
              "anchor": "Shared-behavior",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKPlacemark",
                "doc://com.apple.mapkit/documentation/MapKit/MKAnnotation",
                "doc://com.apple.mapkit/documentation/MapKit/MKAnnotationView"
              ],
              "title": "Shared behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Annotations-and-overlays",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/mapkit-overlays"
              ],
              "title": "Annotations and overlays"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKUserLocation/title",
          "value": "MKUserLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKUserLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKUserLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKUserLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKUserLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointAnnotation/title",
          "value": "MKPointAnnotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointAnnotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointAnnotation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemAnnotation/title",
          "value": "MKMapItemAnnotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemAnnotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemAnnotation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotationView/title",
          "value": "MKAnnotationView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotationView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAnnotationView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotationView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAnnotationView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPinAnnotationView/title",
          "value": "MKPinAnnotationView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPinAnnotationView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPinAnnotationView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPinAnnotationView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPinAnnotationView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotation/title",
          "value": "MKAnnotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKUserLocationView/title",
          "value": "MKUserLocationView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKUserLocationView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKUserLocationView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKUserLocationView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKUserLocationView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKClusterAnnotation/title",
          "value": "MKClusterAnnotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKClusterAnnotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKClusterAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKClusterAnnotation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKClusterAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPlacemark/title",
          "value": "MKPlacemark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPlacemark/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPlacemark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPlacemark/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPlacemark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMarkerAnnotationView/title",
          "value": "MKMarkerAnnotationView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMarkerAnnotationView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMarkerAnnotationView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMarkerAnnotationView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMarkerAnnotationView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mapkit-annotations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mapkit-annotations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
