{
  "abstract": [
    {
      "text": "Create overlays to highlight geographic regions or paths.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/mapkit-overlays"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "MapKit overlays"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKCircle": {
      "abstract": [
        {
          "text": "A circular overlay with a configurable radius that you center on a geographic coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKCircle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCircle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKCircle"
        }
      ],
      "role": "symbol",
      "title": "MKCircle",
      "type": "topic",
      "url": "/documentation/mapkit/mkcircle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKCircleRenderer": {
      "abstract": [
        {
          "text": "The visual representation of a circular overlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKCircleRenderer"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCircleRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKCircleRenderer"
        }
      ],
      "role": "symbol",
      "title": "MKCircleRenderer",
      "type": "topic",
      "url": "/documentation/mapkit/mkcirclerenderer"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKGeodesicPolyline": {
      "abstract": [
        {
          "text": "An open polygon overlay consisting of line segments that follow the contours of the Earth to create the shortest path between the specified points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKGeodesicPolyline"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKGeodesicPolyline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKGeodesicPolyline"
        }
      ],
      "role": "symbol",
      "title": "MKGeodesicPolyline",
      "type": "topic",
      "url": "/documentation/mapkit/mkgeodesicpolyline"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKGradientPolylineRenderer": {
      "abstract": [
        {
          "text": "A visual representation of any polyline overlay object with a gradient.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKGradientPolylineRenderer"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKGradientPolylineRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKGradientPolylineRenderer"
        }
      ],
      "role": "symbol",
      "title": "MKGradientPolylineRenderer",
      "type": "topic",
      "url": "/documentation/mapkit/mkgradientpolylinerenderer"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMultiPoint": {
      "abstract": [
        {
          "text": "An abstract class that defines the common behavior that open and closed polygon overlays share.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMultiPoint"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMultiPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMultiPoint"
        }
      ],
      "role": "symbol",
      "title": "MKMultiPoint",
      "type": "topic",
      "url": "/documentation/mapkit/mkmultipoint"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolygon": {
      "abstract": [
        {
          "text": "A collection of multiple closed polygon overlays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMultiPolygon"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolygon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMultiPolygon"
        }
      ],
      "role": "symbol",
      "title": "MKMultiPolygon",
      "type": "topic",
      "url": "/documentation/mapkit/mkmultipolygon"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolygonRenderer": {
      "abstract": [
        {
          "text": "The visual representation of multiple polygon overlays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMultiPolygonRenderer"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolygonRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMultiPolygonRenderer"
        }
      ],
      "role": "symbol",
      "title": "MKMultiPolygonRenderer",
      "type": "topic",
      "url": "/documentation/mapkit/mkmultipolygonrenderer"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolyline": {
      "abstract": [
        {
          "text": "A collection of multipolyline shapes, each consisting of one or more connected line segments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMultiPolyline"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolyline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMultiPolyline"
        }
      ],
      "role": "symbol",
      "title": "MKMultiPolyline",
      "type": "topic",
      "url": "/documentation/mapkit/mkmultipolyline"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolylineRenderer": {
      "abstract": [
        {
          "text": "A visual representation of multiple polyline overlay objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMultiPolylineRenderer"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolylineRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMultiPolylineRenderer"
        }
      ],
      "role": "symbol",
      "title": "MKMultiPolylineRenderer",
      "type": "topic",
      "url": "/documentation/mapkit/mkmultipolylinerenderer"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlay": {
      "abstract": [
        {
          "text": "An interface for associating content with a specific map region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKOverlay"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKOverlay"
        }
      ],
      "role": "symbol",
      "title": "MKOverlay",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlay"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer": {
      "abstract": [
        {
          "text": "The visual representation of a path-based overlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKOverlayPathRenderer"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKOverlayPathRenderer"
        }
      ],
      "role": "symbol",
      "title": "MKOverlayPathRenderer",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlaypathrenderer"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayRenderer": {
      "abstract": [
        {
          "text": "The shared infrastructure for drawing overlays on the map surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKOverlayRenderer"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKOverlayRenderer"
        }
      ],
      "role": "symbol",
      "title": "MKOverlayRenderer",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlayrenderer"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPlacemark": {
      "abstract": [
        {
          "text": "A user-friendly description of a location on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPlacemark"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPlacemark",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPlacemark"
        }
      ],
      "role": "symbol",
      "title": "MKPlacemark",
      "type": "topic",
      "url": "/documentation/mapkit/mkplacemark"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPolygon": {
      "abstract": [
        {
          "text": "A closed polygon overlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPolygon"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolygon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPolygon"
        }
      ],
      "role": "symbol",
      "title": "MKPolygon",
      "type": "topic",
      "url": "/documentation/mapkit/mkpolygon"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPolygonRenderer": {
      "abstract": [
        {
          "text": "The visual representation of a single polygon overlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPolygonRenderer"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolygonRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPolygonRenderer"
        }
      ],
      "role": "symbol",
      "title": "MKPolygonRenderer",
      "type": "topic",
      "url": "/documentation/mapkit/mkpolygonrenderer"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPolyline": {
      "abstract": [
        {
          "text": "An open polygon overlay consisting of one or more connected line segments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPolyline"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolyline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPolyline"
        }
      ],
      "role": "symbol",
      "title": "MKPolyline",
      "type": "topic",
      "url": "/documentation/mapkit/mkpolyline"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer": {
      "abstract": [
        {
          "text": "A visual representation of any polyline overlay object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPolylineRenderer"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPolylineRenderer"
        }
      ],
      "role": "symbol",
      "title": "MKPolylineRenderer",
      "type": "topic",
      "url": "/documentation/mapkit/mkpolylinerenderer"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKShape": {
      "abstract": [
        {
          "text": "An abstract class that defines the basic properties for all shape-based overlay objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKShape"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKShape",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKShape"
        }
      ],
      "role": "symbol",
      "title": "MKShape",
      "type": "topic",
      "url": "/documentation/mapkit/mkshape"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKTileOverlay": {
      "abstract": [
        {
          "text": "An overlay that covers an area of the map with tiles of bitmap images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKTileOverlay"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKTileOverlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKTileOverlay"
        }
      ],
      "role": "symbol",
      "title": "MKTileOverlay",
      "type": "topic",
      "url": "/documentation/mapkit/mktileoverlay"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKTileOverlayRenderer": {
      "abstract": [
        {
          "text": "The renderer for a tile overlay that handles the drawing of bitmap images on the map surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKTileOverlayRenderer"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKTileOverlayRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKTileOverlayRenderer"
        }
      ],
      "role": "symbol",
      "title": "MKTileOverlayRenderer",
      "type": "topic",
      "url": "/documentation/mapkit/mktileoverlayrenderer"
    },
    "doc://com.apple.mapkit/documentation/MapKit/displaying-an-updating-path-of-a-user-s-location-history": {
      "abstract": [
        {
          "text": "Continually update a MapKit overlay displaying the path a user travels.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/displaying-an-updating-path-of-a-user-s-location-history",
      "kind": "article",
      "role": "sampleCode",
      "title": "Displaying an updating path of a user’s location history",
      "type": "topic",
      "url": "/documentation/mapkit/displaying-an-updating-path-of-a-user-s-location-history"
    },
    "doc://com.apple.mapkit/documentation/MapKit/displaying-overlays-on-a-map": {
      "abstract": [
        {
          "text": "Add regions of layered content to a map view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/displaying-overlays-on-a-map",
      "kind": "article",
      "role": "sampleCode",
      "title": "Displaying overlays on a map",
      "type": "topic",
      "url": "/documentation/mapkit/displaying-overlays-on-a-map"
    },
    "doc://com.apple.mapkit/documentation/MapKit/mapkit-annotations": {
      "abstract": [
        {
          "text": "Create annotations to add indicators and additional details for specific locations on a map.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/mapkit-annotations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MapKit annotations",
      "type": "topic",
      "url": "/documentation/mapkit/mapkit-annotations"
    },
    "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit": {
      "abstract": [],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MapKit for AppKit and UIKit",
      "type": "topic",
      "url": "/documentation/mapkit/mapkit-for-appkit-and-uikit"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Annotations-and-overlays",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/mapkit-annotations"
      ],
      "title": "Annotations and overlays"
    }
  ],
  "topicSections": [
    {
      "anchor": "Samples",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/displaying-overlays-on-a-map",
        "doc://com.apple.mapkit/documentation/MapKit/displaying-an-updating-path-of-a-user-s-location-history"
      ],
      "title": "Samples"
    },
    {
      "anchor": "Circular-overlays",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKCircle",
        "doc://com.apple.mapkit/documentation/MapKit/MKCircleRenderer"
      ],
      "title": "Circular overlays"
    },
    {
      "anchor": "Custom-shape-overlays",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKPolygon",
        "doc://com.apple.mapkit/documentation/MapKit/MKPolygonRenderer",
        "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolygon",
        "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolygonRenderer",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer"
      ],
      "title": "Custom shape overlays"
    },
    {
      "anchor": "Multiple-segment-lines",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKPolyline",
        "doc://com.apple.mapkit/documentation/MapKit/MKGeodesicPolyline",
        "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolyline",
        "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer",
        "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolylineRenderer",
        "doc://com.apple.mapkit/documentation/MapKit/MKGradientPolylineRenderer"
      ],
      "title": "Multiple segment lines"
    },
    {
      "anchor": "Tiled-image-overlays",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKTileOverlay",
        "doc://com.apple.mapkit/documentation/MapKit/MKTileOverlayRenderer"
      ],
      "title": "Tiled image overlays"
    },
    {
      "anchor": "Shared-behavior",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlay",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayRenderer",
        "doc://com.apple.mapkit/documentation/MapKit/MKShape",
        "doc://com.apple.mapkit/documentation/MapKit/MKMultiPoint",
        "doc://com.apple.mapkit/documentation/MapKit/MKPlacemark"
      ],
      "title": "Shared behavior"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Samples",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/displaying-overlays-on-a-map",
                "doc://com.apple.mapkit/documentation/MapKit/displaying-an-updating-path-of-a-user-s-location-history"
              ],
              "title": "Samples"
            },
            {
              "anchor": "Circular-overlays",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKCircle",
                "doc://com.apple.mapkit/documentation/MapKit/MKCircleRenderer"
              ],
              "title": "Circular overlays"
            },
            {
              "anchor": "Custom-shape-overlays",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKPolygon",
                "doc://com.apple.mapkit/documentation/MapKit/MKPolygonRenderer",
                "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolygon",
                "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolygonRenderer",
                "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer"
              ],
              "title": "Custom shape overlays"
            },
            {
              "anchor": "Multiple-segment-lines",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKPolyline",
                "doc://com.apple.mapkit/documentation/MapKit/MKGeodesicPolyline",
                "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolyline",
                "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer",
                "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolylineRenderer",
                "doc://com.apple.mapkit/documentation/MapKit/MKGradientPolylineRenderer"
              ],
              "title": "Multiple segment lines"
            },
            {
              "anchor": "Tiled-image-overlays",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKTileOverlay",
                "doc://com.apple.mapkit/documentation/MapKit/MKTileOverlayRenderer"
              ],
              "title": "Tiled image overlays"
            },
            {
              "anchor": "Shared-behavior",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKOverlay",
                "doc://com.apple.mapkit/documentation/MapKit/MKOverlayRenderer",
                "doc://com.apple.mapkit/documentation/MapKit/MKShape",
                "doc://com.apple.mapkit/documentation/MapKit/MKMultiPoint",
                "doc://com.apple.mapkit/documentation/MapKit/MKPlacemark"
              ],
              "title": "Shared behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Annotations-and-overlays",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/mapkit-annotations"
              ],
              "title": "Annotations and overlays"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPolygonRenderer/title",
          "value": "MKMultiPolygonRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPolygonRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMultiPolygonRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPolygonRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMultiPolygonRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCircle/title",
          "value": "MKCircle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCircle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCircle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCircle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCircle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineRenderer/title",
          "value": "MKPolylineRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolylineRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolylineRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPolygon/title",
          "value": "MKMultiPolygon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPolygon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMultiPolygon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPolygon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMultiPolygon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPoint/title",
          "value": "MKMultiPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMultiPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMultiPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKTileOverlayRenderer/title",
          "value": "MKTileOverlayRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKTileOverlayRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKTileOverlayRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKTileOverlayRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKTileOverlayRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKTileOverlay/title",
          "value": "MKTileOverlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKTileOverlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKTileOverlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKTileOverlay/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKTileOverlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolyline/title",
          "value": "MKPolyline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolyline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolyline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolyline/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolyline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPolylineRenderer/title",
          "value": "MKMultiPolylineRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPolylineRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMultiPolylineRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPolylineRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMultiPolylineRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKShape/title",
          "value": "MKShape"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKShape/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKShape/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPolyline/title",
          "value": "MKMultiPolyline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPolyline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMultiPolyline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPolyline/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMultiPolyline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPlacemark/title",
          "value": "MKPlacemark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPlacemark/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPlacemark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPlacemark/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPlacemark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayRenderer/title",
          "value": "MKOverlayRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer/title",
          "value": "MKOverlayPathRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayPathRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayPathRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCircleRenderer/title",
          "value": "MKCircleRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCircleRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCircleRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCircleRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCircleRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlay/title",
          "value": "MKOverlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlay/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGeodesicPolyline/title",
          "value": "MKGeodesicPolyline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGeodesicPolyline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKGeodesicPolyline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGeodesicPolyline/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKGeodesicPolyline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGradientPolylineRenderer/title",
          "value": "MKGradientPolylineRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGradientPolylineRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKGradientPolylineRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGradientPolylineRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKGradientPolylineRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolygon/title",
          "value": "MKPolygon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolygon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolygon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolygon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolygon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolygonRenderer/title",
          "value": "MKPolygonRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolygonRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolygonRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolygonRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolygonRenderer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mapkit-overlays"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mapkit-overlays"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
