{
  "abstract": [
    {
      "text": "MapKit for SwiftUI allows you to build map-centric views and apps across Apple platforms. You can design expressive and highly interactive Maps with minimal code by composing views, using ViewBuilders and view modifiers.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-swiftui"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "MapKit for SwiftUI"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Like MapKit for AppKit and UIKit, MapKit for SwiftUI allows you to take advantage of map styles ranging from satellite imagery to rich, 3D perspective imagery to present vivid maps. Using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapContentBuilder",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " you can configure your maps to show ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/Marker",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/Annotation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " views, or — for more specialized content — you can design your own SwiftUI views to place on the map. To add even more interactivity, MapKit for SwiftUI supports overlays to highlight areas on the map, enabling you to animate paths and directions using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapPolyline",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or make it easy for people to dig deeper into on the ground details with tappable points of interest. People who use your app can also explore at street level using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/LookAroundPreview",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and Look Around viewer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "For more information about integrating MapKit into your app using SwiftUI, see WWDC23 session 10043: ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/videos/play/wwdc2023/10043/",
                  "isActive": true,
                  "type": "reference"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/Annotation": {
      "abstract": [
        {
          "text": "A customizable annotation used to indicate a location on a map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Annotation"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/Annotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Annotation"
        }
      ],
      "role": "symbol",
      "title": "Annotation",
      "type": "topic",
      "url": "/documentation/mapkit/annotation"
    },
    "doc://com.apple.mapkit/documentation/MapKit/DefaultUserAnnotationContent": {
      "abstract": [
        {
          "text": "A structure that represents the view to show at the user’s location on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DefaultUserAnnotationContent"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/DefaultUserAnnotationContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DefaultUserAnnotationContent"
        }
      ],
      "role": "symbol",
      "title": "DefaultUserAnnotationContent",
      "type": "topic",
      "url": "/documentation/mapkit/defaultuserannotationcontent"
    },
    "doc://com.apple.mapkit/documentation/MapKit/DynamicMapContent": {
      "abstract": [
        {
          "text": "A  type of view that generates views from an underlying collection of data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DynamicMapContent"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/DynamicMapContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DynamicMapContent"
        }
      ],
      "role": "symbol",
      "title": "DynamicMapContent",
      "type": "topic",
      "url": "/documentation/mapkit/dynamicmapcontent"
    },
    "doc://com.apple.mapkit/documentation/MapKit/EmptyMapContent": {
      "abstract": [
        {
          "text": "A map content element that doesn’t contain any content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EmptyMapContent"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/EmptyMapContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EmptyMapContent"
        }
      ],
      "role": "symbol",
      "title": "EmptyMapContent",
      "type": "topic",
      "url": "/documentation/mapkit/emptymapcontent"
    },
    "doc://com.apple.mapkit/documentation/MapKit/LookAroundPreview": {
      "abstract": [
        {
          "text": "A view that provides a Look Around preview for a specific geographic location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LookAroundPreview"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/LookAroundPreview",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LookAroundPreview"
        }
      ],
      "role": "symbol",
      "title": "LookAroundPreview",
      "type": "topic",
      "url": "/documentation/mapkit/lookaroundpreview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/Map": {
      "abstract": [
        {
          "text": "A view that displays an embedded map interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Map"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/Map",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Map"
        }
      ],
      "role": "symbol",
      "title": "Map",
      "type": "topic",
      "url": "/documentation/mapkit/map"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapCamera": {
      "abstract": [
        {
          "text": "Defines a virtual viewpoint above the map surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapCamera"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapCamera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapCamera"
        }
      ],
      "role": "symbol",
      "title": "MapCamera",
      "type": "topic",
      "url": "/documentation/mapkit/mapcamera"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapCameraBounds": {
      "abstract": [
        {
          "text": "Defines an optional boundary of an area within which the map’s center needs to remain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapCameraBounds"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapCameraBounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapCameraBounds"
        }
      ],
      "role": "symbol",
      "title": "MapCameraBounds",
      "type": "topic",
      "url": "/documentation/mapkit/mapcamerabounds"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition": {
      "abstract": [
        {
          "text": "A structure that describes how to position the map’s camera within the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapCameraPosition"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapCameraPosition"
        }
      ],
      "role": "symbol",
      "title": "MapCameraPosition",
      "type": "topic",
      "url": "/documentation/mapkit/mapcameraposition"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapCameraUpdateContext": {
      "abstract": [
        {
          "text": "A structure that defines additional information about the map camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapCameraUpdateContext"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapCameraUpdateContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapCameraUpdateContext"
        }
      ],
      "role": "symbol",
      "title": "MapCameraUpdateContext",
      "type": "topic",
      "url": "/documentation/mapkit/mapcameraupdatecontext"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapCameraUpdateFrequency": {
      "abstract": [
        {
          "text": "A structure that describes when the map camera updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapCameraUpdateFrequency"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapCameraUpdateFrequency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapCameraUpdateFrequency"
        }
      ],
      "role": "symbol",
      "title": "MapCameraUpdateFrequency",
      "type": "topic",
      "url": "/documentation/mapkit/mapcameraupdatefrequency"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapCircle": {
      "abstract": [
        {
          "text": "A circular overlay with a configurable radius that you center on a geographic coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapCircle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapCircle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapCircle"
        }
      ],
      "role": "symbol",
      "title": "MapCircle",
      "type": "topic",
      "url": "/documentation/mapkit/mapcircle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapCompass": {
      "abstract": [
        {
          "text": "A view that reflects the current orientation of the associated map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapCompass"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapCompass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapCompass"
        }
      ],
      "role": "symbol",
      "title": "MapCompass",
      "type": "topic",
      "url": "/documentation/mapkit/mapcompass"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapContent": {
      "abstract": [
        {
          "text": "A protocol used to construct map content such as controls, markers, and annotations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapContent"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapContent"
        }
      ],
      "role": "symbol",
      "title": "MapContent",
      "type": "topic",
      "url": "/documentation/mapkit/mapcontent"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapContent/mapItemDetailSelectionAccessory(_:)": {
      "abstract": [
        {
          "text": "Specifies the selection accessory to display for the selected map item content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapItemDetailSelectionAccessory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15_MapKit_SwiftUI0A33ItemDetailSelectionAccessoryStyleV",
          "text": "MapItemDetailSelectionAccessoryStyle"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15_MapKit_SwiftUI0A7ContentP",
          "text": "MapContent"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapContent/mapItemDetailSelectionAccessory(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "mapItemDetailSelectionAccessory(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mapcontent/mapitemdetailselectionaccessory(_:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapContentBuilder": {
      "abstract": [
        {
          "text": "A result builder that creates map content from closures you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapContentBuilder"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapContentBuilder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapContentBuilder"
        }
      ],
      "role": "symbol",
      "title": "MapContentBuilder",
      "type": "topic",
      "url": "/documentation/mapkit/mapcontentbuilder"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapContentView": {
      "abstract": [
        {
          "text": "A view that contains content that displays on a map at a specific position, and that responds to specific interactions you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapContentView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapContentView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapContentView"
        }
      ],
      "role": "symbol",
      "title": "MapContentView",
      "type": "topic",
      "url": "/documentation/mapkit/mapcontentview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapFeature": {
      "abstract": [
        {
          "text": "A tappable map feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapFeature"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapFeature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapFeature"
        }
      ],
      "role": "symbol",
      "title": "MapFeature",
      "type": "topic",
      "url": "/documentation/mapkit/mapfeature"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapItemDetailSelectionAccessoryStyle": {
      "abstract": [
        {
          "text": "The map item detail selection accessory style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapItemDetailSelectionAccessoryStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapItemDetailSelectionAccessoryStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapItemDetailSelectionAccessoryStyle"
        }
      ],
      "role": "symbol",
      "title": "MapItemDetailSelectionAccessoryStyle",
      "type": "topic",
      "url": "/documentation/mapkit/mapitemdetailselectionaccessorystyle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapItemDetailSelectionAccessoryStyle/callout(_:)": {
      "abstract": [
        {
          "text": "Presents the accessory as an annotation callout on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callout"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15_MapKit_SwiftUI0A33ItemDetailSelectionAccessoryStyleV",
          "text": "MapItemDetailSelectionAccessoryStyle"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15_MapKit_SwiftUI0A33ItemDetailSelectionAccessoryStyleV07CalloutI0V",
          "text": "CalloutStyle"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15_MapKit_SwiftUI0A33ItemDetailSelectionAccessoryStyleV",
          "text": "MapItemDetailSelectionAccessoryStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapItemDetailSelectionAccessoryStyle/callout(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "callout(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mapitemdetailselectionaccessorystyle/callout(_:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapLocationCompass": {
      "abstract": [
        {
          "text": "A view that displays a combined user location button and map compass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapLocationCompass"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapLocationCompass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapLocationCompass"
        }
      ],
      "role": "symbol",
      "title": "MapLocationCompass",
      "type": "topic",
      "url": "/documentation/mapkit/maplocationcompass"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapPitchSlider": {
      "abstract": [
        {
          "text": "A slider control that allows a person to change the pitch of the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapPitchSlider"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapPitchSlider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapPitchSlider"
        }
      ],
      "role": "symbol",
      "title": "MapPitchSlider",
      "type": "topic",
      "url": "/documentation/mapkit/mappitchslider"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapPitchToggle": {
      "abstract": [
        {
          "text": "A button that sets the pitch of the associated map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapPitchToggle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapPitchToggle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapPitchToggle"
        }
      ],
      "role": "symbol",
      "title": "MapPitchToggle",
      "type": "topic",
      "url": "/documentation/mapkit/mappitchtoggle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapPolygon": {
      "abstract": [
        {
          "text": "A closed polygon overlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapPolygon"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapPolygon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapPolygon"
        }
      ],
      "role": "symbol",
      "title": "MapPolygon",
      "type": "topic",
      "url": "/documentation/mapkit/mappolygon"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapPolyline": {
      "abstract": [
        {
          "text": "An open polygon overlay consisting of one or more connected line segments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapPolyline"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapPolyline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapPolyline"
        }
      ],
      "role": "symbol",
      "title": "MapPolyline",
      "type": "topic",
      "url": "/documentation/mapkit/mappolyline"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapProxy": {
      "abstract": [
        {
          "text": "A proxy for accessing sizing information about a given map view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapProxy"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapProxy"
        }
      ],
      "role": "symbol",
      "title": "MapProxy",
      "type": "topic",
      "url": "/documentation/mapkit/mapproxy"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapReader": {
      "abstract": [
        {
          "text": "A container view that defines its contents as a function of information about the first contained map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapReader"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapReader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapReader"
        }
      ],
      "role": "symbol",
      "title": "MapReader",
      "type": "topic",
      "url": "/documentation/mapkit/mapreader"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapScaleView": {
      "abstract": [
        {
          "text": "Displays a legend with distance information for the associated map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapScaleView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapScaleView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapScaleView"
        }
      ],
      "role": "symbol",
      "title": "MapScaleView",
      "type": "topic",
      "url": "/documentation/mapkit/mapscaleview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapSelectable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapSelectable"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapSelectable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapSelectable"
        }
      ],
      "role": "symbol",
      "title": "MapSelectable",
      "type": "topic",
      "url": "/documentation/mapkit/mapselectable"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapSelectableContentView": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapSelectableContentView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapSelectableContentView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapSelectableContentView"
        }
      ],
      "role": "symbol",
      "title": "MapSelectableContentView",
      "type": "topic",
      "url": "/documentation/mapkit/mapselectablecontentview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapSelection": {
      "abstract": [
        {
          "text": "A value representing a selected feature on a map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapSelection"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapSelection"
        }
      ],
      "role": "symbol",
      "title": "MapSelection",
      "type": "topic",
      "url": "/documentation/mapkit/mapselection"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapStyle": {
      "abstract": [
        {
          "text": "A style that you can apply to a map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapStyle"
        }
      ],
      "role": "symbol",
      "title": "MapStyle",
      "type": "topic",
      "url": "/documentation/mapkit/mapstyle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapUserLocationButton": {
      "abstract": [
        {
          "text": "A button that sets the framing of the associated map to the user location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapUserLocationButton"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapUserLocationButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapUserLocationButton"
        }
      ],
      "role": "symbol",
      "title": "MapUserLocationButton",
      "type": "topic",
      "url": "/documentation/mapkit/mapuserlocationbutton"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapZoomStepper": {
      "abstract": [
        {
          "text": "Buttons a person uses to adjust the zoom level of the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapZoomStepper"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapZoomStepper",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapZoomStepper"
        }
      ],
      "role": "symbol",
      "title": "MapZoomStepper",
      "type": "topic",
      "url": "/documentation/mapkit/mapzoomstepper"
    },
    "doc://com.apple.mapkit/documentation/MapKit/Marker": {
      "abstract": [
        {
          "text": "A balloon-shaped annotation that marks a map location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Marker"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/Marker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Marker"
        }
      ],
      "role": "symbol",
      "title": "Marker",
      "type": "topic",
      "url": "/documentation/mapkit/marker"
    },
    "doc://com.apple.mapkit/documentation/MapKit/PointOfInterestCategories": {
      "abstract": [
        {
          "text": "A structure you use to define points of interest to include or exclude on a map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PointOfInterestCategories"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/PointOfInterestCategories",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PointOfInterestCategories"
        }
      ],
      "role": "symbol",
      "title": "PointOfInterestCategories",
      "type": "topic",
      "url": "/documentation/mapkit/pointofinterestcategories"
    },
    "doc://com.apple.mapkit/documentation/MapKit/TupleMapContent": {
      "abstract": [
        {
          "text": "A view created from a Swift tuple of map content values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TupleMapContent"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/TupleMapContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TupleMapContent"
        }
      ],
      "role": "symbol",
      "title": "TupleMapContent",
      "type": "topic",
      "url": "/documentation/mapkit/tuplemapcontent"
    },
    "doc://com.apple.mapkit/documentation/MapKit/Unified-Map-URLs": {
      "abstract": [
        {
          "text": "Access Maps URLs and options for displaying Maps information across Apple platforms.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/Unified-Map-URLs",
      "kind": "article",
      "role": "article",
      "title": "Adopting unified Maps URLs",
      "type": "topic",
      "url": "/documentation/mapkit/unified-map-urls"
    },
    "doc://com.apple.mapkit/documentation/MapKit/UserAnnotation": {
      "abstract": [
        {
          "text": "Displays the person’s current location on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UserAnnotation"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/UserAnnotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UserAnnotation"
        }
      ],
      "role": "symbol",
      "title": "UserAnnotation",
      "type": "topic",
      "url": "/documentation/mapkit/userannotation"
    },
    "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit": {
      "abstract": [],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MapKit for AppKit and UIKit",
      "type": "topic",
      "url": "/documentation/mapkit/mapkit-for-appkit-and-uikit"
    },
    "https://developer.apple.com/videos/play/wwdc2023/10043/": {
      "identifier": "https://developer.apple.com/videos/play/wwdc2023/10043/",
      "title": "Meet MapKit for SwiftUI",
      "titleInlineContent": [
        {
          "text": "Meet MapKit for SwiftUI",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc2023/10043/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "The-MapKit-APIs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit",
        "doc://com.apple.mapkit/documentation/MapKit/Unified-Map-URLs"
      ],
      "title": "The MapKit APIs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/Map",
        "doc://com.apple.mapkit/documentation/MapKit/MapStyle"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Annotations-and-overlays",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/Annotation",
        "doc://com.apple.mapkit/documentation/MapKit/MapCircle",
        "doc://com.apple.mapkit/documentation/MapKit/MapPolygon",
        "doc://com.apple.mapkit/documentation/MapKit/MapPolyline",
        "doc://com.apple.mapkit/documentation/MapKit/Marker",
        "doc://com.apple.mapkit/documentation/MapKit/UserAnnotation"
      ],
      "title": "Annotations and overlays"
    },
    {
      "anchor": "Map-controls",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MapCompass",
        "doc://com.apple.mapkit/documentation/MapKit/MapLocationCompass",
        "doc://com.apple.mapkit/documentation/MapKit/MapPitchSlider",
        "doc://com.apple.mapkit/documentation/MapKit/MapPitchToggle",
        "doc://com.apple.mapkit/documentation/MapKit/MapScaleView",
        "doc://com.apple.mapkit/documentation/MapKit/MapUserLocationButton",
        "doc://com.apple.mapkit/documentation/MapKit/MapZoomStepper"
      ],
      "title": "Map controls"
    },
    {
      "anchor": "Exploring-at-street-level",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/LookAroundPreview"
      ],
      "title": "Exploring at street level"
    },
    {
      "anchor": "Map-features",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MapFeature",
        "doc://com.apple.mapkit/documentation/MapKit/MapSelection",
        "doc://com.apple.mapkit/documentation/MapKit/MapSelectable"
      ],
      "title": "Map features"
    },
    {
      "anchor": "Map-customization",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MapCamera",
        "doc://com.apple.mapkit/documentation/MapKit/MapCameraBounds",
        "doc://com.apple.mapkit/documentation/MapKit/MapCameraPosition",
        "doc://com.apple.mapkit/documentation/MapKit/MapCameraUpdateContext",
        "doc://com.apple.mapkit/documentation/MapKit/MapCameraUpdateFrequency"
      ],
      "title": "Map customization"
    },
    {
      "anchor": "Place-information",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MapItemDetailSelectionAccessoryStyle",
        "doc://com.apple.mapkit/documentation/MapKit/MapContent/mapItemDetailSelectionAccessory(_:)",
        "doc://com.apple.mapkit/documentation/MapKit/MapItemDetailSelectionAccessoryStyle/callout(_:)"
      ],
      "title": "Place information"
    },
    {
      "anchor": "Points-of-interest",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/PointOfInterestCategories"
      ],
      "title": "Points of interest"
    },
    {
      "anchor": "Protocols",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/DynamicMapContent",
        "doc://com.apple.mapkit/documentation/MapKit/MapContent",
        "doc://com.apple.mapkit/documentation/MapKit/MapContentBuilder",
        "doc://com.apple.mapkit/documentation/MapKit/MapContentView"
      ],
      "title": "Protocols"
    },
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/DefaultUserAnnotationContent",
        "doc://com.apple.mapkit/documentation/MapKit/EmptyMapContent",
        "doc://com.apple.mapkit/documentation/MapKit/MapProxy",
        "doc://com.apple.mapkit/documentation/MapKit/MapReader",
        "doc://com.apple.mapkit/documentation/MapKit/TupleMapContent",
        "doc://com.apple.mapkit/documentation/MapKit/MapSelectableContentView"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "The-MapKit-APIs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit",
                "doc://com.apple.mapkit/documentation/MapKit/Unified-Map-URLs"
              ],
              "title": "The MapKit APIs"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mapkit-for-swiftui"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mapkit-for-swiftui"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
