{
  "abstract": [
    {
      "text": "MapKit classes, protocols, and entitlements that are no longer supported.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/mapkit_for_appkit_and_uikit-deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated Symbols"
  },
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.maps": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may provide directions beyond what Maps supports, such as subway routes, hiking trails, and bike paths.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.maps",
      "kind": "symbol",
      "role": "symbol",
      "title": "Maps Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.maps"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKCircle": {
      "abstract": [
        {
          "text": "A circular overlay with a configurable radius that you center on a geographic coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKCircle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCircle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKCircle"
        }
      ],
      "role": "symbol",
      "title": "MKCircle",
      "type": "topic",
      "url": "/documentation/mapkit/mkcircle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKCircleView": {
      "abstract": [
        {
          "text": "Provides the visual representation for an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCircle",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " annotation object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKCircleView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCircleView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKCircleView"
        }
      ],
      "role": "symbol",
      "title": "MKCircleView",
      "type": "topic",
      "url": "/documentation/mapkit/mkcircleview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum": {
      "abstract": [
        {
          "text": "Constants indicating the types of search completions to return.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FilterType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FilterType"
        }
      ],
      "role": "symbol",
      "title": "MKLocalSearchCompleter.FilterType",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompleter/filtertype-swift.enum"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/filterType-swift.property": {
      "abstract": [
        {
          "text": "The filter options for the search results.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filterType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKLocalSearchCompleter",
          "text": "MKLocalSearchCompleter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKSearchCompletionFilterType",
          "text": "FilterType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/filterType-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "filterType"
        }
      ],
      "role": "symbol",
      "title": "filterType",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompleter/filtertype-swift.property"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/mapType": {
      "abstract": [
        {
          "text": "The map’s visual style.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKMapType",
          "text": "MKMapType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/mapType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapType"
        }
      ],
      "role": "symbol",
      "title": "mapType",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter/options/maptype"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/showsPointsOfInterest": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the map displays point-of-interest information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsPointsOfInterest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/showsPointsOfInterest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showsPointsOfInterest"
        }
      ],
      "role": "symbol",
      "title": "showsPointsOfInterest",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsnapshotter/options/showspointsofinterest"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapType": {
      "abstract": [
        {
          "text": "The type of map to display.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapType"
        }
      ],
      "role": "symbol",
      "title": "MKMapType",
      "type": "topic",
      "url": "/documentation/mapkit/mkmaptype"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapView/showsPointsOfInterest": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the map displays point-of-interest information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsPointsOfInterest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapView/showsPointsOfInterest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showsPointsOfInterest"
        }
      ],
      "role": "symbol",
      "title": "showsPointsOfInterest",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapview/showspointsofinterest"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapView/view(for:)-38z60": {
      "abstract": [
        {
          "text": "Returns the view associated with the overlay object, if any.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "view"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MKOverlay",
          "text": "MKOverlay"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKOverlayView",
          "text": "MKOverlayView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapView/view(for:)-38z60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewForOverlay:"
        }
      ],
      "role": "symbol",
      "title": "view(for:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapview/view(for:)-38z60"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapViewDelegate/mapView(_:didAddOverlayViews:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the map adds one or more overlay views to the map.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapView",
          "text": "MKMapView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didAddOverlayViews"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapViewDelegate/mapView(_:didAddOverlayViews:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapView:didAddOverlayViews:"
        }
      ],
      "role": "symbol",
      "title": "mapView(_:didAddOverlayViews:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapviewdelegate/mapview(_:didaddoverlayviews:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapViewDelegate/mapView(_:viewFor:)-6j267": {
      "abstract": [
        {
          "text": "Asks the delegate for the overlay view to use when displaying the specified overlay object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapView",
          "text": "MKMapView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "viewFor"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MKOverlay",
          "text": "MKOverlay"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKOverlayView",
          "text": "MKOverlayView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapViewDelegate/mapView(_:viewFor:)-6j267",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapView:viewForOverlay:"
        }
      ],
      "role": "symbol",
      "title": "mapView(_:viewFor:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapviewdelegate/mapview(_:viewfor:)-6j267"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathView": {
      "abstract": [
        {
          "text": "Represents a generic overlay that draws its contents using a Core Graphics path data type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKOverlayPathView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKOverlayPathView"
        }
      ],
      "role": "symbol",
      "title": "MKOverlayPathView",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlaypathview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView": {
      "abstract": [
        {
          "text": "Defines the basic behavior associated with all overlay views.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKOverlayView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKOverlayView"
        }
      ],
      "role": "symbol",
      "title": "MKOverlayView",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlayview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPinAnnotationColor": {
      "abstract": [
        {
          "text": "The supported colors for pin annotations.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPinAnnotationColor"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPinAnnotationColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPinAnnotationColor"
        }
      ],
      "role": "symbol",
      "title": "MKPinAnnotationColor",
      "type": "topic",
      "url": "/documentation/mapkit/mkpinannotationcolor"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPinAnnotationView": {
      "abstract": [
        {
          "text": "An annotation view that displays a pin image on the map.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPinAnnotationView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPinAnnotationView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPinAnnotationView"
        }
      ],
      "role": "symbol",
      "title": "MKPinAnnotationView",
      "type": "topic",
      "url": "/documentation/mapkit/mkpinannotationview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPinAnnotationView/pinColor": {
      "abstract": [
        {
          "text": "The color of the pin head.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pinColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKPinAnnotationColor",
          "text": "MKPinAnnotationColor"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPinAnnotationView/pinColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pinColor"
        }
      ],
      "role": "symbol",
      "title": "pinColor",
      "type": "topic",
      "url": "/documentation/mapkit/mkpinannotationview/pincolor"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPolygon": {
      "abstract": [
        {
          "text": "A closed polygon overlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPolygon"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolygon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPolygon"
        }
      ],
      "role": "symbol",
      "title": "MKPolygon",
      "type": "topic",
      "url": "/documentation/mapkit/mkpolygon"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPolygonView": {
      "abstract": [
        {
          "text": "Provides the visual representation for an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolygon",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " annotation object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPolygonView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolygonView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPolygonView"
        }
      ],
      "role": "symbol",
      "title": "MKPolygonView",
      "type": "topic",
      "url": "/documentation/mapkit/mkpolygonview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPolyline": {
      "abstract": [
        {
          "text": "An open polygon overlay consisting of one or more connected line segments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPolyline"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolyline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPolyline"
        }
      ],
      "role": "symbol",
      "title": "MKPolyline",
      "type": "topic",
      "url": "/documentation/mapkit/mkpolyline"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPolylineView": {
      "abstract": [
        {
          "text": "Provides the visual representation for an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolyline",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " annotation object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPolylineView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolylineView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPolylineView"
        }
      ],
      "role": "symbol",
      "title": "MKPolylineView",
      "type": "topic",
      "url": "/documentation/mapkit/mkpolylineview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKReverseGeocoder": {
      "abstract": [
        {
          "text": "Provides services for converting a map coordinate (specified as a latitude/longitude pair) into information about that coordinate, such as the country or region, city, or street.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MKReverseGeocoder"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKReverseGeocoder",
      "kind": "symbol",
      "role": "symbol",
      "title": "MKReverseGeocoder",
      "type": "topic",
      "url": "/documentation/mapkit/mkreversegeocoder"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKReverseGeocoderDelegate": {
      "abstract": [
        {
          "text": "Defines the interface for receiving messages from an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKReverseGeocoder",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MKReverseGeocoderDelegate"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKReverseGeocoderDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "MKReverseGeocoderDelegate",
      "type": "topic",
      "url": "/documentation/mapkit/mkreversegeocoderdelegate"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MapPin": {
      "abstract": [
        {
          "text": "A pin-shaped annotation used to indicate a location on a map.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapPin"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MapPin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapPin"
        }
      ],
      "role": "symbol",
      "title": "MapPin",
      "type": "topic",
      "url": "/documentation/mapkit/mappin"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Classes",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKCircleView",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathView",
        "doc://com.apple.mapkit/documentation/MapKit/MKPolygonView",
        "doc://com.apple.mapkit/documentation/MapKit/MKPolylineView",
        "doc://com.apple.mapkit/documentation/MapKit/MKPinAnnotationView"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Properties",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/filterType-swift.property",
        "doc://com.apple.mapkit/documentation/MapKit/MKPinAnnotationView/pinColor",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapView/showsPointsOfInterest",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/showsPointsOfInterest",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/mapType"
      ],
      "title": "Properties"
    },
    {
      "anchor": "Methods",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapView/view(for:)-38z60",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapViewDelegate/mapView(_:didAddOverlayViews:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapViewDelegate/mapView(_:viewFor:)-6j267"
      ],
      "title": "Methods"
    },
    {
      "anchor": "Protocols",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MapPin"
      ],
      "title": "Protocols"
    },
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapType",
        "doc://com.apple.mapkit/documentation/MapKit/MKPinAnnotationColor"
      ],
      "title": "Enumerations"
    },
    {
      "anchor": "Entitlements",
      "identifiers": [
        "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.maps"
      ],
      "title": "Entitlements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Classes",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKCircleView",
                "doc://com.apple.mapkit/documentation/MapKit/MKOverlayView",
                "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathView",
                "doc://com.apple.mapkit/documentation/MapKit/MKPolygonView",
                "doc://com.apple.mapkit/documentation/MapKit/MKPolylineView",
                "doc://com.apple.mapkit/documentation/MapKit/MKPinAnnotationView",
                "doc://com.apple.mapkit/documentation/MapKit/MKReverseGeocoder"
              ],
              "title": "Classes"
            },
            {
              "anchor": "Properties",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/filterType-swift.property",
                "doc://com.apple.mapkit/documentation/MapKit/MKPinAnnotationView/pinColor",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapView/showsPointsOfInterest",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/showsPointsOfInterest",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Options/mapType"
              ],
              "title": "Properties"
            },
            {
              "anchor": "Methods",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapView/view(for:)-38z60",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapViewDelegate/mapView(_:didAddOverlayViews:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapViewDelegate/mapView(_:viewFor:)-6j267"
              ],
              "title": "Methods"
            },
            {
              "anchor": "Protocols",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKReverseGeocoderDelegate"
              ],
              "title": "Protocols"
            },
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/FilterType-swift.enum",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapType",
                "doc://com.apple.mapkit/documentation/MapKit/MKPinAnnotationColor"
              ],
              "title": "Enumerations"
            },
            {
              "anchor": "Entitlements",
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.maps"
              ],
              "title": "Entitlements"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathView/title",
          "value": "MKOverlayPathView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayPathView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayPathView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView~1showsPointsOfInterest/title",
          "value": "showsPointsOfInterest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView~1showsPointsOfInterest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showsPointsOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPinAnnotationView~1pinColor/title",
          "value": "pinColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPinAnnotationView~1pinColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pinColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPinAnnotationView/title",
          "value": "MKPinAnnotationView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPinAnnotationView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPinAnnotationView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPinAnnotationView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPinAnnotationView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView~1view(for:)-38z60/title",
          "value": "viewForOverlay:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView~1view(for:)-38z60/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewForOverlay:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1FilterType-swift.enum/title",
          "value": "MKSearchCompletionFilterType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1FilterType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKSearchCompletionFilterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1FilterType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKSearchCompletionFilterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolygonView/title",
          "value": "MKPolygonView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolygonView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolygonView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolygonView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolygonView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCircleView/title",
          "value": "MKCircleView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCircleView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCircleView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCircleView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCircleView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayView/title",
          "value": "MKOverlayView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapViewDelegate~1mapView(_:viewFor:)-6j267/title",
          "value": "mapView:viewForOverlay:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapViewDelegate~1mapView(_:viewFor:)-6j267/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapView:viewForOverlay:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType/title",
          "value": "MKMapType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPinAnnotationColor/title",
          "value": "MKPinAnnotationColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPinAnnotationColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPinAnnotationColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPinAnnotationColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPinAnnotationColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCircle/title",
          "value": "MKCircle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCircle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCircle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCircle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCircle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolygon/title",
          "value": "MKPolygon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolygon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolygon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolygon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolygon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1filterType-swift.property/title",
          "value": "filterType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1filterType-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "filterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1mapType/title",
          "value": "mapType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1mapType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mapType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolyline/title",
          "value": "MKPolyline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolyline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolyline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolyline/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolyline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1showsPointsOfInterest/title",
          "value": "showsPointsOfInterest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Options~1showsPointsOfInterest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showsPointsOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapViewDelegate~1mapView(_:didAddOverlayViews:)/title",
          "value": "mapView:didAddOverlayViews:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapViewDelegate~1mapView(_:didAddOverlayViews:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapView:didAddOverlayViews:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineView/title",
          "value": "MKPolylineView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolylineView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolylineView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mapkit_for_appkit_and_uikit-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mapkit_for_appkit_and_uikit-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
