{
  "abstract": [
    {
      "text": "Creates a new ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpan",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " from the specified values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpanMake"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@MKCoordinateSpanMake",
    "fragments": [
      {
        "kind": "identifier",
        "text": "MKCoordinateSpanMake"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MKCoordinateSpanMake"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "MKCoordinateSpanMake"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpan",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@MKCoordinateSpan",
              "text": "MKCoordinateSpan"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MKCoordinateSpanMake"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CLLocationDegrees",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CLLocationDegrees",
              "text": "CLLocationDegrees"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "latitudeDelta"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CLLocationDegrees",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CLLocationDegrees",
              "text": "CLLocationDegrees"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "longitudeDelta"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The amount of north-to-south distance (measured in degrees) to use for the span. Unlike longitudinal distances, which vary based on the latitude, one degree of latitude is approximately 111 kilometers (69 miles) at all times.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "latitudeDelta"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The amount of east-to-west distance (measured in degrees) to use for the span. The number of kilometers spanned by a longitude range varies based on the current latitude. For example, one degree of longitude spans a distance of approximately 111 kilometers (69 miles) at the equator but shrinks to 0 kilometers at the poles.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "longitudeDelta"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A span with the specified delta values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion/init(center:latitudinalMeters:longitudinalMeters:)": {
      "abstract": [
        {
          "text": "Creates a new coordinate region from the specified coordinate and distance values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "center"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CLLocationCoordinate2D",
          "text": "CLLocationCoordinate2D"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "latitudinalMeters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDistance",
          "text": "CLLocationDistance"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "longitudinalMeters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDistance",
          "text": "CLLocationDistance"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion/init(center:latitudinalMeters:longitudinalMeters:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKCoordinateRegionMakeWithDistance"
        }
      ],
      "role": "symbol",
      "title": "init(center:latitudinalMeters:longitudinalMeters:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkcoordinateregion/init(center:latitudinalmeters:longitudinalmeters:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegionMake": {
      "abstract": [
        {
          "text": "Creates a new coordinate region from the specified coordinate and span values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MKCoordinateRegionMake"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegionMake",
      "kind": "symbol",
      "role": "symbol",
      "title": "MKCoordinateRegionMake",
      "type": "topic",
      "url": "/documentation/mapkit/mkcoordinateregionmake"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpan": {
      "abstract": [
        {
          "text": "The width and height of a map region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKCoordinateSpan"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKCoordinateSpan"
        }
      ],
      "role": "symbol",
      "title": "MKCoordinateSpan",
      "type": "topic",
      "url": "/documentation/mapkit/mkcoordinatespan"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpanMake": {
      "abstract": [
        {
          "text": "Creates a new ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpan",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " from the specified values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MKCoordinateSpanMake"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpanMake",
      "kind": "symbol",
      "role": "symbol",
      "title": "MKCoordinateSpanMake",
      "type": "topic",
      "url": "/documentation/mapkit/mkcoordinatespanmake"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/init(_:)": {
      "abstract": [
        {
          "text": "Creates the map point data structure that corresponds to the specified coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CLLocationCoordinate2D",
          "text": "CLLocationCoordinate2D"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/init(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapPointForCoordinate"
        }
      ],
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmappoint/init(_:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapPointMake": {
      "abstract": [
        {
          "text": "Creates a new map point structure from the specified values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MKMapPointMake"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapPointMake",
      "kind": "symbol",
      "role": "symbol",
      "title": "MKMapPointMake",
      "type": "topic",
      "url": "/documentation/mapkit/mkmappointmake"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSizeMake": {
      "abstract": [
        {
          "text": "Creates a new map size structure from the specified values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MKMapSizeMake"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSizeMake",
      "kind": "symbol",
      "role": "symbol",
      "title": "MKMapSizeMake",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsizemake"
    },
    "doc://com.externally.resolved.symbol/c:@T@CLLocationDegrees": {
      "abstract": [
        {
          "text": "A latitude or longitude value specified in degrees.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationDegrees"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CLLocationDegrees",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLLocationDegrees",
      "type": "topic",
      "url": "/documentation/CoreLocation/CLLocationDegrees"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegionMake",
        "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion/init(center:latitudinalMeters:longitudinalMeters:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/init(_:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapPointMake",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSizeMake"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateRegion~1init(center:latitudinalMeters:longitudinalMeters:)/title",
          "value": "MKCoordinateRegionMakeWithDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateRegion~1init(center:latitudinalMeters:longitudinalMeters:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCoordinateRegionMakeWithDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateSpan/title",
          "value": "MKCoordinateSpan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateSpan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCoordinateSpan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateSpan/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCoordinateSpan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CLLocationDegrees/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:d",
              "text": "double"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLLocationDegrees"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint~1init(_:)/title",
          "value": "MKMapPointForCoordinate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint~1init(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapPointForCoordinate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkcoordinatespanmake"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
