{
  "abstract": [
    {
      "text": "A class you use to customize the annotation view icon of a point of interest (POI) on the map.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKIconStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MKIconStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MKIconStyle"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MKIconStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MKIconStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MKIconStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKIconStyle": {
      "abstract": [
        {
          "text": "A class you use to customize the annotation view icon of a point of interest (POI) on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKIconStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKIconStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKIconStyle"
        }
      ],
      "role": "symbol",
      "title": "MKIconStyle",
      "type": "topic",
      "url": "/documentation/mapkit/mkiconstyle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKIconStyle/backgroundColor": {
      "abstract": [
        {
          "text": "The background color of the icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKIconStyle/backgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundColor"
        }
      ],
      "role": "symbol",
      "title": "backgroundColor",
      "type": "topic",
      "url": "/documentation/mapkit/mkiconstyle/backgroundcolor"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKIconStyle/image": {
      "abstract": [
        {
          "text": "The icon image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKIconStyle/image",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/mapkit/mkiconstyle/image"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation": {
      "abstract": [
        {
          "text": "A class that describes an annotation element on the map’s display such as a point of interest, territorial boundary, or physical feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapFeatureAnnotation"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapFeatureAnnotation"
        }
      ],
      "role": "symbol",
      "title": "MKMapFeatureAnnotation",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureOptions": {
      "abstract": [
        {
          "text": "A structure you use to tell the map which kinds of features users can interact with.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapFeatureOptions"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapFeatureOptions"
        }
      ],
      "role": "symbol",
      "title": "MKMapFeatureOptions",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureoptions"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItemRequest": {
      "abstract": [
        {
          "text": "A utility class you use to request additional information about a map feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapItemRequest"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItemRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapItemRequest"
        }
      ],
      "role": "symbol",
      "title": "MKMapItemRequest",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitemrequest"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory": {
      "abstract": [
        {
          "text": "A point of interest category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPointOfInterestCategory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPointOfInterestCategory"
        }
      ],
      "role": "symbol",
      "title": "MKPointOfInterestCategory",
      "type": "topic",
      "url": "/documentation/mapkit/mkpointofinterestcategory"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestFilter": {
      "abstract": [
        {
          "text": "A filter that includes or excludes point of interest categories from a map view, local search, or local search completer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPointOfInterestFilter"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPointOfInterestFilter"
        }
      ],
      "role": "symbol",
      "title": "MKPointOfInterestFilter",
      "type": "topic",
      "url": "/documentation/mapkit/mkpointofinterestfilter"
    },
    "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids": {
      "abstract": [
        {
          "text": "Obtain information about a point of interest that persists over its lifetime.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids",
      "kind": "article",
      "role": "article",
      "title": "Identifying unique locations with Place IDs",
      "type": "topic",
      "url": "/documentation/mapkit/identifying-unique-locations-with-place-ids"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Points-of-interest",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureOptions",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItemRequest",
        "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestFilter",
        "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory"
      ],
      "title": "Points of interest"
    }
  ],
  "topicSections": [
    {
      "anchor": "Customizing-the-icon-view",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKIconStyle/backgroundColor",
        "doc://com.apple.mapkit/documentation/MapKit/MKIconStyle/image"
      ],
      "title": "Customizing the icon view"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKIconStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKIconStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKIconStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Customizing-the-icon-view",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKIconStyle/backgroundColor",
                "doc://com.apple.mapkit/documentation/MapKit/MKIconStyle/image"
              ],
              "title": "Customizing the icon view"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Points-of-interest",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureOptions",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItemRequest",
                "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestFilter",
                "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory"
              ],
              "title": "Points of interest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MKIconStyle"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKIconStyle/title",
          "value": "MKIconStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKIconStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKIconStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKIconStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKIconStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemRequest/title",
          "value": "MKMapItemRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKIconStyle~1image/title",
          "value": "image"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKIconStyle~1image/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "image"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestFilter/title",
          "value": "MKPointOfInterestFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation/title",
          "value": "MKMapFeatureAnnotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory/title",
          "value": "MKPointOfInterestCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKIconStyle~1backgroundColor/title",
          "value": "backgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKIconStyle~1backgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureOptions/title",
          "value": "MKMapFeatureOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkiconstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkiconstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
