{
  "abstract": [
    {
      "text": "Driving directions between the specified start and end points.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDriving"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@MKLaunchOptionsDirectionsModeDriving",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MKLaunchOptionsDirectionsModeDriving"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MKLaunchOptionsDirectionsModeDriving"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "MKLaunchOptionsDirectionsModeDriving"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsDirectionsModeDriving"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsCameraKey": {
      "abstract": [
        {
          "text": "The virtual camera to use for viewing the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsCameraKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsCameraKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsCameraKey"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsCameraKey",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionscamerakey"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDefault": {
      "abstract": [
        {
          "text": "Directions that match the user’s preferred transportation type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeDefault"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsDirectionsModeDefault",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsdirectionsmodedefault"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDriving": {
      "abstract": [
        {
          "text": "Driving directions between the specified start and end points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeDriving"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDriving",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeDriving"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsDirectionsModeDriving",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsdirectionsmodedriving"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeKey": {
      "abstract": [
        {
          "text": "The mode of transportation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeKey"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsDirectionsModeKey",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsdirectionsmodekey"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeTransit": {
      "abstract": [
        {
          "text": "Public transit directions between the specified start and end points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeTransit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeTransit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeTransit"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsDirectionsModeTransit",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsdirectionsmodetransit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeWalking": {
      "abstract": [
        {
          "text": "Walking directions between the specified start and end points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeWalking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeWalking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsDirectionsModeWalking"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsDirectionsModeWalking",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsdirectionsmodewalking"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapCenterKey": {
      "abstract": [
        {
          "text": "The coordinate value on which to center the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsMapCenterKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapCenterKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsMapCenterKey"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsMapCenterKey",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsmapcenterkey"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapSpanKey": {
      "abstract": [
        {
          "text": "The amount of the map to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsMapSpanKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapSpanKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsMapSpanKey"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsMapSpanKey",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsmapspankey"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapTypeKey": {
      "abstract": [
        {
          "text": "The type of map (standard, satellite, or hybrid) to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsMapTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsMapTypeKey"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsMapTypeKey",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsmaptypekey"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsShowsTrafficKey": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to display traffic information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsShowsTrafficKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsShowsTrafficKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLaunchOptionsShowsTrafficKey"
        }
      ],
      "role": "symbol",
      "title": "MKLaunchOptionsShowsTrafficKey",
      "type": "topic",
      "url": "/documentation/mapkit/mklaunchoptionsshowstraffickey"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Launch-options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsCameraKey",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDefault",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeKey",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeTransit",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeWalking",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapCenterKey",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapSpanKey",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapTypeKey",
        "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsShowsTrafficKey"
      ],
      "title": "Launch options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKLaunchOptionsDirectionsModeDriving"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsDirectionsModeDriving"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Launch-options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsCameraKey",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeDefault",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeKey",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeTransit",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsDirectionsModeWalking",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapCenterKey",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapSpanKey",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsMapTypeKey",
                "doc://com.apple.mapkit/documentation/MapKit/MKLaunchOptionsShowsTrafficKey"
              ],
              "title": "Launch options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MKLaunchOptionsDirectionsModeDriving"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeDefault/title",
          "value": "MKLaunchOptionsDirectionsModeDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsDirectionsModeDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeDriving/title",
          "value": "MKLaunchOptionsDirectionsModeDriving"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeDriving/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsDirectionsModeDriving"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsCameraKey/title",
          "value": "MKLaunchOptionsCameraKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsCameraKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsCameraKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsMapCenterKey/title",
          "value": "MKLaunchOptionsMapCenterKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsMapCenterKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsMapCenterKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsMapSpanKey/title",
          "value": "MKLaunchOptionsMapSpanKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsMapSpanKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsMapSpanKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeTransit/title",
          "value": "MKLaunchOptionsDirectionsModeTransit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeTransit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsDirectionsModeTransit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsShowsTrafficKey/title",
          "value": "MKLaunchOptionsShowsTrafficKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsShowsTrafficKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsShowsTrafficKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeKey/title",
          "value": "MKLaunchOptionsDirectionsModeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsDirectionsModeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeWalking/title",
          "value": "MKLaunchOptionsDirectionsModeWalking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsDirectionsModeWalking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsDirectionsModeWalking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsMapTypeKey/title",
          "value": "MKLaunchOptionsMapTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLaunchOptionsMapTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLaunchOptionsMapTypeKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mklaunchoptionsdirectionsmodedriving"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mklaunchoptionsdirectionsmodedriving"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
