{
  "abstract": [
    {
      "text": "A class you use to request a LookAround scene at the location you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MKLookAroundSceneRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MKLookAroundSceneRequest"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MKLookAroundSceneRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MKLookAroundSceneRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MKLookAroundSceneRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundScene": {
      "abstract": [
        {
          "text": "A utility class that encapsulates information the framework requires to retrieve and display a specific Look Around location’s imagery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLookAroundScene"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLookAroundScene"
        }
      ],
      "role": "symbol",
      "title": "MKLookAroundScene",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundscene"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest": {
      "abstract": [
        {
          "text": "A class you use to request a LookAround scene at the location you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLookAroundSceneRequest"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLookAroundSceneRequest"
        }
      ],
      "role": "symbol",
      "title": "MKLookAroundSceneRequest",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundscenerequest"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/cancel()": {
      "abstract": [
        {
          "text": "Cancels the pending scene request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancel"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/cancel()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancel"
        }
      ],
      "role": "symbol",
      "title": "cancel()",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundscenerequest/cancel()"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/coordinate": {
      "abstract": [
        {
          "text": "A coordinate value that describes the location of the LookAround scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coordinate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CLLocationCoordinate2D",
          "text": "CLLocationCoordinate2D"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/coordinate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "coordinate"
        }
      ],
      "role": "symbol",
      "title": "coordinate",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundscenerequest/coordinate"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/getSceneWithCompletionHandler(_:)": {
      "abstract": [
        {
          "text": "Requests a LookAround scene and calls the specified completion handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getSceneWithCompletionHandler"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKLookAroundScene",
          "text": "MKLookAroundScene"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/getSceneWithCompletionHandler(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getSceneWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "getSceneWithCompletionHandler(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundscenerequest/getscenewithcompletionhandler(_:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/init(coordinate:)": {
      "abstract": [
        {
          "text": "Creates a LookAround scene at the specified coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "coordinate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CLLocationCoordinate2D",
          "text": "CLLocationCoordinate2D"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/init(coordinate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoordinate:"
        }
      ],
      "role": "symbol",
      "title": "init(coordinate:)",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundscenerequest/init(coordinate:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/init(mapItem:)": {
      "abstract": [
        {
          "text": "Creates a LookAround scene with the location described by the specified map item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "mapItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItem",
          "text": "MKMapItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/init(mapItem:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithMapItem:"
        }
      ],
      "role": "symbol",
      "title": "init(mapItem:)",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundscenerequest/init(mapitem:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/isCancelled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates if the cancellation of a scene request was successful.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isCancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/isCancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "role": "symbol",
      "title": "isCancelled",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundscenerequest/iscancelled"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/isLoading": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a scene request is loading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isLoading"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/isLoading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loading"
        }
      ],
      "role": "symbol",
      "title": "isLoading",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundscenerequest/isloading"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/mapItem": {
      "abstract": [
        {
          "text": "A map item that describes the location of the LookAround scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItem",
          "text": "MKMapItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/mapItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapItem"
        }
      ],
      "role": "symbol",
      "title": "mapItem",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundscenerequest/mapitem"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSnapshotter": {
      "abstract": [
        {
          "text": "A utility class that you use to create a static image from a LookAround scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLookAroundSnapshotter"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSnapshotter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLookAroundSnapshotter"
        }
      ],
      "role": "symbol",
      "title": "MKLookAroundSnapshotter",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundsnapshotter"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewController": {
      "abstract": [
        {
          "text": "A class that manages the presentation and display of a LookAround view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLookAroundViewController"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLookAroundViewController"
        }
      ],
      "role": "symbol",
      "title": "MKLookAroundViewController",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundviewcontroller"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Exploring-at-street-level",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundScene",
        "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewController",
        "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSnapshotter"
      ],
      "title": "Exploring at street level"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-LookAround-scene",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/init(coordinate:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/init(mapItem:)"
      ],
      "title": "Creating a LookAround scene"
    },
    {
      "anchor": "Specifying-the-requests-location",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/coordinate",
        "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/mapItem"
      ],
      "title": "Specifying the request’s location"
    },
    {
      "anchor": "Starting-and-stopping-scene-requests",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/cancel()",
        "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/getSceneWithCompletionHandler(_:)"
      ],
      "title": "Starting and stopping scene requests"
    },
    {
      "anchor": "Monitoring-the-progress-of-scene-requests",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/isCancelled",
        "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/isLoading"
      ],
      "title": "Monitoring the progress of scene requests"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKLookAroundSceneRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLookAroundSceneRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLookAroundSceneRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-LookAround-scene",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/init(coordinate:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/init(mapItem:)"
              ],
              "title": "Creating a LookAround scene"
            },
            {
              "anchor": "Specifying-the-requests-location",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/coordinate",
                "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/mapItem"
              ],
              "title": "Specifying the request’s location"
            },
            {
              "anchor": "Starting-and-stopping-scene-requests",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/cancel()",
                "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/getSceneWithCompletionHandler(_:)"
              ],
              "title": "Starting and stopping scene requests"
            },
            {
              "anchor": "Monitoring-the-progress-of-scene-requests",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/isCancelled",
                "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest/isLoading"
              ],
              "title": "Monitoring the progress of scene requests"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Exploring-at-street-level",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundScene",
                "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewController",
                "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSnapshotter"
              ],
              "title": "Exploring at street level"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MKLookAroundSceneRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundScene/title",
          "value": "MKLookAroundScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLookAroundScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLookAroundScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest/title",
          "value": "MKLookAroundSceneRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLookAroundSceneRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLookAroundSceneRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest~1isLoading/title",
          "value": "loading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest~1isLoading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "loading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewController/title",
          "value": "MKLookAroundViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLookAroundViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLookAroundViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest~1coordinate/title",
          "value": "coordinate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest~1coordinate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "coordinate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest~1init(mapItem:)/title",
          "value": "initWithMapItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest~1init(mapItem:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithMapItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSnapshotter/title",
          "value": "MKLookAroundSnapshotter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSnapshotter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLookAroundSnapshotter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSnapshotter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLookAroundSnapshotter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest~1init(coordinate:)/title",
          "value": "initWithCoordinate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest~1init(coordinate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoordinate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest~1cancel()/title",
          "value": "cancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest~1cancel()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest~1mapItem/title",
          "value": "mapItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest~1mapItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mapItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest~1isCancelled/title",
          "value": "cancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest~1isCancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest~1getSceneWithCompletionHandler(_:)/title",
          "value": "getSceneWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest~1getSceneWithCompletionHandler(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getSceneWithCompletionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mklookaroundscenerequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mklookaroundscenerequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
