{
  "abstract": [
    {
      "text": "Methods you implement to respond to changes in the LookAround view controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MKLookAroundViewControllerDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MKLookAroundViewControllerDelegate"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MKLookAroundViewControllerDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "MKLookAroundViewControllerDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MKLookAroundViewControllerDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewController/delegate": {
      "abstract": [
        {
          "text": "An object you provide to receive events related to the user’s interaction with the LookAround view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MKLookAroundViewControllerDelegate",
          "text": "MKLookAroundViewControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundviewcontroller/delegate"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate": {
      "abstract": [
        {
          "text": "Methods you implement to respond to changes in the LookAround view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLookAroundViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLookAroundViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "MKLookAroundViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundviewcontrollerdelegate"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerDidDismissFullScreen(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the view controller exits full-screen mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lookAroundViewControllerDidDismissFullScreen"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKLookAroundViewController",
          "text": "MKLookAroundViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerDidDismissFullScreen(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lookAroundViewControllerDidDismissFullScreen:"
        }
      ],
      "role": "symbol",
      "title": "lookAroundViewControllerDidDismissFullScreen(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundviewcontrollerdelegate/lookaroundviewcontrollerdiddismissfullscreen(_:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerDidPresentFullScreen(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the view controller enters full-screen mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lookAroundViewControllerDidPresentFullScreen"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKLookAroundViewController",
          "text": "MKLookAroundViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerDidPresentFullScreen(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lookAroundViewControllerDidPresentFullScreen:"
        }
      ],
      "role": "symbol",
      "title": "lookAroundViewControllerDidPresentFullScreen(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundviewcontrollerdelegate/lookaroundviewcontrollerdidpresentfullscreen(_:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerDidUpdateScene(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the scene updated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lookAroundViewControllerDidUpdateScene"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKLookAroundViewController",
          "text": "MKLookAroundViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerDidUpdateScene(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lookAroundViewControllerDidUpdateScene:"
        }
      ],
      "role": "symbol",
      "title": "lookAroundViewControllerDidUpdateScene(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundviewcontrollerdelegate/lookaroundviewcontrollerdidupdatescene(_:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerWillDismissFullScreen(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the view controller is about to exit full-screen mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lookAroundViewControllerWillDismissFullScreen"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKLookAroundViewController",
          "text": "MKLookAroundViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerWillDismissFullScreen(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lookAroundViewControllerWillDismissFullScreen:"
        }
      ],
      "role": "symbol",
      "title": "lookAroundViewControllerWillDismissFullScreen(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundviewcontrollerdelegate/lookaroundviewcontrollerwilldismissfullscreen(_:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerWillPresentFullScreen(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the view controller is about to enter full-screen mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lookAroundViewControllerWillPresentFullScreen"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKLookAroundViewController",
          "text": "MKLookAroundViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerWillPresentFullScreen(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lookAroundViewControllerWillPresentFullScreen:"
        }
      ],
      "role": "symbol",
      "title": "lookAroundViewControllerWillPresentFullScreen(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundviewcontrollerdelegate/lookaroundviewcontrollerwillpresentfullscreen(_:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerWillUpdateScene(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the scene is about to update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lookAroundViewControllerWillUpdateScene"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKLookAroundViewController",
          "text": "MKLookAroundViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerWillUpdateScene(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lookAroundViewControllerWillUpdateScene:"
        }
      ],
      "role": "symbol",
      "title": "lookAroundViewControllerWillUpdateScene(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundviewcontrollerdelegate/lookaroundviewcontrollerwillupdatescene(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Interacting-with-the-controller",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewController/delegate"
      ],
      "title": "Interacting with the controller"
    }
  ],
  "topicSections": [
    {
      "anchor": "Responding-to-scene-changes",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerWillUpdateScene(_:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerDidUpdateScene(_:)"
      ],
      "title": "Responding to scene changes"
    },
    {
      "anchor": "Entering-and-exiting-full-screen-modes",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerWillPresentFullScreen(_:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerDidPresentFullScreen(_:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerWillDismissFullScreen(_:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerDidDismissFullScreen(_:)"
      ],
      "title": "Entering and exiting full-screen modes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKLookAroundViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLookAroundViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLookAroundViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Responding-to-scene-changes",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerWillUpdateScene(_:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerDidUpdateScene(_:)"
              ],
              "title": "Responding to scene changes"
            },
            {
              "anchor": "Entering-and-exiting-full-screen-modes",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerWillPresentFullScreen(_:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerDidPresentFullScreen(_:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerWillDismissFullScreen(_:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewControllerDelegate/lookAroundViewControllerDidDismissFullScreen(_:)"
              ],
              "title": "Entering and exiting full-screen modes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Interacting-with-the-controller",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewController/delegate"
              ],
              "title": "Interacting with the controller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MKLookAroundViewControllerDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewControllerDelegate~1lookAroundViewControllerWillPresentFullScreen(_:)/title",
          "value": "lookAroundViewControllerWillPresentFullScreen:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewControllerDelegate~1lookAroundViewControllerWillPresentFullScreen(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lookAroundViewControllerWillPresentFullScreen:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewControllerDelegate~1lookAroundViewControllerWillDismissFullScreen(_:)/title",
          "value": "lookAroundViewControllerWillDismissFullScreen:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewControllerDelegate~1lookAroundViewControllerWillDismissFullScreen(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lookAroundViewControllerWillDismissFullScreen:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewControllerDelegate~1lookAroundViewControllerWillUpdateScene(_:)/title",
          "value": "lookAroundViewControllerWillUpdateScene:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewControllerDelegate~1lookAroundViewControllerWillUpdateScene(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lookAroundViewControllerWillUpdateScene:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewControllerDelegate~1lookAroundViewControllerDidUpdateScene(_:)/title",
          "value": "lookAroundViewControllerDidUpdateScene:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewControllerDelegate~1lookAroundViewControllerDidUpdateScene(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lookAroundViewControllerDidUpdateScene:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewControllerDelegate/title",
          "value": "MKLookAroundViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLookAroundViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLookAroundViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewControllerDelegate~1lookAroundViewControllerDidDismissFullScreen(_:)/title",
          "value": "lookAroundViewControllerDidDismissFullScreen:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewControllerDelegate~1lookAroundViewControllerDidDismissFullScreen(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lookAroundViewControllerDidDismissFullScreen:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewControllerDelegate~1lookAroundViewControllerDidPresentFullScreen(_:)/title",
          "value": "lookAroundViewControllerDidPresentFullScreen:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewControllerDelegate~1lookAroundViewControllerDidPresentFullScreen(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lookAroundViewControllerDidPresentFullScreen:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mklookaroundviewcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mklookaroundviewcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
