{
  "abstract": [
    {
      "text": "A class that describes an annotation element on the map’s display such as a point of interest, territorial boundary, or physical feature.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MKMapFeatureAnnotation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MKMapFeatureAnnotation"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MKMapFeatureAnnotation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MKMapFeatureAnnotation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MKMapFeatureAnnotation"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAnnotation": {
      "abstract": [
        {
          "text": "An interface for associating your content with a specific map location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKAnnotation"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAnnotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAnnotation"
        }
      ],
      "role": "symbol",
      "title": "MKAnnotation",
      "type": "topic",
      "url": "/documentation/mapkit/mkannotation"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKIconStyle": {
      "abstract": [
        {
          "text": "A class you use to customize the annotation view icon of a point of interest (POI) on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKIconStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKIconStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKIconStyle"
        }
      ],
      "role": "symbol",
      "title": "MKIconStyle",
      "type": "topic",
      "url": "/documentation/mapkit/mkiconstyle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation": {
      "abstract": [
        {
          "text": "A class that describes an annotation element on the map’s display such as a point of interest, territorial boundary, or physical feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapFeatureAnnotation"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapFeatureAnnotation"
        }
      ],
      "role": "symbol",
      "title": "MKMapFeatureAnnotation",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum": {
      "abstract": [
        {
          "text": "Values that describe the kinds of features visible on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FeatureType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FeatureType"
        }
      ],
      "role": "symbol",
      "title": "MKMapFeatureAnnotation.FeatureType",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation/featuretype-swift.enum"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/featureType-swift.property": {
      "abstract": [
        {
          "text": "The type of map feature this annotation represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featureType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapFeatureAnnotation",
          "text": "MKMapFeatureAnnotation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKMapFeatureType",
          "text": "FeatureType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/featureType-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "featureType"
        }
      ],
      "role": "symbol",
      "title": "featureType",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation/featuretype-swift.property"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/iconStyle": {
      "abstract": [
        {
          "text": "The icon style of a feature annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iconStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKIconStyle",
          "text": "MKIconStyle"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/iconStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iconStyle"
        }
      ],
      "role": "symbol",
      "title": "iconStyle",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation/iconstyle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/pointOfInterestCategory": {
      "abstract": [
        {
          "text": "The feature annotation’s point of interest category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointOfInterestCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
          "text": "MKPointOfInterestCategory"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/pointOfInterestCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pointOfInterestCategory"
        }
      ],
      "role": "symbol",
      "title": "pointOfInterestCategory",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureannotation/pointofinterestcategory"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureOptions": {
      "abstract": [
        {
          "text": "A structure you use to tell the map which kinds of features users can interact with.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapFeatureOptions"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapFeatureOptions"
        }
      ],
      "role": "symbol",
      "title": "MKMapFeatureOptions",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapfeatureoptions"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItemRequest": {
      "abstract": [
        {
          "text": "A utility class you use to request additional information about a map feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapItemRequest"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItemRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapItemRequest"
        }
      ],
      "role": "symbol",
      "title": "MKMapItemRequest",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitemrequest"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory": {
      "abstract": [
        {
          "text": "A point of interest category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPointOfInterestCategory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPointOfInterestCategory"
        }
      ],
      "role": "symbol",
      "title": "MKPointOfInterestCategory",
      "type": "topic",
      "url": "/documentation/mapkit/mkpointofinterestcategory"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestFilter": {
      "abstract": [
        {
          "text": "A filter that includes or excludes point of interest categories from a map view, local search, or local search completer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPointOfInterestFilter"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPointOfInterestFilter"
        }
      ],
      "role": "symbol",
      "title": "MKPointOfInterestFilter",
      "type": "topic",
      "url": "/documentation/mapkit/mkpointofinterestfilter"
    },
    "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids": {
      "abstract": [
        {
          "text": "Obtain information about a point of interest that persists over its lifetime.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids",
      "kind": "article",
      "role": "article",
      "title": "Identifying unique locations with Place IDs",
      "type": "topic",
      "url": "/documentation/mapkit/identifying-unique-locations-with-place-ids"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.apple.mapkit/documentation/MapKit/MKAnnotation",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Points-of-interest",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureOptions",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItemRequest",
        "doc://com.apple.mapkit/documentation/MapKit/MKIconStyle",
        "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestFilter",
        "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory"
      ],
      "title": "Points of interest"
    }
  ],
  "topicSections": [
    {
      "anchor": "Customizing-the-annotation",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/featureType-swift.property",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/iconStyle",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/pointOfInterestCategory"
      ],
      "title": "Customizing the annotation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKMapFeatureAnnotation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Customizing-the-annotation",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/featureType-swift.property",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/FeatureType-swift.enum",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/iconStyle",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation/pointOfInterestCategory"
              ],
              "title": "Customizing the annotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKAnnotation"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Points-of-interest",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureOptions",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItemRequest",
                "doc://com.apple.mapkit/documentation/MapKit/MKIconStyle",
                "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestFilter",
                "doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory"
              ],
              "title": "Points of interest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MKMapFeatureAnnotation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1FeatureType-swift.enum/title",
          "value": "MKMapFeatureType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1FeatureType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1FeatureType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemRequest/title",
          "value": "MKMapItemRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestFilter/title",
          "value": "MKPointOfInterestFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKIconStyle/title",
          "value": "MKIconStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKIconStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKIconStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKIconStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKIconStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureOptions/title",
          "value": "MKMapFeatureOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1pointOfInterestCategory/title",
          "value": "pointOfInterestCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1pointOfInterestCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pointOfInterestCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation/title",
          "value": "MKMapFeatureAnnotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapFeatureAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory/title",
          "value": "MKPointOfInterestCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPointOfInterestCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotation/title",
          "value": "MKAnnotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAnnotation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAnnotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1iconStyle/title",
          "value": "iconStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1iconStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "iconStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1featureType-swift.property/title",
          "value": "featureType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation~1featureType-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "featureType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkmapfeatureannotation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkmapfeatureannotation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
