{
  "abstract": [
    {
      "text": "A point on a two-dimensional map projection.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@MKMapPoint",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MKMapPoint"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MKMapPoint"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MKMapPoint"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MKMapPoint"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you project the curved surface of the globe onto a flat surface, you get a two-dimensional version of a map where longitude lines appear to be parallel. An ",
              "type": "text"
            },
            {
              "code": "MKMapPoint",
              "type": "codeVoice"
            },
            {
              "text": " data structure represents a point on this two-dimensional map.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The underlying units that MapKit uses to draw the contents of an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " define the actual units of a map point, but you don’t need to worry about these units directly. You use map points primarily to simplify computations that are complex to do using coordinate values on a curved surface. By converting to map points, you can perform those calculations on a flat surface, which is generally much simpler, and then convert back as necessary. You can map between coordinate values and map points using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/init(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/coordinate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When saving map-related data to a file, save coordinate values (latitude and longitude) rather than map points.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion": {
      "abstract": [
        {
          "text": "A rectangular geographic region that centers around a specific latitude and longitude.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKCoordinateRegion"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKCoordinateRegion"
        }
      ],
      "role": "symbol",
      "title": "MKCoordinateRegion",
      "type": "topic",
      "url": "/documentation/mapkit/mkcoordinateregion"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpan": {
      "abstract": [
        {
          "text": "The width and height of a map region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKCoordinateSpan"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKCoordinateSpan"
        }
      ],
      "role": "symbol",
      "title": "MKCoordinateSpan",
      "type": "topic",
      "url": "/documentation/mapkit/mkcoordinatespan"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter": {
      "abstract": [
        {
          "text": "A utility object that converts between a geographic distance and a string-based expression of that distance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKDistanceFormatter"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKDistanceFormatter"
        }
      ],
      "role": "symbol",
      "title": "MKDistanceFormatter",
      "type": "topic",
      "url": "/documentation/mapkit/mkdistanceformatter"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint": {
      "abstract": [
        {
          "text": "A point on a two-dimensional map projection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapPoint"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapPoint"
        }
      ],
      "role": "symbol",
      "title": "MKMapPoint",
      "type": "topic",
      "url": "/documentation/mapkit/mkmappoint"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/coordinate": {
      "abstract": [
        {
          "text": "A 2D coordinate that corresponds to the latitude and longitude of the specified map point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coordinate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CLLocationCoordinate2D",
          "text": "CLLocationCoordinate2D"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/coordinate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKCoordinateForMapPoint"
        }
      ],
      "role": "symbol",
      "title": "coordinate",
      "type": "topic",
      "url": "/documentation/mapkit/mkmappoint/coordinate"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/distance(to:)": {
      "abstract": [
        {
          "text": "Returns the number of meters between two map points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distance"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MKMapPoint",
          "text": "MKMapPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDistance",
          "text": "CLLocationDistance"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/distance(to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMetersBetweenMapPoints"
        }
      ],
      "role": "symbol",
      "title": "distance(to:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmappoint/distance(to:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/init()": {
      "abstract": [
        {
          "text": "Creates a map point at an unspecified point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/mapkit/mkmappoint/init()"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/init(_:)": {
      "abstract": [
        {
          "text": "Creates the map point data structure that corresponds to the specified coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CLLocationCoordinate2D",
          "text": "CLLocationCoordinate2D"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/init(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapPointForCoordinate"
        }
      ],
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmappoint/init(_:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/init(x:y:)": {
      "abstract": [
        {
          "text": "Creates a new map point structure from the specified values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/init(x:y:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(x:y:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmappoint/init(x:y:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/x": {
      "abstract": [
        {
          "text": "The location of the point along the x-axis of the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "x"
        }
      ],
      "role": "symbol",
      "title": "x",
      "type": "topic",
      "url": "/documentation/mapkit/mkmappoint/x"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/y": {
      "abstract": [
        {
          "text": "The location of the point along the y-axis of the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "y"
        }
      ],
      "role": "symbol",
      "title": "y",
      "type": "topic",
      "url": "/documentation/mapkit/mkmappoint/y"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapPointEqualToPoint(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether two map points are equal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapPointEqualToPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MKMapPoint",
          "text": "MKMapPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MKMapPoint",
          "text": "MKMapPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapPointEqualToPoint(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapPointEqualToPoint"
        }
      ],
      "role": "symbol",
      "title": "MKMapPointEqualToPoint(_:_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmappointequaltopoint(_:_:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapPointsPerMeterAtLatitude(_:)": {
      "abstract": [
        {
          "text": "Returns the number of map points that represent one meter at the specified latitude.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapPointsPerMeterAtLatitude"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDegrees",
          "text": "CLLocationDegrees"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapPointsPerMeterAtLatitude(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapPointsPerMeterAtLatitude"
        }
      ],
      "role": "symbol",
      "title": "MKMapPointsPerMeterAtLatitude(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmappointspermeteratlatitude(_:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapRect": {
      "abstract": [
        {
          "text": "A rectangular area on a two-dimensional map projection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapRect"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapRect"
        }
      ],
      "role": "symbol",
      "title": "MKMapRect",
      "type": "topic",
      "url": "/documentation/mapkit/mkmaprect"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapSize": {
      "abstract": [
        {
          "text": "Width and height information on a two-dimensional map projection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapSize"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapSize"
        }
      ],
      "role": "symbol",
      "title": "MKMapSize",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapsize"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapView": {
      "abstract": [
        {
          "text": "An embeddable map interface, similar to the one that the Maps app provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapView"
        }
      ],
      "role": "symbol",
      "title": "MKMapView",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMetersPerMapPointAtLatitude(_:)": {
      "abstract": [
        {
          "text": "Returns the distance that one map point spans at the specified latitude.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMetersPerMapPointAtLatitude"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDegrees",
          "text": "CLLocationDegrees"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CLLocationDistance",
          "text": "CLLocationDistance"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMetersPerMapPointAtLatitude(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMetersPerMapPointAtLatitude"
        }
      ],
      "role": "symbol",
      "title": "MKMetersPerMapPointAtLatitude(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmeterspermappointatlatitude(_:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKStringFromMapPoint(_:)": {
      "abstract": [
        {
          "text": "Returns a formatted string for the specified map point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKStringFromMapPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MKMapPoint",
          "text": "MKMapPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKStringFromMapPoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKStringFromMapPoint"
        }
      ],
      "role": "symbol",
      "title": "MKStringFromMapPoint(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkstringfrommappoint(_:)"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Map-coordinates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion",
        "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpan",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapRect",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapSize",
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter"
      ],
      "title": "Map coordinates"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-map-point",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/init()",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/init(x:y:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/init(_:)"
      ],
      "title": "Creating a map point"
    },
    {
      "anchor": "Getting-the-point-coordinates",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/x",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/y",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/coordinate"
      ],
      "title": "Getting the point coordinates"
    },
    {
      "anchor": "Comparing-map-points",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapPointEqualToPoint(_:_:)"
      ],
      "title": "Comparing map points"
    },
    {
      "anchor": "Getting-the-distance-between-points",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/distance(to:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKMetersPerMapPointAtLatitude(_:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapPointsPerMeterAtLatitude(_:)"
      ],
      "title": "Getting the distance between points"
    },
    {
      "anchor": "Getting-a-description-of-the-point",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKStringFromMapPoint(_:)"
      ],
      "title": "Getting a description of the point"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKMapPoint"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-map-point",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/init(_:)"
              ],
              "title": "Creating a map point"
            },
            {
              "anchor": "Getting-the-point-coordinates",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/x",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/y",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/coordinate"
              ],
              "title": "Getting the point coordinates"
            },
            {
              "anchor": "Comparing-map-points",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapPointEqualToPoint(_:_:)"
              ],
              "title": "Comparing map points"
            },
            {
              "anchor": "Getting-the-distance-between-points",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapPoint/distance(to:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKMetersPerMapPointAtLatitude(_:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapPointsPerMeterAtLatitude(_:)"
              ],
              "title": "Getting the distance between points"
            },
            {
              "anchor": "Getting-a-description-of-the-point",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKStringFromMapPoint(_:)"
              ],
              "title": "Getting a description of the point"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Map-coordinates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion",
                "doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpan",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapRect",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapSize",
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter"
              ],
              "title": "Map coordinates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "MKMapPoint"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateSpan/title",
          "value": "MKCoordinateSpan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateSpan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCoordinateSpan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateSpan/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCoordinateSpan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint/title",
          "value": "MKMapPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSize/title",
          "value": "MKMapSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint~1distance(to:)/title",
          "value": "MKMetersBetweenMapPoints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint~1distance(to:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMetersBetweenMapPoints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView/title",
          "value": "MKMapView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMetersPerMapPointAtLatitude(_:)/title",
          "value": "MKMetersPerMapPointAtLatitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMetersPerMapPointAtLatitude(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMetersPerMapPointAtLatitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter/title",
          "value": "MKDistanceFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPointEqualToPoint(_:_:)/title",
          "value": "MKMapPointEqualToPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPointEqualToPoint(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapPointEqualToPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint~1x/title",
          "value": "x"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint~1x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "x"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint~1init(_:)/title",
          "value": "MKMapPointForCoordinate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint~1init(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapPointForCoordinate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPointsPerMeterAtLatitude(_:)/title",
          "value": "MKMapPointsPerMeterAtLatitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPointsPerMeterAtLatitude(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapPointsPerMeterAtLatitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint~1y/title",
          "value": "y"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint~1y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "y"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint~1coordinate/title",
          "value": "MKCoordinateForMapPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint~1coordinate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCoordinateForMapPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateRegion/title",
          "value": "MKCoordinateRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateRegion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCoordinateRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateRegion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKCoordinateRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect/title",
          "value": "MKMapRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStringFromMapPoint(_:)/title",
          "value": "MKStringFromMapPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStringFromMapPoint(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKStringFromMapPoint"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkmappoint"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkmappoint"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
