{
  "abstract": [
    {
      "text": "The type of map to display.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use the map view’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapView/preferredConfiguration",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property with one of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapConfiguration",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " subclasses to select a specific map style instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKMapType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MKMapType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MKMapType"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MKMapType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MKMapType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MKMapType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapConfiguration": {
      "abstract": [
        {
          "text": "An abstract class that represents the shared elements of map configurations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapConfiguration"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapConfiguration"
        }
      ],
      "role": "symbol",
      "title": "MKMapConfiguration",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapconfiguration"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapType": {
      "abstract": [
        {
          "text": "The type of map to display.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapType"
        }
      ],
      "role": "symbol",
      "title": "MKMapType",
      "type": "topic",
      "url": "/documentation/mapkit/mkmaptype"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapType/hybrid": {
      "abstract": [
        {
          "text": "A satellite image of the area with road and road name information layered on top.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hybrid"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapType/hybrid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapTypeHybrid"
        }
      ],
      "role": "symbol",
      "title": "MKMapType.hybrid",
      "type": "topic",
      "url": "/documentation/mapkit/mkmaptype/hybrid"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapType/hybridFlyover": {
      "abstract": [
        {
          "text": "A hybrid satellite image with flyover data where available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hybridFlyover"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapType/hybridFlyover",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapTypeHybridFlyover"
        }
      ],
      "role": "symbol",
      "title": "MKMapType.hybridFlyover",
      "type": "topic",
      "url": "/documentation/mapkit/mkmaptype/hybridflyover"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmaptype/init(rawvalue:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapType/mutedStandard": {
      "abstract": [
        {
          "text": "A street map where MapKit emphasizes your data over the underlying map details.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mutedStandard"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapType/mutedStandard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapTypeMutedStandard"
        }
      ],
      "role": "symbol",
      "title": "MKMapType.mutedStandard",
      "type": "topic",
      "url": "/documentation/mapkit/mkmaptype/mutedstandard"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapType/satellite": {
      "abstract": [
        {
          "text": "Satellite imagery of the area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "satellite"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapType/satellite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapTypeSatellite"
        }
      ],
      "role": "symbol",
      "title": "MKMapType.satellite",
      "type": "topic",
      "url": "/documentation/mapkit/mkmaptype/satellite"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapType/satelliteFlyover": {
      "abstract": [
        {
          "text": "A satellite image of the area with flyover data where available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "satelliteFlyover"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapType/satelliteFlyover",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapTypeSatelliteFlyover"
        }
      ],
      "role": "symbol",
      "title": "MKMapType.satelliteFlyover",
      "type": "topic",
      "url": "/documentation/mapkit/mkmaptype/satelliteflyover"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapType/standard": {
      "abstract": [
        {
          "text": "A street map that shows the position of all roads and some road names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "standard"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapType/standard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapTypeStandard"
        }
      ],
      "role": "symbol",
      "title": "MKMapType.standard",
      "type": "topic",
      "url": "/documentation/mapkit/mkmaptype/standard"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapView/isPitchEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the map uses the camera’s pitch information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPitchEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapView/isPitchEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pitchEnabled"
        }
      ],
      "role": "symbol",
      "title": "isPitchEnabled",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapview/ispitchenabled"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapView/isRotateEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the map uses the camera’s heading information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRotateEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapView/isRotateEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rotateEnabled"
        }
      ],
      "role": "symbol",
      "title": "isRotateEnabled",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapview/isrotateenabled"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapView/isScrollEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the user may scroll around the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isScrollEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapView/isScrollEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollEnabled"
        }
      ],
      "role": "symbol",
      "title": "isScrollEnabled",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapview/isscrollenabled"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapView/isZoomEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the user may use pinch gestures to zoom in and out of the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isZoomEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapView/isZoomEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "zoomEnabled"
        }
      ],
      "role": "symbol",
      "title": "isZoomEnabled",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapview/iszoomenabled"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapView/mapType": {
      "abstract": [
        {
          "text": "The type of data the map view displays.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKMapType",
          "text": "MKMapType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapView/mapType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapType"
        }
      ],
      "role": "symbol",
      "title": "mapType",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapview/maptype"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapView/preferredConfiguration": {
      "abstract": [
        {
          "text": "The characteristics of the map view, including the map type and features the map displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapConfiguration",
          "text": "MKMapConfiguration"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapView/preferredConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredConfiguration"
        }
      ],
      "role": "symbol",
      "title": "preferredConfiguration",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapview/preferredconfiguration"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-map-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapView/isZoomEnabled",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapView/isScrollEnabled",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapView/isPitchEnabled",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapView/isRotateEnabled",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapView/mapType"
      ],
      "title": "Accessing map properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapType/standard",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapType/satellite",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapType/hybrid",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapType/satelliteFlyover",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapType/hybridFlyover",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapType/mutedStandard"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKMapType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapType/standard",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapType/satellite",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapType/hybrid",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapType/satelliteFlyover",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapType/hybridFlyover",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapType/mutedStandard"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-map-properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapView/isZoomEnabled",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapView/isScrollEnabled",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapView/isPitchEnabled",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapView/isRotateEnabled",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapView/mapType"
              ],
              "title": "Accessing map properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MKMapType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use the map view’s ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapView/preferredConfiguration",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property with one of the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapConfiguration",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " subclasses to select a specific map style instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView~1preferredConfiguration/title",
          "value": "preferredConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView~1preferredConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView~1mapType/title",
          "value": "mapType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView~1mapType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mapType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1hybridFlyover/title",
          "value": "MKMapTypeHybridFlyover"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1hybridFlyover/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapTypeHybridFlyover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView~1isRotateEnabled/title",
          "value": "rotateEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView~1isRotateEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rotateEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1satellite/title",
          "value": "MKMapTypeSatellite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1satellite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapTypeSatellite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1satelliteFlyover/title",
          "value": "MKMapTypeSatelliteFlyover"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1satelliteFlyover/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapTypeSatelliteFlyover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType/title",
          "value": "MKMapType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapConfiguration/title",
          "value": "MKMapConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1standard/title",
          "value": "MKMapTypeStandard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1standard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapTypeStandard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1hybrid/title",
          "value": "MKMapTypeHybrid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1hybrid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapTypeHybrid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1mutedStandard/title",
          "value": "MKMapTypeMutedStandard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1mutedStandard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapTypeMutedStandard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView~1isZoomEnabled/title",
          "value": "zoomEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView~1isZoomEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "zoomEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView~1isPitchEnabled/title",
          "value": "pitchEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView~1isPitchEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pitchEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView~1isScrollEnabled/title",
          "value": "scrollEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView~1isScrollEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scrollEnabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkmaptype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkmaptype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
