{
  "abstract": [
    {
      "text": "A point of interest on the map.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MKMapItem",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MKMapItem"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MKMapItem"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MKMapItem"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MKMapItem"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A map item includes a geographic location and any interesting data that might apply to that location, such as the address at that location and the name of a business at that address. You can also create a special ",
              "type": "text"
            },
            {
              "code": "MKMapItem",
              "type": "codeVoice"
            },
            {
              "text": " object representing the user’s location.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use this class to do the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Share map-related data with the Maps app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Handle requests for directions that originate from the Maps app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "To display information in the Maps app, create an ",
              "type": "text"
            },
            {
              "code": "MKMapItem",
              "type": "codeVoice"
            },
            {
              "text": " object with the information you want to display and call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openMaps(with:launchOptions:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. The Maps app displays that location on the map and shows the information you provide.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you implement a routing app, the Maps app provides two ",
              "type": "text"
            },
            {
              "code": "MKMapItem",
              "type": "codeVoice"
            },
            {
              "text": " objects representing the start and end points. Use the information in those two objects to plot the route and generate directions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem": {
      "abstract": [
        {
          "text": "A point of interest on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapItem"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapItem"
        }
      ],
      "role": "symbol",
      "title": "MKMapItem",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/Identifier-swift.class": {
      "abstract": [
        {
          "text": "A unique identifier for a place.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Identifier"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/Identifier-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Identifier"
        }
      ],
      "role": "symbol",
      "title": "MKMapItem.Identifier",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/identifier-swift.class"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/alternateIdentifiers": {
      "abstract": [
        {
          "text": "A set of alternative identifiers for a place.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alternateIdentifiers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItem",
          "text": "MKMapItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItemIdentifier",
          "text": "Identifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/alternateIdentifiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alternateIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "alternateIdentifiers",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/alternateidentifiers"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/forCurrentLocation()": {
      "abstract": [
        {
          "text": "Creates and returns a singleton map item object representing the user’s location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forCurrentLocation"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItem",
          "text": "MKMapItem"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/forCurrentLocation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapItemForCurrentLocation"
        }
      ],
      "role": "symbol",
      "title": "forCurrentLocation()",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/forcurrentlocation()"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/identifier-swift.property": {
      "abstract": [
        {
          "text": "A unique identifier for a place.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItem",
          "text": "MKMapItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItemIdentifier",
          "text": "Identifier"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/identifier-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/identifier-swift.property"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/init(coder:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/init(coder:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/init(coder:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/init(placemark:)": {
      "abstract": [
        {
          "text": "Creates and returns a map item object using the specified placemark object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "placemark"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKPlacemark",
          "text": "MKPlacemark"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/init(placemark:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPlacemark:"
        }
      ],
      "role": "symbol",
      "title": "init(placemark:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/init(placemark:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/isCurrentLocation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the map item represents the user’s location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isCurrentLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/isCurrentLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isCurrentLocation"
        }
      ],
      "role": "symbol",
      "title": "isCurrentLocation",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/iscurrentlocation"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/name": {
      "abstract": [
        {
          "text": "The descriptive name associated with the map item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/name"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openInMaps(launchOptions:)": {
      "abstract": [
        {
          "text": "Opens the Maps app and displays the map item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openInMaps"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "launchOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openInMaps(launchOptions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openInMapsWithLaunchOptions:"
        }
      ],
      "role": "symbol",
      "title": "openInMaps(launchOptions:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/openinmaps(launchoptions:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openInMaps(launchOptions:completionHandler:)": {
      "abstract": [
        {
          "text": "Opens the Maps app and displays the map item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openInMaps"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "launchOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openInMaps(launchOptions:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openInMapsWithLaunchOptions:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "openInMaps(launchOptions:completionHandler:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/openinmaps(launchoptions:completionhandler:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openInMaps(launchOptions:from:completionHandler:)": {
      "abstract": [
        {
          "text": "Opens the Maps app from a particular scene using the specified options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openInMaps"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "launchOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScene",
          "text": "UIScene"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openInMaps(launchOptions:from:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openInMapsWithLaunchOptions:fromScene:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "openInMaps(launchOptions:from:completionHandler:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/openinmaps(launchoptions:from:completionhandler:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openMaps(with:launchOptions:)": {
      "abstract": [
        {
          "text": "Opens the Maps app and displays the specified map items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openMaps"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItem",
          "text": "MKMapItem"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "launchOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openMaps(with:launchOptions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openMapsWithItems:launchOptions:"
        }
      ],
      "role": "symbol",
      "title": "openMaps(with:launchOptions:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/openmaps(with:launchoptions:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openMaps(with:launchOptions:completionHandler:)": {
      "abstract": [
        {
          "text": "Opens the Maps app using the specified map items and options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openMaps"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItem",
          "text": "MKMapItem"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "launchOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openMaps(with:launchOptions:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openMapsWithItems:launchOptions:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "openMaps(with:launchOptions:completionHandler:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/openmaps(with:launchoptions:completionhandler:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openMaps(with:launchOptions:from:completionHandler:)": {
      "abstract": [
        {
          "text": "Opens the Maps app from a particular scene using the specified map items and options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openMaps"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItem",
          "text": "MKMapItem"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "launchOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScene",
          "text": "UIScene"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openMaps(with:launchOptions:from:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openMapsWithItems:launchOptions:fromScene:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "openMaps(with:launchOptions:from:completionHandler:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/openmaps(with:launchoptions:from:completionhandler:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/phoneNumber": {
      "abstract": [
        {
          "text": "The phone number associated with a business at the specified location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phoneNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/phoneNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "phoneNumber"
        }
      ],
      "role": "symbol",
      "title": "phoneNumber",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/phonenumber"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/placemark": {
      "abstract": [
        {
          "text": "The placemark object containing the location information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "placemark"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKPlacemark",
          "text": "MKPlacemark"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/placemark",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "placemark"
        }
      ],
      "role": "symbol",
      "title": "placemark",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/placemark"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/pointOfInterestCategory": {
      "abstract": [
        {
          "text": "The point-of-interest category for the map item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointOfInterestCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MKPointOfInterestCategory",
          "text": "MKPointOfInterestCategory"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/pointOfInterestCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pointOfInterestCategory"
        }
      ],
      "role": "symbol",
      "title": "pointOfInterestCategory",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/pointofinterestcategory"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/timeZone": {
      "abstract": [
        {
          "text": "The time zone of the specified location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeZone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8TimeZoneV",
          "text": "TimeZone"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/timeZone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timeZone"
        }
      ],
      "role": "symbol",
      "title": "timeZone",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/timezone"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/url": {
      "abstract": [
        {
          "text": "The URL associated with the specified location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/url",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "url"
        }
      ],
      "role": "symbol",
      "title": "url",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitem/url"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItemTypeIdentifier": {
      "abstract": [
        {
          "text": "A constant that indicates the type of a serialized map item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapItemTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItemTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapItemTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "MKMapItemTypeIdentifier",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitemtypeidentifier"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapView": {
      "abstract": [
        {
          "text": "An embeddable map interface, similar to the one that the Maps app provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapView"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapView"
        }
      ],
      "role": "symbol",
      "title": "MKMapView",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/directions-mode-values": {
      "abstract": [
        {
          "text": "Strings that represent the possible values of the launch options direction mode key.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/directions-mode-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Directions mode values",
      "type": "topic",
      "url": "/documentation/mapkit/directions-mode-values"
    },
    "doc://com.apple.mapkit/documentation/MapKit/enabling-maps-capability-in-xcode": {
      "abstract": [
        {
          "text": "Configure your routing app to support providing directions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/enabling-maps-capability-in-xcode",
      "kind": "article",
      "role": "article",
      "title": "Enabling Maps capability in Xcode",
      "type": "topic",
      "url": "/documentation/mapkit/enabling-maps-capability-in-xcode"
    },
    "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids": {
      "abstract": [
        {
          "text": "Obtain information about a point of interest that persists over its lifetime.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids",
      "kind": "article",
      "role": "article",
      "title": "Identifying unique locations with Place IDs",
      "type": "topic",
      "url": "/documentation/mapkit/identifying-unique-locations-with-place-ids"
    },
    "doc://com.apple.mapkit/documentation/MapKit/launch-options-dictionary-keys": {
      "abstract": [
        {
          "text": "Launch options to specify when opening map items in the Maps app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/launch-options-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Launch options dictionary keys",
      "type": "topic",
      "url": "/documentation/mapkit/launch-options-dictionary-keys"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderReading": {
      "abstract": [
        {
          "text": "The protocol for implementing a class to allow an item provider to create an instance of the class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSItemProviderReading"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderReading",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSItemProviderReading",
      "type": "topic",
      "url": "/documentation/foundation/nsitemproviderreading"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderWriting": {
      "abstract": [
        {
          "text": "The protocol for implementing a class to allow an item provider to retrieve data from an instance of the class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSItemProviderWriting"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderWriting",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSItemProviderWriting",
      "type": "topic",
      "url": "/documentation/foundation/nsitemproviderwriting"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderReading",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderWriting",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/enabling-maps-capability-in-xcode",
        "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapView"
      ],
      "title": "Essentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-map-items",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/init(placemark:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/forCurrentLocation()"
      ],
      "title": "Creating map items"
    },
    {
      "anchor": "Accessing-the-map-item-attributes",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/Identifier-swift.class",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/alternateIdentifiers",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/identifier-swift.property",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/isCurrentLocation",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/name",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/placemark",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/pointOfInterestCategory",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/phoneNumber",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/timeZone",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/url"
      ],
      "title": "Accessing the map item attributes"
    },
    {
      "anchor": "Launching-the-Maps-app",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openMaps(with:launchOptions:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openMaps(with:launchOptions:completionHandler:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openMaps(with:launchOptions:from:completionHandler:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openInMaps(launchOptions:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openInMaps(launchOptions:completionHandler:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openInMaps(launchOptions:from:completionHandler:)"
      ],
      "title": "Launching the Maps app"
    },
    {
      "anchor": "Serializing-a-map-item",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItemTypeIdentifier"
      ],
      "title": "Serializing a map item"
    },
    {
      "anchor": "Opening-items-at-launch-time",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/launch-options-dictionary-keys",
        "doc://com.apple.mapkit/documentation/MapKit/directions-mode-values"
      ],
      "title": "Opening items at launch time"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/init(coder:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKMapItem"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-map-items",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/init(placemark:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/forCurrentLocation()"
              ],
              "title": "Creating map items"
            },
            {
              "anchor": "Accessing-the-map-item-attributes",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/Identifier-swift.class",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/alternateIdentifiers",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/identifier-swift.property",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/isCurrentLocation",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/name",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/placemark",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/pointOfInterestCategory",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/phoneNumber",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/timeZone",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/url"
              ],
              "title": "Accessing the map item attributes"
            },
            {
              "anchor": "Launching-the-Maps-app",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openMaps(with:launchOptions:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openMaps(with:launchOptions:completionHandler:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openMaps(with:launchOptions:from:completionHandler:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openInMaps(launchOptions:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openInMaps(launchOptions:completionHandler:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItem/openInMaps(launchOptions:from:completionHandler:)"
              ],
              "title": "Launching the Maps app"
            },
            {
              "anchor": "Serializing-a-map-item",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItemTypeIdentifier"
              ],
              "title": "Serializing a map item"
            },
            {
              "anchor": "Opening-items-at-launch-time",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/launch-options-dictionary-keys",
                "doc://com.apple.mapkit/documentation/MapKit/directions-mode-values"
              ],
              "title": "Opening items at launch time"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderReading",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderWriting",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/enabling-maps-capability-in-xcode",
                "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapView"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MKMapItem"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1placemark/title",
          "value": "placemark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1placemark/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "placemark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1init(placemark:)/title",
          "value": "initWithPlacemark:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1init(placemark:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPlacemark:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1openMaps(with:launchOptions:)/title",
          "value": "openMapsWithItems:launchOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1openMaps(with:launchOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "openMapsWithItems:launchOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1openInMaps(launchOptions:completionHandler:)/title",
          "value": "openInMapsWithLaunchOptions:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1openInMaps(launchOptions:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "openInMapsWithLaunchOptions:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1timeZone/title",
          "value": "timeZone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1timeZone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timeZone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1phoneNumber/title",
          "value": "phoneNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1phoneNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "phoneNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1openInMaps(launchOptions:from:completionHandler:)/title",
          "value": "openInMapsWithLaunchOptions:fromScene:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1openInMaps(launchOptions:from:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "openInMapsWithLaunchOptions:fromScene:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1forCurrentLocation()/title",
          "value": "mapItemForCurrentLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1forCurrentLocation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "mapItemForCurrentLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1openInMaps(launchOptions:)/title",
          "value": "openInMapsWithLaunchOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1openInMaps(launchOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "openInMapsWithLaunchOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView/title",
          "value": "MKMapView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1openMaps(with:launchOptions:completionHandler:)/title",
          "value": "openMapsWithItems:launchOptions:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1openMaps(with:launchOptions:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "openMapsWithItems:launchOptions:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1openMaps(with:launchOptions:from:completionHandler:)/title",
          "value": "openMapsWithItems:launchOptions:fromScene:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1openMaps(with:launchOptions:from:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "openMapsWithItems:launchOptions:fromScene:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1Identifier-swift.class/title",
          "value": "MKMapItemIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1Identifier-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1Identifier-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1isCurrentLocation/title",
          "value": "isCurrentLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1isCurrentLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isCurrentLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1identifier-swift.property/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1identifier-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1url/title",
          "value": "url"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1url/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "url"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1pointOfInterestCategory/title",
          "value": "pointOfInterestCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1pointOfInterestCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pointOfInterestCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemTypeIdentifier/title",
          "value": "MKMapItemTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1alternateIdentifiers/title",
          "value": "alternateIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem~1alternateIdentifiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alternateIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem/title",
          "value": "MKMapItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkmapitem"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkmapitem"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
