{
  "abstract": [
    {
      "text": "A visual representation of any polyline overlay object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MKPolylineRenderer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MKPolylineRenderer"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MKPolylineRenderer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MKPolylineRenderer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MKPolylineRenderer"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This renderer strokes the line only; it doesn’t fill it. You can change the color and other drawing attributes of the polyline by modifying the properties it inherits from the main class. You typically use this class as-is and don’t subclass it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKGeodesicPolyline": {
      "abstract": [
        {
          "text": "An open polygon overlay consisting of line segments that follow the contours of the Earth to create the shortest path between the specified points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKGeodesicPolyline"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKGeodesicPolyline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKGeodesicPolyline"
        }
      ],
      "role": "symbol",
      "title": "MKGeodesicPolyline",
      "type": "topic",
      "url": "/documentation/mapkit/mkgeodesicpolyline"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKGradientPolylineRenderer": {
      "abstract": [
        {
          "text": "A visual representation of any polyline overlay object with a gradient.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKGradientPolylineRenderer"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKGradientPolylineRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKGradientPolylineRenderer"
        }
      ],
      "role": "symbol",
      "title": "MKGradientPolylineRenderer",
      "type": "topic",
      "url": "/documentation/mapkit/mkgradientpolylinerenderer"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolyline": {
      "abstract": [
        {
          "text": "A collection of multipolyline shapes, each consisting of one or more connected line segments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMultiPolyline"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolyline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMultiPolyline"
        }
      ],
      "role": "symbol",
      "title": "MKMultiPolyline",
      "type": "topic",
      "url": "/documentation/mapkit/mkmultipolyline"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolylineRenderer": {
      "abstract": [
        {
          "text": "A visual representation of multiple polyline overlay objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMultiPolylineRenderer"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolylineRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMultiPolylineRenderer"
        }
      ],
      "role": "symbol",
      "title": "MKMultiPolylineRenderer",
      "type": "topic",
      "url": "/documentation/mapkit/mkmultipolylinerenderer"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer": {
      "abstract": [
        {
          "text": "The visual representation of a path-based overlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKOverlayPathRenderer"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKOverlayPathRenderer"
        }
      ],
      "role": "symbol",
      "title": "MKOverlayPathRenderer",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlaypathrenderer"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPolyline": {
      "abstract": [
        {
          "text": "An open polygon overlay consisting of one or more connected line segments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPolyline"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolyline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPolyline"
        }
      ],
      "role": "symbol",
      "title": "MKPolyline",
      "type": "topic",
      "url": "/documentation/mapkit/mkpolyline"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer": {
      "abstract": [
        {
          "text": "A visual representation of any polyline overlay object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKPolylineRenderer"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKPolylineRenderer"
        }
      ],
      "role": "symbol",
      "title": "MKPolylineRenderer",
      "type": "topic",
      "url": "/documentation/mapkit/mkpolylinerenderer"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer/init(polyline:)": {
      "abstract": [
        {
          "text": "Creates a new overlay view using the specified polyline overlay object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "polyline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKPolyline",
          "text": "MKPolyline"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer/init(polyline:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPolyline:"
        }
      ],
      "role": "symbol",
      "title": "init(polyline:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkpolylinerenderer/init(polyline:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer/polyline": {
      "abstract": [
        {
          "text": "The polyline overlay object that contains the information for drawing the overlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "polyline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKPolyline",
          "text": "MKPolyline"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer/polyline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "polyline"
        }
      ],
      "role": "symbol",
      "title": "polyline",
      "type": "topic",
      "url": "/documentation/mapkit/mkpolylinerenderer/polyline"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer/strokeEnd": {
      "abstract": [
        {
          "text": "The unit distance along the line where the stroke ends.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strokeEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer/strokeEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "strokeEnd"
        }
      ],
      "role": "symbol",
      "title": "strokeEnd",
      "type": "topic",
      "url": "/documentation/mapkit/mkpolylinerenderer/strokeend"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer/strokeStart": {
      "abstract": [
        {
          "text": "The unit distance along the line where the stroke starts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strokeStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer/strokeStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "strokeStart"
        }
      ],
      "role": "symbol",
      "title": "strokeStart",
      "type": "topic",
      "url": "/documentation/mapkit/mkpolylinerenderer/strokestart"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKGradientPolylineRenderer"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Multiple-segment-lines",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKPolyline",
        "doc://com.apple.mapkit/documentation/MapKit/MKGeodesicPolyline",
        "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolyline",
        "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolylineRenderer",
        "doc://com.apple.mapkit/documentation/MapKit/MKGradientPolylineRenderer"
      ],
      "title": "Multiple segment lines"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-polyline-renderer",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer/init(polyline:)"
      ],
      "title": "Creating a polyline renderer"
    },
    {
      "anchor": "Accessing-the-polyline-overlay",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer/polyline"
      ],
      "title": "Accessing the polyline overlay"
    },
    {
      "anchor": "Accessing-the-stroke",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer/strokeStart",
        "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer/strokeEnd"
      ],
      "title": "Accessing the stroke"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKPolylineRenderer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolylineRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolylineRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-polyline-renderer",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer/init(polyline:)"
              ],
              "title": "Creating a polyline renderer"
            },
            {
              "anchor": "Accessing-the-polyline-overlay",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer/polyline"
              ],
              "title": "Accessing the polyline overlay"
            },
            {
              "anchor": "Accessing-the-stroke",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer/strokeStart",
                "doc://com.apple.mapkit/documentation/MapKit/MKPolylineRenderer/strokeEnd"
              ],
              "title": "Accessing the stroke"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKGradientPolylineRenderer"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Multiple-segment-lines",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKPolyline",
                "doc://com.apple.mapkit/documentation/MapKit/MKGeodesicPolyline",
                "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolyline",
                "doc://com.apple.mapkit/documentation/MapKit/MKMultiPolylineRenderer",
                "doc://com.apple.mapkit/documentation/MapKit/MKGradientPolylineRenderer"
              ],
              "title": "Multiple segment lines"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MKPolylineRenderer"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MKOverlayPathRenderer",
                    "text": "MKOverlayPathRenderer"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer/title",
          "value": "MKOverlayPathRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayPathRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayPathRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineRenderer~1strokeStart/title",
          "value": "strokeStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineRenderer~1strokeStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "strokeStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPolylineRenderer/title",
          "value": "MKMultiPolylineRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPolylineRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMultiPolylineRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPolylineRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMultiPolylineRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineRenderer~1polyline/title",
          "value": "polyline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineRenderer~1polyline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "polyline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPolyline/title",
          "value": "MKMultiPolyline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPolyline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMultiPolyline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMultiPolyline/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMultiPolyline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineRenderer~1strokeEnd/title",
          "value": "strokeEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineRenderer~1strokeEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "strokeEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineRenderer/title",
          "value": "MKPolylineRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolylineRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolylineRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGeodesicPolyline/title",
          "value": "MKGeodesicPolyline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGeodesicPolyline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKGeodesicPolyline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGeodesicPolyline/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKGeodesicPolyline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineRenderer~1init(polyline:)/title",
          "value": "initWithPolyline:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolylineRenderer~1init(polyline:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPolyline:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolyline/title",
          "value": "MKPolyline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolyline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolyline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPolyline/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKPolyline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGradientPolylineRenderer/title",
          "value": "MKGradientPolylineRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGradientPolylineRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKGradientPolylineRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGradientPolylineRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKGradientPolylineRenderer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkpolylinerenderer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkpolylinerenderer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
