{
  "abstract": [
    {
      "text": "The type of accessory to display for a selected annotation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MKSelectionAccessory",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MKSelectionAccessory"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MKSelectionAccessory"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MKSelectionAccessory"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MKSelectionAccessory"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapViewDelegate/mapView(_:selectionAccessoryFor:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in your map view delegate to specify a selection accessory for annotation content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewController": {
      "abstract": [
        {
          "text": "An object that displays detailed information about a map item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapItemDetailViewController"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapItemDetailViewController"
        }
      ],
      "role": "symbol",
      "title": "MKMapItemDetailViewController",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitemdetailviewcontroller"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewControllerDelegate": {
      "abstract": [
        {
          "text": "The methods that you use to receive events from an associated map view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapItemDetailViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapItemDetailViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "MKMapItemDetailViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapitemdetailviewcontrollerdelegate"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapViewDelegate/mapView(_:selectionAccessoryFor:)": {
      "abstract": [
        {
          "text": "Specifies the accessory to display for a selected annotation",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapView",
          "text": "MKMapView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "selectionAccessoryFor"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MKAnnotation",
          "text": "MKAnnotation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKSelectionAccessory",
          "text": "MKSelectionAccessory"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapViewDelegate/mapView(_:selectionAccessoryFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapView:selectionAccessoryForAnnotation:"
        }
      ],
      "role": "symbol",
      "title": "mapView(_:selectionAccessoryFor:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapviewdelegate/mapview(_:selectionaccessoryfor:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory": {
      "abstract": [
        {
          "text": "The type of accessory to display for a selected annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKSelectionAccessory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKSelectionAccessory"
        }
      ],
      "role": "symbol",
      "title": "MKSelectionAccessory",
      "type": "topic",
      "url": "/documentation/mapkit/mkselectionaccessory"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle": {
      "abstract": [
        {
          "text": "The type of map item detail accessory presentation to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MapItemDetailPresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MapItemDetailPresentationStyle"
        }
      ],
      "role": "symbol",
      "title": "MKSelectionAccessory.MapItemDetailPresentationStyle",
      "type": "topic",
      "url": "/documentation/mapkit/mkselectionaccessory/mapitemdetailpresentationstyle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/CalloutStyle": {
      "abstract": [
        {
          "text": "The style to use for a map item detail callout presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CalloutStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/CalloutStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CalloutStyle"
        }
      ],
      "role": "symbol",
      "title": "MKSelectionAccessory.MapItemDetailPresentationStyle.CalloutStyle",
      "type": "topic",
      "url": "/documentation/mapkit/mkselectionaccessory/mapitemdetailpresentationstyle/calloutstyle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/mapItemDetail(_:)": {
      "abstract": [
        {
          "text": "Detailed information about a place",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapItemDetail"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKSelectionAccessory",
          "text": "MKSelectionAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItemDetailSelectionAccessoryPresentationStyle",
          "text": "MapItemDetailPresentationStyle"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKSelectionAccessory",
          "text": "MKSelectionAccessory"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/mapItemDetail(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapItemDetailWithPresentationStyle:"
        }
      ],
      "role": "symbol",
      "title": "mapItemDetail(_:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkselectionaccessory/mapitemdetail(_:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids": {
      "abstract": [
        {
          "text": "Obtain information about a point of interest that persists over its lifetime.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids",
      "kind": "article",
      "role": "article",
      "title": "Identifying unique locations with Place IDs",
      "type": "topic",
      "url": "/documentation/mapkit/identifying-unique-locations-with-place-ids"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Place-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewControllerDelegate",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewController",
        "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle",
        "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/CalloutStyle"
      ],
      "title": "Place information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-selection-accessory",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/mapItemDetail(_:)"
      ],
      "title": "Creating a selection accessory"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKSelectionAccessory"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKSelectionAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKSelectionAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-selection-accessory",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/mapItemDetail(_:)"
              ],
              "title": "Creating a selection accessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Place-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewControllerDelegate",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewController",
                "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle",
                "doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/CalloutStyle"
              ],
              "title": "Place information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MKSelectionAccessory"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemDetailViewController/title",
          "value": "MKMapItemDetailViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemDetailViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemDetailViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1mapItemDetail(_:)/title",
          "value": "mapItemDetailWithPresentationStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1mapItemDetail(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "mapItemDetailWithPresentationStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle~1CalloutStyle/title",
          "value": "MKMapItemDetailSelectionAccessoryCalloutStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle~1CalloutStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailSelectionAccessoryCalloutStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle~1CalloutStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailSelectionAccessoryCalloutStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory/title",
          "value": "MKSelectionAccessory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKSelectionAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKSelectionAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapViewDelegate~1mapView(_:selectionAccessoryFor:)/title",
          "value": "mapView:selectionAccessoryForAnnotation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapViewDelegate~1mapView(_:selectionAccessoryFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapView:selectionAccessoryForAnnotation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemDetailViewControllerDelegate/title",
          "value": "MKMapItemDetailViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemDetailViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemDetailViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle/title",
          "value": "MKMapItemDetailSelectionAccessoryPresentationStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailSelectionAccessoryPresentationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapItemDetailSelectionAccessoryPresentationStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkselectionaccessory"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkselectionaccessory"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
