{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nslayoutmanager/layoutmanagerownsfirstresponder(in:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nslayoutmanager/layoutmanagerownsfirstresponder(in:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSLayoutManager"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:objc(cs)NSLayoutManager(im)layoutManagerOwnsFirstResponderInWindow:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutManagerOwnsFirstResponder","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"layoutManagerOwnsFirstResponderInWindow:","kind":"identifier"}],"platforms":[{"deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"extendedModule":"AppKit","title":"layoutManagerOwnsFirstResponder(in:)","modules":[{"name":"AppKit"}]},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/layoutManagerOwnsFirstResponder(in:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates whether the first responder in the specified window is a text view for the layout manager."}],"sections":[],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/firstTextView","doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/textViewForBeginningOfSelection"],"anchor":"Managing-the-responder-chain","title":"Managing the responder chain"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutManagerOwnsFirstResponder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"window","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The window whose first responder is tested."}],"type":"paragraph"}],"name":"window"}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":""},{"identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true,"type":"reference"},{"text":" if the first responder in ","type":"text"},{"code":"window","type":"codeVoice"},{"text":" is a text view associated with the receiver; otherwise, ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/false","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSLayoutManager":{"navigatorTitle":[{"text":"NSLayoutManager","kind":"identifier"}],"title":"NSLayoutManager","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSLayoutManager","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSLayoutManager","abstract":[{"text":"An object that coordinates the layout and display of text characters.","type":"text"}],"role":"symbol","url":"/documentation/appkit/nslayoutmanager","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/textViewForBeginningOfSelection":{"url":"/documentation/appkit/nslayoutmanager/textviewforbeginningofselection","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The text view that contains the first glyph in the selection."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textViewForBeginningOfSelection"},{"text":": ","kind":"text"},{"text":"NSTextView","preciseIdentifier":"c:objc(cs)NSTextView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/textViewForBeginningOfSelection","navigatorTitle":[{"text":"textViewForBeginningOfSelection","kind":"identifier"}],"title":"textViewForBeginningOfSelection"},"doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/firstTextView":{"url":"/documentation/appkit/nslayoutmanager/firsttextview","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The first text view in the layout manager’s series of text views."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstTextView"},{"text":": ","kind":"text"},{"text":"NSTextView","preciseIdentifier":"c:objc(cs)NSTextView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/firstTextView","navigatorTitle":[{"text":"firstTextView","kind":"identifier"}],"title":"firstTextView"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.apple.documentation/documentation/swift/false":{"title":"false","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/false","role":"symbol","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","url":"/documentation/swift/false"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/layoutManagerOwnsFirstResponder(in:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/layoutManagerOwnsFirstResponder(in:)","navigatorTitle":[{"kind":"identifier","text":"layoutManagerOwnsFirstResponderInWindow:"}],"url":"/documentation/appkit/nslayoutmanager/layoutmanagerownsfirstresponder(in:)","kind":"symbol","abstract":[{"type":"text","text":"Indicates whether the first responder in the specified window is a text view for the layout manager."}],"title":"layoutManagerOwnsFirstResponder(in:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"layoutManagerOwnsFirstResponder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSWindow","preciseIdentifier":"c:objc(cs)NSWindow"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"name":"macOS","beta":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"layoutManagerOwnsFirstResponderInWindow:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"layoutManagerOwnsFirstResponderInWindow:","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSLayoutManager"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Managing the responder chain","anchor":"Managing-the-responder-chain","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/firstTextView","doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/textViewForBeginningOfSelection"]}]},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"layoutManagerOwnsFirstResponderInWindow:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"window"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","op":"replace","value":{"parameters":[{"name":"window","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The window whose first responder is tested."}]}]}],"kind":"parameters"}},{"path":"/primaryContentSections/2","value":{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true},{"type":"text","text":" if the first responder in "},{"type":"codeVoice","code":"window"},{"type":"text","text":" is a text view associated with the receiver; otherwise, "},{"identifier":"doc://com.apple.documentation/documentation/swift/false","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"},"op":"replace"},{"op":"replace","value":"NSLayoutManager","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager/title"},{"op":"replace","value":[{"text":"NSLayoutManager","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager/fragments"},{"op":"replace","value":[{"text":"NSLayoutManager","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager/navigatorTitle"},{"op":"replace","value":"textViewForBeginningOfSelection","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1textViewForBeginningOfSelection/title"},{"op":"replace","value":[{"text":"textViewForBeginningOfSelection","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1textViewForBeginningOfSelection/fragments"},{"op":"replace","value":"firstTextView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1firstTextView/title"},{"op":"replace","value":[{"text":"firstTextView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1firstTextView/fragments"},{"op":"replace","value":"NSWindow","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title"},{"op":"replace","value":[{"text":"NSWindow","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments"},{"op":"replace","value":[{"text":"NSWindow","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle"},{"op":"replace","value":"layoutManagerOwnsFirstResponderInWindow:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1layoutManagerOwnsFirstResponder(in:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutManagerOwnsFirstResponderInWindow:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1layoutManagerOwnsFirstResponder(in:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}