{
  "abstract": [
    {
      "text": "Creates a web history instance to delete web-usage data associated to the",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "profile identifier you specify.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Screen-Time/documentation/ScreenTime",
        "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory/init(profileIdentifier:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)STWebHistory(im)initWithProfileIdentifier:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "profileIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)STWebHistory",
        "text": "STWebHistory"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@STWebHistoryProfileIdentifier",
        "text": "ProfileIdentifier"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "Screen Time"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithProfileIdentifier:"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(profileIdentifier:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "profileIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)STWebHistory",
              "text": "STWebHistory"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory/ProfileIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@STWebHistoryProfileIdentifier",
              "text": "ProfileIdentifier"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The identifier of the current browsing profile.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "profileIdentifier"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default value for ",
              "type": "text"
            },
            {
              "code": "profileIdentifier",
              "type": "codeVoice"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ". This identifier can be used to delete",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "browsing history for a specific profile. Using ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " will only delete web history reported",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "without a profile identifier.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Screen-Time/documentation/ScreenTime": {
      "abstract": [
        {
          "text": "Share and manage web-usage data, and observe changes made by a parent or guardian.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime",
      "kind": "symbol",
      "role": "collection",
      "title": "Screen Time",
      "type": "topic",
      "url": "/documentation/screentime"
    },
    "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory": {
      "abstract": [
        {
          "text": "The object you use to delete web-usage data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "STWebHistory"
        }
      ],
      "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "STWebHistory"
        }
      ],
      "role": "symbol",
      "title": "STWebHistory",
      "type": "topic",
      "url": "/documentation/screentime/stwebhistory"
    },
    "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory/ProfileIdentifier": {
      "abstract": [
        {
          "text": "An identifier representing a web history profile.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ProfileIdentifier"
        }
      ],
      "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory/ProfileIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ProfileIdentifier"
        }
      ],
      "role": "symbol",
      "title": "STWebHistory.ProfileIdentifier",
      "type": "topic",
      "url": "/documentation/screentime/stwebhistory/profileidentifier"
    },
    "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory/init(profileIdentifier:)": {
      "abstract": [
        {
          "text": "Creates a web history instance to delete web-usage data associated to the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "profile identifier you specify.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "profileIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)STWebHistory",
          "text": "STWebHistory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@STWebHistoryProfileIdentifier",
          "text": "ProfileIdentifier"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory/init(profileIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithProfileIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "init(profileIdentifier:)",
      "type": "topic",
      "url": "/documentation/screentime/stwebhistory/init(profileidentifier:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithProfileIdentifier:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithProfileIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Screen-Time/documentation/ScreenTime",
                "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithProfileIdentifier:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory/ProfileIdentifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@STWebHistoryProfileIdentifier",
                    "text": "STWebHistoryProfileIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "profileIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The identifier of the current browsing profile.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "profileIdentifier"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory/title",
          "value": "STWebHistory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "STWebHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "STWebHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory~1init(profileIdentifier:)/title",
          "value": "initWithProfileIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory~1init(profileIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithProfileIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory~1ProfileIdentifier/title",
          "value": "STWebHistoryProfileIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory~1ProfileIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "STWebHistoryProfileIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory~1ProfileIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "STWebHistoryProfileIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/screentime/stwebhistory/init(profileidentifier:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/screentime/stwebhistory/init(profileidentifier:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
