{
  "abstract": [
    {
      "text": "Presents a user interface for adding multiple passes at once.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/addPasses(_:withCompletionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKPassLibrary(im)addPasses:withCompletionHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "addPasses"
      },
      {
        "kind": "text",
        "text": "(["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)PKPass",
        "text": "PKPass"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "withCompletionHandler"
      },
      {
        "kind": "text",
        "text": ": (("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@PKPassLibraryAddPassesStatus",
        "text": "PKPassLibraryAddPassesStatus"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")?)"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "addPasses:withCompletionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "addPasses(_:withCompletionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "addPasses"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "passes"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPass",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PKPass",
              "text": "PKPass"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "withCompletionHandler"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "completion"
            },
            {
              "kind": "text",
              "text": ": (("
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PKPassLibraryAddPassesStatus",
              "text": "PKPassLibraryAddPassesStatus"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")? = nil)"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "addPasses"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "passes"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPass",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PKPass",
              "text": "PKPass"
            },
            {
              "kind": "text",
              "text": "]) "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PKPassLibraryAddPassesStatus",
              "text": "PKPassLibraryAddPassesStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The passes to add.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "passes"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The completion handler that PassKit calls after the user selects an action. This handler takes the following parameter:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "A  ",
                            "type": "text"
                          },
                          {
                            "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus",
                            "isActive": true,
                            "type": "reference"
                          },
                          {
                            "text": " value that indicates whether PassKit adds the passes. If the user selects to review the passes, PassKit sets the status to ",
                            "type": "text"
                          },
                          {
                            "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus/shouldReviewPasses",
                            "isActive": true,
                            "type": "reference"
                          },
                          {
                            "text": ". In this case, you must present an instance of ",
                            "type": "text"
                          },
                          {
                            "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPassesViewController",
                            "isActive": true,
                            "type": "reference"
                          },
                          {
                            "text": " to let the user review and add the passes.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "code": "status",
                        "type": "codeVoice"
                      }
                    ]
                  }
                }
              ],
              "type": "termList"
            }
          ],
          "name": "completion"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method whenever the user initiates an action that generates a single pass (like purchasing a concert ticket) or multiple passes (like checking into a multiconnection flight). The user receives a prompt to confirm the overall action or to review the passes individually. If you want to force the user to review individual passes visually before adding them, use an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPassesViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPassesViewController": {
      "abstract": [
        {
          "text": "Lets your app show a pass and prompt the user to add that pass to the pass library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPassesViewController"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPassesViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPassesViewController"
        }
      ],
      "role": "symbol",
      "title": "PKAddPassesViewController",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpassesviewcontroller"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPass": {
      "abstract": [
        {
          "text": "An object that represents a single pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPass"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPass"
        }
      ],
      "role": "symbol",
      "title": "PKPass",
      "type": "topic",
      "url": "/documentation/passkit/pkpass"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary": {
      "abstract": [
        {
          "text": "Provides an interface to the user’s library of passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPassLibrary"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibrary"
        }
      ],
      "role": "symbol",
      "title": "PKPassLibrary",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/addPasses(_:withCompletionHandler:)": {
      "abstract": [
        {
          "text": "Presents a user interface for adding multiple passes at once.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addPasses"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPass",
          "text": "PKPass"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "withCompletionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKPassLibraryAddPassesStatus",
          "text": "PKPassLibraryAddPassesStatus"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/addPasses(_:withCompletionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addPasses:withCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "addPasses(_:withCompletionHandler:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/addpasses(_:withcompletionhandler:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/canAddFelicaPass()": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the library can add FeliCa™ passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canAddFelicaPass"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/canAddFelicaPass()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canAddFelicaPass"
        }
      ],
      "role": "symbol",
      "title": "canAddFelicaPass()",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/canaddfelicapass()"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/canAddSecureElementPass(primaryAccountIdentifier:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether PassKit can add a Secure Element pass for the specified account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canAddSecureElementPass"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "primaryAccountIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/canAddSecureElementPass(primaryAccountIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canAddSecureElementPassWithPrimaryAccountIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "canAddSecureElementPass(primaryAccountIdentifier:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/canaddsecureelementpass(primaryaccountidentifier:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus": {
      "abstract": [
        {
          "text": "Statuses that PassKit uses when it adds passes to the pass library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPassLibraryAddPassesStatus"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryAddPassesStatus"
        }
      ],
      "role": "symbol",
      "title": "PKPassLibraryAddPassesStatus",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibraryaddpassesstatus"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus/shouldReviewPasses": {
      "abstract": [
        {
          "text": "A status that occurs when the app prompts the user to review the passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldReviewPasses"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus/shouldReviewPasses",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryShouldReviewPasses"
        }
      ],
      "role": "symbol",
      "title": "PKPassLibraryAddPassesStatus.shouldReviewPasses",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibraryaddpassesstatus/shouldreviewpasses"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Adding-passes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/canAddSecureElementPass(primaryAccountIdentifier:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/canAddFelicaPass()",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus"
      ],
      "title": "Adding passes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "addPasses:withCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addPasses:withCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Adding-passes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/canAddSecureElementPass(primaryAccountIdentifier:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/canAddFelicaPass()",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus"
              ],
              "title": "Adding passes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "addPasses:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<PKPass *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "passes"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "withCompletionHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@PKPassLibraryAddPassesStatus",
                    "text": "PKPassLibraryAddPassesStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "status"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completion"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The passes to add.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "passes"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The completion handler that PassKit calls after the user selects an action. This handler takes the following parameter:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "A  ",
                                  "type": "text"
                                },
                                {
                                  "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus",
                                  "isActive": true,
                                  "type": "reference"
                                },
                                {
                                  "text": " value that indicates whether PassKit adds the passes. If the user selects to review the passes, PassKit sets the status to ",
                                  "type": "text"
                                },
                                {
                                  "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus/shouldReviewPasses",
                                  "isActive": true,
                                  "type": "reference"
                                },
                                {
                                  "text": ". In this case, you must present an instance of ",
                                  "type": "text"
                                },
                                {
                                  "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPassesViewController",
                                  "isActive": true,
                                  "type": "reference"
                                },
                                {
                                  "text": " to let the user review and add the passes.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "code": "status",
                              "type": "codeVoice"
                            }
                          ]
                        }
                      }
                    ],
                    "type": "termList"
                  }
                ],
                "name": "completion"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryAddPassesStatus~1shouldReviewPasses/title",
          "value": "PKPassLibraryShouldReviewPasses"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryAddPassesStatus~1shouldReviewPasses/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryShouldReviewPasses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary/title",
          "value": "PKPassLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPass/title",
          "value": "PKPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1canAddSecureElementPass(primaryAccountIdentifier:)/title",
          "value": "canAddSecureElementPassWithPrimaryAccountIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1canAddSecureElementPass(primaryAccountIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canAddSecureElementPassWithPrimaryAccountIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1canAddFelicaPass()/title",
          "value": "canAddFelicaPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1canAddFelicaPass()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canAddFelicaPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryAddPassesStatus/title",
          "value": "PKPassLibraryAddPassesStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryAddPassesStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryAddPassesStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryAddPassesStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryAddPassesStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1addPasses(_:withCompletionHandler:)/title",
          "value": "addPasses:withCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1addPasses(_:withCompletionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addPasses:withCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassesViewController/title",
          "value": "PKAddPassesViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassesViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPassesViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassesViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPassesViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpasslibrary/addpasses(_:withcompletionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpasslibrary/addpasses(_:withcompletionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
