{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes(withReaderIdentifier:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKPassLibrary(im)passesWithReaderIdentifier:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "passes"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "withReaderIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sh",
        "text": "Set"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)PKSecureElementPass",
        "text": "PKSecureElementPass"
      },
      {
        "kind": "text",
        "text": ">"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "passesWithReaderIdentifier:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "passes(withReaderIdentifier:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "passes"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "withReaderIdentifier"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "readerIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sh",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sh",
              "text": "Set"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PKSecureElementPass",
              "text": "PKSecureElementPass"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary": {
      "abstract": [
        {
          "text": "Provides an interface to the user’s library of passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPassLibrary"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibrary"
        }
      ],
      "role": "symbol",
      "title": "PKPassLibrary",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes(withReaderIdentifier:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withReaderIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKSecureElementPass",
          "text": "PKSecureElementPass"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes(withReaderIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "passesWithReaderIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "passes(withReaderIdentifier:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/passes(withreaderidentifier:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass": {
      "abstract": [
        {
          "text": "A pass with a credential that the device stores in a certified payment information chip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKSecureElementPass"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKSecureElementPass"
        }
      ],
      "role": "symbol",
      "title": "PKSecureElementPass",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "doc://com.externally.resolved.symbol/s:Sh": {
      "abstract": [
        {
          "text": "An unordered collection of unique elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sh",
      "kind": "symbol",
      "role": "symbol",
      "title": "Set",
      "type": "topic",
      "url": "/documentation/Swift/Set"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "passesWithReaderIdentifier:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "passesWithReaderIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSSet",
                    "text": "NSSet<PKSecureElementPass *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "passesWithReaderIdentifier:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "readerIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1passes(withReaderIdentifier:)/title",
          "value": "passesWithReaderIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1passes(withReaderIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "passesWithReaderIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass/title",
          "value": "PKSecureElementPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary/title",
          "value": "PKPassLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibrary"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpasslibrary/passes(withreaderidentifier:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpasslibrary/passes(withreaderidentifier:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
