{
  "abstract": [
    {
      "text": "The Secure Element passes that PassKit stores on paired devices.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/remoteSecureElementPasses"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKPassLibrary(py)remoteSecureElementPasses",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "remoteSecureElementPasses"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)PKSecureElementPass",
        "text": "PKSecureElementPass"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "remoteSecureElementPasses"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "remoteSecureElementPasses"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "remoteSecureElementPasses"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PKSecureElementPass",
              "text": "PKSecureElementPass"
            },
            {
              "kind": "text",
              "text": "] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This is an array that contains the Secure Element passes from all of the device’s remote paired devices, such as an Apple Watch.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary": {
      "abstract": [
        {
          "text": "Provides an interface to the user’s library of passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPassLibrary"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibrary"
        }
      ],
      "role": "symbol",
      "title": "PKPassLibrary",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/containsPass(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the user’s pass library contains the specified pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containsPass"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPass",
          "text": "PKPass"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/containsPass(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "containsPass:"
        }
      ],
      "role": "symbol",
      "title": "containsPass(_:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/containspass(_:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isPassLibraryAvailable()": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the pass library is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPassLibraryAvailable"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isPassLibraryAvailable()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isPassLibraryAvailable"
        }
      ],
      "role": "symbol",
      "title": "isPassLibraryAvailable()",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/ispasslibraryavailable()"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/pass(withPassTypeIdentifier:serialNumber:)": {
      "abstract": [
        {
          "text": "Returns the pass with the specified pass type identifier and serial number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pass"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withPassTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "serialNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPass",
          "text": "PKPass"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/pass(withPassTypeIdentifier:serialNumber:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "passWithPassTypeIdentifier:serialNumber:"
        }
      ],
      "role": "symbol",
      "title": "pass(withPassTypeIdentifier:serialNumber:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/pass(withpasstypeidentifier:serialnumber:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes()": {
      "abstract": [
        {
          "text": "Returns the passes in the user’s pass library that the app can access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passes"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPass",
          "text": "PKPass"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "passes"
        }
      ],
      "role": "symbol",
      "title": "passes()",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/passes()"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes(of:)": {
      "abstract": [
        {
          "text": "Returns the passes of the specified pass type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKPassType",
          "text": "PKPassType"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPass",
          "text": "PKPass"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes(of:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "passesOfType:"
        }
      ],
      "role": "symbol",
      "title": "passes(of:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/passes(of:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/remoteSecureElementPasses": {
      "abstract": [
        {
          "text": "The Secure Element passes that PassKit stores on paired devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remoteSecureElementPasses"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKSecureElementPass",
          "text": "PKSecureElementPass"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/remoteSecureElementPasses",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "remoteSecureElementPasses"
        }
      ],
      "role": "symbol",
      "title": "remoteSecureElementPasses",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/remotesecureelementpasses"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/serviceProviderData(for:completion:)": {
      "abstract": [
        {
          "text": "Calls a completion handler that returns the custom data for a Secure Element pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceProviderData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKSecureElementPass",
          "text": "PKSecureElementPass"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/serviceProviderData(for:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serviceProviderDataForSecureElementPass:completion:"
        }
      ],
      "role": "symbol",
      "title": "serviceProviderData(for:completion:)",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibrary/serviceproviderdata(for:completion:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass": {
      "abstract": [
        {
          "text": "A pass with a credential that the device stores in a certified payment information chip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKSecureElementPass"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKSecureElementPass"
        }
      ],
      "role": "symbol",
      "title": "PKSecureElementPass",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-passes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isPassLibraryAvailable()",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes()",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes(of:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/pass(withPassTypeIdentifier:serialNumber:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/containsPass(_:)",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/serviceProviderData(for:completion:)"
      ],
      "title": "Accessing passes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "remoteSecureElementPasses"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "remoteSecureElementPasses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-passes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/isPassLibraryAvailable()",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes()",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/passes(of:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/pass(withPassTypeIdentifier:serialNumber:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/containsPass(_:)",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibrary/serviceProviderData(for:completion:)"
              ],
              "title": "Accessing passes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<PKSecureElementPass *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "remoteSecureElementPasses"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1serviceProviderData(for:completion:)/title",
          "value": "serviceProviderDataForSecureElementPass:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1serviceProviderData(for:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "serviceProviderDataForSecureElementPass:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary/title",
          "value": "PKPassLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass/title",
          "value": "PKSecureElementPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1remoteSecureElementPasses/title",
          "value": "remoteSecureElementPasses"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1remoteSecureElementPasses/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "remoteSecureElementPasses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1pass(withPassTypeIdentifier:serialNumber:)/title",
          "value": "passWithPassTypeIdentifier:serialNumber:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1pass(withPassTypeIdentifier:serialNumber:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "passWithPassTypeIdentifier:serialNumber:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1passes()/title",
          "value": "passes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1passes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "passes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1isPassLibraryAvailable()/title",
          "value": "isPassLibraryAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1isPassLibraryAvailable()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "isPassLibraryAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1containsPass(_:)/title",
          "value": "containsPass:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1containsPass(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "containsPass:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1passes(of:)/title",
          "value": "passesOfType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibrary~1passes(of:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "passesOfType:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpasslibrary/remotesecureelementpasses"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpasslibrary/remotesecureelementpasses"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
