{
  "abstract": [
    {
      "text": "The person’s phone numbers. Value is an array of labeled values with phone number values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbookui/documentation/AddressBookUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonPhoneNumbersProperty"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@ABPersonPhoneNumbersProperty",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ABPersonPhoneNumbersProperty"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Address Book UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ABPersonPhoneNumbersProperty"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "ABPersonPhoneNumbersProperty"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ABPersonPhoneNumbersProperty"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.addressbookui/documentation/AddressBookUI": {
      "abstract": [
        {
          "text": "Access users’ contacts and display them in a graphical interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book UI",
      "type": "topic",
      "url": "/documentation/addressbookui"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonBirthdayProperty": {
      "abstract": [
        {
          "text": "The person’s birthday. Value is an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsdatecomponents",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonBirthdayProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonBirthdayProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonBirthdayProperty"
        }
      ],
      "role": "symbol",
      "title": "ABPersonBirthdayProperty",
      "type": "topic",
      "url": "/documentation/addressbookui/abpersonbirthdayproperty"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonDepartmentNameProperty": {
      "abstract": [
        {
          "text": "The person’s department name. Value is an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonDepartmentNameProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonDepartmentNameProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonDepartmentNameProperty"
        }
      ],
      "role": "symbol",
      "title": "ABPersonDepartmentNameProperty",
      "type": "topic",
      "url": "/documentation/addressbookui/abpersondepartmentnameproperty"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonFamilyNameProperty": {
      "abstract": [
        {
          "text": "The person’s family name. Value is an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonFamilyNameProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonFamilyNameProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonFamilyNameProperty"
        }
      ],
      "role": "symbol",
      "title": "ABPersonFamilyNameProperty",
      "type": "topic",
      "url": "/documentation/addressbookui/abpersonfamilynameproperty"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonGivenNameProperty": {
      "abstract": [
        {
          "text": "The person’s given name. Value is an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonGivenNameProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonGivenNameProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonGivenNameProperty"
        }
      ],
      "role": "symbol",
      "title": "ABPersonGivenNameProperty",
      "type": "topic",
      "url": "/documentation/addressbookui/abpersongivennameproperty"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonJobTitleProperty": {
      "abstract": [
        {
          "text": "The person’s job title. Value is an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonJobTitleProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonJobTitleProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonJobTitleProperty"
        }
      ],
      "role": "symbol",
      "title": "ABPersonJobTitleProperty",
      "type": "topic",
      "url": "/documentation/addressbookui/abpersonjobtitleproperty"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonMiddleNameProperty": {
      "abstract": [
        {
          "text": "The person’s middle name. Value is an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonMiddleNameProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonMiddleNameProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonMiddleNameProperty"
        }
      ],
      "role": "symbol",
      "title": "ABPersonMiddleNameProperty",
      "type": "topic",
      "url": "/documentation/addressbookui/abpersonmiddlenameproperty"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonNamePrefixProperty": {
      "abstract": [
        {
          "text": "The name prefix. Value is an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonNamePrefixProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonNamePrefixProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonNamePrefixProperty"
        }
      ],
      "role": "symbol",
      "title": "ABPersonNamePrefixProperty",
      "type": "topic",
      "url": "/documentation/addressbookui/abpersonnameprefixproperty"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonNameSuffixProperty": {
      "abstract": [
        {
          "text": "The name suffix. Value is an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonNameSuffixProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonNameSuffixProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonNameSuffixProperty"
        }
      ],
      "role": "symbol",
      "title": "ABPersonNameSuffixProperty",
      "type": "topic",
      "url": "/documentation/addressbookui/abpersonnamesuffixproperty"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonNicknameProperty": {
      "abstract": [
        {
          "text": "The person’s nickname. Value is an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonNicknameProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonNicknameProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonNicknameProperty"
        }
      ],
      "role": "symbol",
      "title": "ABPersonNicknameProperty",
      "type": "topic",
      "url": "/documentation/addressbookui/abpersonnicknameproperty"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonNoteProperty": {
      "abstract": [
        {
          "text": "The note for the person. Value is an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonNoteProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonNoteProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonNoteProperty"
        }
      ],
      "role": "symbol",
      "title": "ABPersonNoteProperty",
      "type": "topic",
      "url": "/documentation/addressbookui/abpersonnoteproperty"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonOrganizationNameProperty": {
      "abstract": [
        {
          "text": "The person’s organization name. Value is an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonOrganizationNameProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonOrganizationNameProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonOrganizationNameProperty"
        }
      ],
      "role": "symbol",
      "title": "ABPersonOrganizationNameProperty",
      "type": "topic",
      "url": "/documentation/addressbookui/abpersonorganizationnameproperty"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonPhoneNumbersProperty": {
      "abstract": [
        {
          "text": "The person’s phone numbers. Value is an array of labeled values with phone number values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonPhoneNumbersProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonPhoneNumbersProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonPhoneNumbersProperty"
        }
      ],
      "role": "symbol",
      "title": "ABPersonPhoneNumbersProperty",
      "type": "topic",
      "url": "/documentation/addressbookui/abpersonphonenumbersproperty"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonPhoneticFamilyNameProperty": {
      "abstract": [
        {
          "text": "The person’s phonetic family name. Value is an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonPhoneticFamilyNameProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonPhoneticFamilyNameProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonPhoneticFamilyNameProperty"
        }
      ],
      "role": "symbol",
      "title": "ABPersonPhoneticFamilyNameProperty",
      "type": "topic",
      "url": "/documentation/addressbookui/abpersonphoneticfamilynameproperty"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonPhoneticGivenNameProperty": {
      "abstract": [
        {
          "text": "The person’s phonetic given name. Value is an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonPhoneticGivenNameProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonPhoneticGivenNameProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonPhoneticGivenNameProperty"
        }
      ],
      "role": "symbol",
      "title": "ABPersonPhoneticGivenNameProperty",
      "type": "topic",
      "url": "/documentation/addressbookui/abpersonphoneticgivennameproperty"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonPhoneticMiddleNameProperty": {
      "abstract": [
        {
          "text": "The person’s phonetic middle name. Value is an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonPhoneticMiddleNameProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonPhoneticMiddleNameProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonPhoneticMiddleNameProperty"
        }
      ],
      "role": "symbol",
      "title": "ABPersonPhoneticMiddleNameProperty",
      "type": "topic",
      "url": "/documentation/addressbookui/abpersonphoneticmiddlenameproperty"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonPreviousFamilyNameProperty": {
      "abstract": [
        {
          "text": "The person’s previous family name. Value is an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPersonPreviousFamilyNameProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonPreviousFamilyNameProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPersonPreviousFamilyNameProperty"
        }
      ],
      "role": "symbol",
      "title": "ABPersonPreviousFamilyNameProperty",
      "type": "topic",
      "url": "/documentation/addressbookui/abpersonpreviousfamilynameproperty"
    },
    "doc://com.apple.documentation/documentation/foundation/nsdatecomponents": {
      "abstract": [
        {
          "text": "An object that specifies a date or time in terms of calendar units that bridges to ; use  when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSDateComponents"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsdatecomponents",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDateComponents",
      "type": "topic",
      "url": "/documentation/foundation/nsdatecomponents"
    },
    "doc://com.apple.documentation/documentation/foundation/nsstring": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonNamePrefixProperty",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonGivenNameProperty",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonMiddleNameProperty",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonFamilyNameProperty",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonNameSuffixProperty",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonPreviousFamilyNameProperty",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonNicknameProperty",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonPhoneticGivenNameProperty",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonPhoneticMiddleNameProperty",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonPhoneticFamilyNameProperty",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonOrganizationNameProperty",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonDepartmentNameProperty",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonJobTitleProperty",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonBirthdayProperty",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonNoteProperty"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ABPersonPhoneNumbersProperty"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonPhoneNumbersProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbookui/documentation/AddressBookUI"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonNamePrefixProperty",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonGivenNameProperty",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonMiddleNameProperty",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonFamilyNameProperty",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonNameSuffixProperty",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonPreviousFamilyNameProperty",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonNicknameProperty",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonPhoneticGivenNameProperty",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonPhoneticMiddleNameProperty",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonPhoneticFamilyNameProperty",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonOrganizationNameProperty",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonDepartmentNameProperty",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonJobTitleProperty",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonBirthdayProperty",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPersonNoteProperty"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ABPersonPhoneNumbersProperty"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonPhoneticGivenNameProperty/title",
          "value": "ABPersonPhoneticGivenNameProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonPhoneticGivenNameProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonPhoneticGivenNameProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonGivenNameProperty/title",
          "value": "ABPersonGivenNameProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonGivenNameProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonGivenNameProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonDepartmentNameProperty/title",
          "value": "ABPersonDepartmentNameProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonDepartmentNameProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonDepartmentNameProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonPhoneticFamilyNameProperty/title",
          "value": "ABPersonPhoneticFamilyNameProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonPhoneticFamilyNameProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonPhoneticFamilyNameProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonJobTitleProperty/title",
          "value": "ABPersonJobTitleProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonJobTitleProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonJobTitleProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonMiddleNameProperty/title",
          "value": "ABPersonMiddleNameProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonMiddleNameProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonMiddleNameProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonPhoneticMiddleNameProperty/title",
          "value": "ABPersonPhoneticMiddleNameProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonPhoneticMiddleNameProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonPhoneticMiddleNameProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonBirthdayProperty/title",
          "value": "ABPersonBirthdayProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonBirthdayProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonBirthdayProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsstring/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsdatecomponents/abstract",
          "value": [
            {
              "text": "An object that specifies a date or time in terms of units (such as year, month, day, hour, and minute) to be evaluated in a calendar system and time zone.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonPhoneNumbersProperty/title",
          "value": "ABPersonPhoneNumbersProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonPhoneNumbersProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonPhoneNumbersProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonNamePrefixProperty/title",
          "value": "ABPersonNamePrefixProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonNamePrefixProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonNamePrefixProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonNoteProperty/title",
          "value": "ABPersonNoteProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonNoteProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonNoteProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonNameSuffixProperty/title",
          "value": "ABPersonNameSuffixProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonNameSuffixProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonNameSuffixProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonNicknameProperty/title",
          "value": "ABPersonNicknameProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonNicknameProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonNicknameProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonFamilyNameProperty/title",
          "value": "ABPersonFamilyNameProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonFamilyNameProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonFamilyNameProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonOrganizationNameProperty/title",
          "value": "ABPersonOrganizationNameProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonOrganizationNameProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonOrganizationNameProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonPreviousFamilyNameProperty/title",
          "value": "ABPersonPreviousFamilyNameProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPersonPreviousFamilyNameProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPersonPreviousFamilyNameProperty"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbookui/abpersonphonenumbersproperty"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbookui/abpersonphonenumbersproperty"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
