{
  "abstract": [
    {
      "text": "A notification that CloudKit generates when the contents of a record zone change.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/recordZone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CKNotificationType@CKNotificationTypeRecordZone",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "recordZone"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CKNotificationTypeRecordZone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CKNotification.NotificationType.recordZone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "recordZone"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification": {
      "abstract": [
        {
          "text": "The abstract base class for CloudKit notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKNotification"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKNotification"
        }
      ],
      "role": "symbol",
      "title": "CKNotification",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate the type of event that generates the push notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NotificationType"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NotificationType"
        }
      ],
      "role": "symbol",
      "title": "CKNotification.NotificationType",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/notificationtype-swift.enum"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/database": {
      "abstract": [
        {
          "text": "A notification that CloudKit generates when the contents of a database change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "database"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/database",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKNotificationTypeDatabase"
        }
      ],
      "role": "symbol",
      "title": "CKNotification.NotificationType.database",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/notificationtype-swift.enum/database"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/query": {
      "abstract": [
        {
          "text": "A notification that CloudKit generates from a query subscription’s predicate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "query"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/query",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKNotificationTypeQuery"
        }
      ],
      "role": "symbol",
      "title": "CKNotification.NotificationType.query",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/notificationtype-swift.enum/query"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/readNotification": {
      "abstract": [
        {
          "text": "A notification that your app marks as read.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readNotification"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/readNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKNotificationTypeReadNotification"
        }
      ],
      "role": "symbol",
      "title": "CKNotification.NotificationType.readNotification",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/notificationtype-swift.enum/readnotification"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/recordZone": {
      "abstract": [
        {
          "text": "A notification that CloudKit generates when the contents of a record zone change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordZone"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/recordZone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKNotificationTypeRecordZone"
        }
      ],
      "role": "symbol",
      "title": "CKNotification.NotificationType.recordZone",
      "type": "topic",
      "url": "/documentation/cloudkit/cknotification/notificationtype-swift.enum/recordzone"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Notification-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/query",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/database",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/readNotification"
      ],
      "title": "Notification Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CKNotificationTypeRecordZone"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationTypeRecordZone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Notification-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/query",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/database",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKNotification/NotificationType-swift.enum/readNotification"
              ],
              "title": "Notification Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CKNotificationTypeRecordZone"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification/title",
          "value": "CKNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum/title",
          "value": "CKNotificationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum~1readNotification/title",
          "value": "CKNotificationTypeReadNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum~1readNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationTypeReadNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum~1recordZone/title",
          "value": "CKNotificationTypeRecordZone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum~1recordZone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationTypeRecordZone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum~1database/title",
          "value": "CKNotificationTypeDatabase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum~1database/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationTypeDatabase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum~1query/title",
          "value": "CKNotificationTypeQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKNotification~1NotificationType-swift.enum~1query/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKNotificationTypeQuery"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/cknotification/notificationtype-swift.enum/recordzone"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/cknotification/notificationtype-swift.enum/recordzone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
