{
  "abstract": [
    {
      "text": "Constants that identify body height estimation techniques.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Vision",
    "externalID": "c:@E@VNHumanBodyPose3DObservationHeightEstimation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HeightEstimation"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HeightEstimation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "VNHumanBodyPose3DObservation.HeightEstimation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HeightEstimation"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation": {
      "abstract": [
        {
          "text": "An observation that provides the 3D body points the request recognizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNHumanBodyPose3DObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanBodyPose3DObservation"
        }
      ],
      "role": "symbol",
      "title": "VNHumanBodyPose3DObservation",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodypose3dobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum": {
      "abstract": [
        {
          "text": "Constants that identify body height estimation techniques.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HeightEstimation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HeightEstimation"
        }
      ],
      "role": "symbol",
      "title": "VNHumanBodyPose3DObservation.HeightEstimation",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodypose3dobservation/heightestimation-swift.enum"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodypose3dobservation/heightestimation-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/measured": {
      "abstract": [
        {
          "text": "A technique that uses LiDAR depth data to measure body height, in meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "measured"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/measured",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanBodyPose3DObservationHeightEstimationMeasured"
        }
      ],
      "role": "symbol",
      "title": "VNHumanBodyPose3DObservation.HeightEstimation.measured",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodypose3dobservation/heightestimation-swift.enum/measured"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/reference": {
      "abstract": [
        {
          "text": "A technique that uses a reference height.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reference"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/reference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNHumanBodyPose3DObservationHeightEstimationReference"
        }
      ],
      "role": "symbol",
      "title": "VNHumanBodyPose3DObservation.HeightEstimation.reference",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodypose3dobservation/heightestimation-swift.enum/reference"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/bodyHeight": {
      "abstract": [
        {
          "text": "The estimated human body height, in meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bodyHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/bodyHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bodyHeight"
        }
      ],
      "role": "symbol",
      "title": "bodyHeight",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodypose3dobservation/bodyheight"
    },
    "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/heightEstimation-swift.property": {
      "abstract": [
        {
          "text": "The technique the framework uses to estimate body height.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heightEstimation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNHumanBodyPose3DObservation",
          "text": "VNHumanBodyPose3DObservation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@VNHumanBodyPose3DObservationHeightEstimation",
          "text": "HeightEstimation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/heightEstimation-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "heightEstimation"
        }
      ],
      "role": "symbol",
      "title": "heightEstimation",
      "type": "topic",
      "url": "/documentation/vision/vnhumanbodypose3dobservation/heightestimation-swift.property"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Body-Height",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/heightEstimation-swift.property",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/bodyHeight"
      ],
      "title": "Getting the Body Height"
    }
  ],
  "topicSections": [
    {
      "anchor": "Techniques",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/measured",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/reference",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/measured",
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/reference"
      ],
      "title": "Techniques"
    },
    {
      "anchor": "Creating-a-Technique",
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/init(rawValue:)"
      ],
      "title": "Creating a Technique"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNHumanBodyPose3DObservationHeightEstimation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservationHeightEstimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservationHeightEstimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Techniques",
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/measured",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/reference",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/measured",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/HeightEstimation-swift.enum/reference"
              ],
              "title": "Techniques"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Body-Height",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/heightEstimation-swift.property",
                "doc://com.apple.vision/documentation/Vision/VNHumanBodyPose3DObservation/bodyHeight"
              ],
              "title": "Getting the Body Height"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VNHumanBodyPose3DObservationHeightEstimation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1HeightEstimation-swift.enum~1reference/title",
          "value": "VNHumanBodyPose3DObservationHeightEstimationReference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1HeightEstimation-swift.enum~1reference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservationHeightEstimationReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation/title",
          "value": "VNHumanBodyPose3DObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1HeightEstimation-swift.enum~1measured/title",
          "value": "VNHumanBodyPose3DObservationHeightEstimationMeasured"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1HeightEstimation-swift.enum~1measured/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservationHeightEstimationMeasured"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1heightEstimation-swift.property/title",
          "value": "heightEstimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1heightEstimation-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "heightEstimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1HeightEstimation-swift.enum/title",
          "value": "VNHumanBodyPose3DObservationHeightEstimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1HeightEstimation-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservationHeightEstimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1HeightEstimation-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNHumanBodyPose3DObservationHeightEstimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1bodyHeight/title",
          "value": "bodyHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNHumanBodyPose3DObservation~1bodyHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bodyHeight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnhumanbodypose3dobservation/heightestimation-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnhumanbodypose3dobservation/heightestimation-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
