{
  "abstract": [
    {
      "text": "The positive intersection over union (IOU).",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/minimumIOUForObjectPresence"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLCYOLOLossDescriptor(py)minimumIOUForObjectPresence",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "minimumIOUForObjectPresence"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "minimumIOUForObjectPresence"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "minimumIOUForObjectPresence"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "minimumIOUForObjectPresence"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the prediction IOU with groundTruth is higher than this value, consider this is a confident object presence.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The default value is ",
              "type": "text"
            },
            {
              "code": "0.7",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor": {
      "abstract": [
        {
          "text": "The configuration object you use to create the YOLO loss layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCYOLOLossDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCYOLOLossDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MLCYOLOLossDescriptor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/anchorBoxCount": {
      "abstract": [
        {
          "text": "The number of anchor boxes you use to detect an object in each grid cell.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anchorBoxCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/anchorBoxCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "anchorBoxCount"
        }
      ],
      "role": "symbol",
      "title": "anchorBoxCount",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/anchorboxcount"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/anchorBoxes": {
      "abstract": [
        {
          "text": "Data that contains the width and height for all the anchor boxes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anchorBoxes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/anchorBoxes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "anchorBoxes"
        }
      ],
      "role": "symbol",
      "title": "anchorBoxes",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/anchorboxes"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/maximumIOUForObjectAbsence": {
      "abstract": [
        {
          "text": "The negative intersection over union (IOU).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumIOUForObjectAbsence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/maximumIOUForObjectAbsence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumIOUForObjectAbsence"
        }
      ],
      "role": "symbol",
      "title": "maximumIOUForObjectAbsence",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/maximumiouforobjectabsence"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/minimumIOUForObjectPresence": {
      "abstract": [
        {
          "text": "The positive intersection over union (IOU).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumIOUForObjectPresence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/minimumIOUForObjectPresence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumIOUForObjectPresence"
        }
      ],
      "role": "symbol",
      "title": "minimumIOUForObjectPresence",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/minimumiouforobjectpresence"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleClassLoss": {
      "abstract": [
        {
          "text": "The scale factor you use for loss when there are no object classes, and for loss gradient.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleClassLoss"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleClassLoss",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleClassLoss"
        }
      ],
      "role": "symbol",
      "title": "scaleClassLoss",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/scaleclassloss"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleNoObjectConfidenceLoss": {
      "abstract": [
        {
          "text": "The scale factor you use for no object confidence loss and loss gradient.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleNoObjectConfidenceLoss"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleNoObjectConfidenceLoss",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleNoObjectConfidenceLoss"
        }
      ],
      "role": "symbol",
      "title": "scaleNoObjectConfidenceLoss",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/scalenoobjectconfidenceloss"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleObjectConfidenceLoss": {
      "abstract": [
        {
          "text": "The scale factor you use for object confidence loss and loss gradient.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleObjectConfidenceLoss"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleObjectConfidenceLoss",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleObjectConfidenceLoss"
        }
      ],
      "role": "symbol",
      "title": "scaleObjectConfidenceLoss",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/scaleobjectconfidenceloss"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleSpatialPositionLoss": {
      "abstract": [
        {
          "text": "The scale factor you use for spatial position loss and loss gradient.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleSpatialPositionLoss"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleSpatialPositionLoss",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleSpatialPositionLoss"
        }
      ],
      "role": "symbol",
      "title": "scaleSpatialPositionLoss",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/scalespatialpositionloss"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleSpatialSizeLoss": {
      "abstract": [
        {
          "text": "The scale factor you use for spatial size loss and loss gradient.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleSpatialSizeLoss"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleSpatialSizeLoss",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleSpatialSizeLoss"
        }
      ],
      "role": "symbol",
      "title": "scaleSpatialSizeLoss",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/scalespatialsizeloss"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/shouldRescore": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether the layer scales the object confidence loss by the intersection over union (IOU) overlap.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldRescore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/shouldRescore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldRescore"
        }
      ],
      "role": "symbol",
      "title": "shouldRescore",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcyololossdescriptor/shouldrescore"
    },
    "doc://com.externally.resolved.symbol/s:Sf": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-YOLO-Loss-Descriptors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/anchorBoxCount",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/anchorBoxes",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/maximumIOUForObjectAbsence",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleClassLoss",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleObjectConfidenceLoss",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleNoObjectConfidenceLoss",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleSpatialPositionLoss",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleSpatialSizeLoss",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/shouldRescore"
      ],
      "title": "Inspecting YOLO Loss Descriptors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.3",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "minimumIOUForObjectPresence"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumIOUForObjectPresence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-YOLO-Loss-Descriptors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/anchorBoxCount",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/anchorBoxes",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/maximumIOUForObjectAbsence",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleClassLoss",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleObjectConfidenceLoss",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleNoObjectConfidenceLoss",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleSpatialPositionLoss",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/scaleSpatialSizeLoss",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCYOLOLossDescriptor/shouldRescore"
              ],
              "title": "Inspecting YOLO Loss Descriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readwrite"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:f",
                    "text": "float"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "minimumIOUForObjectPresence"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1shouldRescore/title",
          "value": "shouldRescore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1shouldRescore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldRescore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleSpatialSizeLoss/title",
          "value": "scaleSpatialSizeLoss"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleSpatialSizeLoss/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaleSpatialSizeLoss"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1anchorBoxCount/title",
          "value": "anchorBoxCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1anchorBoxCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "anchorBoxCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleNoObjectConfidenceLoss/title",
          "value": "scaleNoObjectConfidenceLoss"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleNoObjectConfidenceLoss/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaleNoObjectConfidenceLoss"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1anchorBoxes/title",
          "value": "anchorBoxes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1anchorBoxes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "anchorBoxes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleObjectConfidenceLoss/title",
          "value": "scaleObjectConfidenceLoss"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleObjectConfidenceLoss/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaleObjectConfidenceLoss"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1minimumIOUForObjectPresence/title",
          "value": "minimumIOUForObjectPresence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1minimumIOUForObjectPresence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumIOUForObjectPresence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleClassLoss/title",
          "value": "scaleClassLoss"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleClassLoss/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaleClassLoss"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor/title",
          "value": "MLCYOLOLossDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCYOLOLossDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCYOLOLossDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1maximumIOUForObjectAbsence/title",
          "value": "maximumIOUForObjectAbsence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1maximumIOUForObjectAbsence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumIOUForObjectAbsence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleSpatialPositionLoss/title",
          "value": "scaleSpatialPositionLoss"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCYOLOLossDescriptor~1scaleSpatialPositionLoss/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaleSpatialPositionLoss"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcyololossdescriptor/minimumiouforobjectpresence"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcyololossdescriptor/minimumiouforobjectpresence"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
