{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.executionpolicy/documentation/ExecutionPolicy",
        "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperTool"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperTool/authorizationStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)EPDeveloperTool(py)authorizationStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "authorizationStatus"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@EPDeveloperToolStatus",
        "text": "EPDeveloperToolStatus"
      }
    ],
    "modules": [
      {
        "name": "Execution Policy"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "authorizationStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "authorizationStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "authorizationStatus"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@EPDeveloperToolStatus",
              "text": "EPDeveloperToolStatus"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy": {
      "abstract": [
        {
          "text": "Provide functionality so developer tools can manage execution policy exceptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy",
      "kind": "symbol",
      "role": "collection",
      "title": "Execution Policy",
      "type": "topic",
      "url": "/documentation/executionpolicy"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperTool": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EPDeveloperTool"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperTool",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EPDeveloperTool"
        }
      ],
      "role": "symbol",
      "title": "EPDeveloperTool",
      "type": "topic",
      "url": "/documentation/executionpolicy/epdevelopertool"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperTool/authorizationStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EPDeveloperToolStatus",
          "text": "EPDeveloperToolStatus"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperTool/authorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "authorizationStatus",
      "type": "topic",
      "url": "/documentation/executionpolicy/epdevelopertool/authorizationstatus"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EPDeveloperToolStatus"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EPDeveloperToolStatus"
        }
      ],
      "role": "symbol",
      "title": "EPDeveloperToolStatus",
      "type": "topic",
      "url": "/documentation/executionpolicy/epdevelopertoolstatus"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "authorizationStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "authorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.executionpolicy/documentation/ExecutionPolicy",
                "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperTool"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPDeveloperToolStatus",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@EPDeveloperToolStatus",
                    "text": "EPDeveloperToolStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "authorizationStatus"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperTool/title",
          "value": "EPDeveloperTool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperTool/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EPDeveloperTool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperTool/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EPDeveloperTool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperTool~1authorizationStatus/title",
          "value": "authorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperTool~1authorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "authorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperToolStatus/title",
          "value": "EPDeveloperToolStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperToolStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EPDeveloperToolStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPDeveloperToolStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EPDeveloperToolStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/executionpolicy/epdevelopertool/authorizationstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/executionpolicy/epdevelopertool/authorizationstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
