{
  "abstract": [
    {
      "text": "No border.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSBorderType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSBorderType/noBorder"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSBorderType@NSNoBorder",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "noBorder"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSNoBorder"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSBorderType.noBorder"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "noBorder"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBorderType": {
      "abstract": [
        {
          "text": "These constants specify the type of a view’s border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBorderType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBorderType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBorderType"
        }
      ],
      "role": "symbol",
      "title": "NSBorderType",
      "type": "topic",
      "url": "/documentation/appkit/nsbordertype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBorderType/bezelBorder": {
      "abstract": [
        {
          "text": "A concave border that makes the view look sunken.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bezelBorder"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBorderType/bezelBorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelBorder"
        }
      ],
      "role": "symbol",
      "title": "NSBorderType.bezelBorder",
      "type": "topic",
      "url": "/documentation/appkit/nsbordertype/bezelborder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBorderType/grooveBorder": {
      "abstract": [
        {
          "text": "A thin border that looks etched around the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "grooveBorder"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBorderType/grooveBorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGrooveBorder"
        }
      ],
      "role": "symbol",
      "title": "NSBorderType.grooveBorder",
      "type": "topic",
      "url": "/documentation/appkit/nsbordertype/grooveborder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBorderType/lineBorder": {
      "abstract": [
        {
          "text": "A black line border around the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineBorder"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBorderType/lineBorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineBorder"
        }
      ],
      "role": "symbol",
      "title": "NSBorderType.lineBorder",
      "type": "topic",
      "url": "/documentation/appkit/nsbordertype/lineborder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBorderType/noBorder": {
      "abstract": [
        {
          "text": "No border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noBorder"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBorderType/noBorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNoBorder"
        }
      ],
      "role": "symbol",
      "title": "NSBorderType.noBorder",
      "type": "topic",
      "url": "/documentation/appkit/nsbordertype/noborder"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBorderType/bezelBorder",
        "doc://com.apple.appkit/documentation/AppKit/NSBorderType/grooveBorder",
        "doc://com.apple.appkit/documentation/AppKit/NSBorderType/lineBorder"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSNoBorder"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNoBorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSBorderType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBorderType/bezelBorder",
                "doc://com.apple.appkit/documentation/AppKit/NSBorderType/grooveBorder",
                "doc://com.apple.appkit/documentation/AppKit/NSBorderType/lineBorder"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSNoBorder"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBorderType~1lineBorder/title",
          "value": "NSLineBorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBorderType~1lineBorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBorderType~1noBorder/title",
          "value": "NSNoBorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBorderType~1noBorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNoBorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBorderType~1bezelBorder/title",
          "value": "NSBezelBorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBorderType~1bezelBorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelBorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBorderType~1grooveBorder/title",
          "value": "NSGrooveBorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBorderType~1grooveBorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGrooveBorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBorderType/title",
          "value": "NSBorderType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBorderType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBorderType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBorderType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBorderType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsbordertype/noborder"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsbordertype/noborder"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
