{
  "abstract": [
    {
      "text": "Returns the credential state for the given user in a completion handler.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider/getCredentialState(forUserID:completion:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ASAuthorizationAppleIDProvider(im)getCredentialStateForUserID:completion:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "getCredentialState"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "forUserID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "completion"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ASAuthorizationAppleIDProvider",
        "text": "ASAuthorizationAppleIDProvider"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@ASAuthorizationAppleIDProviderCredentialState",
        "text": "CredentialState"
      },
      {
        "kind": "text",
        "text": ", (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Authentication Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "getCredentialStateForUserID:completion:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "getCredentialState(forUserID:completion:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "getCredentialState"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "forUserID"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "userID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "completion"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ASAuthorizationAppleIDProvider",
              "text": "ASAuthorizationAppleIDProvider"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider/CredentialState",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ASAuthorizationAppleIDProviderCredentialState",
              "text": "CredentialState"
            },
            {
              "kind": "text",
              "text": ", (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "credentialState"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "forUserID"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "userID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "throws"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ASAuthorizationAppleIDProvider",
              "text": "ASAuthorizationAppleIDProvider"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider/CredentialState",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ASAuthorizationAppleIDProviderCredentialState",
              "text": "CredentialState"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An opaque string associated with the Apple ID that your app receives in the credential’s ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDCredential/user",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property after performing a successful authentication request.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "userID"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A block the method calls to report the state and an optional error condition.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "completion"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices": {
      "abstract": [
        {
          "text": "Make it easy for users to log into apps and services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Authentication Services",
      "type": "topic",
      "url": "/documentation/authenticationservices"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDCredential/user": {
      "abstract": [
        {
          "text": "An identifier for the authenticated user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "user"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDCredential/user",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "user"
        }
      ],
      "role": "symbol",
      "title": "user",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationappleidcredential/user"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider": {
      "abstract": [
        {
          "text": "A mechanism for generating requests to authenticate users based on their Apple ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAuthorizationAppleIDProvider"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationAppleIDProvider"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationAppleIDProvider",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationappleidprovider"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider/CredentialState": {
      "abstract": [
        {
          "text": "Possible values for the credential state of a user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CredentialState"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider/CredentialState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CredentialState"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationAppleIDProvider.CredentialState",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationappleidprovider/credentialstate"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider/credentialRevokedNotification": {
      "abstract": [
        {
          "text": "A notification that indicates the user’s credentials have been revoked and they should be signed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "credentialRevokedNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider/credentialRevokedNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationAppleIDProviderCredentialRevokedNotification"
        }
      ],
      "role": "symbol",
      "title": "credentialRevokedNotification",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationappleidprovider/credentialrevokednotification"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider/getCredentialState(forUserID:completion:)": {
      "abstract": [
        {
          "text": "Returns the credential state for the given user in a completion handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getCredentialState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forUserID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASAuthorizationAppleIDProvider",
          "text": "ASAuthorizationAppleIDProvider"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ASAuthorizationAppleIDProviderCredentialState",
          "text": "CredentialState"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider/getCredentialState(forUserID:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getCredentialStateForUserID:completion:"
        }
      ],
      "role": "symbol",
      "title": "getCredentialState(forUserID:completion:)",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationappleidprovider/getcredentialstate(foruserid:completion:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-State",
      "generated": true,
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider/CredentialState",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider/credentialRevokedNotification"
      ],
      "title": "Getting State"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "getCredentialStateForUserID:completion:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getCredentialStateForUserID:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-State",
              "generated": true,
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider/CredentialState",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider/credentialRevokedNotification"
              ],
              "title": "Getting State"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "getCredentialStateForUserID:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "userID"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "completion:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDProvider/CredentialState",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@ASAuthorizationAppleIDProviderCredentialState",
                    "text": "ASAuthorizationAppleIDProviderCredentialState"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "credentialState"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completion"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An opaque string associated with the Apple ID that your app receives in the credential’s ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationAppleIDCredential/user",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " property after performing a successful authentication request.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "userID"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A block the method calls to report the state and an optional error condition.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "completion"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationAppleIDProvider~1CredentialState/title",
          "value": "ASAuthorizationAppleIDProviderCredentialState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationAppleIDProvider~1CredentialState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationAppleIDProviderCredentialState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationAppleIDProvider~1CredentialState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationAppleIDProviderCredentialState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationAppleIDCredential~1user/title",
          "value": "user"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationAppleIDCredential~1user/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "user"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationAppleIDProvider~1credentialRevokedNotification/title",
          "value": "ASAuthorizationAppleIDProviderCredentialRevokedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationAppleIDProvider~1credentialRevokedNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationAppleIDProviderCredentialRevokedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationAppleIDProvider/title",
          "value": "ASAuthorizationAppleIDProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationAppleIDProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationAppleIDProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationAppleIDProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationAppleIDProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationAppleIDProvider~1getCredentialState(forUserID:completion:)/title",
          "value": "getCredentialStateForUserID:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationAppleIDProvider~1getCredentialState(forUserID:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getCredentialStateForUserID:completion:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/authenticationservices/asauthorizationappleidprovider/getcredentialstate(foruserid:completion:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/authenticationservices/asauthorizationappleidprovider/getcredentialstate(foruserid:completion:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
