{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerDelegate/textFormattingViewController:shouldPresentFontPicker:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UITextFormattingViewControllerDelegate(im)textFormattingViewController:shouldPresentFontPicker:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "textFormattingViewController:shouldPresentFontPicker:"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "textFormattingViewController:shouldPresentFontPicker:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "textFormattingViewController:shouldPresentFontPicker:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "textFormattingViewController:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
              "text": "UITextFormattingViewController"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "viewController"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "shouldPresentFontPicker:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIFontPickerViewController",
              "text": "UIFontPickerViewController"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "fontPicker"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController": {
      "abstract": [
        {
          "text": "A view controller that manages the interface for selecting a font that the system provides or the user installs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFontPickerViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFontPickerViewController"
        }
      ],
      "role": "symbol",
      "title": "UIFontPickerViewController",
      "type": "topic",
      "url": "/documentation/uikit/uifontpickerviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextFormattingViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewController"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerDelegate/textFormattingViewController:shouldPresentFontPicker:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "textFormattingViewController:shouldPresentFontPicker:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerDelegate/textFormattingViewController:shouldPresentFontPicker:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textFormattingViewController:shouldPresentFontPicker:"
        }
      ],
      "role": "symbol",
      "title": "textFormattingViewController:shouldPresentFontPicker:",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerdelegate/textformattingviewcontroller:shouldpresentfontpicker:"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController/title",
          "value": "UITextFormattingViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewController/title",
          "value": "UIFontPickerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontPickerViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextformattingviewcontrollerdelegate/textformattingviewcontroller:shouldpresentfontpicker:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
