{
  "abstract": [
    {
      "text": "The devices are displayed in an outline.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartz/documentation/Quartz",
        "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDisplayMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDisplayMode/outline"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@IKDeviceBrowserViewDisplayMode@IKDeviceBrowserViewDisplayModeOutline",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "outline"
      }
    ],
    "modules": [
      {
        "name": "Quartz"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IKDeviceBrowserViewDisplayModeOutline"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "IKDeviceBrowserViewDisplayMode.outline"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "outline"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartz/documentation/Quartz": {
      "abstract": [
        {
          "text": "Allow users to browse, edit, and save images, using slideshows and Core Image filters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz",
      "kind": "symbol",
      "role": "collection",
      "title": "Quartz",
      "type": "topic",
      "url": "/documentation/quartz"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDisplayMode": {
      "abstract": [
        {
          "text": "These constants specify the display mode of the device browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IKDeviceBrowserViewDisplayMode"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDisplayMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKDeviceBrowserViewDisplayMode"
        }
      ],
      "role": "symbol",
      "title": "IKDeviceBrowserViewDisplayMode",
      "type": "topic",
      "url": "/documentation/quartz/ikdevicebrowserviewdisplaymode"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDisplayMode/icon": {
      "abstract": [
        {
          "text": "The devices are displayed as icons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "icon"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDisplayMode/icon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKDeviceBrowserViewDisplayModeIcon"
        }
      ],
      "role": "symbol",
      "title": "IKDeviceBrowserViewDisplayMode.icon",
      "type": "topic",
      "url": "/documentation/quartz/ikdevicebrowserviewdisplaymode/icon"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDisplayMode/outline": {
      "abstract": [
        {
          "text": "The devices are displayed in an outline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outline"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDisplayMode/outline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKDeviceBrowserViewDisplayModeOutline"
        }
      ],
      "role": "symbol",
      "title": "IKDeviceBrowserViewDisplayMode.outline",
      "type": "topic",
      "url": "/documentation/quartz/ikdevicebrowserviewdisplaymode/outline"
    },
    "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDisplayMode/table": {
      "abstract": [
        {
          "text": "The devices are displayed in a table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "table"
        }
      ],
      "identifier": "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDisplayMode/table",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IKDeviceBrowserViewDisplayModeTable"
        }
      ],
      "role": "symbol",
      "title": "IKDeviceBrowserViewDisplayMode.table",
      "type": "topic",
      "url": "/documentation/quartz/ikdevicebrowserviewdisplaymode/table"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDisplayMode/table",
        "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDisplayMode/icon"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IKDeviceBrowserViewDisplayModeOutline"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserViewDisplayModeOutline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartz/documentation/Quartz",
                "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDisplayMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDisplayMode/table",
                "doc://com.apple.quartz/documentation/Quartz/IKDeviceBrowserViewDisplayMode/icon"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "IKDeviceBrowserViewDisplayModeOutline"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDisplayMode~1table/title",
          "value": "IKDeviceBrowserViewDisplayModeTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDisplayMode~1table/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserViewDisplayModeTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDisplayMode~1outline/title",
          "value": "IKDeviceBrowserViewDisplayModeOutline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDisplayMode~1outline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserViewDisplayModeOutline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDisplayMode~1icon/title",
          "value": "IKDeviceBrowserViewDisplayModeIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDisplayMode~1icon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserViewDisplayModeIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDisplayMode/title",
          "value": "IKDeviceBrowserViewDisplayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDisplayMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserViewDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartz~1documentation~1Quartz~1IKDeviceBrowserViewDisplayMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IKDeviceBrowserViewDisplayMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartz/ikdevicebrowserviewdisplaymode/outline"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartz/ikdevicebrowserviewdisplaymode/outline"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
