{"metadata":{"platforms":[{"unavailable":false,"deprecated":false,"name":"macOS","beta":false}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"childWindows","kind":"identifier"},{"text":": [","kind":"text"},{"text":"NSWindow","preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"externalID":"c:objc(cs)NSWindow(py)childWindows","role":"symbol","navigatorTitle":[{"text":"childWindows","kind":"identifier"}],"title":"childWindows","symbolKind":"property","modules":[{"name":"AppKit"}]},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/addChildWindow(_:ordered:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/removeChildWindow(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/parent"],"title":"Managing Attached Windows","anchor":"Managing-Attached-Windows","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"childWindows"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"An array of the window’s attached child windows."}],"variants":[{"paths":["/documentation/appkit/nswindow/childwindows"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nswindow/childwindows"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/childWindows","interfaceLanguage":"swift"},"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/addChildWindow(_:ordered:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addChildWindow"},{"text":"(","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow"},{"text":", ","kind":"text"},{"text":"ordered","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier","text":"NSWindow"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSWindowOrderingMode","kind":"typeIdentifier","text":"OrderingMode"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"addChildWindow:ordered:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/addChildWindow(_:ordered:)","url":"/documentation/appkit/nswindow/addchildwindow(_:ordered:)","kind":"symbol","title":"addChildWindow(_:ordered:)","abstract":[{"text":"Adds a given window as a child window of the window.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/removeChildWindow(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeChildWindow"},{"text":"(","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"removeChildWindow:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/removeChildWindow(_:)","url":"/documentation/appkit/nswindow/removechildwindow(_:)","kind":"symbol","title":"removeChildWindow(_:)","abstract":[{"text":"Detaches a given child window from the window.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/parent":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parent","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier","text":"NSWindow"},{"kind":"text","text":"?"}],"role":"symbol","title":"parent","url":"/documentation/appkit/nswindow/parent","kind":"symbol","abstract":[{"text":"The parent window to which the window is attached as a child.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"parentWindow"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/parent"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/childWindows":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"childWindows"},{"text":": [","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow"},{"text":"]?","kind":"text"}],"role":"symbol","title":"childWindows","url":"/documentation/appkit/nswindow/childwindows","kind":"symbol","abstract":[{"text":"An array of the window’s attached child windows.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"childWindows","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/childWindows"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"name":"macOS","unavailable":false,"deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"value":"childWindows","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"childWindows","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/addChildWindow(_:ordered:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/removeChildWindow(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/parent"],"anchor":"Managing-Attached-Windows","title":"Managing Attached Windows"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<__kindof NSWindow *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"childWindows"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":"NSWindow","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title"},{"value":[{"kind":"identifier","text":"NSWindow"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments"},{"value":[{"text":"NSWindow","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle"},{"value":"addChildWindow:ordered:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1addChildWindow(_:ordered:)/title"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1addChildWindow(_:ordered:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addChildWindow:ordered:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1removeChildWindow(_:)/title","op":"replace","value":"removeChildWindow:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1removeChildWindow(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeChildWindow:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1parent/title","op":"replace","value":"parentWindow"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1parent/fragments","op":"replace","value":[{"text":"parentWindow","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1childWindows/title","op":"replace","value":"childWindows"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1childWindows/fragments","op":"replace","value":[{"kind":"identifier","text":"childWindows"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}