{
  "abstract": [
    {
      "text": "Window collection behaviors related to Mission Control, Spaces, and Stage Manager.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSWindowCollectionBehavior",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CollectionBehavior"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CollectionBehavior"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSWindow.CollectionBehavior"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CollectionBehavior"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Collection behaviors are properties you set on windows to control their display characteristics in window management technologies. Use them to specify a preference on how windows behave in window management technologies like Mission Control, Spaces, and Stage Manager.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To set a collection behavior on a window, assign one or more behavior options to the window’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/collectionBehavior-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "window.collectionBehavior = .primary"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "window.collectionBehavior = NSWindowCollectionBehaviorPrimary;"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "Not all collection behaviors apply to all windowing management technologies, and some are mutually exclusive to their respective groups. For example, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/primary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/auxiliary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/canJoinAllApplications",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " only apply to full screen and Stage Manager. They’re also mutually exclusive. Specify at most one per window.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow": {
      "abstract": [
        {
          "text": "A window that an app displays on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "role": "symbol",
      "title": "NSWindow",
      "type": "topic",
      "url": "/documentation/appkit/nswindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum": {
      "abstract": [
        {
          "text": "Constants that control the automatic window animation behavior windows use when ordering to the front or out of view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.AnimationBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/animationbehavior-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/BackingStoreType": {
      "abstract": [
        {
          "text": "Constants that specify how the window device buffers the drawing done in a window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BackingStoreType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/BackingStoreType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BackingStoreType"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.BackingStoreType",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/backingstoretype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType": {
      "abstract": [
        {
          "text": "Constants that provide a way to access standard title bar buttons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ButtonType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ButtonType"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.ButtonType",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/buttontype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct": {
      "abstract": [
        {
          "text": "Window collection behaviors related to Mission Control, Spaces, and Stage Manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CollectionBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.CollectionBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/auxiliary": {
      "abstract": [
        {
          "text": "The behavior marking this window as auxiliary for both Stage Manager and full screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auxiliary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/auxiliary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorAuxiliary"
        }
      ],
      "role": "symbol",
      "title": "auxiliary",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/auxiliary"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/canJoinAllApplications": {
      "abstract": [
        {
          "text": "The behavior marking this window as one that can join all apps for both Stage Manager and full screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canJoinAllApplications"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/canJoinAllApplications",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorCanJoinAllApplications"
        }
      ],
      "role": "symbol",
      "title": "canJoinAllApplications",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/canjoinallapplications"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/canJoinAllSpaces": {
      "abstract": [
        {
          "text": "The window can appear in all spaces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canJoinAllSpaces"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/canJoinAllSpaces",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorCanJoinAllSpaces"
        }
      ],
      "role": "symbol",
      "title": "canJoinAllSpaces",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/canjoinallspaces"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenAllowsTiling": {
      "abstract": [
        {
          "text": "The window can be a secondary full screen tile even if it can’t be a full screen window itself.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullScreenAllowsTiling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenAllowsTiling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorFullScreenAllowsTiling"
        }
      ],
      "role": "symbol",
      "title": "fullScreenAllowsTiling",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/fullscreenallowstiling"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenAuxiliary": {
      "abstract": [
        {
          "text": "The window displays on the same space as the full screen window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullScreenAuxiliary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenAuxiliary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorFullScreenAuxiliary"
        }
      ],
      "role": "symbol",
      "title": "fullScreenAuxiliary",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/fullscreenauxiliary"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenDisallowsTiling": {
      "abstract": [
        {
          "text": "The window doesn’t support being a full-screen tile window, but may support being a full-screen window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullScreenDisallowsTiling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenDisallowsTiling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorFullScreenDisallowsTiling"
        }
      ],
      "role": "symbol",
      "title": "fullScreenDisallowsTiling",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/fullscreendisallowstiling"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenNone": {
      "abstract": [
        {
          "text": "The window doesn’t support full-screen mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullScreenNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorFullScreenNone"
        }
      ],
      "role": "symbol",
      "title": "fullScreenNone",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/fullscreennone"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenPrimary": {
      "abstract": [
        {
          "text": "The window can enter full-screen mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullScreenPrimary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenPrimary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorFullScreenPrimary"
        }
      ],
      "role": "symbol",
      "title": "fullScreenPrimary",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/fullscreenprimary"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/ignoresCycle": {
      "abstract": [
        {
          "text": "The window isn’t part of the window cycle for use with the Cycle Through Windows menu item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ignoresCycle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/ignoresCycle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorIgnoresCycle"
        }
      ],
      "role": "symbol",
      "title": "ignoresCycle",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/ignorescycle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a window collection behavior using the given raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/managed": {
      "abstract": [
        {
          "text": "The window participates in Mission Control and Spaces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "managed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/managed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorManaged"
        }
      ],
      "role": "symbol",
      "title": "managed",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/managed"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/moveToActiveSpace": {
      "abstract": [
        {
          "text": "When the window becomes active, move it to the active space instead of switching spaces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moveToActiveSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/moveToActiveSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorMoveToActiveSpace"
        }
      ],
      "role": "symbol",
      "title": "moveToActiveSpace",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/movetoactivespace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/participatesInCycle": {
      "abstract": [
        {
          "text": "The window participates in the window cycle for use with the Cycle Through Windows menu item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "participatesInCycle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/participatesInCycle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorParticipatesInCycle"
        }
      ],
      "role": "symbol",
      "title": "participatesInCycle",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/participatesincycle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/primary": {
      "abstract": [
        {
          "text": "The behavior marking this window as primary for both Stage Manager and full screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/primary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorPrimary"
        }
      ],
      "role": "symbol",
      "title": "primary",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/primary"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/stationary": {
      "abstract": [
        {
          "text": "Mission Control doesn’t affect the window, so it stays visible and stationary, like the desktop window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stationary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/stationary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorStationary"
        }
      ],
      "role": "symbol",
      "title": "stationary",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/stationary"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/transient": {
      "abstract": [
        {
          "text": "The window floats in Spaces and hides in Mission Control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transient"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/transient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorTransient"
        }
      ],
      "role": "symbol",
      "title": "transient",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/transient"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth": {
      "abstract": [
        {
          "text": "A type that represents the depth, or amount of memory, for a single pixel in a window or screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Depth"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Depth"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.Depth",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/depth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/NumberListOptions": {
      "abstract": [
        {
          "text": "Options to use when retrieving window numbers from the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NumberListOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/NumberListOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NumberListOptions"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.NumberListOptions",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/numberlistoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/OcclusionState-swift.struct": {
      "abstract": [
        {
          "text": "Specifies whether the window is occluded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OcclusionState"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/OcclusionState-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OcclusionState"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.OcclusionState",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/occlusionstate-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/OrderingMode": {
      "abstract": [
        {
          "text": "Constants that let you specify how a window is ordered relative to another window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OrderingMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/OrderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OrderingMode"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.OrderingMode",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/orderingmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/SelectionDirection": {
      "abstract": [
        {
          "text": "Constants that specify the direction a window is currently using to change the key view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SelectionDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/SelectionDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SelectionDirection"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.SelectionDirection",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/selectiondirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/SharingType-swift.enum": {
      "abstract": [
        {
          "text": "Constants that represent the access levels other processes can have to a window’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SharingType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/SharingType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SharingType"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.SharingType",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/sharingtype-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/TabbingMode-swift.enum": {
      "abstract": [
        {
          "text": "The preferred tabbing behavior of a window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TabbingMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/TabbingMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TabbingMode"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.TabbingMode",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/tabbingmode-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/TitleVisibility-swift.enum": {
      "abstract": [
        {
          "text": "Specifies the appearance of the window’s title bar area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TitleVisibility"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/TitleVisibility-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TitleVisibility"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.TitleVisibility",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/titlevisibility-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/UserTabbingPreference-swift.enum": {
      "abstract": [
        {
          "text": "A value that indicates the user’s preference for window tabbing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UserTabbingPreference"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/UserTabbingPreference-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UserTabbingPreference"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.UserTabbingPreference",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/usertabbingpreference-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/collectionBehavior-swift.property": {
      "abstract": [
        {
          "text": "A value that identifies the window’s behavior in window collections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collectionBehavior"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/collectionBehavior-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collectionBehavior"
        }
      ],
      "role": "symbol",
      "title": "collectionBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowCollectionBehavior/NSWindowCollectionBehaviorDefault": {
      "abstract": [
        {
          "text": "The window appears in only one space at a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorDefault"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowCollectionBehavior/NSWindowCollectionBehaviorDefault",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWindowCollectionBehaviorDefault",
      "type": "topic",
      "url": "/documentation/appkit/nswindowcollectionbehavior/nswindowcollectionbehaviordefault"
    },
    "doc://com.apple.appkit/documentation/AppKit/application-kit-version-for-custom-sheet-position": {
      "abstract": [
        {
          "text": "The version of the AppKit.framework containing a specific bug fix or capability.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/application-kit-version-for-custom-sheet-position",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Application Kit Version for Custom Sheet Position",
      "type": "topic",
      "url": "/documentation/appkit/application-kit-version-for-custom-sheet-position"
    },
    "doc://com.apple.appkit/documentation/AppKit/application-kit-version-for-deferred-window-display-support": {
      "abstract": [
        {
          "text": "The version of the AppKit.framework containing a specific bug fix or capability.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/application-kit-version-for-deferred-window-display-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Application Kit Version for Deferred Window Display Support",
      "type": "topic",
      "url": "/documentation/appkit/application-kit-version-for-deferred-window-display-support"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsrunloop-ordering-modes-for-nsw": {
      "abstract": [
        {
          "text": "Constants that specify the priority for runloop messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsrunloop-ordering-modes-for-nsw",
      "kind": "article",
      "role": "collectionGroup",
      "title": "NSRunLoop—Ordering Modes for NSWindow",
      "type": "topic",
      "url": "/documentation/appkit/nsrunloop-ordering-modes-for-nsw"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/SelectionDirection",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType",
        "doc://com.apple.appkit/documentation/AppKit/nsrunloop-ordering-modes-for-nsw",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/BackingStoreType",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/OrderingMode",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/SharingType-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/NumberListOptions",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/OcclusionState-swift.struct",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/TitleVisibility-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/UserTabbingPreference-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/TabbingMode-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/application-kit-version-for-deferred-window-display-support",
        "doc://com.apple.appkit/documentation/AppKit/application-kit-version-for-custom-sheet-position"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Window-Collection-Behaviors-Creation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/init(rawValue:)"
      ],
      "title": "Window Collection Behaviors Creation"
    },
    {
      "anchor": "Stage-Manager-and-full-screen",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/primary",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/auxiliary",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/canJoinAllApplications"
      ],
      "title": "Stage Manager and full screen"
    },
    {
      "anchor": "Spaces",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/canJoinAllSpaces",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/moveToActiveSpace"
      ],
      "title": "Spaces"
    },
    {
      "anchor": "Mission-Control",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/stationary"
      ],
      "title": "Mission Control"
    },
    {
      "anchor": "Spaces-and-Mission-Control",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/managed",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/transient"
      ],
      "title": "Spaces and Mission Control"
    },
    {
      "anchor": "Full-screen",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenPrimary",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenAuxiliary",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenNone",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenAllowsTiling",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenDisallowsTiling"
      ],
      "title": "Full screen"
    },
    {
      "anchor": "Window-cycling",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/participatesInCycle",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/ignoresCycle"
      ],
      "title": "Window cycling"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSWindowCollectionBehavior"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Stage-Manager-and-full-screen",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/primary",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/auxiliary",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/canJoinAllApplications"
              ],
              "title": "Stage Manager and full screen"
            },
            {
              "anchor": "Spaces",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindowCollectionBehavior/NSWindowCollectionBehaviorDefault",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/canJoinAllSpaces",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/moveToActiveSpace"
              ],
              "title": "Spaces"
            },
            {
              "anchor": "Mission-Control",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/stationary"
              ],
              "title": "Mission Control"
            },
            {
              "anchor": "Spaces-and-Mission-Control",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/managed",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/transient"
              ],
              "title": "Spaces and Mission Control"
            },
            {
              "anchor": "Full-screen",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenPrimary",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenAuxiliary",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenNone",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenAllowsTiling",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/fullScreenDisallowsTiling"
              ],
              "title": "Full screen"
            },
            {
              "anchor": "Window-cycling",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/participatesInCycle",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/ignoresCycle"
              ],
              "title": "Window cycling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/SelectionDirection",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType",
                "doc://com.apple.appkit/documentation/AppKit/nsrunloop-ordering-modes-for-nsw",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/BackingStoreType",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/OrderingMode",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/SharingType-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/NumberListOptions",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/OcclusionState-swift.struct",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/TitleVisibility-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/UserTabbingPreference-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/TabbingMode-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/application-kit-version-for-deferred-window-display-support",
                "doc://com.apple.appkit/documentation/AppKit/application-kit-version-for-custom-sheet-position"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSWindowCollectionBehavior"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1primary/title",
          "value": "NSWindowCollectionBehaviorPrimary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1primary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorPrimary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct/title",
          "value": "NSWindowCollectionBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1canJoinAllApplications/title",
          "value": "NSWindowCollectionBehaviorCanJoinAllApplications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1canJoinAllApplications/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorCanJoinAllApplications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenAllowsTiling/title",
          "value": "NSWindowCollectionBehaviorFullScreenAllowsTiling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenAllowsTiling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorFullScreenAllowsTiling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1canJoinAllSpaces/title",
          "value": "NSWindowCollectionBehaviorCanJoinAllSpaces"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1canJoinAllSpaces/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorCanJoinAllSpaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1UserTabbingPreference-swift.enum/title",
          "value": "NSWindowUserTabbingPreference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1UserTabbingPreference-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowUserTabbingPreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1UserTabbingPreference-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowUserTabbingPreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1OrderingMode/title",
          "value": "NSWindowOrderingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1OrderingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowOrderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1OrderingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowOrderingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1NumberListOptions/title",
          "value": "NSWindowNumberListOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1NumberListOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowNumberListOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1NumberListOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowNumberListOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TabbingMode-swift.enum/title",
          "value": "NSWindowTabbingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TabbingMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowTabbingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TabbingMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowTabbingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1SelectionDirection/title",
          "value": "NSSelectionDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1SelectionDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSelectionDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1SelectionDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSelectionDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenAuxiliary/title",
          "value": "NSWindowCollectionBehaviorFullScreenAuxiliary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenAuxiliary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorFullScreenAuxiliary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1transient/title",
          "value": "NSWindowCollectionBehaviorTransient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1transient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorTransient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1stationary/title",
          "value": "NSWindowCollectionBehaviorStationary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1stationary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorStationary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1collectionBehavior-swift.property/title",
          "value": "collectionBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1collectionBehavior-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "collectionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth/title",
          "value": "NSWindowDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title",
          "value": "NSWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenPrimary/title",
          "value": "NSWindowCollectionBehaviorFullScreenPrimary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenPrimary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorFullScreenPrimary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1auxiliary/title",
          "value": "NSWindowCollectionBehaviorAuxiliary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1auxiliary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorAuxiliary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenDisallowsTiling/title",
          "value": "NSWindowCollectionBehaviorFullScreenDisallowsTiling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenDisallowsTiling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorFullScreenDisallowsTiling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType/title",
          "value": "NSWindowButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1SharingType-swift.enum/title",
          "value": "NSWindowSharingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1SharingType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowSharingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1SharingType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowSharingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1ignoresCycle/title",
          "value": "NSWindowCollectionBehaviorIgnoresCycle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1ignoresCycle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorIgnoresCycle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1AnimationBehavior-swift.enum/title",
          "value": "NSWindowAnimationBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1AnimationBehavior-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowAnimationBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1AnimationBehavior-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowAnimationBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1participatesInCycle/title",
          "value": "NSWindowCollectionBehaviorParticipatesInCycle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1participatesInCycle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorParticipatesInCycle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1managed/title",
          "value": "NSWindowCollectionBehaviorManaged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1managed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorManaged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1moveToActiveSpace/title",
          "value": "NSWindowCollectionBehaviorMoveToActiveSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1moveToActiveSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorMoveToActiveSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenNone/title",
          "value": "NSWindowCollectionBehaviorFullScreenNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1fullScreenNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorFullScreenNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TitleVisibility-swift.enum/title",
          "value": "NSWindowTitleVisibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TitleVisibility-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowTitleVisibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TitleVisibility-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowTitleVisibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1OcclusionState-swift.struct/title",
          "value": "NSWindowOcclusionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1OcclusionState-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowOcclusionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1OcclusionState-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowOcclusionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1BackingStoreType/title",
          "value": "NSBackingStoreType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1BackingStoreType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBackingStoreType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1BackingStoreType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBackingStoreType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nswindow/collectionbehavior-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nswindow/collectionbehavior-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
