{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"variants":[{"paths":["/documentation/appkit/nswindow/contentviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nswindow/contentviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The main content view controller for the window.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentViewController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSViewController","kind":"typeIdentifier","text":"NSViewController","identifier":"doc://com.apple.appkit/documentation/AppKit/NSViewController"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["macOS"]}]},{"content":[{"text":"Discussion","anchor":"Discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The value of this property provides the content view of the window. Setting this value removes the existing value of ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/contentView","type":"reference"},{"text":" and makes the ","type":"text"},{"code":"contentViewController.view","type":"codeVoice"},{"text":" the main content view for the window. By default, the value of this property is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The content view controller controls only the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/contentView"},{"text":" object, and not the title of the window. The window title can easily be bound to the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/contentViewController"},{"text":" object using code such as: ","type":"text"},{"code":"[window bind:NSTitleBinding toObject:contentViewController withKeyPath:@\"title\" options:nil]","type":"codeVoice"},{"text":". Setting ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/contentViewController"},{"text":" causes the window to resize based on the current size of the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/contentViewController"},{"text":"; to restrict the size of the window, use Auto Layout (note that the value of this property is encoded in the NIB). Directly assigning a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/contentView"},{"text":" value clears out the root view controller.","type":"text"}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/contentViewController"},"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/init(contentViewController:)"],"anchor":"Related-Documentation","title":"Related Documentation"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/contentView"],"anchor":"Configuring-the-Windows-Content","title":"Configuring the Window’s Content","generated":true}],"metadata":{"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"contentViewController","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSViewController"},{"text":"?","kind":"text"}],"platforms":[{"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"10.10","beta":false}],"navigatorTitle":[{"kind":"identifier","text":"contentViewController"}],"modules":[{"name":"AppKit"}],"title":"contentViewController","externalID":"c:objc(cs)NSWindow(py)contentViewController","roleHeading":"Instance Property"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSWindow/contentView":{"kind":"symbol","url":"/documentation/appkit/nswindow/contentview","abstract":[{"text":"The window’s content view, the highest accessible view object in the window’s view hierarchy.","type":"text"}],"type":"topic","title":"contentView","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"contentView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"contentView","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/contentView"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/contentViewController":{"navigatorTitle":[{"text":"contentViewController","kind":"identifier"}],"kind":"symbol","url":"/documentation/appkit/nswindow/contentviewcontroller","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/contentViewController","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentViewController","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSViewController"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The main content view controller for the window."}],"type":"topic","title":"contentViewController"},"doc://com.apple.appkit/documentation/AppKit/NSViewController":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSViewController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSViewController"}],"role":"symbol","type":"topic","title":"NSViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSViewController"}],"abstract":[{"text":"A controller that manages a view, typically loaded from a nib file.","type":"text"}],"url":"/documentation/appkit/nsviewcontroller"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/init(contentViewController:)":{"abstract":[{"type":"text","text":"Creates a titled window that contains the specified content view controller."}],"navigatorTitle":[{"text":"windowWithContentViewController:","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/init(contentViewController:)","url":"/documentation/appkit/nswindow/init(contentviewcontroller:)","kind":"symbol","fragments":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"contentViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSViewController"},{"kind":"text","text":")"}],"role":"symbol","title":"init(contentViewController:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"10.10"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"contentViewController","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"contentViewController"}],"path":"/metadata/fragments","op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/init(contentViewController:)"],"title":"Related Documentation","anchor":"Related-Documentation"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/contentView"],"title":"Configuring the Window’s Content","generated":true,"anchor":"Configuring-the-Windows-Content"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSViewController","preciseIdentifier":"c:objc(cs)NSViewController","identifier":"doc://com.apple.appkit/documentation/AppKit/NSViewController"},{"kind":"text","text":" * "},{"kind":"identifier","text":"contentViewController"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"contentView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1contentView/title","op":"replace"},{"value":[{"kind":"identifier","text":"contentView"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1contentView/fragments","op":"replace"},{"value":"NSWindow","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments"},{"op":"replace","value":[{"text":"NSWindow","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle"},{"op":"replace","value":"contentViewController","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1contentViewController/title"},{"op":"replace","value":[{"kind":"identifier","text":"contentViewController"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1contentViewController/fragments"},{"op":"replace","value":"NSViewController","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSViewController/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSViewController"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSViewController/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSViewController"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSViewController/navigatorTitle"},{"op":"replace","value":"windowWithContentViewController:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1init(contentViewController:)/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"windowWithContentViewController:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1init(contentViewController:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}