{"variants":[{"paths":["/documentation/appkit/nswindow/contentrect(forframerect:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nswindow/contentrect(forframerect:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/contentRect(forFrameRect:)","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"title":"Getting Layout Information","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/contentRect(forFrameRect:styleMask:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/frameRect(forContentRect:styleMask:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/minFrameWidth(withTitle:styleMask:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/frameRect(forContentRect:)"],"anchor":"Getting-Layout-Information"}],"abstract":[{"text":"Returns the window’s content rectangle with a given frame rectangle.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentRect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forFrameRect"},{"kind":"text","text":" "},{"kind":"internalParam","text":"frameRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","text":"NSRect"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","text":"NSRect"}]}]},{"kind":"parameters","parameters":[{"name":"frameRect","content":[{"inlineContent":[{"type":"text","text":"The frame rectangle for the window expressed in screen coordinates."}],"type":"paragraph"}]}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"The window’s content rectangle, expressed in screen coordinates, with f","type":"text"},{"code":"rameRect","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"The window uses its current style mask in computing the content rectangle. See ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct","isActive":true,"type":"reference"},{"text":" for a list of style mask values. The main advantage of this instance-method counterpart to ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/contentRect(forFrameRect:styleMask:)","isActive":true,"type":"reference"},{"text":" is that it allows you to take toolbars into account when converting between content and frame rectangles. (The toolbar is not included in the content rectangle.)","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"roleHeading":"Instance Method","role":"symbol","platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}],"title":"contentRect(forFrameRect:)","symbolKind":"method","navigatorTitle":[{"text":"contentRectForFrameRect:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forFrameRect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}],"externalID":"c:objc(cs)NSWindow(im)contentRectForFrameRect:","modules":[{"name":"AppKit"}]},"sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit/NSWindow/frameRect(forContentRect:styleMask:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/frameRect(forContentRect:styleMask:)","role":"symbol","url":"/documentation/appkit/nswindow/framerect(forcontentrect:stylemask:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frameRect","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forContentRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","text":"NSRect"},{"kind":"text","text":", "},{"text":"styleMask","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSWindowStyleMask","text":"StyleMask","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","text":"NSRect"}],"type":"topic","abstract":[{"type":"text","text":"Returns the frame rectangle used by a window with a given content rectangle and window style."}],"title":"frameRect(forContentRect:styleMask:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"frameRectForContentRect:styleMask:"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/frameRect(forContentRect:)":{"type":"topic","url":"/documentation/appkit/nswindow/framerect(forcontentrect:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameRect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forContentRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","text":"NSRect"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier","text":"NSRect"}],"title":"frameRect(forContentRect:)","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/frameRect(forContentRect:)","abstract":[{"text":"Returns the window’s frame rectangle with a given content rectangle.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"frameRectForContentRect:"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/minFrameWidth(withTitle:styleMask:)":{"navigatorTitle":[{"kind":"identifier","text":"minFrameWidthWithTitle:styleMask:"}],"abstract":[{"type":"text","text":"Returns the minimum width a window’s frame rectangle must have for it to display a title, with a given window style."}],"title":"minFrameWidth(withTitle:styleMask:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/minFrameWidth(withTitle:styleMask:)","url":"/documentation/appkit/nswindow/minframewidth(withtitle:stylemask:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"minFrameWidth"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"styleMask"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier","text":"NSWindow"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSWindowStyleMask","kind":"typeIdentifier","text":"StyleMask"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct":{"role":"symbol","abstract":[{"type":"text","text":"Constants that specify the style of a window, and that you can combine with the C bitwise OR operator."}],"title":"NSWindow.StyleMask","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StyleMask"}],"url":"/documentation/appkit/nswindow/stylemask-swift.struct","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleMask"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/contentRect(forFrameRect:styleMask:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"contentRectForFrameRect:styleMask:"}],"kind":"symbol","abstract":[{"type":"text","text":"Returns the content rectangle used by a window with a given frame rectangle and window style."}],"title":"contentRect(forFrameRect:styleMask:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/contentRect(forFrameRect:styleMask:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentRect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forFrameRect"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"styleMask","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSWindowStyleMask","text":"StyleMask"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","text":"NSRect"}],"url":"/documentation/appkit/nswindow/contentrect(forframerect:stylemask:)"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/contentRect(forFrameRect:)":{"type":"topic","url":"/documentation/appkit/nswindow/contentrect(forframerect:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentRect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forFrameRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier","text":"NSRect"}],"title":"contentRect(forFrameRect:)","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/contentRect(forFrameRect:)","abstract":[{"text":"Returns the window’s content rectangle with a given frame rectangle.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"contentRectForFrameRect:"}]},"doc://com.externally.resolved.symbol/c:@T@NSRect":{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","role":"symbol","type":"topic","url":"/documentation/foundation/nsrect","abstract":[{"text":"A rectangle.","type":"text"}],"fragments":[{"text":"typealias ","kind":"text"},{"text":"NSRect","kind":"identifier"}],"title":"NSRect","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"name":"macOS","unavailable":false,"beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"contentRectForFrameRect:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"contentRectForFrameRect:","kind":"identifier"}]},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"anchor":"Getting-Layout-Information","generated":true,"title":"Getting Layout Information","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/contentRect(forFrameRect:styleMask:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/frameRect(forContentRect:styleMask:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/minFrameWidth(withTitle:styleMask:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/frameRect(forContentRect:)"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","text":"NSRect"},{"kind":"text","text":") "},{"kind":"identifier","text":"contentRectForFrameRect:"},{"kind":"text","text":"("},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","text":"NSRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"frameRect"},{"kind":"text","text":";"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":{"parameters":[{"name":"frameRect","content":[{"inlineContent":[{"text":"The frame rectangle for the window expressed in screen coordinates.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"/primaryContentSections/1","op":"replace"},{"value":{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The window’s content rectangle, expressed in screen coordinates, with f","type":"text"},{"code":"rameRect","type":"codeVoice"},{"text":".","type":"text"}]}],"kind":"content"},"path":"/primaryContentSections/2","op":"replace"},{"value":"frameRectForContentRect:styleMask:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1frameRect(forContentRect:styleMask:)/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"frameRectForContentRect:styleMask:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1frameRect(forContentRect:styleMask:)/fragments","op":"replace"},{"value":"frameRectForContentRect:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1frameRect(forContentRect:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"frameRectForContentRect:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1frameRect(forContentRect:)/fragments","op":"replace"},{"value":"minFrameWidthWithTitle:styleMask:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1minFrameWidth(withTitle:styleMask:)/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"minFrameWidthWithTitle:styleMask:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1minFrameWidth(withTitle:styleMask:)/fragments","op":"replace"},{"value":"NSWindowStyleMask","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSWindowStyleMask"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/fragments","op":"replace"},{"value":[{"text":"NSWindowStyleMask","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/navigatorTitle","op":"replace"},{"value":"contentRectForFrameRect:styleMask:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1contentRect(forFrameRect:styleMask:)/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"contentRectForFrameRect:styleMask:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1contentRect(forFrameRect:styleMask:)/fragments","op":"replace"},{"value":"contentRectForFrameRect:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1contentRect(forFrameRect:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"contentRectForFrameRect:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1contentRect(forFrameRect:)/fragments","op":"replace"},{"value":"NSWindow","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title","op":"replace"},{"value":[{"text":"NSWindow","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSWindow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}