{"variants":[{"paths":["/documentation/appkit/nswindow/converttoscreen(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nswindow/converttoscreen(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"AppKit"}],"externalID":"c:objc(cs)NSWindow(im)convertRectToScreen:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertToScreen"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier","text":"NSRect"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier","text":"NSRect"}],"navigatorTitle":[{"kind":"identifier","text":"convertRectToScreen:"}],"role":"symbol","title":"convertToScreen(_:)","platforms":[{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"10.7","name":"macOS"}]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"abstract":[{"text":"Converts a rectangle to the screen coordinate system from the window’s coordinate system.","type":"text"}],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/backingScaleFactor","doc://com.apple.appkit/documentation/AppKit/NSWindow/backingAlignedRect(_:options:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/convertFromBacking(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/convertFromScreen(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/convertPointFromBacking(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/convertPoint(fromScreen:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/convertToBacking(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/convertPointToBacking(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/convertPoint(toScreen:)"],"anchor":"Converting-Coordinates","title":"Converting Coordinates","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/convertToScreen(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"convertToScreen","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"rect","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"A rectangle in the window’s coordinate system.","type":"text"}],"type":"paragraph"}],"name":"rect"}],"kind":"parameters"},{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"text":"A rectangle in the screen’s coordinate system.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/convertFromBacking(_:)":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/convertFromBacking(_:)","url":"/documentation/appkit/nswindow/convertfrombacking(_:)","navigatorTitle":[{"kind":"identifier","text":"convertRectFromBacking:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertFromBacking"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"}],"type":"topic","title":"convertFromBacking(_:)","role":"symbol","abstract":[{"type":"text","text":"Converts a rectangle from its pixel-aligned backing store coordinate system to the window’s coordinate system."}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/convertPoint(fromScreen:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/convertPoint(fromScreen:)","url":"/documentation/appkit/nswindow/convertpoint(fromscreen:)","navigatorTitle":[{"text":"convertPointFromScreen:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convertPoint","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromScreen","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":") -> ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"}],"kind":"symbol","type":"topic","title":"convertPoint(fromScreen:)","role":"symbol","abstract":[{"text":"Converts a point from the screen coordinate system to the window’s coordinate system.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/convertPointToBacking(_:)":{"title":"convertPointToBacking(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertPointToBacking"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier","text":"NSPoint"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier","text":"NSPoint"}],"kind":"symbol","abstract":[{"text":"Converts a point from the window’s coordinate system to its pixel-aligned backing store coordinate system.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nswindow/convertpointtobacking(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/convertPointToBacking(_:)","navigatorTitle":[{"kind":"identifier","text":"convertPointToBacking:"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/convertPoint(toScreen:)":{"title":"convertPoint(toScreen:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertPoint"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toScreen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"}],"kind":"symbol","abstract":[{"type":"text","text":"Converts a point to the screen coordinate system from the window’s coordinate system."}],"type":"topic","role":"symbol","url":"/documentation/appkit/nswindow/convertpoint(toscreen:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/convertPoint(toScreen:)","navigatorTitle":[{"kind":"identifier","text":"convertPointToScreen:"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/backingAlignedRect(_:options:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"backingAlignedRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NSAlignmentOptions","text":"AlignmentOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier"}],"title":"backingAlignedRect(_:options:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/backingAlignedRect(_:options:)","abstract":[{"text":"Returns a backing store pixel-aligned rectangle in window coordinates.","type":"text"}],"role":"symbol","url":"/documentation/appkit/nswindow/backingalignedrect(_:options:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"backingAlignedRect:options:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/convertFromScreen(_:)":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/convertFromScreen(_:)","url":"/documentation/appkit/nswindow/convertfromscreen(_:)","navigatorTitle":[{"text":"convertRectFromScreen:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convertFromScreen","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}],"type":"topic","title":"convertFromScreen(_:)","role":"symbol","abstract":[{"type":"text","text":"Converts a rectangle from the screen coordinate system to the window’s coordinate system."}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/backingScaleFactor":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/backingScaleFactor","abstract":[{"text":"The backing scale factor.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"backingScaleFactor","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backingScaleFactor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"title":"backingScaleFactor","kind":"symbol","url":"/documentation/appkit/nswindow/backingscalefactor","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/convertPointFromBacking(_:)":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/convertPointFromBacking(_:)","url":"/documentation/appkit/nswindow/convertpointfrombacking(_:)","navigatorTitle":[{"kind":"identifier","text":"convertPointFromBacking:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertPointFromBacking"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSPoint","preciseIdentifier":"c:@T@NSPoint"}],"type":"topic","title":"convertPointFromBacking(_:)","role":"symbol","abstract":[{"type":"text","text":"Converts a point from its pixel-aligned backing store coordinate system to the window’s coordinate system."}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/convertToBacking(_:)":{"url":"/documentation/appkit/nswindow/converttobacking(_:)","type":"topic","title":"convertToBacking(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"convertRectToBacking:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertToBacking"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"}],"abstract":[{"text":"Converts a rectangle from the window’s coordinate system to its pixel-aligned backing store coordinate system.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/convertToBacking(_:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/convertToScreen(_:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"convertRectToScreen:"}],"abstract":[{"type":"text","text":"Converts a rectangle to the screen coordinate system from the window’s coordinate system."}],"url":"/documentation/appkit/nswindow/converttoscreen(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertToScreen"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","text":"NSRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","text":"NSRect"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/convertToScreen(_:)","title":"convertToScreen(_:)"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/c:@T@NSRect":{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","role":"symbol","type":"topic","url":"/documentation/foundation/nsrect","abstract":[{"text":"A rectangle.","type":"text"}],"fragments":[{"text":"typealias ","kind":"text"},{"text":"NSRect","kind":"identifier"}],"title":"NSRect","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"10.7"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"convertRectToScreen:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"convertRectToScreen:"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"op":"replace","path":"/hierarchy"},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/backingScaleFactor","doc://com.apple.appkit/documentation/AppKit/NSWindow/backingAlignedRect(_:options:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/convertFromBacking(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/convertFromScreen(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/convertPointFromBacking(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/convertPoint(fromScreen:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/convertToBacking(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/convertPointToBacking(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/convertPoint(toScreen:)"],"anchor":"Converting-Coordinates","title":"Converting Coordinates","generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect"},{"text":") ","kind":"text"},{"text":"convertRectToScreen:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect"},{"text":") ","kind":"text"},{"text":"rect","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"}},{"path":"/primaryContentSections/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A rectangle in the window’s coordinate system."}],"type":"paragraph"}],"name":"rect"}]}},{"path":"/primaryContentSections/2","op":"replace","value":{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"A rectangle in the screen’s coordinate system.","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title","op":"replace","value":"NSWindow"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments","op":"replace","value":[{"text":"NSWindow","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSWindow"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1convertFromBacking(_:)/title","op":"replace","value":"convertRectFromBacking:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1convertFromBacking(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"convertRectFromBacking:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1convertPoint(fromScreen:)/title","op":"replace","value":"convertPointFromScreen:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1convertPoint(fromScreen:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"convertPointFromScreen:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1convertPointToBacking(_:)/title","op":"replace","value":"convertPointToBacking:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1convertPointToBacking(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"convertPointToBacking:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1convertPoint(toScreen:)/title","value":"convertPointToScreen:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1convertPoint(toScreen:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"convertPointToScreen:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1backingAlignedRect(_:options:)/title","value":"backingAlignedRect:options:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1backingAlignedRect(_:options:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"backingAlignedRect:options:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1convertFromScreen(_:)/title","value":"convertRectFromScreen:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1convertFromScreen(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"convertRectFromScreen:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1backingScaleFactor/title","value":"backingScaleFactor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1backingScaleFactor/fragments","value":[{"text":"backingScaleFactor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1convertPointFromBacking(_:)/title","value":"convertPointFromBacking:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1convertPointFromBacking(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"convertPointFromBacking:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1convertToBacking(_:)/title","value":"convertRectToBacking:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1convertToBacking(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"convertRectToBacking:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1convertToScreen(_:)/title","value":"convertRectToScreen:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1convertToScreen(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"convertRectToScreen:","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}