{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nswindow/depth"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nswindow/depth"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@E@NSWindowDepth","roleHeading":"Enumeration","title":"NSWindow.Depth","symbolKind":"enum","navigatorTitle":[{"text":"Depth","kind":"identifier"}],"platforms":[{"beta":false,"introducedAt":"10.6","name":"macOS","deprecated":false,"unavailable":false}],"role":"symbol","extendedModule":"AppKit","modules":[{"name":"AppKit"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Depth","kind":"identifier"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"abstract":[{"type":"text","text":"A type that represents the depth, or amount of memory, for a single pixel in a window or screen."}],"topicSections":[{"anchor":"Constants","title":"Constants","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/onehundredtwentyeightBitRGB","doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/sixtyfourBitRGB","doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/twentyfourBitRGB"]},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/availableDepths","doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/bestDepth(colorSpaceName:bitsPerSample:bitsPerPixel:isPlanar:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/bitsPerPixel","doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/bitsPerSample","doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/colorSpaceName","doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/isPlanar"],"title":"Accessing Depth Details","anchor":"Accessing-Depth-Details"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/init(rawValue:)"],"title":"Initializers","anchor":"Initializers","generated":true}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth"},"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/SelectionDirection","doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType","doc://com.apple.appkit/documentation/AppKit/nsrunloop-ordering-modes-for-nsw","doc://com.apple.appkit/documentation/AppKit/NSWindow/BackingStoreType","doc://com.apple.appkit/documentation/AppKit/NSWindow/OrderingMode","doc://com.apple.appkit/documentation/AppKit/NSWindow/SharingType-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSWindow/NumberListOptions","doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct","doc://com.apple.appkit/documentation/AppKit/NSWindow/OcclusionState-swift.struct","doc://com.apple.appkit/documentation/AppKit/NSWindow/TitleVisibility-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSWindow/UserTabbingPreference-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSWindow/TabbingMode-swift.enum","doc://com.apple.appkit/documentation/AppKit/application-kit-version-for-deferred-window-display-support","doc://com.apple.appkit/documentation/AppKit/application-kit-version-for-custom-sheet-position"],"title":"Constants","anchor":"Constants","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Depth"}]}]},{"content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A depth of "},{"type":"codeVoice","code":"0"},{"text":" indicates default depth. Don’t make window depths persistent because they aren’t the same across systems.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use the functions "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/colorSpaceName","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/bitsPerPixel","isActive":true},{"type":"text","text":", and "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/isPlanar","isActive":true,"type":"reference"},{"text":" to extract info from an ","type":"text"},{"code":"NSWindowDepth","type":"codeVoice"},{"text":" value.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Use ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBestDepth"},{"text":" to compute window depths. ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBestDepth"},{"text":" tries to accommodate all the parameters (match or better). If there are multiple matches, this function uses color space first, then bits per sample (","type":"text"},{"type":"codeVoice","code":"bps"},{"text":"), then ","type":"text"},{"type":"codeVoice","code":"planar"},{"text":", then bits per pixel (","type":"text"},{"type":"codeVoice","code":"bpp)"},{"text":" to determine the closest match. Use ","type":"text"},{"type":"codeVoice","code":"0"},{"text":" for ","type":"text"},{"type":"codeVoice","code":"bpp"},{"text":" to indicate the default, the same as the number of bits per plane: either ","type":"text"},{"type":"codeVoice","code":"bps"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"bps"},{"text":" * ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/numberOfColorComponents"},{"text":". You may use other values as hints to provide backing stores of different configurations — for instance, 8-bit color.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can also use one of the explicit bit depths defined in "},{"type":"codeVoice","code":"Explicit Window Depth Limits"},{"type":"text","text":" for the "},{"type":"codeVoice","code":"NSWindow"},{"type":"text","text":" property "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/depthLimit","isActive":true,"type":"reference"},{"type":"text","text":"."}]}],"kind":"content"}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSWindow/SharingType-swift.enum":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SharingType","kind":"identifier"}],"abstract":[{"text":"Constants that represent the access levels other processes can have to a window’s content.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/SharingType-swift.enum","navigatorTitle":[{"text":"SharingType","kind":"identifier"}],"title":"NSWindow.SharingType","url":"/documentation/appkit/nswindow/sharingtype-swift.enum","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/sixtyfourBitRGB":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sixtyfourBitRGB","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/sixtyfourBitRGB","navigatorTitle":[{"text":"NSWindowDepthSixtyfourBitRGB","kind":"identifier"}],"title":"NSWindow.Depth.sixtyfourBitRGB","url":"/documentation/appkit/nswindow/depth/sixtyfourbitrgb","abstract":[{"text":"Sixty four bit RGB depth limit.","type":"text"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/isPlanar":{"kind":"symbol","url":"/documentation/appkit/nswindow/depth/isplanar","title":"isPlanar","navigatorTitle":[{"text":"NSPlanarFromDepth","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPlanar","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Returns whether the specified window depth is planar.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/isPlanar","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType":{"url":"/documentation/appkit/nswindow/buttontype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ButtonType","kind":"identifier"}],"title":"NSWindow.ButtonType","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ButtonType","kind":"identifier"}],"abstract":[{"text":"Constants that provide a way to access standard title bar buttons.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","url":"/documentation/appkit/nswindow/depth/init(rawvalue:)","kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/init(rawValue:)","title":"init(rawValue:)","abstract":[]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/bitsPerPixel":{"kind":"symbol","url":"/documentation/appkit/nswindow/depth/bitsperpixel","role":"symbol","navigatorTitle":[{"text":"NSBitsPerPixelFromDepth","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns the bits per pixel for the specified window depth."}],"title":"bitsPerPixel","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bitsPerPixel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/bitsPerPixel","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSBestDepth":{"fragments":[{"text":"NSBestDepth","kind":"identifier"}],"type":"topic","abstract":[{"text":"Attempts to return a window depth adequate for the specified parameters.","type":"text"}],"url":"/documentation/appkit/nsbestdepth","identifier":"doc://com.apple.appkit/documentation/AppKit/NSBestDepth","title":"NSBestDepth","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/NumberListOptions":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/NumberListOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumberListOptions"}],"type":"topic","abstract":[{"text":"Options to use when retrieving window numbers from the system.","type":"text"}],"url":"/documentation/appkit/nswindow/numberlistoptions","title":"NSWindow.NumberListOptions","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NumberListOptions"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/availableDepths":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/availableDepths","abstract":[{"type":"text","text":"An array that contains all available windows depths."}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableDepths"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSWindowDepth","text":"Depth"},{"kind":"text","text":"]"}],"title":"availableDepths","kind":"symbol","url":"/documentation/appkit/nswindow/depth/availabledepths","type":"topic"},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"type":"topic","title":"Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","role":"symbol","url":"/documentation/Swift/Equatable"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","role":"symbol","type":"topic","url":"/documentation/Swift/Sendable","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"title":"Sendable","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"url":"/documentation/Swift/BitwiseCopyable","kind":"symbol","title":"BitwiseCopyable","identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","type":"topic","abstract":[{"text":"","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/bestDepth(colorSpaceName:bitsPerSample:bitsPerPixel:isPlanar:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/bestDepth(colorSpaceName:bitsPerSample:bitsPerPixel:isPlanar:)","role":"symbol","type":"topic","url":"/documentation/appkit/nswindow/depth/bestdepth(colorspacename:bitspersample:bitsperpixel:isplanar:)","abstract":[{"text":"Determines the best window depth that most closely matches the given properties.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bestDepth","kind":"identifier"},{"text":"(","kind":"text"},{"text":"colorSpaceName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSColorSpaceName","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSColorSpaceName"},{"text":", ","kind":"text"},{"text":"bitsPerSample","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"bitsPerPixel","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"isPlanar","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> (","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow"},{"text":".","kind":"text"},{"text":"Depth","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSWindowDepth"},{"text":", isExactMatch","kind":"text"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"bestDepth(colorSpaceName:bitsPerSample:bitsPerPixel:isPlanar:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct":{"url":"/documentation/appkit/nswindow/collectionbehavior-swift.struct","kind":"symbol","abstract":[{"text":"Window collection behaviors related to Mission Control, Spaces, and Stage Manager.","type":"text"}],"title":"NSWindow.CollectionBehavior","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CollectionBehavior"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CollectionBehavior"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/depthLimit":{"title":"depthLimit","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/depthLimit","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"depthLimit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier","text":"NSWindow"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSWindowDepth","text":"Depth","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nswindow/depthlimit","kind":"symbol","abstract":[{"type":"text","text":"The depth limit of the window."}],"navigatorTitle":[{"text":"depthLimit","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/OcclusionState-swift.struct":{"abstract":[{"text":"Specifies whether the window is occluded.","type":"text"}],"url":"/documentation/appkit/nswindow/occlusionstate-swift.struct","kind":"symbol","role":"symbol","title":"NSWindow.OcclusionState","navigatorTitle":[{"text":"OcclusionState","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/OcclusionState-swift.struct","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OcclusionState","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/TabbingMode-swift.enum":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TabbingMode"}],"abstract":[{"type":"text","text":"The preferred tabbing behavior of a window."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/TabbingMode-swift.enum","navigatorTitle":[{"kind":"identifier","text":"TabbingMode"}],"title":"NSWindow.TabbingMode","url":"/documentation/appkit/nswindow/tabbingmode-swift.enum","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum":{"url":"/documentation/appkit/nswindow/animationbehavior-swift.enum","role":"symbol","kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum","navigatorTitle":[{"text":"AnimationBehavior","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnimationBehavior","kind":"identifier"}],"title":"NSWindow.AnimationBehavior","abstract":[{"text":"Constants that control the automatic window animation behavior windows use when ordering to the front or out of view.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/onehundredtwentyeightBitRGB":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"onehundredtwentyeightBitRGB","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/onehundredtwentyeightBitRGB","navigatorTitle":[{"text":"NSWindowDepthOnehundredtwentyeightBitRGB","kind":"identifier"}],"title":"NSWindow.Depth.onehundredtwentyeightBitRGB","url":"/documentation/appkit/nswindow/depth/onehundredtwentyeightbitrgb","abstract":[{"text":"One hundred and twenty eight bit RGB depth limit.","type":"text"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/numberOfColorComponents":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"numberOfColorComponents","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"NSNumberOfColorComponents"}],"type":"topic","abstract":[{"text":"Returns the number of color components in the specified color space.","type":"text"}],"url":"/documentation/appkit/nscolorspacename/numberofcolorcomponents","identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/numberOfColorComponents","title":"numberOfColorComponents","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/twentyfourBitRGB":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"twentyfourBitRGB","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/twentyfourBitRGB","navigatorTitle":[{"text":"NSWindowDepthTwentyfourBitRGB","kind":"identifier"}],"title":"NSWindow.Depth.twentyfourBitRGB","url":"/documentation/appkit/nswindow/depth/twentyfourbitrgb","abstract":[{"type":"text","text":"Twenty four bit RGB depth limit."}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/colorSpaceName":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorSpaceName"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSColorSpaceName","kind":"typeIdentifier","text":"NSColorSpaceName"},{"kind":"text","text":"?"}],"url":"/documentation/appkit/nswindow/depth/colorspacename","title":"colorSpaceName","abstract":[{"text":"Returns the name of the color space corresponding to the passed window depth.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSColorSpaceFromDepth"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/colorSpaceName","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/BackingStoreType":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/BackingStoreType","abstract":[{"text":"Constants that specify how the window device buffers the drawing done in a window.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BackingStoreType"}],"title":"NSWindow.BackingStoreType","url":"/documentation/appkit/nswindow/backingstoretype","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BackingStoreType"}]},"doc://com.externally.resolved.symbol/s:SY":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RawRepresentable","kind":"identifier"},{"text":"<","kind":"text"},{"text":"RawValue","kind":"typeIdentifier","preciseIdentifier":"s:SY8RawValueQa"},{"text":">","kind":"text"}],"url":"/documentation/Swift/RawRepresentable","title":"RawRepresentable","abstract":[{"text":"A type that can be converted to and from an associated raw value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:SY","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/application-kit-version-for-deferred-window-display-support":{"url":"/documentation/appkit/application-kit-version-for-deferred-window-display-support","kind":"article","abstract":[{"text":"The version of the AppKit.framework containing a specific bug fix or capability.","type":"text"}],"title":"Application Kit Version for Deferred Window Display Support","role":"collectionGroup","identifier":"doc://com.apple.appkit/documentation/AppKit/application-kit-version-for-deferred-window-display-support","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/nsrunloop-ordering-modes-for-nsw":{"title":"NSRunLoop—Ordering Modes for NSWindow","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/nsrunloop-ordering-modes-for-nsw","abstract":[{"text":"Constants that specify the priority for runloop messages.","type":"text"}],"role":"collectionGroup","url":"/documentation/appkit/nsrunloop-ordering-modes-for-nsw","kind":"article"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/UserTabbingPreference-swift.enum":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserTabbingPreference","kind":"identifier"}],"abstract":[{"text":"A value that indicates the user’s preference for window tabbing.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/UserTabbingPreference-swift.enum","navigatorTitle":[{"text":"UserTabbingPreference","kind":"identifier"}],"title":"NSWindow.UserTabbingPreference","url":"/documentation/appkit/nswindow/usertabbingpreference-swift.enum","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/bitsPerSample":{"kind":"symbol","url":"/documentation/appkit/nswindow/depth/bitspersample","role":"symbol","navigatorTitle":[{"text":"NSBitsPerSampleFromDepth","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns the bits per sample for the specified window depth."}],"title":"bitsPerSample","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bitsPerSample","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/bitsPerSample","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth","abstract":[{"text":"A type that represents the depth, or amount of memory, for a single pixel in a window or screen.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"Depth","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Depth","kind":"identifier"}],"title":"NSWindow.Depth","kind":"symbol","url":"/documentation/appkit/nswindow/depth","type":"topic"},"doc://com.externally.resolved.symbol/s:SH":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"title":"Hashable"},"doc://com.apple.appkit/documentation/AppKit/application-kit-version-for-custom-sheet-position":{"identifier":"doc://com.apple.appkit/documentation/AppKit/application-kit-version-for-custom-sheet-position","title":"Application Kit Version for Custom Sheet Position","role":"collectionGroup","abstract":[{"text":"The version of the AppKit.framework containing a specific bug fix or capability.","type":"text"}],"kind":"article","type":"topic","url":"/documentation/appkit/application-kit-version-for-custom-sheet-position"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/OrderingMode":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OrderingMode","kind":"identifier"}],"abstract":[{"text":"Constants that let you specify how a window is ordered relative to another window.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/OrderingMode","navigatorTitle":[{"text":"OrderingMode","kind":"identifier"}],"title":"NSWindow.OrderingMode","url":"/documentation/appkit/nswindow/orderingmode","type":"topic"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/TitleVisibility-swift.enum":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TitleVisibility","kind":"identifier"}],"title":"NSWindow.TitleVisibility","url":"/documentation/appkit/nswindow/titlevisibility-swift.enum","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/TitleVisibility-swift.enum","type":"topic","abstract":[{"text":"Specifies the appearance of the window’s title bar area.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"TitleVisibility","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/SelectionDirection":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SelectionDirection","kind":"identifier"}],"title":"NSWindow.SelectionDirection","url":"/documentation/appkit/nswindow/selectiondirection","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/SelectionDirection","type":"topic","abstract":[{"text":"Constants that specify the direction a window is currently using to change the key view.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SelectionDirection","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"introducedAt":"10.6","name":"macOS","deprecated":false,"beta":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration"},{"path":"/metadata/title","op":"replace","value":"NSWindowDepth"},{"path":"/metadata/symbolKind","op":"replace","value":"enum"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"NSWindowDepth"}]},{"path":"/metadata/navigatorTitle","op":"replace","value":[{"text":"NSWindowDepth","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]}},{"path":"/topicSections","op":"replace","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/onehundredtwentyeightBitRGB","doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/sixtyfourBitRGB","doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/twentyfourBitRGB"],"anchor":"Constants","title":"Constants"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/bitsPerPixel","doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/bitsPerSample","doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/colorSpaceName","doc://com.apple.appkit/documentation/AppKit/NSWindow/Depth/isPlanar"],"anchor":"Accessing-Depth-Details","title":"Accessing Depth Details"}]},{"path":"/relationshipsSections","op":"replace","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Constants","anchor":"Constants","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/SelectionDirection","doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType","doc://com.apple.appkit/documentation/AppKit/nsrunloop-ordering-modes-for-nsw","doc://com.apple.appkit/documentation/AppKit/NSWindow/BackingStoreType","doc://com.apple.appkit/documentation/AppKit/NSWindow/OrderingMode","doc://com.apple.appkit/documentation/AppKit/NSWindow/SharingType-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSWindow/NumberListOptions","doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct","doc://com.apple.appkit/documentation/AppKit/NSWindow/OcclusionState-swift.struct","doc://com.apple.appkit/documentation/AppKit/NSWindow/TitleVisibility-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSWindow/UserTabbingPreference-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSWindow/TabbingMode-swift.enum","doc://com.apple.appkit/documentation/AppKit/application-kit-version-for-deferred-window-display-support","doc://com.apple.appkit/documentation/AppKit/application-kit-version-for-custom-sheet-position"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSWindowDepth","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"int32_t","preciseIdentifier":"c:@T@int32_t","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}]}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1SharingType-swift.enum/title","op":"replace","value":"NSWindowSharingType"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1SharingType-swift.enum/fragments","op":"replace","value":[{"text":"NSWindowSharingType","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1SharingType-swift.enum/navigatorTitle","op":"replace","value":[{"text":"NSWindowSharingType","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1sixtyfourBitRGB/title","op":"replace","value":"NSWindowDepthSixtyfourBitRGB"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1sixtyfourBitRGB/fragments","op":"replace","value":[{"kind":"identifier","text":"NSWindowDepthSixtyfourBitRGB"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1isPlanar/title","op":"replace","value":"NSPlanarFromDepth"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1isPlanar/fragments","op":"replace","value":[{"kind":"identifier","text":"NSPlanarFromDepth"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType/title","op":"replace","value":"NSWindowButton"},{"op":"replace","value":[{"text":"NSWindowButton","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType/fragments"},{"op":"replace","value":[{"text":"NSWindowButton","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType/navigatorTitle"},{"op":"replace","value":"NSBitsPerPixelFromDepth","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1bitsPerPixel/title"},{"op":"replace","value":[{"text":"NSBitsPerPixelFromDepth","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1bitsPerPixel/fragments"},{"op":"replace","value":"NSWindowNumberListOptions","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1NumberListOptions/title"},{"op":"replace","value":[{"text":"NSWindowNumberListOptions","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1NumberListOptions/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowNumberListOptions"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1NumberListOptions/navigatorTitle"},{"op":"replace","value":"NSWindowCollectionBehavior","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowCollectionBehavior"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowCollectionBehavior"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct/navigatorTitle"},{"op":"replace","value":"depthLimit","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1depthLimit/title"},{"op":"replace","value":[{"text":"depthLimit","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1depthLimit/fragments"},{"op":"replace","value":"NSWindowOcclusionState","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1OcclusionState-swift.struct/title"},{"op":"replace","value":[{"text":"NSWindowOcclusionState","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1OcclusionState-swift.struct/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowOcclusionState"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1OcclusionState-swift.struct/navigatorTitle"},{"op":"replace","value":"NSWindowTabbingMode","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TabbingMode-swift.enum/title"},{"op":"replace","value":[{"text":"NSWindowTabbingMode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TabbingMode-swift.enum/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowTabbingMode"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TabbingMode-swift.enum/navigatorTitle"},{"op":"replace","value":"NSWindowAnimationBehavior","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1AnimationBehavior-swift.enum/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowAnimationBehavior"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1AnimationBehavior-swift.enum/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowAnimationBehavior"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1AnimationBehavior-swift.enum/navigatorTitle"},{"op":"replace","value":"NSWindowDepthOnehundredtwentyeightBitRGB","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1onehundredtwentyeightBitRGB/title"},{"op":"replace","value":[{"text":"NSWindowDepthOnehundredtwentyeightBitRGB","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1onehundredtwentyeightBitRGB/fragments"},{"op":"replace","value":"NSNumberOfColorComponents","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1numberOfColorComponents/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSNumberOfColorComponents"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1numberOfColorComponents/fragments"},{"op":"replace","value":"NSWindowDepthTwentyfourBitRGB","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1twentyfourBitRGB/title"},{"op":"replace","value":[{"text":"NSWindowDepthTwentyfourBitRGB","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1twentyfourBitRGB/fragments"},{"op":"replace","value":"NSColorSpaceFromDepth","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1colorSpaceName/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSColorSpaceFromDepth"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1colorSpaceName/fragments"},{"op":"replace","value":"NSBackingStoreType","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1BackingStoreType/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSBackingStoreType"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1BackingStoreType/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSBackingStoreType"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1BackingStoreType/navigatorTitle"},{"op":"replace","value":"NSWindow","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments"},{"op":"replace","value":[{"text":"NSWindow","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle"},{"op":"replace","value":"NSWindowUserTabbingPreference","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1UserTabbingPreference-swift.enum/title"},{"op":"replace","value":[{"text":"NSWindowUserTabbingPreference","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1UserTabbingPreference-swift.enum/fragments"},{"op":"replace","value":[{"text":"NSWindowUserTabbingPreference","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1UserTabbingPreference-swift.enum/navigatorTitle"},{"op":"replace","value":"NSBitsPerSampleFromDepth","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1bitsPerSample/title"},{"op":"replace","value":[{"text":"NSBitsPerSampleFromDepth","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth~1bitsPerSample/fragments"},{"op":"replace","value":"NSWindowDepth","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth/title"},{"op":"replace","value":[{"text":"NSWindowDepth","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth/fragments"},{"op":"replace","value":[{"text":"NSWindowDepth","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1Depth/navigatorTitle"},{"op":"replace","value":"NSWindowOrderingMode","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1OrderingMode/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowOrderingMode"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1OrderingMode/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowOrderingMode"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1OrderingMode/navigatorTitle"},{"op":"replace","value":"NSWindowTitleVisibility","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TitleVisibility-swift.enum/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowTitleVisibility"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TitleVisibility-swift.enum/fragments"},{"op":"replace","value":[{"text":"NSWindowTitleVisibility","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TitleVisibility-swift.enum/navigatorTitle"},{"op":"replace","value":"NSSelectionDirection","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1SelectionDirection/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSSelectionDirection"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1SelectionDirection/fragments"},{"op":"replace","value":[{"text":"NSSelectionDirection","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1SelectionDirection/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}