{"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didResignMainNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSNotificationName","preciseIdentifier":"c:@T@NSNotificationName"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The notification object is the ","type":"text"},{"code":"NSWindow","type":"codeVoice"},{"text":" object that resigned its main window status. This notification doesn’t contain a ","type":"text"},{"code":"userInfo","type":"codeVoice"},{"text":" dictionary.","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nswindow/didresignmainnotification"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nswindow/didresignmainnotification"]}],"seeAlsoSections":[{"generated":true,"title":"Notifications","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/didBecomeKeyNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didBecomeMainNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didChangeScreenNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didChangeScreenProfileNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didDeminiaturizeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didEndSheetNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didEndLiveResizeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didExposeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didMiniaturizeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didMoveNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didResignKeyNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didResizeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didUpdateNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/willBeginSheetNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/willCloseNotification"],"anchor":"Notifications"}],"abstract":[{"text":"A notification that the window object resigned its status as main window.","type":"text"}],"sections":[],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didResignMainNotification","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}],"platforms":[{"unavailable":false,"name":"macOS","deprecated":false,"beta":false}],"role":"symbol","externalID":"c:@NSWindowDidResignMainNotification","modules":[{"name":"AppKit"}],"symbolKind":"property","extendedModule":"AppKit","title":"didResignMainNotification","navigatorTitle":[{"text":"NSWindowDidResignMainNotification","kind":"identifier"}],"roleHeading":"Type Property"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didResignMainNotification","interfaceLanguage":"swift"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSWindow/didBecomeMainNotification":{"type":"topic","title":"didBecomeMainNotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didBecomeMainNotification","abstract":[{"type":"text","text":"A notification that the window object became the main window."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindowDidBecomeMainNotification"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didBecomeMainNotification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier","text":"NSNotification"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier","text":"Name"}],"url":"/documentation/appkit/nswindow/didbecomemainnotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didResignMainNotification":{"type":"topic","title":"didResignMainNotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didResignMainNotification","abstract":[{"type":"text","text":"A notification that the window object resigned its status as main window."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindowDidResignMainNotification"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didResignMainNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"url":"/documentation/appkit/nswindow/didresignmainnotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didDeminiaturizeNotification":{"title":"didDeminiaturizeNotification","navigatorTitle":[{"text":"NSWindowDidDeminiaturizeNotification","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didDeminiaturizeNotification"},{"text":": ","kind":"text"},{"text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Name","preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier"}],"abstract":[{"text":"A notification that the window is no longer minimized.","type":"text"}],"kind":"symbol","url":"/documentation/appkit/nswindow/diddeminiaturizenotification","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didDeminiaturizeNotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didMoveNotification":{"type":"topic","title":"didMoveNotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didMoveNotification","abstract":[{"type":"text","text":"A notification that the window object moved."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NSWindowDidMoveNotification","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didMoveNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"url":"/documentation/appkit/nswindow/didmovenotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didChangeScreenProfileNotification":{"type":"topic","title":"didChangeScreenProfileNotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didChangeScreenProfileNotification","abstract":[{"type":"text","text":"A notification that the screen containing the window changed."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NSWindowDidChangeScreenProfileNotification","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didChangeScreenProfileNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"url":"/documentation/appkit/nswindow/didchangescreenprofilenotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didChangeScreenNotification":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didChangeScreenNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Name","preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didChangeScreenNotification","abstract":[{"text":"A notification that a portion of the window object’s frame moved onto or off of a screen.","type":"text"}],"kind":"symbol","title":"didChangeScreenNotification","role":"symbol","navigatorTitle":[{"text":"NSWindowDidChangeScreenNotification","kind":"identifier"}],"url":"/documentation/appkit/nswindow/didchangescreennotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didResignKeyNotification":{"title":"didResignKeyNotification","navigatorTitle":[{"kind":"identifier","text":"NSWindowDidResignKeyNotification"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didResignKeyNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"abstract":[{"type":"text","text":"A notification that the window object resigned its status as key window."}],"kind":"symbol","url":"/documentation/appkit/nswindow/didresignkeynotification","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didResignKeyNotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/willBeginSheetNotification":{"abstract":[{"type":"text","text":"A notification that the window object is about to open a sheet."}],"type":"topic","title":"willBeginSheetNotification","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willBeginSheetNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/willBeginSheetNotification","role":"symbol","url":"/documentation/appkit/nswindow/willbeginsheetnotification","navigatorTitle":[{"text":"NSWindowWillBeginSheetNotification","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:@T@NSNotificationName":{"abstract":[{"text":"A structure that defines the name of a notification.","type":"text"}],"type":"topic","identifier":"doc://com.externally.resolved.symbol/c:@T@NSNotificationName","url":"/documentation/foundation/nsnotification/name","kind":"symbol","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"NSNotification.Name"}],"role":"symbol","title":"NSNotification.Name"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didEndLiveResizeNotification":{"abstract":[{"type":"text","text":"A notification that the user resized the window object."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didEndLiveResizeNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"url":"/documentation/appkit/nswindow/didendliveresizenotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didEndLiveResizeNotification","role":"symbol","navigatorTitle":[{"text":"NSWindowDidEndLiveResizeNotification","kind":"identifier"}],"type":"topic","kind":"symbol","title":"didEndLiveResizeNotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didEndSheetNotification":{"abstract":[{"type":"text","text":"A notification that the window object closed an attached sheet."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"didEndSheetNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"url":"/documentation/appkit/nswindow/didendsheetnotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didEndSheetNotification","role":"symbol","navigatorTitle":[{"text":"NSWindowDidEndSheetNotification","kind":"identifier"}],"type":"topic","kind":"symbol","title":"didEndSheetNotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didResizeNotification":{"title":"didResizeNotification","role":"symbol","url":"/documentation/appkit/nswindow/didresizenotification","navigatorTitle":[{"text":"NSWindowDidResizeNotification","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"A notification that the window object size changed.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didResizeNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didResizeNotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didMiniaturizeNotification":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didMiniaturizeNotification","role":"symbol","type":"topic","url":"/documentation/appkit/nswindow/didminiaturizenotification","navigatorTitle":[{"text":"NSWindowDidMiniaturizeNotification","kind":"identifier"}],"abstract":[{"type":"text","text":"A notification that the window object minimized."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didMiniaturizeNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"title":"didMiniaturizeNotification","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didBecomeKeyNotification":{"title":"didBecomeKeyNotification","navigatorTitle":[{"text":"NSWindowDidBecomeKeyNotification","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didBecomeKeyNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"abstract":[{"type":"text","text":"A notification that the window object became the key window."}],"kind":"symbol","url":"/documentation/appkit/nswindow/didbecomekeynotification","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didBecomeKeyNotification"},"doc://com.externally.resolved.symbol/c:objc(cs)NSNotification":{"fragments":[{"text":"class ","kind":"text"},{"text":"NSNotification","kind":"identifier"}],"url":"/documentation/foundation/nsnotification","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSNotification","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"An object containing information broadcast to registered observers that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"title":"NSNotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didExposeNotification":{"title":"didExposeNotification","role":"symbol","url":"/documentation/appkit/nswindow/didexposenotification","navigatorTitle":[{"text":"NSWindowDidExposeNotification","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"A notification that a window exposed a portion of its nonretained content.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didExposeNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Name","preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didExposeNotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didUpdateNotification":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didUpdateNotification","role":"symbol","type":"topic","url":"/documentation/appkit/nswindow/didupdatenotification","navigatorTitle":[{"text":"NSWindowDidUpdateNotification","kind":"identifier"}],"abstract":[{"type":"text","text":"A notification that the window object received an update message."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdateNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"title":"didUpdateNotification","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/willCloseNotification":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSWindowWillCloseNotification","kind":"identifier"}],"url":"/documentation/appkit/nswindow/willclosenotification","title":"willCloseNotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/willCloseNotification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willCloseNotification"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A notification that the window object is about to close."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":[{"name":"macOS","unavailable":false,"beta":false,"deprecated":false}],"path":"/metadata/platforms"},{"path":"/metadata/roleHeading","op":"replace","value":"Global Variable"},{"path":"/metadata/title","op":"replace","value":"NSWindowDidResignMainNotification"},{"path":"/metadata/symbolKind","op":"replace","value":"var"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"NSWindowDidResignMainNotification"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","value":[{"generated":true,"title":"Notifications","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/didBecomeKeyNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didBecomeMainNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didChangeScreenNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didChangeScreenProfileNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didDeminiaturizeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didEndSheetNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didEndLiveResizeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didExposeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didMiniaturizeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didMoveNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didResignKeyNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didResizeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didUpdateNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/willBeginSheetNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/willCloseNotification"],"anchor":"Notifications"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSNotificationName","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName","identifier":"doc://com.externally.resolved.symbol/c:@T@NSNotificationName"},{"text":" ","kind":"text"},{"text":"NSWindowDidResignMainNotification","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didBecomeMainNotification/title","value":"NSWindowDidBecomeMainNotification","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didBecomeMainNotification/fragments","value":[{"text":"NSWindowDidBecomeMainNotification","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didResignMainNotification/title","value":"NSWindowDidResignMainNotification","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowDidResignMainNotification"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didResignMainNotification/fragments"},{"op":"replace","value":"NSWindowDidDeminiaturizeNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didDeminiaturizeNotification/title"},{"op":"replace","value":[{"text":"NSWindowDidDeminiaturizeNotification","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didDeminiaturizeNotification/fragments"},{"op":"replace","value":"NSWindowDidMoveNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didMoveNotification/title"},{"op":"replace","value":[{"text":"NSWindowDidMoveNotification","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didMoveNotification/fragments"},{"op":"replace","value":"NSWindow","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle"},{"op":"replace","value":"NSWindowDidChangeScreenProfileNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didChangeScreenProfileNotification/title"},{"op":"replace","value":[{"text":"NSWindowDidChangeScreenProfileNotification","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didChangeScreenProfileNotification/fragments"},{"op":"replace","value":"NSWindowDidChangeScreenNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didChangeScreenNotification/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowDidChangeScreenNotification"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didChangeScreenNotification/fragments"},{"op":"replace","value":"NSWindowDidResignKeyNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didResignKeyNotification/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowDidResignKeyNotification"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didResignKeyNotification/fragments"},{"op":"replace","value":"NSWindowWillBeginSheetNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1willBeginSheetNotification/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowWillBeginSheetNotification"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1willBeginSheetNotification/fragments"},{"op":"replace","value":"NSNotificationName","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSNotificationName/title"},{"op":"replace","value":"NSWindowDidEndLiveResizeNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didEndLiveResizeNotification/title"},{"op":"replace","value":[{"text":"NSWindowDidEndLiveResizeNotification","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didEndLiveResizeNotification/fragments"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didEndSheetNotification/title","op":"replace","value":"NSWindowDidEndSheetNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didEndSheetNotification/fragments","op":"replace","value":[{"kind":"identifier","text":"NSWindowDidEndSheetNotification"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didResizeNotification/title","op":"replace","value":"NSWindowDidResizeNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didResizeNotification/fragments","op":"replace","value":[{"kind":"identifier","text":"NSWindowDidResizeNotification"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didMiniaturizeNotification/title","op":"replace","value":"NSWindowDidMiniaturizeNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didMiniaturizeNotification/fragments","op":"replace","value":[{"text":"NSWindowDidMiniaturizeNotification","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didBecomeKeyNotification/title","op":"replace","value":"NSWindowDidBecomeKeyNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didBecomeKeyNotification/fragments","op":"replace","value":[{"kind":"identifier","text":"NSWindowDidBecomeKeyNotification"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSNotification/abstract","op":"replace","value":[{"type":"text","text":"A container for information broadcast through a notification center to all registered observers."}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didExposeNotification/title","op":"replace","value":"NSWindowDidExposeNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didExposeNotification/fragments","op":"replace","value":[{"text":"NSWindowDidExposeNotification","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didUpdateNotification/title","op":"replace","value":"NSWindowDidUpdateNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didUpdateNotification/fragments","op":"replace","value":[{"kind":"identifier","text":"NSWindowDidUpdateNotification"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1willCloseNotification/title","op":"replace","value":"NSWindowWillCloseNotification"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1willCloseNotification/fragments","op":"replace","value":[{"kind":"identifier","text":"NSWindowWillCloseNotification"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}