{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nswindow/didupdatenotification"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nswindow/didupdatenotification"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/didBecomeKeyNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didBecomeMainNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didChangeScreenNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didChangeScreenProfileNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didDeminiaturizeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didEndSheetNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didEndLiveResizeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didExposeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didMiniaturizeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didMoveNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didResignKeyNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didResignMainNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didResizeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/willBeginSheetNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/willCloseNotification"],"generated":true,"anchor":"Notifications","title":"Notifications"}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didUpdateNotification","interfaceLanguage":"swift"},"abstract":[{"text":"A notification that the window object received an update message.","type":"text"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Type Property","symbolKind":"property","platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateNotification"},{"kind":"text","text":": "},{"text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Name","preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier"}],"extendedModule":"AppKit","title":"didUpdateNotification","role":"symbol","externalID":"c:@NSWindowDidUpdateNotification","modules":[{"name":"AppKit"}],"navigatorTitle":[{"text":"NSWindowDidUpdateNotification","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdateNotification","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The notification object is the "},{"type":"codeVoice","code":"NSWindow"},{"type":"text","text":" object that received the "},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/update()","type":"reference"},{"type":"text","text":" message. This notification doesn’t contain a "},{"type":"codeVoice","code":"userInfo"},{"type":"text","text":" dictionary."}]}]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSWindow/didBecomeKeyNotification":{"title":"didBecomeKeyNotification","navigatorTitle":[{"text":"NSWindowDidBecomeKeyNotification","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didBecomeKeyNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"abstract":[{"type":"text","text":"A notification that the window object became the key window."}],"kind":"symbol","url":"/documentation/appkit/nswindow/didbecomekeynotification","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didBecomeKeyNotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didDeminiaturizeNotification":{"title":"didDeminiaturizeNotification","navigatorTitle":[{"text":"NSWindowDidDeminiaturizeNotification","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didDeminiaturizeNotification"},{"text":": ","kind":"text"},{"text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Name","preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier"}],"abstract":[{"text":"A notification that the window is no longer minimized.","type":"text"}],"kind":"symbol","url":"/documentation/appkit/nswindow/diddeminiaturizenotification","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didDeminiaturizeNotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didExposeNotification":{"title":"didExposeNotification","role":"symbol","url":"/documentation/appkit/nswindow/didexposenotification","navigatorTitle":[{"text":"NSWindowDidExposeNotification","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"A notification that a window exposed a portion of its nonretained content.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didExposeNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Name","preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didExposeNotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didResizeNotification":{"title":"didResizeNotification","role":"symbol","url":"/documentation/appkit/nswindow/didresizenotification","navigatorTitle":[{"text":"NSWindowDidResizeNotification","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"A notification that the window object size changed.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didResizeNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didResizeNotification"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didResignMainNotification":{"type":"topic","title":"didResignMainNotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didResignMainNotification","abstract":[{"type":"text","text":"A notification that the window object resigned its status as main window."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindowDidResignMainNotification"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didResignMainNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"url":"/documentation/appkit/nswindow/didresignmainnotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didMiniaturizeNotification":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didMiniaturizeNotification","role":"symbol","type":"topic","url":"/documentation/appkit/nswindow/didminiaturizenotification","navigatorTitle":[{"text":"NSWindowDidMiniaturizeNotification","kind":"identifier"}],"abstract":[{"type":"text","text":"A notification that the window object minimized."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didMiniaturizeNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"title":"didMiniaturizeNotification","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didMoveNotification":{"type":"topic","title":"didMoveNotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didMoveNotification","abstract":[{"type":"text","text":"A notification that the window object moved."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NSWindowDidMoveNotification","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didMoveNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"url":"/documentation/appkit/nswindow/didmovenotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/willBeginSheetNotification":{"abstract":[{"type":"text","text":"A notification that the window object is about to open a sheet."}],"type":"topic","title":"willBeginSheetNotification","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willBeginSheetNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/willBeginSheetNotification","role":"symbol","url":"/documentation/appkit/nswindow/willbeginsheetnotification","navigatorTitle":[{"text":"NSWindowWillBeginSheetNotification","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didChangeScreenProfileNotification":{"type":"topic","title":"didChangeScreenProfileNotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didChangeScreenProfileNotification","abstract":[{"type":"text","text":"A notification that the screen containing the window changed."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NSWindowDidChangeScreenProfileNotification","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didChangeScreenProfileNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"url":"/documentation/appkit/nswindow/didchangescreenprofilenotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didBecomeMainNotification":{"type":"topic","title":"didBecomeMainNotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didBecomeMainNotification","abstract":[{"type":"text","text":"A notification that the window object became the main window."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindowDidBecomeMainNotification"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didBecomeMainNotification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier","text":"NSNotification"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier","text":"Name"}],"url":"/documentation/appkit/nswindow/didbecomemainnotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/update()":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Updates the window."}],"kind":"symbol","url":"/documentation/appkit/nswindow/update()","title":"update()","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/update()","navigatorTitle":[{"text":"update","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"update","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSNotification":{"fragments":[{"text":"class ","kind":"text"},{"text":"NSNotification","kind":"identifier"}],"url":"/documentation/foundation/nsnotification","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSNotification","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"An object containing information broadcast to registered observers that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"title":"NSNotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/willCloseNotification":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSWindowWillCloseNotification","kind":"identifier"}],"url":"/documentation/appkit/nswindow/willclosenotification","title":"willCloseNotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/willCloseNotification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willCloseNotification"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A notification that the window object is about to close."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didResignKeyNotification":{"title":"didResignKeyNotification","navigatorTitle":[{"kind":"identifier","text":"NSWindowDidResignKeyNotification"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didResignKeyNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"abstract":[{"type":"text","text":"A notification that the window object resigned its status as key window."}],"kind":"symbol","url":"/documentation/appkit/nswindow/didresignkeynotification","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didResignKeyNotification"},"doc://com.externally.resolved.symbol/c:@T@NSNotificationName":{"abstract":[{"text":"A structure that defines the name of a notification.","type":"text"}],"type":"topic","identifier":"doc://com.externally.resolved.symbol/c:@T@NSNotificationName","url":"/documentation/foundation/nsnotification/name","kind":"symbol","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"NSNotification.Name"}],"role":"symbol","title":"NSNotification.Name"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didEndLiveResizeNotification":{"abstract":[{"type":"text","text":"A notification that the user resized the window object."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didEndLiveResizeNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"url":"/documentation/appkit/nswindow/didendliveresizenotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didEndLiveResizeNotification","role":"symbol","navigatorTitle":[{"text":"NSWindowDidEndLiveResizeNotification","kind":"identifier"}],"type":"topic","kind":"symbol","title":"didEndLiveResizeNotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didEndSheetNotification":{"abstract":[{"type":"text","text":"A notification that the window object closed an attached sheet."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"didEndSheetNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"url":"/documentation/appkit/nswindow/didendsheetnotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didEndSheetNotification","role":"symbol","navigatorTitle":[{"text":"NSWindowDidEndSheetNotification","kind":"identifier"}],"type":"topic","kind":"symbol","title":"didEndSheetNotification"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didUpdateNotification":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didUpdateNotification","role":"symbol","type":"topic","url":"/documentation/appkit/nswindow/didupdatenotification","navigatorTitle":[{"text":"NSWindowDidUpdateNotification","kind":"identifier"}],"abstract":[{"type":"text","text":"A notification that the window object received an update message."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didUpdateNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"title":"didUpdateNotification","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/didChangeScreenNotification":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didChangeScreenNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Name","preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/didChangeScreenNotification","abstract":[{"text":"A notification that a portion of the window object’s frame moved onto or off of a screen.","type":"text"}],"kind":"symbol","title":"didChangeScreenNotification","role":"symbol","navigatorTitle":[{"text":"NSWindowDidChangeScreenNotification","kind":"identifier"}],"url":"/documentation/appkit/nswindow/didchangescreennotification"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"op":"replace","value":[{"beta":false,"unavailable":false,"deprecated":false,"name":"macOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Global Variable","path":"/metadata/roleHeading"},{"op":"replace","value":"NSWindowDidUpdateNotification","path":"/metadata/title"},{"op":"replace","value":"var","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowDidUpdateNotification"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/didBecomeKeyNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didBecomeMainNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didChangeScreenNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didChangeScreenProfileNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didDeminiaturizeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didEndSheetNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didEndLiveResizeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didExposeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didMiniaturizeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didMoveNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didResignKeyNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didResignMainNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/didResizeNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/willBeginSheetNotification","doc://com.apple.appkit/documentation/AppKit/NSWindow/willCloseNotification"],"title":"Notifications","anchor":"Notifications"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"NSNotificationName","identifier":"doc://com.externally.resolved.symbol/c:@T@NSNotificationName","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"NSWindowDidUpdateNotification","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","value":"NSWindowDidBecomeKeyNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didBecomeKeyNotification/title"},{"op":"replace","value":[{"text":"NSWindowDidBecomeKeyNotification","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didBecomeKeyNotification/fragments"},{"op":"replace","value":"NSWindowDidDeminiaturizeNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didDeminiaturizeNotification/title"},{"op":"replace","value":[{"text":"NSWindowDidDeminiaturizeNotification","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didDeminiaturizeNotification/fragments"},{"op":"replace","value":"NSWindowDidExposeNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didExposeNotification/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowDidExposeNotification"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didExposeNotification/fragments"},{"op":"replace","value":"NSWindowDidResizeNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didResizeNotification/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowDidResizeNotification"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didResizeNotification/fragments"},{"op":"replace","value":"NSWindowDidResignMainNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didResignMainNotification/title"},{"op":"replace","value":[{"text":"NSWindowDidResignMainNotification","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didResignMainNotification/fragments"},{"op":"replace","value":"NSWindowDidMiniaturizeNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didMiniaturizeNotification/title"},{"op":"replace","value":[{"text":"NSWindowDidMiniaturizeNotification","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didMiniaturizeNotification/fragments"},{"op":"replace","value":"NSWindowDidMoveNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didMoveNotification/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowDidMoveNotification"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didMoveNotification/fragments"},{"op":"replace","value":"NSWindowWillBeginSheetNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1willBeginSheetNotification/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowWillBeginSheetNotification"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1willBeginSheetNotification/fragments"},{"op":"replace","value":"NSWindowDidChangeScreenProfileNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didChangeScreenProfileNotification/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowDidChangeScreenProfileNotification"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didChangeScreenProfileNotification/fragments"},{"op":"replace","value":"NSWindowDidBecomeMainNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didBecomeMainNotification/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowDidBecomeMainNotification"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didBecomeMainNotification/fragments"},{"op":"replace","value":"update","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1update()/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"update"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1update()/fragments"},{"op":"replace","value":[{"type":"text","text":"A container for information broadcast through a notification center to all registered observers."}],"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSNotification/abstract"},{"op":"replace","value":"NSWindowWillCloseNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1willCloseNotification/title"},{"op":"replace","value":[{"text":"NSWindowWillCloseNotification","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1willCloseNotification/fragments"},{"op":"replace","value":"NSWindowDidResignKeyNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didResignKeyNotification/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowDidResignKeyNotification"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didResignKeyNotification/fragments"},{"op":"replace","value":"NSNotificationName","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSNotificationName/title"},{"op":"replace","value":"NSWindowDidEndLiveResizeNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didEndLiveResizeNotification/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowDidEndLiveResizeNotification"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didEndLiveResizeNotification/fragments"},{"op":"replace","value":"NSWindowDidEndSheetNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didEndSheetNotification/title"},{"op":"replace","value":[{"text":"NSWindowDidEndSheetNotification","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didEndSheetNotification/fragments"},{"op":"replace","value":"NSWindow","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle"},{"op":"replace","value":"NSWindowDidUpdateNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didUpdateNotification/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowDidUpdateNotification"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didUpdateNotification/fragments"},{"op":"replace","value":"NSWindowDidChangeScreenNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didChangeScreenNotification/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowDidChangeScreenNotification"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1didChangeScreenNotification/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}