{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/hasDynamicDepthLimit","interfaceLanguage":"swift"},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/depthLimit","doc://com.apple.appkit/documentation/AppKit/NSWindow/defaultDepthLimit","doc://com.apple.appkit/documentation/AppKit/NSWindow/windowNumber","doc://com.apple.appkit/documentation/AppKit/NSWindow/windowNumbers(options:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/deviceDescription","doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey","doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeVisibleWithoutLogin","doc://com.apple.appkit/documentation/AppKit/NSWindow/sharingType-swift.property","doc://com.apple.appkit/documentation/AppKit/NSWindow/backingType","doc://com.apple.appkit/documentation/AppKit/NSWindow/displayLink(target:selector:)"],"anchor":"Accessing-Window-Information","title":"Accessing Window Information","generated":true}],"variants":[{"paths":["/documentation/appkit/nswindow/hasdynamicdepthlimit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nswindow/hasdynamicdepthlimit"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"hasDynamicDepthLimit","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasDynamicDepthLimit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"roleHeading":"Instance Property","platforms":[{"beta":false,"name":"macOS","deprecated":false,"unavailable":false}],"externalID":"c:objc(cs)NSWindow(py)hasDynamicDepthLimit","modules":[{"name":"AppKit"}],"title":"hasDynamicDepthLimit"},"sections":[],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the window’s depth limit can change to match the depth of the screen it’s on."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasDynamicDepthLimit","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]},{"content":[{"anchor":"Discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The value of this property is ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference","isActive":true},{"text":" when the window has a dynamic depth limit; otherwise, ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference","isActive":true},{"text":". When the value of ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/hasDynamicDepthLimit","type":"reference","isActive":true},{"text":" is ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference","isActive":true},{"text":", the window uses either its preset depth limit or the default depth limit. A different, and non-dynamic, depth limit can be set using the ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/depthLimit","type":"reference","isActive":true},{"text":" property.","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.documentation/documentation/swift/false":{"title":"false","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/false","role":"symbol","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","url":"/documentation/swift/false"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/depthLimit":{"title":"depthLimit","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/depthLimit","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"depthLimit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier","text":"NSWindow"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSWindowDepth","text":"Depth","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nswindow/depthlimit","kind":"symbol","abstract":[{"type":"text","text":"The depth limit of the window."}],"navigatorTitle":[{"text":"depthLimit","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/sharingType-swift.property":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/sharingType-swift.property","abstract":[{"text":"A Boolean value that indicates the level of access other processes have to the window’s content.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"sharingType","kind":"identifier"}],"url":"/documentation/appkit/nswindow/sharingtype-swift.property","title":"sharingType","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharingType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSWindowSharingType","text":"SharingType","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeVisibleWithoutLogin":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeVisibleWithoutLogin","abstract":[{"text":"A Boolean value that indicates whether the window can be displayed at the login window.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"canBecomeVisibleWithoutLogin"}],"url":"/documentation/appkit/nswindow/canbecomevisiblewithoutlogin","title":"canBecomeVisibleWithoutLogin","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canBecomeVisibleWithoutLogin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/defaultDepthLimit":{"url":"/documentation/appkit/nswindow/defaultdepthlimit","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/defaultDepthLimit","abstract":[{"type":"text","text":"Returns the default depth limit for instances of "},{"code":"NSWindow","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"defaultDepthLimit","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultDepthLimit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSWindowDepth","text":"Depth","kind":"typeIdentifier"}],"title":"defaultDepthLimit"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/backingType":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/backingType","abstract":[{"text":"The window’s backing store type.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"backingType","kind":"identifier"}],"url":"/documentation/appkit/nswindow/backingtype","title":"backingType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backingType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSBackingStoreType","text":"BackingStoreType","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/hasDynamicDepthLimit":{"title":"hasDynamicDepthLimit","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/hasDynamicDepthLimit","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasDynamicDepthLimit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nswindow/hasdynamicdepthlimit","kind":"symbol","abstract":[{"type":"text","text":"A Boolean value that indicates whether the window’s depth limit can change to match the depth of the screen it’s on."}],"navigatorTitle":[{"kind":"identifier","text":"hasDynamicDepthLimit"}]},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/displayLink(target:selector:)":{"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayLink"},{"kind":"text","text":"("},{"kind":"externalParam","text":"target"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":", ","kind":"text"},{"text":"selector","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CADisplayLink","text":"CADisplayLink","kind":"typeIdentifier"}],"url":"/documentation/appkit/nswindow/displaylink(target:selector:)","role":"symbol","title":"displayLink(target:selector:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/displayLink(target:selector:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"displayLinkWithTarget:selector:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/windowNumbers(options:)":{"abstract":[{"text":"Returns the window numbers for all visible windows satisfying the specified options.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"windowNumbers"},{"text":"(","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSWindowNumberListOptions","text":"NumberListOptions","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"url":"/documentation/appkit/nswindow/windownumbers(options:)","role":"symbol","title":"windowNumbers(options:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/windowNumbers(options:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"windowNumbersWithOptions:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/deviceDescription":{"url":"/documentation/appkit/nswindow/devicedescription","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/deviceDescription","abstract":[{"type":"text","text":"A dictionary containing information about the window’s resolution, such as color, depth, and so on."}],"kind":"symbol","navigatorTitle":[{"text":"deviceDescription","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceDescription","kind":"identifier"},{"text":": [","kind":"text"},{"text":"NSDeviceDescriptionKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSDeviceDescriptionKey"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"title":"deviceDescription"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/windowNumber":{"url":"/documentation/appkit/nswindow/windownumber","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/windowNumber","abstract":[{"type":"text","text":"The window number of the window’s window device."}],"kind":"symbol","navigatorTitle":[{"text":"windowNumber","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"windowNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"windowNumber"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey":{"abstract":[{"text":"These constants are the keys for device description dictionaries.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSDeviceDescriptionKey"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey","url":"/documentation/appkit/nsdevicedescriptionkey","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSDeviceDescriptionKey"}],"role":"symbol","title":"NSDeviceDescriptionKey"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"deprecated":false,"name":"macOS","beta":false}],"path":"/metadata/platforms","op":"replace"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"hasDynamicDepthLimit","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"hasDynamicDepthLimit","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Accessing Window Information","anchor":"Accessing-Window-Information","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/depthLimit","doc://com.apple.appkit/documentation/AppKit/NSWindow/defaultDepthLimit","doc://com.apple.appkit/documentation/AppKit/NSWindow/windowNumber","doc://com.apple.appkit/documentation/AppKit/NSWindow/windowNumbers(options:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/deviceDescription","doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey","doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeVisibleWithoutLogin","doc://com.apple.appkit/documentation/AppKit/NSWindow/sharingType-swift.property","doc://com.apple.appkit/documentation/AppKit/NSWindow/backingType","doc://com.apple.appkit/documentation/AppKit/NSWindow/displayLink(target:selector:)"],"generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"hasDynamicDepthLimit","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title","value":"NSWindow"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments","value":[{"text":"NSWindow","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle","value":[{"text":"NSWindow","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1depthLimit/title","value":"depthLimit"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1depthLimit/fragments","value":[{"text":"depthLimit","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1sharingType-swift.property/title","value":"sharingType"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1sharingType-swift.property/fragments","value":[{"kind":"identifier","text":"sharingType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1canBecomeVisibleWithoutLogin/title","value":"canBecomeVisibleWithoutLogin"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1canBecomeVisibleWithoutLogin/fragments","value":[{"kind":"identifier","text":"canBecomeVisibleWithoutLogin"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1defaultDepthLimit/title","value":"defaultDepthLimit"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1defaultDepthLimit/fragments","value":[{"kind":"identifier","text":"defaultDepthLimit"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1backingType/title","value":"backingType"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1backingType/fragments","value":[{"text":"backingType","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1hasDynamicDepthLimit/title","value":"hasDynamicDepthLimit"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1hasDynamicDepthLimit/fragments","value":[{"kind":"identifier","text":"hasDynamicDepthLimit"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1displayLink(target:selector:)/title","value":"displayLinkWithTarget:selector:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1displayLink(target:selector:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"displayLinkWithTarget:selector:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1windowNumbers(options:)/title","value":"windowNumbersWithOptions:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1windowNumbers(options:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"windowNumbersWithOptions:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1deviceDescription/title","value":"deviceDescription"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1deviceDescription/fragments","value":[{"kind":"identifier","text":"deviceDescription"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1windowNumber/title","value":"windowNumber"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1windowNumber/fragments","value":[{"text":"windowNumber","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey/title","value":"NSDeviceDescriptionKey"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey/fragments","value":[{"text":"NSDeviceDescriptionKey","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey/navigatorTitle","value":[{"text":"NSDeviceDescriptionKey","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}