{"kind":"symbol","metadata":{"externalID":"c:objc(cs)NSWindow(py)hasShadow","modules":[{"name":"AppKit"}],"platforms":[{"deprecated":false,"beta":false,"unavailable":false,"name":"macOS"}],"title":"hasShadow","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"hasShadow","kind":"identifier"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasShadow","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"seeAlsoSections":[{"title":"Configuring the Window’s Appearance","generated":true,"anchor":"Configuring-the-Windows-Appearance","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/styleMask-swift.property","doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct","doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleFullScreen(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/worksWhenModal","doc://com.apple.appkit/documentation/AppKit/NSWindow/alphaValue","doc://com.apple.appkit/documentation/AppKit/NSWindow/backgroundColor","doc://com.apple.appkit/documentation/AppKit/NSWindow/colorSpace","doc://com.apple.appkit/documentation/AppKit/NSWindow/setDynamicDepthLimit(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/canHide","doc://com.apple.appkit/documentation/AppKit/NSWindow/isOnActiveSpace","doc://com.apple.appkit/documentation/AppKit/NSWindow/hidesOnDeactivate","doc://com.apple.appkit/documentation/AppKit/NSWindow/collectionBehavior-swift.property","doc://com.apple.appkit/documentation/AppKit/NSWindow/isOpaque","doc://com.apple.appkit/documentation/AppKit/NSWindow/invalidateShadow()","doc://com.apple.appkit/documentation/AppKit/NSWindow/autorecalculatesContentBorderThickness(for:)"]}],"sections":[],"abstract":[{"text":"A Boolean value that indicates whether the window has a shadow.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/hasShadow"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasShadow","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"The value of this property is ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference"},{"text":" when the window has a shadow; otherwise, ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference"},{"text":". If you change the value of this property, the window shadow is invalidated, forcing the window shadow to be recomputed.","type":"text"}]}]}],"variants":[{"paths":["/documentation/appkit/nswindow/hasshadow"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nswindow/hasshadow"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleFullScreen(_:)":{"navigatorTitle":[{"text":"toggleFullScreen:","kind":"identifier"}],"url":"/documentation/appkit/nswindow/togglefullscreen(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"toggleFullScreen"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleFullScreen(_:)","role":"symbol","type":"topic","abstract":[{"text":"Takes the window into or out of fullscreen mode,","type":"text"}],"title":"toggleFullScreen(_:)"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/alphaValue":{"role":"symbol","type":"topic","title":"alphaValue","navigatorTitle":[{"text":"alphaValue","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alphaValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"abstract":[{"text":"The window’s alpha value.","type":"text"}],"url":"/documentation/appkit/nswindow/alphavalue","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/alphaValue","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/isOnActiveSpace":{"navigatorTitle":[{"text":"onActiveSpace","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isOnActiveSpace","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","url":"/documentation/appkit/nswindow/isonactivespace","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/isOnActiveSpace","title":"isOnActiveSpace","abstract":[{"text":"A Boolean value that indicates whether the window is on the currently active space.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/invalidateShadow()":{"navigatorTitle":[{"text":"invalidateShadow","kind":"identifier"}],"abstract":[{"text":"Invalidates the window shadow so that it is recomputed based on the current window shape.","type":"text"}],"role":"symbol","title":"invalidateShadow()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidateShadow","kind":"identifier"},{"text":"()","kind":"text"}],"url":"/documentation/appkit/nswindow/invalidateshadow()","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/invalidateShadow()"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/hidesOnDeactivate":{"url":"/documentation/appkit/nswindow/hidesondeactivate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hidesOnDeactivate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the window is removed from the screen when its application becomes inactive."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"hidesOnDeactivate","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/hidesOnDeactivate","title":"hidesOnDeactivate"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/worksWhenModal":{"url":"/documentation/appkit/nswindow/workswhenmodal","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"worksWhenModal"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the window is able to receive keyboard and mouse events even when some other window is being run modally."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"worksWhenModal","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/worksWhenModal","title":"worksWhenModal"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/backgroundColor":{"navigatorTitle":[{"text":"backgroundColor","kind":"identifier"}],"abstract":[{"type":"text","text":"The color of the window’s background."}],"role":"symbol","title":"backgroundColor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"text":": ","kind":"text"},{"text":"NSColor","preciseIdentifier":"c:objc(cs)NSColor","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"url":"/documentation/appkit/nswindow/backgroundcolor","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/backgroundColor"},"doc://com.apple.documentation/documentation/swift/false":{"title":"false","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/false","role":"symbol","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","url":"/documentation/swift/false"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/collectionBehavior-swift.property":{"navigatorTitle":[{"kind":"identifier","text":"collectionBehavior"}],"abstract":[{"text":"A value that identifies the window’s behavior in window collections.","type":"text"}],"role":"symbol","title":"collectionBehavior","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"collectionBehavior","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSWindowCollectionBehavior","text":"CollectionBehavior"}],"url":"/documentation/appkit/nswindow/collectionbehavior-swift.property","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/collectionBehavior-swift.property"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/isOpaque":{"navigatorTitle":[{"text":"opaque","kind":"identifier"}],"abstract":[{"text":"A Boolean value that indicates whether the window is opaque.","type":"text"}],"role":"symbol","title":"isOpaque","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isOpaque","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"/documentation/appkit/nswindow/isopaque","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/isOpaque"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct":{"role":"symbol","abstract":[{"type":"text","text":"Constants that specify the style of a window, and that you can combine with the C bitwise OR operator."}],"title":"NSWindow.StyleMask","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StyleMask"}],"url":"/documentation/appkit/nswindow/stylemask-swift.struct","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleMask"}]},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/canHide":{"navigatorTitle":[{"text":"canHide","kind":"identifier"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the window can hide when its application becomes hidden."}],"role":"symbol","title":"canHide","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canHide"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"/documentation/appkit/nswindow/canhide","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/canHide"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/autorecalculatesContentBorderThickness(for:)":{"navigatorTitle":[{"kind":"identifier","text":"autorecalculatesContentBorderThicknessForEdge:"}],"abstract":[{"text":"Indicates whether the window calculates the thickness of a given border automatically.","type":"text"}],"role":"symbol","title":"autorecalculatesContentBorderThickness(for:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"autorecalculatesContentBorderThickness","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSRectEdge","text":"NSRectEdge"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"/documentation/appkit/nswindow/autorecalculatescontentborderthickness(for:)","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/autorecalculatesContentBorderThickness(for:)"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/setDynamicDepthLimit(_:)":{"navigatorTitle":[{"text":"setDynamicDepthLimit:","kind":"identifier"}],"abstract":[{"type":"text","text":"Sets a Boolean value that indicates whether the window’s depth limit can change to match the depth of the screen it’s on."}],"role":"symbol","title":"setDynamicDepthLimit(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setDynamicDepthLimit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/appkit/nswindow/setdynamicdepthlimit(_:)","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/setDynamicDepthLimit(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/styleMask-swift.property":{"navigatorTitle":[{"text":"styleMask","kind":"identifier"}],"abstract":[{"type":"text","text":"Flags that describe the window’s current style, such as if it’s resizable or in full-screen mode."}],"role":"symbol","title":"styleMask","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"styleMask"},{"text":": ","kind":"text"},{"text":"NSWindow","preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"StyleMask","preciseIdentifier":"c:@E@NSWindowStyleMask","kind":"typeIdentifier"}],"url":"/documentation/appkit/nswindow/stylemask-swift.property","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/styleMask-swift.property"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/colorSpace":{"navigatorTitle":[{"kind":"identifier","text":"colorSpace"}],"abstract":[{"text":"The window’s color space.","type":"text"}],"role":"symbol","title":"colorSpace","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"colorSpace","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSColorSpace","text":"NSColorSpace"},{"kind":"text","text":"?"}],"url":"/documentation/appkit/nswindow/colorspace","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/colorSpace"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/hasShadow":{"navigatorTitle":[{"text":"hasShadow","kind":"identifier"}],"abstract":[{"text":"A Boolean value that indicates whether the window has a shadow.","type":"text"}],"role":"symbol","title":"hasShadow","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasShadow","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"/documentation/appkit/nswindow/hasshadow","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/hasShadow"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"name":"macOS","beta":false,"deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"hasShadow","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"hasShadow"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Configuring-the-Windows-Appearance","generated":true,"title":"Configuring the Window’s Appearance","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/styleMask-swift.property","doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct","doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleFullScreen(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/worksWhenModal","doc://com.apple.appkit/documentation/AppKit/NSWindow/alphaValue","doc://com.apple.appkit/documentation/AppKit/NSWindow/backgroundColor","doc://com.apple.appkit/documentation/AppKit/NSWindow/colorSpace","doc://com.apple.appkit/documentation/AppKit/NSWindow/setDynamicDepthLimit(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/canHide","doc://com.apple.appkit/documentation/AppKit/NSWindow/isOnActiveSpace","doc://com.apple.appkit/documentation/AppKit/NSWindow/hidesOnDeactivate","doc://com.apple.appkit/documentation/AppKit/NSWindow/collectionBehavior-swift.property","doc://com.apple.appkit/documentation/AppKit/NSWindow/isOpaque","doc://com.apple.appkit/documentation/AppKit/NSWindow/invalidateShadow()","doc://com.apple.appkit/documentation/AppKit/NSWindow/autorecalculatesContentBorderThickness(for:)"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasShadow"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":"toggleFullScreen:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1toggleFullScreen(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toggleFullScreen:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1toggleFullScreen(_:)/fragments"},{"op":"replace","value":"alphaValue","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1alphaValue/title"},{"op":"replace","value":[{"text":"alphaValue","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1alphaValue/fragments"},{"op":"replace","value":"onActiveSpace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isOnActiveSpace/title"},{"op":"replace","value":[{"kind":"identifier","text":"onActiveSpace"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isOnActiveSpace/fragments"},{"op":"replace","value":"invalidateShadow","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1invalidateShadow()/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"invalidateShadow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1invalidateShadow()/fragments"},{"op":"replace","value":"hidesOnDeactivate","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1hidesOnDeactivate/title"},{"op":"replace","value":[{"text":"hidesOnDeactivate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1hidesOnDeactivate/fragments"},{"op":"replace","value":"worksWhenModal","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1worksWhenModal/title"},{"op":"replace","value":[{"text":"worksWhenModal","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1worksWhenModal/fragments"},{"op":"replace","value":"backgroundColor","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1backgroundColor/title"},{"op":"replace","value":[{"text":"backgroundColor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1backgroundColor/fragments"},{"op":"replace","value":"collectionBehavior","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1collectionBehavior-swift.property/title"},{"op":"replace","value":[{"kind":"identifier","text":"collectionBehavior"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1collectionBehavior-swift.property/fragments"},{"op":"replace","value":"opaque","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isOpaque/title"},{"op":"replace","value":[{"kind":"identifier","text":"opaque"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isOpaque/fragments"},{"op":"replace","value":"NSWindowStyleMask","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowStyleMask"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindowStyleMask"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/navigatorTitle"},{"op":"replace","value":"canHide","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1canHide/title"},{"op":"replace","value":[{"text":"canHide","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1canHide/fragments"},{"op":"replace","value":"autorecalculatesContentBorderThicknessForEdge:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1autorecalculatesContentBorderThickness(for:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"autorecalculatesContentBorderThicknessForEdge:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1autorecalculatesContentBorderThickness(for:)/fragments"},{"op":"replace","value":"setDynamicDepthLimit:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setDynamicDepthLimit(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDynamicDepthLimit:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setDynamicDepthLimit(_:)/fragments"},{"op":"replace","value":"styleMask","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1styleMask-swift.property/title"},{"op":"replace","value":[{"kind":"identifier","text":"styleMask"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1styleMask-swift.property/fragments"},{"op":"replace","value":"colorSpace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1colorSpace/title"},{"op":"replace","value":[{"kind":"identifier","text":"colorSpace"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1colorSpace/fragments"},{"op":"replace","value":"hasShadow","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1hasShadow/title"},{"op":"replace","value":[{"kind":"identifier","text":"hasShadow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1hasShadow/fragments"},{"op":"replace","value":"NSWindow","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}