{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidateCursorRects"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"view"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSView","text":"NSView","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView"},{"text":")","kind":"text"}],"platforms":["macOS"]}]},{"parameters":[{"name":"view","content":[{"type":"paragraph","inlineContent":[{"text":"The view in the window’s view hierarchy.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If the window is current the key window, window resets the cursor rectangles immediately."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nswindow/invalidatecursorrects(for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nswindow/invalidatecursorrects(for:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/invalidateCursorRects(for:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"method","title":"invalidateCursorRects(for:)","modules":[{"name":"AppKit"}],"extendedModule":"AppKit","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"invalidateCursorRects","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)NSWindow(im)invalidateCursorRectsForView:","navigatorTitle":[{"kind":"identifier","text":"invalidateCursorRectsForView:"}],"platforms":[{"beta":false,"name":"macOS","unavailable":false,"deprecated":false}]},"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSView/resetCursorRects()"],"anchor":"Related-Documentation"},{"generated":true,"title":"Managing Cursor Rectangles","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/areCursorRectsEnabled","doc://com.apple.appkit/documentation/AppKit/NSWindow/enableCursorRects()","doc://com.apple.appkit/documentation/AppKit/NSWindow/disableCursorRects()","doc://com.apple.appkit/documentation/AppKit/NSWindow/discardCursorRects()","doc://com.apple.appkit/documentation/AppKit/NSWindow/resetCursorRects()"],"anchor":"Managing-Cursor-Rectangles"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Marks as invalid the cursor rectangles of a given view object in the window, so they’ll be set up again when the window becomes key."}],"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/disableCursorRects()":{"abstract":[{"type":"text","text":"Disables all cursor rectangle management within the window."}],"navigatorTitle":[{"kind":"identifier","text":"disableCursorRects"}],"title":"disableCursorRects()","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/disableCursorRects()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableCursorRects"},{"kind":"text","text":"()"}],"url":"/documentation/appkit/nswindow/disablecursorrects()","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSView/resetCursorRects()":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetCursorRects"},{"kind":"text","text":"()"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/resetCursorRects()","navigatorTitle":[{"kind":"identifier","text":"resetCursorRects"}],"abstract":[{"text":"Overridden by subclasses to define their default cursor rectangles.","type":"text"}],"type":"topic","title":"resetCursorRects()","url":"/documentation/appkit/nsview/resetcursorrects()"},"doc://com.apple.appkit/documentation/AppKit/NSView":{"abstract":[{"text":"The infrastructure for drawing, printing, and handling events in an app.","type":"text"}],"url":"/documentation/appkit/nsview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","title":"NSView","navigatorTitle":[{"kind":"identifier","text":"NSView"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/enableCursorRects()":{"abstract":[{"type":"text","text":"Reenables cursor rectangle management within the window after a "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/disableCursorRects()"},{"type":"text","text":" message."}],"navigatorTitle":[{"kind":"identifier","text":"enableCursorRects"}],"title":"enableCursorRects()","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/enableCursorRects()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableCursorRects"},{"kind":"text","text":"()"}],"url":"/documentation/appkit/nswindow/enablecursorrects()","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/areCursorRectsEnabled":{"abstract":[{"type":"text","text":"A Boolean value that indicates whether the window’s cursor rectangles are enabled."}],"navigatorTitle":[{"kind":"identifier","text":"areCursorRectsEnabled"}],"title":"areCursorRectsEnabled","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/areCursorRectsEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"areCursorRectsEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"/documentation/appkit/nswindow/arecursorrectsenabled","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/invalidateCursorRects(for:)":{"url":"/documentation/appkit/nswindow/invalidatecursorrects(for:)","title":"invalidateCursorRects(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidateCursorRects"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSView","preciseIdentifier":"c:objc(cs)NSView"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"invalidateCursorRectsForView:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/invalidateCursorRects(for:)","abstract":[{"text":"Marks as invalid the cursor rectangles of a given view object in the window, so they’ll be set up again when the window becomes key.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/discardCursorRects()":{"abstract":[{"type":"text","text":"Invalidates all cursor rectangles in the window."}],"navigatorTitle":[{"kind":"identifier","text":"discardCursorRects"}],"title":"discardCursorRects()","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/discardCursorRects()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"discardCursorRects"},{"kind":"text","text":"()"}],"url":"/documentation/appkit/nswindow/discardcursorrects()","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/resetCursorRects()":{"abstract":[{"type":"text","text":"Clears the window’s cursor rectangles and the cursor rectangles of the "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView"},{"type":"text","text":" objects in its view hierarchy."}],"navigatorTitle":[{"kind":"identifier","text":"resetCursorRects"}],"title":"resetCursorRects()","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/resetCursorRects()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetCursorRects"},{"kind":"text","text":"()"}],"url":"/documentation/appkit/nswindow/resetcursorrects()","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"name":"macOS","unavailable":false,"deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"invalidateCursorRectsForView:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"invalidateCursorRectsForView:","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSView/resetCursorRects()"]},{"generated":true,"title":"Managing Cursor Rectangles","anchor":"Managing-Cursor-Rectangles","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/areCursorRectsEnabled","doc://com.apple.appkit/documentation/AppKit/NSWindow/enableCursorRects()","doc://com.apple.appkit/documentation/AppKit/NSWindow/disableCursorRects()","doc://com.apple.appkit/documentation/AppKit/NSWindow/discardCursorRects()","doc://com.apple.appkit/documentation/AppKit/NSWindow/resetCursorRects()"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"invalidateCursorRectsForView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","text":"NSView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"view"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"]}]}},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The view in the window’s view hierarchy."}],"type":"paragraph"}],"name":"view"}]}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1disableCursorRects()/title","op":"replace","value":"disableCursorRects"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1disableCursorRects()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"disableCursorRects","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1resetCursorRects()/title","op":"replace","value":"resetCursorRects"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1resetCursorRects()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"resetCursorRects","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title","op":"replace","value":"NSView"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments","op":"replace","value":[{"kind":"identifier","text":"NSView"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSView"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1enableCursorRects()/title","op":"replace","value":"enableCursorRects"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1enableCursorRects()/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableCursorRects"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1areCursorRectsEnabled/title","op":"replace","value":"areCursorRectsEnabled"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1areCursorRectsEnabled/fragments","op":"replace","value":[{"kind":"identifier","text":"areCursorRectsEnabled"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1invalidateCursorRects(for:)/title","op":"replace","value":"invalidateCursorRectsForView:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1invalidateCursorRects(for:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"invalidateCursorRectsForView:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1discardCursorRects()/title","op":"replace","value":"discardCursorRects"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1discardCursorRects()/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"discardCursorRects"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1resetCursorRects()/title","op":"replace","value":"resetCursorRects"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1resetCursorRects()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"resetCursorRects","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title","op":"replace","value":"NSWindow"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments","op":"replace","value":[{"text":"NSWindow","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle","op":"replace","value":[{"text":"NSWindow","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}