{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isZoomable","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This property is key-value coding compliant."}]}],"kind":"content"}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/isZoomable","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"abstract":[{"type":"text","text":"A Boolean value that indicates whether the window allows zooming."}],"kind":"symbol","sections":[],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/hasCloseBox","doc://com.apple.appkit/documentation/AppKit/NSWindow/hasTitleBar","doc://com.apple.appkit/documentation/AppKit/NSWindow/isModalPanel","doc://com.apple.appkit/documentation/AppKit/NSWindow/isFloatingPanel","doc://com.apple.appkit/documentation/AppKit/NSWindow/isResizable","doc://com.apple.appkit/documentation/AppKit/NSWindow/isMiniaturizable","doc://com.apple.appkit/documentation/AppKit/NSWindow/orderedIndex"],"anchor":"Getting-Information-About-Scripting-Attributes","title":"Getting Information About Scripting Attributes"}],"variants":[{"paths":["/documentation/appkit/nswindow/iszoomable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nswindow/iszoomable"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"platforms":[{"deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"modules":[{"name":"AppKit"}],"symbolKind":"property","externalID":"c:objc(cs)NSWindow(py)zoomable","extendedModule":"AppKit","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isZoomable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","roleHeading":"Instance Property","title":"isZoomable","navigatorTitle":[{"kind":"identifier","text":"zoomable"}]},"references":{"doc://com.apple.appkit/documentation/AppKit/NSWindow/hasCloseBox":{"title":"hasCloseBox","kind":"symbol","navigatorTitle":[{"text":"hasCloseBox","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/hasCloseBox","type":"topic","url":"/documentation/appkit/nswindow/hasclosebox","abstract":[{"type":"text","text":"A Boolean value that indicates if the window has a close box."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasCloseBox","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/isResizable":{"title":"isResizable","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/isResizable","abstract":[{"text":"A Boolean value that indicates if the user can resize the window.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isResizable"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"resizable","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"/documentation/appkit/nswindow/isresizable"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/isMiniaturizable":{"title":"isMiniaturizable","kind":"symbol","navigatorTitle":[{"text":"miniaturizable","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/isMiniaturizable","type":"topic","url":"/documentation/appkit/nswindow/isminiaturizable","abstract":[{"type":"text","text":"A Boolean value that indicates whether the window can minimize."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isMiniaturizable","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/isFloatingPanel":{"navigatorTitle":[{"text":"floatingPanel","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/isFloatingPanel","abstract":[{"text":"A Boolean value that indicates whether the window is a floating panel.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFloatingPanel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"/documentation/appkit/nswindow/isfloatingpanel","title":"isFloatingPanel","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/isModalPanel":{"title":"isModalPanel","kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/isModalPanel","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isModalPanel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"modalPanel","kind":"identifier"}],"role":"symbol","url":"/documentation/appkit/nswindow/ismodalpanel","abstract":[{"type":"text","text":"A Boolean value that indicates whether the window is a modal panel."}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/orderedIndex":{"title":"orderedIndex","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/orderedIndex","abstract":[{"text":"The zero-based position of the window, based on its order from front to back among all visible application windows.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderedIndex"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"orderedIndex","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"/documentation/appkit/nswindow/orderedindex"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/isZoomable":{"navigatorTitle":[{"text":"zoomable","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/isZoomable","abstract":[{"text":"A Boolean value that indicates whether the window allows zooming.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isZoomable","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"/documentation/appkit/nswindow/iszoomable","title":"isZoomable","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/hasTitleBar":{"title":"hasTitleBar","kind":"symbol","navigatorTitle":[{"text":"hasTitleBar","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/hasTitleBar","type":"topic","url":"/documentation/appkit/nswindow/hastitlebar","abstract":[{"type":"text","text":"A Boolean value that indicates if the window has a title bar."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasTitleBar","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"macOS","deprecated":false,"unavailable":false,"beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"zoomable","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"zoomable"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/hasCloseBox","doc://com.apple.appkit/documentation/AppKit/NSWindow/hasTitleBar","doc://com.apple.appkit/documentation/AppKit/NSWindow/isModalPanel","doc://com.apple.appkit/documentation/AppKit/NSWindow/isFloatingPanel","doc://com.apple.appkit/documentation/AppKit/NSWindow/isResizable","doc://com.apple.appkit/documentation/AppKit/NSWindow/isMiniaturizable","doc://com.apple.appkit/documentation/AppKit/NSWindow/orderedIndex"],"title":"Getting Information About Scripting Attributes","generated":true,"anchor":"Getting-Information-About-Scripting-Attributes"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":", ","kind":"text"},{"text":"getter","kind":"keyword"},{"text":"=","kind":"text"},{"text":"isZoomable","kind":"identifier"},{"text":") ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"zoomable","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"value":"hasCloseBox","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1hasCloseBox/title"},{"value":[{"text":"hasCloseBox","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1hasCloseBox/fragments"},{"value":"resizable","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isResizable/title"},{"value":[{"kind":"identifier","text":"resizable"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isResizable/fragments"},{"value":"miniaturizable","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isMiniaturizable/title"},{"value":[{"text":"miniaturizable","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isMiniaturizable/fragments"},{"value":"floatingPanel","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isFloatingPanel/title"},{"value":[{"text":"floatingPanel","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isFloatingPanel/fragments"},{"value":"modalPanel","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isModalPanel/title"},{"value":[{"kind":"identifier","text":"modalPanel"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isModalPanel/fragments"},{"value":"orderedIndex","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1orderedIndex/title"},{"value":[{"kind":"identifier","text":"orderedIndex"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1orderedIndex/fragments"},{"value":"NSWindow","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title"},{"value":[{"text":"NSWindow","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments"},{"value":[{"text":"NSWindow","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle"},{"value":"zoomable","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isZoomable/title"},{"value":[{"kind":"identifier","text":"zoomable"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isZoomable/fragments"},{"value":"hasTitleBar","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1hasTitleBar/title"},{"value":[{"text":"hasTitleBar","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1hasTitleBar/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}