{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nswindow/parent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nswindow/parent"]}],"metadata":{"externalID":"c:objc(cs)NSWindow(py)parentWindow","role":"symbol","symbolKind":"property","platforms":[{"name":"macOS","beta":false,"deprecated":false,"unavailable":false}],"title":"parent","modules":[{"name":"AppKit"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSWindow","preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"parentWindow","kind":"identifier"}]},"abstract":[{"text":"The parent window to which the window is attached as a child.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"This property should be set from a subclass when it is overridden by a subclass’s implementation. It should not be set otherwise.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that calling "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/orderOut(_:)","isActive":true},{"type":"text","text":" on a child window causes the window to be removed from its parent window before it is itself removed."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/parent","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"seeAlsoSections":[{"anchor":"Managing-Attached-Windows","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/childWindows","doc://com.apple.appkit/documentation/AppKit/NSWindow/addChildWindow(_:ordered:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/removeChildWindow(_:)"],"title":"Managing Attached Windows"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSWindow/childWindows":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"childWindows"},{"text":": [","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow"},{"text":"]?","kind":"text"}],"role":"symbol","title":"childWindows","url":"/documentation/appkit/nswindow/childwindows","kind":"symbol","abstract":[{"text":"An array of the window’s attached child windows.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"childWindows","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/childWindows"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/parent":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parent","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier","text":"NSWindow"},{"kind":"text","text":"?"}],"role":"symbol","title":"parent","url":"/documentation/appkit/nswindow/parent","kind":"symbol","abstract":[{"text":"The parent window to which the window is attached as a child.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"parentWindow"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/parent"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/orderOut(_:)":{"role":"symbol","title":"orderOut(_:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/orderOut(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"orderOut","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"orderOut:"}],"url":"/documentation/appkit/nswindow/orderout(_:)","abstract":[{"type":"text","text":"Removes the window from the screen list, which hides the window."}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/removeChildWindow(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeChildWindow"},{"text":"(","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"removeChildWindow:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/removeChildWindow(_:)","url":"/documentation/appkit/nswindow/removechildwindow(_:)","kind":"symbol","title":"removeChildWindow(_:)","abstract":[{"text":"Detaches a given child window from the window.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/addChildWindow(_:ordered:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addChildWindow"},{"text":"(","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow"},{"text":", ","kind":"text"},{"text":"ordered","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier","text":"NSWindow"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSWindowOrderingMode","kind":"typeIdentifier","text":"OrderingMode"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"addChildWindow:ordered:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/addChildWindow(_:ordered:)","url":"/documentation/appkit/nswindow/addchildwindow(_:ordered:)","kind":"symbol","title":"addChildWindow(_:ordered:)","abstract":[{"text":"Adds a given window as a child window of the window.","type":"text"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"unavailable":false,"deprecated":false,"name":"macOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"parentWindow","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"parentWindow"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Managing Attached Windows","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/childWindows","doc://com.apple.appkit/documentation/AppKit/NSWindow/addChildWindow(_:ordered:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/removeChildWindow(_:)"],"anchor":"Managing-Attached-Windows"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"weak"},{"kind":"text","text":") "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","kind":"typeIdentifier","text":"NSWindow","preciseIdentifier":"c:objc(cs)NSWindow"},{"kind":"text","text":" * "},{"kind":"identifier","text":"parentWindow"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1childWindows/title","value":"childWindows"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1childWindows/fragments","value":[{"text":"childWindows","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title","value":"NSWindow"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments","value":[{"kind":"identifier","text":"NSWindow"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle","value":[{"text":"NSWindow","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1parent/title","value":"parentWindow"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1parent/fragments","value":[{"kind":"identifier","text":"parentWindow"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1orderOut(_:)/title","value":"orderOut:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1orderOut(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"orderOut:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1removeChildWindow(_:)/title","value":"removeChildWindow:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1removeChildWindow(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"removeChildWindow:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1addChildWindow(_:ordered:)/title","op":"replace","value":"addChildWindow:ordered:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1addChildWindow(_:ordered:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addChildWindow:ordered:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}