{"seeAlsoSections":[{"anchor":"Managing-Window-Frames-in-User-Defaults","title":"Managing Window Frames in User Defaults","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameUsingName(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameUsingName(_:force:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/saveFrame(usingName:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameAutosaveName(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/frameAutosaveName-swift.property","doc://com.apple.appkit/documentation/AppKit/NSWindow/FrameAutosaveName-swift.typealias","doc://com.apple.appkit/documentation/AppKit/NSWindow/frameDescriptor","doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrame(from:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/PersistableFrameDescriptor"],"generated":true}],"abstract":[{"type":"text","text":"Removes the frame data stored under a given name from the application’s user defaults."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"usingName"},{"kind":"text","text":" "},{"kind":"internalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow"},{"text":".","kind":"text"},{"text":"FrameAutosaveName","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/FrameAutosaveName-swift.typealias","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSWindowFrameAutosaveName"},{"text":")","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"name","content":[{"inlineContent":[{"text":"The name of the frame to remove.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"paths":["/documentation/appkit/nswindow/removeframe(usingname:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nswindow/removeframe(usingname:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"AppKit"}],"roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"usingName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow"},{"text":".","kind":"text"},{"text":"FrameAutosaveName","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSWindowFrameAutosaveName"},{"text":")","kind":"text"}],"title":"removeFrame(usingName:)","platforms":[{"name":"macOS","deprecated":false,"unavailable":false,"beta":false}],"externalID":"c:objc(cs)NSWindow(cm)removeFrameUsingName:","navigatorTitle":[{"text":"removeFrameUsingName:","kind":"identifier"}],"symbolKind":"method","role":"symbol"},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/removeFrame(usingName:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit/NSWindow/frameDescriptor":{"url":"/documentation/appkit/nswindow/framedescriptor","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"stringWithSavedFrame"}],"role":"symbol","type":"topic","title":"frameDescriptor","abstract":[{"text":"A string representation of the window’s frame rectangle.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameDescriptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSWindow","preciseIdentifier":"c:objc(cs)NSWindow"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"PersistableFrameDescriptor","preciseIdentifier":"c:@T@NSWindowPersistableFrameDescriptor"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/frameDescriptor"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/PersistableFrameDescriptor":{"role":"symbol","abstract":[{"type":"text","text":"The type of a window’s frame descriptor."}],"title":"NSWindow.PersistableFrameDescriptor","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PersistableFrameDescriptor"}],"url":"/documentation/appkit/nswindow/persistableframedescriptor","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/PersistableFrameDescriptor","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PersistableFrameDescriptor"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/removeFrame(usingName:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/removeFrame(usingName:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"usingName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSWindowFrameAutosaveName","text":"FrameAutosaveName"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"type":"text","text":"Removes the frame data stored under a given name from the application’s user defaults."}],"url":"/documentation/appkit/nswindow/removeframe(usingname:)","title":"removeFrame(usingName:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"removeFrameUsingName:"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrame(from:)":{"role":"symbol","url":"/documentation/appkit/nswindow/setframe(from:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrame(from:)","title":"setFrame(from:)","abstract":[{"text":"Sets the window’s frame rectangle from a given string representation.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"setFrameFromString:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow"},{"text":".","kind":"text"},{"text":"PersistableFrameDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSWindowPersistableFrameDescriptor"},{"text":")","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/FrameAutosaveName-swift.typealias":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/FrameAutosaveName-swift.typealias","title":"NSWindow.FrameAutosaveName","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FrameAutosaveName","kind":"identifier"}],"abstract":[{"text":"The type of a window’s frame autosave name.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"FrameAutosaveName","kind":"identifier"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nswindow/frameautosavename-swift.typealias"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameAutosaveName(_:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setFrameAutosaveName:"}],"abstract":[{"text":"Sets the name AppKit uses to automatically save the window’s frame rectangle data in the defaults system.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setFrameAutosaveName"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier","text":"NSWindow"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSWindowFrameAutosaveName","kind":"typeIdentifier","text":"FrameAutosaveName"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameAutosaveName(_:)","url":"/documentation/appkit/nswindow/setframeautosavename(_:)","title":"setFrameAutosaveName(_:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/saveFrame(usingName:)":{"url":"/documentation/appkit/nswindow/saveframe(usingname:)","role":"symbol","kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/saveFrame(usingName:)","navigatorTitle":[{"text":"saveFrameUsingName:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"saveFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"usingName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow"},{"text":".","kind":"text"},{"text":"FrameAutosaveName","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSWindowFrameAutosaveName"},{"text":")","kind":"text"}],"title":"saveFrame(usingName:)","abstract":[{"text":"Saves the window’s frame rectangle in the user defaults system under a given name.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameUsingName(_:force:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFrameUsingName","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSWindow","preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"FrameAutosaveName","preciseIdentifier":"c:@T@NSWindowFrameAutosaveName","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"force","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameUsingName(_:force:)","abstract":[{"type":"text","text":"Sets the window’s frame rectangle by reading the rectangle data stored under a given name from the defaults system. Can operate on non-resizable windows."}],"type":"topic","title":"setFrameUsingName(_:force:)","kind":"symbol","navigatorTitle":[{"text":"setFrameUsingName:force:","kind":"identifier"}],"url":"/documentation/appkit/nswindow/setframeusingname(_:force:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameUsingName(_:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setFrameUsingName:"}],"abstract":[{"text":"Sets the window’s frame rectangle by reading the rectangle data stored under a given name from the defaults system.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFrameUsingName"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSWindow","preciseIdentifier":"c:objc(cs)NSWindow"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"FrameAutosaveName","preciseIdentifier":"c:@T@NSWindowFrameAutosaveName"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameUsingName(_:)","url":"/documentation/appkit/nswindow/setframeusingname(_:)","title":"setFrameUsingName(_:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/frameAutosaveName-swift.property":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"frameAutosaveName"}],"abstract":[{"text":"The name used to automatically save the window’s frame rectangle data in the defaults system.","type":"text"}],"url":"/documentation/appkit/nswindow/frameautosavename-swift.property","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameAutosaveName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSWindow","preciseIdentifier":"c:objc(cs)NSWindow"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"FrameAutosaveName","preciseIdentifier":"c:@T@NSWindowFrameAutosaveName"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/frameAutosaveName-swift.property","title":"frameAutosaveName"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"name":"macOS","beta":false,"unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"path":"/metadata/roleHeading","op":"replace","value":"Type Method"},{"path":"/metadata/title","op":"replace","value":"removeFrameUsingName:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"removeFrameUsingName:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","value":[{"title":"Managing Window Frames in User Defaults","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameUsingName(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameUsingName(_:force:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/saveFrame(usingName:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameAutosaveName(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/frameAutosaveName-swift.property","doc://com.apple.appkit/documentation/AppKit/NSWindow/FrameAutosaveName-swift.typealias","doc://com.apple.appkit/documentation/AppKit/NSWindow/frameDescriptor","doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrame(from:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/PersistableFrameDescriptor"],"generated":true,"anchor":"Managing-Window-Frames-in-User-Defaults"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"removeFrameUsingName:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/FrameAutosaveName-swift.typealias","preciseIdentifier":"c:@T@NSWindowFrameAutosaveName","text":"NSWindowFrameAutosaveName","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"name"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name of the frame to remove."}]}],"name":"name"}]}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1frameDescriptor/title","value":"stringWithSavedFrame","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1frameDescriptor/fragments","value":[{"kind":"identifier","text":"stringWithSavedFrame"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1PersistableFrameDescriptor/title","value":"NSWindowPersistableFrameDescriptor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1PersistableFrameDescriptor/fragments","value":[{"text":"NSWindowPersistableFrameDescriptor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1PersistableFrameDescriptor/navigatorTitle","value":[{"kind":"identifier","text":"NSWindowPersistableFrameDescriptor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1removeFrame(usingName:)/title","value":"removeFrameUsingName:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1removeFrame(usingName:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"removeFrameUsingName:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setFrame(from:)/title","value":"setFrameFromString:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setFrame(from:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setFrameFromString:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1FrameAutosaveName-swift.typealias/title","value":"NSWindowFrameAutosaveName","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1FrameAutosaveName-swift.typealias/fragments","value":[{"kind":"identifier","text":"NSWindowFrameAutosaveName"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1FrameAutosaveName-swift.typealias/navigatorTitle","value":[{"kind":"identifier","text":"NSWindowFrameAutosaveName"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setFrameAutosaveName(_:)/title","value":"setFrameAutosaveName:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setFrameAutosaveName(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFrameAutosaveName:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1saveFrame(usingName:)/title","value":"saveFrameUsingName:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1saveFrame(usingName:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"saveFrameUsingName:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setFrameUsingName(_:force:)/title","value":"setFrameUsingName:force:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setFrameUsingName(_:force:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setFrameUsingName:force:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setFrameUsingName(_:)/title","value":"setFrameUsingName:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setFrameUsingName(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setFrameUsingName:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title","value":"NSWindow","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments","value":[{"kind":"identifier","text":"NSWindow"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle","value":[{"kind":"identifier","text":"NSWindow"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1frameAutosaveName-swift.property/title","value":"frameAutosaveName","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1frameAutosaveName-swift.property/fragments","value":[{"text":"frameAutosaveName","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}