{"seeAlsoSections":[{"generated":true,"title":"Managing the Key View Loop","anchor":"Managing-the-Key-View-Loop","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(preceding:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(following:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/selectNextKeyView(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/keyViewSelectionDirection","doc://com.apple.appkit/documentation/AppKit/NSWindow/autorecalculatesKeyViewLoop","doc://com.apple.appkit/documentation/AppKit/NSWindow/recalculateKeyViewLoop()"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectPreviousKeyView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}]}],"kind":"declarations"},{"parameters":[{"name":"sender","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The message’s sender."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"Discussion","text":"Discussion"},{"inlineContent":[{"text":"The candidate is one of the following (which this function searches for in this order):","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The current first responder’s previous valid key view, which the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/previousValidKeyView","type":"reference"},{"text":" method of ","type":"text"},{"code":"NSView","type":"codeVoice"},{"text":" returns","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/initialFirstResponder"},{"type":"text","text":" designates as the window’s initial first responder if it returns "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true"},{"type":"text","text":" to an "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/acceptsFirstResponder"},{"type":"text","text":" message"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Otherwise, the initial first responder’s previous valid key view, which may be "},{"type":"codeVoice","code":"nil"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nswindow/selectpreviouskeyview(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nswindow/selectpreviouskeyview(_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Searches for a candidate previous key view and, if it finds one, tries to make it the first responder."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"sections":[],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectPreviousKeyView(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"selectPreviousKeyView(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectPreviousKeyView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"selectPreviousKeyView:","kind":"identifier"}],"platforms":[{"name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"role":"symbol","modules":[{"name":"AppKit"}],"externalID":"c:objc(cs)NSWindow(im)selectPreviousKeyView:","symbolKind":"method","roleHeading":"Instance Method"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(following:)":{"kind":"symbol","title":"selectKeyView(following:)","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(following:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectKeyView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"following"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSView","text":"NSView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Gives key view status to the view that follows the given view."}],"type":"topic","url":"/documentation/appkit/nswindow/selectkeyview(following:)","navigatorTitle":[{"text":"selectKeyViewFollowingView:","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/autorecalculatesKeyViewLoop":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/autorecalculatesKeyViewLoop","abstract":[{"type":"text","text":"A Boolean value that indicates whether the window automatically recalculates the key view loop when views are added."}],"role":"symbol","title":"autorecalculatesKeyViewLoop","url":"/documentation/appkit/nswindow/autorecalculateskeyviewloop","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"autorecalculatesKeyViewLoop"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autorecalculatesKeyViewLoop"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/keyViewSelectionDirection":{"abstract":[{"text":"The direction the window is currently using to change the key view.","type":"text"}],"title":"keyViewSelectionDirection","type":"topic","url":"/documentation/appkit/nswindow/keyviewselectiondirection","kind":"symbol","navigatorTitle":[{"text":"keyViewSelectionDirection","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/keyViewSelectionDirection","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyViewSelectionDirection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSWindow","preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SelectionDirection","preciseIdentifier":"c:@E@NSSelectionDirection","kind":"typeIdentifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/initialFirstResponder":{"title":"initialFirstResponder","url":"/documentation/appkit/nswindow/initialfirstresponder","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"The view that’s made first responder (also called the key view) the first time the window is placed onscreen.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/initialFirstResponder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialFirstResponder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSView","preciseIdentifier":"c:objc(cs)NSView"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"initialFirstResponder"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/recalculateKeyViewLoop()":{"url":"/documentation/appkit/nswindow/recalculatekeyviewloop()","abstract":[{"type":"text","text":"Marks the key view loop as “dirty” and in need of recalculation."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/recalculateKeyViewLoop()","navigatorTitle":[{"kind":"identifier","text":"recalculateKeyViewLoop"}],"role":"symbol","type":"topic","title":"recalculateKeyViewLoop()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recalculateKeyViewLoop"},{"kind":"text","text":"()"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectPreviousKeyView(_:)":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectPreviousKeyView(_:)","abstract":[{"text":"Searches for a candidate previous key view and, if it finds one, tries to make it the first responder.","type":"text"}],"role":"symbol","title":"selectPreviousKeyView(_:)","url":"/documentation/appkit/nswindow/selectpreviouskeyview(_:)","kind":"symbol","navigatorTitle":[{"text":"selectPreviousKeyView:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectPreviousKeyView"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/acceptsFirstResponder":{"abstract":[{"type":"text","text":"A Boolean value that indicates whether the responder accepts first responder status."}],"title":"acceptsFirstResponder","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/acceptsFirstResponder","type":"topic","navigatorTitle":[{"text":"acceptsFirstResponder","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"acceptsFirstResponder","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"/documentation/appkit/nsresponder/acceptsfirstresponder","role":"symbol"},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectNextKeyView(_:)":{"url":"/documentation/appkit/nswindow/selectnextkeyview(_:)","abstract":[{"type":"text","text":"Searches for a candidate next key view and, if it finds one, tries to make it the first responder."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectNextKeyView(_:)","navigatorTitle":[{"text":"selectNextKeyView:","kind":"identifier"}],"role":"symbol","type":"topic","title":"selectNextKeyView(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectNextKeyView"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(preceding:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectKeyView"},{"kind":"text","text":"("},{"text":"preceding","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","text":"NSView"},{"kind":"text","text":")"}],"url":"/documentation/appkit/nswindow/selectkeyview(preceding:)","role":"symbol","navigatorTitle":[{"text":"selectKeyViewPrecedingView:","kind":"identifier"}],"title":"selectKeyView(preceding:)","abstract":[{"text":"Gives key view status to the view that precedes the given view.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(preceding:)"},"doc://com.apple.appkit/documentation/AppKit/NSView/previousValidKeyView":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/previousValidKeyView","type":"topic","abstract":[{"text":"The closest view object in the key view loop that precedes the current view and accepts first responder status.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previousValidKeyView","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","text":"NSView"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"previousValidKeyView"}],"title":"previousValidKeyView","url":"/documentation/appkit/nsview/previousvalidkeyview","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"selectPreviousKeyView:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"selectPreviousKeyView:"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Managing the Key View Loop","anchor":"Managing-the-Key-View-Loop","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(preceding:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/selectKeyView(following:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/selectNextKeyView(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/keyViewSelectionDirection","doc://com.apple.appkit/documentation/AppKit/NSWindow/autorecalculatesKeyViewLoop","doc://com.apple.appkit/documentation/AppKit/NSWindow/recalculateKeyViewLoop()"],"generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"selectPreviousKeyView:"},{"kind":"text","text":"("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":{"parameters":[{"name":"sender","content":[{"inlineContent":[{"type":"text","text":"The message’s sender."}],"type":"paragraph"}]}],"kind":"parameters"},"path":"/primaryContentSections/1","op":"replace"},{"value":"selectKeyViewFollowingView:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectKeyView(following:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"selectKeyViewFollowingView:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectKeyView(following:)/fragments","op":"replace"},{"value":"autorecalculatesKeyViewLoop","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1autorecalculatesKeyViewLoop/title","op":"replace"},{"value":[{"kind":"identifier","text":"autorecalculatesKeyViewLoop"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1autorecalculatesKeyViewLoop/fragments","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1keyViewSelectionDirection/title","value":"keyViewSelectionDirection"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1keyViewSelectionDirection/fragments","value":[{"kind":"identifier","text":"keyViewSelectionDirection"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1initialFirstResponder/title","value":"initialFirstResponder"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1initialFirstResponder/fragments","value":[{"kind":"identifier","text":"initialFirstResponder"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1recalculateKeyViewLoop()/title","value":"recalculateKeyViewLoop"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1recalculateKeyViewLoop()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"recalculateKeyViewLoop","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectPreviousKeyView(_:)/title","op":"replace","value":"selectPreviousKeyView:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectPreviousKeyView(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"selectPreviousKeyView:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title","op":"replace","value":"NSWindow"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments","op":"replace","value":[{"text":"NSWindow","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSWindow"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1acceptsFirstResponder/title","op":"replace","value":"acceptsFirstResponder"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1acceptsFirstResponder/fragments","op":"replace","value":[{"kind":"identifier","text":"acceptsFirstResponder"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectNextKeyView(_:)/title","op":"replace","value":"selectNextKeyView:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectNextKeyView(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectNextKeyView:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectKeyView(preceding:)/title","op":"replace","value":"selectKeyViewPrecedingView:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectKeyView(preceding:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectKeyViewPrecedingView:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1previousValidKeyView/title","op":"replace","value":"previousValidKeyView"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1previousValidKeyView/fragments","op":"replace","value":[{"text":"previousValidKeyView","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}