{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setContentBorderThickness"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"thickness"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"edge"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/c:@E@NSRectEdge","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSRectEdge","text":"NSRectEdge"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The thickness for ","type":"text"},{"code":"edge","type":"codeVoice"},{"text":", in points.","type":"text"}]}],"name":"thickness"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The border whose thickness to set:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"NSMaxYEdge"},{"type":"text","text":": Top border."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"NSMinYEdge"},{"type":"text","text":": Bottom border."}],"type":"paragraph"}]}],"type":"unorderedList"}],"name":"edge"}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"In a nontextured window calling "},{"type":"codeVoice","code":"setContentBorderThickness:forEdge:"},{"type":"text","text":" passing "},{"type":"codeVoice","code":"NSMaxYEdge"},{"type":"text","text":" will raise an exception (in a nontextured window, it’s only valid to set the content border thickness of the bottom edge). It is only valid to set the content border thickness of the top edge in a textured window."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Typically, if you call "},{"type":"codeVoice","code":"setContentBorderThickness:forEdge:"},{"type":"text","text":", you should also call "},{"type":"codeVoice","code":"setAutorecalculatesContentBorderThickness:NO forEdge:"},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"contentBorder"},{"text":" does not include the title bar or toolbar, so a textured window that just wants the gradient in the title bar and toolbar should have a ","type":"text"},{"type":"codeVoice","code":"thickness"},{"text":" of ","type":"text"},{"type":"codeVoice","code":"0"},{"text":" for ","type":"text"},{"type":"codeVoice","code":"NSMaxYEdge"},{"text":".","type":"text"}],"type":"paragraph"}]}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","platforms":[{"introducedAt":"10.5","beta":false,"unavailable":false,"deprecated":false,"name":"macOS"}],"title":"setContentBorderThickness(_:for:)","modules":[{"name":"AppKit"}],"externalID":"c:objc(cs)NSWindow(im)setContentBorderThickness:forEdge:","navigatorTitle":[{"text":"setContentBorderThickness:forEdge:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setContentBorderThickness","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NSRectEdge","text":"NSRectEdge","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/setContentBorderThickness(_:for:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"variants":[{"paths":["/documentation/appkit/nswindow/setcontentborderthickness(_:for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nswindow/setcontentborderthickness(_:for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"title":"Configuring the Window’s Appearance","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/styleMask-swift.property","doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct","doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleFullScreen(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/worksWhenModal","doc://com.apple.appkit/documentation/AppKit/NSWindow/alphaValue","doc://com.apple.appkit/documentation/AppKit/NSWindow/backgroundColor","doc://com.apple.appkit/documentation/AppKit/NSWindow/colorSpace","doc://com.apple.appkit/documentation/AppKit/NSWindow/setDynamicDepthLimit(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/canHide","doc://com.apple.appkit/documentation/AppKit/NSWindow/isOnActiveSpace","doc://com.apple.appkit/documentation/AppKit/NSWindow/hidesOnDeactivate","doc://com.apple.appkit/documentation/AppKit/NSWindow/collectionBehavior-swift.property","doc://com.apple.appkit/documentation/AppKit/NSWindow/isOpaque","doc://com.apple.appkit/documentation/AppKit/NSWindow/hasShadow","doc://com.apple.appkit/documentation/AppKit/NSWindow/invalidateShadow()"],"generated":true,"anchor":"Configuring-the-Windows-Appearance"}],"abstract":[{"text":"Specifies the thickness of a given border of the window.","type":"text"}],"kind":"symbol","sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleFullScreen(_:)":{"navigatorTitle":[{"text":"toggleFullScreen:","kind":"identifier"}],"url":"/documentation/appkit/nswindow/togglefullscreen(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"toggleFullScreen"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleFullScreen(_:)","role":"symbol","type":"topic","abstract":[{"text":"Takes the window into or out of fullscreen mode,","type":"text"}],"title":"toggleFullScreen(_:)"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/invalidateShadow()":{"navigatorTitle":[{"text":"invalidateShadow","kind":"identifier"}],"abstract":[{"text":"Invalidates the window shadow so that it is recomputed based on the current window shape.","type":"text"}],"role":"symbol","title":"invalidateShadow()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidateShadow","kind":"identifier"},{"text":"()","kind":"text"}],"url":"/documentation/appkit/nswindow/invalidateshadow()","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/invalidateShadow()"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/backgroundColor":{"navigatorTitle":[{"text":"backgroundColor","kind":"identifier"}],"abstract":[{"type":"text","text":"The color of the window’s background."}],"role":"symbol","title":"backgroundColor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"text":": ","kind":"text"},{"text":"NSColor","preciseIdentifier":"c:objc(cs)NSColor","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"url":"/documentation/appkit/nswindow/backgroundcolor","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/backgroundColor"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/hasShadow":{"navigatorTitle":[{"text":"hasShadow","kind":"identifier"}],"abstract":[{"text":"A Boolean value that indicates whether the window has a shadow.","type":"text"}],"role":"symbol","title":"hasShadow","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasShadow","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"/documentation/appkit/nswindow/hasshadow","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/hasShadow"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/isOpaque":{"navigatorTitle":[{"text":"opaque","kind":"identifier"}],"abstract":[{"text":"A Boolean value that indicates whether the window is opaque.","type":"text"}],"role":"symbol","title":"isOpaque","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isOpaque","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"/documentation/appkit/nswindow/isopaque","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/isOpaque"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/styleMask-swift.property":{"navigatorTitle":[{"text":"styleMask","kind":"identifier"}],"abstract":[{"type":"text","text":"Flags that describe the window’s current style, such as if it’s resizable or in full-screen mode."}],"role":"symbol","title":"styleMask","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"styleMask"},{"text":": ","kind":"text"},{"text":"NSWindow","preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"StyleMask","preciseIdentifier":"c:@E@NSWindowStyleMask","kind":"typeIdentifier"}],"url":"/documentation/appkit/nswindow/stylemask-swift.property","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/styleMask-swift.property"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/isOnActiveSpace":{"navigatorTitle":[{"text":"onActiveSpace","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isOnActiveSpace","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","url":"/documentation/appkit/nswindow/isonactivespace","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/isOnActiveSpace","title":"isOnActiveSpace","abstract":[{"text":"A Boolean value that indicates whether the window is on the currently active space.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/colorSpace":{"navigatorTitle":[{"kind":"identifier","text":"colorSpace"}],"abstract":[{"text":"The window’s color space.","type":"text"}],"role":"symbol","title":"colorSpace","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"colorSpace","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSColorSpace","text":"NSColorSpace"},{"kind":"text","text":"?"}],"url":"/documentation/appkit/nswindow/colorspace","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/colorSpace"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/worksWhenModal":{"url":"/documentation/appkit/nswindow/workswhenmodal","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"worksWhenModal"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the window is able to receive keyboard and mouse events even when some other window is being run modally."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"worksWhenModal","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/worksWhenModal","title":"worksWhenModal"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/canHide":{"navigatorTitle":[{"text":"canHide","kind":"identifier"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the window can hide when its application becomes hidden."}],"role":"symbol","title":"canHide","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canHide"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"/documentation/appkit/nswindow/canhide","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/canHide"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct":{"role":"symbol","abstract":[{"type":"text","text":"Constants that specify the style of a window, and that you can combine with the C bitwise OR operator."}],"title":"NSWindow.StyleMask","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StyleMask"}],"url":"/documentation/appkit/nswindow/stylemask-swift.struct","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleMask"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/setDynamicDepthLimit(_:)":{"navigatorTitle":[{"text":"setDynamicDepthLimit:","kind":"identifier"}],"abstract":[{"type":"text","text":"Sets a Boolean value that indicates whether the window’s depth limit can change to match the depth of the screen it’s on."}],"role":"symbol","title":"setDynamicDepthLimit(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setDynamicDepthLimit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/appkit/nswindow/setdynamicdepthlimit(_:)","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/setDynamicDepthLimit(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/collectionBehavior-swift.property":{"navigatorTitle":[{"kind":"identifier","text":"collectionBehavior"}],"abstract":[{"text":"A value that identifies the window’s behavior in window collections.","type":"text"}],"role":"symbol","title":"collectionBehavior","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"collectionBehavior","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSWindowCollectionBehavior","text":"CollectionBehavior"}],"url":"/documentation/appkit/nswindow/collectionbehavior-swift.property","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/collectionBehavior-swift.property"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/hidesOnDeactivate":{"url":"/documentation/appkit/nswindow/hidesondeactivate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hidesOnDeactivate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the window is removed from the screen when its application becomes inactive."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"hidesOnDeactivate","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/hidesOnDeactivate","title":"hidesOnDeactivate"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/setContentBorderThickness(_:for:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/setContentBorderThickness(_:for:)","url":"/documentation/appkit/nswindow/setcontentborderthickness(_:for:)","navigatorTitle":[{"text":"setContentBorderThickness:forEdge:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setContentBorderThickness","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRectEdge","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSRectEdge"},{"text":")","kind":"text"}],"title":"setContentBorderThickness(_:for:)","type":"topic","abstract":[{"text":"Specifies the thickness of a given border of the window.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV":{"role":"symbol","type":"topic","title":"CGFloat","url":"/documentation/corefoundation/cgfloat","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","kind":"symbol","fragments":[{"text":"struct ","kind":"text"},{"text":"CGFloat","kind":"identifier"}],"abstract":[{"text":"The basic type for floating-point scalar values in Core Graphics and related frameworks.","type":"text"}]},"doc://com.externally.resolved.symbol/c:@E@NSRectEdge":{"url":"/documentation/foundation/nsrectedge","role":"symbol","title":"NSRectEdge","kind":"symbol","fragments":[{"text":"enum ","kind":"text"},{"text":"NSRectEdge","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:@E@NSRectEdge","abstract":[{"type":"text","text":""}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/alphaValue":{"role":"symbol","type":"topic","title":"alphaValue","navigatorTitle":[{"text":"alphaValue","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alphaValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"abstract":[{"text":"The window’s alpha value.","type":"text"}],"url":"/documentation/appkit/nswindow/alphavalue","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/alphaValue","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@CGFloat":{"kind":"symbol","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","abstract":[{"text":"The basic type for all floating-point values.","type":"text"}],"type":"topic","title":"CGFloat","url":"/documentation/corefoundation/cgfloat"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"deprecated":false,"name":"macOS","introducedAt":"10.5","unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"setContentBorderThickness:forEdge:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setContentBorderThickness:forEdge:"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/styleMask-swift.property","doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct","doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleFullScreen(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/worksWhenModal","doc://com.apple.appkit/documentation/AppKit/NSWindow/alphaValue","doc://com.apple.appkit/documentation/AppKit/NSWindow/backgroundColor","doc://com.apple.appkit/documentation/AppKit/NSWindow/colorSpace","doc://com.apple.appkit/documentation/AppKit/NSWindow/setDynamicDepthLimit(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/canHide","doc://com.apple.appkit/documentation/AppKit/NSWindow/isOnActiveSpace","doc://com.apple.appkit/documentation/AppKit/NSWindow/hidesOnDeactivate","doc://com.apple.appkit/documentation/AppKit/NSWindow/collectionBehavior-swift.property","doc://com.apple.appkit/documentation/AppKit/NSWindow/isOpaque","doc://com.apple.appkit/documentation/AppKit/NSWindow/hasShadow","doc://com.apple.appkit/documentation/AppKit/NSWindow/invalidateShadow()"],"generated":true,"anchor":"Configuring-the-Windows-Appearance","title":"Configuring the Window’s Appearance"}],"op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setContentBorderThickness:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat"},{"kind":"text","text":") "},{"text":"thickness","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forEdge:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSRectEdge","preciseIdentifier":"c:@E@NSRectEdge","identifier":"doc://com.externally.resolved.symbol/c:@E@NSRectEdge","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"edge","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}]},"path":"/primaryContentSections/0","op":"replace"},{"path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"thickness","content":[{"type":"paragraph","inlineContent":[{"text":"The thickness for ","type":"text"},{"type":"codeVoice","code":"edge"},{"text":", in points.","type":"text"}]}]},{"name":"edge","content":[{"inlineContent":[{"text":"The border whose thickness to set:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"NSMaxYEdge","type":"codeVoice"},{"text":": Top border.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"NSMinYEdge"},{"type":"text","text":": Bottom border."}]}]}]}]}]},"op":"replace"},{"value":"toggleFullScreen:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1toggleFullScreen(_:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toggleFullScreen:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1toggleFullScreen(_:)/fragments","op":"replace"},{"value":"invalidateShadow","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1invalidateShadow()/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"invalidateShadow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1invalidateShadow()/fragments","op":"replace"},{"value":"backgroundColor","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1backgroundColor/title","op":"replace"},{"value":[{"text":"backgroundColor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1backgroundColor/fragments","op":"replace"},{"value":"hasShadow","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1hasShadow/title","op":"replace"},{"value":[{"kind":"identifier","text":"hasShadow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1hasShadow/fragments","op":"replace"},{"value":"opaque","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isOpaque/title","op":"replace"},{"op":"replace","value":[{"text":"opaque","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isOpaque/fragments"},{"op":"replace","value":"NSWindow","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle"},{"value":"styleMask","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1styleMask-swift.property/title","op":"replace"},{"value":[{"text":"styleMask","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1styleMask-swift.property/fragments","op":"replace"},{"value":"onActiveSpace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isOnActiveSpace/title","op":"replace"},{"value":[{"kind":"identifier","text":"onActiveSpace"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isOnActiveSpace/fragments","op":"replace"},{"value":"colorSpace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1colorSpace/title","op":"replace"},{"value":[{"kind":"identifier","text":"colorSpace"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1colorSpace/fragments","op":"replace"},{"value":"worksWhenModal","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1worksWhenModal/title","op":"replace"},{"value":[{"kind":"identifier","text":"worksWhenModal"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1worksWhenModal/fragments","op":"replace"},{"value":"canHide","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1canHide/title","op":"replace"},{"value":[{"kind":"identifier","text":"canHide"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1canHide/fragments","op":"replace"},{"value":"NSWindowStyleMask","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSWindowStyleMask"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSWindowStyleMask"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/navigatorTitle","op":"replace"},{"value":"setDynamicDepthLimit:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setDynamicDepthLimit(_:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setDynamicDepthLimit:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setDynamicDepthLimit(_:)/fragments","op":"replace"},{"value":"collectionBehavior","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1collectionBehavior-swift.property/title","op":"replace"},{"value":[{"kind":"identifier","text":"collectionBehavior"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1collectionBehavior-swift.property/fragments","op":"replace"},{"value":"hidesOnDeactivate","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1hidesOnDeactivate/title","op":"replace"},{"value":[{"kind":"identifier","text":"hidesOnDeactivate"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1hidesOnDeactivate/fragments","op":"replace"},{"value":"setContentBorderThickness:forEdge:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setContentBorderThickness(_:for:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setContentBorderThickness:forEdge:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setContentBorderThickness(_:for:)/fragments","op":"replace"},{"value":"alphaValue","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1alphaValue/title","op":"replace"},{"value":[{"kind":"identifier","text":"alphaValue"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1alphaValue/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}