{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/standardWindowButton(_:for:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"platforms":[{"deprecated":false,"name":"macOS","unavailable":false,"beta":false}],"externalID":"c:objc(cs)NSWindow(cm)standardWindowButton:forStyleMask:","title":"standardWindowButton(_:for:)","navigatorTitle":[{"kind":"identifier","text":"standardWindowButton:forStyleMask:"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"standardWindowButton"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSWindow","preciseIdentifier":"c:objc(cs)NSWindow"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ButtonType","preciseIdentifier":"c:@E@NSWindowButton"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSWindow","preciseIdentifier":"c:objc(cs)NSWindow"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"StyleMask","preciseIdentifier":"c:@E@NSWindowStyleMask"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSButton","preciseIdentifier":"c:objc(cs)NSButton"},{"kind":"text","text":"?"}],"modules":[{"name":"AppKit"}],"symbolKind":"method","roleHeading":"Type Method","role":"symbol"},"abstract":[{"type":"text","text":"Returns a new instance of a given standard window button, sized appropriately for a given window style."}],"sections":[],"seeAlsoSections":[{"anchor":"Managing-Title-Bars","title":"Managing Title Bars","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/standardWindowButton(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/showsToolbarButton","doc://com.apple.appkit/documentation/AppKit/NSWindow/titlebarAppearsTransparent","doc://com.apple.appkit/documentation/AppKit/NSWindow/toolbarStyle-swift.property","doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSWindow/titlebarSeparatorStyle","doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle","doc://com.apple.appkit/documentation/AppKit/NSWindow/windowTitlebarLayoutDirection"],"generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standardWindowButton","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"b","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow"},{"text":".","kind":"text"},{"text":"ButtonType","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSWindowButton","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"styleMask","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow"},{"text":".","kind":"text"},{"text":"StyleMask","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSWindowStyleMask","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct"},{"text":") -> ","kind":"text"},{"text":"NSButton","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSButton","identifier":"doc://com.apple.appkit/documentation/AppKit/NSButton"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The type of standard window button to return."}],"type":"paragraph"}],"name":"b"},{"content":[{"inlineContent":[{"text":"The window style for which ","type":"text"},{"code":"b","type":"codeVoice"},{"text":" is to be sized. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct"},{"text":"  for the list of allowable values.","type":"text"}],"type":"paragraph"}],"name":"styleMask"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"The new window button of the type identified by ","type":"text"},{"type":"codeVoice","code":"b"},{"text":"; ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" when no such button type exists.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The caller is responsible for adding the button to the view hierarchy and for setting the target to be the window.","type":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nswindow/standardwindowbutton(_:for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nswindow/standardwindowbutton(_:for:)"]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle":{"role":"symbol","type":"topic","title":"NSTitlebarSeparatorStyle","url":"/documentation/appkit/nstitlebarseparatorstyle","navigatorTitle":[{"text":"NSTitlebarSeparatorStyle","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTitlebarSeparatorStyle","kind":"identifier"}],"abstract":[{"text":"Styles that determine the type of separator displayed between the title bar and content of a window.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum","role":"symbol","type":"topic","url":"/documentation/appkit/nswindow/toolbarstyle-swift.enum","navigatorTitle":[{"kind":"identifier","text":"ToolbarStyle"}],"abstract":[{"text":"Styles that determine the appearance and location of the toolbar in relation to the title bar.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ToolbarStyle"}],"title":"NSWindow.ToolbarStyle","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType":{"url":"/documentation/appkit/nswindow/buttontype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ButtonType","kind":"identifier"}],"title":"NSWindow.ButtonType","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ButtonType","kind":"identifier"}],"abstract":[{"text":"Constants that provide a way to access standard title bar buttons.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/titlebarSeparatorStyle":{"navigatorTitle":[{"kind":"identifier","text":"titlebarSeparatorStyle"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/titlebarSeparatorStyle","role":"symbol","title":"titlebarSeparatorStyle","abstract":[{"text":"The type of separator that the app displays between the title bar and content of a window.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titlebarSeparatorStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NSTitlebarSeparatorStyle","kind":"typeIdentifier","text":"NSTitlebarSeparatorStyle"}],"kind":"symbol","url":"/documentation/appkit/nswindow/titlebarseparatorstyle"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/standardWindowButton(_:)":{"navigatorTitle":[{"kind":"identifier","text":"standardWindowButton:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/standardWindowButton(_:)","role":"symbol","title":"standardWindowButton(_:)","abstract":[{"text":"Returns the window button of a given window button kind in the window’s view hierarchy.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standardWindowButton","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier","text":"NSWindow"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSWindowButton","kind":"typeIdentifier","text":"ButtonType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSButton","kind":"typeIdentifier","text":"NSButton"},{"kind":"text","text":"?"}],"kind":"symbol","url":"/documentation/appkit/nswindow/standardwindowbutton(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/toolbarStyle-swift.property":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"toolbarStyle","kind":"identifier"}],"abstract":[{"text":"The style that determines the appearance and location of the toolbar in relation to the title bar.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toolbarStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow"},{"text":".","kind":"text"},{"text":"ToolbarStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSWindowToolbarStyle"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/toolbarStyle-swift.property","title":"toolbarStyle","url":"/documentation/appkit/nswindow/toolbarstyle-swift.property"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct":{"role":"symbol","abstract":[{"type":"text","text":"Constants that specify the style of a window, and that you can combine with the C bitwise OR operator."}],"title":"NSWindow.StyleMask","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StyleMask"}],"url":"/documentation/appkit/nswindow/stylemask-swift.struct","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StyleMask"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/windowTitlebarLayoutDirection":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"windowTitlebarLayoutDirection","kind":"identifier"}],"abstract":[{"text":"The direction the window’s title bar lays text out, either left to right or right to left.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"windowTitlebarLayoutDirection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSUserInterfaceLayoutDirection","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSUserInterfaceLayoutDirection"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/windowTitlebarLayoutDirection","title":"windowTitlebarLayoutDirection","url":"/documentation/appkit/nswindow/windowtitlebarlayoutdirection"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/standardWindowButton(_:for:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"standardWindowButton:forStyleMask:"}],"abstract":[{"text":"Returns a new instance of a given standard window button, sized appropriately for a given window style.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standardWindowButton","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSWindowButton","kind":"typeIdentifier","text":"ButtonType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier","text":"NSWindow"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"StyleMask","preciseIdentifier":"c:@E@NSWindowStyleMask"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSButton","preciseIdentifier":"c:objc(cs)NSButton"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/standardWindowButton(_:for:)","title":"standardWindowButton(_:for:)","url":"/documentation/appkit/nswindow/standardwindowbutton(_:for:)"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/titlebarAppearsTransparent":{"url":"/documentation/appkit/nswindow/titlebarappearstransparent","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/titlebarAppearsTransparent","kind":"symbol","abstract":[{"type":"text","text":"A Boolean value that indicates whether the title bar draws its background."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"titlebarAppearsTransparent"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titlebarAppearsTransparent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"titlebarAppearsTransparent"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/showsToolbarButton":{"url":"/documentation/appkit/nswindow/showstoolbarbutton","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/showsToolbarButton","kind":"symbol","abstract":[{"type":"text","text":"A Boolean value that indicates whether the toolbar control button is currently displayed."}],"type":"topic","navigatorTitle":[{"text":"showsToolbarButton","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showsToolbarButton"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"deprecated":true,"title":"showsToolbarButton"},"doc://com.apple.appkit/documentation/AppKit/NSButton":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSButton","kind":"identifier"}],"title":"NSButton","url":"/documentation/appkit/nsbutton","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSButton","type":"topic","abstract":[{"text":"A control that defines an area on the screen that a user clicks to trigger an action.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"NSButton","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"name":"macOS","unavailable":false,"beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Type Method","path":"/metadata/roleHeading"},{"op":"replace","value":"standardWindowButton:forStyleMask:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"standardWindowButton:forStyleMask:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"title":"Managing Title Bars","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/standardWindowButton(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/showsToolbarButton","doc://com.apple.appkit/documentation/AppKit/NSWindow/titlebarAppearsTransparent","doc://com.apple.appkit/documentation/AppKit/NSWindow/toolbarStyle-swift.property","doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum","doc://com.apple.appkit/documentation/AppKit/NSWindow/titlebarSeparatorStyle","doc://com.apple.appkit/documentation/AppKit/NSTitlebarSeparatorStyle","doc://com.apple.appkit/documentation/AppKit/NSWindow/windowTitlebarLayoutDirection"],"anchor":"Managing-Title-Bars"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSButton","preciseIdentifier":"c:objc(cs)NSButton","identifier":"doc://com.apple.appkit/documentation/AppKit/NSButton"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"standardWindowButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSWindowButton","preciseIdentifier":"c:@E@NSWindowButton","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/ButtonType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"b"},{"kind":"text","text":" "},{"kind":"identifier","text":"forStyleMask:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSWindowStyleMask","preciseIdentifier":"c:@E@NSWindowStyleMask","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct"},{"kind":"text","text":") "},{"kind":"internalParam","text":"styleMask"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"value":{"parameters":[{"name":"b","content":[{"inlineContent":[{"type":"text","text":"The type of standard window button to return."}],"type":"paragraph"}]},{"name":"styleMask","content":[{"inlineContent":[{"text":"The window style for which ","type":"text"},{"code":"b","type":"codeVoice"},{"text":" is to be sized. See ","type":"text"},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct","isActive":true},{"text":"  for the list of allowable values.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"/primaryContentSections/1","op":"replace"},{"op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The new window button of the type identified by "},{"type":"codeVoice","code":"b"},{"type":"text","text":"; "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" when no such button type exists."}],"type":"paragraph"}]},"path":"/primaryContentSections/2"},{"value":"NSTitlebarSeparatorStyle","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarSeparatorStyle/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSTitlebarSeparatorStyle"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarSeparatorStyle/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSTitlebarSeparatorStyle"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarSeparatorStyle/navigatorTitle","op":"replace"},{"value":"NSWindowToolbarStyle","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ToolbarStyle-swift.enum/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSWindowToolbarStyle"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ToolbarStyle-swift.enum/fragments","op":"replace"},{"value":[{"text":"NSWindowToolbarStyle","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ToolbarStyle-swift.enum/navigatorTitle","op":"replace"},{"value":"NSWindowButton","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSWindowButton"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSWindowButton"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ButtonType/navigatorTitle","op":"replace"},{"value":"titlebarSeparatorStyle","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1titlebarSeparatorStyle/title","op":"replace"},{"value":[{"kind":"identifier","text":"titlebarSeparatorStyle"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1titlebarSeparatorStyle/fragments","op":"replace"},{"value":"standardWindowButton:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1standardWindowButton(_:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"standardWindowButton:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1standardWindowButton(_:)/fragments","op":"replace"},{"value":"toolbarStyle","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1toolbarStyle-swift.property/title","op":"replace"},{"value":[{"kind":"identifier","text":"toolbarStyle"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1toolbarStyle-swift.property/fragments","op":"replace"},{"value":"NSWindowStyleMask","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/title","op":"replace"},{"value":[{"text":"NSWindowStyleMask","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSWindowStyleMask"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/navigatorTitle","op":"replace"},{"value":"windowTitlebarLayoutDirection","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1windowTitlebarLayoutDirection/title","op":"replace"},{"value":[{"text":"windowTitlebarLayoutDirection","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1windowTitlebarLayoutDirection/fragments","op":"replace"},{"value":"standardWindowButton:forStyleMask:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1standardWindowButton(_:for:)/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"standardWindowButton:forStyleMask:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1standardWindowButton(_:for:)/fragments","op":"replace"},{"value":"titlebarAppearsTransparent","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1titlebarAppearsTransparent/title","op":"replace"},{"value":[{"kind":"identifier","text":"titlebarAppearsTransparent"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1titlebarAppearsTransparent/fragments","op":"replace"},{"value":"NSWindow","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title","op":"replace"},{"value":[{"text":"NSWindow","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments","op":"replace"},{"value":[{"text":"NSWindow","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle","op":"replace"},{"value":"showsToolbarButton","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1showsToolbarButton/title","op":"replace"},{"value":[{"kind":"identifier","text":"showsToolbarButton"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1showsToolbarButton/fragments","op":"replace"},{"value":"NSButton","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/title","op":"replace"},{"value":[{"text":"NSButton","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/fragments","op":"replace"},{"value":[{"text":"NSButton","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/navigatorTitle","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}