{
  "abstract": [
    {
      "text": "A value that allows a group of related windows.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWindow/tabbingIdentifier-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSWindow(py)tabbingIdentifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "tabbingIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSWindow",
        "text": "NSWindow"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSWindowTabbingIdentifier",
        "text": "TabbingIdentifier"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "tabbingIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "tabbingIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tabbingIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSWindow",
              "text": "NSWindow"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/TabbingIdentifier-swift.typealias",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSWindowTabbingIdentifier",
              "text": "TabbingIdentifier"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By default, a window generates a tabbing identifier from inherent window properties, such as the window class name, the delegate class name, the window controller class name, and some additional state. Group windows together by using the same tabbing identifier.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow": {
      "abstract": [
        {
          "text": "A window that an app displays on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "role": "symbol",
      "title": "NSWindow",
      "type": "topic",
      "url": "/documentation/appkit/nswindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/TabbingIdentifier-swift.typealias": {
      "abstract": [
        {
          "text": "A value that allows a group of related windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TabbingIdentifier"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/TabbingIdentifier-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TabbingIdentifier"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.TabbingIdentifier",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/tabbingidentifier-swift.typealias"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/addTabbedWindow(_:ordered:)": {
      "abstract": [
        {
          "text": "Adds the provided window as a new tab in a tabbed window using the specified ordering instruction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addTabbedWindow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ordered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowOrderingMode",
          "text": "OrderingMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/addTabbedWindow(_:ordered:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addTabbedWindow:ordered:"
        }
      ],
      "role": "symbol",
      "title": "addTabbedWindow(_:ordered:)",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/addtabbedwindow(_:ordered:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/allowsAutomaticWindowTabbing": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app can automatically organize windows into tabs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsAutomaticWindowTabbing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/allowsAutomaticWindowTabbing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsAutomaticWindowTabbing"
        }
      ],
      "role": "symbol",
      "title": "allowsAutomaticWindowTabbing",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/allowsautomaticwindowtabbing"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/mergeAllWindows(_:)": {
      "abstract": [
        {
          "text": "Merges all open windows into a single tabbed window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mergeAllWindows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/mergeAllWindows(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mergeAllWindows:"
        }
      ],
      "role": "symbol",
      "title": "mergeAllWindows(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/mergeallwindows(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/moveTabToNewWindow(_:)": {
      "abstract": [
        {
          "text": "Moves the tab to a new containing window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moveTabToNewWindow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/moveTabToNewWindow(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "moveTabToNewWindow:"
        }
      ],
      "role": "symbol",
      "title": "moveTabToNewWindow(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/movetabtonewwindow(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/selectNextTab(_:)": {
      "abstract": [
        {
          "text": "Selects the next tab in the tab group in the trailing direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectNextTab"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/selectNextTab(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectNextTab:"
        }
      ],
      "role": "symbol",
      "title": "selectNextTab(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/selectnexttab(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/selectPreviousTab(_:)": {
      "abstract": [
        {
          "text": "Selects the previous tab in the tab group in the leading direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectPreviousTab"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/selectPreviousTab(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectPreviousTab:"
        }
      ],
      "role": "symbol",
      "title": "selectPreviousTab(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/selectprevioustab(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/tab": {
      "abstract": [
        {
          "text": "An object that represents information about a window when it displays as a tab.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tab"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindowTab",
          "text": "NSWindowTab"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/tab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tab"
        }
      ],
      "role": "symbol",
      "title": "tab",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/tab"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/tabGroup": {
      "abstract": [
        {
          "text": "A group of windows that display together as a tab group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabGroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindowTabGroup",
          "text": "NSWindowTabGroup"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/tabGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabGroup"
        }
      ],
      "role": "symbol",
      "title": "tabGroup",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/tabgroup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/tabbedWindows": {
      "abstract": [
        {
          "text": "An array of windows that display as tabs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabbedWindows"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/tabbedWindows",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabbedWindows"
        }
      ],
      "role": "symbol",
      "title": "tabbedWindows",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/tabbedwindows"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/tabbingIdentifier-swift.property": {
      "abstract": [
        {
          "text": "A value that allows a group of related windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabbingIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWindowTabbingIdentifier",
          "text": "TabbingIdentifier"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/tabbingIdentifier-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabbingIdentifier"
        }
      ],
      "role": "symbol",
      "title": "tabbingIdentifier",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/tabbingidentifier-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/tabbingMode-swift.property": {
      "abstract": [
        {
          "text": "A value that indicates when a window displays tabs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabbingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowTabbingMode",
          "text": "TabbingMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/tabbingMode-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabbingMode"
        }
      ],
      "role": "symbol",
      "title": "tabbingMode",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/tabbingmode-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleTabBar(_:)": {
      "abstract": [
        {
          "text": "Shows or hides the tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toggleTabBar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleTabBar(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toggleTabBar:"
        }
      ],
      "role": "symbol",
      "title": "toggleTabBar(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/toggletabbar(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleTabOverview(_:)": {
      "abstract": [
        {
          "text": "Shows or hides the tab overview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toggleTabOverview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleTabOverview(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toggleTabOverview:"
        }
      ],
      "role": "symbol",
      "title": "toggleTabOverview(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/toggletaboverview(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/userTabbingPreference-swift.type.property": {
      "abstract": [
        {
          "text": "A value that indicates the user’s preference for window tabbing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userTabbingPreference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowUserTabbingPreference",
          "text": "UserTabbingPreference"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/userTabbingPreference-swift.type.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userTabbingPreference"
        }
      ],
      "role": "symbol",
      "title": "userTabbingPreference",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/usertabbingpreference-swift.type.property"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Window-Tabs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/allowsAutomaticWindowTabbing",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/userTabbingPreference-swift.type.property",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/tab",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/TabbingIdentifier-swift.typealias",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/addTabbedWindow(_:ordered:)",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/tabbingMode-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/tabbedWindows",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/mergeAllWindows(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/selectNextTab(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/selectPreviousTab(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/moveTabToNewWindow(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleTabBar(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleTabOverview(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/tabGroup"
      ],
      "title": "Managing Window Tabs"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "tabbingIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tabbingIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Window-Tabs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/allowsAutomaticWindowTabbing",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/userTabbingPreference-swift.type.property",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/tab",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/TabbingIdentifier-swift.typealias",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/addTabbedWindow(_:ordered:)",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/tabbingMode-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/tabbedWindows",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/mergeAllWindows(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/selectNextTab(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/selectPreviousTab(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/moveTabToNewWindow(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleTabBar(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleTabOverview(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/tabGroup"
              ],
              "title": "Managing Window Tabs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/TabbingIdentifier-swift.typealias",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSWindowTabbingIdentifier",
                    "text": "NSWindowTabbingIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "tabbingIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectNextTab(_:)/title",
          "value": "selectNextTab:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectNextTab(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectNextTab:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectPreviousTab(_:)/title",
          "value": "selectPreviousTab:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1selectPreviousTab(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectPreviousTab:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1tab/title",
          "value": "tab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1tab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TabbingIdentifier-swift.typealias/title",
          "value": "NSWindowTabbingIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TabbingIdentifier-swift.typealias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowTabbingIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TabbingIdentifier-swift.typealias/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowTabbingIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1userTabbingPreference-swift.type.property/title",
          "value": "userTabbingPreference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1userTabbingPreference-swift.type.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userTabbingPreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1allowsAutomaticWindowTabbing/title",
          "value": "allowsAutomaticWindowTabbing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1allowsAutomaticWindowTabbing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsAutomaticWindowTabbing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1moveTabToNewWindow(_:)/title",
          "value": "moveTabToNewWindow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1moveTabToNewWindow(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "moveTabToNewWindow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title",
          "value": "NSWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1tabbingIdentifier-swift.property/title",
          "value": "tabbingIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1tabbingIdentifier-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tabbingIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1toggleTabBar(_:)/title",
          "value": "toggleTabBar:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1toggleTabBar(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "toggleTabBar:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1mergeAllWindows(_:)/title",
          "value": "mergeAllWindows:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1mergeAllWindows(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mergeAllWindows:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1tabbingMode-swift.property/title",
          "value": "tabbingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1tabbingMode-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tabbingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1addTabbedWindow(_:ordered:)/title",
          "value": "addTabbedWindow:ordered:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1addTabbedWindow(_:ordered:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addTabbedWindow:ordered:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1tabGroup/title",
          "value": "tabGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1tabGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tabGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1tabbedWindows/title",
          "value": "tabbedWindows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1tabbedWindows/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tabbedWindows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1toggleTabOverview(_:)/title",
          "value": "toggleTabOverview:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1toggleTabOverview(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "toggleTabOverview:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nswindow/tabbingidentifier-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nswindow/tabbingidentifier-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
