{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/titleVisibility-swift.property"},"abstract":[{"type":"text","text":"A value that indicates the visibility of the window’s title and title bar buttons."}],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/title","doc://com.apple.appkit/documentation/AppKit/NSWindow/subtitle","doc://com.apple.appkit/documentation/AppKit/NSWindow/setTitleWithRepresentedFilename(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/representedFilename","doc://com.apple.appkit/documentation/AppKit/NSWindow/representedURL"],"anchor":"Managing-Titles","title":"Managing Titles","generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleVisibility"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow"},{"text":".","kind":"text"},{"text":"TitleVisibility","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/TitleVisibility-swift.enum","preciseIdentifier":"c:@E@NSWindowTitleVisibility","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"Discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"By default, the value of this property is "},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/TitleVisibility-swift.enum/visible","type":"reference"},{"type":"text","text":"."}]}],"kind":"content"}],"metadata":{"externalID":"c:objc(cs)NSWindow(py)titleVisibility","navigatorTitle":[{"text":"titleVisibility","kind":"identifier"}],"title":"titleVisibility","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"AppKit"}],"symbolKind":"property","platforms":[{"beta":false,"deprecated":false,"name":"macOS","introducedAt":"10.10","unavailable":false}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleVisibility","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSWindowTitleVisibility","text":"TitleVisibility","kind":"typeIdentifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"sections":[],"variants":[{"paths":["/documentation/appkit/nswindow/titlevisibility-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nswindow/titlevisibility-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSWindow/titleVisibility-swift.property":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"titleVisibility","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/titleVisibility-swift.property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleVisibility","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSWindow","preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"TitleVisibility","preciseIdentifier":"c:@E@NSWindowTitleVisibility","kind":"typeIdentifier"}],"kind":"symbol","url":"/documentation/appkit/nswindow/titlevisibility-swift.property","abstract":[{"text":"A value that indicates the visibility of the window’s title and title bar buttons.","type":"text"}],"title":"titleVisibility"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/representedURL":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/representedURL","kind":"symbol","navigatorTitle":[{"text":"representedURL","kind":"identifier"}],"role":"symbol","type":"topic","title":"representedURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"representedURL","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The URL of the file the window represents."}],"url":"/documentation/appkit/nswindow/representedurl"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/subtitle":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"subtitle","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/subtitle","url":"/documentation/appkit/nswindow/subtitle","title":"subtitle","role":"symbol","abstract":[{"type":"text","text":"A secondary line of text that appears in the title bar of the window."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subtitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/TitleVisibility-swift.enum/visible":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/TitleVisibility-swift.enum/visible","abstract":[{"text":"The window has the regular window title and title bar buttons.","type":"text"}],"title":"NSWindow.TitleVisibility.visible","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindowTitleVisible"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"visible"}],"url":"/documentation/appkit/nswindow/titlevisibility-swift.enum/visible","type":"topic"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/representedFilename":{"url":"/documentation/appkit/nswindow/representedfilename","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"representedFilename","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"representedFilename","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/representedFilename","kind":"symbol","type":"topic","navigatorTitle":[{"text":"representedFilename","kind":"identifier"}],"abstract":[{"text":"The path to the file of the window’s represented file.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/title":{"abstract":[{"type":"text","text":"The string that appears in the title bar of the window or the path to the represented file."}],"url":"/documentation/appkit/nswindow/title","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/title","title":"title","navigatorTitle":[{"kind":"identifier","text":"title"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/setTitleWithRepresentedFilename(_:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setTitleWithRepresentedFilename","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/appkit/nswindow/settitlewithrepresentedfilename(_:)","title":"setTitleWithRepresentedFilename(_:)","abstract":[{"type":"text","text":"Sets a given path as the window’s title, formatting it as a file-system path, and records this path as the window’s associated file."}],"navigatorTitle":[{"text":"setTitleWithRepresentedFilename:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/setTitleWithRepresentedFilename(_:)","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/TitleVisibility-swift.enum":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TitleVisibility","kind":"identifier"}],"title":"NSWindow.TitleVisibility","url":"/documentation/appkit/nswindow/titlevisibility-swift.enum","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/TitleVisibility-swift.enum","type":"topic","abstract":[{"text":"Specifies the appearance of the window’s title bar area.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"TitleVisibility","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"10.10","beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"titleVisibility"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"titleVisibility","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"title":"Managing Titles","anchor":"Managing-Titles","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/title","doc://com.apple.appkit/documentation/AppKit/NSWindow/subtitle","doc://com.apple.appkit/documentation/AppKit/NSWindow/setTitleWithRepresentedFilename(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/representedFilename","doc://com.apple.appkit/documentation/AppKit/NSWindow/representedURL"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/TitleVisibility-swift.enum","text":"NSWindowTitleVisibility","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSWindowTitleVisibility"},{"text":" ","kind":"text"},{"text":"titleVisibility","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1titleVisibility-swift.property/title","value":"titleVisibility"},{"value":[{"kind":"identifier","text":"titleVisibility"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1titleVisibility-swift.property/fragments","op":"replace"},{"value":"representedURL","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1representedURL/title","op":"replace"},{"value":[{"kind":"identifier","text":"representedURL"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1representedURL/fragments","op":"replace"},{"value":"NSWindow","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSWindow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSWindow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle","op":"replace"},{"value":"subtitle","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1subtitle/title","op":"replace"},{"value":[{"text":"subtitle","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1subtitle/fragments","op":"replace"},{"value":"NSWindowTitleVisible","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TitleVisibility-swift.enum~1visible/title","op":"replace"},{"value":[{"text":"NSWindowTitleVisible","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TitleVisibility-swift.enum~1visible/fragments","op":"replace"},{"value":"representedFilename","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1representedFilename/title","op":"replace"},{"value":[{"text":"representedFilename","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1representedFilename/fragments","op":"replace"},{"value":"title","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1title/title","op":"replace"},{"value":[{"text":"title","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1title/fragments","op":"replace"},{"value":"setTitleWithRepresentedFilename:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setTitleWithRepresentedFilename(_:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setTitleWithRepresentedFilename:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setTitleWithRepresentedFilename(_:)/fragments","op":"replace"},{"value":"NSWindowTitleVisibility","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TitleVisibility-swift.enum/title","op":"replace"},{"value":[{"text":"NSWindowTitleVisibility","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TitleVisibility-swift.enum/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSWindowTitleVisibility"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1TitleVisibility-swift.enum/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}