{"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"windowNumbers","kind":"identifier"},{"text":"(","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow"},{"text":".","kind":"text"},{"text":"NumberListOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSWindowNumberListOptions"},{"text":") -> [","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"]?","kind":"text"}],"externalID":"c:objc(cs)NSWindow(cm)windowNumbersWithOptions:","platforms":[{"deprecated":false,"name":"macOS","unavailable":false,"beta":false,"introducedAt":"10.6"}],"modules":[{"name":"AppKit"}],"symbolKind":"method","navigatorTitle":[{"text":"windowNumbersWithOptions:","kind":"identifier"}],"title":"windowNumbers(options:)","roleHeading":"Type Method","role":"symbol"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"kind":"symbol","abstract":[{"type":"text","text":"Returns the window numbers for all visible windows satisfying the specified options."}],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/depthLimit","doc://com.apple.appkit/documentation/AppKit/NSWindow/hasDynamicDepthLimit","doc://com.apple.appkit/documentation/AppKit/NSWindow/defaultDepthLimit","doc://com.apple.appkit/documentation/AppKit/NSWindow/windowNumber","doc://com.apple.appkit/documentation/AppKit/NSWindow/deviceDescription","doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey","doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeVisibleWithoutLogin","doc://com.apple.appkit/documentation/AppKit/NSWindow/sharingType-swift.property","doc://com.apple.appkit/documentation/AppKit/NSWindow/backingType","doc://com.apple.appkit/documentation/AppKit/NSWindow/displayLink(target:selector:)"],"anchor":"Accessing-Window-Information","generated":true,"title":"Accessing Window Information"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"windowNumbers"},{"kind":"text","text":"("},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","text":"NSWindow","preciseIdentifier":"c:objc(cs)NSWindow"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/NumberListOptions","text":"NumberListOptions","preciseIdentifier":"c:@E@NSWindowNumberListOptions"},{"kind":"text","text":" = []) -> ["},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSNumber","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"parameters":[{"name":"options","content":[{"inlineContent":[{"type":"text","text":"The possible options are specified in "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/NumberListOptions","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"An array of window numbers for all visible windows satisfying the specified options. (Windows on the active space are returned in z-order; that is, front to back.)","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/appkit/nswindow/windownumbers(options:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nswindow/windownumbers(options:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/windowNumbers(options:)"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeVisibleWithoutLogin":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeVisibleWithoutLogin","abstract":[{"text":"A Boolean value that indicates whether the window can be displayed at the login window.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"canBecomeVisibleWithoutLogin"}],"url":"/documentation/appkit/nswindow/canbecomevisiblewithoutlogin","title":"canBecomeVisibleWithoutLogin","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canBecomeVisibleWithoutLogin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/depthLimit":{"title":"depthLimit","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/depthLimit","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"depthLimit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier","text":"NSWindow"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSWindowDepth","text":"Depth","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nswindow/depthlimit","kind":"symbol","abstract":[{"type":"text","text":"The depth limit of the window."}],"navigatorTitle":[{"text":"depthLimit","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/backingType":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/backingType","abstract":[{"text":"The window’s backing store type.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"backingType","kind":"identifier"}],"url":"/documentation/appkit/nswindow/backingtype","title":"backingType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backingType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSBackingStoreType","text":"BackingStoreType","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSNumber":{"url":"/documentation/foundation/nsnumber","kind":"symbol","title":"NSNumber","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSNumber","type":"topic","abstract":[{"text":"An object wrapper for primitive scalar numeric values.","type":"text"}],"fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSNumber"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/hasDynamicDepthLimit":{"title":"hasDynamicDepthLimit","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/hasDynamicDepthLimit","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasDynamicDepthLimit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nswindow/hasdynamicdepthlimit","kind":"symbol","abstract":[{"type":"text","text":"A Boolean value that indicates whether the window’s depth limit can change to match the depth of the screen it’s on."}],"navigatorTitle":[{"kind":"identifier","text":"hasDynamicDepthLimit"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/deviceDescription":{"url":"/documentation/appkit/nswindow/devicedescription","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/deviceDescription","abstract":[{"type":"text","text":"A dictionary containing information about the window’s resolution, such as color, depth, and so on."}],"kind":"symbol","navigatorTitle":[{"text":"deviceDescription","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceDescription","kind":"identifier"},{"text":": [","kind":"text"},{"text":"NSDeviceDescriptionKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSDeviceDescriptionKey"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"title":"deviceDescription"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/defaultDepthLimit":{"url":"/documentation/appkit/nswindow/defaultdepthlimit","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/defaultDepthLimit","abstract":[{"type":"text","text":"Returns the default depth limit for instances of "},{"code":"NSWindow","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"defaultDepthLimit","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultDepthLimit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSWindowDepth","text":"Depth","kind":"typeIdentifier"}],"title":"defaultDepthLimit"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey":{"abstract":[{"text":"These constants are the keys for device description dictionaries.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSDeviceDescriptionKey"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey","url":"/documentation/appkit/nsdevicedescriptionkey","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSDeviceDescriptionKey"}],"role":"symbol","title":"NSDeviceDescriptionKey"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/NumberListOptions":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/NumberListOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NumberListOptions"}],"type":"topic","abstract":[{"text":"Options to use when retrieving window numbers from the system.","type":"text"}],"url":"/documentation/appkit/nswindow/numberlistoptions","title":"NSWindow.NumberListOptions","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NumberListOptions"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/displayLink(target:selector:)":{"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayLink"},{"kind":"text","text":"("},{"kind":"externalParam","text":"target"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":", ","kind":"text"},{"text":"selector","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CADisplayLink","text":"CADisplayLink","kind":"typeIdentifier"}],"url":"/documentation/appkit/nswindow/displaylink(target:selector:)","role":"symbol","title":"displayLink(target:selector:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/displayLink(target:selector:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"displayLinkWithTarget:selector:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/windowNumber":{"url":"/documentation/appkit/nswindow/windownumber","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/windowNumber","abstract":[{"type":"text","text":"The window number of the window’s window device."}],"kind":"symbol","navigatorTitle":[{"text":"windowNumber","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"windowNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"windowNumber"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/windowNumbers(options:)":{"abstract":[{"text":"Returns the window numbers for all visible windows satisfying the specified options.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"windowNumbers"},{"text":"(","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSWindowNumberListOptions","text":"NumberListOptions","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"url":"/documentation/appkit/nswindow/windownumbers(options:)","role":"symbol","title":"windowNumbers(options:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/windowNumbers(options:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"windowNumbersWithOptions:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/sharingType-swift.property":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/sharingType-swift.property","abstract":[{"text":"A Boolean value that indicates the level of access other processes have to the window’s content.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"sharingType","kind":"identifier"}],"url":"/documentation/appkit/nswindow/sharingtype-swift.property","title":"sharingType","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharingType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSWindowSharingType","text":"SharingType","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"name":"macOS","unavailable":false,"beta":false,"introducedAt":"10.6"}],"path":"/metadata/platforms","op":"replace"},{"value":"Type Method","path":"/metadata/roleHeading","op":"replace"},{"value":"windowNumbersWithOptions:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"windowNumbersWithOptions:"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Accessing Window Information","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/depthLimit","doc://com.apple.appkit/documentation/AppKit/NSWindow/hasDynamicDepthLimit","doc://com.apple.appkit/documentation/AppKit/NSWindow/defaultDepthLimit","doc://com.apple.appkit/documentation/AppKit/NSWindow/windowNumber","doc://com.apple.appkit/documentation/AppKit/NSWindow/deviceDescription","doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey","doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeVisibleWithoutLogin","doc://com.apple.appkit/documentation/AppKit/NSWindow/sharingType-swift.property","doc://com.apple.appkit/documentation/AppKit/NSWindow/backingType","doc://com.apple.appkit/documentation/AppKit/NSWindow/displayLink(target:selector:)"],"anchor":"Accessing-Window-Information","generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSNumber *>"},{"kind":"text","text":" *) "},{"text":"windowNumbersWithOptions:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSWindowNumberListOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSWindowNumberListOptions","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/NumberListOptions"},{"text":") ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"options","content":[{"inlineContent":[{"text":"The possible options are specified in ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/NumberListOptions"},{"text":".","type":"text"}],"type":"paragraph"}]}]},"path":"/primaryContentSections/1","op":"replace"},{"value":{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"An array of window numbers for all visible windows satisfying the specified options. (Windows on the active space are returned in z-order; that is, front to back.)"}],"type":"paragraph"}],"kind":"content"},"path":"/primaryContentSections/2","op":"replace"},{"value":"canBecomeVisibleWithoutLogin","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1canBecomeVisibleWithoutLogin/title","op":"replace"},{"value":[{"kind":"identifier","text":"canBecomeVisibleWithoutLogin"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1canBecomeVisibleWithoutLogin/fragments","op":"replace"},{"value":"depthLimit","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1depthLimit/title","op":"replace"},{"value":[{"text":"depthLimit","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1depthLimit/fragments","op":"replace"},{"value":"backingType","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1backingType/title","op":"replace"},{"value":[{"text":"backingType","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1backingType/fragments","op":"replace"},{"value":"NSWindow","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title","op":"replace"},{"value":[{"text":"NSWindow","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments","op":"replace"},{"value":[{"text":"NSWindow","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle","op":"replace"},{"value":"hasDynamicDepthLimit","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1hasDynamicDepthLimit/title","op":"replace"},{"value":[{"text":"hasDynamicDepthLimit","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1hasDynamicDepthLimit/fragments","op":"replace"},{"value":"deviceDescription","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1deviceDescription/title","op":"replace"},{"value":[{"text":"deviceDescription","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1deviceDescription/fragments","op":"replace"},{"value":"defaultDepthLimit","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1defaultDepthLimit/title","op":"replace"},{"value":[{"text":"defaultDepthLimit","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1defaultDepthLimit/fragments","op":"replace"},{"value":"NSDeviceDescriptionKey","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey/title","op":"replace"},{"value":[{"text":"NSDeviceDescriptionKey","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey/fragments","op":"replace"},{"value":[{"text":"NSDeviceDescriptionKey","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey/navigatorTitle","op":"replace"},{"value":"NSWindowNumberListOptions","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1NumberListOptions/title","op":"replace"},{"value":[{"text":"NSWindowNumberListOptions","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1NumberListOptions/fragments","op":"replace"},{"value":[{"text":"NSWindowNumberListOptions","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1NumberListOptions/navigatorTitle","op":"replace"},{"value":"displayLinkWithTarget:selector:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1displayLink(target:selector:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"displayLinkWithTarget:selector:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1displayLink(target:selector:)/fragments","op":"replace"},{"value":"windowNumber","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1windowNumber/title","op":"replace"},{"value":[{"kind":"identifier","text":"windowNumber"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1windowNumber/fragments","op":"replace"},{"value":"windowNumbersWithOptions:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1windowNumbers(options:)/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"windowNumbersWithOptions:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1windowNumbers(options:)/fragments","op":"replace"},{"value":"sharingType","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1sharingType-swift.property/title","op":"replace"},{"value":[{"kind":"identifier","text":"sharingType"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1sharingType-swift.property/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}