{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSWindow/zoom(_:)"},"sections":[],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/frame","doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameOrigin(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameTopLeftPoint(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/constrainFrameRect(_:to:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/cascadeTopLeft(from:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrame(_:display:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrame(_:display:animate:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/animationResizeTime(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/aspectRatio","doc://com.apple.appkit/documentation/AppKit/NSWindow/minSize","doc://com.apple.appkit/documentation/AppKit/NSWindow/maxSize","doc://com.apple.appkit/documentation/AppKit/NSWindow/isZoomed","doc://com.apple.appkit/documentation/AppKit/NSWindow/performZoom(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/resizeFlags","doc://com.apple.appkit/documentation/AppKit/NSWindow/resizeIncrements"],"anchor":"Sizing-Windows","title":"Sizing Windows"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/appkit/nswindow/zoom(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nswindow/zoom(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"zoom:","kind":"identifier"}],"platforms":[{"deprecated":false,"name":"macOS","unavailable":false,"beta":false}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zoom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"modules":[{"name":"AppKit"}],"roleHeading":"Instance Method","role":"symbol","title":"zoom(_:)","externalID":"c:objc(cs)NSWindow(im)zoom:"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoom"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The object sending the message.","type":"text"}],"type":"paragraph"}],"name":"sender"}]},{"kind":"content","content":[{"anchor":"Discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"text":"For more information on the standard and user states, see ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate/windowWillUseStandardFrame(_:defaultFrame:)"},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Typically, the system invokes the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/zoom(_:)","type":"reference"},{"text":" method after a user clicks the window’s zoom box, and ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/performZoom(_:)","type":"reference"},{"text":" may also invoke ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/zoom(_:)","type":"reference"},{"type":"text","text":" programmatically. It performs the following steps:"}],"type":"paragraph"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"Invokes the ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate/windowWillUseStandardFrame(_:defaultFrame:)","isActive":true,"type":"reference"},{"text":" method, if the delegate or the window class implements it, to obtain a “best fit” frame for the window. If neither the delegate nor the window class implements the method, ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/zoom(_:)","isActive":true,"type":"reference"},{"text":" uses a default frame. The default frame nearly fills the current screen that contains the largest part of the window’s current frame.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Adjusts the resulting frame, if necessary, to fit on the current screen.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Compares the resulting frame to the current frame to determine whether the window’s standard frame is currently displayed. If the current frame is within a few pixels of the standard frame in size and location, the system considers it a match."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Determines a new frame. If the window is currently in the standard state, the new frame represents the user state, saved during a previous zoom. If the window is currently in the user state, the new frame represents the standard state, computed in step 1 above. If there’s no saved user state because there has been no previous zoom, the size and location of the window don’t change."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Determines whether the window currently allows zooming. By default, zooming is allowed. If the window’s delegate implements the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate/windowShouldZoom(_:toFrame:)"},{"text":" method, ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/zoom(_:)"},{"text":" invokes that method. If the delegate doesn’t implement the method but the window does, ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/zoom(_:)"},{"text":" invokes the window’s version. ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate/windowShouldZoom(_:toFrame:)"},{"text":" returns ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false"},{"text":" if zooming isn’t currently allowed.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"If the window currently allows zooming, sets the new frame.","type":"text"}]}]}]}]}],"abstract":[{"text":"Toggles the size and location of the window between its standard state (which the application provides as the best size to display the window’s data) and its user state (a new size and location the user may have set by moving or resizing the window).","type":"text"}],"kind":"symbol","references":{"doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate/windowShouldZoom(_:toFrame:)":{"type":"topic","url":"/documentation/appkit/nswindowdelegate/windowshouldzoom(_:toframe:)","role":"symbol","abstract":[{"text":"Asks the delegate whether the specified window should zoom to the specified frame.","type":"text"}],"navigatorTitle":[{"text":"windowShouldZoom:toFrame:","kind":"identifier"}],"title":"windowShouldZoom(_:toFrame:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate/windowShouldZoom(_:toFrame:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"windowShouldZoom"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSWindow","kind":"typeIdentifier","text":"NSWindow"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toFrame"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrame(_:display:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setFrame:display:"}],"abstract":[{"text":"Sets the origin and size of the window’s frame rectangle according to a given frame rectangle, thereby setting its position and size onscreen.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","text":"NSRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"display"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrame(_:display:)","url":"/documentation/appkit/nswindow/setframe(_:display:)","title":"setFrame(_:display:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/frame":{"abstract":[{"type":"text","text":"The window’s frame rectangle in screen coordinates, including the title bar."}],"url":"/documentation/appkit/nswindow/frame","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frame","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/frame","title":"frame","navigatorTitle":[{"text":"frame","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/resizeIncrements":{"kind":"symbol","url":"/documentation/appkit/nswindow/resizeincrements","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"resizeIncrements"}],"abstract":[{"type":"text","text":"The window’s resizing increments."}],"title":"resizeIncrements","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resizeIncrements"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSSize","kind":"typeIdentifier","text":"NSSize"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/resizeIncrements","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/zoom(_:)":{"title":"zoom(_:)","navigatorTitle":[{"kind":"identifier","text":"zoom:"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/zoom(_:)","role":"symbol","url":"/documentation/appkit/nswindow/zoom(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoom"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"abstract":[{"text":"Toggles the size and location of the window between its standard state (which the application provides as the best size to display the window’s data) and its user state (a new size and location the user may have set by moving or resizing the window).","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindow/resizeFlags":{"kind":"symbol","url":"/documentation/appkit/nswindow/resizeflags","role":"symbol","navigatorTitle":[{"text":"resizeFlags","kind":"identifier"}],"abstract":[{"text":"The flags field of the event record for the mouse-down event that initiated the resizing session.","type":"text"}],"title":"resizeFlags","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resizeFlags","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ModifierFlags","preciseIdentifier":"c:@E@NSEventModifierFlags","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/resizeFlags","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/cascadeTopLeft(from:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cascadeTopLeft","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSPoint","preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/cascadeTopLeft(from:)","abstract":[{"type":"text","text":"Positions the window’s top-left to a given point."}],"type":"topic","title":"cascadeTopLeft(from:)","kind":"symbol","navigatorTitle":[{"text":"cascadeTopLeftFromPoint:","kind":"identifier"}],"url":"/documentation/appkit/nswindow/cascadetopleft(from:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/animationResizeTime(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animationResizeTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/animationResizeTime(_:)","abstract":[{"text":"Specifies the duration of a smooth frame-size change.","type":"text"}],"type":"topic","title":"animationResizeTime(_:)","kind":"symbol","navigatorTitle":[{"text":"animationResizeTime:","kind":"identifier"}],"url":"/documentation/appkit/nswindow/animationresizetime(_:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/performZoom(_:)":{"url":"/documentation/appkit/nswindow/performzoom(_:)","title":"performZoom(_:)","kind":"symbol","abstract":[{"text":"This action method simulates the user clicking the zoom box by momentarily highlighting the button and then zooming the window.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/performZoom(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"performZoom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"performZoom:","kind":"identifier"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/minSize":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSSize","text":"NSSize","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/minSize","abstract":[{"type":"text","text":"The minimum size to which the window’s frame (including its title bar) can be sized."}],"type":"topic","title":"minSize","kind":"symbol","navigatorTitle":[{"text":"minSize","kind":"identifier"}],"url":"/documentation/appkit/nswindow/minsize","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrame(_:display:animate:)":{"title":"setFrame(_:display:animate:)","navigatorTitle":[{"kind":"identifier","text":"setFrame:display:animate:"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrame(_:display:animate:)","role":"symbol","url":"/documentation/appkit/nswindow/setframe(_:display:animate:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"display"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"text":"Sets the origin and size of the window’s frame rectangle, with optional animation, according to a given frame rectangle, thereby setting its position and size onscreen.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate/windowWillUseStandardFrame(_:defaultFrame:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate/windowWillUseStandardFrame(_:defaultFrame:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"windowWillUseStandardFrame","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSWindow","text":"NSWindow","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"defaultFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"}],"url":"/documentation/appkit/nswindowdelegate/windowwillusestandardframe(_:defaultframe:)","navigatorTitle":[{"text":"windowWillUseStandardFrame:defaultFrame:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Called by "},{"type":"codeVoice","code":"NSWindow"},{"text":"’s ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/zoom(_:)"},{"text":" method while determining the frame a window may be zoomed to.","type":"text"}],"title":"windowWillUseStandardFrame(_:defaultFrame:)","role":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/swift/false":{"title":"false","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/false","role":"symbol","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","url":"/documentation/swift/false"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameTopLeftPoint(_:)":{"url":"/documentation/appkit/nswindow/setframetopleftpoint(_:)","title":"setFrameTopLeftPoint(_:)","kind":"symbol","abstract":[{"type":"text","text":"Positions the top-left corner of the window’s frame rectangle at a given point in screen coordinates."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameTopLeftPoint(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFrameTopLeftPoint"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSPoint","kind":"typeIdentifier","text":"NSPoint"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"setFrameTopLeftPoint:"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/maxSize":{"kind":"symbol","url":"/documentation/appkit/nswindow/maxsize","title":"maxSize","navigatorTitle":[{"text":"maxSize","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSSize","preciseIdentifier":"c:@T@NSSize","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"The maximum size to which the window’s frame (including its title bar) can be sized."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/maxSize","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/aspectRatio":{"abstract":[{"type":"text","text":"The window’s aspect ratio, which constrains the size of its frame rectangle to integral multiples of this ratio when the user resizes it."}],"url":"/documentation/appkit/nswindow/aspectratio","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSSize","preciseIdentifier":"c:@T@NSSize","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"aspectRatio","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/aspectRatio","role":"symbol","type":"topic","title":"aspectRatio"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameOrigin(_:)":{"abstract":[{"type":"text","text":"Positions the bottom-left corner of the window’s frame rectangle at a given point in screen coordinates."}],"url":"/documentation/appkit/nswindow/setframeorigin(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFrameOrigin","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSPoint","text":"NSPoint","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"setFrameOrigin:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameOrigin(_:)","role":"symbol","type":"topic","title":"setFrameOrigin(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/isZoomed":{"url":"/documentation/appkit/nswindow/iszoomed","title":"isZoomed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isZoomed"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"zoomed"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/isZoomed","abstract":[{"type":"text","text":"A Boolean value that indicates whether the window is in a zoomed state."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWindow/constrainFrameRect(_:to:)":{"title":"constrainFrameRect(_:to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"constrainFrameRect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSScreen","preciseIdentifier":"c:objc(cs)NSScreen"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"NSRect","preciseIdentifier":"c:@T@NSRect"}],"kind":"symbol","abstract":[{"text":"Modifies and returns a frame rectangle so that its top edge lies on a specific screen.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nswindow/constrainframerect(_:to:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow/constrainFrameRect(_:to:)","navigatorTitle":[{"kind":"identifier","text":"constrainFrameRect:toScreen:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"name":"macOS","beta":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"zoom:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"zoom:","kind":"identifier"}]},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSWindow"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Sizing Windows","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSWindow/frame","doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameOrigin(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrameTopLeftPoint(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/constrainFrameRect(_:to:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/cascadeTopLeft(from:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrame(_:display:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/setFrame(_:display:animate:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/animationResizeTime(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/aspectRatio","doc://com.apple.appkit/documentation/AppKit/NSWindow/minSize","doc://com.apple.appkit/documentation/AppKit/NSWindow/maxSize","doc://com.apple.appkit/documentation/AppKit/NSWindow/isZoomed","doc://com.apple.appkit/documentation/AppKit/NSWindow/performZoom(_:)","doc://com.apple.appkit/documentation/AppKit/NSWindow/resizeFlags","doc://com.apple.appkit/documentation/AppKit/NSWindow/resizeIncrements"],"anchor":"Sizing-Windows"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"zoom:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"sender","content":[{"type":"paragraph","inlineContent":[{"text":"The object sending the message.","type":"text"}]}]}]},"path":"/primaryContentSections/1","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowDelegate~1windowShouldZoom(_:toFrame:)/title","op":"replace","value":"windowShouldZoom:toFrame:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowDelegate~1windowShouldZoom(_:toFrame:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"windowShouldZoom:toFrame:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setFrame(_:display:)/title","value":"setFrame:display:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setFrame(_:display:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFrame:display:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1frame/title","value":"frame"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1frame/fragments","value":[{"text":"frame","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1resizeIncrements/title","value":"resizeIncrements","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1resizeIncrements/fragments","value":[{"kind":"identifier","text":"resizeIncrements"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1zoom(_:)/title","value":"zoom:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1zoom(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"zoom:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1resizeFlags/title","value":"resizeFlags","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1resizeFlags/fragments","value":[{"text":"resizeFlags","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1cascadeTopLeft(from:)/title","value":"cascadeTopLeftFromPoint:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1cascadeTopLeft(from:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"cascadeTopLeftFromPoint:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title","value":"NSWindow","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments","value":[{"text":"NSWindow","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle","value":[{"kind":"identifier","text":"NSWindow"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1animationResizeTime(_:)/title","value":"animationResizeTime:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1animationResizeTime(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"animationResizeTime:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1performZoom(_:)/title","value":"performZoom:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1performZoom(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"performZoom:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1minSize/title","value":"minSize","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1minSize/fragments","value":[{"text":"minSize","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setFrame(_:display:animate:)/title","value":"setFrame:display:animate:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setFrame(_:display:animate:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setFrame:display:animate:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowDelegate~1windowWillUseStandardFrame(_:defaultFrame:)/title","value":"windowWillUseStandardFrame:defaultFrame:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowDelegate~1windowWillUseStandardFrame(_:defaultFrame:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"windowWillUseStandardFrame:defaultFrame:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setFrameTopLeftPoint(_:)/title","value":"setFrameTopLeftPoint:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setFrameTopLeftPoint(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setFrameTopLeftPoint:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1maxSize/title","value":"maxSize","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1maxSize/fragments","value":[{"text":"maxSize","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1aspectRatio/title","value":"aspectRatio","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1aspectRatio/fragments","value":[{"text":"aspectRatio","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setFrameOrigin(_:)/title","value":"setFrameOrigin:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1setFrameOrigin(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setFrameOrigin:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isZoomed/title","value":"zoomed","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isZoomed/fragments","value":[{"text":"zoomed","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1constrainFrameRect(_:to:)/title","value":"constrainFrameRect:toScreen:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1constrainFrameRect(_:to:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"constrainFrameRect:toScreen:"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}