{
  "abstract": [
    {
      "text": "Creates a menu configuration object with the specified action and preview providers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIContextMenuConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuConfiguration/configurationWithIdentifier:previewProvider:actionProvider:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIContextMenuConfiguration(cm)configurationWithIdentifier:previewProvider:actionProvider:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "configurationWithIdentifier:previewProvider:actionProvider:"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "configurationWithIdentifier:previewProvider:actionProvider:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "configurationWithIdentifier:previewProvider:actionProvider:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "configurationWithIdentifier:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Qoobjc(pl)NSCopying",
              "text": "id<NSCopying>"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "identifier"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "previewProvider:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuContentPreviewProvider",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UIContextMenuContentPreviewProvider",
              "text": "UIContextMenuContentPreviewProvider"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "previewProvider"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "actionProvider:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuActionProvider",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UIContextMenuActionProvider",
              "text": "UIContextMenuActionProvider"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "actionProvider"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A unique identifier for the menu configuration object. If you want this method to generate a unique identifier for you, specify ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "identifier"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An optional block that returns the custom view controller that you use to preview content. If you specify ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": ", UIKit uses a default preview view controller.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "previewProvider"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An optional block that provides a contextual menu to display with the preview. If you specify ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": ", UIKit doesn’t display a contextual menu with the previewed content.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "actionProvider"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new menu configuration object with the specified provider blocks.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContextMenuActionProvider": {
      "abstract": [
        {
          "text": "Returns an action-based contextual menu, optionally incorporating the system-suggested actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContextMenuActionProvider"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuActionProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContextMenuActionProvider"
        }
      ],
      "role": "symbol",
      "title": "UIContextMenuActionProvider",
      "type": "topic",
      "url": "/documentation/uikit/uicontextmenuactionprovider"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContextMenuConfiguration": {
      "abstract": [
        {
          "text": "An object containing the configuration details for the contextual menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContextMenuConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContextMenuConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIContextMenuConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicontextmenuconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContextMenuConfiguration/configurationWithIdentifier:previewProvider:actionProvider:": {
      "abstract": [
        {
          "text": "Creates a menu configuration object with the specified action and preview providers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "configurationWithIdentifier:previewProvider:actionProvider:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuConfiguration/configurationWithIdentifier:previewProvider:actionProvider:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configurationWithIdentifier:previewProvider:actionProvider:"
        }
      ],
      "role": "symbol",
      "title": "configurationWithIdentifier:previewProvider:actionProvider:",
      "type": "topic",
      "url": "/documentation/uikit/uicontextmenuconfiguration/configurationwithidentifier:previewprovider:actionprovider:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContextMenuContentPreviewProvider": {
      "abstract": [
        {
          "text": "Returns the custom view controller to use when previewing your content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContextMenuContentPreviewProvider"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuContentPreviewProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContextMenuContentPreviewProvider"
        }
      ],
      "role": "symbol",
      "title": "UIContextMenuContentPreviewProvider",
      "type": "topic",
      "url": "/documentation/uikit/uicontextmenucontentpreviewprovider"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-the-menu-configuration-object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContextMenuContentPreviewProvider",
        "doc://com.apple.uikit/documentation/UIKit/UIContextMenuActionProvider"
      ],
      "title": "Creating the menu configuration object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuContentPreviewProvider/title",
          "value": "UIContextMenuContentPreviewProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuContentPreviewProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuContentPreviewProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuContentPreviewProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuContentPreviewProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuActionProvider/title",
          "value": "UIContextMenuActionProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuActionProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuActionProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuActionProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuActionProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuConfiguration/title",
          "value": "UIContextMenuConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicontextmenuconfiguration/configurationwithidentifier:previewprovider:actionprovider:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
