{
  "abstract": [
    {
      "text": "The app isn’t entitled to perform the actions in the requested transaction.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unentitled"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CXErrorCodeRequestTransactionError@CXErrorCodeRequestTransactionErrorUnentitled",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unentitled"
      }
    ],
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CXErrorCodeRequestTransactionErrorUnentitled"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CXErrorCodeRequestTransactionError.Code.unentitled"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unentitled"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You most commonly receive this error code when the ",
              "type": "text"
            },
            {
              "code": "voip",
              "type": "codeVoice"
            },
            {
              "text": " value is missing from the ",
              "type": "text"
            },
            {
              "code": "UIBackgroundModes",
              "type": "codeVoice"
            },
            {
              "text": " array in your app’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionError"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionError"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for the CallKit error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/callUUIDAlreadyExists": {
      "abstract": [
        {
          "text": "The requested transaction contains call actions that reference a UUID that already exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callUUIDAlreadyExists"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/callUUIDAlreadyExists",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionErrorCallUUIDAlreadyExists"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code.callUUIDAlreadyExists",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/calluuidalreadyexists"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/emptyTransaction": {
      "abstract": [
        {
          "text": "The requested transaction contains no actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emptyTransaction"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/emptyTransaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionErrorEmptyTransaction"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code.emptyTransaction",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/emptytransaction"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/invalidAction": {
      "abstract": [
        {
          "text": "The requested transaction contains an invalid action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAction"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/invalidAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionErrorInvalidAction"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code.invalidAction",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/invalidaction"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/maximumCallGroupsReached": {
      "abstract": [
        {
          "text": "The requested transaction contains actions that, if performed, would exceed the maximum number of call groups for the provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumCallGroupsReached"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/maximumCallGroupsReached",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionErrorMaximumCallGroupsReached"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code.maximumCallGroupsReached",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/maximumcallgroupsreached"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unentitled": {
      "abstract": [
        {
          "text": "The app isn’t entitled to perform the actions in the requested transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unentitled"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unentitled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionErrorUnentitled"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code.unentitled",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/unentitled"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code.unknown",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/unknown"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknownCallProvider": {
      "abstract": [
        {
          "text": "The controller couldn’t find a call provider to perform the actions in the requested transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownCallProvider"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknownCallProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionErrorUnknownCallProvider"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code.unknownCallProvider",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/unknowncallprovider"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknownCallUUID": {
      "abstract": [
        {
          "text": "The requested transaction contains call actions that reference an unknown UUID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownCallUUID"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknownCallUUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeRequestTransactionErrorUnknownCallUUID"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeRequestTransactionError.Code.unknownCallUUID",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/unknowncalluuid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknown",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknownCallProvider",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/emptyTransaction",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknownCallUUID",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/callUUIDAlreadyExists",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/invalidAction",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/maximumCallGroupsReached"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CXErrorCodeRequestTransactionErrorUnentitled"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionErrorUnentitled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.callkit/documentation/CallKit",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknown",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknownCallProvider",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/emptyTransaction",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/unknownCallUUID",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/callUUIDAlreadyExists",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/invalidAction",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeRequestTransactionError-swift.struct/Code/maximumCallGroupsReached"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CXErrorCodeRequestTransactionErrorUnentitled"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1unknown/title",
          "value": "CXErrorCodeRequestTransactionErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code/title",
          "value": "CXErrorCodeRequestTransactionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1unknownCallUUID/title",
          "value": "CXErrorCodeRequestTransactionErrorUnknownCallUUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1unknownCallUUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionErrorUnknownCallUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1maximumCallGroupsReached/title",
          "value": "CXErrorCodeRequestTransactionErrorMaximumCallGroupsReached"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1maximumCallGroupsReached/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionErrorMaximumCallGroupsReached"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1invalidAction/title",
          "value": "CXErrorCodeRequestTransactionErrorInvalidAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1invalidAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionErrorInvalidAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1unentitled/title",
          "value": "CXErrorCodeRequestTransactionErrorUnentitled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1unentitled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionErrorUnentitled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1unknownCallProvider/title",
          "value": "CXErrorCodeRequestTransactionErrorUnknownCallProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1unknownCallProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionErrorUnknownCallProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1callUUIDAlreadyExists/title",
          "value": "CXErrorCodeRequestTransactionErrorCallUUIDAlreadyExists"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1callUUIDAlreadyExists/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionErrorCallUUIDAlreadyExists"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1emptyTransaction/title",
          "value": "CXErrorCodeRequestTransactionErrorEmptyTransaction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeRequestTransactionError-swift.struct~1Code~1emptyTransaction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeRequestTransactionErrorEmptyTransaction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/unentitled"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/callkit/cxerrorcoderequesttransactionerror-swift.struct/code/unentitled"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
