{
  "abstract": [
    {
      "text": "Specifies a change due to undo from deletion.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/undoDeletion"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSSnapshotEventType@NSSnapshotEventUndoDeletion",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "undoDeletion"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSSnapshotEventType",
        "text": "NSSnapshotEventType"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSSnapshotEventUndoDeletion"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "undoDeletion"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "undoDeletion"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSSnapshotEventType",
              "text": "NSSnapshotEventType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType": {
      "abstract": [
        {
          "text": "Constants that specify the reason the managed object may need to reinitialize its values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSnapshotEventType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSnapshotEventType"
        }
      ],
      "role": "symbol",
      "title": "NSSnapshotEventType",
      "type": "topic",
      "url": "/documentation/coredata/nssnapshoteventtype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/mergePolicy": {
      "abstract": [
        {
          "text": "Specifies a change due to conflict resolution during a save operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mergePolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSnapshotEventType",
          "text": "NSSnapshotEventType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/mergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSnapshotEventMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "mergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nssnapshoteventtype/mergepolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/refresh": {
      "abstract": [
        {
          "text": "Specifies a change due to the managed object being refreshed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "refresh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSnapshotEventType",
          "text": "NSSnapshotEventType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/refresh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSnapshotEventRefresh"
        }
      ],
      "role": "symbol",
      "title": "refresh",
      "type": "topic",
      "url": "/documentation/coredata/nssnapshoteventtype/refresh"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/rollback": {
      "abstract": [
        {
          "text": "Specifies a change due to the managed object context being rolled back.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rollback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSnapshotEventType",
          "text": "NSSnapshotEventType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/rollback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSnapshotEventRollback"
        }
      ],
      "role": "symbol",
      "title": "rollback",
      "type": "topic",
      "url": "/documentation/coredata/nssnapshoteventtype/rollback"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/undoDeletion": {
      "abstract": [
        {
          "text": "Specifies a change due to undo from deletion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undoDeletion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSnapshotEventType",
          "text": "NSSnapshotEventType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/undoDeletion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSnapshotEventUndoDeletion"
        }
      ],
      "role": "symbol",
      "title": "undoDeletion",
      "type": "topic",
      "url": "/documentation/coredata/nssnapshoteventtype/undodeletion"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/undoInsertion": {
      "abstract": [
        {
          "text": "Specifies a change due to undo from insertion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undoInsertion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSnapshotEventType",
          "text": "NSSnapshotEventType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/undoInsertion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSnapshotEventUndoInsertion"
        }
      ],
      "role": "symbol",
      "title": "undoInsertion",
      "type": "topic",
      "url": "/documentation/coredata/nssnapshoteventtype/undoinsertion"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/undoUpdate": {
      "abstract": [
        {
          "text": "Specifies a change due to a property-level undo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undoUpdate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSnapshotEventType",
          "text": "NSSnapshotEventType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/undoUpdate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSnapshotEventUndoUpdate"
        }
      ],
      "role": "symbol",
      "title": "undoUpdate",
      "type": "topic",
      "url": "/documentation/coredata/nssnapshoteventtype/undoupdate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Event-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/undoInsertion",
        "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/undoUpdate",
        "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/rollback",
        "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/refresh",
        "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/mergePolicy"
      ],
      "title": "Event Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSSnapshotEventUndoDeletion"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSnapshotEventUndoDeletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData",
                "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Event-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/undoInsertion",
                "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/undoUpdate",
                "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/rollback",
                "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/refresh",
                "doc://com.apple.coredata/documentation/CoreData/NSSnapshotEventType/mergePolicy"
              ],
              "title": "Event Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSSnapshotEventUndoDeletion"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSnapshotEventType~1refresh/title",
          "value": "NSSnapshotEventRefresh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSnapshotEventType~1refresh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSnapshotEventRefresh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSnapshotEventType/title",
          "value": "NSSnapshotEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSnapshotEventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSnapshotEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSnapshotEventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSnapshotEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSnapshotEventType~1mergePolicy/title",
          "value": "NSSnapshotEventMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSnapshotEventType~1mergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSnapshotEventMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSnapshotEventType~1undoDeletion/title",
          "value": "NSSnapshotEventUndoDeletion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSnapshotEventType~1undoDeletion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSnapshotEventUndoDeletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSnapshotEventType~1rollback/title",
          "value": "NSSnapshotEventRollback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSnapshotEventType~1rollback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSnapshotEventRollback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSnapshotEventType~1undoUpdate/title",
          "value": "NSSnapshotEventUndoUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSnapshotEventType~1undoUpdate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSnapshotEventUndoUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSnapshotEventType~1undoInsertion/title",
          "value": "NSSnapshotEventUndoInsertion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSnapshotEventType~1undoInsertion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSnapshotEventUndoInsertion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nssnapshoteventtype/undodeletion"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nssnapshoteventtype/undodeletion"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
