{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstackview/addview(_:in:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsstackview/addview(_:in:)"]}],"abstract":[{"type":"text","text":"Adds a view to the end of the stack view gravity area."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSStackView/addView(_:in:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"view","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"gravity","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSStackView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSStackView"},{"text":".","kind":"text"},{"text":"Gravity","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Gravity","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSStackViewGravity"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"name":"view","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view to add to the specified gravity area."}]}]},{"name":"gravity","content":[{"inlineContent":[{"text":"The gravity area that you are adding the specified view to. Valid values are those in the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Gravity","type":"reference"},{"text":" enumeration.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The location of a newly added view depends on the stack view layout direction and, for a horizontal stack view, on user interface language:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"emphasis","inlineContent":[{"text":"Horizontal","type":"text"}]},{"type":"text","text":": A newly added view appears at the trailing edge of the specified gravity area, as determined by the value of the inherited "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/userInterfaceLayoutDirection","isActive":true},{"type":"text","text":" property of the stack view. For a left to right language, a new view appears at the right side of the gravity area."}]}]},{"content":[{"inlineContent":[{"inlineContent":[{"text":"Vertical","type":"text"}],"type":"emphasis"},{"text":": A newly added view appears at the bottom of the specified gravity area.","type":"text"}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Calling this method updates the stack view’s layout, which can change the stack view size. As a result, views could detach or clip according to the clipping resistance of the stack view and the visibility priorities of its views."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A view in a detached state is not present in the stack view’s view hierarchy, but it still consumes memory. To respond to detachment and reattachment of views, implement an "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackViewDelegate"},{"type":"text","text":" object and assign it to the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/delegate"},{"type":"text","text":" property."}]}]}],"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Method","modules":[{"name":"AppKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSView","preciseIdentifier":"c:objc(cs)NSView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSStackView","preciseIdentifier":"c:objc(cs)NSStackView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Gravity","preciseIdentifier":"c:@E@NSStackViewGravity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","extendedModule":"AppKit","navigatorTitle":[{"text":"addView:inGravity:","kind":"identifier"}],"platforms":[{"name":"macOS","unavailable":false,"deprecated":false,"beta":false}],"externalID":"c:objc(cs)NSStackView(im)addView:inGravity:","title":"addView(_:in:)","role":"symbol"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView"]]},"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/setVisibilityPriority(_:for:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","doc://com.apple.appkit/documentation/AppKit/NSStackView/setClippingResistancePriority(_:for:)"]},{"anchor":"Managing-Views-in-Gravity-Areas","generated":true,"title":"Managing Views in Gravity Areas","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/insertView(_:at:in:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/setViews(_:in:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/removeView(_:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/Gravity"]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSStackView/addView(_:in:)":{"kind":"symbol","url":"/documentation/appkit/nsstackview/addview(_:in:)","role":"symbol","navigatorTitle":[{"text":"addView:inGravity:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","text":"NSView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSStackView","kind":"typeIdentifier","text":"NSStackView"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSStackViewGravity","kind":"typeIdentifier","text":"Gravity"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/addView(_:in:)","title":"addView(_:in:)","abstract":[{"type":"text","text":"Adds a view to the end of the stack view gravity area."}]},"doc://com.apple.appkit/documentation/AppKit/NSView/userInterfaceLayoutDirection":{"navigatorTitle":[{"kind":"identifier","text":"userInterfaceLayoutDirection"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/userInterfaceLayoutDirection","title":"userInterfaceLayoutDirection","url":"/documentation/appkit/nsview/userinterfacelayoutdirection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userInterfaceLayoutDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSUserInterfaceLayoutDirection","text":"NSUserInterfaceLayoutDirection"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The layout direction for content in the view."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/delegate":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/delegate","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)NSStackViewDelegate","kind":"typeIdentifier","text":"NSStackViewDelegate"},{"kind":"text","text":")?"}],"title":"delegate","url":"/documentation/appkit/nsstackview/delegate","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"role":"symbol","abstract":[{"type":"text","text":"The delegate object for the stack view."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackViewDelegate":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackViewDelegate","url":"/documentation/appkit/nsstackviewdelegate","navigatorTitle":[{"text":"NSStackViewDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStackViewDelegate","kind":"identifier"}],"type":"topic","title":"NSStackViewDelegate","role":"symbol","abstract":[{"text":"A set of methods you use to respond to a stack view detaching and reattaching views.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSView":{"abstract":[{"text":"The infrastructure for drawing, printing, and handling events in an app.","type":"text"}],"url":"/documentation/appkit/nsview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","title":"NSView","navigatorTitle":[{"kind":"identifier","text":"NSView"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/removeView(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/removeView(_:)","abstract":[{"type":"text","text":"Removes a specified view from the stack view."}],"kind":"symbol","title":"removeView(_:)","type":"topic","url":"/documentation/appkit/nsstackview/removeview(_:)","navigatorTitle":[{"kind":"identifier","text":"removeView:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeView","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSView","kind":"typeIdentifier","text":"NSView"},{"kind":"text","text":")"}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","url":"/documentation/appkit/nsstackview/orientation","navigatorTitle":[{"kind":"identifier","text":"orientation"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NSUserInterfaceLayoutOrientation","kind":"typeIdentifier","text":"NSUserInterfaceLayoutOrientation"}],"kind":"symbol","type":"topic","title":"orientation","role":"symbol","abstract":[{"type":"text","text":"The horizontal or vertical layout direction of the stack view."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSStackView","kind":"identifier"}],"url":"/documentation/appkit/nsstackview","title":"NSStackView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStackView","kind":"identifier"}],"abstract":[{"text":"A view that arranges an array of views horizontally or vertically and updates their placement and sizing when the window size changes.","type":"text"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/setClippingResistancePriority(_:for:)":{"abstract":[{"text":"Sets the Auto Layout priority for resisting clipping of views in the stack view when Auto Layout attempts to reduce the stack view’s size.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/setClippingResistancePriority(_:for:)","type":"topic","role":"symbol","kind":"symbol","title":"setClippingResistancePriority(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setClippingResistancePriority"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Priority","preciseIdentifier":"c:@T@NSLayoutPriority"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Orientation","preciseIdentifier":"c:@E@NSLayoutConstraintOrientation"},{"kind":"text","text":")"}],"url":"/documentation/appkit/nsstackview/setclippingresistancepriority(_:for:)","navigatorTitle":[{"kind":"identifier","text":"setClippingResistancePriority:forOrientation:"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/setVisibilityPriority(_:for:)":{"url":"/documentation/appkit/nsstackview/setvisibilitypriority(_:for:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/setVisibilityPriority(_:for:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"setVisibilityPriority:forView:","kind":"identifier"}],"type":"topic","title":"setVisibilityPriority(_:for:)","abstract":[{"text":"Sets the Auto Layout priority for a view to remain attached to the stack view when Auto Layout reduces the stack view’s size.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setVisibilityPriority","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSStackViewVisibilityPriority","text":"VisibilityPriority","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSView","text":"NSView","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/setViews(_:in:)":{"kind":"symbol","url":"/documentation/appkit/nsstackview/setviews(_:in:)","role":"symbol","navigatorTitle":[{"text":"setViews:inGravity:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setViews","kind":"identifier"},{"kind":"text","text":"(["},{"preciseIdentifier":"c:objc(cs)NSView","kind":"typeIdentifier","text":"NSView"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"text":"NSStackView","preciseIdentifier":"c:objc(cs)NSStackView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Gravity","preciseIdentifier":"c:@E@NSStackViewGravity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/setViews(_:in:)","title":"setViews(_:in:)","abstract":[{"type":"text","text":"Specifies an array of views for a specified gravity area in the stack view, replacing any previous views in that area."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/insertView(_:at:in:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","text":"NSView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSStackViewGravity","text":"Gravity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Adds a view to a stack view gravity area at a specified index position."}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/insertView(_:at:in:)","url":"/documentation/appkit/nsstackview/insertview(_:at:in:)","title":"insertView(_:at:in:)","navigatorTitle":[{"text":"insertView:atIndex:inGravity:","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/Gravity":{"kind":"symbol","url":"/documentation/appkit/nsstackview/gravity","role":"symbol","navigatorTitle":[{"text":"Gravity","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Gravity","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Gravity","title":"NSStackView.Gravity","abstract":[{"type":"text","text":"The gravity areas available in a stack view."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"addView:inGravity:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addView:inGravity:"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/setVisibilityPriority(_:for:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","doc://com.apple.appkit/documentation/AppKit/NSStackView/setClippingResistancePriority(_:for:)"],"anchor":"Related-Documentation"},{"title":"Managing Views in Gravity Areas","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/insertView(_:at:in:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/setViews(_:in:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/removeView(_:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/Gravity"],"generated":true,"anchor":"Managing-Views-in-Gravity-Areas"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"addView:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSView","text":"NSView","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView"},{"text":" *) ","kind":"text"},{"text":"view","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"inGravity:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@NSStackViewGravity","text":"NSStackViewGravity","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Gravity"},{"text":") ","kind":"text"},{"text":"gravity","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":{"kind":"parameters","parameters":[{"name":"view","content":[{"inlineContent":[{"type":"text","text":"The view to add to the specified gravity area."}],"type":"paragraph"}]},{"name":"gravity","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The gravity area that you are adding the specified view to. Valid values are those in the "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Gravity"},{"type":"text","text":" enumeration."}]}]}]},"op":"replace","path":"/primaryContentSections/1"},{"value":"addView:inGravity:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1addView(_:in:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addView:inGravity:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1addView(_:in:)/fragments"},{"value":"userInterfaceLayoutDirection","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1userInterfaceLayoutDirection/title"},{"value":[{"kind":"identifier","text":"userInterfaceLayoutDirection"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1userInterfaceLayoutDirection/fragments"},{"value":"delegate","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1delegate/title"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1delegate/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackViewDelegate/title","value":"NSStackViewDelegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackViewDelegate/fragments","value":[{"text":"NSStackViewDelegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackViewDelegate/navigatorTitle","value":[{"text":"NSStackViewDelegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title","value":"NSView"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments","value":[{"text":"NSView","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle","value":[{"text":"NSView","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1removeView(_:)/title","value":"removeView:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1removeView(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeView:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1orientation/title","value":"orientation"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1orientation/fragments","value":[{"text":"orientation","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/title","value":"NSStackView"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/fragments","value":[{"text":"NSStackView","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/navigatorTitle","value":[{"kind":"identifier","text":"NSStackView"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1setClippingResistancePriority(_:for:)/title","value":"setClippingResistancePriority:forOrientation:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1setClippingResistancePriority(_:for:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setClippingResistancePriority:forOrientation:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1setVisibilityPriority(_:for:)/title","value":"setVisibilityPriority:forView:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1setVisibilityPriority(_:for:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setVisibilityPriority:forView:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1setViews(_:in:)/title","value":"setViews:inGravity:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1setViews(_:in:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setViews:inGravity:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1insertView(_:at:in:)/title","value":"insertView:atIndex:inGravity:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1insertView(_:at:in:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"insertView:atIndex:inGravity:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Gravity/title","value":"NSStackViewGravity"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Gravity/fragments","value":[{"kind":"identifier","text":"NSStackViewGravity"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Gravity/navigatorTitle","value":[{"kind":"identifier","text":"NSStackViewGravity"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}