{"abstract":[{"text":"The array of views arranged by the stack view.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSStackView/arrangedSubviews","interfaceLanguage":"swift"},"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/addArrangedSubview(_:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/insertArrangedSubview(_:at:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/removeArrangedSubview(_:)"],"anchor":"Managing-the-Arranged-Subviews","title":"Managing the Arranged Subviews","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstackview/arrangedsubviews"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsstackview/arrangedsubviews"]}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"arrangedSubviews","kind":"identifier"},{"text":": [","kind":"text"},{"text":"NSView","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","preciseIdentifier":"c:objc(cs)NSView"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"inlineContent":[{"text":"The stack view ensures that the contents of this array are always a subset of its ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/subviews","type":"reference"},{"text":" array.","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView"]]},"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"arrangedSubviews","kind":"identifier"}],"platforms":[{"deprecated":false,"introducedAt":"10.11","beta":false,"name":"macOS","unavailable":false}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)NSStackView(py)arrangedSubviews","title":"arrangedSubviews","modules":[{"name":"AppKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"arrangedSubviews","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSView","text":"NSView","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"references":{"doc://com.apple.appkit/documentation/AppKit/NSView":{"abstract":[{"text":"The infrastructure for drawing, printing, and handling events in an app.","type":"text"}],"url":"/documentation/appkit/nsview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","title":"NSView","navigatorTitle":[{"kind":"identifier","text":"NSView"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/arrangedSubviews":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/arrangedSubviews","title":"arrangedSubviews","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"arrangedSubviews","kind":"identifier"},{"text":": [","kind":"text"},{"text":"NSView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView"},{"text":"]","kind":"text"}],"abstract":[{"text":"The array of views arranged by the stack view.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"arrangedSubviews","kind":"identifier"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nsstackview/arrangedsubviews"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/removeArrangedSubview(_:)":{"url":"/documentation/appkit/nsstackview/removearrangedsubview(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeArrangedSubview","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView"},{"text":")","kind":"text"}],"title":"removeArrangedSubview(_:)","kind":"symbol","abstract":[{"text":"Removes the provided view from the stack’s array of arranged subviews.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/removeArrangedSubview(_:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"removeArrangedSubview:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/addArrangedSubview(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/addArrangedSubview(_:)","title":"addArrangedSubview(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addArrangedSubview","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSView","preciseIdentifier":"c:objc(cs)NSView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Adds the specified view to the end of the arranged subviews list."}],"kind":"symbol","navigatorTitle":[{"text":"addArrangedSubview:","kind":"identifier"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nsstackview/addarrangedsubview(_:)"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStackView":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSStackView","kind":"identifier"}],"url":"/documentation/appkit/nsstackview","title":"NSStackView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStackView","kind":"identifier"}],"abstract":[{"text":"A view that arranges an array of views horizontally or vertically and updates their placement and sizing when the window size changes.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/insertArrangedSubview(_:at:)":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/insertArrangedSubview(_:at:)","url":"/documentation/appkit/nsstackview/insertarrangedsubview(_:at:)","abstract":[{"type":"text","text":"Adds the provided view to the array of arranged subviews at the specified index."}],"kind":"symbol","title":"insertArrangedSubview(_:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertArrangedSubview"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","text":"NSView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"insertArrangedSubview:atIndex:"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSView/subviews":{"abstract":[{"text":"The array of views embedded in the current view.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"subviews"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/subviews","url":"/documentation/appkit/nsview/subviews","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subviews"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSView","preciseIdentifier":"c:objc(cs)NSView"},{"kind":"text","text":"]"}],"role":"symbol","title":"subviews"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"introducedAt":"10.11","unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"arrangedSubviews"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"arrangedSubviews","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView"]]}},{"path":"/topicSections","op":"add","value":null},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"anchor":"Managing-the-Arranged-Subviews","title":"Managing the Arranged Subviews","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/addArrangedSubview(_:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/insertArrangedSubview(_:at:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/removeArrangedSubview(_:)"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<__kindof NSView *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"arrangedSubviews","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title","value":"NSView","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments","value":[{"text":"NSView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle","value":[{"kind":"identifier","text":"NSView"}],"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1arrangedSubviews/title","value":"arrangedSubviews"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1arrangedSubviews/fragments","value":[{"kind":"identifier","text":"arrangedSubviews"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1removeArrangedSubview(_:)/title","value":"removeArrangedSubview:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1removeArrangedSubview(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeArrangedSubview:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1addArrangedSubview(_:)/title","value":"addArrangedSubview:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addArrangedSubview:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1addArrangedSubview(_:)/fragments","op":"replace"},{"value":"NSStackView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/title","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/fragments","op":"replace","value":[{"kind":"identifier","text":"NSStackView"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/navigatorTitle","op":"replace","value":[{"text":"NSStackView","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1insertArrangedSubview(_:at:)/title","op":"replace","value":"insertArrangedSubview:atIndex:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1insertArrangedSubview(_:at:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"insertArrangedSubview:atIndex:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1subviews/title","op":"replace","value":"subviews"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1subviews/fragments","op":"replace","value":[{"text":"subviews","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}