{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customSpacing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"after","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"view","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSView","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","preciseIdentifier":"c:objc(cs)NSView"},{"text":") -> ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"view","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view whose trailing spacing you are getting."}]}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The number of points between the trailing edge of the specified view and the one that follows it (that is, the one with the next highest index order).","type":"text"}]}]},{"kind":"content","content":[{"level":2,"anchor":"Discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"If you set custom spacing for a view using the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/setCustomSpacing(_:after:)"},{"type":"text","text":" method, it overrides the stack view’s default spacing as set in the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing"},{"type":"text","text":" property."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"A stack view retains custom spacing across layout updates. Custom spacing for a view is lost if you remove the view from the stack view or specify a new value."}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"Returns the custom spacing, in points, between a specified view in the stack view and the view that follows it."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSStackView/customSpacing(after:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstackview/customspacing(after:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsstackview/customspacing(after:)"]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/setCustomSpacing(_:after:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/visibilityPriority(for:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/setVisibilityPriority(_:for:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority","doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing"],"anchor":"Configuring-Views-in-a-Stack-View","generated":true,"title":"Configuring Views in a Stack View"}],"metadata":{"role":"symbol","roleHeading":"Instance Method","platforms":[{"name":"macOS","deprecated":false,"introducedAt":"10.9","beta":false,"unavailable":false}],"externalID":"c:objc(cs)NSStackView(im)customSpacingAfterView:","symbolKind":"method","modules":[{"name":"AppKit"}],"title":"customSpacing(after:)","navigatorTitle":[{"text":"customSpacingAfterView:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customSpacing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"after","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSView","text":"NSView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.appkit/documentation/AppKit/NSView":{"abstract":[{"text":"The infrastructure for drawing, printing, and handling events in an app.","type":"text"}],"url":"/documentation/appkit/nsview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","title":"NSView","navigatorTitle":[{"kind":"identifier","text":"NSView"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing":{"url":"/documentation/appkit/nsstackview/spacing","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing","title":"spacing","type":"topic","navigatorTitle":[{"text":"spacing","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"spacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The minimum spacing, in points, between adjacent views in the stack view."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/setCustomSpacing(_:after:)":{"role":"symbol","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/setCustomSpacing(_:after:)","type":"topic","abstract":[{"text":"Specifies the custom spacing, in points, between a specified view and the view that follows it in the stack view.","type":"text"}],"url":"/documentation/appkit/nsstackview/setcustomspacing(_:after:)","title":"setCustomSpacing(_:after:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setCustomSpacing","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"after","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSView","text":"NSView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setCustomSpacing:afterView:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/customSpacing(after:)":{"url":"/documentation/appkit/nsstackview/customspacing(after:)","abstract":[{"text":"Returns the custom spacing, in points, between a specified view in the stack view and the view that follows it.","type":"text"}],"title":"customSpacing(after:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/customSpacing(after:)","navigatorTitle":[{"text":"customSpacingAfterView:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customSpacing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"after","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSView","text":"NSView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/visibilityPriority(for:)":{"role":"symbol","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/visibilityPriority(for:)","type":"topic","abstract":[{"text":"Returns the visibility priority for a specified view in the stack view.","type":"text"}],"url":"/documentation/appkit/nsstackview/visibilitypriority(for:)","title":"visibilityPriority(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visibilityPriority","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSView","text":"NSView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSStackViewVisibilityPriority","text":"VisibilityPriority","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"visibilityPriorityForView:","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:@T@CGFloat":{"kind":"symbol","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","abstract":[{"text":"The basic type for all floating-point values.","type":"text"}],"type":"topic","title":"CGFloat","url":"/documentation/corefoundation/cgfloat"},"doc://com.apple.appkit/documentation/AppKit/NSStackView":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSStackView","kind":"identifier"}],"url":"/documentation/appkit/nsstackview","title":"NSStackView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStackView","kind":"identifier"}],"abstract":[{"text":"A view that arranges an array of views horizontally or vertically and updates their placement and sizing when the window size changes.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority":{"kind":"symbol","type":"topic","title":"NSStackView.VisibilityPriority","role":"symbol","abstract":[{"text":"The various Auto Layout priorities for a view in the stack view to remain attached.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VisibilityPriority","kind":"identifier"}],"navigatorTitle":[{"text":"VisibilityPriority","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority","url":"/documentation/appkit/nsstackview/visibilitypriority"},"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV":{"role":"symbol","type":"topic","title":"CGFloat","url":"/documentation/corefoundation/cgfloat","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","kind":"symbol","fragments":[{"text":"struct ","kind":"text"},{"text":"CGFloat","kind":"identifier"}],"abstract":[{"text":"The basic type for floating-point scalar values in Core Graphics and related frameworks.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing":{"url":"/documentation/appkit/nsstackview/usedefaultspacing","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NSStackViewSpacingUseDefault","kind":"identifier"}],"type":"topic","title":"useDefaultSpacing","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useDefaultSpacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/setVisibilityPriority(_:for:)":{"url":"/documentation/appkit/nsstackview/setvisibilitypriority(_:for:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/setVisibilityPriority(_:for:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"setVisibilityPriority:forView:","kind":"identifier"}],"type":"topic","title":"setVisibilityPriority(_:for:)","abstract":[{"text":"Sets the Auto Layout priority for a view to remain attached to the stack view when Auto Layout reduces the stack view’s size.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setVisibilityPriority","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSStackViewVisibilityPriority","text":"VisibilityPriority","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSView","text":"NSView","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"macOS","beta":false,"introducedAt":"10.9","deprecated":false,"unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"customSpacingAfterView:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"customSpacingAfterView:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/setCustomSpacing(_:after:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/visibilityPriority(for:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/setVisibilityPriority(_:for:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority","doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing"],"anchor":"Configuring-Views-in-a-Stack-View","generated":true,"title":"Configuring Views in a Stack View"}]},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"text":") ","kind":"text"},{"text":"customSpacingAfterView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSView","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","preciseIdentifier":"c:objc(cs)NSView"},{"text":" *) ","kind":"text"},{"text":"view","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view whose trailing spacing you are getting."}]}],"name":"view"}]}},{"value":{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The number of points between the trailing edge of the specified view and the one that follows it (that is, the one with the next highest index order)."}]}]},"path":"/primaryContentSections/2","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title","value":"NSView"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments","value":[{"text":"NSView","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle","value":[{"text":"NSView","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1spacing/title","value":"spacing"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1spacing/fragments","value":[{"text":"spacing","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1setCustomSpacing(_:after:)/title","value":"setCustomSpacing:afterView:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1setCustomSpacing(_:after:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setCustomSpacing:afterView:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1customSpacing(after:)/title","value":"customSpacingAfterView:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1customSpacing(after:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"customSpacingAfterView:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1visibilityPriority(for:)/title","value":"visibilityPriorityForView:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1visibilityPriority(for:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"visibilityPriorityForView:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/title","value":"NSStackView"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/fragments","value":[{"text":"NSStackView","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/navigatorTitle","value":[{"kind":"identifier","text":"NSStackView"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority/title","value":"NSStackViewVisibilityPriority"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority/fragments","value":[{"kind":"identifier","text":"NSStackViewVisibilityPriority"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority/navigatorTitle","value":[{"text":"NSStackViewVisibilityPriority","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1useDefaultSpacing/title","value":"NSStackViewSpacingUseDefault"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1useDefaultSpacing/fragments","value":[{"text":"NSStackViewSpacingUseDefault","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1setVisibilityPriority(_:for:)/title","value":"setVisibilityPriority:forView:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1setVisibilityPriority(_:for:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setVisibilityPriority:forView:","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}