{"metadata":{"externalID":"c:objc(cs)NSStackView(py)detachedViews","role":"symbol","modules":[{"name":"AppKit"}],"navigatorTitle":[{"kind":"identifier","text":"detachedViews"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"detachedViews"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","text":"NSView"},{"kind":"text","text":"]"}],"platforms":[{"beta":false,"name":"macOS","introducedAt":"10.9","unavailable":false,"deprecated":false}],"roleHeading":"Instance Property","title":"detachedViews"},"abstract":[{"text":"An array that contains the detached views from all the stack view’s gravity areas.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstackview/detachedviews"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsstackview/detachedviews"]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detachedViews"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","text":"NSView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A view in a detached state is not present in the stack view’s view hierarchy, but it still consumes memory."}]},{"name":"Note","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"There is no guaranteed ordering of the views in the detached views array."}],"type":"paragraph"}]}]}],"seeAlsoSections":[{"generated":true,"title":"Inspecting a Stack View","anchor":"Inspecting-a-Stack-View","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/views","doc://com.apple.appkit/documentation/AppKit/NSStackView/views(in:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/clippingResistancePriority(for:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/huggingPriority(for:)"]}],"kind":"symbol","identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSStackView/detachedViews","interfaceLanguage":"swift"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSStackView/views(in:)":{"abstract":[{"text":"Returns the array of views in the specified gravity area in the stack view.","type":"text"}],"title":"views(in:)","url":"/documentation/appkit/nsstackview/views(in:)","navigatorTitle":[{"kind":"identifier","text":"viewsInGravity:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"views","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSStackViewGravity","text":"Gravity"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","text":"NSView"},{"kind":"text","text":"]"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/views(in:)"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/huggingPriority(for:)":{"abstract":[{"text":"Returns the Auto Layout priority for the stack view to minimize its size to fit its contained views as closely as possible, for a specified user interface axis.","type":"text"}],"title":"huggingPriority(for:)","url":"/documentation/appkit/nsstackview/huggingpriority(for:)","navigatorTitle":[{"kind":"identifier","text":"huggingPriorityForOrientation:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"huggingPriority","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSLayoutConstraintOrientation","text":"Orientation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSLayoutPriority","text":"Priority"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/huggingPriority(for:)"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/views":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"views","kind":"identifier"},{"text":": [","kind":"text"},{"text":"NSView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView"},{"text":"]","kind":"text"}],"title":"views","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/views","abstract":[{"text":"The array of views owned by the stack view.","type":"text"}],"role":"symbol","url":"/documentation/appkit/nsstackview/views","type":"topic","kind":"symbol","navigatorTitle":[{"text":"views","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/detachedViews":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/detachedViews","abstract":[{"text":"An array that contains the detached views from all the stack view’s gravity areas.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"detachedViews"}],"url":"/documentation/appkit/nsstackview/detachedviews","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detachedViews"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSView","kind":"typeIdentifier","text":"NSView"},{"kind":"text","text":"]"}],"type":"topic","title":"detachedViews"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/clippingResistancePriority(for:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clippingResistancePriority","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSLayoutConstraintOrientation","text":"Orientation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSLayoutPriority","text":"Priority"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"clippingResistancePriorityForOrientation:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/clippingResistancePriority(for:)","url":"/documentation/appkit/nsstackview/clippingresistancepriority(for:)","abstract":[{"text":"Returns the Auto Layout priority for resisting clipping of views in the stack view when Auto Layout attempts to reduce the stack view’s size.","type":"text"}],"role":"symbol","type":"topic","title":"clippingResistancePriority(for:)"},"doc://com.apple.appkit/documentation/AppKit/NSView":{"abstract":[{"text":"The infrastructure for drawing, printing, and handling events in an app.","type":"text"}],"url":"/documentation/appkit/nsview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","title":"NSView","navigatorTitle":[{"kind":"identifier","text":"NSView"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSStackView","kind":"identifier"}],"url":"/documentation/appkit/nsstackview","title":"NSStackView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStackView","kind":"identifier"}],"abstract":[{"text":"A view that arranges an array of views horizontally or vertically and updates their placement and sizing when the window size changes.","type":"text"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"introducedAt":"10.9","deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"detachedViews","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"value":[{"text":"detachedViews","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"anchor":"Inspecting-a-Stack-View","title":"Inspecting a Stack View","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/views","doc://com.apple.appkit/documentation/AppKit/NSStackView/views(in:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/clippingResistancePriority(for:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/huggingPriority(for:)"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<__kindof NSView *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"detachedViews"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":"viewsInGravity:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1views(in:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewsInGravity:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1views(in:)/fragments"},{"op":"replace","value":"huggingPriorityForOrientation:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1huggingPriority(for:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"huggingPriorityForOrientation:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1huggingPriority(for:)/fragments"},{"op":"replace","value":"views","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1views/title"},{"op":"replace","value":[{"text":"views","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1views/fragments"},{"op":"replace","value":"detachedViews","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1detachedViews/title"},{"op":"replace","value":[{"kind":"identifier","text":"detachedViews"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1detachedViews/fragments"},{"op":"replace","value":"clippingResistancePriorityForOrientation:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1clippingResistancePriority(for:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clippingResistancePriorityForOrientation:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1clippingResistancePriority(for:)/fragments"},{"value":"NSView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments","op":"replace","value":[{"kind":"identifier","text":"NSView"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle","op":"replace","value":[{"text":"NSView","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/title","op":"replace","value":"NSStackView"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/fragments","op":"replace","value":[{"text":"NSStackView","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/navigatorTitle","op":"replace","value":[{"text":"NSStackView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}