{"sections":[],"metadata":{"title":"NSStackView.Distribution","extendedModule":"AppKit","platforms":[{"deprecated":false,"beta":false,"introducedAt":"10.11","unavailable":false,"name":"macOS"}],"externalID":"c:@E@NSStackViewDistribution","modules":[{"name":"AppKit"}],"roleHeading":"Enumeration","navigatorTitle":[{"text":"Distribution","kind":"identifier"}],"symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Distribution","kind":"identifier"}],"role":"symbol"},"kind":"symbol","seeAlsoSections":[{"title":"Configuring the Stack View Layout","anchor":"Configuring-the-Stack-View-Layout","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation","doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment","doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/edgeInsets","doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/distribution-swift.property"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/appkit/nsstackview/distribution-swift.enum"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsstackview/distribution-swift.enum"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Distribution"}]}]}],"topicSections":[{"title":"Constants","anchor":"Constants","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/equalCentering","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/equalSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fill","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fillEqually","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fillProportionally","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/gravityAreas"]},{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/init(rawValue:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView"]]},"references":{"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","url":"/documentation/appkit/nsstackview/orientation","navigatorTitle":[{"kind":"identifier","text":"orientation"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NSUserInterfaceLayoutOrientation","kind":"typeIdentifier","text":"NSUserInterfaceLayoutOrientation"}],"kind":"symbol","type":"topic","title":"orientation","role":"symbol","abstract":[{"type":"text","text":"The horizontal or vertical layout direction of the stack view."}]},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"type":"topic","title":"Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","role":"symbol","url":"/documentation/Swift/Equatable"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/equalSpacing":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSStackViewDistributionEqualSpacing"}],"url":"/documentation/appkit/nsstackview/distribution-swift.enum/equalspacing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"equalSpacing"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/equalSpacing","title":"NSStackView.Distribution.equalSpacing","abstract":[],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation":{"title":"NSUserInterfaceLayoutOrientation","navigatorTitle":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation","role":"symbol","url":"/documentation/appkit/nsuserinterfacelayoutorientation","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}],"abstract":[{"type":"text","text":"The stack view layout directions, and user interface axes for hugging priority and clipping resistance."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fillEqually":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NSStackViewDistributionFillEqually","kind":"identifier"}],"url":"/documentation/appkit/nsstackview/distribution-swift.enum/fillequally","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillEqually","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fillEqually","title":"NSStackView.Distribution.fillEqually","abstract":[],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/edgeInsets":{"url":"/documentation/appkit/nsstackview/edgeinsets","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/edgeInsets","title":"edgeInsets","type":"topic","navigatorTitle":[{"text":"edgeInsets","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"edgeInsets","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@NSEdgeInsets","text":"NSEdgeInsets","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The geometric padding, in points, inside the stack view, surrounding its views."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing":{"url":"/documentation/appkit/nsstackview/hasequalspacing","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing","title":"hasEqualSpacing","type":"topic","navigatorTitle":[{"text":"hasEqualSpacing","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasEqualSpacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the spacing between adjacent views should be equal to each other."}],"deprecated":true},"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/equalCentering":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"equalCentering"}],"abstract":[],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/equalCentering","navigatorTitle":[{"kind":"identifier","text":"NSStackViewDistributionEqualCentering"}],"title":"NSStackView.Distribution.equalCentering","url":"/documentation/appkit/nsstackview/distribution-swift.enum/equalcentering","type":"topic"},"doc://com.externally.resolved.symbol/s:SH":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"title":"Hashable"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fillProportionally":{"url":"/documentation/appkit/nsstackview/distribution-swift.enum/fillproportionally","title":"NSStackView.Distribution.fillProportionally","kind":"symbol","abstract":[],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fillProportionally","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillProportionally","kind":"identifier"}],"navigatorTitle":[{"text":"NSStackViewDistributionFillProportionally","kind":"identifier"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","role":"symbol","type":"topic","url":"/documentation/Swift/Sendable","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"title":"Sendable","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SY":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RawRepresentable","kind":"identifier"},{"text":"<","kind":"text"},{"text":"RawValue","kind":"typeIdentifier","preciseIdentifier":"s:SY8RawValueQa"},{"text":">","kind":"text"}],"url":"/documentation/Swift/RawRepresentable","title":"RawRepresentable","abstract":[{"text":"A type that can be converted to and from an associated raw value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:SY","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fill":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fill"}],"title":"NSStackView.Distribution.fill","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fill","abstract":[],"role":"symbol","url":"/documentation/appkit/nsstackview/distribution-swift.enum/fill","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSStackViewDistributionFill"}]},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"url":"/documentation/Swift/BitwiseCopyable","kind":"symbol","title":"BitwiseCopyable","identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","type":"topic","abstract":[{"text":"","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/init(rawValue:)":{"kind":"symbol","url":"/documentation/appkit/nsstackview/distribution-swift.enum/init(rawvalue:)","type":"topic","title":"init(rawValue:)","abstract":[],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/distribution-swift.property":{"role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/distribution-swift.property","navigatorTitle":[{"kind":"identifier","text":"distribution"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"distribution","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Distribution","preciseIdentifier":"c:@E@NSStackViewDistribution"}],"url":"/documentation/appkit/nsstackview/distribution-swift.property","title":"distribution","kind":"symbol","abstract":[]},"doc://com.apple.appkit/documentation/AppKit/NSStackView":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSStackView","kind":"identifier"}],"url":"/documentation/appkit/nsstackview","title":"NSStackView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStackView","kind":"identifier"}],"abstract":[{"text":"A view that arranges an array of views horizontally or vertically and updates their placement and sizing when the window size changes.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing":{"url":"/documentation/appkit/nsstackview/usedefaultspacing","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NSStackViewSpacingUseDefault","kind":"identifier"}],"type":"topic","title":"useDefaultSpacing","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useDefaultSpacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment":{"url":"/documentation/appkit/nsstackview/alignment","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment","title":"alignment","type":"topic","navigatorTitle":[{"text":"alignment","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alignment","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSLayoutAttribute","text":"Attribute","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The view alignment within the stack view."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum":{"role":"symbol","abstract":[],"title":"NSStackView.Distribution","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Distribution"}],"url":"/documentation/appkit/nsstackview/distribution-swift.enum","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Distribution"}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/gravityAreas":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"gravityAreas"}],"title":"NSStackView.Distribution.gravityAreas","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/gravityAreas","abstract":[],"role":"symbol","url":"/documentation/appkit/nsstackview/distribution-swift.enum/gravityareas","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSStackViewDistributionGravityAreas"}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing":{"url":"/documentation/appkit/nsstackview/spacing","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing","title":"spacing","type":"topic","navigatorTitle":[{"text":"spacing","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"spacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The minimum spacing, in points, between adjacent views in the stack view."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"introducedAt":"10.11","name":"macOS","unavailable":false,"deprecated":false,"beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Enumeration","path":"/metadata/roleHeading","op":"replace"},{"value":"NSStackViewDistribution","path":"/metadata/title","op":"replace"},{"value":"enum","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"NSStackViewDistribution","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSStackViewDistribution"}],"path":"/metadata/navigatorTitle","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"path":"/hierarchy","op":"replace"},{"value":[{"title":"Constants","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/equalCentering","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/equalSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fill","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fillEqually","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/fillProportionally","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum/gravityAreas"],"anchor":"Constants"}],"path":"/topicSections","op":"replace"},{"value":null,"path":"/relationshipsSections","op":"replace"},{"value":[{"generated":true,"title":"Configuring the Stack View Layout","anchor":"Configuring-the-Stack-View-Layout","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation","doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment","doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/edgeInsets","doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/distribution-swift.property"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSStackViewDistribution"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1orientation/title","op":"replace","value":"orientation"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1orientation/fragments","op":"replace","value":[{"text":"orientation","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1equalSpacing/title","op":"replace","value":"NSStackViewDistributionEqualSpacing"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1equalSpacing/fragments","op":"replace","value":[{"text":"NSStackViewDistributionEqualSpacing","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/title","op":"replace","value":"NSUserInterfaceLayoutOrientation"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/fragments","op":"replace","value":[{"text":"NSUserInterfaceLayoutOrientation","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1fillEqually/title","op":"replace","value":"NSStackViewDistributionFillEqually"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1fillEqually/fragments","op":"replace","value":[{"kind":"identifier","text":"NSStackViewDistributionFillEqually"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1edgeInsets/title","op":"replace","value":"edgeInsets"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1edgeInsets/fragments","op":"replace","value":[{"kind":"identifier","text":"edgeInsets"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1hasEqualSpacing/title","op":"replace","value":"hasEqualSpacing"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1hasEqualSpacing/fragments","op":"replace","value":[{"kind":"identifier","text":"hasEqualSpacing"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1equalCentering/title","op":"replace","value":"NSStackViewDistributionEqualCentering"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1equalCentering/fragments","op":"replace","value":[{"kind":"identifier","text":"NSStackViewDistributionEqualCentering"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1fillProportionally/title","op":"replace","value":"NSStackViewDistributionFillProportionally"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1fillProportionally/fragments","op":"replace","value":[{"text":"NSStackViewDistributionFillProportionally","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1fill/title","op":"replace","value":"NSStackViewDistributionFill"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1fill/fragments","op":"replace","value":[{"kind":"identifier","text":"NSStackViewDistributionFill"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1distribution-swift.property/title","op":"replace","value":"distribution"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1distribution-swift.property/fragments","op":"replace","value":[{"text":"distribution","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/title","op":"replace","value":"NSStackView"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/fragments","op":"replace","value":[{"kind":"identifier","text":"NSStackView"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/navigatorTitle","op":"replace","value":[{"text":"NSStackView","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1useDefaultSpacing/title","op":"replace","value":"NSStackViewSpacingUseDefault"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1useDefaultSpacing/fragments","op":"replace","value":[{"text":"NSStackViewSpacingUseDefault","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1alignment/title","op":"replace","value":"alignment"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1alignment/fragments","op":"replace","value":[{"text":"alignment","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum/title","op":"replace","value":"NSStackViewDistribution"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum/fragments","op":"replace","value":[{"kind":"identifier","text":"NSStackViewDistribution"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSStackViewDistribution"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1gravityAreas/title","op":"replace","value":"NSStackViewDistributionGravityAreas"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum~1gravityAreas/fragments","op":"replace","value":[{"kind":"identifier","text":"NSStackViewDistributionGravityAreas"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1spacing/title","op":"replace","value":"spacing"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1spacing/fragments","op":"replace","value":[{"text":"spacing","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}