{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"distribution","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSStackView","preciseIdentifier":"c:objc(cs)NSStackView","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView"},{"text":".","kind":"text"},{"text":"Distribution","preciseIdentifier":"c:@E@NSStackViewDistribution","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"]}]}],"metadata":{"modules":[{"name":"AppKit"}],"platforms":[{"deprecated":false,"beta":false,"name":"macOS","introducedAt":"10.11","unavailable":false}],"externalID":"c:objc(cs)NSStackView(py)distribution","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"distribution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSStackViewDistribution","kind":"typeIdentifier","text":"Distribution"}],"title":"distribution","navigatorTitle":[{"kind":"identifier","text":"distribution"}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSStackView/distribution-swift.property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Configuring the Stack View Layout","generated":true,"anchor":"Configuring-the-Stack-View-Layout","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation","doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment","doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/edgeInsets","doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum"]}],"variants":[{"paths":["/documentation/appkit/nsstackview/distribution-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsstackview/distribution-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView"]]},"kind":"symbol","sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","url":"/documentation/appkit/nsstackview/orientation","navigatorTitle":[{"kind":"identifier","text":"orientation"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NSUserInterfaceLayoutOrientation","kind":"typeIdentifier","text":"NSUserInterfaceLayoutOrientation"}],"kind":"symbol","type":"topic","title":"orientation","role":"symbol","abstract":[{"type":"text","text":"The horizontal or vertical layout direction of the stack view."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum":{"role":"symbol","abstract":[],"title":"NSStackView.Distribution","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Distribution"}],"url":"/documentation/appkit/nsstackview/distribution-swift.enum","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Distribution"}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing":{"url":"/documentation/appkit/nsstackview/usedefaultspacing","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NSStackViewSpacingUseDefault","kind":"identifier"}],"type":"topic","title":"useDefaultSpacing","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useDefaultSpacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation":{"title":"NSUserInterfaceLayoutOrientation","navigatorTitle":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation","role":"symbol","url":"/documentation/appkit/nsuserinterfacelayoutorientation","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}],"abstract":[{"type":"text","text":"The stack view layout directions, and user interface axes for hugging priority and clipping resistance."}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing":{"url":"/documentation/appkit/nsstackview/hasequalspacing","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing","title":"hasEqualSpacing","type":"topic","navigatorTitle":[{"text":"hasEqualSpacing","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasEqualSpacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the spacing between adjacent views should be equal to each other."}],"deprecated":true},"doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment":{"url":"/documentation/appkit/nsstackview/alignment","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment","title":"alignment","type":"topic","navigatorTitle":[{"text":"alignment","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alignment","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSLayoutAttribute","text":"Attribute","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The view alignment within the stack view."}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing":{"url":"/documentation/appkit/nsstackview/spacing","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing","title":"spacing","type":"topic","navigatorTitle":[{"text":"spacing","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"spacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The minimum spacing, in points, between adjacent views in the stack view."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/distribution-swift.property":{"role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/distribution-swift.property","navigatorTitle":[{"kind":"identifier","text":"distribution"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"distribution","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Distribution","preciseIdentifier":"c:@E@NSStackViewDistribution"}],"url":"/documentation/appkit/nsstackview/distribution-swift.property","title":"distribution","kind":"symbol","abstract":[]},"doc://com.apple.appkit/documentation/AppKit/NSStackView":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSStackView","kind":"identifier"}],"url":"/documentation/appkit/nsstackview","title":"NSStackView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStackView","kind":"identifier"}],"abstract":[{"text":"A view that arranges an array of views horizontally or vertically and updates their placement and sizing when the window size changes.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/edgeInsets":{"url":"/documentation/appkit/nsstackview/edgeinsets","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/edgeInsets","title":"edgeInsets","type":"topic","navigatorTitle":[{"text":"edgeInsets","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"edgeInsets","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@NSEdgeInsets","text":"NSEdgeInsets","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The geometric padding, in points, inside the stack view, surrounding its views."}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"introducedAt":"10.11","deprecated":false,"unavailable":false,"name":"macOS","beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"distribution"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"distribution","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"anchor":"Configuring-the-Stack-View-Layout","title":"Configuring the Stack View Layout","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation","doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment","doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/edgeInsets","doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSStackViewDistribution","text":"NSStackViewDistribution"},{"text":" ","kind":"text"},{"text":"distribution","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}]}},{"value":"orientation","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1orientation/title"},{"value":[{"text":"orientation","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1orientation/fragments"},{"value":"NSStackViewDistribution","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum/title"},{"value":[{"kind":"identifier","text":"NSStackViewDistribution"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum/fragments"},{"value":[{"kind":"identifier","text":"NSStackViewDistribution"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum/navigatorTitle"},{"value":"NSStackViewSpacingUseDefault","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1useDefaultSpacing/title"},{"value":[{"text":"NSStackViewSpacingUseDefault","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1useDefaultSpacing/fragments"},{"value":"NSUserInterfaceLayoutOrientation","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/title"},{"value":[{"text":"NSUserInterfaceLayoutOrientation","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/fragments"},{"value":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/navigatorTitle"},{"value":"hasEqualSpacing","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1hasEqualSpacing/title"},{"value":[{"text":"hasEqualSpacing","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1hasEqualSpacing/fragments"},{"value":"alignment","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1alignment/title"},{"value":[{"text":"alignment","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1alignment/fragments"},{"value":"spacing","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1spacing/title"},{"value":[{"text":"spacing","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1spacing/fragments"},{"value":"distribution","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1distribution-swift.property/title"},{"value":[{"kind":"identifier","text":"distribution"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1distribution-swift.property/fragments"},{"value":"NSStackView","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/title"},{"value":[{"kind":"identifier","text":"NSStackView"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/fragments"},{"value":[{"kind":"identifier","text":"NSStackView"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/navigatorTitle"},{"value":"edgeInsets","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1edgeInsets/title"},{"value":[{"text":"edgeInsets","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1edgeInsets/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}