{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"seeAlsoSections":[{"anchor":"Configuring-the-Stack-View-Layout","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation","doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment","doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/distribution-swift.property","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum"],"title":"Configuring the Stack View Layout","generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView"]]},"abstract":[{"text":"The geometric padding, in points, inside the stack view, surrounding its views.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstackview/edgeinsets"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsstackview/edgeinsets"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSStackView/edgeInsets"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"edgeInsets"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@NSEdgeInsets","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@S@NSEdgeInsets","text":"NSEdgeInsets"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"Discussion","text":"Discussion"},{"inlineContent":[{"text":"The default value is ","type":"text"},{"code":"(0, 0, 0, 0)","type":"codeVoice"},{"text":". Edge insets remain as they are if you change the value of a stack view’s ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","type":"reference"},{"text":" property or the value of its inherited ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/userInterfaceLayoutDirection","type":"reference"},{"text":" property.","type":"text"}],"type":"paragraph"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"edgeInsets"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@NSEdgeInsets","kind":"typeIdentifier","text":"NSEdgeInsets"}],"title":"edgeInsets","navigatorTitle":[{"kind":"identifier","text":"edgeInsets"}],"externalID":"c:objc(cs)NSStackView(py)edgeInsets","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"AppKit"}],"role":"symbol","platforms":[{"beta":false,"deprecated":false,"introducedAt":"10.9","name":"macOS","unavailable":false}]},"references":{"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum":{"role":"symbol","abstract":[],"title":"NSStackView.Distribution","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Distribution"}],"url":"/documentation/appkit/nsstackview/distribution-swift.enum","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Distribution"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/c:@S@NSEdgeInsets":{"type":"topic","kind":"symbol","role":"symbol","url":"/documentation/foundation/nsedgeinsets","abstract":[{"type":"text","text":"A description of the distance between the edges of two rectangles."}],"title":"NSEdgeInsets","identifier":"doc://com.externally.resolved.symbol/c:@S@NSEdgeInsets","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"NSEdgeInsets"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing":{"url":"/documentation/appkit/nsstackview/usedefaultspacing","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NSStackViewSpacingUseDefault","kind":"identifier"}],"type":"topic","title":"useDefaultSpacing","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useDefaultSpacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/edgeInsets":{"url":"/documentation/appkit/nsstackview/edgeinsets","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/edgeInsets","title":"edgeInsets","type":"topic","navigatorTitle":[{"text":"edgeInsets","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"edgeInsets","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@NSEdgeInsets","text":"NSEdgeInsets","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The geometric padding, in points, inside the stack view, surrounding its views."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing":{"url":"/documentation/appkit/nsstackview/spacing","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing","title":"spacing","type":"topic","navigatorTitle":[{"text":"spacing","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"spacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The minimum spacing, in points, between adjacent views in the stack view."}]},"doc://com.apple.appkit/documentation/AppKit/NSView/userInterfaceLayoutDirection":{"navigatorTitle":[{"kind":"identifier","text":"userInterfaceLayoutDirection"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView/userInterfaceLayoutDirection","title":"userInterfaceLayoutDirection","url":"/documentation/appkit/nsview/userinterfacelayoutdirection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userInterfaceLayoutDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSUserInterfaceLayoutDirection","text":"NSUserInterfaceLayoutDirection"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The layout direction for content in the view."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment":{"url":"/documentation/appkit/nsstackview/alignment","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment","title":"alignment","type":"topic","navigatorTitle":[{"text":"alignment","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alignment","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSLayoutAttribute","text":"Attribute","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The view alignment within the stack view."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSStackView","kind":"identifier"}],"url":"/documentation/appkit/nsstackview","title":"NSStackView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStackView","kind":"identifier"}],"abstract":[{"text":"A view that arranges an array of views horizontally or vertically and updates their placement and sizing when the window size changes.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing":{"url":"/documentation/appkit/nsstackview/hasequalspacing","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing","title":"hasEqualSpacing","type":"topic","navigatorTitle":[{"text":"hasEqualSpacing","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasEqualSpacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the spacing between adjacent views should be equal to each other."}],"deprecated":true},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation":{"title":"NSUserInterfaceLayoutOrientation","navigatorTitle":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation","role":"symbol","url":"/documentation/appkit/nsuserinterfacelayoutorientation","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}],"abstract":[{"type":"text","text":"The stack view layout directions, and user interface axes for hugging priority and clipping resistance."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/distribution-swift.property":{"role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/distribution-swift.property","navigatorTitle":[{"kind":"identifier","text":"distribution"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"distribution","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Distribution","preciseIdentifier":"c:@E@NSStackViewDistribution"}],"url":"/documentation/appkit/nsstackview/distribution-swift.property","title":"distribution","kind":"symbol","abstract":[]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","url":"/documentation/appkit/nsstackview/orientation","navigatorTitle":[{"kind":"identifier","text":"orientation"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NSUserInterfaceLayoutOrientation","kind":"typeIdentifier","text":"NSUserInterfaceLayoutOrientation"}],"kind":"symbol","type":"topic","title":"orientation","role":"symbol","abstract":[{"type":"text","text":"The horizontal or vertical layout direction of the stack view."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"name":"macOS","introducedAt":"10.9","beta":false,"deprecated":false,"unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"edgeInsets","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"edgeInsets"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Configuring the Stack View Layout","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation","doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment","doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/distribution-swift.property","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum"],"anchor":"Configuring-the-Stack-View-Layout","generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSEdgeInsets","identifier":"doc://com.externally.resolved.symbol/c:@S@NSEdgeInsets","preciseIdentifier":"c:@S@NSEdgeInsets","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"edgeInsets","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum/title","value":"NSStackViewDistribution"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum/fragments","value":[{"kind":"identifier","text":"NSStackViewDistribution"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum/navigatorTitle","value":[{"kind":"identifier","text":"NSStackViewDistribution"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1useDefaultSpacing/title","value":"NSStackViewSpacingUseDefault"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1useDefaultSpacing/fragments","value":[{"text":"NSStackViewSpacingUseDefault","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1edgeInsets/title","value":"edgeInsets"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1edgeInsets/fragments","value":[{"kind":"identifier","text":"edgeInsets"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1spacing/title","value":"spacing"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1spacing/fragments","value":[{"text":"spacing","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1userInterfaceLayoutDirection/title","value":"userInterfaceLayoutDirection"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1userInterfaceLayoutDirection/fragments","value":[{"kind":"identifier","text":"userInterfaceLayoutDirection"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1alignment/title","value":"alignment"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1alignment/fragments","value":[{"kind":"identifier","text":"alignment"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/title","value":"NSStackView"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/fragments","value":[{"text":"NSStackView","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/navigatorTitle","value":[{"text":"NSStackView","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1hasEqualSpacing/title","value":"hasEqualSpacing"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1hasEqualSpacing/fragments","value":[{"text":"hasEqualSpacing","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/title","value":"NSUserInterfaceLayoutOrientation"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/fragments","value":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/navigatorTitle","value":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1distribution-swift.property/title","value":"distribution"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1distribution-swift.property/fragments","value":[{"kind":"identifier","text":"distribution"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1orientation/title","value":"orientation"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1orientation/fragments","value":[{"text":"orientation","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}