{"metadata":{"title":"orientation","symbolKind":"property","externalID":"c:objc(cs)NSStackView(py)orientation","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"orientation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSUserInterfaceLayoutOrientation","preciseIdentifier":"c:@E@NSUserInterfaceLayoutOrientation","kind":"typeIdentifier"}],"platforms":[{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"10.9","name":"macOS"}],"modules":[{"name":"AppKit"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"orientation","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation"},"abstract":[{"type":"text","text":"The horizontal or vertical layout direction of the stack view."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstackview/orientation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsstackview/orientation"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation","kind":"typeIdentifier","text":"NSUserInterfaceLayoutOrientation","preciseIdentifier":"c:@E@NSUserInterfaceLayoutOrientation"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"inlineContent":[{"text":"Default value is ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/horizontal","isActive":true,"type":"reference"},{"text":". For values that apply to this property, see ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"seeAlsoSections":[{"title":"Configuring the Stack View Layout","anchor":"Configuring-the-Stack-View-Layout","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation","doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment","doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/edgeInsets","doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/distribution-swift.property","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum"],"generated":true}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/horizontal":{"abstract":[{"text":"The horizontal orientation.","type":"text"}],"title":"NSUserInterfaceLayoutOrientation.horizontal","type":"topic","url":"/documentation/appkit/nsuserinterfacelayoutorientation/horizontal","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientationHorizontal"}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/horizontal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontal"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation":{"title":"NSUserInterfaceLayoutOrientation","navigatorTitle":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation","role":"symbol","url":"/documentation/appkit/nsuserinterfacelayoutorientation","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}],"abstract":[{"type":"text","text":"The stack view layout directions, and user interface axes for hugging priority and clipping resistance."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSStackView","kind":"identifier"}],"url":"/documentation/appkit/nsstackview","title":"NSStackView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStackView","kind":"identifier"}],"abstract":[{"text":"A view that arranges an array of views horizontally or vertically and updates their placement and sizing when the window size changes.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing":{"url":"/documentation/appkit/nsstackview/hasequalspacing","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing","title":"hasEqualSpacing","type":"topic","navigatorTitle":[{"text":"hasEqualSpacing","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasEqualSpacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the spacing between adjacent views should be equal to each other."}],"deprecated":true},"doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing":{"url":"/documentation/appkit/nsstackview/usedefaultspacing","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NSStackViewSpacingUseDefault","kind":"identifier"}],"type":"topic","title":"useDefaultSpacing","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useDefaultSpacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum":{"role":"symbol","abstract":[],"title":"NSStackView.Distribution","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Distribution"}],"url":"/documentation/appkit/nsstackview/distribution-swift.enum","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Distribution"}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment":{"url":"/documentation/appkit/nsstackview/alignment","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment","title":"alignment","type":"topic","navigatorTitle":[{"text":"alignment","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alignment","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSLayoutAttribute","text":"Attribute","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The view alignment within the stack view."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","url":"/documentation/appkit/nsstackview/orientation","navigatorTitle":[{"kind":"identifier","text":"orientation"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NSUserInterfaceLayoutOrientation","kind":"typeIdentifier","text":"NSUserInterfaceLayoutOrientation"}],"kind":"symbol","type":"topic","title":"orientation","role":"symbol","abstract":[{"type":"text","text":"The horizontal or vertical layout direction of the stack view."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/edgeInsets":{"url":"/documentation/appkit/nsstackview/edgeinsets","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/edgeInsets","title":"edgeInsets","type":"topic","navigatorTitle":[{"text":"edgeInsets","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"edgeInsets","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@NSEdgeInsets","text":"NSEdgeInsets","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The geometric padding, in points, inside the stack view, surrounding its views."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing":{"url":"/documentation/appkit/nsstackview/spacing","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing","title":"spacing","type":"topic","navigatorTitle":[{"text":"spacing","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"spacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The minimum spacing, in points, between adjacent views in the stack view."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/distribution-swift.property":{"role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/distribution-swift.property","navigatorTitle":[{"kind":"identifier","text":"distribution"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"distribution","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Distribution","preciseIdentifier":"c:@E@NSStackViewDistribution"}],"url":"/documentation/appkit/nsstackview/distribution-swift.property","title":"distribution","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"introducedAt":"10.9","unavailable":false,"name":"macOS","beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"path":"/metadata/title","op":"replace","value":"orientation"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"orientation","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Configuring the Stack View Layout","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation","doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment","doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/edgeInsets","doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/distribution-swift.property","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum"],"anchor":"Configuring-the-Stack-View-Layout"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSUserInterfaceLayoutOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSUserInterfaceLayoutOrientation","identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"]}]}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation~1horizontal/title","op":"replace","value":"NSUserInterfaceLayoutOrientationHorizontal"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation~1horizontal/fragments","op":"replace","value":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientationHorizontal"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/title","op":"replace","value":"NSUserInterfaceLayoutOrientation"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/fragments","value":[{"text":"NSUserInterfaceLayoutOrientation","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/navigatorTitle","value":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/title","value":"NSStackView"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/fragments","value":[{"text":"NSStackView","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/navigatorTitle","value":[{"kind":"identifier","text":"NSStackView"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1hasEqualSpacing/title","value":"hasEqualSpacing"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1hasEqualSpacing/fragments","value":[{"text":"hasEqualSpacing","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1useDefaultSpacing/title","value":"NSStackViewSpacingUseDefault"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1useDefaultSpacing/fragments","value":[{"text":"NSStackViewSpacingUseDefault","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum/title","value":"NSStackViewDistribution"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum/fragments","value":[{"kind":"identifier","text":"NSStackViewDistribution"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum/navigatorTitle","value":[{"text":"NSStackViewDistribution","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1alignment/title","value":"alignment"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1alignment/fragments","value":[{"text":"alignment","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1orientation/title","value":"orientation"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1orientation/fragments","value":[{"kind":"identifier","text":"orientation"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1edgeInsets/title","value":"edgeInsets"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1edgeInsets/fragments","value":[{"text":"edgeInsets","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1spacing/title","value":"spacing"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1spacing/fragments","value":[{"kind":"identifier","text":"spacing"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1distribution-swift.property/title","value":"distribution"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1distribution-swift.property/fragments","value":[{"kind":"identifier","text":"distribution"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}