{
  "abstract": [
    {
      "text": "Sets the Auto Layout priority for resisting clipping of views in the stack view when Auto Layout attempts to reduce the stack view’s size.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSStackView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSStackView/setClippingResistancePriority(_:for:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSStackView(im)setClippingResistancePriority:forOrientation:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setClippingResistancePriority"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
        "text": "NSLayoutConstraint"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSLayoutPriority",
        "text": "Priority"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
        "text": "NSLayoutConstraint"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSLayoutConstraintOrientation",
        "text": "Orientation"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setClippingResistancePriority:forOrientation:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setClippingResistancePriority(_:for:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setClippingResistancePriority"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "clippingResistancePriority"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
              "text": "NSLayoutConstraint"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSLayoutPriority",
              "text": "Priority"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "orientation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
              "text": "NSLayoutConstraint"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Orientation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSLayoutConstraintOrientation",
              "text": "Orientation"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The clipping resistance Auto Layout priority you want to apply to the stack view for a given user interface axis. The default value is NSLayoutPriorityRequired, which disallows clipping. Other valid values are those in the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " enumeration.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "clippingResistancePriority"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The horizontal or vertical user interface axis that the clipping resistance priority applies to; one of the constants from the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " enumeration.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "orientation"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A clipped view is one that is partially hidden beyond the border of its enclosing stack view. When Auto Layout attempts to reduce the stack view’s size (such as when a user attempts to reduce the size of the enclosing window), causing a view to no longer fit, the stack view clips or detaches the view, or else prevents further reduction of the stack view’s size.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To allow view clipping, set a clipping resistance lower than the default value of NSLayoutPriorityRequired and set the visibility priority of all the stack view’s views to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/mustHold",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To ensure that views detach rather than clip, lower the clipping resistance for the stack view to a value less than the default of NSLayoutPriorityRequired and set the visibility priority for at least one view to a value less than ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/mustHold",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you disallow view clipping and disallow view detachment, which is the default behavior for a stack view, Auto Layout prevents the stack view from being reduced in size beyond the minimum needed to show all of its views.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Clipping begins from the right and bottom sides of a stack view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint": {
      "abstract": [
        {
          "text": "The relationship between two user interface objects that must be satisfied by the constraint-based layout system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutConstraint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutConstraint"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Orientation": {
      "abstract": [
        {
          "text": "The layout constraint orientation, either horizontal or vertical, that the constraint uses to enforce layout between objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Orientation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Orientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Orientation"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Orientation",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/orientation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct": {
      "abstract": [
        {
          "text": "Layout priority used to indicate the relative importance of constraints, allowing Auto Layout to make appropriate tradeoffs when satisfying the constraints of the system as a whole.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Priority"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Priority"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Priority",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint/priority-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStackView": {
      "abstract": [
        {
          "text": "A view that arranges an array of views horizontally or vertically and updates their placement and sizing when the window size changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStackView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStackView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStackView"
        }
      ],
      "role": "symbol",
      "title": "NSStackView",
      "type": "topic",
      "url": "/documentation/appkit/nsstackview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/mustHold": {
      "abstract": [
        {
          "text": "The default value, and maximum Auto Layout priority, that results in a view never detaching from the stack view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mustHold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSStackView",
          "text": "NSStackView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSStackViewVisibilityPriority",
          "text": "VisibilityPriority"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStackView/VisibilityPriority/mustHold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStackViewVisibilityPriorityMustHold"
        }
      ],
      "role": "symbol",
      "title": "mustHold",
      "type": "topic",
      "url": "/documentation/appkit/nsstackview/visibilitypriority/musthold"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStackView/clippingResistancePriority(for:)": {
      "abstract": [
        {
          "text": "Returns the Auto Layout priority for resisting clipping of views in the stack view when Auto Layout attempts to reduce the stack view’s size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clippingResistancePriority"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutConstraintOrientation",
          "text": "Orientation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSLayoutPriority",
          "text": "Priority"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStackView/clippingResistancePriority(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clippingResistancePriorityForOrientation:"
        }
      ],
      "role": "symbol",
      "title": "clippingResistancePriority(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsstackview/clippingresistancepriority(for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStackView/detachesHiddenViews": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the stack view removes hidden views from its view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detachesHiddenViews"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStackView/detachesHiddenViews",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "detachesHiddenViews"
        }
      ],
      "role": "symbol",
      "title": "detachesHiddenViews",
      "type": "topic",
      "url": "/documentation/appkit/nsstackview/detacheshiddenviews"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation": {
      "abstract": [
        {
          "text": "The horizontal or vertical layout direction of the stack view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUserInterfaceLayoutOrientation",
          "text": "NSUserInterfaceLayoutOrientation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "orientation"
        }
      ],
      "role": "symbol",
      "title": "orientation",
      "type": "topic",
      "url": "/documentation/appkit/nsstackview/orientation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStackView/setClippingResistancePriority(_:for:)": {
      "abstract": [
        {
          "text": "Sets the Auto Layout priority for resisting clipping of views in the stack view when Auto Layout attempts to reduce the stack view’s size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setClippingResistancePriority"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSLayoutPriority",
          "text": "Priority"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutConstraintOrientation",
          "text": "Orientation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStackView/setClippingResistancePriority(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setClippingResistancePriority:forOrientation:"
        }
      ],
      "role": "symbol",
      "title": "setClippingResistancePriority(_:for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsstackview/setclippingresistancepriority(_:for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStackView/setHuggingPriority(_:for:)": {
      "abstract": [
        {
          "text": "Sets the Auto Layout priority for the stack view to minimize its size, for a specified user interface axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setHuggingPriority"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSLayoutPriority",
          "text": "Priority"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutConstraintOrientation",
          "text": "Orientation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStackView/setHuggingPriority(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setHuggingPriority:forOrientation:"
        }
      ],
      "role": "symbol",
      "title": "setHuggingPriority(_:for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsstackview/sethuggingpriority(_:for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStackView/setVisibilityPriority(_:for:)": {
      "abstract": [
        {
          "text": "Sets the Auto Layout priority for a view to remain attached to the stack view when Auto Layout reduces the stack view’s size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setVisibilityPriority"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSStackView",
          "text": "NSStackView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSStackViewVisibilityPriority",
          "text": "VisibilityPriority"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStackView/setVisibilityPriority(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setVisibilityPriority:forView:"
        }
      ],
      "role": "symbol",
      "title": "setVisibilityPriority(_:for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsstackview/setvisibilitypriority(_:for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation": {
      "abstract": [
        {
          "text": "The stack view layout directions, and user interface axes for hugging priority and clipping resistance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceLayoutOrientation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserInterfaceLayoutOrientation"
        }
      ],
      "role": "symbol",
      "title": "NSUserInterfaceLayoutOrientation",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfacelayoutorientation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSStackView/setVisibilityPriority(_:for:)",
        "doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation",
        "doc://com.apple.appkit/documentation/AppKit/NSStackView/clippingResistancePriority(for:)"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Configuring-Dynamic-Behavior-for-a-Stack-View",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSStackView/detachesHiddenViews",
        "doc://com.apple.appkit/documentation/AppKit/NSStackView/setHuggingPriority(_:for:)"
      ],
      "title": "Configuring Dynamic Behavior for a Stack View"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setClippingResistancePriority:forOrientation:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setClippingResistancePriority:forOrientation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSStackView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSStackView/setVisibilityPriority(_:for:)",
                "doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation",
                "doc://com.apple.appkit/documentation/AppKit/NSStackView/clippingResistancePriority(for:)"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Configuring-Dynamic-Behavior-for-a-Stack-View",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSStackView/detachesHiddenViews",
                "doc://com.apple.appkit/documentation/AppKit/NSStackView/setHuggingPriority(_:for:)"
              ],
              "title": "Configuring Dynamic Behavior for a Stack View"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setClippingResistancePriority:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSLayoutPriority",
                    "text": "NSLayoutPriority"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "clippingResistancePriority"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "forOrientation:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Orientation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSLayoutConstraintOrientation",
                    "text": "NSLayoutConstraintOrientation"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "orientation"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The clipping resistance Auto Layout priority you want to apply to the stack view for a given user interface axis. The default value is NSLayoutPriorityRequired, which disallows clipping. Other valid values are those in the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint/Priority-swift.struct",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " enumeration.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "clippingResistancePriority"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The horizontal or vertical user interface axis that the clipping resistance priority applies to; one of the constants from the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " enumeration.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "orientation"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/title",
          "value": "NSUserInterfaceLayoutOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceLayoutOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceLayoutOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1setHuggingPriority(_:for:)/title",
          "value": "setHuggingPriority:forOrientation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1setHuggingPriority(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setHuggingPriority:forOrientation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct/title",
          "value": "NSLayoutPriority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Priority-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Orientation/title",
          "value": "NSLayoutConstraintOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Orientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutConstraintOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint~1Orientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutConstraintOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/title",
          "value": "NSStackView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStackView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStackView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1mustHold/title",
          "value": "NSStackViewVisibilityPriorityMustHold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1VisibilityPriority~1mustHold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStackViewVisibilityPriorityMustHold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1setClippingResistancePriority(_:for:)/title",
          "value": "setClippingResistancePriority:forOrientation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1setClippingResistancePriority(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setClippingResistancePriority:forOrientation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint/title",
          "value": "NSLayoutConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1detachesHiddenViews/title",
          "value": "detachesHiddenViews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1detachesHiddenViews/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "detachesHiddenViews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1orientation/title",
          "value": "orientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1orientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "orientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1clippingResistancePriority(for:)/title",
          "value": "clippingResistancePriorityForOrientation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1clippingResistancePriority(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "clippingResistancePriorityForOrientation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1setVisibilityPriority(_:for:)/title",
          "value": "setVisibilityPriority:forView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1setVisibilityPriority(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setVisibilityPriority:forView:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsstackview/setclippingresistancepriority(_:for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsstackview/setclippingresistancepriority(_:for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
