{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSStackView/views(in:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"externalID":"c:objc(cs)NSStackView(im)viewsInGravity:","title":"views(in:)","extendedModule":"AppKit","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"views","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSStackView","preciseIdentifier":"c:objc(cs)NSStackView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Gravity","preciseIdentifier":"c:@E@NSStackViewGravity"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"NSView","preciseIdentifier":"c:objc(cs)NSView"},{"kind":"text","text":"]"}],"modules":[{"name":"AppKit"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"viewsInGravity:"}],"role":"symbol","platforms":[{"beta":false,"unavailable":false,"name":"macOS","deprecated":false}]},"kind":"symbol","abstract":[{"type":"text","text":"Returns the array of views in the specified gravity area in the stack view."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstackview/views(in:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsstackview/views(in:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"views","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"gravity","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSStackView","preciseIdentifier":"c:objc(cs)NSStackView","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView"},{"text":".","kind":"text"},{"text":"Gravity","preciseIdentifier":"c:@E@NSStackViewGravity","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Gravity"},{"text":") -> [","kind":"text"},{"text":"NSView","preciseIdentifier":"c:objc(cs)NSView","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSView"},{"text":"]","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The gravity area whose view array you want to get. Valid values are those in the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Gravity","type":"reference"},{"text":" enumeration, according to the stack view’s layout direction..","type":"text"}],"type":"paragraph"}],"name":"gravity"}],"kind":"parameters"},{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The array of views in a specified gravity area."}],"type":"paragraph"}],"kind":"content"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"Discussion"},{"inlineContent":[{"text":"The returned array contains all of the views in the specified gravity area of the stack view, regardless of whether they are attached. The index position of each view in the array matches the view ordering within the gravity area. A detached view’s index position is its gravity area position when attached.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/views","doc://com.apple.appkit/documentation/AppKit/NSStackView/detachedViews","doc://com.apple.appkit/documentation/AppKit/NSStackView/clippingResistancePriority(for:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/huggingPriority(for:)"],"anchor":"Inspecting-a-Stack-View","title":"Inspecting a Stack View"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSStackView":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSStackView","kind":"identifier"}],"url":"/documentation/appkit/nsstackview","title":"NSStackView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStackView","kind":"identifier"}],"abstract":[{"text":"A view that arranges an array of views horizontally or vertically and updates their placement and sizing when the window size changes.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/views(in:)":{"abstract":[{"text":"Returns the array of views in the specified gravity area in the stack view.","type":"text"}],"title":"views(in:)","url":"/documentation/appkit/nsstackview/views(in:)","navigatorTitle":[{"kind":"identifier","text":"viewsInGravity:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"views","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSStackViewGravity","text":"Gravity"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","text":"NSView"},{"kind":"text","text":"]"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/views(in:)"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/Gravity":{"kind":"symbol","url":"/documentation/appkit/nsstackview/gravity","role":"symbol","navigatorTitle":[{"text":"Gravity","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Gravity","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Gravity","title":"NSStackView.Gravity","abstract":[{"type":"text","text":"The gravity areas available in a stack view."}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSView":{"abstract":[{"text":"The infrastructure for drawing, printing, and handling events in an app.","type":"text"}],"url":"/documentation/appkit/nsview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","title":"NSView","navigatorTitle":[{"kind":"identifier","text":"NSView"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/views":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"views","kind":"identifier"},{"text":": [","kind":"text"},{"text":"NSView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView"},{"text":"]","kind":"text"}],"title":"views","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/views","abstract":[{"text":"The array of views owned by the stack view.","type":"text"}],"role":"symbol","url":"/documentation/appkit/nsstackview/views","type":"topic","kind":"symbol","navigatorTitle":[{"text":"views","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/detachedViews":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/detachedViews","abstract":[{"text":"An array that contains the detached views from all the stack view’s gravity areas.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"detachedViews"}],"url":"/documentation/appkit/nsstackview/detachedviews","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detachedViews"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSView","kind":"typeIdentifier","text":"NSView"},{"kind":"text","text":"]"}],"type":"topic","title":"detachedViews"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/clippingResistancePriority(for:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clippingResistancePriority","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSLayoutConstraintOrientation","text":"Orientation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSLayoutPriority","text":"Priority"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"clippingResistancePriorityForOrientation:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/clippingResistancePriority(for:)","url":"/documentation/appkit/nsstackview/clippingresistancepriority(for:)","abstract":[{"text":"Returns the Auto Layout priority for resisting clipping of views in the stack view when Auto Layout attempts to reduce the stack view’s size.","type":"text"}],"role":"symbol","type":"topic","title":"clippingResistancePriority(for:)"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/huggingPriority(for:)":{"abstract":[{"text":"Returns the Auto Layout priority for the stack view to minimize its size to fit its contained views as closely as possible, for a specified user interface axis.","type":"text"}],"title":"huggingPriority(for:)","url":"/documentation/appkit/nsstackview/huggingpriority(for:)","navigatorTitle":[{"kind":"identifier","text":"huggingPriorityForOrientation:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"huggingPriority","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSLayoutConstraintOrientation","text":"Orientation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSLayoutPriority","text":"Priority"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/huggingPriority(for:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"viewsInGravity:","path":"/metadata/title"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewsInGravity:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStackView"]]}},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Inspecting-a-Stack-View","title":"Inspecting a Stack View","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/views","doc://com.apple.appkit/documentation/AppKit/NSStackView/detachedViews","doc://com.apple.appkit/documentation/AppKit/NSStackView/clippingResistancePriority(for:)","doc://com.apple.appkit/documentation/AppKit/NSStackView/huggingPriority(for:)"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<__kindof NSView *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"viewsInGravity:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@NSStackViewGravity","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Gravity","text":"NSStackViewGravity","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"gravity","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]},"op":"replace"},{"op":"replace","path":"/primaryContentSections/1","value":{"parameters":[{"name":"gravity","content":[{"type":"paragraph","inlineContent":[{"text":"The gravity area whose view array you want to get. Valid values are those in the ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Gravity","type":"reference","isActive":true},{"type":"text","text":" enumeration, according to the stack view’s layout direction.."}]}]}],"kind":"parameters"}},{"path":"/primaryContentSections/2","value":{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"text":"The array of views in a specified gravity area.","type":"text"}],"type":"paragraph"}],"kind":"content"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/title","op":"replace","value":"NSStackView"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/fragments","op":"replace","value":[{"text":"NSStackView","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView/navigatorTitle","op":"replace","value":[{"text":"NSStackView","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1views(in:)/title","op":"replace","value":"viewsInGravity:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1views(in:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewsInGravity:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Gravity/title","op":"replace","value":"NSStackViewGravity"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Gravity/fragments","op":"replace","value":[{"text":"NSStackViewGravity","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Gravity/navigatorTitle","op":"replace","value":[{"text":"NSStackViewGravity","kind":"identifier"}]},{"value":"NSView","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title"},{"value":[{"text":"NSView","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSView"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle"},{"op":"replace","value":"views","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1views/title"},{"op":"replace","value":[{"kind":"identifier","text":"views"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1views/fragments"},{"op":"replace","value":"detachedViews","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1detachedViews/title"},{"op":"replace","value":[{"kind":"identifier","text":"detachedViews"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1detachedViews/fragments"},{"op":"replace","value":"clippingResistancePriorityForOrientation:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1clippingResistancePriority(for:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clippingResistancePriorityForOrientation:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1clippingResistancePriority(for:)/fragments"},{"op":"replace","value":"huggingPriorityForOrientation:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1huggingPriority(for:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"huggingPriorityForOrientation:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1huggingPriority(for:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}