{
  "abstract": [
    {
      "text": "Displays a badge that uses an Apple Pay Later icon.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Apple Pay Later is deprecated.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKPayLaterDisplayStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPayLaterDisplayStyle/badge"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKPayLaterDisplayStyle@PKPayLaterDisplayStyleBadge",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "badge"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKPayLaterDisplayStyleBadge"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PKPayLaterDisplayStyle.badge"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "badge"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPayLaterDisplayStyle": {
      "abstract": [
        {
          "text": "Values you use to style an Apple Pay Later visual merchandising widget.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPayLaterDisplayStyle"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPayLaterDisplayStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPayLaterDisplayStyle"
        }
      ],
      "role": "symbol",
      "title": "PKPayLaterDisplayStyle",
      "type": "topic",
      "url": "/documentation/passkit/pkpaylaterdisplaystyle"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPayLaterDisplayStyle/badge": {
      "abstract": [
        {
          "text": "Displays a badge that uses an Apple Pay Later icon.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badge"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPayLaterDisplayStyle/badge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPayLaterDisplayStyleBadge"
        }
      ],
      "role": "symbol",
      "title": "PKPayLaterDisplayStyle.badge",
      "type": "topic",
      "url": "/documentation/passkit/pkpaylaterdisplaystyle/badge"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPayLaterDisplayStyle/checkout": {
      "abstract": [
        {
          "text": "A style used inside of a checkout view that presents Apple Pay and other payment options to the customer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "checkout"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPayLaterDisplayStyle/checkout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPayLaterDisplayStyleCheckout"
        }
      ],
      "role": "symbol",
      "title": "PKPayLaterDisplayStyle.checkout",
      "type": "topic",
      "url": "/documentation/passkit/pkpaylaterdisplaystyle/checkout"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPayLaterDisplayStyle/price": {
      "abstract": [
        {
          "text": "A style that shows the Apple Pay Later view beneath a product’s price.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "price"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPayLaterDisplayStyle/price",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPayLaterDisplayStylePrice"
        }
      ],
      "role": "symbol",
      "title": "PKPayLaterDisplayStyle.price",
      "type": "topic",
      "url": "/documentation/passkit/pkpaylaterdisplaystyle/price"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPayLaterDisplayStyle/standard": {
      "abstract": [
        {
          "text": "The standard Apple Pay Later visual merchandising widget style.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "standard"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPayLaterDisplayStyle/standard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPayLaterDisplayStyleStandard"
        }
      ],
      "role": "symbol",
      "title": "PKPayLaterDisplayStyle.standard",
      "type": "topic",
      "url": "/documentation/passkit/pkpaylaterdisplaystyle/standard"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Payment-view-display-styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPayLaterDisplayStyle/standard",
        "doc://com.apple.passkit/documentation/PassKit/PKPayLaterDisplayStyle/checkout",
        "doc://com.apple.passkit/documentation/PassKit/PKPayLaterDisplayStyle/price"
      ],
      "title": "Payment view display styles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKPayLaterDisplayStyleBadge"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPayLaterDisplayStyleBadge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKPayLaterDisplayStyle"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Payment-view-display-styles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPayLaterDisplayStyle/standard",
                "doc://com.apple.passkit/documentation/PassKit/PKPayLaterDisplayStyle/checkout",
                "doc://com.apple.passkit/documentation/PassKit/PKPayLaterDisplayStyle/price"
              ],
              "title": "Payment view display styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PKPayLaterDisplayStyleBadge"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Apple Pay Later is deprecated.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPayLaterDisplayStyle/title",
          "value": "PKPayLaterDisplayStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPayLaterDisplayStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPayLaterDisplayStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPayLaterDisplayStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPayLaterDisplayStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPayLaterDisplayStyle~1checkout/title",
          "value": "PKPayLaterDisplayStyleCheckout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPayLaterDisplayStyle~1checkout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPayLaterDisplayStyleCheckout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPayLaterDisplayStyle~1price/title",
          "value": "PKPayLaterDisplayStylePrice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPayLaterDisplayStyle~1price/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPayLaterDisplayStylePrice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPayLaterDisplayStyle~1standard/title",
          "value": "PKPayLaterDisplayStyleStandard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPayLaterDisplayStyle~1standard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPayLaterDisplayStyleStandard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPayLaterDisplayStyle~1badge/title",
          "value": "PKPayLaterDisplayStyleBadge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPayLaterDisplayStyle~1badge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPayLaterDisplayStyleBadge"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpaylaterdisplaystyle/badge"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpaylaterdisplaystyle/badge"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
