{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/SendChangesOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/SendChangesOptions/init(scope:operationGroup:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:8CloudKit12CKSyncEngineC18SendChangesOptionsV5scope14operationGroupA2E5ScopeO_So011CKOperationJ0CSgtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "scope"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
        "text": "CKSyncEngine"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:8CloudKit12CKSyncEngineC18SendChangesOptionsV",
        "text": "SendChangesOptions"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:8CloudKit12CKSyncEngineC18SendChangesOptionsV5ScopeO",
        "text": "Scope"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "operationGroup"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CKOperationGroup",
        "text": "CKOperationGroup"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(scope:operationGroup:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "scope"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
              "text": "CKSyncEngine"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/SendChangesOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:8CloudKit12CKSyncEngineC18SendChangesOptionsV",
              "text": "SendChangesOptions"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/SendChangesOptions/Scope-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:8CloudKit12CKSyncEngineC18SendChangesOptionsV5ScopeO",
              "text": "Scope"
            },
            {
              "kind": "text",
              "text": " = .all, "
            },
            {
              "kind": "externalParam",
              "text": "operationGroup"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKOperationGroup",
              "text": "CKOperationGroup"
            },
            {
              "kind": "text",
              "text": "? = nil)"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup": {
      "abstract": [
        {
          "text": "An explicit association between two or more operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKOperationGroup"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperationGroup"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5": {
      "abstract": [
        {
          "text": "An object that manages the synchronization of local and remote record data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKSyncEngine"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSyncEngine"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/SendChangesOptions": {
      "abstract": [
        {
          "text": "A set of options to use with a send operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SendChangesOptions"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/SendChangesOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SendChangesOptions"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine.SendChangesOptions",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/sendchangesoptions"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/SendChangesOptions/Scope-swift.enum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Scope"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/SendChangesOptions/Scope-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Scope"
        }
      ],
      "role": "symbol",
      "title": "CKSyncEngine.SendChangesOptions.Scope",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/sendchangesoptions/scope-swift.enum"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/SendChangesOptions/init(scope:operationGroup:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "scope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC",
          "text": "CKSyncEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC18SendChangesOptionsV",
          "text": "SendChangesOptions"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CloudKit12CKSyncEngineC18SendChangesOptionsV5ScopeO",
          "text": "Scope"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "operationGroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKOperationGroup",
          "text": "CKOperationGroup"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSyncEngine-5sie5/SendChangesOptions/init(scope:operationGroup:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(scope:operationGroup:)",
      "type": "topic",
      "url": "/documentation/cloudkit/cksyncengine-5sie5/sendchangesoptions/init(scope:operationgroup:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup/title",
          "value": "CKOperationGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroup"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/cksyncengine-5sie5/sendchangesoptions/init(scope:operationgroup:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
